msg_0:
[color(yellow)]Loki[color(white)]
[tab]Hmmm...
[tab]Impossible for such a loser like you
[tab]to be my son... Oh heavens...
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahwooo...!
[tab]You, Father.
[tab]Me, You, long time no look!
[wait][clear][end]

msg_2:
[color(yellow)]Loki[color(white)]
[tab]Hmmm...
[tab]And, retarded as well...
[wait][clear][end]

msg_3:
[color(yellow)]Loki[color(white)]
[tab]Whatever... Just give me a hand!
[wait][clear][end]

msg_4:
[color(yellow)]Loki[color(white)]
[tab]Whatever... Just give me your card!
[wait][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahwooo...!
[tab]OKAY, Me give hand.
[tab]Me good boy, Praise Me.
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahwooo...!
[tab]OKAY, Me give card.
[tab]Me good boy, Praise Me.
[wait][clear][end]

msg_7:
[color(yellow)]Loki[color(white)]
[tab]Ahhh... OKAY, OKAY...
[tab]You're a good boy...
[wait][clear][end]

msg_8:
[tab]By way, You want, human?
[choice(2)]Pact
Card
[end_choice][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Mmmm...
[tab]Okay, human [color(green)]Pact[color(white)] with me.
[tab]From next time, count on.
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Mmmm...
[tab]Human many pacts, Me impossible.
[wait][clear][end]

msg_11:
[tab]Which [color(green)]Pact break[color(white)]?
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_12:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Grrr...
[tab]Me feel bad, no can be help.
[tab]Instead, I [color(green)]recover[color(white)] you.
[wait][clear][end]

msg_13:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahwooo...! Me good boy.
[tab]Me give [color(green)][var(msg_var_5)] [var(msg_var_4)][color(white)].
[tab]Take care it.
[wait][clear][end]

msg_14:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Mmmm...
[tab]Human too many cards.
[tab]Me, too bad.
[wait][clear][end]

msg_15:
[color(green)]Selection ERROR[color(white)]
[end]