msg_0:
[color(yellow)]Odin[color(white)]
[tab]My loyal servant, [var(msg_var_0)].
[tab]It has been a while.
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's been a long time, sir...
[tab]However, Master Odin, why is it
[tab]that you are helping humans...?
[wait][clear][end]

msg_2:
[color(yellow)]Odin[color(white)]
[tab]It is the day of the prediction,
[tab]our hope for the future... 
[tab]Thus, can you not help these humans?
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]If it is commanded by Master Odin,
[tab]I shall gladly oblige.
[wait][clear][end]

msg_4:
[tab]What is it that you wish me to do?
[choice(2)]Want a pact.
Want a card.
[end_choice][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Very well...
[tab]In that case, I shall present you
[tab]with my card.
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Then it seems [color(green)]pact is approved[color(white)].
[tab]I look forward to our next meeting.
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]My, you have many pacts.
[tab]I cannot make one like this.
[wait][clear][end]

msg_8:
[tab]Another pact must be [color(green)]canceled[color(white)]...
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]These are the cards of [color(green)][var(msg_var_4)][color(white)].
[tab]There are [color(green)][var(msg_var_5)][color(white)] of them.
[tab]Make good use of them... Farewell.
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It seems you have too many cards.
[wait][clear][end]

msg_11:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I've no other choice... In that case,
[tab]I'll at least [color(green)]recover[color(white)] your wounds.
[tab]When you die, we'll meet at Valhalla.
[wait][clear][end]

msg_12:
[color(yellow)]Odin[color(white)]
[tab]My loyal servant, [var(msg_var_0)].
[tab]It has been a while.
[wait][clear][end]

msg_13:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's been a long time, sir...
[tab]However, Master Odin...
[tab]The other day, I found this...
[wait][clear][end]

msg_14:
[color(yellow)]Odin[color(white)]
[tab]The sacred stone Legenbright...
[tab]It is a wonderful find. Well done!
[wait][clear][end]

msg_15:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It is my honor, Master.
[tab]I shall present you with [color(orange)][item_with_type(skill_earring)][color(white)]...
[wait][clear][end]

msg_16:
[color(yellow)]Odin[color(white)]
[tab]I have certainly received it...
[wait][clear][end]

msg_17:
[color(green)]Selection ERROR[color(white)]
[end]