msg_0:
[color(yellow)]Bacchus[color(white)]
[tab]Hiccup... Hey hey, [var(msg_var_0)]...
[tab]Don't hurt these guys...
[tab]Hiccup!!
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[tab](Sigh)...
[tab]Hey, Bacchus, you fucker... I mean, 
[tab]Lord Bacchus, why are you with those humans?
[wait][clear][end]

msg_2:
[color(yellow)]Bacchus[color(white)]
[tab]......... Hiccup....?
[tab]Huh? I wonder why...
[tab]Anyway, lend these guys your power!
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What the hell, old man...
[tab]Oh, well.
[wait][clear][end]

msg_4:
[tab]What do you want me to do?
[choice(2)]Want a pact.
Want a card.
[end_choice][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You just want cards?
[tab]If you want them, go ahead. Take 'em.
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Heh, oh well... Seeing that it's Lord
[tab]Bacchus' orders, I'll sign a pact with
[tab]you. Don't use me too much...
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey hey, don't ya know that you can sign
[tab]pacts with only 3 demons?
[tab]I can't do anything about this...
[wait][clear][end]

msg_8:
[tab]Choose someone to [color(green)]break Pact[color(white)] with.
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Here, take some [color(green)][var(msg_var_4)][color(white)] cards.
[tab][color(green)][var(msg_var_5)][color(white)] of them should be enough.
[tab]Use them wisely! See ya.
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]D-Damn you're greedy....
[tab]You have too many cards!!
[wait][clear][end]

msg_11:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're sad...
[tab]I'll [color(green)]recover[color(white)] you instead, alright?
[tab]Sweat that old man as much as possible!
[wait][clear][end]

msg_12:
[color(green)]Selection ERROR[color(white)]
[end]