msg_0:
[color(yellow)]Shiva[color(white)]
[tab][var(msg_var_0)], the gods' tool that stirs the sea.
[tab]Long time no see...
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]YOU!!
[tab]Are you here to ridicule me again!?
[tab]I won't forgive you!
[wait][clear][end]

msg_2:
[color(yellow)]Shiva[color(white)]
[tab]Calm down...
[tab]The world exists because of you...
[tab]Isn't that so?
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It doesn't feel bad to be told that...
[tab]Alright, Shiva.
[wait][clear][end]

msg_4:
[tab]So, what do you want me to do?
[choice(2)]Want a pact.
Want a card.
[end_choice][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Let's see....
[tab]Then, let me give you cards...
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Well well, I had never thought of signing
[tab]pacts with humans... Oh well. But
[tab]don't make me work too hard...
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]This isn't good...
[tab]You've signed too many pacts.
[wait][clear][end]

msg_8:
[tab]You must [color(green)]break Pact[color(white)] with someone...
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Here's some [color(green)][var(msg_var_4)][color(white)] cards.
[tab]There's [color(green)][var(msg_var_5)][color(white)] of them...
[tab]You're lucky that I'm so generous...
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]This isn't good... It seems as though you
[tab]have too many cards...
[wait][clear][end]

msg_11:
[color(yellow)][var(msg_var_0)][color(white)]
[tab](Sigh) What can I say, huh?
[tab]Let me just [color(green)]recover[color(white)] you...
[tab]You're lucky that I'm so nice...
[wait][clear][end]

msg_12:
[color(green)]Selection ERROR[color(white)]
[end]