msg_0:
[color(yellow)]Seth[color(white)]
[tab]Poor [var(msg_var_0)], getting killed by me
[tab]day after day...
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ugh....
[tab]Seth....
[tab]You plan to kill me today too...?
[wait][clear][end]

msg_2:
[color(yellow)]Seth[color(white)]
[tab]I will let you go today...
[tab]But first, give your blessing to this person
[tab]whom I protect.
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]. . . . . . . . . . .
[tab]If that is what you want, then let it be...
[wait][clear][end]

msg_4:
[tab]Human, what should I do?
[choice(2)]Want a pact.
Want a card.
[end_choice][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm...
[tab]I do have some cards which I do not
[tab]need anymore...
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Human whom I have made a blood pact
[tab]with... Until the day we meet again...
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are being greedy...
[tab]You cannot sign any more pacts.
[tab]Will you [color(green)]break Pact[color(white)] with someone?
[wait][clear][end]

msg_8:
[tab]Then, choose the one to [color(green)]Break[color(white)].
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I shall give you [color(green)][var(msg_var_5)][color(white)]
[tab][color(green)][var(msg_var_4)][color(white)] card(s).
[tab]Use them wisely...
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are being greedy...
[tab]You cannot hold any more cards.
[tab]Maybe some other time...
[wait][clear][end]

msg_11:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Then, I shall [color(green)]recover[color(white)] you...
[tab]Now you can continue on with
[tab]your battle.
[wait][clear][end]

msg_12:
[color(green)]Selection ERROR[color(white)]
[end]