msg_0:
[color(yellow)]Barbatos[color(white)]
[tab]Well well, Lord [var(msg_var_0)]...
[tab]The last we met was when we hunted in my
[tab]forest near the river bed...
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Sir Barbatos...
[tab]That was one THOUSAND years ago.
[tab]You haven't shown your face for so long...
[wait][clear][end]

msg_2:
[color(yellow)]Barbatos[color(white)]
[tab]Was it? Well, I'm very sorry about that...
[tab]Ever since I was summoned by this human,
[tab]my fate has been sealed...
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Humans don't live for a THOUSAND years...
[tab]Very well. I have yet to see two of my
[tab]followers...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Leaving that aside...
[tab]The one who has summoned you...
[tab]Is that human of any use?
[wait][clear][end]

msg_4:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Humans don't live for a THOUSAND years...
[tab]Very well. I have yet to see one of my
[tab]followers...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Leaving that aside...
[tab]The one who has summoned you...
[tab]Is that human of any use?
[wait][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]There's no need for excuses... I didn't
[tab]think you had also been summoned by this
[tab]human... Hmmm...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha...
[tab]Interesting...
[tab]Very well, then...
[wait][clear][end]

msg_6:
[color(yellow)]Barbatos[color(white)]
[tab]Well, seeing that I have been summoned,
[tab]their abilities are worthy of praise...
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I am delighted to hear that...
[tab]I need a human whom I can use to clear
[tab]my reputation...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Sir Barbatos...
[tab]Take care of those humans for a while.
[tab]There are those I must see right now.
[wait][clear][end]

msg_8:
[color(yellow)]Barbatos[color(white)]
[tab]As you wish, Lord [var(msg_var_0)]...
[wait][clear][end]

msg_9:
[color(yellow)]Barbatos[color(white)]
[tab]Well well, this is an unexpected meeting,
[tab]Lord [var(msg_var_0)]... I didn't expect to see you
[tab]again...
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You again...
[tab]I am tired of seeing your face...
[tab]I'm looking for Adramelech right now.
[wait][clear][end]

msg_11:
[color(yellow)]Barbatos[color(white)]
[tab]I know you don't mean what you just said...
[tab]Lady Adramelech?
[tab]I haven't seen her for a while, either.
[wait][clear][end]

msg_12:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You again...
[tab]I am tired of seeing your face...
[tab]I'm looking for Shax right now.
[wait][clear][end]

msg_13:
[color(yellow)]Barbatos[color(white)]
[tab]I know you don't mean what you just said...
[tab]Sir Shax?
[tab]I haven't seen him for a while, either.
[wait][clear][end]

msg_14:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Very well, then...
[tab]Let that demon know that I need to speak
[tab]to all of my followers...
[wait][clear][end]

msg_15:
[color(yellow)]Barbatos[color(white)]
[tab]As you wish, Lord [var(msg_var_0)]...
[wait][clear][end]

msg_16:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It is better for you to use me as your
[tab]Persona than Sir Barbatos...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]This is your destiny...
[tab]You can't run from it... Hahahahaha...
[tab]You will always be trapped by my power...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Bring this to the Velvet Room...
[tab]The [color(orange)]Mtl./Black Goat[color(white)]...
[tab]You MUST summon me...
[wait][clear][end]

msg_17:
[color(green)]Selection ERROR[color(white)]
[end]