
msg_0:
[color(yellow)]エリー[color(white)]
[tab]Ｏｈ！
[tab]確かに☳…４ではなくて☶…７ですわ！？
[tab]一体なんで、☳に見えたのかしら…
[sync][wait][clear][end]

msg_1:
[color(yellow)]克哉[color(white)]
[tab]確か、あの世界は現実の裏側と言ったね…
[tab]反対だったんだ。
[tab]☳をひっくり返せば、☶に見える。
[sync][wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]他のものが左右現実と同じように見えていたから、
[tab]引っかかったんだ。
[sync][wait][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]恐らく、この札だけが現実とつながっていたんだ。
[tab]それを左右逆に見てるのだから、間違えて当然さ。
[tab]鏡と同じ理屈だな…
[sync][wait][clear][end]

msg_4:
[color(yellow)]エリー[color(white)]
[tab]だから、左右対称の文字だけは現実と同じに見えて
[tab]いたのですね…
[tab]Ｗａｎｇｌｏｎｇ千鶴…やられましたわ…
[sync][wait][clear][end]

msg_5:
[color(yellow)]エリー[color(white)]
[tab]☳と☶が逆に見えていた…Ｗａｎｇｌｏｎｇ千鶴…
[tab]貴女は、色々な意味で私のＰｒｉｄｅを傷つけた…
[tab]許しませんことよ！
[sync][wait][clear][end]
