
msg_0:
[tab][color(green)]ここにはもう用はない。[color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]ドアロック[color(white)]
[tab]この扉はロックされています。
[tab]解除コードを入力してください。
[wait][clear][end]

msg_2:
１３７１
[end]

msg_3:
[color(yellow)]ドアロック[color(white)]
[tab]解除コードが違います。
[tab]正しい番号を入力してください。
[wait][clear][end]

msg_4:
[color(yellow)]ドアロック[color(white)]
[tab]・・・解除コード、確認しました。
[tab]警備ご苦労さまです。
[tab]どうぞお入りください。
[wait][clear][end]
