
msg_0:
[color(yellow)]須藤[tab]竜也の声[color(white)]
[tab]ヒャーハッハッハ！[delay(60)]
[tab]思い出してきたかぁ～？
[tab]「向こう側」のことをよぉ…[delay(120)]
[sync][wait][clear][end]

msg_1:
[color(yellow)]須藤[tab]竜也の声[color(white)]
[tab]俺にはわかるんだよ…[delay(60)]
[tab]この音、この色、この熱さが正しいんだ！！[delay(60)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]須藤[tab]竜也の声[color(white)]
[tab]グランドクロスが過ぎてようが関係ねぇ！！[delay(60)]
[tab]殺して、燃やして、全部ぶっ壊してやる！！
[tab]こんなまがいものの世界なんぞなぁ！！[delay(120)]
[sync][wait][clear][end]

msg_3:
[color(yellow)]須藤[tab]竜也の声[color(white)]
[tab]まだわからねぇってんなら、
[tab]もっと同じ事を起こしてやるよ。[delay(60)]
[sync][wait][clear][end]

msg_4:
[color(yellow)]須藤[tab]竜也の声[color(white)]
[tab]この階からは悪魔が出るぜぇ…？[delay(60)]
[tab]「向こう側」もそうだったろうが！！
[tab]ヒャーハッハッハッハッハッハッハッハ！！
[sync][wait][clear][end]
