
msg_0:
[color(yellow)]流星野郎[color(white)]
[tab]第[var(msg_var_0)]問！！[tab]ムー大陸の噂悪魔は倒したかな？
[tab]呪いの個人タクシーと…もう一匹は何だった？
[tab]カタカナで答えてくれ！
[wait][clear][end]

msg_1:
ムッシー
[end]

msg_2:
[color(yellow)]流星野郎[color(white)]
[tab]ブー[tab]あらら不正解！？
[tab]よっく考えて、ムー大陸だよムー大陸。
[tab]これもう答えの一部だったりして…
[wait][clear][end]

msg_3:
[color(yellow)]流星野郎[color(white)]
[tab]正解！！[tab]そう、ムー大陸にいるからムッシー！！
[tab]安直だなんて言わない！
[tab]おかげで覚えてたでしょ？
[wait][clear][color(yellow)]流星野郎[color(white)]
[tab]では、扉の鍵を外そう。
[tab]奥に進んでねぇ。
[wait][clear][end]
