
msg_0:
[color(yellow)]ローカルセキュリティ[color(white)]
[tab]只今の、管理モードは、
[tab]「Ｂ」です。
[wait][clear][end]

msg_1:
[tab]管理モードをＡに移行しますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_2:
[color(yellow)]ローカルセキュリティ[color(white)]
[tab]管理モードを、「Ａ」へ移行。
[tab]「Ａ」…実行、いたします。
[wait][clear][end]

msg_3:
[color(yellow)]ローカルセキュリティ[color(white)]
[tab]管理モード、現状維持。
[tab]只今の、管理モードは、
[tab]「Ｂ」です。
[wait][clear][end]

msg_4:
[color(yellow)]ローカルセキュリティ[color(white)]
[tab]只今の、管理モードは、
[tab]「Ａ」です。
[wait][clear][end]

msg_5:
[tab]管理モードをＢに移行しますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_6:
[color(yellow)]ローカルセキュリティ[color(white)]
[tab]管理モードを、「Ｂ」へ移行。
[tab]「Ｂ」…実行、いたします。
[wait][clear][end]

msg_7:
[color(yellow)]ローカルセキュリティ[color(white)]
[tab]管理モード、現状維持。
[tab]只今の、管理モードは、
[tab]「Ａ」です。
[wait][clear][end]
