
msg_0:
[color(yellow)]エリー[color(white)]
[tab]これは☵…６ですわ。
[tab]ここが六の門のはずですわ…
[sync][wait][clear][end]

msg_1:
[color(yellow)]エリー[color(white)]
[tab]この八卦文字は☵…６なのですけど…
[tab]自信が無くなってしまいましたわ…
[tab]先にＢｒｏｗｎの楽屋を探しましょう。
[sync][wait][clear][end]

msg_2:
[color(yellow)]エリー[color(white)]
[tab]この八卦文字は☵…６ですわね。
[tab]先に☰…壱の門を探しましょう。
[sync][wait][clear][end]

msg_3:
[color(yellow)]エリー[color(white)]
[tab]この八卦文字は☵…６ですわ。
[tab]次は☱…弐の門を探しましょう。
[sync][wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
[tab]もうここに用はねぇ…
[tab]次は☶…７だな。
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]天野…ここはもう通ったろうが。
[tab]次が最後だな…☷を探せ。
[sync][wait][clear][end]
