
msg_0:
[color(yellow)]研究員[color(white)]
[tab]そうか…あんた達だな。
[tab]事情は仲間から聞いているよ。
[tab]俺も、協力させてもらおう。
[wait][clear][color(yellow)]研究員[color(white)]
[tab]この[color(green)]Ｌｖ．２カード[color(white)]があれば、
[tab]奥の研究室に入ることができる。
[tab]受け取ってくれ。
[wait][clear][end]

msg_1:
[tab][color(green)]舞耶達は、
[tab][item_with_type(item_ffff)]を手に入れた。[color(white)]
[wait][clear][end]

msg_2:
[color(yellow)]研究員[color(white)]
[tab]俺達にはこんな事ぐらいしかできないが…
[tab]だが頼む。これ以上被害者が増える前に、
[tab]ここの研究をやめさせてくれ。
[wait][clear][end]

msg_3:
[color(yellow)]研究員[color(white)]
[tab]あのカードで開く扉は二つある。
[tab]気をつけて行けよ。
[wait][clear][end]
