
msg_0:
[color(yellow)]ミカエル[color(white)]
 [var(msg_var_0)]よ…
 正しい神の意志を人間に伝えているか？
[wait][clear][color(yellow)]ミカエル[color(white)]
 近頃、人間達の倫理観が麻の如く乱れている。
 よもや、怠けている訳ではあるまいな？
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
 お言葉ですがミカエル様！
 堕天使共が人心を惑わしているのであって
 わたくし達が怠けているのではありません！
[wait][clear][end]

msg_2:
[color(yellow)]ミカエル[color(white)]
 そう怒るでない。
 ところで、お前に頼みたい事がある。
 この者の力となってやってはくれぬか？
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
 承知いたしましたわ。
 ミカエル様の命令ならば喜んで…
[wait][clear][end]

msg_4:
 ところで、わたくしにどうして欲しいのです？
[choice(2)]契約して欲しい
カードが欲しい
[end_choice][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
 そうですわね…
 でしたら、あなたにわたくしのカードを
 差し上げましょう。
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
 わたくしもこれで、あなたの守護天使。
 次回の出会いを楽しみにしていますわ。
 では、いずれ…
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
 あら、たくさん契約してますわね。
 これでは、わたくしが契約できませんわ。
[wait][clear][end]

msg_8:
 どなたかの[color(green)]契約を破棄[color(white)]して頂かないと…
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
契約しない
[end_choice][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_4)][color(white)]のカードです。
 [color(green)][var(msg_var_5)]枚[color(white)]あります。
 大事に使って下さい、それでは…
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
 あなた、カードを持ち過ぎの様ですわ。
[wait][clear][end]

msg_11:
[color(yellow)][var(msg_var_0)][color(white)]
 仕方ありませんわね…
 でしたら、[color(green)]傷の治療[color(white)]だけでもしておきます。
 あまり無茶をしない様に気を付けて下さい。
[wait][clear][end]

msg_12:
[color(green)]選択肢ジャンプの挙動エラーです[color(white)]
[end]
