
msg_0:
[color(yellow)]ゆきの[color(white)]
[tab]取材、お疲れさま。
[tab]舞耶さんに、手紙届いてますよ。
[tab]差出人とか、書いてないけど…
[sync][wait][clear][end]

msg_1:
[tab]差出人とか、書いてないけど…
[choice(2)]サンクス、ユッキー！
ありがとう。でも、誰だろう…？
[end_choice][clear][end]

msg_2:
[color(yellow)]天野[tab]舞耶（あまの[tab]まや）[color(white)]
[tab][color(green)]キスメット出版の高校生向け情報誌、
[tab]「クーレスト」編集部に在籍する女性編集者。
[tab]今回の主人公。
[color(white)]
[sync][wait][clear][end]

msg_3:
[color(yellow)]天野[tab]舞耶（あまの[tab]まや）[color(white)]
[tab][color(green)]キスメット出版の高校生向け情報誌、
[tab]「クーレスト」編集部に在籍する女性編集者。
[tab]今回の主人公。
[color(white)]
[sync][wait][clear][end]

msg_4:
[color(yellow)]手紙[color(white)]
[tab]次ハ、オ前ダ。
[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab]ＪＯＫＥＲ
[sync][wait][clear][end]

msg_5:
[color(yellow)]舞耶[color(white)]
[tab]………？
[sync][wait][clear][end]

msg_6:
[color(yellow)]新人[color(white)]
[tab]天野先輩、編集長が呼んでますよ。
[sync][wait][clear][end]

msg_7:
[color(yellow)]新人[color(white)]
[tab]いっつも面倒な仕事ばっか押しつけられて、
[tab]先輩も大変すね…
[sync][wait][clear][end]

msg_8:
[color(yellow)]新人[color(white)]
[tab]あくせく働いても、大していい事あるわけじゃなし
[tab]やっぱ夢と現実って、こんなもんなんすかね…
[tab]はぁ…会社辞めよかなぁ…
[sync][wait][clear][end]
