function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    disableMap();
    levelFootstepSet(sfx_15);
    ref_4 = spriteLoad(sprite_0);
    wait(ref_4);
    ref_6 = spriteLoad(sprite_2);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_6);
    wait(ref_8);
    ref_a = spriteLoad(sprite_d4);
    wait(ref_a);
    cameraSet(northwest, 50, 0, -500);
    objAnimTranslate(obj_1, 0, 0, 100, 1);
    objAnimTranslate(obj_2, 0, 0, -100, 1);
    objAnimWait(obj_1);
    objAnimWait(obj_2);
    bitGet(var_7, EBIT_0005);
    bne(var_7, 0, label_15);
    call(DEAU);
    b(label_18);
  label_15:
    bne(var_7, 1, label_18);
    call(FREE);
    b(label_18);
  label_18:
}

function MODORI()
{
    unitIdleOffAll();
    unitSpawn(maya, sprite_0, 52, 0, -503, north, none);
    unitFace(maya, west);
    unitSpawn(enemy1, sprite_d4, 600, 0, -152, north, none);
    unitFace(enemy1, north);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    sndMusicPlay(sound_30a9, 127);
    objAnimTranslate(obj_1, 0, 0, -100, 60);
    objAnimTranslate(obj_2, 0, 0, 100, 60);
    objAnimWait(obj_1);
    objAnimWait(obj_2);
    delayClear();
    delayWait(60);
    ref_28 = cameraMoveTo(600, 0, -152, 120);
    wait(ref_28);
    unitFace(enemy1, east);
    ref_2b = dialogAlloc();
    ref_2c = msgShow(msg_0);
/***************************************
[color(yellow)]受付嬢[color(white)]
[tab]あ、舞耶。
[tab]友達なら、まだ見えてないわよ。
[wait][clear]
***************************************/
    wait(ref_2c);
    dialogFree(ref_2b);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    bitSet(EBIT_E1000);
    bitClear(EBIT_E1100);
    eventLoad(event_99);
}

function CHECK()
{
    bitGet(var_7, EBIT_0005);
    bne(var_7, 0, label_3d);
    call(DEAU);
    b(label_40);
  label_3d:
    bne(var_7, 1, label_40);
    call(FREE);
    b(label_40);
  label_40:
}

function DEAU()
{
    unitIdleOffAll();
    unitSpawn(maya, sprite_0, 50, 0, -500, west, none);
    unitSpawn(enemy1, sprite_d4, 600, 0, -152, north, none);
    unitSpawn(ulala, sprite_6, 1550, 0, -1050, west, none);
    unitTriggerSet(ulala, BLOCK_URARA, 255, 1);
    envTriggerSet(ELE, 14, 1, line, coll_0);
    envTriggerSet(EXIT, 131, 2, line, coll_1);
    envTriggerSet(EXIT, 7, 2, line, coll_1);
    envTriggerSet(EXIT, 131, 2, line, coll_2);
    envTriggerSet(EXIT, 193, 2, line, coll_2);
    envTriggerSet(BLOCK_UKETUKE, 14, 1, line, coll_1c);
    envTriggerSet(BLOCK_UKETUKE, 14, 1, line, coll_1d);
    envTriggerSet(BLOCK_UKETUKE, 28, 1, line, coll_1e);
    envTriggerSet(BLOCK_UKETUKE, 28, 1, line, coll_1f);
    envTriggerSet(BLOCK_UKETUKE, 56, 1, line, coll_20);
    envTriggerSet(BLOCK_UKETUKE, 56, 1, line, coll_21);
    envTriggerSet(BLOCK_UKETUKE, 112, 1, line, coll_22);
    envTriggerSet(BLOCK_UKETUKE, 112, 1, line, coll_23);
    envTriggerSet(BLOCK_UKETUKE, 224, 1, line, coll_24);
    envTriggerSet(BLOCK_UKETUKE, 224, 1, line, coll_25);
    envTriggerSet(HIJOU, 14, 1, line, coll_38);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    sndMusicPlay(sound_30a9, 127);
    objAnimTranslate(obj_1, 0, 0, -100, 60);
    objAnimTranslate(obj_2, 0, 0, 100, 60);
    delayClear();
    delayWait(90);
    unitAnimationPlay(maya, animation_28, 1);
    unitWait(maya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_3, 1);
    delayClear();
    delayWait(60);
    ref_65 = call(MAYAMOVE);
    cameraMoveTo(1550, 0, -1050, 180);
    delayClear();
    delayWait(60);
    cameraRotateTo(1, 1);
    wait(ref_65);
    unitAnimationHold(ulala, animation_18, -1);
    ref_6c = bustupLoad(bustup_18);
    bustupWait(ref_6c);
    ref_6e = bustupAlloc(ref_6c, left, rgb(0,0,0));
    bustupFade(ref_6e, rgb(128,0,0), 30);
    ref_70 = dialogAlloc();
    ref_71 = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]チャ～オ、マーヤ。
[tab]んじゃ、気ばって行くかんねぇ～
[tab]絶っ対、イイ男捕まえんのよ！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(90);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_1e, 1);
    sync();
    wait(ref_71);
    ref_78 = msgShow(msg_2);
/***************************************
[color(yellow)]芹沢[tab]うらら（せりざわ[tab]うらら）[color(green)]
[tab]女性用下着メーカーに勤める、舞耶の親友。
[tab]占い好きの化粧美人で、
[tab]男運が悪いことを気に病んでいる。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_78);
    dialogFree(ref_70);
    ref_7c = bustupFade(ref_6e, rgb(0,0,0), 10);
    bustupWait(ref_7c);
    bustupFree(ref_6e);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_2d, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(maya, animation_0, 1);
    unitAnimationHold(ulala, animation_21, 60);
    unitWait(ulala);
    delayClear();
    delayWait(30);
    ref_8b = bustupLoad(bustup_19);
    bustupWait(ref_8b);
    ref_8d = bustupAlloc(ref_8b, left, rgb(0,0,0));
    bustupFade(ref_8d, rgb(128,0,0), 30);
    ref_8f = dialogAlloc();
    ref_90 = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なにぃ～！？
[tab]仕事で行けなくなったぁ～！？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    sync();
    wait(ref_90);
    ref_94 = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ちょっとアンタ、
[tab]初めっから行く気なかったんじゃないの！？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1f, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_1e, 2);
    unitWait(ulala);
    sync();
    wait(ref_94);
    ref_9c = bustupFade(ref_8d, rgb(0,0,0), 10);
    bustupWait(ref_9c);
    bustupFree(ref_8d);
    ref_9f = bustupLoad(bustup_17);
    bustupWait(ref_9f);
    ref_a1 = bustupAlloc(ref_9f, left, rgb(0,0,0));
    bustupFade(ref_a1, rgb(128,0,0), 30);
    ref_a3 = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あ、わかった。
[tab]例のデジャ・ヴュの少年が気になってんでしょ？
[tab]かぁ～[tab]やめときなって！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_14, 1);
    unitWait(ulala);
    delayClear();
    delayWait(20);
    unitAnimationPlay(ulala, animation_25, 1);
    unitWait(ulala);
    sync();
    wait(ref_a3);
    ref_ac = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]大体、なんで駅前で１回ぶつかっただけの年下に、
[tab]そんなに入れ込むかねぇ～
[tab]いくら、前に会った気がするったってさぁ…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    unitWait(ulala);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_14, 1);
    unitWait(ulala);
    sync();
    wait(ref_ac);
    dialogFree(ref_8f);
    ref_b6 = bustupFade(ref_a1, rgb(0,0,0), 10);
    bustupWait(ref_b6);
    bustupFree(ref_a1);
    unitAnimationPlay(ulala, animation_a, 1);
    unitAnimationPlay(maya, animation_29, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_2d, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_1f, 1);
    ref_c5 = bustupLoad(bustup_17);
    bustupWait(ref_c5);
    ref_c7 = bustupAlloc(ref_c5, left, rgb(0,0,0));
    bustupFade(ref_c7, rgb(128,0,0), 30);
    ref_c9 = dialogAlloc();
    ref_ca = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なに、本当に仕事なの？
[tab]七姉妹学園で、ＪＯＫＥＲの噂取材？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ca);
    unitAnimationPlay(ulala, animation_1d, 1);
    ref_ce = msgShow(msg_8);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あ～もう、しゃーないな、ホレ！
[tab]ちゃっちゃっと済ませば、まだ間に合うわ。
[tab]手伝ってあげっから、急ぐのよぅ！！
[sync][wait][clear]
***************************************/
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_1e, 1);
    unitWait(ulala);
    delayClear();
    delayWait(30);
    unitAnimationHold(ulala, animation_18, -1);
    sync();
    wait(ref_ce);
    dialogFree(ref_c9);
    ref_d8 = bustupFade(ref_c7, rgb(0,0,0), 10);
    bustupWait(ref_d8);
    bustupFree(ref_c7);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
    partyMemberAdd(ulala);
    bitSet(EBIT_0005);
    delayClear();
    delayWait(60);
    ref_e1 = cameraLookAtUnit(maya, 0, 60);
    wait(ref_e1);
    unitDespawn(maya, none);
    playerInit(north);
    bitClear(EBIT_E1100);
    unitIdleOnAll();
    controlEnable();
}

function FREE()
{
    unknownVar2(var_0);
    bne(var_0, 4, label_ef);
    ref_eb = sndLoad(sound_3035);
    wait(ref_eb);
    sndMusicPlay(sound_3035, 127);
    b(label_f7);
  label_ef:
    sndIdGet(var_0);
    bne(var_0, -1, label_f5);
    ref_f1 = sndLoad(sound_3035);
    wait(ref_f1);
    sndMusicPlay(sound_3035, 127);
    b(label_f6);
  label_f5:
    b(label_f6);
  label_f6:
    b(label_f7);
  label_f7:
    sndMusicPlay(sound_30a9, 127);
    objAnimTranslate(obj_1, 0, 0, -100, 1);
    objAnimTranslate(obj_2, 0, 0, 100, 1);
    objAnimWait(obj_1);
    objAnimWait(obj_2);
    unitSpawn(enemy1, sprite_d4, 600, 0, -152, north, none);
    unitFace(enemy1, north);
    unitSpawn(ulala, sprite_6, 1559, 0, -1051, north, none);
    unitFace(ulala, west);
    unitTriggerSet(ulala, BLOCK_URARA, 255, 1);
    envTriggerSet(ELE, 14, 1, line, coll_0);
    envTriggerSet(EXIT, 131, 2, line, coll_1);
    envTriggerSet(EXIT, 7, 2, line, coll_1);
    envTriggerSet(EXIT, 131, 2, line, coll_2);
    envTriggerSet(EXIT, 193, 2, line, coll_2);
    envTriggerSet(BLOCK_UKETUKE, 14, 1, line, coll_1c);
    envTriggerSet(BLOCK_UKETUKE, 14, 1, line, coll_1d);
    envTriggerSet(BLOCK_UKETUKE, 28, 1, line, coll_1e);
    envTriggerSet(BLOCK_UKETUKE, 28, 1, line, coll_1f);
    envTriggerSet(BLOCK_UKETUKE, 56, 1, line, coll_20);
    envTriggerSet(BLOCK_UKETUKE, 56, 1, line, coll_21);
    envTriggerSet(BLOCK_UKETUKE, 112, 1, line, coll_22);
    envTriggerSet(BLOCK_UKETUKE, 112, 1, line, coll_23);
    envTriggerSet(BLOCK_UKETUKE, 224, 1, line, coll_24);
    envTriggerSet(BLOCK_UKETUKE, 224, 1, line, coll_25);
    envTriggerSet(HIJOU, 14, 1, line, coll_38);
    playerInit(west);
    controlDisable();
    bitClear(EBIT_E1100);
    unitIdleOnAll();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    controlEnable();
    screenFadeWait(inner);
    screenFadeWait(outer);
}

function BLOCK_URARA()
{
    controlDisable();
    unitFacePlayer(ulala);
    ref_11f = bustupLoad(bustup_17);
    bustupWait(ref_11f);
    ref_121 = bustupAlloc(ref_11f, left, rgb(0,0,0));
    ref_122 = bustupLoad(bustup_fe);
    bustupWait(ref_122);
    ref_124 = bustupAlloc(ref_122, right, rgb(0,0,0));
    bustupFade(ref_121, rgb(128,0,0), 30);
    bustupFade(ref_124, rgb(128,0,0), 30);
    ref_127 = dialogAlloc();
    ref_128 = msgShow(msg_9);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ホラ見てみ、ワンロン占いでも
[tab]「今日は運命の出会いの日」って出てんのよ。
[tab]絶対、パーティ行くかんね！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_14, 1);
    sync();
    wait(ref_128);
    dialogFree(ref_127);
    ref_12d = bustupFade(ref_121, rgb(0,0,0), 10);
    ref_12e = bustupFade(ref_124, rgb(0,0,0), 10);
    bustupWait(ref_12d);
    bustupWait(ref_12e);
    ref_131 = bustupFade(ref_121, rgb(0,0,0), 10);
    bustupWait(ref_131);
    bustupFree(ref_121);
    ref_134 = bustupFade(ref_124, rgb(0,0,0), 10);
    bustupWait(ref_134);
    bustupFree(ref_124);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
    bitSet(EBIT_RESEERVE_0015);
    unitRestoreFacing(ulala);
    controlEnable();
}

function BLOCK_UKETUKE()
{
    controlDisable();
    unitFacePlayer(enemy1);
    ref_13f = dialogAlloc();
    ref_140 = msgShow(msg_10);
/***************************************
[color(yellow)]受付嬢[color(white)]
[tab]どうしたの舞耶？[tab]へぇ～
[tab]取材で、お見合いパーティー行けなくなったの？
[tab]あのお局様、ほんとイジワルよねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(enemy1, animation_24, 1);
    wait(ref_140);
    dialogFree(ref_13f);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitRestoreFacing(enemy1);
    controlEnable();
}

function MAYAMOVE()
{
    unitMove(maya, 970, -400, face_west, fast);
    unitWait(maya);
    unitMove(maya, 970, -200, face_west, fast);
    unitWait(maya);
    unitMove(maya, 1550, -200, face_north, fast);
    unitWait(maya);
    unitAnimationPlay(ulala, animation_4, 1);
    unitMove(maya, 1550, -960, face_north, fast);
    delayClear();
    delayWait(60);
    unitFace(ulala, south);
    unitAnimationPlay(ulala, animation_a, 1);
}

function RETURN_HENSHU()
{
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    bitSet(EBIT_E1000);
    bitClear(EBIT_E1100);
    eventLoad(event_99);
}

function EXIT()
{
    controlDisable();
    bitClear(EBIT_E1100);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    sndVolumeFadeOff(sound_3035, 180);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_9b);
}

function ELE()
{
    controlDisable();
    sndMusicPlay(sound_30a9, 127);
    objAnimTranslate(obj_1, 0, 0, 100, 60);
    objAnimTranslate(obj_2, 0, 0, -100, 60);
    objAnimWait(obj_1);
    objAnimWait(obj_2);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    bitSet(EBIT_E1000);
    bitClear(EBIT_E1100);
    eventLoad(event_99);
}

function HIJOU()
{
    controlDisable();
    ref_17b = dialogAlloc();
    ref_17c = msgShow(msg_11);
/***************************************
[color(yellow)]非常口[color(green)]
[tab]ここには入れない。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_17c);
    dialogFree(ref_17b);
    controlEnable();
}
