function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3004, 127);
    cameraSet(north, 1400, -1100, -1400);
    ref_4 = spriteLoad(sprite_0);
    wait(ref_4);
    ref_6 = spriteLoad(sprite_6);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_d);
    wait(ref_8);
    ref_a = spriteLoad(sprite_55);
    wait(ref_a);
    unitSpawn(maya, sprite_0, 1240, 0, -1620, south, none);
    unitSpawn(ulala, sprite_6, 1240, 0, -1170, west, none);
    unitSpawn(katsuya, sprite_d, 1560, 0, -1620, east, none);
    unitSpawn(philemon, sprite_55, 1400, 0, -1400, north, none);
    unitAnimationPlay(maya, animation_48, 1);
    unitAnimationPlay(ulala, animation_48, 1);
    unitAnimationPlay(katsuya, animation_48, 1);
    objAnimRotate(obj_4, 0, 360, 0, 180, 1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_30c0, 127);
    ref_1a = cameraMoveTo(1400, 0, -1400, 180);
    wait(ref_1a);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_31, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_3a, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_28, 1);
    unitAnimationPlay(maya, animation_3c, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_45, 1);
    unitWait(maya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_1, 1);
    unitAnimationPlay(maya, animation_31, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_28, 1);
    ref_38 = spriteLoad(sprite_54);
    wait(ref_38);
    unitAnimationPlay(ulala, animation_3c, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_11, 1);
    unitAnimationPlay(ulala, animation_46, 1);
    unitWait(ulala);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_d, 1);
    unitAnimationPlay(ulala, animation_3f, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_3c, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(ulala, animation_3d, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_3e, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_3d, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(ulala, animation_42, 1);
    ref_53 = spriteLoad(sprite_e);
    wait(ref_53);
    ref_55 = bustupLoad(bustup_1c);
    bustupWait(ref_55);
    ref_57 = bustupAlloc(ref_55, left, rgb(0,0,0));
    bustupFade(ref_57, rgb(128,0,0), 30);
    ref_59 = dialogAlloc();
    ref_5a = msgShow(msg_0);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]私ら、死んじゃったわけ…？
[tab]何だったのよぅ、私の人生…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5a);
    dialogFree(ref_59);
    ref_5e = bustupFade(ref_57, rgb(0,0,0), 10);
    bustupWait(ref_5e);
    bustupFree(ref_57);
    ref_61 = efctDummy(effect_c);
    ref_62 = efctLoad(effect_c);
    ref_63 = unitColor(philemon, rgb(240,240,240), 60);
    wait(ref_63);
    unitAnimationPlay(ulala, animation_3c, 1);
    unitAnimationPlay(maya, animation_0, 1);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_e);
    unitAnimationPlay(katsuya, animation_8, 1);
    ref_6a = unitColor(philemon, rgb(112,112,112), 60);
    wait(ref_6a);
    ref_6c = unitColor(philemon, rgb(240,240,240), 60);
    wait(ref_6c);
    ref_6e = unitColor(philemon, rgb(112,112,112), 60);
    wait(ref_6e);
    ref_70 = unitColor(philemon, rgb(240,240,240), 60);
    wait(ref_70);
    unitDespawn(philemon, ghost);
    sndStop(sound_30c0);
    wait(ref_61);
    wait(ref_62);
    sndMusicPlay(sound_30bf, 127);
    efctPlay(effect_c, efct_1, 1400, -50, -1400, 1400, -50, -1400, false);
    unitSpawn(philemon, sprite_54, 1400, 0, -1400, north, ghost);
    unitSpawn(unit_62, sprite_54, 1400, 0, -1400, north, ghost);
    unitPalette(philemon, 4);
    unitDepthOffset(unit_62, -2);
    unitSpriteEffect(philemon, 3);
    unitSpriteEffect(unit_62, 2);
    unitColor(philemon, rgb(0,0,0), 1);
    unitColor(unit_62, rgb(0,0,0), 1);
    efctWait(efct_1);
    unitColor(philemon, rgb(112,112,112), 120);
    ref_82 = unitColor(unit_62, rgb(112,112,112), 120);
    wait(ref_82);
    wait(ref_82);
    ref_85 = call(FIRE1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_62, animation_c, 1);
    ref_89 = bustupLoad(bustup_de);
    bustupWait(ref_89);
    ref_8b = bustupAlloc(ref_89, right, rgb(0,0,0));
    bustupFade(ref_8b, rgb(128,0,0), 30);
    ref_8d = dialogAlloc();
    ref_8e = msgShow(msg_1);
/***************************************
[color(yellow)]何者かの声[color(white)]
[tab]そうでは…ない…
[tab]私が…諸君を…招いた…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_8e);
    dialogFree(ref_8d);
    ref_92 = bustupFade(ref_8b, rgb(0,0,0), 10);
    bustupWait(ref_92);
    bustupFree(ref_8b);
    unitAnimationPlay(unit_62, animation_0, 1);
    unitAnimationPlay(maya, animation_3, 1);
    unitAnimationPlay(ulala, animation_3f, 1);
    delayClear();
    delayWait(60);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitAnimationPlay(katsuya, animation_11, 1);
    unitAnimationPlay(maya, animation_0, 1);
    unitAnimationPlay(ulala, animation_3c, 1);
    ref_9f = bustupLoad(bustup_de);
    bustupWait(ref_9f);
    ref_a1 = bustupAlloc(ref_9f, right, rgb(0,0,0));
    bustupFade(ref_a1, rgb(128,0,0), 30);
    ref_a3 = dialogAlloc();
    ref_a4 = msgShow(msg_2);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]私の名は…フィレモン…[delay(30)]
[tab]意識と無意識の狭間に…住まう者…
[tab]諸君に…ペルソナを与えた…者だ…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(unit_62, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_2, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(unit_62, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_0, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_4, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(unit_62, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_0, 1);
    sync();
    wait(ref_a4);
    ref_bd = msgShow(msg_3);
/***************************************
[color(yellow)]フィレモン[color(white)]
[color(green)][tab]絶えず人の自我を見守り啓示を与えていると言う、
[tab]普遍的無意識の創造性を象徴する元型。
[tab]何やら弱っている様子だが…[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_bd);
    dialogFree(ref_a3);
    ref_c1 = bustupFade(ref_a1, rgb(0,0,0), 10);
    bustupWait(ref_c1);
    bustupFree(ref_a1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_10, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_11, 1);
    ref_ca = bustupLoad(bustup_21);
    bustupWait(ref_ca);
    ref_cc = bustupAlloc(ref_ca, left, rgb(0,0,0));
    bustupFade(ref_cc, rgb(128,0,0), 30);
    ref_ce = dialogAlloc();
    ref_cf = msgShow(msg_4);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]５０１号も同じ言葉を口にした…
[tab]これが夢だと受け入れて尋ねるが、
[tab]そのペルソナとは、一体何だ？
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_1, 1);
    unitAnimationPlay(unit_62, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_4, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_0, 1);
    unitFace(unit_62, west);
    sync();
    wait(ref_cf);
    dialogFree(ref_ce);
    ref_de = bustupFade(ref_cc, rgb(0,0,0), 10);
    bustupWait(ref_de);
    bustupFree(ref_cc);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_0, 1);
    unitAnimationPlay(unit_62, animation_6, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(unit_62, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_62, animation_24, 1);
    ref_eb = bustupLoad(bustup_de);
    bustupWait(ref_eb);
    ref_ed = bustupAlloc(ref_eb, right, rgb(0,0,0));
    bustupFade(ref_ed, rgb(128,0,0), 30);
    ref_ef = dialogAlloc();
    ref_f0 = msgShow(msg_5);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]諸君が得た力は…
[tab]人の心の奥底に潜む…
[tab]神や悪魔の如き…もう１人の己を呼び出す力…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f0);
    unitAnimationPlay(unit_62, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_4, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_0, 1);
    unitFace(unit_62, north);
    unitAnimationPlay(unit_62, animation_24, 1);
    ref_fc = msgShow(msg_6);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]神の様に…慈愛に満ちた自分…
[tab]悪魔の如き…残酷な自分…
[tab]人は、様々な仮面を着けて…生きるもの…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_fc);
    ref_ff = msgShow(msg_7);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]今の諸君の姿も…無数の仮面の一つに過ぎん…
[tab]ペルソナもまた…数多ある君の姿の一つ…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(unit_62, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_2, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(unit_62, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_0, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_4, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(unit_62, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(unit_62, animation_0, 1);
    sync();
    wait(ref_ff);
    dialogFree(ref_ef);
    ref_119 = bustupFade(ref_ed, rgb(0,0,0), 10);
    bustupWait(ref_119);
    bustupFree(ref_ed);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_b, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_1, 1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(katsuya, animation_11, 1);
    ref_125 = bustupLoad(bustup_21);
    bustupWait(ref_125);
    ref_127 = bustupAlloc(ref_125, left, rgb(0,0,0));
    bustupFade(ref_127, rgb(128,0,0), 30);
    ref_129 = dialogAlloc();
    ref_12a = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]物理的干渉力を持った、別自我…
[tab]元型のようなものだと言うことか…？
[tab]それを僕達に与えた目的は？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(maya, animation_0, 1);
    sync();
    wait(ref_12a);
    dialogFree(ref_129);
    ref_12f = bustupFade(ref_127, rgb(0,0,0), 10);
    bustupWait(ref_12f);
    bustupFree(ref_127);
    unitAnimationPlay(ulala, animation_31, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_3, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_0, 1);
    ref_13c = bustupLoad(bustup_1b);
    bustupWait(ref_13c);
    ref_13e = bustupAlloc(ref_13c, left, rgb(0,0,0));
    bustupFade(ref_13e, rgb(128,0,0), 30);
    ref_140 = dialogAlloc();
    ref_141 = msgShow(msg_9);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]か、会話が成立してる…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_141);
    dialogFree(ref_140);
    ref_145 = bustupFade(ref_13e, rgb(0,0,0), 10);
    bustupWait(ref_145);
    bustupFree(ref_13e);
    bitSet(LBIT_0000);
    delayClear();
    delayWait(30);
    unitAnimationPlay(unit_62, animation_25, 1);
    delayClear();
    delayWait(30);
    ref_14e = bustupLoad(bustup_de);
    bustupWait(ref_14e);
    ref_150 = bustupAlloc(ref_14e, right, rgb(0,0,0));
    bustupFade(ref_150, rgb(128,0,0), 30);
    ref_152 = dialogAlloc();
    ref_153 = msgShow(msg_10);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]諸君に…頼み…ある…
[tab]私の…読み…甘かっ…
[tab]彼奴…仕組ん…因果の糸…あまり…深い…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_153);
    unitAnimationPlay(katsuya, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_1, 1);
    ref_15a = msgShow(msg_11);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]彼ら…血涙を流し…創…た「こちら側」……
[tab]救え……諸君しか…
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitAnimationPlay(maya, animation_0, 1);
    sync();
    wait(ref_15a);
    dialogFree(ref_152);
    ref_162 = bustupFade(ref_150, rgb(0,0,0), 10);
    bustupWait(ref_162);
    bustupFree(ref_150);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_168 = bustupLoad(bustup_21);
    bustupWait(ref_168);
    ref_16a = bustupAlloc(ref_168, left, rgb(0,0,0));
    bustupFade(ref_16a, rgb(128,0,0), 30);
    ref_16c = dialogAlloc();
    ref_16d = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]どうした？
[tab]よく聞き取れない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_16d);
    dialogFree(ref_16c);
    ref_171 = bustupFade(ref_16a, rgb(0,0,0), 10);
    bustupWait(ref_171);
    bustupFree(ref_16a);
    unitAnimationPlay(katsuya, animation_0, 1);
    bitSet(LBIT_0001);
    wait(ref_85);
    ref_177 = efctDummy(effect_c);
    ref_178 = efctLoad(effect_c);
    ref_179 = unitColor(unit_62, rgb(240,240,240), 30);
    wait(ref_179);
    unitAnimationHold(ulala, animation_21, 60);
    unitAnimationHold(maya, animation_21, 60);
    ref_17d = unitColor(unit_62, rgb(112,112,112), 30);
    wait(ref_17d);
    ref_17f = unitColor(unit_62, rgb(240,240,240), 30);
    wait(ref_17f);
    ref_181 = unitColor(unit_62, rgb(112,112,112), 30);
    wait(ref_181);
    ref_183 = unitColor(unit_62, rgb(240,240,240), 30);
    wait(ref_183);
    unitDespawn(unit_62, ghost);
    wait(ref_177);
    wait(ref_178);
    sndMusicPlay(sound_30bf, 127);
    efctPlay(effect_c, efct_1, 1400, -50, -1400, 1400, -50, -1400, false);
    unitSpawn(unit_63, sprite_55, 1400, 0, -1400, north, none);
    unitSpriteEffect(unit_63, 2);
    unitColor(unit_63, rgb(0,0,0), 1);
    ref_18d = unitColor(unit_63, rgb(112,112,112), 60);
    wait(ref_18d);
    unitSpriteEffect(unit_63, 2);
    efctWait(efct_1);
    ref_191 = dialogAlloc();
    ref_192 = msgShow(msg_13);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]注意……噂が現実になる………
[tab]人…心に……光を………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_192);
    dialogFree(ref_191);
    delayClear();
    delayWait(60);
    ref_198 = sndVolumeFadeTo(sound_3004, 0, 240);
    delayClear();
    delayWait(120);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 1.38134765625, false);
    screenFadeOuter(rgb(255,255,255), 1.38134765625, false);
    wait(ref_198);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_9d);
}

function FIRE2()
{
  label_1a4:
    unitSpriteEffect(unit_62, 2);
    ref_1a5 = unitColor(unit_62, rgb(48,48,48), 60);
    wait(ref_1a5);
    bitGet(var_1, LBIT_0001);
    bnz(var_1, label_1af);
    unitSpriteEffect(unit_62, 0);
    ref_1aa = unitColor(unit_62, rgb(112,112,112), 60);
    wait(ref_1aa);
    bitGet(var_1, LBIT_0001);
    bnz(var_1, label_1af);
    b(label_1a4);
  label_1af:
}

function FIRE1()
{
  label_1b0:
    unitColor(philemon, rgb(16,16,16), 120);
    ref_1b1 = unitColor(unit_62, rgb(16,16,16), 120);
    wait(ref_1b1);
    wait(ref_1b1);
    bitGet(var_0, LBIT_0000);
    bnz(var_0, label_1bc);
    unitColor(philemon, rgb(112,112,112), 120);
    ref_1b7 = unitColor(unit_62, rgb(112,112,112), 120);
    wait(ref_1b7);
    bitGet(var_0, LBIT_0000);
    bnz(var_0, label_1bc);
    b(label_1b0);
  label_1bc:
}
