function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    levelFootstepSet(sfx_f);
    sndIdGet(var_0);
    bne(var_0, -1, label_6);
    b(label_8);
  label_6:
    sndVolumeFadeTo(var_0, 90, 60);
    b(label_8);
  label_8:
    sndUnkCF(90);
    sndIdGet(var_0);
    bne(var_0, -1, label_c);
    b(label_e);
  label_c:
    sndVolumeFadeTo(var_0, 90, 60);
    b(label_e);
  label_e:
    sndUnkCF(90);
    screenColorAdjust(1.0986328125, 0.48828125, 0.244140625);
    levelWavy(1, 82, 2, 30, 0);
    objAnimRotate(obj_0, 0, 80, 0, 1, 0);
    objAnimRotate(obj_1, 0, -80, 0, 1, 0);
    objAnimWait(obj_0);
    objAnimWait(obj_1);
    ref_15 = spriteLoad(sprite_0);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_d);
    wait(ref_17);
    ref_19 = spriteLoad(sprite_6);
    wait(ref_19);
    ref_1b = spriteLoad(sprite_13);
    wait(ref_1b);
    ref_1d = spriteLoad(sprite_b4);
    wait(ref_1d);
    ref_1f = spriteLoad(sprite_b5);
    wait(ref_1f);
    ref_21 = spriteLoad(sprite_b6);
    wait(ref_21);
    ref_23 = spriteLoad(sprite_b7);
    wait(ref_23);
    ref_25 = spriteLoad(sprite_118);
    wait(ref_25);
    ref_27 = spriteLoad(sprite_119);
    wait(ref_27);
    ref_29 = spriteLoad(sprite_11a);
    wait(ref_29);
    unitIdleOffAll();
    cameraSet(north, 400, 0, 7);
    cameraRotateTo(7, 1);
    unitSpawn(katsuya, sprite_d, 400, 0, -1300, north, none);
    unitFace(katsuya, south);
    unitSpawn(ulala, sprite_6, 400, 0, -1300, north, none);
    unitFace(ulala, south);
    unitSpawn(baofu, sprite_13, 400, 0, -1300, north, none);
    unitFace(baofu, east);
    unitSpawn(maya, sprite_0, 400, 0, -1300, north, none);
    unitFace(maya, south);
    unitSpawn(enemy1, sprite_b4, 464, 0, -344, north, none);
    unitFace(enemy1, north);
    unitSpawn(enemy2, sprite_b4, 105, 0, -550, north, none);
    unitFace(enemy2, south);
    unitSpawn(enemy3, sprite_b4, 737, 0, -148, north, none);
    unitFace(enemy3, east);
    unitSpawn(enemy4, sprite_b5, 552, 0, -552, north, none);
    unitFace(enemy4, north);
    unitSpawn(enemy5, sprite_b5, 354, 0, -63, north, none);
    unitFace(enemy5, west);
    unitSpawn(enemy6, sprite_b6, 338, 0, -448, north, none);
    unitFace(enemy6, west);
    unitSpawn(enemy7, sprite_b6, 740, 0, -412, north, none);
    unitFace(enemy7, north);
    unitSpawn(unit_4b, sprite_b7, 722, 0, -666, north, none);
    unitFace(unit_4b, north);
    unitSpawn(unit_4c, sprite_b7, 260, 0, -625, north, none);
    unitFace(unit_4c, west);
    unitSpawn(unit_4d, sprite_b7, 66, 0, -188, north, none);
    unitFace(unit_4d, west);
    unitColor(katsuya, rgb(128,64,32), 1);
    unitColor(maya, rgb(128,64,32), 1);
    unitColor(baofu, rgb(128,64,32), 1);
    unitColor(ulala, rgb(128,64,32), 1);
    unitColor(enemy1, rgb(128,64,32), 1);
    unitColor(enemy2, rgb(128,64,32), 1);
    unitColor(enemy3, rgb(128,64,32), 1);
    unitColor(enemy4, rgb(128,64,32), 1);
    unitColor(enemy5, rgb(128,64,32), 1);
    unitColor(enemy6, rgb(128,64,32), 1);
    unitColor(enemy7, rgb(128,64,32), 1);
    unitColor(unit_4b, rgb(128,64,32), 1);
    unitColor(unit_4c, rgb(128,64,32), 1);
    unitColor(unit_4d, rgb(128,64,32), 1);
    unitSpawn(npc1, sprite_118, 500, 0, -680, north, none);
    unitSpawn(npc2, sprite_118, 400, 0, -220, north, none);
    unitSpawn(npc3, sprite_119, 100, 0, -430, north, none);
    unitSpawn(npc4, sprite_119, 100, 0, -430, north, none);
    li(var_7, 0);
    call(NAKINAKI);
    ref_5e = cameraMoveTo(400, 0, -824, 180);
    call(MAYA_IDOU);
    delayClear();
    delayWait(20);
    call(KATUYA_IDOU);
    delayClear();
    delayWait(20);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    call(URARA_IDOU);
    delayClear();
    delayWait(10);
    call(PAOFU_IDOU);
    delayClear();
    delayWait(20);
    wait(ref_5e);
    ref_6f = cameraRotateTo(3, 30);
    wait(ref_6f);
    delayClear();
    delayWait(15);
    unitAnimationPlay(ulala, animation_1f, 1);
    ref_74 = bustupLoad(bustup_17);
    bustupWait(ref_74);
    ref_76 = bustupAlloc(ref_74, left, rgb(0,0,0));
    bustupFade(ref_76, rgb(128,0,0), 30);
    ref_78 = dialogAlloc();
    ref_79 = msgShow(msg_0);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]みっけ！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(maya, animation_28, 1);
    unitWait(maya);
    sync();
    wait(ref_79);
    dialogFree(ref_78);
    ref_7f = bustupFade(ref_76, rgb(0,0,0), 10);
    bustupWait(ref_7f);
    bustupFree(ref_76);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationHold(maya, animation_18, -1);
    delayClear();
    delayWait(60);
    ref_88 = bustupLoad(bustup_1);
    bustupWait(ref_88);
    ref_8a = bustupAlloc(ref_88, center, rgb(0,0,0));
    bustupFade(ref_8a, rgb(128,0,0), 30);
    ref_8c = dialogChoiceAlloc();
    ref_8d = msgShow(msg_1);
/***************************************
[tab]みっけ！
[choice(2)]もう大丈夫。みんな、早く屋上に逃げて！！
みんな、ケツまくって屋上まで逃げるのよ！！
[end_choice][clear]
***************************************/
    wait(ref_8d);
    dialogFree(ref_8c);
    ref_90 = bustupFade(ref_8a, rgb(0,0,0), 10);
    bustupWait(ref_90);
    bustupFree(ref_8a);
    unitAnimationStop(maya);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_0, 1);
    choiceGetResult(var_5);
    bne(var_5, 0, label_9b);
    b(label_af);
    b(label_9e);
  label_9b:
    bne(var_5, 1, label_9e);
    b(label_9e);
    b(label_9e);
  label_9e:
    unitAnimationPlay(ulala, animation_3, 1);
    unitAnimationPlay(katsuya, animation_1, 1);
    unitAnimationPlay(baofu, animation_1, 1);
    unitWait(ulala);
    unitWait(katsuya);
    unitWait(baofu);
    ref_a4 = bustupLoad(bustup_25);
    bustupWait(ref_a4);
    ref_a6 = bustupAlloc(ref_a4, left, rgb(0,0,0));
    bustupFade(ref_a6, rgb(128,0,0), 30);
    ref_a8 = dialogAlloc();
    ref_a9 = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]天野君…[delay(30)]
[tab]ケツまくってって…
[wait][clear]
***************************************/
    wait(ref_a9);
    dialogFree(ref_a8);
    ref_ac = bustupFade(ref_a6, rgb(0,0,0), 10);
    bustupWait(ref_ac);
    bustupFree(ref_a6);
  label_af:
    li(var_7, 1);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(enemy2, animation_0, 1);
    unitAnimationPlay(enemy3, animation_0, 1);
    unitAnimationPlay(enemy4, animation_0, 1);
    unitAnimationPlay(enemy5, animation_0, 1);
    unitAnimationPlay(enemy6, animation_0, 1);
    unitAnimationPlay(enemy7, animation_0, 1);
    unitAnimationPlay(unit_4b, animation_0, 1);
    unitAnimationPlay(unit_4c, animation_0, 1);
    unitAnimationPlay(unit_4d, animation_0, 1);
    unitWait(enemy1);
    unitWait(enemy2);
    unitWait(enemy3);
    unitWait(enemy4);
    unitWait(enemy5);
    unitWait(enemy6);
    unitWait(enemy7);
    unitWait(unit_4b);
    unitWait(unit_4c);
    unitWait(unit_4d);
    delayClear();
    delayWait(5);
    unitFaceUnit(enemy1, maya);
    unitFaceUnit(enemy2, maya);
    unitFaceUnit(enemy3, maya);
    unitFaceUnit(enemy4, maya);
    unitFaceUnit(enemy5, maya);
    unitFaceUnit(enemy6, maya);
    unitFaceUnit(enemy7, maya);
    unitFaceUnit(unit_4b, maya);
    unitFaceUnit(unit_4c, maya);
    unitFaceUnit(unit_4d, maya);
    unitAnimationPlay(maya, animation_0, 1);
    unitWait(maya);
    delayClear();
    delayWait(1);
    unitAnimationPlay(enemy1, animation_6, 1);
    unitAnimationPlay(enemy2, animation_6, 1);
    unitAnimationPlay(enemy3, animation_6, 1);
    unitAnimationPlay(enemy4, animation_6, 1);
    unitAnimationPlay(enemy5, animation_6, 1);
    unitAnimationPlay(enemy6, animation_6, 1);
    unitAnimationPlay(enemy7, animation_6, 1);
    unitAnimationPlay(unit_4b, animation_6, 1);
    unitAnimationPlay(unit_4c, animation_6, 1);
    unitAnimationPlay(unit_4d, animation_6, 1);
    unitWait(enemy1);
    unitWait(enemy2);
    unitWait(enemy3);
    unitWait(enemy4);
    unitWait(enemy5);
    unitWait(enemy6);
    unitWait(enemy7);
    unitWait(unit_4b);
    unitWait(unit_4c);
    unitWait(unit_4d);
    delayClear();
    delayWait(10);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(enemy2, animation_0, 1);
    unitAnimationPlay(enemy3, animation_0, 1);
    unitAnimationPlay(enemy4, animation_0, 1);
    unitAnimationPlay(enemy5, animation_0, 1);
    unitAnimationPlay(enemy6, animation_0, 1);
    unitAnimationPlay(enemy7, animation_0, 1);
    unitAnimationPlay(unit_4b, animation_0, 1);
    unitAnimationPlay(unit_4c, animation_0, 1);
    unitAnimationPlay(unit_4d, animation_0, 1);
    unitWait(enemy1);
    unitWait(enemy2);
    unitWait(enemy3);
    unitWait(enemy4);
    unitWait(enemy5);
    unitWait(enemy6);
    unitWait(enemy7);
    unitWait(unit_4b);
    unitWait(unit_4c);
    unitWait(unit_4d);
    delayClear();
    delayWait(10);
    unitMove(unit_4c, 400, -1300, face_north, medium);
    call(MAYAMW);
    delayClear();
    delayWait(20);
    unitMove(enemy6, 400, -1300, face_north, medium);
    unitMove(unit_4b, 701, -557, face_south, medium);
    call(URARAMW);
    call(KATUYAMW);
    call(PAOFUMW);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 3, false);
    screenFadeOuter(rgb(255,255,255), 3, false);
    unitMove(enemy4, 341, -600, face_east, medium);
    delayClear();
    delayWait(10);
    unitMove(enemy2, 261, -595, face_west, medium);
    unitWait(enemy4);
    unitFace(enemy4, east);
    unitWait(enemy2);
    unitMove(enemy4, 400, -1177, face_north, medium);
    unitMove(enemy2, 400, -1177, face_north, medium);
    unitMove(enemy1, 400, -1177, face_north, medium);
    delayClear();
    delayWait(2);
    unitMove(enemy3, 400, -1177, face_north, medium);
    delayClear();
    delayWait(2);
    unitMove(enemy5, 400, -1177, face_north, medium);
    delayClear();
    delayWait(2);
    unitMove(enemy7, 400, -1177, face_north, medium);
    delayClear();
    delayWait(2);
    screenFadeWait(inner);
    screenFadeWait(outer);
    bitSet(EBIT_E0022);
    bitClear(EBIT_ROOM1);
    dngLoad2(aerospace_museum-7);
}

function MAYA_IDOU()
{
    unitMove(maya, 390, -835, face_east, medium);
    unitWait(maya);
    unitFace(maya, south);
}

function KATUYA_IDOU()
{
    unitMove(katsuya, 294, -924, face_east, medium);
    unitWait(katsuya);
    unitFace(katsuya, south);
}

function URARA_IDOU()
{
    unitMove(ulala, 509, -1045, face_south, medium);
    unitWait(ulala);
    unitFace(ulala, south);
}

function PAOFU_IDOU()
{
    unitMove(baofu, 285, -1045, face_south, medium);
    unitWait(baofu);
    unitFace(baofu, south);
}

function NAKINAKI()
{
  label_138:
    unitAnimationPlay(enemy1, animation_10, 1);
    unitAnimationPlay(enemy2, animation_10, 1);
    unitAnimationPlay(enemy3, animation_10, 1);
    unitAnimationPlay(enemy4, animation_10, 1);
    unitAnimationPlay(enemy5, animation_10, 1);
    unitAnimationPlay(enemy6, animation_10, 1);
    unitAnimationPlay(enemy7, animation_10, 1);
    unitAnimationPlay(unit_4b, animation_10, 1);
    unitAnimationPlay(unit_4c, animation_10, 1);
    unitAnimationPlay(unit_4d, animation_10, 1);
    unitWait(enemy1);
    unitWait(enemy2);
    unitWait(enemy3);
    unitWait(enemy4);
    unitWait(enemy5);
    unitWait(enemy6);
    unitWait(enemy7);
    unitWait(unit_4b);
    unitWait(unit_4c);
    unitWait(unit_4d);
    bez(var_7, label_138);
}

function MAYAMW()
{
    unitMove(maya, 610, -826, face_east, reverse);
    unitWait(maya);
    unitFace(maya, east);
}

function URARAMW()
{
    unitMove(ulala, 609, -1045, face_east, reverse);
    unitWait(ulala);
    unitFace(ulala, east);
}

function KATUYAMW()
{
    unitMove(katsuya, 194, -924, face_west, reverse);
    unitWait(katsuya);
    unitFace(katsuya, west);
}

function PAOFUMW()
{
    unitMove(baofu, 185, -1045, face_west, reverse);
    unitWait(baofu);
    unitFace(baofu, west);
}
