
msg_0:
[color(yellow)]パオフゥ[color(white)]
[tab]………！！
[sync][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ちょ…どこいくのよぉ！？
[sync][wait][clear][end]

msg_2:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]お前ぇの三下なら、
[tab]皆はらわたブチまけてくたばってるぜぇ。
[sync][wait][clear][end]

msg_3:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]いいか、俺は自由だ…
[tab]直に殺しに行くからよぉ…
[tab]クソ親父によろしく伝えとけ！
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]目的はなんだ！？
[end]

msg_5:
[tab]殺しを続ける事か！？[tab]父親への復讐か！？
[sync][wait][clear][end]

msg_6:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]ヒャハ！[tab]殺しはよぉ、昔は好きでやってたが、
[tab]今は街の人間が電話かけてくっからやってる
[tab]だけだぜぇ…
[sync][wait][clear][end]

msg_7:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]なあ？
[sync][wait][clear][end]

msg_8:
[color(yellow)]うらら[color(white)]
[tab]………
[sync][wait][clear][end]

msg_9:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]俺の本当の役目はよぉ…間違いを正す事なんだよ。
[end]

msg_10:
[tab]「こっち側」は間違いで、
[tab]「向こう側」が正しいんだ。
[sync][wait][clear][end]

msg_11:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]クソ親父は、そこんとこがわかっちゃいねぇ…
[end]

msg_12:
[tab]お前なら、わかんだろ？
[sync][wait][clear][end]

msg_13:
[color(yellow)]舞耶[color(white)]
[tab]………
[sync][wait][clear][end]

msg_14:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]チッ…いつまでもバックれてんじゃねぇぞぉ！？
[sync][wait][clear][end]

msg_15:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]思い出させてやるからよぉ…
[end]

msg_16:
[tab]コイツに食われなかったら
[tab]空の科学館まで来やがれぇ！！
[sync][wait][clear][end]

msg_17:
[color(yellow)]克哉[color(white)]
[tab]待て、須藤！！
[sync][wait][clear][end]
