
msg_0:
[color(yellow)]水野編集長[color(white)]
[tab]今日はどうも、
[tab]わざわざご足労頂いてありがとうございました。
[sync][wait][clear][end]

msg_1:
[color(yellow)]水野編集長[color(white)]
[tab]天野！[tab]あなた一体どこをフラフラしてたの！？
[tab]あなたがいつまでたっても連絡よこさないから、
[tab]私がこうして、千鶴さんにお願いして…
[sync][wait][clear][end]

msg_2:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]まぁ、いいじゃありませんか。
[sync][wait][clear][end]

msg_3:
[color(yellow)]石神[tab]千鶴（いしがみ[tab]ちづる）[color(white)]
[color(green)][tab]「ワンロン千鶴」の名で時の人となった、
[tab]ワンロン占いの美人占い師。[color(white)]
[sync][wait][clear][end]

msg_4:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]面白い相をしてるわね…
[tab]私が占ってあげるわ。
[sync][wait][clear][end]

msg_5:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]あなた…
[tab]自分が自分でないような、そんな気がしてるわね？
[tab]自分より年下の男の事で悩んでる…
[sync][wait][clear][end]

msg_6:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]ねぇあなた、生きていて楽しい？
[tab]生まれてきてよかった？
[sync][wait][clear][end]

msg_7:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]この世はね、苦行のための世界なの。
[tab]輪廻転生の輪の中で、永遠に生きる苦しみを
[tab]背負わされた、罪人の世界…
[sync][wait][clear][end]

msg_8:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]前世のあなたは、一体どこにいたのかしら。
[tab]過去？[tab]違う国？[tab]それとも…違う世界…
[sync][wait][clear][end]

msg_9:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]人は繋がってるの。
[tab]過去だけじゃなく、別の世界の自分ともね…
[tab]あなた…変わるわよ。この世界と一緒にね…
[sync][wait][clear][end]

msg_10:
[color(yellow)]水野編集長[color(white)]
[tab]感謝しなさい。
[tab]千鶴さん直々に占ってもらえるなんて、
[tab]そうはないんだから。
[sync][wait][clear][end]

msg_11:
[color(yellow)]ワンロン千鶴[color(white)]
[tab]じゃあ、私はこれで。
[sync][wait][clear][end]

msg_12:
[color(yellow)]水野編集長[color(white)]
[tab]まったく、あなたって人は…
[tab]まぁいいわ。取材の結果をまとめて報告して頂戴。
[tab]さぁ早く！
[sync][wait][clear][end]

msg_13:
[color(yellow)]水野編集長[color(white)]
[tab]報告書はどうしたの！？
[tab]早く仕事なさい！
[tab]本当に手のかかる子ね！！
[sync][wait][clear][end]

msg_14:
[color(yellow)]クーレストの売り上げ表[color(white)]
[tab][color(green)]販売部数が落ち込んでいる。
[tab]編集長のイライラの原因らしい。
[color(white)]
[sync][wait][clear][end]

msg_15:
[color(yellow)]マガジンラック[color(white)]
[tab][color(green)]クーレストのバックナンバーがある。
[color(white)]
[sync][wait][clear][end]
