function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    ref_2 = spriteLoad(sprite_13);
    wait(ref_2);
    ref_4 = spriteLoad(sprite_14);
    wait(ref_4);
    unitSpawn(baofu, sprite_14, 160, -50, -200, east, none);
    unitFace(baofu, east);
    unitAnimationPlay(baofu, animation_0, 1);
    cameraSet(northwest, 160, -50, -200);
    unitIdleOffAll();
    msgLocSet(100, 110);
    ref_c = msgShow(msg_0);
/***************************************
[tab]パオフゥのアジト

***************************************/
    wait(ref_c);
    delayClear();
    delayWait(180);
    ref_10 = msgShow(msg_1);
/***************************************
[clear]
***************************************/
    wait(ref_10);
    msgLocDefault();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(120);
    unitAnimationPlay(baofu, animation_1, 1);
    sndMusicPlay(sound_3112, 127);
    unitAnimationPlay(baofu, animation_2, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_3, 1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(baofu, animation_6, 1);
    delayClear();
    delayWait(60);
    ref_25 = dialogAlloc();
    ref_26 = msgShow(msg_2);
/***************************************
[color(yellow)]盗聴器からの声[color(white)]
[tab]私だ。[delay(30)]
[tab]…………[delay(60)]
[tab]そうか…アレがな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_26);
    ref_29 = msgShow(msg_3);
/***************************************
[color(yellow)]盗聴器からの声[color(white)]
[tab]…構うな…生きているだけ無駄な男だ。[delay(60)]
[tab]…うむ………案ずるな、計画に支障はない。[delay(60)]
[tab]…うむ………処理はまかせたぞ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_29);
    dialogFree(ref_25);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_1, 1);
    delayClear();
    delayWait(30);
    ref_32 = bustupLoad(bustup_2e);
    bustupWait(ref_32);
    ref_34 = bustupAlloc(ref_32, left, rgb(0,0,0));
    bustupFade(ref_34, rgb(128,0,0), 30);
    ref_36 = dialogAlloc();
    ref_37 = msgShow(msg_4);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]須藤…竜蔵…
[tab]誰だ、一体誰と話してる…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_37);
    dialogFree(ref_36);
    ref_3b = bustupFade(ref_34, rgb(0,0,0), 10);
    bustupWait(ref_3b);
    bustupFree(ref_34);
    delayClear();
    delayWait(90);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndStop(sound_3112);
    eventLoad(event_a8);
}
