
msg_0:
[color(yellow)][tatsuya][color(white)]
[tab]淳を放せ…
[tab]そいつはもう、関係ない…
[sync][wait][clear][end]

msg_1:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]頼む、思い出してくれ…
[tab]ジョーカーは俺じゃねぇ…
[tab]貴方の方が相応しいんだ！
[sync][wait][clear][end]

msg_2:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]「向こう側」と同じように、俺達を導いてくれ…
[tab]俺は向こうの俺みてぇなヘマはしねぇ…！
[sync][wait][clear][end]

msg_3:
[color(yellow)]淳[color(white)]
[tab]フジバカマ…「あの日を思い出せ」って…
[end]

msg_4:
[tab]な…何を言ってるの…？
[tab]わからないよ…！
[sync][wait][clear][end]

msg_5:
[tab]な…[tatsuya]…！？
[choice(2)]デ、デジャ・ヴュ君！？
淳君、大丈夫！？
[end_choice][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]なんだって…！？
[end]

msg_7:
[tab]ま、まさか君が探してるデジャ・ヴュの少年って…
[sync][wait][clear][end]

msg_8:
[color(yellow)]うらら[color(white)]
[tab]こりゃ驚きだわ…
[end]

msg_9:
[tab]何がどうなってるわけ！？
[sync][wait][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]ちょ…こっちの背の高い子は誰なわけ？
[sync][wait][clear][end]

msg_11:
[color(yellow)]うらら[color(white)]
[tab]え～！？
[tab]これが、デジャ・ヴュの少年！？
[sync][wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]なんだって！？
[end]

msg_13:
[tab]一体、どういうことなんだ…！？
[sync][wait][clear][end]

msg_14:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]ヒャハ…来やがったなぁ、天野[tab]舞耶ぁ！！
[end]

msg_15:
[tab]この光景に見覚えがあるだろが…[delay(30)]
[tab]てめぇも早く思い出せぇ！！
[sync][wait][clear][end]

msg_16:
[color(yellow)][tatsuya][color(white)]
[tab]やめろ…！
[end]

msg_17:
[tab]何も考えるな…何も…なかったんだ…！
[sync][wait][clear][end]

msg_18:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]バァカ！
[tab]運命には逆らえねぇんだよぉ…
[end]

msg_19:
[tab]５・４・３…
[sync][wait][clear][end]

msg_20:
[color(yellow)][tatsuya][color(white)]
[tab]ハッ…！？
[end]

msg_21:
[tab]飛べ！！
[sync][wait][clear][end]

msg_22:
[color(yellow)][tatsuya][color(white)]
[tab]バカ…手を放せ…！
[sync][wait][clear][end]

msg_23:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]ヒャァァハハハ！
[tab]「向こう側」と同じだろぉ～？
[sync][wait][clear][end]

msg_24:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]まぁ、思い出したところでもう遅ぇ…
[tab]死ねや…
[sync][wait][clear][end]

msg_25:
[color(yellow)]淳[color(white)]
[tab]ダメだー！
[sync][wait][clear][end]

msg_26:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]うおおおおぉぉぉ！？
[tab]な、なぜだぁぁぁぁぁぁ…！
[sync][wait][clear][end]

msg_27:
[color(yellow)]淳[color(white)]
[tab]あ…あ…あ…
[sync][wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]気にするな…お前のせいじゃない…
[sync][wait][clear][end]

msg_29:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]！
[end]

msg_30:
[tab]お前今までどこにいた！？
[end]

msg_31:
[tab]これは一体どういうことなんだ！？
[sync][wait][clear][end]

msg_32:
[color(yellow)]パオフゥ[color(white)]
[tab]後にしろ。
[end]

msg_33:
[tab]ここからずらかるのが先だ。
[sync][wait][clear][end]

msg_34:
[color(yellow)]うらら[color(white)]
[tab]でも、どうやって逃げるのよぅ！？
[sync][wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]付いて来い…
[sync][wait][clear][end]

msg_36:
[color(yellow)]パオフゥ[color(white)]
[tab]おい、そんな飾り物が飛ぶと思って…
[sync][wait][clear][end]

msg_37:
[color(yellow)]パオフゥ[color(white)]
[tab]…噂か！？
[end]

msg_38:
[tab]噂でそいつが飛ぶんだな！？
[sync][wait][clear][end]

msg_39:
[color(yellow)]克哉[color(white)]
[tab]な…[tatsuya]…！？
[sync][wait][clear][end]
