
msg_0:
[color(yellow)]老刑事[color(white)]
[tab]また、ガイシャ周辺の聞き込みだとよ…
[tab]現場の俺達に任しときゃいいものを…
[sync][wait][clear][end]

msg_1:
[color(yellow)]若い刑事[color(white)]
[tab]また？
[tab]本当にそれで、ババ挙げられると思ってるのかねぇ
[tab]あの管理官殿は…
[sync][wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]おい…とんでもないことになってるぞ！
[sync][wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
[tab]やっぱりな…
[tab]ＴＶで流れた占いが噂になって、呪いした連中が
[tab]ＪＯＫＥＲになっちまったに違いねぇ…
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]警察はアテにならない…
[tab]今の捜査方針では、被害が増すだけだ…
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]へへ…随分弱気じゃねぇか…
[tab]まぁ、大人しく謹慎してな。
[sync][wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]そうは行くか…
[tab]見て見ぬふりをするぐらいなら、手帳を県に返す。
[tab]僕も行く。
[sync][wait][clear][end]

msg_7:
[color(yellow)]パオフゥ[color(white)]
[tab]勝手にしな…
[sync][wait][clear][end]

msg_8:
[color(yellow)]うららの声[color(white)]
[tab]マーヤ…早く…逃げて！
[tab]私が…変わっちゃう前に…！！
[tab]は…やく…
[sync][wait][clear][end]

msg_9:
[color(yellow)]パオフゥ[color(white)]
[tab]なんだとぉ…？
[tab]まさかあいつ…ＪＯＫＥＲ呪いをしてたんじゃ
[tab]あるめぇな！？
[sync][wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]そうだとしたら、芹沢君が殺人犯になるぞ…
[tab]狙われる相手の心当たりはないのか！？
[sync][wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]結婚詐欺か…詐欺に本名を使うはずもないしな…
[tab]会ったことは！？
[sync][wait][clear][end]

msg_12:
[color(yellow)]パオフゥ[color(white)]
[tab]なんでもいいから思い出してみな…
[sync][wait][clear][end]
