
msg_0:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]畜生…畜生…畜生畜生畜生畜生畜生畜生畜生畜生…[delay(30)]
[end]

msg_1:
[tab]顔がァ…また俺の顔がァァァ！！[delay(30)]
[end]

msg_2:
[tab]これも…これも運命だってぇのか！！[tab]ああ！？
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]違う…
[end]

msg_4:
[tab]運命なんて、決まった道筋は存在しない…
[end]

msg_5:
[tab]ヤツに…踊らされるな！
[sync][wait][clear][end]

msg_6:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]馬鹿野郎…みんな、間違ってるんだよぉ…[delay(30)]
[end]

msg_7:
[tab]お前も！[tab]そこの女も！[tab]クソ親父もだ！！
[end]

msg_8:
[tab]間違いは、正さなくちゃいけねぇだろが！！
[sync][wait][clear][end]

msg_9:
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]ヒャハ…！！[delay(30)][tab]電波だよ電波ァァ！！[delay(30)]
[end]

msg_10:
[tab]電波電波電波電波電波電波電波電波ァァァ！！[delay(30)]
[end]

msg_11:
[tab]電波からは、逃げられねぇぞぉぉぉ！！
[sync][wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[tab]みんな下がってろ…
[tab]こいつは…俺が倒す…
[sync][wait][clear][end]
