function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    sndMusicPlay(sound_3025, 127);
    cameraSet(southwest, 350, 0, -800);
    levelFootstepSet(sfx_19);
    ref_a = spriteLoad(sprite_ea);
    wait(ref_a);
    ref_c = spriteLoad(sprite_b);
    wait(ref_c);
    ref_e = spriteLoad(sprite_0);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_d);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_f);
    wait(ref_12);
    ref_14 = spriteLoad(sprite_13);
    wait(ref_14);
    ref_16 = spriteLoad(sprite_15);
    wait(ref_16);
    ref_18 = spriteLoad(sprite_6a);
    wait(ref_18);
    ref_1a = spriteLoad(sprite_c);
    wait(ref_1a);
    ref_1c = spriteLoad(sprite_f8);
    wait(ref_1c);
    unitSpawn(unit_67, sprite_ea, 650, 0, -345, west, none);
    unitSpawn(ulala, sprite_b, 430, 0, -270, south, none);
    unitAnimationPlay(ulala, animation_49, 1);
    sndMusicPlay(sound_312f, 127);
    op_ab(1, 255);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_28 = efctAuraLoad();
    wait(ref_28);
    sndMusicPlay(sound_3133, 127);
    objAnimRotate(obj_9, 0, -70, 0, 30, 0);
    ref_2c = objAnimRotate(obj_a, 0, 70, 0, 30, 0);
    wait(ref_2c);
    call(MAYA_TOJO);
    delayClear();
    delayWait(30);
    unitSpawn(makimura, sprite_6a, 300, 0, -980, south, fade);
    unitMove(makimura, 280, -820, face_south, medium);
    delayClear();
    delayWait(30);
    unitSpawn(baofu, sprite_13, 300, 0, -980, south, fade);
    unitAnimationPlay(baofu, animation_a, 1);
    unitWait(makimura);
    unitAnimationHold(makimura, animation_1b, 30);
    unitWait(makimura);
    unitMove(baofu, 280, -870, face_south, medium);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_1f, 1);
    unitAnimationPlay(makimura, animation_4, 1);
    unitSpawn(katsuya, sprite_d, 300, 0, -980, south, fade);
    unitAnimationPlay(katsuya, animation_a, 1);
    ref_40 = sndLoad(sound_301d);
    wait(ref_40);
    call(PAOFU_SAGI);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_44 = bustupLoad(bustup_21);
    bustupWait(ref_44);
    ref_46 = bustupAlloc(ref_44, left, rgb(0,0,0));
    bustupFade(ref_46, rgb(128,0,0), 30);
    ref_48 = dialogAlloc();
    ref_49 = msgShow(msg_0);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]芹沢君、大丈夫か！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_49);
    dialogFree(ref_48);
    ref_4d = bustupFade(ref_46, rgb(0,0,0), 10);
    bustupWait(ref_4d);
    bustupFree(ref_46);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(30);
    ref_53 = dialogAlloc();
    ref_54 = msgShow(msg_1);
/***************************************
[color(yellow)]うずくまったうらら[color(white)]
[tab]グッ……来ない……で……
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_54);
    dialogFree(ref_53);
    waitFunc(PAOFU_SAGI);
    call(KATUYA_IDO);
    call(PAOFU_IDO);
    call(SAGI_IDO);
    delayClear();
    delayWait(60);
    ref_5e = cameraMoveTo(380, 0, -380, 1);
    ref_5f = cameraRotateTo(7, 1);
    wait(ref_5e);
    wait(ref_5f);
    unitAnimationPlay(ulala, animation_49, 1);
    waitFunc(KATUYA_IDO);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_14, 1);
    ref_67 = bustupLoad(bustup_21);
    bustupWait(ref_67);
    ref_69 = bustupAlloc(ref_67, left, rgb(0,0,0));
    bustupFade(ref_69, rgb(128,0,0), 30);
    ref_6b = dialogAlloc();
    ref_6c = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]牧村[tab]洋一は確保したよ。

***************************************/
    wait(ref_6c);
    unitAnimationPlay(katsuya, animation_e, 1);
    ref_6f = msgShow(msg_3);
/***************************************
[tab]こいつの罪は法が裁く。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6f);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_73 = msgShow(msg_4);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]こんな男のために、
[tab]君が人生を台無しにする必要はないんだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_73);
    dialogFree(ref_6b);
    ref_77 = bustupFade(ref_69, rgb(0,0,0), 10);
    bustupWait(ref_77);
    bustupFree(ref_69);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_d, 1);
    ref_7e = bustupLoad(bustup_2d);
    bustupWait(ref_7e);
    ref_80 = bustupAlloc(ref_7e, left, rgb(0,0,0));
    bustupFade(ref_80, rgb(128,0,0), 30);
    ref_82 = dialogAlloc();
    ref_83 = msgShow(msg_5);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]殺すにゃ値しねぇってこった…

***************************************/
    wait(ref_83);
    ref_85 = msgShow(msg_6);
/***************************************
[tab]コイツの余罪なら１０年はくだらねぇ。

***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    unitWait(baofu);
    wait(ref_85);
    unitAnimationHold(baofu, animation_11, -1);
    ref_8a = msgShow(msg_7);
/***************************************
[tab]だからよ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_8a);
    dialogFree(ref_82);
    ref_8e = bustupFade(ref_80, rgb(0,0,0), 10);
    bustupWait(ref_8e);
    bustupFree(ref_80);
    ref_91 = dialogAlloc();
    ref_92 = msgShow(msg_8);
/***************************************
[color(yellow)]うずくまったうらら[color(white)]
[tab]マー…ヤ…は……いる…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_92);
    dialogFree(ref_91);
    unitAnimationStop(baofu);
    delayClear();
    delayWait(30);
    ref_99 = bustupLoad(bustup_3);
    bustupWait(ref_99);
    ref_9b = bustupAlloc(ref_99, center, rgb(0,0,0));
    bustupFade(ref_9b, rgb(128,0,0), 30);
    ref_9d = dialogChoiceAlloc();
    ref_9e = msgShow(msg_9);
/***************************************
[tab]マー…ヤ…は……いる…？
[choice(2)]う、うらら…？
私はここよ、うらら！
[end_choice][clear]
***************************************/
    wait(ref_9e);
    dialogFree(ref_9d);
    ref_a1 = bustupFade(ref_9b, rgb(0,0,0), 10);
    bustupWait(ref_a1);
    bustupFree(ref_9b);
    delayClear();
    delayWait(30);
    cameraMoveTo(350, 0, -280, 30);
    screenColorAdjust(0.5, 0.5, 0.61328125);
    choiceGetResult(var_0);
    bne(var_0, 0, label_ac);
    b(label_af);
    b(label_af);
  label_ac:
    bne(var_0, 1, label_af);
    b(label_106);
    b(label_af);
  label_af:
    unitMove(maya, 430, -430, face_south, slow);
    unitWait(maya);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(60);
    call(SOUND);
    unitAnimationPlay(ulala, animation_12, 1);
    unitWait(ulala);
    call(MAYA_ODOROKU);
    call(KATUYA_ODOROKU);
    call(PAOFU_ODOROKU);
    call(SAGI_ODOROKU);
    waitFunc(MAYA_ODOROKU);
    ref_bc = bustupLoad(bustup_20);
    bustupWait(ref_bc);
    ref_be = bustupAlloc(ref_bc, right, rgb(0,0,0));
    bustupFade(ref_be, rgb(128,0,0), 30);
    ref_c0 = dialogAlloc();
    ref_c1 = msgShow(msg_10);
/***************************************
[color(yellow)]ＪＯＫＥＲうらら[color(white)]
[tab]ようやくわかったのかい？

***************************************/
    ref_c2 = sndVoicePlay(sound_93, 127);
    sndWaitStart();
    unitFace_2(ulala, north);
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_c1);
    ref_c7 = msgShow(msg_11);
/***************************************
[tab]私が殺したいのは、お前なんだよ、マーヤ♥

***************************************/
    delayClear();
    delayWait(210);
    unitAnimationHold(ulala, animation_19, -1);
    wait(ref_c7);
    ref_cc = msgShow(msg_12);
/***************************************
[tab]あはははははは！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_23, 1);
    wait(ref_c2);
    sync();
    wait(ref_cc);
    dialogFree(ref_c0);
    ref_d5 = bustupFade(ref_be, rgb(0,0,0), 10);
    bustupWait(ref_d5);
    bustupFree(ref_be);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_c);
    sndMusicPlay(sound_3131, 127);
    unitAnimationHold(ulala, animation_6, -1);
    unitAura(ulala, true);
    delayClear();
    delayWait(30);
    ref_df = unitEfctPersona(ulala, unit_62, sprite_f8);
    cameraFollow(unit_62);
    wait(ref_df);
    unitAnimationPlay(maya, animation_41, 1);
    unitAnimationHold(baofu, animation_4, -1);
    unitAnimationPlay(katsuya, animation_d, 1);
    ref_e5 = bustupLoad(bustup_25);
    bustupWait(ref_e5);
    ref_e7 = bustupAlloc(ref_e5, left, rgb(0,0,0));
    bustupFade(ref_e7, rgb(128,0,0), 30);
    ref_e9 = dialogAlloc();
    ref_ea = msgShow(msg_13);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ＪＯＫＥＲ！？
[tab]成長…してるのか…！？
[sync][wait][clear]
***************************************/
    ref_eb = sndVoicePlay(sound_c6, 127);
    sndWaitStart();
    wait(ref_eb);
    sync();
    wait(ref_ea);
    dialogFree(ref_e9);
    ref_f1 = bustupFade(ref_e7, rgb(0,0,0), 10);
    bustupWait(ref_f1);
    bustupFree(ref_e7);
    ref_f4 = bustupLoad(bustup_2d);
    bustupWait(ref_f4);
    ref_f6 = bustupAlloc(ref_f4, left, rgb(0,0,0));
    bustupFade(ref_f6, rgb(128,0,0), 30);
    ref_f8 = dialogAlloc();
    ref_f9 = msgShow(msg_14);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]やれやれ…
[tab]「女は魔物」たぁ、よく言ったもんだぜ…
[tab]いっちょ、目ぇ覚まさせてやるか…
[sync][wait][clear]
***************************************/
    ref_fa = sndVoicePlay(sound_80, 127);
    sndWaitStart();
    unitAnimationStop(baofu);
    unitAnimationHold(baofu, animation_12, -1);
    wait(ref_fa);
    sync();
    wait(ref_f9);
    dialogFree(ref_f8);
    ref_102 = bustupFade(ref_f6, rgb(0,0,0), 10);
    bustupWait(ref_102);
    bustupFree(ref_f6);
    b(label_16c);
  label_106:
    bitSet(EBIT_KOKOYO);
    unitMove(maya, 400, -350, face_south, slow);
    unitWait(maya);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(60);
    call(SOUND);
    unitAnimationPlay(ulala, animation_12, 1);
    unitWait(ulala);
    unitAnimationHold(maya, animation_21, -1);
    call(KATUYA_ODOROKU);
    call(PAOFU_ODOROKU);
    call(SAGI_ODOROKU);
    delayClear();
    delayWait(30);
    unitFace_2(ulala, north);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_b);
    unitAnimationHold(ulala, animation_1c, 30);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3130, 127);
    unitAnimationStop(maya);
    unitAnimationPlay(maya, animation_47, 1);
    unitJumpTo(maya, 400, 0, -480, 10, 0);
    unitWait(maya);
    unitAnimationPlay(maya, animation_37, 1);
    delayClear();
    delayWait(30);
    ref_123 = bustupLoad(bustup_20);
    bustupWait(ref_123);
    ref_125 = bustupAlloc(ref_123, right, rgb(0,0,0));
    bustupFade(ref_125, rgb(128,0,0), 30);
    ref_127 = dialogAlloc();
    ref_128 = msgShow(msg_15);
/***************************************
[color(yellow)]ＪＯＫＥＲうらら[color(white)]
[tab]バーカ…まだわからないのかい？

***************************************/
    ref_129 = sndVoicePlay(sound_92, 127);
    sndWaitStart();
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_128);
    ref_12d = msgShow(msg_16);
/***************************************
[tab]私が殺したいのは、お前なんだよマーヤ！

***************************************/
    delayClear();
    delayWait(210);
    unitAnimationPlay(maya, animation_36, 1);
    unitAnimationHold(ulala, animation_19, -1);
    wait(ref_12d);
    ref_133 = msgShow(msg_17);
/***************************************
[tab]あはははははは！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_23, 1);
    wait(ref_129);
    sync();
    wait(ref_133);
    dialogFree(ref_127);
    ref_13c = bustupFade(ref_125, rgb(0,0,0), 10);
    bustupWait(ref_13c);
    bustupFree(ref_125);
    unitAnimationPlay(ulala, animation_a, 1);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_c);
    unitAnimationHold(ulala, animation_6, -1);
    sndMusicPlay(sound_3131, 127);
    unitAura(ulala, true);
    delayClear();
    delayWait(30);
    ref_147 = unitEfctPersona(ulala, unit_62, sprite_f8);
    cameraFollow(unit_62);
    wait(ref_147);
    unitAnimationHold(baofu, animation_4, -1);
    unitAnimationPlay(katsuya, animation_d, 1);
    ref_14c = bustupLoad(bustup_25);
    bustupWait(ref_14c);
    ref_14e = bustupAlloc(ref_14c, left, rgb(0,0,0));
    bustupFade(ref_14e, rgb(128,0,0), 30);
    ref_150 = dialogAlloc();
    ref_151 = msgShow(msg_18);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ＪＯＫＥＲ！？
[tab]成長…してるのか…！？
[sync][wait][clear]
***************************************/
    ref_152 = sndVoicePlay(sound_c6, 127);
    sndWaitStart();
    wait(ref_152);
    sync();
    wait(ref_151);
    dialogFree(ref_150);
    ref_158 = bustupFade(ref_14e, rgb(0,0,0), 10);
    bustupWait(ref_158);
    bustupFree(ref_14e);
    ref_15b = bustupLoad(bustup_2d);
    bustupWait(ref_15b);
    ref_15d = bustupAlloc(ref_15b, left, rgb(0,0,0));
    bustupFade(ref_15d, rgb(128,0,0), 30);
    ref_15f = dialogAlloc();
    ref_160 = msgShow(msg_19);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]「女は魔物」か…やだねぇ…
[tab]しゃーねぇ…
[tab]いっちょ、目ぇ覚まさせてやるか…
[sync][wait][clear]
***************************************/
    ref_161 = sndVoicePlay(sound_81, 127);
    sndWaitStart();
    unitAnimationStop(baofu);
    unitAnimationHold(baofu, animation_12, -1);
    wait(ref_161);
    sync();
    wait(ref_160);
    dialogFree(ref_15f);
    ref_169 = bustupFade(ref_15d, rgb(0,0,0), 10);
    bustupWait(ref_169);
    bustupFree(ref_15d);
  label_16c:
    unitAnimationStop(baofu);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    op_ac();
    sndStop(sound_312f);
    sndMusicPlay(sound_3132, 127);
    encounterLoad(encounter_4);
}

function MAYA_TOJO()
{
    unitSpawn(maya, sprite_0, 300, 0, -980, south, fade);
    unitMove(maya, 430, -590, face_south, medium);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
}

function PAOFU_SAGI()
{
    unitAnimationPlay(baofu, animation_f, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(makimura, animation_1, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_2, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_1, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_0, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_3, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_4, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_3, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_0, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_1, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_2, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_1, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_0, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_3, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_4, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_3, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(makimura, animation_0, 1);
    unitAnimationPlay(makimura, animation_6, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_1d, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_a, 1);
}

function PAOFU_IDO()
{
    unitMove(baofu, 220, -820, face_south, medium);
    unitWait(baofu);
    unitMove(baofu, 270, -350, face_west, medium);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
}

function KATUYA_IDO()
{
    unitMove(katsuya, 580, -500, face_south, medium);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_3133, 127);
    objAnimRotate(obj_9, 0, 70, 0, 30, 0);
    ref_1c5 = objAnimRotate(obj_a, 0, -70, 0, 30, 0);
    wait(ref_1c5);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_a, 1);
}

function SAGI_IDO()
{
    unitAnimationPlay(makimura, animation_0, 1);
    delayClear();
    delayWait(30);
    unitMove(makimura, 360, -620, face_south, medium);
    unitWait(makimura);
    unitAnimationPlay(makimura, animation_6, 1);
}

function MAYA_ODOROKU()
{
    unitAnimationPlay(maya, animation_21, 1);
    unitWait(maya);
    unitMove(maya, 430, -520, face_south, reverse);
    unitWait(maya);
    unitAnimationHold(maya, animation_21, -1);
}

function KATUYA_ODOROKU()
{
    unitAnimationHold(katsuya, animation_21, 60);
    unitWait(katsuya);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
}

function PAOFU_ODOROKU()
{
    unitAnimationHold(baofu, animation_21, 60);
    unitWait(baofu);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
}

function SAGI_ODOROKU()
{
    unitAnimationHold(makimura, animation_1c, 60);
    unitWait(makimura);
    unitAnimationPlay(makimura, animation_2e, 1);
}

function SOUND()
{
    sndVolumeFadeOff(sound_3025, 120);
    delayClear();
    delayWait(90);
    sndMusicPlay(sound_301d, 127);
}
