
msg_0:
[color(yellow)]パオフゥ[color(white)]
[tab]おい…どうした？
[sync][wait][clear][end]

msg_1:
[color(yellow)]克哉[color(white)]
[tab]え…？
[tab]会ったことはないが顔を知っている気がするって？
[sync][wait][clear][end]

msg_2:
[color(yellow)]パオフゥ[color(white)]
[tab]どういう意味だ…？
[sync][wait][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]また、例のデジャ・ヴュか…
[tab]とにかく、その詐欺師を確保しよう。
[tab]芹沢君に罪を犯させるわけにはいかない。
[sync][wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
[tab]よくわからねぇが、顔見りゃわかるんだな？
[tab]歩いて探すしかねぇか…
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]いや…その前に、平坂に寄るか…
[tab]どこぞの赤提灯の女将が、人探しを斡旋してるって
[tab]噂だ。手がかりがあるかも知れねぇぞ…
[sync][wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]ＪＯＫＥＲが増える…
[tab]一人でも手に負えないというのに厄介な…
[sync][wait][clear][end]

msg_7:
[color(yellow)]パオフゥ[color(white)]
[tab]先に平坂区に行こうや。
[tab]人探し屋を探すんだよ。
[sync][wait][clear][end]

msg_8:
[color(yellow)]生真面目な警察官[color(white)]
[tab]ああ、克哉さんのお知り合いの方ですか。
[tab]克哉さんほど、真面目で正義感のある人は、
[tab]この署内にもいませんよ。少し心配性ですが…
[wait][clear][end]

msg_9:
[color(yellow)]生真面目な警察官[color(white)]
[tab]科学館で何があったんですか？
[tab]克哉さんはびしょ濡れで戻ってくるし…
[tab]なんで自分達は待機のままなのでしょう？
[wait][clear][end]

msg_10:
[color(yellow)]生真面目な警察官[color(white)]
[tab]さっきから電話が鳴りっぱなしですよ！
[tab]どれもこれも、突然人が暴れ出したって！
[tab]これじゃいくら警官がいたって足りませんよ！
[wait][clear][end]

msg_11:
[color(yellow)]生真面目な警察官[color(white)]
[tab]最近街で、暴行事件が多発しているのですが、
[tab]まだ被疑者は一人も捕まっておりません。
[tab]その…何とも妙でして…
[wait][clear][color(yellow)]生真面目な警察官[color(white)]
[tab]通報を受け現場に駆けつけたときには、
[tab]もう騒ぎは収まってて、被疑者も消えてるんです。
[tab]目撃者の話では誰かが連れ去ったようなのですが
[wait][clear][end]

msg_12:
[color(yellow)]色白な警察官[color(white)]
[tab]最近は気味の悪い事件が多くて嫌になります。
[tab]特に殺人事件など、目を背けたくなるような
[tab]惨忍な手口で…あ、いや、失礼しました。
[wait][clear][end]

msg_13:
[color(yellow)]色白な警察官[color(white)]
[tab]しかし…あれが人間の仕業でしょうか？
[tab]少し前までは、例え法を犯していても、
[tab]相手は人間であると、認識できたのに…
[wait][clear][end]

msg_14:
[color(yellow)]色白な警察官[color(white)]
[tab]克哉さん、戻ってくるなり、
[tab]署長室に走って行きましたよ。
[tab]あの様子じゃまた衝突しそうだ…
[wait][clear][end]

msg_15:
[color(yellow)]色白な警察官[color(white)]
[tab]無闇に外出しないで下さい。
[tab]今、あちこちでＪＯＫＥＲ事件が発生しています。
[tab]いつ何時犯人が現れるとも限りませんから！
[wait][clear][end]

msg_16:
[color(yellow)]色白な警察官[color(white)]
[tab]最近は誘拐事件まで多発しているようですよ。
[tab]目撃者の話では、黒服の男達が連れ去ったとか…
[tab]組織的な犯行でしょうか。
[wait][clear][end]

msg_17:
[color(yellow)]ベテラン警察官[color(white)]
[tab]克哉は、ああ見えてもまだ若いんだ。
[tab]なのに不出来な弟の為に、限られた給金から
[tab]学費を捻出し、生活の面倒まで見てやってる。
[wait][clear][color(yellow)]ベテラン警察官[color(white)]
[tab]敏腕だの、堅物だのと言われているが、
[tab]結局アイツは、自分を犠牲にして、
[tab]何かを必死に守ってる。一番人間臭いヤツさ。
[wait][clear][end]

msg_18:
[color(yellow)]ベテラン警察官[color(white)]
[tab]現外務大臣の須藤[tab]竜蔵は知っているな？
[tab]何かと黒い噂の絶えない御仁だ。
[tab]最近克哉は、その尻尾を押さえようと必死でな。
[wait][clear][color(yellow)]ベテラン警察官[color(white)]
[tab]いつもは冷静沈着を売りにしてるようなヤツが、
[tab]竜蔵の事となると目の色変えて奔走する…
[tab]正義感が強いってだけで、ああなれるもんかな？
[wait][clear][end]

msg_19:
[color(yellow)]ベテラン警察官[color(white)]
[tab]ちっ、管理官のやつ、捜査本部しきっときながら、
[tab]こっちにゃまるで情報まわしやがらねえ！
[tab]俺ら所轄じゃアテにならないってのか！
[wait][clear][end]

msg_20:
[color(yellow)]ベテラン警察官[color(white)]
[tab]どうも捜査本部の動きがヘンだな…
[tab]的外れな捜査を繰り返して、
[tab]わざとここら一帯を手薄にしているような…
[wait][clear][end]

msg_21:
[color(yellow)]新米警察官[color(white)]
[tab]くふぅ…自分も頑張って早く刑事になりたいッス！
[tab]そして克哉さんのように、バリバリ働いて、
[tab]婦警にモテモテになりたいッス。
[wait][clear][end]

msg_22:
[color(yellow)]新米警察官[color(white)]
[tab]だけど克哉さんって彼女とかいないんスよね。
[tab]やっぱ、仕事が恋人なんスかね。
[wait][clear][end]

msg_23:
[color(yellow)]新米警察官[color(white)]
[tab]不思議ッス。科学館が燃えること、
[tab]前に夢で見た気がするッス。
[tab]まさか正夢というヤツじゃ…
[wait][clear][end]

msg_24:
[color(yellow)]新米警察官[color(white)]
[tab]い、いや、だとしたら、
[tab]この警察署も燃えているはずッス。
[tab]や…やっぱ、何かの勘違いッス。
[wait][clear][end]

msg_25:
[color(yellow)]新米警察官[color(white)]
[tab]そ…そりゃ、自分達はノンキャリですけど、
[tab]少しは捜査に参加したいッスよ！
[tab]あ…あの管理官じゃ、やっぱダメッス！！
[wait][clear][end]

msg_26:
[color(yellow)]新米警察官[color(white)]
[tab]さっき署長がコソコソと外に出て行くの見たッス。
[tab]顔を隠してたけど…あれは間違い無いッス。
[tab]いったいドコに、何しに行ったんでしょうね。
[wait][clear][end]

msg_27:
[color(yellow)]新米警察官[color(white)]
[tab]所長…
[tab]さっきまでどこに行ってたんスかね？
[tab]後ろ姿が寂しげだったッス。
[wait][clear][end]

msg_28:
[color(yellow)]ポーピーくん[color(white)]
[tab]百円入れてワーン♥
[tab]百円入れてワーン♥
[tab]百円入れてワーン♥[wait][clear][end]

msg_29:
[tab]ここに百円入れて欲しいワーン♥
[choice(2)]入れる
入れない
[end_choice][clear][end]

msg_30:
[color(yellow)]ポーピーくん[color(white)]
[tab]あっ、持ってないワーン♥
[tab]うそつきは泥棒の始まりワーン♥
[tab]兄ちゃん、出直してきな。[wait][clear][end]

msg_31:
[color(yellow)]ポーピーくん[color(white)]
[tab]ワン！[delay(15)]
[tab]もう５０００円溜まったワン！[delay(15)]
[tab]ワーンダフル！！[wait][clear][end]

msg_32:
[color(yellow)]ポーピーくん[color(white)]
[tab]ワン！[delay(10)]
[tab]ついに１００００円も募金が集まったワン！[delay(15)]
[tab]これもひとえに、お姉さんのおかげワン！！[wait][clear][end]

msg_33:
[color(yellow)]ポーピーくん[color(white)]
[tab]これはそのお礼ワン！
[tab][color(green)][var(msg_var_0)][color(white)]。
[tab]どど～んとプレゼントワン♥[wait][clear][end]

msg_34:
[color(green)][tab]舞耶達は、
[tab][item_with_type(item_ffff)]を手に入れた。[color(white)]
[wait][clear][end]

msg_35:
[color(yellow)]ポーピーくん[color(white)]
[tab]ありがとワーン♥[wait][clear][end]

msg_36:
[color(yellow)]ポーピーくん[color(white)]
[tab]…[delay(15)]ケチ。[wait][clear][end]

msg_37:
[color(yellow)]ご案内[color(white)]
[tab]Ｂ１Ｆ[tab]総合相談センター、外国人困りごと相談
[tab]１Ｆ[tab]遺失物管理所、免許更新受付、相談コーナー
[tab]２Ｆ[tab]犯罪被害者相談、災害対策課、交通捜査課[wait][clear][end]

msg_38:
[color(yellow)]ご案内[color(white)]
[tab]３Ｆ[tab]捜査二課聴訴室、防犯総務課、家事相談室
[tab]４Ｆ[tab]鑑識課身元不明相談室、少年第一課
[tab]５Ｆ[tab]家出人相談室、特捜第一課[wait][clear][end]

msg_39:
[color(yellow)]新米警察官[color(white)]
[tab]ピ～～～～～～～～～～～～～～～～～～～！！
[tab]そこから先は関係者以外、立ち入り禁止ッス！
[tab]入っちゃダメダメッス！！
[sync][wait][clear][end]
