function START()
{
    op_107();
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3000, 127);
    levelFootstepSet(sfx_10);
    ref_5 = todLoad(tod_e);
    wait(ref_5);
    todRun(tod_e, 1);
    call(TEST02);
    objVisible(obj_29, false);
    objVisible(obj_2a, false);
    ref_b = spriteLoad(sprite_a4);
    wait(ref_b);
    unitSpawn(shopkeeper, sprite_a4, 1088, -60, -968, north, none);
    ref_e = spriteLoad(sprite_a6);
    wait(ref_e);
    unitSpawn(npc1, sprite_a6, 1269, -60, -695, north, none);
    ref_11 = spriteLoad(sprite_a5);
    wait(ref_11);
    unitSpawn(npc2, sprite_a5, 1028, -60, -740, north, none);
    ref_14 = spriteLoad(sprite_a7);
    wait(ref_14);
    unitSpawn(npc3, sprite_a7, 677, -60, -1265, north, none);
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationPlay(npc1, animation_7, 1);
    call(LJSDHKGJKHSFDZ);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    ref_1b = spriteLoad(sprite_0);
    wait(ref_1b);
    unitSpawn(maya, sprite_0, 1050, -60, -1262, south, none);
    unitAnimationPlay(maya, animation_a, 1);
    ref_1f = spriteLoad(sprite_6);
    wait(ref_1f);
    unitSpawn(ulala, sprite_6, 808, -60, -1239, west, none);
    unitAnimationPlay(ulala, animation_a, 1);
    ref_23 = spriteLoad(sprite_d);
    wait(ref_23);
    unitSpawn(katsuya, sprite_d, 797, -60, -1129, west, none);
    unitAnimationPlay(katsuya, animation_1a, 1);
    ref_27 = spriteLoad(sprite_13);
    wait(ref_27);
    unitSpawn(baofu, sprite_13, 843, -60, -951, north, none);
    unitAnimationPlay(baofu, animation_3, 1);
    ref_2b = spriteLoad(sprite_5c);
    wait(ref_2b);
    unitSpawn(npc4, sprite_5c, 1002, -60, -1151, west, none);
    ref_2e = spriteLoad(sprite_5d);
    wait(ref_2e);
    unitSpawn(npc5, sprite_5d, 1115, -60, -1135, east, none);
    unitAnimationPlay(npc5, animation_6, 1);
    cameraSet(northwest, 1075, -60, -1180);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_3a = bustupLoad(bustup_5c);
    bustupWait(ref_3a);
    ref_3c = bustupAlloc(ref_3a, right, rgb(0,0,0));
    bustupFade(ref_3c, rgb(128,0,0), 30);
    ref_3e = dialogAlloc();
    ref_3f = msgShow(msg_0);
/***************************************
[color(yellow)]杏奈[color(white)]
[tab]安心して…
[tab]もうあんたはＪＯＫＥＲじゃない…

***************************************/
    unitAnimationPlay(npc4, animation_2d, 1);
    wait(ref_3f);
    ref_42 = msgShow(msg_1);
/***************************************
[tab]この人達が助けてくれたから。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_0, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc4, animation_3, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(npc4, animation_4, 1);
    sync();
    wait(ref_42);
    dialogFree(ref_3e);
    ref_4d = bustupFade(ref_3c, rgb(0,0,0), 10);
    bustupWait(ref_4d);
    bustupFree(ref_3c);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_24, 1);
    unitWait(maya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc5, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(npc5, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(npc5, animation_2, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc5, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc5, animation_0, 1);
    delayClear();
    delayWait(20);
    unitMove(npc5, 1040, -1144, face_east, medium);
    ref_66 = call(ANNAUKE);
    unitWait(npc5);
    unitAnimationPlay(npc5, animation_25, 1);
    ref_69 = bustupLoad(bustup_5d);
    bustupWait(ref_69);
    ref_6b = bustupAlloc(ref_69, right, rgb(0,0,0));
    bustupFade(ref_6b, rgb(128,0,0), 30);
    ref_6d = dialogAlloc();
    ref_6e = msgShow(msg_2);
/***************************************
[color(yellow)]ノリコ[color(white)]
[tab]うう…ごめんなさい…ごめんなさい…
[tab]私…私…
[wait][clear]
***************************************/
    wait(ref_6e);
    dialogFree(ref_6d);
    ref_71 = bustupFade(ref_6b, rgb(0,0,0), 10);
    bustupWait(ref_71);
    bustupFree(ref_6b);
    wait(ref_66);
    delayClear();
    delayWait(60);
    cameraMoveTo(1032, -60, -1223, 60);
    unitAnimationPlay(npc4, animation_3, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(npc4, animation_4, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(shopkeeper, animation_1, 1);
    unitFace(npc4, north);
    unitAnimationPlay(npc4, animation_0, 1);
    delayClear();
    delayWait(6);
    unitFace(npc4, east);
    delayClear();
    delayWait(30);
    unitMove(npc4, 899, -1133, face_east, medium);
    call(MAYANMGU);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(baofu, animation_0, 1);
    unitAnimationPlay(ulala, animation_1, 1);
    unitWait(npc4);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc4, animation_2d, 1);
    ref_8f = bustupLoad(bustup_5c);
    bustupWait(ref_8f);
    ref_91 = bustupAlloc(ref_8f, right, rgb(0,0,0));
    bustupFade(ref_91, rgb(128,0,0), 30);
    ref_93 = dialogAlloc();
    ref_94 = msgShow(msg_3);
/***************************************
[color(yellow)]杏奈[color(white)]
[tab]ノリコは…逮捕されるの？
[wait][clear]
***************************************/
    wait(ref_94);
    dialogFree(ref_93);
    ref_97 = bustupFade(ref_91, rgb(0,0,0), 10);
    bustupWait(ref_97);
    bustupFree(ref_91);
    unitAnimationPlay(npc4, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_6, 1);
    delayClear();
    delayWait(60);
    ref_a0 = bustupLoad(bustup_21);
    bustupWait(ref_a0);
    ref_a2 = bustupAlloc(ref_a0, left, rgb(0,0,0));
    bustupFade(ref_a2, rgb(128,0,0), 30);
    ref_a4 = dialogAlloc();
    ref_a5 = msgShow(msg_4);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]どんな事情にしろ罪は罪だ…

***************************************/
    wait(ref_a5);
    call(URARAMIRU);
    ref_a8 = msgShow(msg_5);
/***************************************
[tab]だが、今は彼女の犯罪を立証できない。
[tab]当分、君に保護観察をお願いするよ…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_a8);
    dialogFree(ref_a4);
    ref_ac = bustupFade(ref_a2, rgb(0,0,0), 10);
    bustupWait(ref_ac);
    bustupFree(ref_a2);
    unitAnimationPlay(katsuya, animation_1a, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc4, animation_2e, 1);
    delayClear();
    delayWait(30);
    ref_b5 = bustupLoad(bustup_5c);
    bustupWait(ref_b5);
    ref_b7 = bustupAlloc(ref_b5, right, rgb(0,0,0));
    bustupFade(ref_b7, rgb(128,0,0), 30);
    ref_b9 = dialogAlloc();
    ref_ba = msgShow(msg_6);
/***************************************
[color(yellow)]杏奈[color(white)]
[tab]ありがとう…
[sync][wait][clear]
***************************************/
    unitAnimationHold(katsuya, animation_21, 30);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_2c, 1);
    unitWait(katsuya);
    sync();
    wait(ref_ba);
    dialogFree(ref_b9);
    ref_c2 = bustupFade(ref_b7, rgb(0,0,0), 10);
    bustupWait(ref_c2);
    bustupFree(ref_b7);
    unitAnimationPlay(ulala, animation_30, 1);
    call(KATTOURA);
    ref_c7 = bustupLoad(bustup_17);
    bustupWait(ref_c7);
    ref_c9 = bustupAlloc(ref_c7, left, rgb(0,0,0));
    bustupFade(ref_c9, rgb(128,0,0), 30);
    ref_cb = dialogAlloc();
    ref_cc = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]優しいじゃ～ん？
[tab]逮捕って騒ぎ出したら、
[tab]殴ってやろうかと思ってたのに。
[wait][clear]
***************************************/
    wait(ref_cc);
    dialogFree(ref_cb);
    ref_cf = bustupFade(ref_c9, rgb(0,0,0), 10);
    bustupWait(ref_cf);
    bustupFree(ref_c9);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_1d, 1);
    unitWait(baofu);
    call(KATTOPAO);
    ref_d8 = bustupLoad(bustup_2c);
    bustupWait(ref_d8);
    ref_da = bustupAlloc(ref_d8, left, rgb(0,0,0));
    bustupFade(ref_da, rgb(128,0,0), 30);
    ref_dc = dialogAlloc();
    ref_dd = msgShow(msg_8);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]こんな状況は法律じゃ裁けねぇってことだ…

***************************************/
    wait(ref_dd);
    ref_df = msgShow(msg_9);
/***************************************
[tab]ようやく、限界がわかってきたか？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_df);
    dialogFree(ref_dc);
    ref_e3 = bustupFade(ref_da, rgb(0,0,0), 10);
    bustupWait(ref_e3);
    bustupFree(ref_da);
    unitAnimationPlay(katsuya, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(katsuya, animation_29, 1);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_1a, 1);
    delayClear();
    delayWait(30);
    ref_f1 = bustupLoad(bustup_21);
    bustupWait(ref_f1);
    ref_f3 = bustupAlloc(ref_f1, left, rgb(0,0,0));
    bustupFade(ref_f3, rgb(128,0,0), 30);
    ref_f5 = dialogAlloc();
    ref_f6 = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]あの子より先に裁かれるべき者がいるからな。
[tab]竜蔵やマフィア…それとつながる警察内部の人間…
[tab]絶対、腐敗を暴いてやる…
[wait][clear]
***************************************/
    ref_f7 = spriteLoad(sprite_e);
    wait(ref_f7);
    wait(ref_f6);
    dialogFree(ref_f5);
    ref_fb = bustupFade(ref_f3, rgb(0,0,0), 10);
    bustupWait(ref_fb);
    bustupFree(ref_f3);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc4, animation_0, 1);
    unitAnimationHold(katsuya, animation_21, 30);
    sndMusicPlay(sound_3145, 127);
    call(MAYAGYO);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(10);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_e);
    unitFace(katsuya, west);
    unitAnimationHold(katsuya, animation_1, -1);
    delayClear();
    delayWait(60);
    ref_10e = bustupLoad(bustup_fe);
    bustupWait(ref_10e);
    ref_110 = bustupAlloc(ref_10e, right, rgb(0,0,0));
    bustupFade(ref_110, rgb(128,0,0), 30);
    ref_112 = dialogAlloc();
    ref_113 = msgShow(msg_11);
/***************************************
[color(yellow)]男の声[color(white)]
[tab][suou][tab]克哉君だな…
[tab]君たちが追いかけている事件の情報を提供したい…
[tab]青葉公園の休憩所で××時に待つ…
[wait][clear]
***************************************/
    wait(ref_113);
    call(MAYACHKATT);
    ref_116 = bustupLoad(bustup_21);
    bustupWait(ref_116);
    ref_118 = bustupAlloc(ref_116, left, rgb(0,0,0));
    bustupFade(ref_118, rgb(128,0,0), 30);
    ref_11a = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]なに…！？
[tab]あんたは何者だ？
[wait][clear]
***************************************/
    wait(ref_11a);
    ref_11c = bustupFade(ref_118, rgb(0,0,0), 10);
    bustupWait(ref_11c);
    bustupFree(ref_118);
    ref_11f = msgShow(msg_13);
/***************************************
[color(yellow)]男の声[color(white)]
[tab]…スニーク。
[tab]そう憶えておきたまえ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_11f);
    dialogFree(ref_112);
    ref_123 = bustupFade(ref_110, rgb(0,0,0), 10);
    bustupWait(ref_123);
    bustupFree(ref_110);
    unitAnimationStop(katsuya);
    sndMusicPlay(sound_3146, 127);
    delayClear();
    delayWait(30);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitFace(katsuya, north);
    unitAnimationPlay(katsuya, animation_1a, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_1d, 1);
    ref_132 = bustupLoad(bustup_2c);
    bustupWait(ref_132);
    ref_134 = bustupAlloc(ref_132, left, rgb(0,0,0));
    bustupFade(ref_134, rgb(128,0,0), 30);
    ref_136 = dialogAlloc();
    ref_137 = msgShow(msg_14);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]スニークだぁ…？
[tab]「卑怯者」か…胡散臭ぇ…

***************************************/
    wait(ref_137);
    ref_139 = msgShow(msg_15);
/***************************************
[tab]どうする気だ？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_139);
    dialogFree(ref_136);
    ref_13d = bustupFade(ref_134, rgb(0,0,0), 10);
    bustupWait(ref_13d);
    bustupFree(ref_134);
    unitAnimationPlay(katsuya, animation_6, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_3, 1);
    delayClear();
    delayWait(60);
    ref_149 = bustupLoad(bustup_21);
    bustupWait(ref_149);
    ref_14b = bustupAlloc(ref_149, left, rgb(0,0,0));
    bustupFade(ref_14b, rgb(128,0,0), 30);
    ref_14d = dialogAlloc();
    ref_14e = msgShow(msg_16);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]竜蔵近辺の密告者かもしれない…
[tab]会ってみようと思う。

***************************************/
    wait(ref_14e);
    unitFace(katsuya, west);
    ref_151 = msgShow(msg_17);
/***************************************
[tab]いいね、天野君？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1f, 1);
    wait(ref_151);
    dialogFree(ref_14d);
    ref_155 = bustupFade(ref_14b, rgb(0,0,0), 10);
    bustupWait(ref_155);
    bustupFree(ref_14b);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(60);
    unitFace(maya, east);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_6, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(120);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    bitSet(EBIT_E0043);
    bitClear(TBIT_MD303);
    bitSet(TBIT_MD403);
    bitClear(TBIT_ON404);
    bitSet(VBIT_KOEN_HAJIKI);
    mapLoad(yumezaki, 29, 4);
}

function ANNAUKE()
{
    unitAnimationPlay(npc4, animation_3, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(npc4, animation_0, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc4, animation_6, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc4, animation_25, 1);
    unitWait(npc4);
}

function MAYANMGU()
{
    unitMove(maya, 1059, -1208, face_south, medium);
    unitAnimationPlay(npc5, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(npc5, animation_2, 1);
    delayClear();
    delayWait(60);
    unitFace(npc5, north);
    unitAnimationPlay(npc5, animation_0, 1);
    unitWait(maya);
    unitAnimationPlay(maya, animation_1f, 1);
    delayClear();
    delayWait(40);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(maya, animation_24, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_1e, 1);
    unitWait(maya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc5, animation_6, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(npc5, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(maya, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(maya, animation_4, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc5, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc5, animation_2, 1);
}

function URARAMIRU()
{
    unitAnimationPlay(baofu, animation_1a, 1);
    unitAnimationPlay(ulala, animation_2, 1);
    delayClear();
    delayWait(10);
    unitFace(ulala, south);
    unitAnimationPlay(ulala, animation_0, 1);
}

function KATTOURA()
{
    unitAnimationPlay(katsuya, animation_3, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(katsuya, animation_4, 1);
}

function KATTOPAO()
{
    unitAnimationPlay(katsuya, animation_3, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(katsuya, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(katsuya, animation_2, 1);
}

function MAYAGYO()
{
    unitAnimationPlay(maya, animation_0, 1);
    unitFace(maya, east);
}

function MAYACHKATT()
{
    unitMove(maya, 1013, -1196, face_east, medium);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
    unitFace(npc5, east);
    unitAnimationPlay(npc5, animation_0, 1);
}

function LJSDHKGJKHSFDZ()
{
  label_1c7:
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc3, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc3, animation_4, 1);
    delayClear();
    delayWait(360);
    unitAnimationPlay(npc3, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc3, animation_9, 1);
    unitWait(npc3);
    delayClear();
    delayWait(60);
    b(label_1c7);
}

function TEST02()
{
    objVisible(obj_2, false);
    objVisible(obj_4, false);
    objVisible(obj_5, false);
    objVisible(obj_6, false);
    objVisible(obj_9, false);
    objVisible(obj_a, false);
    objVisible(obj_b, false);
    objVisible(obj_c, false);
    objVisible(obj_d, false);
    objVisible(obj_10, false);
    objVisible(obj_11, false);
    objVisible(obj_12, false);
    objVisible(obj_13, false);
    objVisible(obj_14, false);
    objVisible(obj_15, false);
    objVisible(obj_17, false);
    objVisible(obj_18, false);
    objVisible(obj_19, false);
    objVisible(obj_1b, false);
    objVisible(obj_1e, false);
    objVisible(obj_25, false);
}
