function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    cameraSet(east, 2100, 0, -680);
    levelFootstepSet(sfx_19);
    ref_9 = spriteLoad(sprite_0);
    wait(ref_9);
    ref_b = spriteLoad(sprite_3);
    wait(ref_b);
    ref_d = spriteLoad(sprite_6);
    wait(ref_d);
    ref_f = spriteLoad(sprite_8);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_d);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_f);
    wait(ref_13);
    ref_15 = spriteLoad(sprite_13);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_15);
    wait(ref_17);
    ref_19 = spriteLoad(sprite_5f);
    wait(ref_19);
    unitSpawn(maya, sprite_3, 1580, -200, -610, west, none);
    unitSpawn(ulala, sprite_8, 1870, -200, -830, east, none);
    unitSpawn(katsuya, sprite_f, 1380, -200, -680, west, none);
    unitSpawn(baofu, sprite_15, 1460, -200, -500, west, none);
    unitSpawn(noriko, sprite_5f, 1750, -200, -780, north, none);
    unitAnimationPlay(noriko, animation_c, 1);
    unitAnimationPlay(maya, animation_16, 1);
    unitAnimationPlay(ulala, animation_15, 1);
    unitShadowRadius(noriko, 0);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    call(URARA_START);
    delayClear();
    delayWait(30);
    call(MAYA_START);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    ref_33 = cameraMoveTo(1940, 0, -560, 60);
    wait(ref_33);
    delayClear();
    delayWait(30);
    call(PAOFU_START);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitAnimationPlay(katsuya, animation_d, 1);
    ref_3b = bustupLoad(bustup_21);
    bustupWait(ref_3b);
    ref_3d = bustupAlloc(ref_3b, left, rgb(0,0,0));
    bustupFade(ref_3d, rgb(128,0,0), 30);
    ref_3f = dialogAlloc();
    ref_40 = msgShow(msg_0);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]その子は大丈夫か？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_40);
    dialogFree(ref_3f);
    ref_44 = bustupFade(ref_3d, rgb(0,0,0), 10);
    bustupWait(ref_44);
    bustupFree(ref_3d);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_3d, 1);
    ref_4a = bustupLoad(bustup_17);
    bustupWait(ref_4a);
    ref_4c = bustupAlloc(ref_4a, left, rgb(0,0,0));
    bustupFade(ref_4c, rgb(128,0,0), 30);
    ref_4e = dialogAlloc();
    ref_4f = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]気を失ってるだけみたいね…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4f);
    dialogFree(ref_4e);
    ref_53 = bustupFade(ref_4c, rgb(0,0,0), 10);
    bustupWait(ref_53);
    bustupFree(ref_4c);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_c, 1);
    delayClear();
    delayWait(30);
    ref_5b = bustupLoad(bustup_21);
    bustupWait(ref_5b);
    ref_5d = bustupAlloc(ref_5b, left, rgb(0,0,0));
    bustupFade(ref_5d, rgb(128,0,0), 30);
    ref_5f = dialogAlloc();
    ref_60 = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]奴は逃げたか…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_60);
    dialogFree(ref_5f);
    ref_64 = bustupFade(ref_5d, rgb(0,0,0), 10);
    bustupWait(ref_64);
    bustupFree(ref_5d);
    delayClear();
    delayWait(30);
    unitAnimationHold(baofu, animation_1c, -1);
    ref_6a = bustupLoad(bustup_2e);
    bustupWait(ref_6a);
    ref_6c = bustupAlloc(ref_6a, left, rgb(0,0,0));
    bustupFade(ref_6c, rgb(128,0,0), 30);
    ref_6e = dialogAlloc();
    ref_6f = msgShow(msg_3);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]クソッタレ…！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(10);
    sndMusicPlay(sound_3144, 127);
    sync();
    wait(ref_6f);
    dialogFree(ref_6e);
    ref_76 = bustupFade(ref_6c, rgb(0,0,0), 10);
    bustupWait(ref_76);
    bustupFree(ref_6c);
    unitAnimationStop(baofu);
    unitAnimationPlay(maya, animation_12, 1);
    unitAnimationPlay(ulala, animation_3c, 1);
    unitAnimationPlay(katsuya, animation_e, 1);
    delayClear();
    delayWait(30);
    unitFace_2(maya, east);
    unitFace_2(katsuya, south);
    unitAnimationPlay(maya, animation_a, 1);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(ulala, animation_31, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_14, 1);
    ref_8a = bustupLoad(bustup_21);
    bustupWait(ref_8a);
    ref_8c = bustupAlloc(ref_8a, left, rgb(0,0,0));
    bustupFade(ref_8c, rgb(128,0,0), 30);
    ref_8e = dialogAlloc();
    ref_8f = msgShow(msg_4);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]おい…
[tab]奴が言った事…事実なのか？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_8f);
    dialogFree(ref_8e);
    ref_93 = bustupFade(ref_8c, rgb(0,0,0), 10);
    bustupWait(ref_93);
    bustupFree(ref_8c);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_12, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    unitFace_2(baofu, north);
    unitAnimationPlay(baofu, animation_1f, 1);
    ref_9f = bustupLoad(bustup_2e);
    bustupWait(ref_9f);
    ref_a1 = bustupAlloc(ref_9f, left, rgb(0,0,0));
    bustupFade(ref_a1, rgb(128,0,0), 30);
    ref_a3 = dialogAlloc();
    ref_a4 = msgShow(msg_5);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]本当だったらどうだってんだ…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a4);
    unitAnimationPlay(baofu, animation_14, 1);
    ref_a8 = msgShow(msg_6);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]台湾じゃ「一清専案」であいつらは狩られてんだよ。

***************************************/
    wait(ref_a8);
    unitAnimationPlay(baofu, animation_1e, 1);
    ref_ab = msgShow(msg_7);
/***************************************
[tab]悪党を何人殺ろうが、感謝されこそすれ、
[tab]文句言われる筋合いはねぇな！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ab);
    unitAnimationPlay(baofu, animation_1d, 1);
    ref_af = msgShow(msg_8);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]それとも、国際指名手配でもされてるってぇのか？

***************************************/
    wait(ref_af);
    unitAnimationHold(baofu, animation_19, -1);
    ref_b2 = msgShow(msg_9);
/***************************************
[tab]どの道、所轄の強行犯係の管轄じゃねぇだろが！

***************************************/
    wait(ref_b2);
    unitAnimationStop(baofu);
    unitAnimationPlay(baofu, animation_e, 1);
    ref_b6 = msgShow(msg_10);
/***************************************
[tab]引っ込んでな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_b6);
    dialogFree(ref_a3);
    ref_ba = bustupFade(ref_a1, rgb(0,0,0), 10);
    bustupWait(ref_ba);
    bustupFree(ref_a1);
    delayClear();
    delayWait(30);
    unitAnimationHold(katsuya, animation_11, -1);
    ref_c0 = bustupLoad(bustup_23);
    bustupWait(ref_c0);
    ref_c2 = bustupAlloc(ref_c0, left, rgb(0,0,0));
    bustupFade(ref_c2, rgb(128,0,0), 30);
    ref_c4 = dialogAlloc();
    ref_c5 = msgShow(msg_11);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]随分、警察やマフィアの内情に詳しいじゃないか…
[tab]お前、何者なんだ…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c5);
    dialogFree(ref_c4);
    ref_c9 = bustupFade(ref_c2, rgb(0,0,0), 10);
    bustupWait(ref_c9);
    bustupFree(ref_c2);
    delayClear();
    delayWait(30);
    ref_ce = cameraMoveTo(2100, 0, -680, 30);
    wait(ref_ce);
    delayClear();
    delayWait(30);
    ref_d2 = bustupLoad(bustup_1a);
    bustupWait(ref_d2);
    ref_d4 = bustupAlloc(ref_d2, left, rgb(0,0,0));
    bustupFade(ref_d4, rgb(128,0,0), 30);
    ref_d6 = dialogAlloc();
    ref_d7 = msgShow(msg_12);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]やめてよ…

***************************************/
    unitAnimationPlay(ulala, animation_2b, 1);
    unitWait(ulala);
    wait(ref_d7);
    unitAnimationPlay(ulala, animation_1f, 1);
    unitAnimationStop(katsuya);
    unitAnimationPlay(katsuya, animation_d, 1);
    unitAnimationPlay(baofu, animation_c, 1);
    unitAnimationPlay(maya, animation_12, 1);
    ref_e0 = msgShow(msg_13);
/***************************************
[tab]早くこの子、ベルベットルームに連れてかなきゃ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_e0);
    dialogFree(ref_d6);
    ref_e4 = bustupFade(ref_d4, rgb(0,0,0), 10);
    bustupWait(ref_e4);
    bustupFree(ref_d4);
    delayClear();
    delayWait(60);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_ae);
}

function MAYA_START()
{
    unitAnimationPlay(maya, animation_15, 1);
    delayClear();
    delayWait(30);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitAnimationPlay(maya, animation_a, 1);
}

function URARA_START()
{
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitAnimationPlay(ulala, animation_41, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_42, 1);
}

function PAOFU_START()
{
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_c, 1);
    delayClear();
    delayWait(30);
    unitFace_2(baofu, north);
    unitAnimationPlay(baofu, animation_2a, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_12, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    unitFace_2(baofu, south);
    unitAnimationPlay(baofu, animation_10, 1);
}
