
msg_0:
[color(yellow)]二枚目の男[color(white)]
[tab]君にこの前お願いしていたことだけど…
[tab]どうだろう、都合ついたかな？
[wait][clear][end]

msg_1:
[color(yellow)]若い女[color(white)]
[tab]うん…
[tab]３００万くらいならなんとか用意できるけど…
[tab]信じていいのよね…？
[wait][clear][end]

msg_2:
[color(yellow)]二枚目の男[color(white)]
[tab]あたりまえじゃないか…
[tab]君のおかげで今の研究も上手く行く。
[tab]そうすれば僕は副院長だ。
[sync][wait][clear][end]

msg_3:
[color(yellow)]二枚目の男[color(white)]
[tab]君も副院長婦人だよ。
[tab]愛してる…
[wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
[tab]なぁにが副院長だ…
[tab]あの阿呆も、あんな手でコロっといったのかねぇ…
[sync][wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]牧村[tab]洋一さんですね？
[tab]芹沢[tab]うららさんをご存知でしょう。
[tab]詐欺容疑でご同行願いたい。
[wait][clear][end]

msg_6:
[color(yellow)]牧村[color(white)]
[tab]な、何を言ってるんだアンタ…？
[tab]そんな女知らないな。
[tab]人違いでしょう。
[wait][clear][end]

msg_7:
[color(yellow)]牧村[tab]洋一（まきむら[tab]よういち）[color(white)]
[color(green)][tab]うららを騙して貯金を奪った結婚詐欺師。
[tab]牧村という名はその時の偽名。[color(white)]
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]そうですか…
[end]

msg_9:
[tab]詐欺にあった女性がＪＯＫＥＲに復讐を依頼した
[tab]疑いがありましてね…
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]保護したかったのですが、人違いでしたか…
[end]

msg_11:
[tab]失礼しました。
[wait][clear][end]

msg_12:
[color(yellow)]牧村[color(white)]
[tab]え…？
[wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]やれやれ…また死体が一つ増えるのか…
[end]

msg_14:
[tab]もう、手後れかもしれねぇなぁ…
[wait][clear][end]

msg_15:
[color(yellow)]若い女[color(white)]
[tab]ねぇ！[tab]詐欺ってどういうこと…！？
[tab]うららって誰なの！？
[wait][clear][end]

msg_16:
[color(yellow)]牧村[color(white)]
[tab]ヒ…
[tab]い、いや…
[wait][clear][end]

msg_17:
[color(yellow)]牧村[color(white)]
[tab]ま、待ってくれ…！！
[tab]ＪＯＫＥＲって、本当なのか！？
[tab]た、助けてくれ！[tab]死にたくない！！
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]自供成立だな…
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]姉ちゃん、もっと男見る目磨きなよ…
[wait][clear][end]

msg_20:
[color(yellow)]克哉[color(white)]
[tab]天野君、芹沢君が行きそうな所は？
[wait][clear][end]

msg_21:
[color(yellow)]克哉[color(white)]
[tab]ＧＯＬＤ…？
[tab]フィットネスクラブか…
[tab]よし、行ってみよう。
[wait][clear][end]
