
msg_0:
[color(yellow)]少年の声[color(white)]
[tab]だーからぁ！[tab]何度も言ってるじゃねぇすか！
[tab]道に迷ったんすよぉ。
[tab]もう勘弁してくださいよぉ。
[sync][wait][clear][end]

msg_1:
[color(yellow)]栄吉の声[color(white)]
[tab]だーからぁ！[tab]何度も言ってるじゃねぇすか！
[tab]道に迷ったんすよぉ。
[tab]もう勘弁してくださいよぉ。
[sync][wait][clear][end]

msg_2:
[color(yellow)]若い警備員[color(white)]
[tab]もっとマシな嘘をつけ！
[sync][wait][clear][end]

msg_3:
[color(yellow)]目つきのするどい警備員[color(white)]
[tab]もういい。
[tab]大方、実験材料の知り合いかなにかだろう。
[sync][wait][clear][end]

msg_4:
[color(yellow)]目つきのするどい警備員[color(white)]
[tab]このまま帰すわけにもいかん。
[tab]研究員に引き渡す。
[sync][wait][clear][end]

msg_5:
[color(yellow)]青頭の少年[color(white)]
[tab]やいやいやい！
[tab]やっぱ噂通り、ここで人体実験かなにかして
[tab]やがんだな！？
[sync][wait][clear][end]

msg_6:
[color(yellow)]三科[tab]栄吉（みしな[tab]えいきち）[color(white)]
[color(green)][tab]春日山高校の番長を務める２年生。
[tab]どこかで会った気がする…[color(white)]
[sync][wait][clear][end]

msg_7:
[color(yellow)]栄吉[color(white)]
[tab]チキショー！[tab]杉本を返しやがれ！！
[tab]じゃねぇとひどい目に会わすぞ、コラァ！！
[sync][wait][clear][end]

msg_8:
[color(yellow)]栄吉[color(white)]
[tab]やいやいやい！
[tab]やっぱ噂通り、ここで人体実験かなにかして
[tab]やがんだな！？
[sync][wait][clear][end]

msg_9:
[color(yellow)]栄吉[color(white)]
[tab]チキショー！[tab]杉本を返しやがれ！！
[tab]じゃねぇとひどい目に合わすぞ、コラァ！！
[sync][wait][clear][end]

msg_10:
[color(yellow)]若い警備員[color(white)]
[tab]そんな格好で何ができるんだ？
[tab]やれるもんならやってみな。
[sync][wait][clear][end]

msg_11:
[color(yellow)]南条[color(white)]
[tab]承知した。
[sync][wait][clear][end]
