
msg_0:
[color(yellow)]うらら[color(white)]
[tab]さっすがマスコミ…
[tab]マーヤが言った通り、耳が早いわ。
[sync][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]って…
[tab]いつまでむくれてんのよぅ。
[tab]クジで負けたんだからしゃーないじゃんよ。
[sync][wait][clear][end]

msg_2:
[color(yellow)]パオフゥ[color(white)]
[tab]こんな役は俺の柄じゃねぇ…
[tab][suou]にでもやらせろ。
[sync][wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]自分のキャラか…
[tab]私、よくわかんないんだよねぇ…
[tab]その「自分」ってヤツ。
[sync][wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]アンタは、わかってるんだよね…？
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]…当たり前だ。
[sync][wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]「何のために生きてる」とか、
[tab]「何をしたらいいのか」とかさ…
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]大人になれば全部わかるものだと思ってたけど…
[tab]現実は甘くないよね。
[tab]ますますわかんなくなるだけだわ…
[sync][wait][clear][end]

msg_8:
[color(yellow)]パオフゥ[color(white)]
[tab]…なぜそんなことを俺に話すんだ？
[sync][wait][clear][end]

msg_9:
[color(yellow)]うらら[color(white)]
[tab]わかんない…
[tab]ただ、ワケありみたいだからさ。
[tab]どんな生き方してきたのかなぁって思っただけ…
[sync][wait][clear][end]
