
msg_0:
[color(yellow)]南条[color(white)]
[tab]俺も最近知ったのだが、うちはセベク事件から流出
[tab]したセベクの技術者やノウハウを囲い込み、
[tab]政府と組んで研究を続けていたらしい…
[sync][wait][clear][end]

msg_1:
[color(yellow)]南条[color(white)]
[tab]神取の開発した空間歪曲装置…ＤＶＡシステムや
[tab]その他の研究は、実用化できれば莫大な利益を
[tab]もたらすからな…
[sync][wait][clear][end]

msg_2:
[color(yellow)]南条[color(white)]
[tab]そこで竜蔵とパイプができたのだろう。
[tab]新世塾の存在を知らぬ間に、
[tab]荷担する形になってしまった…
[sync][wait][clear][end]

msg_3:
[color(yellow)]南条[color(white)]
[tab]愚かな話だ…
[tab]あの事件に関わった者の心情を思うと、
[tab]詫びのしようもない…
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]どうやらここにいるのは、不器用な連中らしい。
[tab]生きていく事に…ね。
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]政道は綺麗事だけじゃ治まらねぇ、か…
[tab]そんなのは、上から見下ろすヤツの強弁だ。
[tab]俺は絶対認めねぇ…
[sync][wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]大人になるって、
[tab]色々汚い事を憶えてくって事かもね…
[tab]ダマしたり利用したり…
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]仕舞いにゃ自分にも嘘ついて、
[tab]わかんなくなってくんだわ…
[sync][wait][clear][end]

msg_8:
[color(yellow)]麻希の声[color(white)]
[tab]それが最後の扉みたいね…開ける？
[sync][wait][clear][end]

msg_9:
[tab]それが最後の扉みたいね…開ける？
[choice(2)]ええ…
少し…待って。
[end_choice][clear][end]

msg_10:
[color(yellow)]麻希の声[color(white)]
[tab]天野さん…
[tab]南条君と……[delay(30)]
[tab]南条君をお願いします。気を付けて…
[sync][wait][clear][end]

msg_11:
[color(yellow)]麻希の声[color(white)]
[tab]わかりました…決めたらまた連絡してね。
[sync][wait][clear][end]

msg_12:
[color(yellow)]玲司の声[color(white)]
[tab]それが最後の扉みてぇだな…開けるか？
[sync][wait][clear][end]

msg_13:
[tab]それが最後の扉みてぇだな…開けるか？
[choice(2)]うん…開けて。
少し…待って。
[end_choice][clear][end]

msg_14:
[color(yellow)]玲司の声[color(white)]
[tab]わかった…
[sync][wait][clear][end]

msg_15:
[color(yellow)]玲司の声[color(white)]
[tab]あのよ…
[tab]あんたにこんな事頼める義理じゃねぇが…
[tab]南条を頼む…
[sync][wait][clear][end]

msg_16:
[color(yellow)]玲司の声[color(white)]
[tab]そいつは頭はいいが…血も上り易い。
[tab]無茶しねぇように見てやってくれ…
[sync][wait][clear][end]

msg_17:
[color(yellow)]玲司の声[color(white)]
[tab]ああ…ゆっくり決めな。
[sync][wait][clear][end]

msg_18:
[color(yellow)]南条[color(white)]
[tab]天野さん、もう後戻りはできない。
[tab]前進あるのみだ！
[sync][wait][clear][end]

msg_19:
[color(yellow)]南条[color(white)]
[tab]天野さん、もう後戻りはできない。
[tab]前進あるのみだ！
[sync][wait][clear][end]
