
msg_0:
[color(yellow)]うらら[color(white)]
[tab]…それで塀乗り越えて、ＪＯＫＥＲ使いになって
[tab]さらわれた友達を追っかけてきたってわけ？
[sync][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]しっかしアンタ、無茶するわ…
[tab]大体、そいつがＪＯＫＥＲ呪いした相手って、
[tab]アンタなんでしょ？
[sync][wait][clear][end]

msg_2:
[color(yellow)]栄吉[color(white)]
[tab]そりゃアイツのせいで、どエライ目に会ったけど、
[tab]ほっとけないっしょ。
[tab]俺は番長すからね。
[sync][wait][clear][end]

msg_3:
[color(yellow)]南条[color(white)]
[tab]セキュリティはカットしました。
[tab]これで警報装置の類はしばらくごまかせるはずだ。
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]栄吉君、友達のことは我々にまかせて帰りたまえ。
[tab]ここは子供の来るところじゃない。
[sync][wait][clear][end]

msg_5:
[color(yellow)]栄吉[color(white)]
[tab]冗談じゃねぇ！
[tab]このまますっこんでられっか！
[tab]俺も連れて行ってくれよ！
[sync][wait][clear][end]

msg_6:
[color(yellow)]栄吉[color(white)]
[tab]じゃねぇと、騒ぐぜ！？
[tab]「だーれーかぁー！！」
[sync][wait][clear][end]

msg_7:
[color(yellow)]南条[color(white)]
[tab]仕方ない…連れて行きましょう。
[tab]気持ちは理解できる。
[sync][wait][clear][end]

msg_8:
[color(yellow)]南条[color(white)]
[tab]その代わり…
[tab]少年、我々の邪魔はするなよ。
[tab]途中で戻れと言ったら戻るんだ。
[sync][wait][clear][end]

msg_9:
[color(yellow)]栄吉[color(white)]
[tab]がってん承知でぃ！
[sync][wait][clear][end]

msg_10:
[color(yellow)]南条[color(white)]
[tab]友人を助けたいという心根は見上げたものだ…
[tab]大事にしてやるべきですよ。
[sync][wait][clear][end]

msg_11:
[color(yellow)]パオフゥ[color(white)]
[tab]やれやれ…とんだお荷物が増えたもんだぜ。
[tab]俺は知らねぇぞ…
[sync][wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]人体実験か…
[tab]略取誘拐、逮捕監禁致死傷…罪は重いぞ。
[sync][wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]もっとも、僕達も不法侵入以上の罪を犯している
[tab]事になるんだがね…
[sync][wait][clear][end]

msg_14:
[color(yellow)]うらら[color(white)]
[tab]マーヤもお人好しだけどさ、コイツも相当だね…
[sync][wait][clear][end]

msg_15:
[color(yellow)]うらら[color(white)]
[tab]よっしゃ、ここはお姉さん達で、
[tab]その頭の悪いダチ公を助けてやろうじゃん？
[sync][wait][clear][end]

msg_16:
[color(yellow)]栄吉[color(white)]
[tab]姐さん…前にどっかで会ったことねぇすか？
[tab]なーんか知ってる気がするんだよなぁ。
[sync][wait][clear][end]

msg_17:
[tab]なーんか知ってる気がするんだよなぁ。
[choice(2)]私も…
前に駅前で見たかな？
[end_choice][clear][end]

msg_18:
[color(yellow)]栄吉[color(white)]
[tab]姐さんも…？
[tab]どこだっけかなぁ…
[tab]ひょっとして、カニ缶好き？
[sync][wait][clear][end]

msg_19:
[color(yellow)]栄吉[color(white)]
[tab]やっぱり…
[tab]なんで俺、そんなこと知ってんだぁ？
[sync][wait][clear][end]

msg_20:
[color(yellow)]栄吉[color(white)]
[tab]ああ、思い出した！
[tab]セブンスの[suou]と派手にぶつかってた…
[tab]それでか…？
[sync][wait][clear][end]

msg_21:
[color(yellow)]栄吉[color(white)]
[tab]いや…なんか、もっと前から知ってるような気が
[tab]するんだよなぁ…
[sync][wait][clear][end]

msg_22:
[color(yellow)]栄吉[color(white)]
[tab]邪魔にはならねぇようにするからさ、
[tab]ここはひとつ頼んますぜ、姐さん！
[sync][wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]どこへ行く気です？
[tab]もう引き返している時間はない。
[tab]前進あるのみだ。
[wait][clear][end]
