
msg_0:
[color(yellow)]克哉[color(white)]
[tab]少し冷え込んできたな…
[tab]大丈夫かい？
[sync][wait][clear][end]

msg_1:
[color(yellow)]克哉[color(white)]
[tab]本当にそんな男女が現れるんだろうか…
[tab]来たとして、あの二人は上手くやれるんだろうか…
[tab]不安だな…
[sync][wait][clear][end]

msg_2:
[tab]不安だな…
[choice(2)]考え過ぎよ。レッツ・ポジティブシンキング♥
うーん、心配かも♥
[end_choice][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]………
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]あ…
[tab]まぁ…いずれにしろ成り行きにまかせるさ…
[sync][wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]なんだ…そんなにおかしいか？
[sync][wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]わかってはいるんだがね…
[tab]あれこれ考え過ぎて、
[tab]色々背負込んでしまう性分なんだ。
[sync][wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]昔からね…
[sync][wait][clear][end]

msg_8:
[color(yellow)]舞耶[color(white)]
[tab]………
[sync][wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]君は…自分の役割に疲れたりしないのかい？
[sync][wait][clear][end]

msg_10:
[tab]君は…自分の役割に疲れたりしないのかい？
[choice(2)]疲れることもあるかな…？
自分で決めたことだから。
[end_choice][clear][end]

msg_11:
[color(yellow)]舞耶[color(white)]
[tab]………！
[sync][wait][clear][end]

msg_12:
[color(yellow)]舞耶[color(white)]
[tab]………！
[sync][wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]そうか…
[tab]人生、なかなか思い通りにいかないもんだな…
[sync][wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]せめて、[tatsuya]くらいには…
[sync][wait][clear][end]

msg_15:
[color(yellow)]克哉[color(white)]
[tab]そうか…そうだな…
[sync][wait][clear][end]

msg_16:
[color(yellow)]克哉[color(white)]
[tab]君は…強いな。
[sync][wait][clear][end]
