function START()
{
    timerClear();
    bitClear(EBIT_NOSAVE_B);
    bitSet(EBIT_CHUKEITEN1);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    levelFootstepSet(sfx_1a);
    sndIdGet(var_0);
    bne(var_0, -1, label_9);
    b(label_b);
  label_9:
    sndVolumeFadeTo(var_0, 0, 5);
    b(label_b);
  label_b:
    sndUnkCF(0);
    sndMusicPlay(sound_3156, 60);
    ref_d = spriteLoad(sprite_0);
    wait(ref_d);
    ref_f = spriteLoad(sprite_2);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_1);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_6);
    wait(ref_13);
    ref_15 = spriteLoad(sprite_d);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_13);
    wait(ref_17);
    ref_19 = spriteLoad(sprite_1f);
    wait(ref_19);
    unknownVar1(var_0);
    bne(var_0, 1793, label_22);
    cameraSetNorth(east);
    cameraSet(northeast, 930, 0, -80);
    playerInit(north);
    controlDisable();
    b(label_2d);
  label_22:
    bne(var_0, 6915, label_28);
    cameraSetNorth(east);
    cameraSet(northeast, 980, 0, -330);
    playerInit(east);
    controlDisable();
    b(label_2d);
  label_28:
    cameraSetNorth(east);
    cameraSet(northeast, 980, 0, -330);
    playerInit(east);
    controlDisable();
    b(label_2d);
  label_2d:
    unitSpawn(ulala, sprite_6, 280, -300, -700, east, none);
    unitAnimationPlay(ulala, animation_a, 1);
    unitSpawn(katsuya, sprite_d, 800, 0, -950, south, none);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitSpawn(baofu, sprite_13, 80, -300, -500, north, none);
    unitAnimationPlay(baofu, animation_a, 1);
    unitSpawn(nanjo, sprite_1f, 980, 0, -700, east, none);
    unitAnimationPlay(nanjo, animation_a, 1);
    unitIdleOnAll();
    unitTriggerSet(ulala, URARA, 255, 1);
    unitTriggerSet(katsuya, KATUYA, 255, 1);
    unitTriggerSet(baofu, PAOFU, 255, 1);
    unitTriggerSet(nanjo, NANJO, 255, 1);
    envTriggerSet(RED_DOOR, 131, 1, line, coll_14);
    envTriggerSet(BLUE_DOOR, 14, 1, line, coll_13);
    envTriggerSet(EXIT_BLUE, 56, 1, line, coll_8);
    envTriggerSet(EXIT_RED, 224, 1, line, coll_5);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function NANJO()
{
    controlDisable();
    unitFacePlayer(nanjo);
    ref_47 = bustupLoad(bustup_36);
    bustupWait(ref_47);
    ref_49 = bustupAlloc(ref_47, left, rgb(0,0,0));
    bustupFade(ref_49, rgb(128,0,0), 30);
    ref_4b = dialogAlloc();
    ref_4c = msgShow(msg_0);
/***************************************
[color(yellow)]南条[color(white)]
[tab]しかし桐島の奴、いらぬ気を回したものだ…
[tab]あの二人は、神取と浅からぬ因縁があるからと
[tab]俺が連絡しなかったものを…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_4c);
    dialogFree(ref_4b);
    ref_53 = bustupFade(ref_49, rgb(0,0,0), 10);
    bustupWait(ref_53);
    bustupFree(ref_49);
    ref_56 = bustupLoad(bustup_37);
    bustupWait(ref_56);
    ref_58 = bustupAlloc(ref_56, left, rgb(0,0,0));
    bustupFade(ref_58, rgb(128,0,0), 30);
    ref_5a = dialogAlloc();
    ref_5b = msgShow(msg_1);
/***************************************
[color(yellow)]南条[color(white)]
[tab]まあ、それがわかっているから、
[tab]自分で行きたいのをこらえたのだろうがな…
[tab]流石、俺が認めた奴らだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5b);
    dialogFree(ref_5a);
    ref_5f = bustupFade(ref_58, rgb(0,0,0), 10);
    bustupWait(ref_5f);
    bustupFree(ref_58);
    unitAnimationPlay(nanjo, animation_a, 1);
    unitRestoreFacing(nanjo);
    controlEnable();
}

function KATUYA()
{
    controlDisable();
    unitFacePlayer(katsuya);
    ref_68 = bustupLoad(bustup_21);
    bustupWait(ref_68);
    ref_6a = bustupAlloc(ref_68, left, rgb(0,0,0));
    bustupFade(ref_6a, rgb(128,0,0), 30);
    ref_6c = dialogAlloc();
    ref_6d = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]言葉がなくても分かり合える関係か…
[tab]少し、南条君がうらやましいな。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_6d);
    dialogFree(ref_6c);
    ref_74 = bustupFade(ref_6a, rgb(0,0,0), 10);
    bustupWait(ref_74);
    bustupFree(ref_6a);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitRestoreFacing(katsuya);
    controlEnable();
}

function PAOFU()
{
    controlDisable();
    ref_7c = bustupLoad(bustup_30);
    bustupWait(ref_7c);
    ref_7e = bustupAlloc(ref_7c, left, rgb(0,0,0));
    bustupFade(ref_7e, rgb(128,0,0), 30);
    ref_80 = dialogAlloc();
    ref_81 = msgShow(msg_3);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]そいつはどうかな…
[tab]所詮、人間なんざ一人だぜ…
[sync][wait][clear]
***************************************/
    unitLookAtUnit(baofu, ulala);
    unitLookAtUnit(ulala, baofu);
    unitLookAtUnit(katsuya, baofu);
    unitLookAtUnit(nanjo, baofu);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_81);
    dialogFree(ref_80);
    ref_8b = bustupFade(ref_7e, rgb(0,0,0), 10);
    bustupWait(ref_8b);
    bustupFree(ref_7e);
    unitAnimationPlay(baofu, animation_a, 1);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(ulala, animation_a, 1);
    unitAnimationPlay(nanjo, animation_a, 1);
    controlEnable();
}

function URARA()
{
    controlDisable();
    unitFacePlayer(ulala);
    ref_96 = bustupLoad(bustup_18);
    bustupWait(ref_96);
    ref_98 = bustupAlloc(ref_96, left, rgb(0,0,0));
    bustupFade(ref_98, rgb(128,0,0), 30);
    ref_9a = dialogAlloc();
    ref_9b = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]私とアンタも、長い付き合いだもんねぇ…
[tab]ま、人と人の関係なんて、時間の長さで
[tab]決まるもんじゃないけどさ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_9b);
    dialogFree(ref_9a);
    ref_a2 = bustupFade(ref_98, rgb(0,0,0), 10);
    bustupWait(ref_a2);
    bustupFree(ref_98);
    unitAnimationPlay(ulala, animation_a, 1);
    unitRestoreFacing(ulala);
    controlEnable();
}

function RED_DOOR()
{
    controlDisable();
    playerConvertToUnit(maya, sprite_1, north);
    playerHide();
    unitAnimationPlay(maya, animation_5, 1);
    sndMusicPlay(sound_3154, 127);
    unitWait(maya);
    delayClear();
    delayWait(30);
    ref_b1 = dialogAlloc();
    ref_b2 = bustupLoad(bustup_10a);
    bustupWait(ref_b2);
    ref_b4 = bustupAlloc(ref_b2, right, rgb(0,0,0));
    bustupFade(ref_b4, rgb(128,0,0), 30);
    ref_b6 = msgShow(msg_5);
/***************************************
[color(yellow)]麻希の声[color(white)]
[tab]御用でござるか？
[tab]なんちゃって♥
[tab]こっちのドアでいいのね？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_b6);
    ref_b9 = bustupFade(ref_b4, rgb(0,0,0), 10);
    bustupWait(ref_b9);
    bustupFree(ref_b4);
    dialogFree(ref_b1);
    ref_bd = bustupLoad(bustup_1);
    bustupWait(ref_bd);
    ref_bf = bustupAlloc(ref_bd, center, rgb(0,0,0));
    bustupFade(ref_bf, rgb(128,0,0), 30);
    ref_c1 = dialogChoiceAlloc();
    ref_c2 = msgShow(msg_6);
/***************************************
[tab]こっちのドアでいいのね？
[choice(2)]こちらにするでござる！なんちゃって♥
しばし待たれよ。なんちゃって♥
[end_choice][clear]
***************************************/
    sync();
    wait(ref_c2);
    dialogFree(ref_c1);
    ref_c6 = bustupFade(ref_bf, rgb(0,0,0), 10);
    bustupWait(ref_c6);
    bustupFree(ref_bf);
    choiceGetResult(var_3);
    bne(var_3, 0, label_eb);
    ref_cb = dialogAlloc();
    ref_cc = bustupLoad(bustup_10a);
    bustupWait(ref_cc);
    ref_ce = bustupAlloc(ref_cc, right, rgb(0,0,0));
    bustupFade(ref_ce, rgb(128,0,0), 30);
    ref_d0 = msgShow(msg_7);
/***************************************
[color(yellow)]麻希の声[color(white)]
[tab]クス…私、この街好きよ…
[tab]天野さんとも気が合うみたいだし…
[tab]じゃ、開けるね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d0);
    ref_d3 = bustupFade(ref_ce, rgb(0,0,0), 10);
    bustupWait(ref_d3);
    bustupFree(ref_ce);
    dialogFree(ref_cb);
    delayClear();
    delayWait(30);
    unitDespawn(maya, none);
    playerInit(north);
    controlDisable();
    timerSet(600, event_90);
    bitSet(EBIT_MAKI1);
    bitSet(EBIT_NOSAVE_B);
    objAnimRotate(obj_3, 0, 80, 0, 60, 0);
    sndMusicPlay(sound_3155, 127);
    objAnimWait(obj_3);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    cameraSetNorth(east);
    dngLoad2(sewer1-2);
    b(label_ff);
  label_eb:
    bne(var_3, 1, label_ff);
    ref_ec = dialogAlloc();
    ref_ed = bustupLoad(bustup_10a);
    bustupWait(ref_ed);
    ref_ef = bustupAlloc(ref_ed, right, rgb(0,0,0));
    bustupFade(ref_ef, rgb(128,0,0), 30);
    ref_f1 = msgShow(msg_8);
/***************************************
[color(yellow)]麻希の声[color(white)]
[tab]クス…私、この街好きよ…
[tab]天野さんとも気が合うみたいだし…
[tab]じゃあ、決めたらまた連絡してね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f1);
    ref_f4 = bustupFade(ref_ef, rgb(0,0,0), 10);
    bustupWait(ref_f4);
    bustupFree(ref_ef);
    dialogFree(ref_ec);
    delayClear();
    delayWait(30);
    unitDespawn(maya, none);
    playerInit(north);
    controlDisable();
    controlEnable();
    b(label_ff);
  label_ff:
}

function BLUE_DOOR()
{
    controlDisable();
    playerConvertToUnit(maya, sprite_1, east);
    playerHide();
    unitAnimationPlay(maya, animation_5, 1);
    sndMusicPlay(sound_3154, 127);
    unitWait(maya);
    delayClear();
    delayWait(30);
    ref_108 = dialogAlloc();
    ref_109 = bustupLoad(bustup_10a);
    bustupWait(ref_109);
    ref_10b = bustupAlloc(ref_109, right, rgb(0,0,0));
    bustupFade(ref_10b, rgb(128,0,0), 30);
    ref_10d = msgShow(msg_9);
/***************************************
[color(yellow)]玲司の声[color(white)]
[tab]どうだ調子は…？
[tab]こっちを開けるんだな？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_10d);
    ref_110 = bustupFade(ref_10b, rgb(0,0,0), 10);
    bustupWait(ref_110);
    bustupFree(ref_10b);
    dialogFree(ref_108);
    ref_114 = bustupLoad(bustup_1);
    bustupWait(ref_114);
    ref_116 = bustupAlloc(ref_114, center, rgb(0,0,0));
    bustupFade(ref_116, rgb(128,0,0), 30);
    ref_118 = dialogChoiceAlloc();
    ref_119 = msgShow(msg_10);
/***************************************
[tab]こっちを開けるんだな？
[choice(2)]レッツらゴー！ドーゾ。
う～ん、やっぱちょっと待って、ドーゾ。
[end_choice][clear]
***************************************/
    sync();
    wait(ref_119);
    dialogFree(ref_118);
    ref_11d = bustupFade(ref_116, rgb(0,0,0), 10);
    bustupWait(ref_11d);
    bustupFree(ref_116);
    choiceGetResult(var_4);
    bne(var_4, 0, label_14b);
    ref_122 = dialogAlloc();
    ref_123 = bustupLoad(bustup_10a);
    bustupWait(ref_123);
    ref_125 = bustupAlloc(ref_123, right, rgb(0,0,0));
    bustupFade(ref_125, rgb(128,0,0), 30);
    ref_127 = msgShow(msg_11);
/***************************************
[color(yellow)]玲司の声[color(white)]
[tab]よし、待ってろ…
[tab]どぉりゃあぁー！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_127);
    ref_12a = bustupLoad(bustup_5);
    bustupWait(ref_12a);
    ref_12c = bustupAlloc(ref_12a, left, rgb(0,0,0));
    bustupFade(ref_12c, rgb(128,0,0), 30);
    ref_12e = msgShow(msg_12);
/***************************************
[color(yellow)]玲司の声[color(white)]
[tab]ぐわっ…！
[tab]ビリッときたぜ…やるじゃねぇか。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12e);
    ref_131 = bustupFade(ref_125, rgb(0,0,0), 10);
    bustupWait(ref_131);
    bustupFree(ref_125);
    dialogFree(ref_122);
    ref_135 = bustupFade(ref_12c, rgb(0,0,0), 10);
    bustupWait(ref_135);
    bustupFree(ref_12c);
    delayClear();
    delayWait(30);
    unitDespawn(maya, none);
    playerInit(east);
    controlDisable();
    timerSet(600, event_90);
    bitSet(EBIT_NOSAVE_B);
    objAnimRotate(obj_2, 0, 80, 0, 60, 0);
    sndMusicPlay(sound_3155, 127);
    objAnimWait(obj_2);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    cameraSetNorth(east);
    dngLoad2(sewer2-1);
    b(label_15f);
  label_14b:
    bne(var_4, 1, label_15f);
    ref_14c = dialogAlloc();
    ref_14d = bustupLoad(bustup_10a);
    bustupWait(ref_14d);
    ref_14f = bustupAlloc(ref_14d, right, rgb(0,0,0));
    bustupFade(ref_14f, rgb(128,0,0), 30);
    ref_151 = msgShow(msg_13);
/***************************************
[color(yellow)]玲司の声[color(white)]
[tab]チッ…身体がなまっちまうぜ…
[tab]決めたらまた連絡よこしな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_151);
    ref_154 = bustupFade(ref_14f, rgb(0,0,0), 10);
    bustupWait(ref_154);
    bustupFree(ref_14f);
    dialogFree(ref_14c);
    delayClear();
    delayWait(30);
    unitDespawn(maya, none);
    playerInit(east);
    controlDisable();
    controlEnable();
    b(label_15f);
  label_15f:
}

function EXIT_RED()
{
    controlDisable();
    unitAnimationPlay(nanjo, animation_b, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(nanjo, animation_c, 1);
    cameraRotateTo(1, 60);
    ref_166 = cameraMoveTo(980, 0, -700, 60);
    wait(ref_166);
    ref_168 = bustupLoad(bustup_36);
    bustupWait(ref_168);
    ref_16a = bustupAlloc(ref_168, left, rgb(0,0,0));
    bustupFade(ref_16a, rgb(128,0,0), 30);
    ref_16c = dialogAlloc();
    ref_16d = msgShow(msg_14);
/***************************************
[color(yellow)]南条[color(white)]
[tab]天野さん、もう後戻りはできない。
[tab]前進あるのみだ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_16d);
    dialogFree(ref_16c);
    ref_171 = bustupFade(ref_16a, rgb(0,0,0), 10);
    bustupWait(ref_171);
    bustupFree(ref_16a);
    playerConvertToUnit(maya, sprite_0, west);
    playerHide();
    ref_176 = cameraLookAtUnit(maya, 0, 60);
    wait(ref_176);
    unitDespawn(maya, none);
    playerInit(west);
    controlDisable();
    unitAnimationPlay(nanjo, animation_a, 1);
    controlEnable();
}

function EXIT_BLUE()
{
    controlDisable();
    unitAnimationPlay(nanjo, animation_b, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(nanjo, animation_c, 1);
    cameraRotateTo(1, 60);
    ref_184 = cameraMoveTo(980, 0, -700, 60);
    wait(ref_184);
    ref_186 = bustupLoad(bustup_36);
    bustupWait(ref_186);
    ref_188 = bustupAlloc(ref_186, left, rgb(0,0,0));
    bustupFade(ref_188, rgb(128,0,0), 30);
    ref_18a = dialogAlloc();
    ref_18b = msgShow(msg_15);
/***************************************
[color(yellow)]南条[color(white)]
[tab]天野さん、もう後戻りはできない。
[tab]前進あるのみだ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_18b);
    dialogFree(ref_18a);
    ref_18f = bustupFade(ref_188, rgb(0,0,0), 10);
    bustupWait(ref_18f);
    bustupFree(ref_188);
    playerConvertToUnit(maya, sprite_0, south);
    playerHide();
    ref_194 = cameraLookAtUnit(maya, 0, 60);
    wait(ref_194);
    unitDespawn(maya, none);
    playerInit(south);
    controlDisable();
    unitAnimationPlay(nanjo, animation_a, 1);
    controlEnable();
}
