
msg_0:
[color(yellow)]パオフゥ[color(white)]
[tab]俺がどう生きてこようが、お前にゃ関係ねぇ…
[tab]傷口舐めて欲しきゃ、他の奴にあたるんだな…
[sync][wait][clear][end]

msg_1:
[color(yellow)]水野編集長[color(white)]
[tab]ん…天野…？
[sync][wait][clear][end]

msg_2:
[color(yellow)]水野編集長[color(white)]
[tab]まさかあの子…
[tab]抜け駆けする気！？
[sync][wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
[tab]チッ…バレやがった…
[sync][wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
[tab]しゃーねぇ…始めるぞ。
[sync][wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]ああ、そうでしょうとも！！
[tab]私にゃ関係ないわよ！！
[tab]なぁによ偉そうに！！
[sync][wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]そうやって何でもかんでも秘密にして、
[tab]いつまでも人を見下してりゃいいわ！！
[sync][wait][clear][end]

msg_7:
[color(yellow)]パオフゥ[color(white)]
[tab]や、やけに真に迫った芝居じゃねぇか…
[tab]よ、よし…
[sync][wait][clear][end]

msg_8:
[color(yellow)]パオフゥ[color(white)]
[tab]「よ、寄り掛かられるのは迷惑だぜぃ。
[tab][tab]そんなんだから、いつまでも男に
[tab][tab]逃げられるんだぜぃ。このＣＤ女」
[sync][wait][clear][end]

msg_9:
[color(yellow)]うらら[color(white)]
[tab]なにおぅ！？
[tab]でっかいお世話よ！！
[sync][wait][clear][end]

msg_10:
[color(yellow)]パオフゥ[color(white)]
[tab]ば、馬鹿野郎…本気で殴るんじゃねぇ！
[tab]酔ってんのか！？
[sync][wait][clear][end]

msg_11:
[color(yellow)]うらら[color(white)]
[tab]うるせぇー！[tab]このクサレ野郎ぅ！！
[tab]気にしてることをー！！
[sync][wait][clear][end]

msg_12:
[color(yellow)]パオフゥ[color(white)]
[tab]ち、違…天野が…
[sync][wait][clear][end]

msg_13:
[color(yellow)]水野編集長[color(white)]
[tab]ちょっと！！
[tab]痴話げんかなら他でやって頂戴！！
[tab]ターゲットが逃げるでしょ！？
[sync][wait][clear][end]

msg_14:
[color(yellow)]マスコミの方々[color(white)]
[tab]なんだって！？
[tab]どこどこ！？
[sync][wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]のわぁー！？
[sync][wait][clear][end]
