function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_300e, 127);
    levelFootstepSet(sfx_19);
    screenNarrow(3);
    cameraSet(northeast, 1000, -100, -780);
    ref_6 = spriteLoad(sprite_7);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_14);
    wait(ref_8);
    ref_a = spriteLoad(sprite_98);
    wait(ref_a);
    ref_c = spriteLoad(sprite_56);
    wait(ref_c);
    ref_e = spriteLoad(sprite_c0);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_c2);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_ca);
    wait(ref_12);
    unitSpawn(ulala, sprite_7, 1000, -60, -780, north, none);
    unitSpawn(baofu, sprite_14, 875, -60, -780, north, none);
    unitAnimationPlay(ulala, animation_14, 1);
    unitAnimationPlay(baofu, animation_2a, 1);
    unitSpawn(unit_63, sprite_14, 875, -60, -780, north, none);
    unitAnimationPlay(unit_63, animation_48, 1);
    unitShadowRadius(unit_63, 0);
    unitSpawn(npc1, sprite_98, 1000, -20, -970, south, none);
    unitAnimationPlay(npc1, animation_30, 1);
    unitSpawn(unit_1f, sprite_56, 1320, 0, -250, east, none);
    unitSpawn(unit_58, sprite_c2, 1225, 0, -325, south, none);
    unitSpawn(npc2, sprite_c0, 1210, 0, -150, north, none);
    unitSpawn(npc3, sprite_c0, 1120, 0, -230, west, none);
    unitPalette(npc3, 1);
    unitAnimationPlay(unit_1f, animation_31, 1);
    unitAnimationPlay(unit_58, animation_2a, 1);
    unitAnimationPlay(npc2, animation_29, 1);
    unitAnimationPlay(npc3, animation_28, 1);
    unitSpawn(npc4, sprite_ca, 260, 0, -175, east, none);
    unitPalette(npc4, 1);
    unitSpawn(npc5, sprite_c0, 260, 0, -310, east, none);
    unitPalette(npc5, 2);
    unitSpawn(unit_59, sprite_c2, 75, 0, -175, west, none);
    unitPalette(unit_59, 1);
    unitSpawn(npc6, sprite_ca, 50, 0, -310, west, none);
    unitAnimationPlay(npc4, animation_28, 1);
    unitAnimationPlay(npc5, animation_2a, 1);
    unitAnimationPlay(unit_59, animation_28, 1);
    unitAnimationPlay(npc6, animation_29, 1);
    objAnimTranslate(obj_35, 0, 0, -30, 1);
    objAnimTranslate(obj_36, 0, 0, -30, 1);
    objAnimTranslate(obj_37, 0, 0, -30, 1);
    objAnimTranslate(obj_38, 0, 0, -30, 1);
    objAnimTranslate(obj_39, 0, 0, -30, 1);
    objAnimTranslate(obj_3a, 0, 0, -30, 1);
    objAnimTranslate(obj_34, -50, 0, 0, 1);
    objAnimTranslate(obj_a, -50, 0, 0, 1);
    objAnimTranslate(obj_b, -50, 0, 0, 1);
    objAnimTranslate(obj_41, -50, 0, 0, 1);
    objAnimTranslate(obj_2, -130, 0, 0, 1);
    objAnimTranslate(obj_3, -130, 0, 0, 1);
    objAnimTranslate(obj_31, -50, 0, 0, 1);
    objAnimTranslate(obj_c, -50, 0, 0, 1);
    objAnimTranslate(obj_d, -50, 0, 0, 1);
    objAnimTranslate(obj_40, -50, 0, 0, 1);
    objAnimTranslate(obj_4, -110, 0, 0, 1);
    objAnimTranslate(obj_5, -110, 0, 0, 1);
    objAnimTranslate(obj_6, -110, 0, 0, 1);
    objAnimTranslate(obj_1a, -80, 0, 0, 1);
    objAnimTranslate(obj_1b, 0, 0, 115, 1);
    objAnimTranslate(obj_1c, 75, 0, 0, 1);
    objAnimTranslate(obj_1d, 0, 0, -70, 1);
    objVisible(obj_29, false);
    objVisible(obj_48, false);
    objVisible(obj_34, false);
    objVisible(obj_a, false);
    objVisible(obj_b, false);
    objVisible(obj_41, false);
    objVisible(obj_2, false);
    objVisible(obj_3, false);
    objVisible(obj_31, false);
    objVisible(obj_c, false);
    objVisible(obj_d, false);
    objVisible(obj_40, false);
    objVisible(obj_4, false);
    objVisible(obj_5, false);
    objVisible(obj_6, false);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(120);
    unitAnimationPlay(baofu, animation_25, 1);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_2a, 1);
    ref_61 = bustupLoad(bustup_31);
    bustupWait(ref_61);
    ref_63 = bustupAlloc(ref_61, left, rgb(0,0,0));
    bustupFade(ref_63, rgb(128,0,0), 30);
    ref_65 = dialogAlloc();
    ref_66 = msgShow(msg_0);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]俺がどう生きてこようが、お前にゃ関係ねぇ…
[tab]傷口舐めて欲しきゃ、他の奴にあたるんだな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_66);
    dialogFree(ref_65);
    ref_6a = bustupFade(ref_63, rgb(0,0,0), 10);
    bustupWait(ref_6a);
    bustupFree(ref_63);
    unitAnimationPlay(ulala, animation_16, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_29, 1);
    ref_71 = cameraMoveTo(1250, 0, -300, 60);
    wait(ref_71);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_1f, animation_32, 1);
    ref_76 = bustupLoad(bustup_5b);
    bustupWait(ref_76);
    ref_78 = bustupAlloc(ref_76, right, rgb(0,0,0));
    bustupFade(ref_78, rgb(128,0,0), 30);
    ref_7a = dialogAlloc();
    ref_7b = msgShow(msg_1);
/***************************************
[color(yellow)]水野編集長[color(white)]
[tab]ん…天野…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7b);
    dialogFree(ref_7a);
    ref_7f = bustupFade(ref_78, rgb(0,0,0), 10);
    bustupWait(ref_7f);
    bustupFree(ref_78);
    unitAnimationPlay(baofu, animation_27, 1);
    unitAnimationPlay(unit_1f, animation_1, 1);
    sndMusicPlay(sound_314a, 127);
    objAnimTranslate(obj_1a, 30, 0, 0, 10);
    objAnimWait(obj_1a);
    delayClear();
    delayWait(60);
    unitFace(baofu, west);
    unitAnimationPlay(baofu, animation_26, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_28, 1);
    unitMove(unit_1f, 1320, -30, face_east, fast);
    unitAnimationPlay(unit_58, animation_28, 1);
    unitAnimationPlay(npc2, animation_28, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc2, animation_2a, 1);
    delayClear();
    delayWait(8);
    unitFace(npc2, east);
    unitAnimationPlay(npc2, animation_28, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc2, animation_29, 1);
    unitAnimationPlay(npc3, animation_2a, 1);
    unitWait(unit_1f);
    unitMove(unit_1f, 1240, -30, face_south, fast);
    unitWait(unit_1f);
    unitAnimationPlay(unit_1f, animation_1, 1);
    ref_a0 = bustupLoad(bustup_5b);
    bustupWait(ref_a0);
    ref_a2 = bustupAlloc(ref_a0, right, rgb(0,0,0));
    bustupFade(ref_a2, rgb(128,0,0), 30);
    ref_a4 = dialogAlloc();
    ref_a5 = msgShow(msg_2);
/***************************************
[color(yellow)]水野編集長[color(white)]
[tab]まさかあの子…
[tab]抜け駆けする気！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a5);
    dialogFree(ref_a4);
    ref_a9 = bustupFade(ref_a2, rgb(0,0,0), 10);
    bustupWait(ref_a9);
    bustupFree(ref_a2);
    ref_ac = spriteLoad(sprite_6);
    wait(ref_ac);
    ref_ae = cameraMoveTo(1000, -160, -780, 60);
    wait(ref_ae);
    ref_b0 = spriteLoad(sprite_13);
    wait(ref_b0);
    unitAnimationPlay(baofu, animation_26, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_27, 1);
    ref_b6 = bustupLoad(bustup_2c);
    bustupWait(ref_b6);
    ref_b8 = bustupAlloc(ref_b6, left, rgb(0,0,0));
    bustupFade(ref_b8, rgb(128,0,0), 30);
    ref_ba = dialogAlloc();
    ref_bb = msgShow(msg_3);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]チッ…バレやがった…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_bb);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitSpawn(baofu, sprite_13, 875, -20, -780, west, none);
    unitAnimationPlay(baofu, animation_1, 1);
    unitMove(baofu, 930, -780, face_west, medium);
    ref_c3 = msgShow(msg_4);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]しゃーねぇ…始めるぞ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c3);
    dialogFree(ref_ba);
    ref_c7 = bustupFade(ref_b8, rgb(0,0,0), 10);
    bustupWait(ref_c7);
    bustupFree(ref_b8);
    unitWait(baofu);
    delayClear();
    delayWait(60);
    unitSpawn(unit_62, sprite_7, 1000, -60, -780, north, none);
    unitAnimationPlay(unit_62, animation_18, 1);
    unitShadowRadius(unit_62, 0);
    unitAnimationPlay(ulala, animation_b, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(ulala, animation_d, 1);
    ref_d4 = sndVolumeFadeTo(sound_300e, 0, 360);
    ref_d5 = bustupLoad(bustup_19);
    bustupWait(ref_d5);
    ref_d7 = bustupAlloc(ref_d5, left, rgb(0,0,0));
    bustupFade(ref_d7, rgb(128,0,0), 30);
    ref_d9 = dialogAlloc();
    ref_da = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ああ、そうでしょうとも！！
[tab]私にゃ関係ないわよ！！
[tab]なぁによ偉そうに！！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(60);
    unitAnimationHold(baofu, animation_21, 30);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(unit_1f, animation_2, 1);
    delayClear();
    delayWait(10);
    unitFace(unit_1f, east);
    unitAnimationPlay(unit_1f, animation_3, 1);
    unitAnimationPlay(unit_58, animation_29, 1);
    unitAnimationPlay(npc2, animation_28, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc2, animation_2a, 1);
    unitAnimationPlay(npc3, animation_28, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc3, animation_29, 1);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitSpawn(ulala, sprite_6, 1000, -20, -780, north, none);
    unitAnimationPlay(ulala, animation_3, 1);
    sync();
    wait(ref_da);
    dialogFree(ref_d9);
    ref_f4 = bustupFade(ref_d7, rgb(0,0,0), 10);
    bustupWait(ref_f4);
    bustupFree(ref_d7);
    unitWait(baofu);
    cameraMoveTo(1000, -70, -520, 120);
    unitMove(baofu, 930, -630, face_north, reverse);
    unitAnimationPlay(ulala, animation_4, 1);
    delayClear();
    delayWait(12);
    unitFace(ulala, east);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(ulala, animation_1, 1);
    unitWait(baofu);
    unitMove(ulala, 930, -710, face_south, fast);
    unitWait(ulala);
    ref_105 = spriteLoad(sprite_14);
    wait(ref_105);
    unitAnimationPlay(ulala, animation_2f, 1);
    ref_108 = bustupLoad(bustup_19);
    bustupWait(ref_108);
    ref_10a = bustupAlloc(ref_108, left, rgb(0,0,0));
    bustupFade(ref_10a, rgb(128,0,0), 30);
    ref_10c = dialogAlloc();
    ref_10d = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]そうやって何でもかんでも秘密にして、
[tab]いつまでも人を見下してりゃいいわ！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_10d);
    dialogFree(ref_10c);
    ref_111 = bustupFade(ref_10a, rgb(0,0,0), 10);
    bustupWait(ref_111);
    bustupFree(ref_10a);
    unitAnimationPlay(ulala, animation_a, 1);
    unitMove(baofu, 910, -520, face_north, reverse);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_b, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_c, 1);
    ref_11b = spriteLoad(sprite_15);
    wait(ref_11b);
    ref_11d = sndLoad(sound_303a);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_b, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_a, 1);
    wait(ref_d4);
    wait(ref_11d);
    sndMusicPlay(sound_303a, 127);
    ref_127 = bustupLoad(bustup_2c);
    bustupWait(ref_127);
    ref_129 = bustupAlloc(ref_127, left, rgb(0,0,0));
    bustupFade(ref_129, rgb(128,0,0), 30);
    ref_12b = dialogAlloc();
    ref_12c = msgShow(msg_7);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]や、やけに真に迫った芝居じゃねぇか…
[tab]よ、よし…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12c);
    dialogFree(ref_12b);
    ref_130 = bustupFade(ref_129, rgb(0,0,0), 10);
    bustupWait(ref_130);
    bustupFree(ref_129);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_14);
    unitAnimationPlay(baofu, animation_35, 1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_314b, 127);
    unitWait(baofu);
    delayClear();
    delayWait(60);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_d, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_e, 1);
    ref_145 = bustupLoad(bustup_2c);
    bustupWait(ref_145);
    ref_147 = bustupAlloc(ref_145, left, rgb(0,0,0));
    bustupFade(ref_147, rgb(128,0,0), 30);
    ref_149 = dialogAlloc();
    ref_14a = msgShow(msg_8);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]「よ、寄り掛かられるのは迷惑だぜぃ。
[tab][tab]そんなんだから、いつまでも男に
[tab][tab]逃げられるんだぜぃ。このＣＤ女」
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_14a);
    dialogFree(ref_149);
    ref_14e = bustupFade(ref_147, rgb(0,0,0), 10);
    bustupWait(ref_14e);
    bustupFree(ref_147);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_2f, 1);
    ref_154 = spriteLoad(sprite_7);
    wait(ref_154);
    ref_156 = bustupLoad(bustup_19);
    bustupWait(ref_156);
    ref_158 = bustupAlloc(ref_156, left, rgb(0,0,0));
    bustupFade(ref_158, rgb(128,0,0), 30);
    ref_15a = dialogAlloc();
    ref_15b = msgShow(msg_9);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なにおぅ！？
[tab]でっかいお世話よ！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_15b);
    dialogFree(ref_15a);
    ref_15f = bustupFade(ref_158, rgb(0,0,0), 10);
    bustupWait(ref_15f);
    bustupFree(ref_158);
    unitMove(ulala, 950, -600, face_south, fastest);
    unitWait(ulala);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_7);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(80);
    sndMusicPlay(sound_314c, 127);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitFace(baofu, north);
    unitAnimationPlay(baofu, animation_47, 1);
    unitWait(ulala);
    unitMove(baofu, 930, -500, face_north, fastest);
    unitAnimationPlay(baofu, animation_47, 1);
    unitFace(baofu, north);
    unitWait(baofu);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitAnimationPlay(baofu, animation_15, 1);
    ref_176 = spriteLoad(sprite_6);
    wait(ref_176);
    ref_178 = bustupLoad(bustup_32);
    bustupWait(ref_178);
    ref_17a = bustupAlloc(ref_178, left, rgb(0,0,0));
    bustupFade(ref_17a, rgb(128,0,0), 30);
    ref_17c = dialogAlloc();
    ref_17d = msgShow(msg_10);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ば、馬鹿野郎…本気で殴るんじゃねぇ！
[tab]酔ってんのか！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_17d);
    dialogFree(ref_17c);
    ref_181 = bustupFade(ref_17a, rgb(0,0,0), 10);
    bustupWait(ref_181);
    bustupFree(ref_17a);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    objVisible(obj_34, true);
    objVisible(obj_a, true);
    objVisible(obj_b, true);
    objVisible(obj_41, true);
    objVisible(obj_2, true);
    objVisible(obj_3, true);
    objVisible(obj_4, true);
    unitDespawn(unit_62, none);
    unitDespawn(unit_63, none);
    cameraMoveTo(450, 0, -190, 120);
    cameraRotateTo(7, 1);
    unitMove(baofu, 450, -500, face_south, fast);
    delayClear();
    delayWait(20);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitMove(ulala, 450, -600, face_south, fastest);
    unitWait(baofu);
    unitMove(baofu, 450, -50, face_north, fastest);
    unitWait(ulala);
    unitMove(ulala, 450, -130, face_south, fastest);
    unitWait(baofu);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitAnimationPlay(baofu, animation_15, 1);
    unitWait(ulala);
    ref_1a0 = spriteLoad(sprite_8);
    wait(ref_1a0);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_8);
    ref_1a4 = bustupLoad(bustup_19);
    bustupWait(ref_1a4);
    ref_1a6 = bustupAlloc(ref_1a4, left, rgb(0,0,0));
    bustupFade(ref_1a6, rgb(128,0,0), 30);
    ref_1a8 = dialogAlloc();
    ref_1a9 = msgShow(msg_11);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]うるせぇー！[tab]このクサレ野郎ぅ！！
[tab]気にしてることをー！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1a9);
    dialogFree(ref_1a8);
    ref_1ad = bustupFade(ref_1a6, rgb(0,0,0), 10);
    bustupWait(ref_1ad);
    bustupFree(ref_1a6);
    unitAnimationPlay(ulala, animation_5, 1);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_314d, 127);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitAnimationPlay(baofu, animation_47, 1);
    unitWait(ulala);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitAnimationPlay(baofu, animation_15, 1);
    ref_1bb = bustupLoad(bustup_32);
    bustupWait(ref_1bb);
    ref_1bd = bustupAlloc(ref_1bb, left, rgb(0,0,0));
    bustupFade(ref_1bd, rgb(128,0,0), 30);
    ref_1bf = dialogAlloc();
    ref_1c0 = msgShow(msg_12);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ち、違…天野が…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1c0);
    dialogFree(ref_1bf);
    ref_1c4 = bustupFade(ref_1bd, rgb(0,0,0), 10);
    bustupWait(ref_1c4);
    bustupFree(ref_1bd);
    unitMove(unit_1f, 1045, -30, face_north, fastest);
    unitWait(unit_1f);
    unitMove(unit_1f, 1045, -460, face_east, fastest);
    unitWait(unit_1f);
    unitMove(unit_1f, 450, -460, face_south, fastest);
    unitWait(unit_1f);
    unitMove(unit_1f, 450, -240, face_south, fastest);
    unitWait(unit_1f);
    unitAnimationPlay(unit_1f, animation_2f, 1);
    ref_1d0 = bustupLoad(bustup_5b);
    bustupWait(ref_1d0);
    ref_1d2 = bustupAlloc(ref_1d0, right, rgb(0,0,0));
    bustupFade(ref_1d2, rgb(128,0,0), 30);
    ref_1d4 = dialogAlloc();
    ref_1d5 = msgShow(msg_13);
/***************************************
[color(yellow)]水野編集長[color(white)]
[tab]ちょっと！！
[tab]痴話げんかなら他でやって頂戴！！
[tab]ターゲットが逃げるでしょ！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1d5);
    dialogFree(ref_1d4);
    ref_1d9 = bustupFade(ref_1d2, rgb(0,0,0), 10);
    bustupWait(ref_1d9);
    bustupFree(ref_1d2);
    ref_1dc = dialogAlloc();
    ref_1dd = msgShow(msg_14);
/***************************************
[color(yellow)]マスコミの方々[color(white)]
[tab]なんだって！？
[tab]どこどこ！？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_1e, 1);
    unitAnimationPlay(npc5, animation_1e, 1);
    unitAnimationPlay(unit_59, animation_1e, 1);
    unitAnimationPlay(npc6, animation_1e, 1);
    unitMove(npc6, 75, -310, face_east, fast);
    delayClear();
    delayWait(5);
    unitFace(npc6, west);
    sndMusicPlay(sound_314a, 127);
    objAnimTranslate(obj_2, 70, 0, 0, 10);
    objAnimTranslate(obj_3, 70, 0, 0, 10);
    unitWait(npc4);
    unitWait(npc5);
    unitWait(unit_59);
    unitWait(npc6);
    unitAnimationPlay(npc4, animation_0, 1);
    unitAnimationPlay(npc5, animation_0, 1);
    unitAnimationPlay(unit_59, animation_0, 1);
    unitAnimationPlay(npc6, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc4, animation_a, 1);
    unitWait(npc4);
    unitFace(npc4, west);
    unitAnimationPlay(npc4, animation_1, 1);
    unitAnimationPlay(npc5, animation_a, 1);
    unitWait(npc5);
    unitFace(npc5, west);
    unitAnimationPlay(npc5, animation_1, 1);
    sync();
    wait(ref_1dd);
    dialogFree(ref_1dc);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitMove(ulala, 450, -100, face_south, fastest);
    unitWait(ulala);
    sndMusicPlay(sound_314e, 127);
    unitAnimationPlay(ulala, animation_18, 1);
    unitWait(ulala);
    call(URARA);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitAnimationPlay(baofu, animation_47, 1);
    unitMove(unit_1f, 520, -240, face_south, fastest);
    unitWait(unit_1f);
    unitMove(unit_1f, 520, -50, face_east, fastest);
    unitWait(unit_1f);
    unitAnimationPlay(unit_1f, animation_18, 1);
    unitWait(unit_1f);
    call(HENSHU);
    ref_210 = bustupLoad(bustup_32);
    bustupWait(ref_210);
    ref_212 = bustupAlloc(ref_210, left, rgb(0,0,0));
    bustupFade(ref_212, rgb(128,0,0), 30);
    ref_214 = dialogAlloc();
    ref_215 = msgShow(msg_15);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]のわぁー！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_215);
    dialogFree(ref_214);
    ref_219 = bustupFade(ref_212, rgb(0,0,0), 10);
    bustupWait(ref_219);
    bustupFree(ref_212);
    sndVolumeFadeTo(sound_303a, 0, 180);
    ref_21d = sndVolumeFadeTo(sound_314e, 0, 180);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    wait(ref_21d);
    eventLoad(event_b1);
}

function URARA()
{
  label_227:
    unitAnimationPlay(ulala, animation_18, 1);
    unitWait(ulala);
    b(label_227);
}

function HENSHU()
{
  label_22b:
    unitAnimationPlay(unit_1f, animation_18, 1);
    unitWait(unit_1f);
    b(label_22b);
}
