
msg_0:
[color(yellow)]南条[color(white)]
[tab]あそこが、この研究棟の警備管理室だ。
[tab]監視カメラやセンサー類を集中管理している。
[wait][clear][end]

msg_1:
[color(yellow)]南条[color(white)]
[tab]まずあそこを無力化しないと、
[tab]これから先の行動の自由は確保できない。
[wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]おい、帯銃しているぞ…
[tab]君のところは、警備員に銃を持たせるのか！？
[wait][clear][end]

msg_3:
[color(yellow)]南条[color(white)]
[tab]バカな…
[tab]この区画は、うちのグループの研究員すら
[tab]立ち入りできないんです。
[sync][wait][clear][end]

msg_4:
[color(yellow)]南条[color(white)]
[tab]警備員たちも、うちが雇った連中ではない。
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]じゃあ遠慮はいらねぇな…
[sync][wait][clear][end]

msg_6:
[color(yellow)]南条[color(white)]
[tab]音を立てるのはまずい。
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]よっしゃ、ここはいっちょ私の色仕掛けで…
[wait][clear][end]

msg_8:
[color(yellow)]警備員[color(white)]
[tab]ぐっ…！？
[wait][clear][end]

msg_9:
[color(yellow)]パオフゥ[color(white)]
[tab]ほらよ…やり易いように眠らせてやったぜ。
[wait][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]どーいう意味なのよぅ！？
[sync][wait][clear][end]

msg_11:
[color(yellow)]うらら[color(white)]
[tab]むぅ…
[sync][wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]行くぞ、芹沢君。
[tab]色仕掛けは今度でいいから。
[wait][clear][end]
