function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    disableMap();
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_9);
    ref_5 = sndLoad(sound_3043);
    wait(ref_5);
    sndMusicPlay(sound_3043, 127);
    b(label_16);
  label_9:
    bne(var_0, 1, label_16);
    bitGet(var_0, EBIT_E1E00);
    bne(var_0, 0, label_10);
    sndIdGet(var_0);
    sndVolumeFadeTo(var_0, 90, 60);
    sndUnkCF(90);
    b(label_15);
  label_10:
    bne(var_0, 1, label_15);
    ref_11 = sndLoad(sound_1120);
    wait(ref_11);
    sndMusicPlay(sound_1120, 90);
    b(label_15);
  label_15:
    b(label_16);
  label_16:
    levelFootstepSet(sfx_15);
    envTriggerSet(EXIT, 131, 1, line, coll_23);
    envTriggerSet(ELE1, 224, 1, line, coll_24);
    envTriggerSet(ELE2, 224, 1, line, coll_25);
    ref_1a = spriteLoad(sprite_0);
    wait(ref_1a);
    ref_1c = spriteLoad(sprite_2);
    wait(ref_1c);
    ref_1e = spriteLoad(sprite_6);
    wait(ref_1e);
    ref_20 = spriteLoad(sprite_d);
    wait(ref_20);
    ref_22 = spriteLoad(sprite_13);
    wait(ref_22);
    ref_24 = spriteLoad(sprite_23);
    wait(ref_24);
    ref_26 = spriteLoad(sprite_34);
    wait(ref_26);
    ref_28 = spriteLoad(sprite_35);
    wait(ref_28);
    ref_2a = spriteLoad(sprite_6b);
    wait(ref_2a);
    ref_2c = spriteLoad(sprite_d4);
    wait(ref_2c);
    unitSpawn(unit_58, sprite_d4, 1350, 0, -80, north, none);
    unitPalette(unit_58, 2);
    unitTriggerSet(unit_58, BLOCK_UKETUKE, 255, 1);
    envTriggerSet(BLOCK_UKETUKE, 255, 1, collision_2, coll_0);
    envTriggerSet(BLOCK_UKETUKE, 28, 1, line, coll_11);
    bitGet(var_0, EBIT_E0057);
    bne(var_0, 0, label_3c);
    ref_35 = spriteLoad(sprite_89);
    wait(ref_35);
    bitSet(EBIT_E0057);
    bitSet(MBIT_BROWNTALK);
    cameraSet(northwest, 1350, 0, -110);
    cameraSetNorth(south);
    b(label_5d);
  label_3c:
    bne(var_0, 1, label_5d);
    bitGet(var_0, EBIT_E1E00);
    bne(var_0, 0, label_55);
    unknownVar1(var_0);
    bne(var_0, 2311, label_47);
    cameraSetNorth(south);
    cameraSet(northeast, 1880, 0, -405);
    playerInit(east);
    controlDisable();
    b(label_1c4);
    b(label_54);
  label_47:
    bne(var_0, 2312, label_4e);
    cameraSetNorth(south);
    cameraSet(northeast, 1880, 0, -900);
    playerInit(east);
    controlDisable();
    b(label_1c4);
    b(label_54);
  label_4e:
    cameraSet(southeast, 1200, 0, -1230);
    playerInit(south);
    cameraSetNorth(south);
    controlDisable();
    b(label_1c4);
    b(label_54);
  label_54:
    b(label_5c);
  label_55:
    bne(var_0, 1, label_5c);
    cameraSet(southeast, 1200, 0, -1230);
    playerInit(south);
    cameraSetNorth(south);
    controlDisable();
    b(label_1c4);
    b(label_5c);
  label_5c:
    b(label_5d);
  label_5d:
    bitSet(DBIT_TV_GAKUYA1);
    bitSet(DBIT_TV_GAKUYA2);
    bitSet(DBIT_TV_GAKUYA3);
    bitSet(DBIT_TV_GAKUYA4);
    bitSet(DBIT_TV_ST1DR);
    unitSpawn(maya, sprite_0, 1165, 0, -1300, south, none);
    unitSpawn(ulala, sprite_6, 1035, 0, -1300, south, none);
    unitSpawn(katsuya, sprite_d, 1120, 0, -1300, south, none);
    unitSpawn(baofu, sprite_13, 1160, 0, -1300, west, none);
    unitSpawn(elly, sprite_23, 1230, 0, -1300, south, none);
    unitSpawn(brown, sprite_34, 1185, 0, -460, south, none);
    unitSpawn(yukino, sprite_35, 1090, 0, -415, north, none);
    unitSpawn(fujii, sprite_6b, 1235, 0, -370, north, none);
    unitSpawn(npc1, sprite_89, -50, 0, -180, west, none);
    unitFootstepSet(npc1, sfx_ff);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    unitAnimationPlay(yukino, animation_3, 1);
    unitAnimationPlay(fujii, animation_1, 1);
    unitAnimationPlay(brown, animation_30, 1);
    ref_72 = cameraMoveTo(1085, 0, -475, 210);
    screenFadeWait(inner);
    screenFadeWait(outer);
    wait(ref_72);
    unitAnimationPlay(brown, animation_1d, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(yukino, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(fujii, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(brown, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(brown, animation_12, 1);
    delayClear();
    delayWait(30);
    unitFace(brown, north);
    unitAnimationPlay(brown, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationHold(brown, animation_18, -1);
    delayClear();
    delayWait(30);
    unitMove(elly, 1230, -585, face_south, fast);
    delayClear();
    delayWait(15);
    unitMove(maya, 1155, -585, face_south, fast);
    delayClear();
    delayWait(30);
    unitMove(katsuya, 1125, -680, face_south, fast);
    delayClear();
    delayWait(15);
    unitMove(ulala, 1027, -680, face_south, fast);
    delayClear();
    delayWait(15);
    unitMove(baofu, 1230, -735, face_south, medium);
    unitAnimationStop(brown);
    unitWait(brown);
    unitAnimationPlay(brown, animation_a, 1);
    delayClear();
    delayWait(30);
    unitWait(maya);
    unitAnimationPlay(maya, animation_3, 1);
    unitAnimationPlay(brown, animation_2d, 1);
    ref_a1 = bustupLoad(bustup_c3);
    bustupWait(ref_a1);
    ref_a3 = bustupAlloc(ref_a1, right, rgb(0,0,0));
    bustupFade(ref_a3, rgb(128,0,0), 30);
    ref_a5 = dialogAlloc();
    ref_a6 = msgShow(msg_0);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]いよぉ、待ってたよん。
[tab]エリーちゃん。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a6);
    unitAnimationPlay(brown, animation_a, 1);
    ref_aa = msgShow(msg_1);
/***************************************
[color(yellow)]上杉[tab]秀彦（うえすぎ[tab]ひでひこ）[color(white)]
[color(green)][tab]ブラウンの通称で親しまれるマルチタレント。
[tab]エリーやゆきのと同じくエルミン学園卒業の
[tab]ペルソナ使い。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_aa);
    dialogFree(ref_a5);
    ref_ae = bustupFade(ref_a3, rgb(0,0,0), 10);
    bustupWait(ref_ae);
    bustupFree(ref_a3);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_3, 1);
    unitAnimationPlay(elly, animation_2d, 1);
    ref_b5 = bustupLoad(bustup_3e);
    bustupWait(ref_b5);
    ref_b7 = bustupAlloc(ref_b5, left, rgb(0,0,0));
    bustupFade(ref_b7, rgb(128,0,0), 30);
    ref_b9 = dialogAlloc();
    ref_ba = msgShow(msg_2);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｈｉ[tab]Ｂｒｏｗｎ．Ｙｕｋｉｎｏ．
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ba);
    unitAnimationPlay(elly, animation_0, 1);
    dialogFree(ref_b9);
    ref_bf = bustupFade(ref_b7, rgb(0,0,0), 10);
    bustupWait(ref_bf);
    bustupFree(ref_b7);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_0, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_2d, 1);
    unitAnimationPlay(elly, animation_3, 1);
    ref_c9 = bustupLoad(bustup_11a);
    bustupWait(ref_c9);
    ref_cb = bustupAlloc(ref_c9, right, rgb(0,0,0));
    bustupFade(ref_cb, rgb(128,0,0), 30);
    ref_cd = dialogAlloc();
    ref_ce = msgShow(msg_3);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]話は聞いたよ、舞耶さん。
[tab]今日は俊介さんとこいつの撮影で来たんだけど、
[tab]出来る事があれば協力するよ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ce);
    unitAnimationPlay(yukino, animation_0, 1);
    dialogFree(ref_cd);
    ref_d3 = bustupFade(ref_cb, rgb(0,0,0), 10);
    bustupWait(ref_d3);
    bustupFree(ref_cb);
    delayClear();
    delayWait(60);
    unitAnimationPlay(elly, animation_0, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(elly, animation_1f, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    ref_dd = bustupLoad(bustup_3e);
    bustupWait(ref_dd);
    ref_df = bustupAlloc(ref_dd, left, rgb(0,0,0));
    bustupFade(ref_df, rgb(128,0,0), 30);
    ref_e1 = dialogAlloc();
    ref_e2 = msgShow(msg_4);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]早速ですけどＢｒｏｗｎ…
[tab]彼女はもうみえてますの？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(yukino, animation_3, 1);
    unitAnimationPlay(ulala, animation_1, 1);
    sync();
    wait(ref_e2);
    unitAnimationPlay(elly, animation_0, 1);
    dialogFree(ref_e1);
    ref_e9 = bustupFade(ref_df, rgb(0,0,0), 10);
    bustupWait(ref_e9);
    bustupFree(ref_df);
    call(NEKO);
    delayClear();
    delayWait(30);
    unitAnimationPlay(brown, animation_2d, 1);
    ref_f0 = bustupLoad(bustup_c3);
    bustupWait(ref_f0);
    ref_f2 = bustupAlloc(ref_f0, right, rgb(0,0,0));
    bustupFade(ref_f2, rgb(128,0,0), 30);
    ref_f4 = dialogAlloc();
    ref_f5 = msgShow(msg_5);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]ああ、ワンロン千鶴なら楽屋に入ってるぜ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f5);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(ulala, animation_d, 1);
    unitAnimationPlay(brown, animation_1d, 1);
    ref_fd = msgShow(msg_6);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]それと、頼まれてた件だけどさ、
[tab]例の占いブームの火つけになった番組、
[tab]やっぱヤラセだったみたいだぜ？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_fd);
    unitAnimationPlay(brown, animation_0, 1);
    dialogFree(ref_f4);
    ref_102 = bustupFade(ref_f2, rgb(0,0,0), 10);
    bustupWait(ref_102);
    bustupFree(ref_f2);
    delayClear();
    delayWait(45);
    unitAnimationPlay(yukino, animation_0, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_2d, 1);
    unitAnimationPlay(maya, animation_0, 1);
    ref_10c = bustupLoad(bustup_11a);
    bustupWait(ref_10c);
    ref_10e = bustupAlloc(ref_10c, right, rgb(0,0,0));
    bustupFade(ref_10e, rgb(128,0,0), 30);
    ref_110 = dialogAlloc();
    unitAnimationPlay(elly, animation_3, 1);
    ref_112 = msgShow(msg_7);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]いろんな雑誌でワンロン占いが特集されだしたのも
[tab]最初の放映と同じ時期だよ。
[tab]あからさまな情報操作みたいだね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_112);
    unitAnimationPlay(yukino, animation_0, 1);
    dialogFree(ref_110);
    ref_117 = bustupFade(ref_10e, rgb(0,0,0), 10);
    bustupWait(ref_117);
    bustupFree(ref_10e);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_1a, 1);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(ulala, animation_b, 1);
    unitAnimationPlay(maya, animation_3, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(ulala, animation_c, 1);
    unitAnimationPlay(elly, animation_4, 1);
    unitAnimationPlay(maya, animation_4, 1);
    unitAnimationPlay(baofu, animation_3, 1);
    ref_128 = bustupLoad(bustup_21);
    bustupWait(ref_128);
    ref_12a = bustupAlloc(ref_128, left, rgb(0,0,0));
    bustupFade(ref_12a, rgb(128,0,0), 30);
    ref_12c = dialogAlloc();
    ref_12d = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]問題は、その女性が新世塾の人間かどうかだな。
[tab]利用されているだけの可能性もある。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12d);
    dialogFree(ref_12c);
    ref_131 = bustupFade(ref_12a, rgb(0,0,0), 10);
    bustupWait(ref_131);
    bustupFree(ref_12a);
    delayClear();
    delayWait(90);
    unitAnimationPlay(ulala, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(ulala, animation_3, 1);
    delayClear();
    delayWait(90);
    unitFace(ulala, east);
    bitSet(LBIT_0000);
    delayClear();
    delayWait(90);
    ref_143 = bustupLoad(bustup_17);
    bustupWait(ref_143);
    ref_145 = bustupAlloc(ref_143, left, rgb(0,0,0));
    bustupFade(ref_145, rgb(128,0,0), 30);
    ref_147 = dialogAlloc();
    ref_148 = msgShow(msg_9);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ねぇ…
[tab]あの猫、さっきからこっちじっと見てるんだけど…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_148);
    dialogFree(ref_147);
    ref_14c = bustupFade(ref_145, rgb(0,0,0), 10);
    bustupWait(ref_14c);
    bustupFree(ref_145);
    delayClear();
    delayWait(30);
    cameraRotateTo(1, 1);
    unitAnimationPlay(ulala, animation_b, 1);
    unitAnimationPlay(elly, animation_2, 1);
    unitAnimationPlay(maya, animation_2, 1);
    unitAnimationPlay(baofu, animation_1, 1);
    ref_156 = cameraMoveTo(1220, 0, -440, 1);
    wait(ref_156);
    delayClear();
    delayWait(30);
    call(MAYA00);
    call(KATUYA00);
    call(PAOFU00);
    call(ERI00);
    call(BROWN00);
    call(YUKINO00);
    ref_160 = call(FUJII00);
    wait(ref_160);
    delayClear();
    delayWait(30);
    ref_164 = cameraMoveTo(880, 0, -490, 90);
    wait(ref_164);
    delayClear();
    delayWait(90);
    unitAnimationPlay(katsuya, animation_27, 1);
    ref_169 = bustupLoad(bustup_22);
    bustupWait(ref_169);
    ref_16b = bustupAlloc(ref_169, left, rgb(0,0,0));
    bustupFade(ref_16b, rgb(128,0,0), 30);
    ref_16d = dialogAlloc();
    ref_16e = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ほう、可愛いな。
[tab]大方、タレントさんのペットかなにかじゃないか？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_16e);
    dialogFree(ref_16d);
    ref_172 = bustupFade(ref_16b, rgb(0,0,0), 10);
    bustupWait(ref_172);
    bustupFree(ref_16b);
    delayClear();
    delayWait(30);
    unitAnimationPlay(brown, animation_1d, 1);
    ref_178 = bustupLoad(bustup_c3);
    bustupWait(ref_178);
    ref_17a = bustupAlloc(ref_178, right, rgb(0,0,0));
    bustupFade(ref_17a, rgb(128,0,0), 30);
    ref_17c = dialogAlloc();
    ref_17d = msgShow(msg_11);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]そう言や、ワンロン千鶴がそんな猫つれてたなぁ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_17d);
    unitAnimationPlay(brown, animation_a, 1);
    dialogFree(ref_17c);
    ref_182 = bustupFade(ref_17a, rgb(0,0,0), 10);
    bustupWait(ref_182);
    bustupFree(ref_17a);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_7, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc1, animation_13, 1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3186, 127);
    unitWait(npc1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_3, 1);
    delayClear();
    delayWait(3);
    unitFace(npc1, north);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(npc1, animation_3, 1);
    delayClear();
    delayWait(3);
    unitAnimationPlay(npc1, animation_4, 1);
    delayClear();
    delayWait(3);
    unitFace(npc1, east);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(12);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_a, 1);
    ref_1a8 = bustupLoad(bustup_2c);
    bustupWait(ref_1a8);
    ref_1aa = bustupAlloc(ref_1a8, left, rgb(0,0,0));
    bustupFade(ref_1aa, rgb(128,0,0), 30);
    ref_1ac = dialogAlloc();
    unitMove(npc1, -60, -180, face_east, medium);
    unitAnimationPlay(npc1, animation_e, 1);
    ref_1af = msgShow(msg_12);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]猫なんざ放っとけ。
[tab]さっさと行くぞ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1af);
    dialogFree(ref_1ac);
    ref_1b3 = bustupFade(ref_1aa, rgb(0,0,0), 10);
    bustupWait(ref_1b3);
    bustupFree(ref_1aa);
    delayClear();
    delayWait(60);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 9, false);
    screenFadeOuter(rgb(255,255,255), 9, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_1be = cameraLookAtUnit(maya, 1, 5);
    unitDespawn(maya, none);
    wait(ref_1be);
    playerInit(northeast);
    controlDisable();
    unitDespawn(npc1, none);
  label_1c4:
    ref_1c4 = spriteLoad(sprite_cf);
    wait(ref_1c4);
    unitSpawn(npc4, sprite_cf, 160, 0, -440, west, none);
    unitTriggerSet(npc4, KEIBIIN, 255, 1);
    bitGet(var_0, IBIT_RUMOR_KASA);
    bne(var_0, 0, label_1d2);
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_1cf);
    unitSpawn(npc5, sprite_cf, 160, 0, -210, west, none);
    unitTriggerSet(npc5, KEIBIIN2, 255, 1);
    b(label_1d1);
  label_1cf:
    bne(var_0, 1, label_1d1);
    b(label_1d1);
  label_1d1:
    b(label_1d4);
  label_1d2:
    bne(var_0, 1, label_1d4);
    b(label_1d4);
  label_1d4:
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_1e7);
    unitSpawn(ulala, sprite_6, 1200, 0, -770, north, none);
    unitSpawn(katsuya, sprite_d, 560, 0, -300, east, none);
    unitSpawn(baofu, sprite_13, 1450, 0, -1140, east, none);
    unitSpawn(elly, sprite_23, 1530, 0, -320, east, none);
    unitSpawn(brown, sprite_34, 800, 0, -620, north, none);
    unitSpawn(yukino, sprite_35, 850, 0, -755, south, none);
    unitSpawn(fujii, sprite_6b, 750, 0, -755, south, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
    unitTriggerSet(baofu, B_PAO, 255, 1);
    unitTriggerSet(elly, B_ERI, 255, 1);
    unitTriggerSet(brown, BROWN, 255, 1);
    unitTriggerSet(yukino, YUKINO, 255, 1);
    unitTriggerSet(fujii, FUJII, 255, 1);
    unitIdleOnAll();
    unitAnimationPlay(brown, animation_30, 1);
    b(label_1f2);
  label_1e7:
    bne(var_0, 1, label_1f2);
    unitSpawn(ulala, sprite_6, 1200, 0, -770, north, none);
    unitSpawn(katsuya, sprite_d, 560, 0, -300, east, none);
    unitSpawn(baofu, sprite_13, 1450, 0, -1140, east, none);
    unitSpawn(elly, sprite_23, 1530, 0, -320, east, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
    unitTriggerSet(baofu, B_PAO, 255, 1);
    unitTriggerSet(elly, B_ERI, 255, 1);
    unitIdleOnAll();
    b(label_1f2);
  label_1f2:
    delayClear();
    delayWait(75);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 9, true);
    screenFadeOuter(rgb(0,0,0), 9, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    unitFacePlayer(ulala);
    unitAnimationPlay(ulala, animation_2d, 1);
    ref_1fe = bustupLoad(bustup_17);
    bustupWait(ref_1fe);
    ref_200 = bustupAlloc(ref_1fe, left, rgb(0,0,0));
    bustupFade(ref_200, rgb(128,0,0), 30);
    ref_202 = dialogAlloc();
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_209);
    ref_205 = msgShow(msg_13);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なーんかあの猫、気になるなぁ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_205);
    b(label_20e);
  label_209:
    bne(var_0, 1, label_20e);
    ref_20a = msgShow(msg_14);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]黒須さんって…
[tab]ＪＯＫＥＲ呪いをしたわけじゃないんだよね？
[tab]ホントにみんなＪＯＫＥＲになっちゃうの！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_20a);
    b(label_20e);
  label_20e:
    unitAnimationPlay(ulala, animation_0, 1);
    dialogFree(ref_202);
    ref_210 = bustupFade(ref_200, rgb(0,0,0), 10);
    bustupWait(ref_210);
    bustupFree(ref_200);
    unitRestoreFacing(ulala);
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    unitFacePlayer(katsuya);
    unitAnimationPlay(katsuya, animation_1a, 1);
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_229);
    ref_21b = bustupLoad(bustup_22);
    bustupWait(ref_21b);
    ref_21d = bustupAlloc(ref_21b, left, rgb(0,0,0));
    bustupFade(ref_21d, rgb(128,0,0), 30);
    ref_21f = dialogAlloc();
    ref_220 = msgShow(msg_15);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]猫は、あのどうにも気まぐれなところがいい。
[tab]それでいて時々擦り寄ってくるところがまた…
[tab]いかん、考えただけでアレルギーが…グスッ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_220);
    unitAnimationPlay(katsuya, animation_0, 1);
    dialogFree(ref_21f);
    ref_225 = bustupFade(ref_21d, rgb(0,0,0), 10);
    bustupWait(ref_225);
    bustupFree(ref_21d);
    b(label_238);
  label_229:
    bne(var_0, 1, label_238);
    ref_22a = bustupLoad(bustup_21);
    bustupWait(ref_22a);
    ref_22c = bustupAlloc(ref_22a, left, rgb(0,0,0));
    bustupFade(ref_22c, rgb(128,0,0), 30);
    ref_22e = dialogAlloc();
    ref_22f = msgShow(msg_16);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]黒須[tab]純子がＪＯＫＥＲになった…
[tab]確か６階にいたＡＤがそう言っていたな。
[tab]一体どういうことなんだ？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_22f);
    unitAnimationPlay(katsuya, animation_0, 1);
    dialogFree(ref_22e);
    ref_234 = bustupFade(ref_22c, rgb(0,0,0), 10);
    bustupWait(ref_234);
    bustupFree(ref_22c);
    b(label_238);
  label_238:
    unitRestoreFacing(katsuya);
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    unitFacePlayer(baofu);
    unitAnimationPlay(baofu, animation_1a, 1);
    ref_23e = bustupLoad(bustup_2d);
    bustupWait(ref_23e);
    ref_240 = bustupAlloc(ref_23e, left, rgb(0,0,0));
    bustupFade(ref_240, rgb(128,0,0), 30);
    ref_242 = dialogAlloc();
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_249);
    ref_245 = msgShow(msg_17);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]さて、女狐の化けの皮を剥ぎに行くかい…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_245);
    b(label_24e);
  label_249:
    bne(var_0, 1, label_24e);
    ref_24a = msgShow(msg_18);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ケッ、いきなりＪＯＫＥＲの登場とはな。
[tab]あの女の占い通り…いや…
[tab]新世塾の計画通りに事が運んでるってわけだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_24a);
    b(label_24e);
  label_24e:
    unitAnimationPlay(baofu, animation_0, 1);
    dialogFree(ref_242);
    ref_250 = bustupFade(ref_240, rgb(0,0,0), 10);
    bustupWait(ref_250);
    bustupFree(ref_240);
    unitRestoreFacing(baofu);
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    unitFacePlayer(elly);
    unitAnimationPlay(elly, animation_2d, 1);
    ref_259 = bustupLoad(bustup_3d);
    bustupWait(ref_259);
    ref_25b = bustupAlloc(ref_259, left, rgb(0,0,0));
    bustupFade(ref_25b, rgb(128,0,0), 30);
    ref_25d = dialogAlloc();
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_264);
    ref_260 = msgShow(msg_19);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]楽屋は２階だそうですわ。
[tab]Ｗａｎｇｌｏｎｇ千鶴の楽屋に行ってみましょう。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_260);
    b(label_269);
  label_264:
    bne(var_0, 1, label_269);
    ref_265 = msgShow(msg_20);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．Ａｍａｎｏ！
[tab]第一Ｓｔｕｄｉｏは２階ですわ！
[tab]…さぁ、急ぎましょう！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_265);
    b(label_269);
  label_269:
    unitAnimationPlay(elly, animation_0, 1);
    dialogFree(ref_25d);
    ref_26b = bustupFade(ref_25b, rgb(0,0,0), 10);
    bustupWait(ref_26b);
    bustupFree(ref_25b);
    unitRestoreFacing(elly);
    controlEnable();
}

function BROWN()
{
    controlDisable();
    unitFacePlayer(brown);
    unitAnimationPlay(brown, animation_23, 1);
    ref_274 = bustupLoad(bustup_c3);
    bustupWait(ref_274);
    ref_276 = bustupAlloc(ref_274, right, rgb(0,0,0));
    bustupFade(ref_276, rgb(128,0,0), 30);
    ref_278 = dialogAlloc();
    ref_279 = msgShow(msg_21);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]取材があるんで一緒にゃ行けないけど、
[tab]お仲間っつーことで、今後ともよろしくぅ！
[tab]でひゃひゃひゃひゃ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_279);
    unitAnimationPlay(brown, animation_0, 1);
    dialogFree(ref_278);
    ref_27e = bustupFade(ref_276, rgb(0,0,0), 10);
    bustupWait(ref_27e);
    bustupFree(ref_276);
    unitRestoreFacing(brown);
    controlEnable();
    unitAnimationPlay(brown, animation_30, 1);
}

function YUKINO()
{
    controlDisable();
    unitFacePlayer(yukino);
    unitAnimationPlay(yukino, animation_2d, 1);
    ref_288 = bustupLoad(bustup_11a);
    bustupWait(ref_288);
    ref_28a = bustupAlloc(ref_288, right, rgb(0,0,0));
    bustupFade(ref_28a, rgb(128,0,0), 30);
    ref_28c = dialogAlloc();
    ref_28d = msgShow(msg_22);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]ひとまず、楽屋でこいつの撮影してるから、
[tab]何かあったら声かけてね、舞耶さん。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_28d);
    unitAnimationPlay(yukino, animation_0, 1);
    dialogFree(ref_28c);
    ref_292 = bustupFade(ref_28a, rgb(0,0,0), 10);
    bustupWait(ref_292);
    bustupFree(ref_28a);
    unitRestoreFacing(yukino);
    controlEnable();
}

function FUJII()
{
    controlDisable();
    unitFacePlayer(fujii);
    unitAnimationPlay(fujii, animation_24, 1);
    ref_29b = bustupLoad(bustup_d5);
    bustupWait(ref_29b);
    ref_29d = bustupAlloc(ref_29b, right, rgb(0,0,0));
    bustupFade(ref_29d, rgb(128,0,0), 30);
    ref_29f = dialogAlloc();
    ref_2a0 = msgShow(msg_23);
/***************************************
[color(yellow)]藤井[color(white)]
[tab]あのショートのお嬢さんが、桐島[tab]英理子君か…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2a0);
    ref_2a3 = msgShow(msg_24);
/***************************************
[color(yellow)]藤井[color(white)]
[tab]なぁマッキー…
[tab]機会があったら、それとなく
[tab]何か悩んでないか聞いてみてくれないか？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2a3);
    ref_2a6 = msgShow(msg_25);
/***************************************
[color(yellow)]藤井[color(white)]
[tab]彼女、モデルの素質は十分なんだがね、
[tab]笑顔が固いって、カメラマンうちじゃ
[tab]評判あまりよくないんだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2a6);
    ref_2a9 = msgShow(msg_26);
/***************************************
[color(yellow)]藤井[color(white)]
[tab]君たちの前じゃ自然に笑えてるみたいだし、
[tab]何か、悩みでもあるんじゃないかと思ってね…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2a9);
    unitAnimationPlay(fujii, animation_0, 1);
    dialogFree(ref_29f);
    ref_2ae = bustupFade(ref_29d, rgb(0,0,0), 10);
    bustupWait(ref_2ae);
    bustupFree(ref_29d);
    unitRestoreFacing(fujii);
    controlEnable();
}

function CAT()
{
}

function BLOCK_UKETUKE()
{
    controlDisable();
    unitFacePlayer(unit_58);
    unitAnimationPlay(unit_58, animation_24, 1);
    ref_2b8 = dialogAlloc();
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_2bf);
    ref_2bb = msgShow(msg_27);
/***************************************
[color(yellow)]受付嬢[color(white)]
[tab]ブラウンさんのご紹介の見学の方ですね？
[tab]どうぞ、そこのエレベーターから上に上がって
[tab]ください。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2bb);
    b(label_2c4);
  label_2bf:
    bne(var_0, 1, label_2c4);
    ref_2c0 = msgShow(msg_28);
/***************************************
[color(yellow)]受付嬢[color(white)]
[tab]あ、見学の方ですね？
[tab]急いで急いで！[tab]姿勢は低く、煙を吸わないよ…
[tab]と、とにかく早く、早く逃げてくださーい！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2c0);
    b(label_2c4);
  label_2c4:
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_2b8);
    unitRestoreFacing(unit_58);
    controlEnable();
}

function KEIBIIN()
{
    controlDisable();
    bitGet(var_0, EBIT_E0069);
    bne(var_0, 0, label_2cd);
    b(label_2e1);
  label_2cd:
    bne(var_0, 1, label_2e1);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_2d0 = dialogAlloc();
    ref_2d1 = msgShow(msg_29);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]第一スタジオがタイヘンだって聞いたけど…
[tab]ど、ど、ど、どうにも足が動かな～い。
[tab]さ、さぁ…こ、ここは私に任せて…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2d1);
    bitGet(var_0, MBIT_KI_DEVIL3);
    bne(var_0, 0, label_2d7);
    b(label_2dc);
  label_2d7:
    bne(var_0, 1, label_2dc);
    ref_2d8 = msgShow(msg_30);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]…え！？[tab]カシマレイコ？
[tab]い、今はそれどころじゃないでしょ！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2d8);
    b(label_2dc);
  label_2dc:
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_2d0);
    unitRestoreFacing(npc4);
    b(label_33f);
    b(label_2e1);
  label_2e1:
    bitGet(var_0, MBIT_KI_DEVIL3);
    bne(var_0, 0, label_2f7);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_2e5 = dialogAlloc();
    ref_2e6 = msgShow(msg_31);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]…第３金曜日の雨の日……
[tab][color(orange)]カシマレイコ[color(white)]がこの[color(orange)]珠閒瑠テレビ[color(white)]に現れたんだ！
[tab]間違いない、あれはカシマレイコだ！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2e6);
    ref_2e9 = msgShow(msg_32);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]カシマレイコに会ったら、
[tab]「カシマさんのカは、カメンのカ。」
[tab]「カシマさんのシは、シニンのシ。」
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2e9);
    ref_2ec = msgShow(msg_33);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]「カシマさんのマは、アクマのマ。」
[tab]…と答えないと殺されてしまうんだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2ec);
    ref_2ef = msgShow(msg_34);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]被害者が出てからでは遅い。
[tab]誰か…誰か退治してくれないか！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2ef);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_2e5);
    unitRestoreFacing(npc4);
    bitSet(MBIT_KI_DEVIL3);
    b(label_33f);
  label_2f7:
    bne(var_0, 1, label_33f);
    bitGet(var_0, MBIT_KASIMA_OREIGET);
    bne(var_0, 0, label_333);
    bitGet(var_0, IBIT_RUMOR_KASA);
    bne(var_0, 0, label_306);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_2fe = dialogAlloc();
    ref_2ff = msgShow(msg_35);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]間違いない！[tab]あれはカシマレイコだ！！
[tab]やはり、ただの噂では無かった。
[tab]誰か…誰か退治してくれ！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2ff);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_2fe);
    unitRestoreFacing(npc4);
    b(label_332);
  label_306:
    bne(var_0, 1, label_332);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_309 = dialogAlloc();
    ref_30a = msgShow(msg_36);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]キミの持っているその傘は…
[tab]カシマレイコの傘じゃないか！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_30a);
    ref_30d = msgShow(msg_37);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]あのカシマレイコを退治するなんて…
[tab]キミは、キミは偉い！[tab]警備員より偉いよ！
[tab]ぜひ、これを受けとって欲しい。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_30d);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_309);
    delayClear();
    delayWait(30);
    ref_314 = dialogAlloc();
    ref_315 = msgShow(msg_38);
/***************************************
[tab][color(green)]インセンスカードセットを手に入れた。[color(white)]
[wait][clear]
***************************************/
    wait(ref_315);
    dialogFree(ref_314);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_31b = dialogAlloc();
    ref_31c = msgShow(msg_39);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]…受け取れない？[tab]いいっていいって。
[tab]本当なら自分達の仕事だったんだもの。
[tab]これくらいは…なぁ？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_31c);
    unitFace(npc4, south);
    delayClear();
    delayWait(12);
    unitAnimationPlay(npc4, animation_19, 1);
    ref_323 = msgShow(msg_40);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]あっれー！？
[tab]あいつどこ行ったんだ？
[tab]…まったく職務放棄じゃないか！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_323);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_31b);
    unitRestoreFacing(npc4);
    partyItemAdd(st_card, 1);
    partyItemAdd(vi_card, 1);
    partyItemAdd(dx_card, 1);
    partyItemAdd(ag_card, 1);
    partyItemAdd(lu_card, 1);
    partyItemAdd(all_card, 1);
    bitClear(IBIT_RUMOR_KASA);
    bitSet(MBIT_KASIMA_OREIGET);
    b(label_332);
  label_332:
    b(label_33e);
  label_333:
    bne(var_0, 1, label_33e);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_336 = dialogAlloc();
    ref_337 = msgShow(msg_41);
/***************************************
[color(yellow)]おびえる警備員[color(white)]
[tab]やっぱりあれはカシマレイコだった！！
[tab]予想通り、ただの噂じゃ無かったよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_337);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_336);
    unitRestoreFacing(npc4);
    b(label_33e);
  label_33e:
    b(label_33f);
  label_33f:
    controlEnable();
}

function KEIBIIN2()
{
    controlDisable();
    bitGet(var_0, MBIT_KASIMA_TANEAKA);
    bne(var_0, 0, label_358);
    unitFacePlayer(npc5);
    unitAnimationPlay(npc5, animation_24, 1);
    ref_346 = dialogAlloc();
    ref_347 = msgShow(msg_42);
/***************************************
[color(yellow)]クールな警備員[color(white)]
[tab]…私になにか？
[tab]え、カシマレイコ？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_347);
    ref_34a = msgShow(msg_43);
/***************************************
[color(yellow)]クールな警備員[color(white)]
[tab]アイツから聞いたんでしょ？
[tab]シカトしていいですよ。
[tab]…全部アイツの勘違いだから。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_34a);
    ref_34d = msgShow(msg_44);
/***************************************
[color(yellow)]クールな警備員[color(white)]
[tab]黒須さんっているでしょ？[tab]そう、あの大女優。
[tab]アイツ、黒須さんをカシマレイコと
[tab]見間違えたんですよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_34d);
    ref_350 = msgShow(msg_45);
/***************************************
[color(yellow)]クールな警備員[color(white)]
[tab]確かに黒須さんは独特の雰囲気があるから、
[tab]わからない事は無いけどねぇ。
[tab]でも、一緒にするのは失礼だよなぁ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_350);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_346);
    unitRestoreFacing(npc5);
    bitSet(MBIT_KASIMA_TANEAKA);
    b(label_363);
  label_358:
    bne(var_0, 1, label_363);
    unitFacePlayer(npc5);
    unitAnimationPlay(npc5, animation_24, 1);
    ref_35b = dialogAlloc();
    ref_35c = msgShow(msg_46);
/***************************************
[color(yellow)]クールな警備員[color(white)]
[tab]確かに黒須さんは独特の雰囲気があるから、
[tab]わからない事は無いけどねぇ。
[tab]でもカシマレイコなんて、ただの噂でしょ？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_35c);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_35b);
    unitRestoreFacing(npc5);
    b(label_363);
  label_363:
    controlEnable();
}

function EXIT()
{
    controlDisable();
    bitSet(EBIT_E1E00);
    sndMusicPlay(sound_3187, 127);
    objAnimTranslate(obj_8, 100, 0, 0, 30);
    objAnimTranslate(obj_9, -100, 0, 0, 30);
    objAnimWait(obj_8);
    objAnimWait(obj_9);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    mapLoad(aoba, 9, 4);
}

function ELE1()
{
    controlDisable();
    bitClear(EBIT_E1E00);
    sndMusicPlay(sound_3185, 127);
    objAnimTranslate(obj_a, 0, 0, 100, 30);
    objAnimTranslate(obj_b, 0, 0, -100, 30);
    objAnimWait(obj_a);
    objAnimWait(obj_b);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    dngLoad2(sumaru_tv1-7);
}

function ELE2()
{
    controlDisable();
    bitClear(EBIT_E1E00);
    sndMusicPlay(sound_3185, 127);
    objAnimTranslate(obj_c, 0, 0, 100, 30);
    objAnimTranslate(obj_d, 0, 0, -100, 30);
    objAnimWait(obj_c);
    objAnimWait(obj_d);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    dngLoad2(sumaru_tv1-8);
}

function MAYA00()
{
    unitFace(maya, east);
    unitAnimationPlay(maya, animation_1, 1);
}

function KATUYA00()
{
    unitAnimationPlay(katsuya, animation_b, 1);
    delayClear();
    delayWait(30);
    unitFace(katsuya, east);
    unitAnimationPlay(katsuya, animation_b, 1);
}

function PAOFU00()
{
    unitAnimationPlay(baofu, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(baofu, animation_2, 1);
}

function ERI00()
{
    unitAnimationPlay(elly, animation_1, 1);
    delayClear();
    delayWait(30);
    unitFace(elly, east);
    unitAnimationPlay(elly, animation_b, 1);
}

function BROWN00()
{
    unitAnimationPlay(brown, animation_d, 1);
    delayClear();
    delayWait(30);
    unitFace(brown, east);
    unitAnimationPlay(brown, animation_a, 1);
}

function YUKINO00()
{
    unitAnimationPlay(yukino, animation_3, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_4, 1);
}

function FUJII00()
{
    unitAnimationPlay(fujii, animation_3, 1);
    delayClear();
    delayWait(30);
    unitFace(fujii, east);
    unitAnimationPlay(fujii, animation_0, 1);
}

function NEKO()
{
    delayClear();
    delayWait(120);
    unitMove(npc1, 770, -430, face_west, medium);
    unitAnimationPlay(npc1, animation_e, 1);
    unitWait(npc1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc1, animation_7, 1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(npc1, animation_8, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(npc1, animation_7, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(npc1, animation_a, 1);
    delayClear();
    delayWait(12);
  label_3ca:
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_3cf);
    delayClear();
    delayWait(120);
    b(label_3d2);
  label_3cf:
    bne(var_0, 1, label_3d2);
    b(label_3f3);
    b(label_3d2);
  label_3d2:
    delayClear();
    delayWait(90);
    unitAnimationPlay(npc1, animation_7, 1);
    delayClear();
    delayWait(30);
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_3da);
    b(label_3dd);
  label_3da:
    bne(var_0, 1, label_3dd);
    b(label_3f3);
    b(label_3dd);
  label_3dd:
    unitAnimationPlay(npc1, animation_f, 1);
    delayClear();
    delayWait(90);
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_3e5);
    delayClear();
    delayWait(120);
    b(label_3e8);
  label_3e5:
    bne(var_0, 1, label_3e8);
    b(label_3f3);
    b(label_3e8);
  label_3e8:
    unitAnimationPlay(npc1, animation_a, 1);
    delayClear();
    delayWait(7);
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_3f1);
    delayClear();
    delayWait(120);
    b(label_3ca);
    b(label_3f3);
  label_3f1:
    bne(var_0, 1, label_3f3);
    b(label_3f3);
  label_3f3:
    unitAnimationPlay(npc1, animation_a, 1);
}
