
msg_0:
[color(yellow)]男の声[color(white)]
[tab]相変わらずスパイの真似事かね、南条君…？
[sync][wait][clear][end]

msg_1:
[color(yellow)]南条[color(white)]
[tab]お、お前は…神取！？
[sync][wait][clear][end]

msg_2:
[color(yellow)]神取[color(white)]
[tab]月並みだが、データを返してもらおうか。
[tab]この少年の命が惜しくば…な。
[sync][wait][clear][end]

msg_3:
[color(yellow)]神取[tab]鷹久（かんどり[tab]たかひさ）[color(white)]
[color(green)][tab]かつて世界の破滅を目論見、南条やエリー達に
[tab]倒されたペルソナ使い。
[tab]３年前に死んだはずなのだが…[color(white)]
[sync][wait][clear][end]

msg_4:
[color(yellow)]南条[color(white)]
[tab]神取…！
[tab]なぜだ…なぜ生きている！？
[sync][wait][clear][end]

msg_5:
[color(yellow)]神取[color(white)]
[tab]言霊だよ…
[tab]御覧の通り、彼らは私の研究に興味を持って
[tab]くれてね…
[sync][wait][clear][end]

msg_6:
[color(yellow)]神取[color(white)]
[tab]私を常世から呼び寄せたというわけだ…
[sync][wait][clear][end]

msg_7:
[color(yellow)]パオフゥ[color(white)]
[tab]………
[sync][wait][clear][end]

msg_8:
[color(yellow)]南条[color(white)]
[tab]なぜ未だに悪事に手を染める…
[tab]あの時のお前は…！
[sync][wait][clear][end]

msg_9:
[color(yellow)]神取[color(white)]
[tab]フッ…
[tab]影に魅入られた者の宿命…とでも言っておこうか…
[sync][wait][clear][end]

msg_10:
[color(yellow)]神取[color(white)]
[tab]私は君ほど若くはない。
[tab]今更、生き方は変えられんよ…
[sync][wait][clear][end]

msg_11:
[color(yellow)]神取[color(white)]
[tab]さて…どうするね？
[sync][wait][clear][end]

msg_12:
[color(yellow)]南条[color(white)]
[tab]わかった…データは返す…
[sync][wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]チッ…
[tab]だから足手まといはごめんだって言ったんだよ。
[sync][wait][clear][end]

msg_14:
[color(yellow)]栄吉[color(white)]
[tab]俺なんかのために…ダメだぁ…！！
[sync][wait][clear][end]

msg_15:
[color(yellow)]神取[color(white)]
[tab]やはりまだ子供か…失望したよ。
[tab]些事のために目的を失うようでは、
[tab]企業家など務まらんぞ？
[sync][wait][clear][end]

msg_16:
[color(yellow)]神取[color(white)]
[tab]私が切り捨て方を教えてあげよう。
[sync][wait][clear][end]

msg_17:
[color(yellow)]南条[color(white)]
[tab]やめろ、神取！！
[sync][wait][clear][end]

msg_18:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]！？
[sync][wait][clear][end]

msg_19:
[color(yellow)][tatsuya][color(white)]
[tab]早く逃げろ…！
[sync][wait][clear][end]

msg_20:
[color(yellow)]神取[color(white)]
[tab]フッ…
[sync][wait][clear][end]

msg_21:
[color(yellow)]神取[color(white)]
[tab]どのみち彼らも君も、
[tab]運命から逃がれることはできんぞ？
[tab]「特異点」の少年よ…
[sync][wait][clear][end]

msg_22:
[color(yellow)][tatsuya][color(white)]
[tab]そうか…
[tab]お前も魅入られたんだな…「ヤツ」に…
[sync][wait][clear][end]

msg_23:
[color(yellow)][tatsuya][color(white)]
[tab]なら「ヤツ」に伝えろ…
[tab]舞耶姉や皆は…俺が守ってみせる…！
[sync][wait][clear][end]
