function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    bitGet(var_0, EBIT_E005F);
    bez(var_0, label_143);
    sndMusicPlay(sound_3019, 127);
    objVisible(obj_b, false);
    objVisible(obj_11, false);
    objVisible(obj_12, false);
    objVisible(obj_13, false);
    objVisible(obj_14, false);
    ref_a = spriteLoad(sprite_0);
    wait(ref_a);
    unitSpawn(maya, sprite_0, 831, 0, -1318, south, none);
    ref_d = spriteLoad(sprite_d);
    wait(ref_d);
    unitSpawn(katsuya, sprite_d, 1252, -310, -1753, south, none);
    unitFootstepSet(katsuya, sfx_18);
    ref_11 = spriteLoad(sprite_13);
    wait(ref_11);
    unitSpawn(baofu, sprite_13, 445, 0, -1445, east, none);
    ref_14 = spriteLoad(sprite_6);
    wait(ref_14);
    unitSpawn(ulala, sprite_6, 669, 0, -845, south, none);
    ref_17 = spriteLoad(sprite_23);
    wait(ref_17);
    unitSpawn(elly, sprite_23, 664, 0, -1407, south, none);
    cameraSet(southeast, 749, 0, -1522);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    call(SAGASI_MAYA);
    call(SAGASI_KATU);
    call(SAGASI_PAO);
    unitAnimationPlay(elly, animation_28, 1);
    unitWait(elly);
    delayClear();
    delayWait(60);
    unitMove(elly, 655, -1133, face_south, medium);
    call(CAME_01);
    unitWait(elly);
    call(ERISHDH);
    delayClear();
    delayWait(30);
    unitFace(ulala, east);
    delayClear();
    delayWait(6);
    unitAnimationPlay(ulala, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(ulala, animation_4, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(6);
    unitMove(ulala, 612, -232, face_south, medium);
    unitWait(ulala);
    ref_3c = bustupLoad(bustup_17);
    bustupWait(ref_3c);
    ref_3e = bustupAlloc(ref_3c, left, rgb(0,0,0));
    bustupFade(ref_3e, rgb(128,0,0), 30);
    ref_40 = dialogAlloc();
    ref_41 = msgShow(msg_0);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]トォ～トォトォトォトォ…
[tab]猫ちゃぁ～ん…
[tab]いないならいないって返事しなさいよぉ～…
[wait][clear]
***************************************/
    ref_42 = spriteLoad(sprite_f);
    wait(ref_42);
    ref_44 = call(SAGASI_URARA);
    wait(ref_41);
    dialogFree(ref_40);
    ref_47 = bustupFade(ref_3e, rgb(0,0,0), 10);
    bustupWait(ref_47);
    bustupFree(ref_3e);
    wait(ref_44);
    unitFace(ulala, east);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(8);
    unitFace(ulala, north);
    unitMove(ulala, 719, -798, face_north, medium);
    ref_51 = cameraMoveTo(1024, 0, -775, 120);
    call(SYU_MAYA);
    call(SYU_KATU);
    call(SYU_PAO);
    unitWait(ulala);
    wait(ref_51);
    unitAnimationPlay(ulala, animation_1d, 1);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(katsuya, animation_1a, 1);
    unitAnimationPlay(baofu, animation_2d, 1);
    unitAnimationPlay(maya, animation_2d, 1);
    unitAnimationPlay(elly, animation_25, 1);
    delayClear();
    delayWait(180);
    sndVolumeFadeTo(sound_3019, 0, 230);
    call(FRASHU);
    call(AAA_KATU);
    call(AAA_MAYA);
    call(AAA_PAO);
    call(AAA_ERI);
    call(AAA_URARA);
    delayClear();
    delayWait(180);
    ref_69 = bustupLoad(bustup_55);
    bustupWait(ref_69);
    ref_6b = bustupAlloc(ref_69, right, rgb(0,0,0));
    bustupFade(ref_6b, rgb(128,0,0), 30);
    ref_6d = dialogAlloc();
    ref_6e = msgShow(msg_1);
/***************************************
[color(yellow)]気持ち悪い男[color(white)]
[tab]うひへぇ～
[tab]やっと見つけたよぉ、エリ～ちゃぁ～ん♥
[wait][clear]
***************************************/
    ref_6f = spriteLoad(sprite_7f);
    wait(ref_6f);
    unitSpawn(npc1, sprite_7f, 802, 0, -1705, south, none);
    unitAnimationPlay(npc1, animation_1d, 1);
    wait(ref_6e);
    dialogFree(ref_6d);
    ref_75 = bustupFade(ref_6b, rgb(0,0,0), 10);
    bustupWait(ref_75);
    bustupFree(ref_6b);
    ref_78 = cameraRotateTo(3, 60);
    ref_79 = cameraMoveTo(818, 0, -1104, 60);
    wait(ref_78);
    wait(ref_79);
    li(var_2, 0);
    call(SUTO_TIKA);
    ref_7e = bustupLoad(bustup_44);
    bustupWait(ref_7e);
    ref_80 = bustupAlloc(ref_7e, left, rgb(0,0,0));
    bustupFade(ref_80, rgb(128,0,0), 30);
    ref_82 = dialogAlloc();
    ref_83 = msgShow(msg_2);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]ヒッ…！？
[wait][clear]
***************************************/
    ref_84 = spriteLoad(sprite_3);
    wait(ref_84);
    unitAnimationHold(elly, animation_21, -1);
    wait(ref_83);
    unitAnimationStop(elly);
    unitAnimationPlay(elly, animation_0, 1);
    dialogFree(ref_82);
    ref_8b = bustupFade(ref_80, rgb(0,0,0), 10);
    bustupWait(ref_8b);
    bustupFree(ref_80);
    unitMove(elly, 675, -1019, face_north, reverse);
    delayClear();
    delayWait(20);
    unitAnimationPlay(baofu, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(baofu, animation_4, 1);
    unitWait(elly);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(baofu, animation_0, 1);
    delayClear();
    delayWait(20);
    unitMove(baofu, 613, -1151, face_north, medium);
    call(MAYAIKARI);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_a4 = bustupLoad(bustup_2e);
    bustupWait(ref_a4);
    ref_a6 = bustupAlloc(ref_a4, left, rgb(0,0,0));
    bustupFade(ref_a6, rgb(128,0,0), 30);
    ref_a8 = dialogAlloc();
    ref_a9 = msgShow(msg_3);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]なんだ、てめぇは？
[wait][clear]
***************************************/
    wait(ref_a9);
    dialogFree(ref_a8);
    ref_ac = bustupFade(ref_a6, rgb(0,0,0), 10);
    bustupWait(ref_ac);
    bustupFree(ref_a6);
    unitAnimationPlay(elly, animation_1, 1);
    delayClear();
    delayWait(60);
    ref_b2 = bustupLoad(bustup_44);
    bustupWait(ref_b2);
    ref_b4 = bustupAlloc(ref_b2, left, rgb(0,0,0));
    bustupFade(ref_b4, rgb(128,0,0), 30);
    ref_b6 = dialogAlloc();
    ref_b7 = msgShow(msg_4);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]わ、私を追い回していたＳｔａｌｋｅｒですわ！
[tab]ＰＥＲＳＯＮＡで追い払ったはずなのに…
[sync][wait][clear]
***************************************/
    ref_b8 = spriteLoad(sprite_8);
    wait(ref_b8);
    unitAnimationPlay(elly, animation_0, 1);
    sync();
    wait(ref_b7);
    dialogFree(ref_b6);
    ref_be = bustupFade(ref_b4, rgb(0,0,0), 10);
    bustupWait(ref_be);
    bustupFree(ref_b4);
    call(KATUGAN);
    call(URAIKARI);
    ref_c3 = bustupLoad(bustup_19);
    bustupWait(ref_c3);
    ref_c5 = bustupAlloc(ref_c3, left, rgb(0,0,0));
    bustupFade(ref_c5, rgb(128,0,0), 30);
    ref_c7 = dialogAlloc();
    ref_c8 = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ぬわぁにぃ～！？
[tab]ストーカーだぁ！？
[wait][clear]
***************************************/
    wait(ref_c8);
    dialogFree(ref_c7);
    ref_cb = bustupFade(ref_c5, rgb(0,0,0), 10);
    bustupWait(ref_cb);
    bustupFree(ref_c5);
  label_ce:
    delayClear();
    delayWait(5);
    bez(var_2, label_ce);
    unitAnimationPlay(npc1, animation_24, 1);
    delayClear();
    delayWait(60);
    ref_d4 = bustupLoad(bustup_55);
    bustupWait(ref_d4);
    ref_d6 = bustupAlloc(ref_d4, right, rgb(0,0,0));
    bustupFade(ref_d6, rgb(128,0,0), 30);
    ref_d8 = dialogAlloc();
    ref_d9 = msgShow(msg_6);
/***************************************
[color(yellow)]ストーカー[color(white)]
[tab]愛情表現だったんだよねぇ～？

***************************************/
    unitAnimationPlay(elly, animation_29, 1);
    wait(ref_d9);
    ref_dc = msgShow(msg_7);
/***************************************
[tab]痛いほどわかったよほぉ～でへへへぇ～
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1d, 1);
    wait(ref_dc);
    ref_df = msgShow(msg_8);
/***************************************
[color(yellow)]桑原[tab]真（くわはら[tab]まこと）[color(white)]
[color(green)][tab]エリーをつけ回すストーカー。
[tab]留守中家に上がり込むなど、
[tab]数々の暴挙を行ってきた。[color(white)]
[wait][clear]
***************************************/
    ref_e0 = spriteLoad(sprite_15);
    wait(ref_e0);
    wait(ref_df);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_d8);
    ref_e5 = bustupFade(ref_d6, rgb(0,0,0), 10);
    bustupWait(ref_e5);
    bustupFree(ref_d6);
    call(SUTOIDOU02);
    unitAnimationPlay(npc1, animation_24, 1);
    ref_ea = bustupLoad(bustup_55);
    bustupWait(ref_ea);
    ref_ec = bustupAlloc(ref_ea, right, rgb(0,0,0));
    bustupFade(ref_ec, rgb(128,0,0), 30);
    ref_ee = dialogAlloc();
    ref_ef = msgShow(msg_9);
/***************************************
[color(yellow)]ストーカー[color(white)]
[tab]今日はぁ、お返ししようと思ってぇ
[tab]ボクもこれ持って来たんだぁ～♥
[wait][clear]
***************************************/
    ref_f0 = spriteLoad(sprite_25);
    wait(ref_f0);
    ref_f2 = spriteLoad(sprite_80);
    wait(ref_f2);
    wait(ref_ef);
    dialogFree(ref_ee);
    ref_f6 = bustupFade(ref_ec, rgb(0,0,0), 10);
    bustupWait(ref_f6);
    bustupFree(ref_ec);
    unitSpriteClear(npc1);
    unitSpriteSet(npc1, sprite_80);
    unitFace(npc1, south);
    unitAnimationPlay(npc1, animation_0, 1);
    unitFace(npc1, south);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitFace(baofu, north);
    unitAnimationPlay(baofu, animation_0, 1);
    unitFace(baofu, north);
    screenColorAdjust(0.5, 0.5, 0.61328125);
    ref_104 = sndLoad(sound_301d);
    wait(ref_104);
    sndMusicPlay(sound_301d, 127);
    unitSpriteClear(elly);
    unitSpriteSet(elly, sprite_25);
    unitAnimationPlay(elly, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(elly, animation_5, 1);
    ref_10d = bustupLoad(bustup_3f);
    bustupWait(ref_10d);
    ref_10f = bustupAlloc(ref_10d, left, rgb(0,0,0));
    bustupFade(ref_10f, rgb(128,0,0), 30);
    ref_111 = dialogAlloc();
    ref_112 = sndVoicePlay(sound_5b, 128);
    sndWaitStart();
    ref_114 = msgShow(msg_10);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｎｏ[tab]ｗａｙ！
[tab]近寄らないで！！
[sync][wait][clear]
***************************************/
    wait(ref_112);
    sync();
    wait(ref_114);
    dialogFree(ref_111);
    ref_119 = bustupFade(ref_10f, rgb(0,0,0), 10);
    bustupWait(ref_119);
    bustupFree(ref_10f);
    unitAnimationPlay(ulala, animation_5, 1);
    delayClear();
    delayWait(30);
    ref_11f = bustupLoad(bustup_19);
    bustupWait(ref_11f);
    ref_121 = bustupAlloc(ref_11f, left, rgb(0,0,0));
    bustupFade(ref_121, rgb(128,0,0), 30);
    ref_123 = dialogAlloc();
    ref_124 = msgShow(msg_11);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]こんの女の敵が！！
[tab]こぉーーーーーい！！
[sync][wait][clear]
***************************************/
    ref_125 = sndVoicePlay(sound_a9, 128);
    sndWaitStart();
    wait(ref_125);
    sync();
    wait(ref_124);
    dialogFree(ref_123);
    ref_12b = bustupFade(ref_121, rgb(0,0,0), 10);
    bustupWait(ref_12b);
    bustupFree(ref_121);
    ref_12e = bustupLoad(bustup_55);
    bustupWait(ref_12e);
    ref_130 = bustupAlloc(ref_12e, right, rgb(0,0,0));
    bustupFade(ref_130, rgb(128,0,0), 30);
    ref_132 = dialogAlloc();
    ref_133 = msgShow(msg_12);
/***************************************
[color(yellow)]ストーカー[color(white)]
[tab]アイ[tab]ラァビュゥゥゥゥゥゥゥ～！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_6, 1);
    ref_135 = sndVoicePlay(sound_8e, 128);
    sndWaitStart();
    wait(ref_135);
    sync();
    wait(ref_133);
    dialogFree(ref_132);
    ref_13b = bustupFade(ref_130, rgb(0,0,0), 10);
    bustupWait(ref_13b);
    bustupFree(ref_130);
    delayClear();
    delayWait(10);
    sndMusicPlay(sound_319b, 127);
    encounterLoad(encounter_8);
    b(label_145);
  label_143:
    dngLoad2(sumaru_tv2-4);
    b(label_145);
  label_145:
}

function SUTOIDOU02()
{
    unitMove(npc1, 777, -1370, face_south, medium);
    unitWait(npc1);
}

function URAIKARI()
{
    unitAnimationPlay(ulala, animation_1e, 3);
    unitWait(ulala);
    unitMove(ulala, 757, -1198, face_north, fast);
    cameraMoveTo(808, 0, -1258, 40);
    unitWait(ulala);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_8);
    unitFace(ulala, north);
    unitAnimationPlay(ulala, animation_5, 1);
    delayClear();
    delayWait(55);
    sndMusicPlay(sound_319a, 127);
    unitFace(ulala, north);
    unitWait(ulala);
}

function KATUGAN()
{
    unitFace(katsuya, north);
}

function SUTO_TIKA()
{
    unitMove(npc1, 778, -1463, face_south, medium);
    unitWait(npc1);
    li(var_2, 1);
}

function AAA_URARA()
{
    unitAnimationHold(ulala, animation_21, 60);
    unitWait(ulala);
    unitMove(ulala, 778, -913, face_north, fast);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_1b, 1);
}

function AAA_ERI()
{
    delayClear();
    delayWait(60);
    unitFace(elly, north);
    delayClear();
    delayWait(30);
    unitAnimationHold(elly, animation_21, 120);
    unitWait(elly);
    unitAnimationPlay(elly, animation_29, 1);
    unitWait(elly);
    unitAnimationPlay(elly, animation_0, 1);
}

function AAA_PAO()
{
    unitAnimationPlay(baofu, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(baofu, animation_2, 1);
    delayClear();
    delayWait(60);
    unitFace(baofu, north);
    unitAnimationPlay(baofu, animation_a, 1);
}

function AAA_KATU()
{
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitFace(katsuya, north);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitFace(katsuya, north);
    delayClear();
    delayWait(30);
    unitMove(katsuya, 836, -1148, face_north, medium);
    unitWait(katsuya);
    delayClear();
    delayWait(60);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    unitFace(katsuya, north);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitFace(katsuya, north);
}

function AAA_MAYA()
{
    unitAnimationPlay(maya, animation_1, 1);
    delayClear();
    delayWait(4);
    unitAnimationPlay(maya, animation_2, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(10);
    unitFace(maya, north);
}

function FRASHU()
{
    screenColorAdjust(2, 2, 2);
    sndMusicPlay(sound_3199, 127);
    unitColor(maya, rgb(255,255,255), 1);
    unitColor(ulala, rgb(255,255,255), 1);
    unitColor(katsuya, rgb(255,255,255), 1);
    unitColor(baofu, rgb(255,255,255), 1);
    ref_19d = unitColor(elly, rgb(255,255,255), 1);
    wait(ref_19d);
    delayClear();
    delayWait(15);
    screenColorAdjust(0.5, 0.5, 0.5);
    unitColor(maya, rgb(112,112,112), 30);
    unitColor(ulala, rgb(112,112,112), 30);
    unitColor(katsuya, rgb(112,112,112), 30);
    unitColor(baofu, rgb(112,112,112), 30);
    ref_1a6 = unitColor(elly, rgb(112,112,112), 30);
    wait(ref_1a6);
    delayClear();
    delayWait(80);
    screenColorAdjust(2, 2, 2);
    sndMusicPlay(sound_3199, 127);
    unitColor(maya, rgb(255,255,255), 1);
    unitColor(ulala, rgb(255,255,255), 1);
    unitColor(katsuya, rgb(255,255,255), 1);
    unitColor(baofu, rgb(255,255,255), 1);
    ref_1b0 = unitColor(elly, rgb(255,255,255), 1);
    wait(ref_1b0);
    delayClear();
    delayWait(15);
    screenColorAdjust(0.5, 0.5, 0.5);
    unitColor(maya, rgb(112,112,112), 30);
    unitColor(ulala, rgb(112,112,112), 30);
    unitColor(katsuya, rgb(112,112,112), 30);
    unitColor(baofu, rgb(112,112,112), 30);
    ref_1b9 = unitColor(elly, rgb(112,112,112), 30);
    wait(ref_1b9);
    delayClear();
    delayWait(30);
    screenColorAdjust(2, 2, 2);
    sndMusicPlay(sound_3199, 127);
    unitColor(maya, rgb(255,255,255), 1);
    unitColor(ulala, rgb(255,255,255), 1);
    unitColor(katsuya, rgb(255,255,255), 1);
    unitColor(baofu, rgb(255,255,255), 1);
    ref_1c3 = unitColor(elly, rgb(255,255,255), 1);
    wait(ref_1c3);
    delayClear();
    delayWait(15);
    screenColorAdjust(0.5, 0.5, 0.5);
    unitColor(maya, rgb(112,112,112), 30);
    unitColor(ulala, rgb(112,112,112), 30);
    unitColor(katsuya, rgb(112,112,112), 30);
    unitColor(baofu, rgb(112,112,112), 30);
    ref_1cc = unitColor(elly, rgb(112,112,112), 30);
    wait(ref_1cc);
}

function SYU_PAO()
{
    unitMove(baofu, 577, -1000, face_west, medium);
    unitWait(baofu);
}

function SYU_KATU()
{
    unitMove(katsuya, 840, -1095, face_south, medium);
    unitWait(katsuya);
}

function SYU_MAYA()
{
    unitMove(maya, 906, -929, face_east, medium);
    unitWait(maya);
}

function SAGASI_URARA()
{
    unitAnimationPlay(ulala, animation_28, 1);
    unitWait(ulala);
    delayClear();
    delayWait(30);
    unitMove(ulala, 640, -67, face_south, medium);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(ulala, animation_2, 1);
}

function CAME_01()
{
    cameraMoveTo(606, 0, -192, 420);
    delayClear();
    delayWait(80);
    cameraRotateTo(1, 1);
}

function SAGASI_PAO()
{
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_28, 1);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_3, 1);
    delayClear();
    delayWait(60);
    unitMove(baofu, 342, -1386, face_east, medium);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_31, 1);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_34, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_31, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(baofu, animation_32, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_a, 1);
}

function SAGASI_KATU()
{
    unitMove(katsuya, 1250, -1546, face_south, medium);
    unitWait(katsuya);
    unitMove(katsuya, 1032, -1535, face_east, medium);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(katsuya, animation_4, 1);
}

function SAGASI_MAYA()
{
    unitAnimationPlay(maya, animation_28, 2);
    unitWait(maya);
    unitMove(maya, 984, -1306, face_west, medium);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_28, 1);
}

function MAYAIKARI()
{
    delayClear();
    delayWait(20);
    unitMove(maya, 926, -1074, face_north, fast);
    unitWait(maya);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
    unitFace(maya, north);
    unitAnimationPlay(maya, animation_0, 1);
    unitFace(maya, north);
}

function ERISHDH()
{
    unitAnimationHold(elly, animation_18, 60);
    unitWait(elly);
    unitAnimationPlay(elly, animation_0, 1);
}
