
msg_0:
[color(yellow)]黒須[tab]純子[color(white)]
[tab]あら、ここは私の楽屋よ、お嬢さん。
[tab]道に迷ったのなら、人を呼んであげましょうか？
[sync][wait][clear][end]

msg_1:
[color(yellow)]黒須[tab]純子（くろす[tab]じゅんこ）[color(white)]
[color(green)][tab]本名は橿原[tab]純子。
[tab]大女優であり橿原[tab]淳の母。
[tab]なんとなく知っている気がする…[color(white)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]黒須[tab]純子[color(white)]
[tab]あら、ここは私の楽屋よ、お嬢さん。
[tab]道に迷ったのなら、人を呼んであげましょうか？
[sync][wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
[tab]黒須…純子か…
[tab]大人の女ってないいねぇ～
[tab]芹沢なんかにゃねぇ、色気ってのがある。
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]ほう…あの淳君のお母さんなのか？
[tab]なるほど…彼はお母さん似というわけか。
[sync][wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]ぎゃ～黒須[tab]純子よ！
[tab]マーヤ、サインサイン！
[tab]おじさん連中に高く売れるわよぅ！！
[sync][wait][clear][end]

msg_6:
[color(yellow)]エリー[color(white)]
[tab]さすが大女優の貫禄ですわね。
[tab]ご迷惑をおかけしないうちに、おいとましましょう。
[sync][wait][clear][end]
