function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3043, 127);
    levelFootstepSet(sfx_19);
    cameraSet(northeast, 630, 0, -280);
    ref_5 = spriteLoad(sprite_34);
    wait(ref_5);
    ref_7 = spriteLoad(sprite_35);
    wait(ref_7);
    ref_9 = spriteLoad(sprite_6b);
    wait(ref_9);
    ref_b = spriteLoad(sprite_23);
    wait(ref_b);
    unitSpawn(brown, sprite_34, 700, 0, -300, west, none);
    unitSpawn(yukino, sprite_35, 500, 0, -430, west, none);
    unitSpawn(fujii, sprite_6b, 415, 0, -150, west, none);
    unitSpawn3d(elly, sprite_23, 900, 40, 0, east, none);
    unitSpawn3d(npc1, sprite_34, 900, 40, -225, east, none);
    ref_12 = unitColor(elly, rgb(0,0,0), 1);
    wait(ref_12);
    unitAnimationPlay(elly, animation_a, 1);
    unitAnimationPlay(yukino, animation_a, 1);
    ref_16 = call(BROWN00);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_1c = bustupLoad(bustup_c3);
    bustupWait(ref_1c);
    ref_1e = bustupAlloc(ref_1c, right, rgb(0,0,0));
    bustupFade(ref_1e, rgb(128,0,0), 30);
    ref_20 = dialogAlloc();
    ref_21 = msgShow(msg_0);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]あ～どんなポーズが一番バチっとキマんかな～？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_21);
    bitSet(LBIT_0000);
    wait(ref_16);
    unitAnimationPlay(brown, animation_1, 1);
    unitAnimationPlay(npc1, animation_3, 1);
    delayClear();
    delayWait(7);
    unitFace(brown, north);
    unitFace(npc1, north);
    unitAnimationPlay(brown, animation_0, 1);
    unitAnimationPlay(npc1, animation_0, 1);
    ref_2e = msgShow(msg_1);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]ねね、こんなんどうすか、姐御！？
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(7);
    unitAnimationPlay(brown, animation_3, 1);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(7);
    unitFace(brown, east);
    unitFace(npc1, west);
    unitAnimationPlay(brown, animation_0, 1);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(brown, animation_a, 1);
    unitAnimationPlay(npc1, animation_a, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(brown, animation_1a, 1);
    unitAnimationPlay(npc1, animation_1a, 1);
    sync();
    wait(ref_2e);
    dialogFree(ref_20);
    ref_44 = bustupFade(ref_1e, rgb(0,0,0), 10);
    bustupWait(ref_44);
    bustupFree(ref_1e);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_2f, 1);
    ref_4a = bustupLoad(bustup_11b);
    bustupWait(ref_4a);
    ref_4c = bustupAlloc(ref_4a, right, rgb(0,0,0));
    bustupFade(ref_4c, rgb(128,0,0), 30);
    ref_4e = dialogAlloc();
    ref_4f = msgShow(msg_2);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]あ～もうイライラするね！
[tab]なんでもいいからさっさと決めな！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(brown, animation_3, 1);
    unitAnimationPlay(npc1, animation_1, 1);
    unitAnimationPlay(fujii, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(fujii, animation_2, 1);
    sync();
    wait(ref_4f);
    unitAnimationPlay(yukino, animation_a, 1);
    dialogFree(ref_4e);
    ref_5a = bustupFade(ref_4c, rgb(0,0,0), 10);
    bustupWait(ref_5a);
    bustupFree(ref_4c);
    delayClear();
    delayWait(30);
    unitFace(fujii, north);
    unitAnimationPlay(fujii, animation_0, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(fujii, animation_24, 1);
    ref_64 = bustupLoad(bustup_d5);
    bustupWait(ref_64);
    ref_66 = bustupAlloc(ref_64, right, rgb(0,0,0));
    bustupFade(ref_66, rgb(128,0,0), 30);
    ref_68 = dialogAlloc();
    ref_69 = msgShow(msg_3);
/***************************************
[color(yellow)]藤井[color(white)]
[tab]こらユッキー
[tab]モデルさんが一番映えるポーズを見てあげるのも、
[tab]カメラマンの大切な仕事だぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(brown, animation_0, 1);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(yukino, animation_d, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_e, 1);
    unitAnimationPlay(brown, animation_1, 1);
    unitAnimationPlay(npc1, animation_3, 1);
    sync();
    wait(ref_69);
    unitAnimationPlay(fujii, animation_0, 1);
    dialogFree(ref_68);
    ref_76 = bustupFade(ref_66, rgb(0,0,0), 10);
    bustupWait(ref_76);
    bustupFree(ref_66);
    delayClear();
    delayWait(30);
    unitFace(yukino, south);
    unitAnimationPlay(yukino, animation_a, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_2c, 2);
    ref_80 = bustupLoad(bustup_11a);
    bustupWait(ref_80);
    ref_82 = bustupAlloc(ref_80, right, rgb(0,0,0));
    bustupFade(ref_82, rgb(128,0,0), 30);
    ref_84 = dialogAlloc();
    ref_85 = msgShow(msg_4);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]そ、そうですわよねぇ～
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_85);
    unitAnimationPlay(brown, animation_0, 1);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(yukino, animation_3, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(brown, animation_3, 1);
    unitAnimationPlay(npc1, animation_1, 1);
    unitAnimationPlay(yukino, animation_0, 1);
    unitFace(yukino, west);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_2d, 1);
    ref_94 = msgShow(msg_5);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]な、なかなかよろしいんじゃねぇですこと？
[tab]上杉くん。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_94);
    unitAnimationPlay(yukino, animation_0, 1);
    dialogFree(ref_84);
    ref_99 = bustupFade(ref_82, rgb(0,0,0), 10);
    bustupWait(ref_99);
    bustupFree(ref_82);
    delayClear();
    delayWait(30);
    unitAnimationPlay(brown, animation_1d, 1);
    unitAnimationPlay(npc1, animation_1d, 1);
    ref_a0 = unitColor(npc1, rgb(0,0,0), 120);
    ref_a1 = bustupLoad(bustup_c3);
    bustupWait(ref_a1);
    ref_a3 = bustupAlloc(ref_a1, right, rgb(0,0,0));
    bustupFade(ref_a3, rgb(128,0,0), 30);
    ref_a5 = dialogAlloc();
    ref_a6 = msgShow(msg_6);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]はぁ…これだもんなぁ～
[sync][wait][clear]
***************************************/
    unitWait(brown);
    delayClear();
    delayWait(20);
    sndVolumeFadeTo(sound_3043, 0, 180);
    delayClear();
    delayWait(40);
    unitAnimationPlay(npc1, animation_12, 1);
    unitAnimationPlay(brown, animation_12, 1);
    wait(ref_a0);
    unitSpawn(npc1, sprite_34, 850, 0, 0, east, none);
    unitSpawn3d(elly, sprite_23, 900, 40, -225, east, none);
    ref_b2 = unitColor(elly, rgb(112,112,112), 120);
    sndMusicPlay(sound_3192, 127);
    unitAnimationPlay(fujii, animation_1, 1);
    wait(ref_b2);
    sync();
    wait(ref_a6);
    unitFace(brown, west);
    unitAnimationPlay(brown, animation_0, 1);
    unitAnimationPlay(brown, animation_22, 1);
    delayClear();
    delayWait(20);
    unitAnimationHold(brown, animation_22, -1);
    ref_be = msgShow(msg_7);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]って…ぎょええええええ！？
[tab]エ、エ、エ、エリー！？
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitAnimationHold(yukino, animation_21, -1);
    unitFace(fujii, west);
    unitAnimationPlay(fujii, animation_0, 1);
    delayClear();
    delayWait(7);
    unitAnimationHold(fujii, animation_1b, -1);
    sync();
    wait(ref_be);
    dialogFree(ref_a5);
    ref_ca = bustupFade(ref_a3, rgb(0,0,0), 10);
    bustupWait(ref_ca);
    bustupFree(ref_a3);
    ref_cd = sndLoad(sound_3025);
    wait(ref_cd);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_2d, 1);
    ref_d2 = bustupLoad(bustup_3d);
    bustupWait(ref_d2);
    ref_d4 = bustupAlloc(ref_d2, left, rgb(0,0,0));
    bustupFade(ref_d4, rgb(128,0,0), 30);
    ref_d6 = dialogAlloc();
    ref_d7 = msgShow(msg_8);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]お取り込み中のところ、ごめんあそばせ。
[tab]実は、二人にお願いしたい事がありますの…
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3025, 127);
    unitAnimationStop(brown);
    unitWait(brown);
    unitAnimationPlay(brown, animation_0, 1);
    delayClear();
    delayWait(12);
    unitAnimationStop(yukino);
    unitAnimationStop(fujii);
    unitWait(yukino);
    unitWait(fujii);
    unitAnimationPlay(yukino, animation_0, 1);
    unitAnimationPlay(fujii, animation_0, 1);
    sync();
    wait(ref_d7);
    unitAnimationPlay(elly, animation_0, 1);
    dialogFree(ref_d6);
    ref_ea = bustupFade(ref_d4, rgb(0,0,0), 10);
    bustupWait(ref_ea);
    bustupFree(ref_d4);
    delayClear();
    delayWait(90);
    unitAnimationPlay(elly, animation_2d, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(elly, animation_1f, 1);
    unitWait(elly);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_1e, 1);
    unitWait(elly);
    delayClear();
    delayWait(60);
    unitAnimationPlay(elly, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_24, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_1f, 1);
    ref_101 = bustupLoad(bustup_11a);
    bustupWait(ref_101);
    ref_103 = bustupAlloc(ref_101, right, rgb(0,0,0));
    bustupFade(ref_103, rgb(128,0,0), 30);
    ref_105 = dialogAlloc();
    ref_106 = msgShow(msg_9);
/***************************************
[color(yellow)]ゆきの[color(white)]
[tab]じゃあ、こっちの世界にあるそのお札を探して、
[tab]それに書いてある記号を教えればいいんだね！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_106);
    unitAnimationPlay(yukino, animation_a, 1);
    dialogFree(ref_105);
    ref_10b = bustupFade(ref_103, rgb(0,0,0), 10);
    bustupWait(ref_10b);
    bustupFree(ref_103);
    delayClear();
    delayWait(30);
    unitAnimationPlay(brown, animation_2d, 1);
    ref_111 = bustupLoad(bustup_c3);
    bustupWait(ref_111);
    ref_113 = bustupAlloc(ref_111, right, rgb(0,0,0));
    bustupFade(ref_113, rgb(128,0,0), 30);
    ref_115 = dialogAlloc();
    ref_116 = msgShow(msg_10);
/***************************************
[color(yellow)]ブラウン[color(white)]
[tab]お安い御用だけんど…
[tab]☱って書いてあるお札みたいのなら、
[tab]俺様５スタのドアで見たぜ？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_116);
    unitAnimationPlay(brown, animation_a, 1);
    dialogFree(ref_115);
    ref_11b = bustupFade(ref_113, rgb(0,0,0), 10);
    bustupWait(ref_11b);
    bustupFree(ref_113);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_2d, 1);
    ref_121 = bustupLoad(bustup_3d);
    bustupWait(ref_121);
    ref_123 = bustupAlloc(ref_121, left, rgb(0,0,0));
    bustupFade(ref_123, rgb(128,0,0), 30);
    ref_125 = dialogAlloc();
    ref_126 = msgShow(msg_11);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｒｅａｌｌｙ？
[tab]だとしたら、それが二番目の門ですわ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_126);
    unitAnimationPlay(elly, animation_0, 1);
    ref_12a = msgShow(msg_12);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]おかしいですわね…
[tab]他の御札がどうなってるかも、
[tab]見てきてくださいます？
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(60);
    unitAnimationPlay(elly, animation_1a, 1);
    sync();
    wait(ref_12a);
    dialogFree(ref_125);
    ref_131 = bustupFade(ref_123, rgb(0,0,0), 10);
    bustupWait(ref_131);
    bustupFree(ref_123);
    delayClear();
    delayWait(60);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_b7);
}

function BROWN00()
{
  label_13e:
    unitAnimationPlay(brown, animation_1f, 1);
    unitAnimationPlay(npc1, animation_1f, 1);
    b(label_14a);
  label_141:
    unitAnimationPlay(brown, animation_1a, 1);
    unitAnimationPlay(npc1, animation_1a, 1);
    b(label_14a);
  label_144:
    unitAnimationPlay(brown, animation_1d, 1);
    unitAnimationPlay(npc1, animation_1d, 1);
    b(label_14a);
  label_147:
    unitAnimationPlay(brown, animation_a, 1);
    unitAnimationPlay(npc1, animation_a, 1);
    b(label_14a);
  label_14a:
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_14d);
    b(label_150);
  label_14d:
    bne(var_0, 1, label_150);
    b(label_167);
    b(label_150);
  label_150:
    delayClear();
    delayWait(45);
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_155);
    b(label_158);
  label_155:
    bne(var_0, 1, label_158);
    b(label_167);
    b(label_158);
  label_158:
    delayClear();
    delayWait(45);
    rand(var_0, 3);
    bne(var_0, 0, label_15e);
    b(label_13e);
    b(label_167);
  label_15e:
    bne(var_0, 1, label_161);
    b(label_141);
    b(label_167);
  label_161:
    bne(var_0, 2, label_164);
    b(label_144);
    b(label_167);
  label_164:
    bne(var_0, 3, label_167);
    b(label_147);
    b(label_167);
  label_167:
}
