
msg_0:
[color(yellow)]うらら[color(white)]
[tab]トォ～トォトォトォトォ…
[tab]猫ちゃぁ～ん…
[tab]いないならいないって返事しなさいよぉ～…
[wait][clear][end]

msg_1:
[color(yellow)]気持ち悪い男[color(white)]
[tab]うひへぇ～
[tab]やっと見つけたよぉ、エリ～ちゃぁ～ん♥
[wait][clear][end]

msg_2:
[color(yellow)]エリー[color(white)]
[tab]ヒッ…！？
[wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
[tab]なんだ、てめぇは？
[wait][clear][end]

msg_4:
[color(yellow)]エリー[color(white)]
[tab]わ、私を追い回していたＳｔａｌｋｅｒですわ！
[tab]ＰＥＲＳＯＮＡで追い払ったはずなのに…
[sync][wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]ぬわぁにぃ～！？
[tab]ストーカーだぁ！？
[wait][clear][end]

msg_6:
[color(yellow)]ストーカー[color(white)]
[tab]愛情表現だったんだよねぇ～？
[end]

msg_7:
[tab]痛いほどわかったよほぉ～でへへへぇ～
[wait][clear][end]

msg_8:
[color(yellow)]桑原[tab]真（くわはら[tab]まこと）[color(white)]
[color(green)][tab]エリーをつけ回すストーカー。
[tab]留守中家に上がり込むなど、
[tab]数々の暴挙を行ってきた。[color(white)]
[wait][clear][end]

msg_9:
[color(yellow)]ストーカー[color(white)]
[tab]今日はぁ、お返ししようと思ってぇ
[tab]ボクもこれ持って来たんだぁ～♥
[wait][clear][end]

msg_10:
[color(yellow)]エリー[color(white)]
[tab]Ｎｏ[tab]ｗａｙ！
[tab]近寄らないで！！
[sync][wait][clear][end]

msg_11:
[color(yellow)]うらら[color(white)]
[tab]こんの女の敵が！！
[tab]こぉーーーーーい！！
[sync][wait][clear][end]

msg_12:
[color(yellow)]ストーカー[color(white)]
[tab]アイ[tab]ラァビュゥゥゥゥゥゥゥ～！！
[sync][wait][clear][end]
