function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    levelFootstepSet(sfx_1a);
    sndMusicPlay(sound_300a, 1);
    cameraSet(southwest, 470, -50, -1670);
    ref_5 = spriteLoad(sprite_0);
    wait(ref_5);
    ref_7 = spriteLoad(sprite_6);
    wait(ref_7);
    ref_9 = spriteLoad(sprite_d);
    wait(ref_9);
    ref_b = spriteLoad(sprite_15);
    wait(ref_b);
    ref_d = spriteLoad(sprite_21);
    wait(ref_d);
    ref_f = spriteLoad(sprite_27);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_70);
    wait(ref_11);
    unitSpawn(eikichi, sprite_27, 280, 0, -1600, north, none);
    unitSpawn(maya, sprite_0, 250, 0, -1900, south, none);
    unitSpawn(ulala, sprite_6, 690, 0, -1600, east, none);
    unitSpawn(katsuya, sprite_d, 580, 0, -1850, south, none);
    unitSpawn(baofu, sprite_15, 370, 0, -1970, south, none);
    unitSpawn(nanjo, sprite_21, 500, 0, -1700, east, none);
    unitSpawn(npc1, sprite_70, 250, 0, -1750, west, none);
    unitAnimationPlay(eikichi, animation_37, 1);
    unitAnimationPlay(nanjo, animation_11, 1);
    unitAnimationPlay(katsuya, animation_1, 1);
    unitAnimationPlay(ulala, animation_a, 1);
    unitAnimationPlay(maya, animation_10, 1);
    unitAnimationPlay(npc1, animation_17, 1);
    objAnimRotate(obj_82, 0, -150, 0, 1, 0);
    objAnimRotate(obj_83, 0, 130, 0, 1, 0);
    sndMusicPlay(sound_317f, 127);
    unitAnimationHold(baofu, animation_12, -1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_2b = bustupLoad(bustup_118);
    bustupWait(ref_2b);
    ref_2d = bustupAlloc(ref_2b, right, rgb(0,0,0));
    bustupFade(ref_2d, rgb(128,0,0), 30);
    ref_2f = dialogAlloc();
    ref_30 = msgShow(msg_0);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]杉本ぉぉ！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_30);
    dialogFree(ref_2f);
    ref_34 = bustupFade(ref_2d, rgb(0,0,0), 10);
    bustupWait(ref_34);
    bustupFree(ref_2d);
    delayClear();
    delayWait(120);
    unitAnimationPlay(eikichi, animation_42, 1);
    ref_3a = bustupLoad(bustup_117);
    bustupWait(ref_3a);
    ref_3c = bustupAlloc(ref_3a, right, rgb(0,0,0));
    bustupFade(ref_3c, rgb(128,0,0), 30);
    ref_3e = dialogAlloc();
    ref_3f = msgShow(msg_1);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]何も…何も殺すことねぇじゃねぇか！
[tab]てめぇらも、アイツらと同じ人殺しだ！！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(60);
    unitAnimationPlay(nanjo, animation_10, 1);
    sync();
    wait(ref_3f);
    dialogFree(ref_3e);
    ref_46 = bustupFade(ref_3c, rgb(0,0,0), 10);
    bustupWait(ref_46);
    bustupFree(ref_3c);
    unitAnimationPlay(eikichi, animation_3e, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_2a, 1);
    unitWait(ulala);
    sndVolumeFadeTo(sound_300a, 127, 300);
    ref_4f = bustupLoad(bustup_18);
    bustupWait(ref_4f);
    ref_51 = bustupAlloc(ref_4f, left, rgb(0,0,0));
    bustupFade(ref_51, rgb(128,0,0), 30);
    ref_53 = dialogAlloc();
    ref_54 = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]よく見なさいって…
[tab]南条君は、殺しちゃいないよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_54);
    dialogFree(ref_53);
    ref_58 = bustupFade(ref_51, rgb(0,0,0), 10);
    bustupWait(ref_58);
    bustupFree(ref_51);
    delayClear();
    delayWait(60);
    unitAnimationPlay(eikichi, animation_42, 1);
    ref_5e = spriteLoad(sprite_13);
    wait(ref_5e);
    ref_60 = dialogAlloc();
    ref_61 = msgShow(msg_3);
/***************************************
[color(yellow)]杉本[color(white)]
[tab]ぐがっ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_61);
    dialogFree(ref_60);
    delayClear();
    delayWait(60);
    unitAnimationPlay(nanjo, animation_11, 1);
    ref_68 = bustupLoad(bustup_3b);
    bustupWait(ref_68);
    ref_6a = bustupAlloc(ref_68, left, rgb(0,0,0));
    bustupFade(ref_6a, rgb(128,0,0), 30);
    ref_6c = dialogAlloc();
    ref_6d = msgShow(msg_4);
/***************************************
[color(yellow)]南条[color(white)]
[tab]大のために…小は切り捨てん…
[tab]昔、学んだからな…
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_d, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(eikichi, animation_3e, 1);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitFace(baofu, west);
    unitAnimationPlay(baofu, animation_e, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(baofu, animation_d, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(ulala, animation_d, 1);
    sync();
    wait(ref_6d);
    dialogFree(ref_6c);
    ref_84 = bustupFade(ref_6a, rgb(0,0,0), 10);
    bustupWait(ref_84);
    bustupFree(ref_6a);
    unitMove(katsuya, 500, -1850, face_south, medium);
    unitWait(katsuya);
    unitMove(katsuya, 500, -1780, face_south, medium);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_31, 1);
    ref_8c = spriteLoad(sprite_1f);
    wait(ref_8c);
    ref_8e = bustupLoad(bustup_22);
    bustupWait(ref_8e);
    ref_90 = bustupAlloc(ref_8e, left, rgb(0,0,0));
    bustupFade(ref_90, rgb(128,0,0), 30);
    ref_92 = dialogAlloc();
    ref_93 = msgShow(msg_5);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]マキャベリは、そんな事を言ったかな？
[tab]立てるか？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_93);
    dialogFree(ref_92);
    ref_97 = bustupFade(ref_90, rgb(0,0,0), 10);
    bustupWait(ref_97);
    bustupFree(ref_90);
    sndMusicPlay(sound_3180, 127);
    unitSpriteClear(nanjo);
    unitSpriteSet(nanjo, sprite_1f);
    unitAnimationPlay(nanjo, animation_0, 1);
    unitAnimationPlay(katsuya, animation_36, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(nanjo, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(nanjo, animation_4, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    ref_a6 = bustupLoad(bustup_36);
    bustupWait(ref_a6);
    ref_a8 = bustupAlloc(ref_a6, left, rgb(0,0,0));
    bustupFade(ref_a8, rgb(128,0,0), 30);
    ref_aa = dialogAlloc();
    ref_ab = msgShow(msg_6);
/***************************************
[color(yellow)]南条[color(white)]
[tab]俺は欲張りなんですよ…
[tab]この手にすくえるものは、全て抱く…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ab);
    dialogFree(ref_aa);
    ref_af = bustupFade(ref_a8, rgb(0,0,0), 10);
    bustupWait(ref_af);
    bustupFree(ref_a8);
    unitAnimationPlay(nanjo, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(nanjo, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(nanjo, animation_6, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_1, 1);
    unitAnimationPlay(eikichi, animation_33, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(eikichi, animation_2, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_a, 1);
    unitAnimationPlay(baofu, animation_e, 1);
    unitAnimationPlay(ulala, animation_a, 1);
    unitFace(eikichi, west);
    unitAnimationPlay(eikichi, animation_6, 1);
    ref_c7 = bustupLoad(bustup_118);
    bustupWait(ref_c7);
    ref_c9 = bustupAlloc(ref_c7, right, rgb(0,0,0));
    bustupFade(ref_c9, rgb(128,0,0), 30);
    ref_cb = dialogAlloc();
    ref_cc = msgShow(msg_7);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]す、すいませんしたっ！
[tab]俺ぁ、とんでもねぇ事を…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_cc);
    unitAnimationPlay(eikichi, animation_2d, 1);
    ref_d0 = msgShow(msg_8);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]あんた、ホントの漢だ！
[tab]俺を舎弟にして下さい！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d0);
    dialogFree(ref_cb);
    ref_d4 = bustupFade(ref_c9, rgb(0,0,0), 10);
    bustupWait(ref_d4);
    bustupFree(ref_c9);
    unitAnimationPlay(eikichi, animation_0, 1);
    delayClear();
    delayWait(60);
    unitFace(baofu, south);
    unitAnimationPlay(baofu, animation_a, 1);
    ref_dc = bustupLoad(bustup_2d);
    bustupWait(ref_dc);
    ref_de = bustupAlloc(ref_dc, left, rgb(0,0,0));
    bustupFade(ref_de, rgb(128,0,0), 30);
    ref_e0 = dialogAlloc();
    ref_e1 = msgShow(msg_9);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]人情話はそこらへんにしときな…
[tab]とっととずらかるぜ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(maya, animation_d, 1);
    delayClear();
    delayWait(12);
    unitAnimationPlay(maya, animation_e, 1);
    unitAnimationPlay(katsuya, animation_2, 1);
    unitAnimationPlay(nanjo, animation_3, 1);
    unitAnimationPlay(ulala, animation_3, 1);
    unitAnimationPlay(eikichi, animation_1, 1);
    sync();
    wait(ref_e1);
    dialogFree(ref_e0);
    ref_ed = bustupFade(ref_de, rgb(0,0,0), 10);
    bustupWait(ref_ed);
    bustupFree(ref_de);
    unitMove(ulala, 680, -1980, face_east, fast);
    unitWait(ulala);
    unitMove(ulala, 480, -1980, face_east, fast);
    unitWait(ulala);
    unitAnimationPlay(baofu, animation_d, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(baofu, animation_e, 1);
    unitAnimationPlay(ulala, animation_2d, 1);
    ref_f9 = spriteLoad(sprite_f);
    wait(ref_f9);
    ref_fb = bustupLoad(bustup_1b);
    bustupWait(ref_fb);
    ref_fd = bustupAlloc(ref_fb, left, rgb(0,0,0));
    bustupFade(ref_fd, rgb(128,0,0), 30);
    ref_ff = dialogAlloc();
    ref_100 = msgShow(msg_10);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ちょっと待ってよ！
[tab][tatsuya]君はどうすんの？
[tab]せっかく盗んだデータだって…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_100);
    dialogFree(ref_ff);
    ref_104 = bustupFade(ref_fd, rgb(0,0,0), 10);
    bustupWait(ref_104);
    bustupFree(ref_fd);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(30);
    ref_10a = spriteLoad(sprite_3);
    wait(ref_10a);
    ref_10c = bustupLoad(bustup_2d);
    bustupWait(ref_10c);
    ref_10e = bustupAlloc(ref_10c, left, rgb(0,0,0));
    bustupFade(ref_10e, rgb(128,0,0), 30);
    ref_110 = dialogAlloc();
    ref_111 = bustupLoad(bustup_10d);
    bustupWait(ref_111);
    ref_113 = bustupAlloc(ref_111, right, rgb(0,0,0));
    bustupFade(ref_113, rgb(128,0,0), 30);
    ref_115 = msgShow(msg_11);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]心配すんな…ハードディスクは抜いといた。
[tab]俺はそんな間抜けじゃねぇよ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_115);
    ref_118 = bustupFade(ref_10e, rgb(0,0,0), 10);
    bustupWait(ref_118);
    bustupFree(ref_10e);
    dialogFree(ref_110);
    ref_11c = bustupFade(ref_113, rgb(0,0,0), 10);
    bustupWait(ref_11c);
    bustupFree(ref_113);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_d, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(baofu, animation_b, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(baofu, animation_c, 1);
    ref_12b = efctAuraLoad();
    ref_12c = bustupLoad(bustup_31);
    bustupWait(ref_12c);
    ref_12e = bustupAlloc(ref_12c, left, rgb(0,0,0));
    bustupFade(ref_12e, rgb(128,0,0), 30);
    ref_130 = dialogAlloc();
    ref_131 = msgShow(msg_12);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]それに…アイツの事はほっとけ。
[tab]お前さん達よりよっぽど場数踏んでるし、
[tab]肝もすわってる…むしろ足手まといだろうぜ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_131);
    dialogFree(ref_130);
    ref_135 = bustupFade(ref_12e, rgb(0,0,0), 10);
    bustupWait(ref_135);
    bustupFree(ref_12e);
    ref_138 = spriteLoad(sprite_dd);
    wait(ref_138);
    ref_13a = spriteLoad(sprite_21);
    wait(ref_13a);
    ref_13c = sndVolumeFadeTo(sound_300a, 0, 120);
    unitAnimationPlay(baofu, animation_b, 1);
    ref_13e = dialogAlloc();
    ref_13f = msgShow(msg_13);
/***************************************
[color(yellow)]警備員達の声[color(white)]
[tab]いたぞ！[tab]逃がすな！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_13f);
    dialogFree(ref_13e);
    call(KEIBI);
    wait(ref_13c);
    unitAnimationPlay(ulala, animation_1, 1);
    unitAnimationPlay(maya, animation_3, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(maya, animation_1, 1);
    unitFace(eikichi, north);
    unitAnimationPlay(eikichi, animation_0, 1);
    unitAnimationPlay(eikichi, animation_2c, 1);
    unitFace(katsuya, east);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(12);
    unitFace(katsuya, east);
    delayClear();
    delayWait(12);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    sndMusicPlay(sound_3182, 127);
    unitAnimationPlay(katsuya, animation_5, 1);
    call(MAYA);
    call(URARA);
    call(PAOFU);
    unitSpriteClear(nanjo);
    unitSpriteSet(nanjo, sprite_21);
    unitAnimationHold(nanjo, animation_4, -1);
    wait(ref_12b);
    sndMusicPlay(sound_3181, 127);
    unitAura(nanjo, true);
    unitWait(eikichi);
    unitAnimationPlay(eikichi, animation_35, 1);
    ref_166 = todLoad(tod_5);
    ref_167 = bustupLoad(bustup_23);
    bustupWait(ref_167);
    ref_169 = bustupAlloc(ref_167, left, rgb(0,0,0));
    bustupFade(ref_169, rgb(128,0,0), 30);
    ref_16b = dialogAlloc();
    ref_16c = msgShow(msg_14);
/***************************************
[color(yellow)]克哉[color(white)]
[tab][tatsuya]…無事でいろ…！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_16c);
    dialogFree(ref_16b);
    ref_170 = bustupFade(ref_169, rgb(0,0,0), 10);
    bustupWait(ref_170);
    bustupFree(ref_169);
    sndMusicPlay(sound_3182, 127);
    unitAnimationPlay(katsuya, animation_5, 1);
    unitWait(katsuya);
    sndVolumeFadeTo(sound_3183, 0, 60);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    wait(ref_166);
    unitAura(nanjo, false);
    bitSet(TBIT_MD404);
    bitClear(TBIT_MD605);
    unitDespawn(maya, none);
    unitDespawn(ulala, none);
    unitDespawn(nanjo, none);
    unitDespawn(katsuya, none);
    unitDespawn(baofu, none);
    unitDespawn(eikichi, none);
    unitDespawn(npc1, none);
    ref_188 = spriteLoad(sprite_dd);
    wait(ref_188);
    delayClear();
    delayWait(30);
    todRun(tod_5, 0);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_3184, 127);
    call(KEIBI1);
    call(KEIBI2);
    delayClear();
    delayWait(510);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_b5);
}

function MAYA()
{
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
    unitMove(maya, 80, -1890, face_south, fastest);
    unitAnimationPlay(maya, animation_2, 1);
    unitWait(maya);
    unitAnimationPlay(maya, animation_0, 1);
}

function URARA()
{
    unitMove(ulala, 680, -1980, face_south, fast);
    unitWait(ulala);
    unitMove(ulala, 680, -1540, face_east, fast);
    unitWait(ulala);
    unitMove(ulala, 200, -1540, face_north, fast);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_35, 1);
}

function PAOFU()
{
    delayClear();
    delayWait(60);
    unitMove(baofu, 680, -1970, face_south, fast);
    unitWait(baofu);
    unitMove(baofu, 680, -1540, face_east, fast);
    unitWait(baofu);
    unitMove(baofu, 370, -1540, face_north, fast);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_3, 1);
}

function KEIBI()
{
    delayClear();
    delayWait(90);
    unitSpawn(npc2, sprite_dd, -130, 0, -1710, west, none);
    unitMove(npc2, -10, -1710, face_west, fast);
    unitAnimationPlay(npc2, animation_2, 1);
    unitWait(npc2);
    unitMove(npc2, -90, -1710, face_west, reverse);
    unitAnimationPlay(npc2, animation_a, 1);
    unitWait(npc2);
    unitDespawn(npc2, none);
}

function KEIBI1()
{
    delayClear();
    delayWait(360);
    unitSpawn(npc3, sprite_dd, -50, 0, -1700, west, fade);
    unitMove(npc3, 150, -1600, face_south, fast);
    unitWait(npc3);
    unitAnimationPlay(npc3, animation_5, 4);
}

function KEIBI2()
{
    delayClear();
    delayWait(420);
    unitSpawn(npc4, sprite_dd, -50, 0, -1700, west, fade);
    unitMove(npc4, 100, -1700, face_south, fast);
    unitFace(npc4, south);
    unitWait(npc4);
    unitAnimationPlay(npc4, animation_5, 4);
}
