function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    bitClear(DBIT_TV_ST6DR);
    cameraSet(southeast, 880, 0, -1400);
    objVisible(obj_b, false);
    objVisible(obj_11, false);
    objVisible(obj_12, false);
    objVisible(obj_13, false);
    objVisible(obj_14, false);
    ref_9 = spriteLoad(sprite_23);
    wait(ref_9);
    ref_b = spriteLoad(sprite_0);
    wait(ref_b);
    ref_d = spriteLoad(sprite_6);
    wait(ref_d);
    ref_f = spriteLoad(sprite_13);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_d);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_83);
    wait(ref_13);
    unitSpawn(ulala, sprite_6, 648, 0, -1361, west, none);
    unitAnimationPlay(ulala, animation_6, 1);
    unitSpawn(enemy1, sprite_83, 800, 0, -1500, west, none);
    unitAnimationPlay(enemy1, animation_28, 1);
    unitSpawn(baofu, sprite_13, 800, 0, -1600, south, none);
    unitAnimationPlay(baofu, animation_37, 1);
    unitSpawn(elly, sprite_23, 1000, 0, -1600, east, none);
    unitAnimationPlay(elly, animation_a, 1);
    unitSpawn(katsuya, sprite_d, 960, 0, -1430, east, none);
    unitAnimationPlay(katsuya, animation_10, 1);
    unitSpawn(maya, sprite_0, 770, 0, -1300, north, none);
    unitAnimationPlay(maya, animation_10, 1);
    unitIdleOffAll();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(90);
    unitAnimationPlay(baofu, animation_32, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(baofu, animation_33, 1);
    delayClear();
    delayWait(30);
    ref_30 = bustupLoad(bustup_2c);
    bustupWait(ref_30);
    ref_32 = bustupAlloc(ref_30, left, rgb(0,0,0));
    bustupFade(ref_32, rgb(128,0,0), 30);
    ref_34 = dialogAlloc();
    ref_35 = msgShow(msg_0);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]首の骨が折れてるぜ…
[tab]いくらなんでも、もう動けねぇだろ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_35);
    dialogFree(ref_34);
    ref_39 = bustupFade(ref_32, rgb(0,0,0), 10);
    bustupWait(ref_39);
    bustupFree(ref_32);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_10, 1);
    delayClear();
    delayWait(60);
    ref_41 = bustupLoad(bustup_40);
    bustupWait(ref_41);
    ref_43 = bustupAlloc(ref_41, left, rgb(0,0,0));
    bustupFade(ref_43, rgb(128,0,0), 30);
    ref_45 = dialogAlloc();
    ref_46 = msgShow(msg_1);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]私が…同じ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_46);
    dialogFree(ref_45);
    ref_4a = bustupFade(ref_43, rgb(0,0,0), 10);
    bustupWait(ref_4a);
    bustupFree(ref_43);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_d, 1);
    delayClear();
    delayWait(30);
    ref_52 = bustupLoad(bustup_21);
    bustupWait(ref_52);
    ref_54 = bustupAlloc(ref_52, left, rgb(0,0,0));
    bustupFade(ref_54, rgb(128,0,0), 30);
    ref_56 = dialogAlloc();
    ref_57 = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]天野君…おかしくないか？
[tab]僕達が迷いに迷ってるのに、なぜこいつはこうも
[tab]行く先々に現れることができるんだ？
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_d, 1);
    unitAnimationPlay(baofu, animation_32, 1);
    delayClear();
    delayWait(50);
    sync();
    wait(ref_57);
    ref_60 = msgShow(msg_3);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]これがあの猫の言った、奇門遁甲の恐ろしさと
[tab]いうやつかもしれんぞ…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_11, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    sync();
    wait(ref_60);
    dialogFree(ref_56);
    ref_68 = bustupFade(ref_54, rgb(0,0,0), 10);
    bustupWait(ref_68);
    bustupFree(ref_54);
    delayClear();
    delayWait(60);
    bitSet(EBIT_E0066);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    dngLoad2(sumaru_tv2-5);
}
