function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    sndMusicPlay(sound_300d, 127);
    cameraSet(southeast, 960, 0, -1680);
    levelFootstepSet(sfx_19);
    ref_a = spriteLoad(sprite_0);
    wait(ref_a);
    ref_c = spriteLoad(sprite_3);
    wait(ref_c);
    ref_e = spriteLoad(sprite_6);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_8);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_d);
    wait(ref_12);
    ref_14 = spriteLoad(sprite_f);
    wait(ref_14);
    ref_16 = spriteLoad(sprite_13);
    wait(ref_16);
    ref_18 = spriteLoad(sprite_15);
    wait(ref_18);
    ref_1a = spriteLoad(sprite_23);
    wait(ref_1a);
    ref_1c = spriteLoad(sprite_25);
    wait(ref_1c);
    ref_1e = spriteLoad(sprite_46);
    wait(ref_1e);
    unitSpawn(maya, sprite_3, 750, 0, -1700, south, none);
    unitSpawn(ulala, sprite_8, 1000, 0, -1580, south, none);
    unitSpawn(katsuya, sprite_f, 850, 0, -1530, south, none);
    unitSpawn(baofu, sprite_15, 900, 0, -1700, south, none);
    unitSpawn(elly, sprite_25, 680, 0, -1500, south, none);
    unitSpawn(unit_67, sprite_46, 840, 0, -1300, north, none);
    unitShadowRadius(unit_67, 0);
    unitAnimationPlay(maya, animation_d, 1);
    unitAnimationPlay(ulala, animation_10, 1);
    unitAnimationPlay(baofu, animation_15, 1);
    unitAnimationPlay(elly, animation_d, 1);
    unitAnimationPlay(unit_67, animation_53, 1);
    objAnimRotate(obj_17, 0, 360, 0, 360, 1);
    objAnimRotate(obj_1a, 360, 0, 0, 360, 1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(30);
    unitSpriteClear(maya);
    unitSpriteClear(baofu);
    unitSpriteClear(elly);
    unitSpriteSet(maya, sprite_0);
    unitSpriteSet(baofu, sprite_13);
    unitSpriteSet(elly, sprite_23);
    unitAnimationPlay(ulala, animation_15, 1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitSpriteClear(ulala);
    unitSpriteClear(katsuya);
    unitSpriteSet(ulala, sprite_6);
    unitSpriteSet(katsuya, sprite_d);
    call(ERI_MIRU);
    call(MAYA_KYORO);
    call(URARA_KYORO);
    call(PAOFU_KYORO);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_28, 1);
    ref_47 = spriteLoad(sprite_6d);
    wait(ref_47);
    ref_49 = spriteLoad(sprite_2b);
    wait(ref_49);
    ref_4b = spriteLoad(sprite_62);
    wait(ref_4b);
    ref_4d = spriteLoad(sprite_64);
    wait(ref_4d);
    unitSpawn(junko, sprite_6d, 670, 0, -670, west, none);
    unitSpawn(lisa, sprite_2b, 700, 0, -850, south, none);
    unitSpawn(unit_28, sprite_62, 900, 0, -720, east, none);
    unitSpawn(unit_29, sprite_64, 945, 0, -675, east, none);
    unitAnimationPlay(junko, animation_16, 1);
    unitAnimationPlay(lisa, animation_6, 1);
    unitAnimationPlay(unit_28, animation_6, 1);
    unitAnimationPlay(unit_29, animation_6, 1);
    ref_57 = cameraMoveTo(900, 0, -1470, 60);
    wait(ref_57);
    waitFunc(ERI_MIRU);
    ref_5a = bustupLoad(bustup_3f);
    bustupWait(ref_5a);
    ref_5c = bustupAlloc(ref_5a, left, rgb(0,0,0));
    bustupFade(ref_5c, rgb(128,0,0), 30);
    ref_5e = dialogAlloc();
    ref_5f = msgShow(msg_0);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｄａｍｎ…[delay(30)]

***************************************/
    wait(ref_5f);
    unitAnimationPlay(maya, animation_e, 1);
    unitAnimationPlay(ulala, animation_c, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitAnimationStop(baofu);
    unitAnimationPlay(elly, animation_3b, 1);
    ref_66 = msgShow(msg_1);
/***************************************
[tab]どうりで簡単に倒せたと思ったら、
[tab]身代わり符だったのですね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_66);
    dialogFree(ref_5e);
    ref_6a = bustupFade(ref_5c, rgb(0,0,0), 10);
    bustupWait(ref_6a);
    bustupFree(ref_5c);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    unitMove(katsuya, 850, -1520, face_south, fast);
    unitWait(katsuya);
    call(KATUYA_IDO);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_2, 1);
    ref_76 = cameraRotateTo(7, 1);
    ref_77 = cameraMoveTo(760, 0, -760, 1);
    wait(ref_76);
    wait(ref_77);
    waitFunc(KATUYA_IDO);
    call(PARTY_IDO);
    unitAnimationPlay(lisa, animation_2, 1);
    unitAnimationPlay(unit_28, animation_2, 1);
    unitAnimationPlay(unit_29, animation_2, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_82 = bustupLoad(bustup_25);
    bustupWait(ref_82);
    ref_84 = bustupAlloc(ref_82, left, rgb(0,0,0));
    bustupFade(ref_84, rgb(128,0,0), 30);
    ref_86 = dialogAlloc();
    ref_87 = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab][tatsuya]は…！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_87);
    dialogFree(ref_86);
    ref_8b = bustupFade(ref_84, rgb(0,0,0), 10);
    bustupWait(ref_8b);
    bustupFree(ref_84);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitFace_2(lisa, west);
    unitAnimationPlay(lisa, animation_14, 1);
    ref_93 = bustupLoad(bustup_122);
    bustupWait(ref_93);
    ref_95 = bustupAlloc(ref_93, right, rgb(0,0,0));
    bustupFade(ref_95, rgb(128,0,0), 30);
    ref_97 = dialogAlloc();
    ref_98 = msgShow(msg_3);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]この人をベルベットルームってとこに
[tab]つれて行けって…さっき…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_98);
    dialogFree(ref_97);
    ref_9c = bustupFade(ref_95, rgb(0,0,0), 10);
    bustupWait(ref_9c);
    bustupFree(ref_95);
    unitAnimationPlay(katsuya, animation_e, 1);
    unitAnimationPlay(lisa, animation_10, 1);
    delayClear();
    delayWait(60);
    bitGet(var_0, EBIT_IWATOCLEAR);
    bez(var_0, label_cc);
    bitGet(var_1, EBIT_LOVEGINKO);
    bez(var_1, label_cc);
    bitGet(var_2, EBIT_SUKI);
    bez(var_2, label_cc);
    unitAnimationPlay(lisa, animation_1f, 1);
    ref_aa = bustupLoad(bustup_122);
    bustupWait(ref_aa);
    ref_ac = bustupAlloc(ref_aa, right, rgb(0,0,0));
    bustupFade(ref_ac, rgb(128,0,0), 30);
    ref_ae = dialogAlloc();
    ref_af = msgShow(msg_4);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]お願い！[tab]情人（チンヤン）を助けてあげて！！
[tab]情人（チンヤン）、凄く悩んでるみたいだった…

***************************************/
    wait(ref_af);
    unitAnimationPlay(lisa, animation_10, 1);
    ref_b2 = msgShow(msg_5);
/***************************************
[tab]お願いします！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_b2);
    dialogFree(ref_ae);
    ref_b6 = bustupFade(ref_ac, rgb(0,0,0), 10);
    bustupWait(ref_b6);
    bustupFree(ref_ac);
    delayClear();
    delayWait(60);
    unitAnimationPlay(lisa, animation_a, 1);
    ref_bc = bustupLoad(bustup_122);
    bustupWait(ref_bc);
    ref_be = bustupAlloc(ref_bc, right, rgb(0,0,0));
    bustupFade(ref_be, rgb(128,0,0), 30);
    ref_c0 = dialogAlloc();
    ref_c1 = msgShow(msg_6);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]情人（チンヤン）…？[delay(30)]

***************************************/
    wait(ref_c1);
    unitAnimationPlay(lisa, animation_13, 1);
    ref_c4 = msgShow(msg_7);
/***************************************
[tab]情人（チンヤン）って…
[tab]なんでわたし、先輩をそんな風に呼ぶの…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c4);
    dialogFree(ref_c0);
    ref_c8 = bustupFade(ref_be, rgb(0,0,0), 10);
    bustupWait(ref_c8);
    bustupFree(ref_be);
    b(label_dc);
  label_cc:
    unitAnimationPlay(lisa, animation_1f, 1);
    ref_cd = bustupLoad(bustup_122);
    bustupWait(ref_cd);
    ref_cf = bustupAlloc(ref_cd, right, rgb(0,0,0));
    bustupFade(ref_cf, rgb(128,0,0), 30);
    ref_d1 = dialogAlloc();
    ref_d2 = msgShow(msg_8);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]お願い！[tab][suou]先輩を助けてあげて！！
[tab]先輩、凄く悩んでるみたいだった…

***************************************/
    wait(ref_d2);
    unitAnimationPlay(lisa, animation_10, 1);
    ref_d5 = msgShow(msg_9);
/***************************************
[tab]お願いします！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d5);
    dialogFree(ref_d1);
    ref_d9 = bustupFade(ref_cf, rgb(0,0,0), 10);
    bustupWait(ref_d9);
    bustupFree(ref_cf);
  label_dc:
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, east);
    unitAnimationPlay(katsuya, animation_14, 1);
    ref_e0 = bustupLoad(bustup_21);
    bustupWait(ref_e0);
    ref_e2 = bustupAlloc(ref_e0, left, rgb(0,0,0));
    bustupFade(ref_e2, rgb(128,0,0), 30);
    ref_e4 = dialogAlloc();
    ref_e5 = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]落ち着いて…あれは僕の弟だ。

***************************************/
    wait(ref_e5);
    unitAnimationPlay(lisa, animation_a, 1);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_e9 = msgShow(msg_11);
/***************************************
[tab]必ず学校に行かせるようにするから…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_e9);
    dialogFree(ref_e4);
    ref_ed = bustupFade(ref_e2, rgb(0,0,0), 10);
    bustupWait(ref_ed);
    bustupFree(ref_e2);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_f3 = cameraMoveTo(830, 0, -960, 60);
    wait(ref_f3);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_14, 1);
    ref_f8 = bustupLoad(bustup_2c);
    bustupWait(ref_f8);
    ref_fa = bustupAlloc(ref_f8, left, rgb(0,0,0));
    bustupFade(ref_fa, rgb(128,0,0), 30);
    ref_fc = dialogAlloc();
    ref_fd = msgShow(msg_12);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]これ以上ここにいると厄介な事になるぜ…

***************************************/
    wait(ref_fd);
    unitAnimationPlay(maya, animation_c, 1);
    unitAnimationPlay(ulala, animation_12, 1);
    unitAnimationPlay(katsuya, animation_c, 1);
    unitAnimationPlay(elly, animation_c, 1);
    unitAnimationPlay(lisa, animation_d, 1);
    ref_104 = msgShow(msg_13);
/***************************************
[tab]引き上げだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_104);
    dialogFree(ref_fc);
    ref_108 = bustupFade(ref_fa, rgb(0,0,0), 10);
    bustupWait(ref_108);
    bustupFree(ref_fa);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_b5);
}

function MAYA_KYORO()
{
    unitAnimationPlay(maya, animation_4, 1);
    delayClear();
    delayWait(30);
    unitFace_2(maya, east);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_2a, 1);
}

function URARA_KYORO()
{
    unitAnimationPlay(ulala, animation_2, 1);
    delayClear();
    delayWait(30);
    unitFace_2(ulala, west);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_2a, 1);
}

function PAOFU_KYORO()
{
    unitAnimationPlay(baofu, animation_28, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    unitAnimationHold(baofu, animation_11, -1);
}

function ERI_MIRU()
{
    unitMove(elly, 680, -1300, face_west, medium);
    unitWait(elly);
    unitMove(elly, 760, -1300, face_west, medium);
    unitWait(elly);
    unitAnimationPlay(elly, animation_37, 1);
}

function KATUYA_IDO()
{
    unitMove(katsuya, 900, -850, face_south, fast);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_28, 1);
    unitWait(katsuya);
}

function MAYA_IDO()
{
    unitMove(maya, 640, -1050, face_south, medium);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
}

function URARA_IDO()
{
    unitMove(ulala, 900, -1000, face_south, medium);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
}

function PAOFU_IDO()
{
    unitMove(baofu, 940, -1140, face_south, medium);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
}

function ERI_IDO()
{
    unitMove(elly, 760, -1050, face_south, medium);
    unitWait(elly);
    unitAnimationPlay(elly, animation_a, 1);
}

function PARTY_IDO()
{
    call(ERI_IDO);
    delayClear();
    delayWait(60);
    call(MAYA_IDO);
    call(URARA_IDO);
    delayClear();
    delayWait(60);
    call(PAOFU_IDO);
}
