function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    bitGet(var_0, EBIT_E0067);
    bez(var_0, label_1fe);
    sndIdGet(var_a);
    bne(var_a, -1, label_7);
    b(label_9);
  label_7:
    sndVolumeFadeTo(var_a, 90, 60);
    b(label_9);
  label_9:
    objVisible(obj_17, false);
    objVisible(obj_33, false);
    objVisible(obj_30, false);
    cameraSet(southeast, 900, 0, -1680);
    levelFootstepSet(sfx_19);
    ref_e = spriteLoad(sprite_0);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_6);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_d);
    wait(ref_12);
    ref_14 = spriteLoad(sprite_13);
    wait(ref_14);
    ref_16 = spriteLoad(sprite_23);
    wait(ref_16);
    ref_18 = spriteLoad(sprite_36);
    wait(ref_18);
    ref_1a = spriteLoad(sprite_89);
    wait(ref_1a);
    ref_1c = spriteLoad(sprite_f);
    wait(ref_1c);
    unitSpawn(naoya, sprite_36, 750, 0, -500, north, none);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_31ae, 127);
    ref_27 = objAnimRotate(obj_a, 0, -70, 0, 30, 0);
    wait(ref_27);
    call(PAOFU_TOJO);
    delayClear();
    delayWait(30);
    call(KATUYA_TOJO);
    delayClear();
    delayWait(60);
    call(ERI_TOJO);
    delayClear();
    delayWait(60);
    call(MAYA_TOJO);
    delayClear();
    delayWait(30);
    call(URARA_TOJO);
    waitFunc(URARA_TOJO);
    delayClear();
    delayWait(60);
    sndVolumeFadeOff(var_a, 90);
    unitAnimationPlay(maya, animation_e, 1);
    unitAnimationPlay(ulala, animation_12, 1);
    unitAnimationPlay(katsuya, animation_c, 1);
    unitAnimationPlay(baofu, animation_e, 1);
    unitAnimationHold(elly, animation_21, 60);
    unitWait(elly);
    delayClear();
    delayWait(30);
    call(HERO_IDO);
    call(PAOFU_IDO);
    call(KATUYA_IDO);
    call(MAYA_IDO);
    call(URARA_IDO);
    call(ERI_IDO);
    cameraSet(northeast, 750, 0, -1000);
    sndMusicPlay(sound_301a, 127);
    waitFunc(HERO_IDO);
    ref_4b = bustupLoad(bustup_68);
    bustupWait(ref_4b);
    ref_4d = bustupAlloc(ref_4b, right, rgb(0,0,0));
    bustupFade(ref_4d, rgb(128,0,0), 30);
    ref_4f = dialogAlloc();
    ref_50 = msgShow(msg_0);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]久しぶり…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_50);
    dialogFree(ref_4f);
    ref_54 = bustupFade(ref_4d, rgb(0,0,0), 10);
    bustupWait(ref_54);
    bustupFree(ref_4d);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_1f, 1);
    ref_5a = bustupLoad(bustup_41);
    bustupWait(ref_5a);
    ref_5c = bustupAlloc(ref_5a, left, rgb(0,0,0));
    bustupFade(ref_5c, rgb(128,0,0), 30);
    ref_5e = dialogAlloc();
    ref_5f = msgShow(msg_1);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]そんな…どうしてここに…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5f);
    dialogFree(ref_5e);
    ref_63 = bustupFade(ref_5c, rgb(0,0,0), 10);
    bustupWait(ref_63);
    bustupFree(ref_5c);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(naoya, animation_14, 1);
    ref_6a = bustupLoad(bustup_68);
    bustupWait(ref_6a);
    ref_6c = bustupAlloc(ref_6a, right, rgb(0,0,0));
    bustupFade(ref_6c, rgb(128,0,0), 30);
    ref_6e = dialogAlloc();
    ref_6f = msgShow(msg_2);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]エリーがちゃんと約束守ったか、
[tab]確かめに来たんだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6f);
    dialogFree(ref_6e);
    ref_73 = bustupFade(ref_6c, rgb(0,0,0), 10);
    bustupWait(ref_73);
    bustupFree(ref_6c);
    unitAnimationPlay(naoya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_1f, 1);
    ref_7a = bustupLoad(bustup_1b);
    bustupWait(ref_7a);
    ref_7c = bustupAlloc(ref_7a, left, rgb(0,0,0));
    bustupFade(ref_7c, rgb(128,0,0), 30);
    ref_7e = dialogAlloc();
    ref_7f = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ほぇ～これがエリーちゃんの…

***************************************/
    wait(ref_7f);
    unitAnimationPlay(ulala, animation_1d, 1);
    ref_82 = msgShow(msg_4);
/***************************************
[tab]目からウロコだわ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_82);
    dialogFree(ref_7e);
    ref_86 = bustupFade(ref_7c, rgb(0,0,0), 10);
    bustupWait(ref_86);
    bustupFree(ref_7c);
    unitAnimationPlay(ulala, animation_a, 1);
    ref_8a = bustupLoad(bustup_45);
    bustupWait(ref_8a);
    ref_8c = bustupAlloc(ref_8a, left, rgb(0,0,0));
    bustupFade(ref_8c, rgb(128,0,0), 30);
    ref_8e = dialogAlloc();
    ref_8f = msgShow(msg_5);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]も、もちろんですわ…！
[tab]わ、私ね…
[sync][wait][clear]
***************************************/
    unitMove(elly, 720, -1030, face_south, medium);
    unitWait(elly);
    unitAnimationPlay(elly, animation_1f, 1);
    sync();
    wait(ref_8f);
    dialogFree(ref_8e);
    ref_96 = bustupFade(ref_8c, rgb(0,0,0), 10);
    bustupWait(ref_96);
    bustupFree(ref_8c);
    unitAnimationHold(baofu, animation_11, -1);
    ref_9a = bustupLoad(bustup_2c);
    bustupWait(ref_9a);
    ref_9c = bustupAlloc(ref_9a, left, rgb(0,0,0));
    bustupFade(ref_9c, rgb(128,0,0), 30);
    ref_9e = dialogAlloc();
    ref_9f = msgShow(msg_6);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]待ちな、嬢ちゃん…[delay(30)]

***************************************/
    wait(ref_9f);
    unitAnimationPlay(elly, animation_c, 1);
    unitAnimationStop(baofu);
    unitAnimationPlay(baofu, animation_2b, 1);
    ref_a4 = msgShow(msg_7);
/***************************************
[tab]こいつは胡散くさすぎる。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a4);
    dialogFree(ref_9e);
    ref_a8 = bustupFade(ref_9c, rgb(0,0,0), 10);
    bustupWait(ref_a8);
    bustupFree(ref_9c);
    ref_ab = bustupLoad(bustup_21);
    bustupWait(ref_ab);
    ref_ad = bustupAlloc(ref_ab, left, rgb(0,0,0));
    bustupFade(ref_ad, rgb(128,0,0), 30);
    ref_af = dialogAlloc();
    ref_b0 = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]まったくだ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_26, 1);
    sync();
    wait(ref_b0);
    dialogFree(ref_af);
    ref_b5 = bustupFade(ref_ad, rgb(0,0,0), 10);
    bustupWait(ref_b5);
    bustupFree(ref_ad);
    unitAnimationPlay(elly, animation_e, 1);
    unitAnimationPlay(katsuya, animation_b, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(naoya, animation_1f, 1);
    ref_bd = bustupLoad(bustup_68);
    bustupWait(ref_bd);
    ref_bf = bustupAlloc(ref_bd, right, rgb(0,0,0));
    bustupFade(ref_bf, rgb(128,0,0), 30);
    ref_c1 = dialogAlloc();
    ref_c2 = msgShow(msg_9);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]君は、オレを信じないのかい？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c2);
    dialogFree(ref_c1);
    ref_c6 = bustupFade(ref_bf, rgb(0,0,0), 10);
    bustupWait(ref_c6);
    bustupFree(ref_bf);
    unitAnimationPlay(naoya, animation_a, 1);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_cd = bustupLoad(bustup_45);
    bustupWait(ref_cd);
    ref_cf = bustupAlloc(ref_cd, left, rgb(0,0,0));
    bustupFade(ref_cf, rgb(128,0,0), 30);
    ref_d1 = dialogAlloc();
    ref_d2 = msgShow(msg_10);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]そ、そんなことありませんわ…！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2b, 1);
    unitWait(elly);
    unitAnimationPlay(elly, animation_1f, 1);
    sync();
    wait(ref_d2);
    dialogFree(ref_d1);
    ref_d9 = bustupFade(ref_cf, rgb(0,0,0), 10);
    bustupWait(ref_d9);
    bustupFree(ref_cf);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_df = bustupLoad(bustup_68);
    bustupWait(ref_df);
    ref_e1 = bustupAlloc(ref_df, right, rgb(0,0,0));
    bustupFade(ref_e1, rgb(128,0,0), 30);
    ref_e3 = dialogAlloc();
    ref_e4 = msgShow(msg_11);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]あ～あ、なんて顔だ…まるで仮面だな。
[tab]それで笑ってるつもり？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(naoya, animation_1d, 1);
    unitWait(naoya);
    unitAnimationPlay(naoya, animation_1f, 1);
    sync();
    wait(ref_e4);
    dialogFree(ref_e3);
    ref_eb = bustupFade(ref_e1, rgb(0,0,0), 10);
    bustupWait(ref_eb);
    bustupFree(ref_e1);
    unitAnimationHold(elly, animation_21, -1);
    ref_ef = bustupLoad(bustup_41);
    bustupWait(ref_ef);
    ref_f1 = bustupAlloc(ref_ef, left, rgb(0,0,0));
    bustupFade(ref_f1, rgb(128,0,0), 30);
    ref_f3 = dialogAlloc();
    ref_f4 = msgShow(msg_12);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]え…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f4);
    dialogFree(ref_f3);
    ref_f8 = bustupFade(ref_f1, rgb(0,0,0), 10);
    bustupWait(ref_f8);
    bustupFree(ref_f1);
    unitAnimationStop(elly);
    delayClear();
    delayWait(30);
    unitAnimationHold(naoya, animation_19, -1);
    ref_ff = bustupLoad(bustup_68);
    bustupWait(ref_ff);
    ref_101 = bustupAlloc(ref_ff, right, rgb(0,0,0));
    bustupFade(ref_101, rgb(128,0,0), 30);
    ref_103 = dialogAlloc();
    ref_104 = msgShow(msg_13);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]何か、心に引っかかってるんだろ？
[tab]だからそんな顔しかできないんだ。

***************************************/
    wait(ref_104);
    unitAnimationPlay(naoya, animation_1f, 1);
    ref_107 = msgShow(msg_14);
/***************************************
[tab]言ってみなよ…聞いてやるからさ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_107);
    dialogFree(ref_103);
    ref_10b = bustupFade(ref_101, rgb(0,0,0), 10);
    bustupWait(ref_10b);
    bustupFree(ref_101);
    unitAnimationPlay(naoya, animation_a, 1);
    unitAnimationPlay(elly, animation_10, 1);
    delayClear();
    delayWait(90);
    ref_112 = bustupLoad(bustup_42);
    bustupWait(ref_112);
    ref_114 = bustupAlloc(ref_112, left, rgb(0,0,0));
    bustupFade(ref_114, rgb(128,0,0), 30);
    ref_116 = dialogAlloc();
    ref_117 = msgShow(msg_15);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]………
[tab]わ…私…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_117);
    dialogFree(ref_116);
    ref_11b = bustupFade(ref_114, rgb(0,0,0), 10);
    bustupWait(ref_11b);
    bustupFree(ref_114);
    delayClear();
    delayWait(150);
    sndVolumeFadeOff(sound_301a, 90);
    unitAnimationPlay(naoya, animation_2b, 1);
    ref_122 = bustupLoad(bustup_68);
    bustupWait(ref_122);
    ref_124 = bustupAlloc(ref_122, right, rgb(0,0,0));
    bustupFade(ref_124, rgb(128,0,0), 30);
    ref_126 = dialogAlloc();
    ref_127 = msgShow(msg_16);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]ハッキリしないな…

***************************************/
    wait(ref_127);
    unitAnimationPlay(elly, animation_a, 1);
    unitAnimationPlay(naoya, animation_14, 1);
    ref_12b = msgShow(msg_17);
/***************************************
[tab]じゃあ、代わりにエリーが一番聞きたい事を
[tab]言ってやるよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12b);
    unitAnimationHold(naoya, animation_19, -1);
    ref_12f = msgShow(msg_18);
/***************************************
[color(yellow)]ピアスの少年[color(white)]
[tab]「一方的な好意は迷惑だ」

***************************************/
    wait(ref_12f);
    unitAnimationHold(elly, animation_21, -1);
    unitAnimationStop(naoya);
    unitAnimationPlay(naoya, animation_1d, 1);
    ref_134 = msgShow(msg_19);
/***************************************
[tab]「もうオレに関わらないでくれ」[delay(30)]

***************************************/
    wait(ref_134);
    unitAnimationPlay(naoya, animation_1f, 1);
    ref_137 = msgShow(msg_20);
/***************************************
[tab]…満足した？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_137);
    dialogFree(ref_126);
    ref_13b = bustupFade(ref_124, rgb(0,0,0), 10);
    bustupWait(ref_13b);
    bustupFree(ref_124);
    unitAnimationPlay(naoya, animation_a, 1);
    delayClear();
    delayWait(60);
    unitAnimationStop(elly);
    unitAnimationPlay(elly, animation_41, 1);
    sndMusicPlay(sound_31b0, 127);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_42, 1);
    unitAnimationPlay(katsuya, animation_c, 1);
    delayClear();
    delayWait(90);
    unitFace_2(katsuya, south);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    sndMusicPlay(sound_31b1, 127);
    ref_14f = bustupLoad(bustup_124);
    bustupWait(ref_14f);
    ref_151 = bustupAlloc(ref_14f, left, rgb(0,0,0));
    bustupFade(ref_151, rgb(128,0,0), 30);
    ref_153 = dialogAlloc();
    ref_154 = msgShow(msg_21);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]そこか！
[sync][wait][clear]
***************************************/
    ref_155 = cameraMoveTo(810, 0, -830, 15);
    wait(ref_155);
    sync();
    wait(ref_154);
    dialogFree(ref_153);
    ref_15a = bustupFade(ref_151, rgb(0,0,0), 10);
    bustupWait(ref_15a);
    bustupFree(ref_151);
    unitAnimationPlay(baofu, animation_d, 1);
    unitAnimationPlay(katsuya, animation_5, 1);
    delayClear();
    delayWait(45);
    sndMusicPlay(sound_31b2, 127);
    unitWait(katsuya);
    ref_163 = dialogAlloc();
    ref_164 = msgShow(msg_22);
/***************************************
[color(yellow)]黒猫[color(white)]
[tab]ギニャァァァァ！！
[sync][wait][clear]
***************************************/
    call(CAT_JUMP);
    call(ODOROKI);
    sync();
    wait(ref_164);
    dialogFree(ref_163);
    delayClear();
    delayWait(60);
    ref_16c = efctDummy(effect_27);
    wait(ref_16c);
    ref_16e = efctLoad(effect_27);
    wait(ref_16e);
    sndLoad(sound_301d);
    unitAnimationPlay(maya, animation_a, 1);
    unitAnimationPlay(ulala, animation_a, 1);
    unitAnimationPlay(elly, animation_31, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_28, 1);
    unitWait(elly);
    delayClear();
    delayWait(60);
    unitAnimationPlay(enemy1, animation_d, 1);
    unitWait(enemy1);
    unitShadowRadius(enemy1, 30);
    sndMusicPlay(sound_31b4, 127);
    delayClear();
    delayWait(20);
    unitFace_2(enemy1, north);
    unitAnimationPlay(enemy1, animation_7, 1);
    unitWait(enemy1);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(enemy1, animation_10, 1);
    ref_18b = spriteLoad(sprite_15);
    wait(ref_18b);
    ref_18d = spriteLoad(sprite_d);
    wait(ref_18d);
    screenColorAdjust(0.5, 0.5, 0.61328125);
    ref_190 = spriteLoad(sprite_3);
    wait(ref_190);
    ref_192 = spriteLoad(sprite_8);
    wait(ref_192);
    ref_194 = spriteLoad(sprite_25);
    wait(ref_194);
    sndMusicPlay(sound_301d, 127);
    ref_197 = bustupLoad(bustup_2d);
    bustupWait(ref_197);
    ref_199 = bustupAlloc(ref_197, left, rgb(0,0,0));
    bustupFade(ref_199, rgb(128,0,0), 30);
    ref_19b = dialogAlloc();
    ref_19c = msgShow(msg_23);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]んなこったろうと思ったぜ…阿呆。
[sync][wait][clear]
***************************************/
    ref_19d = sndVoicePlay(sound_83, 127);
    sndWaitStart();
    unitMove(baofu, 570, -930, face_west, medium);
    unitWait(baofu);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    wait(ref_19d);
    sync();
    wait(ref_19c);
    dialogFree(ref_19b);
    ref_1a7 = bustupFade(ref_199, rgb(0,0,0), 10);
    bustupWait(ref_1a7);
    bustupFree(ref_199);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitAnimationHold(katsuya, animation_11, -1);
    ref_1ad = bustupLoad(bustup_23);
    bustupWait(ref_1ad);
    ref_1af = bustupAlloc(ref_1ad, left, rgb(0,0,0));
    bustupFade(ref_1af, rgb(128,0,0), 30);
    ref_1b1 = dialogAlloc();
    ref_1b2 = msgShow(msg_24);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]あのストーカーも今の少年も、
[tab]桐島君の恐怖心の投影…そんなところか。
[sync][wait][clear]
***************************************/
    ref_1b3 = sndVoicePlay(sound_c5, 127);
    sndWaitStart();
    wait(ref_1b3);
    sync();
    wait(ref_1b2);
    unitAnimationPlay(elly, animation_4, 1);
    unitAnimationStop(katsuya);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_1bb = msgShow(msg_25);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]生憎、今は大衆にも学問が浸透していてね。
[tab]呪術や幻術への免疫もできあがってるのさ…

***************************************/
    ref_1bc = sndVoicePlay(sound_c4, 127);
    sndWaitStart();
    wait(ref_1bb);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    ref_1c1 = msgShow(msg_26);
/***************************************
[tab]１００年…手が古かったな。
[sync][wait][clear]
***************************************/
    wait(ref_1bc);
    sync();
    wait(ref_1c1);
    dialogFree(ref_1b1);
    ref_1c6 = bustupFade(ref_1af, rgb(0,0,0), 10);
    bustupWait(ref_1c6);
    bustupFree(ref_1af);
    unitSpriteClear(maya);
    unitSpriteClear(ulala);
    unitSpriteClear(elly);
    unitSpriteSet(maya, sprite_3);
    unitSpriteSet(ulala, sprite_8);
    unitSpriteSet(elly, sprite_25);
    unitAnimationPlay(elly, animation_d, 1);
    ref_1d0 = dialogAlloc();
    ref_1d1 = msgShow(msg_27);
/***************************************
[color(yellow)]黒猫[color(white)]
[tab]お、おのれぇぇぇぇぇぇぇ！
[sync][wait][clear]
***************************************/
    ref_1d2 = sndVoicePlay(sound_72, 127);
    sndWaitStart();
    unitAnimationPlay(enemy1, animation_11, 1);
    wait(ref_1d2);
    sync();
    wait(ref_1d1);
    dialogFree(ref_1d0);
    unitAnimationPlay(enemy1, animation_10, 1);
    unitAnimationPlay(elly, animation_0, 1);
    ref_1db = bustupLoad(bustup_3f);
    bustupWait(ref_1db);
    ref_1dd = bustupAlloc(ref_1db, left, rgb(0,0,0));
    bustupFade(ref_1dd, rgb(128,0,0), 30);
    ref_1df = dialogAlloc();
    ref_1e0 = msgShow(msg_28);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]よくも…よくもあの人の顔で…[delay(60)]

***************************************/
    ref_1e1 = sndVoicePlay(sound_5e, 127);
    sndWaitStart();
    wait(ref_1e0);
    ref_1e4 = msgShow(msg_29);
/***************************************
[tab]許しませんわーっ！！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitAnimationHold(elly, animation_12, -1);
    wait(ref_1e1);
    sync();
    wait(ref_1e4);
    dialogFree(ref_1df);
    ref_1ec = bustupFade(ref_1dd, rgb(0,0,0), 10);
    bustupWait(ref_1ec);
    bustupFree(ref_1dd);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_31b5, 127);
    unitAnimationPlay(enemy1, animation_12, 1);
    ref_1f3 = sndLoad(sound_3162);
    delayClear();
    delayWait(60);
    unitDespawn(enemy1, ghost);
    efctPlay(effect_27, efct_0, 900, 0, -600, 900, 0, -600, false);
    delayClear();
    delayWait(60);
    wait(ref_1f3);
    sndMusicPlay(sound_3162, 127);
    encounterLoad(encounter_b);
    b(label_1ff);
  label_1fe:
    dngLoad2(sumaru_tv2-3);
  label_1ff:
}

function MAYA_TOJO()
{
    unitSpawn(maya, sprite_0, 850, 0, -1830, south, none);
    unitMove(maya, 850, -1600, face_east, medium);
    unitWait(maya);
    unitMove(maya, 650, -1600, face_east, medium);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_f, 1);
}

function URARA_TOJO()
{
    unitSpawn(ulala, sprite_6, 850, 0, -1830, south, none);
    unitMove(ulala, 850, -1650, face_west, medium);
    unitWait(ulala);
    sndMusicPlay(sound_31af, 127);
    objAnimRotate(obj_a, 0, 70, 0, 30, 0);
    unitMove(ulala, 1030, -1650, face_north, medium);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_e, 1);
}

function KATUYA_TOJO()
{
    unitSpawn(katsuya, sprite_d, 850, 0, -1830, south, none);
    unitMove(katsuya, 950, -1410, face_west, medium);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_2a, 1);
}

function PAOFU_TOJO()
{
    unitSpawn(baofu, sprite_13, 850, 0, -1830, south, none);
    unitMove(baofu, 850, -1350, face_east, medium);
    unitWait(baofu);
    unitMove(baofu, 550, -1350, face_east, medium);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_2a, 1);
}

function ERI_TOJO()
{
    unitSpawn(elly, sprite_23, 850, 0, -1830, south, none);
    unitMove(elly, 800, -1500, face_south, medium);
    unitWait(elly);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_28, 1);
    unitWait(elly);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_5, 1);
}

function MAYA_IDO()
{
    unitMove(maya, 530, -1250, face_south, fast);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
}

function URARA_IDO()
{
    unitMove(ulala, 720, -1650, face_south, fast);
    unitWait(ulala);
    unitMove(ulala, 720, -1300, face_south, medium);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
}

function KATUYA_IDO()
{
    unitMove(katsuya, 920, -1050, face_east, fast);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_b, 1);
}

function PAOFU_IDO()
{
    unitMove(baofu, 550, -1080, face_south, fast);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
}

function ERI_IDO()
{
    unitMove(elly, 720, -1150, face_south, medium);
    unitWait(elly);
    unitAnimationPlay(elly, animation_a, 1);
}

function HERO_IDO()
{
    unitMove(naoya, 750, -750, face_north, slow);
    unitWait(naoya);
    unitAnimationPlay(naoya, animation_a, 1);
}

function ODOROKI()
{
    unitAnimationPlay(elly, animation_3f, 1);
    unitAnimationHold(maya, animation_21, 60);
    unitAnimationHold(ulala, animation_21, 60);
}

function CAT_JUMP()
{
    unitDespawn(naoya, ghost);
    sndMusicPlay(sound_31b3, 127);
    unitSpawn(enemy1, sprite_89, 1080, 0, -530, east, none);
    unitShadowRadius(enemy1, 0);
    unitAnimationPlay(enemy1, animation_15, 1);
    unitJumpTo(enemy1, 900, 0, -600, 20, 0);
    unitWait(enemy1);
    unitAnimationPlay(enemy1, animation_16, 1);
}
