
msg_0:
[color(yellow)]ＪＯＫＥＲ銀次[color(white)]
[tab]ぐぐ…
[sync][wait][clear][end]

msg_1:
[color(yellow)]パオフゥ[color(white)]
[tab]チッ…
[tab]とんだことになりやがったぜ…
[sync][wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]結局、何も聞き出せなかったな…
[end]

msg_3:
[tab]強度のマインドコントロールも受けていた様だし、
[tab]下っ端をいくら挙げても無駄かもしれない…
[sync][wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]でもこれと同じ事、
[tab]あっちこっちでやってんでしょ？
[end]

msg_5:
[tab]どうすんのさ…
[sync][wait][clear][end]

msg_6:
[color(yellow)]エリー[color(white)]
[tab]数が多くて手に負えませんわね…
[end]

msg_7:
[tab]これ以上被害を増やさないためにも、
[tab]新世塾の情報を公開するべきですわ。
[sync][wait][clear][end]

msg_8:
[color(yellow)]エリー[color(white)]
[tab]Ｋｅｉ？
[tab]新世塾の情報を、Ｍａｓｓ[tab]ｍｅｄｉａに
[tab]流して欲しいんですの…
[sync][wait][clear][end]

msg_9:
[color(yellow)]南条[color(white)]
[tab]一つ一つ潰していっても、焼け石に水だ。
[end]

msg_10:
[tab]これ以上被害を増やさないためにも、
[tab]新世塾の情報を公開すべきでしょう。
[sync][wait][clear][end]

msg_11:
[color(yellow)]南条[color(white)]
[tab]桐島か？
[tab]松岡に我々が集めた新世塾のデータを渡してくれ。
[tab]信頼できるマスコミにリークする。
[sync][wait][clear][end]

msg_12:
[color(yellow)]スニークの声[color(white)]
[tab]私だ…スニークだ。
[sync][wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]…ひとつ聞きたい。
[tab]ペントハウスが襲撃された…お前のせいか？
[sync][wait][clear][end]

msg_14:
[color(yellow)]スニークの声[color(white)]
[tab]…信じてくれと言っても、無理かな？
[tab]わかった…次は姿を見せよう。
[tab]気が済むようにしたらいい…
[sync][wait][clear][end]

msg_15:
[color(yellow)]スニークの声[color(white)]
[tab]ただ…伝えなければならない事がある。
[tab]それを聞いてからにして欲しい。
[tab]青葉公園の野外音楽堂で待っているよ…
[sync][wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]あいつか…？
[sync][wait][clear][end]

msg_17:
[color(yellow)]克哉[color(white)]
[tab]ああ…[delay(30)]
[end]

msg_18:
[tab]野外音楽堂に呼び出された。
[sync][wait][clear][end]

msg_19:
[color(yellow)]うらら[color(white)]
[tab]やめなって！[tab]絶対罠だよ！！
[sync][wait][clear][end]

msg_20:
[color(yellow)]克哉[color(white)]
[tab]南条君のペントハウスの件もある…[delay(30)]
[end]

msg_21:
[tab]本当に信頼できるかどうか…行ってみるつもりだ。
[sync][wait][clear][end]

msg_22:
[color(yellow)]パオフゥ[color(white)]
[tab]へっ…どうだかな。
[tab]てめぇの親父の事が知りたいだけじゃねぇのか？
[end]

msg_23:
[tab]巻き添えはごめんだぜ…
[sync][wait][clear][end]

msg_24:
[color(yellow)]克哉[color(white)]
[tab]好きにするさ…
[tab]僕もお前が来るとは思ってない。
[sync][wait][clear][end]

msg_25:
[color(yellow)]克哉[color(white)]
[tab]天野君…行ってくる。
[sync][wait][clear][end]

msg_26:
[color(yellow)]うらら[color(white)]
[tab]ちょっと、なんであんな事言うわけ！？
[end]

msg_27:
[tab]仲間でしょ！？
[sync][wait][clear][end]

msg_28:
[color(yellow)]パオフゥ[color(white)]
[tab]へへ…
[tab]そんな風に思ったことは一度もねぇな…
[sync][wait][clear][end]

msg_29:
[color(yellow)]パオフゥ[color(white)]
[tab]イライラはしてもな…
[sync][wait][clear][end]

msg_30:
[color(yellow)]うらら[color(white)]
[tab]おいこら、パオ…
[end]

msg_31:
[tab]本気で見損なうよ…
[sync][wait][clear][end]

msg_32:
[color(yellow)]うらら[color(white)]
[tab]追えったら追え！
[end]

msg_33:
[tab]それともここでオネンネする！？
[sync][wait][clear][end]

msg_34:
[color(yellow)]パオフゥ[color(white)]
[tab]パオ…
[sync][wait][clear][end]

msg_35:
[color(yellow)]パオフゥ[color(white)]
[tab]チッ…わかったよ…[delay(30)]
[end]

msg_36:
[tab]あいつはどうでもいいが、ここで天野と別れんのは
[tab]得じゃねぇからな…
[sync][wait][clear][end]
