
msg_0:
[color(yellow)]パオフゥ[color(white)]
[tab]もう逃げようがねぇぜ…諦めな…
[sync][wait][clear][end]

msg_1:
[color(yellow)]云豹[color(white)]
[tab]竜蔵は私裏切った。
[tab]私が殺す…
[sync][wait][clear][end]

msg_2:
[color(yellow)]云豹[color(white)]
[tab]見逃せないか…？
[sync][wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
[tab]できねぇな…
[sync][wait][clear][end]

msg_4:
[color(yellow)]云豹[color(white)]
[tab]そうか…
[sync][wait][clear][end]

msg_5:
[color(yellow)]云豹[color(white)]
[tab]………
[tab]あれから…何年…だ…？
[sync][wait][clear][end]

msg_6:
[color(yellow)]パオフゥ[color(white)]
[tab]５年だ…
[tab]胸の傷がふさがるにゃ…短か過ぎる…
[tab]あばよ…
[sync][wait][clear][end]

msg_7:
[color(yellow)]克哉の声[color(white)]
[tab]やめろ、嵯峨…！
[sync][wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]元、珠閒瑠地検特別刑事部の特捜検事、
[tab]嵯峨[tab]薫（さが[tab]かおる）…
[end]

msg_9:
[tab]南条君に調べてもらったよ…
[sync][wait][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]うそ…検事って…
[sync][wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]５年前、台湾で検察官と検察事務官の男女が、
[tab]旅行中に死亡した事故記録があった…
[sync][wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]旅行でもなければ、事故でもなかったんだな…
[end]

msg_13:
[tab]法務省で握り潰された「天道連疑惑」…
[end]

msg_14:
[tab]知らなかったよ…
[sync][wait][clear][end]

msg_15:
[color(yellow)]克哉[color(white)]
[tab]目的は、浅井[tab]美樹さんの仇討ちか…？
[end]

msg_16:
[tab]竜蔵への復讐か？
[sync][wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]黙ってろ…
[sync][wait][clear][end]

msg_18:
[color(yellow)]克哉[color(white)]
[tab]お前は、盗聴がばれていた事も知っていた…
[end]

msg_19:
[tab]それを承知で罠に飛び込んだんだ。
[end]

msg_20:
[tab]僕たちを足止めにして、そいつを殺すために…
[sync][wait][clear][end]

msg_21:
[color(yellow)]うらら[color(white)]
[tab]ほ…ほんとなの…？
[sync][wait][clear][end]

msg_22:
[color(yellow)]克哉[color(white)]
[tab]最初からそのつもりだったのか…？
[tab]僕達を利用するために…
[sync][wait][clear][end]

msg_23:
[color(yellow)]パオフゥ[color(white)]
[tab]そこまでわかってるなら、邪魔するな！
[sync][wait][clear][end]

msg_24:
[color(yellow)]克哉[color(white)]
[tab]逮捕するんだ…
[end]

msg_25:
[tab]気持ちはわかるが、殺せばそいつらと変わらない。
[end]

msg_26:
[tab]竜蔵の汚職や悪事の一切を証言させるんだ…
[sync][wait][clear][end]

msg_27:
[color(yellow)]うらら[color(white)]
[tab]やめてぇー！
[sync][wait][clear][end]

msg_28:
[color(yellow)]天誅軍兵士[color(white)]
[tab]ガフッ…
[sync][wait][clear][end]

msg_29:
[color(yellow)]パオフゥ[color(white)]
[tab]どいつもこいつも人の邪魔しやがる…
[end]

msg_30:
[tab]いいぜ…来な！
[sync][wait][clear][end]
