
msg_0:
[color(yellow)]克哉[color(white)]
[tab]このまま…
[end]

msg_1:
[tab]公僕のまま、死なせはしない…
[sync][wait][clear][end]

msg_2:
[color(yellow)]島津管理官[color(white)]
[tab]無原罪の…世界を創るためだよ…
[tab]私は…間違っていない…
[sync][wait][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]富樫署長…！
[sync][wait][clear][end]

msg_4:
[color(yellow)]富樫署長[color(white)]
[tab]克哉君…済まなかった…
[tab]私は…愚かだった…
[tab]奴等を…止めてくれ…
[sync][wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]わかりました…
[sync][wait][clear][end]

msg_6:
[color(yellow)]富樫署長[color(white)]
[tab]や、奴等の…アジト…は…
[sync][wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]笑わないのか…？
[end]

msg_8:
[tab]結果はどうあれ…罠にはまったのは事実だ…
[sync][wait][clear][end]

msg_9:
[color(yellow)]パオフゥ[color(white)]
[tab]死んだ漢の前で爆笑するほど、腐っちゃいねぇよ…[delay(30)]
[end]

msg_10:
[tab]おっさんは過去の罪を償った…
[tab]漢には敬意を表するもんだ…
[sync][wait][clear][end]

msg_11:
[color(yellow)]パオフゥ[color(white)]
[tab]一旦、俺のヤサに戻るぜ…
[tab]竜蔵の動きが気になる…
[sync][wait][clear][end]
