function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    cameraSet(northwest, 1050, 0, -380);
    levelFootstepSet(sfx_10);
    ref_9 = spriteLoad(sprite_0);
    wait(ref_9);
    ref_b = spriteLoad(sprite_3);
    wait(ref_b);
    ref_d = spriteLoad(sprite_6);
    wait(ref_d);
    ref_f = spriteLoad(sprite_8);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_f);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_13);
    wait(ref_13);
    ref_15 = spriteLoad(sprite_15);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_86);
    wait(ref_17);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_22);
    ref_1b = spriteLoad(sprite_25);
    wait(ref_1b);
    ref_1d = spriteLoad(sprite_23);
    wait(ref_1d);
    unitSpawn(elly, sprite_25, 920, 0, -550, south, none);
    unitAnimationHold(elly, animation_4, -1);
    b(label_2a);
  label_22:
    bne(var_0, 1, label_2a);
    ref_23 = spriteLoad(sprite_1f);
    wait(ref_23);
    ref_25 = spriteLoad(sprite_21);
    wait(ref_25);
    unitSpawn(nanjo, sprite_21, 920, 0, -550, south, none);
    unitAnimationHold(nanjo, animation_4, -1);
    b(label_2a);
  label_2a:
    unitSpawn(maya, sprite_3, 1040, 0, -460, south, none);
    unitSpawn(ulala, sprite_8, 1200, 0, -550, south, none);
    unitSpawn(katsuya, sprite_f, 1100, 0, -620, south, none);
    unitSpawn(baofu, sprite_15, 1100, 0, -780, south, none);
    unitSpawn(enemy1, sprite_86, 1200, 0, -150, north, none);
    unitAnimationPlay(maya, animation_d, 1);
    unitAnimationPlay(enemy1, animation_10, 1);
    bitSet(TBIT_MD604);
    bitClear(TBIT_MD505);
    bitClear(TBIT_ON603);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_320d, 127);
    ref_3a = efctDummy(effect_7);
    ref_3b = efctLoad(effect_7);
    delayClear();
    delayWait(60);
    unitAnimationPlay(enemy1, animation_c, 1);
    unitWait(enemy1);
    ref_40 = unitColor(enemy1, rgb(0,0,0), 5);
    wait(ref_40);
    ref_42 = unitColor(enemy1, rgb(112,112,112), 5);
    wait(ref_42);
    ref_44 = unitColor(enemy1, rgb(0,0,0), 5);
    wait(ref_44);
    ref_46 = unitColor(enemy1, rgb(112,112,112), 5);
    wait(ref_46);
    ref_48 = unitColor(enemy1, rgb(0,0,0), 5);
    wait(ref_48);
    ref_4a = unitColor(enemy1, rgb(112,112,112), 5);
    wait(ref_4a);
    ref_4c = unitColor(enemy1, rgb(0,0,0), 5);
    wait(ref_4c);
    ref_4e = unitColor(enemy1, rgb(112,112,112), 5);
    wait(ref_4e);
    ref_50 = unitColor(enemy1, rgb(0,0,0), 5);
    wait(ref_50);
    ref_52 = unitColor(enemy1, rgb(112,112,112), 5);
    wait(ref_52);
    ref_54 = unitColor(enemy1, rgb(0,0,0), 5);
    wait(ref_54);
    ref_56 = unitColor(enemy1, rgb(112,112,112), 5);
    wait(ref_56);
    wait(ref_3a);
    wait(ref_3b);
    efctPlay(effect_7, efct_0, 1200, 0, -150, 1200, 0, -150, false);
    unitDespawn(enemy1, ghost);
    unitSpriteClear(enemy1);
    efctWait(efct_0);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_12, 1);
    call(MAYA_SET);
    call(URARA_SET);
    call(PAOFU_SET);
    bne(var_0, 0, label_67);
    call(ERI_SET);
    b(label_6a);
  label_67:
    bne(var_0, 1, label_6a);
    call(NANJO_SET);
    b(label_6a);
  label_6a:
    ref_6a = spriteLoad(sprite_48);
    wait(ref_6a);
    ref_6c = spriteLoad(sprite_eb);
    wait(ref_6c);
    ref_6e = spriteLoad(sprite_d);
    wait(ref_6e);
    unitSpawn(unit_17, sprite_48, 1100, 0, -1300, south, none);
    unitSpawn(unit_67, sprite_eb, 1100, 0, -1300, south, none);
    unitAnimationPlay(unit_17, animation_5d, 1);
    unitAnimationPlay(baofu, animation_12, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    unitFace_2(baofu, north);
    unitAnimationHold(baofu, animation_21, 60);
    call(KATUYA_HURIKAERI);
    call(URARA_HURIKAERI);
    delayClear();
    delayWait(30);
    bne(var_0, 0, label_80);
    call(ERI_HURIKAERI);
    b(label_83);
  label_80:
    bne(var_0, 1, label_83);
    call(NANJO_HURIKAERI);
    b(label_83);
  label_83:
    call(MAYA_HURIKAERI);
    waitFunc(MAYA_HURIKAERI);
    delayClear();
    delayWait(30);
    unitMove(baofu, 1100, -1100, face_north, slow);
    delayClear();
    delayWait(30);
    ref_8a = cameraRotateTo(5, 1);
    ref_8b = cameraMoveTo(1080, 0, -1230, 1);
    wait(ref_8a);
    wait(ref_8b);
    unitAnimationStop(katsuya);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_29, 1);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    ref_94 = bustupLoad(bustup_4c);
    bustupWait(ref_94);
    ref_96 = bustupAlloc(ref_94, right, rgb(0,0,0));
    bustupFade(ref_96, rgb(128,0,0), 30);
    ref_98 = dialogAlloc();
    ref_99 = msgShow(msg_0);
/***************************************
[color(yellow)]云豹[color(white)]
[tab]菅原陸将ご自慢の…「×－１」か…
[tab]さすがに…狙いは…正確ね…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_99);
    dialogFree(ref_98);
    ref_9d = bustupFade(ref_96, rgb(0,0,0), 10);
    bustupWait(ref_9d);
    bustupFree(ref_96);
    delayClear();
    delayWait(30);
    unitAnimationPlay(unit_17, animation_5c, 1);
    ref_a3 = bustupLoad(bustup_4c);
    bustupWait(ref_a3);
    ref_a5 = bustupAlloc(ref_a3, right, rgb(0,0,0));
    bustupFade(ref_a5, rgb(128,0,0), 30);
    ref_a7 = dialogAlloc();
    ref_a8 = msgShow(msg_1);
/***************************************
[color(yellow)]云豹[color(white)]
[tab]竜蔵は…今ごろきっと海の上だね…
[tab]海底遺跡の…青龍の封印解こうとしてるはず…
[tab]竜蔵のアジト…日輪丸という船だ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a8);
    unitAnimationPlay(unit_17, animation_5d, 1);
    ref_ac = msgShow(msg_2);
/***************************************
[color(yellow)]云豹[color(white)]
[tab]竜蔵会ったら…
[tab]地獄で待ってる…伝えとけ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ac);
    dialogFree(ref_a7);
    ref_b0 = bustupFade(ref_a5, rgb(0,0,0), 10);
    bustupWait(ref_b0);
    bustupFree(ref_a5);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_320e, 127);
    unitAnimationPlay(unit_17, animation_5e, 1);
    unitWait(unit_17);
    delayClear();
    delayWait(90);
    ref_ba = bustupLoad(bustup_30);
    bustupWait(ref_ba);
    ref_bc = bustupAlloc(ref_ba, left, rgb(0,0,0));
    bustupFade(ref_bc, rgb(128,0,0), 30);
    ref_be = dialogAlloc();
    ref_bf = msgShow(msg_3);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ああ…野郎もきっちり送ってやる…
[tab]安心して地獄に逝きな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_bf);
    dialogFree(ref_be);
    ref_c3 = bustupFade(ref_bc, rgb(0,0,0), 10);
    bustupWait(ref_c3);
    bustupFree(ref_bc);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_12, 1);
    unitWait(baofu);
    cameraRotateTo(7, 1);
    cameraMoveTo(1000, 0, -517, 1);
    unitMove(baofu, 1100, -800, face_south, slow);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(60);
    unitAnimationHold(baofu, animation_11, -1);
    ref_d2 = bustupLoad(bustup_30);
    bustupWait(ref_d2);
    ref_d4 = bustupAlloc(ref_d2, left, rgb(0,0,0));
    bustupFade(ref_d4, rgb(128,0,0), 30);
    ref_d6 = dialogAlloc();
    ref_d7 = msgShow(msg_4);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]俺が撃ったら…どうするつもりだったんだ…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d7);
    dialogFree(ref_d6);
    ref_db = bustupFade(ref_d4, rgb(0,0,0), 10);
    bustupWait(ref_db);
    bustupFree(ref_d4);
    unitAnimationStop(baofu);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_1d, 1);
    ref_e2 = bustupLoad(bustup_21);
    bustupWait(ref_e2);
    ref_e4 = bustupAlloc(ref_e2, left, rgb(0,0,0));
    bustupFade(ref_e4, rgb(128,0,0), 30);
    ref_e6 = dialogAlloc();
    ref_e7 = msgShow(msg_5);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]女のために復讐しようとする甘ちゃんに、
[tab]無関係の人間は撃てないよ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_e7);
    dialogFree(ref_e6);
    ref_eb = bustupFade(ref_e4, rgb(0,0,0), 10);
    bustupWait(ref_eb);
    bustupFree(ref_e4);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_10, 1);
    ref_f2 = bustupLoad(bustup_33);
    bustupWait(ref_f2);
    ref_f4 = bustupAlloc(ref_f2, left, rgb(0,0,0));
    bustupFade(ref_f4, rgb(128,0,0), 30);
    ref_f6 = dialogAlloc();
    ref_f7 = msgShow(msg_6);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]フッ…
[tab]そうでもないかもしれんぜ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f7);
    dialogFree(ref_f6);
    ref_fb = bustupFade(ref_f4, rgb(0,0,0), 10);
    bustupWait(ref_fb);
    bustupFree(ref_f4);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_10, 1);
    ref_101 = bustupLoad(bustup_1a);
    bustupWait(ref_101);
    ref_103 = bustupAlloc(ref_101, left, rgb(0,0,0));
    bustupFade(ref_103, rgb(128,0,0), 30);
    ref_105 = dialogAlloc();
    ref_106 = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_106);
    dialogFree(ref_105);
    ref_10a = bustupFade(ref_103, rgb(0,0,0), 10);
    bustupWait(ref_10a);
    bustupFree(ref_103);
    delayClear();
    delayWait(60);
    bne(var_0, 0, label_112);
    b(label_115);
    b(label_115);
  label_112:
    bne(var_0, 1, label_115);
    b(label_138);
    b(label_115);
  label_115:
    unitAnimationPlay(elly, animation_e, 1);
    delayClear();
    delayWait(30);
    unitFace_2(elly, west);
    unitAnimationPlay(elly, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_14, 1);
    ref_11d = bustupLoad(bustup_3d);
    bustupWait(ref_11d);
    ref_11f = bustupAlloc(ref_11d, left, rgb(0,0,0));
    bustupFade(ref_11f, rgb(128,0,0), 30);
    ref_121 = dialogAlloc();
    ref_122 = msgShow(msg_8);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]ゆっくりしている暇はありませんわ。

***************************************/
    wait(ref_122);
    unitAnimationPlay(maya, animation_b, 1);
    unitAnimationPlay(ulala, animation_c, 1);
    unitAnimationPlay(katsuya, animation_c, 1);
    unitAnimationPlay(baofu, animation_d, 1);
    ref_128 = msgShow(msg_9);
/***************************************
[tab]Ｔａｔｕｚｏｕを追わないと…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_128);
    unitAnimationHold(elly, animation_1a, -1);
    ref_12c = msgShow(msg_10);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]確か、ＫｅｉのＣｒｕｉｓｅｒが
[tab]Ｙａｃｈｔ[tab]Ｈａｒｂｏｒにあったはずですわ。

***************************************/
    wait(ref_12c);
    unitAnimationPlay(elly, animation_1f, 1);
    ref_12f = msgShow(msg_11);
/***************************************
[tab]連絡してみます。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12f);
    dialogFree(ref_121);
    ref_133 = bustupFade(ref_11f, rgb(0,0,0), 10);
    bustupWait(ref_133);
    bustupFree(ref_11f);
    unitAnimationPlay(elly, animation_a, 1);
    b(label_154);
  label_138:
    unitAnimationPlay(nanjo, animation_4, 1);
    delayClear();
    delayWait(30);
    unitFace_2(nanjo, west);
    unitAnimationPlay(nanjo, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(nanjo, animation_14, 1);
    ref_140 = bustupLoad(bustup_36);
    bustupWait(ref_140);
    ref_142 = bustupAlloc(ref_140, left, rgb(0,0,0));
    bustupFade(ref_142, rgb(128,0,0), 30);
    ref_144 = dialogAlloc();
    ref_145 = msgShow(msg_12);
/***************************************
[color(yellow)]南条[color(white)]
[tab]悪いが、ゆっくりしている暇はない。

***************************************/
    wait(ref_145);
    unitAnimationPlay(maya, animation_b, 1);
    unitAnimationPlay(ulala, animation_c, 1);
    unitAnimationPlay(katsuya, animation_c, 1);
    unitAnimationPlay(baofu, animation_d, 1);
    unitAnimationPlay(nanjo, animation_1f, 1);
    ref_14c = msgShow(msg_13);
/***************************************
[tab]さっそく竜蔵を追いましょう。
[tab]ヨットハーバーにうちのクルーザーがある。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_14c);
    dialogFree(ref_144);
    ref_150 = bustupFade(ref_142, rgb(0,0,0), 10);
    bustupWait(ref_150);
    bustupFree(ref_142);
    unitAnimationPlay(nanjo, animation_a, 1);
  label_154:
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_26, 1);
    unitAnimationPlay(ulala, animation_26, 1);
    unitAnimationPlay(katsuya, animation_26, 1);
    unitAnimationPlay(baofu, animation_26, 1);
    unitWait(maya);
    unitWait(ulala);
    unitWait(katsuya);
    unitWait(baofu);
    delayClear();
    delayWait(30);
    call(MAYA_TAIJO);
    call(URARA_TAIJO);
    call(KATUYA_TAIJO);
    delayClear();
    delayWait(60);
    unitMove(baofu, 1100, -200, despawn, slow);
    bne(var_0, 0, label_169);
    call(ERI_TAIJO);
    b(label_16c);
  label_169:
    bne(var_0, 1, label_16c);
    call(NANJO_TAIJO);
    b(label_16c);
  label_16c:
    delayClear();
    delayWait(30);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    mapLoad(kounan, 15, 1);
}

function MAYA_SET()
{
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitAnimationPlay(maya, animation_a, 1);
}

function URARA_SET()
{
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitAnimationHold(ulala, animation_11, -1);
}

function PAOFU_SET()
{
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitAnimationPlay(baofu, animation_a, 1);
}

function NANJO_SET()
{
    unitSpriteClear(nanjo);
    unitSpriteSet(nanjo, sprite_1f);
    unitAnimationPlay(nanjo, animation_a, 1);
}

function ERI_SET()
{
    unitSpriteClear(elly);
    unitSpriteSet(elly, sprite_23);
    unitAnimationPlay(elly, animation_a, 1);
}

function MAYA_HURIKAERI()
{
    unitAnimationPlay(maya, animation_12, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitFace_2(maya, north);
    unitAnimationHold(maya, animation_21, 60);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
}

function URARA_HURIKAERI()
{
    unitAnimationPlay(ulala, animation_12, 1);
    unitWait(ulala);
    delayClear();
    delayWait(30);
    unitFace_2(ulala, north);
    unitAnimationHold(ulala, animation_22, 60);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_0, 1);
}

function KATUYA_HURIKAERI()
{
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, north);
    unitAnimationHold(katsuya, animation_11, -1);
}

function ERI_HURIKAERI()
{
    unitAnimationPlay(elly, animation_12, 1);
    unitWait(elly);
    delayClear();
    delayWait(30);
    unitFace_2(elly, north);
    unitAnimationHold(elly, animation_21, 60);
    unitWait(elly);
    unitAnimationPlay(elly, animation_d, 1);
}

function NANJO_HURIKAERI()
{
    unitAnimationPlay(nanjo, animation_12, 1);
    unitWait(nanjo);
    delayClear();
    delayWait(30);
    unitFace_2(nanjo, north);
    unitAnimationHold(nanjo, animation_21, 60);
    unitWait(nanjo);
    unitAnimationPlay(nanjo, animation_d, 1);
}

function MAYA_TAIJO()
{
    unitAnimationPlay(maya, animation_12, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitFace_2(maya, south);
    unitMove(maya, 1000, -200, despawn, slow);
}

function URARA_TAIJO()
{
    unitAnimationPlay(ulala, animation_12, 1);
    unitWait(ulala);
    delayClear();
    delayWait(30);
    unitFace_2(ulala, south);
    unitMove(ulala, 1200, -200, despawn, slow);
}

function KATUYA_TAIJO()
{
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, south);
    unitMove(katsuya, 1100, -200, despawn, slow);
}

function ERI_TAIJO()
{
    unitAnimationPlay(elly, animation_2, 1);
    delayClear();
    delayWait(15);
    unitFace_2(elly, south);
    unitMove(elly, 920, -200, despawn, slow);
}

function NANJO_TAIJO()
{
    unitAnimationPlay(nanjo, animation_2, 1);
    delayClear();
    delayWait(15);
    unitFace_2(nanjo, south);
    unitMove(nanjo, 920, -200, despawn, slow);
}
