function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    cameraSet(southwest, 700, 0, -1950);
    sndMusicPlay(sound_3025, 127);
    levelFootstepSet(sfx_19);
    ref_a = spriteLoad(sprite_72);
    wait(ref_a);
    ref_c = spriteLoad(sprite_73);
    wait(ref_c);
    ref_e = spriteLoad(sprite_74);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_0);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_3);
    wait(ref_12);
    ref_14 = spriteLoad(sprite_6);
    wait(ref_14);
    ref_16 = spriteLoad(sprite_d);
    wait(ref_16);
    ref_18 = spriteLoad(sprite_13);
    wait(ref_18);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_1f);
    ref_1c = spriteLoad(sprite_23);
    wait(ref_1c);
    b(label_23);
  label_1f:
    bne(var_0, 1, label_23);
    ref_20 = spriteLoad(sprite_1f);
    wait(ref_20);
    b(label_23);
  label_23:
    unitSpawn(ginji, sprite_72, 700, 0, -700, north, none);
    unitSpawn(katsuya, sprite_d, 700, 0, -950, south, none);
    unitSpawn(baofu, sprite_13, 520, 0, -860, west, none);
    unitAnimationPlay(ginji, animation_17, 1);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(baofu, animation_b, 1);
    ref_29 = todLoad(tod_6);
    objVisible(obj_2e, false);
    bitClear(DBIT_SMILE_KEIHO);
    partyMemberAdd(katsuya);
    partyMemberAdd(baofu);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_33 = efctAuraLoad();
    wait(ref_33);
    ref_35 = sndLoad(sound_301d);
    sndMusicPlay(sound_31d4, 127);
    objAnimRotate(obj_3, 0, -70, 0, 30, 0);
    ref_38 = objAnimRotate(obj_4, 0, 70, 0, 30, 0);
    wait(ref_38);
    wait(ref_38);
    call(MAYA_TOJO);
    delayClear();
    delayWait(30);
    call(URARA_TOJO);
    delayClear();
    delayWait(30);
    bne(var_0, 0, label_44);
    call(ERI_TOJO);
    b(label_47);
  label_44:
    bne(var_0, 1, label_47);
    call(NANJO_TOJO);
    b(label_47);
  label_47:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_31d4, 127);
    objAnimRotate(obj_3, 0, 70, 0, 30, 0);
    ref_4b = objAnimRotate(obj_4, 0, -70, 0, 30, 0);
    wait(ref_4b);
    wait(ref_4b);
    ref_4e = cameraMoveTo(650, 0, -800, 1);
    ref_4f = cameraRotateTo(7, 1);
    wait(ref_4e);
    wait(ref_4f);
    objVisible(obj_2e, true);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ginji, animation_26, 1);
    ref_56 = bustupLoad(bustup_58);
    bustupWait(ref_56);
    ref_58 = bustupAlloc(ref_56, right, rgb(0,0,0));
    bustupFade(ref_58, rgb(128,0,0), 30);
    ref_5a = dialogAlloc();
    ref_5b = msgShow(msg_0);
/***************************************
[color(yellow)]銀次[color(white)]
[tab]なんなんだ君達は！？
[tab]こんなことをして、穢れに憑かれても知らないぞ！
[tab]私はみんなの罪穢れをだな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5b);
    dialogFree(ref_5a);
    ref_5f = bustupFade(ref_58, rgb(0,0,0), 10);
    bustupWait(ref_5f);
    bustupFree(ref_58);
    unitAnimationPlay(ginji, animation_0, 1);
    unitAnimationPlay(katsuya, animation_2b, 1);
    ref_64 = bustupLoad(bustup_23);
    bustupWait(ref_64);
    ref_66 = bustupAlloc(ref_64, left, rgb(0,0,0));
    bustupFade(ref_66, rgb(128,0,0), 30);
    ref_68 = dialogAlloc();
    ref_69 = msgShow(msg_1);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]こんなもので罪が消せるなら、誰も苦労しない。

***************************************/
    wait(ref_69);
    unitAnimationHold(katsuya, animation_11, -1);
    ref_6c = msgShow(msg_2);
/***************************************
[tab]下らない世迷言で人を惑わすのは
[tab]止めてもらいたいな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6c);
    dialogFree(ref_68);
    ref_70 = bustupFade(ref_66, rgb(0,0,0), 10);
    bustupWait(ref_70);
    bustupFree(ref_66);
    unitAnimationStop(katsuya);
    delayClear();
    delayWait(30);
    ref_76 = bustupLoad(bustup_31);
    bustupWait(ref_76);
    ref_78 = bustupAlloc(ref_76, left, rgb(0,0,0));
    bustupFade(ref_78, rgb(128,0,0), 30);
    ref_7a = dialogAlloc();
    ref_7b = msgShow(msg_3);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]まったくだぜ…

***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    unitWait(baofu);
    wait(ref_7b);
    unitAnimationPlay(ginji, animation_1, 1);
    unitAnimationPlay(baofu, animation_b, 1);
    ref_81 = msgShow(msg_4);
/***************************************
[tab]お前さんにゃ、聞きてぇ事が山ほどあるんだ。
[tab]そんな機械より、てめぇの心配でもしてな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_81);
    dialogFree(ref_7a);
    ref_85 = bustupFade(ref_78, rgb(0,0,0), 10);
    bustupWait(ref_85);
    bustupFree(ref_78);
    unitAnimationHold(ginji, animation_1b, -1);
    ref_89 = bustupLoad(bustup_58);
    bustupWait(ref_89);
    ref_8b = bustupAlloc(ref_89, right, rgb(0,0,0));
    bustupFade(ref_8b, rgb(128,0,0), 30);
    ref_8d = dialogAlloc();
    ref_8e = msgShow(msg_5);
/***************************************
[color(yellow)]銀次[color(white)]
[tab]私は何も喋らんぞ！？

***************************************/
    wait(ref_8e);
    unitAnimationStop(ginji);
    unitAnimationPlay(ginji, animation_26, 1);
    ref_92 = msgShow(msg_6);
/***************************************
[tab]横暴だ！[tab]弁護士を呼んでくれ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_92);
    dialogFree(ref_8d);
    ref_96 = bustupFade(ref_8b, rgb(0,0,0), 10);
    bustupWait(ref_96);
    bustupFree(ref_8b);
    delayClear();
    delayWait(90);
    unitAnimationHold(baofu, animation_11, -1);
    ref_9c = bustupLoad(bustup_2e);
    bustupWait(ref_9c);
    ref_9e = bustupAlloc(ref_9c, left, rgb(0,0,0));
    bustupFade(ref_9e, rgb(128,0,0), 30);
    ref_a0 = dialogAlloc();
    ref_a1 = msgShow(msg_7);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ぎゃあぎゃあうるせぇ男だな…

***************************************/
    wait(ref_a1);
    unitAnimationStop(baofu);
    unitAnimationPlay(baofu, animation_3, 1);
    ref_a5 = msgShow(msg_8);
/***************************************
[tab]天野…そんなもんがクソの役にも立たねぇって
[tab]教えてやんな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a5);
    dialogFree(ref_a0);
    ref_a9 = bustupFade(ref_9e, rgb(0,0,0), 10);
    bustupWait(ref_a9);
    bustupFree(ref_9e);
    unitAnimationPlay(ginji, animation_17, 1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, north);
    unitAnimationPlay(katsuya, animation_24, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_24, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    call(KATUYA_IDO);
    call(PAOFU_IDO);
    delayClear();
    delayWait(30);
    unitMove(maya, 700, -850, face_south, medium);
    call(URARA_IDO);
    call(ERI_IDO);
    waitFunc(URARA_IDO);
    waitFunc(ERI_IDO);
    unitWait(maya);
    sndMusicPlay(sound_31d5, 127);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
    unitAnimationHold(ginji, animation_1b, 60);
    unitWait(ginji);
    unitAnimationPlay(ginji, animation_19, 1);
    ref_cb = bustupLoad(bustup_58);
    bustupWait(ref_cb);
    ref_cd = bustupAlloc(ref_cb, right, rgb(0,0,0));
    bustupFade(ref_cd, rgb(128,0,0), 30);
    ref_cf = dialogAlloc();
    ref_d0 = msgShow(msg_9);
/***************************************
[color(yellow)]銀次[color(white)]
[tab]な、何をする気だ？

***************************************/
    wait(ref_d0);
    ref_d2 = msgShow(msg_10);
/***************************************
[tab]や、やめろ…[delay(30)]恐ろしい事になるぞ！

***************************************/
    ref_d3 = cameraRotateTo(0, 1);
    wait(ref_d3);
    cameraMoveTo(700, 0, -300, 90);
    unitFace_2(maya, east);
    call(MAYA_IDO);
    unitMove(ginji, 580, -390, face_west, reverse);
    unitWait(ginji);
    unitAnimationPlay(ginji, animation_19, 1);
    wait(ref_d2);
    ref_dc = msgShow(msg_11);
/***************************************
[tab]やめろぉぉ！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(ginji, animation_1, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_2, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_1, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_3, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_4, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_3, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_1, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_2, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_1, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_3, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_4, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_3, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(ginji, animation_19, 1);
    sync();
    wait(ref_dc);
    dialogFree(ref_cf);
    ref_111 = bustupFade(ref_cd, rgb(0,0,0), 10);
    bustupWait(ref_111);
    bustupFree(ref_cd);
    ref_114 = efctDummy(effect_28);
    wait(ref_114);
    ref_116 = efctLoad(effect_28);
    wait(ref_116);
    sndMusicPlay(sound_31d6, 127);
    unitAnimationPlay(maya, animation_5, 1);
    delayClear();
    delayWait(30);
    unitAnimationHold(ginji, animation_1b, -1);
    wait(ref_29);
    ref_11e = todRun(tod_6, 0);
    delayClear();
    delayWait(60);
    unitAnimationStop(ginji);
    unitAnimationPlay(ginji, animation_a, 1);
    unitWait(ginji);
    unitFace_2(ginji, east);
    unitAnimationHold(ginji, animation_1b, 60);
    wait(ref_11e);
    ref_127 = todLoad(tod_16);
    wait(ref_127);
    unitFace_2(maya, south);
    sndMusicPlay(sound_31d7, 127);
    unitAnimationPlay(maya, animation_5, 1);
    wait(ref_127);
    ref_12d = todRun(tod_16, 0);
    delayClear();
    delayWait(90);
    unitAnimationPlay(ginji, animation_4, 1);
    delayClear();
    delayWait(30);
    unitFace_2(ginji, south);
    unitAnimationPlay(ginji, animation_0, 1);
    wait(ref_12d);
    delayClear();
    delayWait(60);
    ref_138 = spriteLoad(sprite_0);
    wait(ref_138);
    sndMusicPlay(sound_31d8, 127);
    objVisible(obj_20, false);
    efctPlay(effect_28, efct_0, 480, -150, -270, 480, -150, -270, false);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitFace_2(maya, east);
    unitAnimationPlay(ginji, animation_4, 1);
    unitAnimationHold(maya, animation_21, -1);
    unitAnimationHold(katsuya, animation_21, -1);
    unitAnimationHold(baofu, animation_21, -1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_31d9, 127);
    objVisible(obj_21, false);
    efctPlay(effect_28, efct_1, 920, -150, -270, 920, -150, -270, false);
    unitAnimationHold(ginji, animation_1b, -1);
    efctWait(efct_0);
    efctWait(efct_1);
    ref_14c = efctDummy(effect_25);
    wait(ref_14c);
    ref_14e = efctLoad(effect_25);
    wait(ref_14e);
    sndMusicPlay(sound_31da, 127);
    efctPlay(effect_25, efct_2, 580, -250, -390, 580, -250, -390, false);
    ref_152 = bustupLoad(bustup_58);
    bustupWait(ref_152);
    ref_154 = bustupAlloc(ref_152, right, rgb(0,0,0));
    bustupFade(ref_154, rgb(128,0,0), 30);
    ref_156 = dialogAlloc();
    ref_157 = msgShow(msg_12);
/***************************************
[color(yellow)]銀次[color(white)]
[tab]ぎゃあああ！
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitSpriteClear(ginji);
    unitSpriteSet(ginji, sprite_74);
    unitFace_2(ginji, west);
    efctWait(efct_2);
    unitAnimationPlay(ginji, animation_c, 1);
    unitWait(ginji);
    sync();
    wait(ref_157);
    dialogFree(ref_156);
    ref_163 = bustupFade(ref_154, rgb(0,0,0), 10);
    bustupWait(ref_163);
    bustupFree(ref_154);
    delayClear();
    delayWait(30);
    unitFace_2(ginji, west);
    unitFace_2(maya, south);
    unitAnimationPlay(maya, animation_a, 1);
    cameraSet(northwest, 520, 0, -480);
    call(URARA_IDO2);
    call(KATUYA_IDO2);
    call(PAOFU_IDO2);
    call(ERI_IDO2);
    waitFunc(URARA_IDO2);
    waitFunc(KATUYA_IDO2);
    waitFunc(PAOFU_IDO2);
    waitFunc(ERI_IDO2);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_1f, 1);
    bne(var_0, 0, label_185);
    ref_178 = bustupLoad(bustup_41);
    bustupWait(ref_178);
    ref_17a = bustupAlloc(ref_178, left, rgb(0,0,0));
    bustupFade(ref_17a, rgb(128,0,0), 30);
    ref_17c = dialogAlloc();
    ref_17d = msgShow(msg_13);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｗｈａｔ’ｓ！？
[tab]あれ…生きてるんですの！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_17d);
    dialogFree(ref_17c);
    ref_181 = bustupFade(ref_17a, rgb(0,0,0), 10);
    bustupWait(ref_181);
    bustupFree(ref_17a);
    b(label_193);
  label_185:
    bne(var_0, 1, label_193);
    ref_186 = bustupLoad(bustup_3a);
    bustupWait(ref_186);
    ref_188 = bustupAlloc(ref_186, left, rgb(0,0,0));
    bustupFade(ref_188, rgb(128,0,0), 30);
    ref_18a = dialogAlloc();
    ref_18b = msgShow(msg_14);
/***************************************
[color(yellow)]南条[color(white)]
[tab]馬鹿な…意志があるとでも言うのか！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_18b);
    dialogFree(ref_18a);
    ref_18f = bustupFade(ref_188, rgb(0,0,0), 10);
    bustupWait(ref_18f);
    bustupFree(ref_188);
    b(label_193);
  label_193:
    unitAnimationPlay(elly, animation_a, 1);
    unitAnimationPlay(ulala, animation_2c, 1);
    ref_195 = bustupLoad(bustup_1b);
    bustupWait(ref_195);
    ref_197 = bustupAlloc(ref_195, left, rgb(0,0,0));
    bustupFade(ref_197, rgb(128,0,0), 30);
    ref_199 = dialogAlloc();
    ref_19a = msgShow(msg_15);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]身体ん中…入っちゃった…
[tab]うぇぇぇっ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_19a);
    dialogFree(ref_199);
    ref_19e = bustupFade(ref_197, rgb(0,0,0), 10);
    bustupWait(ref_19e);
    bustupFree(ref_197);
    unitAnimationPlay(ulala, animation_0, 1);
    ref_1a2 = bustupLoad(bustup_23);
    bustupWait(ref_1a2);
    ref_1a4 = bustupAlloc(ref_1a2, left, rgb(0,0,0));
    bustupFade(ref_1a4, rgb(128,0,0), 30);
    ref_1a6 = dialogAlloc();
    ref_1a7 = msgShow(msg_16);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]おい、大丈夫か！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1a7);
    dialogFree(ref_1a6);
    ref_1ab = bustupFade(ref_1a4, rgb(0,0,0), 10);
    bustupWait(ref_1ab);
    bustupFree(ref_1a4);
    op_119();
    ref_1af = spriteLoad(sprite_8);
    wait(ref_1af);
    ref_1b1 = spriteLoad(sprite_f);
    wait(ref_1b1);
    ref_1b3 = spriteLoad(sprite_15);
    wait(ref_1b3);
    bne(var_0, 0, label_1b9);
    ref_1b6 = spriteLoad(sprite_25);
    wait(ref_1b6);
    b(label_1bd);
  label_1b9:
    bne(var_0, 1, label_1bd);
    ref_1ba = spriteLoad(sprite_21);
    wait(ref_1ba);
    b(label_1bd);
  label_1bd:
    ref_1bd = spriteLoad(sprite_3);
    wait(ref_1bd);
    sndMusicPlay(sound_31dc, 127);
    levelColorInvert();
    sndMusicPlay(sound_31db, 127);
    op_ab(1, 255);
    wait(ref_35);
    call(SOUND);
    unitAnimationPlay(ginji, animation_0, 1);
    delayClear();
    delayWait(60);
    levelColorInvert();
    screenColorAdjust(0.5, 0.5, 0.61328125);
    delayClear();
    delayWait(30);
    unitSpriteClear(maya);
    unitSpriteClear(ulala);
    unitSpriteClear(katsuya);
    unitSpriteClear(baofu);
    unitSpriteClear(elly);
    unitSpriteSet(maya, sprite_3);
    unitSpriteSet(ulala, sprite_8);
    unitSpriteSet(katsuya, sprite_f);
    unitSpriteSet(baofu, sprite_15);
    bne(var_0, 0, label_1d8);
    unitSpriteSet(elly, sprite_25);
    b(label_1db);
  label_1d8:
    bne(var_0, 1, label_1db);
    unitSpriteSet(elly, sprite_21);
    b(label_1db);
  label_1db:
    unitAnimationPlay(elly, animation_d, 1);
    delayClear();
    delayWait(60);
    unitFace_2(ginji, north);
    ref_1df = bustupLoad(bustup_59);
    bustupWait(ref_1df);
    ref_1e1 = bustupAlloc(ref_1df, right, rgb(0,0,0));
    bustupFade(ref_1e1, rgb(128,0,0), 30);
    ref_1e3 = dialogAlloc();
    ref_1e4 = msgShow(msg_17);
/***************************************
[color(yellow)]ＪＯＫＥＲ銀次[color(white)]
[tab]だから恐ろしい事になるって言っただろうが！
[tab]ヒャーハハハハハ！
[sync][wait][clear]
***************************************/
    ref_1e5 = sndVoicePlay(sound_64, 127);
    sndWaitStart();
    wait(ref_1e5);
    sync();
    wait(ref_1e4);
    dialogFree(ref_1e3);
    ref_1eb = bustupFade(ref_1e1, rgb(0,0,0), 10);
    bustupWait(ref_1eb);
    bustupFree(ref_1e1);
    ref_1ee = spriteLoad(sprite_74);
    wait(ref_1ee);
    ref_1f0 = spriteLoad(sprite_fa);
    wait(ref_1f0);
    unitSpriteClear(ginji);
    unitSpriteSet(ginji, sprite_74);
    unitAnimationHold(ginji, animation_6, -1);
    cameraMoveTo(330, 0, -250, 20);
    unitSpawn3d(unit_62, sprite_fa, 580, -70, -390, north, none);
    sndMusicPlay(sound_31dd, 127);
    unitAura(ginji, true);
    unitSummonEffect(unit_62, true);
    unitMove3d(unit_62, 580, var_7fffff56, var_7ffffe7a, 20, 0);
    unitWait(unit_62);
    unitAnimationPlay(maya, animation_d, 1);
    unitAnimationPlay(ulala, animation_d, 1);
    unitAnimationPlay(katsuya, animation_d, 1);
    delayClear();
    delayWait(60);
    bne(var_0, 0, label_213);
    ref_202 = bustupLoad(bustup_41);
    bustupWait(ref_202);
    ref_204 = bustupAlloc(ref_202, left, rgb(0,0,0));
    bustupFade(ref_204, rgb(128,0,0), 30);
    ref_206 = dialogAlloc();
    ref_207 = msgShow(msg_18);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｉ[tab]ｇｏｔ[tab]ｉｔ…わかりましたわ…
[tab]穢れとは、ＪＯＫＥＲそのものなんですのね…
[sync][wait][clear]
***************************************/
    ref_208 = sndVoicePlay(sound_5f, 127);
    sndWaitStart();
    unitAnimationPlay(elly, animation_d, 1);
    wait(ref_208);
    sync();
    wait(ref_207);
    dialogFree(ref_206);
    ref_20f = bustupFade(ref_204, rgb(0,0,0), 10);
    bustupWait(ref_20f);
    bustupFree(ref_204);
    b(label_225);
  label_213:
    bne(var_0, 1, label_225);
    ref_214 = bustupLoad(bustup_3a);
    bustupWait(ref_214);
    ref_216 = bustupAlloc(ref_214, left, rgb(0,0,0));
    bustupFade(ref_216, rgb(128,0,0), 30);
    ref_218 = dialogAlloc();
    ref_219 = msgShow(msg_19);
/***************************************
[color(yellow)]南条[color(white)]
[tab]なるほど…
[tab]人の罪を具象化させた穢れとは、
[tab]ＪＯＫＥＲそのものということか…
[sync][wait][clear]
***************************************/
    ref_21a = sndVoicePlay(sound_78, 127);
    sndWaitStart();
    unitAnimationPlay(elly, animation_d, 1);
    wait(ref_21a);
    sync();
    wait(ref_219);
    dialogFree(ref_218);
    ref_221 = bustupFade(ref_216, rgb(0,0,0), 10);
    bustupWait(ref_221);
    bustupFree(ref_216);
    b(label_225);
  label_225:
    unitAnimationHold(katsuya, animation_0, 1);
    ref_226 = bustupLoad(bustup_23);
    bustupWait(ref_226);
    ref_228 = bustupAlloc(ref_226, left, rgb(0,0,0));
    bustupFade(ref_228, rgb(128,0,0), 30);
    ref_22a = dialogAlloc();
    ref_22b = msgShow(msg_20);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]罪が形を成したるペルソナ…
[tab]どうりで力を増していくわけだ…
[sync][wait][clear]
***************************************/
    ref_22c = sndVoicePlay(sound_c3, 127);
    sndWaitStart();
    wait(ref_22c);
    sync();
    wait(ref_22b);
    dialogFree(ref_22a);
    ref_232 = bustupFade(ref_228, rgb(0,0,0), 10);
    bustupWait(ref_232);
    bustupFree(ref_228);
    sndLoad(sound_3162);
    ref_236 = bustupLoad(bustup_2e);
    bustupWait(ref_236);
    ref_238 = bustupAlloc(ref_236, left, rgb(0,0,0));
    bustupFade(ref_238, rgb(128,0,0), 30);
    ref_23a = dialogAlloc();
    ref_23b = msgShow(msg_21);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]今までとは桁違いってわけかい…くるぞ！
[sync][wait][clear]
***************************************/
    ref_23c = sndVoicePlay(sound_84, 127);
    sndWaitStart();
    delayClear();
    delayWait(150);
    unitAnimationHold(baofu, animation_4, -1);
    wait(ref_23c);
    sync();
    wait(ref_23b);
    dialogFree(ref_23a);
    ref_245 = bustupFade(ref_238, rgb(0,0,0), 10);
    bustupWait(ref_245);
    bustupFree(ref_238);
    op_ac();
    sndStop(sound_31db);
    sndMusicPlay(sound_3162, 127);
    encounterLoad(encounter_d);
}

function MAYA_TOJO()
{
    unitSpawn(maya, sprite_0, 700, 0, -2180, south, none);
    unitMove(maya, 700, -1100, face_south, fast);
    unitWait(maya);
    unitAnimationPlay(maya, animation_a, 1);
}

function URARA_TOJO()
{
    unitSpawn(ulala, sprite_6, 700, 0, -2180, south, none);
    unitMove(ulala, 750, -1240, face_south, fast);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
}

function ERI_TOJO()
{
    unitSpawn(elly, sprite_23, 700, 0, -2180, south, none);
    unitMove(elly, 620, -1180, face_south, fast);
    unitWait(elly);
    unitAnimationPlay(elly, animation_a, 1);
}

function NANJO_TOJO()
{
    unitSpawn(elly, sprite_1f, 700, 0, -2180, south, none);
    unitMove(elly, 620, -1180, face_south, fast);
    unitWait(elly);
    unitAnimationPlay(elly, animation_a, 1);
}

function URARA_IDO()
{
    unitMove(ulala, 770, -1100, face_south, medium);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
}

function KATUYA_IDO()
{
    unitAnimationPlay(katsuya, animation_4, 1);
    delayClear();
    delayWait(30);
    unitMove(katsuya, 960, -940, face_east, medium);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_d, 1);
}

function PAOFU_IDO()
{
    unitAnimationPlay(baofu, animation_12, 1);
    unitWait(baofu);
    unitMove(baofu, 400, -840, face_south, medium);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
}

function ERI_IDO()
{
    unitMove(elly, 630, -1120, face_south, medium);
    unitWait(elly);
    unitAnimationPlay(elly, animation_a, 1);
}

function MAYA_IDO()
{
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitAnimationPlay(maya, animation_7, 1);
    unitMove3d(maya, 700, 0, var_7ffffd76, 40, 0);
    unitWait(maya);
    unitAnimationPlay(maya, animation_0, 1);
    sndMusicPlay(sound_31d5, 127);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
}

function URARA_IDO2()
{
    unitMove(ulala, 730, -770, face_south, medium);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_a, 1);
}

function KATUYA_IDO2()
{
    unitMove(katsuya, 800, -420, face_east, medium);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_31, 1);
}

function PAOFU_IDO2()
{
    unitMove(baofu, 520, -840, face_south, medium);
    unitWait(baofu);
    unitMove(baofu, 520, -630, face_south, medium);
    unitWait(baofu);
    unitAnimationHold(baofu, animation_11, -1);
}

function ERI_IDO2()
{
    unitMove(elly, 620, -810, face_south, fast);
    unitWait(elly);
    unitAnimationPlay(elly, animation_a, 1);
}

function SOUND()
{
    sndVolumeFadeOff(sound_3025, 120);
    delayClear();
    delayWait(90);
    sndMusicPlay(sound_301d, 127);
}
