function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    sndMusicPlay(sound_3025, 127);
    cameraSet(southwest, 2400, 0, -2200);
    levelFootstepSet(sfx_19);
    cameraZoom(-1500, 1);
    ref_b = spriteLoad(sprite_0);
    wait(ref_b);
    ref_d = spriteLoad(sprite_6);
    wait(ref_d);
    ref_f = spriteLoad(sprite_d);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_13);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_48);
    wait(ref_13);
    ref_15 = spriteLoad(sprite_da);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_86);
    wait(ref_17);
    ref_19 = spriteLoad(sprite_e2);
    wait(ref_19);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_21);
    ref_1d = spriteLoad(sprite_23);
    wait(ref_1d);
    unitSpawn(elly, sprite_23, 3400, -600, -1000, north, none);
    b(label_26);
  label_21:
    bne(var_0, 1, label_26);
    ref_22 = spriteLoad(sprite_1f);
    wait(ref_22);
    unitSpawn(elly, sprite_1f, 3400, -600, -1000, north, none);
    b(label_26);
  label_26:
    unitSpawn(maya, sprite_0, 3360, -600, -1100, north, none);
    unitSpawn(ulala, sprite_6, 3220, -600, -1020, north, none);
    unitSpawn(katsuya, sprite_d, 3310, -600, -1080, north, none);
    unitSpawn(baofu, sprite_13, 3150, -600, -1050, north, none);
    unitAnimationPlay(maya, animation_31, 1);
    unitAnimationPlay(ulala, animation_34, 1);
    unitAnimationPlay(katsuya, animation_31, 1);
    unitAnimationPlay(baofu, animation_34, 1);
    unitAnimationPlay(elly, animation_31, 1);
    unitSpawn(unit_17, sprite_48, 2200, 0, -2050, west, none);
    unitSpawn(npc1, sprite_da, 2300, 0, -2120, west, none);
    unitSpawn(npc2, sprite_da, 2550, 0, -1850, west, none);
    unitSpawn(npc3, sprite_da, 2480, 0, -2300, north, none);
    unitSpawn(npc4, sprite_da, 2600, 0, -2450, west, none);
    unitSpawn(npc5, sprite_da, 3500, 0, -2000, east, none);
    unitAnimationPlay(unit_17, animation_a, 1);
    li(var_1, 0);
    bitSet(EBIT_E007D);
    bitSet(EBIT_KOJO_KYOMEI);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndLoad(sound_301b);
    call(MAFIA2_TAIKI);
    call(MAFIA5_TAIKI);
    delayClear();
    delayWait(30);
    call(MAFIA4_TAIKI);
    delayClear();
    delayWait(30);
    call(MAFIA3_TAIKI);
    ref_47 = cameraZoom(0, 120);
    wait(ref_47);
    call(MAFIA_TALK);
    delayClear();
    delayWait(90);
    ref_4c = cameraMoveTo(2500, 0, -1890, 60);
    wait(ref_4c);
    delayClear();
    delayWait(60);
    ref_50 = bustupLoad(bustup_2e);
    bustupWait(ref_50);
    ref_52 = bustupAlloc(ref_50, left, rgb(0,0,0));
    bustupFade(ref_52, rgb(128,0,0), 30);
    ref_54 = dialogAlloc();
    ref_55 = msgShow(msg_0);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_55);
    dialogFree(ref_54);
    ref_59 = bustupFade(ref_52, rgb(0,0,0), 10);
    bustupWait(ref_59);
    bustupFree(ref_52);
    delayClear();
    delayWait(30);
    ref_5e = bustupLoad(bustup_1e);
    bustupWait(ref_5e);
    ref_60 = bustupAlloc(ref_5e, left, rgb(0,0,0));
    bustupFade(ref_60, rgb(128,0,0), 30);
    ref_62 = dialogAlloc();
    ref_63 = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ねぇ…[delay(30)]

***************************************/
    wait(ref_63);
    unitAnimationPlay(katsuya, animation_35, 1);
    unitAnimationPlay(ulala, animation_37, 1);
    ref_67 = msgShow(msg_2);
/***************************************
[tab]どうしてそんなに憎むの…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_67);
    dialogFree(ref_62);
    ref_6b = bustupFade(ref_60, rgb(0,0,0), 10);
    bustupWait(ref_6b);
    bustupFree(ref_60);
    unitAnimationPlay(ulala, animation_34, 1);
    delayClear();
    delayWait(60);
    ref_71 = bustupLoad(bustup_21);
    bustupWait(ref_71);
    ref_73 = bustupAlloc(ref_71, left, rgb(0,0,0));
    bustupFade(ref_73, rgb(128,0,0), 30);
    ref_75 = dialogAlloc();
    ref_76 = msgShow(msg_3);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_76);
    dialogFree(ref_75);
    ref_7a = bustupFade(ref_73, rgb(0,0,0), 10);
    bustupWait(ref_7a);
    bustupFree(ref_73);
    delayClear();
    delayWait(60);
    li(var_1, 1);
    ref_80 = spriteLoad(sprite_db);
    wait(ref_80);
    call(SOUND);
    call(JIEITAIKI_TOJO);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_33, 1);
    unitAnimationPlay(ulala, animation_33, 1);
    unitAnimationPlay(katsuya, animation_33, 1);
    unitAnimationPlay(baofu, animation_33, 1);
    unitAnimationPlay(elly, animation_33, 1);
    delayClear();
    delayWait(30);
    cameraMoveTo(2650, 0, -2150, 60);
    unitSpriteClear(npc1);
    unitSpriteSet(npc1, sprite_db);
    call(MAFIA2_ODOROKI);
    call(MAFIA3_ODOROKI);
    call(MAFIA4_ODOROKI);
    call(MAFIA5_ODOROKI);
    sndMusicPlay(sound_3202, 127);
    unitAnimationPlay(npc1, animation_6, 5);
    waitFunc(JIEITAIKI_TOJO);
    call(MAFIA1_DIE);
    sndMusicPlay(sound_31fc, 127);
    unitAnimationPlay(unit_58, animation_5, 1);
    unitWait(unit_58);
    unitAnimationHold(unit_17, animation_21, -1);
    call(JIEI1_TOJO);
    call(JIEI3_TOJO);
    sndMusicPlay(sound_31fc, 127);
    unitAnimationPlay(unit_58, animation_5, 1);
    unitWait(unit_58);
    call(JIEI2_TOJO);
    delayClear();
    delayWait(30);
    waitFunc(JIEI1_TOJO);
    waitFunc(JIEI3_TOJO);
    call(MAFIA2_DIE);
    delayClear();
    delayWait(30);
    call(MAFIA3_DIE);
    delayClear();
    delayWait(30);
    call(MAFIA5_DIE);
    call(JIEITAIKI_OU);
    delayClear();
    delayWait(30);
    sndStop(sound_3202);
    call(MAFIA4_DIE);
    delayClear();
    delayWait(120);
    cameraFollow(unit_17);
    call(KOROSI_TAIJO);
    delayClear();
    delayWait(60);
    ref_b8 = spriteLoad(sprite_3);
    wait(ref_b8);
    ref_ba = spriteLoad(sprite_8);
    wait(ref_ba);
    ref_bc = spriteLoad(sprite_f);
    wait(ref_bc);
    sndStop(sound_3203);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(enemy2, animation_0, 1);
    unitAnimationPlay(enemy3, animation_0, 1);
    waitFunc(KOROSI_TAIJO);
    ref_c3 = spriteLoad(sprite_15);
    wait(ref_c3);
    bne(var_0, 0, label_c9);
    ref_c6 = spriteLoad(sprite_25);
    wait(ref_c6);
    b(label_cd);
  label_c9:
    bne(var_0, 1, label_cd);
    ref_ca = spriteLoad(sprite_21);
    wait(ref_ca);
    b(label_cd);
  label_cd:
    delayClear();
    delayWait(30);
    ref_cf = cameraMoveTo(2500, 0, -1890, 60);
    wait(ref_cf);
    call(JIEI1_IDO);
    call(JIEI2_IDO);
    call(JIEI3_IDO);
    unitFace_2(unit_58, south);
    unitAnimationPlay(baofu, animation_3, 1);
    unitAnimationPlay(maya, animation_35, 1);
    unitAnimationPlay(ulala, animation_35, 1);
    unitAnimationPlay(katsuya, animation_35, 1);
    unitAnimationPlay(elly, animation_35, 1);
    unitAnimationPlay(baofu, animation_12, 1);
    unitWait(baofu);
    unitFace_2(baofu, south);
    unitAnimationPlay(baofu, animation_1b, 1);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitAnimationPlay(baofu, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(baofu, 3150, -300, -750, 20, 1);
    ref_e3 = bustupLoad(bustup_1b);
    bustupWait(ref_e3);
    ref_e5 = bustupAlloc(ref_e3, left, rgb(0,0,0));
    bustupFade(ref_e5, rgb(128,0,0), 30);
    ref_e7 = dialogAlloc();
    ref_e8 = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あっ…！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_e8);
    dialogFree(ref_e7);
    ref_ec = bustupFade(ref_e5, rgb(0,0,0), 10);
    bustupWait(ref_ec);
    bustupFree(ref_e5);
    bne(var_0, 0, label_f2);
    call(ERI_NIGE1);
    b(label_f5);
  label_f2:
    bne(var_0, 1, label_f5);
    call(NANJO_NIGE1);
    b(label_f5);
  label_f5:
    ref_f5 = efctDummy(effect_8);
    wait(ref_f5);
    call(MAYA_NIGE1);
    ref_f8 = efctLoad(effect_8);
    wait(ref_f8);
    call(KATUYA_NIGE1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_4, 1);
    sndMusicPlay(sound_31fd, 127);
    unitAnimationPlay(unit_58, animation_6, 1);
    unitWait(unit_58);
    sndMusicPlay(sound_31fe, 127);
    efctPlay(effect_8, efct_a, 3200, -600, -1100, 3200, -600, -1100, false);
    unitAnimationHold(ulala, animation_21, -1);
    ref_104 = bustupLoad(bustup_1b);
    bustupWait(ref_104);
    ref_106 = bustupAlloc(ref_104, left, rgb(0,0,0));
    bustupFade(ref_106, rgb(128,0,0), 30);
    ref_108 = dialogAlloc();
    ref_109 = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]わわっ…！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_109);
    dialogFree(ref_108);
    ref_10d = bustupFade(ref_106, rgb(0,0,0), 10);
    bustupWait(ref_10d);
    bustupFree(ref_106);
    call(KOKA);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_12, 1);
    unitWait(ulala);
    unitFace_2(ulala, south);
    unitAnimationPlay(ulala, animation_1b, 1);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_8);
    unitAnimationPlay(ulala, animation_1, 1);
    cameraMoveTo(2880, 0, -1230, 20);
    unitJumpTo(ulala, 3220, -300, -850, 20, 0);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_10, 1);
    bne(var_0, 0, label_121);
    waitFunc(ERI_NIGE2);
    call(ERI_NIGE2);
    b(label_125);
  label_121:
    bne(var_0, 1, label_125);
    waitFunc(NANJO_NIGE2);
    call(NANJO_NIGE2);
    b(label_125);
  label_125:
    delayClear();
    delayWait(30);
    waitFunc(MAYA_NIGE2);
    call(MAYA_NIGE2);
    ref_129 = spriteLoad(sprite_d);
    wait(ref_129);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_2, 1);
    sndVolumeFadeOff(sound_3203, 150);
    ref_132 = bustupLoad(bustup_21);
    bustupWait(ref_132);
    ref_134 = bustupAlloc(ref_132, left, rgb(0,0,0));
    bustupFade(ref_134, rgb(128,0,0), 30);
    ref_136 = dialogAlloc();
    ref_137 = msgShow(msg_6);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]奴を追うぞ。
[sync][wait][clear]
***************************************/
    unitMove(katsuya, 3350, -750, face_east, fast);
    unitWait(katsuya);
    unitMove(katsuya, 3100, -750, face_east, fast);
    sync();
    wait(ref_137);
    dialogFree(ref_136);
    ref_13e = bustupFade(ref_134, rgb(0,0,0), 10);
    bustupWait(ref_13e);
    bustupFree(ref_134);
    call(KATUYA_NIGE2);
    cameraFollow(ulala);
    ref_143 = spriteLoad(sprite_6);
    wait(ref_143);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitAnimationPlay(ulala, animation_1, 1);
    delayClear();
    delayWait(30);
    ref_14a = bustupLoad(bustup_1b);
    bustupWait(ref_14a);
    ref_14c = bustupAlloc(ref_14a, left, rgb(0,0,0));
    bustupFade(ref_14c, rgb(128,0,0), 30);
    ref_14e = dialogAlloc();
    ref_14f = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なんなのよぅ！？

***************************************/
    unitMove(ulala, 3220, -750, face_east, fast);
    unitWait(ulala);
    unitMove(ulala, 3100, -750, face_east, fast);
    unitWait(ulala);
    wait(ref_14f);
    ref_155 = msgShow(msg_8);
/***************************************
[tab]なにがどうなってんの！？
[sync][wait][clear]
***************************************/
    ref_156 = spriteLoad(sprite_8);
    wait(ref_156);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_8);
    unitAnimationPlay(ulala, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(ulala, 2820, 0, -750, 20, 0);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_10, 1);
    sync();
    wait(ref_155);
    dialogFree(ref_14e);
    ref_162 = bustupFade(ref_14c, rgb(0,0,0), 10);
    bustupWait(ref_162);
    bustupFree(ref_14c);
    delayClear();
    delayWait(30);
    ref_167 = spriteLoad(sprite_6);
    wait(ref_167);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    unitFace_2(katsuya, west);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_170 = bustupLoad(bustup_21);
    bustupWait(ref_170);
    ref_172 = bustupAlloc(ref_170, left, rgb(0,0,0));
    bustupFade(ref_172, rgb(128,0,0), 30);
    ref_174 = dialogAlloc();
    ref_175 = msgShow(msg_9);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]盗聴がバレていたんだ。

***************************************/
    wait(ref_175);
    unitAnimationHold(katsuya, animation_11, -1);
    ref_178 = msgShow(msg_10);
/***************************************
[tab]あの電話は、マフィア共々僕らを抹殺する
[tab]ための罠だったんだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_178);
    dialogFree(ref_174);
    ref_17c = bustupFade(ref_172, rgb(0,0,0), 10);
    bustupWait(ref_17c);
    bustupFree(ref_172);
    unitAnimationStop(katsuya);
    unitAnimationHold(ulala, animation_21, -1);
    ref_181 = bustupLoad(bustup_1b);
    bustupWait(ref_181);
    ref_183 = bustupAlloc(ref_181, left, rgb(0,0,0));
    bustupFade(ref_183, rgb(128,0,0), 30);
    ref_185 = dialogAlloc();
    ref_186 = msgShow(msg_11);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]えぇ！？
[tab]じゃあ、パオの奴が…

***************************************/
    wait(ref_186);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_2c, 1);
    ref_18a = msgShow(msg_12);
/***************************************
[tab]ヤバイよ、教えてやんなきゃ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_18a);
    dialogFree(ref_185);
    ref_18e = bustupFade(ref_183, rgb(0,0,0), 10);
    bustupWait(ref_18e);
    bustupFree(ref_183);
    delayClear();
    delayWait(30);
    ref_193 = bustupLoad(bustup_21);
    bustupWait(ref_193);
    ref_195 = bustupAlloc(ref_193, left, rgb(0,0,0));
    bustupFade(ref_195, rgb(128,0,0), 30);
    ref_197 = dialogAlloc();
    ref_198 = msgShow(msg_13);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]自分の身を心配しろ。

***************************************/
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    wait(ref_198);
    unitFace_2(katsuya, west);
    unitMove(katsuya, 1600, -400, despawn, fastest);
    ref_19e = msgShow(msg_14);
/***************************************
[tab]奴も、知っていることだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_19e);
    dialogFree(ref_197);
    ref_1a2 = bustupFade(ref_195, rgb(0,0,0), 10);
    bustupWait(ref_1a2);
    bustupFree(ref_195);
    unitAnimationPlay(ulala, animation_0, 1);
    ref_1a6 = bustupLoad(bustup_1b);
    bustupWait(ref_1a6);
    ref_1a8 = bustupAlloc(ref_1a6, left, rgb(0,0,0));
    bustupFade(ref_1a8, rgb(128,0,0), 30);
    ref_1aa = dialogAlloc();
    ref_1ab = msgShow(msg_15);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]え…？

***************************************/
    wait(ref_1ab);
    unitAnimationPlay(ulala, animation_1f, 1);
    ref_1ae = msgShow(msg_16);
/***************************************
[tab]なんて言ったの？[tab]ねぇ！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1ae);
    dialogFree(ref_1aa);
    ref_1b2 = bustupFade(ref_1a8, rgb(0,0,0), 10);
    bustupWait(ref_1b2);
    bustupFree(ref_1a8);
    unitMove(ulala, 500, -300, despawn, fastest);
    delayClear();
    delayWait(60);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    dngLoad2(abandoned_factory-4);
}

function MAFIA_TALK()
{
    unitAnimationPlay(npc1, animation_4, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_17, animation_27, 1);
    unitWait(unit_17);
    delayClear();
    delayWait(30);
    unitAnimationPlay(unit_17, animation_2d, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(unit_17, animation_a, 1);
    unitAnimationPlay(npc1, animation_6, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_0, 1);
}

function MAFIA2_TAIKI()
{
  label_1d0:
    bnz(var_1, label_1df);
    unitAnimationPlay(npc2, animation_1f, 1);
    unitWait(npc2);
    bnz(var_1, label_1df);
    delayClear();
    delayWait(30);
    bnz(var_1, label_1df);
    delayClear();
    delayWait(30);
    bnz(var_1, label_1df);
    unitAnimationPlay(npc2, animation_0, 1);
    bnz(var_1, label_1df);
    delayClear();
    delayWait(30);
    bez(var_1, label_1d0);
  label_1df:
}

function MAFIA3_TAIKI()
{
  label_1e0:
    bnz(var_1, label_1ef);
    unitAnimationPlay(npc3, animation_1f, 1);
    unitWait(npc3);
    bnz(var_1, label_1ef);
    delayClear();
    delayWait(30);
    bnz(var_1, label_1ef);
    delayClear();
    delayWait(30);
    bnz(var_1, label_1ef);
    unitAnimationPlay(npc3, animation_0, 1);
    bnz(var_1, label_1ef);
    delayClear();
    delayWait(30);
    bez(var_1, label_1e0);
  label_1ef:
}

function MAFIA4_TAIKI()
{
  label_1f0:
    bnz(var_1, label_1ff);
    unitAnimationPlay(npc4, animation_1f, 1);
    unitWait(npc4);
    bnz(var_1, label_1ff);
    delayClear();
    delayWait(30);
    bnz(var_1, label_1ff);
    delayClear();
    delayWait(30);
    bnz(var_1, label_1ff);
    unitAnimationPlay(npc4, animation_0, 1);
    bnz(var_1, label_1ff);
    delayClear();
    delayWait(30);
    bez(var_1, label_1f0);
  label_1ff:
}

function MAFIA5_TAIKI()
{
    unitMove(npc5, 2670, -2000, face_east, slow);
    unitWait(npc5);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc5, animation_2, 1);
    delayClear();
    delayWait(30);
    unitFace_2(npc5, south);
    unitAnimationPlay(npc5, animation_0, 1);
    delayClear();
    delayWait(30);
  label_20b:
    bnz(var_1, label_21a);
    unitAnimationPlay(npc5, animation_1f, 1);
    unitWait(npc5);
    bnz(var_1, label_21a);
    delayClear();
    delayWait(30);
    bnz(var_1, label_21a);
    delayClear();
    delayWait(30);
    bnz(var_1, label_21a);
    unitAnimationPlay(npc5, animation_0, 1);
    bnz(var_1, label_21a);
    delayClear();
    delayWait(30);
    bez(var_1, label_20b);
  label_21a:
}

function JIEITAIKI_TOJO()
{
    unitSpawn(unit_58, sprite_86, 3500, 0, -2150, north, none);
    unitAnimationPlay(unit_58, animation_1, 1);
    sndMusicPlay(sound_31fa, 127);
    unitMove3d(unit_58, 3000, 0, var_7ffff79a, 70, 0);
    unitWait(unit_58);
    sndStop(sound_31fa);
    unitAnimationPlay(unit_58, animation_0, 1);
    unitAnimationPlay(maya, animation_31, 1);
    unitAnimationPlay(ulala, animation_31, 1);
    unitAnimationPlay(katsuya, animation_31, 1);
    unitAnimationPlay(baofu, animation_34, 1);
    unitAnimationPlay(elly, animation_31, 1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_31fc, 127);
    unitAnimationPlay(unit_58, animation_5, 1);
    unitWait(unit_58);
}

function MAFIA2_ODOROKI()
{
    unitAnimationHold(npc2, animation_1b, 60);
    unitWait(npc2);
    unitSpriteClear(npc2);
    unitSpriteSet(npc2, sprite_db);
    unitAnimationPlay(npc2, animation_6, 5);
}

function MAFIA3_ODOROKI()
{
    unitAnimationPlay(npc3, animation_4, 1);
    delayClear();
    delayWait(30);
    unitFace_2(npc3, west);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc3, animation_19, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_19, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_19, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_19, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(npc3, animation_19, 1);
    delayClear();
    delayWait(30);
    unitSpriteClear(npc3);
    unitSpriteSet(npc3, sprite_db);
    unitAnimationPlay(npc3, animation_6, 5);
}

function MAFIA4_ODOROKI()
{
    unitAnimationPlay(npc4, animation_3, 1);
    delayClear();
    delayWait(30);
    unitSpriteClear(npc4);
    unitSpriteSet(npc4, sprite_db);
    unitAnimationPlay(npc4, animation_6, 5);
}

function MAFIA5_ODOROKI()
{
    unitAnimationPlay(npc5, animation_4, 1);
    delayClear();
    delayWait(30);
    unitFace_2(npc5, west);
    unitAnimationPlay(npc5, animation_0, 1);
    delayClear();
    delayWait(30);
    unitMove(npc5, 2530, -2000, face_west, reverse);
    unitWait(npc5);
    unitAnimationHold(npc5, animation_1b, -1);
}

function JIEI1_TOJO()
{
    unitSpawn(enemy1, sprite_e2, 3350, 0, -1950, north, none);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitMove3d(enemy1, 3050, 0, var_7ffff862, 30, 0);
    unitWait(enemy1);
    unitAnimationPlay(enemy1, animation_6, 7);
}

function JIEI2_TOJO()
{
    unitSpawn(enemy2, sprite_e2, 3250, 0, -1850, north, none);
    unitAnimationPlay(enemy2, animation_1, 1);
    unitMove3d(enemy2, 2950, 0, var_7ffff8c6, 30, 0);
    unitWait(enemy2);
    unitAnimationPlay(enemy2, animation_6, 7);
}

function JIEI3_TOJO()
{
    unitSpawn(enemy3, sprite_e2, 3350, 0, -2280, north, none);
    unitAnimationPlay(enemy3, animation_1, 1);
    unitMove3d(enemy3, 3050, 0, var_7ffff718, 30, 0);
    unitWait(enemy3);
    sndMusicPlay(sound_3203, 127);
    unitAnimationPlay(enemy3, animation_6, 7);
}

function MAFIA1_DIE()
{
    unitSpriteClear(npc1);
    unitSpriteSet(npc1, sprite_db);
    unitAnimationHold(npc1, animation_a, 60);
    unitWait(npc1);
    unitSpriteClear(npc1);
    unitSpriteSet(npc1, sprite_da);
    unitFace_2(npc1, east);
    sndMusicPlay(sound_31f9, 127);
    unitAnimationPlay(npc1, animation_16, 1);
    delayClear();
    delayWait(30);
    ref_289 = unitColor(npc1, rgb(0,0,0), 5);
    wait(ref_289);
    ref_28b = unitColor(npc1, rgb(112,112,112), 5);
    wait(ref_28b);
    ref_28d = unitColor(npc1, rgb(0,0,0), 5);
    wait(ref_28d);
    ref_28f = unitColor(npc1, rgb(112,112,112), 5);
    wait(ref_28f);
    ref_291 = unitColor(npc1, rgb(0,0,0), 5);
    wait(ref_291);
    ref_293 = unitColor(npc1, rgb(112,112,112), 5);
    wait(ref_293);
    ref_295 = unitColor(npc1, rgb(0,0,0), 5);
    wait(ref_295);
    ref_297 = unitColor(npc1, rgb(112,112,112), 5);
    wait(ref_297);
    ref_299 = unitColor(npc1, rgb(0,0,0), 5);
    wait(ref_299);
    ref_29b = unitColor(npc1, rgb(112,112,112), 5);
    wait(ref_29b);
    ref_29d = unitColor(npc1, rgb(0,0,0), 5);
    wait(ref_29d);
    ref_29f = unitColor(npc1, rgb(112,112,112), 5);
    wait(ref_29f);
    unitDespawn(npc1, ghost);
}

function MAFIA2_DIE()
{
    unitAnimationPlay(npc2, animation_1, 1);
    unitMove3d(npc2, 2750, 0, var_7ffff8c6, 15, 0);
    unitWait(npc2);
    unitAnimationHold(npc2, animation_a, 60);
    unitWait(npc2);
    unitSpriteClear(npc2);
    unitSpriteSet(npc2, sprite_da);
    unitFace_2(npc2, east);
    sndMusicPlay(sound_31f9, 127);
    unitAnimationPlay(npc2, animation_16, 1);
    delayClear();
    delayWait(30);
    ref_2af = unitColor(npc2, rgb(0,0,0), 5);
    wait(ref_2af);
    ref_2b1 = unitColor(npc2, rgb(112,112,112), 5);
    wait(ref_2b1);
    ref_2b3 = unitColor(npc2, rgb(0,0,0), 5);
    wait(ref_2b3);
    ref_2b5 = unitColor(npc2, rgb(112,112,112), 5);
    wait(ref_2b5);
    ref_2b7 = unitColor(npc2, rgb(0,0,0), 5);
    wait(ref_2b7);
    ref_2b9 = unitColor(npc2, rgb(112,112,112), 5);
    wait(ref_2b9);
    ref_2bb = unitColor(npc2, rgb(0,0,0), 5);
    wait(ref_2bb);
    ref_2bd = unitColor(npc2, rgb(112,112,112), 5);
    wait(ref_2bd);
    ref_2bf = unitColor(npc2, rgb(0,0,0), 5);
    wait(ref_2bf);
    ref_2c1 = unitColor(npc2, rgb(112,112,112), 5);
    wait(ref_2c1);
    ref_2c3 = unitColor(npc2, rgb(0,0,0), 5);
    wait(ref_2c3);
    ref_2c5 = unitColor(npc2, rgb(112,112,112), 5);
    wait(ref_2c5);
    unitDespawn(npc2, ghost);
}

function MAFIA3_DIE()
{
    unitAnimationHold(npc3, animation_a, 60);
    unitWait(npc3);
    unitSpriteClear(npc3);
    unitSpriteSet(npc3, sprite_da);
    unitFace_2(npc3, east);
    sndMusicPlay(sound_31f9, 127);
    unitAnimationPlay(npc3, animation_16, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(unit_58, animation_0, 1);
    ref_2d3 = unitColor(npc3, rgb(0,0,0), 5);
    wait(ref_2d3);
    ref_2d5 = unitColor(npc3, rgb(112,112,112), 5);
    wait(ref_2d5);
    ref_2d7 = unitColor(npc3, rgb(0,0,0), 5);
    wait(ref_2d7);
    ref_2d9 = unitColor(npc3, rgb(112,112,112), 5);
    wait(ref_2d9);
    ref_2db = unitColor(npc3, rgb(0,0,0), 5);
    wait(ref_2db);
    ref_2dd = unitColor(npc3, rgb(112,112,112), 5);
    wait(ref_2dd);
    ref_2df = unitColor(npc3, rgb(0,0,0), 5);
    wait(ref_2df);
    ref_2e1 = unitColor(npc3, rgb(112,112,112), 5);
    wait(ref_2e1);
    ref_2e3 = unitColor(npc3, rgb(0,0,0), 5);
    wait(ref_2e3);
    ref_2e5 = unitColor(npc3, rgb(112,112,112), 5);
    wait(ref_2e5);
    ref_2e7 = unitColor(npc3, rgb(0,0,0), 5);
    wait(ref_2e7);
    ref_2e9 = unitColor(npc3, rgb(112,112,112), 5);
    wait(ref_2e9);
    unitDespawn(npc3, ghost);
}

function MAFIA4_DIE()
{
    unitFace_2(npc4, south);
    unitSpriteClear(npc4);
    unitSpriteSet(npc4, sprite_da);
    unitAnimationHold(npc4, animation_1b, 60);
    unitWait(npc4);
    unitAnimationPlay(npc4, animation_a, 1);
    unitWait(npc4);
    unitMove(npc4, 2600, -2630, face_north, medium);
    waitFunc(JIEITAIKI_OU);
    delayClear();
    delayWait(30);
    unitWait(npc4);
    unitFace_2(npc4, south);
    sndMusicPlay(sound_31f9, 127);
    unitAnimationPlay(npc4, animation_16, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(unit_58, animation_0, 1);
    ref_2ff = unitColor(npc4, rgb(0,0,0), 5);
    wait(ref_2ff);
    ref_301 = unitColor(npc4, rgb(112,112,112), 5);
    wait(ref_301);
    ref_303 = unitColor(npc4, rgb(0,0,0), 5);
    wait(ref_303);
    ref_305 = unitColor(npc4, rgb(112,112,112), 5);
    wait(ref_305);
    ref_307 = unitColor(npc4, rgb(0,0,0), 5);
    wait(ref_307);
    ref_309 = unitColor(npc4, rgb(112,112,112), 5);
    wait(ref_309);
    ref_30b = unitColor(npc4, rgb(0,0,0), 5);
    wait(ref_30b);
    ref_30d = unitColor(npc4, rgb(112,112,112), 5);
    wait(ref_30d);
    ref_30f = unitColor(npc4, rgb(0,0,0), 5);
    wait(ref_30f);
    ref_311 = unitColor(npc4, rgb(112,112,112), 5);
    wait(ref_311);
    ref_313 = unitColor(npc4, rgb(0,0,0), 5);
    wait(ref_313);
    ref_315 = unitColor(npc4, rgb(112,112,112), 5);
    wait(ref_315);
    unitDespawn(npc4, ghost);
}

function MAFIA5_DIE()
{
    unitAnimationStop(npc5);
    unitAnimationPlay(npc5, animation_a, 1);
    unitWait(npc5);
    unitMove(npc5, 2400, -2000, face_east, fast);
    unitWait(npc5);
    unitFace_2(npc5, west);
    sndMusicPlay(sound_31f9, 127);
    unitAnimationPlay(npc5, animation_16, 1);
    delayClear();
    delayWait(30);
    ref_323 = unitColor(npc5, rgb(0,0,0), 5);
    wait(ref_323);
    ref_325 = unitColor(npc5, rgb(112,112,112), 5);
    wait(ref_325);
    ref_327 = unitColor(npc5, rgb(0,0,0), 5);
    wait(ref_327);
    ref_329 = unitColor(npc5, rgb(112,112,112), 5);
    wait(ref_329);
    ref_32b = unitColor(npc5, rgb(0,0,0), 5);
    wait(ref_32b);
    ref_32d = unitColor(npc5, rgb(112,112,112), 5);
    wait(ref_32d);
    ref_32f = unitColor(npc5, rgb(0,0,0), 5);
    wait(ref_32f);
    ref_331 = unitColor(npc5, rgb(112,112,112), 5);
    wait(ref_331);
    ref_333 = unitColor(npc5, rgb(0,0,0), 5);
    wait(ref_333);
    ref_335 = unitColor(npc5, rgb(112,112,112), 5);
    wait(ref_335);
    ref_337 = unitColor(npc5, rgb(0,0,0), 5);
    wait(ref_337);
    ref_339 = unitColor(npc5, rgb(112,112,112), 5);
    wait(ref_339);
    unitDespawn(npc5, ghost);
}

function JIEITAIKI_OU()
{
    unitAnimationPlay(unit_58, animation_1, 1);
    sndMusicPlay(sound_31fa, 127);
    unitMove3d(unit_58, 2600, 0, var_7ffff79a, 60, 0);
    unitWait(unit_58);
    sndStop(sound_31fa);
    unitAnimationPlay(unit_58, animation_0, 1);
    unitFace_2(unit_58, east);
    ref_344 = sndMusicPlay(sound_31fb, 127);
    wait(ref_344);
    sndMusicPlay(sound_31fc, 127);
    unitAnimationPlay(unit_58, animation_5, 1);
}

function KOROSI_TAIJO()
{
    unitAnimationStop(unit_17);
    unitMove(unit_17, 2000, -2050, face_west, reverse);
    unitWait(unit_17);
    unitAnimationPlay(unit_17, animation_12, 1);
    unitWait(unit_17);
    unitMove(unit_17, 1780, -2050, face_south, fastest);
    unitWait(unit_17);
    unitAnimationPlay(baofu, animation_35, 1);
    unitMove(unit_17, 1780, -1650, despawn, fastest);
    unitWait(unit_17);
}

function JIEI1_IDO()
{
    unitAnimationPlay(enemy1, animation_1, 1);
    unitMove3d(enemy1, 2800, 0, var_7ffff7e0, 30, 0);
    unitWait(enemy1);
    unitFace_2(enemy1, south);
  label_358:
    unitAnimationPlay(enemy1, animation_6, 245);
    unitWait(enemy1);
    b(label_358);
}

function JIEI2_IDO()
{
    unitAnimationPlay(enemy2, animation_1, 1);
    unitMove3d(enemy2, 2420, 0, var_7ffff8c6, 60, 0);
    unitWait(enemy2);
    unitFace_2(enemy2, south);
    unitMove3d(enemy2, 2420, 0, var_7ffff830, 15, 0);
    unitWait(enemy2);
  label_362:
    unitAnimationPlay(enemy2, animation_6, 245);
    unitWait(enemy2);
    b(label_362);
}

function JIEI3_IDO()
{
    unitAnimationPlay(enemy3, animation_1, 1);
    unitMove3d(enemy3, 2600, 0, var_7ffff6be, 30, 0);
    unitWait(enemy3);
    unitFace_2(enemy3, south);
  label_36a:
    sndMusicPlay(sound_3203, 127);
    unitAnimationPlay(enemy3, animation_6, 245);
    unitWait(enemy3);
    b(label_36a);
}

function MAYA_NIGE1()
{
    unitAnimationPlay(maya, animation_12, 1);
    unitWait(maya);
    unitFace_2(maya, south);
    unitAnimationPlay(maya, animation_1b, 1);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
    unitAnimationPlay(maya, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(maya, 3440, -300, -680, 20, 0);
    unitWait(maya);
    unitAnimationPlay(maya, animation_10, 1);
}

function MAYA_NIGE2()
{
    unitAnimationPlay(maya, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(maya, 3440, 0, -400, 20, 1);
}

function KATUYA_NIGE1()
{
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    unitFace_2(katsuya, south);
    unitAnimationPlay(katsuya, animation_1b, 1);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    unitAnimationPlay(katsuya, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(katsuya, 3350, -300, -820, 20, 0);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_10, 1);
}

function KATUYA_NIGE2()
{
    ref_38b = spriteLoad(sprite_d);
    wait(ref_38b);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    unitAnimationPlay(katsuya, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitDepthOffset(katsuya, 10);
    unitJumpTo(katsuya, 2850, 0, -750, 20, 0);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_10, 1);
    ref_395 = spriteLoad(sprite_d);
    wait(ref_395);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitMove(katsuya, 2550, -700, face_east, fast);
    unitWait(katsuya);
}

function ERI_NIGE1()
{
    unitAnimationPlay(elly, animation_12, 1);
    unitWait(elly);
    unitFace_2(elly, south);
    unitAnimationPlay(elly, animation_1b, 1);
    unitSpriteClear(elly);
    unitSpriteSet(elly, sprite_25);
    unitAnimationPlay(elly, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(elly, 3530, -300, -740, 20, 0);
    unitWait(elly);
    unitAnimationPlay(elly, animation_10, 1);
}

function ERI_NIGE2()
{
    unitAnimationPlay(elly, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(elly, 3530, 0, -500, 20, 1);
}

function NANJO_NIGE1()
{
    unitAnimationPlay(elly, animation_12, 1);
    unitWait(elly);
    unitFace_2(elly, south);
    unitAnimationPlay(elly, animation_1b, 1);
    unitSpriteClear(elly);
    unitSpriteSet(elly, sprite_21);
    unitAnimationPlay(elly, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(elly, 3530, -300, -740, 20, 0);
    unitWait(elly);
    unitAnimationPlay(elly, animation_10, 1);
}

function NANJO_NIGE2()
{
    unitAnimationPlay(elly, animation_1, 1);
    sndMusicPlay(sound_3201, 127);
    unitJumpTo(elly, 3530, 0, -500, 20, 1);
}

function SOUND()
{
    sndVolumeFadeOff(sound_3025, 120);
    delayClear();
    delayWait(90);
    sndMusicPlay(sound_301b, 127);
}

function KOKA()
{
    sndMusicPlay(sound_31fd, 127);
    unitAnimationPlay(unit_58, animation_6, 1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_31fe, 127);
    efctPlay(effect_8, efct_4, 3400, -600, -1000, 3400, -600, -1000, false);
}
