
msg_0:
[color(yellow)]克哉[color(white)]
[tab]これは、海底の地図のようだな…
[sync][wait][clear][end]

msg_1:
[color(yellow)]パオフゥ[color(white)]
[tab]らしいな…
[tab]海底遺跡ってなどこだ？
[sync][wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]丁度、天野君が立っている辺りらしい。
[sync][wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
[tab]ぐずぐずしてられねぇな…急ぐぞ。
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]この祠のようなもの…気にならないか。
[tab]一体、誰がその中にいた…？
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]ここで、悪巧みの算段をしてやがったみてぇだな…
[tab]待ってろ…竜蔵…
[sync][wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]マーヤ、約束したお見合いパーティの事憶えてる？
[tab]あれ、船上パーティだったんだよねぇ…
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]船は船でも、まさかこんな船に乗ることになる
[tab]なんて、思ってもなかったわ…
[sync][wait][clear][end]

msg_8:
[color(yellow)]南条[color(white)]
[tab]現代テクノロジーと呪術の融合が、
[tab]新世塾の十八番らしい。
[tab]酔狂な事だ。
[sync][wait][clear][end]

msg_9:
[color(yellow)]エリー[color(white)]
[tab]その床のＭａｒｋ…
[tab]何か呪術的なＳｉｇｎのようですわね。
[tab]旧き印にも似ていますけど…
[sync][wait][clear][end]
