
msg_0:
[color(yellow)]パオフゥ[color(white)]
[tab]じゃあ何か…
[tab]天野のデジャ・ヴュは、全部違う世界の記憶
[tab]だったってのか…？
[sync][wait][clear][end]

msg_1:
[color(yellow)]克哉[color(white)]
[tab]天野君や須藤[tab]竜也も、お前と同じ世界から
[tab]来たと言うのか！？
[sync][wait][clear][end]

msg_2:
[color(yellow)][tatsuya][color(white)]
[tab]それは…正確な表現じゃない…
[tab]須藤は、「純粋」に「こちら側」の人間だった…
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]「ヤツ」に「向こう側」の存在を教えられ、
[tab]いいように使われただけだ…
[sync][wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]じゃあ、どういうことなのさ！？
[tab]マーヤだって、その世界から来たんじゃ
[tab]ないんでしょ？
[sync][wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]マーヤにだけ、なんで「向こう側」とやらの
[tab]記憶があるわけ？
[tab]私らにはないんだよ！？
[sync][wait][clear][end]

msg_6:
[color(yellow)][tatsuya][color(white)]
[tab]色々理由があるんだ…
[sync][wait][clear][end]

msg_7:
[color(yellow)][tatsuya][color(white)]
[tab]やはり、これ以上知るのは止めた方がいい…
[sync][wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]バカ者…！
[tab]このまま引き下がれるものか！
[sync][wait][clear][end]

msg_9:
[color(yellow)][tatsuya][color(white)]
[tab]取り返しのつかないことになるかもしれないんだ！
[sync][wait][clear][end]

msg_10:
[tab]取り返しのつかないことになるかもしれないんだ！
[choice(2)][tatsuya]クン…私には知る権利があるわ。
[tatsuya]クン…一人で苦しまないで…
[end_choice][clear][end]

msg_11:
[color(yellow)][tatsuya][color(white)]
[tab]わかった…
[tab]見た方が早い…
[sync][wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[tab]………
[sync][wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]「ヤツ」…？
[tab]一体誰のことなんだ…
[sync][wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]這い寄る混沌…
[tab]我々の心の中にある元型が、意志を持ち
[tab]現実の世界に介入してくるだと…バカな…！
[sync][wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]違う世界にも、ＪＯＫＥＲがいただと…
[tab]何があった…「向こう側」とやらで…
[sync][wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]「向こう側」とやらじゃ、あの淳とかいうガキが
[tab]ＪＯＫＥＲだったってぇのか…
[tab]信じられんぜ…
[sync][wait][clear][end]

msg_17:
[color(yellow)]うらら[color(white)]
[tab]ねぇ…マーヤはマーヤだよね！？
[tab]私ら高校の頃からずっと一緒だったじゃないのさ！
[sync][wait][clear][end]

msg_18:
[color(yellow)]南条[color(white)]
[tab]園村と同じ…だとでも言うのか…
[tab]ありえんこと…だと思いたいが…
[sync][wait][clear][end]

msg_19:
[color(yellow)]エリー[color(white)]
[tab]Ｍａｋｉと同じ…ですの…？
[tab]まさか…そんな…
[sync][wait][clear][end]
