function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), add);
    sndIdGet(var_a);
    bne(var_a, -1, label_5);
    b(label_7);
  label_5:
    sndVolumeFadeOff(var_a, 60);
    b(label_7);
  label_7:
    sndMusicPlay(sound_3028, 127);
    cameraSet(southeast, 760, 0, -1280);
    levelFootstepSet(sfx_19);
    ref_a = spriteLoad(sprite_18);
    wait(ref_a);
    ref_c = spriteLoad(sprite_0);
    wait(ref_c);
    ref_e = spriteLoad(sprite_1);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_6);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_d);
    wait(ref_12);
    ref_14 = spriteLoad(sprite_13);
    wait(ref_14);
    ref_16 = spriteLoad(sprite_10d);
    wait(ref_16);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_1e);
    ref_1a = spriteLoad(sprite_23);
    wait(ref_1a);
    unitSpawn(elly, sprite_23, 900, 0, -1270, east, none);
    b(label_23);
  label_1e:
    bne(var_0, 1, label_23);
    ref_1f = spriteLoad(sprite_1f);
    wait(ref_1f);
    unitSpawn(elly, sprite_1f, 900, 0, -1270, east, none);
    b(label_23);
  label_23:
    unitSpawn(tatsuya, sprite_18, 700, 0, -1250, south, none);
    unitSpawn(maya, sprite_0, 700, -10, -1040, south, none);
    unitSpawn(ulala, sprite_6, 830, 0, -1460, south, none);
    unitSpawn(katsuya, sprite_d, 530, 0, -1250, south, none);
    unitSpawn(baofu, sprite_13, 620, 0, -1460, south, none);
    unitAnimationPlay(tatsuya, animation_10, 1);
    unitAnimationPlay(maya, animation_6, 1);
    unitAnimationPlay(ulala, animation_6, 1);
    unitAnimationPlay(katsuya, animation_10, 1);
    unitAnimationPlay(baofu, animation_10, 1);
    unitAnimationPlay(elly, animation_10, 1);
    bitSet(EBIT_E009F);
    bitSet(IBIT_ZIPPO);
    bitSet(TBIT_MD606);
    bitClear(TBIT_MD106);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), add);
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(90);
    ref_3a = bustupLoad(bustup_10);
    bustupWait(ref_3a);
    ref_3c = bustupAlloc(ref_3a, right, rgb(0,0,0));
    bustupFade(ref_3c, rgb(128,0,0), 30);
    bustupFlip(ref_3c, true);
    ref_3f = dialogAlloc();
    ref_40 = msgShow(msg_0);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]思い出したか…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_40);
    dialogFree(ref_3f);
    ref_44 = bustupFade(ref_3c, rgb(0,0,0), 10);
    bustupWait(ref_44);
    bustupFree(ref_3c);
    sndMusicPlay(sound_3269, 127);
    unitAnimationPlay(maya, animation_3c, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_42, 1);
    ref_4d = bustupLoad(bustup_4);
    bustupWait(ref_4d);
    ref_4f = bustupAlloc(ref_4d, left, rgb(0,0,0));
    bustupFade(ref_4f, rgb(128,0,0), 30);
    ref_51 = dialogAlloc();
    ref_52 = msgShow(msg_1);
/***************************************
[color(yellow)]舞耶[color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_52);
    dialogFree(ref_51);
    ref_56 = bustupFade(ref_4f, rgb(0,0,0), 10);
    bustupWait(ref_56);
    bustupFree(ref_4f);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_c, 1);
    ref_5c = bustupLoad(bustup_29);
    bustupWait(ref_5c);
    ref_5e = bustupAlloc(ref_5c, left, rgb(0,0,0));
    bustupFade(ref_5e, rgb(128,0,0), 30);
    ref_60 = dialogAlloc();
    ref_61 = msgShow(msg_2);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]この後…どうなった…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_61);
    dialogFree(ref_60);
    ref_65 = bustupFade(ref_5e, rgb(0,0,0), 10);
    bustupWait(ref_65);
    bustupFree(ref_5e);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(60);
    ref_6d = bustupLoad(bustup_10);
    bustupWait(ref_6d);
    ref_6f = bustupAlloc(ref_6d, right, rgb(0,0,0));
    bustupFade(ref_6f, rgb(128,0,0), 30);
    bustupFlip(ref_6f, true);
    ref_72 = dialogAlloc();
    ref_73 = msgShow(msg_3);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]岡村[tab]真夜という女と同じ名前の舞耶姉が死んで…
[tab]滅びの予言は成就した…

***************************************/
    wait(ref_73);
    ref_75 = msgShow(msg_4);
/***************************************
[tab]俺達の世界は…空に珠閒瑠市を残して滅亡した…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2b, 1);
    unitWait(tatsuya);
    unitAnimationPlay(tatsuya, animation_10, 1);
    sync();
    wait(ref_75);
    dialogFree(ref_72);
    ref_7c = bustupFade(ref_6f, rgb(0,0,0), 10);
    bustupWait(ref_7c);
    bustupFree(ref_6f);
    unitFace_2(katsuya, west);
    unitAnimationHold(katsuya, animation_21, 60);
    unitAnimationHold(elly, animation_21, 60);
    unitAnimationHold(baofu, animation_21, 60);
    unitAnimationHold(ulala, animation_22, 60);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(30);
    ref_88 = bustupLoad(bustup_10);
    bustupWait(ref_88);
    ref_8a = bustupAlloc(ref_88, right, rgb(0,0,0));
    bustupFade(ref_8a, rgb(128,0,0), 30);
    bustupFlip(ref_8a, true);
    ref_8d = dialogAlloc();
    ref_8e = msgShow(msg_5);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ヤツと戦った普遍的無意識の世界では、
[tab]強い想念が現実になる…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_8e);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    unitAnimationPlay(elly, animation_a, 1);
    unitAnimationPlay(tatsuya, animation_f, 1);
    ref_95 = msgShow(msg_6);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]俺達は…１０年前の出会いをリセットすることで、
[tab]それまでの事実や記憶と引き換えに、
[tab]そこから生まれる別の可能性世界を創ったんだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_95);
    dialogFree(ref_8d);
    ref_99 = bustupFade(ref_8a, rgb(0,0,0), 10);
    bustupWait(ref_99);
    bustupFree(ref_8a);
    unitAnimationPlay(tatsuya, animation_10, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(baofu, animation_14, 1);
    ref_a0 = bustupLoad(bustup_30);
    bustupWait(ref_a0);
    ref_a2 = bustupAlloc(ref_a0, left, rgb(0,0,0));
    bustupFade(ref_a2, rgb(128,0,0), 30);
    ref_a4 = dialogAlloc();
    ref_a5 = msgShow(msg_7);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]それが…この世界ってわけか…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a5);
    dialogFree(ref_a4);
    ref_a9 = bustupFade(ref_a2, rgb(0,0,0), 10);
    bustupWait(ref_a9);
    bustupFree(ref_a2);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(maya, animation_31, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_6, 1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(tatsuya, animation_a, 1);
    ref_b6 = bustupLoad(bustup_10);
    bustupWait(ref_b6);
    ref_b8 = bustupAlloc(ref_b6, right, rgb(0,0,0));
    bustupFade(ref_b8, rgb(128,0,0), 30);
    bustupFlip(ref_b8, true);
    ref_bb = dialogAlloc();
    ref_bc = msgShow(msg_8);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉は、自分のことは忘れろと言った…
[tab]全てを受け入れ、前に進めと…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_bc);
    unitAnimationPlay(maya, animation_12, 1);
    unitWait(maya);
    unitAnimationPlay(tatsuya, animation_2b, 1);
    ref_c2 = msgShow(msg_9);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]でも…俺達は耐えられなかった…

***************************************/
    wait(ref_c2);
    unitAnimationPlay(tatsuya, animation_10, 1);
    ref_c5 = msgShow(msg_10);
/***************************************
[tab]だから記憶と引き換えにこの世界を創って
[tab]逃げ込んできたんだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c5);
    ref_c8 = msgShow(msg_11);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]絶対忘れないと…淡い期待にすがりながら…
[sync][wait][clear]
***************************************/
    sndMusicPlay(sound_3269, 127);
    unitAnimationPlay(tatsuya, animation_31, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_37, 1);
    sync();
    wait(ref_c8);
    dialogFree(ref_bb);
    ref_d2 = bustupFade(ref_b8, rgb(0,0,0), 10);
    bustupWait(ref_d2);
    bustupFree(ref_b8);
    delayClear();
    delayWait(30);
    unitAnimationHold(ulala, animation_16, -1);
    ref_d8 = bustupLoad(bustup_1a);
    bustupWait(ref_d8);
    ref_da = bustupAlloc(ref_d8, left, rgb(0,0,0));
    bustupFade(ref_da, rgb(128,0,0), 30);
    ref_dc = dialogAlloc();
    ref_dd = msgShow(msg_12);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_dd);
    dialogFree(ref_dc);
    ref_e1 = bustupFade(ref_da, rgb(0,0,0), 10);
    bustupWait(ref_e1);
    bustupFree(ref_da);
    delayClear();
    delayWait(60);
    unitAnimationPlay(tatsuya, animation_3b, 1);
    ref_e7 = bustupLoad(bustup_10);
    bustupWait(ref_e7);
    ref_e9 = bustupAlloc(ref_e7, right, rgb(0,0,0));
    bustupFade(ref_e9, rgb(128,0,0), 30);
    bustupFlip(ref_e9, true);
    ref_ec = dialogAlloc();
    ref_ed = msgShow(msg_13);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]虫のいい話だ…そんな期待が叶うはずが無い…

***************************************/
    wait(ref_ed);
    unitAnimationPlay(tatsuya, animation_32, 1);
    ref_f0 = msgShow(msg_14);
/***************************************
[tab]「こちら側」の自分とシンクロした仲間達は、
[tab]「向こう側」のこともお互いのことも忘れてる…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f0);
    unitAnimationPlay(tatsuya, animation_37, 1);
    ref_f4 = msgShow(msg_15);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]なのに…俺は…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f4);
    dialogFree(ref_ec);
    ref_f8 = bustupFade(ref_e9, rgb(0,0,0), 10);
    bustupWait(ref_f8);
    bustupFree(ref_e9);
    unitAnimationStop(ulala);
    unitAnimationPlay(ulala, animation_6, 1);
    delayClear();
    delayWait(30);
    unitAnimationHold(baofu, animation_11, -1);
    ref_100 = bustupLoad(bustup_30);
    bustupWait(ref_100);
    ref_102 = bustupAlloc(ref_100, left, rgb(0,0,0));
    bustupFade(ref_102, rgb(128,0,0), 30);
    ref_104 = dialogAlloc();
    ref_105 = msgShow(msg_16);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]それで、天野や淳とかいう坊主達は、
[tab]「向こう側」の事を憶えてねぇのか…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_105);
    dialogFree(ref_104);
    ref_109 = bustupFade(ref_102, rgb(0,0,0), 10);
    bustupWait(ref_109);
    bustupFree(ref_102);
    bne(var_0, 0, label_11b);
    unitAnimationHold(elly, animation_1a, -1);
    ref_10e = bustupLoad(bustup_42);
    bustupWait(ref_10e);
    ref_110 = bustupAlloc(ref_10e, left, rgb(0,0,0));
    bustupFade(ref_110, rgb(128,0,0), 30);
    ref_112 = dialogAlloc();
    ref_113 = msgShow(msg_17);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]私達に「向こう側」の記憶が無いのは、
[tab]純粋な「こちら側」の人間だからなのですわね…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_113);
    dialogFree(ref_112);
    ref_117 = bustupFade(ref_110, rgb(0,0,0), 10);
    bustupWait(ref_117);
    bustupFree(ref_110);
    b(label_12a);
  label_11b:
    bne(var_0, 1, label_12a);
    unitAnimationHold(elly, animation_11, -1);
    ref_11d = bustupLoad(bustup_3b);
    bustupWait(ref_11d);
    ref_11f = bustupAlloc(ref_11d, left, rgb(0,0,0));
    bustupFade(ref_11f, rgb(128,0,0), 30);
    ref_121 = dialogAlloc();
    ref_122 = msgShow(msg_18);
/***************************************
[color(yellow)]南条[color(white)]
[tab]純粋に「こちら側」の人間である我々に、
[tab]「向こう側」の記憶が無いのも当然だな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_122);
    dialogFree(ref_121);
    ref_126 = bustupFade(ref_11f, rgb(0,0,0), 10);
    bustupWait(ref_126);
    bustupFree(ref_11f);
    b(label_12a);
  label_12a:
    delayClear();
    delayWait(90);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_29, 1);
    ref_131 = bustupLoad(bustup_10);
    bustupWait(ref_131);
    ref_133 = bustupAlloc(ref_131, right, rgb(0,0,0));
    bustupFade(ref_133, rgb(128,0,0), 30);
    bustupFlip(ref_133, true);
    ref_136 = dialogAlloc();
    ref_137 = msgShow(msg_19);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]だが、それも変わりつつある…
[tab]「ヤツ」は、俺が特異点だと言った…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_137);
    unitAnimationStop(baofu);
    unitAnimationStop(elly);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(tatsuya, animation_1f, 1);
    ref_13e = msgShow(msg_20);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]この世界は、俺達５人の記憶のリセットという
[tab]法則で成り立っている…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_13e);
    unitAnimationPlay(tatsuya, animation_6, 1);
    ref_142 = msgShow(msg_21);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]俺達全員が記憶を取り戻せば、
[tab]二つの世界を隔てる境界の歪みが大きくなって…
[tab]この世界そのものが消えてしまうんだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_142);
    dialogFree(ref_136);
    ref_146 = bustupFade(ref_133, rgb(0,0,0), 10);
    bustupWait(ref_146);
    bustupFree(ref_133);
    unitFace_2(maya, north);
    unitAnimationHold(maya, animation_21, 60);
    unitAnimationHold(katsuya, animation_21, 60);
    unitAnimationHold(elly, animation_21, 60);
    unitAnimationHold(baofu, animation_21, 60);
    unitAnimationHold(ulala, animation_22, 60);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_14, 1);
    ref_155 = bustupLoad(bustup_10);
    bustupWait(ref_155);
    ref_157 = bustupAlloc(ref_155, right, rgb(0,0,0));
    bustupFade(ref_157, rgb(128,0,0), 30);
    bustupFlip(ref_157, true);
    ref_15a = dialogAlloc();
    ref_15b = msgShow(msg_22);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]これ以上、舞耶姉に関わって欲しくないんだ…
[tab]わかっただろ…

***************************************/
    wait(ref_15b);
    sndVolumeFadeOff(sound_3028, 120);
    ref_15e = msgShow(msg_23);
/***************************************
[tab]手を引いてくれ…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_12, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(30);
    unitFace_2(tatsuya, north);
    unitAnimationPlay(tatsuya, animation_1, 1);
    sync();
    wait(ref_15e);
    dialogFree(ref_15a);
    ref_168 = bustupFade(ref_157, rgb(0,0,0), 10);
    bustupWait(ref_168);
    bustupFree(ref_157);
    delayClear();
    delayWait(60);
    sndLoad(sound_300c);
    ref_16e = bustupLoad(bustup_31);
    bustupWait(ref_16e);
    ref_170 = bustupAlloc(ref_16e, left, rgb(0,0,0));
    bustupFade(ref_170, rgb(128,0,0), 30);
    ref_172 = dialogAlloc();
    ref_173 = msgShow(msg_24);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]何の話だったっけなぁ…芹沢…？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_c, 1);
    sync();
    wait(ref_173);
    dialogFree(ref_172);
    ref_17a = bustupFade(ref_170, rgb(0,0,0), 10);
    bustupWait(ref_17a);
    bustupFree(ref_170);
    unitAnimationPlay(maya, animation_0, 1);
    unitAnimationPlay(ulala, animation_4, 1);
    unitAnimationPlay(katsuya, animation_3, 1);
    unitAnimationPlay(elly, animation_0, 1);
    unitAnimationPlay(tatsuya, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationHold(ulala, animation_1a, -1);
    ref_188 = bustupLoad(bustup_17);
    bustupWait(ref_188);
    ref_18a = bustupAlloc(ref_188, left, rgb(0,0,0));
    bustupFade(ref_18a, rgb(128,0,0), 30);
    ref_18c = dialogAlloc();
    ref_18d = msgShow(msg_25);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]さぁ…[delay(30)]

***************************************/
    wait(ref_18d);
    unitAnimationPlay(katsuya, animation_3, 1);
    unitAnimationPlay(elly, animation_1, 1);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitAnimationStop(ulala);
    ref_193 = msgShow(msg_26);
/***************************************
[tab]子供を騙すのは、大人の特権って話じゃなかった？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_193);
    dialogFree(ref_18c);
    ref_197 = bustupFade(ref_18a, rgb(0,0,0), 10);
    bustupWait(ref_197);
    bustupFree(ref_18a);
    delayClear();
    delayWait(60);
    unitAnimationPlay(katsuya, animation_2b, 1);
    ref_19d = bustupLoad(bustup_2a);
    bustupWait(ref_19d);
    ref_19f = bustupAlloc(ref_19d, left, rgb(0,0,0));
    bustupFade(ref_19f, rgb(128,0,0), 30);
    ref_1a1 = dialogAlloc();
    ref_1a2 = msgShow(msg_27);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]いや…[delay(30)]

***************************************/
    wait(ref_1a2);
    unitAnimationPlay(maya, animation_1, 1);
    unitAnimationPlay(ulala, animation_d, 1);
    unitAnimationPlay(baofu, animation_d, 1);
    unitAnimationPlay(elly, animation_0, 1);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitAnimationHold(katsuya, animation_11, -1);
    ref_1aa = msgShow(msg_28);
/***************************************
[tab]子供の不始末の責任を取るのが、大人の役目
[tab]という話だ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1aa);
    dialogFree(ref_1a1);
    ref_1ae = bustupFade(ref_19f, rgb(0,0,0), 10);
    bustupWait(ref_1ae);
    bustupFree(ref_19f);
    unitAnimationStop(katsuya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_0, 1);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    unitAnimationPlay(tatsuya, animation_0, 1);
    delayClear();
    delayWait(60);
    ref_1ba = bustupLoad(bustup_e);
    bustupWait(ref_1ba);
    ref_1bc = bustupAlloc(ref_1ba, right, rgb(0,0,0));
    bustupFade(ref_1bc, rgb(128,0,0), 30);
    bustupFlip(ref_1bc, true);
    ref_1bf = dialogAlloc();
    ref_1c0 = msgShow(msg_29);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_28, 1);
    unitWait(tatsuya);
    sync();
    wait(ref_1c0);
    ref_1c5 = bustupFade(ref_1bc, rgb(0,0,0), 10);
    bustupWait(ref_1c5);
    bustupFree(ref_1bc);
    unitAnimationPlay(tatsuya, animation_6, 1);
    ref_1c9 = bustupLoad(bustup_d);
    bustupWait(ref_1c9);
    ref_1cb = bustupAlloc(ref_1c9, right, rgb(0,0,0));
    bustupFade(ref_1cb, rgb(128,0,0), 30);
    bustupFlip(ref_1cb, true);
    ref_1ce = msgShow(msg_30);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]騙したな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1ce);
    dialogFree(ref_1bf);
    ref_1d2 = bustupFade(ref_1cb, rgb(0,0,0), 10);
    bustupWait(ref_1d2);
    bustupFree(ref_1cb);
    unitMove(maya, 700, -1180, face_north, slow);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_12, 1);
    unitWait(tatsuya);
    unitFace_2(tatsuya, south);
    unitAnimationPlay(tatsuya, animation_0, 1);
    delayClear();
    delayWait(30);
    ref_1df = bustupLoad(bustup_9);
    bustupWait(ref_1df);
    ref_1e1 = bustupAlloc(ref_1df, center, rgb(0,0,0));
    bustupFade(ref_1e1, rgb(128,0,0), 30);
    ref_1e3 = dialogChoiceAlloc();
    ref_1e4 = msgShow(msg_31);
/***************************************
[tab]騙したな…
[choice(2)]バカッ…！そんなに傷だらけになって…
いいの…もう…いいの…
[end_choice][clear]
***************************************/
    sync();
    wait(ref_1e4);
    dialogFree(ref_1e3);
    ref_1e8 = bustupFade(ref_1e1, rgb(0,0,0), 10);
    bustupWait(ref_1e8);
    bustupFree(ref_1e1);
    choiceGetResult(var_1);
    bne(var_1, 0, label_1ef);
    b(label_1f2);
    b(label_1f2);
  label_1ef:
    bne(var_1, 1, label_1f2);
    b(label_24a);
    b(label_1f2);
  label_1f2:
    sndMusicPlay(sound_300c, 127);
    unitMove(maya, 710, -1220, face_north, slow);
    unitWait(maya);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_1);
    unitAnimationPlay(maya, animation_10, 1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_326a, 127);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitAnimationHold(ulala, animation_22, 60);
    unitAnimationHold(katsuya, animation_22, 60);
    unitAnimationHold(baofu, animation_21, 60);
    unitAnimationHold(elly, animation_21, 60);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_1f, 1);
    ref_207 = bustupLoad(bustup_f);
    bustupWait(ref_207);
    ref_209 = bustupAlloc(ref_207, right, rgb(0,0,0));
    bustupFade(ref_209, rgb(128,0,0), 30);
    bustupFlip(ref_209, true);
    ref_20c = dialogAlloc();
    ref_20d = msgShow(msg_32);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]お、俺は…！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_20d);
    dialogFree(ref_20c);
    ref_211 = bustupFade(ref_209, rgb(0,0,0), 10);
    bustupWait(ref_211);
    bustupFree(ref_209);
    unitAnimationPlay(maya, animation_11, 1);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_326a, 127);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitAnimationHold(ulala, animation_22, 60);
    unitAnimationHold(katsuya, animation_22, 60);
    unitAnimationHold(baofu, animation_21, 60);
    unitAnimationHold(elly, animation_21, 60);
    delayClear();
    delayWait(60);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitMove(maya, 700, -1150, face_north, reverse);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_6, 1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(tatsuya, animation_6, 1);
    ref_22e = bustupLoad(bustup_10);
    bustupWait(ref_22e);
    ref_230 = bustupAlloc(ref_22e, right, rgb(0,0,0));
    bustupFade(ref_230, rgb(128,0,0), 30);
    bustupFlip(ref_230, true);
    ref_233 = dialogAlloc();
    ref_234 = msgShow(msg_33);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ごめん…
[tab]わかったから…怒らないでくれ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_234);
    dialogFree(ref_233);
    ref_238 = bustupFade(ref_230, rgb(0,0,0), 10);
    bustupWait(ref_238);
    bustupFree(ref_230);
    unitAnimationPlay(tatsuya, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_10, 1);
    unitAnimationPlay(elly, animation_10, 1);
    unitAnimationHold(ulala, animation_16, -1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, east);
    unitAnimationHold(katsuya, animation_16, -1);
    delayClear();
    delayWait(200);
    b(label_2b7);
  label_24a:
    sndMusicPlay(sound_300c, 127);
    bitSet(EBIT_HOLD);
    unitMove(maya, 700, -1210, face_north, slow);
    unitWait(maya);
    unitSpawn(npc1, sprite_10d, 700, 0, -1230, south, none);
    unitDespawn(tatsuya, none);
    unitDespawn(maya, none);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc1, animation_1, 1);
    unitWait(npc1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_2, 1);
    ref_258 = bustupLoad(bustup_d);
    bustupWait(ref_258);
    ref_25a = bustupAlloc(ref_258, right, rgb(0,0,0));
    bustupFade(ref_25a, rgb(128,0,0), 30);
    bustupFlip(ref_25a, true);
    ref_25d = dialogAlloc();
    ref_25e = msgShow(msg_34);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉…俺に、そんな資格は…！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_25e);
    dialogFree(ref_25d);
    ref_262 = bustupFade(ref_25a, rgb(0,0,0), 10);
    bustupWait(ref_262);
    bustupFree(ref_25a);
    unitAnimationPlay(npc1, animation_4, 1);
    unitWait(npc1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc1, animation_5, 1);
    delayClear();
    delayWait(60);
    ref_26c = bustupLoad(bustup_10);
    bustupWait(ref_26c);
    ref_26e = bustupAlloc(ref_26c, right, rgb(0,0,0));
    bustupFade(ref_26e, rgb(128,0,0), 30);
    bustupFlip(ref_26e, true);
    ref_271 = dialogAlloc();
    ref_272 = msgShow(msg_35);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]俺は…ここにいていいのか…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_272);
    dialogFree(ref_271);
    ref_276 = bustupFade(ref_26e, rgb(0,0,0), 10);
    bustupWait(ref_276);
    bustupFree(ref_26e);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_1, 1);
    unitWait(npc1);
    delayClear();
    delayWait(60);
    ref_27f = bustupLoad(bustup_9);
    bustupWait(ref_27f);
    ref_281 = bustupAlloc(ref_27f, left, rgb(0,0,0));
    bustupFade(ref_281, rgb(128,0,0), 30);
    ref_283 = dialogAlloc();
    ref_284 = msgShow(msg_36);
/***************************************
[color(yellow)]舞耶[color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_3, 1);
    unitWait(npc1);
    sync();
    wait(ref_284);
    dialogFree(ref_283);
    ref_28a = bustupFade(ref_281, rgb(0,0,0), 10);
    bustupWait(ref_28a);
    bustupFree(ref_281);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_4, 1);
    unitWait(npc1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc1, animation_5, 1);
    ref_294 = bustupLoad(bustup_10);
    bustupWait(ref_294);
    ref_296 = bustupAlloc(ref_294, right, rgb(0,0,0));
    bustupFade(ref_296, rgb(128,0,0), 30);
    bustupFlip(ref_296, true);
    ref_299 = dialogAlloc();
    ref_29a = msgShow(msg_37);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ありがとう…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_29a);
    dialogFree(ref_299);
    ref_29e = bustupFade(ref_296, rgb(0,0,0), 10);
    bustupWait(ref_29e);
    bustupFree(ref_296);
    delayClear();
    delayWait(60);
    unitAnimationPlay(baofu, animation_10, 1);
    unitAnimationPlay(elly, animation_10, 1);
    unitAnimationHold(ulala, animation_16, -1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitWait(katsuya);
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, east);
    unitAnimationHold(katsuya, animation_16, -1);
    delayClear();
    delayWait(200);
    unitAnimationPlay(npc1, animation_6, 1);
    unitWait(npc1);
    unitSpawn(tatsuya, sprite_18, 695, 0, -1235, south, none);
    unitSpawn(maya, sprite_0, 700, 0, -1210, north, none);
    unitDespawn(npc1, none);
    unitAnimationPlay(maya, animation_5, 1);
    unitAnimationPlay(tatsuya, animation_6, 1);
    delayClear();
    delayWait(90);
  label_2b7:
    bne(var_0, 0, label_2ba);
    b(label_2bd);
    b(label_2bd);
  label_2ba:
    bne(var_0, 1, label_2bd);
    b(label_320);
    b(label_2bd);
  label_2bd:
    unitAnimationPlay(elly, animation_a, 1);
    ref_2be = bustupLoad(bustup_3e);
    bustupWait(ref_2be);
    ref_2c0 = bustupAlloc(ref_2be, left, rgb(0,0,0));
    bustupFade(ref_2c0, rgb(128,0,0), 30);
    ref_2c2 = dialogAlloc();
    ref_2c3 = msgShow(msg_38);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]私の役目も、ここまでのようですわね…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2c3);
    unitAnimationStop(ulala);
    unitAnimationStop(katsuya);
    unitAnimationPlay(maya, animation_4, 1);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitAnimationPlay(baofu, animation_b, 1);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitAnimationPlay(elly, animation_14, 1);
    ref_2ce = msgShow(msg_39);
/***************************************
[color(yellow)]エリー[color(white)]
[tab][tatsuya]…後は、Ｙｏｕと皆さんの戦い…

***************************************/
    wait(ref_2ce);
    unitAnimationPlay(elly, animation_1f, 1);
    ref_2d1 = msgShow(msg_40);
/***************************************
[tab]しっかり、Ｍｓ．Ａｍａｎｏをお守りして
[tab]差し上げてね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2d1);
    dialogFree(ref_2c2);
    ref_2d5 = bustupFade(ref_2c0, rgb(0,0,0), 10);
    bustupWait(ref_2d5);
    bustupFree(ref_2c0);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(ulala, animation_1f, 1);
    ref_2dc = bustupLoad(bustup_17);
    bustupWait(ref_2dc);
    ref_2de = bustupAlloc(ref_2dc, left, rgb(0,0,0));
    bustupFade(ref_2de, rgb(128,0,0), 30);
    ref_2e0 = dialogAlloc();
    ref_2e1 = msgShow(msg_41);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]エリーちゃんはどうするの？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2e1);
    dialogFree(ref_2e0);
    ref_2e5 = bustupFade(ref_2de, rgb(0,0,0), 10);
    bustupWait(ref_2e5);
    bustupFree(ref_2de);
    unitAnimationPlay(elly, animation_b, 1);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(elly, animation_1f, 1);
    ref_2ed = bustupLoad(bustup_3e);
    bustupWait(ref_2ed);
    ref_2ef = bustupAlloc(ref_2ed, left, rgb(0,0,0));
    bustupFade(ref_2ef, rgb(128,0,0), 30);
    ref_2f1 = dialogAlloc();
    ref_2f2 = msgShow(msg_42);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｋｅｉ達と、街の人々をお助けしますわ。

***************************************/
    wait(ref_2f2);
    unitAnimationPlay(elly, animation_10, 1);
    ref_2f5 = msgShow(msg_43);
/***************************************
[tab]そして、約束を果たします。

***************************************/
    wait(ref_2f5);
    unitAnimationPlay(elly, animation_1e, 1);
    ref_2f8 = msgShow(msg_44);
/***************************************
[tab]私自身のために。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2f8);
    dialogFree(ref_2f1);
    ref_2fc = bustupFade(ref_2ef, rgb(0,0,0), 10);
    bustupWait(ref_2fc);
    bustupFree(ref_2ef);
    unitAnimationPlay(elly, animation_a, 1);
    unitAnimationPlay(ulala, animation_1e, 1);
    ref_301 = bustupLoad(bustup_18);
    bustupWait(ref_301);
    ref_303 = bustupAlloc(ref_301, left, rgb(0,0,0));
    bustupFade(ref_303, rgb(128,0,0), 30);
    ref_305 = dialogAlloc();
    ref_306 = msgShow(msg_45);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]イイ顔してるじゃん！

***************************************/
    wait(ref_306);
    unitAnimationPlay(elly, animation_b, 1);
    unitAnimationPlay(ulala, animation_1f, 1);
    ref_30a = msgShow(msg_46);
/***************************************
[tab]それなら、きっと大丈夫よ。
[tab]がんばってね！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_30a);
    dialogFree(ref_305);
    ref_30e = bustupFade(ref_303, rgb(0,0,0), 10);
    bustupWait(ref_30e);
    bustupFree(ref_303);
    unitAnimationPlay(ulala, animation_a, 1);
    partyItemUnequip(elly, weapon);
    partyItemUnequip(elly, head);
    partyItemUnequip(elly, body);
    partyItemUnequip(elly, leg);
    partyItemUnequip(elly, accessory);
    partyHealthRestore(elly);
    partySPRestore(elly);
    partyStatusClear(elly);
    partyMemberRemovePermanent(elly);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_26, 1);
    unitWait(elly);
    b(label_37f);
  label_320:
    unitAnimationPlay(elly, animation_a, 1);
    ref_321 = bustupLoad(bustup_37);
    bustupWait(ref_321);
    ref_323 = bustupAlloc(ref_321, left, rgb(0,0,0));
    bustupFade(ref_323, rgb(128,0,0), 30);
    ref_325 = dialogAlloc();
    ref_326 = msgShow(msg_47);
/***************************************
[color(yellow)]南条[color(white)]
[tab]フッ…
[tab]どうやら、俺の役目はここまでのようだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_326);
    unitAnimationStop(ulala);
    unitAnimationStop(katsuya);
    unitAnimationPlay(maya, animation_4, 1);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(katsuya, animation_12, 1);
    unitAnimationPlay(baofu, animation_b, 1);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitAnimationPlay(elly, animation_14, 1);
    ref_331 = msgShow(msg_48);
/***************************************
[color(yellow)]南条[color(white)]
[tab]良い大人に囲まれているな、少年…

***************************************/
    wait(ref_331);
    unitAnimationPlay(elly, animation_14, 1);
    ref_334 = msgShow(msg_49);
/***************************************
[tab]恩は、身命を賭して返せよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_334);
    dialogFree(ref_325);
    ref_338 = bustupFade(ref_323, rgb(0,0,0), 10);
    bustupWait(ref_338);
    bustupFree(ref_323);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    unitFace_2(katsuya, west);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_340 = bustupLoad(bustup_21);
    bustupWait(ref_340);
    ref_342 = bustupAlloc(ref_340, left, rgb(0,0,0));
    bustupFade(ref_342, rgb(128,0,0), 30);
    ref_344 = dialogAlloc();
    ref_345 = msgShow(msg_50);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]君はどうするんだ…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_345);
    dialogFree(ref_344);
    ref_349 = bustupFade(ref_342, rgb(0,0,0), 10);
    bustupWait(ref_349);
    bustupFree(ref_342);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_1e, 1);
    ref_350 = bustupLoad(bustup_36);
    bustupWait(ref_350);
    ref_352 = bustupAlloc(ref_350, left, rgb(0,0,0));
    bustupFade(ref_352, rgb(128,0,0), 30);
    ref_354 = dialogAlloc();
    ref_355 = msgShow(msg_51);
/***************************************
[color(yellow)]南条[color(white)]
[tab]己の信じる道を行くまでです。

***************************************/
    wait(ref_355);
    unitAnimationPlay(elly, animation_1f, 1);
    ref_358 = msgShow(msg_52);
/***************************************
[tab]俺は俺で、街の混乱を治めるために尽力します。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_358);
    dialogFree(ref_354);
    ref_35c = bustupFade(ref_352, rgb(0,0,0), 10);
    bustupWait(ref_35c);
    bustupFree(ref_352);
    unitAnimationPlay(elly, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationHold(baofu, animation_11, -1);
    ref_363 = bustupLoad(bustup_31);
    bustupWait(ref_363);
    ref_365 = bustupAlloc(ref_363, left, rgb(0,0,0));
    bustupFade(ref_365, rgb(128,0,0), 30);
    ref_367 = dialogAlloc();
    ref_368 = msgShow(msg_53);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]へへ…
[tab]お互い命があったら、そのうち一杯やろうや…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_368);
    dialogFree(ref_367);
    ref_36c = bustupFade(ref_365, rgb(0,0,0), 10);
    bustupWait(ref_36c);
    bustupFree(ref_365);
    unitAnimationStop(baofu);
    unitAnimationPlay(baofu, animation_b, 1);
    partyItemUnequip(nanjo, weapon);
    partyItemUnequip(nanjo, head);
    partyItemUnequip(nanjo, body);
    partyItemUnequip(nanjo, leg);
    partyItemUnequip(nanjo, accessory);
    partyHealthRestore(nanjo);
    partySPRestore(nanjo);
    partyStatusClear(nanjo);
    partyMemberRemovePermanent(nanjo);
    delayClear();
    delayWait(30);
    unitAnimationPlay(elly, animation_26, 1);
    unitWait(elly);
    b(label_37f);
  label_37f:
    delayClear();
    delayWait(30);
    call(PERSONASET);
}

function PERSONASET()
{
    delayClear();
    delayWait(30);
    partyPersonaStockCount(var_2, party_stock);
    call(TATUYA);
    b(label_39e);
    bitGet(var_3, MBIT_HI_NANJOTOUJO);
    bne(var_3, 0, label_393);
    ref_38a = dialogAlloc();
    ref_38b = msgShow(msg_54);
/***************************************
[color(green)][tab]エリーがパーティから外れ、[tatsuya]が入ります。
[tab]パーティストックに空きがありません。
[tab]一体分の空きを確保してください。[color(white)]
[wait][clear]
***************************************/
    wait(ref_38b);
    dialogFree(ref_38a);
    ref_38e = shopOverlayInit();
    wait(ref_38e);
    ref_390 = shopOpen(22);
    wait(ref_390);
    b(label_39d);
  label_393:
    bne(var_3, 1, label_39d);
    ref_394 = dialogAlloc();
    ref_395 = msgShow(msg_55);
/***************************************
[color(green)][tab]南条がパーティから外れ、[tatsuya]が入ります。
[tab]パーティストックに空きがありません。
[tab]一体分の空きを確保してください。[color(white)]
[wait][clear]
***************************************/
    wait(ref_395);
    dialogFree(ref_394);
    ref_398 = shopOverlayInit();
    wait(ref_398);
    ref_39a = shopOpen(22);
    wait(ref_39a);
    b(label_39d);
  label_39d:
    b(label_39e);
  label_39e:
}

function TATUYA()
{
    bitSet(TBIT_EVT104);
    partyMemberAdd(tatsuya);
    sndVolumeFadeOff(sound_300c, 90);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    mapLoad(rengedai, 36, 1);
}

function HA_SHOP_END_0()
{
    call(TEST01);
}

function TEST01()
{
    delayClear();
    delayWait(10);
    call(PERSONASET);
}
