
msg_0:
[color(yellow)]うらら[color(white)]
[tab]似てるよ…
[tab]この話、新世塾と戦ってる私らに似てない…？
[sync][wait][clear][end]

msg_1:
[color(yellow)]克哉[color(white)]
[tab]淳君を操ったという、「ヤツ」とは何者なんだ…？
[sync][wait][clear][end]

msg_2:
[color(yellow)][tatsuya][color(white)]
[tab]姿は淳の父親だが、中身は全然違う…
[tab]這い寄る混沌…ニャルラトホテプ…
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]ヤツは、フィレモンと対を成す存在だ…
[tab]俺達人間の心の奥に潜み、運命を弄ぶ巨大な影…
[sync][wait][clear][end]

msg_4:
[color(yellow)][tatsuya][color(white)]
[tab]ヤツの目的は、「向こう側」と同じようなことを
[tab]「こちら側」でも起こすことだ…
[tab]新世塾は、その駒に過ぎない…
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]お前さんの世界と同じ事を起こすってな…
[tab]どういうことだ…？
[sync][wait][clear][end]

msg_6:
[color(yellow)][tatsuya][color(white)]
[tab]………
[tab]それは、この先でわかる…
[sync][wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]フィレモンと対の存在…？
[tab]人の自我を破滅に導く元型だと…？
[sync][wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]そんなものがいるとすれば…
[tab]とてつもなく大きなシャドウだぞ…
[tab]人間という種そのものの影だとでもいうのか…
[sync][wait][clear][end]

msg_9:
[color(yellow)]パオフゥ[color(white)]
[tab]夢見る心を集める仮面党に、
[tab]穢れを集める新世塾か…
[tab]確かに、芹沢の言う通り似てやがる…
[sync][wait][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]新世塾の裏に、でっかいボスがいるってわけ…？
[tab]それも、私らの心の中に！？
[sync][wait][clear][end]

msg_11:
[color(yellow)]南条[color(white)]
[tab]ニャルラトホテプだと…！？
[tab]神取の…単なるペルソナではないというのか？
[sync][wait][clear][end]

msg_12:
[color(yellow)]エリー[color(white)]
[tab]Ｎｙａｒｌａｔｈｏｔｅｐ…
[tab]這い寄る混沌…無貌の神…
[tab]単なるＰＥＲＳＯＮＡではないという事ですの？
[sync][wait][clear][end]
