function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(northwest, 960, 0, -571);
    ref_3 = spriteLoad(sprite_0);
    wait(ref_3);
    ref_5 = spriteLoad(sprite_6);
    wait(ref_5);
    ref_7 = spriteLoad(sprite_d);
    wait(ref_7);
    ref_9 = spriteLoad(sprite_13);
    wait(ref_9);
    ref_b = spriteLoad(sprite_1f);
    wait(ref_b);
    ref_d = spriteLoad(sprite_23);
    wait(ref_d);
    ref_f = spriteLoad(sprite_18);
    wait(ref_f);
    unitSpawn(maya, sprite_0, 1250, 0, -600, north, none);
    unitSpawn(ulala, sprite_6, 1250, 0, -600, north, none);
    unitSpawn(katsuya, sprite_d, 1250, 0, -600, north, none);
    unitSpawn(baofu, sprite_13, 1250, 0, -600, north, none);
    unitSpawn(tatsuya, sprite_18, 601, 0, -617, north, none);
    unitFace(tatsuya, east);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    bitGet(var_1, MBIT_HI_NANJOTOUJO);
    bnz(var_1, label_1d);
    unitSpawn(elly, sprite_23, 1250, 0, -600, north, none);
    b(label_1e);
  label_1d:
    unitSpawn(nanjo, sprite_1f, 1250, 0, -600, north, none);
  label_1e:
    screenNarrow(3);
    sndIdGet(var_0);
    sndVolumeFadeOff(var_0, 180);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    call(URARA_IDOU);
    delayClear();
    delayWait(12);
    unitMove(maya, 900, -650, face_east, medium);
    delayClear();
    delayWait(8);
    call(KATUYA_IDOU);
    delayClear();
    delayWait(5);
    call(PAOFU_IDOU);
    delayClear();
    delayWait(10);
    bnz(var_1, label_36);
    call(ERI_IDOU);
    delayClear();
    delayWait(16);
    unitWait(maya);
    b(label_3a);
  label_36:
    call(NANJO_IDOU);
    delayClear();
    delayWait(16);
    unitWait(maya);
  label_3a:
    delayClear();
    delayWait(60);
    unitLook(maya, lookDir_1);
    delayClear();
    delayWait(30);
    unitLook(maya, lookDir_2);
    delayClear();
    delayWait(10);
    unitLook(maya, lookDir_3);
    delayClear();
    delayWait(50);
    cameraMoveTo(323, 0, -313, 120);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_3255, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), add);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    op_bd();
    eventLoad(event_c9);
}

function URARA_IDOU()
{
    unitMove(ulala, 1050, -700, face_east, medium);
    unitWait(ulala);
    unitFace(ulala, east);
}

function KATUYA_IDOU()
{
    unitMove(katsuya, 1220, -650, face_east, medium);
    unitWait(katsuya);
    unitFace(katsuya, east);
}

function PAOFU_IDOU()
{
    unitMove(baofu, 1020, -540, face_east, medium);
    unitWait(baofu);
    unitFace(baofu, east);
}

function ERI_IDOU()
{
    unitMove(elly, 1170, -470, face_east, medium);
    unitWait(elly);
    unitFace(elly, east);
}

function NANJO_IDOU()
{
    unitMove(nanjo, 1170, -470, face_east, medium);
    unitWait(nanjo);
    unitFace(nanjo, east);
}
