
msg_0:
[color(yellow)]パオフゥ[color(white)]
[tab]驚いたねどうも…
[tab]なんてぇでかさだ…
[sync][wait][clear][end]

msg_1:
[color(yellow)][tatsuya][color(white)]
[tab]街を乗せて飛ぶくらいだからな…
[sync][wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]これさ、神様だか宇宙人だかの船って噂じゃん…？
[tab]なんか、凄い罠とかあったりするんじゃ…
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]「向こう側」でシバルバーと呼ばれたこの船では、
[tab]悪い思考が現実になる…
[tab]下手な事は考えないほうがいい。
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]なぜそんな事が…
[sync][wait][clear][end]

msg_5:
[color(yellow)][tatsuya][color(white)]
[tab]人々の怖れ…不安…期待…
[tab]それが噂の形を借りて作り出したこいつは、
[tab]無意識の世界の現身なんだ…
[sync][wait][clear][end]

msg_6:
[color(yellow)][tatsuya][color(white)]
[tab]フィレモンは、
[tab]無意識の世界では思考が現実になると言った…
[tab]たぶんそのせいだ…
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]じゃあ、楽しい事考えればいいわけね。
[tab]楽勝じゃ～ん？[tab]じゃんじゃ～ん。
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]いや…ここはヤツの独壇場だ…
[tab]何も考えるな…
[sync][wait][clear][end]
