
msg_0:
[color(yellow)]シャドウ克哉[color(white)]
[tab]フン…
[tab]後悔ここに極まれり、だな…
[wait][clear][end]

msg_1:
[color(yellow)]克哉[color(white)]
[tab]ふざけるな！
[tab]僕は後悔などしていない！
[wait][clear][end]

msg_2:
[color(yellow)]シャドウ克哉[color(white)]
[tab]フッ…嘘つきは泥棒の始まりだぞ？
[tab]本当は、父や弟を疎ましく思っているはずだ。
[tab]父や弟がいなければ違う道を選べたのに、とな。
[wait][clear][end]

msg_3:
[color(yellow)]シャドウ克哉[color(white)]
[tab]良き長男を演じるのも疲れたろう…
[tab]お前の家族への愛情は、ただの役割だ。
[sync][wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]断じて…違…う…
[wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]どうした、[suou]！？
[tab]シャキっとしろ…！
[wait][clear][end]

msg_6:
[color(yellow)]シャドウ克哉[color(white)]
[tab]また…お前はその女に惚れている。
[sync][wait][clear][end]

msg_7:
[color(yellow)]舞耶[tab][tatsuya][color(white)]
[tab]………！？
[wait][clear][end]

msg_8:
[color(yellow)]シャドウ克哉[color(white)]
[tab]弟の手前、自分の気持ちを偽っているだけだ。
[tab]欲しいものは手に入れろよ。
[end]

msg_9:
[tab]これ以上、あんな弟に何を譲ってやる必要がある。
[wait][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]ちょ…ちょっと、[suou]兄！？
[tab]正気に戻んなさいよ！！
[end]

msg_11:
[tab]マーヤ、止めて！！
[wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[tab]………
[wait][clear][end]

msg_13:
[tab]………
[choice(2)]止めて…克哉さん！！
信じるわ…克哉さん…
[end_choice][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]ハッ…！？
[sync][wait][clear][end]

msg_15:
[color(yellow)]シャドウ克哉[color(white)]
[tab]フッ…執着、残したぞ。
[wait][clear][end]

msg_16:
[color(yellow)]克哉[color(white)]
[tab]怪我はないか、[tatsuya]！？
[wait][clear][end]

msg_17:
[color(yellow)][tatsuya][color(white)]
[tab]兄さん…俺は…
[wait][clear][end]

msg_18:
[color(yellow)]克哉[color(white)]
[tab]悪かった…
[tab]確かに奴の言ったように、お前や父さんを
[tab]疎ましく思ったこともあった…
[wait][clear][end]

msg_19:
[color(yellow)]克哉[color(white)]
[tab]だが、これだけは信じてくれ…
[tab]僕がお前を愛しているのは…
[tab]決して役割なんかじゃあない！
[wait][clear][end]

msg_20:
[color(yellow)][tatsuya][color(white)]
[tab]ああ…信じるよ…
[tab]謝るのは…俺の方だ…
[wait][clear][end]

msg_21:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]…教えてやる…
[tab]こいつが言っている事は…
[wait][clear][end]

msg_22:
[color(yellow)]克哉[color(white)]
[tab]半分当たりで半分外れだ！！
[wait][clear][end]

msg_23:
[color(yellow)]克哉[color(white)]
[tab]お前は一つミスを犯した…
[tab]その顔で、僕達兄弟の間を否定したことだ！！
[end]

msg_24:
[tab]目障りだ…消えろ。
[wait][clear][end]

msg_25:
[color(yellow)]シャドウ克哉[color(white)]
[tab]フッ…残念だよ。
[wait][clear][end]

msg_26:
[color(yellow)][tatsuya][color(white)]
[tab]兄さん…俺は…
[wait][clear][end]

msg_27:
[color(yellow)]克哉[color(white)]
[tab]そんな顔をするな…
[tab]お前は、僕の弟なんだぞ…
[wait][clear][end]

msg_28:
[color(yellow)]克哉[color(white)]
[tab]皆にも迷惑をかけたね…もう大丈夫だ。
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]兄さんなら…舞耶姉をずっと守ってくれる…
[tab]これで…安心できる…
[wait][clear][end]

msg_30:
[color(yellow)]パオフゥ[color(white)]
[tab]あのブラコンが、可愛い弟を殺れるわけねぇだろ…
[tab]ったく…見てる方が小恥ずかしいぜ…
[wait][clear][end]

msg_31:
[color(yellow)]克哉[color(white)]
[tab]天野君…その…
[tab]あれは半分当たりで…半分は外れなんだが…
[tab]なんだ…その…
[wait][clear][end]

msg_32:
[color(yellow)]克哉[color(white)]
[tab]ありがとう。君のおかげだよ…
[tab][tatsuya]を…頼む。
[wait][clear][end]

msg_33:
[color(yellow)]克哉[color(white)]
[tab]天野君…その…奴の言った事だが…
[tab]好きとか嫌いとか…そういうのは色々でだね…
[tab]あの…気にしないでくれないか…うん…
[wait][clear][end]

msg_34:
[color(yellow)]うらら[color(white)]
[tab]さあ～どうすんのマーヤ？
[tab]兄か弟か、難しい選択ねぇ～
[wait][clear][end]
