
msg_0:
[color(yellow)]ニャルラトホテプ[color(white)]
[tab]フハハハハハハハハハハッ！！
[tab]お前達は、一つ大きな事を学んだぞ。
[tab]どうにもできない事もあるという、世の理をだ！
[sync][wait][clear][end]

msg_1:
[color(yellow)]ニャルラトホテプ[color(white)]
[tab]私は、お前達全ての人間の影だ。
[tab]人間に昏き心がある限り、私は消せん。
[tab]這い寄る混沌の、最後の試練を受取れ！！
[sync][wait][clear][end]

msg_2:
[color(yellow)]フィレモン[color(white)]
[tab]一つだけ、この現実を変える方法がある…
[tab]それは、諸君があの夏の日の夜、
[tab]出会った事実を消し去る事だ…
[sync][wait][clear][end]

msg_3:
[color(yellow)]フィレモン[color(white)]
[tab]彼奴が紡いだ悪しき因果の糸は、
[tab]全てあの日より始まっている…
[sync][wait][clear][end]

msg_4:
[color(yellow)]フィレモン[color(white)]
[tab]その一点さえ消し去れば、この様な悲劇の起きぬ、
[tab]あの日から別れた、
[tab]別の時間軸と世界が生まれるだろう…
[sync][wait][clear][end]

msg_5:
[color(yellow)]栄吉[color(white)]
[tab]そんなことが…できるのか…？
[sync][wait][clear][end]

msg_6:
[color(yellow)]フィレモン[color(white)]
[tab]元々人の心の中には、
[tab]現実の流れを変える大きな力がある。
[sync][wait][clear][end]

msg_7:
[color(yellow)]フィレモン[color(white)]
[tab]シバルバーや水晶髑髏の幻想に頼らずとも、
[tab]諸君の強い意志と行動こそが、
[tab]唯一現実を変えるエナジーとなるのだ。
[sync][wait][clear][end]

msg_8:
[color(yellow)]フィレモン[color(white)]
[tab]そう…諸君が属する宇宙を生んだ力さえも、
[tab]諸君の心の力と同じもの…
[tab]この普遍的無意識の世界では、それが可能だ。
[sync][wait][clear][end]

msg_9:
[color(yellow)]淳[color(white)]
[tab]全てをリセットしろ…
[tab]そういうことか…？
[tab]僕たちの記憶や思い出…全てと引き換えに…
[sync][wait][clear][end]

msg_10:
[color(yellow)]ギンコ[color(white)]
[tab]みんな…忘れちゃうってこと…！？
[tab]そんなの…そんなのイヤだっ！！
[tab]他に方法はないの！？
[sync][wait][clear][end]

msg_11:
[color(yellow)]フィレモン[color(white)]
[tab]彼奴の力が強いこの世界では、方法はない。
[tab]無意識に、破滅を望む人々の昏き想いが、
[tab]彼奴の力の源だ…
[sync][wait][clear][end]

msg_12:
[color(yellow)]フィレモン[color(white)]
[tab]彼奴を抑えるならば、
[tab]人そのものが変わらなければならない…
[tab]その新たな世界を、君達が創るのだ。
[sync][wait][clear][end]

msg_13:
[color(yellow)]淳[color(white)]
[tab]僕は…絶対忘れない…
[tab]忘れるものか…
[sync][wait][clear][end]

msg_14:
[color(yellow)]栄吉[color(white)]
[tab]あたりめぇだ…
[tab]忘れてたまるかよ…！！
[sync][wait][clear][end]

msg_15:
[color(yellow)]栄吉[color(white)]
[tab]野郎がそこまで仕組んでたってんなら、
[tab]乗ってやろうぜ…
[tab]これ以上思い通りにならねぇって、教えてやる…
[sync][wait][clear][end]

msg_16:
[color(yellow)]ギンコ[color(white)]
[tab]絶対…
[tab]また会えるよね…？
[sync][wait][clear][end]

msg_17:
[color(yellow)]フィレモン[color(white)]
[tab]では、自分があるべき姿を、強く想い描きたまえ。
[tab]意志する力が、諸君を新たな現在へと導くだろう。
[sync][wait][clear][end]

msg_18:
[color(yellow)]ギンコ[color(white)]
[tab]おまじない…
[tab]これできっと、[tatsuya]のこと忘れないよ…
[sync][wait][clear][end]

msg_19:
[color(yellow)]フィレモン[color(white)]
[tab]さて…しばしの別れだ。
[tab]最後に、言っておきたいことはないかね？
[sync][wait][clear][end]

msg_20:
[tab]最後に、言っておきたいことはないかね？
[choice(2)]礼を言う
ぶん殴る
[end_choice][clear][end]

msg_21:
[color(yellow)]フィレモン[color(white)]
[tab]礼には及ばん。
[tab]諸君が運命の不文律を破り、
[tab]お互いを憶えていることを祈ろう…さらばだ。
[sync][wait][clear][end]

msg_22:
[color(yellow)]フィレモン[color(white)]
[tab]私は、全ての人間の意識と無意識の
[tab]狭間に住まう者…
[sync][wait][clear][end]

msg_23:
[color(yellow)]フィレモン[color(white)]
[tab]私は君で、君は私だ…
[tab]いつまでも、君の中で君を見守ろう。
[tab]さらばだ…
[sync][wait][clear][end]
