function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(northwest, 1034, 0, -940);
    objCollisionLink(circle, coll_1, obj_23);
    objVisible(obj_23, false);
    objVisible(obj_24, false);
    objVisible(obj_25, false);
    objVisible(obj_3, false);
    objVisible(obj_11, false);
    objVisible(obj_12, false);
    ref_a = spriteLoad(sprite_27);
    wait(ref_a);
    ref_c = spriteLoad(sprite_2a);
    wait(ref_c);
    ref_e = spriteLoad(sprite_103);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_2e);
    wait(ref_10);
    bitGet(var_0, EBIT_GINKOOKITA);
    bne(var_0, 0, label_1c);
    bitGet(var_0, EBIT_EIKITIOKITA);
    bne(var_0, 0, label_18);
    call(DAREMO_OK);
    b(label_1b);
  label_18:
    bne(var_0, 1, label_1b);
    call(EIKIOKI);
    b(label_1b);
  label_1b:
    b(label_25);
  label_1c:
    bne(var_0, 1, label_25);
    bitGet(var_0, EBIT_EIKITIOKITA);
    bne(var_0, 0, label_21);
    call(GINKO_NO);
    b(label_24);
  label_21:
    bne(var_0, 1, label_24);
    call(MESAEE);
    b(label_24);
  label_24:
    b(label_25);
  label_25:
}

function SOUNDFADE()
{
    sndVolumeFadeTo(sound_3018, 0, 240);
}

function DAREMO_OK()
{
    unitSpawn(npc1, sprite_27, 997, 0, -979, south, none);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc1, animation_6, 1);
    delayClear();
    delayWait(120);
    unitSpawn(npc2, sprite_2e, 1104, 0, -1754, south, none);
    call(JUNSHU);
    delayClear();
    delayWait(60);
    ref_37 = bustupLoad(bustup_10e);
    bustupWait(ref_37);
    ref_39 = bustupAlloc(ref_37, right, rgb(0,0,0));
    bustupFade(ref_39, rgb(128,0,0), 30);
    ref_3b = dialogAlloc();
    ref_3c = msgShow(msg_0);
/***************************************
[color(yellow)]淳[color(white)]
[tab]番長が、こんなところで何を…？
[wait][clear]
***************************************/
    wait(ref_3c);
    dialogFree(ref_3b);
    ref_3f = bustupFade(ref_39, rgb(0,0,0), 10);
    bustupWait(ref_3f);
    bustupFree(ref_39);
    ref_42 = call(EIMOKUD);
    wait(ref_42);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(npc1, animation_6, 1);
    ref_4d = bustupLoad(bustup_118);
    bustupWait(ref_4d);
    ref_4f = bustupAlloc(ref_4d, right, rgb(0,0,0));
    bustupFade(ref_4f, rgb(128,0,0), 30);
    ref_51 = dialogAlloc();
    ref_52 = msgShow(msg_1);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]わかんねぇすよ…
[tab]ただ…ここに、とても大事な思い出を置いてきた
[tab]気がして…
[wait][clear]
***************************************/
    wait(ref_52);
    dialogFree(ref_51);
    ref_55 = bustupFade(ref_4f, rgb(0,0,0), 10);
    bustupWait(ref_55);
    bustupFree(ref_4f);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(npc2, animation_6, 1);
    delayClear();
    delayWait(80);
    ref_5c = call(KUROIDOOO);
    ref_5d = bustupLoad(bustup_10f);
    bustupWait(ref_5d);
    ref_5f = bustupAlloc(ref_5d, right, rgb(0,0,0));
    bustupFade(ref_5f, rgb(128,0,0), 30);
    ref_61 = dialogAlloc();
    ref_62 = msgShow(msg_2);
/***************************************
[color(yellow)]淳[color(white)]
[tab]僕もなんだ…
[wait][clear]
***************************************/
    wait(ref_62);
    dialogFree(ref_61);
    ref_65 = bustupFade(ref_5f, rgb(0,0,0), 10);
    bustupWait(ref_65);
    bustupFree(ref_5f);
    wait(ref_5c);
    delayClear();
    delayWait(60);
    ref_6b = bustupLoad(bustup_111);
    bustupWait(ref_6b);
    ref_6d = bustupAlloc(ref_6b, right, rgb(0,0,0));
    bustupFade(ref_6d, rgb(128,0,0), 30);
    ref_6f = dialogAlloc();
    ref_70 = msgShow(msg_3);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]あんた達もなの…
[wait][clear]
***************************************/
    unitSpawn(npc3, sprite_2a, 986, 0, -1770, south, none);
    wait(ref_70);
    dialogFree(ref_6f);
    ref_74 = bustupFade(ref_6d, rgb(0,0,0), 10);
    bustupWait(ref_74);
    bustupFree(ref_6d);
    call(EIGAGIN);
    call(KUROGINE);
    unitMove(npc3, 1061, -1276, face_south, slow);
    unitWait(npc3);
    delayClear();
    delayWait(80);
    ref_7d = call(MIMAGIN);
    wait(ref_7d);
    unitMove(npc3, 1061, -1101, face_south, slow);
    unitWait(npc3);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc3, animation_6, 1);
    ref_84 = bustupLoad(bustup_112);
    bustupWait(ref_84);
    ref_86 = bustupAlloc(ref_84, right, rgb(0,0,0));
    bustupFade(ref_86, rgb(128,0,0), 30);
    ref_88 = dialogAlloc();
    ref_89 = msgShow(msg_4);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]なんだか…すごく哀しいね…
[wait][clear]
***************************************/
    wait(ref_89);
    dialogFree(ref_88);
    ref_8c = bustupFade(ref_86, rgb(0,0,0), 10);
    bustupWait(ref_8c);
    bustupFree(ref_86);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc3, animation_5, 1);
    delayClear();
    delayWait(30);
    ref_99 = bustupLoad(bustup_118);
    bustupWait(ref_99);
    ref_9b = bustupAlloc(ref_99, right, rgb(0,0,0));
    bustupFade(ref_9b, rgb(128,0,0), 30);
    ref_9d = dialogAlloc();
    ref_9e = msgShow(msg_5);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]そうだな…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_9e);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_9d);
    ref_a3 = bustupFade(ref_9b, rgb(0,0,0), 10);
    bustupWait(ref_a3);
    bustupFree(ref_9b);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_5, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc2, animation_6, 1);
    ref_ac = bustupLoad(bustup_10f);
    bustupWait(ref_ac);
    ref_ae = bustupAlloc(ref_ac, right, rgb(0,0,0));
    bustupFade(ref_ae, rgb(128,0,0), 30);
    ref_b0 = dialogAlloc();
    ref_b1 = msgShow(msg_6);
/***************************************
[color(yellow)]淳[color(white)]
[tab]とっても…哀しいね…
[wait][clear]
***************************************/
    wait(ref_b1);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_b0);
    ref_b5 = bustupFade(ref_ae, rgb(0,0,0), 10);
    bustupWait(ref_b5);
    bustupFree(ref_ae);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc2, animation_5, 1);
    delayClear();
    delayWait(30);
    cameraMoveTo(1034, -740, -940, 360);
    call(SOUNDFADE);
    delayClear();
    delayWait(90);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_df);
}

function EIKIOKI()
{
    unitSpawn(npc1, sprite_27, 997, 0, -979, south, none);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc1, animation_6, 1);
    delayClear();
    delayWait(30);
    ref_d4 = bustupLoad(bustup_118);
    bustupWait(ref_d4);
    ref_d6 = bustupAlloc(ref_d4, right, rgb(0,0,0));
    bustupFade(ref_d6, rgb(128,0,0), 30);
    ref_d8 = dialogAlloc();
    ref_d9 = msgShow(msg_7);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]これで…これでよかったのかよ…！？
[tab]一人だけ…カッコ良すぎるじゃねぇかよ…

***************************************/
    wait(ref_d9);
    ref_db = msgShow(msg_8);
/***************************************
[tab]グッ…[tatsu]よぉ…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_16, 1);
    wait(ref_db);
    dialogFree(ref_d8);
    ref_df = bustupFade(ref_d6, rgb(0,0,0), 10);
    bustupWait(ref_df);
    bustupFree(ref_d6);
    delayClear();
    delayWait(30);
    unitSpawn(npc2, sprite_2e, 1104, 0, -1754, south, none);
    call(JUNSHU);
    delayClear();
    delayWait(60);
    ref_e8 = bustupLoad(bustup_10e);
    bustupWait(ref_e8);
    ref_ea = bustupAlloc(ref_e8, right, rgb(0,0,0));
    bustupFade(ref_ea, rgb(128,0,0), 30);
    ref_ec = dialogAlloc();
    ref_ed = msgShow(msg_9);
/***************************************
[color(yellow)]淳[color(white)]
[tab]どうしたんだい、番長君…？
[tab]君…泣いてるの…？
[sync][wait][clear]
***************************************/
    ref_ee = call(EIGAMAN);
    wait(ref_ee);
    sync();
    wait(ref_ed);
    dialogFree(ref_ec);
    ref_f3 = bustupFade(ref_ea, rgb(0,0,0), 10);
    bustupWait(ref_f3);
    bustupFree(ref_ea);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_29, 1);
    ref_f9 = bustupLoad(bustup_118);
    bustupWait(ref_f9);
    ref_fb = bustupAlloc(ref_f9, right, rgb(0,0,0));
    bustupFade(ref_fb, rgb(128,0,0), 30);
    ref_fd = dialogAlloc();
    ref_fe = msgShow(msg_10);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]な…なんでもねぇ…
[tab]ただ…ここに忘れもんしてよ…

***************************************/
    wait(ref_fe);
    ref_100 = msgShow(msg_11);
/***************************************
[tab]ジュ…先輩は…何しに来たんすか…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(npc1, animation_2, 1);
    sync();
    wait(ref_100);
    dialogFree(ref_fd);
    ref_108 = bustupFade(ref_fb, rgb(0,0,0), 10);
    bustupWait(ref_108);
    bustupFree(ref_fb);
    unitAnimationPlay(npc2, animation_6, 1);
    delayClear();
    delayWait(30);
    ref_10e = call(KUROIDOOO);
    ref_10f = bustupLoad(bustup_10f);
    bustupWait(ref_10f);
    ref_111 = bustupAlloc(ref_10f, right, rgb(0,0,0));
    bustupFade(ref_111, rgb(128,0,0), 30);
    ref_113 = dialogAlloc();
    ref_114 = msgShow(msg_12);
/***************************************
[color(yellow)]淳[color(white)]
[tab]僕もなんだ…
[tab]ここに、大切なものを忘れた気がして…
[wait][clear]
***************************************/
    wait(ref_114);
    dialogFree(ref_113);
    ref_117 = bustupFade(ref_111, rgb(0,0,0), 10);
    bustupWait(ref_117);
    bustupFree(ref_111);
    wait(ref_10e);
    delayClear();
    delayWait(60);
    ref_11d = bustupLoad(bustup_111);
    bustupWait(ref_11d);
    ref_11f = bustupAlloc(ref_11d, right, rgb(0,0,0));
    bustupFade(ref_11f, rgb(128,0,0), 30);
    ref_121 = dialogAlloc();
    ref_122 = msgShow(msg_13);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]あんた達もなの…
[sync][wait][clear]
***************************************/
    unitSpawn(npc3, sprite_2a, 986, 0, -1770, south, none);
    sync();
    wait(ref_122);
    dialogFree(ref_121);
    ref_127 = bustupFade(ref_11f, rgb(0,0,0), 10);
    bustupWait(ref_127);
    bustupFree(ref_11f);
    unitFace(npc1, west);
    unitAnimationPlay(npc1, animation_3, 1);
    call(KUROGINE);
    unitMove(npc3, 1061, -1276, face_south, slow);
    unitWait(npc3);
    delayClear();
    delayWait(80);
    ref_131 = call(MIMAGIN);
    wait(ref_131);
    unitMove(npc3, 1061, -1101, face_south, slow);
    unitWait(npc3);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc3, animation_6, 1);
    ref_138 = bustupLoad(bustup_112);
    bustupWait(ref_138);
    ref_13a = bustupAlloc(ref_138, right, rgb(0,0,0));
    bustupFade(ref_13a, rgb(128,0,0), 30);
    ref_13c = dialogAlloc();
    ref_13d = msgShow(msg_14);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]なんだか…すごく哀しいね…
[wait][clear]
***************************************/
    wait(ref_13d);
    dialogFree(ref_13c);
    ref_140 = bustupFade(ref_13a, rgb(0,0,0), 10);
    bustupWait(ref_140);
    bustupFree(ref_13a);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc3, animation_5, 1);
    delayClear();
    delayWait(30);
    ref_149 = bustupLoad(bustup_118);
    bustupWait(ref_149);
    ref_14b = bustupAlloc(ref_149, right, rgb(0,0,0));
    bustupFade(ref_14b, rgb(128,0,0), 30);
    ref_14d = dialogAlloc();
    ref_14e = msgShow(msg_15);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]そう…だな…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_14e);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_14d);
    ref_153 = bustupFade(ref_14b, rgb(0,0,0), 10);
    bustupWait(ref_153);
    bustupFree(ref_14b);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_5, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc2, animation_6, 1);
    ref_15c = bustupLoad(bustup_10f);
    bustupWait(ref_15c);
    ref_15e = bustupAlloc(ref_15c, right, rgb(0,0,0));
    bustupFade(ref_15e, rgb(128,0,0), 30);
    ref_160 = dialogAlloc();
    ref_161 = msgShow(msg_16);
/***************************************
[color(yellow)]淳[color(white)]
[tab]とっても…哀しいね…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_161);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_160);
    ref_166 = bustupFade(ref_15e, rgb(0,0,0), 10);
    bustupWait(ref_166);
    bustupFree(ref_15e);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc2, animation_5, 1);
    delayClear();
    delayWait(120);
    ref_16e = bustupLoad(bustup_118);
    bustupWait(ref_16e);
    ref_170 = bustupAlloc(ref_16e, right, rgb(0,0,0));
    bustupFade(ref_170, rgb(128,0,0), 30);
    ref_172 = dialogAlloc();
    ref_173 = msgShow(msg_17);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab][tatsu]…こいつらは俺が守る…
[tab]だから…だから…安心…してくれ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_173);
    dialogFree(ref_172);
    ref_177 = bustupFade(ref_170, rgb(0,0,0), 10);
    bustupWait(ref_177);
    bustupFree(ref_170);
    cameraMoveTo(1034, -740, -940, 360);
    call(SOUNDFADE);
    delayClear();
    delayWait(80);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_df);
}

function GINKO_NO()
{
    unitSpawn3d(npc3, sprite_103, 955, -20, -883, north, none);
    unitAnimationPlay(npc3, animation_6, 1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_18f = bustupLoad(bustup_112);
    bustupWait(ref_18f);
    ref_191 = bustupAlloc(ref_18f, right, rgb(0,0,0));
    bustupFade(ref_191, rgb(128,0,0), 30);
    ref_193 = dialogAlloc();
    ref_194 = msgShow(msg_18);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]ヒク…[tatsuya]…
[tab]ほんとに…これでよかったの…？
[tab]一人だけ…カッコ良すぎるよ…
[wait][clear]
***************************************/
    wait(ref_194);
    dialogFree(ref_193);
    ref_197 = bustupFade(ref_191, rgb(0,0,0), 10);
    bustupWait(ref_197);
    bustupFree(ref_191);
    delayClear();
    delayWait(60);
    unitSpawn(npc2, sprite_2e, 1104, 0, -1754, south, none);
    call(JUNSHU);
    delayClear();
    delayWait(60);
    ref_1a0 = bustupLoad(bustup_10e);
    bustupWait(ref_1a0);
    ref_1a2 = bustupAlloc(ref_1a0, right, rgb(0,0,0));
    bustupFade(ref_1a2, rgb(128,0,0), 30);
    ref_1a4 = dialogAlloc();
    ref_1a5 = msgShow(msg_19);
/***************************************
[color(yellow)]淳[color(white)]
[tab]どうしたんだい、君…？
[tab]君…泣いてるの…？
[wait][clear]
***************************************/
    wait(ref_1a5);
    dialogFree(ref_1a4);
    ref_1a8 = bustupFade(ref_1a2, rgb(0,0,0), 10);
    bustupWait(ref_1a8);
    bustupFree(ref_1a2);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc3, animation_5, 1);
    delayClear();
    delayWait(30);
    ref_1b1 = bustupLoad(bustup_112);
    bustupWait(ref_1b1);
    ref_1b3 = bustupAlloc(ref_1b1, right, rgb(0,0,0));
    bustupFade(ref_1b3, rgb(128,0,0), 30);
    ref_1b5 = dialogAlloc();
    ref_1b6 = msgShow(msg_20);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]な…なんでもないよ…
[tab]ただ…ここに忘れ物しただけ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1b6);
    dialogFree(ref_1b5);
    ref_1ba = bustupFade(ref_1b3, rgb(0,0,0), 10);
    bustupWait(ref_1ba);
    bustupFree(ref_1b3);
    delayClear();
    delayWait(30);
    ref_1bf = call(KUROIDOOO);
    ref_1c0 = bustupLoad(bustup_10f);
    bustupWait(ref_1c0);
    ref_1c2 = bustupAlloc(ref_1c0, right, rgb(0,0,0));
    bustupFade(ref_1c2, rgb(128,0,0), 30);
    ref_1c4 = dialogAlloc();
    ref_1c5 = msgShow(msg_21);
/***************************************
[color(yellow)]淳[color(white)]
[tab]僕もなんだ…
[tab]ここに、大切なものを忘れた気がして…
[wait][clear]
***************************************/
    wait(ref_1c5);
    dialogFree(ref_1c4);
    ref_1c8 = bustupFade(ref_1c2, rgb(0,0,0), 10);
    bustupWait(ref_1c8);
    bustupFree(ref_1c2);
    wait(ref_1bf);
    delayClear();
    delayWait(60);
    ref_1ce = bustupLoad(bustup_116);
    bustupWait(ref_1ce);
    ref_1d0 = bustupAlloc(ref_1ce, right, rgb(0,0,0));
    bustupFade(ref_1d0, rgb(128,0,0), 30);
    ref_1d2 = dialogAlloc();
    ref_1d3 = msgShow(msg_22);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]お前らもなのか…
[sync][wait][clear]
***************************************/
    unitSpawn(npc1, sprite_27, 986, 0, -1770, south, none);
    sync();
    wait(ref_1d3);
    dialogFree(ref_1d2);
    ref_1d8 = bustupFade(ref_1d0, rgb(0,0,0), 10);
    bustupWait(ref_1d8);
    bustupFree(ref_1d0);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationPlay(npc3, animation_1, 1);
    unitMove(npc1, 1055, -1391, face_south, slow);
    unitWait(npc1);
    delayClear();
    delayWait(60);
    ref_1e2 = call(MIMAWA_EIKI);
    wait(ref_1e2);
    unitMove(npc1, 1027, -1052, face_south, slow);
    ref_1e5 = bustupLoad(bustup_118);
    bustupWait(ref_1e5);
    ref_1e7 = bustupAlloc(ref_1e5, right, rgb(0,0,0));
    bustupFade(ref_1e7, rgb(128,0,0), 30);
    ref_1e9 = dialogAlloc();
    ref_1ea = msgShow(msg_23);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]なんだか…凄ぇ哀しいな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1ea);
    dialogFree(ref_1e9);
    ref_1ee = bustupFade(ref_1e7, rgb(0,0,0), 10);
    bustupWait(ref_1ee);
    bustupFree(ref_1e7);
    unitWait(npc1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_5, 1);
    unitAnimationPlay(npc2, animation_6, 1);
    delayClear();
    delayWait(30);
    ref_1f8 = bustupLoad(bustup_10f);
    bustupWait(ref_1f8);
    ref_1fa = bustupAlloc(ref_1f8, right, rgb(0,0,0));
    bustupFade(ref_1fa, rgb(128,0,0), 30);
    ref_1fc = dialogAlloc();
    ref_1fd = msgShow(msg_24);
/***************************************
[color(yellow)]淳[color(white)]
[tab]そうだね…哀しいね…
[wait][clear]
***************************************/
    wait(ref_1fd);
    dialogFree(ref_1fc);
    ref_200 = bustupFade(ref_1fa, rgb(0,0,0), 10);
    bustupWait(ref_200);
    bustupFree(ref_1fa);
    unitAnimationPlay(npc2, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_5, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_5, 1);
    delayClear();
    delayWait(30);
    ref_20f = bustupLoad(bustup_112);
    bustupWait(ref_20f);
    ref_211 = bustupAlloc(ref_20f, right, rgb(0,0,0));
    bustupFade(ref_211, rgb(128,0,0), 30);
    ref_213 = dialogAlloc();
    ref_214 = msgShow(msg_25);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]ヒグッ…！
[tab]私…頑張るから…！
[tab]泣いたり…しないから…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_214);
    dialogFree(ref_213);
    ref_218 = bustupFade(ref_211, rgb(0,0,0), 10);
    bustupWait(ref_218);
    bustupFree(ref_211);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_4, 1);
    delayClear();
    delayWait(60);
    cameraMoveTo(1034, -740, -940, 360);
    call(SOUNDFADE);
    delayClear();
    delayWait(80);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_df);
}

function MESAEE()
{
    unitSpawn(npc1, sprite_27, 999, 0, -1063, south, none);
    unitAnimationPlay(npc1, animation_16, 1);
    unitSpawn3d(npc3, sprite_103, 955, -20, -883, north, none);
    unitAnimationPlay(npc3, animation_6, 1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_238 = bustupLoad(bustup_118);
    bustupWait(ref_238);
    ref_23a = bustupAlloc(ref_238, right, rgb(0,0,0));
    bustupFade(ref_23a, rgb(128,0,0), 30);
    ref_23c = dialogAlloc();
    ref_23d = msgShow(msg_26);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]これで…これでよかったのかよ…！？
[tab]グッ…[tatsu]よぉ…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_2e, 1);
    wait(ref_23d);
    unitAnimationPlay(npc1, animation_6, 1);
    dialogFree(ref_23c);
    ref_242 = bustupFade(ref_23a, rgb(0,0,0), 10);
    bustupWait(ref_242);
    bustupFree(ref_23a);
    ref_245 = bustupLoad(bustup_112);
    bustupWait(ref_245);
    ref_247 = bustupAlloc(ref_245, right, rgb(0,0,0));
    bustupFade(ref_247, rgb(128,0,0), 30);
    ref_249 = dialogAlloc();
    ref_24a = msgShow(msg_27);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]ヒク…[tatsuya]…
[tab]一人だけ…カッコ良すぎるよ…
[wait][clear]
***************************************/
    wait(ref_24a);
    dialogFree(ref_249);
    ref_24d = bustupFade(ref_247, rgb(0,0,0), 10);
    bustupWait(ref_24d);
    bustupFree(ref_247);
    unitSpawn(npc2, sprite_2e, 1104, 0, -1754, south, none);
    ref_251 = call(KUROMUVE);
    delayClear();
    delayWait(60);
    ref_254 = bustupLoad(bustup_10e);
    bustupWait(ref_254);
    ref_256 = bustupAlloc(ref_254, right, rgb(0,0,0));
    bustupFade(ref_256, rgb(128,0,0), 30);
    ref_258 = dialogAlloc();
    ref_259 = msgShow(msg_28);
/***************************************
[color(yellow)]淳[color(white)]
[tab]どうしたんだい、君たち…？
[tab]泣いてるの…？
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_5, 1);
    unitAnimationPlay(npc1, animation_0, 1);
    sync();
    wait(ref_259);
    dialogFree(ref_258);
    ref_25f = bustupFade(ref_256, rgb(0,0,0), 10);
    bustupWait(ref_25f);
    bustupFree(ref_256);
    wait(ref_251);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_3, 1);
    unitAnimationPlay(npc1, animation_29, 1);
    unitWait(npc1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_2, 1);
    delayClear();
    delayWait(30);
    ref_271 = bustupLoad(bustup_118);
    bustupWait(ref_271);
    ref_273 = bustupAlloc(ref_271, right, rgb(0,0,0));
    bustupFade(ref_273, rgb(128,0,0), 30);
    ref_275 = dialogAlloc();
    ref_276 = msgShow(msg_29);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]な…なんでもねぇ…
[tab]ただ…ここに忘れもんしてよ…
[tab]ジュ…先輩は…何しに来たんすか…
[wait][clear]
***************************************/
    wait(ref_276);
    dialogFree(ref_275);
    ref_279 = bustupFade(ref_273, rgb(0,0,0), 10);
    bustupWait(ref_279);
    bustupFree(ref_273);
    ref_27c = call(KUROIDOOO);
    ref_27d = bustupLoad(bustup_10f);
    bustupWait(ref_27d);
    ref_27f = bustupAlloc(ref_27d, right, rgb(0,0,0));
    bustupFade(ref_27f, rgb(128,0,0), 30);
    ref_281 = dialogAlloc();
    ref_282 = msgShow(msg_30);
/***************************************
[color(yellow)]淳[color(white)]
[tab]僕もなんだ…
[tab]ここに、大切なものを忘れた気がして…
[wait][clear]
***************************************/
    wait(ref_282);
    dialogFree(ref_281);
    ref_285 = bustupFade(ref_27f, rgb(0,0,0), 10);
    bustupWait(ref_285);
    bustupFree(ref_27f);
    wait(ref_27c);
    delayClear();
    delayWait(60);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    delayClear();
    delayWait(30);
    ref_28f = call(KUROMIRU01);
    wait(ref_28f);
    unitAnimationPlay(npc2, animation_6, 1);
    ref_292 = bustupLoad(bustup_10f);
    bustupWait(ref_292);
    ref_294 = bustupAlloc(ref_292, right, rgb(0,0,0));
    bustupFade(ref_294, rgb(128,0,0), 30);
    ref_296 = dialogAlloc();
    ref_297 = msgShow(msg_31);
/***************************************
[color(yellow)]淳[color(white)]
[tab]なんだか…とっても哀しいね…
[wait][clear]
***************************************/
    wait(ref_297);
    dialogFree(ref_296);
    ref_29a = bustupFade(ref_294, rgb(0,0,0), 10);
    bustupWait(ref_29a);
    bustupFree(ref_294);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc2, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_5, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc1, animation_6, 1);
    delayClear();
    delayWait(20);
    ref_2ae = bustupLoad(bustup_118);
    bustupWait(ref_2ae);
    ref_2b0 = bustupAlloc(ref_2ae, right, rgb(0,0,0));
    bustupFade(ref_2b0, rgb(128,0,0), 30);
    ref_2b2 = dialogAlloc();
    ref_2b3 = msgShow(msg_32);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]そ…そうだな…
[tab]グッ…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_16, 1);
    wait(ref_2b3);
    dialogFree(ref_2b2);
    ref_2b7 = bustupFade(ref_2b0, rgb(0,0,0), 10);
    bustupWait(ref_2b7);
    bustupFree(ref_2b0);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_5, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_5, 1);
    delayClear();
    delayWait(20);
    ref_2c6 = bustupLoad(bustup_112);
    bustupWait(ref_2c6);
    ref_2c8 = bustupAlloc(ref_2c6, right, rgb(0,0,0));
    bustupFade(ref_2c8, rgb(128,0,0), 30);
    ref_2ca = dialogAlloc();
    ref_2cb = msgShow(msg_33);
/***************************************
[color(yellow)]リサ[color(white)]
[tab]ヒグッ…！
[tab]私…頑張るから…！
[tab]泣いたり…しないから…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_2cb);
    dialogFree(ref_2ca);
    ref_2cf = bustupFade(ref_2c8, rgb(0,0,0), 10);
    bustupWait(ref_2cf);
    bustupFree(ref_2c8);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_4, 1);
    delayClear();
    delayWait(60);
    cameraMoveTo(1034, -740, -940, 360);
    call(SOUNDFADE);
    delayClear();
    delayWait(80);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventLoad(event_df);
}

function KUROMIRU01()
{
    unitAnimationPlay(npc2, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_2, 1);
    delayClear();
    delayWait(80);
    unitAnimationPlay(npc2, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_4, 1);
    delayClear();
    delayWait(80);
    unitAnimationPlay(npc2, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc2, animation_0, 1);
    delayClear();
    delayWait(60);
}

function KUROMUVE()
{
    unitMove(npc2, 1099, -1178, face_south, slow);
    unitWait(npc2);
}

function MIMAWA_EIKI()
{
    unitAnimationPlay(npc1, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_4, 1);
    delayClear();
    delayWait(80);
    unitAnimationPlay(npc1, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_2, 1);
    delayClear();
    delayWait(80);
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(60);
}

function EIGAMAN()
{
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(npc1, animation_6, 1);
}

function KUROGINE()
{
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
}

function EIGAGIN()
{
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc1, animation_2, 1);
}

function KUROIDOOO()
{
    unitMove(npc2, 1098, -932, face_south, slow);
    unitWait(npc2);
    unitAnimationPlay(npc2, animation_12, 1);
    unitWait(npc2);
    unitFace_2(npc2, north);
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationHold(npc2, animation_11, -1);
}

function EIMOKUD()
{
    unitAnimationPlay(npc1, animation_1, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc1, animation_2, 1);
}

function JUNSHU()
{
    unitMove(npc2, 1109, -1158, face_south, slow);
    unitWait(npc2);
    unitAnimationPlay(npc2, animation_3, 1);
}

function MIMAGIN()
{
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_2, 1);
    delayClear();
    delayWait(80);
    unitAnimationPlay(npc3, animation_1, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(8);
    unitAnimationPlay(npc3, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_4, 1);
    delayClear();
    delayWait(80);
    unitAnimationPlay(npc3, animation_3, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(40);
}
