function START()
{
    sndMusicPlay(sound_3004, 127);
    cameraSet(north, 1000, 0, 1000);
    ref_2 = evtbgLoad(evtbg_9);
    wait(ref_2);
    evtbgInit(evtbg_handle_9, evtbg_9, 0, 0, rgb(0,0,0), true);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_d = evtbgFade(evtbg_handle_9, rgb(128,128,128), 1, false);
    wait(ref_d);
    delayClear();
    delayWait(120);
    ref_11 = dialogAlloc();
    ref_12 = msgShow(msg_0);
/***************************************
またこの夢だ…[tab]私はうんざりした。
最近、仕事が終わってからずっと
５０１号のことを調べ回っていたので、
ろくに寝ていなかったからだろう。
[wait][clear]
***************************************/
    wait(ref_12);
    ref_14 = msgShow(msg_1);
/***************************************
ＶＩＰフロアの入り口脇の壁に背中を預け、
私は立ったまま夢と現の狭間を彷徨っていた。
[wait][clear]
***************************************/
    wait(ref_14);
    ref_16 = msgShow(msg_2);
/***************************************
柱に囲まれた円形の部屋を、金色の蝶々が舞っている。
飛び方はいつもより弱弱しかったが、この先どうなるかは
知っていた。
[wait][clear]
***************************************/
    wait(ref_16);
    ref_18 = msgShow(msg_3);
/***************************************
どうせ、蝶が仮面をつけた人間になり、いつも通り
私の名を尋ねてくるだけだ。
昔、弟にせがまれて変な呪いをしてから何度も見ている。
[wait][clear]
***************************************/
    wait(ref_18);
    ref_1a = msgShow(msg_4);
/***************************************
案の定、蝶が消え仮面の人が現れた。
変わった点といえば、男とも女ともつかない声が
聞き取りづらくなり、姿が薄くなっていた。
向こう側が透けて見える。
[wait][clear]
***************************************/
    wait(ref_1a);
    ref_1c = msgShow(msg_5);
/***************************************
そういえば、柱の間もいつもより
赤味がかってぼんやりしていた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1c);
    dialogFree(ref_11);
    ref_20 = bustupLoad(bustup_12b);
    bustupWait(ref_20);
    ref_22 = bustupAlloc(ref_20, right, rgb(0,0,0));
    bustupFade(ref_22, rgb(128,0,0), 30);
    ref_24 = dialogAlloc();
    ref_25 = msgShow(msg_6);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]何度聞かれても、あんたには教えない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_25);
    dialogFree(ref_24);
    ref_29 = bustupFade(ref_22, rgb(0,0,0), 10);
    bustupWait(ref_29);
    bustupFree(ref_22);
    ref_2c = dialogAlloc();
    ref_2d = msgShow(msg_7);
/***************************************
どうせ本当のことを言っても、誰も信じやしない。
私は見たのだ。
弟を解体していたあいつを。
[wait][clear]
***************************************/
    wait(ref_2d);
    ref_2f = msgShow(msg_8);
/***************************************
私が知りたいのは、あいつの名前だ。
私の名が知りたければ、先にあいつの名前を教えろ。
[wait][clear]
***************************************/
    wait(ref_2f);
    ref_31 = msgShow(msg_9);
/***************************************
いや、大人になった今は違う。
知りたいのは、ＪＯＫＥＲがあいつ…
須藤[tab]竜也だという噂の真偽だ。
[wait][clear]
***************************************/
    wait(ref_31);
    ref_33 = msgShow(msg_10);
/***************************************
とうとう捕まることのなかった１０年前の連続殺人鬼。
その犯人が、現職外務大臣須藤[tab]竜蔵の息子、
須藤[tab]竜也だったということは、自分が警官となることで
突き止めた。だが証拠がない。
[wait][clear]
***************************************/
    wait(ref_33);
    ref_35 = msgShow(msg_11);
/***************************************
ならば、ＪＯＫＥＲが街で噂される通り
１０年前の犯人と同一人物であることを証明し、
居場所を突き止めるまでだ。
[wait][clear]
***************************************/
    wait(ref_35);
    ref_37 = msgShow(msg_12);
/***************************************
ここまでくるのに、１０年かかった。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_37);
    dialogFree(ref_2c);
    delayClear();
    delayWait(30);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_45 = sndStop(sound_3004);
    delayClear();
    delayWait(180);
    wait(ref_45);
    sndMusicPlay(sound_3316, 127);
    ref_4a = dialogAlloc();
    ref_4b = msgShow(msg_13);
/***************************************
夢と記憶がごちゃ混ぜになっていた。
ドアの鍵が解かれ、ノブが回る音がした。
私はバックサイドホルスターからＰ２３０ＪＰを抜き、
撃鉄を起こしてマニュアルセイフティを解除した。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4b);
    dialogFree(ref_4a);
    sndMusicPlay(sound_30c1, 127);
    ref_50 = dialogAlloc();
    ref_51 = msgShow(msg_14);
/***************************************
この方が、ただセイフティを解除してダブルアクションで
撃つより、引き金は軽くて済む。
５０１号の捜査本部ができてから、拳銃携帯命令は
協力する所轄の少年課にも発令済みだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_51);
    dialogFree(ref_50);
    eventFileLoad(E, 238);
}
