function START()
{
    bitClear(bit_c6d);
    bitClear(bit_c6e);
    bitClear(bit_c6f);
    bitClear(bit_c70);
    sndMusicPlay(sound_403b, 127);
    cameraSet(north, 1000, 0, 1000);
    msgLocSet(25, 110);
    ref_7 = msgShow(msg_0);
/***************************************
[tab][tab]ペルソナ２[tab]孤影[tab]～Ｌｏｎｅ[tab]ｓｈａｄｏｗ～[tab][tab]

***************************************/
    wait(ref_7);
    delayClear();
    delayWait(180);
    msgShow(msg_1);
/***************************************
[clear]
***************************************/
    msgLocSet(30, 110);
    ref_d = msgShow(msg_2);
/***************************************
[tab][tab][tab][tab][tab]○○月１３日[tab]ＰＭ：１６時４７分[tab][tab][tab][tab][tab]
[tab][tab][tab][tab][tab][tab]ルナパレス港南[tab]宮代[tab]詩織宅[tab][tab][tab][tab][tab][tab]

***************************************/
    wait(ref_d);
    delayClear();
    delayWait(180);
    msgShow(msg_3);
/***************************************
[clear]
***************************************/
    msgLocDefault();
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_1b = bustupLoad(bustup_12a);
    bustupWait(ref_1b);
    ref_1d = bustupAlloc(ref_1b, right, rgb(0,0,0));
    bustupFade(ref_1d, rgb(128,0,0), 30);
    ref_1f = dialogAlloc();
    ref_20 = msgShow(msg_4);
/***************************************
[color(yellow)]綺麗な女性[color(white)]
[tab]どうぞ、入って[tatsuya]君。
[tab]隣の部屋空いてるから、好きに使って。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_20);
    dialogFree(ref_1f);
    ref_24 = bustupFade(ref_1d, rgb(0,0,0), 10);
    bustupWait(ref_24);
    bustupFree(ref_1d);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_30da, 127);
    delayClear();
    delayWait(120);
    ref_2c = evtbgLoad(evtbg_d);
    wait(ref_2c);
    evtbgInit(evtbg_handle_d, evtbg_d, 0, 0, rgb(0,0,0), true);
    ref_2f = evtbgFade(evtbg_handle_d, rgb(128,128,128), 1, false);
    wait(ref_2f);
    delayClear();
    delayWait(120);
    ref_33 = bustupLoad(bustup_12a);
    bustupWait(ref_33);
    ref_35 = bustupAlloc(ref_33, right, rgb(0,0,0));
    bustupFade(ref_35, rgb(128,0,0), 30);
    ref_37 = dialogAlloc();
    ref_38 = msgShow(msg_5);
/***************************************
[color(yellow)]綺麗な女性[color(white)]
[tab]去年まで独身寮にいたんだけどね。
[tab]プライバシーなんてないようなもんだから、
[tab]奮発してここ借りたの。
[wait][clear]
***************************************/
    wait(ref_38);
    ref_3a = msgShow(msg_6);
/***************************************
[color(yellow)]綺麗な女性[color(white)]
[tab]一人暮らしにはちょっと大きな家だから、
[tab]君が来てくれて丁度良かったわ。
[tab]ほら、職場に近くて空いてる部屋、ここしかなくって。
[wait][clear]
***************************************/
    wait(ref_3a);
    ref_3c = msgShow(msg_7);
/***************************************
[color(yellow)]綺麗な女性[color(white)]
[tab]えっと、後でリビングのソファ、君の部屋に運ぶわね。
[tab]ベッドの方がいい？
[tab]あ、テレビ見たかったらいつでもこの部屋使って。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_3c);
    dialogFree(ref_37);
    ref_40 = bustupFade(ref_35, rgb(0,0,0), 10);
    bustupWait(ref_40);
    bustupFree(ref_35);
    ref_43 = bustupLoad(bustup_10);
    bustupWait(ref_43);
    ref_45 = bustupAlloc(ref_43, left, rgb(0,0,0));
    bustupFade(ref_45, rgb(128,0,0), 30);
    ref_47 = dialogAlloc();
    ref_48 = msgShow(msg_8);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]………
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_48);
    dialogFree(ref_47);
    ref_4c = bustupFade(ref_45, rgb(0,0,0), 10);
    bustupWait(ref_4c);
    bustupFree(ref_45);
    ref_4f = dialogAlloc();
    ref_50 = msgShow(msg_9);
/***************************************
[tab]私は彼を自宅に招き入れると、
[tab]脱ぎ散らかしたままの服や、床に散乱した
[tab]それほど数があるわけでもない化粧品を
[tab]拾い集めながら、努めて明るい声で喋り続けた。

[wait][clear]
***************************************/
    wait(ref_50);
    ref_52 = msgShow(msg_10);
/***************************************
[tab]少し声が上ずっていたかもしれない。
[tab]私に気を遣っているのか、身の置き場に困っているのか、
[tab]彼は押し黙ったまま部屋を見ないよう窓辺に佇んでいた。
[wait][clear]
***************************************/
    wait(ref_52);
    ref_54 = msgShow(msg_11);
/***************************************
[tab]代わりに、床に刻まれた長い影が
[tab]彼の心境を物語っていた。
[tab]戸惑い、拒絶、そして、孤独覧覧
[wait][clear]
***************************************/
    wait(ref_54);
    ref_56 = msgShow(msg_12);
/***************************************
[tab]これから先もずっとそうやって独りで何かをやり、
[tab]日没と共に闇に紛れる影のように
[tab]どこかへ消えていくつもりなのだ。
[wait][clear]
***************************************/
    wait(ref_56);
    ref_58 = msgShow(msg_13);
/***************************************
[tab]そうはさせない。
[wait][clear]
***************************************/
    wait(ref_58);
    ref_5a = msgShow(msg_14);
/***************************************
[tab]こちらにも１０年待った事情がある。
[tab]そう、これは彼だけの物語ではない。
[tab]私と彼の物語だ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5a);
    dialogFree(ref_4f);
    delayClear();
    delayWait(30);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    sndVolumeFadeOff(sound_3010, 60);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    eventFileLoad(E, 230);
}
