
msg_0:
[tab][tab]ペルソナ２[tab]孤影[tab]～Ｌｏｎｅ[tab]ｓｈａｄｏｗ～[tab][tab]
[end]

msg_1:
[clear][end]

msg_2:
[tab][tab][tab][tab][tab]○○月１３日[tab]ＰＭ：１６時４７分[tab][tab][tab][tab][tab]
[tab][tab][tab][tab][tab][tab]ルナパレス港南[tab]宮代[tab]詩織宅[tab][tab][tab][tab][tab][tab]
[end]

msg_3:
[clear][end]

msg_4:
[color(yellow)]綺麗な女性[color(white)]
[tab]どうぞ、入って[tatsuya]君。
[tab]隣の部屋空いてるから、好きに使って。
[sync][wait][clear][end]

msg_5:
[color(yellow)]綺麗な女性[color(white)]
[tab]去年まで独身寮にいたんだけどね。
[tab]プライバシーなんてないようなもんだから、
[tab]奮発してここ借りたの。
[wait][clear][end]

msg_6:
[color(yellow)]綺麗な女性[color(white)]
[tab]一人暮らしにはちょっと大きな家だから、
[tab]君が来てくれて丁度良かったわ。
[tab]ほら、職場に近くて空いてる部屋、ここしかなくって。
[wait][clear][end]

msg_7:
[color(yellow)]綺麗な女性[color(white)]
[tab]えっと、後でリビングのソファ、君の部屋に運ぶわね。
[tab]ベッドの方がいい？
[tab]あ、テレビ見たかったらいつでもこの部屋使って。
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]………
[sync][wait][clear][end]

msg_9:
[tab]私は彼を自宅に招き入れると、
[tab]脱ぎ散らかしたままの服や、床に散乱した
[tab]それほど数があるわけでもない化粧品を
[tab]拾い集めながら、努めて明るい声で喋り続けた。

[wait][clear][end]

msg_10:
[tab]少し声が上ずっていたかもしれない。
[tab]私に気を遣っているのか、身の置き場に困っているのか、
[tab]彼は押し黙ったまま部屋を見ないよう窓辺に佇んでいた。
[wait][clear][end]

msg_11:
[tab]代わりに、床に刻まれた長い影が
[tab]彼の心境を物語っていた。
[tab]戸惑い、拒絶、そして、孤独覧覧
[wait][clear][end]

msg_12:
[tab]これから先もずっとそうやって独りで何かをやり、
[tab]日没と共に闇に紛れる影のように
[tab]どこかへ消えていくつもりなのだ。
[wait][clear][end]

msg_13:
[tab]そうはさせない。
[wait][clear][end]

msg_14:
[tab]こちらにも１０年待った事情がある。
[tab]そう、これは彼だけの物語ではない。
[tab]私と彼の物語だ。
[sync][wait][clear][end]
