
msg_0:
入り口が静かに開き、照明を落とした
薄暗いダンスフロアに長身の人影が入ってきた。
[wait][clear][end]

msg_1:
手に反った棒状の武器を携行している。
刀のようだ。
５０１号に殺された被害者数人の成傷器痕と一致する。
[sync][wait][clear][end]

msg_2:
[color(yellow)]詩織[color(white)]
[tab]警察です。
[tab]武器を捨てなさい！
[sync][wait][clear][end]

msg_3:
私は影の横から頭に狙いを付けて、
擦れた声を張り上げた。
熱い緑茶が欲しい。
[wait][clear][end]

msg_4:
[color(yellow)]影[color(white)]
[tab]…宮代[tab]詩織、だな。
[sync][wait][clear][end]

msg_5:
[color(yellow)]詩織[color(white)]
[tab]銃で頭を狙ってます。
[tab]武器を捨てて！
[sync][wait][clear][end]

msg_6:
影はわずかの間硬直したように動かなかったが、
観念したのかすぐ凶器を手放した。
私は床に落ちた凶器を蹴り飛ばし、
銃を突きつけたまま喚き続けた。
[sync][wait][clear][end]

msg_7:
[color(yellow)]詩織[color(white)]
[tab]銃刀法違反で現行犯逮捕します！
[tab]手を頭の後ろで組んで、膝を突いて！
[sync][wait][clear][end]

msg_8:
影は頭の後ろで手を組むと、おとなしく膝を突いた。
油断はできない。斬殺されただけでなく、
食い殺されたとしか思えない被害者もいるのだ。
どんな凶器を隠しているかわからない。
[wait][clear][end]

msg_9:
少しでも抵抗のそぶりを見せたら、
迷わず全弾発射するつもりだ。
年間３６発程度しか射撃訓練のできない日本の警官が、
動体目標に命中させるのは難しい。
[wait][clear][end]

msg_10:
まして、薬物やアルコールで痛覚が麻痺してる人間や
凶暴な精神異常者を、完全被甲の３２口径弾一発で
止められるわけがない。
海外では９ミリ弾でさえ威力不足が議論になる。
[wait][clear][end]

msg_11:
勿論、過剰発砲として問題になるだろう。
[wait][clear][end]

msg_12:
実のところ、私は５０１号に死んで欲しかった。
こいつは明らかに狂人だ。
確保しても心神卵失で不起訴、措置入院になり、
下手をすれば数ヶ月も経たず退院させられる。
[wait][clear][end]

msg_13:
何の罪に問われることもなく、娑婆に出てくるのだ。
[wait][clear][end]

msg_14:
この国には、凶悪犯罪を起こした精神障害者に対する
司法制度がない。
措置入院は、あくまで精神障害者を対象としたものだ。
犯罪者としては扱われない。
[wait][clear][end]

msg_15:
故に、自傷他傷の恐れがなくなったと判断されれば、
即刻退院させねばならない。
再犯の恐れを、診察した医師自身が感じていてもだ。
[wait][clear][end]

msg_16:
より拘束力の強い保安処分を導入しようという動きは
何度もあったが、人権保護を掲げる反対派の強い反対に
よって何度も見送られてきた。
[wait][clear][end]

msg_17:
では、犯罪被害者の人権はどうなる？
ある日突然、平凡だが幸せな日常を奪われた被害者と
遺族の人権は？
[wait][clear][end]

msg_18:
加害者は正常な精神状態ではありませんでした。
責任能力がありません、で納得しろというのか？
[wait][clear][end]

msg_19:
大切な人の命と未来は理不尽に奪われ、
奪った本人は人権の名の元に庇護される。
これがこの国の司法の現状だ。
[wait][clear][end]

msg_20:
[color(yellow)]影[color(white)]
[tab]…泣いてるのか？
[sync][wait][clear][end]

msg_21:
[color(yellow)]詩織[color(white)]
[tab]き、緊張すると涙が出る体質なのよ！
[sync][wait][clear][end]

msg_22:
この明るさで私の目元が見えたのか？
何にせよ、大きなお世話だ。
[wait][clear][end]

msg_23:
[color(yellow)]影[color(white)]
[tab]…それ、木刀なんだけど。
[wait][clear][end]

msg_24:
影は顎で床の凶器を指した。
顔を逸らさないように、目だけ動かして確認した。
[wait][clear][end]

msg_25:
木剣がドアから差し込む廊下の明かりで
照らされている。
銃刀法違反には問えない。
[wait][clear][end]

msg_26:
[color(yellow)]影[color(white)]
[tab]…立っていいかな。
[sync][wait][clear][end]

msg_27:
[color(yellow)]詩織[color(white)]
[tab]だ、だめよ。
[tab]凶器準備集合罪の恐れもある。
[tab]名前は！？
[sync][wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab][suou]…[tab][tatsuya]。
[sync][wait][clear][end]

msg_29:
[suou][tab][tatsuya]？
私は手元のリモコンでホールの照明を上げて、
影の顔を確認した。
精粉ではあるが、まだ幼さを残した少年だ。
[wait][clear][end]

msg_30:
１７、８歳くらいだろうか。
[suou]巡査部長に似ている。
この子が、[suou]元刑事の息子？
どうしてここに？[tab]この子がＪＯＫＥＲ？[tab]混乱した。
[sync][wait][clear][end]

msg_31:
[color(yellow)]詩織[color(white)]
[tab]身元を確認できるものは？
[sync][wait][clear][end]

msg_32:
[color(yellow)][tatsuya][color(white)]
[tab]財布に免許証が入ってると思う。
[tab]学校にもバイクで行ってた。
[tab]無免許じゃないはずだ。
[sync][wait][clear][end]

msg_33:
自分のことを他人のように喋る…
おかしな子だ。
[sync][wait][clear][end]

msg_34:
[color(yellow)]詩織[color(white)]
[tab]財布は？
[sync][wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]パンツの後ろ。
[sync][wait][clear][end]

msg_36:
[color(yellow)]詩織[color(white)]
[tab]ゆっくり立って、壁に手をついて。
[tab]足を開いて。
[sync][wait][clear][end]

msg_37:
私は少年が指示に従うと、素早くボディチェックを
済ませた。
他に武器は所持していない。
[wait][clear][end]

msg_38:
財布の中には、普通自動二輪車の免許証があった。
いわゆる中免だ。
[wait][clear][end]

msg_39:
顔写真と名前…
確かに[suou][tab][tatsuya]だ。
[sync][wait][clear][end]

msg_40:
[color(yellow)]詩織[color(white)]
[tab]いいわ、こっちを向いて。
[tab]手は見えるようにしておいて。
[sync][wait][clear][end]

msg_41:
おとなしく従った。
改めて写真と顔を見比べる。
だが写真の中の、斜に構えた人を食ったような
挑戦的な笑みを浮かべる少年とは、やはり何かが違う。
[wait][clear][end]

msg_42:
目だ。なんだろう、この子の目。
吸い込まれそうだ。
子供がこんな目をするのか。
諦観とか諦念とか、何かそんな超然とした…
[sync][wait][clear][end]

msg_43:
[color(yellow)]詩織[color(white)]
[tab]どうして私の名前を？
[tab]電話に出たのは君？
[tab]それとも、お父さんに聞いたの？
[sync][wait][clear][end]

msg_44:
免許証の住所は、確かに突き止めた
[suou]元刑事の自宅のものだった。
この子は間違いなくあの人の子で、
[suou]巡査部長の弟だ。
[sync][wait][clear][end]

msg_45:
[color(yellow)][tatsuya][color(white)]
[tab]親父…？
[tab]下であんたの名刺を見た。
[sync][wait][clear][end]

msg_46:
私が父親を知っていることに驚いたのだろう。
怪訝な顔をした。
[sync][wait][clear][end]

msg_47:
[color(yellow)]詩織[color(white)]
[tab]そう、店の人に追い出してくれって頼まれたの？
[tab]それとも、私を殺しに来た…
[tab]まさか君がＪＯＫＥＲ、なんてことはないわよね？
[sync][wait][clear][end]

msg_48:
[color(yellow)][tatsuya][color(white)]
[tab]店は関係ない。
[tab]吉栄に聞いて忠告に来た。
[tab]このままじゃ、あんたは本当にＪＯＫＥＲに殺される。
[sync][wait][clear][end]

msg_49:
[color(yellow)]詩織[color(white)]
[tab]予告状のこと？
[tab]わかってるなら早く帰りなさい。
[sync][wait][clear][end]

msg_50:
[color(yellow)][tatsuya][color(white)]
[tab]あんたは何もわかってない。
[tab]そんな拳銃で…
[sync][wait][clear][end]

msg_51:
次の瞬間、私は彼の胸の中できょとんとしていた。
拳銃ごと右手を捕まれ抱き寄せられたのだと
理解するまで、数秒かかった。
彼の動きが速過ぎて、時間が飛んだように錯覚したのだ。
[wait][clear][end]

msg_52:
小さな自動拳銃は、少年とは思えない大きな
左手にがっちり握られていた。
[wait][clear][end]

msg_53:
スライドも若干後退している。
これでは、反射的にトリガーを引いても撃発しない。
どこでこんなことを覚えたのだ。
[wait][clear][end]

msg_54:
真っ赤なライダースーツ越しに、
頬に力強い心臓の鼓動が伝わってくる。
見上げると、彼の顔の横の壁に、先ほどまでなかった
果物ナイフか何かの柄が根元まで突き刺さっていた。
[wait][clear][end]

msg_55:
今こうして彼の胸に顔をうずめていなかったら、
あれが私の後頭部を直撃していたのかもしれない。
彼は私の頭を抱いていた右手を離すと、厳しい視線を
店の奥に向けたまま、顔の横のナイフを引き抜いた。
[wait][clear][end]

msg_56:
１０センチほどもある刀身が、全て壁にめり込んでいた。
投擲した者の筋力も凄まじいが、
それを易々と引き抜いたこの子も凄い。
[sync][wait][clear][end]

msg_57:
[color(yellow)][tatsuya][color(white)]
[tab]…いつからそこにいた。
[sync][wait][clear][end]

msg_58:
[color(yellow)]何者かの声[color(white)]
[tab]最初からだよ、バーカ。
[wait][clear][end]

msg_59:
[tatsuya]君の問いかけに、
私の背後から別の男の声が応じた。
距離は結構離れているようだ。
[wait][clear][end]

msg_60:
[color(yellow)]何者かの声[color(white)]
[tab]久しぶりなんだよ、酒。
[tab]ちびちびやりながら、どうやってその女をバラすか
[tab]考えてたのによぉ、邪魔しやがって。
[wait][clear][end]

msg_61:
声の主が、５０１号だ。
この子が来るまで、私は奴と二人で闇の中にいたようだ。
ホールに誰もいないのは来た時に確認した。
一体いつから…[tab]悪寒が背筋を駆け上った。
[wait][clear][end]

msg_62:
怖気を振り払うように身を捻ると、
[tatsuya]君は私を押さえていた手を離した。
すかさず、声の方と彼へ交互に銃を向ける。
[sync][wait][clear][end]

msg_63:
[color(yellow)]詩織[color(white)]
[tab]二人とも動かないで！
[tab]武器を捨てなさい！
[sync][wait][clear][end]

msg_64:
[tatsuya]君は、私など見ていなかった。
私も奥に銃を向け目を凝らした。
[wait][clear][end]

msg_65:
１０年経ってはいるが、面影は変わっていない。
間違いない、この男だ。
陣也の無残な死体の横に立っていた少年…
忘れられない狂気じみた笑み…
[wait][clear][end]

msg_66:
やはり、こいつが５０１号だったのだ。
須藤[tab]竜也…
ようやく見つけた。
[sync][wait][clear][end]

msg_67:
[color(yellow)]須藤[color(white)]
[tab]イヒ…！[tab]はじめてぶりだなぁ、クソガキ。
[tab]てめぇのことも、向こう側のことも、
[tab]全部電波に聞いて知ってるぜぇ。
[sync][wait][clear][end]

msg_68:
須藤はだらしなく足を投げ出し、
フロアの奥のソファに踏ん反り返っていた。
片手にぶら下げたドライジンを、ボトルごと剤っている。
横のバーカウンターからちょろまかしたものだろう。
[wait][clear][end]

msg_69:
たてがみのように伸びきってボサボサの髪に無精髭、
どこかの病院の入院着の上に、肩でコートを
羽織っただけの異様な出で立ちだ。
[wait][clear][end]

msg_70:
棒状の武器を左手で担いでいた。
剥き身の日本刀だ。
こいつは、これだけで現行犯逮捕できる。
[wait][clear][end]

msg_71:
[tatsuya]君は、そんな須藤に怖気づいた風もなく
歩み寄っていった。
いつの間にか私が蹴り飛ばしたはずの木刀を携えている。
[wait][clear][end]

msg_72:
ずっと私の横にいたのに、どうやって拾ったのだ！？
慌てて後を追った。
[sync][wait][clear][end]

msg_73:
[color(yellow)][tatsuya][color(white)]
[tab]お前がこちら側のＪＯＫＥＲか…[tab]須藤[tab]竜也。
[tab]【奴】がやりそうなことだ。
[sync][wait][clear][end]

msg_74:
この二人はお互いを知っている。
だが、須藤ははじめてとも言った。
向こう側とはなんだ？[tab]【奴】とは誰のことだ？
黒い噂の絶えない、須藤[tab]竜蔵のことだろうか。
[sync][wait][clear][end]

msg_75:
[color(yellow)]須藤[color(white)]
[tab]代わりだよ代わり。あの方が目覚めるまでのなぁ。
[tab]本物のＪＯＫＥＲは俺じゃねぇ。
[tab]お前が一番よーく知ってんだろうが。
[sync][wait][clear][end]

msg_76:
[color(yellow)][tatsuya][color(white)]
[tab]…そうだな。
[tab]淳は、お前のように薄汚い殺し屋じゃない。
[wait][clear][end]

msg_77:
[color(yellow)][tatsuya][color(white)]
[tab]お前は須藤[tab]竜也だ。
[tab]ＪＯＫＥＲの代わりなんか、できやしない。
[sync][wait][clear][end]

msg_78:
[color(yellow)]須藤[color(white)]
[tab]ヒャッハ！
[tab]そうか…[tab]そうだな。
[tab]あの方は、こんなむさ苦しい顔しちゃいねぇ。
[wait][clear][end]

msg_79:
[color(yellow)]須藤[color(white)]
[tab]ありがとうよ、クソガキ。
[tab]仮面がいるよな、ＪＯＫＥＲの仮面がよぉ。
[sync][wait][clear][end]

msg_80:
須藤は下卑た忍び笑いをもらすとボトルを剤った。
口から溢れた酒が喉を伝い、血で汚れた入院着を濡らす。
あの方…[tab]ＪＯＫＥＲの代わり…
この二人は一体何を知っているのだろう。
[sync][wait][clear][end]

msg_81:
[color(yellow)][tatsuya][color(white)]
[tab]須藤、今ならまだやり直せる。
[tab]奴の声に耳を貸すな…！
[sync][wait][clear][end]

msg_82:
[color(yellow)]詩織[color(white)]
[tab]やりなおす！？
[tab]なんの話か知らないけど、こいつは１０年前にも
[tab]大勢人を殺してるのよ？[tab]更生なんてできっこない！
[sync][wait][clear][end]

msg_83:
刑事の台詞じゃない。
でも、叫ばずにはいられなかった。
たとえこいつが真人間になっても、陣也は帰ってこない。
[wait][clear][end]

msg_84:
[tatsuya]君は、少し驚いたような顔を
わずかに私に振り向けた。
[sync][wait][clear][end]

msg_85:
[color(yellow)]須藤[color(white)]
[tab]熱力学の第一法則ってやつを知ってるか？
[tab]熱とかエネルギーってのはよぉ、
[tab]他のもんに交換しても全体の量は変わらねぇんだよ。
[wait][clear][end]

msg_86:
[color(yellow)]須藤[color(white)]
[tab]宇宙のエネルギーの量は一定だ。
[tab]形が違うだけなんだよ。
[tab]そう決まってんだ。
[wait][clear][end]

msg_87:
[color(yellow)]須藤[color(white)]
[tab]運命ってやつも同じでな。
[tab]誰かが幸せんなったら、その分他の奴が不幸になる。
[wait][clear][end]

msg_88:
[color(yellow)]須藤[color(white)]
[tab]お前、飯食うだろ。
[tab]食いきれなくなったら捨てるわな？
[wait][clear][end]

msg_89:
[color(yellow)]須藤[color(white)]
[tab]その分、食えねぇで死ぬ奴がいるんだよ。
[tab]世界のどっかにはよぉ。
[wait][clear][end]

msg_90:
[color(yellow)]須藤[color(white)]
[tab]ああ、今ならわかるぜ。
[tab]電波すげーなぁ。電波。
[tab]その女の弟はよ、お前の代わりだよ。
[sync][wait][clear][end]

msg_91:
[color(yellow)][tatsuya][color(white)]
[tab]俺の…[tab]代わり？
[sync][wait][clear][end]

msg_92:
[color(yellow)]須藤[color(white)]
[tab]お前らがあの日の運命を変えて逃げちまったから、
[tab]代わりに俺にバラされたんだ。
[tab]わかるよな？
[sync][wait][clear][end]

msg_93:
[tatsuya]君は目を見開き、
私の顔を見つめながら奴の話を聞いていた。
私も彼から目を離せなかった。
陣也が、この子の代わり…？
[sync][wait][clear][end]

msg_94:
[color(yellow)]須藤[color(white)]
[tab]きてるぜ、電話。
[tab]天野[tab]舞耶を殺してくれってなぁ。
[sync][wait][clear][end]

msg_95:
須藤がそう言った瞬間、[tatsuya]君の身体から
紅い人のような影が吹き上がり、須藤に襲い掛かった。
須藤の身体からも黒い人影が湧き上がる。
[wait][clear][end]

msg_96:
二つの影は、いつの間にか激しい鍔迫り合いを
演じている。
[tatsuya]君と須藤の頭上で、
同じような格好で激突した。
[sync][wait][clear][end]

msg_97:
紅蓮の炎と漆黒の炎が絡み合い、互いを飲み込もうとする
二匹の蛇のようにフロア中で渦巻いた。
カウンターの上に置かれたままのボトルが何本か破裂し、
天板の上を酒臭い炎が走る。
[sync][wait][clear][end]

msg_98:
[color(yellow)]須藤[color(white)]
[tab]これがてめぇの罪が生んだペルソナ、ＪＯＫＥＲだ！
[tab]どうだ、てめぇにそっくりだろうが！
[tab]ヒャーハハハハァァァァァァ！！
[sync][wait][clear][end]

msg_99:
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉に指一本触れてみろ。
[tab]必ず見つけ出して殺してやる。
[tab]何度でも、どこの世界でもだ…！
[sync][wait][clear][end]

msg_100:
[color(yellow)]須藤[color(white)]
[tab]あの女がおっ死んだのは誰のせいだ、ああ？
[tab]向こう側が吹っ飛んだのは、誰のせいだよ！
[sync][wait][clear][end]

msg_101:
[color(yellow)][tatsuya][color(white)]
[tab]黙れ…！
[sync][wait][clear][end]

msg_102:
[color(yellow)]須藤[color(white)]
[tab]みんなてめぇが殺したんだ。
[tab]俺なんか可愛いもんだ。
[wait][clear][end]

msg_103:
[color(yellow)]須藤[color(white)]
[tab]見ろよ、俺のペルソナの嬉しそうな顔をよぉ！
[tab]負け犬！[tab]人殺しぃ！！
[sync][wait][clear][end]

msg_104:
[color(yellow)][tatsuya][color(white)]
[tab]須藤ぉぉぉぉ！
[sync][wait][clear][end]

msg_105:
[color(yellow)]須藤[color(white)]
[tab]そうだ、怒れぇ！
[tab]もっと怒って、てめぇも電波に飲み込まれろ！
[tab]電波だよ電波ぁ！[tab]電電電電波波波ぁぁぁぁ！！
[sync][wait][clear][end]
