function START()
{
    bitClear(bit_c76);
    bitClear(bit_c77);
    bitClear(bit_c78);
    bitClear(bit_c79);
    bitClear(bit_c7a);
    bitClear(IBIT_LV1_KEY);
    bitClear(IBIT_LV2_KEY);
    bitClear(DBIT_KEN_GET_A);
    bitClear(DBIT_KEN_GET_B);
    bitClear(DBIT_KEN_GET_B2);
    bitSet(DBIT_KEN_SHATA);
    bitSet(DBIT_KEN_SHATA2);
    bitSet(DBIT_KEN_SHATA3);
    bitClear(DBIT_KENKYU_A);
    bitSet(DBIT_KENKYU_B);
    bitClear(DBIT_KEN_ELEV);
    sndMusicPlay(sound_4099, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(northwest, 700, 0, -900);
    msgLocSet(20, 110);
    ref_15 = msgShow(msg_0);
/***************************************
[tab][tab][tab][tab]ペルソナ２[tab]孤影[tab]～Ｌｏｎｅ[tab]ｓｈａｄｏｗ～[tab][tab]

***************************************/
    wait(ref_15);
    delayClear();
    delayWait(180);
    msgShow(msg_1);
/***************************************
[clear]
***************************************/
    msgShow(msg_2);
/***************************************
[clear]
***************************************/
    msgLocSet(30, 110);
    ref_1c = msgShow(msg_3);
/***************************************
[tab][tab][tab][tab][tab]○○月０２日[tab]ＰＭ：１３時０８分[tab][tab][tab][tab][tab]
[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab]青葉公園[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab]

***************************************/
    wait(ref_1c);
    delayClear();
    delayWait(180);
    ref_20 = msgShow(msg_4);
/***************************************
[clear]
***************************************/
    wait(ref_20);
    msgLocDefault();
    ref_23 = spriteLoad(sprite_127);
    wait(ref_23);
    ref_25 = spriteLoad(sprite_12a);
    wait(ref_25);
    unitSpawn(unit_71, sprite_127, 750, 0, -800, north, none);
    unitAnimationPlay(unit_71, animation_5, 1);
    unitSpawn(unit_73, sprite_12a, 600, 0, -900, west, none);
    unitAnimationPlay(unit_73, animation_1, 1);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_30ef, 127);
    ref_34 = bustupLoad(bustup_133);
    bustupWait(ref_34);
    ref_36 = bustupAlloc(ref_34, right, rgb(0,0,0));
    bustupFade(ref_36, rgb(128,0,0), 30);
    ref_38 = dialogAlloc();
    ref_39 = msgShow(msg_5);
/***************************************
[color(yellow)]中年のガードマン[color(white)]
[tab]確かに[tatsuya]の声だが…
[tab]信じられん。
[tab]こんな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_39);
    dialogFree(ref_38);
    ref_3d = bustupFade(ref_36, rgb(0,0,0), 10);
    bustupWait(ref_3d);
    bustupFree(ref_36);
    ref_40 = dialogAlloc();
    ref_41 = msgShow(msg_6);
/***************************************
[suou]元刑事は、イヤホンを外すと
頭を振り私を見上げた。
[wait][clear]
***************************************/
    wait(ref_41);
    ref_43 = msgShow(msg_7);
/***************************************
ベンチから腰を浮かし、ボイスレコーダーを
私に返す間も呆然とした顔は変わらない。
当然だ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_43);
    dialogFree(ref_40);
    ref_47 = bustupLoad(bustup_129);
    bustupWait(ref_47);
    ref_49 = bustupAlloc(ref_47, right, rgb(0,0,0));
    bustupFade(ref_49, rgb(128,0,0), 30);
    ref_4b = dialogAlloc();
    ref_4c = msgShow(msg_8);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]私も[tatsuya]君と須藤のペルソナを
[tab]見ていなかったら、信じられなかったと思います。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4c);
    dialogFree(ref_4b);
    ref_50 = bustupFade(ref_49, rgb(0,0,0), 10);
    bustupWait(ref_50);
    bustupFree(ref_49);
    ref_53 = dialogAlloc();
    ref_54 = msgShow(msg_9);
/***************************************
ボイスレコーダーには、[tatsuya]君が話してくれた
向こう側で起きた事、これからこちら側で起きるであろう
事の推測が録音されている。
[wait][clear]
***************************************/
    wait(ref_54);
    ref_56 = msgShow(msg_10);
/***************************************
誰にも話さないとの約束でやっと聞き出し、
こっそり録音したものだ。
ごめんね、[tatsuya]君。
大人は平気で嘘をつく。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_56);
    dialogFree(ref_53);
    ref_5a = bustupLoad(bustup_133);
    bustupWait(ref_5a);
    ref_5c = bustupAlloc(ref_5a, right, rgb(0,0,0));
    bustupFade(ref_5c, rgb(128,0,0), 30);
    ref_5e = dialogAlloc();
    ref_5f = msgShow(msg_11);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]ペルソナ…
[tab]しかし、噂が本当になるなど…
[tab]そんな事があるのかね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5f);
    dialogFree(ref_5e);
    ref_63 = bustupFade(ref_5c, rgb(0,0,0), 10);
    bustupWait(ref_63);
    bustupFree(ref_5c);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(60);
    ref_6a = dialogAlloc();
    ref_6b = msgShow(msg_12);
/***************************************
私は警察手帳に挟んでおいたお守りを取り出した。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6b);
    dialogFree(ref_6a);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    ref_71 = bustupLoad(bustup_129);
    bustupWait(ref_71);
    ref_73 = bustupAlloc(ref_71, right, rgb(0,0,0));
    bustupFade(ref_73, rgb(128,0,0), 30);
    ref_75 = dialogAlloc();
    ref_76 = msgShow(msg_13);
/***************************************
[color(yellow)]詩織[color(white)]
[tab][tatsuya]君が貸してくれた学生証です。
[tab]七姉妹学園のエンブレムを身に着けていれば、
[tab]ＪＯＫＥＲに狙われても安全だと。
[wait][clear]
***************************************/
    wait(ref_76);
    ref_78 = msgShow(msg_14);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]最近子供たちの間で噂になってますよね。
[tab]事実、あれから須藤は私の前に現れていません。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_78);
    dialogFree(ref_75);
    ref_7c = bustupFade(ref_73, rgb(0,0,0), 10);
    bustupWait(ref_7c);
    bustupFree(ref_73);
    ref_7f = dialogAlloc();
    ref_80 = msgShow(msg_15);
/***************************************
そんなことを言われても、信じられないだろう。
大人には大人の理屈が必要だ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_80);
    dialogFree(ref_7f);
    ref_84 = bustupLoad(bustup_129);
    bustupWait(ref_84);
    ref_86 = bustupAlloc(ref_84, right, rgb(0,0,0));
    bustupFade(ref_86, rgb(128,0,0), 30);
    ref_88 = dialogAlloc();
    ref_89 = msgShow(msg_16);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]ご自分で確かめてみたければ、この公園の近くにある
[tab]パラベラムってバーに行ってみてください。
[tab]噂通り、こんなものも販売しています。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_89);
    dialogFree(ref_88);
    ref_8d = bustupFade(ref_86, rgb(0,0,0), 10);
    bustupWait(ref_8d);
    bustupFree(ref_86);
    cameraMoveTo(750, 0, -800, 50);
    ref_91 = unitMove(unit_73, 750, -900, face_south, medium);
    unitAnimationPlay(unit_73, animation_5, 1);
    wait(ref_91);
    sndMusicPlay(sound_30a4, 127);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_71, animation_0, 1);
    unitWait(unit_71);
    sndMusicPlay(sound_3180, 127);
    delayClear();
    delayWait(90);
    sndMusicPlay(sound_30c5, 127);
    ref_9d = dialogAlloc();
    ref_9e = msgShow(msg_17);
/***************************************
私は上着の前をはだけ、ショルダーホルスターで
左脇の下に吊るしたＧ３３を引き抜くと、念のため
弾倉を抜いてから銃と別々に手渡した。
[wait][clear]
***************************************/
    wait(ref_9e);
    ref_a0 = msgShow(msg_18);
/***************************************
掌に収まるような超コンパクト拳銃だが、３５７マグナム
に匹敵する威力を持つ３５７ＳＩＧ弾を採用し、
署から貸し出される３２口径の５倍近い威力がある。
ポケットロケットとはよく言ったものだ。
[wait][clear]
***************************************/
    wait(ref_a0);
    ref_a2 = msgShow(msg_19);
/***************************************
無論、日本の警察官に支給されるような代物ではない。
仕事で貸与される銃は毎日勤務後署に返却しなければ
ならないので、護身用に購入したものだ。
[wait][clear]
***************************************/
    wait(ref_a2);
    ref_a4 = msgShow(msg_20);
/***************************************
ペルソナだの悪魔だのを使役する犯罪者相手に、
こちらだけルールに従っていたら身を守れない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a4);
    dialogFree(ref_9d);
    unitAnimationPlay(unit_71, animation_1, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_2, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_1, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_0, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_3, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_4, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_3, 1);
    unitWait(unit_71);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_71, animation_0, 1);
    unitWait(unit_71);
    ref_c6 = bustupLoad(bustup_133);
    bustupWait(ref_c6);
    ref_c8 = bustupAlloc(ref_c6, right, rgb(0,0,0));
    bustupFade(ref_c8, rgb(128,0,0), 30);
    ref_ca = dialogAlloc();
    ref_cb = msgShow(msg_21);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]本物か…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_cb);
    dialogFree(ref_ca);
    ref_cf = bustupFade(ref_c8, rgb(0,0,0), 10);
    bustupWait(ref_cf);
    bustupFree(ref_c8);
    ref_d2 = dialogAlloc();
    ref_d3 = msgShow(msg_22);
/***************************************
銃の重みと弾倉の弾頭を確認して、元刑事は唸った。
弾頭はＰ２３０ＪＰやニューナンブでの使用が許された
完全被甲弾、いわゆるフルメタルジャケットではない。
[wait][clear]
***************************************/
    wait(ref_d3);
    ref_d5 = msgShow(msg_23);
/***************************************
先端の鐘が露出し、中央が猛んでいる
ジャケティッド・ホローポイント。
確実に人の動きを止め、殺すための弾頭だ。
[wait][clear]
***************************************/
    wait(ref_d5);
    ref_d7 = msgShow(msg_24);
/***************************************
貫通力では完全被甲弾に劣るが、人体などの
ソフトターゲットに与えるダメージは遥かに勝る。
命中の瞬間鐘がマッシュルーム状に弾け、
効率よく衝撃を与え大出血をもたらすからだ。
[wait][clear]
***************************************/
    wait(ref_d7);
    ref_d9 = msgShow(msg_25);
/***************************************
それ故、ハーグ条約によって軍での使用が
禁じられている。
不必要な苦痛を与えるため人道的ではないとの理由だ
そうだが、世の中には人道的な戦争とやらがあるらしい。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d9);
    dialogFree(ref_d2);
    ref_dd = bustupLoad(bustup_129);
    bustupWait(ref_dd);
    ref_df = bustupAlloc(ref_dd, right, rgb(0,0,0));
    bustupFade(ref_df, rgb(128,0,0), 30);
    ref_e1 = dialogAlloc();
    ref_e2 = msgShow(msg_26);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]黒星やマカロフならともかく、大陸やフィリピン、
[tab]ロシア経由の闇ルートでも、おいそれと
[tab]入手できるようなものじゃありません。
[wait][clear]
***************************************/
    wait(ref_e2);
    ref_e4 = msgShow(msg_27);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]どういう理屈かは知りませんけど、
[tab]噂が現実になったとしか思えません。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_e4);
    dialogFree(ref_e1);
    ref_e8 = bustupFade(ref_df, rgb(0,0,0), 10);
    bustupWait(ref_e8);
    bustupFree(ref_df);
    ref_eb = bustupLoad(bustup_133);
    bustupWait(ref_eb);
    ref_ed = bustupAlloc(ref_eb, right, rgb(0,0,0));
    bustupFade(ref_ed, rgb(128,0,0), 30);
    ref_ef = dialogAlloc();
    ref_f0 = msgShow(msg_28);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]しまっておきなさい。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f0);
    dialogFree(ref_ef);
    ref_f4 = bustupFade(ref_ed, rgb(0,0,0), 10);
    bustupWait(ref_f4);
    bustupFree(ref_ed);
    unitAnimationPlay(unit_71, animation_5, 1);
    unitWait(unit_71);
    sndMusicPlay(sound_3180, 127);
    delayClear();
    delayWait(60);
    ref_fc = unitMove(unit_73, 650, -900, face_east, medium);
    unitAnimationPlay(unit_73, animation_5, 1);
    wait(ref_fc);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_30a4, 127);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_4, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitFace(unit_73, south);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(60);
    ref_111 = dialogAlloc();
    ref_112 = msgShow(msg_29);
/***************************************
[suou]さんは銃と弾倉を返すと、腿の上で組んだ
両手に顎を乗せ再び唸った。
彼の脇では、先ほど二人で並んで食べたあんぱんの袋が、
牛乳の紙パックの下で秋の微風に揺れている。
[wait][clear]
***************************************/
    wait(ref_112);
    ref_114 = msgShow(msg_30);
/***************************************
無理に昼休みに時間を作ってもらったので、
ここで話をしながらの昼食となった。
立ちっぱなしの警備員には酷なメニューだろうが、
こんな話そこらの店じゃできやしない。
[wait][clear]
***************************************/
    wait(ref_114);
    ref_116 = msgShow(msg_31);
/***************************************
聞いていた昼休みの時間はとうに過ぎていた。
あまり長く引き止めておくのも申し訳ない。
そろそろ話を本題に戻そう。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_116);
    dialogFree(ref_111);
    ref_11a = bustupLoad(bustup_129);
    bustupWait(ref_11a);
    ref_11c = bustupAlloc(ref_11a, right, rgb(0,0,0));
    bustupFade(ref_11c, rgb(128,0,0), 30);
    ref_11e = dialogAlloc();
    ref_11f = msgShow(msg_32);
/***************************************
[color(yellow)]詩織[color(white)]
[tab][tatsuya]君は、今も須藤を追っています。
[tab]こんな状況に対処できるのは自分だけだ。
[tab]いいえ…
[wait][clear]
***************************************/
    wait(ref_11f);
    ref_121 = msgShow(msg_33);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]ただ一人、記憶を失わなかった自分が、
[tab]一人でやらなければならない、そう思ってるんです。
[tab]ですから…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_121);
    dialogFree(ref_11e);
    ref_125 = bustupFade(ref_11c, rgb(0,0,0), 10);
    bustupWait(ref_125);
    bustupFree(ref_11c);
    ref_128 = bustupLoad(bustup_133);
    bustupWait(ref_128);
    ref_12a = bustupAlloc(ref_128, right, rgb(0,0,0));
    bustupFade(ref_12a, rgb(128,0,0), 30);
    ref_12c = dialogAlloc();
    ref_12d = msgShow(msg_34);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]克哉は、事情を承知しているんですか。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12d);
    dialogFree(ref_12c);
    ref_131 = bustupFade(ref_12a, rgb(0,0,0), 10);
    bustupWait(ref_131);
    bustupFree(ref_12a);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_4, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_2, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_4, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(60);
    ref_168 = bustupLoad(bustup_129);
    bustupWait(ref_168);
    ref_16a = bustupAlloc(ref_168, right, rgb(0,0,0));
    bustupFade(ref_16a, rgb(128,0,0), 30);
    ref_16c = dialogAlloc();
    ref_16d = msgShow(msg_35);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]いえ…[tab]恐らくはまだ。
[tab][suou]巡査部長は、[tatsuya]君が守ろうとしている
[tab]天野[tab]舞耶という女性と行動を共にしているようです。
[wait][clear]
***************************************/
    wait(ref_16d);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(60);
    ref_173 = msgShow(msg_36);
/***************************************
[color(yellow)]詩織[color(white)]
[tab][tatsuya]君は、向こう側の仲間たちや
[tab]ご家族を巻き込みたくないと言っていました。
[tab]だから家を出たんです。
[wait][clear]
***************************************/
    wait(ref_173);
    ref_175 = msgShow(msg_37);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]こんなこと、本来子供がやることじゃありません。
[tab]私たち警官の仕事です。
[tab]ですが、警察があてにならないのはご存知の通りです。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_175);
    dialogFree(ref_16c);
    ref_179 = bustupFade(ref_16a, rgb(0,0,0), 10);
    bustupWait(ref_179);
    bustupFree(ref_16a);
    ref_17c = bustupLoad(bustup_133);
    bustupWait(ref_17c);
    ref_17e = bustupAlloc(ref_17c, right, rgb(0,0,0));
    bustupFade(ref_17e, rgb(128,0,0), 30);
    ref_180 = dialogAlloc();
    ref_181 = msgShow(msg_38);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]富樫はまだ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_181);
    dialogFree(ref_180);
    ref_185 = bustupFade(ref_17e, rgb(0,0,0), 10);
    bustupWait(ref_185);
    bustupFree(ref_17e);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    ref_18e = dialogAlloc();
    ref_18f = msgShow(msg_39);
/***************************************
[suou]さんは、かつての親友を慮って
すがるように私を見上げた。
私はこの人が喜ぶようなことを何も言ってあげられない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_18f);
    dialogFree(ref_18e);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(60);
    ref_19b = bustupLoad(bustup_129);
    bustupWait(ref_19b);
    ref_19d = bustupAlloc(ref_19b, right, rgb(0,0,0));
    bustupFade(ref_19d, rgb(128,0,0), 30);
    ref_19f = dialogAlloc();
    ref_1a0 = msgShow(msg_40);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]須藤[tab]竜蔵とつながっています。
[tab]管理官の島津と、須藤[tab]竜也が確保されないように
[tab]捜査を妨害しているのは明らかです。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1a0);
    dialogFree(ref_19f);
    ref_1a4 = bustupFade(ref_19d, rgb(0,0,0), 10);
    bustupWait(ref_1a4);
    bustupFree(ref_19d);
    ref_1a7 = bustupLoad(bustup_133);
    bustupWait(ref_1a7);
    ref_1a9 = bustupAlloc(ref_1a7, right, rgb(0,0,0));
    bustupFade(ref_1a9, rgb(128,0,0), 30);
    ref_1ab = dialogAlloc();
    ref_1ac = msgShow(msg_41);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]富樫…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1ac);
    dialogFree(ref_1ab);
    ref_1b0 = bustupFade(ref_1a9, rgb(0,0,0), 10);
    bustupWait(ref_1b0);
    bustupFree(ref_1a9);
    ref_1b3 = dialogAlloc();
    ref_1b4 = msgShow(msg_42);
/***************************************
額に手をやり俯いた姿は、実際の年齢より十も
老けこんで見えた。
親友が自分を裏切り、未だに本来取り締まるべき
悪事に加担していると知るのは辛いだろう。
[wait][clear]
***************************************/
    wait(ref_1b4);
    ref_1b6 = msgShow(msg_43);
/***************************************
この人は、まだどこかで富樫を信じていたのだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1b6);
    dialogFree(ref_1b3);
    ref_1ba = bustupLoad(bustup_129);
    bustupWait(ref_1ba);
    ref_1bc = bustupAlloc(ref_1ba, right, rgb(0,0,0));
    bustupFade(ref_1bc, rgb(128,0,0), 30);
    ref_1be = dialogAlloc();
    ref_1bf = msgShow(msg_44);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]…今、須藤を倒しこの世界を守ることができるのは
[tab][tatsuya]君だけです。
[tab]虫がいいことを言っているのは承知しています。
[wait][clear]
***************************************/
    wait(ref_1bf);
    ref_1c1 = msgShow(msg_45);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]でも、彼一人に重荷は背負わせません。
[tab]私ができる限りサポートします。
[tab][tatsuya]君には、事情を知る大人の助けが必要なんです。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1c1);
    dialogFree(ref_1be);
    ref_1c5 = bustupFade(ref_1bc, rgb(0,0,0), 10);
    bustupWait(ref_1c5);
    bustupFree(ref_1bc);
    ref_1c8 = dialogAlloc();
    ref_1c9 = msgShow(msg_46);
/***************************************
改装中のゾディアックで初めて出会い、
陣也の死の必然と世界の秘密を聞き出した後、
私は強引に[tatsuya]君と協定を結んだ。
[wait][clear]
***************************************/
    wait(ref_1c9);
    ref_1cb = msgShow(msg_47);
/***************************************
私はねぐらと須藤に関する警察の捜査情報を提供する。
代わりに、須藤を再起不能にするか殺してくれと。
[wait][clear]
***************************************/
    wait(ref_1cb);
    ref_1cd = msgShow(msg_48);
/***************************************
恐らく、どう転んでも[tatsuya]君は
いずれ須藤と決着をつけざるを得ないだろう。
[wait][clear]
***************************************/
    wait(ref_1cd);
    ref_1cf = msgShow(msg_49);
/***************************************
法的には正当防衛が成立する余地があるかもしれない。
しかし、人を傷つけたり殺すことに変わりはない。
相手がどんな悪人であろうと、人の命を奪ったという
事実は一生[tatsuya]君の心に残り続ける。
[wait][clear]
***************************************/
    wait(ref_1cf);
    ref_1d1 = msgShow(msg_50);
/***************************************
だが彼が一人でやったのではない。
私が殺してくれと頼んだのだ。
気休めでもいい。
彼が、自分を許すきっかけくらいにはなるかもしれない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1d1);
    dialogFree(ref_1c8);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    ref_1d7 = bustupLoad(bustup_129);
    bustupWait(ref_1d7);
    ref_1d9 = bustupAlloc(ref_1d7, right, rgb(0,0,0));
    bustupFade(ref_1d9, rgb(128,0,0), 30);
    ref_1db = dialogAlloc();
    ref_1dc = msgShow(msg_51);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]彼の…[tab][tatsuya]君のやりたいように
[tab]やらせてあげてもらえないでしょうか。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1dc);
    dialogFree(ref_1db);
    ref_1e0 = bustupFade(ref_1d9, rgb(0,0,0), 10);
    bustupWait(ref_1e0);
    bustupFree(ref_1d9);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_71, animation_0, 1);
    unitWait(unit_71);
    sndMusicPlay(sound_3180, 127);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    ref_1ea = dialogAlloc();
    ref_1eb = msgShow(msg_52);
/***************************************
立ち上がった[suou]さんの瞳から
苦悩の色は消えていた。
過酷な運命に抗おうとする息子を、
見守ることに決めたのだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1eb);
    dialogFree(ref_1ea);
    unitAnimationPlay(unit_71, animation_1, 1);
    unitWait(unit_71);
    ref_1f1 = bustupLoad(bustup_133);
    bustupWait(ref_1f1);
    ref_1f3 = bustupAlloc(ref_1f1, right, rgb(0,0,0));
    bustupFade(ref_1f3, rgb(128,0,0), 30);
    ref_1f5 = dialogAlloc();
    ref_1f6 = msgShow(msg_53);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]…わかりました。
[tab]あなたが預かってくれていると知って、安心しました。
[tab]家内にも話して、捜索願いは取り下げます。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_1f6);
    dialogFree(ref_1f5);
    ref_1fa = bustupFade(ref_1f3, rgb(0,0,0), 10);
    bustupWait(ref_1fa);
    bustupFree(ref_1f3);
    unitAnimationPlay(unit_71, animation_0, 1);
    unitWait(unit_71);
    unitAnimationPlay(unit_73, animation_0, 1);
    ref_200 = unitMove(unit_73, 750, -900, face_south, medium);
    unitAnimationPlay(unit_73, animation_5, 1);
    wait(ref_200);
    delayClear();
    delayWait(15);
    ref_205 = bustupLoad(bustup_129);
    bustupWait(ref_205);
    ref_207 = bustupAlloc(ref_205, right, rgb(0,0,0));
    bustupFade(ref_207, rgb(128,0,0), 30);
    ref_209 = dialogAlloc();
    ref_20a = msgShow(msg_54);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]ありがとうございます。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_20a);
    dialogFree(ref_209);
    ref_20e = bustupFade(ref_207, rgb(0,0,0), 10);
    bustupWait(ref_20e);
    bustupFree(ref_207);
    ref_211 = dialogAlloc();
    ref_212 = msgShow(msg_55);
/***************************************
心の底から頭を下げた。
息子さんの命をくれと言っているようなものだ。
ぶん殴られても文句は言えない。
[wait][clear]
***************************************/
    wait(ref_212);
    ref_214 = msgShow(msg_56);
/***************************************
だがこれで、[tatsuya]君も少しは動きやすくなるはずだ。
ただでさえ目立つ子だ。
この街の中を動き回る以上、
余計な足枷はなるべく取り除いてやったほうがいい。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_214);
    dialogFree(ref_211);
    ref_218 = bustupLoad(bustup_133);
    bustupWait(ref_218);
    ref_21a = bustupAlloc(ref_218, right, rgb(0,0,0));
    bustupFade(ref_21a, rgb(128,0,0), 30);
    ref_21c = dialogAlloc();
    ref_21d = msgShow(msg_57);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]まさか、こんなことに巻き込まれているとは
[tab]思いもしませんでしたが…
[tab]因縁、というやつなんでしょうな。
[wait][clear]
***************************************/
    wait(ref_21d);
    unitAnimationPlay(unit_71, animation_1, 1);
    unitWait(unit_71);
    ref_221 = msgShow(msg_58);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]あの子たちのためと思いしたことだが、
[tab]結局自分自身の不始末を、
[tab]息子たちに押し付ける形になってしまった…
[wait][clear]
***************************************/
    wait(ref_221);
    unitAnimationPlay(unit_71, animation_0, 1);
    unitWait(unit_71);
    ref_225 = msgShow(msg_59);
/***************************************
[color(yellow)][tatsuya]の父[color(white)]
[tab]詩織さん、あなたにも本当に申し訳ないと思っています。
[tab]私は自分の家庭を守るために、竜蔵の脅迫に屈した。
[tab]そのために、あなたが今はこんな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_225);
    dialogFree(ref_21c);
    ref_229 = bustupFade(ref_21a, rgb(0,0,0), 10);
    bustupWait(ref_229);
    bustupFree(ref_21a);
    ref_22c = dialogAlloc();
    ref_22d = msgShow(msg_60);
/***************************************
私や[suou]さん、富樫署長に須藤親子、巡査部長や
こちら側を作った子供たち、そして世界の命運を握る女、
天野[tab]舞耶…
[wait][clear]
***************************************/
    wait(ref_22d);
    ref_22f = msgShow(msg_61);
/***************************************
[tatsuya]君を中心に広がる人間関係は、
まるで陰募で冷笑的な画家が、モデルやギャラリーを
嘲笑うために描いた狂った曼荼羅のようだ。
[wait][clear]
***************************************/
    wait(ref_22f);
    ref_231 = msgShow(msg_62);
/***************************************
個々人は一見無関係に見えながら、
別の誰かを通して相似的な関係図を描いている。
知らず知らずそこに名を連ねる私たちにとって、
１０年という時間は何の解決も与えはしなかった。
[wait][clear]
***************************************/
    wait(ref_231);
    ref_233 = msgShow(msg_63);
/***************************************
耐え難い卵失や絶望、積み上げられた哀しみや怒りの
全ては、ただの準備に過ぎなかったのだ。
だが、それでも立ち上がるための時間は十分あった。
人間を舐めるな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_233);
    dialogFree(ref_22c);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_4, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_2, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_0, 1);
    unitWait(unit_73);
    ref_255 = bustupLoad(bustup_129);
    bustupWait(ref_255);
    ref_257 = bustupAlloc(ref_255, right, rgb(0,0,0));
    bustupFade(ref_257, rgb(128,0,0), 30);
    ref_259 = dialogAlloc();
    ref_25a = msgShow(msg_64);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]私が同じ立場なら、きっと同じことをしました。
[tab]それに私、今は警官になってよかったと
[tab]思ってるんです。
[wait][clear]
***************************************/
    wait(ref_25a);
    ref_25c = msgShow(msg_65);
/***************************************
[color(yellow)]詩織[color(white)]
[tab][tatsuya]君にも会えましたし、
[tab]大人が作った歪な社会になじめず、罪を犯してしまう
[tab]子供たちに手を差し伸べることもできますから。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_25c);
    dialogFree(ref_259);
    ref_260 = bustupFade(ref_257, rgb(0,0,0), 10);
    bustupWait(ref_260);
    bustupFree(ref_257);
    ref_263 = dialogAlloc();
    ref_264 = msgShow(msg_66);
/***************************************
今はまだダメかもしれないが、いずれは[tatsuya]君のような
子供たちが、笑って暮らせる社会にしたい。
それが大人の仕事のはずだ。
[wait][clear]
***************************************/
    wait(ref_264);
    ref_266 = msgShow(msg_67);
/***************************************
子供たちに、何かと引き換えに生まれてくる世界を
選ばせるようなことがあってはならない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_266);
    dialogFree(ref_263);
    ref_26a = dialogAlloc();
    ref_26b = msgShow(msg_68);
/***************************************
[color(yellow)]女の子の声[color(white)]
[tab]空の科学館の飛行船が飛んだって！
[tab]見に行こうよ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_26b);
    dialogFree(ref_26a);
    unitAnimationPlay(unit_73, animation_1, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_2, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitFace(unit_73, west);
    unitAnimationPlay(unit_73, animation_3, 1);
    unitWait(unit_73);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_73, animation_4, 1);
    unitWait(unit_73);
    ref_27e = dialogAlloc();
    ref_27f = msgShow(msg_69);
/***************************************
[color(yellow)]男の子の声[color(white)]
[tab]飛ぶって噂、本当だったんだ！
[tab]行こう行こう。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_27f);
    dialogFree(ref_27e);
    ref_283 = dialogAlloc();
    ref_284 = msgShow(msg_70);
/***************************************
近くを走り抜けていく子供たちの声に、
私と[suou]さんは、顔を見合わせ空を見上げた。
飛行船の姿は見えなかったが、恐らく
本当に飛んでいるに違いない。
[wait][clear]
***************************************/
    wait(ref_284);
    ref_286 = msgShow(msg_71);
/***************************************
そういえば、少し前から
消防車のサイレンが騒がしかった。
なぜだかわからないが、その船にはきっと
[tatsuya]君が乗っている、そんな気がした。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_286);
    dialogFree(ref_283);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 4, false);
    screenFadeOuter(rgb(255,255,255), 4, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(20);
    ref_292 = bustupLoad(bustup_129);
    bustupWait(ref_292);
    ref_294 = bustupAlloc(ref_292, right, rgb(0,0,0));
    bustupFade(ref_294, rgb(128,0,0), 30);
    ref_296 = dialogAlloc();
    ref_297 = msgShow(msg_72);
/***************************************
[color(yellow)]詩織[color(white)]
[tab]徹底的にやりなさい、[tatsuya]君…
[tab]後悔しないようにね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_297);
    dialogFree(ref_296);
    ref_29b = bustupFade(ref_294, rgb(0,0,0), 10);
    bustupWait(ref_29b);
    bustupFree(ref_294);
    delayClear();
    delayWait(60);
    eventFileLoad(E, 243);
}
