
msg_0:
[color(yellow)]栄吉[color(white)]
[tab][suou]！？
[tab]セブンスの[suou]…[tab]だよな？
[sync][wait][clear][end]

msg_1:
[color(yellow)][tatsuya][color(white)]
[tab]栄吉！？
[tab]お、お前何やってんだこんな所で！
[sync][wait][clear][end]

msg_2:
死ぬほど驚いた。
なんでこいつがここにいるんだ…
[sync][wait][clear][end]

msg_3:
[color(yellow)]栄吉[color(white)]
[tab]な、なにったてよ…
[tab]お前こそ、なんでこんな所にいんだ？
[tab]天野さんたちと一緒に来たのか？
[sync][wait][clear][end]

msg_4:
やはり舞耶姉たちが来ている…
今の口ぶりからすると、こいつは舞耶姉たちと
この研究所で鉢合わせでもしたようだ。
[wait][clear][end]

msg_5:
なんてこった…[tab]またやることが増えた。
[sync][wait][clear][end]

msg_6:
[color(yellow)][tatsuya][color(white)]
[tab]…ああ。
[tab]舞耶…[tab]天野さんたちはどこへ行った？
[sync][wait][clear][end]

msg_7:
[color(yellow)]栄吉[color(white)]
[tab]なんかよく知らねぇけど、
[tab]この建物の奥の方を調べに行ったぜ。
[tab]ったく、とんでもねぇとこだぜ、ここはよ。
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]後ろのは、ここに収容されてた連中だな。
[tab]それで全部か？
[sync][wait][clear][end]

msg_9:
詩織さんの姿は見当たらない。
別の場所にいるのか…
[sync][wait][clear][end]

msg_10:
[color(yellow)]栄吉[color(white)]
[tab]ああ、ここにいたのはこの人らだけだ。
[tab]俺も杉本って奴を探しに来たんだけどよ、
[tab]人体実験されてたみてぇだ…[tab]ひでぇことしやがるぜ。
[wait][clear][end]

msg_11:
[color(yellow)]栄吉[color(white)]
[tab]南条って人が病院で面倒見るから、
[tab]駐車場のトレーラーまで連れてけってよ。
[sync][wait][clear][end]

msg_12:
南条？[tab]ゆきのさんの知り合いのか？
ここは元々南条グループの施設のはずだ。
[wait][clear][end]

msg_13:
南条って人が舞耶姉と一緒に行動しているということは、
会社全体が【奴】の手駒の組織に加担している、
というわけではないのかもしれない。
[sync][wait][clear][end]

msg_14:
[color(yellow)]栄吉[color(white)]
[tab]なぁ、杉本見なかったか？
[tab]憎ったらしい顔した、うちの学校の奴なんだけど。
[sync][wait][clear][end]

msg_15:
[color(yellow)][tatsuya][color(white)]
[tab]…知らないな。
[sync][wait][clear][end]

msg_16:
向こう側でならよく知っていた、とは言えない。
こいつには、何もかも忘れていてもらわないと困る。
だが栄吉がここにいる理由はピンときた。
向こう側でも、杉本とこいつは犬猿の仲だった。
[sync][wait][clear][end]

msg_17:
[color(yellow)][tatsuya][color(white)]
[tab]お前を狙って、ＪＯＫＥＲ呪いをしたそいつを探しに
[tab]ここに来たってわけか。
[tab]相変わらず、お人よしだな。
[sync][wait][clear][end]

msg_18:
[color(yellow)]栄吉[color(white)]
[tab]…お前、よくわかったな。
[sync][wait][clear][end]

msg_19:
[color(yellow)][tatsuya][color(white)]
[tab]こいつを持ってろ。
[sync][wait][clear][end]

msg_20:
俺はセブンスの校章が描かれたバッヂを投げた。
受け取った栄吉は、きょとんとしている。
まだＪＯＫＥＲ使い相手には効果があるはずだ。
[sync][wait][clear][end]

msg_21:
[color(yellow)]栄吉[color(white)]
[tab]なんだこりゃ。
[tab]お前まで、あんな噂を信じてんのかよ。
[sync][wait][clear][end]

msg_22:
[color(yellow)][tatsuya][color(white)]
[tab]いいから持ってろ。
[tab]行くぞ、駐車場まで付き合ってやる。
[tab]ついて来い。
[sync][wait][clear][end]

msg_23:
こちら側の栄吉とシンクロした栄吉は
向こう側を思い出しでもしない限り、もうペルソナを
使えないはずだ。放っておけない。
[sync][wait][clear][end]

msg_24:
[color(yellow)]栄吉[color(white)]
[tab]お、悪いな。
[tab]恩に着るぜ！
[sync][wait][clear][end]
