
msg_0:
[color(yellow)][tatsuya][color(white)]
[tab]みんなで中に隠れてろ、栄吉。
[tab]ドアは全部閉めるなよ。
[tab]酸欠で死ぬぞ。
[sync][wait][clear][end]

msg_1:
[color(yellow)]栄吉[color(white)]
[tab]ああ…[tab]なぁ、[suou]。
[tab]さっきから俺たちすげー自然に話してっけど、
[tab]なんで俺の名前知ってんだ？
[sync][wait][clear][end]

msg_2:
[color(yellow)][tatsuya][color(white)]
[tab]…カス校のパンツ番長の名前を、知らない奴が
[tab]いるのか？
[sync][wait][clear][end]

msg_3:
[color(yellow)]栄吉[color(white)]
[tab]パンツ番長？[tab]なんだそりゃ。
[tab]なんか、すげー懐かしいっつーか、腹立つっつーか…
[sync][wait][clear][end]

msg_4:
失敗した。
こいつは、こちら側ではそんな通り名じゃないらしい。
もうこれ以上は無理だ。
[sync][wait][clear][end]

msg_5:
[color(yellow)][tatsuya][color(white)]
[tab]いいから、そいつらを見張ってろ。
[tab]すぐ、舞…天野さんたちも戻ってくる。
[sync][wait][clear][end]

msg_6:
[color(yellow)]栄吉[color(white)]
[tab]おい、お前はどうすんだよ！
[sync][wait][clear][end]
