function START()
{
    sndMusicPlay(sound_3033, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(southeast, 740, -600, -2500);
    ref_4 = cameraZoom(400, 1);
    wait(ref_4);
    ref_6 = spriteLoad(sprite_1a);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_19);
    wait(ref_8);
    ref_a = spriteLoad(sprite_44);
    wait(ref_a);
    ref_c = spriteLoad(sprite_45);
    wait(ref_c);
    ref_e = spriteLoad(sprite_dd);
    wait(ref_e);
    unitSpawn(tatsuya, sprite_1a, 1150, -400, -2700, east, none);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitSpawn(unit_14, sprite_44, 750, -400, -2700, west, none);
    unitAnimationPlay(unit_14, animation_11, 1);
    unitSpawn(npc1, sprite_dd, 1300, -400, -2740, north, none);
    unitAnimationPlay(npc1, animation_c, 1);
    unitSpawn(enemy1, sprite_dd, 1250, 0, -2700, east, none);
    unitAnimationPlay(enemy1, animation_c, 1);
    objVisible(obj_35, false);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_1f = bustupLoad(bustup_51);
    bustupWait(ref_1f);
    ref_21 = bustupAlloc(ref_1f, right, rgb(0,0,0));
    bustupFade(ref_21, rgb(128,0,0), 30);
    ref_23 = dialogAlloc();
    ref_24 = msgShow(msg_0);
/***************************************
[color(yellow)]神取[color(white)]
[tab]流石だ、特異点の少年よ。
[tab]だがまだ己の若さを御しきれていない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_24);
    dialogFree(ref_23);
    ref_28 = bustupFade(ref_21, rgb(0,0,0), 10);
    bustupWait(ref_28);
    bustupFree(ref_21);
    unitAnimationPlay(unit_14, animation_23, 1);
    delayClear();
    delayWait(60);
    cameraMoveTo(600, -600, -2500, 15);
    unitFace(tatsuya, east);
    unitMove(tatsuya, 850, -2700, face_east, fastest);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    unitAnimationHold(tatsuya, animation_5, -1);
    sndMusicPlay(sound_321e, 127);
    unitAnimationPlay(unit_14, animation_11, 1);
    unitFace(unit_14, west);
    unitMove(unit_14, 700, -2700, face_west, reverse);
    unitWait(unit_14);
    ref_39 = dialogAlloc();
    ref_3a = msgShow(msg_1);
/***************************************
首を狙って左右に薙いだ切っ先を、
神取は舞うように半歩ずつ引いて避けた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_3a);
    dialogFree(ref_39);
    ref_3e = bustupLoad(bustup_d);
    bustupWait(ref_3e);
    ref_40 = bustupAlloc(ref_3e, left, rgb(0,0,0));
    bustupFade(ref_40, rgb(128,0,0), 30);
    ref_42 = dialogAlloc();
    ref_43 = msgShow(msg_2);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]どうすれば詩織さんを戻せる！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_43);
    dialogFree(ref_42);
    ref_47 = bustupFade(ref_40, rgb(0,0,0), 10);
    bustupWait(ref_47);
    bustupFree(ref_40);
    ref_4a = dialogAlloc();
    ref_4b = msgShow(msg_3);
/***************************************
左に薙いだ刀を無理に返さず、
そのまま柄頭を左掌で押し込むように、
奴の顔の人中を狙って突いた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4b);
    dialogFree(ref_4a);
    unitAnimationPlay(unit_14, animation_11, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    ref_54 = bustupLoad(bustup_51);
    bustupWait(ref_54);
    ref_56 = bustupAlloc(ref_54, right, rgb(0,0,0));
    bustupFade(ref_56, rgb(128,0,0), 30);
    ref_58 = dialogAlloc();
    ref_59 = msgShow(msg_4);
/***************************************
[color(yellow)]神取[color(white)]
[tab]ひとつ君にヒントをやろう。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_59);
    dialogFree(ref_58);
    ref_5d = bustupFade(ref_56, rgb(0,0,0), 10);
    bustupWait(ref_5d);
    bustupFree(ref_56);
    ref_60 = dialogAlloc();
    ref_61 = msgShow(msg_5);
/***************************************
神取はこれも顔を傾けかわすと、
耳を掠めた刀身を左手で掴んだ。[tab]
そのまま引けば、指が全部落ちる。
自然と口元が綻んだ。
[wait][clear]
***************************************/
    wait(ref_61);
    ref_63 = msgShow(msg_6);
/***************************************
だが、渾身の力で引いても、
刀は万力に挟まれたようにびくともしない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_63);
    dialogFree(ref_60);
    ref_67 = bustupLoad(bustup_51);
    bustupWait(ref_67);
    ref_69 = bustupAlloc(ref_67, right, rgb(0,0,0));
    bustupFade(ref_69, rgb(128,0,0), 30);
    ref_6b = dialogAlloc();
    ref_6c = msgShow(msg_7);
/***************************************
[color(yellow)]神取[color(white)]
[tab]創造とは矛盾の統合だ。
[tab]両立し難い相反するものがひとつになる時、
[tab]何かが生まれる。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6c);
    dialogFree(ref_6b);
    ref_70 = bustupFade(ref_69, rgb(0,0,0), 10);
    bustupWait(ref_70);
    bustupFree(ref_69);
    ref_73 = bustupLoad(bustup_d);
    bustupWait(ref_73);
    ref_75 = bustupAlloc(ref_73, left, rgb(0,0,0));
    bustupFade(ref_75, rgb(128,0,0), 30);
    ref_77 = dialogAlloc();
    ref_78 = msgShow(msg_8);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]なんだと？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_78);
    dialogFree(ref_77);
    ref_7c = bustupFade(ref_75, rgb(0,0,0), 10);
    bustupWait(ref_7c);
    bustupFree(ref_75);
    ref_7f = bustupLoad(bustup_51);
    bustupWait(ref_7f);
    ref_81 = bustupAlloc(ref_7f, right, rgb(0,0,0));
    bustupFade(ref_81, rgb(128,0,0), 30);
    ref_83 = dialogAlloc();
    ref_84 = msgShow(msg_9);
/***************************************
[color(yellow)]神取[color(white)]
[tab]私も君も、役割を演じているに過ぎんということだ。
[tab]だが、卑下することはない。
[tab]結果に過程はつきものだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_84);
    dialogFree(ref_83);
    ref_88 = bustupFade(ref_81, rgb(0,0,0), 10);
    bustupWait(ref_88);
    bustupFree(ref_81);
    unitAnimationPlay(unit_14, animation_23, 1);
    unitWait(unit_14);
    delayClear();
    delayWait(60);
    ref_8f = bustupLoad(bustup_d);
    bustupWait(ref_8f);
    ref_91 = bustupAlloc(ref_8f, left, rgb(0,0,0));
    bustupFade(ref_91, rgb(128,0,0), 30);
    ref_93 = dialogAlloc();
    ref_94 = msgShow(msg_10);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]使い走りが言うことか！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_94);
    dialogFree(ref_93);
    ref_98 = bustupFade(ref_91, rgb(0,0,0), 10);
    bustupWait(ref_98);
    bustupFree(ref_91);
    unitAnimationPlay(unit_14, animation_11, 1);
    delayClear();
    delayWait(60);
    ref_9e = bustupLoad(bustup_51);
    bustupWait(ref_9e);
    ref_a0 = bustupAlloc(ref_9e, right, rgb(0,0,0));
    bustupFade(ref_a0, rgb(128,0,0), 30);
    ref_a2 = dialogAlloc();
    ref_a3 = msgShow(msg_11);
/***************************************
[color(yellow)]神取[color(white)]
[tab]フッ…[tab]宮代[tab]詩織を救いたければ、それに
[tab]相応しい場所を探したまえ。
[tab]矛盾する価値を同時に手にできると思うのならば、な。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a3);
    dialogFree(ref_a2);
    ref_a7 = bustupFade(ref_a0, rgb(0,0,0), 10);
    bustupWait(ref_a7);
    bustupFree(ref_a0);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3136, 127);
    unitSpawn(unit_14, sprite_44, 800, 0, -2500, north, none);
    unitAnimationPlay(unit_14, animation_11, 1);
    unitSpriteClear(tatsuya);
    unitSpriteSet(tatsuya, sprite_1a);
    unitFace(tatsuya, south);
    unitAnimationPlay(tatsuya, animation_11, 1);
    sndMusicPlay(sound_31cc, 127);
    delayClear();
    delayWait(60);
    cameraMoveTo(200, -600, -2100, 30);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(30);
    ref_c5 = dialogAlloc();
    ref_c6 = msgShow(msg_12);
/***************************************
意味を考えている隙を突かれた。
神取の右足が脇腹に食い込み、息が詰まる。
その隙に奴は、軽々と踊り場の手すりを飛び越え
階下に飛び降りた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c6);
    dialogFree(ref_c5);
    ref_ca = bustupLoad(bustup_f);
    bustupWait(ref_ca);
    ref_cc = bustupAlloc(ref_ca, left, rgb(0,0,0));
    bustupFade(ref_cc, rgb(128,0,0), 30);
    ref_ce = dialogAlloc();
    ref_cf = msgShow(msg_13);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]待て！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_cf);
    dialogFree(ref_ce);
    ref_d3 = bustupFade(ref_cc, rgb(0,0,0), 10);
    bustupWait(ref_d3);
    bustupFree(ref_cc);
    unitAnimationPlay(unit_14, animation_23, 1);
    unitWait(unit_14);
    ref_d8 = bustupLoad(bustup_51);
    bustupWait(ref_d8);
    ref_da = bustupAlloc(ref_d8, right, rgb(0,0,0));
    bustupFade(ref_da, rgb(128,0,0), 30);
    ref_dc = dialogAlloc();
    ref_dd = msgShow(msg_14);
/***************************************
[color(yellow)]神取[color(white)]
[tab]手遊びでもしながら、ゆっくり考えたまえ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_dd);
    dialogFree(ref_dc);
    ref_e1 = bustupFade(ref_da, rgb(0,0,0), 10);
    bustupWait(ref_e1);
    bustupFree(ref_da);
    unitFace(unit_14, west);
    unitMove(unit_14, 1010, -2500, face_north, fast);
    unitWait(unit_14);
    unitMove(unit_14, 1010, -2850, face_north, fast);
    unitWait(unit_14);
    unitDespawn(unit_14, fade);
    ref_ea = dialogAlloc();
    ref_eb = msgShow(msg_15);
/***************************************
神取は俺を見上げ、手にした健身球をかざすと、
階下のドアをくぐり姿を消した。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_eb);
    dialogFree(ref_ea);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    eventFileLoad(E, 263);
}
