
msg_0:
[color(green)]ウムル・アト・タウィルが消え去った後に、
輝く光そのものが浮いている。[color(white)]
[wait][clear][end]

msg_1:
[color(green)]その近くに、
空間をすり抜けるようにズーラが跳躍してきた。[color(white)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]グッド！
[tab]ウムル・アト・タウィルを退散させるとは、
[tab]賞賛の敬礼！
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]これが、詩織さんの心の欠片か…？
[sync][wait][clear][end]

msg_4:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]そう、これは宮代[tab]詩織の
[tab]「知識のトラペゾヘドロン」である。
[tab]覗いてみるがいい。
[sync][wait][clear][end]

msg_5:
[color(green)]覗き込むと、様々な文字や言葉、数式や情報が、
刻々と変わる万華鏡の中のビーズのように、
集まっては散り散りになり、流れ、渦巻いていた。[color(white)]
[sync][wait][clear][end]

msg_6:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]さて、ぐずぐずしている暇はないぞ。
[tab]ウムル・アト・タウィルが、より強力になって
[tab]戻ってくる前に、仕事を片付けるのだ。
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]げー！
[tab]あれ死んでないの？
[sync][wait][clear][end]

msg_8:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]境界とはそういうものである。
[tab]あれがいなければ、貴様ら人間の意識と普遍的無意識の
[tab]境も無くなり、個人として存在できなくなるのだぞ。
[wait][clear][end]

msg_9:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]では、次なるトラペゾヘドロンを求め、
[tab]カダスを旅するがよい。
[tab]ムーブ！[tab]ムーブ！[tab]ムーブ！
[sync][wait][clear][end]

msg_10:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_11:
[color(green)]舞耶達は、知識のトラペゾヘドロンを手に入れ、
知識の塔を後にした。[color(white)]
[sync][wait][clear][end]
