function START()
{
    sndMusicPlay(sound_3011, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(southeast, 740, -600, -2500);
    ref_4 = cameraZoom(400, 1);
    wait(ref_4);
    ref_6 = spriteLoad(sprite_1a);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_44);
    wait(ref_8);
    ref_a = spriteLoad(sprite_45);
    wait(ref_a);
    ref_c = spriteLoad(sprite_27);
    wait(ref_c);
    ref_e = spriteLoad(sprite_102);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_dc);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_dd);
    wait(ref_12);
    unitSpawn(unit_14, sprite_44, 750, -400, -2740, west, none);
    unitAnimationPlay(unit_14, animation_4b, 1);
    unitSpawn(eikichi, sprite_27, 1200, -400, -2740, south, none);
    unitAnimationPlay(eikichi, animation_35, 1);
    unitSpawn(enemy3, sprite_dd, 1300, -400, -2740, east, none);
    unitAnimationPlay(enemy3, animation_0, 1);
    unitSpawn(enemy1, sprite_dd, 900, 0, -2600, south, none);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitSpawn(enemy2, sprite_dd, 1100, 0, -2600, south, none);
    unitAnimationPlay(enemy2, animation_0, 1);
    objVisible(obj_35, false);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    efctDummy(effect_2d);
    efctLoad(effect_2d);
    call(DOA);
    unitAnimationPlay(unit_14, animation_4c, 1);
    objAnimRotate(obj_34, 0, -90, 0, 15, 0);
    objAnimWait(obj_34);
    efctPlay(effect_2d, efct_1, 945, -500, -2740, 945, -500, -2740, false);
    delayClear();
    delayWait(5);
    efctPlay(effect_2d, efct_2, 945, -520, -2770, 945, -520, -2770, false);
    unitSpawn(tatsuya, sprite_1a, 1000, -400, -2850, south, fade);
    unitAnimationPlay(tatsuya, animation_2, 1);
    efctWait(efct_1);
    efctWait(efct_2);
    ref_35 = dialogAlloc();
    ref_36 = msgShow(msg_0);
/***************************************
神取のいる方に扉が開くと同時に、銃弾か何かが
扉にぶち当たるような音がした。
神取の姿は扉に隠れ見えない。
[wait][clear]
***************************************/
    wait(ref_36);
    ref_38 = msgShow(msg_1);
/***************************************
アドレナリンが分泌され、周りの状況がひどく
ゆっくりに流れていた。
[wait][clear]
***************************************/
    wait(ref_38);
    ref_3a = msgShow(msg_2);
/***************************************
全身がセンサーと化し、知覚が研ぎ澄まされ、
あらゆる動きがはっきり見え、
全ての音が明確に聞こえた。
[wait][clear]
***************************************/
    wait(ref_3a);
    ref_3c = msgShow(msg_3);
/***************************************
俺のすぐ横、右目の視界の隅には、腰を浮かしかけている
栄吉と、その後ろで栄吉の頭に銃を突きつけている
警備員の姿が映った。
[wait][clear]
***************************************/
    wait(ref_3c);
    ref_3e = msgShow(msg_4);
/***************************************
目の前の広大な空間には、リボルバーのシリンダーを
模したでかい機械があり、その周囲に不気味な黒い粘液が
詰められた試験管のようなタンクが無数に並んでいた。
[wait][clear]
***************************************/
    wait(ref_3e);
    ref_40 = msgShow(msg_5);
/***************************************
その機械の前で、舞耶姉や兄さんたちが、
一段高い踊り場から銃を向ける
警備員たちに包囲されている。
言わんこっちゃない！
[wait][clear]
***************************************/
    wait(ref_40);
    ref_42 = msgShow(msg_6);
/***************************************
全体の位置関係から、舞耶姉たちは３階、俺と栄吉、
神取と警備員たちは、吹き抜けになっている４階の
踊り場にいることがわかった。
[wait][clear]
***************************************/
    wait(ref_42);
    ref_44 = msgShow(msg_7);
/***************************************
後は考えるより先に身体が動いた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_44);
    dialogFree(ref_35);
    unitMove(tatsuya, 1000, -2660, face_south, fastest);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitWait(tatsuya);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitMove(tatsuya, 1300, -2660, face_north, fastest);
    unitAnimationPlay(tatsuya, animation_2, 1);
    call(EIKITI);
    unitWait(tatsuya);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitSpriteClear(enemy3);
    unitSpriteSet(enemy3, sprite_dc);
    unitFace(enemy3, south);
    unitAnimationHold(enemy3, animation_1b, -1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_5, 1);
    sndMusicPlay(sound_321e, 127);
    delayClear();
    delayWait(30);
    unitSpriteClear(enemy3);
    unitSpriteSet(enemy3, sprite_dd);
    unitAnimationPlay(enemy3, animation_a, 1);
    unitMove(enemy3, 1300, -2770, face_south, reverse);
    unitAnimationPlay(enemy3, animation_a, 1);
    unitWait(enemy3);
    unitMove(enemy3, 1300, -2740, face_south, fast);
    unitAnimationPlay(enemy3, animation_a, 1);
    unitWait(enemy3);
    unitFace(enemy3, north);
    unitAnimationPlay(enemy3, animation_c, 1);
    unitWait(tatsuya);
    unitMove(tatsuya, 1150, -2700, face_east, fastest);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitWait(tatsuya);
    unitAnimationPlay(tatsuya, animation_0, 1);
    delayClear();
    delayWait(60);
    ref_6d = dialogAlloc();
    ref_6e = msgShow(msg_8);
/***************************************
俺は栄吉の横を駆け抜けざま、奴の腰を後ろから
思い切り蹴飛ばし、ドアの方に押しやった。
栄吉は顔からドアにぶち当たり、俺が来た通路の中へ
転がり込んでいく。
[wait][clear]
***************************************/
    wait(ref_6e);
    ref_70 = msgShow(msg_9);
/***************************************
その勢いで跳ね返った扉が閉まっていくのを視界の隅に
捉えながら、栄吉を蹴った反動を利用して身を捻り、
後ろにいた警備員を下から斬り上げた。
[wait][clear]
***************************************/
    wait(ref_70);
    ref_72 = msgShow(msg_10);
/***************************************
いきなり複数の標的が視界に飛び込むと、どちらを先に
撃てばいいのか一瞬混乱すると聞いたことがある。
そいつも結論を出せないまま絶命した。
[wait][clear]
***************************************/
    wait(ref_72);
    ref_74 = msgShow(msg_11);
/***************************************
即座に体勢を立て直し扉の向こうを振り向くと、
顔に派手な傷のあるグラサンの男が、まだ銃口から
薄く硝煙を上げる拳銃をこちらに向けていた。
[wait][clear]
***************************************/
    wait(ref_74);
    ref_76 = msgShow(msg_12);
/***************************************
動揺するどころか、口元に薄い笑みすら浮かべている。
皮肉と倦怠、伊達と酔狂、有り余る才能と虚無主義を
ブレンドすると、こんな男ができあがるのだろう。
[wait][clear]
***************************************/
    wait(ref_76);
    ref_78 = msgShow(msg_13);
/***************************************
こいつが神取だ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_78);
    dialogFree(ref_6d);
    ref_7c = bustupLoad(bustup_25);
    bustupWait(ref_7c);
    ref_7e = bustupAlloc(ref_7c, left, rgb(0,0,0));
    bustupFade(ref_7e, rgb(128,0,0), 30);
    ref_80 = dialogAlloc();
    ref_81 = msgShow(msg_14);
/***************************************
[color(yellow)]克哉[color(white)]
[tab][tatsuya]！？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_81);
    dialogFree(ref_80);
    ref_85 = bustupFade(ref_7e, rgb(0,0,0), 10);
    bustupWait(ref_85);
    bustupFree(ref_7e);
    ref_88 = dialogAlloc();
    ref_89 = msgShow(msg_15);
/***************************************
下から兄さんが俺の名を呼んだ。
今の一言の間に二人は倒せる。
仕方なく、ひどく月並みな台詞で背中を押した。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_89);
    dialogFree(ref_88);
    unitAnimationPlay(tatsuya, animation_d, 1);
    ref_8e = bustupLoad(bustup_b);
    bustupWait(ref_8e);
    ref_90 = bustupAlloc(ref_8e, left, rgb(0,0,0));
    bustupFade(ref_90, rgb(128,0,0), 30);
    ref_92 = dialogAlloc();
    ref_93 = msgShow(msg_16);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]早く逃げろ…！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_93);
    dialogFree(ref_92);
    ref_97 = bustupFade(ref_90, rgb(0,0,0), 10);
    bustupWait(ref_97);
    bustupFree(ref_90);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_3174, 127);
    sndMusicPlay(sound_3177, 127);
    sndMusicPlay(sound_3176, 127);
    sndMusicPlay(sound_3175, 127);
    unitSpawn(unit_14, sprite_44, 750, -400, -2700, west, none);
    unitDespawn(enemy2, none);
    unitSpawn(enemy1, sprite_dd, 1250, 0, -2700, east, none);
    unitAnimationPlay(enemy1, animation_c, 1);
    ref_a8 = dialogAlloc();
    ref_a9 = msgShow(msg_17);
/***************************************
全員、自分が何をすべきか思い出したようだ。
舞耶姉たちは慌てて逃げ出し、警備員たちも一斉に
銃を撃ち始めた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a9);
    dialogFree(ref_a8);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    unitAnimationPlay(unit_14, animation_b, 1);
    ref_b4 = bustupLoad(bustup_51);
    bustupWait(ref_b4);
    ref_b6 = bustupAlloc(ref_b4, right, rgb(0,0,0));
    bustupFade(ref_b6, rgb(128,0,0), 30);
    ref_b8 = dialogAlloc();
    ref_b9 = msgShow(msg_18);
/***************************************
[color(yellow)]神取[color(white)]
[tab]フッ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_b9);
    dialogFree(ref_b8);
    ref_bd = bustupFade(ref_b6, rgb(0,0,0), 10);
    bustupWait(ref_bd);
    bustupFree(ref_b6);
    unitAnimationPlay(unit_14, animation_10, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(unit_14, animation_11, 1);
    ref_c4 = efctAuraLoad();
    ref_c5 = bustupLoad(bustup_51);
    bustupWait(ref_c5);
    ref_c7 = bustupAlloc(ref_c5, right, rgb(0,0,0));
    bustupFade(ref_c7, rgb(128,0,0), 30);
    ref_c9 = dialogAlloc();
    ref_ca = msgShow(msg_19);
/***************************************
[color(yellow)]神取[color(white)]
[tab]どのみち彼らも君も、
[tab]運命から逃れることはできんぞ？
[tab]「特異点」の少年よ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ca);
    dialogFree(ref_c9);
    ref_ce = bustupFade(ref_c7, rgb(0,0,0), 10);
    bustupWait(ref_ce);
    bustupFree(ref_c7);
    ref_d1 = dialogAlloc();
    ref_d2 = msgShow(msg_20);
/***************************************
特異点。
今の一言で、俺とこの男の因縁を理解した。
俺にもやることがあった。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d2);
    dialogFree(ref_d1);
    ref_d6 = bustupLoad(bustup_b);
    bustupWait(ref_d6);
    ref_d8 = bustupAlloc(ref_d6, left, rgb(0,0,0));
    bustupFade(ref_d8, rgb(128,0,0), 30);
    ref_da = dialogAlloc();
    ref_db = msgShow(msg_21);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]そうか…
[tab]お前も魅入られたんだな、【奴】に。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_db);
    dialogFree(ref_da);
    ref_df = bustupFade(ref_d8, rgb(0,0,0), 10);
    bustupWait(ref_df);
    bustupFree(ref_d8);
    sndMusicPlay(sound_3178, 127);
    wait(ref_c4);
    unitAnimationHold(tatsuya, animation_12, -1);
    unitAura(tatsuya, true);
    ref_e6 = bustupLoad(bustup_b);
    bustupWait(ref_e6);
    ref_e8 = bustupAlloc(ref_e6, left, rgb(0,0,0));
    bustupFade(ref_e8, rgb(128,0,0), 30);
    ref_ea = dialogAlloc();
    ref_eb = msgShow(msg_22);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]なら【奴】に伝えろ…
[tab]舞耶姉や皆は、俺が守ってみせる！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_eb);
    dialogFree(ref_ea);
    ref_ef = bustupFade(ref_e8, rgb(0,0,0), 10);
    bustupWait(ref_ef);
    bustupFree(ref_e8);
    ref_f2 = dialogAlloc();
    ref_f3 = msgShow(msg_23);
/***************************************
この男は、須藤より深く俺と【奴】のことを知っている。
「特異点」。
その忌まわしい言葉が、どんな結末を意味するかも。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f3);
    dialogFree(ref_f2);
    unitAnimationPlay(unit_14, animation_23, 1);
    unitWait(unit_14);
    ref_f9 = bustupLoad(bustup_51);
    bustupWait(ref_f9);
    ref_fb = bustupAlloc(ref_f9, right, rgb(0,0,0));
    bustupFade(ref_fb, rgb(128,0,0), 30);
    ref_fd = dialogAlloc();
    ref_fe = msgShow(msg_24);
/***************************************
[color(yellow)]神取[color(white)]
[tab]伝えるまでもない。
[tab]聞いているよ、この通りな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_fe);
    dialogFree(ref_fd);
    ref_102 = bustupFade(ref_fb, rgb(0,0,0), 10);
    bustupWait(ref_102);
    bustupFree(ref_fb);
    sndMusicPlay(sound_3178, 127);
    unitAura(unit_14, true);
    delayClear();
    delayWait(60);
    unitAnimationPlay(tatsuya, animation_0, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(unit_14, animation_a, 1);
    ref_10d = bustupLoad(bustup_d);
    bustupWait(ref_10d);
    ref_10f = bustupAlloc(ref_10d, left, rgb(0,0,0));
    bustupFade(ref_10f, rgb(128,0,0), 30);
    ref_111 = dialogAlloc();
    ref_112 = msgShow(msg_25);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_112);
    dialogFree(ref_111);
    ref_116 = bustupFade(ref_10f, rgb(0,0,0), 10);
    bustupWait(ref_116);
    bustupFree(ref_10f);
    ref_119 = dialogAlloc();
    ref_11a = msgShow(msg_26);
/***************************************
神取が宿したペルソナは、明らかに【奴】の化身だった。
[wait][clear]
***************************************/
    wait(ref_11a);
    ref_11c = msgShow(msg_27);
/***************************************
俺と同じく、極限までペルソナの気配を消していたのだ。
目の当たりにするまで気づかなかった。
怒りが血管を拡張し、憎しみが全身を駆け巡る。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_11c);
    dialogFree(ref_119);
    sndMusicPlay(sound_4097, 127);
    ref_121 = bustupLoad(bustup_51);
    bustupWait(ref_121);
    ref_123 = bustupAlloc(ref_121, right, rgb(0,0,0));
    bustupFade(ref_123, rgb(128,0,0), 30);
    ref_125 = dialogAlloc();
    ref_126 = msgShow(msg_28);
/***************************************
[color(yellow)]神取[color(white)]
[tab]君が求めてやまぬ月が、
[tab]どうしてあれほど美しく輝くのか、
[tab]考えたことはあるかね？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_126);
    dialogFree(ref_125);
    ref_12a = bustupFade(ref_123, rgb(0,0,0), 10);
    bustupWait(ref_12a);
    bustupFree(ref_123);
    ref_12d = dialogAlloc();
    ref_12e = msgShow(msg_29);
/***************************************
熱い。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_12e);
    dialogFree(ref_12d);
    ref_132 = bustupLoad(bustup_51);
    bustupWait(ref_132);
    ref_134 = bustupAlloc(ref_132, right, rgb(0,0,0));
    bustupFade(ref_134, rgb(128,0,0), 30);
    ref_136 = dialogAlloc();
    ref_137 = msgShow(msg_30);
/***************************************
[color(yellow)]神取[color(white)]
[tab]日の光を反射しているからではない。
[tab]闇に包まれているからだ。
[tab]闇が深ければ深いほど、光は輝きを増すのだよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_137);
    dialogFree(ref_136);
    ref_13b = bustupFade(ref_134, rgb(0,0,0), 10);
    bustupWait(ref_13b);
    bustupFree(ref_134);
    ref_13e = dialogAlloc();
    ref_13f = msgShow(msg_31);
/***************************************
視界が狭まる。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_13f);
    dialogFree(ref_13e);
    ref_143 = bustupLoad(bustup_51);
    bustupWait(ref_143);
    ref_145 = bustupAlloc(ref_143, right, rgb(0,0,0));
    bustupFade(ref_145, rgb(128,0,0), 30);
    ref_147 = dialogAlloc();
    ref_148 = msgShow(msg_32);
/***************************************
[color(yellow)]神取[color(white)]
[tab]いずれ、天野[tab]舞耶も闇に堕ちる。
[tab]君も黒い太陽となりたまえ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_148);
    dialogFree(ref_147);
    ref_14c = bustupFade(ref_145, rgb(0,0,0), 10);
    bustupWait(ref_14c);
    bustupFree(ref_145);
    ref_14f = bustupLoad(bustup_d);
    bustupWait(ref_14f);
    ref_151 = bustupAlloc(ref_14f, left, rgb(0,0,0));
    bustupFade(ref_151, rgb(128,0,0), 30);
    ref_153 = dialogAlloc();
    ref_154 = msgShow(msg_33);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]オオオオオオオオオオオッ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_154);
    dialogFree(ref_153);
    ref_158 = bustupFade(ref_151, rgb(0,0,0), 10);
    bustupWait(ref_158);
    bustupFree(ref_151);
    unitAnimationHold(tatsuya, animation_4, -1);
    unitFace(unit_14, north);
    unitSpriteClear(unit_14);
    unitSpriteSet(unit_14, sprite_45);
    unitAnimationHold(unit_14, animation_6, -1);
    delayClear();
    delayWait(60);
    encounterLoad(encounter_47);
}

function DOA()
{
    sndMusicPlay(sound_316f, 127);
    delayClear();
    delayWait(70);
    sndStop(sound_316f);
}

function EIKITI()
{
    unitSpriteClear(eikichi);
    unitSpriteSet(eikichi, sprite_102);
    unitMove(eikichi, 1000, -2740, face_north, fastest);
    unitAnimationPlay(eikichi, animation_0, 1);
    unitWait(eikichi);
    unitMove(eikichi, 1000, -2850, face_north, fastest);
    unitAnimationPlay(eikichi, animation_0, 1);
    unitWait(eikichi);
    unitDespawn(eikichi, fade);
    objAnimRotate(obj_34, 0, 90, 0, 15, 0);
    objAnimWait(obj_34);
}
