function START()
{
    sndMusicPlay(sound_4058, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(south, 800, 0, -800);
    bitClear(bit_c7d);
    objAnimRotate(obj_a, 0, 360, 0, 1660, 1);
    objAnimRotate(obj_c, 0, 360, 0, 3200, 1);
    objAnimRotate(obj_b, 0, -360, 0, 2000, 1);
    objAnimRotate(obj_d, 0, -360, 0, 4000, 1);
    ref_9 = spriteLoad(sprite_18);
    wait(ref_9);
    ref_b = spriteLoad(sprite_0);
    wait(ref_b);
    ref_d = spriteLoad(sprite_6);
    wait(ref_d);
    ref_f = spriteLoad(sprite_d);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_13);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_3);
    wait(ref_13);
    ref_15 = spriteLoad(sprite_8);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_f);
    wait(ref_17);
    ref_19 = spriteLoad(sprite_15);
    wait(ref_19);
    ref_1b = spriteLoad(sprite_1a);
    wait(ref_1b);
    ref_1d = spriteLoad(sprite_12c);
    wait(ref_1d);
    ref_1f = spriteLoad(sprite_192);
    wait(ref_1f);
    ref_21 = spriteLoad(sprite_117);
    wait(ref_21);
    unitSpawn(tatsuya, sprite_18, 570, 0, -600, west, none);
    unitSpawn(maya, sprite_0, 640, 0, -540, west, none);
    unitAnimationPlay(maya, animation_a, 1);
    unitSpawn(ulala, sprite_6, 950, 0, -1050, east, none);
    unitAnimationPlay(ulala, animation_a, 1);
    unitSpawn(katsuya, sprite_d, 650, 0, -1050, south, none);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitSpawn(baofu, sprite_13, 950, 0, -550, north, none);
    unitAnimationPlay(baofu, animation_a, 1);
    unitSpawn(unit_58, sprite_12c, 800, 0, -450, north, none);
    unitAnimationPlay(unit_58, animation_3, 1);
    unitSpawn(unit_43, sprite_192, 800, 0, -800, east, none);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 1.46484375, true);
    screenFadeOuter(rgb(0,0,0), 1.46484375, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_37 = dialogAlloc();
    ref_38 = msgShow(msg_0);
/***************************************
[color(green)]塔の中央に、日輪のごとく光り輝く
大いなるものが座している。[color(white)]
[wait][clear]
***************************************/
    wait(ref_38);
    ref_3a = msgShow(msg_1);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]汝が内なる曼荼羅の、蓮華の華の上に座し、
[tab]森羅万象形成せしは、我偉大なる光照者の姿なり。
[tab]我は汝…[tab]汝こそが、ヴィローシャナの姿なり…
[wait][clear]
***************************************/
    wait(ref_3a);
    ref_3c = msgShow(msg_2);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]されば問う。
[tab]真なる自我「アートマン」とは何か？
[tab]汝が内に、汝の汝たる「我」は在るや否や？
[wait][clear]
***************************************/
    sync();
    wait(ref_3c);
    dialogFree(ref_37);
    ref_40 = bustupLoad(bustup_139);
    bustupWait(ref_40);
    ref_42 = bustupAlloc(ref_40, right, rgb(0,0,0));
    bustupFade(ref_42, rgb(128,0,0), 30);
    ref_44 = dialogAlloc();
    ref_45 = msgShow(msg_3);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]敬礼！[tab]この大いなるものは、
[tab]ヒンドゥの神々に敵対するアスラの王。
[tab]さて、貴様たちはなんと答えるのかな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_45);
    dialogFree(ref_44);
    ref_49 = bustupFade(ref_42, rgb(0,0,0), 10);
    bustupWait(ref_49);
    bustupFree(ref_42);
    unitAnimationPlay(katsuya, animation_1a, 1);
    ref_4d = bustupLoad(bustup_21);
    bustupWait(ref_4d);
    ref_4f = bustupAlloc(ref_4d, left, rgb(0,0,0));
    bustupFade(ref_4f, rgb(128,0,0), 30);
    ref_51 = dialogAlloc();
    ref_52 = msgShow(msg_4);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]古ウパニシャッド、
[tab]インド哲学の源流だな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_52);
    dialogFree(ref_51);
    ref_56 = bustupFade(ref_4f, rgb(0,0,0), 10);
    bustupWait(ref_56);
    bustupFree(ref_4f);
    unitAnimationPlay(ulala, animation_2d, 1);
    ref_5a = bustupLoad(bustup_1e);
    bustupWait(ref_5a);
    ref_5c = bustupAlloc(ref_5a, left, rgb(0,0,0));
    bustupFade(ref_5c, rgb(128,0,0), 30);
    ref_5e = dialogAlloc();
    ref_5f = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]え…[tab]こうやって考えてる私がいるってことは、
[tab]たぶん私はいるってことなんだろうけど…
[tab]じゃあ、私ってなに？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5f);
    dialogFree(ref_5e);
    ref_63 = bustupFade(ref_5c, rgb(0,0,0), 10);
    bustupWait(ref_63);
    bustupFree(ref_5c);
    unitAnimationPlay(ulala, animation_a, 1);
    unitAnimationPlay(baofu, animation_1d, 1);
    ref_68 = bustupLoad(bustup_2c);
    bustupWait(ref_68);
    ref_6a = bustupAlloc(ref_68, left, rgb(0,0,0));
    bustupFade(ref_6a, rgb(128,0,0), 30);
    ref_6c = dialogAlloc();
    ref_6d = msgShow(msg_6);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]くだらねぇこと聞きやがる…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6d);
    dialogFree(ref_6c);
    ref_71 = bustupFade(ref_6a, rgb(0,0,0), 10);
    bustupWait(ref_71);
    bustupFree(ref_6a);
    unitAnimationPlay(tatsuya, animation_10, 1);
    ref_75 = bustupLoad(bustup_10);
    bustupWait(ref_75);
    ref_77 = bustupAlloc(ref_75, left, rgb(0,0,0));
    bustupFade(ref_77, rgb(128,0,0), 30);
    ref_79 = dialogAlloc();
    ref_7a = msgShow(msg_7);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]いるに決まってるさ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7a);
    dialogFree(ref_79);
    ref_7e = bustupFade(ref_77, rgb(0,0,0), 10);
    bustupWait(ref_7e);
    bustupFree(ref_77);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(katsuya, animation_14, 1);
    ref_85 = bustupLoad(bustup_21);
    bustupWait(ref_85);
    ref_87 = bustupAlloc(ref_85, left, rgb(0,0,0));
    bustupFade(ref_87, rgb(128,0,0), 30);
    ref_89 = dialogAlloc();
    ref_8a = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]どうかな。
[tab]自我に固執する我執が、苦しみを生むとも言える。
[tab]これは、我々の己に対する態度への問いかけだな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_8a);
    dialogFree(ref_89);
    ref_8e = bustupFade(ref_87, rgb(0,0,0), 10);
    bustupWait(ref_8e);
    bustupFree(ref_87);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(60);
    ref_94 = bustupLoad(bustup_1);
    bustupWait(ref_94);
    ref_96 = bustupAlloc(ref_94, left, rgb(0,0,0));
    bustupFade(ref_96, rgb(128,0,0), 30);
    ref_98 = dialogAlloc();
    ref_99 = msgShow(msg_9);
/***************************************
[tab]汝が内に、汝の汝たる「我」は在るや否や？
[choice(2)]確かに、私という自我があるわ
ほんとは、自我なんて存在しないんじゃないかな…
[end_choice][clear]
***************************************/
    sync();
    wait(ref_99);
    dialogFree(ref_98);
    ref_9d = bustupFade(ref_96, rgb(0,0,0), 10);
    bustupWait(ref_9d);
    bustupFree(ref_96);
    choiceGetResult(var_5);
    bne(var_5, 0, label_c7);
    ref_a2 = dialogAlloc();
    ref_a3 = msgShow(msg_10);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]然り！
[wait][clear]
***************************************/
    wait(ref_a3);
    ref_a5 = msgShow(msg_11);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]水面に映る汝が姿こそ、真なる自我「アートマン」であり
[tab]宇宙の真理、梵「ブラフマン」である。
[tab]汝こそ宇宙であり、自我こそが魂を照らす光なり。
[wait][clear]
***************************************/
    wait(ref_a5);
    ref_a7 = msgShow(msg_12);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]その求道を賛助し、汝らが知己の、
[tab]内なる世界と外なる世界を結ぶ光明を授けよう。
[tab]梵我一如の理、忘るべからず…
[wait][clear]
***************************************/
    wait(ref_a7);
    screenFlash(255, 255, 255);
    sndMusicPlay(sound_32ee, 127);
    unitDespawn(unit_43, none);
    unitSpawn(npc1, sprite_117, 800, 0, -800, east, none);
    unitWait(unit_43);
    ref_ae = msgShow(msg_13);
/***************************************
[color(green)]大いなるものは消え去った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ae);
    dialogFree(ref_a2);
    msgVar_Item(msgvar_0, sun_card);
    ref_b3 = dialogAlloc();
    ref_b4 = msgShow(msg_14);
/***************************************
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_b4);
    dialogFree(ref_b3);
    partyItemAdd(sun_card, 200);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_bf = dialogAlloc();
    ref_c0 = msgShow(msg_15);
/***************************************
[color(green)]舞耶達は、理性のトラペゾヘドロンを手に入れ、
理性の塔を後にした。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c0);
    dialogFree(ref_bf);
    bitSet(bit_c7e);
    dngLoad2(kadath_mandala2-3);
    b(label_e7);
  label_c7:
    bne(var_5, 1, label_e7);
    ref_c8 = dialogAlloc();
    ref_c9 = msgShow(msg_16);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]では、我の前にいる汝はなんであるか。
[tab]梵我一如を否むこと、
[tab]即ち己と宇宙を無に帰すことと知れ。
[wait][clear]
***************************************/
    wait(ref_c9);
    ref_cb = msgShow(msg_17);
/***************************************
[color(yellow)]ヴィローシャナ[color(white)]
[tab]真理を覆い隠さんとする幻の女「マーヤー」よ、
[tab]消え失せよ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_cb);
    dialogFree(ref_c8);
    unitSpriteClear(tatsuya);
    unitSpriteSet(tatsuya, sprite_1a);
    sndMusicPlay(sound_32e9, 127);
    delayClear();
    delayWait(15);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    sndMusicPlay(sound_32c1, 127);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitAnimationHold(baofu, animation_4, -1);
    sndMusicPlay(sound_32e8, 127);
    delayClear();
    delayWait(30);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
    sndMusicPlay(sound_32e7, 127);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_8);
    sndMusicPlay(sound_32cc, 127);
    delayClear();
    delayWait(60);
    encounterLoad(encounter_49);
    b(label_e7);
  label_e7:
}
