function START()
{
    sndMusicPlay(sound_4080, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(north, 800, 0, -800);
    objAnimRotate(obj_a, 0, 360, 0, 1660, 1);
    objAnimRotate(obj_c, 0, 360, 0, 3200, 1);
    objAnimRotate(obj_b, 0, -360, 0, 2000, 1);
    objAnimRotate(obj_d, 0, -360, 0, 4000, 1);
    ref_8 = spriteLoad(sprite_18);
    wait(ref_8);
    ref_a = spriteLoad(sprite_0);
    wait(ref_a);
    ref_c = spriteLoad(sprite_6);
    wait(ref_c);
    ref_e = spriteLoad(sprite_d);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_13);
    wait(ref_10);
    ref_12 = spriteLoad(sprite_1a);
    wait(ref_12);
    ref_14 = spriteLoad(sprite_3);
    wait(ref_14);
    ref_16 = spriteLoad(sprite_8);
    wait(ref_16);
    ref_18 = spriteLoad(sprite_f);
    wait(ref_18);
    ref_1a = spriteLoad(sprite_15);
    wait(ref_1a);
    ref_1c = spriteLoad(sprite_12c);
    wait(ref_1c);
    ref_1e = spriteLoad(sprite_117);
    wait(ref_1e);
    unitSpawn(tatsuya, sprite_1a, 570, 0, -600, west, none);
    unitSpawn(maya, sprite_3, 640, 0, -540, west, none);
    unitSpawn(ulala, sprite_8, 950, 0, -1050, east, none);
    unitSpawn(katsuya, sprite_f, 650, 0, -1050, south, none);
    unitSpawn(baofu, sprite_15, 950, 0, -550, north, none);
    unitSpawn(npc1, sprite_117, 800, 0, -800, north, none);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    unitSpriteClear(tatsuya);
    unitSpriteSet(tatsuya, sprite_18);
    delayClear();
    delayWait(15);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_d);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_13);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_6);
    unitAnimationPlay(ulala, animation_a, 1);
    delayClear();
    delayWait(60);
    ref_42 = dialogAlloc();
    ref_43 = msgShow(msg_0);
/***************************************
[color(green)]ウムル・アト・タウィルが消え去った後に、
輝く光そのものが浮いている。[color(white)]
[wait][clear]
***************************************/
    wait(ref_43);
    screenFlash(255, 255, 255);
    sndMusicPlay(sound_32ee, 127);
    unitSpawn(unit_58, sprite_12c, 850, 0, -700, north, none);
    ref_48 = msgShow(msg_1);
/***************************************
[color(green)]その近くに、
空間をすり抜けるようにズーラが跳躍してきた。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_48);
    dialogFree(ref_42);
    ref_4c = bustupLoad(bustup_139);
    bustupWait(ref_4c);
    ref_4e = bustupAlloc(ref_4c, right, rgb(0,0,0));
    bustupFade(ref_4e, rgb(128,0,0), 30);
    ref_50 = dialogAlloc();
    ref_51 = msgShow(msg_2);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]グッド！
[tab]ウムル・アト・タウィルを退散させるとは、
[tab]賞賛の敬礼！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_51);
    dialogFree(ref_50);
    ref_55 = bustupFade(ref_4e, rgb(0,0,0), 10);
    bustupWait(ref_55);
    bustupFree(ref_4e);
    unitAnimationHold(unit_58, animation_6, -1);
    delayClear();
    delayWait(30);
    ref_5b = bustupLoad(bustup_b);
    bustupWait(ref_5b);
    ref_5d = bustupAlloc(ref_5b, left, rgb(0,0,0));
    bustupFade(ref_5d, rgb(128,0,0), 30);
    ref_5f = dialogAlloc();
    ref_60 = msgShow(msg_3);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]これが、詩織さんの心の欠片か…？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_60);
    dialogFree(ref_5f);
    ref_64 = bustupFade(ref_5d, rgb(0,0,0), 10);
    bustupWait(ref_64);
    bustupFree(ref_5d);
    unitAnimationPlay(unit_58, animation_0, 1);
    unitWait(unit_58);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_58, animation_1, 1);
    unitWait(unit_58);
    delayClear();
    delayWait(5);
    unitAnimationPlay(unit_58, animation_2, 1);
    ref_70 = bustupLoad(bustup_139);
    bustupWait(ref_70);
    ref_72 = bustupAlloc(ref_70, right, rgb(0,0,0));
    bustupFade(ref_72, rgb(128,0,0), 30);
    ref_74 = dialogAlloc();
    ref_75 = msgShow(msg_4);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]そう、これは宮代[tab]詩織の
[tab]「知識のトラペゾヘドロン」である。
[tab]覗いてみるがいい。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_75);
    dialogFree(ref_74);
    ref_79 = bustupFade(ref_72, rgb(0,0,0), 10);
    bustupWait(ref_79);
    bustupFree(ref_72);
    unitMove(tatsuya, 750, -750, face_west, medium);
    delayClear();
    delayWait(10);
    unitAnimationPlay(unit_58, animation_1, 1);
    unitWait(unit_58);
    delayClear();
    delayWait(10);
    unitAnimationPlay(unit_58, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_6, 1);
    ref_88 = dialogAlloc();
    ref_89 = msgShow(msg_5);
/***************************************
[color(green)]覗き込むと、様々な文字や言葉、数式や情報が、
刻々と変わる万華鏡の中のビーズのように、
集まっては散り散りになり、流れ、渦巻いていた。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_89);
    dialogFree(ref_88);
    unitAnimationPlay(tatsuya, animation_1, 1);
    ref_8e = bustupLoad(bustup_139);
    bustupWait(ref_8e);
    ref_90 = bustupAlloc(ref_8e, right, rgb(0,0,0));
    bustupFade(ref_90, rgb(128,0,0), 30);
    ref_92 = dialogAlloc();
    ref_93 = msgShow(msg_6);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]さて、ぐずぐずしている暇はないぞ。
[tab]ウムル・アト・タウィルが、より強力になって
[tab]戻ってくる前に、仕事を片付けるのだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_93);
    dialogFree(ref_92);
    ref_97 = bustupFade(ref_90, rgb(0,0,0), 10);
    bustupWait(ref_97);
    bustupFree(ref_90);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitAnimationPlay(katsuya, animation_1, 1);
    unitAnimationPlay(baofu, animation_d, 1);
    unitAnimationHold(ulala, animation_21, -1);
    delayClear();
    delayWait(90);
    unitAnimationPlay(ulala, animation_2c, 1);
    ref_a1 = bustupLoad(bustup_123);
    bustupWait(ref_a1);
    ref_a3 = bustupAlloc(ref_a1, left, rgb(0,0,0));
    bustupFade(ref_a3, rgb(128,0,0), 30);
    ref_a5 = dialogAlloc();
    ref_a6 = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]げー！
[tab]あれ死んでないの？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a6);
    dialogFree(ref_a5);
    ref_aa = bustupFade(ref_a3, rgb(0,0,0), 10);
    bustupWait(ref_aa);
    bustupFree(ref_a3);
    unitAnimationPlay(unit_58, animation_3, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    ref_b0 = bustupLoad(bustup_139);
    bustupWait(ref_b0);
    ref_b2 = bustupAlloc(ref_b0, right, rgb(0,0,0));
    bustupFade(ref_b2, rgb(128,0,0), 30);
    ref_b4 = dialogAlloc();
    ref_b5 = msgShow(msg_8);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]境界とはそういうものである。
[tab]あれがいなければ、貴様ら人間の意識と普遍的無意識の
[tab]境も無くなり、個人として存在できなくなるのだぞ。
[wait][clear]
***************************************/
    wait(ref_b5);
    unitAnimationPlay(maya, animation_a, 1);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(baofu, animation_1d, 1);
    unitAnimationPlay(ulala, animation_6, 1);
    delayClear();
    delayWait(30);
    ref_bd = msgShow(msg_9);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]では、次なるトラペゾヘドロンを求め、
[tab]カダスを旅するがよい。
[tab]ムーブ！[tab]ムーブ！[tab]ムーブ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_bd);
    dialogFree(ref_b4);
    ref_c1 = bustupFade(ref_b2, rgb(0,0,0), 10);
    bustupWait(ref_c1);
    bustupFree(ref_b2);
    msgVar_Item(msgvar_0, world_card);
    ref_c5 = dialogAlloc();
    ref_c6 = msgShow(msg_10);
/***************************************
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c6);
    dialogFree(ref_c5);
    partyItemAdd(world_card, 200);
    ref_cb = dialogAlloc();
    ref_cc = msgShow(msg_11);
/***************************************
[color(green)]舞耶達は、知識のトラペゾヘドロンを手に入れ、
知識の塔を後にした。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_cc);
    dialogFree(ref_cb);
    bitSet(bit_c7d);
    dngLoad2(kadath_mandala3-2);
}
