
msg_0:
[tab][tab][tab][tab][tab][tab][tab]ペルソナ２[tab][tab][tab]無影無踪[tab][tab][tab][tab][tab][tab][tab]
[end]

msg_1:
[clear][end]

msg_2:
[tab][tab][tab][tab][tab]○○月４日[tab][tab]ＡＭ：０３時１７分[tab][tab][tab][tab][tab]
[tab][tab][tab][tab][tab][tab][tab][tab][tab]ベルベットルーム[tab][tab][tab][tab][tab][tab][tab][tab][tab]
[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab]数日前[tab][tab][tab][tab][tab][tab][tab][tab][tab][tab][tab]
[end]

msg_3:
[clear][end]

msg_4:
[color(yellow)]イゴール[color(white)]
[tab]なるほど。
[tab]そのようなことがございましたか。
[sync][wait][clear][end]

msg_5:
[color(yellow)][tatsuya][color(white)]
[tab]どうにかなるか？
[sync][wait][clear][end]

msg_6:
[color(yellow)]イゴール[color(white)]
[tab]残念ながら、私の手に負える範疇を超えております。
[wait][clear][end]

msg_7:
[color(yellow)]イゴール[color(white)]
[tab]この肉体に宿る悪魔の意識を
[tab]普遍的無意識に帰還させることはできますが、
[tab]宮代様の意識を呼び戻すことはできません。
[wait][clear][end]

msg_8:
[color(yellow)]イゴール[color(white)]
[tab]ＪＯＫＥＲ使いのように、精神がペルソナに乗っ取られた
[tab]段階であればまだ手の施しようがありますが、
[tab]宮代様の心は肉体から切り離されてしまっております。
[wait][clear][end]

msg_9:
[color(yellow)]イゴール[color(white)]
[tab]恐らく、悪魔と入れ替えられた宮代様の自我や自己は、
[tab]普遍的無意識のカダス・マンダラと呼ばれる領域で
[tab]散り散りとなっておられるでしょう。
[sync][wait][clear][end]

msg_10:
[color(yellow)][tatsuya][color(white)]
[tab]カダス？
[sync][wait][clear][end]

msg_11:
[color(yellow)]イゴール[color(white)]
[tab]我が主、フィレモン様や這い寄る混沌が座す深淵より
[tab]一段浅き所にある、ペルソナや悪魔たちの元型が眠る
[tab]領域にございます。
[wait][clear][end]

msg_12:
[color(yellow)]イゴール[color(white)]
[tab][suou]様の分身たるペルソナも、カダスより来るもの。
[tab]皆様方が共有する、神話の神々のイメージが
[tab]生まれる場所、と言った方がわかりやすいですかな。
[wait][clear][end]

msg_13:
[color(yellow)]イゴール[color(white)]
[tab]かつて、夢見の力を体得し、自ら普遍的無意識の世界を
[tab]訪れることができた古のペルソナ使いたちは、
[tab]幻夢境とも呼んでおられました。
[sync][wait][clear][end]

msg_14:
[color(yellow)][tatsuya][color(white)]
[tab]幻夢境…[tab]そこに行けば、どうにかなるか？
[tab]教えてくれ、イゴール。
[tab]俺はこの人を助けたい。
[sync][wait][clear][end]

msg_15:
[color(yellow)]イゴール[color(white)]
[tab]人がその人であるためには、
[tab]驚くほど多くの定義が必要です。
[wait][clear][end]

msg_16:
[color(yellow)]イゴール[color(white)]
[tab]外界を認識し、己と他者を区別するために必要な
[tab]知覚、知識、記憶。
[tab]己の内界を認知するための、欲動や感情、知恵や機根。
[wait][clear][end]

msg_17:
[color(yellow)]イゴール[color(white)]
[tab]そして、普段は抑圧され秘められたコンプレックスですら
[tab]それら自我の統合性を保障する防衛機能として、
[tab]欠くべからざるものなのです。
[wait][clear][end]

msg_18:
[color(yellow)]イゴール[color(white)]
[tab]カダスへ赴き、それら宮代様を宮代様たらしめる
[tab]心のよすがを拾い集めることができれば、あるいは…
[sync][wait][clear][end]

msg_19:
[color(yellow)][tatsuya][color(white)]
[tab]わかった。
[tab]どうすれば、そのカダスへ行ける。
[sync][wait][clear][end]

msg_20:
[color(yellow)]イゴール[color(white)]
[tab]我が主フィレモン様か、
[tab]あなた様の怨敵、這い寄る混沌ならば、
[tab]すぐにでもカダスへの門を開けましょう。
[wait][clear][end]

msg_21:
[color(yellow)]イゴール[color(white)]
[tab]ですが、人々の心的エネルギーの多くが
[tab]影に流れている今、フィレモン様のお力は
[tab]大変弱くなっておられます。
[wait][clear][end]

msg_22:
[color(yellow)]イゴール[color(white)]
[tab]あなた様をカダスへ誘うことは、適いますまい。
[sync][wait][clear][end]

msg_23:
[color(yellow)][tatsuya][color(white)]
[tab]…さっき、自分で無意識の世界に行き来できる奴らが
[tab]いたと言ったな？
[tab]どうすれば、俺はそうなれる。
[sync][wait][clear][end]

msg_24:
[color(yellow)]イゴール[color(white)]
[tab]あなた様は、ペルソナ使いとして偉大な才能を
[tab]お持ちです。
[wait][clear][end]

msg_25:
[color(yellow)]イゴール[color(white)]
[tab]良き師の元で修練を積めば、自ら夢の中で
[tab]心の深淵の門を開くことができるようになりましょう。
[wait][clear][end]

msg_26:
[color(yellow)]イゴール[color(white)]
[tab]園村[tab]麻希様なども、
[tab]半ばその境地に達しておいでです。
[wait][clear][end]

msg_27:
[color(yellow)]イゴール[color(white)]
[tab]ですが、それには時間がかかります。
[tab]その間に、千千に砕けた宮代様の心は、
[tab]普遍的無意識に溶け消えてしまうでしょう。
[sync][wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]他に方法はないのか！？
[sync][wait][clear][end]

msg_29:
[color(yellow)]イゴール[color(white)]
[tab]ただ一人、人間としてこの覚醒の世界と
[tab]無意識の世界を隔てる「窮極の門」を、
[tab]物理的に開くことができる鍵を持つお方がおられます。
[wait][clear][end]

msg_30:
[color(yellow)]イゴール[color(white)]
[tab]伝説のペルソナ使い、
[tab]チャンドラプトラ師をご紹介しましょう。
[wait][clear][end]

msg_31:
[color(yellow)]イゴール[color(white)]
[tab]師の持っておられる「銀の鍵」であれば、
[tab]深淵なるカダスへの扉、開くことができるでしょう。
[wait][clear][end]

msg_32:
[color(yellow)]イゴール[color(white)]
[tab]ですが、無意識の探求は大変危険な旅ですぞ。
[tab]カダスは、神々や悪魔が、我が主や這い寄る混沌に
[tab]庇護される世界。
[wait][clear][end]

msg_33:
[color(yellow)]イゴール[color(white)]
[tab]そこを旅する者の精神は、常に危険に晒されます。
[wait][clear][end]

msg_34:
[color(yellow)]イゴール[color(white)]
[tab]隙を見せれば、あなたにとって代わろうとする悪魔に
[tab]肉体と精神を乗っ取られ、宮代様と同じように
[tab]なってしまうでしょう。
[sync][wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]かまわない。
[sync][wait][clear][end]

msg_36:
[color(yellow)]イゴール[color(white)]
[tab]わかりました。
[tab]しかし、師はご多忙な時空の旅人。
[tab]お呼びするまで、少々時間がかかります。
[wait][clear][end]

msg_37:
[color(yellow)]イゴール[color(white)]
[tab]また後ほどお越しください。
[tab]宮代様の肉体は、
[tab]私が責任を持ってお預かり致しましょう。
[sync][wait][clear][end]
