function START()
{
    sndMusicPlay(sound_406b, 90);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(southwest, 500, 0, -800);
    ref_4 = spriteLoad(sprite_18);
    wait(ref_4);
    ref_6 = spriteLoad(sprite_1a);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_194);
    wait(ref_8);
    ref_a = spriteLoad(sprite_12e);
    wait(ref_a);
    ref_c = spriteLoad(sprite_120);
    wait(ref_c);
    ref_e = spriteLoad(sprite_121);
    wait(ref_e);
    ref_10 = spriteLoad(sprite_eb);
    wait(ref_10);
    unitSpawn(tatsuya, sprite_1a, 500, 0, -800, north, none);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitSpawn(enemy3, sprite_194, 550, 0, -950, south, none);
    unitSpawn(enemy1, sprite_120, 500, 0, -550, north, none);
    unitSpawn(enemy2, sprite_121, 350, 0, -1050, south, none);
    unitAnimationPlay(enemy2, animation_5, 1);
    unitSpawn(enemy4, sprite_eb, 400, 0, -700, north, none);
    unitAnimationPlay(enemy4, animation_1, 1);
    unitSpawn(enemy5, sprite_eb, 560, 0, -680, north, none);
    unitAnimationPlay(enemy5, animation_3, 1);
    unitSpawn(enemy7, sprite_eb, 350, 0, -1050, north, none);
    unitAnimationPlay(enemy7, animation_0, 1);
    unitSpawn(unit_4b, sprite_eb, 370, 0, -960, north, none);
    unitAnimationPlay(unit_4b, animation_2, 1);
    unitSpawn(unit_4c, sprite_eb, 400, 0, -850, north, none);
    unitAnimationPlay(unit_4c, animation_2, 1);
    unitShadowRadius(enemy4, 0);
    unitShadowRadius(enemy5, 0);
    unitShadowRadius(enemy7, 0);
    unitShadowRadius(unit_4b, 0);
    unitShadowRadius(unit_4c, 0);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    unitAnimationPlay(tatsuya, animation_5, 1);
    sndMusicPlay(sound_321e, 127);
    unitMove(enemy3, 550, -1000, face_south, reverse);
    unitAnimationPlay(enemy3, animation_0, 1);
    unitWait(enemy3);
    ref_32 = dialogAlloc();
    ref_33 = msgShow(msg_0);
/***************************************
[color(yellow)]悪魔化した詩織[color(white)]
[tab]Ｈｙｏｏｏｏｏａａａａａ！
[wait][clear]
***************************************/
    sync();
    wait(ref_33);
    dialogFree(ref_32);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_3305, 127);
    unitSpriteClear(enemy3);
    unitSpriteSet(enemy3, sprite_12e);
    unitWait(enemy3);
    unitFace(enemy3, west);
    unitAnimationPlay(enemy3, animation_1, 1);
    ref_45 = dialogAlloc();
    ref_46 = msgShow(msg_1);
/***************************************
俺は詩織さんを床に叩き落すと、床を這っていた太い
麻酔のパイプを刀でぶった切り、パイプから吹き出る
液化ガスを詩織さんにぶっ掛けた。
[wait][clear]
***************************************/
    wait(ref_46);
    ref_48 = msgShow(msg_2);
/***************************************
[color(yellow)]悪魔化した詩織[color(white)]
[tab]Ｆｓｈｏｏｏｏａａａａａ！
[wait][clear]
***************************************/
    wait(ref_48);
    ref_4a = msgShow(msg_3);
/***************************************
詩織さんは立ち上がろうと牙を剥く。
耳まで裂けたその口めがけて、
思いっきりパイプを突っ込んだ。
[wait][clear]
***************************************/
    wait(ref_4a);
    ref_4c = msgShow(msg_4);
/***************************************
[color(yellow)]悪魔化した詩織[color(white)]
[tab]Ｇｏｂｏｏｏｏａａａａａ………
[wait][clear]
***************************************/
    wait(ref_4c);
    ref_4e = msgShow(msg_5);
/***************************************
徐々にガボガボいっていた詩織さんの身体が弛緩し、
大人しくなっていく。
どれだけ食わせればいいのか見当がつかない。
揮発したガスのせいか、頭がくらくらしてきた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4e);
    dialogFree(ref_45);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_2, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_3, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_4, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_3, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    ref_78 = dialogAlloc();
    ref_79 = msgShow(msg_6);
/***************************************
[color(yellow)]小月[color(white)]
[tab]も、もう十分だ…
[wait][clear]
***************************************/
    sync();
    wait(ref_79);
    dialogFree(ref_78);
    unitSpriteClear(tatsuya);
    unitSpriteSet(tatsuya, sprite_18);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitAnimationPlay(tatsuya, animation_4, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitFace(tatsuya, east);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(120);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    ref_9e = dialogAlloc();
    ref_9f = msgShow(msg_7);
/***************************************
部屋の隅で震えていた小月が、タンクの元栓を締めた。
中年の男に目をやると、うれしそうに目を見開き
凍り付いて死んでいた。
[wait][clear]
***************************************/
    sync();
    wait(ref_9f);
    dialogFree(ref_9e);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(5);
    unitFace(tatsuya, south);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(30);
    ref_b0 = bustupLoad(bustup_b);
    bustupWait(ref_b0);
    ref_b2 = bustupAlloc(ref_b0, left, rgb(0,0,0));
    bustupFade(ref_b2, rgb(128,0,0), 30);
    ref_b4 = dialogAlloc();
    ref_b5 = msgShow(msg_8);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]…どれくらいもつ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_b5);
    dialogFree(ref_b4);
    ref_b9 = bustupFade(ref_b2, rgb(0,0,0), 10);
    bustupWait(ref_b9);
    bustupFree(ref_b2);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitWait(enemy1);
    ref_be = dialogAlloc();
    ref_bf = msgShow(msg_9);
/***************************************
[color(yellow)]小月[color(white)]
[tab]たぶん、２時間くらいだろう。
[tab]アフリカ象でも、三日はピクリともないはずの量だが…
[wait][clear]
***************************************/
    wait(ref_bf);
    ref_c1 = msgShow(msg_10);
/***************************************
小月は、俺の脇に来て詩織さんを見下ろした。
中年の男の死体にも目をやったが、慌てて目を背けた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_c1);
    dialogFree(ref_be);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_6, 1);
    unitWait(tatsuya);
    ref_cb = bustupLoad(bustup_10);
    bustupWait(ref_cb);
    ref_cd = bustupAlloc(ref_cb, left, rgb(0,0,0));
    bustupFade(ref_cd, rgb(128,0,0), 30);
    ref_cf = dialogAlloc();
    ref_d0 = msgShow(msg_11);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]…さっきは、悪かった。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d0);
    dialogFree(ref_cf);
    ref_d4 = bustupFade(ref_cd, rgb(0,0,0), 10);
    bustupWait(ref_d4);
    bustupFree(ref_cd);
    ref_d7 = dialogAlloc();
    ref_d8 = msgShow(msg_12);
/***************************************
中年男が詩織さんの戒めを解かなかったら、
俺は憎しみに駆られて小月を殺していたかもしれない。
[wait][clear]
***************************************/
    wait(ref_d8);
    ref_da = msgShow(msg_13);
/***************************************
こいつは詩織さんをこんな風にする実験に加担したが、
眠らせるヒントはくれた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_da);
    dialogFree(ref_d7);
    unitAnimationPlay(enemy1, animation_2, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_4, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_2, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitWait(enemy1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    ref_f8 = dialogAlloc();
    ref_f9 = msgShow(msg_14);
/***************************************
[color(yellow)]小月[color(white)]
[tab]…いや、いいんだ。
[tab]この女性は君の知り合いなんだろう？
[tab]殺されても文句は言えないよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_f9);
    dialogFree(ref_f8);
    unitAnimationPlay(tatsuya, animation_6, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(10);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitFace(tatsuya, east);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_4, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(120);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitWait(tatsuya);
    ref_124 = bustupLoad(bustup_b);
    bustupWait(ref_124);
    ref_126 = bustupAlloc(ref_124, left, rgb(0,0,0));
    bustupFade(ref_126, rgb(128,0,0), 30);
    ref_128 = dialogAlloc();
    ref_129 = msgShow(msg_15);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]神条…
[tab]神取とかいう男は、この先だと言ったな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_129);
    dialogFree(ref_128);
    ref_12d = bustupFade(ref_126, rgb(0,0,0), 10);
    bustupWait(ref_12d);
    bustupFree(ref_126);
    ref_130 = dialogAlloc();
    ref_131 = msgShow(msg_16);
/***************************************
[color(yellow)]小月[color(white)]
[tab]ああ。
[tab]他の侵入者を歓迎する間、
[tab]君を足止めするようにと言っていた。
[wait][clear]
***************************************/
    wait(ref_131);
    ref_133 = msgShow(msg_17);
/***************************************
[color(yellow)]小月[color(white)]
[tab]ＪＳＭ…[tab]ＪＯＫＥＲをＪＯＫＥＲ使いから
[tab]分離するマシンは、この先の通路の突き当たりだ。
[tab]神取はそこにいる。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_133);
    dialogFree(ref_130);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitFace(tatsuya, north);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(60);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitWait(tatsuya);
    ref_14e = bustupLoad(bustup_b);
    bustupWait(ref_14e);
    ref_150 = bustupAlloc(ref_14e, left, rgb(0,0,0));
    bustupFade(ref_150, rgb(128,0,0), 30);
    ref_152 = dialogAlloc();
    ref_153 = msgShow(msg_18);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]すぐ戻る。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_153);
    dialogFree(ref_152);
    ref_157 = bustupFade(ref_150, rgb(0,0,0), 10);
    bustupWait(ref_157);
    bustupFree(ref_150);
    unitAnimationPlay(tatsuya, animation_3, 1);
    unitWait(tatsuya);
    delayClear();
    delayWait(3);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitWait(tatsuya);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    unitMove(tatsuya, 500, -950, face_north, medium);
    unitWait(tatsuya);
    unitMove(tatsuya, 750, -950, face_north, medium);
    ref_167 = dialogAlloc();
    ref_168 = msgShow(msg_19);
/***************************************
俺は詩織さんを残して、
小月が示した奥へ続くドアに駆け出した。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_168);
    dialogFree(ref_167);
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_316a, 127);
    ref_16f = dialogAlloc();
    ref_170 = msgShow(msg_20);
/***************************************
神取[tab]鷹久、名前だけは知っている。
[wait][clear]
***************************************/
    wait(ref_170);
    ref_172 = msgShow(msg_21);
/***************************************
３年前、御影町の事件でゆきのさんたちが
倒したはずの男だ。
そんな男がここにいる。
[wait][clear]
***************************************/
    wait(ref_172);
    ref_174 = msgShow(msg_22);
/***************************************
偶然のはずがない。
[wait][clear]
***************************************/
    wait(ref_174);
    ref_176 = msgShow(msg_23);
/***************************************
そのＪＳＭとやらが、この研究所の研究の核なのだろう。
でなければ、これほど大掛かりに噂を操作して
ＪＯＫＥＲを増やそうとするはずがない。
[wait][clear]
***************************************/
    wait(ref_176);
    ref_178 = msgShow(msg_24);
/***************************************
新世塾とやらにとって、ＪＯＫＥＲは
数が問題なのだろう。
[wait][clear]
***************************************/
    wait(ref_178);
    ref_17a = msgShow(msg_25);
/***************************************
ドアを抜けると、左右に同じような研究室のものと
思しき扉が並ぶ通路が続き、やがて突き当たりに
周囲とは違う鉄製のドアが現れた。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_17a);
    dialogFree(ref_16f);
    sndMusicPlay(sound_3011, 127);
    ref_17f = dialogAlloc();
    ref_180 = msgShow(msg_26);
/***************************************
[color(yellow)]栄吉の声[color(white)]
[tab]俺なんかのために…
[tab]ダメだぁ…！！
[wait][clear]
***************************************/
    wait(ref_180);
    ref_182 = msgShow(msg_27);
/***************************************
ドアの前に立つと、かすかに栄吉の絶叫が聞こえてきた。
どうやら捕まって連れてこられたらしい。
舞耶姉たちを脅す人質だろう。
[wait][clear]
***************************************/
    wait(ref_182);
    ref_184 = msgShow(msg_28);
/***************************************
[color(yellow)]渋い男の声[color(white)]
[tab]やはりまだ子供か…[tab]失望したよ。
[tab]些事のために目的を失うようでは、
[tab]企業家など務まらんぞ？
[wait][clear]
***************************************/
    wait(ref_184);
    ref_186 = msgShow(msg_29);
/***************************************
この声が神取という男に違いない。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_186);
    dialogFree(ref_17f);
    sndMusicPlay(sound_316e, 127);
    ref_18b = dialogAlloc();
    ref_18c = msgShow(msg_30);
/***************************************
[color(yellow)]渋い男の声[color(white)]
[tab]私が切り捨て方を教えてあげよう。
[wait][clear]
***************************************/
    wait(ref_18c);
    ref_18e = msgShow(msg_31);
/***************************************
栄吉が危ないことは、会話の内容で察しが着いた。
声の位置からして、栄吉は俺の右手側、神取は左手だ。
[wait][clear]
***************************************/
    wait(ref_18e);
    ref_190 = msgShow(msg_32);
/***************************************
大体、二人の間にちょうど目の前のドアがあるはずだ。
扉の蝶番は内側にはない。外開きってことだ。
[wait][clear]
***************************************/
    wait(ref_190);
    ref_192 = msgShow(msg_33);
/***************************************
俺は神取が扉にぶち当たるのを期待して、
めいいっぱい力を込めて扉を開け放ち、
向こう側に飛び出した。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_192);
    dialogFree(ref_18b);
    sndMusicPlay(sound_316f, 127);
    delayClear();
    delayWait(70);
    eventFileLoad(E, 261);
}
