function START()
{
    sndMusicPlay(sound_3028, 127);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(north, 800, 0, -800);
    bitClear(bit_c85);
    objAnimRotate(obj_a, 0, 360, 0, 1660, 1);
    objAnimRotate(obj_c, 0, 360, 0, 3200, 1);
    objAnimRotate(obj_b, 0, -360, 0, 2000, 1);
    objAnimRotate(obj_d, 0, -360, 0, 4000, 1);
    ref_9 = spriteLoad(sprite_18);
    wait(ref_9);
    ref_b = spriteLoad(sprite_0);
    wait(ref_b);
    ref_d = spriteLoad(sprite_6);
    wait(ref_d);
    ref_f = spriteLoad(sprite_d);
    wait(ref_f);
    ref_11 = spriteLoad(sprite_13);
    wait(ref_11);
    ref_13 = spriteLoad(sprite_3);
    wait(ref_13);
    ref_15 = spriteLoad(sprite_8);
    wait(ref_15);
    ref_17 = spriteLoad(sprite_f);
    wait(ref_17);
    ref_19 = spriteLoad(sprite_15);
    wait(ref_19);
    ref_1b = spriteLoad(sprite_1a);
    wait(ref_1b);
    ref_1d = spriteLoad(sprite_14);
    wait(ref_1d);
    ref_1f = spriteLoad(sprite_12c);
    wait(ref_1f);
    ref_21 = spriteLoad(sprite_18a);
    wait(ref_21);
    ref_23 = spriteLoad(sprite_117);
    wait(ref_23);
    unitSpawn(tatsuya, sprite_18, 680, 0, -980, south, none);
    unitSpawn(maya, sprite_0, 600, 0, -950, south, none);
    unitAnimationPlay(maya, animation_a, 1);
    unitSpawn(ulala, sprite_6, 750, 0, -1100, south, none);
    unitAnimationPlay(ulala, animation_0, 1);
    unitSpawn(katsuya, sprite_d, 570, 0, -650, west, none);
    unitAnimationPlay(katsuya, animation_b, 1);
    unitSpawn(baofu, sprite_13, 940, 0, -1050, east, none);
    unitAnimationPlay(baofu, animation_d, 1);
    unitSpawn(unit_58, sprite_12c, 650, 0, -1100, south, none);
    unitSpawn(unit_43, sprite_18a, 850, 0, -700, north, none);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_36 = dialogAlloc();
    ref_37 = msgShow(msg_0);
/***************************************
[color(green)]塔の中央に、忌まわしくもおぞましい
大いなる旧支配者が座している。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_37);
    dialogFree(ref_36);
    unitAnimationHold(ulala, animation_22, -1);
    ref_3c = bustupLoad(bustup_123);
    bustupWait(ref_3c);
    ref_3e = bustupAlloc(ref_3c, left, rgb(0,0,0));
    bustupFade(ref_3e, rgb(128,0,0), 30);
    ref_40 = dialogAlloc();
    ref_41 = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ぎゃあああぁぁぁ！！
[tab]名状し難いぃぃぃ！！！！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_41);
    dialogFree(ref_40);
    ref_45 = bustupFade(ref_3e, rgb(0,0,0), 10);
    bustupWait(ref_45);
    bustupFree(ref_3e);
    ref_48 = dialogAlloc();
    ref_49 = msgShow(msg_2);
/***************************************
[color(yellow)]クトゥルフ[color(white)]
[tab]Ｐｈ’ｎｇｌｕｉ[tab]ｍｇｌｗ’ｎａｆｈ
[tab]Ｃｔｈｕｌｈｕ[tab]Ｒ’ｌｙｅｈ
[tab]ｍｇａｈ’ｎａｇｌ[tab]ｆｈｔａｇｎ・・・
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_49);
    dialogFree(ref_48);
    unitAnimationPlay(ulala, animation_29, 1);
    ref_4e = bustupLoad(bustup_139);
    bustupWait(ref_4e);
    ref_50 = bustupAlloc(ref_4e, right, rgb(0,0,0));
    bustupFade(ref_50, rgb(128,0,0), 30);
    ref_52 = dialogAlloc();
    ref_53 = msgShow(msg_3);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]「ルルイエの館にて
[tab][tab]死せるクトゥルフ
[tab][tab]夢見るままに待ちいたり」
[wait][clear]
***************************************/
    wait(ref_53);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitAnimationPlay(maya, animation_b, 1);
    unitAnimationPlay(ulala, animation_3, 1);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(5);
    unitWait(tatsuya);
    unitWait(maya);
    unitWait(ulala);
    unitWait(katsuya);
    unitWait(baofu);
    unitAnimationPlay(tatsuya, animation_2, 1);
    unitAnimationPlay(maya, animation_c, 1);
    unitAnimationPlay(ulala, animation_4, 1);
    unitAnimationPlay(katsuya, animation_d, 1);
    unitAnimationPlay(baofu, animation_b, 1);
    delayClear();
    delayWait(5);
    unitWait(tatsuya);
    unitFace(tatsuya, west);
    unitAnimationPlay(tatsuya, animation_3, 1);
    ref_6b = msgShow(msg_4);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]この旧支配者は、かつて古のものと地球の覇権を争い、
[tab]彼のものたちの都市をことごとく破壊し、
[tab]全ての海洋とムー大陸を支配した大いなるもの。
[wait][clear]
***************************************/
    wait(ref_6b);
    unitAnimationPlay(unit_58, animation_3, 1);
    ref_6e = msgShow(msg_5);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]今もなお、太平洋に沈んだ狂気の都、
[tab]ルルイエに封じられているが
[tab]死んではいない。
[wait][clear]
***************************************/
    wait(ref_6e);
    ref_70 = msgShow(msg_6);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]「そは永久に伏する死者にあらず
[tab][tab]旺遠なる時を経て
[tab][tab]死すらも死ぬるものなれば」
[wait][clear]
***************************************/
    wait(ref_70);
    unitAnimationPlay(unit_58, animation_0, 1);
    unitAnimationPlay(katsuya, animation_a, 1);
    ref_74 = msgShow(msg_7);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]深海の底から人々に悪夢を送り、狂える信徒どもを
[tab]増やし彼らの精神を貪り、再び地上に君臨する日を
[tab]待っているのだ。その日は必ずやってくる。
[wait][clear]
***************************************/
    wait(ref_74);
    unitAnimationHold(katsuya, animation_21, -1);
    ref_77 = msgShow(msg_8);
/***************************************
[color(yellow)]猫中将ズーラ[color(white)]
[tab]星辰が再び正しき道を示す時、
[tab]旧支配者たちは無数の眷属を連れて復活し、
[tab]宇宙は再び彼らのものとなるのだ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_77);
    dialogFree(ref_52);
    ref_7b = bustupFade(ref_50, rgb(0,0,0), 10);
    bustupWait(ref_7b);
    bustupFree(ref_50);
    delayClear();
    delayWait(30);
    unitAnimationPlay(tatsuya, animation_0, 1);
    unitAnimationPlay(maya, animation_b, 1);
    unitAnimationPlay(ulala, animation_3, 1);
    unitAnimationPlay(katsuya, animation_0, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(5);
    unitWait(tatsuya);
    unitWait(maya);
    unitWait(ulala);
    unitWait(baofu);
    unitAnimationPlay(tatsuya, animation_1, 1);
    unitAnimationPlay(maya, animation_a, 1);
    unitAnimationPlay(ulala, animation_0, 1);
    unitAnimationPlay(baofu, animation_d, 1);
    delayClear();
    delayWait(5);
    unitWait(tatsuya);
    unitAnimationPlay(tatsuya, animation_2, 1);
    delayClear();
    delayWait(60);
    ref_95 = dialogAlloc();
    ref_96 = msgShow(msg_9);
/***************************************
[color(green)]大いなる旧支配者の、冒寺的な粘液滴る触手に、
光輝く意志のトラペゾヘドロンが握られている。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_96);
    dialogFree(ref_95);
    unitAnimationPlay(katsuya, animation_28, 1);
    unitWait(katsuya);
    ref_9c = bustupLoad(bustup_25);
    bustupWait(ref_9c);
    ref_9e = bustupAlloc(ref_9c, left, rgb(0,0,0));
    bustupFade(ref_9e, rgb(128,0,0), 30);
    ref_a0 = dialogAlloc();
    ref_a1 = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]心を貪り粋らうだと…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a1);
    dialogFree(ref_a0);
    ref_a5 = bustupFade(ref_9e, rgb(0,0,0), 10);
    bustupWait(ref_a5);
    bustupFree(ref_9e);
    unitAnimationPlay(baofu, animation_1d, 1);
    ref_a9 = bustupLoad(bustup_2e);
    bustupWait(ref_a9);
    ref_ab = bustupAlloc(ref_a9, left, rgb(0,0,0));
    bustupFade(ref_ab, rgb(128,0,0), 30);
    ref_ad = dialogAlloc();
    ref_ae = msgShow(msg_11);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]生憎、もう地上はクソみてぇな人間様で満員御礼でな。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_ae);
    dialogFree(ref_ad);
    ref_b2 = bustupFade(ref_ab, rgb(0,0,0), 10);
    bustupWait(ref_b2);
    bustupFree(ref_ab);
    unitFace(tatsuya, south);
    unitSpriteClear(tatsuya);
    unitSpriteSet(tatsuya, sprite_1a);
    sndMusicPlay(sound_32e9, 127);
    ref_b9 = bustupLoad(bustup_d);
    bustupWait(ref_b9);
    ref_bb = bustupAlloc(ref_b9, left, rgb(0,0,0));
    bustupFade(ref_bb, rgb(128,0,0), 30);
    ref_bd = dialogAlloc();
    ref_be = msgShow(msg_12);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ずっと、寝ていてもらおうか！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_be);
    dialogFree(ref_bd);
    ref_c2 = bustupFade(ref_bb, rgb(0,0,0), 10);
    bustupWait(ref_c2);
    bustupFree(ref_bb);
    unitSpriteClear(katsuya);
    unitSpriteSet(katsuya, sprite_f);
    sndMusicPlay(sound_32c1, 127);
    unitSpriteClear(baofu);
    unitSpriteSet(baofu, sprite_15);
    unitAnimationHold(baofu, animation_4, -1);
    sndMusicPlay(sound_32e8, 127);
    delayClear();
    delayWait(30);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_3);
    sndMusicPlay(sound_32e7, 127);
    unitSpriteClear(ulala);
    unitSpriteSet(ulala, sprite_8);
    sndMusicPlay(sound_32cc, 127);
    delayClear();
    delayWait(60);
    encounterLoad(encounter_50);
}
