
msg_0:
[color(green)]クトゥルフが消え去った後に、
輝く光そのものが浮いている。[color(white)]
[wait][clear][end]

msg_1:
[color(green)]その近くに、
空間をすり抜けるようにズーラが跳躍してきた。[color(white)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]ウェルダン、プラトゥーン！
[tab]クトゥルフすら退散させるとは、激賞の敬礼！
[wait][clear][end]

msg_3:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]ペルソナ使いでなければ、
[tab]彼のものの姿を見たり、
[tab]接触しただけで発狂していたであろう。
[sync][wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]あんなのも、私たちの心の中にいるの？
[tab]あまりにも違いすぎやしない？
[sync][wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]じわじわと心を贈む狂気、
[tab]忍び寄る恐怖が形を与えたもうたもの…
[tab]といったところか。
[sync][wait][clear][end]

msg_6:
[color(yellow)]パオフゥ[color(white)]
[tab]今日日、イカレちまった奴なんざ珍しくもねぇからな。
[tab]案外、一皮剥きゃ中身はあんな化け物が、
[tab]もう街中闊歩してるのかもしれんぜ？
[wait][clear][end]

msg_7:
[color(yellow)]パオフゥ[color(white)]
[tab]連日のように子殺しのニュースが流れたり、
[tab]毎年３万人が自殺してる国がまともなわきゃねぇ。
[tab]おっそろしい世の中だぜ…
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]どうすれば、俺たちはまともでいられるんだ…？
[sync][wait][clear][end]

msg_9:
[tab]どうすれば、俺たちはまともでいられるんだ…？
[choice(2)]レッツ・ポジティブシンキングよ、[tatsuya]君。
どうすればいいんだろ…
[end_choice][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]はいはい、言うと思った。
[sync][wait][clear][end]

msg_11:
[color(yellow)]パオフゥ[color(white)]
[tab]お得意の呪文だな。
[sync][wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]自己暗示だろうと構わんさ。
[tab]病は気からと言うじゃないか。
[sync][wait][clear][end]

msg_13:
[color(yellow)][tatsuya][color(white)]
[tab]…そうだな。
[tab]暗闇ばかり見ている必要はないんだ。
[wait][clear][end]

msg_14:
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉、ありがとう…
[sync][wait][clear][end]

msg_15:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]どうもこうもねぇ。
[tab]自分って奴を、しっかり持つしかねぇな。
[tab]あとは、一息つける旨い酒がありゃいいさ。
[sync][wait][clear][end]

msg_17:
[color(yellow)]克哉[color(white)]
[tab]政治参加の意識を持つことも大切だな。
[tab]勿論、権利を叫ぶだけでなく義務を果たした上でだが。
[tab]我々は一人で生きているわけじゃないからな。
[sync][wait][clear][end]

msg_18:
[color(yellow)]うらら[color(white)]
[tab]それと、思いやりかな…
[tab]ひとりひとりが優しい世の中なら、
[tab]みんなハッピーになれるわよ…[tab]なんてね。
[sync][wait][clear][end]

msg_19:
[color(yellow)][tatsuya][color(white)]
[tab]一人で生きているわけじゃない…
[tab]そうか…
[tab]そうだな。
[sync][wait][clear][end]

msg_20:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを５０枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_21:
[color(green)]舞耶達は、意志のトラペゾヘドロンを手に入れ、
意志の塔を後にした。[color(white)]
[sync][wait][clear][end]
