
msg_0:
[color(green)]アザゼルが消え去った後に、
輝く光そのものが浮いている。[color(white)]
[wait][clear][end]

msg_1:
[color(green)]その近くに、
空間をすり抜けるようにズーラが跳躍してきた。[color(white)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]グッジョブ、ソルジャーズ。
[tab]まずまずの敬礼！
[sync][wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]思い知ったか、ド畜生！
[sync][wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
[tab]おー、こわ。
[sync][wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]なんか言った！？
[sync][wait][clear][end]

msg_6:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]これが、宮代[tab]詩織の
[tab]「欲動のトラペゾヘドロン」である。
[tab]彼女が抱く、あらゆる欲望が詰まっておる。
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]じゃあ、置いってった方がいいんじゃない？
[wait][clear][end]

msg_8:
[color(yellow)]うらら[color(white)]
[tab]お金でしょ？[tab]かわいい服でしょ？
[tab]おいしい食べ物に、あー男欲しいって…
[wait][clear][end]

msg_9:
[color(yellow)]うらら[color(white)]
[tab]欲しいもんばっかりで満たされないから、
[tab]毎日辛いんじゃん？
[sync][wait][clear][end]

msg_10:
[color(yellow)]パオフゥ[color(white)]
[tab]阿呆。
[tab]生きてけねぇだろうが。
[sync][wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]それに振り回されない限り、
[tab]より幸福に生きたいと望むのは、
[tab]人間として自然な欲求だよ。
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]悟りでも開いて捨て去るならともかく、他人が
[tab]どうこうしていいもんじゃ、ないんじゃないかな。
[tab]その欲望が、大多数の幸福に反しない限りね。
[sync][wait][clear][end]

msg_13:
[color(yellow)][tatsuya][color(white)]
[tab]………
[sync][wait][clear][end]

msg_14:
[color(yellow)]パオフゥ[color(white)]
[tab]生きる糧にもなりゃあ、
[tab]身を滅ぼす毒にもなるってな。
[tab]へへ、酒と同じだな。
[sync][wait][clear][end]

msg_15:
[color(yellow)]うらら[color(white)]
[tab]まぁ、そうよねぇ…
[tab]いっか！
[tab]私も今まで通りで。
[sync][wait][clear][end]

msg_16:
[color(yellow)]克哉[color(white)]
[tab]いや、君の場合は…

[sync][wait][clear][end]

msg_17:
[color(yellow)]うらら[color(white)]
[tab]じゃあ、その自然な欲望に従って、
[tab]覗いてみちゃおうかしら～ん？
[tab]他の人の欲望って、ちょっと興味あるわよね。
[sync][wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]悪趣味な女だねぇ…
[tab]まぁ、芹沢らしいぜ。
[sync][wait][clear][end]

msg_19:
[color(green)]うららは、詩織の欲動のトラペゾヘドロンを
覗き込んだ。[color(white)]
[sync][wait][clear][end]

msg_20:
[color(yellow)]うらら[color(white)]
[tab]うっわ…！[tab]スゴ…[tab]生生しい…
[tab]これが詩織さんって人？
[tab]ちょっとぉ～、凄い美人じゃないのさ！
[wait][clear][end]

msg_21:
[color(yellow)]うらら[color(white)]
[tab]あっ！[tab]あんなことして！
[tab]マーヤ、来て来て！[tab]あんたも見てみなさいよ。
[tab]男どもはダメよ！
[sync][wait][clear][end]

msg_22:
[color(yellow)]克哉[color(white)]
[tab]全く…
[tab]人の心を覗き見するなんて、感心せんな。
[sync][wait][clear][end]

msg_23:
[tab]人の心を覗き見するなんて、感心せんな。
[choice(2)]ちょっとだけ…
ですよねー
[end_choice][clear][end]

msg_24:
[color(green)]舞耶とうららは、
詩織の欲動のトラペゾヘドロンを覗き込んだ。[color(white)]
[wait][clear][end]

msg_25:
[color(green)]様々な食事や娯楽、ふかふかのベッド、
緑茶や誰もが憧撮を抱くようなリゾート地…
それらイメージの奔流の中に、
何度も幼い少年が登場し、渦巻き、流されている。[color(white)]
[wait][clear][end]

msg_26:
[color(green)]それらのイメージに混ざり、
[tatsuya]と詩織の姿が…[color(white)]
[sync][wait][clear][end]

msg_27:
[color(yellow)]詩織[color(white)]
[tab]いいのよ…[tab][tatsuya]君。
[sync][wait][clear][end]

msg_28:
[color(yellow)]舞耶[color(white)]
[tab]…！
[sync][wait][clear][end]

msg_29:
[color(green)]どうやら詩織は、
[tatsuya]に複雑な欲動を抱いているようだ。[color(white)]
[sync][wait][clear][end]

msg_30:
[color(green)]舞耶とうららは、
顔を見合わせ[tatsuya]を見た。[color(white)]
[sync][wait][clear][end]

msg_31:
[color(yellow)][tatsuya][color(white)]
[tab]…？
[wait][clear][end]

msg_32:
[color(yellow)][tatsuya][color(white)]
[tab]満足したのか、舞耶姉？
[tab]こうしてる間も、詩織さんの心は消えかけているんだ。
[tab]先を急ごう。
[sync][wait][clear][end]

msg_33:
[color(yellow)]うらら[color(white)]
[tab]こりゃ、言えないわ…
[sync][wait][clear][end]

msg_34:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを５０枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]満足したか、うららさん。
[tab]こうしてる間も、詩織さんの心は消えかけているんだ。
[tab]先を急ごう。
[sync][wait][clear][end]

msg_36:
[color(green)]うららは、[tatsuya]を見た。[color(white)]
[sync][wait][clear][end]

msg_37:
[color(yellow)]うらら[color(white)]
[tab]う、うん。
[tab]こりゃ、言えないわ…
[sync][wait][clear][end]

msg_38:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_39:
[color(green)]舞耶達は、欲動のトラペゾヘドロンを手に入れ、
欲動の塔を後にした。[color(white)]
[sync][wait][clear][end]
