
msg_0:
[color(green)]塔の中央に、忌まわしくもおぞましい
大いなる旧支配者が座している。[color(white)]
[sync][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ぎゃあああぁぁぁ！！
[tab]名状し難いぃぃぃ！！！！！
[sync][wait][clear][end]

msg_2:
[color(yellow)]クトゥルフ[color(white)]
[tab]Ｐｈ’ｎｇｌｕｉ[tab]ｍｇｌｗ’ｎａｆｈ
[tab]Ｃｔｈｕｌｈｕ[tab]Ｒ’ｌｙｅｈ
[tab]ｍｇａｈ’ｎａｇｌ[tab]ｆｈｔａｇｎ・・・
[sync][wait][clear][end]

msg_3:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]「ルルイエの館にて
[tab][tab]死せるクトゥルフ
[tab][tab]夢見るままに待ちいたり」
[wait][clear][end]

msg_4:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]この旧支配者は、かつて古のものと地球の覇権を争い、
[tab]彼のものたちの都市をことごとく破壊し、
[tab]全ての海洋とムー大陸を支配した大いなるもの。
[wait][clear][end]

msg_5:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]今もなお、太平洋に沈んだ狂気の都、
[tab]ルルイエに封じられているが
[tab]死んではいない。
[wait][clear][end]

msg_6:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]「そは永久に伏する死者にあらず
[tab][tab]旺遠なる時を経て
[tab][tab]死すらも死ぬるものなれば」
[wait][clear][end]

msg_7:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]深海の底から人々に悪夢を送り、狂える信徒どもを
[tab]増やし彼らの精神を貪り、再び地上に君臨する日を
[tab]待っているのだ。その日は必ずやってくる。
[wait][clear][end]

msg_8:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]星辰が再び正しき道を示す時、
[tab]旧支配者たちは無数の眷属を連れて復活し、
[tab]宇宙は再び彼らのものとなるのだ。
[sync][wait][clear][end]

msg_9:
[color(green)]大いなる旧支配者の、冒寺的な粘液滴る触手に、
光輝く意志のトラペゾヘドロンが握られている。[color(white)]
[sync][wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]心を貪り粋らうだと…
[sync][wait][clear][end]

msg_11:
[color(yellow)]パオフゥ[color(white)]
[tab]生憎、もう地上はクソみてぇな人間様で満員御礼でな。
[sync][wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[tab]ずっと、寝ていてもらおうか！
[sync][wait][clear][end]
