
msg_0:
[color(green)]塔の中央に、深い悲しみを纏う
大いなるものが座している。[color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]イザナミ[color(white)]
[tab]私はイザナミ…[tab]黄泉比良坂で、
[tab]心とはうつろいやすく儚いものと知りました…
[tab]私がこのような仮面をかぶっている訳、わかりますか？
[sync][wait][clear][end]

msg_2:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]この大いなるものは、夫に裏切られ、
[tab]怒り悲しみ死を生んだ黄泉の女王。
[tab]さて、貴様たちはなんと答えるのかな。
[sync][wait][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]イザナミとイザナギの国造り、
[tab]黄泉比良坂と千引岩戸の神話か…
[tab]日本人なら誰でも知ってる、残酷な話だな。
[wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]愛するイザナギの子を産んで死に、黄泉国の住人と
[tab]なったイザナミは、迎えに来た夫に腐り果てた姿を
[tab]見せまいとした。
[wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]だが、イザナギは誓いを破り醜い妻の姿を
[tab]見てしまった。
[wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]イザナギは驚いて逃げ出し、
[tab]恥をかかされたと怒り狂ったイザナミは、
[tab]黄泉の鬼たちに彼を追わせた。
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]なんとか逃げ切ったイザナギは、
[tab]千引岩で死者の国へと通じる黄泉比良坂を塞いだが、
[tab]イザナミの怒りはおさまらない。
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]妻は、夫が治める地上の人間を
[tab]一日千人殺すと呪いをかけ、夫は一日千五百の子を
[tab]産ませると永遠の離縁を宣言したんだ。
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]イザナミは都合三度…
[tab]いや、四度か？
[tab]夫に裏切られたんだな。
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]見るなと言ったのに見られ、
[tab]迎えに来たはずの夫に逃げられ、
[tab]離縁を突きつけられた。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]彼女が亡くなったのは、火の神を産んだからなんだが、
[tab]妻を失い怒り狂ったイザナギは、その子の首をはね
[tab]殺しているんだ。
[sync][wait][clear][end]

msg_12:
[color(yellow)]うらら[color(white)]
[tab]ひどっ…！
[tab]私なんか、まだましだわ…
[sync][wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]人間なんざ、結局どこまでいっても
[tab]独りよがりな生き物だってぇ、いい見本だな。
[tab]感情が一番ままならねぇのさ。
[sync][wait][clear][end]

msg_14:
[color(yellow)][tatsuya][color(white)]
[tab]…イザナギは、どうすればよかったんだ？
[sync][wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]死んだ女房に、会いになんざ行かなきゃ良かったのさ。
[tab]一度で済んだことをてめぇで蒸し返して、
[tab]自分も相手も傷つけてりゃあ、世話ねぇぜ。
[sync][wait][clear][end]

msg_16:
[color(yellow)][tatsuya][color(white)]
[tab]………
[sync][wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]だがな、俺はそういう馬鹿が好きだぜ。
[tab]人間臭ぇじゃねぇか。
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]惚れちまったもんは仕方ねぇ。
[tab]会えなくなっちまっても、会いてぇもんさ。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]この神さんが顔を隠してるわけも、
[tab]そこら辺にあるんじゃねぇのかい…
[sync][wait][clear][end]

msg_20:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]…貴様たちは面白い。
[tab]さぁ、天野[tab]舞耶、貴様はどう思うのだ。
[sync][wait][clear][end]

msg_21:
[tab]さぁ、天野[tab]舞耶、貴様はどう思うのだ。
[choice(2)]感情を押し殺すためね…
腐ってしまった顔を、見られたくないのね…
[end_choice][clear][end]

msg_22:
[color(yellow)]イザナミ[color(white)]
[tab]そうであった…
[tab]我が子を殺し、私を辱めたあの方が憎い…
[tab]許せぬ…！
[wait][clear][end]

msg_23:
[color(green)]大いなるものの髪が逆立ち、
全身にとぐろを巻く雷が現れた。[color(white)]
[wait][clear][end]

msg_24:
[color(yellow)]イザナミ[color(white)]
[tab]千五百人の子を産ませると言うのなら、
[tab]二千人殺すまで！
[wait][clear][end]

msg_25:
[color(yellow)]イザナミ[color(white)]
[tab]大雷！[tab]火雷！[tab]黒雷！[tab]折雷！
[tab]若雷！[tab]土雷！[tab]鳴雷！[tab]伏雷！
[tab]地上の人間どもを焼き殺せ！
[sync][wait][clear][end]

msg_26:
[color(yellow)]イザナミ[color(white)]
[tab]そう…
[tab]私はまだ、あの方をお慕いしています…
[wait][clear][end]

msg_27:
[color(yellow)]イザナミ[color(white)]
[tab]たとえ天と地深くに分かたれ、永久の別離を
[tab]告げられようと、二人でこの国を産んだ
[tab]麗しき日々が忘れられぬのです。
[wait][clear][end]

msg_28:
[color(yellow)]イザナミ[color(white)]
[tab]怒りはとうに消えました。
[tab]怨みもすでに絶えました。
[wait][clear][end]

msg_29:
[color(yellow)]イザナミ[color(white)]
[tab]でも、悲しみと想慕の念だけは消えぬのです。
[tab]故に、私は顔を隠しました。
[wait][clear][end]

msg_30:
[color(yellow)]イザナミ[color(white)]
[tab]あの方が、いつかまた迎えに来てくださった時に、
[tab]この醜い顔を見られなくて済むように…
[wait][clear][end]

msg_31:
[color(green)]大いなるものの手に、
光輝く感情のトラペゾヘドロンが現れた。[color(white)]
[wait][clear][end]

msg_32:
[color(yellow)]イザナミ[color(white)]
[tab]この娘にも、そのような相手がいたやもしれません。
[tab]持っておいきなさい…
[wait][clear][end]

msg_33:
[color(green)]大いなるものは消え去った。[color(white)]
[sync][wait][clear][end]

msg_34:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_35:
[color(green)]舞耶達は、感情のトラペゾヘドロンを手に入れ、
感情の塔を後にした。[color(white)]
[sync][wait][clear][end]
