
msg_0:
[color(green)]塔の中央に、いかにも契粉そうな
大いなるものが座している。[color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]ほう…[tab]人間か。
[tab]この深淵で、己を保っている人間を見たのは久しいな。
[tab]２万と５９４０日前にカーターという男を見て以来か。
[wait][clear][end]

msg_2:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]再び、絶対の善とやらがあると妄信する、
[tab]盲いた狂神と棄雄を決する時が来たのかどうか、
[tab]うぬらに問うて占うとしよう。
[wait][clear][end]

msg_3:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]うぬらにとって、
[tab]善は揺ぎ無くそこにあるものか？
[sync][wait][clear][end]

msg_4:
[color(yellow)]猫中将ズーラ[color(white)]
[tab]この強壮なるものは、覚醒の世界が生まれる遥か以前、
[tab]善神アフラ・マズダに敗れ、深淵に落ちたるもの。
[tab]さて、貴様たちはなんと答えるのかな。
[sync][wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]正義や善なんてのは、建前でしか見たことねぇが、
[tab]悪なら反吐が出るほど見てきたぜ。
[sync][wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]正しいこと、善かれと思って
[tab]罪を犯す確信犯もいるからな…
[sync][wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]難しいことはわかんないけどさ、
[tab]善いこと悪いことの基準点っていうの？
[tab]そういうのはあって欲しいよね。
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]善いか悪いかなんて関係ない。
[tab]やらなきゃいけないことをするだけだ。
[sync][wait][clear][end]

msg_9:
[tab]善は揺ぎ無くそこにあるものか？
[choice(2)]絶対的な善は存在する
善悪は相対的なものじゃないかな
[end_choice][clear][end]

msg_10:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]古から今に至るまで、敵対する民族や国を
[tab]滅ぼすことは、うぬら人間が神の名の下に奨励し、
[tab]善としてきたことだ。これは善か？
[wait][clear][end]

msg_11:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]人は、より安全に自己を保存するため、
[tab]道徳で「善きこと」を定めるが、一方で生存のため
[tab]他者を蹴落とし、食らい、滅ぼすを善しとする。
[wait][clear][end]

msg_12:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]だがそれは、詮方ないことだ。
[tab]元来、自然の摂理が利己的で悪なのだ。
[tab]命の目的は、自己の複製と種の拡大だ。
[wait][clear][end]

msg_13:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]うぬら人間だけではない。
[tab]生きとし生けるもの、みな悪の原理を生きている。
[tab]これでも善が存在するか。
[sync][wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]それでは、貴様も存在しないことになるな。
[tab]善がなければ、悪も存在しえないはずだ。
[sync][wait][clear][end]

msg_15:
[color(green)]強壮なるものは、我が意を得たりと口元を歪めた。[color(white)]
[wait][clear][end]

msg_16:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]それよ。
[wait][clear][end]

msg_17:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]善悪に境界など無く、そもそも存在しないのであれば、
[tab]アフラ・マズダも最初からありはせぬ。
[tab]我は、永劫に回帰する相克に勝利したとは思わぬか。
[sync][wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]真理など無く、ただ解釈のみが存在する、か…
[tab]落としどころとしちゃ、まぁそんなところだろうな。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]こんなところで、負け戦の理由と捲土重来の方法を
[tab]延々自問自答してたってわけかい。
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]それが、悪神自らてめぇの存在を否定することに
[tab]なっちまったってのは、皮肉だな。
[tab]ご苦労なこった。
[sync][wait][clear][end]

msg_21:
[color(green)]強壮なるものの手に、
光輝く倫理のトラペゾヘドロンが現れた。[color(white)]
[wait][clear][end]

msg_22:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]正義と善の守護者たるこの女にも、
[tab]己が守るものが如何に虚ろか教えてやるがいい。
[wait][clear][end]

msg_23:
[color(green)]強壮なるものは、
倫理のトラペゾヘドロンを残し消え去った。[color(white)]
[sync][wait][clear][end]

msg_24:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_25:
[color(green)]舞耶達は、倫理のトラペゾヘドロンを手に入れ、
倫理の塔を後にした。[color(white)]
[sync][wait][clear][end]

msg_26:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]左様。善と悪は相対的なものであり、
[tab]境界などなく存在しない。
[tab]己にとって善いか悪いかは、その解釈に過ぎぬ。
[wait][clear][end]

msg_27:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]だが、相対するものの解釈には相克が必要だ。
[tab]それを実感させてやろう。
[tab]体験の伴わぬ解釈など、妄想に過ぎぬからな。
[wait][clear][end]

msg_28:
[color(green)]強壮なるものの手に、
光輝く倫理のトラペゾヘドロンが現れた。[color(white)]
[wait][clear][end]

msg_29:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]うぬらにとって、このトラペゾヘドロンを有する
[tab]我は悪であり、我にとってこれを欲する
[tab]うぬらは悪である。
[wait][clear][end]

msg_30:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]さぁ、解釈を通じて己が生の喜びを謳歌するがいい。
[sync][wait][clear][end]

msg_31:
[tab]善は揺ぎ無くそこにあるものか？
[choice(2)]絶対的な善は存在する
善悪は相対的なものじゃないかな
[end_choice][clear][end]

msg_32:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]古から今に至るまで、敵対する民族や国を
[tab]滅ぼすことは、うぬら人間が神の名の下に奨励し、
[tab]善としてきたことだ。これは善か？
[wait][clear][end]

msg_33:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]人は、より安全に自己を保存するため、
[tab]道徳で「善きこと」を定めるが、一方で生存のため
[tab]他者を蹴落とし、食らい、滅ぼすを善しとする。
[wait][clear][end]

msg_34:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]だがそれは、詮方ないことだ。
[tab]元来、自然の摂理が利己的で悪なのだ。
[tab]命の目的は、自己の複製と種の拡大だ。
[wait][clear][end]

msg_35:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]うぬら人間だけではない。
[tab]生きとし生けるもの、みな悪の原理を生きている。
[tab]これでも善が存在するか。
[sync][wait][clear][end]

msg_36:
[color(yellow)]克哉[color(white)]
[tab]それでは、貴様も存在しないことになるな。
[tab]善がなければ、悪も存在しえないはずだ。
[sync][wait][clear][end]

msg_37:
[color(green)]強壮なるものは、我が意を得たりと口元を歪めた。[color(white)]
[wait][clear][end]

msg_38:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]それよ。
[wait][clear][end]

msg_39:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]善悪に境界など無く、そもそも存在しないのであれば、
[tab]アフラ・マズダも最初からありはせぬ。
[tab]我は、永劫に回帰する相克に勝利したとは思わぬか。
[sync][wait][clear][end]

msg_40:
[color(yellow)]パオフゥ[color(white)]
[tab]真理など無く、ただ解釈のみが存在する、か…
[tab]落としどころとしちゃ、まぁそんなところだろうな。
[wait][clear][end]

msg_41:
[color(yellow)]パオフゥ[color(white)]
[tab]こんなところで、負け戦の理由と捲土重来の方法を
[tab]延々自問自答してたってわけかい。
[wait][clear][end]

msg_42:
[color(yellow)]パオフゥ[color(white)]
[tab]それが、悪神自らてめぇの存在を否定することに
[tab]なっちまったってのは、皮肉だな。
[tab]ご苦労なこった。
[sync][wait][clear][end]

msg_43:
[color(green)]強壮なるものの手に、
光輝く倫理のトラペゾヘドロンが現れた。[color(white)]
[wait][clear][end]

msg_44:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]正義と善の守護者たるこの女にも、
[tab]己が守るものが如何に虚ろか教えてやるがいい。
[wait][clear][end]

msg_45:
[color(green)]強壮なるものは、
倫理のトラペゾヘドロンを残し消え去った。[color(white)]
[sync][wait][clear][end]

msg_46:
[color(green)]舞耶達は、[var(msg_var_0)]のカードを２００枚
手に入れた。[color(white)]
[sync][wait][clear][end]

msg_47:
[color(green)]舞耶達は、倫理のトラペゾヘドロンを手に入れ、
倫理の塔を後にした。[color(white)]
[sync][wait][clear][end]

msg_48:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]左様。善と悪は相対的なものであり、
[tab]境界などなく存在しない。
[tab]己にとって善いか悪いかは、その解釈に過ぎぬ。
[wait][clear][end]

msg_49:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]だが、相対するものの解釈には相克が必要だ。
[tab]それを実感させてやろう。
[tab]体験の伴わぬ解釈など、妄想に過ぎぬからな。
[wait][clear][end]

msg_50:
[color(green)]強壮なるものの手に、
光輝く倫理のトラペゾヘドロンが現れた。[color(white)]
[wait][clear][end]

msg_51:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]うぬらにとって、このトラペゾヘドロンを有する
[tab]我は悪であり、我にとってこれを欲する
[tab]うぬらは悪である。
[wait][clear][end]

msg_52:
[color(yellow)]アンリ・マンユ[color(white)]
[tab]さぁ、解釈を通じて己が生の喜びを謳歌するがいい。
[sync][wait][clear][end]
