
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ワンロンが駄目なら、
[tab]また純和風に、お賽銭投げてお願いしようかな…
[tab]素敵なご縁がありますように…って。
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]ねぇマーヤ…
[tab]やっぱり、新世塾の情報流したの失敗だったかな…
[tab]でも、あの場合、そうするしかなかったし…
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]あのお婆さんの話聞いた？
[tab]ここで何かあったみたいだよ。
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]神様は信じるものではあっても、
[tab]頼る者じゃない…か。
[tab]誰かが言ってたっけ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]ちょっとマーヤ、空見て空！
[tab]私ら、街ごと普遍的無意識だかの世界に
[tab]来ちゃったワケ！？
[wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]昔はよく神社で遊ぶ子供達を目にしたものだが…
[tab]最近は寂しいものだな。
[tab]古き良き…を尊ぶ時代ではないという事か。
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]新世塾の情報を流したのは失敗だったな…
[tab]奴らの方が一枚上手だったというわけか…！
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]今度はアラヤの岩戸か…
[tab][tatsuya]の奴、
[tab]一体、何がしたいんだ？
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]天野君…早く戻ろう。
[tab]続きが知りたいんだ…
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]たった一人で今まで戦ってきたのか…
[tab]辛かったろうに…
[tab]……
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]をああまで突き動かすものは何なんだ…
[tab]天野君を死なせてしまった罪悪感か…
[tab]この悲劇を生んだ張本人への恨みか…
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]いや、違うな…
[tab]本当にアイツが成そうとしている事は…
[sync][wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]できれば、今の[tatsuya]の姿を
[tab]親父にも見せてやりたいな。
[tab]きっと安心するだろう…
[wait][clear][end]

msg_14:
[color(yellow)]パオフゥ[color(white)]
[tab]共鳴…だと？
[tab]今は眠っているようだが…
[tab]まさか…あいつらもペルソナを？
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]竜蔵との決着をつけるまで…
[tab]俺の仕事は終わらねぇ。
[tab]それまでは付き合ってやるさ。
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]どうした？
[tab]顔色が良くねぇぞ。
[tab]またデジャ・ヴュでも見たか？
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]さすが甘ちゃんだな…
[tab][suou]の奴、感動的な話にゃ弱いと見える。
[tab]いい大人がみっともねぇ…
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]この社…
[tab]どこか変じゃねぇか？
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]ゲームってのは、
[tab]先に笑った野郎が最後に泣きを見るもんなんだ。
[tab]その点、奴ァ笑いっぱなしだからな。
[wait][clear][end]

msg_20:
[color(yellow)]南条[color(white)]
[tab]神取と…ペルソナが関係する謎の事件…
[tab]ここにアラヤ神社があるのも、
[tab]単なる偶然ではないかも知れませんね。
[wait][clear][end]

msg_21:
[color(yellow)]南条[color(white)]
[tab]ここに来る途中、
[tab]洞窟らしい物を見かけましたが…
[tab]まさか、アラヤの岩戸…
[wait][clear][end]

msg_22:
[color(yellow)]南条[color(white)]
[tab]どうやら[suou]の目的は、
[tab]天野さん、あなたに何かを気付かせる…
[tab]いや、思い出させる為のように見える。
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]何か心当たりはありませんか？
[tab]ここまで関わった以上、
[tab]俺も多少なりと関心があります。
[wait][clear][end]

msg_24:
[color(yellow)]エリー[color(white)]
[tab]Ｍｒ．神取…そしてＰＥＲＳＯＮＡが関係する
[tab]謎の事件…ここにＡＲＡＹＡ神社があるのは、
[tab]ただの偶然でしょうか？
[wait][clear][end]

msg_25:
[color(yellow)]エリー[color(white)]
[tab]あの…ここに来る途中で、
[tab]洞窟のような物を見かけましたわ。
[tab]あれはまさか、ＡＲＡＹＡの岩戸と言うのでは…
[wait][clear][end]

msg_26:
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．Ａｍａｎｏ、[tatsuya]はあなたに
[tab]何かを思い出してほしいんじゃなくて？
[tab]私にはそう見えるのですが…
[wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]アラヤの岩戸に行けば…
[tab]全てを知ることができる。
[tab]大切な今と引き換えに…
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]ここで俺達は…舞耶姉と初めて出会った…
[tab]ここが全ての始まり、向こうとこちらを分かつ、
[tab]分岐点だったんだ。
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]須藤[tab]竜蔵も、
[tab]所詮は操られているに過ぎないんだ…
[tab]本当の敵は…
[wait][clear][end]

msg_30:
[color(yellow)][tatsuya][color(white)]
[tab]そうさ…全てはこの社から始まった…
[tab]ここを通って来いと言うなら行ってやる！
[tab]全ての決着をつけるんだ！
[wait][clear][end]

msg_31:
[color(yellow)]お婆さん[color(white)]
[tab]私はねぇ…どういう訳か、
[tab]ここに来なくてはならないような気がすんだよぉ。
[tab]ここに…誰かがいたような気がするのさ…
[wait][clear][color(yellow)]お婆さん[color(white)]
[tab]勝手に出てきちまったから、
[tab]今頃娘夫婦が心配しとるかもしれんが…
[tab]なぜか、どうしても気になってねぇ。
[wait][clear][end]

msg_32:
[color(yellow)]お婆さん[color(white)]
[tab]はいはい。
[tab]私に何かご用かいな？
[tab]何でも言うてみんさい。
[wait][clear][end]

msg_33:
[tab]何か用かいな？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_34:
ニシタニセツ
[end]

msg_35:
[color(yellow)]お婆さん[color(white)]
[tab]はぁ…
[tab]そっただ名前の人、聞いたことねぇなぁ…
[tab]誰か別の人に聞いた方が良いと思うけんども。
[wait][clear][end]

msg_36:
[color(yellow)]お婆さん[color(white)]
[tab]はいはい、確かに私はニシタニ[tab]セツと申します。
[tab]けれど、アンタとはどこかでお会いしたかのぉ…
[tab]なんで私の名前を知っとるんかの？
[wait][clear][end]

msg_37:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]はぁ…私を捜して欲しいと…そうですか。
[tab]きっと娘夫婦が捜索願を出したんでしょうねぇ。
[tab]心配かけてしまったよぉ。
[wait][clear][color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]分かりました。娘と、その人捜し屋さんには、
[tab]私から連絡しときますよって。
[tab]安心してつかぁさい。
[wait][clear][color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]こう見えても、
[tab]携帯電話っちゅーもんを持っとりますけぇ。
[tab]大丈夫ですよ。
[wait][clear][end]

msg_38:
[color(yellow)]お婆さん[color(white)]
[end]

msg_39:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[end]

msg_40:
[tab]なんでも最近は、穢れ祓いの講演会が
[tab]あちこちで開かれとるそうだねぇ。
[tab]娘にも勧められたんだけど…どうしようかね。
[wait][clear][end]

msg_41:
[color(yellow)]お婆さん[color(white)]
[end]

msg_42:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[end]

msg_43:
[tab]トリフネだとか、世界滅亡だとか、
[tab]ホントに、街の中は怖い話ばかりで…
[tab]私はここにいる方が落ち着きますわ。
[wait][clear][end]

msg_44:
[color(yellow)]お婆さん[color(white)]
[end]

msg_45:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[end]

msg_46:
[tab]な…何だったんじゃ今のは…
[tab]と…突然、黒い渦が出てきて、
[tab]ここにいた子らを吸い込んで…
[wait][clear][end]

msg_47:
[color(yellow)]お婆さん[color(white)]
[end]

msg_48:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[end]

msg_49:
[tab]不思議じゃ…
[tab]街が空を飛んでいるというのに、
[tab]これが初めてという気がせんのじゃ…
[wait][clear][end]

msg_50:
[color(yellow)]お婆さん[color(white)]
[end]

msg_51:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[end]

msg_52:
[tab]あ、アンタ達、いつお社の中に入ったんじゃ？
[tab]どうして中から急に…
[tab]うう…次から次へと…熱が出そうじゃ…
[wait][clear][end]

msg_53:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]あんたかい…
[tab]丁度今、昔話を思い出しててねぇ…
[sync][wait][clear][end]

msg_54:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]昔、この土地の悪い殿様を懲らしめたお侍さんと、
[tab]お姫様の悲しいお話さね…
[tab]聞いていきなさるかね？
[sync][wait][clear][end]

msg_55:
[tab]聞いていきなさるかね？
[choice(2)]ぜひ…
時間が無いので…結構です。
[end_choice][clear][end]

msg_56:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]そうかい…残念だねぇ。
[sync][wait][clear][end]

msg_57:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]まぁ、あんたくらいの時が、
[tab]一番時間の流れが早いもんさね。
[tab]後悔しないように生きなさるんだよ。
[sync][wait][clear][end]

msg_58:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]昔、澄丸[tab]清忠っちゅう、そりゃあ悪い殿様が
[tab]この土地を治めなさっててな…
[tab]その殿様は、色々な妖術で人々を苦しめた。
[sync][wait][clear][end]

msg_59:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]それを見かねた、従兄弟の辰之進という若侍が、
[tab]その殿様を成敗しようとしたのさね。
[sync][wait][clear][end]

msg_60:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]でも、殿様は普通の人間じゃあない…
[tab]若侍は、死を覚悟して殿様のお城に乗り込んだ。
[tab]恋人のお姫様に、別れも告げずにね…
[sync][wait][clear][end]

msg_61:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]それを、若侍の家来から知らされたお姫様は、
[tab]たいそう悲しんでなぁ、急いで恋人の後を
[tab]追いかけたのさね。
[sync][wait][clear][end]

msg_62:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]お城では、若侍と殿様の戦いの真っ最中だった。
[tab]そして、追い詰められた若侍をかばって…
[tab]姫様は槍で突かれて死んでしまったのさね…
[sync][wait][clear][end]

msg_63:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]若侍は殿様を成敗したけれど、そのまま燃え崩れる
[tab]お城に姫様の亡骸と残りなさった…
[tab]親友の家来に、姫様の供養を託しなさってな…
[sync][wait][clear][end]

msg_64:
[tab]親友の家来に、姫様の供養を託しなさってな…
[choice(2)]あの…そのお姫様の名前は…
そうですか…
[end_choice][clear][end]

msg_65:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab][color(orange)]天野[tab]舞姫[color(white)]…
[tab]そりゃあ綺麗なお姫様だったって話さね…
[sync][wait][clear][end]

msg_66:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]ああやってお城が出てきたってことは、
[tab]ただの昔話じゃあなかったんだねぇ…
[sync][wait][clear][end]

msg_67:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]その後、家来さんは出家して、
[tab]蝸牛山にお篭りになったって話さね…
[tab]名前は…確か黒田[tab]純之介とか言ったかねぇ…
[sync][wait][clear][end]

msg_68:
[color(yellow)]ニシタニ[tab]セツ[color(white)]
[tab]ああやってお城が出てきたってことは、
[tab]ただの昔話じゃあなかったんだねぇ…
[sync][wait][clear][end]

msg_69:
[color(yellow)]淳[color(white)]
[tab]新世塾…
[tab]空の科学館を襲ったあの男も、
[tab]その新世塾のメンバーだったんですか？
[wait][clear][end]

msg_70:
[color(yellow)]淳[color(white)]
[tab]世界の滅亡…
[tab]なぜだ…胸が苦しい…
[tab]何か…大切な事を僕達は…
[wait][clear][end]

msg_71:
[color(yellow)]栄吉[color(white)]
[tab]あれ…アンタは…なんでアンタがここに？
[tab]え？[tab]俺？[tab]俺はその…フラフラっと…
[tab]…なんとなく…
[sync][wait][clear][end]

msg_72:
[color(yellow)]栄吉[color(white)]
[tab]それにしても、なんだよここ…
[tab]どこを向いても、一瞬そこを知ってる気がする…
[tab]これがデジャ・ヴュってヤツか？
[wait][clear][end]

msg_73:
[color(yellow)]栄吉[color(white)]
[tab]なんだよここ…
[tab]どこを向いても、一瞬そこを知ってる気がする…
[tab]これがデジャ・ヴュってヤツか？
[wait][clear][end]

msg_74:
[color(yellow)]栄吉[color(white)]
[tab]あり？
[wait][clear][end]

msg_75:
[color(yellow)]栄吉[color(white)]
[tab]……！？
[wait][clear][end]

msg_76:
[color(yellow)]栄吉[color(white)]
[tab]なんでだ？[tab]これもデジャ・ヴュ？
[tab]初対面だよな？
[tab]しっかりしろミッシェル！！
[wait][clear][end]

msg_77:
[color(yellow)]栄吉[color(white)]
[tab]な、なんだいベイビィ。
[tab]この珠閒瑠市一のビューティホーボーイ、
[tab]ミッシェル様に何か用かい？
[wait][clear][end]

msg_78:
[color(yellow)]三科[tab]栄吉（みしな[tab]えいきち）[color(white)]
[color(green)][tab]春日山高校の番長を務める２年生。
[tab]どこかで会った気がする…[color(white)]
[wait][clear][end]

msg_79:
[color(yellow)]栄吉[color(white)]
[tab]へ？[tab]天野…舞耶…？
[tab]ああ、じゃあベイビィが
[tab]南条さんの言ってた雑誌記者だね？
[wait][clear][end]

msg_80:
[color(yellow)]栄吉[color(white)]
[tab]ふふん、何を隠そう、
[tab]このボクも例の理学研究所に忍び込んでたのさ。
[tab]南条さんともそこで会ったんだ。
[wait][clear][end]

msg_81:
[color(yellow)]栄吉[color(white)]
[tab]まあ、あそこから無事に脱出できたのも、
[tab]ボクの力あってこそだね。
[tab]おっと、サインかい？[tab]サインが欲しいのかい？
[wait][clear][end]

msg_82:
[color(yellow)]栄吉[color(white)]
[tab]レッツ・ポジティブシンキング…か。
[tab]いやその、最近街でそう騒いでる奴が多いだろ？
[tab]それから気になっちまってさ。
[sync][wait][clear][end]

msg_83:
[color(yellow)]栄吉[color(white)]
[tab]なんか昔にも、そんな事言って
[tab]騒いでる人がいたような気がすんだよなぁ…
[tab]誰だったっけか…
[sync][wait][clear][end]

msg_84:
[color(yellow)]栄吉[color(white)]
[tab]トリフネ…トリフ？[tab]ね？
[tab]鳥の船？
[tab]…ちがうな…
[sync][wait][clear][end]

msg_85:
[color(yellow)]リサ[color(white)]
[tab]天野さん…デジャ・ヴュって、
[tab]本当にあるんだね。
[tab]アタシ、さっきからそれ起きまくりだもん。
[wait][clear][end]

msg_86:
[color(yellow)]リサ[color(white)]
[tab]なんだかここ、とっても懐かしい気がするの。
[tab]あの社も、この風景も…
[tab]でもどうして…
[wait][clear][end]

msg_87:
[color(yellow)]リサ[color(white)]
[tab]アラヤ…神社…
[tab]ア…ラヤ…
[tab]なんでだろ…
[wait][clear][end]

msg_88:
[color(yellow)]リサ[color(white)]
[tab]あれ？
[wait][clear][end]

msg_89:
[color(yellow)]リサ[color(white)]
[tab]……
[wait][clear][end]

msg_90:
[color(yellow)]リサ[color(white)]
[tab]ソ…Ｓｏｒｒｙ呀（ソーリーア）
[tab]し、知り合いの誰かと似てたのかな…
[tab]なんかビックリしちゃって…ハハハ…
[wait][clear][end]

msg_91:
[color(yellow)]リサ[color(white)]
[tab]ア、アタシ、リサ。
[tab]リサ・シルバーマン。
[tab]よろしくね。
[sync][wait][clear][end]

msg_92:
[color(yellow)]リサ・シルバーマン
[color(green)][tab]七姉妹学園の生徒であり、
[tab]アイドルグループＭＵＳＥＳのメンバー
[tab]生粋の白人だが、日本生まれの日本育ち。
[wait][clear][end]

msg_93:
[color(yellow)]リサ[color(white)]
[tab]え？[tab]アナタが天野さん？
[tab]ああ、聞いてる、聞いてる。
[tab]エリーさんの知り合いでしょ？
[wait][clear][end]

msg_94:
[color(yellow)]リサ[color(white)]
[tab]ちょうどアタシ、珠閒瑠ＴＶにいて、
[tab]中で事件が起きたとき、
[tab]エリーさんに助けてもらったの。
[wait][clear][end]

msg_95:
[color(yellow)]リサ[color(white)]
[tab]何かあれば、アタシも協力するよ。
[tab]こう見えてもカンフーには自信あんだから！
[tab]アチョー！！[tab]ってね。
[wait][clear][end]

msg_96:
[color(yellow)]リサ[color(white)]
[tab]新世塾…新世塾…
[tab]たしか、プロデューサーも、
[tab]その名前知ってたっけ…
[sync][wait][clear][end]

msg_97:
[color(yellow)]リサ[color(white)]
[tab]街の下にある巨大な船…
[tab]おかしいよ！[tab]前にもこんな事なかった？
[tab]だって…だってそんな気がするんだもん！
[sync][wait][clear][end]

msg_98:
[color(yellow)]リサ[color(white)]
[tab]でも思い出せないの…
[tab]頭の中をチラチラと何かが過るのに…
[tab]思い出せない…どうして？
[sync][wait][clear][end]

msg_99:
[color(yellow)]物知り大ちゃん[color(white)]
[tab]お姉ちゃん知ってる？
[tab]この街には伝説の武器職人がいるんだよ。
[tab]あーっ、信じてないでしょー！？
[wait][clear][end]

msg_100:
[color(yellow)]物知り大ちゃん[color(white)]
[tab]大ちゃんのお父さん、いるって言ってたもん！！
[tab]いいよー、信じなくても。
[tab]しらいしのおばちゃんに捜してもらうもんねー！
[wait][clear][end]

msg_101:
[color(yellow)]物知り大ちゃん[color(white)]
[tab]大ちゃんのツルギ、つくってもらうんだー！
[tab]…でも、大ちゃんガンもすてがたいね。
[wait][clear][end]

msg_102:
[color(yellow)]野暮ったい男[color(white)]
[tab]はぁ～
[tab]やっぱり私に会社勤めは無理なのかなぁ。
[wait][clear][end]

msg_103:
[color(yellow)]野暮ったい男[color(white)]
[tab]…はい、どなた様ですか？
[tab]私に何か御用ですか？
[wait][clear][end]

msg_104:
[tab]私に何か御用ですか？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_105:
アサノタクミ
[end]

msg_106:
[color(yellow)]野暮ったい男[color(white)]
[tab]…え？
[tab]それ、私のことですか？
[tab]私を誰かと間違われているようですね。
[wait][clear][end]

msg_107:
[color(yellow)]野暮ったい男[color(white)]
[tab]…はぁ、アサノタクミは私ですが。
[tab]どこかでお会いした事、ありましたか？
[wait][clear][end]

msg_108:
[color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]はぁ…伝説の武器職人を捜していると。
[tab]確かに我が一族は、古くから武具の制作を
[tab]生業としておりました。
[wait][clear][color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]しかし、それも先代までの話。
[tab]先代…父の死と同時にやめてしまいました。
[tab]…何故って、食べて行けないからですよ。
[wait][clear][color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]…三十五過ぎて初めての会社勤め。
[tab]営業って難しいもんですね。
[wait][clear][end]

msg_109:
[color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]…残念ですが、あなたの力にはなれません。
[tab]会社勤めに慣れちゃって…
[tab]ほら！[tab]もう手が動かないんですよ。
[wait][clear][color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]リハビリには時間が必要ですし…
[tab]うん、この[color(green)]秘伝書[color(white)]をおゆずりしましょう。
[wait][clear][color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]…大事な物だろうって？
[tab]心配いりません。内容は全て頭に入ってます。
[tab]それに、今の私には必要無いものですから…
[wait][clear][end]

msg_110:
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear][end]

msg_111:
[color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]…秘伝書の事、気にしないで下さい。
[tab]今の私には必要の無いもの。
[tab]腕のいい職人がいたら見せてあげて下さい。
[wait][clear][end]

msg_112:
[color(yellow)]アサノ[tab]タクミ[color(white)]
[tab]あれ？[tab]なんかおかしいな？
[tab]私の父って職人だったかな？
[tab]普通のサラリーマンだったような気も…？
[wait][clear][end]

msg_113:
[color(yellow)]野暮ったい男[color(white)]
[tab]聞いてもらえます？
[tab]私、三十五過ぎて初めての会社勤めしたんです。
[tab]いやぁ、営業って難しいもんですね。
[wait][clear][end]

msg_114:
[color(yellow)]野暮ったい男[color(white)]
[tab]以前は自宅で仕事していました。
[tab]フリー…って言うんですかね？
[wait][clear][end]

msg_115:
[color(yellow)]パオフゥ[color(white)]
[tab]やれやれ、またここかい…
[tab]芸のねぇ野郎だぜ。
[wait][clear][end]

msg_116:
[color(yellow)]うらら[color(white)]
[tab]でもここを通れば、
[tab]いつでも街に戻れるんだし、
[tab]ラッキーじゃん？
[wait][clear][end]

msg_117:
[color(yellow)]克哉[color(white)]
[tab]これも奴の仕業なのだろ？
[tab]今となっては余裕を見せつけられているようで
[tab]癇にさわるよ。
[wait][clear][end]

msg_118:
[color(yellow)][tatsuya][color(white)]
[tab]全てはここに始まり…
[tab]ここに終わる…
[tab]そう言いたいのか。
[wait][clear][end]
