function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3045, 127);
    ref_3 = todLoad(tod_1f);
    wait(ref_3);
    todRun(tod_1f, 1);
    envTriggerSet(DOORBOX, 131, 1, line, coll_36);
    li(var_0, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, tatsuya);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_17);
    li(var_0, 0);
    b(label_1c);
  label_17:
    ref_17 = dialogAlloc();
    ref_18 = msgShow(msg_0);
/***************************************
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear]
***************************************/
    wait(ref_18);
    dialogFree(ref_17);
    b(label_1c);
  label_1c:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_22);
    ref_1e = spriteLoad(sprite_6);
    wait(ref_1e);
    unitSpawn(ulala, sprite_6, 86, 0, -792, east, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_22:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_28);
    ref_24 = spriteLoad(sprite_d);
    wait(ref_24);
    unitSpawn(katsuya, sprite_d, 686, 0, -779, east, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_28:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_2e);
    ref_2a = spriteLoad(sprite_13);
    wait(ref_2a);
    unitSpawn(baofu, sprite_13, 248, 0, -1389, south, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_2e:
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_34);
    ref_30 = spriteLoad(sprite_1f);
    wait(ref_30);
    unitSpawn(nanjo, sprite_1f, 420, 0, -949, west, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
  label_34:
    partyMemberCheck(var_0, elly);
    bez(var_0, label_3a);
    ref_36 = spriteLoad(sprite_23);
    wait(ref_36);
    unitSpawn(elly, sprite_23, 420, 0, -879, west, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
  label_3a:
    partyMemberCheck(var_0, tatsuya);
    bez(var_0, label_41);
    ref_3c = spriteLoad(sprite_18);
    wait(ref_3c);
    unitSpawn(tatsuya, sprite_18, 135, -50, -391, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_4a);
  label_41:
    bitGet(var_0, EBIT_E008C);
    bne(var_0, 0, label_44);
    b(label_4a);
  label_44:
    bne(var_0, 1, label_4a);
    ref_45 = spriteLoad(sprite_18);
    wait(ref_45);
    unitSpawn(tatsuya, sprite_18, 135, -50, -391, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_4a);
  label_4a:
    ref_4a = spriteLoad(sprite_8c);
    wait(ref_4a);
    unitSpawn(shopkeeper, sprite_8c, 498, -50, -402, north, none);
    unitTriggerSet(shopkeeper, SHOPBOX, 255, 1);
    ref_4e = spriteLoad(sprite_ca);
    wait(ref_4e);
    unitSpawn(npc1, sprite_ca, 864, -50, -243, west, none);
    unitTriggerSet(npc1, SIZUKA, 255, 1);
    ref_52 = spriteLoad(sprite_101);
    wait(ref_52);
    unitSpawn(npc2, sprite_101, 586, 0, -1100, west, none);
    unitPalette(npc2, 2);
    unitTriggerSet(npc2, BOXWOMAN, 255, 1);
    bitGet(var_0, MBIT_HAVEZIKAN);
    bne(var_0, 0, label_5b);
    cameraSet(southeast, 503, 0, -1441);
    b(label_5e);
  label_5b:
    bne(var_0, 1, label_5e);
    cameraSet(northeast, 508, -50, -470);
    b(label_5e);
  label_5e:
    ref_5e = spriteLoad(sprite_0);
    wait(ref_5e);
    ref_60 = spriteLoad(sprite_2);
    wait(ref_60);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_e3);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_c9);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_b9);
    bitGet(var_0, EBIT_E008F);
    bnz(var_0, label_a9);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_99);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_89);
    unitFacePlayer(ulala);
    ref_7a = bustupLoad(bustup_17);
    bustupWait(ref_7a);
    ref_7c = bustupAlloc(ref_7a, left, rgb(0,0,0));
    bustupFade(ref_7c, rgb(128,0,0), 30);
    ref_7e = dialogAlloc();
    ref_7f = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なんか最近、
[tab]デジャ・ヴュを見たって人多くない？
[tab]これって偶然？[tab]偶然にしてはちょっと…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_7f);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_7e);
    ref_84 = bustupFade(ref_7c, rgb(0,0,0), 10);
    bustupWait(ref_84);
    bustupFree(ref_7c);
    unitRestoreFacing(ulala);
    b(label_f2);
  label_89:
    unitFacePlayer(ulala);
    ref_8a = bustupLoad(bustup_1f);
    bustupWait(ref_8a);
    ref_8c = bustupAlloc(ref_8a, left, rgb(0,0,0));
    bustupFade(ref_8c, rgb(128,0,0), 30);
    ref_8e = dialogAlloc();
    ref_8f = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]最近、私も多いのよねぇ…デジャ・ヴュ…
[tab]…でも少し違うかな…
[tab]何かを思い出す前みたいな…そんな感じなのよね
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_6, 1);
    wait(ref_8f);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_8e);
    ref_94 = bustupFade(ref_8c, rgb(0,0,0), 10);
    bustupWait(ref_94);
    bustupFree(ref_8c);
    unitRestoreFacing(ulala);
    b(label_f2);
  label_99:
    unitFacePlayer(ulala);
    ref_9a = bustupLoad(bustup_17);
    bustupWait(ref_9a);
    ref_9c = bustupAlloc(ref_9a, left, rgb(0,0,0));
    bustupFade(ref_9c, rgb(128,0,0), 30);
    ref_9e = dialogAlloc();
    ref_9f = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab][tatsuya]君…
[tab]やっと事情を話す気になったみたいだけど…
[tab]神社なんかで何をするつもりだろ？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_9f);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_9e);
    ref_a4 = bustupFade(ref_9c, rgb(0,0,0), 10);
    bustupWait(ref_a4);
    bustupFree(ref_9c);
    unitRestoreFacing(ulala);
    b(label_f2);
  label_a9:
    unitFacePlayer(ulala);
    ref_aa = bustupLoad(bustup_17);
    bustupWait(ref_aa);
    ref_ac = bustupAlloc(ref_aa, left, rgb(0,0,0));
    bustupFade(ref_ac, rgb(128,0,0), 30);
    ref_ae = dialogAlloc();
    ref_af = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]やっぱ[tatsuya]君は、
[tab]マーヤに何かを伝えようとしてんのよ！
[tab]ねぇ、何か心当たりはないの？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_af);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ae);
    ref_b4 = bustupFade(ref_ac, rgb(0,0,0), 10);
    bustupWait(ref_b4);
    bustupFree(ref_ac);
    unitRestoreFacing(ulala);
    b(label_f2);
  label_b9:
    unitFacePlayer(ulala);
    ref_ba = bustupLoad(bustup_1f);
    bustupWait(ref_ba);
    ref_bc = bustupAlloc(ref_ba, left, rgb(0,0,0));
    bustupFade(ref_bc, rgb(128,0,0), 30);
    ref_be = dialogAlloc();
    ref_bf = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]パラレルワールドかぁ…
[tab]本や映画の中だけの物かと思ってたけど、
[tab]ホントにあるんだねぇ…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_bf);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_be);
    ref_c4 = bustupFade(ref_bc, rgb(0,0,0), 10);
    bustupWait(ref_c4);
    bustupFree(ref_bc);
    unitRestoreFacing(ulala);
    b(label_f2);
  label_c9:
    unitFacePlayer(ulala);
    ref_ca = bustupLoad(bustup_1f);
    bustupWait(ref_ca);
    ref_cc = bustupAlloc(ref_ca, left, rgb(0,0,0));
    bustupFade(ref_cc, rgb(128,0,0), 30);
    ref_ce = dialogAlloc();
    ref_cf = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]はぁ…街が飛んでるわよ、マジで…
[tab]こんな状況、私達だけでどうにかできんのかなぁ…
[tab]いくら頑張ったってこれじゃ…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_cf);
    ref_d2 = bustupFade(ref_cc, rgb(0,0,0), 10);
    bustupWait(ref_d2);
    bustupFree(ref_cc);
    ref_d5 = bustupLoad(bustup_19);
    bustupWait(ref_d5);
    ref_d7 = bustupAlloc(ref_d5, left, rgb(0,0,0));
    bustupFade(ref_d7, rgb(128,0,0), 30);
    ref_d9 = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]っ！？[tab]おっととっと！
[tab]弱音吐いてる場合じゃないわよねぇ！
[tab]女２５前の一念発起なんだから！
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_d9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ce);
    ref_de = bustupFade(ref_d7, rgb(0,0,0), 10);
    bustupWait(ref_de);
    bustupFree(ref_d7);
    unitRestoreFacing(ulala);
    b(label_f2);
  label_e3:
    unitFacePlayer(ulala);
    ref_e4 = bustupLoad(bustup_19);
    bustupWait(ref_e4);
    ref_e6 = bustupAlloc(ref_e4, left, rgb(0,0,0));
    bustupFade(ref_e6, rgb(128,0,0), 30);
    ref_e8 = dialogAlloc();
    ref_e9 = msgShow(msg_8);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あいつがこの事件を起こした張本人って訳だ。
[tab]ならば！[tab]牧村に使わなかった正義の鉄拳！
[tab]ここで使わず、いつ使うってのよ！
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_e9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_e8);
    ref_ee = bustupFade(ref_e6, rgb(0,0,0), 10);
    bustupWait(ref_ee);
    bustupFree(ref_e6);
    unitRestoreFacing(ulala);
  label_f2:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_1ba);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_168);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_158);
    bitGet(var_0, EBIT_E008F);
    bnz(var_0, label_134);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_121);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_111);
    unitFacePlayer(katsuya);
    ref_102 = bustupLoad(bustup_26);
    bustupWait(ref_102);
    ref_104 = bustupAlloc(ref_102, left, rgb(0,0,0));
    bustupFade(ref_104, rgb(128,0,0), 30);
    ref_106 = dialogAlloc();
    ref_107 = msgShow(msg_9);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]下手に穢れマシンを破壊すれば、
[tab]佐々木[tab]銀次の二の舞だ…
[tab]どうすれば人に穢れを戻せるんだ？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_107);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_106);
    ref_10c = bustupFade(ref_104, rgb(0,0,0), 10);
    bustupWait(ref_10c);
    bustupFree(ref_104);
    unitRestoreFacing(katsuya);
    b(label_1c9);
  label_111:
    unitFacePlayer(katsuya);
    ref_112 = bustupLoad(bustup_23);
    bustupWait(ref_112);
    ref_114 = bustupAlloc(ref_112, left, rgb(0,0,0));
    bustupFade(ref_114, rgb(128,0,0), 30);
    ref_116 = dialogAlloc();
    ref_117 = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]穢れた人間は新世塾に滅ぼされる…
[tab]だから自分も穢れを祓ってもらおう…か？
[tab]街の人間はなぜそう他力本願なんだ？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_117);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_116);
    ref_11c = bustupFade(ref_114, rgb(0,0,0), 10);
    bustupWait(ref_11c);
    bustupFree(ref_114);
    unitRestoreFacing(katsuya);
    b(label_1c9);
  label_121:
    unitFacePlayer(katsuya);
    ref_122 = bustupLoad(bustup_21);
    bustupWait(ref_122);
    ref_124 = bustupAlloc(ref_122, left, rgb(0,0,0));
    bustupFade(ref_124, rgb(128,0,0), 30);
    ref_126 = dialogAlloc();
    ref_127 = msgShow(msg_11);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]アラヤ神社…か。
[tab]子供の頃、アイツを連れて、
[tab]よく祭りに出かけたものだ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_127);
    ref_12a = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]だがそれも昔の話…
[tab]アイツの口から、あの神社の名を聞いたことなど、
[tab]もう何年も無かったが…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_12a);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_126);
    ref_12f = bustupFade(ref_124, rgb(0,0,0), 10);
    bustupWait(ref_12f);
    bustupFree(ref_124);
    unitRestoreFacing(katsuya);
    b(label_1c9);
  label_134:
    bitGet(var_0, EBIT_E0096);
    bne(var_0, 0, label_146);
    unitFacePlayer(katsuya);
    ref_137 = bustupLoad(bustup_21);
    bustupWait(ref_137);
    ref_139 = bustupAlloc(ref_137, left, rgb(0,0,0));
    bustupFade(ref_139, rgb(128,0,0), 30);
    ref_13b = dialogAlloc();
    ref_13c = msgShow(msg_13);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]気になっていたんだが、
[tab]僕と知り合う前から[tatsuya]の事を知っていたのか？
[tab]少なくとも、アイツはそんな様子だが…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_13c);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_13b);
    ref_141 = bustupFade(ref_139, rgb(0,0,0), 10);
    bustupWait(ref_141);
    bustupFree(ref_139);
    unitRestoreFacing(katsuya);
    b(label_157);
  label_146:
    bne(var_0, 1, label_157);
    unitFacePlayer(katsuya);
    unitAnimationPlay(katsuya, animation_10, 1);
    ref_149 = bustupLoad(bustup_24);
    bustupWait(ref_149);
    ref_14b = bustupAlloc(ref_149, left, rgb(0,0,0));
    bustupFade(ref_14b, rgb(128,0,0), 30);
    ref_14d = dialogAlloc();
    ref_14e = msgShow(msg_14);
/***************************************
[color(yellow)]克哉[color(white)]
[tab][tatsuya]はずっと前から君を知っていた…
[tab]しかし、それが違う平行世界の話だとは…
[tab]なんということだ…なんという…
[wait][clear]
***************************************/
    wait(ref_14e);
    dialogFree(ref_14d);
    ref_151 = bustupFade(ref_14b, rgb(0,0,0), 10);
    bustupWait(ref_151);
    bustupFree(ref_14b);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitRestoreFacing(katsuya);
    b(label_157);
  label_157:
    b(label_1c9);
  label_158:
    unitFacePlayer(katsuya);
    ref_159 = bustupLoad(bustup_21);
    bustupWait(ref_159);
    ref_15b = bustupAlloc(ref_159, left, rgb(0,0,0));
    bustupFade(ref_15b, rgb(128,0,0), 30);
    ref_15d = dialogAlloc();
    ref_15e = msgShow(msg_15);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]向こうの世界で天野君を刺した女性…
[tab]あれは確かセブンスで見かけた教員だな。
[tab]世界が違えば、人も違う、ということか。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_15e);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_15d);
    ref_163 = bustupFade(ref_15b, rgb(0,0,0), 10);
    bustupWait(ref_163);
    bustupFree(ref_15b);
    unitRestoreFacing(katsuya);
    b(label_1c9);
  label_168:
    bitGet(var_0, MBIT_ARA_KATUTALK5);
    bnz(var_0, label_1aa);
    unitFacePlayer(katsuya);
    ref_16b = bustupLoad(bustup_21);
    bustupWait(ref_16b);
    ref_16d = bustupAlloc(ref_16b, left, rgb(0,0,0));
    bustupFade(ref_16d, rgb(128,0,0), 30);
    ref_16f = dialogAlloc();
    ref_170 = msgShow(msg_16);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]付かぬ事を尋ねるが…
[tab]僕と[tatsuya]は…似ていると思うか？
[tab]勘でいい。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_170);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_16f);
    ref_175 = bustupFade(ref_16d, rgb(0,0,0), 10);
    bustupWait(ref_175);
    bustupFree(ref_16d);
    unitRestoreFacing(katsuya);
    ref_179 = bustupLoad(bustup_1);
    bustupWait(ref_179);
    ref_17b = bustupAlloc(ref_179, center, rgb(0,0,0));
    bustupFade(ref_17b, rgb(128,0,0), 30);
    ref_17d = dialogChoiceAlloc();
    ref_17e = msgShow(msg_17);
/***************************************
[tab]どうだ？
[choice(2)]似ている
似ていない
[end_choice][clear]
***************************************/
    wait(ref_17e);
    dialogFree(ref_17d);
    ref_181 = bustupFade(ref_17b, rgb(0,0,0), 10);
    bustupWait(ref_181);
    bustupFree(ref_17b);
    choiceGetResult(var_0);
    bne(var_0, 0, label_197);
    unitFacePlayer(katsuya);
    ref_187 = bustupLoad(bustup_22);
    bustupWait(ref_187);
    ref_189 = bustupAlloc(ref_187, left, rgb(0,0,0));
    bustupFade(ref_189, rgb(128,0,0), 30);
    ref_18b = dialogAlloc();
    ref_18c = msgShow(msg_18);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]そ、そうか…似ているか…
[tab]なら、もう…迷う必要はないな。
[tab]済まん、気にしないでくれ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_18c);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_18b);
    ref_191 = bustupFade(ref_189, rgb(0,0,0), 10);
    bustupWait(ref_191);
    bustupFree(ref_189);
    unitRestoreFacing(katsuya);
    bitSet(MBIT_ARA_KATUTALK5);
    b(label_1a9);
  label_197:
    bne(var_0, 1, label_1a9);
    unitFacePlayer(katsuya);
    ref_199 = bustupLoad(bustup_21);
    bustupWait(ref_199);
    ref_19b = bustupAlloc(ref_199, left, rgb(0,0,0));
    bustupFade(ref_19b, rgb(128,0,0), 30);
    ref_19d = dialogAlloc();
    ref_19e = msgShow(msg_19);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]…そうか…
[tab]そうだな。僕は僕だ。
[tab]兄弟だからという理由は…必要無い。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_19e);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_19d);
    ref_1a3 = bustupFade(ref_19b, rgb(0,0,0), 10);
    bustupWait(ref_1a3);
    bustupFree(ref_19b);
    unitRestoreFacing(katsuya);
    bitSet(MBIT_ARA_KATUTALK5);
    b(label_1a9);
  label_1a9:
    b(label_1c9);
  label_1aa:
    unitFacePlayer(katsuya);
    ref_1ab = bustupLoad(bustup_21);
    bustupWait(ref_1ab);
    ref_1ad = bustupAlloc(ref_1ab, left, rgb(0,0,0));
    bustupFade(ref_1ad, rgb(128,0,0), 30);
    ref_1af = dialogAlloc();
    ref_1b0 = msgShow(msg_20);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]弟は兄の姿を見て成長する。
[tab]だが兄もまた、弟の姿を見て変わるものだ。
[tab]弟を尊敬する兄が居ても…不思議じゃあるまい？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_1b0);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_1af);
    ref_1b5 = bustupFade(ref_1ad, rgb(0,0,0), 10);
    bustupWait(ref_1b5);
    bustupFree(ref_1ad);
    unitRestoreFacing(katsuya);
    b(label_1c9);
  label_1ba:
    unitFacePlayer(katsuya);
    ref_1bb = bustupLoad(bustup_23);
    bustupWait(ref_1bb);
    ref_1bd = bustupAlloc(ref_1bb, left, rgb(0,0,0));
    bustupFade(ref_1bd, rgb(128,0,0), 30);
    ref_1bf = dialogAlloc();
    ref_1c0 = msgShow(msg_21);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]人間を駒のごとく扱う外道の分際で、
[tab]弟の姿を借りるとは…
[tab]ふざけるにも限度があるぞ！
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2f, 1);
    wait(ref_1c0);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_1bf);
    ref_1c5 = bustupFade(ref_1bd, rgb(0,0,0), 10);
    bustupWait(ref_1c5);
    bustupFree(ref_1bd);
    unitRestoreFacing(katsuya);
  label_1c9:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_22e);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_21e);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_210);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_200);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_1e6);
    unitFacePlayer(baofu);
    ref_1d7 = bustupLoad(bustup_2d);
    bustupWait(ref_1d7);
    ref_1d9 = bustupAlloc(ref_1d7, left, rgb(0,0,0));
    bustupFade(ref_1d9, rgb(128,0,0), 30);
    ref_1db = dialogAlloc();
    ref_1dc = msgShow(msg_22);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]佐々木[tab]銀次も、
[tab]あそこの女と同じような眼をしてたな。
[tab]既に洗脳されてたって事か…
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1dc);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1db);
    ref_1e1 = bustupFade(ref_1d9, rgb(0,0,0), 10);
    bustupWait(ref_1e1);
    bustupFree(ref_1d9);
    unitRestoreFacing(baofu);
    b(label_23d);
  label_1e6:
    unitFacePlayer(baofu);
    ref_1e7 = bustupLoad(bustup_31);
    bustupWait(ref_1e7);
    ref_1e9 = bustupAlloc(ref_1e7, left, rgb(0,0,0));
    bustupFade(ref_1e9, rgb(128,0,0), 30);
    ref_1eb = dialogAlloc();
    ref_1ec = msgShow(msg_23);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]結局、平和ボケした連中には、
[tab]自分の命を自分で守ろうという気力もない。
[tab]死の現実味さえ忘れちまったのさ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_1ec);
    ref_1ef = bustupFade(ref_1e9, rgb(0,0,0), 10);
    bustupWait(ref_1ef);
    bustupFree(ref_1e9);
    ref_1f2 = bustupLoad(bustup_2d);
    bustupWait(ref_1f2);
    ref_1f4 = bustupAlloc(ref_1f2, left, rgb(0,0,0));
    bustupFade(ref_1f4, rgb(128,0,0), 30);
    ref_1f6 = msgShow(msg_24);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]それが悪いとは言わねえ。
[tab]平和にこしたこたぁないからな。
[tab]だが、それが今の結果を招いたのも事実だ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1f6);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1eb);
    ref_1fb = bustupFade(ref_1f4, rgb(0,0,0), 10);
    bustupWait(ref_1fb);
    bustupFree(ref_1f4);
    unitRestoreFacing(baofu);
    b(label_23d);
  label_200:
    unitFacePlayer(baofu);
    ref_201 = bustupLoad(bustup_2d);
    bustupWait(ref_201);
    ref_203 = bustupAlloc(ref_201, left, rgb(0,0,0));
    bustupFade(ref_203, rgb(128,0,0), 30);
    ref_205 = dialogAlloc();
    ref_206 = msgShow(msg_25);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab][tatsuya]の事情も気になるところだが、
[tab]こうしてる間も新世塾の計画は着々と進んでる。
[tab]のんびりしてる暇はねえぞ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_206);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_205);
    ref_20b = bustupFade(ref_203, rgb(0,0,0), 10);
    bustupWait(ref_20b);
    bustupFree(ref_203);
    unitRestoreFacing(baofu);
    b(label_23d);
  label_210:
    ref_210 = bustupLoad(bustup_2d);
    bustupWait(ref_210);
    ref_212 = bustupAlloc(ref_210, left, rgb(0,0,0));
    bustupFade(ref_212, rgb(128,0,0), 30);
    ref_214 = dialogAlloc();
    ref_215 = msgShow(msg_26);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]「向こう側」の世界とそこで起きた事件…
[tab]裏で手を引いていた野郎は、
[tab]こっちも同じだったってわけかい…
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_215);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_214);
    ref_21a = bustupFade(ref_212, rgb(0,0,0), 10);
    bustupWait(ref_21a);
    bustupFree(ref_212);
    b(label_23d);
  label_21e:
    unitFacePlayer(baofu);
    ref_21f = bustupLoad(bustup_31);
    bustupWait(ref_21f);
    ref_221 = bustupAlloc(ref_21f, left, rgb(0,0,0));
    bustupFade(ref_221, rgb(128,0,0), 30);
    ref_223 = dialogAlloc();
    ref_224 = msgShow(msg_27);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]神事を食い止める…か。
[tab]考え様によっては大それた事だな…
[tab]まさに俺に相応しい役目だ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_224);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_223);
    ref_229 = bustupFade(ref_221, rgb(0,0,0), 10);
    bustupWait(ref_229);
    bustupFree(ref_221);
    unitRestoreFacing(baofu);
    b(label_23d);
  label_22e:
    unitFacePlayer(baofu);
    ref_22f = bustupLoad(bustup_31);
    bustupWait(ref_22f);
    ref_231 = bustupAlloc(ref_22f, left, rgb(0,0,0));
    bustupFade(ref_231, rgb(128,0,0), 30);
    ref_233 = dialogAlloc();
    ref_234 = msgShow(msg_28);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ふん、これだけ大騒ぎを起こしておいて、
[tab]ゲームだってのか…
[tab]ヤツも相当なもんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_234);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_233);
    ref_239 = bustupFade(ref_231, rgb(0,0,0), 10);
    bustupWait(ref_239);
    bustupFree(ref_231);
    unitRestoreFacing(baofu);
  label_23d:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_265);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_257);
    unitFacePlayer(nanjo);
    ref_245 = bustupLoad(bustup_36);
    bustupWait(ref_245);
    ref_247 = bustupAlloc(ref_245, left, rgb(0,0,0));
    bustupFade(ref_247, rgb(128,0,0), 30);
    ref_249 = dialogAlloc();
    ref_24a = msgShow(msg_29);
/***************************************
[color(yellow)]南条[color(white)]
[tab]講演会に参加した人間は、
[tab]穢れを奪われるだけでなく、
[tab]新世塾に盲従するよう洗脳までされてしまう…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_24a);
    ref_24d = msgShow(msg_30);
/***************************************
[color(yellow)]南条[color(white)]
[tab]洗脳…
[tab]不思議だ…
[tab]前にも似たような事件があったような気がする…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_6, 1);
    wait(ref_24d);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_249);
    ref_252 = bustupFade(ref_247, rgb(0,0,0), 10);
    bustupWait(ref_252);
    bustupFree(ref_247);
    unitRestoreFacing(nanjo);
    b(label_272);
  label_257:
    ref_257 = bustupLoad(bustup_36);
    bustupWait(ref_257);
    ref_259 = bustupAlloc(ref_257, left, rgb(0,0,0));
    bustupFade(ref_259, rgb(128,0,0), 30);
    ref_25b = dialogAlloc();
    ref_25c = msgShow(msg_31);
/***************************************
[color(yellow)]南条[color(white)]
[tab]…あの店主…
[tab]伯爵と名乗っていたか…
[tab]どうも気になるな。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_25c);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_25b);
    ref_261 = bustupFade(ref_259, rgb(0,0,0), 10);
    bustupWait(ref_261);
    bustupFree(ref_259);
    b(label_272);
  label_265:
    ref_265 = bustupLoad(bustup_36);
    bustupWait(ref_265);
    ref_267 = bustupAlloc(ref_265, left, rgb(0,0,0));
    bustupFade(ref_267, rgb(128,0,0), 30);
    ref_269 = dialogAlloc();
    ref_26a = msgShow(msg_32);
/***************************************
[color(yellow)]南条[color(white)]
[tab]海底遺跡での神取の言葉…
[tab]奴は[suou]から何かを見出そうとしていたのか…
[tab]それとも…何かを託したかったのか…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_6, 1);
    wait(ref_26a);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_269);
    ref_26f = bustupFade(ref_267, rgb(0,0,0), 10);
    bustupWait(ref_26f);
    bustupFree(ref_267);
  label_272:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_299);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_289);
    unitFacePlayer(elly);
    ref_27a = bustupLoad(bustup_40);
    bustupWait(ref_27a);
    ref_27c = bustupAlloc(ref_27a, left, rgb(0,0,0));
    bustupFade(ref_27c, rgb(128,0,0), 30);
    ref_27e = dialogAlloc();
    ref_27f = msgShow(msg_33);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]あの講演会は洗脳によって新世塾に盲従する民を
[tab]増やすためのものだったんですわ。
[tab]このままでは遅かれ早かれ…
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_27f);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_27e);
    ref_284 = bustupFade(ref_27c, rgb(0,0,0), 10);
    bustupWait(ref_284);
    bustupFree(ref_27c);
    unitRestoreFacing(elly);
    b(label_2a8);
  label_289:
    unitFaceUnit(elly, shopkeeper);
    ref_28a = bustupLoad(bustup_3d);
    bustupWait(ref_28a);
    ref_28c = bustupAlloc(ref_28a, left, rgb(0,0,0));
    bustupFade(ref_28c, rgb(128,0,0), 30);
    ref_28e = dialogAlloc();
    ref_28f = msgShow(msg_34);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]あの店主さん…
[tab]なぜかしら…普通の人とは違う、何かを感じる…
[tab]鳥肌が立つようなこの感覚…何なのかしら。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_1a, 1);
    wait(ref_28f);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_28e);
    ref_294 = bustupFade(ref_28c, rgb(0,0,0), 10);
    bustupWait(ref_294);
    bustupFree(ref_28c);
    unitRestoreFacing(elly);
    b(label_2a8);
  label_299:
    unitFacePlayer(elly);
    ref_29a = bustupLoad(bustup_3d);
    bustupWait(ref_29a);
    ref_29c = bustupAlloc(ref_29a, left, rgb(0,0,0));
    bustupFade(ref_29c, rgb(128,0,0), 30);
    ref_29e = dialogAlloc();
    ref_29f = msgShow(msg_35);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]もしかしたらＭｒ．神取は…[tatsuya]に何かを
[tab]託したかったのかもしれません…
[tab]不思議と、そんな気がするんです。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_29f);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_29e);
    ref_2a4 = bustupFade(ref_29c, rgb(0,0,0), 10);
    bustupWait(ref_2a4);
    bustupFree(ref_29c);
    unitRestoreFacing(elly);
  label_2a8:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_2e0);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2d0);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_2c0);
    ref_2b1 = bustupLoad(bustup_10);
    bustupWait(ref_2b1);
    ref_2b3 = bustupAlloc(ref_2b1, right, rgb(0,0,0));
    bustupFade(ref_2b3, rgb(128,0,0), 30);
    bustupFlip(ref_2b3, true);
    ref_2b6 = dialogAlloc();
    ref_2b7 = msgShow(msg_36);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]…やはり街の人達にまで影響が出始めている…
[tab]もう、猶予は無い。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_6, 1);
    wait(ref_2b7);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2b6);
    ref_2bc = bustupFade(ref_2b3, rgb(0,0,0), 10);
    bustupWait(ref_2bc);
    bustupFree(ref_2b3);
    b(label_2ef);
  label_2c0:
    unitFacePlayer(tatsuya);
    ref_2c1 = bustupLoad(bustup_b);
    bustupWait(ref_2c1);
    ref_2c3 = bustupAlloc(ref_2c1, left, rgb(0,0,0));
    bustupFade(ref_2c3, rgb(128,0,0), 30);
    ref_2c5 = dialogAlloc();
    ref_2c6 = msgShow(msg_37);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉が全てを思い出したことで、
[tab]「向こう側」と「こちら側」を隔てる揺らぎは
[tab]確実に大きくなったはずだ…もう、時間がない…
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2c6);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2c5);
    ref_2cb = bustupFade(ref_2c3, rgb(0,0,0), 10);
    bustupWait(ref_2cb);
    bustupFree(ref_2c3);
    unitRestoreFacing(tatsuya);
    b(label_2ef);
  label_2d0:
    unitFacePlayer(tatsuya);
    ref_2d1 = bustupLoad(bustup_d);
    bustupWait(ref_2d1);
    ref_2d3 = bustupAlloc(ref_2d1, left, rgb(0,0,0));
    bustupFade(ref_2d3, rgb(128,0,0), 30);
    ref_2d5 = dialogAlloc();
    ref_2d6 = msgShow(msg_38);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]こうしている間も、
[tab]奴はどこかで俺達を見ているはずなんだ。
[tab]口元に笑みを浮かべながら…
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2f, 1);
    wait(ref_2d6);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2d5);
    ref_2db = bustupFade(ref_2d3, rgb(0,0,0), 10);
    bustupWait(ref_2db);
    bustupFree(ref_2d3);
    unitRestoreFacing(tatsuya);
    b(label_2ef);
  label_2e0:
    unitFacePlayer(tatsuya);
    ref_2e1 = bustupLoad(bustup_d);
    bustupWait(ref_2e1);
    ref_2e3 = bustupAlloc(ref_2e1, left, rgb(0,0,0));
    bustupFade(ref_2e3, rgb(128,0,0), 30);
    ref_2e5 = dialogAlloc();
    ref_2e6 = msgShow(msg_39);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉…感じないか…
[tab]この男…まさか…
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_6, 1);
    wait(ref_2e6);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2e5);
    ref_2eb = bustupFade(ref_2e3, rgb(0,0,0), 10);
    bustupWait(ref_2eb);
    bustupFree(ref_2e3);
    unitRestoreFacing(tatsuya);
  label_2ef:
    controlEnable();
}

function SHOPBOX()
{
    controlDisable();
    bitSet(MBIT_HAVEZIKAN);
    unitFacePlayer(shopkeeper);
    bitGet(var_0, MBIT_HI_JIKANDUP);
    bne(var_0, 0, label_324);
    bitGet(var_0, MBIT_HI_JIKANSELL);
    bne(var_0, 0, label_30c);
    bitGet(var_0, MBIT_UMAETALKHAKU);
    bne(var_0, 0, label_302);
    bitGet(var_0, MBIT_AIS_02);
    bne(var_0, 0, label_2fe);
    b(label_33c);
    b(label_301);
  label_2fe:
    bne(var_0, 1, label_301);
    b(label_34b);
    b(label_301);
  label_301:
    b(label_30b);
  label_302:
    bne(var_0, 1, label_30b);
    bitGet(var_0, MBIT_AIS_02);
    bne(var_0, 0, label_307);
    b(label_35a);
    b(label_30a);
  label_307:
    bne(var_0, 1, label_30a);
    b(label_368);
    b(label_30a);
  label_30a:
    b(label_30b);
  label_30b:
    b(label_323);
  label_30c:
    bne(var_0, 1, label_323);
    ref_30d = shopOverlayInit();
    bitGet(var_0, MBIT_ZIKANHANBAI);
    bne(var_0, 0, label_318);
    bitGet(var_0, MBIT_AIS_02);
    bne(var_0, 0, label_314);
    b(label_376);
    b(label_317);
  label_314:
    bne(var_0, 1, label_317);
    b(label_387);
    b(label_317);
  label_317:
    b(label_321);
  label_318:
    bne(var_0, 1, label_321);
    bitGet(var_0, MBIT_AIS_02);
    bne(var_0, 0, label_31d);
    b(label_398);
    b(label_320);
  label_31d:
    bne(var_0, 1, label_320);
    b(label_3ad);
    b(label_320);
  label_320:
    b(label_321);
  label_321:
    wait(ref_30d);
    b(label_323);
  label_323:
    b(label_33b);
  label_324:
    bne(var_0, 1, label_33b);
    ref_325 = shopOverlayInit();
    bitGet(var_0, MBIT_ZIKANFUKUSEI);
    bne(var_0, 0, label_330);
    bitGet(var_0, MBIT_AIS_02);
    bne(var_0, 0, label_32c);
    b(label_3c2);
    b(label_32f);
  label_32c:
    bne(var_0, 1, label_32f);
    b(label_3d3);
    b(label_32f);
  label_32f:
    b(label_339);
  label_330:
    bne(var_0, 1, label_339);
    bitGet(var_0, MBIT_AIS_02);
    bne(var_0, 0, label_335);
    b(label_398);
    b(label_338);
  label_335:
    bne(var_0, 1, label_338);
    b(label_3ad);
    b(label_338);
  label_338:
    b(label_339);
  label_339:
    wait(ref_325);
    b(label_33b);
  label_33b:
    b(label_3e7);
  label_33c:
    ref_33c = bustupLoad(bustup_f0);
    bustupWait(ref_33c);
    ref_33e = bustupAlloc(ref_33c, right, rgb(0,0,0));
    bustupFade(ref_33e, rgb(128,0,0), 30);
    ref_340 = dialogAlloc();
    ref_341 = msgShow(msg_40);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]なるほど…運命を受け入れず、
[tab]今一度、時の歯車を戻したか…
[tab]どこまでも人間とは哀れな生き物だな…
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]しかし、私にはまだ演ずるべき役が無いようだ。
[tab]早く決めて欲しいものだな…
[tab]この世界での私の存在意義を。
[wait][clear]
***************************************/
    bitSet(MBIT_UMAETALKHAKU);
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_341);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_340);
    ref_347 = bustupFade(ref_33e, rgb(0,0,0), 10);
    bustupWait(ref_347);
    bustupFree(ref_33e);
    b(label_3e4);
  label_34b:
    ref_34b = bustupLoad(bustup_f0);
    bustupWait(ref_34b);
    ref_34d = bustupAlloc(ref_34b, right, rgb(0,0,0));
    bustupFade(ref_34d, rgb(128,0,0), 30);
    ref_34f = dialogAlloc();
    ref_350 = msgShow(msg_41);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]なるほど…運命を受け入れず、
[tab]今一度、時の歯車を戻したか…
[tab]どこまでも人間とは哀れな生き物だな…
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]しかし、私にはまだ演ずるべき役が無いようだ。
[tab]早く決めて欲しいものだな…
[tab]この世界での私の存在意義を。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]いくら相性が良くなろうとも、
[tab]役目が無ければ、どうしようもあるまい。
[wait][clear]
***************************************/
    bitSet(MBIT_UMAETALKHAKU);
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_350);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_34f);
    ref_356 = bustupFade(ref_34d, rgb(0,0,0), 10);
    bustupWait(ref_356);
    bustupFree(ref_34d);
    b(label_3e4);
  label_35a:
    ref_35a = bustupLoad(bustup_f0);
    bustupWait(ref_35a);
    ref_35c = bustupAlloc(ref_35a, right, rgb(0,0,0));
    bustupFade(ref_35c, rgb(128,0,0), 30);
    ref_35e = dialogAlloc();
    ref_35f = msgShow(msg_42);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何度訪れようと同じ事だ。
[tab]今の私では君達の役には立たん。
[tab]さっさと噂操作でもしたらどうだ？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_35f);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_35e);
    ref_364 = bustupFade(ref_35c, rgb(0,0,0), 10);
    bustupWait(ref_364);
    bustupFree(ref_35c);
    b(label_3e4);
  label_368:
    ref_368 = bustupLoad(bustup_f0);
    bustupWait(ref_368);
    ref_36a = bustupAlloc(ref_368, right, rgb(0,0,0));
    bustupFade(ref_36a, rgb(128,0,0), 30);
    ref_36c = dialogAlloc();
    ref_36d = msgShow(msg_43);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何度訪れようと同じ事だ。
[tab]今の私では君達の役には立たん。
[tab]さっさと噂操作でもしたらどうだ？
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]相性も何も、
[tab]全てはそれからだ。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_36d);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_36c);
    ref_372 = bustupFade(ref_36a, rgb(0,0,0), 10);
    bustupWait(ref_372);
    bustupFree(ref_36a);
    b(label_3e4);
  label_376:
    ref_376 = bustupLoad(bustup_f0);
    bustupWait(ref_376);
    ref_378 = bustupAlloc(ref_376, right, rgb(0,0,0));
    bustupFade(ref_378, rgb(128,0,0), 30);
    ref_37a = dialogAlloc();
    ref_37b = msgShow(msg_44);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふふふ…なるほど。
[tab]どうやら私の役目が決まったようだな。
[tab]…今一度…私は時の傀儡となるのか…
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]ようこそ時の城へ。
[tab]ここでは、魔性のカードを多数扱っている。
[tab]さあ、ご用件を伺おうか？
[wait][clear]
***************************************/
    bitSet(MBIT_ZIKANHANBAI);
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_37b);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_37a);
    ref_381 = bustupFade(ref_378, rgb(0,0,0), 10);
    bustupWait(ref_381);
    bustupFree(ref_378);
    shopInventory(10, shopInventory_1);
    shopRate(100);
    b(label_3e7);
  label_387:
    ref_387 = bustupLoad(bustup_f0);
    bustupWait(ref_387);
    ref_389 = bustupAlloc(ref_387, right, rgb(0,0,0));
    bustupFade(ref_389, rgb(128,0,0), 30);
    ref_38b = dialogAlloc();
    ref_38c = msgShow(msg_45);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふふふ…なるほど。
[tab]どうやら私の役目が決まったようだな。
[tab]…今一度…私は時の傀儡となるのか…
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]ようこそ時の城へ。
[tab]ここでは、魔性のカードを多数扱っている。
[tab]さあ、ご用件を…
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]…ふふ…そうか…相性占いとは抜け目が無い。
[tab]よかろう。確かに君とは只ならぬ縁があるようだ。
[tab]特別に二割引で取引させてもらおう。
[wait][clear]
***************************************/
    bitSet(MBIT_ZIKANHANBAI);
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_38c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_38b);
    ref_392 = bustupFade(ref_389, rgb(0,0,0), 10);
    bustupWait(ref_392);
    bustupFree(ref_389);
    shopInventory(10, shopInventory_1);
    shopRate(80);
    b(label_3e7);
  label_398:
    ref_398 = bustupLoad(bustup_f0);
    bustupWait(ref_398);
    ref_39a = bustupAlloc(ref_398, right, rgb(0,0,0));
    bustupFade(ref_39a, rgb(128,0,0), 30);
    ref_39c = dialogAlloc();
    ref_39d = msgShow(msg_46);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ようこそ時の城へ。
[tab]さあ、ご用件を伺おうか。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_39d);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_39c);
    ref_3a2 = bustupFade(ref_39a, rgb(0,0,0), 10);
    bustupWait(ref_3a2);
    bustupFree(ref_39a);
    shopInventory(10, shopInventory_1);
    shopRate(100);
    bitGet(var_0, MBIT_HI_JIKANDUP);
    bne(var_0, 0, label_3aa);
    b(label_3ac);
  label_3aa:
    bne(var_0, 1, label_3ac);
    b(label_3ac);
  label_3ac:
    b(label_3e7);
  label_3ad:
    ref_3ad = bustupLoad(bustup_f0);
    bustupWait(ref_3ad);
    ref_3af = bustupAlloc(ref_3ad, right, rgb(0,0,0));
    bustupFade(ref_3af, rgb(128,0,0), 30);
    ref_3b1 = dialogAlloc();
    ref_3b2 = msgShow(msg_47);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]この私と相性が良いと？
[tab]ふふ…まあ、そう言えなくもないか…
[tab]よかろう。通常の二割引で取引させてもらおう。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_3b2);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_3b1);
    ref_3b7 = bustupFade(ref_3af, rgb(0,0,0), 10);
    bustupWait(ref_3b7);
    bustupFree(ref_3af);
    shopInventory(10, shopInventory_1);
    shopRate(80);
    bitGet(var_0, MBIT_HI_JIKANDUP);
    bne(var_0, 0, label_3bf);
    b(label_3c1);
  label_3bf:
    bne(var_0, 1, label_3c1);
    b(label_3c1);
  label_3c1:
    b(label_3e7);
  label_3c2:
    ref_3c2 = bustupLoad(bustup_f0);
    bustupWait(ref_3c2);
    ref_3c4 = bustupAlloc(ref_3c2, right, rgb(0,0,0));
    bustupFade(ref_3c4, rgb(128,0,0), 30);
    ref_3c6 = dialogAlloc();
    ref_3c7 = msgShow(msg_48);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふふふ…今度はカードの複製か…
[tab]なかなか楽しませてくれる。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]ついに我が城にてカードの複製が可能となった。
[tab]レアカードを手に入れたなら持ってくるがよい。
[tab]何枚にでも増やし、販売してやろう。
[wait][clear]
***************************************/
    bitSet(MBIT_ZIKANFUKUSEI);
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_3c7);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_3c6);
    ref_3cd = bustupFade(ref_3c4, rgb(0,0,0), 10);
    bustupWait(ref_3cd);
    bustupFree(ref_3c4);
    shopInventory(10, shopInventory_1);
    shopRate(100);
    b(label_3e7);
  label_3d3:
    ref_3d3 = bustupLoad(bustup_f0);
    bustupWait(ref_3d3);
    ref_3d5 = bustupAlloc(ref_3d3, right, rgb(0,0,0));
    bustupFade(ref_3d5, rgb(128,0,0), 30);
    ref_3d7 = dialogAlloc();
    ref_3d8 = msgShow(msg_49);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふふふ…今度はカードの複製か…
[tab]なかなか楽しませてくれる。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]ついに我が城にてカードの複製が可能となった。
[tab]レアカードを手に入れたなら持ってくるがよい。
[tab]何枚にでも増やし、販売してやろう。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]もちろん…二割引で取引しよう。
[tab]相性の良い君へ、
[tab]心ばかりのサービスだ…
[wait][clear]
***************************************/
    bitSet(MBIT_ZIKANFUKUSEI);
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_3d8);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_3d7);
    ref_3de = bustupFade(ref_3d5, rgb(0,0,0), 10);
    bustupWait(ref_3de);
    bustupFree(ref_3d5);
    shopInventory(10, shopInventory_1);
    shopRate(80);
    b(label_3e7);
  label_3e4:
    controlEnable();
    unitRestoreFacing(shopkeeper);
    b(label_45f);
  label_3e7:
    bitGet(var_0, MBIT_HI_JIKANDUP);
    bne(var_0, 0, label_422);
    choiceSetResult(4);
    ref_3ea = bustupLoad(bustup_f0);
    bustupWait(ref_3ea);
    ref_3ec = bustupAlloc(ref_3ea, right, rgb(0,0,0));
    bustupFade(ref_3ec, rgb(128,0,0), 30);
    ref_3ee = dialogAlloc();
    ref_3ef = msgShow(msg_50);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]さあ、ご用件を伺おうか。
[choice(6)]カードを買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_3ef);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_3f8);
    li(var_5, 0);
    b(label_41b);
  label_3f8:
    bne(var_0, 1, label_403);
    choiceSetResult(0);
    ref_3fa = msgShow(msg_51);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何を売るのかね？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear]
***************************************/
    wait(ref_3fa);
    choiceGetResult(var_5);
    bne(var_5, 0, label_400);
    li(var_5, 1000);
    b(label_402);
  label_400:
    add(var_5, var_5, 10);
    b(label_402);
  label_402:
    b(label_41b);
  label_403:
    bne(var_0, 2, label_412);
    choiceSetResult(2);
    ref_405 = msgShow(msg_52);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何について話したいのかね？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_405);
    choiceGetResult(var_0);
    bne(var_0, 0, label_40b);
    li(var_5, 2);
    b(label_411);
  label_40b:
    bne(var_0, 1, label_40e);
    li(var_5, 2000);
    b(label_411);
  label_40e:
    bne(var_0, 2, label_411);
    li(var_5, 1000);
    b(label_411);
  label_411:
    b(label_41b);
  label_412:
    bne(var_0, 3, label_415);
    li(var_5, 3);
    b(label_41b);
  label_415:
    bne(var_0, 4, label_418);
    li(var_5, 4);
    b(label_41b);
  label_418:
    bne(var_0, 5, label_41b);
    li(var_5, 5);
    b(label_41b);
  label_41b:
    dialogFree(ref_3ee);
    ref_41c = bustupFade(ref_3ec, rgb(0,0,0), 10);
    bustupWait(ref_41c);
    bustupFree(ref_3ec);
    ref_41f = shopOpen(1);
    wait(ref_41f);
    b(label_45f);
  label_422:
    bne(var_0, 1, label_45f);
    choiceSetResult(5);
    ref_424 = bustupLoad(bustup_f0);
    bustupWait(ref_424);
    ref_426 = bustupAlloc(ref_424, right, rgb(0,0,0));
    bustupFade(ref_426, rgb(128,0,0), 30);
    ref_428 = dialogAlloc();
    ref_429 = msgShow(msg_53);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]さあ、ご用件を伺おうか。
[choice(7)]カードを買う
カードを登録
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_429);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_432);
    li(var_5, 0);
    b(label_458);
  label_432:
    bne(var_0, 1, label_435);
    li(var_5, 1);
    b(label_458);
  label_435:
    bne(var_0, 2, label_440);
    choiceSetResult(0);
    ref_437 = msgShow(msg_54);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何を売るのかね？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear]
***************************************/
    wait(ref_437);
    choiceGetResult(var_5);
    bne(var_5, 0, label_43d);
    li(var_5, 1000);
    b(label_43f);
  label_43d:
    add(var_5, var_5, 20);
    b(label_43f);
  label_43f:
    b(label_458);
  label_440:
    bne(var_0, 3, label_44f);
    choiceSetResult(2);
    ref_442 = msgShow(msg_55);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何について話したいのかね？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_442);
    choiceGetResult(var_0);
    bne(var_0, 0, label_448);
    li(var_5, 3);
    b(label_44e);
  label_448:
    bne(var_0, 1, label_44b);
    li(var_5, 2000);
    b(label_44e);
  label_44b:
    bne(var_0, 2, label_44e);
    li(var_5, 1000);
    b(label_44e);
  label_44e:
    b(label_458);
  label_44f:
    bne(var_0, 4, label_452);
    li(var_5, 4);
    b(label_458);
  label_452:
    bne(var_0, 5, label_455);
    li(var_5, 5);
    b(label_458);
  label_455:
    bne(var_0, 6, label_458);
    li(var_5, 6);
    b(label_458);
  label_458:
    dialogFree(ref_428);
    ref_459 = bustupFade(ref_426, rgb(0,0,0), 10);
    bustupWait(ref_459);
    bustupFree(ref_426);
    ref_45c = shopOpen(2);
    wait(ref_45c);
    b(label_45f);
  label_45f:
}

function HA_SHOP_RESTART_0()
{
    bitGet(var_0, MBIT_HI_JIKANDUP);
    bne(var_0, 0, label_499);
    choiceSetResult(4);
    ref_463 = bustupLoad(bustup_f0);
    bustupWait(ref_463);
    ref_465 = bustupAlloc(ref_463, right, rgb(0,0,0));
    bustupFade(ref_465, rgb(128,0,0), 30);
    ref_467 = dialogAlloc();
    ref_468 = msgShow(msg_56);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]他に用はあるかね？
[choice(6)]カードを買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_468);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_471);
    li(var_5, 0);
    b(label_494);
  label_471:
    bne(var_0, 1, label_47c);
    choiceSetResult(0);
    ref_473 = msgShow(msg_57);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何を売るのかね？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear]
***************************************/
    wait(ref_473);
    choiceGetResult(var_5);
    bne(var_5, 0, label_479);
    li(var_5, 1000);
    b(label_47b);
  label_479:
    add(var_5, var_5, 10);
    b(label_47b);
  label_47b:
    b(label_494);
  label_47c:
    bne(var_0, 2, label_48b);
    choiceSetResult(2);
    ref_47e = msgShow(msg_58);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何について話したいのかね？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_47e);
    choiceGetResult(var_0);
    bne(var_0, 0, label_484);
    li(var_5, 2);
    b(label_48a);
  label_484:
    bne(var_0, 1, label_487);
    li(var_5, 2000);
    b(label_48a);
  label_487:
    bne(var_0, 2, label_48a);
    li(var_5, 1000);
    b(label_48a);
  label_48a:
    b(label_494);
  label_48b:
    bne(var_0, 3, label_48e);
    li(var_5, 3);
    b(label_494);
  label_48e:
    bne(var_0, 4, label_491);
    li(var_5, 4);
    b(label_494);
  label_491:
    bne(var_0, 5, label_494);
    li(var_5, 5);
    b(label_494);
  label_494:
    dialogFree(ref_467);
    ref_495 = bustupFade(ref_465, rgb(0,0,0), 10);
    bustupWait(ref_495);
    bustupFree(ref_465);
    b(label_4d4);
  label_499:
    bne(var_0, 1, label_4d4);
    choiceSetResult(5);
    ref_49b = bustupLoad(bustup_f0);
    bustupWait(ref_49b);
    ref_49d = bustupAlloc(ref_49b, right, rgb(0,0,0));
    bustupFade(ref_49d, rgb(128,0,0), 30);
    ref_49f = dialogAlloc();
    ref_4a0 = msgShow(msg_59);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]他に用はあるかね？
[choice(7)]カードを買う
カードを登録
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_4a0);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4a9);
    li(var_5, 0);
    b(label_4cf);
  label_4a9:
    bne(var_0, 1, label_4ac);
    li(var_5, 1);
    b(label_4cf);
  label_4ac:
    bne(var_0, 2, label_4b7);
    choiceSetResult(0);
    ref_4ae = msgShow(msg_60);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何を売るのかね？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear]
***************************************/
    wait(ref_4ae);
    choiceGetResult(var_5);
    bne(var_5, 0, label_4b4);
    li(var_5, 1000);
    b(label_4b6);
  label_4b4:
    add(var_5, var_5, 20);
    b(label_4b6);
  label_4b6:
    b(label_4cf);
  label_4b7:
    bne(var_0, 3, label_4c6);
    choiceSetResult(2);
    ref_4b9 = msgShow(msg_61);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何について話したいのかね？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_4b9);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4bf);
    li(var_5, 3);
    b(label_4c5);
  label_4bf:
    bne(var_0, 1, label_4c2);
    li(var_5, 2000);
    b(label_4c5);
  label_4c2:
    bne(var_0, 2, label_4c5);
    li(var_5, 1000);
    b(label_4c5);
  label_4c5:
    b(label_4cf);
  label_4c6:
    bne(var_0, 4, label_4c9);
    li(var_5, 4);
    b(label_4cf);
  label_4c9:
    bne(var_0, 5, label_4cc);
    li(var_5, 5);
    b(label_4cf);
  label_4cc:
    bne(var_0, 6, label_4cf);
    li(var_5, 6);
    b(label_4cf);
  label_4cf:
    dialogFree(ref_49f);
    ref_4d0 = bustupFade(ref_49d, rgb(0,0,0), 10);
    bustupWait(ref_4d0);
    bustupFree(ref_49d);
    b(label_4d4);
  label_4d4:
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_515);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_507);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_4f9);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_4eb);
    ref_4dd = bustupLoad(bustup_f0);
    bustupWait(ref_4dd);
    ref_4df = bustupAlloc(ref_4dd, right, rgb(0,0,0));
    bustupFade(ref_4df, rgb(128,0,0), 30);
    ref_4e1 = dialogAlloc();
    ref_4e2 = msgShow(msg_62);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]あの女性は、しばらく行方不明だったのだが…
[tab]先ほど、無事に戻って来たのだ。
[tab]穢れなき民となってな。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_4e2);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_4e1);
    ref_4e7 = bustupFade(ref_4df, rgb(0,0,0), 10);
    bustupWait(ref_4e7);
    bustupFree(ref_4df);
    b(label_522);
  label_4eb:
    ref_4eb = bustupLoad(bustup_f0);
    bustupWait(ref_4eb);
    ref_4ed = bustupAlloc(ref_4eb, right, rgb(0,0,0));
    bustupFade(ref_4ed, rgb(128,0,0), 30);
    ref_4ef = dialogAlloc();
    ref_4f0 = msgShow(msg_63);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]君達の活躍が、街に混乱を招き、
[tab]状況を更に悪化させて行く…
[tab]全てが同じ。全てが繰り返しだ。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]君達は今、細かな差異こそあれ、
[tab]過ぎ去ったはずの過去と同じ境遇に
[tab]立たされている事に気付かんのかね？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_4f0);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_4ef);
    ref_4f5 = bustupFade(ref_4ed, rgb(0,0,0), 10);
    bustupWait(ref_4f5);
    bustupFree(ref_4ed);
    b(label_522);
  label_4f9:
    ref_4f9 = bustupLoad(bustup_f0);
    bustupWait(ref_4f9);
    ref_4fb = bustupAlloc(ref_4f9, right, rgb(0,0,0));
    bustupFade(ref_4fb, rgb(128,0,0), 30);
    ref_4fd = dialogAlloc();
    ref_4fe = msgShow(msg_64);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふふ…この世界の均衡が崩れようとしているな。
[tab]所詮、命を賭した最後の決断も、
[tab]人の業の前には無力に等しい…か。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]さて…
[tab]最後にその均衡を崩すのは誰かな？
[tab]鍵を握るのは君のようだが…
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_4fe);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_4fd);
    ref_503 = bustupFade(ref_4fb, rgb(0,0,0), 10);
    bustupWait(ref_503);
    bustupFree(ref_4fb);
    b(label_522);
  label_507:
    ref_507 = bustupLoad(bustup_f0);
    bustupWait(ref_507);
    ref_509 = bustupAlloc(ref_507, right, rgb(0,0,0));
    bustupFade(ref_509, rgb(128,0,0), 30);
    ref_50b = dialogAlloc();
    ref_50c = msgShow(msg_65);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]君は全てを知ったはずだ。
[tab]「向こう側」の世界の存在も、
[tab]「こちら側」の世界の持つ意味さえも。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]だがなお足掻くのはなぜだ？
[tab]仮初の平穏に、一体なんの意味がある？
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]矛盾だ。
[tab]やはり人は、矛盾を抱えたまま生き続ける、
[tab]不完全な生命なのだ。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_50c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_50b);
    ref_511 = bustupFade(ref_509, rgb(0,0,0), 10);
    bustupWait(ref_511);
    bustupFree(ref_509);
    b(label_522);
  label_515:
    ref_515 = bustupLoad(bustup_f0);
    bustupWait(ref_515);
    ref_517 = bustupAlloc(ref_515, right, rgb(0,0,0));
    bustupFade(ref_517, rgb(128,0,0), 30);
    ref_519 = dialogAlloc();
    ref_51a = msgShow(msg_66);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]さて…これがラストゲームだ。
[tab]この私に君達が示す答えを見せてくれ。
[tab]その為の舞台は、充分に整ったはずだ。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_51a);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_519);
    ref_51f = bustupFade(ref_517, rgb(0,0,0), 10);
    bustupWait(ref_51f);
    bustupFree(ref_517);
  label_522:
}

function HA_SHOP_END_0()
{
    ref_523 = bustupLoad(bustup_f0);
    bustupWait(ref_523);
    ref_525 = bustupAlloc(ref_523, right, rgb(0,0,0));
    bustupFade(ref_525, rgb(128,0,0), 30);
    ref_527 = dialogAlloc();
    ref_528 = msgShow(msg_67);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]今再び、時の円環は動き出した。
[tab]過ぎ去った時を追う咎人よ…
[tab]また会おう。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_528);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopOverlayInit();
    dialogFree(ref_527);
    ref_52e = bustupFade(ref_525, rgb(0,0,0), 10);
    bustupWait(ref_52e);
    bustupFree(ref_525);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_536);
    controlEnable();
    unitRestoreFacing(shopkeeper);
    b(label_539);
  label_536:
    bne(var_0, 1, label_539);
    call(EXITBOX);
    b(label_539);
  label_539:
}

function BOXWOMAN()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_56b);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_561);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_557);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_54d);
    unitFacePlayer(npc2);
    ref_544 = dialogAlloc();
    ref_545 = msgShow(msg_68);
/***************************************
[color(yellow)]オバサン[color(white)]
[tab]レッツ・ポジティブシンキングー！！
[tab]穢れなき民は素晴らしき民！
[tab]新しい時代を切り開く民なのだー！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_545);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_544);
    unitRestoreFacing(npc2);
    b(label_574);
  label_54d:
    unitFacePlayer(npc2);
    ref_54e = dialogAlloc();
    ref_54f = msgShow(msg_69);
/***************************************
[color(yellow)]オバサン[color(white)]
[tab]レッツ・ポジティブシンキングー！！
[tab]トリフネが我々を新たな時代へ導くのだー！
[tab]レッツ・ポジティブシンキングー！！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_54f);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_54e);
    unitRestoreFacing(npc2);
    b(label_574);
  label_557:
    unitFacePlayer(npc2);
    ref_558 = dialogAlloc();
    ref_559 = msgShow(msg_70);
/***************************************
[color(yellow)]オバサン[color(white)]
[tab]レッツ・ポジティブシンキングー！！
[tab]動き出すー！[tab]トリフネが動き出すー！
[tab]世界の滅亡、新時代の夜明けは目前だー！！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_559);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_558);
    unitRestoreFacing(npc2);
    b(label_574);
  label_561:
    unitFacePlayer(npc2);
    ref_562 = dialogAlloc();
    ref_563 = msgShow(msg_71);
/***************************************
[color(yellow)]オバサン[color(white)]
[tab]レッツ・ポジティブシンキングー！！
[tab]もうすぐ世界は滅亡する！！
[tab]優れた者、穢れ無き者だけが生き残るのだー！！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_563);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_562);
    unitRestoreFacing(npc2);
    b(label_574);
  label_56b:
    unitFacePlayer(npc2);
    ref_56c = dialogAlloc();
    ref_56d = msgShow(msg_72);
/***************************************
[color(yellow)]オバサン[color(white)]
[tab]レッツ・ポジティブシンキングー！！
[tab]だけど龍が消えてしまったー！？
[tab]滅亡は？[tab]新時代はどうなってしまうのー！？
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_56d);
    unitAnimationStop(npc2);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_56c);
    unitRestoreFacing(npc2);
  label_574:
    controlEnable();
}

function SIZUKA()
{
    controlDisable();
    bitGet(var_0, MBIT_SH_S_01);
    bne(var_0, 0, label_57a);
    b(label_587);
  label_57a:
    bne(var_0, 1, label_587);
    bitGet(var_0, MBIT_SH_H_01);
    bne(var_0, 0, label_584);
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_581);
    b(label_588);
    b(label_583);
  label_581:
    bne(var_0, 1, label_583);
    b(label_583);
  label_583:
    b(label_586);
  label_584:
    bne(var_0, 1, label_586);
    b(label_586);
  label_586:
    b(label_587);
  label_587:
    b(label_5d4);
  label_588:
    add(var_a, var_a, 1);
    boutrange(var_a, 0, 1, label_58c);
    b(label_590);
    b(label_590);
  label_58c:
    bne(var_a, 2, label_590);
    sub(var_a, var_a, 2);
    b(label_599);
    b(label_590);
  label_590:
    unitFacePlayer(npc1);
    ref_591 = dialogAlloc();
    ref_592 = msgShow(msg_73);
/***************************************
[color(yellow)]物静かな紳士[color(white)]
[tab]サラリーマンになって８年…
[tab]元々控えめだった私にとって、
[tab]社会はあまりにも厳しく…冷たかった。
[wait][clear][color(yellow)]物静かな紳士[color(white)]
[tab]最近はこうして、物静かにアンティークを
[tab]眺めることが唯一の楽しみなのです…
[tab]妹は心配しているかも知れませんが…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_592);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_591);
    unitRestoreFacing(npc1);
    b(label_660);
  label_599:
    unitFacePlayer(npc1);
    ref_59a = dialogAlloc();
    ref_59b = msgShow(msg_74);
/***************************************
[color(yellow)]物静かな紳士[color(white)]
[tab]あの…
[tab]私にまだ何かご用ですか？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_59b);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_59a);
    choiceSetResult(2);
    ref_5a1 = bustupLoad(bustup_1);
    bustupWait(ref_5a1);
    ref_5a3 = bustupAlloc(ref_5a1, center, rgb(0,0,0));
    bustupFade(ref_5a3, rgb(128,0,0), 30);
    ref_5a5 = dialogChoiceAlloc();
    ref_5a6 = msgShow(msg_75);
/***************************************
[tab]何の用でしょう？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear]
***************************************/
    ref_5a7 = textInputInit();
    wait(ref_5a6);
    dialogFree(ref_5a5);
    ref_5aa = bustupFade(ref_5a3, rgb(0,0,0), 10);
    bustupWait(ref_5aa);
    bustupFree(ref_5a3);
    wait(ref_5a7);
    choiceGetResult(var_0);
    bne(var_0, 0, label_5b2);
    b(label_5ba);
    b(label_5b9);
  label_5b2:
    bne(var_0, 1, label_5b6);
    unitRestoreFacing(npc1);
    b(label_5d4);
    b(label_5b9);
  label_5b6:
    bne(var_0, 2, label_5b9);
    unitRestoreFacing(npc1);
    b(label_5b9);
  label_5b9:
    b(label_660);
  label_5ba:
    ref_5ba = textInputPrompt();
    wait(ref_5ba);
    textInputCompare(msg_76, var_0);
    bne(var_0, 0, label_5c7);
    ref_5be = dialogAlloc();
    ref_5bf = msgShow(msg_77);
/***************************************
[color(yellow)]物静かな紳士[color(white)]
[tab]は？
[tab]い…いえ、私はそんな名前では…
[tab]人違いではありませんか？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_5bf);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_5be);
    unitRestoreFacing(npc1);
    b(label_660);
    b(label_5d3);
  label_5c7:
    bne(var_0, 1, label_5d3);
    ref_5c8 = dialogAlloc();
    ref_5c9 = msgShow(msg_78);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]
[tab]え！？
[tab]どうして私の名前をご存知なんですか？
[tab]え！？[tab]私の捜索願が出ていたのですか？
[wait][clear][color(yellow)]ホンダ[tab]リョウイチ[color(white)]
[tab]そ…そうですか…
[tab]きっと妹が出したのでしょう…
[tab]心配をかけてしまったな。
[wait][clear][color(yellow)]ホンダ[tab]リョウイチ[color(white)]
[tab]分かりました。妹と、しらいしさんには、
[tab]私から連絡しておきましょう。
[tab]わざわざ済みませんでした。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_5c9);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_5c8);
    bitSet(MBIT_HONDA_GET);
    bitSet(MBIT_SH_HH);
    unitRestoreFacing(npc1);
    b(label_660);
    b(label_5d3);
  label_5d3:
    b(label_660);
  label_5d4:
    bitGet(var_0, MBIT_HI_JIKANDUP);
    bnz(var_0, label_5d9);
    bitGet(var_0, MBIT_HI_JIKANSELL);
    bnz(var_0, label_5dc);
    b(label_5df);
  label_5d9:
    bitGet(var_0, MBIT_FUKUSEITALK);
    bnz(var_0, label_5df);
    b(label_640);
  label_5dc:
    bitGet(var_0, MBIT_CADETALK);
    bnz(var_0, label_5df);
    b(label_640);
  label_5df:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_627);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_617);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_607);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_5f7);
    unitFacePlayer(npc1);
    ref_5e8 = dialogAlloc();
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_5ed);
    msgShow(msg_79);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_5f0);
  label_5ed:
    bne(var_0, 1, label_5f0);
    msgShow(msg_80);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_5f0);
  label_5f0:
    ref_5f0 = msgShow(msg_81);
/***************************************
[tab]あそこの女の人はどうしたのでしょうか？
[tab]無事に戻って来たかと思えば、
[tab]さっきから同じ言葉を繰り返してばかりで…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_5f0);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_5e8);
    unitRestoreFacing(npc1);
    b(label_660);
  label_5f7:
    unitFacePlayer(npc1);
    ref_5f8 = dialogAlloc();
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_5fd);
    msgShow(msg_82);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_600);
  label_5fd:
    bne(var_0, 1, label_600);
    msgShow(msg_83);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_600);
  label_600:
    ref_600 = msgShow(msg_84);
/***************************************
[tab]新世塾は世界を滅亡させてまで、
[tab]穢れある人間を消そうとしている。
[tab]それを恐れ講演会に赴く人も多いようです。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_600);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_5f8);
    unitRestoreFacing(npc1);
    b(label_660);
  label_607:
    unitFacePlayer(npc1);
    ref_608 = dialogAlloc();
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_60d);
    msgShow(msg_85);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_610);
  label_60d:
    bne(var_0, 1, label_610);
    msgShow(msg_86);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_610);
  label_610:
    ref_610 = msgShow(msg_87);
/***************************************
[tab]あの…イン…なんとか、という本を
[tab]ご存知ありませんか？
[tab]なぜか急に、そんな本の事を思い出しまして…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_610);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_608);
    unitRestoreFacing(npc1);
    b(label_660);
  label_617:
    unitFacePlayer(npc1);
    ref_618 = dialogAlloc();
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_61d);
    msgShow(msg_88);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_620);
  label_61d:
    bne(var_0, 1, label_620);
    msgShow(msg_89);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_620);
  label_620:
    ref_620 = msgShow(msg_90);
/***************************************
[tab]穢れを消す事が、人類の滅亡へと繋がってしまう…
[tab]とても悲しい事ですね…
[tab]人間は…私は…このままでいいのだろうか…
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_620);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_618);
    unitRestoreFacing(npc1);
    b(label_660);
  label_627:
    unitFacePlayer(npc1);
    ref_628 = dialogAlloc();
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_62d);
    msgShow(msg_91);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_630);
  label_62d:
    bne(var_0, 1, label_630);
    msgShow(msg_92);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_630);
  label_630:
    ref_630 = msgShow(msg_93);
/***************************************
[tab]一体、この街はどうなってしまうのでしょう…
[tab]怖くて震えが止まりませんが、
[tab]私に何が出来るかを考えているところです。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_630);
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_637);
    msgShow(msg_94);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_63a);
  label_637:
    bne(var_0, 1, label_63a);
    msgShow(msg_95);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_63a);
  label_63a:
    ref_63a = msgShow(msg_96);
/***************************************
[tab]逃げてばかりの私でしたが…
[tab]最後くらい、力いっぱい何かをやって
[tab]死にたいですからね…
[wait][clear]
***************************************/
    wait(ref_63a);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_628);
    unitRestoreFacing(npc1);
    b(label_660);
  label_640:
    unitFacePlayer(npc1);
    ref_641 = dialogAlloc();
    bitGet(var_0, MBIT_CADETALK);
    bne(var_0, 0, label_650);
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_648);
    msgShow(msg_97);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_64b);
  label_648:
    bne(var_0, 1, label_64b);
    msgShow(msg_98);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_64b);
  label_64b:
    ref_64b = msgShow(msg_99);
/***************************************
[tab]この時間城では、
[tab]魔法のカードまで販売してたんですね。
[tab]いやあ、噂を聞いたときは驚きましたよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_64b);
    bitSet(MBIT_CADETALK);
    b(label_65d);
  label_650:
    bne(var_0, 1, label_65d);
    bitGet(var_0, MBIT_HONDA_GET);
    bne(var_0, 0, label_655);
    msgShow(msg_100);
/***************************************
[color(yellow)]物静かな紳士[color(white)]

***************************************/
    b(label_658);
  label_655:
    bne(var_0, 1, label_658);
    msgShow(msg_101);
/***************************************
[color(yellow)]ホンダ[tab]リョウイチ[color(white)]

***************************************/
    b(label_658);
  label_658:
    ref_658 = msgShow(msg_102);
/***************************************
[tab]あの伯爵は、魔法のカードの
[tab]複製までしてしまうそうですよ。
[tab]やはり只者ではありませんねえ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_658);
    bitSet(MBIT_FUKUSEITALK);
    b(label_65d);
  label_65d:
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_641);
    unitRestoreFacing(npc1);
  label_660:
    controlEnable();
}

function DOORBOX()
{
    controlDisable();
    objAnimRotate(obj_8, 0, -90, 0, 30, 0);
    objAnimRotate(obj_27, 0, 90, 0, 30, 0);
    sndMusicPlay(sound_3066, 127);
    objAnimWait(obj_8);
    objAnimWait(obj_27);
    call(EXITBOX);
}

function warp1()
{
    call(DOORBOX);
}

function EXITBOX()
{
    controlDisable();
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function HA_SHOP_EXPLAIN_0()
{
    choiceSetResult(2);
    ref_671 = dialogChoiceAlloc();
    ref_672 = msgShow(msg_103);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]何を聞きたいのかね？
[choice(3)]売買
[if_all(MBIT_HI_JIKANDUP)]カードを登録
やめる
[end_choice][clear]
***************************************/
    wait(ref_672);
    dialogFree(ref_671);
    choiceGetResult(var_0);
    bne(var_0, 0, label_67c);
    ref_677 = dialogAlloc();
    ref_678 = msgShow(msg_104);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふむ、「売買」についてだな。
[tab]まず初めに、購入の説明をしよう。
[tab]この時の城で「カードを買う」を選ぶと
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]特殊なカードを購入できる。
[tab]有用なカードほど値段が高い。
[tab]…当然のことではあるが。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]金を無駄にしないよう、よく検討してから買いたまえ。
[tab]つぎは、売却の説明だ。
[tab]「アイテムを売る」を選択すると、種類の選択になる。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]売却する物の種類を選択し、その後に物を選択するのだ。
[tab]買い取り価格は元値の約半額ほどになる。
[tab]装備中のものと一部の物は売却することができない。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]…こんなところかね。
[wait][clear]
***************************************/
    wait(ref_678);
    dialogFree(ref_677);
    b(label_684);
  label_67c:
    bne(var_0, 1, label_682);
    ref_67d = dialogAlloc();
    ref_67e = msgShow(msg_105);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]ふむ、「カードを登録」についてだな。
[tab]この時の城で扱っているカードの種類には限りがある…
[tab]しかし、その種類を増やす方法があるのだよ。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]それがこの「カードを登録」というわけだ。
[tab]まず「カードを登録」を選び、
[tab]我が店に置いてほしいカードを一枚差し出すのだ。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]…犠牲なくして得られるものは何も無い、当然だな。
[tab]さすれば、私がそのカードを無限に複製し、
[tab]購入リストに並べさせていただく。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]その後、必要なだけ思う存分買うがいい。
[tab]私は取り扱う商品が増える。
[tab]君達は有用なカードをいくらでも手に入れられる。
[wait][clear][color(yellow)]伯爵[color(white)]
[tab]…お互いに有意義な行為だと思わんかね？
[wait][clear]
***************************************/
    wait(ref_67e);
    dialogFree(ref_67d);
    b(label_684);
  label_682:
    bne(var_0, 2, label_684);
    b(label_684);
  label_684:
}

function NOITEM()
{
    unitFacePlayer(shopkeeper);
    ref_686 = bustupLoad(bustup_f0);
    bustupWait(ref_686);
    ref_688 = bustupAlloc(ref_686, right, rgb(0,0,0));
    bustupFade(ref_688, rgb(128,0,0), 30);
    ref_68a = dialogAlloc();
    ref_68b = msgShow(msg_106);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]残念ながら、私が買い取れるものを持っていないようだ。
[tab]出なおしてきたまえ。[wait][clear]
***************************************/
    wait(ref_68b);
    dialogFree(ref_68a);
    ref_68e = bustupFade(ref_688, rgb(0,0,0), 10);
    bustupWait(ref_68e);
    bustupFree(ref_688);
    li(var_5, 20);
}

function DECIDE_BUY()
{
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_695 = bustupLoad(bustup_f0);
    bustupWait(ref_695);
    ref_697 = bustupAlloc(ref_695, left, rgb(0,0,0));
    bustupFade(ref_697, rgb(128,0,0), 30);
    ref_699 = dialogAlloc();
    choiceSetResult(1);
    ref_69b = msgShow(msg_107);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab][var(msg_var_0)]円いただくことになるが、
[tab]よろしいかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_69b);
    choiceGetResult(var_7);
    bne(var_7, 0, label_6a2);
    sndMusicPlay(sound_3037, 127);
    li(var_7, 1);
    b(label_6a5);
  label_6a2:
    bne(var_7, 1, label_6a5);
    li(var_7, 0);
    b(label_6a5);
  label_6a5:
    wait(ref_69b);
    dialogFree(ref_699);
    ref_6a7 = bustupFade(ref_697, rgb(0,0,0), 10);
    bustupWait(ref_6a7);
    bustupFree(ref_697);
    li(var_5, 20);
}

function DECIDE_SELL()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_6af = bustupLoad(bustup_f0);
    bustupWait(ref_6af);
    ref_6b1 = bustupAlloc(ref_6af, left, rgb(0,0,0));
    bustupFade(ref_6b1, rgb(128,0,0), 30);
    ref_6b3 = dialogAlloc();
    choiceSetResult(1);
    ref_6b5 = msgShow(msg_108);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab][var(msg_var_0)]円で買い取ることになるが、
[tab]よろしいかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_6b5);
    choiceGetResult(var_7);
    bne(var_7, 0, label_6bc);
    sndMusicPlay(sound_3037, 127);
    li(var_7, 1);
    b(label_6bf);
  label_6bc:
    bne(var_7, 1, label_6bf);
    li(var_7, 0);
    b(label_6bf);
  label_6bf:
    wait(ref_6b5);
    ref_6c0 = bustupFade(ref_6b1, rgb(0,0,0), 10);
    bustupWait(ref_6c0);
    bustupFree(ref_6b1);
    dialogFree(ref_6b3);
    li(var_5, 20);
}

function DECIDE_REGIST()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_6c9 = bustupLoad(bustup_f0);
    bustupWait(ref_6c9);
    ref_6cb = bustupAlloc(ref_6c9, left, rgb(0,0,0));
    bustupFade(ref_6cb, rgb(128,0,0), 30);
    ref_6cd = dialogAlloc();
    ref_6ce = msgShow(msg_109);
/***************************************
[color(yellow)]伯爵[color(white)]
[tab]では、登録の代償として、
[tab]そのカードを一枚いただくことになる。
[tab]よろしいかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_6ce);
    choiceGetResult(var_7);
    bne(var_7, 0, label_6d5);
    sndMusicPlay(sound_3067, 127);
    li(var_7, 1);
    b(label_6d8);
  label_6d5:
    bne(var_7, 1, label_6d8);
    li(var_7, 0);
    b(label_6d8);
  label_6d8:
    wait(ref_6ce);
    dialogFree(ref_6cd);
    ref_6da = bustupFade(ref_6cb, rgb(0,0,0), 10);
    bustupWait(ref_6da);
    bustupFree(ref_6cb);
}
