function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3049, 127);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_6);
    b(label_1a);
  label_6:
    bne(var_0, 1, label_1a);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bne(var_0, 0, label_a);
    b(label_19);
  label_a:
    bne(var_0, 1, label_19);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bitGet(var_1, MBIT_SIRAHENNISHU_2);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_16);
    rand(var_0, 1);
    bne(var_0, 0, label_13);
    bitSet(MBIT_SIRAHENNISHU_2);
    b(label_15);
  label_13:
    bitSet(MBIT_SIRAHENNISHU);
    b(label_15);
  label_15:
    b(label_18);
  label_16:
    bne(var_1, 1, label_18);
    b(label_18);
  label_18:
    b(label_19);
  label_19:
    b(label_1a);
  label_1a:
    envTriggerSet(DOORBOX, 131, 1, line, coll_0);
    bitGet(var_0, EBIT_E008C);
    bne(var_0, 0, label_1e);
    b(label_26);
  label_1e:
    bne(var_0, 1, label_26);
    bitGet(var_0, MBIT_KUZU_HATUNEKO);
    bne(var_0, 0, label_23);
    bitSet(MBIT_NEKO_SAGASI);
    b(label_25);
  label_23:
    bne(var_0, 1, label_25);
    b(label_25);
  label_25:
    b(label_26);
  label_26:
    bitGet(var_0, MBIT_SIRA_HATURAITEN);
    bne(var_0, 0, label_2a);
    cameraSet(southeast, 400, 0, -840);
    b(label_2d);
  label_2a:
    bne(var_0, 1, label_2d);
    cameraSet(northeast, 365, 0, -400);
    b(label_2d);
  label_2d:
    li(var_0, 0);
    li(var_1, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_3c);
    li(var_0, 0);
    b(label_41);
  label_3c:
    ref_3c = dialogAlloc();
    ref_3d = msgShow(msg_0);
/***************************************
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear]
***************************************/
    wait(ref_3d);
    dialogFree(ref_3c);
    b(label_41);
  label_41:
    bitGet(var_0, EBIT_E0046);
    bez(var_0, label_4f);
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_49);
    ref_45 = spriteLoad(sprite_1f);
    wait(ref_45);
    unitSpawn(nanjo, sprite_1f, 230, 0, -330, west, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
  label_49:
    partyMemberCheck(var_0, elly);
    bez(var_0, label_4f);
    ref_4b = spriteLoad(sprite_23);
    wait(ref_4b);
    unitSpawn(elly, sprite_23, 230, 0, -730, south, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
  label_4f:
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_57);
    bitGet(var_0, EBIT_E0038);
    bez(var_0, label_57);
    ref_53 = spriteLoad(sprite_6a);
    wait(ref_53);
    unitSpawn(makimura, sprite_6a, 420, 0, -570, south, none);
    unitTriggerSet(makimura, SAGIBOX, 255, 1);
  label_57:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_5d);
    ref_59 = spriteLoad(sprite_6);
    wait(ref_59);
    unitSpawn(ulala, sprite_6, 165, 0, -440, east, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_5d:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_63);
    ref_5f = spriteLoad(sprite_d);
    wait(ref_5f);
    unitSpawn(katsuya, sprite_d, 490, 0, -620, east, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_63:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_69);
    ref_65 = spriteLoad(sprite_13);
    wait(ref_65);
    unitSpawn(baofu, sprite_13, 125, 0, -840, west, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_69:
    ref_69 = spriteLoad(sprite_90);
    wait(ref_69);
    unitSpawn(shopkeeper, sprite_90, 650, 0, -270, east, none);
    envTriggerSet(SHOP, 224, 1, collision_2, coll_0);
    envTriggerSet(SHOP, 56, 1, collision_2, coll_1);
    envTriggerSet(SHOP, 112, 1, collision_2, coll_2);
    ref_6f = spriteLoad(sprite_c0);
    wait(ref_6f);
    unitSpawn3d(npc1, sprite_c0, 445, -20, -248, west, none);
    unitShadowRadius(npc1, 0);
    unitTriggerSet(npc1, MAN1, 255, 1);
    ref_74 = spriteLoad(sprite_ca);
    wait(ref_74);
    unitSpawn(npc2, sprite_ca, 250, 0, -140, north, none);
    unitPalette(npc2, 2);
    unitTriggerSet(npc2, MAN2, 255, 1);
    ref_79 = spriteLoad(sprite_ab);
    wait(ref_79);
    unitSpawn(npc3, sprite_ab, 740, 0, -680, west, none);
    unitTriggerSet(npc3, MAN3, 255, 1);
    ref_7d = spriteLoad(sprite_0);
    wait(ref_7d);
    ref_7f = spriteLoad(sprite_2);
    wait(ref_7f);
    bitGet(var_0, MBIT_SIRA_HATURAITEN);
    bne(var_0, 0, label_85);
    playerInit(south);
    b(label_88);
  label_85:
    bne(var_0, 1, label_88);
    playerInit(west);
    b(label_88);
  label_88:
    controlDisable();
    unitIdleOnAll();
    unitIdleOff(npc1);
    unitRevolveAnimationPlay(npc1, animrevolve_1);
    unitFace8(npc1, west);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_b9);
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_a9);
    unitFacePlayer(ulala);
    ref_9a = bustupLoad(bustup_18);
    bustupWait(ref_9a);
    ref_9c = bustupAlloc(ref_9a, left, rgb(0,0,0));
    bustupFade(ref_9c, rgb(128,0,0), 30);
    ref_9e = dialogAlloc();
    ref_9f = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]私、みんなに迷惑かけちゃったね…
[tab]ごめん！[tab]この通～りだから、許してよぉ。
[tab]…ダメ？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_9f);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_9e);
    ref_a4 = bustupFade(ref_9c, rgb(0,0,0), 10);
    bustupWait(ref_a4);
    bustupFree(ref_9c);
    unitRestoreFacing(ulala);
    b(label_c9);
  label_a9:
    unitFacePlayer(ulala);
    ref_aa = bustupLoad(bustup_17);
    bustupWait(ref_aa);
    ref_ac = bustupAlloc(ref_aa, left, rgb(0,0,0));
    bustupFade(ref_ac, rgb(128,0,0), 30);
    ref_ae = dialogAlloc();
    ref_af = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]な～んかムカツクなぁ～
[tab]私達とは育ちがチガウ！[tab]って言われてるみたい。
[tab]ねぇマーヤ、そう思わない？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_af);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ae);
    ref_b4 = bustupFade(ref_ac, rgb(0,0,0), 10);
    bustupWait(ref_b4);
    bustupFree(ref_ac);
    unitRestoreFacing(ulala);
    b(label_c9);
  label_b9:
    unitFacePlayer(ulala);
    ref_ba = bustupLoad(bustup_1b);
    bustupWait(ref_ba);
    ref_bc = bustupAlloc(ref_ba, left, rgb(0,0,0));
    bustupFade(ref_bc, rgb(128,0,0), 30);
    ref_be = dialogAlloc();
    ref_bf = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]げげっ！？[tab]なにコレ！？
[tab]ねぇ見てよマーヤ、あんこ餃子だって！
[tab]聞いた事無いよ、そんなの。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_bf);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_be);
    ref_c4 = bustupFade(ref_bc, rgb(0,0,0), 10);
    bustupWait(ref_c4);
    bustupFree(ref_bc);
    unitRestoreFacing(ulala);
    b(label_c9);
  label_c9:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_114);
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_104);
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_f4);
    bitGet(var_0, EBIT_E0038);
    bnz(var_0, label_e4);
    unitFacePlayer(katsuya);
    ref_d5 = bustupLoad(bustup_21);
    bustupWait(ref_d5);
    ref_d7 = bustupAlloc(ref_d5, left, rgb(0,0,0));
    bustupFade(ref_d7, rgb(128,0,0), 30);
    ref_d9 = dialogAlloc();
    ref_da = msgShow(msg_4);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]彼女がマンサーチャーなのか？
[tab]見かけで判断する気は無いが…
[tab]信用していいのか？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_da);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_d9);
    ref_df = bustupFade(ref_d7, rgb(0,0,0), 10);
    bustupWait(ref_df);
    bustupFree(ref_d7);
    unitRestoreFacing(katsuya);
    b(label_124);
  label_e4:
    unitFacePlayer(katsuya);
    ref_e5 = bustupLoad(bustup_21);
    bustupWait(ref_e5);
    ref_e7 = bustupAlloc(ref_e5, left, rgb(0,0,0));
    bustupFade(ref_e7, rgb(128,0,0), 30);
    ref_e9 = dialogAlloc();
    ref_ea = msgShow(msg_5);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]全く、自分の立場が理解出来ていない様だな。
[tab]いいか牧村！[tab]ここの店主の協力がなければ、
[tab]お前は死んでいたのかも知れないんだぞ！
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_ea);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_e9);
    ref_ef = bustupFade(ref_e7, rgb(0,0,0), 10);
    bustupWait(ref_ef);
    bustupFree(ref_e7);
    unitRestoreFacing(katsuya);
    b(label_124);
  label_f4:
    unitFacePlayer(katsuya);
    ref_f5 = bustupLoad(bustup_27);
    bustupWait(ref_f5);
    ref_f7 = bustupAlloc(ref_f5, left, rgb(0,0,0));
    bustupFade(ref_f7, rgb(128,0,0), 30);
    ref_f9 = dialogAlloc();
    ref_fa = msgShow(msg_6);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]何と言うか…その…芹沢君！
[tab]ああいうクズの事は早く忘れるんだ！
[tab]…野良犬に噛まれたとでも思って……
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_fa);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_f9);
    ref_ff = bustupFade(ref_f7, rgb(0,0,0), 10);
    bustupWait(ref_ff);
    bustupFree(ref_f7);
    unitRestoreFacing(katsuya);
    b(label_124);
  label_104:
    unitFacePlayer(katsuya);
    ref_105 = bustupLoad(bustup_21);
    bustupWait(ref_105);
    ref_107 = bustupAlloc(ref_105, left, rgb(0,0,0));
    bustupFade(ref_107, rgb(128,0,0), 30);
    ref_109 = dialogAlloc();
    ref_10a = msgShow(msg_7);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]仕事柄、こういう店へ出入りする機会は多いが、
[tab]特別意識した事など無かったな。
[tab]生活環境が違うと、感じる事も違うと言う事か。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_10a);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_109);
    ref_10f = bustupFade(ref_107, rgb(0,0,0), 10);
    bustupWait(ref_10f);
    bustupFree(ref_107);
    unitRestoreFacing(katsuya);
    b(label_124);
  label_114:
    unitFacePlayer(katsuya);
    ref_115 = bustupLoad(bustup_27);
    bustupWait(ref_115);
    ref_117 = bustupAlloc(ref_115, left, rgb(0,0,0));
    bustupFade(ref_117, rgb(128,0,0), 30);
    ref_119 = dialogAlloc();
    ref_11a = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]この店の常連客は一体何を目当てにここへ来る？
[tab]彼女の愉快な話か？[tab]…まさかこの特殊メニュー？
[tab]バカな…ナンセンスだ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_11a);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_119);
    ref_11f = bustupFade(ref_117, rgb(0,0,0), 10);
    bustupWait(ref_11f);
    bustupFree(ref_117);
    unitRestoreFacing(katsuya);
    b(label_124);
  label_124:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_17c);
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_15f);
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_14f);
    bitGet(var_0, EBIT_E0038);
    bnz(var_0, label_13f);
    unitFacePlayer(baofu);
    ref_130 = bustupLoad(bustup_31);
    bustupWait(ref_130);
    ref_132 = bustupAlloc(ref_130, left, rgb(0,0,0));
    bustupFade(ref_132, rgb(128,0,0), 30);
    ref_134 = dialogAlloc();
    ref_135 = msgShow(msg_9);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ここの店主、噂以上にあやしいぜ。
[tab]おっと、あんまり人の事は言えねぇか？
[tab]俺も同類だからな。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_135);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_134);
    ref_13a = bustupFade(ref_132, rgb(0,0,0), 10);
    bustupWait(ref_13a);
    bustupFree(ref_132);
    unitRestoreFacing(baofu);
    b(label_18c);
  label_13f:
    unitFacePlayer(baofu);
    ref_140 = bustupLoad(bustup_2d);
    bustupWait(ref_140);
    ref_142 = bustupAlloc(ref_140, left, rgb(0,0,0));
    bustupFade(ref_142, rgb(128,0,0), 30);
    ref_144 = dialogAlloc();
    ref_145 = msgShow(msg_10);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]あのサギ野郎、犯人役に酔ってんな？
[tab]普通のヤツはそんなセリフは吐かねぇって。
[tab]刑事ドラマの見過ぎなんだよ！
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_145);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_144);
    ref_14a = bustupFade(ref_142, rgb(0,0,0), 10);
    bustupWait(ref_14a);
    bustupFree(ref_142);
    unitRestoreFacing(baofu);
    b(label_18c);
  label_14f:
    unitFacePlayer(baofu);
    ref_150 = bustupLoad(bustup_2d);
    bustupWait(ref_150);
    ref_152 = bustupAlloc(ref_150, left, rgb(0,0,0));
    bustupFade(ref_152, rgb(128,0,0), 30);
    ref_154 = dialogAlloc();
    ref_155 = msgShow(msg_11);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢のヤツ、無理しやがって。
[tab]まぁ、これで少しは成長出来たんじゃねぇか？
[tab]…おい芹沢！[tab]お前、甘ったれてんじゃねぇぞ！
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_155);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_154);
    ref_15a = bustupFade(ref_152, rgb(0,0,0), 10);
    bustupWait(ref_15a);
    bustupFree(ref_152);
    unitRestoreFacing(baofu);
    b(label_18c);
  label_15f:
    unitFacePlayer(baofu);
    ref_160 = bustupLoad(bustup_31);
    bustupWait(ref_160);
    ref_162 = bustupAlloc(ref_160, left, rgb(0,0,0));
    bustupFade(ref_162, rgb(128,0,0), 30);
    ref_164 = dialogAlloc();
    ref_165 = msgShow(msg_12);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]お上品で世間知らずなヤツにゃあ、
[tab]この店の良さはわかんねぇだろうなぁ。
[tab]…耳をすますと聞こえてくる、あの……
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_165);
    ref_168 = bustupFade(ref_162, rgb(0,0,0), 10);
    bustupWait(ref_168);
    bustupFree(ref_162);
    delayClear();
    delayWait(4);
    ref_16d = bustupLoad(bustup_2f);
    bustupWait(ref_16d);
    ref_16f = bustupAlloc(ref_16d, left, rgb(0,0,0));
    bustupFade(ref_16f, rgb(128,0,0), 30);
    ref_171 = msgShow(msg_13);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]野球中継！？[tab]忘れてたぜ！
[tab]今日は半神ジャガーズの試合がある日じゃねぇか！
[tab]くっそー、欠かさず見てたのにな～
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2f, 1);
    wait(ref_171);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_164);
    ref_176 = bustupFade(ref_16f, rgb(0,0,0), 10);
    bustupWait(ref_176);
    bustupFree(ref_16f);
    unitRestoreFacing(baofu);
    bitSet(MBIT_PAOFU_HANSIN);
    b(label_18c);
  label_17c:
    unitFacePlayer(baofu);
    ref_17d = bustupLoad(bustup_2f);
    bustupWait(ref_17d);
    ref_17f = bustupAlloc(ref_17d, left, rgb(0,0,0));
    bustupFade(ref_17f, rgb(128,0,0), 30);
    ref_181 = dialogAlloc();
    ref_182 = msgShow(msg_14);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]五目バナナそばにあんこ餃子ぁ？
[tab]美食天堂と言われる香港にだって
[tab]そんなものねぇぞ？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_182);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_181);
    ref_187 = bustupFade(ref_17f, rgb(0,0,0), 10);
    bustupWait(ref_187);
    bustupFree(ref_17f);
    unitRestoreFacing(baofu);
    b(label_18c);
  label_18c:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_1a1);
    unitFacePlayer(nanjo);
    ref_192 = bustupLoad(bustup_36);
    bustupWait(ref_192);
    ref_194 = bustupAlloc(ref_192, left, rgb(0,0,0));
    bustupFade(ref_194, rgb(128,0,0), 30);
    ref_196 = dialogAlloc();
    ref_197 = msgShow(msg_15);
/***************************************
[color(yellow)]南条[color(white)]
[tab]この様な雰囲気の店は、あまり好みではない。
[tab]…が、広く人々の心を知るのには良さそうだな。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_197);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_196);
    ref_19c = bustupFade(ref_194, rgb(0,0,0), 10);
    bustupWait(ref_19c);
    bustupFree(ref_194);
    unitRestoreFacing(nanjo);
    b(label_1b0);
  label_1a1:
    unitFacePlayer(nanjo);
    ref_1a2 = bustupLoad(bustup_36);
    bustupWait(ref_1a2);
    ref_1a4 = bustupAlloc(ref_1a2, left, rgb(0,0,0));
    bustupFade(ref_1a4, rgb(128,0,0), 30);
    ref_1a6 = dialogAlloc();
    ref_1a7 = msgShow(msg_16);
/***************************************
[color(yellow)]南条[color(white)]
[tab]この店には食した事の無い料理があるな。
[tab]うむ、我が日本の料理も奥が深い。
[tab]食前方丈も飽きた所だ。…一つ試してみるか？
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_1a7);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1a6);
    ref_1ac = bustupFade(ref_1a4, rgb(0,0,0), 10);
    bustupWait(ref_1ac);
    bustupFree(ref_1a4);
    unitRestoreFacing(nanjo);
  label_1b0:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_1c5);
    unitFacePlayer(elly);
    ref_1b6 = bustupLoad(bustup_41);
    bustupWait(ref_1b6);
    ref_1b8 = bustupAlloc(ref_1b6, left, rgb(0,0,0));
    bustupFade(ref_1b8, rgb(128,0,0), 30);
    ref_1ba = dialogAlloc();
    ref_1bb = msgShow(msg_17);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]これが赤提灯ですの？
[tab]Ｗｏｗ！[tab]驚きましたわ。
[tab]…Ｍｅｎｕはどこにありますの？
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_1bb);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_1ba);
    ref_1c0 = bustupFade(ref_1b8, rgb(0,0,0), 10);
    bustupWait(ref_1c0);
    bustupFree(ref_1b8);
    unitRestoreFacing(elly);
    b(label_1d4);
  label_1c5:
    unitFacePlayer(elly);
    ref_1c6 = bustupLoad(bustup_3d);
    bustupWait(ref_1c6);
    ref_1c8 = bustupAlloc(ref_1c6, left, rgb(0,0,0));
    bustupFade(ref_1c8, rgb(128,0,0), 30);
    ref_1ca = dialogAlloc();
    ref_1cb = msgShow(msg_18);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｏｈ[tab]ｎｏ！[tab]私、勉強不足でしたわ。
[tab]Ｊａｐａｎにこの様な料理があったなんて。
[tab]…でも、Ｓｔｒａｎｇｅな組み合わせですわね？
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_1cb);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_1ca);
    ref_1d0 = bustupFade(ref_1c8, rgb(0,0,0), 10);
    bustupWait(ref_1d0);
    bustupFree(ref_1c8);
    unitRestoreFacing(elly);
  label_1d4:
    controlEnable();
}

function B_TATU()
{
}

function SAGIBOX()
{
    controlDisable();
    unitFacePlayer(makimura);
    ref_1d9 = bustupLoad(bustup_128);
    bustupWait(ref_1d9);
    ref_1db = bustupAlloc(ref_1d9, right, rgb(0,0,0));
    bustupFade(ref_1db, rgb(128,0,0), 30);
    ref_1dd = dialogAlloc();
    ref_1de = msgShow(msg_19);
/***************************************
[color(yellow)]牧村[color(white)]
[tab]そこのババアだな？
[tab]ババアがオレの居場所をバラしたんだな！？
[tab]くそぉ、覚えてろよ！
[wait][clear]
***************************************/
    unitAnimationPlay(makimura, animation_26, 1);
    wait(ref_1de);
    unitAnimationPlay(makimura, animation_0, 1);
    dialogFree(ref_1dd);
    ref_1e3 = bustupFade(ref_1db, rgb(0,0,0), 10);
    bustupWait(ref_1e3);
    bustupFree(ref_1db);
    unitRestoreFacing(makimura);
    controlEnable();
}

function MAN1()
{
    controlDisable();
    unitSpawn3d(npc1, sprite_c0, 422, -20, -248, east, none);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bne(var_0, 0, label_1ee);
    b(label_1fc);
  label_1ee:
    bne(var_0, 1, label_1fc);
    bitGet(var_0, MBIT_SIRAHENNI_MIHA);
    bne(var_0, 0, label_1f9);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bne(var_0, 0, label_1f5);
    b(label_22c);
    b(label_1f8);
  label_1f5:
    bne(var_0, 1, label_1f8);
    b(label_232);
    b(label_1f8);
  label_1f8:
    b(label_1fb);
  label_1f9:
    bne(var_0, 1, label_1fb);
    b(label_1fb);
  label_1fb:
    b(label_1fc);
  label_1fc:
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_1ff);
    b(label_207);
  label_1ff:
    bne(var_0, 1, label_207);
    bitGet(var_0, MBIT_SIRAMAN_MIHA);
    bne(var_0, 0, label_204);
    b(label_226);
    b(label_206);
  label_204:
    bne(var_0, 1, label_206);
    b(label_206);
  label_206:
    b(label_207);
  label_207:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_221);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_21c);
    bitGet(var_0, EBIT_E0038);
    bez(var_0, label_210);
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_210);
    b(label_215);
  label_210:
    ref_210 = dialogAlloc();
    ref_211 = msgShow(msg_20);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]いやァ～オバチャンの料理はホント効くッス。
[tab]なんかこう、体が熱くなるんスよ。
[tab]今なら誰にも負ける気がしないッス！
[wait][clear]
***************************************/
    wait(ref_211);
    dialogFree(ref_210);
    b(label_238);
  label_215:
    ref_215 = dialogAlloc();
    ref_216 = msgShow(msg_21);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]…え、詐欺男、見つけたんスか？
[tab]おォ～オバチャンの情報はすごいッス。
[tab]さすがマンサーチャーッスね！
[wait][clear]
***************************************/
    wait(ref_216);
    ref_218 = msgShow(msg_22);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]これで街の人達も、
[tab]オバチャンの話を信じるようになるッスね！
[wait][clear]
***************************************/
    wait(ref_218);
    dialogFree(ref_215);
    b(label_238);
  label_21c:
    ref_21c = dialogAlloc();
    ref_21d = msgShow(msg_23);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]何やら誘拐事件が頻発しているらしいッスよ。
[tab]ＪＯＫＥＲ事件もどうなる事やら…
[tab]ホント、物騒な世の中ッス。
[wait][clear]
***************************************/
    wait(ref_21d);
    dialogFree(ref_21c);
    b(label_238);
  label_221:
    ref_221 = dialogAlloc();
    ref_222 = msgShow(msg_24);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]無個性化が進む若者ッスか～
[tab]まぁオバチャンの人生が個性的過ぎるッス。
[tab]…でも、どこまでホントッスかね～？
[wait][clear]
***************************************/
    wait(ref_222);
    dialogFree(ref_221);
    b(label_238);
  label_226:
    ref_226 = dialogAlloc();
    ref_227 = msgShow(msg_25);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]ここのオバチャン、堂々とマンサーチャーを
[tab]始めたッス！[tab]いつまでも隠しきれるもんじゃ
[tab]ないから、開き直ったッスね。
[wait][clear]
***************************************/
    wait(ref_227);
    dialogFree(ref_226);
    bitSet(MBIT_SIRAMAN_MIHA);
    b(label_238);
  label_22c:
    ref_22c = dialogAlloc();
    ref_22d = msgShow(msg_26);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]オバチャンってば、
[tab]夢を実現するなんてすごいッスよね。
[tab]発売日が待ちどおしいッス！！
[wait][clear]
***************************************/
    wait(ref_22d);
    dialogFree(ref_22c);
    bitSet(MBIT_SIRAHENNI_MIHA);
    b(label_238);
  label_232:
    ref_232 = dialogAlloc();
    ref_233 = msgShow(msg_27);
/***************************************
[color(yellow)]浪人生[color(white)]
[tab]オバチャンってば、
[tab]夢を実現するなんてすごいッスよね。
[tab]…でも、自分はちょっと遠慮したいッス。
[wait][clear]
***************************************/
    wait(ref_233);
    dialogFree(ref_232);
    bitSet(MBIT_SIRAHENNI_MIHA);
    b(label_238);
  label_238:
    controlEnable();
    unitIdleOff(npc1);
    unitRevolveAnimationPlay(npc1, animrevolve_1);
    unitFace8(npc1, west);
    unitSpawn3d(npc1, sprite_c0, 445, -20, -248, west, none);
}

function MAN2()
{
    controlDisable();
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    bitClear(LBIT_0007);
    bitClear(LBIT_0008);
    bitClear(LBIT_0009);
    li(var_5, 0);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bez(var_0, label_2cc);
    bitGet(var_0, MBIT_SH_HH);
    bne(var_0, 0, label_24a);
    b(label_24e);
  label_24a:
    bne(var_0, 1, label_24e);
    bitClear(MBIT_YOJIN_JOHO);
    b(label_2cc);
    b(label_24e);
  label_24e:
    bitGet(var_0, MBIT_SH_S_01);
    bez(var_0, label_254);
    bitGet(var_0, MBIT_SH_H_01);
    bnz(var_0, label_254);
    bitSet(LBIT_0005);
    b(label_2fc);
  label_254:
    bitGet(var_0, MBIT_SH_S_02);
    bez(var_0, label_25a);
    bitGet(var_0, MBIT_SH_H_02);
    bnz(var_0, label_25a);
    bitSet(LBIT_0005);
    b(label_2fc);
  label_25a:
    bitGet(var_0, MBIT_SH_S_03);
    bez(var_0, label_260);
    bitGet(var_0, MBIT_SH_H_03);
    bnz(var_0, label_260);
    bitSet(LBIT_0005);
    b(label_2fc);
  label_260:
    bitGet(var_0, MBIT_SH_S_04);
    bez(var_0, label_266);
    bitGet(var_0, MBIT_SH_H_04);
    bnz(var_0, label_266);
    bitSet(LBIT_0007);
    b(label_2fc);
  label_266:
    bitGet(var_0, MBIT_SH_S_05);
    bez(var_0, label_26c);
    bitGet(var_0, MBIT_SH_H_05);
    bnz(var_0, label_26c);
    bitSet(LBIT_0005);
    b(label_2fc);
  label_26c:
    bitGet(var_0, MBIT_SH_S_06);
    bez(var_0, label_272);
    bitGet(var_0, MBIT_SH_H_06);
    bnz(var_0, label_272);
    bitSet(LBIT_0006);
    b(label_2fc);
  label_272:
    bitGet(var_0, MBIT_SH_S_07);
    bez(var_0, label_278);
    bitGet(var_0, MBIT_SH_H_07);
    bnz(var_0, label_278);
    bitSet(LBIT_0006);
    b(label_2fc);
  label_278:
    bitGet(var_0, MBIT_SH_S_08);
    bez(var_0, label_27e);
    bitGet(var_0, MBIT_SH_H_08);
    bnz(var_0, label_27e);
    bitSet(LBIT_0006);
    b(label_2fc);
  label_27e:
    bitGet(var_0, MBIT_SH_S_09);
    bez(var_0, label_284);
    bitGet(var_0, MBIT_SH_H_09);
    bnz(var_0, label_284);
    bitSet(LBIT_0008);
    b(label_2fc);
  label_284:
    bitGet(var_0, MBIT_SH_S_10);
    bez(var_0, label_28a);
    bitGet(var_0, MBIT_SH_H_10);
    bnz(var_0, label_28a);
    bitSet(LBIT_0006);
    b(label_2fc);
  label_28a:
    bitGet(var_0, MBIT_SH_S_11);
    bez(var_0, label_290);
    bitGet(var_0, MBIT_SH_H_11);
    bnz(var_0, label_290);
    bitSet(LBIT_0007);
    b(label_2fc);
  label_290:
    bitGet(var_0, MBIT_SH_S_12);
    bez(var_0, label_296);
    bitGet(var_0, MBIT_SH_H_12);
    bnz(var_0, label_296);
    bitSet(LBIT_0007);
    b(label_2fc);
  label_296:
    bitGet(var_0, MBIT_SH_S_13);
    bez(var_0, label_29c);
    bitGet(var_0, MBIT_SH_H_13);
    bnz(var_0, label_29c);
    bitSet(LBIT_0008);
    b(label_2fc);
  label_29c:
    bitGet(var_0, MBIT_SH_S_14);
    bez(var_0, label_2a2);
    bitGet(var_0, MBIT_SH_H_14);
    bnz(var_0, label_2a2);
    bitSet(LBIT_0008);
    b(label_2fc);
  label_2a2:
    bitGet(var_0, MBIT_SH_S_15);
    bez(var_0, label_2a8);
    bitGet(var_0, MBIT_SH_H_15);
    bnz(var_0, label_2a8);
    bitSet(LBIT_0007);
    b(label_2fc);
  label_2a8:
    bitGet(var_0, MBIT_SH_S_16);
    bez(var_0, label_2ae);
    bitGet(var_0, MBIT_SH_H_16);
    bnz(var_0, label_2ae);
    bitSet(LBIT_0008);
    b(label_2fc);
  label_2ae:
    bitGet(var_0, MBIT_SH_S_17);
    bez(var_0, label_2b4);
    bitGet(var_0, MBIT_SH_H_17);
    bnz(var_0, label_2b4);
    bitSet(LBIT_0009);
    b(label_2fc);
  label_2b4:
    bitGet(var_0, MBIT_SH_S_18);
    bez(var_0, label_2ba);
    bitGet(var_0, MBIT_SH_H_18);
    bnz(var_0, label_2ba);
    bitSet(LBIT_0009);
    b(label_2fc);
  label_2ba:
    bitGet(var_0, MBIT_SH_S_19);
    bez(var_0, label_2c0);
    bitGet(var_0, MBIT_SH_H_19);
    bnz(var_0, label_2c0);
    bitSet(LBIT_0009);
    b(label_2fc);
  label_2c0:
    bitGet(var_0, MBIT_SH_S_20);
    bez(var_0, label_2c6);
    bitGet(var_0, MBIT_SH_H_20);
    bnz(var_0, label_2c6);
    bitSet(LBIT_0009);
    b(label_2fc);
  label_2c6:
    bitGet(var_0, MBIT_SH_S_21);
    bez(var_0, label_2cc);
    bitGet(var_0, MBIT_SH_H_21);
    bnz(var_0, label_2cc);
    bitSet(LBIT_0013);
    b(label_2fc);
  label_2cc:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_2f3);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_2ea);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bnz(var_0, label_2de);
    unitFacePlayer(npc2);
    ref_2d3 = dialogAlloc();
    ref_2d4 = msgShow(msg_28);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]あのオバチャンがマンサーチャーだって？
[tab]アッハッハッハッ。
[tab]それじゃ俺ぁここの用心棒にでもなるか。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_2d4);
    ref_2d7 = msgShow(msg_29);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]そう、俺ぁここの用心棒様よ！
[tab]秘密だぜ？[tab]姉ちゃん。
[tab]…アッハッハッハッ！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_2d7);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2d3);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_2de:
    unitFacePlayer(npc2);
    ref_2df = dialogAlloc();
    ref_2e0 = msgShow(msg_30);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]言ってなかったか？
[tab]あのオバチャンがマンサーチャーだって。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_2e0);
    ref_2e3 = msgShow(msg_31);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]そして、俺ぁここの用心棒様よ！
[tab]わかったかい？[tab]姉ちゃん。
[tab]…アッハッハッハッ！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_2e3);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2df);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_2ea:
    unitFacePlayer(npc2);
    ref_2eb = dialogAlloc();
    ref_2ec = msgShow(msg_32);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]ＪＯＫＥＲ呪いって何なんだよ？
[tab]何を大騒ぎしているのか俺にはよくわからん。
[tab]…わからないもの程、怖いんだけどな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_2ec);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2eb);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_2f3:
    unitFacePlayer(npc2);
    ref_2f4 = dialogAlloc();
    ref_2f5 = msgShow(msg_33);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]しかし珠閒瑠市は事件の多い所だよな。
[tab]この間の連続テロ。あれもひどかったよなぁ。
[tab]…ん？[tab]知らない？[tab]おいおい大事件だったろ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_19, 1);
    wait(ref_2f5);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2f4);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_2fc:
    unitFacePlayer(npc2);
    bitGet(var_0, MBIT_YOJIN_JOHO);
    bne(var_0, 0, label_300);
    b(label_30a);
  label_300:
    bne(var_0, 1, label_30a);
    ref_301 = dialogAlloc();
    ref_302 = msgShow(msg_34);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]なんだよ！[tab]俺のとっておきの情報、
[tab]忘れちまったのかい？
[tab]…ったく、しょうがねぇなぁ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_302);
    dialogFree(ref_301);
    delayClear();
    delayWait(30);
    b(label_3be);
    b(label_30a);
  label_30a:
    ref_30a = dialogAlloc();
    bitGet(var_0, MBIT_YOUJIN_HATU);
    bne(var_0, 0, label_316);
    bitSet(MBIT_YOUJIN_HATU);
    ref_30e = msgShow(msg_35);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]姉ちゃんも人捜しかい？
[tab]実はよぉ、俺もオバチャンの人捜しを
[tab]手伝ってんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_30e);
    ref_311 = msgShow(msg_36);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]用心棒兼、ビジネスパートナーって訳だ。
[tab]…なんか違う気もするけどよぉ。
[tab]ところで、誰か探してるんかい？
[wait][clear]
***************************************/
    wait(ref_311);
    ref_313 = msgShow(msg_37);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]人捜しで困ってるんならよぉ、
[tab]俺の特選イチオシ生情報、分けてやってもいいぜ？
[tab]そうだな…報酬額の２割程でどうだ？
[wait][clear]
***************************************/
    wait(ref_313);
    b(label_31b);
  label_316:
    bne(var_0, 1, label_31b);
    ref_317 = msgShow(msg_38);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]人捜し、困った時はお互い様ってことで、
[tab]俺の特選イチオシ生情報、分けてやってもいいぜ？
[tab]そうだな…報酬額の２割程でどうだ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_317);
    b(label_31b);
  label_31b:
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_30a);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_343);
    bitGet(var_0, LBIT_0006);
    bne(var_0, 0, label_33e);
    bitGet(var_0, LBIT_0007);
    bne(var_0, 0, label_339);
    bitGet(var_0, LBIT_0008);
    bne(var_0, 0, label_334);
    bitGet(var_0, LBIT_0009);
    bne(var_0, 0, label_32f);
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_32a);
    b(label_32e);
  label_32a:
    bne(var_0, 1, label_32e);
    li(var_5, 100);
    msgVar_Number(msgvar_0, var_5);
    b(label_32e);
  label_32e:
    b(label_333);
  label_32f:
    bne(var_0, 1, label_333);
    li(var_5, 10000);
    msgVar_Number(msgvar_0, var_5);
    b(label_333);
  label_333:
    b(label_338);
  label_334:
    bne(var_0, 1, label_338);
    li(var_5, 8000);
    msgVar_Number(msgvar_0, var_5);
    b(label_338);
  label_338:
    b(label_33d);
  label_339:
    bne(var_0, 1, label_33d);
    li(var_5, 6000);
    msgVar_Number(msgvar_0, var_5);
    b(label_33d);
  label_33d:
    b(label_342);
  label_33e:
    bne(var_0, 1, label_342);
    li(var_5, 4000);
    msgVar_Number(msgvar_0, var_5);
    b(label_342);
  label_342:
    b(label_347);
  label_343:
    bne(var_0, 1, label_347);
    li(var_5, 2000);
    msgVar_Number(msgvar_0, var_5);
    b(label_347);
  label_347:
    choiceSetResult(1);
    ref_348 = bustupLoad(bustup_1);
    bustupWait(ref_348);
    ref_34a = bustupAlloc(ref_348, center, rgb(0,0,0));
    bustupFade(ref_34a, rgb(128,0,0), 30);
    ref_34c = dialogChoiceAlloc();
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_34f = msgShow(msg_39);
/***************************************
[tab]俺の情報、[var(msg_var_0)]円で買うかい？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_34f);
    dialogFree(ref_34c);
    ref_352 = bustupFade(ref_34a, rgb(0,0,0), 10);
    bustupWait(ref_352);
    bustupFree(ref_34a);
    choiceGetResult(var_0);
    bne(var_0, 0, label_359);
    b(label_360);
    b(label_360);
  label_359:
    bne(var_0, 1, label_360);
    shopCurrencyDisplay(-110, 150, true);
    delayClear();
    delayWait(60);
    bitSet(LBIT_0004);
    b(label_475);
    b(label_360);
  label_360:
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_363);
    b(label_36f);
  label_363:
    bne(var_0, 1, label_36f);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 1999, label_368);
    b(label_46a);
    b(label_36e);
  label_368:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(-2000);
    b(label_3ba);
    b(label_36e);
  label_36e:
    b(label_36f);
  label_36f:
    bitGet(var_0, LBIT_0006);
    bne(var_0, 0, label_372);
    b(label_37e);
  label_372:
    bne(var_0, 1, label_37e);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 3999, label_377);
    b(label_46a);
    b(label_37d);
  label_377:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(-4000);
    b(label_3ba);
    b(label_37d);
  label_37d:
    b(label_37e);
  label_37e:
    bitGet(var_0, LBIT_0007);
    bne(var_0, 0, label_381);
    b(label_38d);
  label_381:
    bne(var_0, 1, label_38d);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 5999, label_386);
    b(label_46a);
    b(label_38c);
  label_386:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(-6000);
    b(label_3ba);
    b(label_38c);
  label_38c:
    b(label_38d);
  label_38d:
    bitGet(var_0, LBIT_0008);
    bne(var_0, 0, label_390);
    b(label_39c);
  label_390:
    bne(var_0, 1, label_39c);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 7999, label_395);
    b(label_46a);
    b(label_39b);
  label_395:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(-8000);
    b(label_3ba);
    b(label_39b);
  label_39b:
    b(label_39c);
  label_39c:
    bitGet(var_0, LBIT_0009);
    bne(var_0, 0, label_39f);
    b(label_3ab);
  label_39f:
    bne(var_0, 1, label_3ab);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 9999, label_3a4);
    b(label_46a);
    b(label_3aa);
  label_3a4:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(-10000);
    b(label_3ba);
    b(label_3aa);
  label_3aa:
    b(label_3ab);
  label_3ab:
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_3ae);
    b(label_3ba);
  label_3ae:
    bne(var_0, 1, label_3ba);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 99, label_3b3);
    b(label_46a);
    b(label_3b9);
  label_3b3:
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(-100);
    b(label_3ba);
    b(label_3b9);
  label_3b9:
    b(label_3ba);
  label_3ba:
    delayClear();
    delayWait(30);
    shopCurrencyDisplay(-110, 150, true);
    bitSet(MBIT_YOJIN_JOHO);
  label_3be:
    delayClear();
    delayWait(30);
    ref_3c0 = dialogAlloc();
    ref_3c1 = msgShow(msg_40);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]よし、それじゃあ教えるぜ。
[tab]え～と捜してんのは…
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_3c1);
    bitGet(var_0, MBIT_SH_S_01);
    bez(var_0, label_3c7);
    bnz(var_0, label_403);
  label_3c7:
    bitGet(var_0, MBIT_SH_S_02);
    bez(var_0, label_3ca);
    bnz(var_0, label_407);
  label_3ca:
    bitGet(var_0, MBIT_SH_S_03);
    bez(var_0, label_3cd);
    bnz(var_0, label_40b);
  label_3cd:
    bitGet(var_0, MBIT_SH_S_04);
    bez(var_0, label_3d0);
    bnz(var_0, label_40f);
  label_3d0:
    bitGet(var_0, MBIT_SH_S_05);
    bez(var_0, label_3d3);
    bnz(var_0, label_413);
  label_3d3:
    bitGet(var_0, MBIT_SH_S_06);
    bez(var_0, label_3d6);
    bnz(var_0, label_417);
  label_3d6:
    bitGet(var_0, MBIT_SH_S_07);
    bez(var_0, label_3d9);
    bnz(var_0, label_41b);
  label_3d9:
    bitGet(var_0, MBIT_SH_S_08);
    bez(var_0, label_3dc);
    bnz(var_0, label_41f);
  label_3dc:
    bitGet(var_0, MBIT_SH_S_09);
    bez(var_0, label_3df);
    bnz(var_0, label_423);
  label_3df:
    bitGet(var_0, MBIT_SH_S_10);
    bez(var_0, label_3e2);
    bnz(var_0, label_427);
  label_3e2:
    bitGet(var_0, MBIT_SH_S_11);
    bez(var_0, label_3e5);
    bnz(var_0, label_42b);
  label_3e5:
    bitGet(var_0, MBIT_SH_S_12);
    bez(var_0, label_3e8);
    bnz(var_0, label_42f);
  label_3e8:
    bitGet(var_0, MBIT_SH_S_13);
    bez(var_0, label_3eb);
    bnz(var_0, label_433);
  label_3eb:
    bitGet(var_0, MBIT_SH_S_14);
    bez(var_0, label_3ee);
    bnz(var_0, label_437);
  label_3ee:
    bitGet(var_0, MBIT_SH_S_15);
    bez(var_0, label_3f1);
    bnz(var_0, label_43b);
  label_3f1:
    bitGet(var_0, MBIT_SH_S_16);
    bez(var_0, label_3f4);
    bnz(var_0, label_43f);
  label_3f4:
    bitGet(var_0, MBIT_SH_S_17);
    bez(var_0, label_3f7);
    bnz(var_0, label_443);
  label_3f7:
    bitGet(var_0, MBIT_SH_S_18);
    bez(var_0, label_3fa);
    bnz(var_0, label_447);
  label_3fa:
    bitGet(var_0, MBIT_SH_S_19);
    bez(var_0, label_3fd);
    bnz(var_0, label_44b);
  label_3fd:
    bitGet(var_0, MBIT_SH_S_20);
    bez(var_0, label_400);
    bnz(var_0, label_44f);
  label_400:
    bitGet(var_0, MBIT_SH_S_21);
    bez(var_0, label_47d);
    bnz(var_0, label_453);
  label_403:
    ref_403 = msgShow(msg_41);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]ホンダリョウイチだな？
[tab]こいつは最近、アンティークにハマってたらしい。
[tab]そういったものを扱ってる店にいるかもな？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_403);
    b(label_466);
  label_407:
    ref_407 = msgShow(msg_42);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]タナカオサミツか…
[tab]一流ジャーナリストになるのが夢だったようだ。
[tab]…関連施設をあたってみるのはどうだ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_407);
    b(label_466);
  label_40b:
    ref_40b = msgShow(msg_43);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]ムラタタクヤねぇ。目撃情報が少ないんだよ。
[tab]たまに帰ってくると香水のような良い香りがする
[tab]らしいから、それを手がかりとしたらどうだ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_40b);
    b(label_466);
  label_40f:
    ref_40f = msgShow(msg_44);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]お、ナガセタイチね。
[tab]少し前の事でもすぐ忘れ、意味不明な事を口走る
[tab]って話だが、歳が歳だからね。仕方ないよな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_40f);
    b(label_466);
  label_413:
    ref_413 = msgShow(msg_45);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]サツマゴンゾウ…す、すごい名前だね。
[tab]本人はギャンブラーを気取ってるようだな。
[tab]ここらへんで賭け事ができる場所といえば…
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_413);
    b(label_466);
  label_417:
    ref_417 = msgShow(msg_46);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]スズキユウイチ…くせ者だぜ。
[tab]友人達に自分は貴族だと触れ回っていたらしい。
[tab]…貴族って愛称みたいなもんかもな？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_417);
    b(label_466);
  label_41b:
    ref_41b = msgShow(msg_47);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]イケナカユウタ…
[tab]最近は、占いが趣味だったようだな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_41b);
    b(label_466);
  label_41f:
    ref_41f = msgShow(msg_48);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]あぁ、ハンフリーって愛称のヤツね。
[tab]ハードボイルドを気取り、「自分には関係無い」
[tab]とか言っているそうだ。…カッコいいねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_41f);
    b(label_466);
  label_423:
    ref_423 = msgShow(msg_49);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]シミズショウイチとタナカシズエかぁ。
[tab]お互いをニックネームで呼び合っているらしいな。
[tab]女の子の方は大人しくて内向的な性格のようだ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_423);
    b(label_466);
  label_427:
    ref_427 = msgShow(msg_50);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]キムラヤヨイさんって、ワンロン占いと貴金属が
[tab]大好きらしいな。なんだ、ただのオバサンだな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_427);
    b(label_466);
  label_42b:
    ref_42b = msgShow(msg_51);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]え～っと、ヨコヤマケイコちゃんね。
[tab]どうやらこの子のいう宿題というのは観察日誌
[tab]らしいな。何を観察するのかはしらんがね。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_42b);
    b(label_466);
  label_42f:
    ref_42f = msgShow(msg_52);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]あ～クドウサオリさんね。立ち仕事には慣れてる
[tab]って言ってたらしいぜ。芸能人に度々誘われた事が
[tab]あるってのが自慢のようだな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_42f);
    b(label_466);
  label_433:
    ref_433 = msgShow(msg_53);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]はいはい、イイダサトミさんね。
[tab]最近はワンロン占いにはまっていたらしいな。
[tab]かなり詳しかったようだね。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_433);
    b(label_466);
  label_437:
    ref_437 = msgShow(msg_54);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]キノシタジュンジ…依頼主は責任感の強い子だって
[tab]言ってるようだけど、まだ高校生だぞ？
[tab]家にも帰らず、学校に居続ける理由って何だ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_437);
    b(label_466);
  label_43b:
    ref_43b = msgShow(msg_55);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]あー、ネコマタかぁ！！[tab]本当にこんなヤツが
[tab]いるのか謎だぜ。何しろ目撃者がほとんどいない。
[tab]手がかりは…やっぱネコに関係するのか？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_43b);
    b(label_466);
  label_43f:
    ref_43f = msgShow(msg_56);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]ニシタニセツさんかぁ…
[tab]依頼人は二児の母だったって言うからね。
[tab]その母親だから…結構な歳だろうな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_43f);
    b(label_466);
  label_443:
    ref_443 = msgShow(msg_57);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]ナカタニケンイチってのは流行りモノ好きらしい。
[tab]人気のスポットは常にチェック。業界人を気取って
[tab]いるが、誰にも信用されてないんだとさ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_443);
    b(label_466);
  label_447:
    ref_447 = msgShow(msg_58);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]サイトウジュン…う～む。よく記憶を消したいとか
[tab]言ってたそうだ。精神的にまいっていたようだから
[tab]どこかその手の病院にでも行ってるのかも？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_447);
    b(label_466);
  label_44b:
    ref_44b = msgShow(msg_59);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]おーおー、マツシタヒロミさんね。依頼者の言った
[tab]「男と話すのが怖いなら男になっちゃえば？」って
[tab]言葉を真に受けちゃったらしいが…
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_44b);
    b(label_466);
  label_44f:
    ref_44f = msgShow(msg_60);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]イケダジュンコさんか…彼女の意中の相手は、
[tab]女ったらしで有名らしいな。本人も表向きは店主の
[tab]女好きを批難してるらしいぞ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_44f);
    b(label_466);
  label_453:
    ref_453 = msgShow(msg_61);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]あぁ、アサノタクミさんね。
[tab]これって子供からの依頼だろ？
[tab]真に受けちゃダメだって。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_453);
    ref_456 = msgShow(msg_62);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]伝説の武器職人…だっけ？
[tab]そんな職人がこの国にいるワケねぇって。
[tab]…それでも情報が欲しい？[tab]しょうがねぇなぁ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_456);
    bitGet(var_0, MBIT_KI_DENNSETU);
    bne(var_0, 0, label_45f);
    ref_45b = msgShow(msg_63);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab][color(orange)]アラヤ神社[color(white)]で物思いにふけっている男性が、
[tab]もとは[color(orange)]武器職人[color(white)]だった…って噂があったな。
[tab]自宅が仕事場って話だが…あくまで噂だぞ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_45b);
    b(label_464);
  label_45f:
    bne(var_0, 1, label_464);
    ref_460 = msgShow(msg_64);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]アラヤ神社で物思いにふけっている男性が、
[tab]もとは武器職人だった…って噂があったな。
[tab]自宅が仕事場って話だが…あくまで噂だぞ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_460);
    b(label_464);
  label_464:
    bitSet(MBIT_KI_DENNSETU);
    b(label_466);
  label_466:
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_3c0);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_46a:
    ref_46a = dialogAlloc();
    ref_46b = msgShow(msg_65);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]残念だなぁ姉ちゃん。
[tab]手持ちが足りないようだぜ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_46b);
    shopCurrencyDisplay(-110, 150, true);
    dialogFree(ref_46a);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc2, animation_0, 1);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_475:
    ref_475 = dialogAlloc();
    ref_476 = msgShow(msg_66);
/***************************************
[color(yellow)]用心棒のおっちゃん[color(white)]
[tab]用があったらまた声をかけてくれ。
[tab]じゃあな、姉ちゃん。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_476);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_475);
    unitRestoreFacing(npc2);
    b(label_47d);
  label_47d:
    controlEnable();
}

function MAN3()
{
    controlDisable();
    li(var_5, 0);
    li(var_6, 0);
    li(var_7, 0);
    li(var_8, 0);
    li(var_9, 0);
    li(var_a, 0);
    li(var_b, 0);
    playerConvertToUnit(maya, sprite_0, north);
    playerHide();
    unitFaceUnit(maya, npc3);
    bitGet(var_0, MBIT_SIRA_TOKUSAN);
    bne(var_0, 0, label_48f);
    bitSet(MBIT_SIRA_TOKUSAN);
    b(label_492);
    b(label_492);
  label_48f:
    bne(var_0, 1, label_492);
    b(label_4d4);
    b(label_492);
  label_492:
    unitFacePlayer(npc3);
    bitGet(var_0, EBIT_E0038);
    bne(var_0, 0, label_4bd);
    ref_495 = bustupLoad(bustup_e8);
    bustupWait(ref_495);
    ref_497 = bustupAlloc(ref_495, right, rgb(0,0,0));
    bustupFade(ref_497, rgb(128,0,0), 30);
    ref_499 = dialogAlloc();
    ref_49a = msgShow(msg_67);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]ん？
[tab]君みたいな若者が、
[tab]こんなホームレスの親父になんの用かな？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_49a);
    unitAnimationPlay(npc3, animation_0, 1);
    ref_49e = msgShow(msg_68);
/***************************************
[color(yellow)]トクさん[color(green)]
[tab]赤提灯しらいしに入り浸る自由人。
[tab]噂に詳しく、世間を蚊帳の外から傍観して、
[tab]何やら哲学している様子。実はインテリらしい。[color(white)]
[wait][clear]
***************************************/
    wait(ref_49e);
    unitAnimationPlay(npc3, animation_0, 1);
    ref_4a1 = msgShow(msg_69);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]…何？[tab]ここのおばちゃんがマンサーチャー？
[tab]その噂は知ってるけど…それねぇ、多分嘘だよ。
[tab]おばちゃんの嘘を信じた人がいたんだねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_4a1);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_499);
    ref_4a6 = bustupFade(ref_497, rgb(0,0,0), 10);
    bustupWait(ref_4a6);
    bustupFree(ref_497);
    delayClear();
    delayWait(45);
    ref_4ab = bustupLoad(bustup_e8);
    bustupWait(ref_4ab);
    ref_4ad = bustupAlloc(ref_4ab, right, rgb(0,0,0));
    bustupFade(ref_4ad, rgb(128,0,0), 30);
    ref_4af = dialogAlloc();
    ref_4b0 = msgShow(msg_70);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]そんな噂を信じてここに来るなんて…
[tab]君も噂話が好きなのかい？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_4b0);
    unitAnimationPlay(npc3, animation_0, 1);
    ref_4b4 = msgShow(msg_71);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]僕は今、社会の呟きってやつに耳を傾けてるのさ。
[tab]面白い噂を知ってたら教えてくれないかな？
[tab]代わりに僕が知ってる噂を教えてあげよう。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_4b4);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_4af);
    ref_4b9 = bustupFade(ref_4ad, rgb(0,0,0), 10);
    bustupWait(ref_4b9);
    bustupFree(ref_4ad);
    b(label_4d3);
  label_4bd:
    bne(var_0, 1, label_4d3);
    ref_4be = bustupLoad(bustup_e8);
    bustupWait(ref_4be);
    ref_4c0 = bustupAlloc(ref_4be, right, rgb(0,0,0));
    bustupFade(ref_4c0, rgb(128,0,0), 30);
    ref_4c2 = dialogAlloc();
    ref_4c3 = msgShow(msg_72);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]ん？
[tab]君みたいな若者が、
[tab]こんなホームレスの親父になんの用かな？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_4c3);
    unitAnimationPlay(npc3, animation_0, 1);
    ref_4c7 = msgShow(msg_73);
/***************************************
[color(yellow)]噂屋トクさん[color(green)]
[tab]赤提灯しらいしに入り浸る自由人。
[tab]噂に詳しく、世間を蚊帳の外から傍観して、
[tab]何やら哲学している様子。実はインテリらしい。[color(white)]
[wait][clear]
***************************************/
    wait(ref_4c7);
    unitAnimationPlay(npc3, animation_0, 1);
    ref_4ca = msgShow(msg_74);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]僕は今、社会の呟きってやつに耳を傾けてるのさ。
[tab]面白い噂を知ってたら教えてくれないかな？
[tab]代わりに僕が知ってる噂を教えてあげよう。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_4ca);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_4c2);
    ref_4cf = bustupFade(ref_4c0, rgb(0,0,0), 10);
    bustupWait(ref_4cf);
    bustupFree(ref_4c0);
    b(label_4d3);
  label_4d3:
    b(label_4e3);
  label_4d4:
    unitFacePlayer(npc3);
    ref_4d5 = bustupLoad(bustup_e8);
    bustupWait(ref_4d5);
    ref_4d7 = bustupAlloc(ref_4d5, right, rgb(0,0,0));
    bustupFade(ref_4d7, rgb(128,0,0), 30);
    ref_4d9 = dialogAlloc();
    ref_4da = msgShow(msg_75);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]やあ、キミか。[delay(10)]
[tab]こんにちは。[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_4da);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_4d9);
    ref_4df = bustupFade(ref_4d7, rgb(0,0,0), 10);
    bustupWait(ref_4df);
    bustupFree(ref_4d7);
    b(label_4e3);
  label_4e3:
    choiceSetResult(2);
    ref_4e4 = bustupLoad(bustup_1);
    bustupWait(ref_4e4);
    ref_4e6 = bustupAlloc(ref_4e4, center, rgb(0,0,0));
    bustupFade(ref_4e6, rgb(128,0,0), 30);
    ref_4e8 = dialogChoiceAlloc();
    ref_4e9 = msgShow(msg_76);
/***************************************
[tab]今日はどんな用かな？
[choice(3)]噂話を聞きたい
話を聞きたい
用はない
[end_choice][clear]
***************************************/
    wait(ref_4e9);
    dialogFree(ref_4e8);
    ref_4ec = bustupFade(ref_4e6, rgb(0,0,0), 10);
    bustupWait(ref_4ec);
    bustupFree(ref_4e6);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4f3);
    b(label_4f9);
    b(label_4f9);
  label_4f3:
    bne(var_0, 1, label_4f6);
    b(label_5df);
    b(label_4f9);
  label_4f6:
    bne(var_0, 2, label_4f9);
    b(label_612);
    b(label_4f9);
  label_4f9:
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_4fc);
    b(label_504);
  label_4fc:
    bne(var_0, 1, label_504);
    bitGet(var_0, MBIT_KE_CLEAOBA);
    bne(var_0, 0, label_501);
    b(label_50f);
    b(label_503);
  label_501:
    bne(var_0, 1, label_503);
    b(label_503);
  label_503:
    b(label_504);
  label_504:
    bitGet(var_0, EBIT_E0046);
    bez(var_0, label_50f);
    bitGet(var_0, MBIT_KE_CLE);
    bitGet(var_1, MBIT_KI_CLEDEF);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_50d);
    li(var_5, 1);
    b(label_567);
    b(label_50f);
  label_50d:
    boutrange(var_1, 1, 2, label_50f);
    b(label_50f);
  label_50f:
    bitGet(var_0, EBIT_E0045);
    bez(var_0, label_51f);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_514);
    b(label_51f);
  label_514:
    bne(var_0, 1, label_51f);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bitGet(var_1, MBIT_KI_SIRAHENNI);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_51c);
    li(var_6, 1);
    b(label_567);
    b(label_51e);
  label_51c:
    boutrange(var_1, 1, 2, label_51e);
    b(label_51e);
  label_51e:
    b(label_51f);
  label_51f:
    bitGet(var_0, EBIT_E0043);
    bez(var_0, label_52e);
    bitGet(var_0, MBIT_HBATOLUBOUGU);
    bnz(var_0, label_52e);
    bitGet(var_0, MBIT_DMAGICK);
    bez(var_0, label_52e);
    bitGet(var_0, MBIT_DPELPEL);
    bitGet(var_1, MBIT_KI_PELPELBOUGU);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_52c);
    li(var_7, 1);
    b(label_567);
    b(label_52e);
  label_52c:
    boutrange(var_1, 1, 2, label_52e);
    b(label_52e);
  label_52e:
    bitGet(var_0, EBIT_E0038);
    bez(var_0, label_550);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bitGet(var_1, MBIT_KI_SIRAMAN);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_537);
    li(var_8, 1);
    b(label_567);
    b(label_539);
  label_537:
    boutrange(var_1, 1, 2, label_539);
    b(label_539);
  label_539:
    bitGet(var_0, MBIT_DBATOLU);
    bne(var_0, 0, label_53c);
    b(label_547);
  label_53c:
    bne(var_0, 1, label_547);
    bitGet(var_0, MBIT_DMAGICK);
    bitGet(var_1, MBIT_KI_MAGICKITEM);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_544);
    li(var_9, 1);
    b(label_567);
    b(label_546);
  label_544:
    boutrange(var_1, 1, 2, label_546);
    b(label_546);
  label_546:
    b(label_547);
  label_547:
    bitGet(var_0, MBIT_KE_MU);
    bitGet(var_1, MBIT_KI_MUPOKER);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_54e);
    li(var_a, 1);
    b(label_567);
    b(label_550);
  label_54e:
    boutrange(var_1, 1, 2, label_550);
    b(label_550);
  label_550:
    bitGet(var_0, MBIT_KE_TOA);
    bitGet(var_1, MBIT_KI_TOAARM);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_557);
    li(var_b, 1);
    b(label_567);
    b(label_559);
  label_557:
    boutrange(var_1, 1, 2, label_559);
    b(label_559);
  label_559:
    ref_559 = bustupLoad(bustup_e8);
    bustupWait(ref_559);
    ref_55b = bustupAlloc(ref_559, right, rgb(0,0,0));
    bustupFade(ref_55b, rgb(128,0,0), 30);
    ref_55d = dialogAlloc();
    ref_55e = msgShow(msg_77);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]今のところ、僕の知っている噂はこれで全部だ。
[tab]新しいネタが入ったら、また教えてあげよう。
[tab]君も、面白い情報を用意しておいてくれよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_55e);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_55d);
    ref_563 = bustupFade(ref_55b, rgb(0,0,0), 10);
    bustupWait(ref_563);
    bustupFree(ref_55b);
    b(label_5de);
  label_567:
    ref_567 = bustupLoad(bustup_e8);
    bustupWait(ref_567);
    ref_569 = bustupAlloc(ref_567, right, rgb(0,0,0));
    bustupFade(ref_569, rgb(128,0,0), 30);
    ref_56b = dialogAlloc();
    unitAnimationPlay(npc3, animation_24, 1);
    rand(var_0, 2);
    bne(var_0, 0, label_572);
    ref_56f = msgShow(msg_78);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]噂話か…よし、いいだろう。
[tab]だがその前に…
[tab]君の知る噂を教えてもらおうかな。
[wait][clear]
***************************************/
    wait(ref_56f);
    b(label_579);
  label_572:
    bne(var_0, 1, label_576);
    ref_573 = msgShow(msg_79);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]噂屋の僕を納得させるには、
[tab]ありがちな噂じゃ無理だけど…大丈夫かい？
[tab]…では、君の噂を聞かせてもらおうか？
[wait][clear]
***************************************/
    wait(ref_573);
    b(label_579);
  label_576:
    ref_576 = msgShow(msg_80);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]最近、噂と言いつつ嘘をつく者が多くてね。
[tab]僕でも嘘と噂の判別は難しいものだよ。
[tab]…君の持って来た噂は、嘘じゃないよね？
[wait][clear]
***************************************/
    wait(ref_576);
    b(label_579);
  label_579:
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_56b);
    ref_57b = bustupFade(ref_569, rgb(0,0,0), 10);
    bustupWait(ref_57b);
    bustupFree(ref_569);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(maya, animation_2d, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc3, animation_6, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc3, animation_6, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc3, animation_0, 1);
    delayClear();
    delayWait(15);
    ref_593 = bustupLoad(bustup_e8);
    bustupWait(ref_593);
    ref_595 = bustupAlloc(ref_593, right, rgb(0,0,0));
    bustupFade(ref_595, rgb(128,0,0), 30);
    ref_597 = dialogAlloc();
    unitAnimationPlay(npc3, animation_24, 1);
    rand(var_0, 2);
    bne(var_0, 0, label_59e);
    ref_59b = msgShow(msg_81);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]ほう、なるほどねぇ。
[tab]じゃあ今度は僕のネタを教えよう。
[wait][clear]
***************************************/
    wait(ref_59b);
    b(label_5a5);
  label_59e:
    bne(var_0, 1, label_5a2);
    ref_59f = msgShow(msg_82);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]ふーむ、なかなか興味深い噂だな。
[tab]それでは僕のネタを話そうかな？
[wait][clear]
***************************************/
    wait(ref_59f);
    b(label_5a5);
  label_5a2:
    ref_5a2 = msgShow(msg_83);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]おっと、それは凄い情報だなぁ。
[tab]よし、こちらも負けてられんな。
[wait][clear]
***************************************/
    wait(ref_5a2);
    b(label_5a5);
  label_5a5:
    bnz(var_5, label_5c4);
    bnz(var_6, label_5ca);
    bnz(var_7, label_5be);
    bnz(var_8, label_5d0);
    bnz(var_9, label_5b8);
    bnz(var_a, label_5b2);
    bnz(var_b, label_5ac);
  label_5ac:
    ref_5ac = msgShow(msg_84);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]この平坂区にある[color(orange)]東亜ディフェンス[color(white)]って店だが、
[tab]どうも[color(orange)]特殊な武器を販売している[color(white)]らしいよ。
[tab]…はて、何がどう特殊なのかね？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5ac);
    bitSet(MBIT_KI_TOAARM);
    li(var_b, 0);
    b(label_5d9);
  label_5b2:
    ref_5b2 = msgShow(msg_85);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]夢崎区に[color(orange)]ムー大陸[color(white)]ってゲームセンターがあるだろ？
[tab]あそこ実は[color(orange)]カジノ[color(white)]らしいんだ。
[tab]特に[color(orange)]ポーカーが有利[color(white)]だって噂だよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5b2);
    bitSet(MBIT_KI_MUPOKER);
    li(var_a, 0);
    b(label_5d9);
  label_5b8:
    ref_5b8 = msgShow(msg_86);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab][color(orange)]別冊ミラクル[color(white)]って本があるんだが、
[tab]何とその本の懸賞に応募すると、[color(orange)]特殊なアイテム[color(white)]が
[tab]当たるらしいぞ。…ところで、何の別冊なんだ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5b8);
    bitSet(MBIT_KI_MAGICKITEM);
    li(var_9, 0);
    b(label_5d9);
  label_5be:
    ref_5be = msgShow(msg_87);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab][color(orange)]ファンタジーワールド[color(white)]という本の懸賞に応募すると
[tab][color(orange)]本物の防具[color(white)]が当たるという話だが、知ってたかい？
[tab]…どうにも恥ずかしい名前の本だね。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5be);
    bitSet(MBIT_KI_PELPELBOUGU);
    li(var_7, 0);
    b(label_5d9);
  label_5c4:
    ref_5c4 = msgShow(msg_88);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]地獄のギャルソンと呼ばれる副島さんの店、
[tab][color(orange)]クレール・ド・リュンヌ[color(white)]。あそこで[color(orange)]不思議な防具[color(white)]を
[tab]販売しているらしい。…不思議な防具って何？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5c4);
    bitSet(MBIT_KI_CLEDEF);
    li(var_5, 0);
    b(label_5d9);
  label_5ca:
    ref_5ca = msgShow(msg_89);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab][color(orange)]しらいし[color(white)]のおばちゃんが[color(orange)]夢を実現[color(white)]したらしいよ。
[tab]今の世の中、そうそう出来ることじゃないね。
[tab]…人を巻き込むのだけは、やめて欲しいけど。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5ca);
    bitSet(MBIT_KI_SIRAHENNI);
    li(var_6, 0);
    b(label_5d9);
  label_5d0:
    ref_5d0 = msgShow(msg_90);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]以前からあった噂だけど、
[tab][color(orange)]しらいし[color(white)]のおばちゃんは[color(orange)]マンサーチャー[color(white)]らしい。
[tab]今でも信じられないけど、本当の様だよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5d0);
    ref_5d3 = msgShow(msg_91);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]現に結婚詐欺探しの依頼を受け、
[tab]見事、それを見つけ出したらしいからね。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5d3);
    bitSet(MBIT_KI_SIRAMAN);
    li(var_8, 0);
    b(label_5d9);
  label_5d9:
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_597);
    ref_5db = bustupFade(ref_595, rgb(0,0,0), 10);
    bustupWait(ref_5db);
    bustupFree(ref_595);
  label_5de:
    b(label_4e3);
  label_5df:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_5ff);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_5f1);
    ref_5e3 = bustupLoad(bustup_e8);
    bustupWait(ref_5e3);
    ref_5e5 = bustupAlloc(ref_5e3, right, rgb(0,0,0));
    bustupFade(ref_5e5, rgb(128,0,0), 30);
    ref_5e7 = dialogAlloc();
    ref_5e8 = msgShow(msg_92);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]パラベラムってバー知ってるかい？
[tab]あの店、結構女の子に人気があるようだけど、
[tab]オリジナルカクテルの名前は評判悪いねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5e8);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_5e7);
    ref_5ed = bustupFade(ref_5e5, rgb(0,0,0), 10);
    bustupWait(ref_5ed);
    bustupFree(ref_5e5);
    b(label_611);
  label_5f1:
    ref_5f1 = bustupLoad(bustup_e8);
    bustupWait(ref_5f1);
    ref_5f3 = bustupAlloc(ref_5f1, right, rgb(0,0,0));
    bustupFade(ref_5f3, rgb(128,0,0), 30);
    ref_5f5 = dialogAlloc();
    ref_5f6 = msgShow(msg_93);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]どうも最近、イライラしてる人が多いねぇ。
[tab]噂では、ＪＯＫＥＲになる事を恐れた連中が
[tab]イライラしているらしいよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5f6);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_5f5);
    ref_5fb = bustupFade(ref_5f3, rgb(0,0,0), 10);
    bustupWait(ref_5fb);
    bustupFree(ref_5f3);
    b(label_611);
  label_5ff:
    ref_5ff = bustupLoad(bustup_e8);
    bustupWait(ref_5ff);
    ref_601 = bustupAlloc(ref_5ff, right, rgb(0,0,0));
    bustupFade(ref_601, rgb(128,0,0), 30);
    ref_603 = dialogAlloc();
    ref_604 = msgShow(msg_94);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]ここのおばちゃん、前はラーメン屋だったんだよ。
[tab]でも、急に客の入りが悪くなっちゃってね。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_604);
    ref_607 = msgShow(msg_95);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]その後、店に居眠り運転のトラックが突っ込んで
[tab]来たって言ってたなぁ。
[tab]もうついてないとしか言いようがないよね。
[wait][clear]
***************************************/
    wait(ref_607);
    ref_609 = msgShow(msg_96);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]そんな訳でラーメン屋は閉めちゃったんだよ。
[tab]…君達も知らなかっただろう？
[wait][clear]
***************************************/
    wait(ref_609);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_603);
    ref_60d = bustupFade(ref_601, rgb(0,0,0), 10);
    bustupWait(ref_60d);
    bustupFree(ref_601);
    b(label_611);
  label_611:
    b(label_4e3);
  label_612:
    ref_612 = bustupLoad(bustup_e8);
    bustupWait(ref_612);
    ref_614 = bustupAlloc(ref_612, right, rgb(0,0,0));
    bustupFade(ref_614, rgb(128,0,0), 30);
    ref_616 = dialogAlloc();
    ref_617 = msgShow(msg_97);
/***************************************
[color(yellow)]噂屋トクさん[color(white)]
[tab]そうか。
[tab]また噂が聞きたくなったら来るといい。
[tab]僕はいつも、ここにいるからね。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_617);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_616);
    ref_61c = bustupFade(ref_614, rgb(0,0,0), 10);
    bustupWait(ref_61c);
    bustupFree(ref_614);
    unitRestoreFacing(npc3);
    unitDespawn(maya, none);
    playerInit(south);
    controlEnable();
}

function SHOP()
{
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    bitClear(LBIT_0007);
    bitClear(LBIT_0008);
    bitClear(LBIT_0009);
    controlDisable();
    unitFacePlayer(shopkeeper);
    ref_62b = shopOverlayInit();
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bez(var_0, label_71b);
    bitGet(var_0, MBIT_SH_HH);
    bez(var_0, label_71b);
    ref_630 = bustupLoad(bustup_ec);
    bustupWait(ref_630);
    ref_632 = bustupAlloc(ref_630, right, rgb(0,0,0));
    bustupFade(ref_632, rgb(128,0,0), 30);
    ref_634 = dialogAlloc();
    ref_635 = msgShow(msg_98);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]ちゃ～んと見付けたみたいだねェ～
[tab]さっき依頼人から連絡あったよォ～
[tab]はいコレ、報酬だよ。また頼むわねェ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_635);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_634);
    ref_63a = bustupFade(ref_632, rgb(0,0,0), 10);
    bustupWait(ref_63a);
    bustupFree(ref_632);
    bitClear(MBIT_SH_HH);
    bitClear(MBIT_YOJIN_JOHO);
    bitGet(var_0, MBIT_SH_S_01);
    bez(var_0, label_645);
    bitSet(LBIT_0005);
    bitSet(MBIT_SH_H_01);
    bitClear(MBIT_SH_S_01);
    bnz(var_0, label_6bd);
  label_645:
    bitGet(var_0, MBIT_SH_S_02);
    bez(var_0, label_64b);
    bitSet(LBIT_0005);
    bitSet(MBIT_SH_H_02);
    bitClear(MBIT_SH_S_02);
    bnz(var_0, label_6bd);
  label_64b:
    bitGet(var_0, MBIT_SH_S_03);
    bez(var_0, label_651);
    bitSet(LBIT_0005);
    bitSet(MBIT_SH_H_03);
    bitClear(MBIT_SH_S_03);
    bnz(var_0, label_6bd);
  label_651:
    bitGet(var_0, MBIT_SH_S_04);
    bez(var_0, label_657);
    bitSet(LBIT_0007);
    bitSet(MBIT_SH_H_04);
    bitClear(MBIT_SH_S_04);
    bnz(var_0, label_6bd);
  label_657:
    bitGet(var_0, MBIT_SH_S_05);
    bez(var_0, label_65d);
    bitSet(LBIT_0005);
    bitSet(MBIT_SH_H_05);
    bitClear(MBIT_SH_S_05);
    bnz(var_0, label_6bd);
  label_65d:
    bitGet(var_0, MBIT_SH_S_06);
    bez(var_0, label_663);
    bitSet(LBIT_0006);
    bitSet(MBIT_SH_H_06);
    bitClear(MBIT_SH_S_06);
    bnz(var_0, label_6bd);
  label_663:
    bitGet(var_0, MBIT_SH_S_07);
    bez(var_0, label_669);
    bitSet(LBIT_0006);
    bitSet(MBIT_SH_H_07);
    bitClear(MBIT_SH_S_07);
    bnz(var_0, label_6bd);
  label_669:
    bitGet(var_0, MBIT_SH_S_08);
    bez(var_0, label_66f);
    bitSet(LBIT_0006);
    bitSet(MBIT_SH_H_08);
    bitClear(MBIT_SH_S_08);
    bnz(var_0, label_6bd);
  label_66f:
    bitGet(var_0, MBIT_SH_S_09);
    bez(var_0, label_675);
    bitSet(LBIT_0008);
    bitSet(MBIT_SH_H_09);
    bitClear(MBIT_SH_S_09);
    bnz(var_0, label_6bd);
  label_675:
    bitGet(var_0, MBIT_SH_S_10);
    bez(var_0, label_67b);
    bitSet(LBIT_0006);
    bitSet(MBIT_SH_H_10);
    bitClear(MBIT_SH_S_10);
    bnz(var_0, label_6bd);
  label_67b:
    bitGet(var_0, MBIT_SH_S_11);
    bez(var_0, label_681);
    bitSet(LBIT_0007);
    bitSet(MBIT_SH_H_11);
    bitClear(MBIT_SH_S_11);
    bnz(var_0, label_6bd);
  label_681:
    bitGet(var_0, MBIT_SH_S_12);
    bez(var_0, label_687);
    bitSet(LBIT_0007);
    bitSet(MBIT_SH_H_12);
    bitClear(MBIT_SH_S_12);
    bnz(var_0, label_6bd);
  label_687:
    bitGet(var_0, MBIT_SH_S_13);
    bez(var_0, label_68d);
    bitSet(LBIT_0008);
    bitSet(MBIT_SH_H_13);
    bitClear(MBIT_SH_S_13);
    bnz(var_0, label_6bd);
  label_68d:
    bitGet(var_0, MBIT_SH_S_14);
    bez(var_0, label_693);
    bitSet(LBIT_0008);
    bitSet(MBIT_SH_H_14);
    bitClear(MBIT_SH_S_14);
    bnz(var_0, label_6bd);
  label_693:
    bitGet(var_0, MBIT_SH_S_15);
    bez(var_0, label_699);
    bitSet(LBIT_0007);
    bitSet(MBIT_SH_H_15);
    bitClear(MBIT_SH_S_15);
    bnz(var_0, label_6bd);
  label_699:
    bitGet(var_0, MBIT_SH_S_16);
    bez(var_0, label_69f);
    bitSet(LBIT_0008);
    bitSet(MBIT_SH_H_16);
    bitClear(MBIT_SH_S_16);
    bnz(var_0, label_6bd);
  label_69f:
    bitGet(var_0, MBIT_SH_S_17);
    bez(var_0, label_6a5);
    bitSet(LBIT_0009);
    bitSet(MBIT_SH_H_17);
    bitClear(MBIT_SH_S_17);
    bnz(var_0, label_6bd);
  label_6a5:
    bitGet(var_0, MBIT_SH_S_18);
    bez(var_0, label_6ab);
    bitSet(LBIT_0009);
    bitSet(MBIT_SH_H_18);
    bitClear(MBIT_SH_S_18);
    bnz(var_0, label_6bd);
  label_6ab:
    bitGet(var_0, MBIT_SH_S_19);
    bez(var_0, label_6b1);
    bitSet(LBIT_0009);
    bitSet(MBIT_SH_H_19);
    bitClear(MBIT_SH_S_19);
    bnz(var_0, label_6bd);
  label_6b1:
    bitGet(var_0, MBIT_SH_S_20);
    bez(var_0, label_6b7);
    bitSet(LBIT_0009);
    bitSet(MBIT_SH_H_20);
    bitClear(MBIT_SH_S_20);
    bnz(var_0, label_6bd);
  label_6b7:
    bitGet(var_0, MBIT_SH_S_21);
    bez(var_0, label_6bd);
    bitSet(LBIT_0013);
    bitSet(MBIT_SH_H_21);
    bitClear(MBIT_SH_S_21);
    bnz(var_0, label_6bd);
  label_6bd:
    ref_6bd = dialogAlloc();
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_70c);
    bitGet(var_0, LBIT_0006);
    bne(var_0, 0, label_6ff);
    bitGet(var_0, LBIT_0007);
    bne(var_0, 0, label_6f2);
    bitGet(var_0, LBIT_0008);
    bne(var_0, 0, label_6e5);
    bitGet(var_0, LBIT_0009);
    bne(var_0, 0, label_6d8);
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_6cb);
    b(label_6d7);
  label_6cb:
    bne(var_0, 1, label_6d7);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_6ce = msgShow(msg_99);
/***************************************
[tab][color(green)]人捜しの成功報酬、５００円を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(500);
    sync();
    wait(ref_6ce);
    shopCurrencyDisplay(-110, 150, true);
    b(label_6d7);
  label_6d7:
    b(label_6e4);
  label_6d8:
    bne(var_0, 1, label_6e4);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_6db = msgShow(msg_100);
/***************************************
[tab][color(green)]人捜しの成功報酬、５００００円を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(50000);
    sync();
    wait(ref_6db);
    shopCurrencyDisplay(-110, 150, true);
    b(label_6e4);
  label_6e4:
    b(label_6f1);
  label_6e5:
    bne(var_0, 1, label_6f1);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_6e8 = msgShow(msg_101);
/***************************************
[tab][color(green)]人捜しの成功報酬、４００００円を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(40000);
    sync();
    wait(ref_6e8);
    shopCurrencyDisplay(-110, 150, true);
    b(label_6f1);
  label_6f1:
    b(label_6fe);
  label_6f2:
    bne(var_0, 1, label_6fe);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_6f5 = msgShow(msg_102);
/***************************************
[tab][color(green)]人捜しの成功報酬、３００００円を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(30000);
    sync();
    wait(ref_6f5);
    shopCurrencyDisplay(-110, 150, true);
    b(label_6fe);
  label_6fe:
    b(label_70b);
  label_6ff:
    bne(var_0, 1, label_70b);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_702 = msgShow(msg_103);
/***************************************
[tab][color(green)]人捜しの成功報酬、２００００円を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(20000);
    sync();
    wait(ref_702);
    shopCurrencyDisplay(-110, 150, true);
    b(label_70b);
  label_70b:
    b(label_718);
  label_70c:
    bne(var_0, 1, label_718);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_70f = msgShow(msg_104);
/***************************************
[tab][color(green)]人捜しの成功報酬、１００００円を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(180);
    sndMusicPlay(sound_3037, 127);
    partyMoneyAdd(10000);
    sync();
    wait(ref_70f);
    shopCurrencyDisplay(-110, 150, true);
    b(label_718);
  label_718:
    dialogFree(ref_6bd);
    delayClear();
    delayWait(90);
  label_71b:
    bitGet(var_0, MBIT_AIS_29);
    bne(var_0, 0, label_73d);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_721);
    b(label_764);
    b(label_73c);
  label_721:
    bne(var_0, 1, label_73c);
    bitGet(var_0, MBIT_SIRA_UWASAHATU);
    bne(var_0, 0, label_726);
    b(label_766);
    b(label_73b);
  label_726:
    bne(var_0, 1, label_73b);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bne(var_0, 0, label_72b);
    b(label_764);
    b(label_73a);
  label_72b:
    bne(var_0, 1, label_73a);
    bitGet(var_0, MBIT_SIRA_HENIHATU);
    bne(var_0, 0, label_736);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bne(var_0, 0, label_732);
    b(label_764);
    b(label_735);
  label_732:
    bne(var_0, 1, label_735);
    b(label_77a);
    b(label_735);
  label_735:
    b(label_739);
  label_736:
    bne(var_0, 1, label_739);
    b(label_764);
    b(label_739);
  label_739:
    b(label_73a);
  label_73a:
    b(label_73b);
  label_73b:
    b(label_73c);
  label_73c:
    b(label_764);
  label_73d:
    bne(var_0, 1, label_764);
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_748);
    bitGet(var_0, MBIT_SIRA_HATURAITEN);
    bne(var_0, 0, label_744);
    b(label_78a);
    b(label_747);
  label_744:
    bne(var_0, 1, label_747);
    b(label_79a);
    b(label_747);
  label_747:
    b(label_763);
  label_748:
    bne(var_0, 1, label_763);
    bitGet(var_0, MBIT_SIRA_UWASAHATU);
    bne(var_0, 0, label_74d);
    b(label_7aa);
    b(label_762);
  label_74d:
    bne(var_0, 1, label_762);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bne(var_0, 0, label_752);
    b(label_79a);
    b(label_761);
  label_752:
    bne(var_0, 1, label_761);
    bitGet(var_0, MBIT_SIRA_HENIHATU);
    bne(var_0, 0, label_75d);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bne(var_0, 0, label_759);
    b(label_79a);
    b(label_75c);
  label_759:
    bne(var_0, 1, label_75c);
    b(label_7c1);
    b(label_75c);
  label_75c:
    b(label_760);
  label_75d:
    bne(var_0, 1, label_760);
    b(label_79a);
    b(label_760);
  label_760:
    b(label_761);
  label_761:
    b(label_762);
  label_762:
    b(label_763);
  label_763:
    b(label_764);
  label_764:
    shopRate(100);
    b(label_7d4);
  label_766:
    ref_766 = bustupLoad(bustup_ec);
    bustupWait(ref_766);
    ref_768 = bustupAlloc(ref_766, right, rgb(0,0,0));
    bustupFade(ref_768, rgb(128,0,0), 30);
    ref_76a = dialogAlloc();
    ref_76b = msgShow(msg_105);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]…マンサーチャー…因果な商売よねェ～
[tab]アタシは普通の女で死にたかったのよねェ～
[tab]でもねェ～世間が許してくれなかったのよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_76b);
    ref_76e = msgShow(msg_106);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]ふゥ～もう隠す必要も無いわねェ～
[tab]あんた、ヒマなら人捜し手伝わなァ～い？
[tab]もちろん、お礼は出すわよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_76e);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_76a);
    ref_773 = bustupFade(ref_768, rgb(0,0,0), 10);
    bustupWait(ref_773);
    bustupFree(ref_768);
    wait(ref_62b);
    bitSet(MBIT_SIRA_UWASAHATU);
    shopRate(100);
    b(label_7d4);
  label_77a:
    ref_77a = bustupLoad(bustup_ec);
    bustupWait(ref_77a);
    ref_77c = bustupAlloc(ref_77a, right, rgb(0,0,0));
    bustupFade(ref_77c, rgb(128,0,0), 30);
    ref_77e = dialogAlloc();
    ref_77f = msgShow(msg_107);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]はいよ。今日は何にするゥ～？
[tab]そうそう、新しい料理を用意したのよォ～
[tab]アタシが夢見た新料理、食べてねェ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_77f);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_77e);
    ref_784 = bustupFade(ref_77c, rgb(0,0,0), 10);
    bustupWait(ref_784);
    bustupFree(ref_77c);
    wait(ref_62b);
    shopRate(100);
    b(label_7d4);
  label_78a:
    ref_78a = bustupLoad(bustup_ec);
    bustupWait(ref_78a);
    ref_78c = bustupAlloc(ref_78a, right, rgb(0,0,0));
    bustupFade(ref_78c, rgb(128,0,0), 30);
    ref_78e = dialogAlloc();
    ref_78f = msgShow(msg_108);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]おや、初めてのお客さんだねェ～？
[tab]こんな店に来てくれてうれしいわァ。
[tab]よし、今日はまけとくよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_78f);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_78e);
    ref_794 = bustupFade(ref_78c, rgb(0,0,0), 10);
    bustupWait(ref_794);
    bustupFree(ref_78c);
    wait(ref_62b);
    shopRate(80);
    b(label_7d4);
  label_79a:
    ref_79a = bustupLoad(bustup_ec);
    bustupWait(ref_79a);
    ref_79c = bustupAlloc(ref_79a, right, rgb(0,0,0));
    bustupFade(ref_79c, rgb(128,0,0), 30);
    ref_79e = dialogAlloc();
    ref_79f = msgShow(msg_109);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]おやおや、今日も来てくれたのかい～？
[tab]あんたが来てくれると、ホントうれしいよォ。
[tab]よし、今日はまけとくよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_79f);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_79e);
    ref_7a4 = bustupFade(ref_79c, rgb(0,0,0), 10);
    bustupWait(ref_7a4);
    bustupFree(ref_79c);
    wait(ref_62b);
    shopRate(80);
    b(label_7d4);
  label_7aa:
    ref_7aa = bustupLoad(bustup_ec);
    bustupWait(ref_7aa);
    ref_7ac = bustupAlloc(ref_7aa, right, rgb(0,0,0));
    bustupFade(ref_7ac, rgb(128,0,0), 30);
    ref_7ae = dialogAlloc();
    ref_7af = msgShow(msg_110);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]…マンサーチャー…因果な商売よねェ～
[tab]アタシは普通の女で死にたかったのよねェ～
[tab]でもねェ～世間が許してくれなかったのよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7af);
    ref_7b2 = msgShow(msg_111);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]ふゥ～もう隠す必要も無いわねェ～
[tab]あんた、ヒマなら人捜し手伝わな～い？
[tab]もちろん、お礼は出すわよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7b2);
    ref_7b5 = msgShow(msg_112);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]それにしても、
[tab]あんたが来てくれると気分がいいわァ～
[tab]よし、今日はまけとくよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7b5);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7ae);
    ref_7ba = bustupFade(ref_7ac, rgb(0,0,0), 10);
    bustupWait(ref_7ba);
    bustupFree(ref_7ac);
    wait(ref_62b);
    bitSet(MBIT_SIRA_UWASAHATU);
    shopRate(80);
    b(label_7d4);
  label_7c1:
    ref_7c1 = bustupLoad(bustup_ec);
    bustupWait(ref_7c1);
    ref_7c3 = bustupAlloc(ref_7c1, right, rgb(0,0,0));
    bustupFade(ref_7c3, rgb(128,0,0), 30);
    ref_7c5 = dialogAlloc();
    ref_7c6 = msgShow(msg_113);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]おやおや、今日も来てくれたのかい～？
[tab]あんたが来てくれると、ホントうれしいよォ。
[tab]…そうそう、新しい料理を用意したのよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7c6);
    ref_7c9 = msgShow(msg_114);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]よし、今日はまけとくからねェ。
[tab]アタシが夢見た新料理、食べてよォ～？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7c9);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7c5);
    ref_7ce = bustupFade(ref_7c3, rgb(0,0,0), 10);
    bustupWait(ref_7ce);
    bustupFree(ref_7c3);
    wait(ref_62b);
    shopRate(80);
    b(label_7d4);
  label_7d4:
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_802);
    choiceSetResult(2);
    ref_7d7 = bustupLoad(bustup_ec);
    bustupWait(ref_7d7);
    ref_7d9 = bustupAlloc(ref_7d7, right, rgb(0,0,0));
    bustupFade(ref_7d9, rgb(128,0,0), 30);
    ref_7db = dialogAlloc();
    ref_7dc = msgShow(msg_115);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]はいよ。
[tab]今日は何にするゥ～？
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7dc);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_7e5);
    li(var_5, 0);
    b(label_7fa);
  label_7e5:
    bne(var_0, 1, label_7f4);
    choiceSetResult(2);
    ref_7e7 = msgShow(msg_116);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_7e7);
    choiceGetResult(var_0);
    bne(var_0, 0, label_7ed);
    li(var_5, 1);
    b(label_7f3);
  label_7ed:
    bne(var_0, 1, label_7f0);
    li(var_5, 2000);
    b(label_7f3);
  label_7f0:
    bne(var_0, 2, label_7f3);
    li(var_5, 1000);
    b(label_7f3);
  label_7f3:
    b(label_7fa);
  label_7f4:
    bne(var_0, 2, label_7f7);
    li(var_5, 2);
    b(label_7fa);
  label_7f7:
    bne(var_0, 3, label_7fa);
    li(var_5, 3);
    b(label_7fa);
  label_7fa:
    dialogFree(ref_7db);
    ref_7fb = bustupFade(ref_7d9, rgb(0,0,0), 10);
    bustupWait(ref_7fb);
    bustupFree(ref_7d9);
    shopInventory(12, shopInventory_5);
    ref_7ff = shopOpen(4);
    wait(ref_7ff);
    b(label_842);
  label_802:
    bne(var_0, 1, label_842);
    choiceSetResult(3);
    ref_804 = bustupLoad(bustup_ec);
    bustupWait(ref_804);
    ref_806 = bustupAlloc(ref_804, right, rgb(0,0,0));
    bustupFade(ref_806, rgb(128,0,0), 30);
    ref_808 = dialogAlloc();
    ref_809 = msgShow(msg_117);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]はいよ。
[tab]今日は何にするゥ～？
[choice(5)]人捜しの依頼
食事をする
話をする
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_809);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_812);
    li(var_5, 0);
    b(label_82a);
  label_812:
    bne(var_0, 1, label_815);
    li(var_5, 1);
    b(label_82a);
  label_815:
    bne(var_0, 2, label_824);
    choiceSetResult(2);
    ref_817 = msgShow(msg_118);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_817);
    choiceGetResult(var_0);
    bne(var_0, 0, label_81d);
    li(var_5, 2);
    b(label_823);
  label_81d:
    bne(var_0, 1, label_820);
    li(var_5, 2000);
    b(label_823);
  label_820:
    bne(var_0, 2, label_823);
    li(var_5, 1000);
    b(label_823);
  label_823:
    b(label_82a);
  label_824:
    bne(var_0, 3, label_827);
    li(var_5, 3);
    b(label_82a);
  label_827:
    bne(var_0, 4, label_82a);
    li(var_5, 4);
    b(label_82a);
  label_82a:
    dialogFree(ref_808);
    ref_82b = bustupFade(ref_806, rgb(0,0,0), 10);
    bustupWait(ref_82b);
    bustupFree(ref_806);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bne(var_0, 0, label_834);
    shopInventory(12, shopInventory_5);
    ref_831 = shopOpen(9);
    wait(ref_831);
    b(label_841);
  label_834:
    bne(var_0, 1, label_841);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bne(var_0, 0, label_83b);
    shopInventory(12, shopInventory_5);
    ref_838 = shopOpen(9);
    wait(ref_838);
    b(label_840);
  label_83b:
    bne(var_0, 1, label_840);
    shopInventory(12, shopInventory_6);
    ref_83d = shopOpen(9);
    wait(ref_83d);
    b(label_840);
  label_840:
    b(label_841);
  label_841:
    b(label_842);
  label_842:
}

function HA_SHOP_END_0()
{
    ref_843 = bustupLoad(bustup_ec);
    bustupWait(ref_843);
    ref_845 = bustupAlloc(ref_843, right, rgb(0,0,0));
    bustupFade(ref_845, rgb(128,0,0), 30);
    ref_847 = dialogAlloc();
    ref_848 = msgShow(msg_119);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]はいよォ～[delay(10)]
[tab]また来てちょうだいねェ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_848);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopOverlayInit();
    dialogFree(ref_847);
    ref_84e = bustupFade(ref_845, rgb(0,0,0), 10);
    bustupWait(ref_84e);
    bustupFree(ref_845);
    delayClear();
    delayWait(10);
    bitSet(MBIT_SIRA_HATURAITEN);
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bne(var_0, 0, label_857);
    b(label_86c);
  label_857:
    bne(var_0, 1, label_86c);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bne(var_0, 0, label_868);
    bitGet(var_0, LBIT_0010);
    bitGet(var_1, LBIT_0011);
    bitGet(var_2, LBIT_0012);
    add(var_0, var_0, var_1);
    add(var_0, var_0, var_2);
    boutrange(var_0, 0, 2, label_864);
    bitClear(LBIT_0010);
    bitClear(LBIT_0011);
    bitClear(LBIT_0012);
    b(label_867);
  label_864:
    bne(var_0, 3, label_867);
    bitSet(MBIT_SIRA_HENIHATU);
    b(label_867);
  label_867:
    b(label_86b);
  label_868:
    bne(var_0, 1, label_86b);
    bitSet(MBIT_SIRA_HENIHATU);
    b(label_86b);
  label_86b:
    b(label_86c);
  label_86c:
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_871);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    b(label_874);
  label_871:
    bne(var_0, 1, label_874);
    call(GOOUT);
    b(label_874);
  label_874:
}

function HA_SHOP_RESTART_0()
{
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bne(var_0, 0, label_8a0);
    choiceSetResult(2);
    ref_878 = bustupLoad(bustup_ec);
    bustupWait(ref_878);
    ref_87a = bustupAlloc(ref_878, right, rgb(0,0,0));
    bustupFade(ref_87a, rgb(128,0,0), 30);
    ref_87c = dialogAlloc();
    ref_87d = msgShow(msg_120);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]他にあるかしらァ～？
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_87d);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_886);
    li(var_5, 0);
    b(label_89b);
  label_886:
    bne(var_0, 1, label_895);
    choiceSetResult(2);
    ref_888 = msgShow(msg_121);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_888);
    choiceGetResult(var_0);
    bne(var_0, 0, label_88e);
    li(var_5, 1);
    b(label_894);
  label_88e:
    bne(var_0, 1, label_891);
    li(var_5, 2000);
    b(label_894);
  label_891:
    bne(var_0, 2, label_894);
    li(var_5, 1000);
    b(label_894);
  label_894:
    b(label_89b);
  label_895:
    bne(var_0, 2, label_898);
    li(var_5, 2);
    b(label_89b);
  label_898:
    bne(var_0, 3, label_89b);
    li(var_5, 3);
    b(label_89b);
  label_89b:
    dialogFree(ref_87c);
    ref_89c = bustupFade(ref_87a, rgb(0,0,0), 10);
    bustupWait(ref_89c);
    bustupFree(ref_87a);
    b(label_8cd);
  label_8a0:
    bne(var_0, 1, label_8cd);
    choiceSetResult(3);
    ref_8a2 = bustupLoad(bustup_ec);
    bustupWait(ref_8a2);
    ref_8a4 = bustupAlloc(ref_8a2, right, rgb(0,0,0));
    bustupFade(ref_8a4, rgb(128,0,0), 30);
    ref_8a6 = dialogAlloc();
    ref_8a7 = msgShow(msg_122);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]他にあるかしらァ～？
[choice(5)]人捜しの依頼
食事をする
話をする
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_8a7);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8b0);
    li(var_5, 0);
    b(label_8c8);
  label_8b0:
    bne(var_0, 1, label_8b3);
    li(var_5, 1);
    b(label_8c8);
  label_8b3:
    bne(var_0, 2, label_8c2);
    choiceSetResult(2);
    ref_8b5 = msgShow(msg_123);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_8b5);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8bb);
    li(var_5, 2);
    b(label_8c1);
  label_8bb:
    bne(var_0, 1, label_8be);
    li(var_5, 2000);
    b(label_8c1);
  label_8be:
    bne(var_0, 2, label_8c1);
    li(var_5, 1000);
    b(label_8c1);
  label_8c1:
    b(label_8c8);
  label_8c2:
    bne(var_0, 3, label_8c5);
    li(var_5, 3);
    b(label_8c8);
  label_8c5:
    bne(var_0, 4, label_8c8);
    li(var_5, 4);
    b(label_8c8);
  label_8c8:
    dialogFree(ref_8a6);
    ref_8c9 = bustupFade(ref_8a4, rgb(0,0,0), 10);
    bustupWait(ref_8c9);
    bustupFree(ref_8a4);
    b(label_8cd);
  label_8cd:
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bez(var_0, label_8e6);
    bitGet(var_0, MBIT_SIRA_HENIHATU);
    bnz(var_0, label_8e6);
    bitGet(var_0, MBIT_SIRAHENNISHU);
    bne(var_0, 0, label_8e3);
    bitGet(var_0, LBIT_0010);
    bitGet(var_1, LBIT_0011);
    bitGet(var_2, LBIT_0012);
    add(var_0, var_0, var_1);
    add(var_0, var_0, var_2);
    bne(var_0, 0, label_8dc);
    b(label_951);
    b(label_8e2);
  label_8dc:
    bne(var_0, 1, label_8df);
    b(label_975);
    b(label_8e2);
  label_8df:
    boutrange(var_0, 2, 3, label_8e2);
    b(label_990);
    b(label_8e2);
  label_8e2:
    b(label_8e6);
  label_8e3:
    bne(var_0, 1, label_8e6);
    b(label_943);
    b(label_8e6);
  label_8e6:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_935);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_927);
    bitGet(var_0, EBIT_E0038);
    bne(var_0, 0, label_8ed);
    b(label_8f6);
  label_8ed:
    bne(var_0, 1, label_8f6);
    bitGet(var_0, MBIT_SIRA_SAGIHAKKEN);
    bne(var_0, 0, label_8f2);
    b(label_90b);
    b(label_8f5);
  label_8f2:
    bne(var_0, 1, label_8f5);
    b(label_919);
    b(label_8f5);
  label_8f5:
    b(label_8f6);
  label_8f6:
    ref_8f6 = bustupLoad(bustup_ec);
    bustupWait(ref_8f6);
    ref_8f8 = bustupAlloc(ref_8f6, right, rgb(0,0,0));
    bustupFade(ref_8f8, rgb(128,0,0), 30);
    ref_8fa = dialogAlloc();
    ref_8fb = msgShow(msg_124);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]何？[tab]マンサーチャー？
[tab]そんな過去もあったっけねェ～？
[tab]でも、今はただの一杯飲み屋なのよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_8fb);
    ref_8fe = msgShow(msg_125);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]結婚詐欺の居場所を知りたいって言われてもねェ。
[tab]あ～そう言えば青葉区のパラベラムってバー、
[tab]最近女のコに人気があるみたいよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_8fe);
    ref_901 = msgShow(msg_126);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]女のコを騙すなら、
[tab]そういう店を利用するんじゃな～い？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_901);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_8fa);
    ref_906 = bustupFade(ref_8f8, rgb(0,0,0), 10);
    bustupWait(ref_906);
    bustupFree(ref_8f8);
    bitSet(MBIT_SAGIBER);
    b(label_99e);
  label_90b:
    ref_90b = bustupLoad(bustup_ec);
    bustupWait(ref_90b);
    ref_90d = bustupAlloc(ref_90b, right, rgb(0,0,0));
    bustupFade(ref_90d, rgb(128,0,0), 30);
    ref_90f = dialogAlloc();
    ref_910 = msgShow(msg_127);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]あらァ～ホントに結婚詐欺がいたのォ？
[tab]まァ、アタシを信じていればオッケェ～って事。
[tab]才能って怖いわねェ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_910);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_90f);
    ref_915 = bustupFade(ref_90d, rgb(0,0,0), 10);
    bustupWait(ref_915);
    bustupFree(ref_90d);
    b(label_99e);
  label_919:
    ref_919 = bustupLoad(bustup_ec);
    bustupWait(ref_919);
    ref_91b = bustupAlloc(ref_919, right, rgb(0,0,0));
    bustupFade(ref_91b, rgb(128,0,0), 30);
    ref_91d = dialogAlloc();
    ref_91e = msgShow(msg_128);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]マンサーチャーしてた頃の最後の仕事はねェ～
[tab]大統領の別れた愛人捜しだったのよォ～
[tab]ホント、未練がましい男だったねェ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_91e);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_91d);
    ref_923 = bustupFade(ref_91b, rgb(0,0,0), 10);
    bustupWait(ref_923);
    bustupFree(ref_91b);
    b(label_99e);
  label_927:
    ref_927 = bustupLoad(bustup_ec);
    bustupWait(ref_927);
    ref_929 = bustupAlloc(ref_927, right, rgb(0,0,0));
    bustupFade(ref_929, rgb(128,0,0), 30);
    ref_92b = dialogAlloc();
    ref_92c = msgShow(msg_129);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]近ごろ、人捜しをしてくれって客が多くてねェ～
[tab]ちょっとゲンナリしてるトコなのよォ。
[tab]どうも警察は取り合ってくれないらしいわァ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_92c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_92b);
    ref_931 = bustupFade(ref_929, rgb(0,0,0), 10);
    bustupWait(ref_931);
    bustupFree(ref_929);
    b(label_99e);
  label_935:
    ref_935 = bustupLoad(bustup_ec);
    bustupWait(ref_935);
    ref_937 = bustupAlloc(ref_935, right, rgb(0,0,0));
    bustupFade(ref_937, rgb(128,0,0), 30);
    ref_939 = dialogAlloc();
    ref_93a = msgShow(msg_130);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]最近の若者は個性がないわねェ～
[tab]その点、あの頃のハリウッドは違ったわァ。
[tab]皆、ギラギラして個性を放っていたものォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_93a);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_939);
    ref_93f = bustupFade(ref_937, rgb(0,0,0), 10);
    bustupWait(ref_93f);
    bustupFree(ref_937);
    b(label_99e);
  label_943:
    ref_943 = bustupLoad(bustup_ec);
    bustupWait(ref_943);
    ref_945 = bustupAlloc(ref_943, right, rgb(0,0,0));
    bustupFade(ref_945, rgb(128,0,0), 30);
    ref_947 = dialogAlloc();
    ref_948 = msgShow(msg_131);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]夢はねェ～追い続ける事に意味があるよねェ～
[tab]…夢を実現したんじゃないのかってェ～？
[tab]まだよォ～まだまだ夢の途中なのよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_948);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_947);
    ref_94d = bustupFade(ref_945, rgb(0,0,0), 10);
    bustupWait(ref_94d);
    bustupFree(ref_945);
    b(label_99e);
  label_951:
    ref_951 = bustupLoad(bustup_ec);
    bustupWait(ref_951);
    ref_953 = bustupAlloc(ref_951, right, rgb(0,0,0));
    bustupFade(ref_953, rgb(128,0,0), 30);
    ref_955 = dialogAlloc();
    ref_956 = msgShow(msg_132);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]なァ～に～？[tab]夢を実現したんだろって～？
[tab]ちょいと、あんまり大声で言わないでよォ～
[tab]照れちゃうじゃないかァ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_956);
    ref_959 = msgShow(msg_133);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]…自叙伝を出すこと。
[tab]それがアタシの夢だったのよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_959);
    ref_95c = msgShow(msg_134);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]お客さんに雑誌社の人がいてねェ～
[tab]是非ウチから出させてくれって言ってさァ。
[tab]いやァ～ラッキーだったわよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_95c);
    ref_95f = msgShow(msg_135);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]夢はねェ～追い続けるだけじゃダメなのよねェ～
[tab]実現してこそ意味があるのよォ～
[tab]…読みたいかい？[tab]アタシが読んであげるよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_95f);
    ref_962 = msgShow(msg_136);
/***************************************
[color(green)][tab]アタシが愛したゴールドのライセンスを持つ
[tab][tab]大統領のムーンボール・ノット・イナフ
[tab][tab][tab]～[tab]しらいしより、愛を込めて[tab]～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_962);
    ref_965 = msgShow(msg_137);
/***************************************
…アタシは、物心ついた時から戦士だった。
ノマノフ王朝最後の瞬間、幼かったアタシを
助け出したのは、西側の特殊諜報部員。
それが、あの男だった。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_965);
    ref_968 = msgShow(msg_138);
/***************************************
幼いアタシを助けたのは任務？[tab]それとも…
今となっては、誰にもわからないコト。
社会主義を目指し、共に戦ったのが最後の思い出。
過去を捨て、パリへと流れ着いたアタシの前に……
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_968);
    ref_96b = msgShow(msg_139);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]ふうゥ～今日はここまでにしとこうかねェ～
[tab]続きは今度聞かせてあげるよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_96b);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_955);
    ref_970 = bustupFade(ref_953, rgb(0,0,0), 10);
    bustupWait(ref_970);
    bustupFree(ref_953);
    bitSet(LBIT_0010);
    b(label_99e);
  label_975:
    ref_975 = bustupLoad(bustup_ec);
    bustupWait(ref_975);
    ref_977 = bustupAlloc(ref_975, right, rgb(0,0,0));
    bustupFade(ref_977, rgb(128,0,0), 30);
    ref_979 = dialogAlloc();
    ref_97a = msgShow(msg_140);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]続きねェ～？[tab]続きが知りたいのねェ～？
[tab]いいわよォ～読んであげるわよォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_97a);
    ref_97d = msgShow(msg_141);
/***************************************
[color(green)][tab]アタシが愛したゴールドのライセンスを持つ
[tab][tab]大統領のムーンボール・ノット・イナフ
[tab][tab][tab]～[tab]しらいしより、愛を込めて[tab]～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_97d);
    ref_980 = msgShow(msg_142);
/***************************************
…スーパーモデルとしての生活を捨て、
２０世紀最後のアイドルとなる事を選んだアタシ。
誰が悪い訳でもないし、誰の為でもなかった。
でも、大統領の想いには応えられなかった。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_980);
    ref_983 = msgShow(msg_143);
/***************************************
あの華やかなステージだけが、アタシの居場所。
偶像…それで良かった。それだけで良かった。
アタシに安住の地が無いコトはわかっていたけど、
もう硝煙に霞む世界にはいられない。それが……
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_983);
    ref_986 = msgShow(msg_144);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]とりあえずここまで。後は買って読んでねェ～
[tab]発行は株式会社キスメット出版。
[tab]１６００円（予）よォ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_986);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_979);
    ref_98b = bustupFade(ref_977, rgb(0,0,0), 10);
    bustupWait(ref_98b);
    bustupFree(ref_977);
    bitSet(LBIT_0011);
    b(label_99e);
  label_990:
    ref_990 = bustupLoad(bustup_ec);
    bustupWait(ref_990);
    ref_992 = bustupAlloc(ref_990, right, rgb(0,0,0));
    bustupFade(ref_992, rgb(128,0,0), 30);
    ref_994 = dialogAlloc();
    ref_995 = msgShow(msg_145);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]自叙伝の続き？[tab]もうダメよォ。
[tab]ちゃんと買って読んでよねェ～
[tab]…でも、発売日は未定なのよねェ～
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_995);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_994);
    ref_99a = bustupFade(ref_992, rgb(0,0,0), 10);
    bustupWait(ref_99a);
    bustupFree(ref_992);
    bitSet(LBIT_0012);
  label_99e:
}

function MESTEST1()
{
    bitGet(var_0, MBIT_KE_SIRAMAN);
    bnz(var_0, label_9a7);
    bitSet(MBIT_KE_SIRAMAN);
    ref_9a2 = dialogAlloc();
    ref_9a3 = msgShow(msg_146);
/***************************************
ＭＢＩＴ[tab]ＫＥ[tab]ＳＩＲＡＭＡＮ
マンサーチャーの噂[tab]
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9a3);
    dialogFree(ref_9a2);
    b(label_9af);
  label_9a7:
    bitGet(var_0, MBIT_KE_SIRAHENNI);
    bnz(var_0, label_9af);
    bitSet(MBIT_KE_SIRAHENNI);
    ref_9aa = dialogAlloc();
    ref_9ab = msgShow(msg_147);
/***************************************
ＭＢＩＴ[tab]ＫＥ[tab]ＳＩＲＡＨＥＮＮＩ
変異噂・決定
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9ab);
    dialogFree(ref_9aa);
    b(label_9af);
  label_9af:
}

function MESTEST()
{
    bitGet(var_0, MBIT_AIS_29);
    bnz(var_0, label_9b8);
    bitSet(MBIT_AIS_29);
    ref_9b3 = dialogAlloc();
    ref_9b4 = msgShow(msg_148);
/***************************************
ＭＢＩＴ[tab]ＡＩＳ[tab]２９
相性占いの
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9b4);
    dialogFree(ref_9b3);
    b(label_9e8);
  label_9b8:
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_9c0);
    bitSet(EBIT_E0037);
    ref_9bb = dialogAlloc();
    ref_9bc = msgShow(msg_149);
/***************************************
ＥＢＩＴ[tab]Ｅ００３７
警察署[half_tab]受付、終了
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9bc);
    dialogFree(ref_9bb);
    b(label_9e8);
  label_9c0:
    bitGet(var_0, EBIT_E0038);
    bnz(var_0, label_9c8);
    bitSet(EBIT_E0038);
    ref_9c3 = dialogAlloc();
    ref_9c4 = msgShow(msg_150);
/***************************************
ＥＢＩＴ[tab]Ｅ００３８
「詐欺男を確保」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9c4);
    dialogFree(ref_9c3);
    b(label_9e8);
  label_9c8:
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_9d0);
    bitSet(EBIT_E003E);
    ref_9cb = dialogAlloc();
    ref_9cc = msgShow(msg_151);
/***************************************
ＥＢＩＴ[tab]Ｅ００３Ｅ
「ゴールドクリア」「うらら編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9cc);
    dialogFree(ref_9cb);
    b(label_9e8);
  label_9d0:
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_9d8);
    bitSet(EBIT_E0043);
    ref_9d3 = dialogAlloc();
    ref_9d4 = msgShow(msg_152);
/***************************************
ＥＢＩＴ[tab]Ｅ００４３
「クラブクリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9d4);
    dialogFree(ref_9d3);
    b(label_9e8);
  label_9d8:
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_9e0);
    bitSet(EBIT_E0046);
    ref_9db = dialogAlloc();
    ref_9dc = msgShow(msg_153);
/***************************************
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9dc);
    dialogFree(ref_9db);
    b(label_9e8);
  label_9e0:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_9e8);
    bitSet(EBIT_E006F);
    ref_9e3 = dialogAlloc();
    ref_9e4 = msgShow(msg_154);
/***************************************
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9e4);
    dialogFree(ref_9e3);
    b(label_9e8);
  label_9e8:
}

function DOORBOX()
{
    controlDisable();
    sndMusicPlay(sound_306d, 127);
    objAnimTranslate(obj_0, 100, 0, 0, 30);
    objAnimWait(obj_0);
    call(GOOUT);
}

function warp1()
{
    call(DOORBOX);
}

function GOOUT()
{
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function HA_SHOP_EXPLAIN_0()
{
    choiceSetResult(2);
    ref_9f5 = dialogChoiceAlloc();
    ref_9f6 = msgShow(msg_155);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)][if_all(MBIT_KE_SIRAMAN)]人捜し
食事
やめる
[end_choice][clear]
***************************************/
    wait(ref_9f6);
    dialogFree(ref_9f5);
    choiceGetResult(var_0);
    bne(var_0, 0, label_a00);
    ref_9fb = dialogAlloc();
    ref_9fc = msgShow(msg_156);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]「人捜し」の説明ね～。
[tab]ウチの店で「人捜し」を選んだら
[tab]人捜しの依頼を受けてもらうよォ～。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]人捜しってェ～のは、依頼された「尋ね人」を捜すことよ。
[tab]まず、依頼のリストからどれを受けるか選んでねェ～。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]リストには「尋ね人」の名前と情報、あと受ける際に
[tab]払ってもらう請負料が書いてあるわよォ～。
[tab]でェ～、引き受けたら捜索開始ねェ～。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]捜す方法としては、とにかく人に話しかけることねェ～。
[tab]それでェ～、情報と照らし合わせてこれだ！という
[tab]人がいたら、もう一度話しかけてみるのよォ～！
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]捜している本人だったら、用件を聞き返してくるよォ～。
[tab]そこで、相手の名前を言い当てるのよォ～。
[tab]当たっていればめでたく捜索終了ねェ。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]ここへ戻ってくれば、報酬をあげるわ～。
[tab]ひと～つ覚えておいてほしいのは、引き受けた依頼を
[tab]終わらせるまで、次の依頼は受けさせないわよォ～。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]そ～んないい加減、許さないからねェ～！
[wait][clear]
***************************************/
    wait(ref_9fc);
    dialogFree(ref_9fb);
    b(label_a08);
  label_a00:
    bne(var_0, 1, label_a06);
    ref_a01 = dialogAlloc();
    ref_a02 = msgShow(msg_157);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]「食事」の説明ねェ～。
[tab]ウチの店で「食事をする」を選ぶと
[tab]食事をすることができるわ～。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]食事には、一時的に能力を高める効果があるわよォ～。
[tab]効果はメニューによって違うから、色々食べて
[tab]確認してみてねェ～。
[wait][clear][color(yellow)]おばちゃん[color(white)]
[tab]あと、一度食事を取るとその効果が切れるまで
[tab]つぎの食事はできないわよ～。
[tab]こ～んなとこかしら～。
[wait][clear]
***************************************/
    wait(ref_a02);
    dialogFree(ref_a01);
    b(label_a08);
  label_a06:
    bne(var_0, 2, label_a08);
    b(label_a08);
  label_a08:
}

function DECIDE_EAT()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a0c = bustupLoad(bustup_ec);
    bustupWait(ref_a0c);
    ref_a0e = bustupAlloc(ref_a0c, left, rgb(0,0,0));
    bustupFade(ref_a0e, rgb(128,0,0), 30);
    ref_a10 = dialogAlloc();
    ref_a11 = msgShow(msg_158);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]それなら[var(msg_var_0)]円になるけど、
[tab]一杯やってくかいィ～？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_a11);
    choiceGetResult(var_7);
    bne(var_7, 0, label_a17);
    li(var_7, 1);
    b(label_a1a);
  label_a17:
    bne(var_7, 1, label_a1a);
    li(var_7, 0);
    b(label_a1a);
  label_a1a:
    wait(ref_a11);
    dialogFree(ref_a10);
    ref_a1c = bustupFade(ref_a0e, rgb(0,0,0), 10);
    bustupWait(ref_a1c);
    bustupFree(ref_a0e);
    li(var_5, 20);
}

function DECIDE_SEARCH()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a24 = bustupLoad(bustup_ec);
    bustupWait(ref_a24);
    ref_a26 = bustupAlloc(ref_a24, left, rgb(0,0,0));
    bustupFade(ref_a26, rgb(128,0,0), 30);
    ref_a28 = dialogAlloc();
    ref_a29 = msgShow(msg_159);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]紹介料として、[var(msg_var_0)]円いただくけど、
[tab]この依頼、引き受けてくれるのかァ～い？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_a29);
    choiceGetResult(var_7);
    bne(var_7, 0, label_a2f);
    li(var_7, 1);
    b(label_a32);
  label_a2f:
    bne(var_7, 1, label_a32);
    li(var_7, 0);
    b(label_a32);
  label_a32:
    wait(ref_a29);
    dialogFree(ref_a28);
    ref_a34 = bustupFade(ref_a26, rgb(0,0,0), 10);
    bustupWait(ref_a34);
    bustupFree(ref_a26);
}

function NODECIDE()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a3b = bustupLoad(bustup_ec);
    bustupWait(ref_a3b);
    ref_a3d = bustupAlloc(ref_a3b, left, rgb(0,0,0));
    bustupFade(ref_a3d, rgb(128,0,0), 30);
    ref_a3f = dialogAlloc();
    ref_a40 = msgShow(msg_160);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]ダメよォ～！[tab]前に引き受けた依頼を
[tab]解決してからにしてねェ～
[wait][clear]
***************************************/
    wait(ref_a40);
    dialogFree(ref_a3f);
    ref_a43 = bustupFade(ref_a3d, rgb(0,0,0), 10);
    bustupWait(ref_a43);
    bustupFree(ref_a3d);
}

function NOMONEY()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a4a = bustupLoad(bustup_ec);
    bustupWait(ref_a4a);
    ref_a4c = bustupAlloc(ref_a4a, left, rgb(0,0,0));
    bustupFade(ref_a4c, rgb(128,0,0), 30);
    ref_a4e = dialogAlloc();
    ref_a4f = msgShow(msg_161);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]依頼料も払えないような大人には
[tab]頼めないねェ～
[wait][clear]
***************************************/
    wait(ref_a4f);
    dialogFree(ref_a4e);
    ref_a52 = bustupFade(ref_a4c, rgb(0,0,0), 10);
    bustupWait(ref_a52);
    bustupFree(ref_a4c);
}

function RESULTDECIDE()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a59 = bustupLoad(bustup_ec);
    bustupWait(ref_a59);
    ref_a5b = bustupAlloc(ref_a59, left, rgb(0,0,0));
    bustupFade(ref_a5b, rgb(128,0,0), 30);
    ref_a5d = dialogAlloc();
    ref_a5e = msgShow(msg_162);
/***************************************
[color(yellow)]おばちゃん[color(white)]
[tab]その依頼はもう解決したでしょ～
[tab]忘れたのかいィ？
[wait][clear]
***************************************/
    wait(ref_a5e);
    dialogFree(ref_a5d);
    ref_a61 = bustupFade(ref_a5b, rgb(0,0,0), 10);
    bustupWait(ref_a61);
    bustupFree(ref_a5b);
}

function MISEINEN()
{
    ref_a65 = dialogAlloc();
    ref_a66 = msgShow(msg_163);
/***************************************
[color(green)]未成年は飲酒できません。
[wait][clear]
***************************************/
    wait(ref_a66);
    dialogFree(ref_a65);
    li(var_5, 20);
}
