
msg_0:
このままじゃハングします。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ありゃ…なんだコイツ、
[tab]私のこと睨んでるよ。
[tab]食っちゃうぞ～
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]あの板さん、いっさましいねぇ～
[tab]街の人が皆ああならいいんだけど…
[tab]それもうるさいかな？
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]こりゃ、太郎！[tab]お前元気か？
[tab]お前美味そう～
[tab]俺様丸呑み！
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]マーヤも複雑な心境なんじゃない？
[tab]だって向こうの世界じゃ、死んじゃってんのよ。
[tab]…まぁ…実感無いかも知れないけどさ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]太郎…元気か？[tab]街が飛んでるよ～
[tab]お前には分からないだろうけどさ…
[tab]私が何とかすっからねぇ～
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]ねぇマーヤ、
[tab]この魚、買って帰ってもいいかな？
[end]

msg_7:
[tab]しょ…食用じゃないよ！[tab]飼うんだから！
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]スニーク…か。
[tab]聞き覚えのある声とは思っていたが…
[tab]なぜすぐに気付かなかったんだ僕は！
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]ここでパニックを起こせば、
[tab]それこそ奴らの思うツボだ。
[tab]どうにかできないものか…
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]の奴、がってん寿司を見たとき
[tab]随分と驚いてたな…
[tab]どうしたんだ？
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]そうか…
[tab]「向こう側」では、この寿司屋は平坂区に
[tab]あったのか…
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]嵯峨の奴…
[tab][tatsuya]をうまく引き止めてくれた事は感謝するが、
[tab]貯金の事までバラさなくてもいいだろうに…
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]うまく神事とやらを食いとめたとしても、
[tab]それからどうする？
[tab]この街、下ろす事はできるのか？
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]親父さんや栄吉君、みんなのためにも…
[tab]負けるわけにはいかないぞ…天野君。
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢は何してんだ？
[tab]気でもふれたか？
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]俺達は、
[tab]あのイケスの魚と同じかも知れねぇな…
[tab]…嫌になってくるぜ。
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢の奴、またやってるのか？
[tab]イケスの魚に名前つけてどうする気だ？
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]へへへ、
[tab][suou]はだいぶご立腹のようだな。
[tab]まぁ、眼には眼を…ってやつだ。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢の奴、話しかけているうちに
[tab]情が湧いたそうだ。
[tab]ありゃ買い取るんじゃねえか？
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]結局、云豹も、あの竜蔵も、ニャルとかいうヤツの
[tab]手駒に過ぎなかったって事か…
[tab]舐めたマネしてくれるじゃねぇか…
[wait][clear][end]

msg_21:
[color(yellow)]南条[color(white)]
[tab]一つの講演会を叩いたところで、
[tab]効果は期待できない…か。
[tab]既に何人洗脳されてしまっているんだ…
[wait][clear][end]

msg_22:
[color(yellow)]南条[color(white)]
[tab]あの栄吉という少年は、
[tab]ここの息子のようですが…
[tab]まだ帰ってきていないのか…
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]そうか…城戸は行ってしまったか。
[tab]神取の事、できれば俺の口から伝えたかったが…
[tab]また、いずれ会うこともあるだろう。
[wait][clear][end]

msg_24:
[color(yellow)]エリー[color(white)]
[tab]講演会を一つ叩いただけでは、
[tab]あまり効果は期待できませんわね…
[tab]もう何人の人が洗脳されてしまったのかしら…
[wait][clear][end]

msg_25:
[color(yellow)]エリー[color(white)]
[tab]Ｎｏ…ウニを見てたら、
[tab]あのドロドロを思い出してしまって…
[tab]ちょっと食欲Ｄｏｗｎですわ…
[wait][clear][end]

msg_26:
[color(yellow)]エリー[color(white)]
[tab]あそこにいるのは、Ｒｅｉｊｉですわ！
[tab]彼も昔の仲間なんですの。
[tab]まさかこんな所で会えるなんて。
[wait][clear][end]

msg_27:
[color(yellow)]エリー[color(white)]
[tab]Ｗａｎｇｌｏｎｇ千鶴…
[tab]私、少しだけ彼女が羨ましいんです。
[wait][clear][end]

msg_28:
[color(yellow)]エリー[color(white)]
[tab]…どうやらＲｅｉｊｉは
[tab]行ってしまったようですわね。
[tab]またいつか会えるかしら…
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]な…なんで、がってん寿司が蓮華台に…
[tab]平坂区じゃなかったのか…
[wait][clear][end]

msg_30:
[color(yellow)][tatsuya][color(white)]
[tab]舞耶姉…
[tab]ここが栄吉の家だって、覚えてるか…？
[tab]栄吉…いないのか…
[wait][clear][end]

msg_31:
[color(yellow)][tatsuya][color(white)]
[tab]このトリフネの姿は、
[tab]「向こう側」に出現したシバルバーと同じなんだ。
[tab]このままじゃ、街の人達の記憶が…
[wait][clear][end]

msg_32:
[color(yellow)][tatsuya][color(white)]
[tab]栄吉…
[tab]絶対、終わらせる…
[tab]待ってろ…
[wait][clear][end]

msg_33:
[color(yellow)]噂屋トロ[color(white)]
[tab]何を隠そう、僕は凄腕のセールスマンなんだけど、
[tab]職業がら、噂話にくわしくなっちゃってね。
[tab]今じゃ「噂屋」なんて呼ばれてるんだ。
[wait][clear][end]

msg_34:
[color(yellow)]横内[tab]健太（よこうち[tab]けんた）[color(white)]
[tab][color(green)]エルミン学園の卒業生。
[tab]噂に詳しい、訪問販売のトップセールスマン。
[tab]営業成績は、実はペルソナの賜物らしい。[color(white)]
[wait][clear][end]

msg_35:
[color(yellow)]噂屋トロ[color(white)]
[tab]噂話は、セールスの役に立つからね～
[tab]君も、何か面白い噂を聞いたら、ぜひ教えてよ。
[tab]かわりに、僕の知ってる噂を提供するからさ。
[wait][clear][end]

msg_36:
[color(yellow)]噂屋トロ[color(white)]
[tab]ムハァ～
[tab]やっぱ寿司はエンガワだね、エンガワ最高ー！！
[tab]…で？[tab]何の用かな？
[wait][clear][end]

msg_37:
[color(yellow)]噂屋トロ[color(white)]
[tab]何の用かな？
[end]

msg_38:
[color(yellow)]噂屋トロ[color(white)]
[tab]他に何かある？
[end]

msg_39:
[choice(3)]噂話を聞く
話をする
用はない
[end_choice][clear][end]

msg_40:
[color(yellow)]噂屋トロ[color(white)]
[tab]う～ん…
[tab]今のところ、他に情報は無いね。
[tab]また仕入れておくよ。
[wait][clear][end]

msg_41:
[color(yellow)]噂屋トロ[color(white)]
[tab]噂だね？
[tab]丁度良い話があるよ。
[tab]じゃあまず、そっちの情報聞かせて。
[wait][clear][end]

msg_42:
[color(yellow)]噂屋トロ[color(white)]
[tab]ムハァ～いいとも～
[tab]じゃあ、そっちの情報から教えてくれる？
[tab]新鮮なヤツじゃないとダメだよ。
[wait][clear][end]

msg_43:
[color(yellow)]噂屋トロ[color(white)]
[tab]……ふ～ん。なかなか良い情報だね。
[tab]っていうか、やるねキミ。
[tab]じゃあボクの情報だけど…
[wait][clear][end]

msg_44:
[color(yellow)]噂屋トロ[color(white)]
[tab]へぇ～、その情報は知らなかったなぁ。
[tab]ムハァ～激大漁って感じ。
[tab]じゃあボクの情報を教えてあげるよ。
[wait][clear][end]

msg_45:
[color(yellow)]噂屋トロ[color(white)]
[tab]あのね、この区にある[color(orange)]時間城[color(white)]ってお店で、
[tab]不思議な[color(orange)]魔法のカードを売ってる[color(white)]らしいんだ。
[tab]だけど魔法なんて本当にあるのかな？
[wait][clear][end]

msg_46:
[color(yellow)]噂屋トロ[color(white)]
[tab]実はまた[color(orange)]時間城[color(white)]の噂を仕入れたんだ。
[tab]なんでもあそこの店主、
[tab][color(orange)]魔法のカードの複製[color(white)]までやってるらしいよ。
[wait][clear][end]

msg_47:
[color(yellow)]噂屋トロ[color(white)]
[tab][color(orange)]月刊バトルマスター[color(white)]って雑誌知ってる？
[tab]実はあの本の懸賞に応募すると、
[tab][color(orange)]本物の武器[color(white)]が当たるらしいんだ。
[wait][clear][end]

msg_48:
[color(yellow)]噂屋トロ[color(white)]
[tab][color(orange)]ファンタジーワールド[color(white)]って雑誌、知ってるかい？
[tab]噂じゃその雑誌の懸賞に応募すると
[tab][color(orange)]本物の武器[color(white)]が当たるらしいんだ。
[wait][clear][end]

msg_49:
[color(yellow)]噂屋トロ[color(white)]
[tab]うひょ～エンガワうま～い！！
[tab]だけど玲司クンにはあげないもんね。
[tab]うっふふ～
[wait][clear][end]

msg_50:
[color(yellow)]噂屋トロ[color(white)]
[tab]望龍術…世界滅亡…トリフネかぁ…
[tab]なぜか、前にもこんな事件があった気がする…
[tab]そしてその時も僕はエンガワ食べてた気がする…
[wait][clear][color(yellow)]噂屋トロ[color(white)]
[tab]これって気のせいかな？
[tab]気のせいだよね？
[wait][clear][end]

msg_51:
[color(yellow)]噂屋トロ[color(white)]
[tab]さっきまで、デキの悪い同僚に、
[tab]セールスのコツをレクチャーしてあげてたんだ。
[tab]少しはうまくなるかな……ムリだなきっと。
[wait][clear][end]

msg_52:
[color(yellow)]噂屋トロ[color(white)]
[tab]玲司クンなら本社の方に帰ったよ。
[tab]何か大切な話でもあったの？
[wait][clear][end]

msg_53:
[color(yellow)]噂屋トロ[color(white)]
[tab]あのさ…イケスの魚を注文したら、
[tab]髪の赤い女の人に、涙目で睨まれたんだけど…
[tab]ボク何か悪いことしたかな…
[wait][clear][end]

msg_54:
[color(yellow)]噂屋トロ[color(white)]
[tab]ペルソナはね、もう一人の君であると同時に、
[tab]僕達みんなの一部でもあるんだ。
[tab]君は一人で戦っているんじゃないよ。
[wait][clear][color(yellow)]噂屋トロ[color(white)]
[tab]ペルソナの共鳴…
[tab]知ってたさ、全部。
[tab]だから…がんばってね。
[wait][clear][end]

msg_55:
[color(yellow)]噂屋トロ[color(white)]
[tab]そう。
[tab]じゃあ、また噂が聞きたくなったら来てよ。
[tab]僕はここで、ひたすらエンガワ食べてるからさ。
[wait][clear][end]

msg_56:
[color(yellow)]寿司公爵[color(white)]
[tab]この前、奥に座ってた社長を見かけてよ、
[tab]話しかけたらレッツ・ポジティブ…なんとか～って
[tab]そればっかり言うんだよ。どうしちまったんだ？
[wait][clear][end]

msg_57:
[color(yellow)]寿司公爵[color(white)]
[tab]望龍術ったら、
[tab]最近人気の占いだったよなぁ。
[tab]それで世界を滅ぼす…なんてできんのかい？
[wait][clear][end]

msg_58:
[color(yellow)]寿司公爵[color(white)]
[tab]なんでぃ、
[tab]さっきからグラグラしやがって！
[tab]ナマズでも暴れてんのか？
[wait][clear][end]

msg_59:
[color(yellow)]寿司公爵[color(white)]
[tab]鳴海区の地下鉄工事。
[tab]ありゃホントは工事なんかじゃなくてよ、
[tab]アメノトリフネの発掘をしてるらしいんだわ。
[wait][clear][color(yellow)]寿司公爵[color(white)]
[tab]いや、俺もそういう噂を聞いただけで、
[tab]じかに中を見たわけじゃねぇんだが…
[tab]ありえねぇ話じゃねえよな？
[wait][clear][end]

msg_60:
[color(yellow)]寿司公爵[color(white)]
[tab]なぁ…シバルバーって知らねぇか？
[tab]あのドデカイリングを見たとき、
[tab]思わずそう叫んじまってよ…
[wait][clear][color(yellow)]寿司公爵[color(white)]
[tab]だけどシバルバーって何だ？
[tab]それがどうにも思い出せねぇんだよなぁ…
[wait][clear][end]

msg_61:
[color(yellow)]寿司公爵[color(white)]
[tab]ここの若旦那が行方不明なんだとよ。
[tab]こんな時だしなぁ…
[tab]さすがの大将も冷静じゃいられねぇか…
[wait][clear][end]

msg_62:
[color(yellow)]寿司貴族[color(white)]
[tab]寿司貴族は寿司貴族だけに寿司が主食ッス！
[tab]故に自分も貴族の端くれとして恥じぬよう、
[tab]一生懸命エンガワを食ってるッス！！
[wait][clear][color(yellow)]寿司貴族[color(white)]
[tab]もうお腹がいっぱいで、
[tab]家に帰っても何も食べられないッス。
[tab]だけどいいんッス！[tab]これが貴族の生き様ッス！
[wait][clear][end]

msg_63:
[color(yellow)]寿司貴族[color(white)]
[tab]あれ？
[tab]まだ自分に何か用ッスか？
[tab]もしかして、メンバーに入りたいッスか？
[wait][clear][end]

msg_64:
[tab]何か用ですか？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_65:
スズキユウイチ
[end]

msg_66:
[color(yellow)]寿司貴族[color(white)]
[tab]あえ？
[tab]それ…誰ッスか？
[tab]自分はそんな人、知らないッスよ。
[wait][clear][end]

msg_67:
[color(yellow)]寿司貴族[color(white)]
[tab]あれれれ？
[tab]どうして自分の名を知ってるんスか？
[tab]あ、あなたは一体…
[wait][clear][color(yellow)]スズキ[tab]ユウイチ[color(white)]
[tab]えっ！？[tab]自分の捜索願が！？
[tab]ははーん、多分ママンの仕業ッスねぇ。
[tab]ママンはあれで心配性ッスから…
[wait][clear][color(yellow)]スズキ[tab]ユウイチ[color(white)]
[tab]了解ッス。報せてくれて感謝ッス！
[tab]しらいしさんとママンには僕が報告しておくッス。
[tab]ありがとうございましたッス！
[wait][clear][end]

msg_68:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_69:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_70:
[tab]新世塾というのを聞いたことがありますか？
[tab]なんでもそんな組織があるらしいッスよ。
[tab]穢れを集めて…街の人達を洗脳してる…とか。
[wait][clear][end]

msg_71:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_72:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_73:
[tab]自分は知ってるッス。
[tab]あの板さん、トリフネのニュース聞いたとき、
[tab]マジでビビッてたッス。
[wait][clear][end]

msg_74:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_75:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_76:
[tab]あれはどう見ても、
[tab]カラ元気ってヤツッス。
[wait][clear][end]

msg_77:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_78:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_79:
[tab]やっぱトリフネは実在するんスか？
[tab]だって、さっきから地震続きッス！！
[tab]じゃあやっぱり、世界滅亡も…アワワワワ…
[wait][clear][end]

msg_80:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_81:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_82:
[tab]毎度の事ですが、
[tab]トリフネが出てきて一番ビビってたのは、
[tab]ここの板さんッス。
[wait][clear][end]

msg_83:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_84:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_85:
[tab]例によって、
[tab]あれはカラ元気ッスよ。
[wait][clear][end]

msg_86:
[color(yellow)]寿司貴族[color(white)]
[end]

msg_87:
[color(yellow)]スズキ[tab]ユウイチ[color(white)]
[end]

msg_88:
[tab]知ってるッス…大変な事くらい。
[tab]でもね、騒いでも何もならないでしょ？
[tab]だからヤケ食いッス。
[wait][clear][end]

msg_89:
[color(yellow)]玲司[color(white)]
[tab]こいつ、
[tab]寿司食うばっかりで、
[tab]ちっとも俺の話を聞きやがらねぇ！
[wait][clear][end]

msg_90:
[color(yellow)]玲司[color(white)]
[tab]用も粗方片付いたしな…
[tab]俺はそろそろ、行くぜ。
[tab]アンタ等も達者でな。
[wait][clear][color(yellow)]玲司[color(white)]
[tab]そうだ…
[tab]よく切れる包丁が欲しいって時は連絡してくれ。
[tab]すぐに駆けつけるからよ。
[wait][clear][end]

msg_91:
[color(yellow)]玲司[color(white)]
[tab]ど、どうもこんにちは…でございまして、
[tab]私、包丁のセールスをしておりましまして…て…
[tab]……
[wait][clear][end]

msg_92:
[color(yellow)]玲司[color(white)]
[tab]ダメだぁ…
[tab]どうにも、この甘ったるい喋り方は
[tab]性に合わねぇぜ…
[wait][clear][end]

msg_93:
[color(yellow)]城戸[tab]玲司（きど[tab]れいじ）[color(white)]
[tab][color(green)]かつて南条やエリーと共に戦ったペルソナ使い。
[tab]「伝説の裸番長」の異名を持つ。
[tab]南条が追う神取の異母兄弟でもある。[color(white)]
[wait][clear][end]

msg_94:
[color(yellow)]玲司[color(white)]
[tab]ん？
[tab]ペルソナが共鳴しやがる…
[tab]…なるほどな、あんたがそうか。
[wait][clear][end]

msg_95:
[color(yellow)]玲司[color(white)]
[tab]話は南条から聞いてるぜ。
[tab]昔の仲間が世話になってるらしいな。
[tab]一応、礼を言っとくぜ。
[wait][clear][end]

msg_96:
[color(yellow)]板さん[color(white)]
[tab]へい、らっしゃい！！
[tab]おっ、初めてのお客さんかい？
[tab]よく来てくれたねえ！！
[wait][clear][color(yellow)]板さん[color(white)]
[tab]当店がってん寿司は新鮮なネタと、
[tab]神をも恐れぬ低価格が売りよ！！

[wait][clear][end]

msg_97:
[color(yellow)]板さん[color(white)]
[tab]…それにしても…なんだな…
[tab]姉さんたぁ、他人って気がしねぇやなぁ。
[tab]よっしゃ！[tab]今日のところはお値段割引でぃ！！
[wait][clear][end]

msg_98:
[color(yellow)]板さん[color(white)]
[tab]ヘイッ、らっしゃいっ！！
[tab]どうでぃ、いい呼び声だろ？
[tab]客はこうやって心と魂で迎えるもんでぃ。
[wait][clear][end]

msg_99:
[color(yellow)]板さん[color(white)]
[tab]おっと、なんかへんな感じだねえ。
[tab]姉さんは他人って気がしねぇや。
[tab]よっしゃ！[tab]料金はオマケしとくぜぃ！
[wait][clear][end]

msg_100:
[color(yellow)]板さん[color(white)]
[tab]ジャンジャン食べてってくんな！！
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_101:
[color(yellow)]板さん[color(white)]
[tab]おうっ！[tab]何が聞きたいんでい！
[choice(3)]世間話をする
食事の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_102:
[color(yellow)]板さん[color(white)]
[tab]他に何かあるかい！
[tab]どんどん言ってくれよ！！
[tab]威勢の良い客大歓迎でぃ！！
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_103:
[color(yellow)]板さん[color(white)]
[tab]おうっ！[tab]何が聞きたいんでい！
[choice(3)]世間話をする
食事の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_104:
[color(yellow)]板さん[color(white)]
[tab]なんでもスマイル平坂で
[tab]ボヤ騒動があったんだとよ！
[tab]火の用心だけはしっかりしねぇとな！
[wait][clear][end]

msg_105:
[color(yellow)]板さん[color(white)]
[tab]世界が滅亡しようと、
[tab]がってん寿司は年中無休よ！
[tab]安心して来てくんな！！
[wait][clear][end]

msg_106:
[color(yellow)]板さん[color(white)]
[tab]あり…
[tab]その赤いなりした兄ちゃん…
[tab]どっかで見た気がするなぁ…気のせいか？
[wait][clear][end]

msg_107:
[color(yellow)]板さん[color(white)]
[tab]てやんでぃ、べらぼうめぃ！！
[tab]空を飛ぶたぁ、
[tab]この街も随分と生きが良いじゃねぇか！
[wait][clear][end]

msg_108:
[color(yellow)]板さん[color(white)]
[tab]栄吉の奴？[tab]まだ帰ってねぇな…
[tab]アイツは大丈夫だ…簡単に死ぬ玉じゃねぇ…
[wait][clear][end]

msg_109:
[color(yellow)]板さん[color(white)]
[tab]てめぇの倅が信じられなくて、
[tab]寿司が握れるかってんだ…！
[tab]あいつが帰ぇってくるまで、寿司を握るだけよ！
[wait][clear][end]

msg_110:
[color(yellow)]板さん[color(white)]
[tab]おうっ！
[tab]ネタが新鮮なうちにまた来てくんな！
[tab]歓迎するからよ！[tab]てやんでぃ！
[wait][clear][end]

msg_111:
[color(yellow)]板さん[color(white)]
[tab]おうっ、「食事」の説明だな。
[tab]うちの店で「食事をする」を選ぶと
[tab]自慢の寿司をふるまってやるぜっ！
[wait][clear][color(yellow)]板さん[color(white)]
[tab]うちの寿司にはなんと、
[tab]一時的に能力を高める効果があるんだぜっ！
[tab]効果はネタによって違うから、色々食べてみてくんな！
[wait][clear][color(yellow)]板さん[color(white)]
[tab]あと、一度何かを食べたり飲んだりしたら、
[tab]その効果が切れるまでつぎの食事はできねぇかんな！
[tab]ざっとこんなもんでぃ！
[wait][clear][end]

msg_112:
[color(yellow)]板さん[color(white)]
[tab]そいつぁ、[var(msg_var_0)]円だぜ！
[tab]いいかい？
[choice(2)]はい
いいえ
[end_choice][clear][end]
