
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]スニークは裏切り者で、[suou]さんは単独行動。
[tab]はぁ～どちらもまとまりきれてないねぇ。
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]敵の罠にはまるなんて、カッコ悪いよね。
[tab]でもあんな話、誰も信じなきゃいいのになぁ～
[tab]そしたらさぁ、新世塾の計画も失敗でしょ？
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]マーヤ、腰でも痛いの？
[tab]早く治して行こう。
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab][tatsuya]君も健気だよねぇ。
[tab]マーヤはどうなの？
[tab]悪い気はしてないんでしょ？
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]本丸公園って言えば、マーヤ知ってる？
[tab]あそこでデートしたカップルは、
[tab]必ず別れちゃうんだってよ。気を付けてねぇ～
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]あんま死ぬとか言わないでよね。
[tab]…私だって不安なんだからね。
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]…私情を優先してしまった。
[tab]申し訳ない。
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]ＪＯＫＥＲ事件の後にこの報道だ。
[tab]心に不安がある以上、人々はこれを受け入れ、
[tab]全て信じてしまうのだろうな。
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]天野君、具合でも悪いのかい？
[tab]さぁ、早く治してもらって。
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]が君の事をあれ程想っていたなんて。
[tab]…ん？[tab]あれは「向こう側」の[tatsuya]だから、
[tab]僕の弟ではない…あれ、でも[tatsuya]は弟だぞ？
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]アメノトリフネ浮上と共に現れた城か。
[tab]やはり歴史にある珠閒瑠城と関係があるのか？
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]…父さん、母さん、行ってくるよ。
[tab][tatsuya]の事は心配しないでくれ。
[tab]僕が付いてるから大丈夫だよ。
[wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]行動を共にしていても、それぞれ目的や考え方は
[tab]違うってこった。別に[suou]を責めやしねぇよ。
[tab]…結局は皆、自分が大事だしな。
[wait][clear][end]

msg_14:
[color(yellow)]パオフゥ[color(white)]
[tab]ワンロン占いブームも古代史ブームも
[tab]連中の手による下準備だったというわけだ。
[tab]…こりゃ一本取られたねぇ。
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]どうした、天野？
[tab]お前、頭でも悪いのか？
[tab]へへへ、早く治してもらえよ。
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]水の一念岩をも通すって言ったってよぉ、
[tab]世界を変えるってのはすげぇ話だよな。
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]一人の男にそこまで想われるとは、
[tab]女冥利に尽きるってもんだぞ。
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]珠閒瑠城と言えば悪政をしいた澄丸[tab]清忠の城…
[tab]本人は最近の古代史ブームで見直されていたが、
[tab]連中はなんでこんな城を出してきたんだ？
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab][tatsuya]、死んだら負けだぜ？
[tab]何かを成しても、死んじまったらおしまいだ。
[tab]…それじゃ悲しいだろ？
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]いいな、お前は生きて戻るんだぞ。
[wait][clear][end]

msg_21:
[color(yellow)]南条[color(white)]
[tab]…同床異夢。
[tab]個人の集まりが組織を構成する以上、
[tab]ある程度のばらつきは仕方のない事ですか…
[wait][clear][end]

msg_22:
[color(yellow)]南条[color(white)]
[tab]新世塾の罠にはまった事を後悔しても仕方がない。
[tab]今は、もっと先の事を考えるべきでしょう。
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]どうしたんですかＭｓ．天野？
[tab]ここに御用ですか？
[wait][clear][end]

msg_24:
[color(yellow)]エリー[color(white)]
[tab]今回の件、納得は出来ないのですが、
[tab]個人の集まりが組織である以上、
[tab]仕方のない事ですわ。
[wait][clear][end]

msg_25:
[color(yellow)]エリー[color(white)]
[tab]新世塾のＴｒａｐにはまった事を後悔しても
[tab]仕方ありませんわ。
[tab]もっと先の事を考えましょう。
[wait][clear][end]

msg_26:
[color(yellow)]エリー[color(white)]
[tab]どうしたのですかＭｓ．Ａｍａｎｏ？
[tab]こちらに何か御用なのですか？
[wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]…俺はどこも悪くない。
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]…みんな、下らない話が好きだな。
[tab]今はそれ所じゃない筈なのに。
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]珠閒瑠城…向こうではただの公園だったが…
[tab]やはり、前とは違うんだな。
[wait][clear][end]

msg_30:
[color(yellow)][tatsuya][color(white)]
[tab]生きては戻れないかも知れない。
[tab]でも、俺は後悔しないよ…舞耶姉。
[wait][clear][end]

msg_31:
[color(yellow)]おじいさん[color(white)]
[tab]最近の若いのは何じゃ？[tab]ぽじてぃぶしんきんぐ？
[tab]見た目だけではなく言う事まで同じなのか？
[tab]自立出来てないのじゃろうな。あ～情けない！
[wait][clear][end]

msg_32:
[color(yellow)]おじいさん[color(white)]
[tab]最近はニュースもあてにならんようじゃな。
[tab]この街の下に、船があるじゃと？
[tab]船は海にあるもんじゃ。何ゆえ地下にある！
[wait][clear][end]

msg_33:
[color(yellow)]おじいさん[color(white)]
[tab]はぁ～街中大混乱。外に出るのは怖い怖い。
[tab]追いつめられた人間は何をするか分からんからな！
[tab]…そこへ行くと富先生は立派なもんじゃて。
[wait][clear][end]

msg_34:
[color(yellow)]おじいさん[color(white)]
[tab]さすがの富先生も自分の背骨は揉めんか～
[tab]しかし、逃げれなかったとはいえ、
[tab]あの強気の姿勢は大したもんじゃ。…うん。
[wait][clear][end]

msg_35:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[tab]うちの嫁はいい嫁なんじゃが…
[tab]物忘れがひどくてのぉ。
[tab]何でもわしのせいにするのは反則じゃな。
[wait][clear][end]

msg_36:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[tab]…なんじゃあ？
[tab]わしにまだ何か用か？
[wait][clear][end]

msg_37:
[tab]何の用じゃ？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_38:
ナガセタイチ
[end]

msg_39:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[tab]はぁ～～～？
[tab]誰のこと言ってるんじゃ？
[wait][clear][end]

msg_40:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[tab]あぁ！？
[tab]なんでわしの名前を知っとるんじゃ？
[tab]…嫁が捜してるとな！？
[wait][clear][end]

msg_41:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[tab]…そうか、そうか。
[tab]心配させていたようじゃのぉ。
[tab]でも、ここに来る事は言ってあるはずじゃが？
[wait][clear][end]

msg_42:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[tab]まぁいいか、家に連絡しとくかなぁ。
[tab]ほんと、うちの嫁はいい嫁じゃ。
[tab]…物忘れのひどさが玉に傷じゃがな。
[wait][clear][end]

msg_43:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[end]

msg_44:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[end]

msg_45:
[tab]富先生が何でも治すっちゅう噂は、本当じゃのぉ。
[tab]最近では物忘れもせんし、その上無かった事まで
[tab]思い出せる様になったんじゃのぉ。
[wait][clear][end]

msg_46:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[end]

msg_47:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[end]

msg_48:
[tab]ん～わしが思い出した通りじゃのぉ。
[tab]あんたにだけ教えてやろうか？
[tab]この街はのぉ、…実は飛ぶんじゃよ。
[wait][clear][end]

msg_49:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[end]

msg_50:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[end]

msg_51:
[tab]ほれ、わしが言った通りじゃろぉ？
[tab]…などと喜んでいる場合じゃないのぉ。
[tab]…認知症のままでいた方が幸せだったかも？
[wait][clear][end]

msg_52:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[end]

msg_53:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[end]

msg_54:
[tab]幸せなんてのは人それぞれ違うもんじゃ。
[tab]しかし、それも生きていてこそわかる事…[delay(30)]
[tab]すべての人が…[delay(15)]幸せに…[delay(15)]なれる……[delay(15)]と………
[wait][clear][end]

msg_55:
[color(yellow)]認知症の治った？[tab]おじいさん[color(white)]
[end]

msg_56:
[color(yellow)]ナガセ[tab]タイチ[color(white)]
[end]

msg_57:
[tab]…はぁ！！
[tab]爺ちゃん、ちょっと寝ちゃってたのぉ。
[wait][clear][end]

msg_58:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]ゴールドフィンガ～！！[delay(30)]
[tab]ようこそ富永カイロプラクティックへ。
[tab]私が黄金の指を持つ男、Ｍｒ．富だ。
[choice(4)]回復してもらう
話をする
なにもしない
店の外に出る
[end_choice][clear][end]

msg_59:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]ゴ～～～ルドッフィンガ～！！[delay(30)]
[tab]何故だ！？[tab]君の顔が見れてとてもうれしいな！
[tab]うん、今日はサービスさせてもらうぞ！
[choice(4)]回復してもらう
話をする
なにもしない
店の外に出る
[end_choice][clear][end]

msg_60:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]何が聞きたいのかね？
[choice(3)]世間話をする
回復の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_61:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]うーむ、最近は記憶障害を訴える者が多いな。
[tab]何か妙な感じだが、恐らく原因は尾骨のズレ！
[tab]…私の尾骨もズレているのか？
[wait][clear][end]

msg_62:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]し、新世塾が、…何だというのだぁ！
[tab]あ、あのような連中など、
[tab]我がゴールドフィンガーの敵ではない…
[wait][clear][end]

msg_63:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]我がゴールドフィンガーに治せぬもの無し！
[tab]恐れるもの無し！[tab]年中無休、お休み無し！
[tab]何があろうと、私は患者を見捨てたりしないぞ。
[wait][clear][end]

msg_64:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]我がゴールドフィンガーに治せぬもの無し！
[tab]…しかーし、自分のギックリ腰は治せなかった。
[tab]じ、実は逃げたくても逃げられなかったのだ！！
[wait][clear][end]

msg_65:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]他に何かあるかね？
[tab]我がゴールドフィンガーをもってすれば、
[tab]問題は全て解決だぞ！？
[choice(4)]回復してもらう
話をする
なにもしない
店の外に出る
[end_choice][clear][end]

msg_66:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]何が聞きたいのかね？
[choice(3)]世間話をする
回復の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_67:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]疲れたらまた来るがよい。
[tab]我が黄金の指に治せぬもの無し！
[tab]ゴールドフィンガ～！！
[wait][clear][end]

msg_68:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]アム？[tab]だがしかし皆健康なようだぞ。
[tab]過ぎたるは、及ばざるが如し。
[tab]治療の必要はなかろう。
[wait][clear][end]

msg_69:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]おお、これは酷い。背骨が著しく歪んでおる。
[tab]確かに矯正が必要のようだな。
[tab]ちなみに治療費は３０００円ほどになるが…
[wait][clear][end]

msg_70:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]むむっ、これは…
[tab]酷い、背骨が著しく歪んでおる。
[tab]仕方ない、治療費は１５００円でいいぞ。
[wait][clear][end]

msg_71:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]治療をうけるかね？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_72:
[color(green)][tab]舞耶達は回復した。[color(white)][wait][clear][end]

msg_73:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]ムムムム！！
[tab]残念だが代金が足りぬようだぞ。
[tab]これでは治療できんな。
[wait][clear][end]

msg_74:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]なんと…
[tab]我がゴールドフィンガーにかかれば、
[tab]その傷も癒えようというのに…[delay(15)]無理はいかんぞ。
[wait][clear][end]

msg_75:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]承知した。しからば…マジックにて印をつけて…
[tab]いくぞ！！[tab]伝家の宝刀！！
[tab]ゴールドフィンガァーーー！！！
[wait][clear][end]

msg_76:
ＭＢＩＴ[tab]ＨＩ[tab]ＮＡＮＪＯＴＯＵＪＯ
南条出現噂：広げた
びっとお～んッ！！
[wait][clear][end]

msg_77:
ＭＢＩＴ[tab]ＡＩＳ[tab]５４
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_78:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_79:
ＥＢＩＴ[tab]Ｅ００７７
「スマイル平坂クリア・克哉離脱」
びっとお～んッ！！
[wait][clear][end]

msg_80:
ＥＢＩＴ[tab]Ｅ００７Ａ
「野音クリア・克哉編入」
びっとお～んッ！！
[wait][clear][end]

msg_81:
ＥＢＩＴ[tab]Ｅ００７Ｂ
「竜蔵と殺し屋の電話を盗聴」
びっとお～んッ！！
[wait][clear][end]

msg_82:
ＥＢＩＴ[tab]Ｅ００７Ｆ
「廃工場クリア・パオフゥ編入」
びっとお～んッ！！
[wait][clear][end]

msg_83:
ＥＢＩＴ[tab]Ｅ００８Ｃ
「海底遺跡クリア」
びっとお～んッ！！
[wait][clear][end]

msg_84:
ＥＢＩＴ[tab]Ｅ００９Ｆ
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお～んッ！！
[wait][clear][end]

msg_85:
ＥＢＩＴ[tab]Ｅ００ＡＦ
「アメノトリフネクリア」
びっとお～んッ！！
[wait][clear][end]

msg_86:
ＥＢＩＴ[tab]Ｅ００Ｂ８
「珠「瑠城クリア」
びっとお～んッ！！
[wait][clear][end]

msg_87:
[color(yellow)]Ｍｒ．富[color(white)]
[tab]よし、「回復」についてだな。
[wait][clear][color(yellow)]Ｍｒ．富[color(white)]
[tab]当店で「回復してもらう」を選ぶと
[tab]我じきじきのマッサージによって「ＨＰ」と「ＳＰ」のほか
[tab]「猛毒」などのステータス異常も含め回復してやるぞ。
[wait][clear][color(yellow)]Ｍｒ．富[color(white)]
[tab]ちなみに、当店はグループで来たら
[tab]全員を治療することになっている、決まりでな。
[tab]安くはないが、薬に頼るよりは金はかからんはずだぞ。
[wait][clear][color(yellow)]Ｍｒ．富[color(white)]
[tab]まあ、こんなところだな。
[tab]我がゴールドフィンガーを体感したくなったかね？
[wait][clear][end]
