function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_304d, 127);
    levelFootstepSet(sfx_15);
    envTriggerSet(DOORBOX, 131, 1, line, coll_14);
    bitGet(var_0, MBIT_HSATOMI_HATURAITEN);
    bnz(var_0, label_9);
    cameraSet(southeast, 1001, 0, -1427);
    b(label_a);
  label_9:
    cameraSet(northeast, 1125, 0, -505);
  label_a:
    li(var_0, 0);
    li(var_1, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, tatsuya);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_1b);
    li(var_0, 0);
    b(label_20);
  label_1b:
    ref_1b = dialogAlloc();
    ref_1c = msgShow(msg_0);
/***************************************
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear]
***************************************/
    wait(ref_1c);
    dialogFree(ref_1b);
    b(label_20);
  label_20:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_25);
    bitGet(var_0, EBIT_E008C);
    bez(var_0, label_2b);
    bnz(var_0, label_27);
  label_25:
    partyMemberCheck(var_0, tatsuya);
    bez(var_0, label_2b);
  label_27:
    ref_27 = spriteLoad(sprite_18);
    wait(ref_27);
    unitSpawn(tatsuya, sprite_18, 1240, 0, -980, north, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
  label_2b:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_3e);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_36);
    partyMemberCheck(var_0, elly);
    bez(var_0, label_3e);
    ref_31 = spriteLoad(sprite_23);
    wait(ref_31);
    unitSpawn(elly, sprite_23, 360, 0, -450, west, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
    b(label_3e);
  label_36:
    bne(var_0, 1, label_3e);
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_3e);
    ref_39 = spriteLoad(sprite_1f);
    wait(ref_39);
    unitSpawn(nanjo, sprite_1f, 725, 0, -1450, north, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
    b(label_3e);
  label_3e:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_44);
    ref_40 = spriteLoad(sprite_6);
    wait(ref_40);
    unitSpawn(ulala, sprite_6, 950, 0, -1150, east, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_44:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_4a);
    ref_46 = spriteLoad(sprite_d);
    wait(ref_46);
    unitSpawn(katsuya, sprite_d, 650, 0, -760, south, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_4a:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_50);
    ref_4c = spriteLoad(sprite_13);
    wait(ref_4c);
    unitSpawn(baofu, sprite_13, 50, 0, -610, east, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_50:
    ref_50 = spriteLoad(sprite_8f);
    wait(ref_50);
    unitSpawn(shopkeeper, sprite_8f, 1179, 0, -268, north, none);
    envTriggerSet(SHOP, 224, 1, line, coll_0);
    envTriggerSet(SHOP, 224, 1, line, coll_1);
    envTriggerSet(SHOP, 112, 1, line, coll_2);
    envTriggerSet(SHOP, 112, 1, line, coll_3);
    envTriggerSet(SHOP, 56, 1, line, coll_4);
    envTriggerSet(SHOP, 56, 1, line, coll_5);
    ref_59 = spriteLoad(sprite_c8);
    wait(ref_59);
    unitSpawn(npc1, sprite_c8, 540, 0, -990, east, none);
    unitPalette(npc1, 1);
    unitTriggerSet(npc1, SARARII, 255, 1);
    ref_5e = spriteLoad(sprite_bb);
    wait(ref_5e);
    unitSpawn(npc2, sprite_bb, 830, 0, -50, north, none);
    unitPalette(npc2, 1);
    unitTriggerSet(npc2, KAOIRO, 255, 1);
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_66);
    b(label_6c);
  label_66:
    bne(var_0, 1, label_6c);
    ref_67 = spriteLoad(sprite_a3);
    wait(ref_67);
    unitSpawn(npc3, sprite_a3, 420, 0, -300, west, none);
    unitTriggerSet(npc3, MAN3, 255, 1);
    b(label_6c);
  label_6c:
    ref_6c = spriteLoad(sprite_0);
    wait(ref_6c);
    ref_6e = spriteLoad(sprite_2);
    wait(ref_6e);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_d8);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_c8);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_b8);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_a8);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_98);
    unitFacePlayer(ulala);
    ref_86 = bustupLoad(bustup_1d);
    bustupWait(ref_86);
    ref_88 = bustupAlloc(ref_86, left, rgb(0,0,0));
    bustupFade(ref_88, rgb(128,0,0), 30);
    ref_8a = dialogAlloc();
    ref_8b = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]うわぁ、みんな四字熟語使ってるよぉ！？
[tab]あぁどうしようかマーヤぁ。
[tab]私達も何か言わなきゃ。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_8b);
    ref_8e = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]えーと、…ええい、国士無双うららの拳！！
[tab]ホレ、マーヤも一発かましてやんな！
[tab][delay(30)]…え、立直一発！？[tab]…って…あぁ～
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_8e);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_8a);
    ref_93 = bustupFade(ref_88, rgb(0,0,0), 10);
    bustupWait(ref_93);
    bustupFree(ref_88);
    unitRestoreFacing(ulala);
    b(label_e8);
  label_98:
    unitFacePlayer(ulala);
    ref_99 = bustupLoad(bustup_1d);
    bustupWait(ref_99);
    ref_9b = bustupAlloc(ref_99, left, rgb(0,0,0));
    bustupFade(ref_9b, rgb(128,0,0), 30);
    ref_9d = dialogAlloc();
    ref_9e = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ねぇマーヤ…
[tab]この混乱って新世塾が悪いんだよね？
[tab]私達は…悪くないよね？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_9e);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_9d);
    ref_a3 = bustupFade(ref_9b, rgb(0,0,0), 10);
    bustupWait(ref_a3);
    bustupFree(ref_9b);
    unitRestoreFacing(ulala);
    b(label_e8);
  label_a8:
    unitFacePlayer(ulala);
    ref_a9 = bustupLoad(bustup_17);
    bustupWait(ref_a9);
    ref_ab = bustupAlloc(ref_a9, left, rgb(0,0,0));
    bustupFade(ref_ab, rgb(128,0,0), 30);
    ref_ad = dialogAlloc();
    ref_ae = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あの子が自分に酔ってるって？[tab]ふ～ん。
[tab]思春期でもないのに自分に酔ってるオジサンが
[tab]そんなこと言ってもねぇ～説得力無いわねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_ae);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ad);
    ref_b3 = bustupFade(ref_ab, rgb(0,0,0), 10);
    bustupWait(ref_b3);
    bustupFree(ref_ab);
    unitRestoreFacing(ulala);
    b(label_e8);
  label_b8:
    unitFacePlayer(ulala);
    ref_b9 = bustupLoad(bustup_17);
    bustupWait(ref_b9);
    ref_bb = bustupAlloc(ref_b9, left, rgb(0,0,0));
    bustupFade(ref_bb, rgb(128,0,0), 30);
    ref_bd = dialogAlloc();
    ref_be = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]う～ん、「向こう側」の世界でも
[tab]サトミタダシは人気あったのかな？
[tab]聞いてみよ～よ。ねぇマーヤ。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_be);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_bd);
    ref_c3 = bustupFade(ref_bb, rgb(0,0,0), 10);
    bustupWait(ref_c3);
    bustupFree(ref_bb);
    unitRestoreFacing(ulala);
    b(label_e8);
  label_c8:
    unitFacePlayer(ulala);
    ref_c9 = bustupLoad(bustup_17);
    bustupWait(ref_c9);
    ref_cb = bustupAlloc(ref_c9, left, rgb(0,0,0));
    bustupFade(ref_cb, rgb(128,0,0), 30);
    ref_cd = dialogAlloc();
    ref_ce = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]どうマーヤ、買物は終了？
[tab]準備は出来た？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_ce);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_cd);
    ref_d3 = bustupFade(ref_cb, rgb(0,0,0), 10);
    bustupWait(ref_d3);
    bustupFree(ref_cb);
    unitRestoreFacing(ulala);
    b(label_e8);
  label_d8:
    unitFacePlayer(ulala);
    ref_d9 = bustupLoad(bustup_1b);
    bustupWait(ref_d9);
    ref_db = bustupAlloc(ref_d9, left, rgb(0,0,0));
    bustupFade(ref_db, rgb(128,0,0), 30);
    ref_dd = dialogAlloc();
    ref_de = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]もしもよ、このアメノトリフネが
[tab]飛ぶのを止めたらどうなんの！？
[tab]もしかして…墜落！？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1f, 1);
    wait(ref_de);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_dd);
    ref_e3 = bustupFade(ref_db, rgb(0,0,0), 10);
    bustupWait(ref_e3);
    bustupFree(ref_db);
    unitRestoreFacing(ulala);
    b(label_e8);
  label_e8:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_15c);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_14c);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_13c);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_115);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_105);
    unitFacePlayer(katsuya);
    ref_f6 = bustupLoad(bustup_27);
    bustupWait(ref_f6);
    ref_f8 = bustupAlloc(ref_f6, left, rgb(0,0,0));
    bustupFade(ref_f8, rgb(128,0,0), 30);
    ref_fa = dialogAlloc();
    ref_fb = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]…申し訳ない。滅私奉公すべき立場の者が
[tab]取るべき行動ではなかった。
[tab]心から反省している。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_fb);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_fa);
    ref_100 = bustupFade(ref_f8, rgb(0,0,0), 10);
    bustupWait(ref_100);
    bustupFree(ref_f8);
    unitRestoreFacing(katsuya);
    b(label_16c);
  label_105:
    unitFacePlayer(katsuya);
    ref_106 = bustupLoad(bustup_21);
    bustupWait(ref_106);
    ref_108 = bustupAlloc(ref_106, left, rgb(0,0,0));
    bustupFade(ref_108, rgb(128,0,0), 30);
    ref_10a = dialogAlloc();
    ref_10b = msgShow(msg_9);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]確かに原因は我々かも知れないが、
[tab]そうなるよう仕向けたのは新世塾だ。
[tab]…落ち込んでいる暇は無いぞ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_10b);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_10a);
    ref_110 = bustupFade(ref_108, rgb(0,0,0), 10);
    bustupWait(ref_110);
    bustupFree(ref_108);
    unitRestoreFacing(katsuya);
    b(label_16c);
  label_115:
    bitGet(var_0, EBIT_E0096);
    bne(var_0, 0, label_127);
    unitFacePlayer(katsuya);
    ref_118 = bustupLoad(bustup_27);
    bustupWait(ref_118);
    ref_11a = bustupAlloc(ref_118, left, rgb(0,0,0));
    bustupFade(ref_11a, rgb(128,0,0), 30);
    ref_11c = dialogAlloc();
    ref_11d = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab][tatsuya]…どうして僕を避けるんだ。
[tab]僕の知らぬ間に何があったと言うんだ！？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_11d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_11c);
    ref_122 = bustupFade(ref_11a, rgb(0,0,0), 10);
    bustupWait(ref_122);
    bustupFree(ref_11a);
    unitRestoreFacing(katsuya);
    b(label_13b);
  label_127:
    bne(var_0, 1, label_13b);
    unitFacePlayer(katsuya);
    unitAnimationPlay(katsuya, animation_6, 1);
    ref_12a = bustupLoad(bustup_27);
    bustupWait(ref_12a);
    ref_12c = bustupAlloc(ref_12a, left, rgb(0,0,0));
    bustupFade(ref_12c, rgb(128,0,0), 30);
    ref_12e = dialogAlloc();
    ref_12f = msgShow(msg_11);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]違う世界から来た…
[tab]でも、「向こう側」とやらでも
[tab]僕の弟だったのだろう…？
[wait][clear]
***************************************/
    wait(ref_12f);
    unitAnimationPlay(katsuya, animation_1f, 1);
    ref_132 = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ならば「こちら側」でも僕の弟だ…！
[tab]兄には弟を守る義務がある。
[tab]世界の違いなど、関係あるものか…
[wait][clear]
***************************************/
    wait(ref_132);
    dialogFree(ref_12e);
    ref_135 = bustupFade(ref_12c, rgb(0,0,0), 10);
    bustupWait(ref_135);
    bustupFree(ref_12c);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitRestoreFacing(katsuya);
    b(label_13b);
  label_13b:
    b(label_16c);
  label_13c:
    unitFacePlayer(katsuya);
    ref_13d = bustupLoad(bustup_21);
    bustupWait(ref_13d);
    ref_13f = bustupAlloc(ref_13d, left, rgb(0,0,0));
    bustupFade(ref_13f, rgb(128,0,0), 30);
    ref_141 = dialogAlloc();
    ref_142 = msgShow(msg_13);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]「向こう側」との差は少ないようだが、
[tab]やはり大きく違う別の世界も存在するのだろうな。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_142);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_141);
    ref_147 = bustupFade(ref_13f, rgb(0,0,0), 10);
    bustupWait(ref_147);
    bustupFree(ref_13f);
    unitRestoreFacing(katsuya);
    b(label_16c);
  label_14c:
    unitFacePlayer(katsuya);
    ref_14d = bustupLoad(bustup_22);
    bustupWait(ref_14d);
    ref_14f = bustupAlloc(ref_14d, left, rgb(0,0,0));
    bustupFade(ref_14f, rgb(128,0,0), 30);
    ref_151 = dialogAlloc();
    ref_152 = msgShow(msg_14);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]そんなに焦る必要はないよ天野君。
[tab]急いては事を仕損じると言うしね。
[tab]…さて、僕はどれを……
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_152);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_151);
    ref_157 = bustupFade(ref_14f, rgb(0,0,0), 10);
    bustupWait(ref_157);
    bustupFree(ref_14f);
    unitRestoreFacing(katsuya);
    b(label_16c);
  label_15c:
    unitFacePlayer(katsuya);
    ref_15d = bustupLoad(bustup_21);
    bustupWait(ref_15d);
    ref_15f = bustupAlloc(ref_15d, left, rgb(0,0,0));
    bustupFade(ref_15f, rgb(128,0,0), 30);
    ref_161 = dialogAlloc();
    ref_162 = msgShow(msg_15);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]アメノトリフネがどうなるか分からないが…
[tab]新世塾の連中が操ろうとしたんだ。
[tab]我々でも、なんとか出来るんじゃないかな？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1f, 1);
    wait(ref_162);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_161);
    ref_167 = bustupFade(ref_15f, rgb(0,0,0), 10);
    bustupWait(ref_167);
    bustupFree(ref_15f);
    unitRestoreFacing(katsuya);
    b(label_16c);
  label_16c:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_1c9);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1b9);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_1a9);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_199);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_189);
    unitFacePlayer(baofu);
    ref_17a = bustupLoad(bustup_31);
    bustupWait(ref_17a);
    ref_17c = bustupAlloc(ref_17a, left, rgb(0,0,0));
    bustupFade(ref_17c, rgb(128,0,0), 30);
    ref_17e = dialogAlloc();
    ref_17f = msgShow(msg_16);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab][suou]に失望か…南条らしいねぇ。
[tab]まぁヤツにとってはそれほどの好機だったんだろ？
[tab]千載一遇だったってワケだよ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_17f);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_17e);
    ref_184 = bustupFade(ref_17c, rgb(0,0,0), 10);
    bustupWait(ref_184);
    bustupFree(ref_17c);
    unitRestoreFacing(baofu);
    b(label_1d9);
  label_189:
    unitFacePlayer(baofu);
    ref_18a = bustupLoad(bustup_2d);
    bustupWait(ref_18a);
    ref_18c = bustupAlloc(ref_18a, left, rgb(0,0,0));
    bustupFade(ref_18c, rgb(128,0,0), 30);
    ref_18e = dialogAlloc();
    ref_18f = msgShow(msg_17);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢の気持ちもわからないではないが、
[tab]俺達が混乱の原因だな。
[tab]連中の方が一枚上手だったってワケだ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_18f);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_18e);
    ref_194 = bustupFade(ref_18c, rgb(0,0,0), 10);
    bustupWait(ref_194);
    bustupFree(ref_18c);
    unitRestoreFacing(baofu);
    b(label_1d9);
  label_199:
    unitFacePlayer(baofu);
    ref_19a = bustupLoad(bustup_2d);
    bustupWait(ref_19a);
    ref_19c = bustupAlloc(ref_19a, left, rgb(0,0,0));
    bustupFade(ref_19c, rgb(128,0,0), 30);
    ref_19e = dialogAlloc();
    ref_19f = msgShow(msg_18);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]思春期は自分の世界にこもりがちだからなぁ。
[tab]案外、自分のちょっとした不幸に
[tab]酔ってるだけかもな？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_19f);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_19e);
    ref_1a4 = bustupFade(ref_19c, rgb(0,0,0), 10);
    bustupWait(ref_1a4);
    bustupFree(ref_19c);
    unitRestoreFacing(baofu);
    b(label_1d9);
  label_1a9:
    unitFacePlayer(baofu);
    ref_1aa = bustupLoad(bustup_2d);
    bustupWait(ref_1aa);
    ref_1ac = bustupAlloc(ref_1aa, left, rgb(0,0,0));
    bustupFade(ref_1ac, rgb(128,0,0), 30);
    ref_1ae = dialogAlloc();
    ref_1af = msgShow(msg_19);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]学生時代は結構ＳＦ小説とか読んだからなぁ。
[tab]平行宇宙…パラレルワールド…
[tab]なかなか懐かしい響きだぜ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1af);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1ae);
    ref_1b4 = bustupFade(ref_1ac, rgb(0,0,0), 10);
    bustupWait(ref_1b4);
    bustupFree(ref_1ac);
    unitRestoreFacing(baofu);
    b(label_1d9);
  label_1b9:
    unitFacePlayer(baofu);
    ref_1ba = bustupLoad(bustup_2d);
    bustupWait(ref_1ba);
    ref_1bc = bustupAlloc(ref_1ba, left, rgb(0,0,0));
    bustupFade(ref_1bc, rgb(128,0,0), 30);
    ref_1be = dialogAlloc();
    ref_1bf = msgShow(msg_20);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]言ってる事はもっともだが…
[tab][suou]のヤツ、なんか南条みてぇになったな？
[tab]俺の気のせいか？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1bf);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1be);
    ref_1c4 = bustupFade(ref_1bc, rgb(0,0,0), 10);
    bustupWait(ref_1c4);
    bustupFree(ref_1bc);
    unitRestoreFacing(baofu);
    b(label_1d9);
  label_1c9:
    unitFacePlayer(baofu);
    ref_1ca = bustupLoad(bustup_2d);
    bustupWait(ref_1ca);
    ref_1cc = bustupAlloc(ref_1ca, left, rgb(0,0,0));
    bustupFade(ref_1cc, rgb(128,0,0), 30);
    ref_1ce = dialogAlloc();
    ref_1cf = msgShow(msg_21);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]アメノトリフネ、浮いたまんまだな。
[tab]やっぱあの野郎を倒すまでは、このまんまか？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1cf);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1ce);
    ref_1d4 = bustupFade(ref_1cc, rgb(0,0,0), 10);
    bustupWait(ref_1d4);
    bustupFree(ref_1cc);
    unitRestoreFacing(baofu);
    b(label_1d9);
  label_1d9:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_200);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_1f0);
    unitFacePlayer(nanjo);
    ref_1e1 = bustupLoad(bustup_3b);
    bustupWait(ref_1e1);
    ref_1e3 = bustupAlloc(ref_1e1, left, rgb(0,0,0));
    bustupFade(ref_1e3, rgb(128,0,0), 30);
    ref_1e5 = dialogAlloc();
    ref_1e6 = msgShow(msg_22);
/***************************************
[color(yellow)]南条[color(white)]
[tab]残念ながら、今回の[suou]巡査部長の行動には
[tab]軽い失望を感じ得ません。
[tab]軽挙妄動…身にしみる言葉です。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_1e6);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1e5);
    ref_1eb = bustupFade(ref_1e3, rgb(0,0,0), 10);
    bustupWait(ref_1eb);
    bustupFree(ref_1e3);
    unitRestoreFacing(nanjo);
    b(label_210);
  label_1f0:
    unitFacePlayer(nanjo);
    ref_1f1 = bustupLoad(bustup_3b);
    bustupWait(ref_1f1);
    ref_1f3 = bustupAlloc(ref_1f1, left, rgb(0,0,0));
    bustupFade(ref_1f3, rgb(128,0,0), 30);
    ref_1f5 = dialogAlloc();
    ref_1f6 = msgShow(msg_23);
/***************************************
[color(yellow)]南条[color(white)]
[tab]…騙した方が悪いのか、騙された方が悪いのか？
[tab]どちらの側に属するかで見方は変わる。
[tab]自分達の非、認めたくはないですね。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_1f6);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1f5);
    ref_1fb = bustupFade(ref_1f3, rgb(0,0,0), 10);
    bustupWait(ref_1fb);
    bustupFree(ref_1f3);
    unitRestoreFacing(nanjo);
    b(label_210);
  label_200:
    unitFacePlayer(nanjo);
    ref_201 = bustupLoad(bustup_36);
    bustupWait(ref_201);
    ref_203 = bustupAlloc(ref_201, left, rgb(0,0,0));
    bustupFade(ref_203, rgb(128,0,0), 30);
    ref_205 = dialogAlloc();
    ref_206 = msgShow(msg_24);
/***************************************
[color(yellow)]南条[color(white)]
[tab][suou]…か。
[tab]俺達の仲間に…あいつに似た感じがするな…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_206);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_205);
    ref_20b = bustupFade(ref_203, rgb(0,0,0), 10);
    bustupWait(ref_20b);
    bustupFree(ref_203);
    unitRestoreFacing(nanjo);
    b(label_210);
  label_210:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_237);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_227);
    unitFacePlayer(elly);
    ref_218 = bustupLoad(bustup_3d);
    bustupWait(ref_218);
    ref_21a = bustupAlloc(ref_218, left, rgb(0,0,0));
    bustupFade(ref_21a, rgb(128,0,0), 30);
    ref_21c = dialogAlloc();
    ref_21d = msgShow(msg_25);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｋｅｉは今回のＭｒ．Ｋａｔｕｙａの行動に
[tab]軽い失望を感じているようです。
[tab]軽挙妄動…とかいってましたわ。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_21d);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_21c);
    ref_222 = bustupFade(ref_21a, rgb(0,0,0), 10);
    bustupWait(ref_222);
    bustupFree(ref_21a);
    unitRestoreFacing(elly);
    b(label_247);
  label_227:
    unitFacePlayer(elly);
    ref_228 = bustupLoad(bustup_3d);
    bustupWait(ref_228);
    ref_22a = bustupAlloc(ref_228, left, rgb(0,0,0));
    bustupFade(ref_22a, rgb(128,0,0), 30);
    ref_22c = dialogAlloc();
    ref_22d = msgShow(msg_26);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]噂…言霊のＰｏｗｅｒを理解出来ていなかった事。
[tab]これが原因ですわ。
[tab]Ｂｕｔもう同じ手には乗りません。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_22d);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_22c);
    ref_232 = bustupFade(ref_22a, rgb(0,0,0), 10);
    bustupWait(ref_232);
    bustupFree(ref_22a);
    unitRestoreFacing(elly);
    b(label_247);
  label_237:
    unitFacePlayer(elly);
    ref_238 = bustupLoad(bustup_3e);
    bustupWait(ref_238);
    ref_23a = bustupAlloc(ref_238, left, rgb(0,0,0));
    bustupFade(ref_23a, rgb(128,0,0), 30);
    ref_23c = dialogAlloc();
    ref_23d = msgShow(msg_27);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]あのＣｏｏｌｂｏｙ…
[tab]私たちがよく知る人と、
[tab]同じＦｅｅｌｉｎｇがしますわ…
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_23d);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_23c);
    ref_242 = bustupFade(ref_23a, rgb(0,0,0), 10);
    bustupWait(ref_242);
    bustupFree(ref_23a);
    unitRestoreFacing(elly);
    b(label_247);
  label_247:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_283);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_273);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_263);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_252);
  label_252:
    unitFacePlayer(tatsuya);
    ref_253 = bustupLoad(bustup_10);
    bustupWait(ref_253);
    ref_255 = bustupAlloc(ref_253, right, rgb(0,0,0));
    bustupFade(ref_255, rgb(128,0,0), 30);
    bustupFlip(ref_255, true);
    ref_258 = dialogAlloc();
    ref_259 = msgShow(msg_28);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]…俺は、あの人の知る[tatsuya]じゃない。
[tab]そしてあんたも…[delay(30)]俺の知る人じゃない。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_259);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_258);
    ref_25e = bustupFade(ref_255, rgb(0,0,0), 10);
    bustupWait(ref_25e);
    bustupFree(ref_255);
    unitRestoreFacing(tatsuya);
    b(label_293);
  label_263:
    unitFacePlayer(tatsuya);
    ref_264 = bustupLoad(bustup_b);
    bustupWait(ref_264);
    ref_266 = bustupAlloc(ref_264, left, rgb(0,0,0));
    bustupFade(ref_266, rgb(128,0,0), 30);
    ref_268 = dialogAlloc();
    ref_269 = msgShow(msg_29);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]サトミタダシ…？
[tab]人気があったかは分からないが、
[tab]良く利用してはいた。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_269);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_268);
    ref_26e = bustupFade(ref_266, rgb(0,0,0), 10);
    bustupWait(ref_26e);
    bustupFree(ref_266);
    unitRestoreFacing(tatsuya);
    b(label_293);
  label_273:
    unitFacePlayer(tatsuya);
    ref_274 = bustupLoad(bustup_b);
    bustupWait(ref_274);
    ref_276 = bustupAlloc(ref_274, left, rgb(0,0,0));
    bustupFade(ref_276, rgb(128,0,0), 30);
    ref_278 = dialogAlloc();
    ref_279 = msgShow(msg_30);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]相手は今までのような雑魚じゃない…
[tab]万全を期すべきだ。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_279);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_278);
    ref_27e = bustupFade(ref_276, rgb(0,0,0), 10);
    bustupWait(ref_27e);
    bustupFree(ref_276);
    unitRestoreFacing(tatsuya);
    b(label_293);
  label_283:
    unitFacePlayer(tatsuya);
    ref_284 = bustupLoad(bustup_10);
    bustupWait(ref_284);
    ref_286 = bustupAlloc(ref_284, left, rgb(0,0,0));
    bustupFade(ref_286, rgb(128,0,0), 30);
    ref_288 = dialogAlloc();
    ref_289 = msgShow(msg_31);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]この街がどうなるのか…俺には分からない。
[tab]「向こう側」と同じ結末にはならない筈だから…
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_289);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_288);
    ref_28e = bustupFade(ref_286, rgb(0,0,0), 10);
    bustupWait(ref_28e);
    bustupFree(ref_286);
    unitRestoreFacing(tatsuya);
    b(label_293);
  label_293:
    controlEnable();
}

function SARARII()
{
    controlDisable();
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_299);
    b(label_2a6);
  label_299:
    bne(var_0, 1, label_2a6);
    bitGet(var_0, MBIT_KE_SKYMAP);
    bne(var_0, 0, label_29d);
    b(label_2a5);
  label_29d:
    bne(var_0, 1, label_2a5);
    bitGet(var_0, MBIT_SKYMAP_MIHA);
    bne(var_0, 0, label_2a2);
    b(label_2db);
    b(label_2a4);
  label_2a2:
    bne(var_0, 1, label_2a4);
    b(label_2a4);
  label_2a4:
    b(label_2a5);
  label_2a5:
    b(label_2a6);
  label_2a6:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_2d2);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2c9);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_2b5);
    unitFacePlayer(npc1);
    ref_2ad = dialogAlloc();
    ref_2ae = msgShow(msg_32);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]もーイヤ！[tab][delay(15)]もー勘弁！[delay(15)]
[tab]いつまでここでこの曲を聴きつづけねばならんの？
[tab][delay(15)]…永遠！？[tab]そんなぁぁぁ！！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2ae);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2ad);
    unitRestoreFacing(npc1);
    b(label_2e8);
  label_2b5:
    unitFacePlayer(npc1);
    ref_2b6 = dialogAlloc();
    bitGet(var_0, EBIT_E009F);
    bne(var_0, 0, label_2bd);
    ref_2b9 = msgShow(msg_33);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]アメノトリフネの話、聞きました？[tab]あれって
[tab]例の工事中の地下鉄の穴のその先にあるらしく、
[tab]忍び込む人があとを絶たないそうですよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2b9);
    b(label_2c2);
  label_2bd:
    bne(var_0, 1, label_2c2);
    ref_2be = msgShow(msg_34);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]アメノトリフネの話、聞きました？[tab]あれって
[tab]例の工事中の地下鉄の穴のその先にあるらしく、
[tab]忍び込む人が…え、あなたも行くんですか？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2be);
    b(label_2c2);
  label_2c2:
    ref_2c2 = msgShow(msg_35);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]…私ですか？[tab]私は大人しく曲を聞いてますよ。
[tab]そう、この曲を聞き続けるのです。
[tab]きっと死ぬときもここにいるでしょうよ！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2c2);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2b6);
    unitRestoreFacing(npc1);
    b(label_2e8);
  label_2c9:
    unitFacePlayer(npc1);
    ref_2ca = dialogAlloc();
    ref_2cb = msgShow(msg_36);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]シクーッ！[tab]会社が潰れてしまった！
[tab]…倒産ではなく倒壊だが…[delay(15)]
[tab]でもあの巨大リングは何？[tab]どこかで見たよな？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_25, 1);
    wait(ref_2cb);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2ca);
    unitRestoreFacing(npc1);
    b(label_2e8);
  label_2d2:
    unitFacePlayer(npc1);
    ref_2d3 = dialogAlloc();
    ref_2d4 = msgShow(msg_37);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]え？[tab]滅亡？？[tab]龍？？？
[tab]そんな事はもう、どうでもいいんです。[delay(15)]
[tab]…私はこの曲が聞けるだけで幸せでぇーす！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2d4);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2d3);
    unitRestoreFacing(npc1);
    b(label_2e8);
  label_2db:
    unitFacePlayer(npc1);
    ref_2dc = dialogAlloc();
    ref_2dd = msgShow(msg_38);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]え？[tab]あぁ、あの外人さんでしょ？
[tab]黒い噂のある世界的大金持ちの地図収集家って。
[tab]裏では、悪魔って呼ばれるんだっけ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2dd);
    ref_2e0 = msgShow(msg_39);
/***************************************
[color(yellow)]サラリーマン[color(white)]
[tab]でも、なんでここに来たんだろ？
[tab]もしかして、この店の曲が好きだとか？
[tab]…結構、趣味が合ってたりして！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2e0);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2dc);
    unitRestoreFacing(npc1);
    bitSet(MBIT_SKYMAP_MIHA);
    b(label_2e8);
  label_2e8:
    controlEnable();
}

function KAOIRO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_30c);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_303);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_2fa);
    unitFacePlayer(npc2);
    ref_2f2 = dialogAlloc();
    ref_2f3 = msgShow(msg_40);
/***************************************
[color(yellow)]顔色の悪い男[color(white)]
[tab]あぁ身が軽い、心も軽い～
[tab]やっぱり僕は穢れてたんだなぁ～
[tab]薬よさようなら～レッツ、明るい未来～
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_2f3);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2f2);
    unitRestoreFacing(npc2);
    b(label_318);
  label_2fa:
    unitFacePlayer(npc2);
    ref_2fb = dialogAlloc();
    ref_2fc = msgShow(msg_41);
/***************************************
[color(yellow)]顔色の悪い男[color(white)]
[tab]新世塾！！[tab]アメノトリフネ！！
[tab]薬に代わる新たな導き手だぁ。グフフ。
[tab]…レッツ・ポジティブシンキング！！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_2fc);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2fb);
    unitRestoreFacing(npc2);
    b(label_318);
  label_303:
    unitFacePlayer(npc2);
    ref_304 = dialogAlloc();
    ref_305 = msgShow(msg_42);
/***************************************
[color(yellow)]顔色の悪い男[color(white)]
[tab]穢れ無き人類が宙に舞い、
[tab]穢れた人類は罰を受けるのだ～！[tab]グフフ。
[tab]…レッツ・ポジティブシンキング！！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_305);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_304);
    unitRestoreFacing(npc2);
    b(label_318);
  label_30c:
    unitFacePlayer(npc2);
    ref_30d = dialogAlloc();
    ref_30e = msgShow(msg_43);
/***************************************
[color(yellow)]顔色の悪い男[color(white)]
[tab]龍がいなく…なっ…た…
[tab]…けど、レッツ・ポジティブシンキング！！
[tab]生きてる事に感謝感謝！
[wait][clear]
***************************************/
    unitAnimationHold(npc2, animation_13, -1);
    wait(ref_30e);
    ref_311 = msgShow(msg_44);
/***************************************
[color(yellow)]顔色の悪い男[color(white)]
[tab]龍よさらばぁ～
[tab]薬もさらばぁ～
[tab]僕一人でも生き続けるぞ！[tab]…グフフ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_311);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_30d);
    unitRestoreFacing(npc2);
    b(label_318);
  label_318:
    controlEnable();
}

function MAN3()
{
    controlDisable();
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_32d);
    bitGet(var_0, MBIT_KE_SKYMAP);
    bne(var_0, 0, label_323);
    ref_31f = call(MAPMES);
    wait(ref_31f);
    b(label_5eb);
    b(label_32c);
  label_323:
    bne(var_0, 1, label_32c);
    bitGet(var_0, MBIT_SKY_HENIHATU);
    bne(var_0, 0, label_328);
    b(label_332);
    b(label_32b);
  label_328:
    bne(var_0, 1, label_32b);
    b(label_345);
    b(label_32b);
  label_32b:
    b(label_32c);
  label_32c:
    b(label_332);
  label_32d:
    bne(var_0, 1, label_332);
    ref_32e = call(MAPMES);
    wait(ref_32e);
    b(label_5eb);
    b(label_332);
  label_332:
    unitFacePlayer(npc3);
    ref_333 = bustupLoad(bustup_75);
    bustupWait(ref_333);
    ref_335 = bustupAlloc(ref_333, right, rgb(0,0,0));
    bustupFade(ref_335, rgb(128,0,0), 30);
    ref_337 = dialogAlloc();
    ref_338 = msgShow(msg_45);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ハァー、ワタシ命カラガラ逃ゲテキタヨ。
[tab]アノばーてんサンガ注意シテクレナカッタラ、
[tab]ワタシ鳴海区ト心中ダッタネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_338);
    ref_33b = msgShow(msg_46);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ワタシ、モウオ金ニ興味無クナッタ。
[tab]今ヤ趣味ダケ、地図収集ダケガ生キ甲斐。
[tab]…トコロデ、今日ハ何ダ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_33b);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_337);
    bitSet(MBIT_MAP_ITENHATU);
    ref_341 = bustupFade(ref_335, rgb(0,0,0), 10);
    bustupWait(ref_341);
    bustupFree(ref_335);
    b(label_35d);
  label_345:
    unitFacePlayer(npc3);
    ref_346 = bustupLoad(bustup_75);
    bustupWait(ref_346);
    ref_348 = bustupAlloc(ref_346, right, rgb(0,0,0));
    bustupFade(ref_348, rgb(128,0,0), 30);
    ref_34a = dialogAlloc();
    bitGet(var_0, MBIT_MAP_ITENHATU);
    bne(var_0, 0, label_352);
    ref_34d = msgShow(msg_47);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ハァ、ワタシ命カラガラ逃ゲテキタヨ。
[tab]アノばーてんサンガ注意シテクレナカッタラ、
[tab]ワタシ鳴海区ト心中ダッタネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_34d);
    bitSet(MBIT_MAP_ITENHATU);
    b(label_357);
  label_352:
    bne(var_0, 1, label_357);
    ref_353 = msgShow(msg_48);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]アラー、キレーナオ嬢サン！
[tab]マタワタシノ所ニ来テクレタカ。ウレシイデッス。
[tab]トコロデ、今日ハ何ダ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_353);
    b(label_357);
  label_357:
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_34a);
    ref_359 = bustupFade(ref_348, rgb(0,0,0), 10);
    bustupWait(ref_359);
    bustupFree(ref_348);
    b(label_35d);
  label_35d:
    ref_35d = call(MESHYOUJI);
    wait(ref_35d);
    choiceSetResult(3);
    ref_360 = bustupLoad(bustup_1);
    bustupWait(ref_360);
    ref_362 = bustupAlloc(ref_360, center, rgb(0,0,0));
    bustupFade(ref_362, rgb(128,0,0), 30);
    bitGet(var_0, LBIT_0010);
    bne(var_0, 0, label_36b);
    ref_366 = dialogChoiceAlloc();
    ref_367 = msgShow(msg_49);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]トコロデ、今日ハ何ダ？
[choice(4)][if_all(!LBIT_0000)]依頼を受ける
話を聞きたい
説明
用はない
[end_choice][clear]
***************************************/
    wait(ref_367);
    dialogFree(ref_366);
    b(label_371);
  label_36b:
    bne(var_0, 1, label_371);
    ref_36c = dialogChoiceAlloc();
    ref_36d = msgShow(msg_50);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]トコロデ、今日ハ何ダ？
[choice(4)][if_all(!LBIT_0000)]地図を渡す
話を聞きたい
説明
用はない
[end_choice][clear]
***************************************/
    wait(ref_36d);
    dialogFree(ref_36c);
    b(label_371);
  label_371:
    ref_371 = bustupFade(ref_362, rgb(0,0,0), 10);
    bustupWait(ref_371);
    bustupFree(ref_362);
    choiceGetResult(var_0);
    beq(var_0, 0, label_387);
    beq(var_0, 1, label_5d7);
    beq(var_0, 2, label_379);
    beq(var_0, 3, label_5dc);
  label_379:
    ref_379 = bustupLoad(bustup_75);
    bustupWait(ref_379);
    ref_37b = bustupAlloc(ref_379, right, rgb(0,0,0));
    bustupFade(ref_37b, rgb(128,0,0), 30);
    ref_37d = dialogAlloc();
    ref_37e = msgShow(msg_51);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ワタシノ依頼ヲ受ケテクレタラ、依頼シタ場所の
[tab]白地図ヲ渡スヨ。ソレ持ッテルト、ソコニ入ッタ時
[tab]イツモト違ウマップガ見レルネ。
[wait][clear][color(yellow)]サラーム・ラディーン[color(white)]
[tab]歩イタコトナイ場所、灰色ニナッテルカラ
[tab]歩イテソレ消シテッテ。
[tab]消シ忘レガアルト後デ大変ダカラ、丁寧ニネ。
[wait][clear][color(yellow)]サラーム・ラディーン[color(white)]
[tab]ゼンブ消セレバ、地図ノ完成ネ。
[tab]ココニ持ッテキテクレレバ、イイ物ト交換シテアゲルヨ！
[tab]スゴクイイ物トダヨ！
[wait][clear][color(yellow)]サラーム・ラディーン[color(white)]
[tab]アーチナミニ、ソノ場所ニ入レナクナッタラ地図作成ハ
[tab]終了ネ。諦メテ未完成ノヲ持ッテキナサーイ。
[tab]何ニモアゲナイケド。
[wait][clear]
***************************************/
    wait(ref_37e);
    dialogFree(ref_37d);
    ref_381 = bustupFade(ref_37b, rgb(0,0,0), 10);
    bustupWait(ref_381);
    bustupFree(ref_37b);
    delayClear();
    delayWait(30);
    b(label_35d);
  label_387:
    bitGet(var_0, MBIT_MAPSAKUSEI);
    bnz(var_0, label_466);
    ref_389 = call(TUGIDOKOIKU);
    wait(ref_389);
    bitGet(var_0, LBIT_0012);
    bne(var_0, 0, label_38e);
    b(label_39f);
  label_38e:
    bne(var_0, 1, label_39f);
    ref_38f = bustupLoad(bustup_75);
    bustupWait(ref_38f);
    ref_391 = bustupAlloc(ref_38f, right, rgb(0,0,0));
    bustupFade(ref_391, rgb(128,0,0), 30);
    ref_393 = dialogAlloc();
    ref_394 = msgShow(msg_52);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ、ソコノ地図ハモウモラッタヨ？
[tab]今度ハ別ノ所ヲオ願イシタイネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_394);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_393);
    ref_399 = bustupFade(ref_391, rgb(0,0,0), 10);
    bustupWait(ref_399);
    bustupFree(ref_391);
    bitSet(LBIT_0000);
    b(label_5c7);
    b(label_39f);
  label_39f:
    bitGet(var_0, LBIT_0011);
    bne(var_0, 0, label_3f2);
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_3e0);
    bitGet(var_0, EBIT_E008C);
    bne(var_0, 0, label_3ce);
    bitGet(var_0, EBIT_E007A);
    bne(var_0, 0, label_3bc);
    bitGet(var_0, EBIT_E0077);
    bne(var_0, 0, label_3aa);
    b(label_3bb);
  label_3aa:
    bne(var_0, 1, label_3bb);
    ref_3ab = bustupLoad(bustup_75);
    bustupWait(ref_3ab);
    ref_3ad = bustupAlloc(ref_3ab, right, rgb(0,0,0));
    bustupFade(ref_3ad, rgb(128,0,0), 30);
    ref_3af = dialogAlloc();
    ref_3b0 = msgShow(msg_53);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ～？[tab]青葉公園～？[tab]アソコハ遠慮スルヨ。
[tab]ダッテ、公園ナンカ珍シクナイダロ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_3b0);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_3af);
    ref_3b5 = bustupFade(ref_3ad, rgb(0,0,0), 10);
    bustupWait(ref_3b5);
    bustupFree(ref_3ad);
    bitSet(LBIT_0000);
    b(label_5c7);
    b(label_3bb);
  label_3bb:
    b(label_3cd);
  label_3bc:
    bne(var_0, 1, label_3cd);
    ref_3bd = bustupLoad(bustup_75);
    bustupWait(ref_3bd);
    ref_3bf = bustupAlloc(ref_3bd, right, rgb(0,0,0));
    bustupFade(ref_3bf, rgb(128,0,0), 30);
    ref_3c1 = dialogAlloc();
    ref_3c2 = msgShow(msg_54);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]ナ～ンダ、ソンナ所カァ～
[tab]ソコノ地図ハ…イラナイヨ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_3c2);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_3c1);
    ref_3c7 = bustupFade(ref_3bf, rgb(0,0,0), 10);
    bustupWait(ref_3c7);
    bustupFree(ref_3bf);
    bitSet(LBIT_0000);
    b(label_5c7);
    b(label_3cd);
  label_3cd:
    b(label_3df);
  label_3ce:
    bne(var_0, 1, label_3df);
    ref_3cf = bustupLoad(bustup_75);
    bustupWait(ref_3cf);
    ref_3d1 = bustupAlloc(ref_3cf, right, rgb(0,0,0));
    bustupFade(ref_3d1, rgb(128,0,0), 30);
    ref_3d3 = dialogAlloc();
    ref_3d4 = msgShow(msg_55);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ、神社？[tab]興味無イナァ～
[tab]ソコノ地図ハ…イラナイヨ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_3d4);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_3d3);
    ref_3d9 = bustupFade(ref_3d1, rgb(0,0,0), 10);
    bustupWait(ref_3d9);
    bustupFree(ref_3d1);
    bitSet(LBIT_0000);
    b(label_5c7);
    b(label_3df);
  label_3df:
    b(label_3f1);
  label_3e0:
    bne(var_0, 1, label_3f1);
    ref_3e1 = bustupLoad(bustup_75);
    bustupWait(ref_3e1);
    ref_3e3 = bustupAlloc(ref_3e1, right, rgb(0,0,0));
    bustupFade(ref_3e3, rgb(128,0,0), 30);
    ref_3e5 = dialogAlloc();
    ref_3e6 = msgShow(msg_56);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ、珠閒瑠城？[tab]ア、アソコハ遠慮スルヨ。
[tab]ダッテ、殿サマノ怒リヲ買ッタラ腹切リダロ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_3e6);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_3e5);
    ref_3eb = bustupFade(ref_3e3, rgb(0,0,0), 10);
    bustupWait(ref_3eb);
    bustupFree(ref_3e3);
    bitSet(LBIT_0000);
    b(label_5c7);
    b(label_3f1);
  label_3f1:
    b(label_3f4);
  label_3f2:
    bne(var_0, 1, label_3f4);
    b(label_3f4);
  label_3f4:
    bitGet(var_0, MBIT_SKY_HENIHATU);
    bne(var_0, 0, label_408);
    ref_3f6 = bustupLoad(bustup_75);
    bustupWait(ref_3f6);
    ref_3f8 = bustupAlloc(ref_3f6, right, rgb(0,0,0));
    bustupFade(ref_3f8, rgb(128,0,0), 30);
    ref_3fa = dialogAlloc();
    ref_3fb = msgShow(msg_57);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]…ワタシ、オ金モウ飽キタ。興味無イデッス。
[tab]今ヤ地図収集ダケガ生キ甲斐。
[tab]オ嬢サン、コレカラドコ行ク？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3fb);
    ref_3fe = msgShow(msg_58);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]…[delay(10)]…[delay(10)]…[delay(1)]フム、ワタシノ知ラナイ所ダナ。
[tab]ソコ珍シイ所！[tab]ソコ調ベテクレナイカ？
[tab]オ嬢サン、ソコノ地図ヲ作ッテ来テクレ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_27, 1);
    wait(ref_3fe);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3fa);
    ref_403 = bustupFade(ref_3f8, rgb(0,0,0), 10);
    bustupWait(ref_403);
    bustupFree(ref_3f8);
    bitSet(MBIT_SKY_HENIHATU);
    b(label_417);
  label_408:
    bne(var_0, 1, label_417);
    ref_409 = bustupLoad(bustup_75);
    bustupWait(ref_409);
    ref_40b = bustupAlloc(ref_409, right, rgb(0,0,0));
    bustupFade(ref_40b, rgb(128,0,0), 30);
    ref_40d = dialogAlloc();
    ref_40e = msgShow(msg_59);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]…[delay(1)]フム、又モワタシノ知ラナイ所ダ。
[tab]オ嬢サン、ソコノ地図ヲ作ッテ来テクレ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_27, 1);
    wait(ref_40e);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_40d);
    ref_413 = bustupFade(ref_40b, rgb(0,0,0), 10);
    bustupWait(ref_413);
    bustupFree(ref_40b);
    b(label_417);
  label_417:
    choiceSetResult(1);
    ref_418 = bustupLoad(bustup_1);
    bustupWait(ref_418);
    ref_41a = bustupAlloc(ref_418, center, rgb(0,0,0));
    bustupFade(ref_41a, rgb(128,0,0), 30);
    ref_41c = dialogChoiceAlloc();
    ref_41d = msgShow(msg_60);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]地図ヲ作ッテ来テクレルカ？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_41d);
    dialogFree(ref_41c);
    ref_420 = bustupFade(ref_41a, rgb(0,0,0), 10);
    bustupWait(ref_420);
    bustupFree(ref_41a);
    choiceGetResult(var_0);
    bne(var_0, 0, label_427);
    b(label_42a);
    b(label_42a);
  label_427:
    bne(var_0, 1, label_42a);
    b(label_458);
    b(label_42a);
  label_42a:
    ref_42a = call(TOUHACHECK);
    wait(ref_42a);
    bitGet(var_0, MBIT_MAP_NOHAKUSI);
    bne(var_0, 0, label_42f);
    b(label_432);
  label_42f:
    bne(var_0, 1, label_432);
    b(label_4af);
    b(label_432);
  label_432:
    ref_432 = call(EVENTCHECK);
    wait(ref_432);
    bitSet(LBIT_0000);
    ref_435 = bustupLoad(bustup_75);
    bustupWait(ref_435);
    ref_437 = bustupAlloc(ref_435, right, rgb(0,0,0));
    bustupFade(ref_437, rgb(128,0,0), 30);
    ref_439 = dialogAlloc();
    ref_43a = msgShow(msg_61);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ソウカ！[tab]地図作ッテ来テクレルカ！
[tab]ホンットニ頼ンダヨ、オ嬢サン。
[tab]デハ、コノ白地図ヲ渡ソウ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_27, 1);
    wait(ref_43a);
    ref_43d = msgShow(msg_62);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ヒタスラ歩イテ、地図ヲ完成サセテクレ。
[tab]出来ガ良カッタラ、ワタシノ大事ナかーどト
[tab]交換シテアゲルカラネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_43d);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_439);
    ref_442 = bustupFade(ref_437, rgb(0,0,0), 10);
    bustupWait(ref_442);
    bustupFree(ref_437);
    delayClear();
    delayWait(30);
    ref_447 = call(TIZU);
    wait(ref_447);
    bne(var_2, 0, label_44f);
    ref_44a = dialogAlloc();
    ref_44b = msgShow(msg_63);
/***************************************
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear]
***************************************/
    wait(ref_44b);
    dialogFree(ref_44a);
    b(label_455);
  label_44f:
    bne(var_2, 1, label_455);
    ref_450 = dialogAlloc();
    ref_451 = msgShow(msg_64);
/***************************************
[tab][color(green)][item_with_type(item_fffe)]と
[tab][item_with_type(item_fffd)]を手に入れた。[color(white)]
[wait][clear]
***************************************/
    wait(ref_451);
    dialogFree(ref_450);
    b(label_455);
  label_455:
    delayClear();
    delayWait(30);
    b(label_5c7);
  label_458:
    ref_458 = bustupLoad(bustup_75);
    bustupWait(ref_458);
    ref_45a = bustupAlloc(ref_458, right, rgb(0,0,0));
    bustupFade(ref_45a, rgb(128,0,0), 30);
    ref_45c = dialogAlloc();
    ref_45d = msgShow(msg_65);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]…ソウカ…地図作ッテ来テクレナイノカ。
[tab]出来ガ良ケレバ珍シイかーどト交換シタノニ。
[tab]非常ニ残念デッスヨ、オ嬢サン。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_45d);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_45c);
    ref_462 = bustupFade(ref_45a, rgb(0,0,0), 10);
    bustupWait(ref_462);
    bustupFree(ref_45a);
    b(label_5c7);
  label_466:
    ref_466 = bustupLoad(bustup_75);
    bustupWait(ref_466);
    ref_468 = bustupAlloc(ref_466, right, rgb(0,0,0));
    bustupFade(ref_468, rgb(128,0,0), 30);
    ref_46a = dialogAlloc();
    ref_46b = msgShow(msg_66);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オォ、珍シイ地図ヲ持ッテ来テクレタカ！
[tab]今ヤ地図収集ダケガ生キ甲斐。
[tab]ドレドレ……
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_46b);
    dialogFree(ref_46a);
    ref_46f = bustupFade(ref_468, rgb(0,0,0), 10);
    bustupWait(ref_46f);
    bustupFree(ref_468);
    ref_472 = call(CLMAPCHECK);
    wait(ref_472);
    delayClear();
    delayWait(45);
    bitGet(var_0, MBIT_MAPKANSEI);
    bne(var_0, 0, label_49f);
    bitGet(var_0, MBIT_MAPMIKANSEI);
    bne(var_0, 0, label_489);
    ref_47a = bustupLoad(bustup_75);
    bustupWait(ref_47a);
    ref_47c = bustupAlloc(ref_47a, right, rgb(0,0,0));
    bustupFade(ref_47c, rgb(128,0,0), 30);
    ref_47e = dialogAlloc();
    ref_47f = msgShow(msg_67);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]確カニ珍シイ地図ダ…ガ…未完成ダゾ？
[tab]かーどト交換スルワケニハイカナイナァ。
[tab]…ゼヒ、完成サセテ欲シイデッス！
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_47f);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_47e);
    ref_484 = bustupFade(ref_47c, rgb(0,0,0), 10);
    bustupWait(ref_484);
    bustupFree(ref_47c);
    b(label_5c6);
    b(label_49e);
  label_489:
    bne(var_0, 1, label_49e);
    ref_48a = bustupLoad(bustup_75);
    bustupWait(ref_48a);
    ref_48c = bustupAlloc(ref_48a, right, rgb(0,0,0));
    bustupFade(ref_48c, rgb(128,0,0), 30);
    ref_48e = dialogAlloc();
    ref_48f = msgShow(msg_68);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]確カニ珍シイ地図ダ…ガ…未完成デハナァ。
[tab]かーどト交換スルワケニハイカナイデッス。
[tab]…コノ地図ハ受ケ取ッテオクケドネ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_48f);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_48e);
    ref_494 = bustupFade(ref_48c, rgb(0,0,0), 10);
    bustupWait(ref_494);
    bustupFree(ref_48c);
    bitClear(MBIT_MAPKANSEI);
    bitClear(MBIT_MAPMIKANSEI);
    bitClear(MBIT_MAPSAKUSEI);
    ref_49a = call(BITOFFALL);
    wait(ref_49a);
    b(label_5c6);
    b(label_49e);
  label_49e:
    b(label_4ae);
  label_49f:
    bne(var_0, 1, label_4ae);
    ref_4a0 = bustupLoad(bustup_75);
    bustupWait(ref_4a0);
    ref_4a2 = bustupAlloc(ref_4a0, right, rgb(0,0,0));
    bustupFade(ref_4a2, rgb(128,0,0), 30);
    ref_4a4 = dialogAlloc();
    ref_4a5 = msgShow(msg_69);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]コレハ確カニ珍シイ地図ダ！
[tab]ゼヒ、ゼヒかーどト交換サセテモラウゾ！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_27, 1);
    wait(ref_4a5);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_4a4);
    ref_4aa = bustupFade(ref_4a2, rgb(0,0,0), 10);
    bustupWait(ref_4aa);
    bustupFree(ref_4a2);
    b(label_4ae);
  label_4ae:
    b(label_4c0);
  label_4af:
    ref_4af = bustupLoad(bustup_75);
    bustupWait(ref_4af);
    ref_4b1 = bustupAlloc(ref_4af, right, rgb(0,0,0));
    bustupFade(ref_4b1, rgb(128,0,0), 30);
    ref_4b3 = dialogAlloc();
    ref_4b4 = msgShow(msg_70);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ソウカ！[tab]地図作ッテ来テクレルカ！
[tab]デハ、コノ白紙ノ地図ヲ渡ソ……
[tab]ナニ！？[tab]モウ行ッテ来タノカ？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_4b4);
    ref_4b7 = msgShow(msg_71);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ドレドレ……
[tab]コレハ確カニ珍シイ地図ダ！
[tab]ゼヒ、ゼヒかーどト交換サセテモラウゾ！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_4b7);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_4b3);
    ref_4bc = bustupFade(ref_4b1, rgb(0,0,0), 10);
    bustupWait(ref_4bc);
    bustupFree(ref_4b1);
    b(label_4c0);
  label_4c0:
    bitGet(var_1, IBIT_CMP_MAP_13);
    bitGet(var_2, IBIT_CMP_MAP_29);
    add(var_0, var_1, var_2);
    boutrange(var_0, 0, 1, label_4c5);
    b(label_4c8);
  label_4c5:
    bne(var_0, 2, label_4c8);
    b(label_4f1);
    b(label_4c8);
  label_4c8:
    bitGet(var_1, IBIT_CMP_MAP_11);
    bitGet(var_2, IBIT_CMP_MAP_2C);
    add(var_0, var_1, var_2);
    boutrange(var_0, 0, 1, label_4cd);
    b(label_4d0);
  label_4cd:
    bne(var_0, 2, label_4d0);
    b(label_518);
    b(label_4d0);
  label_4d0:
    bitGet(var_0, IBIT_CMP_MAP_0F);
    bnz(var_0, label_53c);
    bitGet(var_1, IBIT_CMP_MAP_0D);
    bitGet(var_2, IBIT_CMP_MAP_19);
    add(var_0, var_1, var_2);
    boutrange(var_0, 0, 1, label_4d7);
    b(label_4da);
  label_4d7:
    bne(var_0, 2, label_4da);
    b(label_558);
    b(label_4da);
  label_4da:
    bitGet(var_0, IBIT_CMP_MAP_0C);
    bnz(var_0, label_571);
    bitGet(var_1, IBIT_CMP_MAP_0B);
    bitGet(var_2, IBIT_CMP_MAP_2A);
    add(var_0, var_1, var_2);
    boutrange(var_0, 0, 1, label_4e1);
    b(label_4e4);
  label_4e1:
    bne(var_0, 2, label_4e4);
    b(label_588);
    b(label_4e4);
  label_4e4:
    bitGet(var_0, IBIT_CMP_MAP_09);
    bne(var_0, 0, label_4ed);
    bitGet(var_0, IBIT_CMP_MAP_08);
    bne(var_0, 0, label_4e9);
    b(label_4ec);
  label_4e9:
    bne(var_0, 1, label_4ec);
    b(label_5ad);
    b(label_4ec);
  label_4ec:
    b(label_4f0);
  label_4ed:
    bne(var_0, 1, label_4f0);
    b(label_59c);
    b(label_4f0);
  label_4f0:
    b(label_5c0);
  label_4f1:
    ref_4f1 = dialogAlloc();
    ref_4f2 = msgShow(msg_72);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット[tab]ＦＩＮＡＬ
[tab]を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4f2);
    dialogFree(ref_4f1);
    partyItemAdd(st_card, 10);
    partyItemAdd(vi_card, 10);
    partyItemAdd(dx_card, 10);
    partyItemAdd(ag_card, 10);
    partyItemAdd(lu_card, 10);
    partyItemAdd(all_card, 10);
    partyItemAdd(emperor_card, 100);
    partyItemAdd(hierophant_card, 100);
    partyItemAdd(justice_card, 100);
    partyItemAdd(priestess_card, 100);
    partyItemAdd(empress_card, 100);
    partyItemAdd(lovers_card, 100);
    partyItemAdd(sun_card, 100);
    partyItemAdd(fool_card, 3);
    bitSet(VBIT_FOOL_GET);
    partyItemAdd(healing_card, 1);
    partyItemAdd(holylight_card, 1);
    partyItemAdd(attack mirror_card, 1);
    partyItemAdd(blessing_card, 1);
    partyItemAdd(sacrifice_card, 1);
    partyItemAdd(magic mirror_card, 1);
    partyItemAdd(inferno_card, 1);
    partyItemAdd(torrent_card, 1);
    partyItemAdd(gale_card, 1);
    partyItemAdd(quake_card, 1);
    partyItemAdd(frigid_card, 1);
    partyItemAdd(thunderbolt_card, 1);
    partyItemAdd(scorching_card, 1);
    partyItemAdd(wavelength_card, 1);
    partyItemAdd(pressure_card, 1);
    partyItemAdd(nuclear_card, 1);
    bitSet(MBIT_MEND_13);
    b(label_5c0);
    b(label_5c0);
  label_518:
    ref_518 = dialogAlloc();
    ref_519 = msgShow(msg_73);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット
[tab]ＴＡＲＯＴ[tab]ＳＰＥＣＩＡＬ
[tab]を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_519);
    dialogFree(ref_518);
    partyItemAdd(magician_card, 100);
    partyItemAdd(priestess_card, 100);
    partyItemAdd(empress_card, 100);
    partyItemAdd(emperor_card, 100);
    partyItemAdd(hierophant_card, 100);
    partyItemAdd(lovers_card, 100);
    partyItemAdd(chariot_card, 100);
    partyItemAdd(strength_card, 100);
    partyItemAdd(hermit_card, 100);
    partyItemAdd(fortune_card, 100);
    partyItemAdd(justice_card, 100);
    partyItemAdd(hanged_man_card, 100);
    partyItemAdd(death_card, 100);
    partyItemAdd(temperance_card, 100);
    partyItemAdd(devil_card, 100);
    partyItemAdd(tower_card, 100);
    partyItemAdd(star_card, 100);
    partyItemAdd(moon_card, 100);
    partyItemAdd(sun_card, 100);
    partyItemAdd(judgement_card, 100);
    partyItemAdd(world_card, 100);
    partyItemAdd(fool_card, 2);
    bitSet(VBIT_FOOL_GET);
    ref_534 = call(RNDCHECK);
    wait(ref_534);
    ref_536 = call(RNDCHECK);
    wait(ref_536);
    ref_538 = call(RNDCHECK);
    wait(ref_538);
    bitSet(MBIT_MEND_11);
    b(label_5c0);
  label_53c:
    ref_53c = dialogAlloc();
    ref_53d = msgShow(msg_74);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・スキルカードセット[tab]Ｐａｒｔ２
[tab]を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_53d);
    dialogFree(ref_53c);
    partyItemAdd(emperor_card, 100);
    partyItemAdd(hierophant_card, 100);
    partyItemAdd(justice_card, 100);
    partyItemAdd(priestess_card, 100);
    partyItemAdd(empress_card, 100);
    partyItemAdd(lovers_card, 100);
    partyItemAdd(sun_card, 100);
    partyItemAdd(maragion_card, 2);
    partyItemAdd(malaques_card, 2);
    partyItemAdd(magarula_card, 2);
    partyItemAdd(mamagnara_card, 2);
    partyItemAdd(freila_card, 2);
    partyItemAdd(gryva_card, 2);
    partyItemAdd(medirama_card, 2);
    partyItemAdd(megidola_card, 2);
    partyItemAdd(fool_card, 1);
    bitSet(VBIT_FOOL_GET);
    ref_552 = call(RNDCHECK);
    wait(ref_552);
    ref_554 = call(RNDCHECK);
    wait(ref_554);
    bitSet(MBIT_MEND_0F);
    b(label_5c0);
  label_558:
    ref_558 = dialogAlloc();
    ref_559 = msgShow(msg_75);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・スキルカードセット
[tab]を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_559);
    dialogFree(ref_558);
    partyItemAdd(emperor_card, 80);
    partyItemAdd(hierophant_card, 80);
    partyItemAdd(justice_card, 80);
    partyItemAdd(priestess_card, 80);
    partyItemAdd(empress_card, 80);
    partyItemAdd(sun_card, 80);
    partyItemAdd(agidyne_card, 2);
    partyItemAdd(aquadyne_card, 2);
    partyItemAdd(garudyne_card, 2);
    partyItemAdd(magnadyne_card, 2);
    partyItemAdd(diarama_card, 2);
    partyItemAdd(bufula_card, 2);
    partyItemAdd(zionga_card, 2);
    partyItemAdd(zanma_card, 2);
    ref_56b = call(RNDCHECK);
    wait(ref_56b);
    ref_56d = call(RNDCHECK);
    wait(ref_56d);
    bitSet(MBIT_MEND_0D);
    b(label_5c0);
  label_571:
    ref_571 = dialogAlloc();
    ref_572 = msgShow(msg_76);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット[tab]ブースターパック
[tab]を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_572);
    dialogFree(ref_571);
    partyItemAdd(st_card, 10);
    partyItemAdd(vi_card, 10);
    partyItemAdd(dx_card, 10);
    partyItemAdd(ag_card, 10);
    partyItemAdd(lu_card, 10);
    partyItemAdd(all_card, 10);
    partyItemAdd(tarukaja_card, 2);
    partyItemAdd(rakukaja_card, 2);
    partyItemAdd(makakaja_card, 2);
    partyItemAdd(samakaja_card, 2);
    partyItemAdd(sukukaja_card, 2);
    partyItemAdd(dekaja_card, 2);
    partyItemAdd(tetraja_card, 2);
    partyItemAdd(free_tarot, 150);
    ref_584 = call(RNDCHECK);
    wait(ref_584);
    bitSet(MBIT_MEND_0C);
    b(label_5c0);
  label_588:
    ref_588 = dialogAlloc();
    ref_589 = msgShow(msg_77);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット[tab]Ｐａｒｔ２
[tab]を受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_589);
    dialogFree(ref_588);
    partyItemAdd(emperor_card, 50);
    partyItemAdd(empress_card, 50);
    partyItemAdd(hierophant_card, 50);
    partyItemAdd(priestess_card, 50);
    partyItemAdd(justice_card, 50);
    partyItemAdd(free_tarot, 100);
    partyItemAdd(posumudi_card, 2);
    partyItemAdd(kotoludi_card, 2);
    partyItemAdd(patra_card, 2);
    partyItemAdd(me patra_card, 2);
    partyItemAdd(recarm_card, 2);
    ref_598 = call(RNDCHECK);
    wait(ref_598);
    bitSet(MBIT_MEND_0B);
    b(label_5c0);
  label_59c:
    ref_59c = dialogAlloc();
    ref_59d = msgShow(msg_78);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセットを受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_59d);
    dialogFree(ref_59c);
    partyItemAdd(empress_card, 30);
    partyItemAdd(emperor_card, 30);
    partyItemAdd(fortune_card, 30);
    partyItemAdd(hierophant_card, 30);
    partyItemAdd(justice_card, 30);
    partyItemAdd(priestess_card, 30);
    partyItemAdd(strength_card, 30);
    partyItemAdd(sun_card, 30);
    partyItemAdd(world_card, 30);
    partyItemAdd(free_tarot, 50);
    bitSet(MBIT_MEND_09);
    b(label_5c0);
  label_5ad:
    ref_5ad = dialogAlloc();
    ref_5ae = msgShow(msg_79);
/***************************************
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセットを受け取った。[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_5ae);
    dialogFree(ref_5ad);
    partyItemAdd(empress_card, 30);
    partyItemAdd(emperor_card, 30);
    partyItemAdd(fortune_card, 30);
    partyItemAdd(hierophant_card, 30);
    partyItemAdd(justice_card, 30);
    partyItemAdd(priestess_card, 30);
    partyItemAdd(strength_card, 30);
    partyItemAdd(sun_card, 30);
    partyItemAdd(world_card, 30);
    partyItemAdd(free_tarot, 50);
    ref_5bc = call(RNDCHECK);
    wait(ref_5bc);
    bitSet(MBIT_MEND_08);
    b(label_5c0);
  label_5c0:
    bitClear(MBIT_MAPKANSEI);
    bitClear(MBIT_MAPMIKANSEI);
    bitClear(MBIT_MAPSAKUSEI);
    bitClear(MBIT_MAP_NOHAKUSI);
    ref_5c4 = call(BITOFFALL);
    wait(ref_5c4);
  label_5c6:
    b(label_5c7);
  label_5c7:
    delayClear();
    delayWait(30);
    ref_5c9 = bustupLoad(bustup_75);
    bustupWait(ref_5c9);
    ref_5cb = bustupAlloc(ref_5c9, right, rgb(0,0,0));
    bustupFade(ref_5cb, rgb(128,0,0), 30);
    ref_5cd = dialogAlloc();
    ref_5ce = msgShow(msg_80);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]他ニ何カアルカ？
[tab]何デモ言ッテクダサイヨ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_5ce);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_5cd);
    ref_5d3 = bustupFade(ref_5cb, rgb(0,0,0), 10);
    bustupWait(ref_5d3);
    bustupFree(ref_5cb);
    b(label_35d);
  label_5d7:
    ref_5d7 = call(MAPMES);
    wait(ref_5d7);
    delayClear();
    delayWait(30);
    b(label_35d);
  label_5dc:
    ref_5dc = bustupLoad(bustup_75);
    bustupWait(ref_5dc);
    ref_5de = bustupAlloc(ref_5dc, right, rgb(0,0,0));
    bustupFade(ref_5de, rgb(128,0,0), 30);
    ref_5e0 = dialogAlloc();
    ref_5e1 = msgShow(msg_81);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]マタ来テネ、キレーナオ嬢サン。
[tab]デモ、ワタシノ事ハ内緒ネ。
[tab]ワタシ、裏社会ニ敵ガ多イカラ…アッハッハ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_1d, 1);
    wait(ref_5e1);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_5e0);
    ref_5e6 = bustupFade(ref_5de, rgb(0,0,0), 10);
    bustupWait(ref_5e6);
    bustupFree(ref_5de);
    unitRestoreFacing(npc3);
    b(label_5eb);
  label_5eb:
    controlEnable();
}

function EVENTCHECK()
{
    bitGet(var_0, EBIT_E00B8);
    bez(var_0, label_5f3);
    bitSet(IBIT_BLK_MAP_13);
    bitSet(IBIT_BLK_MAP_29);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_5f3:
    bitGet(var_0, EBIT_E009F);
    bez(var_0, label_5f9);
    bitSet(IBIT_BLK_MAP_11);
    bitSet(IBIT_BLK_MAP_2C);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_5f9:
    bitGet(var_0, EBIT_E008C);
    bez(var_0, label_5fe);
    bitSet(IBIT_BLK_MAP_0F);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_5fe:
    bitGet(var_0, EBIT_E007F);
    bez(var_0, label_604);
    bitSet(IBIT_BLK_MAP_0D);
    bitSet(IBIT_BLK_MAP_19);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_604:
    bitGet(var_0, EBIT_E007B);
    bez(var_0, label_609);
    bitSet(IBIT_BLK_MAP_0C);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_609:
    bitGet(var_0, EBIT_E006F);
    bez(var_0, label_60f);
    bitSet(IBIT_BLK_MAP_0B);
    bitSet(IBIT_BLK_MAP_2A);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_60f:
    bitGet(var_0, MBIT_HI_ERITOUJO);
    bez(var_0, label_614);
    bitSet(IBIT_BLK_MAP_09);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_614:
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bez(var_0, label_619);
    bitSet(IBIT_BLK_MAP_08);
    bitSet(MBIT_MAPSAKUSEI);
    b(label_619);
  label_619:
}

function CLMAPCHECK()
{
    li(var_0, 0);
    bitGet(var_1, IBIT_CMP_MAP_13);
    bitGet(var_2, IBIT_CMP_MAP_29);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_622);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_62b);
  label_622:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_13);
    bitGet(var_2, IBIT_BLK_MAP_29);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_628);
    b(label_62a);
  label_628:
    b(label_6c3);
    b(label_62a);
  label_62a:
    b(label_62b);
  label_62b:
    li(var_0, 0);
    bitGet(var_1, IBIT_CMP_MAP_11);
    bitGet(var_2, IBIT_CMP_MAP_2C);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_633);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_643);
  label_633:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_11);
    bitGet(var_2, IBIT_BLK_MAP_2C);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_639);
    b(label_642);
  label_639:
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_63d);
    b(label_6c3);
    b(label_641);
  label_63d:
    bne(var_0, 1, label_641);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_641);
  label_641:
    b(label_642);
  label_642:
    b(label_643);
  label_643:
    bitGet(var_0, IBIT_CMP_MAP_0F);
    bne(var_0, 0, label_653);
    bitGet(var_0, IBIT_BLK_MAP_0F);
    bne(var_0, 0, label_648);
    b(label_652);
  label_648:
    bne(var_0, 1, label_652);
    bitGet(var_0, EBIT_E009F);
    bne(var_0, 0, label_64d);
    b(label_6c3);
    b(label_651);
  label_64d:
    bne(var_0, 1, label_651);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_651);
  label_651:
    b(label_652);
  label_652:
    b(label_657);
  label_653:
    bne(var_0, 1, label_657);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_657);
  label_657:
    li(var_0, 0);
    bitGet(var_1, IBIT_CMP_MAP_0D);
    bitGet(var_2, IBIT_CMP_MAP_19);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_65f);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_66f);
  label_65f:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_0D);
    bitGet(var_2, IBIT_BLK_MAP_19);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_665);
    b(label_66e);
  label_665:
    bitGet(var_0, EBIT_E0088);
    bne(var_0, 0, label_669);
    b(label_6c3);
    b(label_66d);
  label_669:
    bne(var_0, 1, label_66d);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_66d);
  label_66d:
    b(label_66e);
  label_66e:
    b(label_66f);
  label_66f:
    bitGet(var_0, IBIT_CMP_MAP_0C);
    bne(var_0, 0, label_67f);
    bitGet(var_0, IBIT_BLK_MAP_0C);
    bne(var_0, 0, label_674);
    b(label_67e);
  label_674:
    bne(var_0, 1, label_67e);
    bitGet(var_0, EBIT_E007F);
    bne(var_0, 0, label_679);
    b(label_6c3);
    b(label_67d);
  label_679:
    bne(var_0, 1, label_67d);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_67d);
  label_67d:
    b(label_67e);
  label_67e:
    b(label_683);
  label_67f:
    bne(var_0, 1, label_683);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_683);
  label_683:
    li(var_0, 0);
    bitGet(var_1, IBIT_CMP_MAP_0B);
    bitGet(var_2, IBIT_CMP_MAP_2A);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_68b);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_69b);
  label_68b:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_0B);
    bitGet(var_2, IBIT_BLK_MAP_2A);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_691);
    b(label_69a);
  label_691:
    bitGet(var_0, EBIT_E0077);
    bne(var_0, 0, label_695);
    b(label_6c3);
    b(label_699);
  label_695:
    bne(var_0, 1, label_699);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_699);
  label_699:
    b(label_69a);
  label_69a:
    b(label_69b);
  label_69b:
    bitGet(var_0, IBIT_CMP_MAP_09);
    bne(var_0, 0, label_6ab);
    bitGet(var_0, IBIT_BLK_MAP_09);
    bne(var_0, 0, label_6a0);
    b(label_6aa);
  label_6a0:
    bne(var_0, 1, label_6aa);
    bitGet(var_0, EBIT_E006F);
    bne(var_0, 0, label_6a5);
    b(label_6c3);
    b(label_6a9);
  label_6a5:
    bne(var_0, 1, label_6a9);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_6a9);
  label_6a9:
    b(label_6aa);
  label_6aa:
    b(label_6af);
  label_6ab:
    bne(var_0, 1, label_6af);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_6af);
  label_6af:
    bitGet(var_0, IBIT_CMP_MAP_08);
    bne(var_0, 0, label_6bf);
    bitGet(var_0, IBIT_BLK_MAP_08);
    bne(var_0, 0, label_6b4);
    b(label_6be);
  label_6b4:
    bne(var_0, 1, label_6be);
    bitGet(var_0, EBIT_E006F);
    bne(var_0, 0, label_6b9);
    b(label_6c3);
    b(label_6bd);
  label_6b9:
    bne(var_0, 1, label_6bd);
    bitSet(MBIT_MAPMIKANSEI);
    b(label_6c3);
    b(label_6bd);
  label_6bd:
    b(label_6be);
  label_6be:
    b(label_6c3);
  label_6bf:
    bne(var_0, 1, label_6c3);
    bitSet(MBIT_MAPKANSEI);
    b(label_6c3);
    b(label_6c3);
  label_6c3:
}

function MAPMES()
{
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_6d8);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_6c8);
  label_6c8:
    unitFacePlayer(npc3);
    ref_6c9 = bustupLoad(bustup_75);
    bustupWait(ref_6c9);
    ref_6cb = bustupAlloc(ref_6c9, right, rgb(0,0,0));
    bustupFade(ref_6cb, rgb(128,0,0), 30);
    ref_6cd = dialogAlloc();
    ref_6ce = msgShow(msg_82);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]街ガ空ヲ飛ンデイイノカ？[tab]神ノ許シハ得タノカ？
[tab]ダメ！[tab]コンナ所ニイラレナイヨ。
[tab]…デモ、地上ハモット危険カ……。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_6ce);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_6cd);
    ref_6d3 = bustupFade(ref_6cb, rgb(0,0,0), 10);
    bustupWait(ref_6d3);
    bustupFree(ref_6cb);
    unitRestoreFacing(npc3);
    b(label_6e7);
  label_6d8:
    unitFacePlayer(npc3);
    ref_6d9 = bustupLoad(bustup_75);
    bustupWait(ref_6d9);
    ref_6db = bustupAlloc(ref_6d9, right, rgb(0,0,0));
    bustupFade(ref_6db, rgb(128,0,0), 30);
    ref_6dd = dialogAlloc();
    ref_6de = msgShow(msg_83);
/***************************************
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ドラゴン…アンナ生物ガイルナンテ…。
[tab]地球上ニハ、マダマダ不思議ガ一杯デッス！
[tab]新タナ趣味ガ見付ケラレソウダネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_6de);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_6dd);
    ref_6e3 = bustupFade(ref_6db, rgb(0,0,0), 10);
    bustupWait(ref_6e3);
    bustupFree(ref_6db);
    unitRestoreFacing(npc3);
  label_6e7:
}

function SHOP()
{
    controlDisable();
    ref_6e9 = shopOverlayInit();
    unitFacePlayer(shopkeeper);
    bitGet(var_0, MBIT_AIS_67);
    bne(var_0, 0, label_6ef);
    b(label_6f8);
    b(label_6f8);
  label_6ef:
    bne(var_0, 1, label_6f8);
    bitGet(var_0, MBIT_HSATOMI_HATURAITEN);
    bne(var_0, 0, label_6f4);
    b(label_709);
    b(label_6f7);
  label_6f4:
    bne(var_0, 1, label_6f7);
    b(label_71a);
    b(label_6f7);
  label_6f7:
    b(label_6f8);
  label_6f8:
    ref_6f8 = bustupLoad(bustup_fd);
    bustupWait(ref_6f8);
    ref_6fa = bustupAlloc(ref_6f8, right, rgb(0,0,0));
    bustupFade(ref_6fa, rgb(128,0,0), 30);
    ref_6fc = dialogAlloc();
    ref_6fd = msgShow(msg_84);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]はいはい、いらっしゃいませ～！！
[tab]今日もせっせと全国制覇！
[tab]さぁ、何が欲しいのかしら？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_6fd);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_6fc);
    ref_702 = bustupFade(ref_6fa, rgb(0,0,0), 10);
    bustupWait(ref_702);
    bustupFree(ref_6fa);
    wait(ref_6e9);
    shopInventory(9, shopInventory_0);
    shopRate(100);
    b(label_72b);
  label_709:
    ref_709 = bustupLoad(bustup_fd);
    bustupWait(ref_709);
    ref_70b = bustupAlloc(ref_709, right, rgb(0,0,0));
    bustupFade(ref_70b, rgb(128,0,0), 30);
    ref_70d = dialogAlloc();
    ref_70e = msgShow(msg_85);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]はいはい、いらっしゃいませ～！！
[tab]ここは初めて？[tab]うひょひょひょ！！
[tab]サービスするから、いっぱい買ってねー
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_70e);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_70d);
    ref_713 = bustupFade(ref_70b, rgb(0,0,0), 10);
    bustupWait(ref_713);
    bustupFree(ref_70b);
    wait(ref_6e9);
    shopInventory(9, shopInventory_0);
    shopRate(80);
    b(label_72b);
  label_71a:
    ref_71a = bustupLoad(bustup_fd);
    bustupWait(ref_71a);
    ref_71c = bustupAlloc(ref_71a, right, rgb(0,0,0));
    bustupFade(ref_71c, rgb(128,0,0), 30);
    ref_71e = dialogAlloc();
    ref_71f = msgShow(msg_86);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]いらっしゃいま…あらぁ！！
[tab]いつもどーもなのねー！[tab]うひょひょひょ！！
[tab]サービスするから、いっぱい買ってねー
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_71f);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_71e);
    ref_724 = bustupFade(ref_71c, rgb(0,0,0), 10);
    bustupWait(ref_724);
    bustupFree(ref_71c);
    wait(ref_6e9);
    shopInventory(9, shopInventory_0);
    shopRate(80);
    b(label_72b);
  label_72b:
    ref_72b = bustupLoad(bustup_fd);
    bustupWait(ref_72b);
    ref_72d = bustupAlloc(ref_72b, right, rgb(0,0,0));
    bustupFade(ref_72d, rgb(128,0,0), 30);
    choiceSetResult(4);
    ref_730 = dialogAlloc();
    ref_731 = msgShow(msg_87);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]サービスするから、いっぱい買ってねー
[choice(6)]消費物を買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_731);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_73a);
    li(var_5, 0);
    b(label_75d);
  label_73a:
    bne(var_0, 1, label_745);
    choiceSetResult(0);
    ref_73c = msgShow(msg_88);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]さぁ、何を売りたいのかしらぁ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear]
***************************************/
    wait(ref_73c);
    choiceGetResult(var_5);
    bne(var_5, 0, label_742);
    li(var_5, 1000);
    b(label_744);
  label_742:
    add(var_5, var_5, 10);
    b(label_744);
  label_744:
    b(label_75d);
  label_745:
    bne(var_0, 2, label_754);
    choiceSetResult(2);
    ref_747 = msgShow(msg_89);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
売買の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_747);
    choiceGetResult(var_0);
    bne(var_0, 0, label_74d);
    li(var_5, 2);
    b(label_753);
  label_74d:
    bne(var_0, 1, label_750);
    li(var_5, 2000);
    b(label_753);
  label_750:
    bne(var_0, 2, label_753);
    li(var_5, 1000);
    b(label_753);
  label_753:
    b(label_75d);
  label_754:
    bne(var_0, 3, label_757);
    li(var_5, 4);
    b(label_75d);
  label_757:
    bne(var_0, 4, label_75a);
    li(var_5, 4);
    b(label_75d);
  label_75a:
    bne(var_0, 5, label_75d);
    li(var_5, 5);
    b(label_75d);
  label_75d:
    dialogFree(ref_730);
    ref_75e = bustupFade(ref_72d, rgb(0,0,0), 10);
    bustupWait(ref_75e);
    bustupFree(ref_72d);
    ref_761 = shopOpen(5);
    wait(ref_761);
}

function HA_SHOP_RESTART_0()
{
    choiceSetResult(4);
    ref_765 = bustupLoad(bustup_fd);
    bustupWait(ref_765);
    ref_767 = bustupAlloc(ref_765, right, rgb(0,0,0));
    bustupFade(ref_767, rgb(128,0,0), 30);
    ref_769 = dialogAlloc();
    ref_76a = msgShow(msg_90);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]うひょひょひょ！！[delay(10)]
[tab]はいはい。
[tab]他に用はあるかしらぁ？
[choice(6)]消費物を買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_76a);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_773);
    li(var_5, 0);
    b(label_796);
  label_773:
    bne(var_0, 1, label_77e);
    choiceSetResult(0);
    ref_775 = msgShow(msg_91);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]さぁ、何を売りたいのかしら？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear]
***************************************/
    wait(ref_775);
    choiceGetResult(var_5);
    bne(var_5, 0, label_77b);
    li(var_5, 1000);
    b(label_77d);
  label_77b:
    add(var_5, var_5, 10);
    b(label_77d);
  label_77d:
    b(label_796);
  label_77e:
    bne(var_0, 2, label_78d);
    choiceSetResult(2);
    ref_780 = msgShow(msg_92);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
売買の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_780);
    choiceGetResult(var_0);
    bne(var_0, 0, label_786);
    li(var_5, 2);
    b(label_78c);
  label_786:
    bne(var_0, 1, label_789);
    li(var_5, 2000);
    b(label_78c);
  label_789:
    bne(var_0, 2, label_78c);
    li(var_5, 1000);
    b(label_78c);
  label_78c:
    b(label_796);
  label_78d:
    bne(var_0, 3, label_790);
    li(var_5, 4);
    b(label_796);
  label_790:
    bne(var_0, 4, label_793);
    li(var_5, 4);
    b(label_796);
  label_793:
    bne(var_0, 5, label_796);
    li(var_5, 5);
    b(label_796);
  label_796:
    dialogFree(ref_769);
    ref_797 = bustupFade(ref_767, rgb(0,0,0), 10);
    bustupWait(ref_797);
    bustupFree(ref_767);
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_7cb);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_7bd);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_7af);
    ref_7a1 = bustupLoad(bustup_fd);
    bustupWait(ref_7a1);
    ref_7a3 = bustupAlloc(ref_7a1, right, rgb(0,0,0));
    bustupFade(ref_7a3, rgb(128,0,0), 30);
    ref_7a5 = dialogAlloc();
    ref_7a6 = msgShow(msg_93);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]穢れ祓いの講演会が大人気ですってね～
[tab]マッタク、芸能人に何が出来るって言うのよー！
[tab]…お客を少し分けて欲しいわ～…シクーッ！
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7a6);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7a5);
    ref_7ab = bustupFade(ref_7a3, rgb(0,0,0), 10);
    bustupWait(ref_7ab);
    bustupFree(ref_7a3);
    b(label_7dc);
  label_7af:
    ref_7af = bustupLoad(bustup_fd);
    bustupWait(ref_7af);
    ref_7b1 = bustupAlloc(ref_7af, right, rgb(0,0,0));
    bustupFade(ref_7b1, rgb(128,0,0), 30);
    ref_7b3 = dialogAlloc();
    ref_7b4 = msgShow(msg_94);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]新世塾…お近付きになりたいわー！
[tab]まあ、サトミタダシのパトロンになってくれるなら
[tab]どんな組織でもいいけど！[tab]うひょひょひょ！！
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7b4);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7b3);
    ref_7b9 = bustupFade(ref_7b1, rgb(0,0,0), 10);
    bustupWait(ref_7b9);
    bustupFree(ref_7b1);
    b(label_7dc);
  label_7bd:
    ref_7bd = bustupLoad(bustup_fd);
    bustupWait(ref_7bd);
    ref_7bf = bustupAlloc(ref_7bd, right, rgb(0,0,0));
    bustupFade(ref_7bf, rgb(128,0,0), 30);
    ref_7c1 = dialogAlloc();
    ref_7c2 = msgShow(msg_95);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]シクー、街が空飛んでどうすんのよー！[delay(15)]
[tab]しかも世界滅亡でしょー？[delay(15)]
[tab]私達の全国制覇の夢はどうなるのよー！
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7c2);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7c1);
    ref_7c7 = bustupFade(ref_7bf, rgb(0,0,0), 10);
    bustupWait(ref_7c7);
    bustupFree(ref_7bf);
    b(label_7dc);
  label_7cb:
    ref_7cb = bustupLoad(bustup_fd);
    bustupWait(ref_7cb);
    ref_7cd = bustupAlloc(ref_7cb, right, rgb(0,0,0));
    bustupFade(ref_7cd, rgb(128,0,0), 30);
    ref_7cf = dialogAlloc();
    ref_7d0 = msgShow(msg_96);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]うひょひょひょ！！
[tab]なんか滅亡しないみたいだけど、
[tab]どうなってるのかしらねー！
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7d0);
    ref_7d3 = msgShow(msg_97);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]でも、このままじゃ全国制覇は無理なのねー！
[tab]シクー！
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7d3);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7cf);
    ref_7d8 = bustupFade(ref_7cd, rgb(0,0,0), 10);
    bustupWait(ref_7d8);
    bustupFree(ref_7cd);
    b(label_7dc);
  label_7dc:
}

function HA_SHOP_END_0()
{
    ref_7dd = bustupLoad(bustup_fd);
    bustupWait(ref_7dd);
    ref_7df = bustupAlloc(ref_7dd, right, rgb(0,0,0));
    bustupFade(ref_7df, rgb(128,0,0), 30);
    ref_7e1 = dialogAlloc();
    ref_7e2 = msgShow(msg_98);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]サトミタダシは年中無休よ！
[tab]また来てちょうだぁ～い！
[tab]うひょひょひょひょ！！
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_7e2);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopOverlayInit();
    dialogFree(ref_7e1);
    ref_7e8 = bustupFade(ref_7df, rgb(0,0,0), 10);
    bustupWait(ref_7e8);
    bustupFree(ref_7df);
    delayClear();
    delayWait(10);
    bitSet(MBIT_HSATOMI_HATURAITEN);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_7f3);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    b(label_7f6);
  label_7f3:
    bne(var_0, 1, label_7f6);
    call(GOOUT);
    b(label_7f6);
  label_7f6:
}

function DANBOORU0()
{
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bnz(var_0, label_7ff);
    bitSet(MBIT_HI_NANJOTOUJO);
    ref_7fa = dialogAlloc();
    ref_7fb = msgShow(msg_99);
/***************************************
ＭＢＩＴ[tab]ＨＩ[tab]ＮＡＮＪＯＴＯＵＪＯ
南条出現噂：広げた
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_7fb);
    dialogFree(ref_7fa);
    b(label_816);
  label_7ff:
    bitGet(var_0, MBIT_KE_SKYMAP);
    bnz(var_0, label_807);
    bitSet(MBIT_KE_SKYMAP);
    ref_802 = dialogAlloc();
    ref_803 = msgShow(msg_100);
/***************************************
マップ屋の噂・決定
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_803);
    dialogFree(ref_802);
    b(label_816);
  label_807:
    bitGet(var_0, LBIT_0000);
    bne(var_0, 0, label_80f);
    bitSet(LBIT_0000);
    ref_80a = dialogAlloc();
    ref_80b = msgShow(msg_101);
/***************************************
マップ屋の依頼を受けた
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_80b);
    dialogFree(ref_80a);
    b(label_816);
  label_80f:
    bne(var_0, 1, label_816);
    bitClear(LBIT_0000);
    ref_811 = dialogAlloc();
    ref_812 = msgShow(msg_102);
/***************************************
マップ屋の依頼を受けた
びっとお～ふッ！！
びっとお～ふッ！！
[wait][clear]
***************************************/
    wait(ref_812);
    dialogFree(ref_811);
    b(label_816);
  label_816:
}

function DANBOORU()
{
    bitGet(var_0, MBIT_AIS_67);
    bnz(var_0, label_81f);
    bitSet(MBIT_AIS_67);
    ref_81a = dialogAlloc();
    ref_81b = msgShow(msg_103);
/***************************************
ＭＢＩＴ[tab]ＡＩＳ[tab]６７
相性占いの
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_81b);
    dialogFree(ref_81a);
    b(label_866);
  label_81f:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_827);
    bitSet(EBIT_E006F);
    ref_822 = dialogAlloc();
    ref_823 = msgShow(msg_104);
/***************************************
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_823);
    dialogFree(ref_822);
    b(label_866);
  label_827:
    bitGet(var_0, EBIT_E0077);
    bnz(var_0, label_82f);
    bitSet(EBIT_E0077);
    ref_82a = dialogAlloc();
    ref_82b = msgShow(msg_105);
/***************************************
ＥＢＩＴ[tab]Ｅ００７７
「スマイル平坂クリア・克哉離脱」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_82b);
    dialogFree(ref_82a);
    b(label_866);
  label_82f:
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_837);
    bitSet(EBIT_E007A);
    ref_832 = dialogAlloc();
    ref_833 = msgShow(msg_106);
/***************************************
ＥＢＩＴ[tab]Ｅ００７Ａ
「野音クリア・克哉編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_833);
    dialogFree(ref_832);
    b(label_866);
  label_837:
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_83f);
    bitSet(EBIT_E007B);
    ref_83a = dialogAlloc();
    ref_83b = msgShow(msg_107);
/***************************************
ＥＢＩＴ[tab]Ｅ００７Ｂ
「竜蔵と殺し屋の電話を盗聴」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_83b);
    dialogFree(ref_83a);
    b(label_866);
  label_83f:
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_847);
    bitSet(EBIT_E007F);
    ref_842 = dialogAlloc();
    ref_843 = msgShow(msg_108);
/***************************************
ＥＢＩＴ[tab]Ｅ００７Ｆ
「廃工場クリア・パオフゥ編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_843);
    dialogFree(ref_842);
    b(label_866);
  label_847:
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_84f);
    bitSet(EBIT_E008C);
    ref_84a = dialogAlloc();
    ref_84b = msgShow(msg_109);
/***************************************
ＥＢＩＴ[tab]Ｅ００８Ｃ
「海底遺跡クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_84b);
    dialogFree(ref_84a);
    b(label_866);
  label_84f:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_857);
    bitSet(EBIT_E009F);
    ref_852 = dialogAlloc();
    ref_853 = msgShow(msg_110);
/***************************************
ＥＢＩＴ[tab]Ｅ００９Ｆ
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_853);
    dialogFree(ref_852);
    b(label_866);
  label_857:
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_85f);
    bitSet(EBIT_E00AF);
    ref_85a = dialogAlloc();
    ref_85b = msgShow(msg_111);
/***************************************
ＥＢＩＴ[tab]Ｅ００ＡＦ
「アメノトリフネクリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_85b);
    dialogFree(ref_85a);
    b(label_866);
  label_85f:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_866);
    bitSet(EBIT_E00B8);
    ref_862 = dialogAlloc();
    ref_863 = msgShow(msg_112);
/***************************************
ＥＢＩＴ[tab]Ｅ００Ｂ８
「珠「瑠城クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_863);
    dialogFree(ref_862);
  label_866:
}

function DOORBOX()
{
    controlDisable();
    sndMusicPlay(sound_306b, 127);
    objAnimTranslate(obj_6, 80, 0, 0, 30);
    objAnimTranslate(obj_7, -80, 0, 0, 30);
    objAnimWait(obj_6);
    objAnimWait(obj_7);
    call(GOOUT);
}

function GOOUT()
{
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function warp1()
{
    call(DOORBOX);
}

function HA_SHOP_EXPLAIN_0()
{
    ref_874 = dialogAlloc();
    ref_875 = msgShow(msg_113);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]うひょひょひょ。
[tab]「売買」についてねぇ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]まずは、購入の説明なのねぇ～。
[tab]うちの店で「消費物を買う」を選ぶと
[tab]消費アイテムを買うことができるわよぉ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]あっ、そうそう、アイテムは持てる数が
[tab]決まってるからねぇ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]次に、売却の説明なのねぇ～。
[tab]「アイテムを売る」を選んで、まず種類を決めて、
[tab]次に売りたいものを選んでねぇ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]買取価格は元値の約半額くらいよぉ～。
[tab]あと、装備中の物は売ることができないからねぇ～。
[tab]それと、物によっては買取できない物もあるわよぉ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]こんなとこかしらぁ～。
[tab]うひょひょひょ。
[wait][clear]
***************************************/
    wait(ref_875);
    dialogFree(ref_874);
}

function BITOFFALL()
{
    bitClear(IBIT_BLK_MAP_13);
    bitClear(IBIT_BLK_MAP_29);
    bitClear(IBIT_CMP_MAP_13);
    bitClear(IBIT_CMP_MAP_29);
    bitClear(IBIT_BLK_MAP_11);
    bitClear(IBIT_BLK_MAP_2C);
    bitClear(IBIT_CMP_MAP_11);
    bitClear(IBIT_CMP_MAP_2C);
    bitClear(IBIT_BLK_MAP_0F);
    bitClear(IBIT_CMP_MAP_0F);
    bitClear(IBIT_BLK_MAP_0D);
    bitClear(IBIT_BLK_MAP_19);
    bitClear(IBIT_CMP_MAP_0D);
    bitClear(IBIT_CMP_MAP_19);
    bitClear(IBIT_BLK_MAP_0C);
    bitClear(IBIT_CMP_MAP_0C);
    bitClear(IBIT_BLK_MAP_0B);
    bitClear(IBIT_BLK_MAP_2A);
    bitClear(IBIT_CMP_MAP_0B);
    bitClear(IBIT_CMP_MAP_2A);
    bitClear(IBIT_BLK_MAP_09);
    bitClear(IBIT_CMP_MAP_09);
    bitClear(IBIT_BLK_MAP_08);
    bitClear(IBIT_CMP_MAP_08);
}

function MESHYOUJI()
{
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_13);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_29);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_13);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_29);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_11);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_2C);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_11);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_2C);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_0F);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_0F);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_0D);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_19);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_0D);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_19);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_0C);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_0C);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_0B);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_2A);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_0B);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_2A);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_09);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_09);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_BLK_MAP_08);
    add(var_0, var_0, var_1);
    bitGet(var_1, IBIT_CMP_MAP_08);
    add(var_0, var_0, var_1);
    bne(var_0, 0, label_8c6);
    bitClear(LBIT_0010);
    b(label_8c8);
  label_8c6:
    bitSet(LBIT_0010);
    b(label_8c8);
  label_8c8:
}

function TIZU()
{
    li(var_0, 0);
    li(var_1, 0);
    li(var_2, 0);
    bitGet(var_1, IBIT_BLK_MAP_13);
    bitGet(var_2, IBIT_BLK_MAP_29);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_8d1);
    b(label_8d5);
  label_8d1:
    msgVarSet(msgvar_1, 4179);
    msgVarSet(msgvar_2, 4201);
    b(label_90b);
    b(label_8d5);
  label_8d5:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_11);
    bitGet(var_2, IBIT_BLK_MAP_2C);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_8db);
    b(label_8df);
  label_8db:
    msgVarSet(msgvar_1, 4177);
    msgVarSet(msgvar_2, 4204);
    b(label_90b);
    b(label_8df);
  label_8df:
    bitGet(var_1, IBIT_BLK_MAP_0F);
    bne(var_1, 0, label_8e2);
    b(label_8e5);
  label_8e2:
    msgVarSet(msgvar_1, 4175);
    b(label_90b);
    b(label_8e5);
  label_8e5:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_0D);
    bitGet(var_2, IBIT_BLK_MAP_19);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_8eb);
    b(label_8ef);
  label_8eb:
    msgVarSet(msgvar_1, 4173);
    msgVarSet(msgvar_2, 4185);
    b(label_90b);
    b(label_8ef);
  label_8ef:
    bitGet(var_1, IBIT_BLK_MAP_0C);
    bne(var_1, 0, label_8f2);
    b(label_8f5);
  label_8f2:
    msgVarSet(msgvar_1, 4172);
    b(label_90b);
    b(label_8f5);
  label_8f5:
    li(var_0, 0);
    bitGet(var_1, IBIT_BLK_MAP_0B);
    bitGet(var_2, IBIT_BLK_MAP_2A);
    add(var_0, var_1, var_2);
    bne(var_0, 0, label_8fb);
    b(label_8ff);
  label_8fb:
    msgVarSet(msgvar_1, 4171);
    msgVarSet(msgvar_2, 4202);
    b(label_90b);
    b(label_8ff);
  label_8ff:
    bitGet(var_1, IBIT_BLK_MAP_09);
    bne(var_1, 0, label_902);
    b(label_905);
  label_902:
    msgVarSet(msgvar_1, 4169);
    b(label_90b);
    b(label_905);
  label_905:
    bitGet(var_1, IBIT_BLK_MAP_08);
    bne(var_1, 0, label_908);
    b(label_90b);
  label_908:
    msgVarSet(msgvar_1, 4168);
    b(label_90b);
    b(label_90b);
  label_90b:
}

function TUGIDOKOIKU()
{
    bitGet(var_0, EBIT_E00B8);
    bne(var_0, 0, label_90f);
    b(label_91a);
  label_90f:
    bne(var_0, 1, label_91a);
    bitGet(var_0, MBIT_MEND_13);
    bne(var_0, 0, label_915);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_919);
  label_915:
    bne(var_0, 1, label_919);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_919);
  label_919:
    b(label_91a);
  label_91a:
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_91d);
    b(label_920);
  label_91d:
    bne(var_0, 1, label_920);
    b(label_98c);
    b(label_920);
  label_920:
    bitGet(var_0, EBIT_E009F);
    bne(var_0, 0, label_923);
    b(label_92e);
  label_923:
    bne(var_0, 1, label_92e);
    bitGet(var_0, MBIT_MEND_11);
    bne(var_0, 0, label_929);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_92d);
  label_929:
    bne(var_0, 1, label_92d);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_92d);
  label_92d:
    b(label_92e);
  label_92e:
    bitGet(var_0, EBIT_E008F);
    bne(var_0, 0, label_931);
    b(label_93c);
  label_931:
    bne(var_0, 1, label_93c);
    bitGet(var_0, MBIT_MEND_0F);
    bne(var_0, 0, label_937);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_93b);
  label_937:
    bne(var_0, 1, label_93b);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_93b);
  label_93b:
    b(label_93c);
  label_93c:
    bitGet(var_0, EBIT_E008C);
    bne(var_0, 0, label_93f);
    b(label_942);
  label_93f:
    bne(var_0, 1, label_942);
    b(label_98c);
    b(label_942);
  label_942:
    bitGet(var_0, EBIT_E007F);
    bne(var_0, 0, label_945);
    b(label_950);
  label_945:
    bne(var_0, 1, label_950);
    bitGet(var_0, MBIT_MEND_0D);
    bne(var_0, 0, label_94b);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_94f);
  label_94b:
    bne(var_0, 1, label_94f);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_94f);
  label_94f:
    b(label_950);
  label_950:
    bitGet(var_0, EBIT_E007B);
    bne(var_0, 0, label_953);
    b(label_95e);
  label_953:
    bne(var_0, 1, label_95e);
    bitGet(var_0, MBIT_MEND_0C);
    bne(var_0, 0, label_959);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_95d);
  label_959:
    bne(var_0, 1, label_95d);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_95d);
  label_95d:
    b(label_95e);
  label_95e:
    bitGet(var_0, EBIT_E0077);
    bne(var_0, 0, label_961);
    b(label_964);
  label_961:
    bne(var_0, 1, label_964);
    b(label_98c);
    b(label_964);
  label_964:
    bitGet(var_0, EBIT_E006F);
    bne(var_0, 0, label_967);
    b(label_972);
  label_967:
    bne(var_0, 1, label_972);
    bitGet(var_0, MBIT_MEND_0B);
    bne(var_0, 0, label_96d);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_971);
  label_96d:
    bne(var_0, 1, label_971);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_971);
  label_971:
    b(label_972);
  label_972:
    bitGet(var_0, MBIT_HI_ERITOUJO);
    bne(var_0, 0, label_975);
    b(label_980);
  label_975:
    bne(var_0, 1, label_980);
    bitGet(var_0, MBIT_MEND_09);
    bne(var_0, 0, label_97b);
    bitSet(LBIT_0011);
    b(label_98c);
    b(label_97f);
  label_97b:
    bne(var_0, 1, label_97f);
    bitSet(LBIT_0012);
    b(label_98c);
    b(label_97f);
  label_97f:
    b(label_980);
  label_980:
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_983);
    b(label_98c);
  label_983:
    bne(var_0, 1, label_98c);
    bitGet(var_0, MBIT_MEND_08);
    bne(var_0, 0, label_988);
    bitSet(LBIT_0011);
    b(label_98b);
  label_988:
    bne(var_0, 1, label_98b);
    bitSet(LBIT_0012);
    b(label_98b);
  label_98b:
    b(label_98c);
  label_98c:
}

function TOUHACHECK()
{
    li(var_0, 0);
    bitGet(var_1, MBIT_OK_MAP_13);
    bitGet(var_2, MBIT_OK_MAP_29);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_99d);
    bitGet(var_0, MBIT_MEND_13);
    bne(var_0, 0, label_999);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_13);
    bitSet(IBIT_CMP_MAP_29);
    b(label_a09);
    b(label_99c);
  label_999:
    bne(var_0, 1, label_99c);
    b(label_a09);
    b(label_99c);
  label_99c:
    b(label_99e);
  label_99d:
    b(label_99e);
  label_99e:
    li(var_0, 0);
    bitGet(var_1, MBIT_OK_MAP_11);
    bitGet(var_2, MBIT_OK_MAP_2C);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_9ae);
    bitGet(var_0, MBIT_MEND_11);
    bne(var_0, 0, label_9aa);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_11);
    bitSet(IBIT_CMP_MAP_2C);
    b(label_a09);
    b(label_9ad);
  label_9aa:
    bne(var_0, 1, label_9ad);
    b(label_a09);
    b(label_9ad);
  label_9ad:
    b(label_9af);
  label_9ae:
    b(label_9af);
  label_9af:
    bitGet(var_0, MBIT_OK_MAP_0F);
    bne(var_0, 0, label_9b2);
    b(label_9bd);
  label_9b2:
    bne(var_0, 1, label_9bd);
    bitGet(var_0, MBIT_MEND_0F);
    bne(var_0, 0, label_9b9);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_0F);
    b(label_a09);
    b(label_9bc);
  label_9b9:
    bne(var_0, 1, label_9bc);
    b(label_a09);
    b(label_9bc);
  label_9bc:
    b(label_9bd);
  label_9bd:
    li(var_0, 0);
    bitGet(var_1, MBIT_OK_MAP_0D);
    bitGet(var_2, MBIT_OK_MAP_19);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_9cd);
    bitGet(var_0, MBIT_MEND_0D);
    bne(var_0, 0, label_9c9);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_0D);
    bitSet(IBIT_CMP_MAP_19);
    b(label_a09);
    b(label_9cc);
  label_9c9:
    bne(var_0, 1, label_9cc);
    b(label_a09);
    b(label_9cc);
  label_9cc:
    b(label_9ce);
  label_9cd:
    b(label_9ce);
  label_9ce:
    bitGet(var_0, MBIT_OK_MAP_0C);
    bne(var_0, 0, label_9d1);
    b(label_9dc);
  label_9d1:
    bne(var_0, 1, label_9dc);
    bitGet(var_0, MBIT_MEND_0C);
    bne(var_0, 0, label_9d8);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_0C);
    b(label_a09);
    b(label_9db);
  label_9d8:
    bne(var_0, 1, label_9db);
    b(label_a09);
    b(label_9db);
  label_9db:
    b(label_9dc);
  label_9dc:
    li(var_0, 0);
    bitGet(var_1, MBIT_OK_MAP_0B);
    bitGet(var_2, MBIT_OK_MAP_2A);
    add(var_0, var_1, var_2);
    bne(var_0, 2, label_9ec);
    bitGet(var_0, MBIT_MEND_0B);
    bne(var_0, 0, label_9e8);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_0B);
    bitSet(IBIT_CMP_MAP_2A);
    b(label_a09);
    b(label_9eb);
  label_9e8:
    bne(var_0, 1, label_9eb);
    b(label_a09);
    b(label_9eb);
  label_9eb:
    b(label_9ed);
  label_9ec:
    b(label_9ed);
  label_9ed:
    bitGet(var_0, MBIT_OK_MAP_09);
    bne(var_0, 0, label_9f0);
    b(label_9fb);
  label_9f0:
    bne(var_0, 1, label_9fb);
    bitGet(var_0, MBIT_MEND_09);
    bne(var_0, 0, label_9f7);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_09);
    b(label_a09);
    b(label_9fa);
  label_9f7:
    bne(var_0, 1, label_9fa);
    b(label_a09);
    b(label_9fa);
  label_9fa:
    b(label_9fb);
  label_9fb:
    bitGet(var_0, MBIT_OK_MAP_08);
    bne(var_0, 0, label_9fe);
    b(label_a09);
  label_9fe:
    bne(var_0, 1, label_a09);
    bitGet(var_0, MBIT_MEND_08);
    bne(var_0, 0, label_a05);
    bitSet(MBIT_MAP_NOHAKUSI);
    bitSet(IBIT_CMP_MAP_08);
    b(label_a09);
    b(label_a08);
  label_a05:
    bne(var_0, 1, label_a08);
    b(label_a09);
    b(label_a08);
  label_a08:
    b(label_a09);
  label_a09:
}

function RNDCHECK()
{
    rand(var_0, 15);
    bne(var_0, 0, label_a0e);
    partyItemAdd(healing_card, 1);
    b(label_a3a);
  label_a0e:
    bne(var_0, 1, label_a11);
    partyItemAdd(holylight_card, 1);
    b(label_a3a);
  label_a11:
    bne(var_0, 2, label_a14);
    partyItemAdd(attack mirror_card, 1);
    b(label_a3a);
  label_a14:
    bne(var_0, 3, label_a17);
    partyItemAdd(blessing_card, 1);
    b(label_a3a);
  label_a17:
    bne(var_0, 4, label_a1a);
    partyItemAdd(sacrifice_card, 1);
    b(label_a3a);
  label_a1a:
    bne(var_0, 5, label_a1d);
    partyItemAdd(magic mirror_card, 1);
    b(label_a3a);
  label_a1d:
    bne(var_0, 6, label_a20);
    partyItemAdd(inferno_card, 1);
    b(label_a3a);
  label_a20:
    bne(var_0, 7, label_a23);
    partyItemAdd(torrent_card, 1);
    b(label_a3a);
  label_a23:
    bne(var_0, 8, label_a26);
    partyItemAdd(gale_card, 1);
    b(label_a3a);
  label_a26:
    bne(var_0, 9, label_a29);
    partyItemAdd(quake_card, 1);
    b(label_a3a);
  label_a29:
    bne(var_0, 10, label_a2c);
    partyItemAdd(frigid_card, 1);
    b(label_a3a);
  label_a2c:
    bne(var_0, 11, label_a2f);
    partyItemAdd(thunderbolt_card, 1);
    b(label_a3a);
  label_a2f:
    bne(var_0, 12, label_a32);
    partyItemAdd(scorching_card, 1);
    b(label_a3a);
  label_a32:
    bne(var_0, 13, label_a35);
    partyItemAdd(wavelength_card, 1);
    b(label_a3a);
  label_a35:
    bne(var_0, 14, label_a38);
    partyItemAdd(pressure_card, 1);
    b(label_a3a);
  label_a38:
    partyItemAdd(nuclear_card, 1);
    b(label_a3a);
  label_a3a:
}

function BARTEN()
{
  label_a3b:
    unitAnimationPlay(shopkeeper, animation_28, 1);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_a5c);
    delayClear();
    delayWait(180);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_a59);
    unitIdleOn(shopkeeper);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_a56);
    delayClear();
    delayWait(900);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_a53);
    unitIdleOff(shopkeeper);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_a50);
    delayClear();
    delayWait(60);
    b(label_a3b);
    b(label_a52);
  label_a50:
    bne(var_0, 1, label_a52);
    b(label_a52);
  label_a52:
    b(label_a55);
  label_a53:
    bne(var_0, 1, label_a55);
    b(label_a55);
  label_a55:
    b(label_a58);
  label_a56:
    bne(var_0, 1, label_a58);
    b(label_a58);
  label_a58:
    b(label_a5b);
  label_a59:
    bne(var_0, 1, label_a5b);
    b(label_a5b);
  label_a5b:
    b(label_a5e);
  label_a5c:
    bne(var_0, 1, label_a5e);
    b(label_a5e);
  label_a5e:
}

function NOITEM()
{
    unitFacePlayer(shopkeeper);
    ref_a60 = bustupLoad(bustup_fd);
    bustupWait(ref_a60);
    ref_a62 = bustupAlloc(ref_a60, right, rgb(0,0,0));
    bustupFade(ref_a62, rgb(128,0,0), 30);
    ref_a64 = dialogAlloc();
    ref_a65 = msgShow(msg_114);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]売れる物、持ってないじゃないの～。[wait][clear]
***************************************/
    wait(ref_a65);
    dialogFree(ref_a64);
    ref_a68 = bustupFade(ref_a62, rgb(0,0,0), 10);
    bustupWait(ref_a68);
    bustupFree(ref_a62);
    li(var_5, 20);
}

function DECIDE_BUY()
{
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a6f = bustupLoad(bustup_fd);
    bustupWait(ref_a6f);
    ref_a71 = bustupAlloc(ref_a6f, left, rgb(0,0,0));
    bustupFade(ref_a71, rgb(128,0,0), 30);
    ref_a73 = dialogAlloc();
    choiceSetResult(1);
    ref_a75 = msgShow(msg_115);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]全部で、[var(msg_var_0)]円になるけど
[tab]いいかしらぁ～？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_a75);
    choiceGetResult(var_7);
    bne(var_7, 0, label_a7c);
    sndMusicPlay(sound_3037, 127);
    li(var_7, 1);
    b(label_a7f);
  label_a7c:
    bne(var_7, 1, label_a7f);
    li(var_7, 0);
    b(label_a7f);
  label_a7f:
    wait(ref_a75);
    dialogFree(ref_a73);
    ref_a81 = bustupFade(ref_a71, rgb(0,0,0), 10);
    bustupWait(ref_a81);
    bustupFree(ref_a71);
    li(var_5, 20);
}

function DECIDE_SELL()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_a89 = bustupLoad(bustup_fd);
    bustupWait(ref_a89);
    ref_a8b = bustupAlloc(ref_a89, left, rgb(0,0,0));
    bustupFade(ref_a8b, rgb(128,0,0), 30);
    ref_a8d = dialogAlloc();
    choiceSetResult(1);
    ref_a8f = msgShow(msg_116);
/***************************************
[color(yellow)]オバサン・五女[color(white)]
[tab]全部で、[var(msg_var_0)]円になるけど
[tab]いいかしらぁ～？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_a8f);
    choiceGetResult(var_7);
    bne(var_7, 0, label_a96);
    sndMusicPlay(sound_3037, 127);
    li(var_7, 1);
    b(label_a99);
  label_a96:
    bne(var_7, 1, label_a99);
    li(var_7, 0);
    b(label_a99);
  label_a99:
    wait(ref_a8f);
    ref_a9a = bustupFade(ref_a8b, rgb(0,0,0), 10);
    bustupWait(ref_a9a);
    bustupFree(ref_a8b);
    dialogFree(ref_a8d);
    li(var_5, 20);
}
