
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ディスカウント系の薬屋さんっていいわよね。
[tab]安いし、品揃えいいし。でも、ちょ～っと不安。
[tab]ちゃんと薬の事を知ってるかねぇ？
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]おかしいなぁ～？
[tab]最近の私、人生の裏街道を突っ走ってない？
[tab]極めて普通のＯＬだったのに、どーして？
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]なんかオリジナルのテーマソングっていいよね。
[tab]みんなで作ろっか？[tab]歌詞に名前入れたりして！
[tab]…うらら～うらら～とか良くない？[tab][delay(10)]…ヘイ！！
[wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]さ、最近では甘いものが好きな男だって多いぞ！
[tab]おかし職人だって男性の方が多いじゃないか。
[tab]あ、天野君はおかし作りとか好きかい？
[wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]一卵性の双子などは、他人に見分けがつかないが、
[tab]よく知る人…家族なんかには、すぐわかるらしい。
[tab]サトミ七姉妹も、わかる人にはわかるんだろう？
[wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
[tab]最近この手の薬屋チェーンで、全店員に薬剤師の
[tab]免許を取らせた所があるそうだ。ここはどうかな？
[tab]…はぁ？[tab][delay(10)]ヤクザ医師？[tab][delay(10)]…あ、[delay(5)]天野君…
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]警察を信じてくれ…とは言えないな。
[tab]ただ、勘違いはしないで欲しい。
[tab]不正などしない、正しい警官もいるんだ。
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]サトミタダシ店内で流れる曲に洗脳効果がある！
[tab]…との疑いか。…捜査の必要があるかも？
[tab]しかし、今はそれどころじゃないな。
[wait][clear][end]

msg_9:
[color(yellow)]かたおか[color(white)]
[tab]出ないハズなので削除
[wait][clear][end]

msg_10:
[color(yellow)]パオフゥ[color(white)]
[tab]すげ～なぁ、このダイエット関連商品の量！
[tab]薬に頼り過ぎ！[tab]みんな自分に甘いんだよなぁ。
[tab]女は甘いもんが好きだから仕方ねぇか？
[wait][clear][end]

msg_11:
[color(yellow)]パオフゥ[color(white)]
[tab]そっくりな血縁者とその違い…ワインと同じだな。
[tab]同じ種のブドウを使っても、作った畑や収穫した
[tab]時期で差が出る。銘柄だけじゃわからねぇ差だ。
[wait][clear][end]

msg_12:
[color(yellow)]パオフゥ[color(white)]
[tab]他社と競争になった時、武器となるのは何か？
[tab]それは価格と信頼だ。もし価格に差がねぇのなら
[tab]客はみな、信頼できる方へ行くんじゃねぇか？
[wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]警察やマスコミを信じてると、見える筈のものまで
[tab]見えなくなるんだよ。ちょっとでも調べてみな。
[tab]とんでもねぇ事件が起きてる事に気が付くぜ？
[wait][clear][end]

msg_14:
[color(yellow)]パオフゥ[color(white)]
[tab]酒と歌、昔から切っても切れない関係だが…
[tab]カラオケだけは未だに馴染めんな。
[wait][clear][end]

msg_15:
[color(yellow)]南条[color(white)]
[tab]噂が現実になるなんて、未だに信じ難い話だ。
[tab]しかし、その様な現実の中に生きていたら
[tab]気付くわけの無い事かもな…
[wait][clear][end]

msg_16:
[color(yellow)]南条[color(white)]
[tab]まただ…またこのチェーン店の曲が…あぁ！
[tab]俺の頭の中でサトミタダシの曲がループしている！
[tab]…天野さんも頭から離れない曲、あります？
[wait][clear][end]

msg_17:
[color(yellow)]エリー[color(white)]
[tab]私やＫｅｉの知らないところで、
[tab]様々なＡｃｃｉｄｅｎｔが起きていたのですね。
[tab]みなさん、ご苦労さまです。
[wait][clear][end]

msg_18:
[color(yellow)]エリー[color(white)]
[tab]ＳＡＴＯＭＩＴＡＤＡＳＨＩといえば…
[tab]Ｋｅｉはここの曲が気に入ってるらしいですわ。
[tab]気が付くと、いつも歌っていますもの。
[wait][clear][end]

msg_19:
[color(yellow)]サラリーマン[color(white)]
[tab]チャラララ～𝅘𝅥𝅮[delay(30)]
[tab]はっ！？[tab]この曲はどこかで聞いたことが！？
[tab]チャララララ～ラランランラン𝅘𝅥𝅮
[wait][clear][end]

msg_20:
[color(yellow)]サラリーマン[color(white)]
[tab]ノォォォーッ！！[tab]この曲が脳を駆け巡るー！[tab]
[tab]店から出れば開放されるのだが…[tab]
[tab]それはできなぁーい！[tab]理由は言えなぁーい！
[wait][clear][end]

msg_21:
[color(yellow)]サラリーマン[color(white)]
[tab]もーイヤ！[tab][tab]もー勘弁！[tab]
[tab]いつまでここでこの曲を聴きつづけねばならんの？
[tab]永遠！？[tab]そんなぁぁぁ！！！
[wait][clear][end]

msg_22:
[color(yellow)]顔色の悪い男[color(white)]
[tab]あ、君もドラッグ漬けかい？[tab]僕もそうなのさ…
[tab]だけど最近は、アイドル漬け…
[tab]今はＭＵＳＥＳにドップリなのさ。
[wait][clear][end]

msg_23:
[color(yellow)]顔色の悪い男[color(white)]
[tab]もしかして良くない薬とか使ってたのかな…
[tab]薬は正しく使わ…グフッグフッ。気持ち悪ぅ。
[tab]…ＪＯＫＥＲ呪い？[tab]そんなの興味無いよ。
[wait][clear][end]

msg_24:
[color(yellow)]顔色の悪い男[color(white)]
[tab]あぁ身が軽い、心も軽い～
[tab]やっぱり僕は穢れてたんだなぁ～
[tab]薬よさようなら～レッツ、明るい未来～
[wait][clear][end]

msg_25:
[color(yellow)]牧村[color(white)]
[tab]キミ、知ってるかい？
[tab]ここのオバサンってさぁ、七人姉妹なんだよ！
[tab]しかも、皆同じ顔なんだぜ？
[wait][clear][end]

msg_26:
[color(yellow)]オバサン・五女[color(white)]
[tab]はいはい、いらっしゃいませ～！！
[tab]今日もせっせと全国制覇！
[tab]さぁ、何が欲しいのかしら？
[wait][clear][end]

msg_27:
[color(yellow)]オバサン・五女[color(white)]
[tab]はいはい、いらっしゃいませ～！！
[tab]ここは初めて？[tab]うひょひょひょ！！

[wait][clear][end]

msg_28:
[color(yellow)]オバサン・五女[color(white)]
[tab]いらっしゃいま…あらぁ！！
[tab]いつもどーもなのねー！[tab]うひょひょひょ！！

[wait][clear][end]

msg_29:
[color(yellow)]オバサン・五女[color(white)]
[tab]サービスするから、いっぱい買ってねー
[choice(6)]消費物を買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_30:
[color(yellow)]オバサン・五女[color(white)]
[tab]さぁ、何を売りたいのかしらぁ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_31:
[color(yellow)]オバサン・五女[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
売買の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_32:
[color(yellow)]オバサン・五女[color(white)]
[tab]うひょひょひょ！！[delay(10)]
[tab]はいはい。
[tab]他に用はあるかしらぁ？
[choice(6)]消費物を買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_33:
[color(yellow)]オバサン・五女[color(white)]
[tab]さぁ、何を売りたいのかしら？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_34:
[color(yellow)]オバサン・五女[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
売買の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_35:
[color(yellow)]オバサン・五女[color(white)]
[tab]うひょひょひょ！[tab]薬局サトミタダシは、
[tab]遂に全国制覇に向け動き出したのよー！！
[tab]手始めはこの珠閒瑠市なのよー！！
[wait][clear][end]

msg_36:
[color(yellow)]オバサン・五女[color(white)]
[tab]あたしらが洗脳してる？[tab]うひょひょひょ！！
[tab]そんなのデタラメよー！
[tab]サトミ七姉妹を馬鹿にしないでよねェ～
[wait][clear][end]

msg_37:
[color(yellow)]オバサン・五女[color(white)]
[tab]穢れ祓いの講演会が大人気ですってね～
[tab]マッタク、芸能人に何が出来るって言うのよー！
[tab]…お客を少し分けて欲しいわ～…シクーッ！
[wait][clear][end]

msg_38:
[color(yellow)]オバサン・五女[color(white)]
[tab]サトミタダシは年中無休よ！
[tab]また来てちょうだぁ～い！
[tab]うひょひょひょひょ！！
[wait][clear][end]

msg_39:
ＭＢＩＴ[tab]ＡＩＳ[tab]６７
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_40:
ＥＢＩＴ[tab]Ｅ００３７
警察署[half_tab]受付、終了
びっとお～んッ！！
[wait][clear][end]

msg_41:
ＥＢＩＴ[tab]Ｅ００３８
「詐欺男を確保」
びっとお～んッ！！
[wait][clear][end]

msg_42:
ＥＢＩＴ[tab]Ｅ００３Ｅ
「ゴールドクリア」「うらら編入」
びっとお～んッ！！
[wait][clear][end]

msg_43:
ＥＢＩＴ[tab]Ｅ００４３
「クラブクリア」
びっとお～んッ！！
[wait][clear][end]

msg_44:
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear][end]

msg_45:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_46:
[color(yellow)]オバサン・五女[color(white)]
[tab]うひょひょひょ。
[tab]「売買」についてねぇ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]まずは、購入の説明なのねぇ～。
[tab]うちの店で「消費物を買う」を選ぶと
[tab]消費アイテムを買うことができるわよぉ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]あっ、そうそう、アイテムは持てる数が
[tab]決まってるからねぇ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]次に、売却の説明なのねぇ～。
[tab]「アイテムを売る」を選んで、まず種類を決めて、
[tab]次に売りたいものを選んでねぇ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]買取価格は元値の約半額くらいよぉ～。
[tab]あと、装備中の物は売ることができないからねぇ～。
[tab]それと、物によっては買取できない物もあるわよぉ～。
[wait][clear][color(yellow)]オバサン・五女[color(white)]
[tab]こんなとこかしらぁ～。
[tab]うひょひょひょ。
[wait][clear][end]

msg_47:
[color(yellow)]オバサン・五女[color(white)]
[tab]売れる物、持ってないじゃないの～。[wait][clear][end]

msg_48:
[color(yellow)]オバサン・五女[color(white)]
[tab]全部で、[var(msg_var_0)]円になるけど
[tab]いいかしらぁ～？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_49:
[color(yellow)]オバサン・五女[color(white)]
[tab]全部で、[var(msg_var_0)]円になるけど
[tab]いいかしらぁ～？
[choice(2)]はい
いいえ
[end_choice][clear][end]
