
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]係員[color(white)]
[tab]あらあらギブアップデ～スか？
[tab]それとも今のは下調べ？
[tab]がんばれ、がんばれ、お客サン！！
[wait][clear][end]

msg_2:
[color(yellow)]係員[color(white)]
[tab]あらあら、ギブデ～スか？
[tab]さすがのお客様もこの第二ラウンドは過酷な様子。
[tab]でもでもがんばってほしいデ～ス！！
[wait][clear][end]

msg_3:
[color(yellow)]係員[color(white)]
[tab]ブラボ～！！
[tab]誰がブラボ～かって、あなたがブラボ～！！
[tab]よくぞ無事にゴールなさいました！！[wait][clear][color(yellow)]係員[color(white)]
[tab]では！！[tab]賞金授与とまいりたいところデ～スが、
[tab]そこは遊びの宝庫、ムー大陸。
[tab]ただの授与じゃつまらないデ～ス。[wait][clear][color(yellow)]係員[color(white)]
[tab]さァ、いくらになるかはお客様の努力次第。
[tab]○ボタン連打で
[tab]バンバン賞金増やしてください！！[wait][clear][color(yellow)]係員[color(white)]
[tab]制限時間はたったの１０秒！！
[tab]指の準備はよろしいデ～スか？
[tab]では行きますよ！！[tab]スタートゥ！！！[wait][clear][end]

msg_4:
[delay(0)][unk2f(0)][tab][var(msg_var_0)]円[wait][clear][end]

msg_5:
[color(yellow)]係員[color(white)]
[delay(2)][unk2f(2)][tab]はい、終了ーデ～ス！！！[end]

msg_6:
[wait][clear][end]

msg_7:
[color(yellow)]係員[color(white)]
[tab]では口惜しい集計結果発表！！
[tab]ななんと、[var(msg_var_1)]円！！
[tab]自動連射使ってないでしょうね！？[wait][clear][color(yellow)]係員[color(white)]
[tab]まァ仕方ないデ～ス！
[tab]お客様は神様デ～ス！
[tab]ご利用、ありがとうございました！！[wait][clear][end]

msg_8:
[color(yellow)]係員[color(white)]
[tab]ヤーフー！！
[tab]コングラッチュレーショーン！！
[tab]おめでとうデース！！[wait][clear][color(yellow)]係員[color(white)]
[tab]あなたは凄い、素晴らしい！！
[tab]女の私も惚れ惚れする逞しさ！！
[tab]エクセレントデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]無事にアイテムをゲットして、
[tab]ゴールしたあなたには、
[tab]お待ちかねの賞金ターイムデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]さァ、今回も行きますよォ～
[tab]いくらになるかは、あなた次第！
[tab]○ボタン連打で大金をゲットしてください。[wait][clear][color(yellow)]係員[color(white)]
[tab]制限時間は約１０秒！！
[tab]ケイレンする準備はいいですかぁ？
[tab]ではよォ～い…スタートゥ！！[wait][clear][end]

msg_9:
[delay(0)][unk2f(0)][tab][var(msg_var_0)]円[wait][clear][end]

msg_10:
[color(yellow)]係員[color(white)]
[delay(2)][unk2f(2)][tab]はい、終了ーデ～ス！！！[end]

msg_11:
[wait][clear][end]

msg_12:
[color(yellow)]係員[color(white)]
[tab]では口惜しい集計結果発表！！
[tab]ななんと、[var(msg_var_1)]円！！
[tab]自動連射使ってないでしょうね！？[wait][clear][color(yellow)]係員[color(white)]
[tab]まァ仕方ないデ～ス！
[tab]お客様は神様デ～ス！
[tab]クリア、おめでとうデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]ちなみに、今日をもちまして、
[tab]スペシャルキャンペーンは終了デ～ス！
[tab]今の今までありがとうございましたァ！！
[wait][clear][end]

msg_13:
[color(yellow)]係員[color(white)]
[tab]もうスペシャルキャンペーンは終了ですよ。
[tab]だからこの奥も準備中デ～ス。
[tab]はい。もう開きません。
[wait][clear][end]

msg_14:
[color(yellow)]係員[color(white)]
[tab]ラウンド２は１より過酷デ～ス！
[tab]だけどあなたならきっと大丈夫デ～ス！！
[tab]ちなみにリップサービスデ～ス♥
[wait][clear][end]

msg_15:
[color(yellow)]係員[color(white)]
[tab]タイムアタックダンジョン、
[tab]ラウンド２、タク帽争奪戦！！
[tab]より激しく、より熱いこのアトラクション！！
[wait][clear][end]

msg_16:
[tab]チャレンジするデ～スか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_17:
[color(yellow)]係員[color(white)]
[tab]あゥ…
[tab]それはそれは残念な物語…
[tab]私は悲しいのデ～ス…
[wait][clear][end]

msg_18:
[color(yellow)]係員[color(white)]
[tab]オーゥ！！[tab]ユーアーナイスバデー！！
[end]

msg_19:
[tab]では、相変わらず神秘でも恐怖でもない扉、
[tab]開きませい！！
[wait][clear][end]

msg_20:
[color(yellow)]係員[color(white)]
[tab]はい、開きましたァ！
[tab]中に入った途端、ゲームスタートデ～ス！！
[tab]足腰立たなくなるまで頑張って欲しいデ～ス！！
[wait][clear][end]

msg_21:
[color(yellow)]係員[color(white)]
[tab]ジャーン！！
[tab]何がジャーンって、あなたがジャーン！！
[tab]どうジャーンかって、こうジャーン！！[wait][clear][color(yellow)]係員[color(white)]
[tab]ついに、第二ラウンド！
[tab]ムー大陸タイムアタックダンジョン、
[tab]呪いのタク帽争奪戦ー！！[tab]が始まりました！[wait][clear][end]

msg_22:
[tab]参加するなら説明聞くデ～ス！！
[choice(2)]聞く
聞かない
[end_choice][clear][end]

msg_23:
[color(yellow)]係員[color(white)]
[tab]オーゥ…
[tab]それは残念デ～ス。
[wait][clear][end]

msg_24:
[color(yellow)]係員[color(white)]
[tab]その扉の奥は、前回以上に広大な迷宮デ～ス。
[tab]先には、前回以上に凶悪なボスモンスターが、
[tab]今か今かと待ち構えているデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]無事に凶悪なボスモンスターを倒し、
[tab]秘密のお宝をゲットして戻ってこれれば…
[tab]またまた賞金を差し上げるデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]だけど、もち制限時間つきデ～ス！！
[tab]時間内に戻れなければアウトデ～ス！！
[tab]例えモンスターを倒していてもアウトデ～ス！[wait][clear][color(yellow)]係員[color(white)]
[tab]そうなったら賞金は無し、
[tab]お宝も没収。もちろん中ではセーブ不可デ～ス！！
[tab]だけど途中で出るのは可能デ～ス！！[wait][clear][end]

msg_25:
[tab]さァ、最後の聖戦へ旅立て勇者よ！！
[choice(2)]挑戦する
やめておく
[end_choice][clear][end]

msg_26:
[color(yellow)]係員[color(white)]
[tab]あゥ…
[tab]それはそれは残念な物語…
[tab]私は悲しいのデ～ス…
[wait][clear][end]

msg_27:
[color(yellow)]係員[color(white)]
[tab]オーゥ！！[tab]ユーアーナイスバデー！！
[end]

msg_28:
[tab]では、相変わらず神秘でも恐怖でもない扉、
[tab]開きませい！！
[wait][clear][end]

msg_29:
[color(yellow)]係員[color(white)]
[tab]はい、開きましたァ！
[tab]中に入った途端、ゲームスタートデ～ス！！
[tab]足腰立たなくなるまで頑張って欲しいデ～ス！！
[wait][clear][end]

msg_30:
[color(yellow)]係員[color(white)]
[tab]次回の開催は～
[tab]まだ未定デ～ス！！
[tab]お楽しみに～！！
[wait][clear][end]

msg_31:
[color(yellow)]係員[color(white)]
[tab]最近、中で本物の怪物を見たって噂聞くデ～ス！
[tab]きっと嘘、偽りだと思うけど…
[tab]こういう場合、大概本当デ～ス！
[wait][clear][end]

msg_32:
[color(yellow)]係員[color(white)]
[tab]いらっしゃいデ～ス！！
[tab]いらっしゃいデ～ス！！
[tab]今なら無料でダンジョン楽しめるデ～ス！！
[wait][clear][end]

msg_33:
[tab]さァ、きたれ勇者よ、集え勇者よ～
[choice(2)]挑戦する
やめておく
[end_choice][clear][end]

msg_34:
[color(yellow)]係員[color(white)]
[tab]それは残念デ～ス！！
[tab]気が変わったら、
[tab]カモンベイベーデ～ス！！
[wait][clear][end]

msg_35:
[color(yellow)]係員[color(white)]
[tab]オー・ユーアー・ナイスギャ～ウ！
[end]

msg_36:
[tab]では！[tab]神秘でも恐怖でもない扉…
[tab]オープンデ～ス！！
[wait][clear][end]

msg_37:
[color(yellow)]係員[color(white)]
[tab]中に入った途端、ゲームスタートデ～スよ。
[tab]頑張ってくださいデ～ス！！
[wait][clear][end]

msg_38:
[color(yellow)]係員[color(white)]
[tab]ラッキーデ～ス！！
[tab]誰がラッキーかって、お客様がラッキーデ～ス！！
[tab]どうラッキーかって、こうラッキーデ～ス！[wait][clear][color(yellow)]係員[color(white)]
[tab]当ムー大陸では
[tab]スペシャルキャンペーンを実施中デ～ス！！
[tab]ワクワク、どんなキャンペーンデ～しょうか！！[wait][clear][end]

msg_39:
[tab]説明聞くデ～スか？
[choice(2)]聞く
聞かない
[end_choice][clear][end]

msg_40:
[color(yellow)]係員[color(white)]
[tab]お客様は、
[tab]アンラッキーデ～ス！
[wait][clear][end]

msg_41:
[color(yellow)]係員[color(white)]
[tab]オー・ユーアー・ラッキーギャ～ウ！
[tab]その扉の奥は、広大なダンジョンデ～ス！！
[tab]奥に、凶悪モンスターがいるデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]無事に凶悪モンスターを倒し、
[tab]秘密のお宝をゲットして戻ってこれれば…
[tab]なんと賞金を差し上げるデ～ス！！[wait][clear][color(yellow)]係員[color(white)]
[tab]だけど！！[tab]制限時間があるのデ～ス！！
[tab]制限時間内に戻れなければアウトデ～ス！！
[tab]例えモンスターを倒していてもアウトデ～ス！[wait][clear][color(yellow)]係員[color(white)]
[tab]そうなったら賞金は無し、
[tab]お宝も没収。もちろん中ではセーブ不可デ～ス！！
[tab]だけど途中で出るのは可能デ～ス！！[wait][clear][end]

msg_42:
[tab]さァ、きたれ勇者よ、集え勇者よ～
[choice(2)]挑戦する
やめておく
[end_choice][clear][end]

msg_43:
[color(yellow)]係員[color(white)]
[tab]それは残念デ～ス！！
[tab]気が変わったら、
[tab]カモンベイベーデ～ス！！
[wait][clear][end]

msg_44:
[color(yellow)]係員[color(white)]
[tab]オー・ユーアー・ナイスギャ～ウ！
[end]

msg_45:
[tab]では！[tab]神秘でも恐怖でもない扉…
[tab]オープンデ～ス！！
[wait][clear][end]

msg_46:
[color(yellow)]係員[color(white)]
[tab]中に入った途端、ゲームスタートデ～スよ。
[tab]頑張ってくださいデ～ス！！
[wait][clear][end]

msg_47:
[color(yellow)]係員[color(white)]
[tab]この奥は現在準備中デ～ス！！
[tab]え？[tab]ずっと準備中だろうって？
[tab]そんなことないデ～ス！！
[wait][clear][end]

msg_48:
[color(yellow)]うらら[color(white)]
[tab]おっおーう、ギャンブル～
[tab]私も賭け事にゃ目が無いからねぇ～
[tab]さーて、ど・れ・を・し・よ・う・かっなぁ～
[wait][clear][end]

msg_49:
[color(yellow)]うらら[color(white)]
[tab]…って、ありゃ。店主サンいないの？
[tab]んじゃ、コインに替えられないじゃないの！
[tab]ここってカジノじゃないの？
[wait][clear][end]

msg_50:
[color(yellow)]うらら[color(white)]
[tab]こんな時までカジノとは、さっすがマーヤ。
[tab]どんな時でもレッツ・ポジティブシンキングー！！
[tab]私だって負けないんだから！
[wait][clear][end]

msg_51:
[color(yellow)]うらら[color(white)]
[tab]さーて…
[tab]今日はどのゲームをするかな～
[end]

msg_52:
[tab]目指せ、億万長者！
[wait][clear][end]

msg_53:
[color(yellow)]うらら[color(white)]
[tab]たはァ…
[tab]うまくビンゴしてたのに…
[tab]赤なんかに賭けなきゃよかったよ…
[wait][clear][end]

msg_54:
[color(yellow)]うらら[color(white)]
[tab]なんか[tatsuya]君真剣ねぇ…
[end]

msg_55:
[tab]な、なんか遊んでちゃ悪いかな？
[tab]私もほどほどにしとこ…
[wait][clear][end]

msg_56:
[color(yellow)]うらら[color(white)]
[tab]あんな話を聞かされた後に
[tab]ギャンブルだなんて、マーヤも相当なもんよね。
[tab]ま…まあ、私もそうなんだけれども。
[wait][clear][end]

msg_57:
[color(yellow)]うらら[color(white)]
[tab]聞いてよマーヤ！！
[tab]私さっきフィーバー出しちゃったよ～
[tab]ラッキー！[end]

msg_58:
[tab]…ってここで運使っちゃまずい？[wait][clear][end]

msg_59:
[color(yellow)]うらら[color(white)]
[tab]結局人生なんてバクチの連続なのよねぇ。
[tab]この先どうなるか…
[tab]なんて、誰にも解らないんだから。
[wait][clear][end]

msg_60:
[color(yellow)]克哉[color(white)]
[tab]こうした遊技施設の多くは、
[tab]午後六時以降の、中学生以下の立ち入りは
[tab]禁止されている。[wait][clear][color(yellow)]克哉[color(white)]
[tab]だが…それを守らない子供が多いんだ。
[tab]歳を誤魔化す者も少なくない。
[tab]まぁ、干支を聞けば大体分かるがな。
[wait][clear][end]

msg_61:
[color(yellow)]克哉[color(white)]
[tab]天野君、
[tab]イライラする気持ちも分からんではないが、
[tab]現実逃避しても何も解決しないぞ。
[wait][clear][end]

msg_62:
[color(yellow)]克哉[color(white)]
[tab]どう言ったところで、
[tab]君がそれに従うとは思えんしな…
[tab]まぁ…ほどほどにしておけよ。
[wait][clear][end]

msg_63:
[color(yellow)]克哉[color(white)]
[tab]以前の[tatsuya]なら、
[tab]こうした店にも頻繁に出入りしていたのだろうが…
[tab]今のアイツは…いったいどうしたんだ？
[wait][clear][end]

msg_64:
[color(yellow)]克哉[color(white)]
[tab]天野君…君は[tatsuya]の話の続きより、
[tab]ギャンブルの方が気になるのかい…？
[wait][clear][end]

msg_65:
[color(yellow)]克哉[color(white)]
[tab]きっと天野君は「向こう側」でも
[tab]ギャンブル好きだったのだろうな…
[tab][tatsuya]に聞かなくても想像がつく。
[wait][clear][end]

msg_66:
[color(yellow)]克哉[color(white)]
[tab]時々、天野君の神経の図太さには感服する。
[tab]少なくとも僕には、街が空を飛び、
[tab]地上が滅亡目前という時に遊ぶ事はできん。
[wait][clear][end]

msg_67:
[color(yellow)]克哉[color(white)]
[tab]まだ大仕事が残っているんだ。
[tab]遊ぶのもほどほどにしておけよ。
[wait][clear][end]

msg_68:
[color(yellow)]パオフゥ[color(white)]
[tab]ここがカジノだって噂は俺も聞いたことがある。
[tab]もっとも、スロットが揃いやすいだの、
[tab]ビンゴが儲かるだの、中身はバラバラだったがな。
[wait][clear][end]

msg_69:
[color(yellow)]パオフゥ[color(white)]
[tab]カジノで遊んでる場合か？
[tab]まったく…お前と芹沢の共通点が
[tab]はっきりと見えた気がするぜ…
[wait][clear][end]

msg_70:
[color(yellow)]パオフゥ[color(white)]
[tab]ふん…
[tab]悪いが今は遊ぶ気分じゃねえんでな。
[tab]勝手にやっててくれ。
[wait][clear][end]

msg_71:
[color(yellow)]パオフゥ[color(white)]
[tab]今のゲームは、
[tab]どれも機械仕掛けばかりだな…
[end]

msg_72:
[tab]どうも安っぽくていけねぇ。
[wait][clear][end]

msg_73:
[color(yellow)]パオフゥ[color(white)]
[tab]こいつぁ、性分ってやつだろうが、
[tab]機械相手に賭け事をする気にはなれなくてな。
[tab]…スロット程度ならやってもいいが。
[wait][clear][end]

msg_74:
[color(yellow)]パオフゥ[color(white)]
[tab]くそっ…
[tab]芹沢がフィーバーで、なんで俺が…
[tab]納得できねぇ…
[wait][clear][end]

msg_75:
[color(yellow)]パオフゥ[color(white)]
[tab]こんな時までカジノか…
[tab]へっ、まあ好きにやんな。
[tab]止めやしねぇよ。
[wait][clear][end]

msg_76:
[color(yellow)]南条[color(white)]
[tab]そう言えば昔の仲間にも、事件解決そっちのけで
[tab]ゲームセンターに行きたがる奴がいましたが…
[tab]まさか天野さんまで、そんな事はないでしょうね。
[wait][clear][end]

msg_77:
[color(yellow)]南条[color(white)]
[tab]辛い戦いの中にあっては、
[tab]時に気晴らしも良いでしょう…
[end]

msg_78:
[tab]しかし！[tab]何事もケジメが大切ですよ。
[wait][clear][end]

msg_79:
[color(yellow)]南条[color(white)]
[tab]己が志を貫くためには…
[tab]時に強運も必要…か。
[tab]ここで鍛えて行くのも良いかもな。
[wait][clear][end]

msg_80:
[color(yellow)]南条[color(white)]
[tab]今はとても遊ぶ気にはなれません。
[tab]放っておいてください。
[wait][clear][end]

msg_81:
[color(yellow)]エリー[color(white)]
[tab]フフフ、最近のＢｉｎｇｏＧａｍｅは、
[tab]仕掛けが面白いですわね。
[tab]こうして見てるだけでも楽しめますわ。
[wait][clear][end]

msg_82:
[color(yellow)]エリー[color(white)]
[tab]ここの方たちに
[tab]外の状況は関係無いのでしょうか…
[tab]なんだか…複雑な心境ですわ…
[wait][clear][end]

msg_83:
[color(yellow)]エリー[color(white)]
[tab]私、Ｇａｍｂｌｅをする前には、
[tab]必ずその日の運勢を占う事にしていますの。
[tab]同じやるなら、勝ちたいですものね。
[wait][clear][end]

msg_84:
[color(yellow)]エリー[color(white)]
[tab]ごめんなさい…
[tab]少し…一人にしてくださる？
[tab]考えたい事があるんです。
[wait][clear][end]

msg_85:
[color(yellow)][tatsuya][color(white)]
[tab]こっちじゃカジノになってないのか…
[tab]まあ…その方がいいか。
[wait][clear][end]

msg_86:
[color(yellow)][tatsuya][color(white)]
[tab]こっちじゃカジノになってないのか…
[tab]まあ…その方がいいか。
[wait][clear][end]

msg_87:
[color(yellow)][tatsuya][color(white)]
[tab]こうしている間にも、
[tab]この世界は崩壊の道を辿っている…
[tab]やはり俺は…一人でいるべきなんだ。
[wait][clear][end]

msg_88:
[color(yellow)][tatsuya][color(white)]
[tab]今もこの世界は
[tab]少しずつ消滅していってるんだ。
[tab]グズグズしてはいられない。
[wait][clear][end]

msg_89:
[color(yellow)][tatsuya][color(white)]
[tab]パオフゥさん、
[tab]さっきから大分スロットに注ぎ込んでるけど…
[tab]注意しなくていいのか？
[wait][clear][end]

msg_90:
[color(yellow)][tatsuya][color(white)]
[tab]奴は、今もあの奥で
[tab]俺達が来るのを待っているんだ。
[tab]早く行こう、舞耶姉！
[wait][clear][end]

msg_91:
[color(yellow)]ギャンブル好きの男[color(white)]
[tab]ギャンブルこそ男のロマン！
[tab]ギャンブルこそ私の人生そのもの！！
[tab]う～ん…今私は輝いている。
[wait][clear][end]

msg_92:
[color(yellow)]ギャンブル好きの男[color(white)]
[tab]ん…？[tab]何かね？
[tab]この私に何か用かな？
[tab]ギャンブルの挑戦ならいつでも受けるぞ。
[wait][clear][end]

msg_93:
[tab]用件を伺おうか。
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_94:
サツマゴンゾウ
[end]

msg_95:
[color(yellow)]ギャンブル好きの男[color(white)]
[tab]なんだって？
[tab]誰の事だね、それは。
[tab]私はそんな人は知らんよ。
[wait][clear][end]

msg_96:
[color(yellow)]ギャンブル好きの男[color(white)]
[tab]ゲッ！？[tab]な…なぜ私の本名を…
[tab]なに？[tab]人捜し？
[tab]私の捜索願が出ているのかね？
[wait][clear][color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[tab]と…という事は…まさか女房が…
[tab]し、しまった、こんな所にいた事がばれたら、
[tab]…またボコボコに…
[wait][clear][color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[tab]き…君、報せてくれた事には感謝する。
[tab]だが、女房にだけは内緒にしておいてくれ！
[tab]しらいしには私からよろしく伝えておくから！
[wait][clear][color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[tab]所詮、ギャンブルは男の世界。
[tab]女子供には理解できぬ世界なのだ。
[tab]フ…フフフフ。
[wait][clear][end]

msg_97:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_98:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_99:
[tab]ここでカジノが楽しめると聞きましてね、
[tab]はるばるやって来たのですが…
[tab]どうやら流言蜚語の類だったようだ。[wait][clear][end]

msg_100:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_101:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_102:
[tab]たしかゲームは、専用のコインを使って
[tab]行うという事だったが…コインどころか
[tab]店長までいないではないか。[wait][clear][end]

msg_103:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_104:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_105:
[tab]新世塾とやらが人の穢れを集めているとか…
[tab]確かに業深き人間は、穢れを集めるには
[tab]打ってつけの素材でしょうな…
[wait][clear][end]

msg_106:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_107:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_108:
[tab]もっとも、穢れという言い方は正しくない。
[tab]人は皆、欲を原動力として生きているのです。
[tab]それを否定してしまっては、生きる意味がない。
[wait][clear][end]

msg_109:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_110:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_111:
[tab]世界一のギャンブラーを志す以上、
[tab]如何なる賭けにも命を賭して臨まねば。
[tab]勝負とは、そういうものだ。
[wait][clear][end]

msg_112:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_113:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_114:
[tab]時に社会を乱す混乱は、
[tab]全て人が持つ迷いから生ずるもの。
[tab]私はそれが嫌いでしてね。
[wait][clear][end]

msg_115:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_116:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_117:
[tab]今世間が何に騒いでいるのかは知りませんが、
[tab]所詮それも、迷いが生み出した結果。
[tab]まったく興味ありませんね。
[wait][clear][end]

msg_118:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_119:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_120:
[tab]世界が本当に滅亡するかどうか…
[tab]一つ賭けてみないかね？
[tab]ふふふ…少し不謹慎だったかな？
[wait][clear][end]

msg_121:
[color(yellow)]ギャンブル好きの男[color(white)]
[end]

msg_122:
[color(yellow)]サツマ[tab]ゴンゾウ[color(white)]
[end]

msg_123:
[tab]外で勇ましいお嬢サンを見かけたよ。
[tab]剣片手に、天誅軍と戦っていた…
[tab]そんな事をして、何が変わるというのだ…
[wait][clear][end]

msg_124:
[color(yellow)]店長[color(white)]
[tab]いらっしゃいませ。ムー大陸へようこそ。
[tab]コインチェンジと景品の交換は、
[tab]こちらで承ります。
[wait][clear][end]

msg_125:
[color(yellow)]店長[color(white)]
[tab]いらっしゃいませ。ムー大陸へようこそ。
[tab]コインチェンジと景品の交換は、
[tab]こちらで承ります。[wait][clear][color(yellow)]店長[color(white)]
[tab]…って…キミ…あれ？
[tab]なんか相性いい気がする…
[tab]こんな俺ってどこかヘン？[wait][clear][color(yellow)]店長[color(white)]
[tab]ヘンかも知れないけど、
[tab]ヤッパ相性良さそうだし…
[tab]しゃあねぇ…オマケしてやるか。[wait][clear][end]

msg_126:
[color(yellow)]店長[color(white)]
[tab]やっぱ人間関係、相性の良し悪しがデカイよねぇ。
[tab]ま、でもアレじゃない？[tab]ウチらバッチリでしょ？
[tab]だから特別にマケたげる。…喜べや。
[wait][clear][end]

msg_127:
[color(yellow)]店長[color(white)]
[tab]おっし、よく来た！
[tab]…で、何の用？
[tab]予想はつくけど。
[wait][clear][end]

msg_128:
[color(yellow)]店長[color(white)]
[tab]なんなりと言えや。
[choice(5)]コインを購入する
景品と交換する
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_129:
[color(yellow)]店長[color(white)]
[tab]何と交換するんだ？
[choice(5)][if(EBIT_SINARIOFF)]非表示項目
消費物と交換する
[if_all(EBIT_SINARIOFF)]武器と交換する
アクセサリーと交換する
カードと交換する
[end_choice][clear][end]

msg_130:
[color(yellow)]店長[color(white)]
[tab]何が聞きたいんだ？
[choice(3)]世間話をする
コインと景品の説明を聞く
[if(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_131:
[color(yellow)]店長[color(white)]
[tab]えー、まだなんかあんの？[delay(15)]
[tab]…って、うそうそ。
[tab]何でも言っとくれ。
[choice(5)]コインを購入する
景品と交換する
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_132:
[color(yellow)]店長[color(white)]
[tab]何と交換するんだ？
[choice(5)][if(EBIT_SINARIOFF)]非表示項目
消費物と交換する
[if_all(EBIT_SINARIOFF)]武器と交換する
アクセサリーと交換する
カードと交換する
[end_choice][clear][end]

msg_133:
[color(yellow)]店長[color(white)]
[tab]何が聞きたいんだ？
[choice(3)]世間話をする
コインと景品の説明を聞く
[if(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_134:
[color(yellow)]店長[color(white)]
[tab]…ナニ？[tab]この奥？[tab]ムッシー？
[tab]あーあれ、ただのハリボテだよ。
[tab]アトラクション用のな。
[wait][clear][end]

msg_135:
[color(yellow)]店長[color(white)]
[tab]よく出来てんだろ？
[tab]子供が見たら泣いちゃうよな？
[tab]…そりゃ言い過ぎ？
[wait][clear][end]

msg_136:
[color(yellow)]店長[color(white)]
[tab]はぁ？[tab]呪いのタクシーってナニよ？
[tab]死傷者も出た大事故？
[tab]そんなの知らないってば。
[wait][clear][end]

msg_137:
[color(yellow)]店長[color(white)]
[tab]前の通りでタクシーが事故ったことならあるけど、
[tab]ソレとカン違いしてんじゃないか？
[tab]…その前に、店の中を車が走れるかっての。
[wait][clear][end]

msg_138:
[color(yellow)]店長[color(white)]
[tab]奥にいたカップル、講演会に行ったみたいだね。
[tab]ま…行くのは勝手だし。
[tab]でも俺は行かないよ。一応仕事中だし。
[wait][clear][end]

msg_139:
[color(yellow)]店長[color(white)]
[tab]トリフネ伝説だの新世塾だの、
[tab]この街って賑やかだよなぁ…
[tab]ここもそうだけど。
[wait][clear][end]

msg_140:
[color(yellow)]店長[color(white)]
[tab]望龍術で世界が滅亡するってホントなの？
[tab]だって望龍術って占いでしょ？
[tab]占いで世界をどうこうできるもんなの？
[wait][clear][end]

msg_141:
[color(yellow)]店長[color(white)]
[tab]やな噂聞いちゃってさぁ…俺、まじブルーモード。
[tab]いや実は些細なことなんだけど、
[tab]鳴海区の工事現場でトリフネ掘ってんだって。
[wait][clear][color(yellow)]店長[color(white)]
[tab]じゃ滅亡とかの噂もホントかいな？
[tab]でも、トリフネに乗ってれば助かるってのも
[tab]都合良すぎる気がするし…なんか嫌だね。
[wait][clear][end]

msg_142:
[color(yellow)]店長[color(white)]
[tab]君さ、街が空を飛んでる夢って見たことある？
[tab]…無いよね？[tab]あってもどうせ夢の話だし…
[tab]だけど飛んでんだよなぁ…あれって正夢？
[wait][clear][end]

msg_143:
[color(yellow)]店長[color(white)]
[tab]俺ってさぁ、眼鏡してっけど、
[tab]意外と目が良いんだよねぇ。
[tab]それで空見てたんだけどさぁ…見えたんだよ…
[wait][clear][color(yellow)]店長[color(white)]
[tab]勿体つけずに言うと道なんだけどさ。
[tab]空に道があったのよ、迷路みたいなやつ…
[tab]いやいや、ホントだって、信じれや！
[wait][clear][end]

msg_144:
[color(yellow)]店長[color(white)]
[tab]まぁ、いろいろあるだろうけど、
[tab]また遊びに来てよ。
[tab]それなりに歓迎はするし。
[wait][clear][end]

msg_145:
[color(yellow)]ゲーム台[color(green)]
[tab]ブラックジャック
[tab]「ＪＯＩＮ[tab]ＦＯＲＣＥＳ」がある。[color(white)][wait][clear][end]

msg_146:
[color(green)][tab]ブラックジャック[tab]「ＪＯＩＮ[tab]ＦＯＲＣＥＳ」
[tab]プレイしますか？[color(white)]
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_147:
[color(yellow)]ゲーム台[color(green)]
[tab]ビンゴゲーム
[tab]「ＦＯＲＴＵＮＥ’Ｓ[tab]ＲＥＥＬ」
[tab]がある。[color(white)][wait][clear][end]

msg_148:
[color(green)][tab]「ＦＯＲＴＵＮＥ’Ｓ[tab]ＲＥＥＬ」
[tab]プレイしますか？[color(white)]
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_149:
[color(yellow)]ゲーム台[color(green)]
[tab]ポーカー
[tab]「ＷＩＬＤ[tab]９」
[tab][var(msg_var_0)]番台がある。[color(white)]
[wait][clear][end]

msg_150:
[color(green)][tab]ポーカー[tab]「ＷＩＬＤ[tab]９」
[tab][var(msg_var_0)]番台[tab]プレイしますか？[color(white)]
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_151:
[color(yellow)]ゲーム台[color(green)]
[tab]スロットマシン
[tab]「ＡＲＯＵＳＥ[tab]ＢＬＡＮＫ」
[tab][var(msg_var_0)]番台がある。[color(white)]
[wait][clear][end]

msg_152:
[color(green)][tab]スロット[tab]「ＡＲＯＵＳＥ[tab]ＢＬＡＮＫ」
[tab][var(msg_var_0)]番台[tab]プレイしますか？[color(white)]
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_153:
[color(green)][tab]電源が入っていないようだ。[color(white)][wait][clear][end]

msg_154:
[color(green)][tab]鍵がかかっている。[color(white)][wait][clear][end]

msg_155:
[tab]えらびませい！！
[choice(5)]カジノにする
Ｒ１進入可能
Ｒ２進入可能
賞金処理
ぬける
[end_choice][clear][end]

msg_156:
[var(msg_var_5)][wait][clear][end]

msg_157:
[var(msg_var_5)][wait][clear][end]

msg_158:
[var(msg_var_5)][wait][clear][end]

msg_159:
[color(yellow)]店長[color(white)]
[tab]説明か…
[tab]だりーけどこれも仕事だからなぁ。
[tab]よし、まずは「コイン」についてだな。
[wait][clear][color(yellow)]店長[color(white)]
[tab]俺に話しかけて「コインを購入する」を選べば、
[tab]お金を店内で使えるコインに両替してやるよ。
[wait][clear][color(yellow)]店長[color(white)]
[tab]もうひとつは「景品交換」だな。
[tab]「景品と交換する」を選べば、ゲームで増やしたコインを
[tab]珍しいアイテムと交換してやるよ。
[wait][clear][color(yellow)]店長[color(white)]
[tab]コインはお金には両替できねぇけど、
[tab]景品のラインナップはなかなかのもんだと思うぜ。
[tab]せいぜいがんばって稼いでくれや。
[wait][clear][end]

msg_160:
[color(yellow)]警備員[color(white)]
[tab]これでも仕事中です。邪魔しないで下さい。
[tab]店内でのもめ事もご遠慮下さい。
[tab]…事後処理が面倒なんでね。
[wait][clear][end]

msg_161:
[color(yellow)]警備員[color(white)]
[tab]この奥の警備をしていたのですが…
[tab]大変な怪物を見てしまった。
[tab]あれは、[color(orange)]ムー大陸[color(white)]の主…[color(orange)]ムッシー[color(white)]！？
[wait][clear][end]

msg_162:
[color(yellow)]警備員[color(white)]
[tab]あんなものが居ては、仕事も手に付かない！
[tab]何かあったら報告書も書かなきゃいけないし…
[tab]どうでもいい、誰かなんとかしてくれ！
[wait][clear][end]

msg_163:
[color(yellow)]警備員[color(white)]
[tab]出来れば！！[tab]…証拠が欲しいなぁ。
[tab]報告書だけじゃ信じてもらえないだろうし。
[tab]誰か！[tab]お願い！！
[wait][clear][end]

msg_164:
[color(yellow)]警備員[color(white)]
[tab]この目で見たんだよ！
[tab]あれこそ、このムー大陸の主…
[tab]ムッシーなんだ！！
[wait][clear][end]

msg_165:
[color(yellow)]警備員[color(white)]
[tab]なに、これ？
[tab]恐竜の化石かなんか？
[tab]…え、ムッシーの牙！？
[wait][clear][end]

msg_166:
[color(yellow)]警備員[color(white)]
[tab]あの化け物を倒したのかい！？
[tab]ありがとう！[tab]ホントにありがとう！
[tab]これで安心して仕事が出来るよ！
[wait][clear][end]

msg_167:
[color(yellow)]警備員[color(white)]
[tab]…いらないかもしれないけど、
[tab]これ受けとって。
[tab]一応、感謝の気持ち。
[wait][clear][end]

msg_168:
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear][end]

msg_169:
[color(yellow)]警備員[color(white)]
[tab]ムッシー、何も事件を起こさなかったな…
[tab]はっ、俺は何を期待してたんだ？
[tab]何も無いのが一番！[tab]…報告書も不要だし。
[wait][clear][end]

msg_170:
[color(yellow)]冬子[color(white)]
[tab]…初めまして。私は月影[tab]冬子。
[tab]セブンスに通うホラーな少女…[delay(15)]ケケケケ。
[tab]あら、ホントに初めてかしら？
[wait][clear][end]

msg_171:
[color(yellow)]冬子[color(white)]
[tab]…まぁいいわ。…ところで知ってる？
[tab]数ヶ月前、このムー大陸にタクシーが突っ込み、
[tab]数名の死傷者を出す大事故になった事…
[wait][clear][end]

msg_172:
[color(yellow)]冬子[color(white)]
[tab]恐らくそれは、[color(orange)]呪いのタクシー[color(white)]の仕業。
[tab]もしかしたら呪いのタクシーは、
[tab]今もこの[color(orange)]ムー大陸[color(white)]の中に潜んでいるのかも？
[wait][clear][end]

msg_173:
[color(yellow)]冬子[color(white)]
[tab]何のために？[delay(15)][tab]ケケケケ…[delay(15)]
[tab]人間を轢き殺すためよ！
[tab]それが呪いのタクシーなの！[delay(15)][tab]ケーッケケケ！
[wait][clear][end]

msg_174:
[color(yellow)]冬子[color(white)]
[tab]なんとか証拠を手に入れて、
[tab]愛読書「メー」に投稿したい…
[tab]証拠さえあれば、採用間違い無しなのに…
[wait][clear][end]

msg_175:
[color(yellow)]冬子[color(white)]
[tab]あの事故は、きっと呪いのタクシーの仕業。
[tab]感じるわ…呪いのタクシーは今もこのムー大陸に
[tab]潜んでいる！[delay(15)][tab]ケーッケケケ！
[wait][clear][end]

msg_176:
[color(yellow)]冬子[color(white)]
[tab]ああっ！[tab]あなたが持っているそれはっ！
[tab]呪いのタクシーが存在する証拠…[delay(15)]
[tab]って…あら？[delay(15)][tab]これは、[delay(15)]タク帽？
[wait][clear][end]

msg_177:
[color(yellow)]冬子[color(white)]
[tab]ヨット帽だったような気もするけど…
[tab]大丈夫っ、これこそ呪いのタクシーが実在した
[tab]という動かぬ証拠！
[wait][clear][end]

msg_178:
[color(yellow)]冬子[color(white)]
[tab]はいこれ、お礼よ。
[tab]ありがとね、[delay(15)]お・ば・さ・ん！
[tab][delay(30)]ケーッケケケ！
[wait][clear][end]

msg_179:
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear][end]

msg_180:
[color(yellow)]冬子[color(white)]
[tab]ケケケ、これで「メー」に呪いのタクシーの事を
[tab]投稿することが出来る…
[tab]私もメー族の仲間入りだわ…[delay(15)]ケーッケケケ！
[wait][clear][end]

msg_181:
[color(yellow)]店長[color(white)]
[tab]全部で、[var(msg_var_0)]円になるが、いいかい？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_182:
[color(yellow)]店長[color(white)]
[tab]全部で、コイン[var(msg_var_0)]枚になるが、いいかい？
[choice(2)]はい
いいえ
[end_choice][clear][end]
