
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ペルソナって、自分の人格の一部なんだよねぇ？
[tab]ということは…
[tab]わ、私にあんな一面がぁ！？
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]サトミタダシって急成長企業なんだって。
[tab]向かうところ敵無しって感じらしいよ。
[tab]あ、女子高生が敵だっけ？
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]…ごめん、ごめんネェ？
[tab]でも、ほら、ＪＯＫＥＲ呪いをした人が
[tab]ＪＯＫＥＲになるって確認出来たじゃん！
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]相手の想いが強過ぎると、
[tab]素直になれなくなっちゃうのよねぇ～
[tab]杏奈ちゃんもきっとそうだったんだよ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]あの写真の女のコ…どっかで見た事あんだよねぇ。
[tab]マーヤは見覚えない？
[tab]うーん、誰だっけな？[tab]芸能人？
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]はぁ～目から鱗だわ。
[tab]なに、[suou]さんとなんかあったの？
[tab]こらマーヤ！[tab]おしえろ！
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]君は落ち着いているんだな。
[tab]このペルソナと言う力、僕は身に余るものと
[tab]感じているんだが…
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]この店は高校生の盗難事件が多いと聞いていたが、
[tab]こうオープンな雰囲気ではなぁ…
[tab]犯罪抑止効果は無いと言っていいだろう。
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]…パオフゥの言う通りだな。
[tab]もう警察機構の一員である事に、こだわりはない。
[tab]僕は一人の人間として、正しい道を行く。
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]犯罪者の言う事でも、少しは為になるものだな。
[tab]方向性が違うと言うか、担当分野が違うと言うか。
[tab]しかし、自分がそれを実践する事はないだろう。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]人の罪を象徴するペルソナ…ＪＯＫＥＲ…
[tab]誰にもその一面があるってわけか。
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]杏奈君に対するノリコ君の強い想い。
[tab]若者の純粋な想いまで利用するとは…許せん！
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]写真の二人か…
[tab]管轄の手配書に該当する人物はいなかった。
[tab]前科は無いようだな。
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]…あ、天野君、どうした？
[tab]ぼ、僕かい？
[tab]ちょっとこの商品を…
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]今は子供を叱れる大人がいねぇんだ、少年犯罪も
[tab]増えて当然だろ？[tab]子供にも罪の意識ってのを
[tab]植え付ける必要があると思うぜ。
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]俺達が関わった事件は、どれも事故として
[tab]扱われている。様々な機関を利用した情報操作だ。
[tab]…[suou]の甘ちゃんは大丈夫か？
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]どうだ[suou]、警察の腐敗っぷり堪能出来たか？
[tab]自分の甘さに嫌気もさしたろ？
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]確かに安酒も旨くはなったが、
[tab]安物っていうのは所詮、高級品の代用だろ？
[tab]それで喜ばせるってのもねぇよなぁ。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]誰もがＪＯＫＥＲとなる可能性を持っている。
[tab]芹沢がそれを実証しちまったってわけだ。
[tab]…皮肉なもんだぜ。
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]意志の弱い連中って多いよな。
[tab]そこに付け込むヤツ等は…賢者か…愚者か？
[tab]微妙な所だな。
[wait][clear][end]

msg_21:
[color(yellow)]パオフゥ[color(white)]
[tab]例の写真、もう一回見直した方がいいな。
[tab]お前達、顔ばっかり見てるだろ？
[tab]写真が持つ情報は思ったよりずっと多いんだぞ！
[wait][clear][end]

msg_22:
[color(yellow)]パオフゥ[color(white)]
[tab]なんだっ！
[tab][suou]の野郎、急に赤くなりやがって。
[tab]天野、お前なんかしたのか？
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab][suou]巡査部長、あんな顔もするのだな。
[tab]俺はもっと表情の少ない、
[tab]クールな人だと思っていたが…
[wait][clear][end]

msg_24:
[color(yellow)]エリー[color(white)]
[tab]Ｍｒ．Ｋａｔｕｙａがあたふたしているのは
[tab]どうしてですの？[tab]何か大変な事でも？
[wait][clear][end]

msg_25:
[color(yellow)]作曲家[color(white)]
[tab]私の様に創作に生きる者は、時として
[tab]常人の目には見えぬ世界へ旅立つ事がある。
[tab]…眠れぬ日々の果てにある、特別な世界。
[wait][clear][end]

msg_26:
[color(yellow)]作曲家[color(white)]
[tab]そしてそこに見えてくる。
[tab]…いや、そこにあるのだよ。
[tab]「ベルベットルーム」とかいう青い扉が。
[wait][clear][end]

msg_27:
[color(yellow)]作曲家[color(white)]
[tab]本物の武器が売られているのか…
[tab]人気アイドル、ＭＵＳＥＳのライブチケットと
[tab]本物の武器、同じ値段ならどっちを買う？
[wait][clear][end]

msg_28:
[color(yellow)]作曲家[color(white)]
[tab]私は…
[tab]恥ずかしながらどっちも欲しい～！！
[wait][clear][end]

msg_29:
[color(yellow)]作曲家[color(white)]
[tab]ＪＯＫＥＲ呪いが新たなＪＯＫＥＲを生む…
[tab]人々の間では、様々な憶測が飛びかっていますね。
[tab]改めて、ワンロン占いの影響力を感じますよ。
[wait][clear][end]

msg_30:
[color(yellow)]作曲家[color(white)]
[tab]罪や妬み、邪気に憑かれた人々か…うむッ！
[tab]この動乱と向かい合ってこそ現代のアーティスト！
[tab]私が創作すべきは、…癒し系？
[wait][clear][end]

msg_31:
[color(yellow)]飄々とした男[color(white)]
[tab]なぁ、聞いたか？
[tab]セブンスの校長が殺されちまったってよ。
[tab]…校長ってそんなに恨まれる商売なのかぁ？
[wait][clear][end]

msg_32:
[color(yellow)]飄々とした男[color(white)]
[tab]バーで武器が買える？
[tab]噂には聞いていたが本当だったのか…
[tab]別に驚きはしないけど、物騒な世の中だな。
[wait][clear][end]

msg_33:
[color(yellow)]飄々とした男[color(white)]
[tab]ここに来てまたワンロン占いか…
[tab]まあ不安な時は何かに縋りたいと思うもんだが…
[tab]現実と妄想は区別するべきなんじゃないかな？
[wait][clear][end]

msg_34:
[color(yellow)]飄々とした男[color(white)]
[tab]ＪＯＫＥＲねぇ？[tab]本当に増えてるのか？
[tab]マスコミが面白がってるだけの気がするなぁ…
[tab]第一、見たこと無いからね。
[wait][clear][end]

msg_35:
[color(yellow)]牧村[color(white)]
[tab]最近不景気だろ？
[tab]そこでお勧めは１００円ショップデート！
[tab]金を使いたくない女に好評だぜ？
[wait][clear][end]

msg_36:
[color(yellow)]オバサン・長女[color(white)]
[tab]うひょひょひょ。
[tab]サトミタダシ青葉店へようこそ～
[tab]さあさあ御用は何かしらぁ？[tab]うひょひょひょ。
[wait][clear][end]

msg_37:
[color(yellow)]オバサン・長女[color(white)]
[tab]サトミタダシ青葉店へようこそ～
[tab]あらぁ！[tab]初めて見るお客さんねー
[tab]せっかくだから今日はサービスしちゃうわぁ～
[wait][clear][end]

msg_38:
[color(yellow)]オバサン・長女[color(white)]
[tab]サトミタダシ青葉店へようこ…あらぁ！！
[tab]うひょひょひょ！！[tab]いつもどーもなのねー
[tab]せっかくだから今日はサービスしちゃうわぁ～
[wait][clear][end]

msg_39:
[color(yellow)]オバサン・長女[color(white)]
[tab]うひょひょひょ～
[tab]いらっしゃいま～せ～
[choice(6)]消費物を買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_40:
[color(yellow)]オバサン・長女[color(white)]
[tab]さぁ、何を売りたいのかしらぁ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_41:
[color(yellow)]オバサン・長女[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
売買の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_42:
[color(yellow)]オバサン・長女[color(white)]
[tab]他に御用はあるかしらぁ～？
[tab]うひょひょひょ。
[choice(6)]消費物を買う
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_43:
[color(yellow)]オバサン・長女[color(white)]
[tab]さぁ、何を売りたいのかしら？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_44:
[color(yellow)]オバサン・長女[color(white)]
[tab]何を聞きたいのかしらぁ～？
[choice(3)]世間話をする
売買の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_45:
[color(yellow)]オバサン・長女[color(white)]
[tab]何？[tab]私を見たことがある？[tab]うひょひょひょ。
[tab]妹達は私にそっくりなのよねぇ～
[tab]私はサトミ七姉妹の長女なのよぉ～
[wait][clear][end]

msg_46:
[color(yellow)]オバサン・長女[color(white)]
[tab]うひょひょひょ！！
[tab]まぁ、妹達の支店共々、
[tab]よろしくお願いするのよぉ～
[wait][clear][end]

msg_47:
[color(yellow)]オバサン・長女[color(white)]
[tab]この曲がある限り、サトミタダシは千客万来！
[tab]ＪＯＫＥＲが現れたって店は閉められないわー！
[tab]むしろ今は、稼ぎ時かもぉ～
[wait][clear][end]

msg_48:
[color(yellow)]オバサン・長女[color(white)]
[tab]知ってる？[tab]最近のワンロン占いは怖いのよぉ～
[tab]「あなたの知人はＪＯＫＥＲかも？」ですってぇ。
[tab]…美容室で読んだ雑誌に載ってたわぁ～
[wait][clear][end]

msg_49:
[color(yellow)]オバサン・長女[color(white)]
[tab]ありがとねぇ～
[tab]また来てちょうだいなぁ～
[tab]うひょひょひょ。
[wait][clear][end]

msg_50:
ＭＢＩＴ[tab]ＡＩＳ[tab]６５
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_51:
ＥＢＩＴ[tab]Ｅ００１５
七姉妹学園クリア
びっとお～んッ！！
[wait][clear][end]

msg_52:
ＥＢＩＴ[tab]Ｅ００１８
バー終了・パオフゥ初参加
びっとお～んッ！！
[wait][clear][end]

msg_53:
ＥＢＩＴ[tab]Ｅ００３３
「パオフゥ編入」
びっとお～んッ！！
[wait][clear][end]

msg_54:
ＥＢＩＴ[tab]Ｅ００３７
警察署[half_tab]受付、終了
びっとお～んッ！！
[wait][clear][end]

msg_55:
ＥＢＩＴ[tab]Ｅ００３８
「詐欺男を確保」
びっとお～んッ！！
[wait][clear][end]

msg_56:
ＥＢＩＴ[tab]Ｅ００３Ｅ
「ゴールドクリア」「うらら編入」
びっとお～んッ！！
[wait][clear][end]

msg_57:
ＥＢＩＴ[tab]Ｅ００４３
「クラブクリア」
びっとお～んッ！！
[wait][clear][end]

msg_58:
ＥＢＩＴ[tab]Ｅ００４４
「青葉公園クリア」
びっとお～んッ！！
[wait][clear][end]

msg_59:
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear][end]

msg_60:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_61:
[color(yellow)]オバサン・長女[color(white)]
[tab]うひょひょひょ。
[tab]「売買」についてねぇ～。
[wait][clear][color(yellow)]オバサン・長女[color(white)]
[tab]まずは、購入の説明なのねぇ～。
[tab]うちの店で「消費物を買う」を選ぶと
[tab]消費アイテムを買うことができるわよぉ～。
[wait][clear][color(yellow)]オバサン・長女[color(white)]
[tab]あっ、そうそう、アイテムは持てる数が
[tab]決まってるからねぇ～。
[wait][clear][color(yellow)]オバサン・長女[color(white)]
[tab]次に、売却の説明なのねぇ～。
[tab]「アイテムを売る」を選んで、まず種類を決めて、
[tab]次に売りたいものを選んでねぇ～。
[wait][clear][color(yellow)]オバサン・長女[color(white)]
[tab]買取価格は元値の約半額くらいよぉ～。
[tab]あと、装備中の物は売ることができないからねぇ～。
[tab]それと、物によっては買取できない物もあるわよぉ～。
[wait][clear][color(yellow)]オバサン・長女[color(white)]
[tab]こんなとこかしらぁ～。
[tab]うひょひょひょ。
[wait][clear][end]

msg_62:
[color(yellow)]オバサン・長女[color(white)]
[tab]売れる物、持ってないじゃないの～。[wait][clear][end]

msg_63:
[color(yellow)]オバサン・長女[color(white)]
[tab]全部で、[var(msg_var_0)]円になるけど
[tab]いいかしらぁ～？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_64:
[color(yellow)]オバサン・長女[color(white)]
[tab]全部で、[var(msg_var_0)]円になるけど
[tab]いいかしらぁ～？
[choice(2)]はい
いいえ
[end_choice][clear][end]
