function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3005, 127);
    ref_3 = call(UWASABIT);
    wait(ref_3);
    objAnimRotate(obj_28, 0, 360, 0, 300, 1);
    envTriggerSet(DOORBOX, 131, 1, line, coll_0);
    envTriggerSet(OKUNOHEYA, 14, 1, line, coll_2);
    bitGet(var_0, MBIT_KUZU_HATUNEKO);
    bne(var_0, 0, label_c);
    envTriggerSet(BIGNEKO, 255, 1, collision_1, coll_1);
    b(label_e);
  label_c:
    bne(var_0, 1, label_e);
    b(label_e);
  label_e:
    objCollisionLink(line, coll_d, obj_11);
    envTriggerSet(HONDANA, 14, 1, line, coll_d);
    envTriggerSet(MAGAZIN, 14, 1, line, coll_21);
    cameraSet(southeast, 795, 0, -1300);
    li(var_0, 0);
    li(var_1, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, tatsuya);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_23);
    li(var_0, 0);
    b(label_28);
  label_23:
    ref_23 = dialogAlloc();
    ref_24 = msgShow(msg_0);
/***************************************
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear]
***************************************/
    wait(ref_24);
    dialogFree(ref_23);
    b(label_28);
  label_28:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_2d);
    bitGet(var_0, EBIT_E008C);
    bez(var_0, label_33);
    bnz(var_0, label_2f);
  label_2d:
    partyMemberCheck(var_0, tatsuya);
    bez(var_0, label_33);
  label_2f:
    ref_2f = spriteLoad(sprite_18);
    wait(ref_2f);
    unitSpawn(tatsuya, sprite_18, 860, 0, -1150, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
  label_33:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_46);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_3e);
    partyMemberCheck(var_0, elly);
    bez(var_0, label_46);
    ref_39 = spriteLoad(sprite_23);
    wait(ref_39);
    unitSpawn(elly, sprite_23, 645, 0, -1250, south, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
    b(label_46);
  label_3e:
    bne(var_0, 1, label_46);
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_46);
    ref_41 = spriteLoad(sprite_1f);
    wait(ref_41);
    unitSpawn(nanjo, sprite_1f, 675, 0, -1250, south, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
    b(label_46);
  label_46:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_4c);
    ref_48 = spriteLoad(sprite_6);
    wait(ref_48);
    unitSpawn(ulala, sprite_6, 930, 0, -310, south, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_4c:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_52);
    ref_4e = spriteLoad(sprite_d);
    wait(ref_4e);
    unitSpawn(katsuya, sprite_d, 650, 30, -740, north, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_52:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_58);
    ref_54 = spriteLoad(sprite_13);
    wait(ref_54);
    unitSpawn(baofu, sprite_13, 450, 0, -520, east, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_58:
    ref_58 = spriteLoad(sprite_9c);
    wait(ref_58);
    unitSpawn(shopkeeper, sprite_9c, 120, 0, -1020, north, none);
    unitTriggerSet(shopkeeper, SHOP, 255, 1);
    ref_5c = spriteLoad(sprite_a9);
    wait(ref_5c);
    unitSpawn(unit_58, sprite_a9, 510, 0, -1220, south, none);
    unitTriggerSet(unit_58, WOMAN1, 255, 1);
    bitGet(var_0, MBIT_KUZU_HATUNEKO);
    bez(var_0, label_63);
    objVisible(obj_1b, false);
  label_63:
    ref_63 = spriteLoad(sprite_8b);
    wait(ref_63);
    unitSpawn(npc1, sprite_8b, 200, 0, -150, west, none);
    unitTriggerSet(npc1, MAN1, 255, 1);
    ref_67 = spriteLoad(sprite_0);
    wait(ref_67);
    ref_69 = spriteLoad(sprite_2);
    wait(ref_69);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_f4);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_e4);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_c2);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_b2);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_a2);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_92);
    unitFacePlayer(ulala);
    ref_83 = bustupLoad(bustup_1e);
    bustupWait(ref_83);
    ref_85 = bustupAlloc(ref_83, left, rgb(0,0,0));
    bustupFade(ref_85, rgb(128,0,0), 30);
    ref_87 = dialogAlloc();
    ref_88 = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]…スニークって人、信用出来ないよねぇ？
[tab][suou]さんってホントにあの人の事、
[tab]信じてんのかなぁ？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_88);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_87);
    ref_8d = bustupFade(ref_85, rgb(0,0,0), 10);
    bustupWait(ref_8d);
    bustupFree(ref_85);
    unitRestoreFacing(ulala);
    b(label_104);
  label_92:
    unitFacePlayer(ulala);
    ref_93 = bustupLoad(bustup_17);
    bustupWait(ref_93);
    ref_95 = bustupAlloc(ref_93, left, rgb(0,0,0));
    bustupFade(ref_95, rgb(128,0,0), 30);
    ref_97 = dialogAlloc();
    ref_98 = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab][suou]さん、困ってるみたいだね。
[tab]…自分の事じゃないから、一層難しいのかも。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1a, 1);
    wait(ref_98);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_97);
    ref_9d = bustupFade(ref_95, rgb(0,0,0), 10);
    bustupWait(ref_9d);
    bustupFree(ref_95);
    unitRestoreFacing(ulala);
    b(label_104);
  label_a2:
    unitFacePlayer(ulala);
    ref_a3 = bustupLoad(bustup_17);
    bustupWait(ref_a3);
    ref_a5 = bustupAlloc(ref_a3, left, rgb(0,0,0));
    bustupFade(ref_a5, rgb(128,0,0), 30);
    ref_a7 = dialogAlloc();
    ref_a8 = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]珠閒瑠市を空に浮かべるなんて、
[tab]普通の人は考えないよねぇ。
[tab]…そんなことホントにできんのかな？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_a8);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_a7);
    ref_ad = bustupFade(ref_a5, rgb(0,0,0), 10);
    bustupWait(ref_ad);
    bustupFree(ref_a5);
    unitRestoreFacing(ulala);
    b(label_104);
  label_b2:
    unitFacePlayer(ulala);
    ref_b3 = bustupLoad(bustup_17);
    bustupWait(ref_b3);
    ref_b5 = bustupAlloc(ref_b3, left, rgb(0,0,0));
    bustupFade(ref_b5, rgb(128,0,0), 30);
    ref_b7 = dialogAlloc();
    ref_b8 = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あの子、なんか懐かしんでるよ？
[tab]前にもここに来た事あるみたいだから、
[tab]ＪＯＫＥＲの噂の時以外にも来てたんだね。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_b8);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_b7);
    ref_bd = bustupFade(ref_b5, rgb(0,0,0), 10);
    bustupWait(ref_bd);
    bustupFree(ref_b5);
    unitRestoreFacing(ulala);
    b(label_104);
  label_c2:
    unitFacePlayer(ulala);
    bitGet(var_0, MBIT_KUZU_HATUNEKO);
    bne(var_0, 0, label_d3);
    ref_c5 = bustupLoad(bustup_17);
    bustupWait(ref_c5);
    ref_c7 = bustupAlloc(ref_c5, left, rgb(0,0,0));
    bustupFade(ref_c7, rgb(128,0,0), 30);
    ref_c9 = dialogAlloc();
    ref_ca = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あの招き猫の料金設定は誰がしてんだろうねぇ。
[tab]…え、おっちゃんでもたまきちゃんでもない！？
[tab]じゃあ誰よ！[tab]…業者の人？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_ca);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_c9);
    ref_cf = bustupFade(ref_c7, rgb(0,0,0), 10);
    bustupWait(ref_cf);
    bustupFree(ref_c7);
    b(label_e2);
  label_d3:
    bne(var_0, 1, label_e2);
    ref_d4 = bustupLoad(bustup_19);
    bustupWait(ref_d4);
    ref_d6 = bustupAlloc(ref_d4, left, rgb(0,0,0));
    bustupFade(ref_d6, rgb(128,0,0), 30);
    ref_d8 = dialogAlloc();
    ref_d9 = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]向こうは１００エ～ン？[tab]あんのネコマタぁ！！
[tab]私達が何も知らないと思って～！！[delay(30)]
[tab]…ハッ、もしかしてたまきちゃんの差し金！？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_d9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_d8);
    ref_de = bustupFade(ref_d6, rgb(0,0,0), 10);
    bustupWait(ref_de);
    bustupFree(ref_d6);
    b(label_e2);
  label_e2:
    unitRestoreFacing(ulala);
    b(label_104);
  label_e4:
    unitFacePlayer(ulala);
    ref_e5 = bustupLoad(bustup_17);
    bustupWait(ref_e5);
    ref_e7 = bustupAlloc(ref_e5, left, rgb(0,0,0));
    bustupFade(ref_e7, rgb(128,0,0), 30);
    ref_e9 = dialogAlloc();
    ref_ea = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]さっ、行こっかマーヤ！
[tab]噂で世界が滅亡なんてカッコわるいじゃん？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_ea);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_e9);
    ref_ef = bustupFade(ref_e7, rgb(0,0,0), 10);
    bustupWait(ref_ef);
    bustupFree(ref_e7);
    unitRestoreFacing(ulala);
    b(label_104);
  label_f4:
    unitFacePlayer(ulala);
    ref_f5 = bustupLoad(bustup_17);
    bustupWait(ref_f5);
    ref_f7 = bustupAlloc(ref_f5, left, rgb(0,0,0));
    bustupFade(ref_f7, rgb(128,0,0), 30);
    ref_f9 = dialogAlloc();
    ref_fa = msgShow(msg_8);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あの子達をあのままには出来ないよ！
[tab]マーヤ、急ご！！
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_fa);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_f9);
    ref_ff = bustupFade(ref_f7, rgb(0,0,0), 10);
    bustupWait(ref_ff);
    bustupFree(ref_f7);
    unitRestoreFacing(ulala);
    b(label_104);
  label_104:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_163);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_153);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_143);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_133);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_123);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_113);
  label_113:
    unitFacePlayer(katsuya);
    ref_114 = bustupLoad(bustup_27);
    bustupWait(ref_114);
    ref_116 = bustupAlloc(ref_114, left, rgb(0,0,0));
    bustupFade(ref_116, rgb(128,0,0), 30);
    ref_118 = dialogAlloc();
    ref_119 = msgShow(msg_9);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]あの署長が父さんの親友であり、
[tab]父さんを裏切った男だったなんて。
[tab]…僕は父さんになんと言えばいいんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_119);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_118);
    ref_11e = bustupFade(ref_116, rgb(0,0,0), 10);
    bustupWait(ref_11e);
    bustupFree(ref_116);
    unitRestoreFacing(katsuya);
    b(label_173);
  label_123:
    unitFacePlayer(katsuya);
    ref_124 = bustupLoad(bustup_21);
    bustupWait(ref_124);
    ref_126 = bustupAlloc(ref_124, left, rgb(0,0,0));
    bustupFade(ref_126, rgb(128,0,0), 30);
    ref_128 = dialogAlloc();
    ref_129 = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]新世塾がこれ程の事を計画しているとは…
[tab]我々は敵組織を甘く見過ぎていたのか？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_129);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_128);
    ref_12e = bustupFade(ref_126, rgb(0,0,0), 10);
    bustupWait(ref_12e);
    bustupFree(ref_126);
    unitRestoreFacing(katsuya);
    b(label_173);
  label_133:
    unitFacePlayer(katsuya);
    ref_134 = bustupLoad(bustup_25);
    bustupWait(ref_134);
    ref_136 = bustupAlloc(ref_134, left, rgb(0,0,0));
    bustupFade(ref_136, rgb(128,0,0), 30);
    ref_138 = dialogAlloc();
    ref_139 = msgShow(msg_11);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]まさか！
[tab]普通の高校生がこんな所に用などある訳が無い！
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2f, 1);
    wait(ref_139);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_138);
    ref_13e = bustupFade(ref_136, rgb(0,0,0), 10);
    bustupWait(ref_13e);
    bustupFree(ref_136);
    unitRestoreFacing(katsuya);
    b(label_173);
  label_143:
    unitFacePlayer(katsuya);
    ref_144 = bustupLoad(bustup_21);
    bustupWait(ref_144);
    ref_146 = bustupAlloc(ref_144, left, rgb(0,0,0));
    bustupFade(ref_146, rgb(128,0,0), 30);
    ref_148 = dialogAlloc();
    ref_149 = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]我々がここを利用したように、[tatsuya]達も
[tab]「向こう側」で利用していたんだな。
[tab]…しかし、９００円も違うとは。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_149);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_148);
    ref_14e = bustupFade(ref_146, rgb(0,0,0), 10);
    bustupWait(ref_14e);
    bustupFree(ref_146);
    unitRestoreFacing(katsuya);
    b(label_173);
  label_153:
    unitFacePlayer(katsuya);
    ref_154 = bustupLoad(bustup_21);
    bustupWait(ref_154);
    ref_156 = bustupAlloc(ref_154, left, rgb(0,0,0));
    bustupFade(ref_156, rgb(128,0,0), 30);
    ref_158 = dialogAlloc();
    ref_159 = msgShow(msg_13);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]噂で世界が滅亡か…
[tab]未だに信じられない事だが、
[tab]この状況ではあり得るのだな。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_159);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_158);
    ref_15e = bustupFade(ref_156, rgb(0,0,0), 10);
    bustupWait(ref_15e);
    bustupFree(ref_156);
    unitRestoreFacing(katsuya);
    b(label_173);
  label_163:
    unitFacePlayer(katsuya);
    ref_164 = bustupLoad(bustup_21);
    bustupWait(ref_164);
    ref_166 = bustupAlloc(ref_164, left, rgb(0,0,0));
    bustupFade(ref_166, rgb(128,0,0), 30);
    ref_168 = dialogAlloc();
    ref_169 = msgShow(msg_14);
/***************************************
[color(yellow)]克哉[color(white)]
[tab][tatsuya]の友達を…天野君の仲間達を
[tab]放っておく訳にはいかない！
[tab]行こう、天野君。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_169);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_168);
    ref_16e = bustupFade(ref_166, rgb(0,0,0), 10);
    bustupWait(ref_16e);
    bustupFree(ref_166);
    unitRestoreFacing(katsuya);
    b(label_173);
  label_173:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_1e2);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1d2);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_1c2);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_1b2);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_1a2);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_192);
    unitFacePlayer(baofu);
    ref_183 = bustupLoad(bustup_2d);
    bustupWait(ref_183);
    ref_185 = bustupAlloc(ref_183, left, rgb(0,0,0));
    bustupFade(ref_185, rgb(128,0,0), 30);
    ref_187 = dialogAlloc();
    ref_188 = msgShow(msg_15);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]大きな組織となれば、意志の統一もままならねぇ。
[tab]新世塾を裏切る者がいてもおかしくはねぇが、
[tab]…どうなんだろうなぁ？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_188);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_187);
    ref_18d = bustupFade(ref_185, rgb(0,0,0), 10);
    bustupWait(ref_18d);
    bustupFree(ref_185);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_192:
    unitFacePlayer(baofu);
    ref_193 = bustupLoad(bustup_31);
    bustupWait(ref_193);
    ref_195 = bustupAlloc(ref_193, left, rgb(0,0,0));
    bustupFade(ref_195, rgb(128,0,0), 30);
    ref_197 = dialogAlloc();
    ref_198 = msgShow(msg_16);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]今更、隠したってしょうがねぇだろ？
[tab][suou]の親父だって、わかってたから
[tab]何も言わなかったんじゃねぇのか？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_198);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_197);
    ref_19d = bustupFade(ref_195, rgb(0,0,0), 10);
    bustupWait(ref_19d);
    bustupFree(ref_195);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_1a2:
    unitFacePlayer(baofu);
    ref_1a3 = bustupLoad(bustup_2d);
    bustupWait(ref_1a3);
    ref_1a5 = bustupAlloc(ref_1a3, left, rgb(0,0,0));
    bustupFade(ref_1a5, rgb(128,0,0), 30);
    ref_1a7 = dialogAlloc();
    ref_1a8 = msgShow(msg_17);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]俺達が新世塾を甘く見ていたのは認めるが、
[tab]あんなぶっ飛んだ計画、誰も想像出来ねぇよ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1a8);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1a7);
    ref_1ad = bustupFade(ref_1a5, rgb(0,0,0), 10);
    bustupWait(ref_1ad);
    bustupFree(ref_1a5);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_1b2:
    unitFacePlayer(baofu);
    ref_1b3 = bustupLoad(bustup_31);
    bustupWait(ref_1b3);
    ref_1b5 = bustupAlloc(ref_1b3, left, rgb(0,0,0));
    bustupFade(ref_1b5, rgb(128,0,0), 30);
    ref_1b7 = dialogAlloc();
    ref_1b8 = msgShow(msg_18);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab][suou]のヤツ、弟の事ならなんでも知ってる
[tab]ってな口ぶりだが、認識甘いんじゃねぇーか？
[tab]第一、あの野郎は普通の高校生じゃねぇだろぉ？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_1b8);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1b7);
    ref_1bd = bustupFade(ref_1b5, rgb(0,0,0), 10);
    bustupWait(ref_1bd);
    bustupFree(ref_1b5);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_1c2:
    unitFacePlayer(baofu);
    ref_1c3 = bustupLoad(bustup_2d);
    bustupWait(ref_1c3);
    ref_1c5 = bustupAlloc(ref_1c3, left, rgb(0,0,0));
    bustupFade(ref_1c5, rgb(128,0,0), 30);
    ref_1c7 = dialogAlloc();
    ref_1c8 = msgShow(msg_19);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ふ～ん、「向こう側」でもねぇ。
[tab]ここのおっさんも怪しいからなぁ、
[tab]案外[tatsuya]の事も気付いているかもよ？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1c8);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1c7);
    ref_1cd = bustupFade(ref_1c5, rgb(0,0,0), 10);
    bustupWait(ref_1cd);
    bustupFree(ref_1c5);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_1d2:
    unitFacePlayer(baofu);
    ref_1d3 = bustupLoad(bustup_2d);
    bustupWait(ref_1d3);
    ref_1d5 = bustupAlloc(ref_1d3, left, rgb(0,0,0));
    bustupFade(ref_1d5, rgb(128,0,0), 30);
    ref_1d7 = dialogAlloc();
    ref_1d8 = msgShow(msg_20);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]噂に振りまわされて死ぬなんて御免だぜ？
[tab]そんな馬鹿な事で死ねるかよ！
[tab]俺は死なねぇし、世界も滅亡なんかさせねぇよ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_1d8);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1d7);
    ref_1dd = bustupFade(ref_1d5, rgb(0,0,0), 10);
    bustupWait(ref_1dd);
    bustupFree(ref_1d5);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_1e2:
    unitFacePlayer(baofu);
    ref_1e3 = bustupLoad(bustup_2d);
    bustupWait(ref_1e3);
    ref_1e5 = bustupAlloc(ref_1e3, left, rgb(0,0,0));
    bustupFade(ref_1e5, rgb(128,0,0), 30);
    ref_1e7 = dialogAlloc();
    ref_1e8 = msgShow(msg_21);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ガキ共なんかどうでもいいだろ！？
[tab]俺はこの馬鹿げた戦いを終わらせたいんだ。
[tab]…ガキなんかついででいいよ、ついでで。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1e8);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1e7);
    ref_1ed = bustupFade(ref_1e5, rgb(0,0,0), 10);
    bustupWait(ref_1ed);
    bustupFree(ref_1e5);
    unitRestoreFacing(baofu);
    b(label_1f2);
  label_1f2:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, MBIT_KUZU_T_TALK_N);
    bez(var_0, label_23d);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_22d);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_21d);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_20d);
    unitFacePlayer(nanjo);
    ref_1fe = bustupLoad(bustup_36);
    bustupWait(ref_1fe);
    ref_200 = bustupAlloc(ref_1fe, left, rgb(0,0,0));
    bustupFade(ref_200, rgb(128,0,0), 30);
    ref_202 = dialogAlloc();
    ref_203 = msgShow(msg_22);
/***************************************
[color(yellow)]南条[color(white)]
[tab]スニーク…卑怯者を名乗る者か。
[tab]自ら卑怯である事を語るのだから、
[tab]新世塾にとっては獅子身中の虫ということか？
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_203);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_202);
    ref_208 = bustupFade(ref_200, rgb(0,0,0), 10);
    bustupWait(ref_208);
    bustupFree(ref_200);
    unitRestoreFacing(nanjo);
    b(label_250);
  label_20d:
    unitFacePlayer(nanjo);
    ref_20e = bustupLoad(bustup_3b);
    bustupWait(ref_20e);
    ref_210 = bustupAlloc(ref_20e, left, rgb(0,0,0));
    bustupFade(ref_210, rgb(128,0,0), 30);
    ref_212 = dialogAlloc();
    ref_213 = msgShow(msg_23);
/***************************************
[color(yellow)]南条[color(white)]
[tab]あの警察署長、弱い人だったのだな。
[tab]悪人になりきれぬ事を、もっと早く自覚していれば
[tab]こんな事には…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_6, 1);
    wait(ref_213);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_212);
    ref_218 = bustupFade(ref_210, rgb(0,0,0), 10);
    bustupWait(ref_218);
    bustupFree(ref_210);
    unitRestoreFacing(nanjo);
    b(label_250);
  label_21d:
    unitFacePlayer(nanjo);
    ref_21e = bustupLoad(bustup_36);
    bustupWait(ref_21e);
    ref_220 = bustupAlloc(ref_21e, left, rgb(0,0,0));
    bustupFade(ref_220, rgb(128,0,0), 30);
    ref_222 = dialogAlloc();
    ref_223 = msgShow(msg_24);
/***************************************
[color(yellow)]南条[color(white)]
[tab]既存の価値観を超えた計画か…
[tab]その是非はともかく、大物でなければ
[tab]考えもつかぬ事。須藤[tab]竜蔵とは案外…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_223);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_222);
    ref_228 = bustupFade(ref_220, rgb(0,0,0), 10);
    bustupWait(ref_228);
    bustupFree(ref_220);
    unitRestoreFacing(nanjo);
    b(label_250);
  label_22d:
    unitFacePlayer(nanjo);
    ref_22e = bustupLoad(bustup_36);
    bustupWait(ref_22e);
    ref_230 = bustupAlloc(ref_22e, left, rgb(0,0,0));
    bustupFade(ref_230, rgb(128,0,0), 30);
    ref_232 = dialogAlloc();
    ref_233 = msgShow(msg_25);
/***************************************
[color(yellow)]南条[color(white)]
[tab][suou]の奴、ここで話す気はないようだ。
[tab]…先を急ぎましょう。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_233);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_232);
    ref_238 = bustupFade(ref_230, rgb(0,0,0), 10);
    bustupWait(ref_238);
    bustupFree(ref_230);
    unitRestoreFacing(nanjo);
    b(label_250);
  label_23d:
    unitFaceUnit(nanjo, unit_58);
    unitFaceUnit(unit_58, nanjo);
    ref_23f = bustupLoad(bustup_36);
    bustupWait(ref_23f);
    ref_241 = bustupAlloc(ref_23f, left, rgb(0,0,0));
    bustupFade(ref_241, rgb(128,0,0), 30);
    ref_243 = dialogAlloc();
    ref_244 = msgShow(msg_26);
/***************************************
[color(yellow)]南条[color(white)]
[tab]ほう、懐かしい顔だな。
[tab]君は確か大学へ進んだ筈では…
[tab]…バイト？[tab]こんな所でか？
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_244);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_243);
    ref_249 = bustupFade(ref_241, rgb(0,0,0), 10);
    bustupWait(ref_249);
    bustupFree(ref_241);
    unitRestoreFacing(nanjo);
    unitRestoreFacing(unit_58);
    bitSet(LBIT_0014);
    b(label_250);
  label_250:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, MBIT_KUZU_T_TALK_E);
    bez(var_0, label_29b);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_28b);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_27b);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_26b);
    unitFacePlayer(elly);
    ref_25c = bustupLoad(bustup_42);
    bustupWait(ref_25c);
    ref_25e = bustupAlloc(ref_25c, left, rgb(0,0,0));
    bustupFade(ref_25e, rgb(128,0,0), 30);
    ref_260 = dialogAlloc();
    ref_261 = msgShow(msg_27);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｓｎｅａｋ…告げ口をするとも受け取れますわ。
[tab]私達に新世塾の事を告げ口してくれる人だと
[tab]いいのですが…
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_261);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_260);
    ref_266 = bustupFade(ref_25e, rgb(0,0,0), 10);
    bustupWait(ref_266);
    bustupFree(ref_25e);
    unitRestoreFacing(elly);
    b(label_2ae);
  label_26b:
    unitFacePlayer(elly);
    ref_26c = bustupLoad(bustup_42);
    bustupWait(ref_26c);
    ref_26e = bustupAlloc(ref_26c, left, rgb(0,0,0));
    bustupFade(ref_26e, rgb(128,0,0), 30);
    ref_270 = dialogAlloc();
    ref_271 = msgShow(msg_28);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]あの警察署長さん、弱い人だったのですね。
[tab]悪人になりきれたなら、罪の意識に苦しむ事も
[tab]無かったでしょうに。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_271);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_270);
    ref_276 = bustupFade(ref_26e, rgb(0,0,0), 10);
    bustupWait(ref_276);
    bustupFree(ref_26e);
    unitRestoreFacing(elly);
    b(label_2ae);
  label_27b:
    unitFacePlayer(elly);
    ref_27c = bustupLoad(bustup_3d);
    bustupWait(ref_27c);
    ref_27e = bustupAlloc(ref_27c, left, rgb(0,0,0));
    bustupFade(ref_27e, rgb(128,0,0), 30);
    ref_280 = dialogAlloc();
    ref_281 = msgShow(msg_29);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]既存の価値観を超えたＰｒｏｊｅｃｔ…
[tab]その是非はともかく、大物でなければ考えも
[tab]つかない事でしょうね。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_281);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_280);
    ref_286 = bustupFade(ref_27e, rgb(0,0,0), 10);
    bustupWait(ref_286);
    bustupFree(ref_27e);
    unitRestoreFacing(elly);
    b(label_2ae);
  label_28b:
    unitFacePlayer(elly);
    ref_28c = bustupLoad(bustup_3d);
    bustupWait(ref_28c);
    ref_28e = bustupAlloc(ref_28c, left, rgb(0,0,0));
    bustupFade(ref_28e, rgb(128,0,0), 30);
    ref_290 = dialogAlloc();
    ref_291 = msgShow(msg_30);
/***************************************
[color(yellow)]エリー[color(white)]
[tab][tatsuya]…ここで話す気はないようですね。
[tab]先を急ぎましょう。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_291);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_290);
    ref_296 = bustupFade(ref_28e, rgb(0,0,0), 10);
    bustupWait(ref_296);
    bustupFree(ref_28e);
    unitRestoreFacing(elly);
    b(label_2ae);
  label_29b:
    unitFaceUnit(elly, unit_58);
    unitFaceUnit(unit_58, elly);
    ref_29d = bustupLoad(bustup_3e);
    bustupWait(ref_29d);
    ref_29f = bustupAlloc(ref_29d, left, rgb(0,0,0));
    bustupFade(ref_29f, rgb(128,0,0), 30);
    ref_2a1 = dialogAlloc();
    ref_2a2 = msgShow(msg_31);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｏｈ！[tab]久しぶりですわ、Ｍｓ．Ｔａｍａｋｉ！
[tab]お元気でした？
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_2a2);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_2a1);
    ref_2a7 = bustupFade(ref_29f, rgb(0,0,0), 10);
    bustupWait(ref_2a7);
    bustupFree(ref_29f);
    unitRestoreFacing(elly);
    unitRestoreFacing(unit_58);
    bitSet(LBIT_0015);
    b(label_2ae);
  label_2ae:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_2ed);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2dd);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_2ca);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_2b9);
  label_2b9:
    unitFacePlayer(tatsuya);
    ref_2ba = bustupLoad(bustup_b);
    bustupWait(ref_2ba);
    ref_2bc = bustupAlloc(ref_2ba, right, rgb(0,0,0));
    bustupFade(ref_2bc, rgb(128,0,0), 30);
    bustupFlip(ref_2bc, true);
    ref_2bf = dialogAlloc();
    ref_2c0 = msgShow(msg_32);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ここは…随分変わったな。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_28, 1);
    wait(ref_2c0);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2bf);
    ref_2c5 = bustupFade(ref_2bc, rgb(0,0,0), 10);
    bustupWait(ref_2c5);
    bustupFree(ref_2bc);
    unitRestoreFacing(tatsuya);
    b(label_2fd);
  label_2ca:
    unitFacePlayer(tatsuya);
    ref_2cb = bustupLoad(bustup_b);
    bustupWait(ref_2cb);
    ref_2cd = bustupAlloc(ref_2cb, left, rgb(0,0,0));
    bustupFade(ref_2cd, rgb(128,0,0), 30);
    ref_2cf = dialogAlloc();
    ref_2d0 = msgShow(msg_33);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ここは「向こう側」でも噂を操作してくれた。
[tab]その他にも色々と手助けしてもらったが、
[tab]…俺の事はわからないだろうな。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2d0);
    ref_2d3 = msgShow(msg_34);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]しかし、「こちら側」は物価が高いのか？
[tab]「向こう側」であの招き猫が要求してきたのは
[tab]１００円だったはずだ。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_1a, 1);
    wait(ref_2d3);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2cf);
    ref_2d8 = bustupFade(ref_2cd, rgb(0,0,0), 10);
    bustupWait(ref_2d8);
    bustupFree(ref_2cd);
    unitRestoreFacing(tatsuya);
    b(label_2fd);
  label_2dd:
    unitFacePlayer(tatsuya);
    ref_2de = bustupLoad(bustup_b);
    bustupWait(ref_2de);
    ref_2e0 = bustupAlloc(ref_2de, left, rgb(0,0,0));
    bustupFade(ref_2e0, rgb(128,0,0), 30);
    ref_2e2 = dialogAlloc();
    ref_2e3 = msgShow(msg_35);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]この世界を消させやしない。
[tab]…俺はその為に戦っているんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2f, 1);
    wait(ref_2e3);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2e2);
    ref_2e8 = bustupFade(ref_2e0, rgb(0,0,0), 10);
    bustupWait(ref_2e8);
    bustupFree(ref_2e0);
    unitRestoreFacing(tatsuya);
    b(label_2fd);
  label_2ed:
    unitFacePlayer(tatsuya);
    ref_2ee = bustupLoad(bustup_b);
    bustupWait(ref_2ee);
    ref_2f0 = bustupAlloc(ref_2ee, left, rgb(0,0,0));
    bustupFade(ref_2f0, rgb(128,0,0), 30);
    ref_2f2 = dialogAlloc();
    ref_2f3 = msgShow(msg_36);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]あれがヤツの…
[tab]ニャルラトホテプのやり方だ。
[tab]気を付けてくれ、舞耶姉。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2f3);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2f2);
    ref_2f8 = bustupFade(ref_2f0, rgb(0,0,0), 10);
    bustupWait(ref_2f8);
    bustupFree(ref_2f0);
    unitRestoreFacing(tatsuya);
    b(label_2fd);
  label_2fd:
    controlEnable();
}

function WOMAN1()
{
    controlDisable();
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_303);
    b(label_306);
  label_303:
    bne(var_0, 1, label_306);
    shopOverlayInit();
    b(label_306);
  label_306:
    unitFacePlayer(unit_58);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_30d);
    bitGet(var_0, MBIT_AIS_25);
    bnz(var_0, label_51e);
    b(label_53a);
    b(label_31d);
  label_30d:
    bne(var_0, 1, label_31d);
    bitGet(var_0, MBIT_KUZU_KENSHOUHATU);
    bne(var_0, 0, label_313);
    bitGet(var_0, MBIT_KUZU_KENSHOUTALK);
    bez(var_0, label_33c);
    b(label_31c);
  label_313:
    bne(var_0, 1, label_31c);
    bitGet(var_0, MBIT_AIS_25);
    bne(var_0, 0, label_318);
    b(label_31d);
    b(label_31b);
  label_318:
    bne(var_0, 1, label_31b);
    b(label_32b);
    b(label_31b);
  label_31b:
    b(label_31c);
  label_31c:
    b(label_31d);
  label_31d:
    ref_31d = bustupLoad(bustup_e6);
    bustupWait(ref_31d);
    ref_31f = bustupAlloc(ref_31d, right, rgb(0,0,0));
    bustupFade(ref_31f, rgb(128,0,0), 30);
    ref_321 = dialogAlloc();
    ref_322 = msgShow(msg_37);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]おつかれー！
[tab]さて、ご用件はなにかしら？
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_19, 1);
    wait(ref_322);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_321);
    ref_327 = bustupFade(ref_31f, rgb(0,0,0), 10);
    bustupWait(ref_327);
    bustupFree(ref_31f);
    b(label_34b);
  label_32b:
    ref_32b = bustupLoad(bustup_e6);
    bustupWait(ref_32b);
    ref_32d = bustupAlloc(ref_32b, right, rgb(0,0,0));
    bustupFade(ref_32d, rgb(128,0,0), 30);
    ref_32f = dialogAlloc();
    ref_330 = msgShow(msg_38);
/***************************************
[tab]あ、こんにちは～！
[tab]あっれぇ～？[tab]天野さん最近なんかありました？
[tab]…だって、すっごくキレイになったもん！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_19, 1);
    wait(ref_330);
    ref_333 = msgShow(msg_39);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]はっは～ん？[tab]さては…
[tab]な～んてね！！[tab]エヘヘ。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_333);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_32f);
    ref_338 = bustupFade(ref_32d, rgb(0,0,0), 10);
    bustupWait(ref_338);
    bustupFree(ref_32d);
    b(label_34b);
  label_33c:
    ref_33c = bustupLoad(bustup_e6);
    bustupWait(ref_33c);
    ref_33e = bustupAlloc(ref_33c, right, rgb(0,0,0));
    bustupFade(ref_33e, rgb(128,0,0), 30);
    ref_340 = dialogAlloc();
    ref_341 = msgShow(msg_40);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]これで、懸賞に関する噂も現実になるはず。
[tab]それでは、応募は私が引き受けますね。
[tab]天野さん達、忙しいでしょ？
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_19, 1);
    wait(ref_341);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_340);
    ref_346 = bustupFade(ref_33e, rgb(0,0,0), 10);
    bustupWait(ref_346);
    bustupFree(ref_33e);
    bitSet(MBIT_KUZU_KENSHOUTALK);
    b(label_34b);
  label_34b:
    bitClear(LBIT_0013);
    choiceSetResult(3);
    ref_34d = bustupLoad(bustup_1);
    bustupWait(ref_34d);
    ref_34f = bustupAlloc(ref_34d, center, rgb(0,0,0));
    bustupFade(ref_34f, rgb(128,0,0), 30);
    ref_351 = dialogChoiceAlloc();
    ref_352 = msgShow(msg_41);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]さて、どうします？
[choice(4)]話をする
応募したい
懸賞とは？
用はない
[end_choice][clear]
***************************************/
    wait(ref_352);
    dialogFree(ref_351);
    ref_355 = bustupFade(ref_34f, rgb(0,0,0), 10);
    bustupWait(ref_355);
    bustupFree(ref_34f);
    choiceGetResult(var_0);
    bne(var_0, 0, label_35c);
    b(label_53a);
    b(label_365);
  label_35c:
    bne(var_0, 1, label_35f);
    b(label_365);
    b(label_365);
  label_35f:
    bne(var_0, 2, label_362);
    b(label_501);
    b(label_365);
  label_362:
    bne(var_0, 3, label_365);
    b(label_5f4);
    b(label_365);
  label_365:
    bitGet(var_0, MBIT_DMAGICK);
    bez(var_0, label_382);
    bitGet(var_0, MBIT_DPELPEL);
    bez(var_0, label_376);
    b(label_36a);
  label_36a:
    bitGet(var_0, MBIT_WORLD_OUBO);
    bne(var_0, 0, label_373);
    partyItemCount(var_d, fantasy_world);
    bne(var_d, 0, label_370);
    b(label_376);
    b(label_372);
  label_370:
    bitSet(LBIT_0003);
    b(label_372);
  label_372:
    b(label_376);
  label_373:
    bne(var_0, 1, label_376);
    bitSet(LBIT_0009);
    b(label_376);
  label_376:
    bitGet(var_0, MBIT_MRCLE_OUBO);
    bne(var_0, 0, label_37f);
    partyItemCount(var_c, miracle_magazine);
    bne(var_c, 0, label_37c);
    b(label_382);
    b(label_37e);
  label_37c:
    bitSet(LBIT_0002);
    b(label_37e);
  label_37e:
    b(label_382);
  label_37f:
    bne(var_0, 1, label_382);
    bitSet(LBIT_0008);
    b(label_382);
  label_382:
    bitGet(var_0, MBIT_BATLE_OUBO);
    bne(var_0, 0, label_38a);
    partyItemCount(var_b, battle_master);
    bne(var_b, 0, label_387);
    b(label_389);
  label_387:
    bitSet(LBIT_0001);
    b(label_389);
  label_389:
    b(label_38d);
  label_38a:
    bne(var_0, 1, label_38d);
    bitSet(LBIT_0007);
    b(label_38d);
  label_38d:
    bitGet(var_0, LBIT_0001);
    bnz(var_0, label_3fc);
    bitGet(var_0, LBIT_0007);
    bnz(var_0, label_3a0);
  label_391:
    bitGet(var_0, LBIT_0002);
    bnz(var_0, label_410);
    bitGet(var_0, LBIT_0008);
    bnz(var_0, label_3be);
  label_395:
    bitGet(var_0, LBIT_0003);
    bnz(var_0, label_42c);
    bitGet(var_0, LBIT_0009);
    bnz(var_0, label_3e0);
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_39d);
    b(label_4e5);
    b(label_3a0);
  label_39d:
    bne(var_0, 1, label_3a0);
    b(label_4f3);
    b(label_3a0);
  label_3a0:
    ref_3a0 = bustupLoad(bustup_e6);
    bustupWait(ref_3a0);
    ref_3a2 = bustupAlloc(ref_3a0, right, rgb(0,0,0));
    bustupFade(ref_3a2, rgb(128,0,0), 30);
    ref_3a4 = dialogAlloc();
    ref_3a5 = msgShow(msg_42);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ＯＫ、応募ですね。
[tab]え～と、月刊バトルマスターは…[delay(30)]
[tab]ブッブーッ！！[tab]ダメで～す。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_3a5);
    ref_3a8 = msgShow(msg_43);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]この前応募した分、確認してませんね？
[tab]受け取りはキスメット出版の編集部ですから、
[tab]当たってるか確認してから来てくださいね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_3a8);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitSet(LBIT_0013);
    dialogFree(ref_3a4);
    ref_3ae = bustupFade(ref_3a2, rgb(0,0,0), 10);
    bustupWait(ref_3ae);
    bustupFree(ref_3a2);
    bitClear(LBIT_0007);
    bitGet(var_0, LBIT_0002);
    bnz(var_0, label_3bd);
    bitGet(var_0, LBIT_0008);
    bnz(var_0, label_3bd);
    bitGet(var_0, LBIT_0003);
    bnz(var_0, label_3bd);
    bitGet(var_0, LBIT_0009);
    bnz(var_0, label_3bd);
    delayClear();
    delayWait(30);
    b(label_34b);
  label_3bd:
    b(label_391);
  label_3be:
    ref_3be = bustupLoad(bustup_e6);
    bustupWait(ref_3be);
    ref_3c0 = bustupAlloc(ref_3be, right, rgb(0,0,0));
    bustupFade(ref_3c0, rgb(128,0,0), 30);
    ref_3c2 = dialogAlloc();
    msgShow(msg_44);
/***************************************
[color(yellow)]たまきちゃん[color(white)]

***************************************/
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_3c8);
    msgShow(msg_45);
/***************************************
[tab]ＯＫ、応募ですね。

***************************************/
    b(label_3cb);
  label_3c8:
    bne(var_0, 1, label_3cb);
    msgShow(msg_46);
/***************************************
[tab]お、続けて応募ですね。

***************************************/
    b(label_3cb);
  label_3cb:
    ref_3cb = msgShow(msg_47);
/***************************************
[tab]え～と、別冊ミラクルは…[delay(30)]
[tab]ブッブーッ！！[tab]ダメで～す。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_3cb);
    ref_3ce = msgShow(msg_48);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]この前応募した分、確認してませんね？
[tab]受け取りはキスメット出版の編集部ですから、
[tab]当たってるか確認してから来てくださいね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_3ce);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitSet(LBIT_0013);
    dialogFree(ref_3c2);
    ref_3d4 = bustupFade(ref_3c0, rgb(0,0,0), 10);
    bustupWait(ref_3d4);
    bustupFree(ref_3c0);
    delayClear();
    delayWait(30);
    bitClear(LBIT_0008);
    bitGet(var_0, LBIT_0003);
    bnz(var_0, label_3df);
    bitGet(var_0, LBIT_0009);
    bnz(var_0, label_3df);
    b(label_34b);
  label_3df:
    b(label_395);
  label_3e0:
    ref_3e0 = bustupLoad(bustup_e6);
    bustupWait(ref_3e0);
    ref_3e2 = bustupAlloc(ref_3e0, right, rgb(0,0,0));
    bustupFade(ref_3e2, rgb(128,0,0), 30);
    ref_3e4 = dialogAlloc();
    msgShow(msg_49);
/***************************************
[color(yellow)]たまきちゃん[color(white)]

***************************************/
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_3ea);
    msgShow(msg_50);
/***************************************
[tab]ＯＫ、応募ですね。

***************************************/
    b(label_3ed);
  label_3ea:
    bne(var_0, 1, label_3ed);
    msgShow(msg_51);
/***************************************
[tab]お、続けて応募ですね。

***************************************/
    b(label_3ed);
  label_3ed:
    ref_3ed = msgShow(msg_52);
/***************************************
[tab]え～と、ファンタジーワールドは…[delay(30)]
[tab]ブッブーッ！！[tab]ダメで～す。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_3ed);
    ref_3f0 = msgShow(msg_53);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]この前応募した分、確認してませんね？
[tab]受け取りはキスメット出版の編集部ですから、
[tab]当たってるか確認してから来てくださいね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_3f0);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_3e4);
    ref_3f5 = bustupFade(ref_3e2, rgb(0,0,0), 10);
    bustupWait(ref_3f5);
    bustupFree(ref_3e2);
    delayClear();
    delayWait(30);
    bitClear(LBIT_0009);
    b(label_34b);
  label_3fc:
    msgVar_Number(msgvar_1, var_b);
    ref_3fd = bustupLoad(bustup_e6);
    bustupWait(ref_3fd);
    ref_3ff = bustupAlloc(ref_3fd, right, rgb(0,0,0));
    bustupFade(ref_3ff, rgb(128,0,0), 30);
    ref_401 = dialogAlloc();
    ref_402 = msgShow(msg_54);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ＯＫ、応募ですね。
[tab]え～と、月刊バトルマスターは…[delay(30)]
[tab][var(msg_var_1)]冊分ですね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_402);
    ref_405 = msgShow(msg_55);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]受け取りは…
[tab]キスメット出版の編集部…っと。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_405);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_401);
    ref_40a = bustupFade(ref_3ff, rgb(0,0,0), 10);
    bustupWait(ref_40a);
    bustupFree(ref_3ff);
    bitSet(LBIT_0004);
    bitSet(LBIT_0013);
    b(label_448);
  label_410:
    msgVar_Number(msgvar_2, var_c);
    ref_411 = bustupLoad(bustup_e6);
    bustupWait(ref_411);
    ref_413 = bustupAlloc(ref_411, right, rgb(0,0,0));
    bustupFade(ref_413, rgb(128,0,0), 30);
    ref_415 = dialogAlloc();
    msgShow(msg_56);
/***************************************
[color(yellow)]たまきちゃん[color(white)]

***************************************/
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_41b);
    msgShow(msg_57);
/***************************************
[tab]ＯＫ、応募ですね。

***************************************/
    b(label_41e);
  label_41b:
    bne(var_0, 1, label_41e);
    msgShow(msg_58);
/***************************************
[tab]お、続けて応募ですね。

***************************************/
    b(label_41e);
  label_41e:
    ref_41e = msgShow(msg_59);
/***************************************
[tab]え～と、別冊ミラクルは…[delay(30)]
[tab][var(msg_var_2)]冊分ですね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_41e);
    ref_421 = msgShow(msg_60);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]受け取りは…
[tab]キスメット出版の編集部…っと。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_421);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_415);
    ref_426 = bustupFade(ref_413, rgb(0,0,0), 10);
    bustupWait(ref_426);
    bustupFree(ref_413);
    bitSet(LBIT_0005);
    bitSet(LBIT_0013);
    b(label_448);
  label_42c:
    msgVar_Number(msgvar_3, var_d);
    ref_42d = bustupLoad(bustup_e6);
    bustupWait(ref_42d);
    ref_42f = bustupAlloc(ref_42d, right, rgb(0,0,0));
    bustupFade(ref_42f, rgb(128,0,0), 30);
    ref_431 = dialogAlloc();
    msgShow(msg_61);
/***************************************
[color(yellow)]たまきちゃん[color(white)]

***************************************/
    bitGet(var_0, LBIT_0013);
    bne(var_0, 0, label_437);
    msgShow(msg_62);
/***************************************
[tab]ＯＫ、応募ですね。

***************************************/
    b(label_43a);
  label_437:
    bne(var_0, 1, label_43a);
    msgShow(msg_63);
/***************************************
[tab]お、続けて応募ですね。

***************************************/
    b(label_43a);
  label_43a:
    ref_43a = msgShow(msg_64);
/***************************************
[tab]え～と、ファンタジーワールドは…[delay(30)]
[tab][var(msg_var_3)]冊分ですね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_43a);
    ref_43d = msgShow(msg_65);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]受け取りは…
[tab]キスメット出版の編集部…っと。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_43d);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_431);
    ref_442 = bustupFade(ref_42f, rgb(0,0,0), 10);
    bustupWait(ref_442);
    bustupFree(ref_42f);
    bitSet(LBIT_0006);
    bitSet(LBIT_0013);
    b(label_448);
  label_448:
    choiceSetResult(1);
    ref_449 = bustupLoad(bustup_1);
    bustupWait(ref_449);
    ref_44b = bustupAlloc(ref_449, center, rgb(0,0,0));
    bustupFade(ref_44b, rgb(128,0,0), 30);
    ref_44d = dialogChoiceAlloc();
    ref_44e = msgShow(msg_66);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]本当にいいんですか～？
[choice(2)]ＯＫ
やっぱりやめる
[end_choice][clear]
***************************************/
    wait(ref_44e);
    dialogFree(ref_44d);
    ref_451 = bustupFade(ref_44b, rgb(0,0,0), 10);
    bustupWait(ref_451);
    bustupFree(ref_44b);
    choiceGetResult(var_0);
    bne(var_0, 0, label_458);
    b(label_45b);
    b(label_45b);
  label_458:
    bne(var_0, 1, label_45b);
    b(label_4a1);
    b(label_45b);
  label_45b:
    bitGet(var_0, LBIT_0004);
    bez(var_0, label_462);
    sweepstakesEnter(battle);
    bitSet(MBIT_BATLE_OUBO);
    bitClear(LBIT_0004);
    bitClear(LBIT_0001);
    b(label_46f);
  label_462:
    bitGet(var_0, LBIT_0005);
    bez(var_0, label_469);
    sweepstakesEnter(miracle);
    bitSet(MBIT_MRCLE_OUBO);
    bitClear(LBIT_0005);
    bitClear(LBIT_0002);
    b(label_46f);
  label_469:
    bitGet(var_0, LBIT_0006);
    bez(var_0, label_46f);
    sweepstakesEnter(fantasy);
    bitSet(MBIT_WORLD_OUBO);
    bitClear(LBIT_0006);
    bitClear(LBIT_0003);
  label_46f:
    bitGet(var_0, LBIT_0002);
    bnz(var_0, label_485);
    bitGet(var_0, LBIT_0008);
    bnz(var_0, label_485);
    bitGet(var_0, LBIT_0003);
    bnz(var_0, label_493);
    bitGet(var_0, LBIT_0009);
    bnz(var_0, label_493);
    ref_477 = bustupLoad(bustup_e6);
    bustupWait(ref_477);
    ref_479 = bustupAlloc(ref_477, right, rgb(0,0,0));
    bustupFade(ref_479, rgb(128,0,0), 30);
    ref_47b = dialogAlloc();
    ref_47c = msgShow(msg_67);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]ちゃーんと応募しときますよ。
[tab]なんか当たるといいですね！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_47c);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_47b);
    ref_481 = bustupFade(ref_479, rgb(0,0,0), 10);
    bustupWait(ref_481);
    bustupFree(ref_479);
    b(label_34b);
  label_485:
    ref_485 = bustupLoad(bustup_e6);
    bustupWait(ref_485);
    ref_487 = bustupAlloc(ref_485, right, rgb(0,0,0));
    bustupFade(ref_487, rgb(128,0,0), 30);
    ref_489 = dialogAlloc();
    ref_48a = msgShow(msg_68);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！[tab]ちゃーんと応募しますね。
[tab]え～と、あとは…
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_48a);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_489);
    ref_48f = bustupFade(ref_487, rgb(0,0,0), 10);
    bustupWait(ref_48f);
    bustupFree(ref_487);
    b(label_391);
  label_493:
    ref_493 = bustupLoad(bustup_e6);
    bustupWait(ref_493);
    ref_495 = bustupAlloc(ref_493, right, rgb(0,0,0));
    bustupFade(ref_495, rgb(128,0,0), 30);
    ref_497 = dialogAlloc();
    ref_498 = msgShow(msg_69);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！[tab]ちゃーんと応募しますね。
[tab]え～と、あとは…
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_498);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_497);
    ref_49d = bustupFade(ref_495, rgb(0,0,0), 10);
    bustupWait(ref_49d);
    bustupFree(ref_495);
    b(label_395);
  label_4a1:
    bitGet(var_0, LBIT_0004);
    bez(var_0, label_4a6);
    bitClear(LBIT_0004);
    bitClear(LBIT_0001);
    b(label_4af);
  label_4a6:
    bitGet(var_0, LBIT_0005);
    bez(var_0, label_4ab);
    bitClear(LBIT_0005);
    bitClear(LBIT_0002);
    b(label_4af);
  label_4ab:
    bitGet(var_0, LBIT_0006);
    bez(var_0, label_4af);
    bitClear(LBIT_0006);
    bitClear(LBIT_0003);
  label_4af:
    bitGet(var_0, LBIT_0002);
    bnz(var_0, label_4c5);
    bitGet(var_0, LBIT_0008);
    bnz(var_0, label_4c5);
    bitGet(var_0, LBIT_0003);
    bnz(var_0, label_4d5);
    bitGet(var_0, LBIT_0009);
    bnz(var_0, label_4d5);
    ref_4b7 = bustupLoad(bustup_e6);
    bustupWait(ref_4b7);
    ref_4b9 = bustupAlloc(ref_4b7, right, rgb(0,0,0));
    bustupFade(ref_4b9, rgb(128,0,0), 30);
    ref_4bb = dialogAlloc();
    ref_4bc = msgShow(msg_70);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]応募したくなったらまた来てくださいね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_4bc);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_4bb);
    ref_4c1 = bustupFade(ref_4b9, rgb(0,0,0), 10);
    bustupWait(ref_4c1);
    bustupFree(ref_4b9);
    b(label_34b);
  label_4c5:
    ref_4c5 = bustupLoad(bustup_e6);
    bustupWait(ref_4c5);
    ref_4c7 = bustupAlloc(ref_4c5, right, rgb(0,0,0));
    bustupFade(ref_4c7, rgb(128,0,0), 30);
    ref_4c9 = dialogAlloc();
    ref_4ca = msgShow(msg_71);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]応募したくなったら言ってくださいね。
[tab]え～と、あとは…
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_4ca);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_4c9);
    ref_4cf = bustupFade(ref_4c7, rgb(0,0,0), 10);
    bustupWait(ref_4cf);
    bustupFree(ref_4c7);
    delayClear();
    delayWait(30);
    b(label_391);
  label_4d5:
    ref_4d5 = bustupLoad(bustup_e6);
    bustupWait(ref_4d5);
    ref_4d7 = bustupAlloc(ref_4d5, right, rgb(0,0,0));
    bustupFade(ref_4d7, rgb(128,0,0), 30);
    ref_4d9 = dialogAlloc();
    ref_4da = msgShow(msg_72);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]応募したくなったら言ってくださいね。
[tab]え～と、あとは…
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_4da);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_4d9);
    ref_4df = bustupFade(ref_4d7, rgb(0,0,0), 10);
    bustupWait(ref_4df);
    bustupFree(ref_4d7);
    delayClear();
    delayWait(30);
    b(label_395);
  label_4e5:
    ref_4e5 = bustupLoad(bustup_e6);
    bustupWait(ref_4e5);
    ref_4e7 = bustupAlloc(ref_4e5, right, rgb(0,0,0));
    bustupFade(ref_4e7, rgb(128,0,0), 30);
    ref_4e9 = dialogAlloc();
    ref_4ea = msgShow(msg_73);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ＯＫ！[delay(30)]
[tab]…って天野さ～ん、１冊も持ってないですよ～
[tab]サトミタダシで買ってから来てくださいね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_4ea);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_4e9);
    ref_4ef = bustupFade(ref_4e7, rgb(0,0,0), 10);
    bustupWait(ref_4ef);
    bustupFree(ref_4e7);
    b(label_34b);
  label_4f3:
    ref_4f3 = bustupLoad(bustup_e6);
    bustupWait(ref_4f3);
    ref_4f5 = bustupAlloc(ref_4f3, right, rgb(0,0,0));
    bustupFade(ref_4f5, rgb(128,0,0), 30);
    ref_4f7 = dialogAlloc();
    ref_4f8 = msgShow(msg_74);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]…これで終わりみたいですよ。
[tab]なんか当たるといいですね！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_4f8);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_4f7);
    ref_4fd = bustupFade(ref_4f5, rgb(0,0,0), 10);
    bustupWait(ref_4fd);
    bustupFree(ref_4f5);
    b(label_34b);
  label_501:
    ref_501 = bustupLoad(bustup_e6);
    bustupWait(ref_501);
    ref_503 = bustupAlloc(ref_501, right, rgb(0,0,0));
    bustupFade(ref_503, rgb(128,0,0), 30);
    ref_505 = dialogAlloc();
    ref_506 = msgShow(msg_75);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]懸賞は抽選で何々を差し上げますってヤツ。
[tab]本を買って応募すれば、ある程度の確率で
[tab]アイテムが貰えるの。当たればラッキー！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_506);
    ref_509 = msgShow(msg_76);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]手順は、懸賞のついた雑誌をサトミタダシで購入。
[tab]私に雑誌を渡す。私がかわって応募。
[tab]キスメット出版編集部で受け取る…ってカンジ。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_509);
    ref_50c = msgShow(msg_77);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ここでルール！！[tab]まず応募は一回ずつ。
[tab]先の当選結果が出るまで次の応募はできないの。
[tab]…なぜって？[tab]そういうモノなの！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_50c);
    ref_50f = msgShow(msg_78);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]それから、一度に応募できるのは、９９冊分まで。
[tab]やっぱ、たくさん送った方が当たりやすいわ。
[tab]私的には毎回９９冊分での挑戦がオススメ！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_50f);
    ref_512 = msgShow(msg_79);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]最後に、結果が出るまでにはある程度時間が必要。
[tab]ジッとしててもダメダメ。
[tab]ひたすらダンジョンを歩く歩く。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_512);
    ref_515 = msgShow(msg_80);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]後は根気と運しだい！
[tab]夢を捨てない天野さんなら、
[tab]レアなアイテムが取れるかも…
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_515);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_505);
    ref_51a = bustupFade(ref_503, rgb(0,0,0), 10);
    bustupWait(ref_51a);
    bustupFree(ref_503);
    b(label_34b);
  label_51e:
    ref_51e = bustupLoad(bustup_e6);
    bustupWait(ref_51e);
    ref_520 = bustupAlloc(ref_51e, right, rgb(0,0,0));
    bustupFade(ref_520, rgb(128,0,0), 30);
    ref_522 = dialogAlloc();
    ref_523 = msgShow(msg_81);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]あっれぇ～？[tab]天野さん最近なんかありました？
[tab]…だって、すっごくキレイになったもん！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_523);
    ref_526 = msgShow(msg_82);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]はっは～ん？[tab]さては…
[tab]な～んてね！！[tab]エヘヘ。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_526);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_533);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_52f);
    b(label_532);
  label_52f:
    bne(var_0, 1, label_532);
    shopOverlayInit();
    b(label_532);
  label_532:
    b(label_535);
  label_533:
    bne(var_0, 1, label_535);
    b(label_535);
  label_535:
    dialogFree(ref_522);
    ref_536 = bustupFade(ref_520, rgb(0,0,0), 10);
    bustupWait(ref_536);
    bustupFree(ref_520);
    b(label_607);
  label_53a:
    bitGet(var_0, EBIT_E0046);
    bne(var_0, 0, label_53d);
    b(label_54f);
  label_53d:
    bne(var_0, 1, label_54f);
    bitGet(var_0, EBIT_E009F);
    bne(var_0, 0, label_54c);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_546);
    bitGet(var_0, MBIT_KUZU_T_TALK_E);
    bnz(var_0, label_54f);
    b(label_5d5);
    b(label_54b);
  label_546:
    bne(var_0, 1, label_54b);
    bitGet(var_0, MBIT_KUZU_T_TALK_N);
    bnz(var_0, label_54f);
    b(label_5b9);
    b(label_54b);
  label_54b:
    b(label_54e);
  label_54c:
    bne(var_0, 1, label_54e);
    b(label_54e);
  label_54e:
    b(label_54f);
  label_54f:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_5a0);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_587);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_56e);
    ref_555 = bustupLoad(bustup_e6);
    bustupWait(ref_555);
    ref_557 = bustupAlloc(ref_555, right, rgb(0,0,0));
    bustupFade(ref_557, rgb(128,0,0), 30);
    ref_559 = dialogAlloc();
    ref_55a = msgShow(msg_83);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]新世塾かぁ。ゼンゼン聞いたことないけど、
[tab]財界の大物とかが参加してるんでしょ？
[tab]じゃあ、すぐに尻尾は掴めそうね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_55a);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_567);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_563);
    b(label_566);
  label_563:
    bne(var_0, 1, label_566);
    shopOverlayInit();
    b(label_566);
  label_566:
    b(label_569);
  label_567:
    bne(var_0, 1, label_569);
    b(label_569);
  label_569:
    dialogFree(ref_559);
    ref_56a = bustupFade(ref_557, rgb(0,0,0), 10);
    bustupWait(ref_56a);
    bustupFree(ref_557);
    b(label_5f1);
  label_56e:
    ref_56e = bustupLoad(bustup_e6);
    bustupWait(ref_56e);
    ref_570 = bustupAlloc(ref_56e, right, rgb(0,0,0));
    bustupFade(ref_570, rgb(128,0,0), 30);
    ref_572 = dialogAlloc();
    ref_573 = msgShow(msg_84);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]新世塾の目的ってトンデモないスケールなのね。
[tab]私の想像を遥かに超えていたわ。
[tab]気をつけてね、天野さん。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_573);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_580);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_57c);
    b(label_57f);
  label_57c:
    bne(var_0, 1, label_57f);
    shopOverlayInit();
    b(label_57f);
  label_57f:
    b(label_582);
  label_580:
    bne(var_0, 1, label_582);
    b(label_582);
  label_582:
    dialogFree(ref_572);
    ref_583 = bustupFade(ref_570, rgb(0,0,0), 10);
    bustupWait(ref_583);
    bustupFree(ref_570);
    b(label_5f1);
  label_587:
    ref_587 = bustupLoad(bustup_e6);
    bustupWait(ref_587);
    ref_589 = bustupAlloc(ref_587, right, rgb(0,0,0));
    bustupFade(ref_589, rgb(128,0,0), 30);
    ref_58b = dialogAlloc();
    ref_58c = msgShow(msg_85);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]この街がアメノトリフネになったのって、
[tab]やっぱりみんなの噂が原因なのかしら？
[tab]ということは…世界も滅亡？[tab]うそー！？
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_58c);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_599);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_595);
    b(label_598);
  label_595:
    bne(var_0, 1, label_598);
    shopOverlayInit();
    b(label_598);
  label_598:
    b(label_59b);
  label_599:
    bne(var_0, 1, label_59b);
    b(label_59b);
  label_59b:
    dialogFree(ref_58b);
    ref_59c = bustupFade(ref_589, rgb(0,0,0), 10);
    bustupWait(ref_59c);
    bustupFree(ref_589);
    b(label_5f1);
  label_5a0:
    ref_5a0 = bustupLoad(bustup_e6);
    bustupWait(ref_5a0);
    ref_5a2 = bustupAlloc(ref_5a0, right, rgb(0,0,0));
    bustupFade(ref_5a2, rgb(128,0,0), 30);
    ref_5a4 = dialogAlloc();
    ref_5a5 = msgShow(msg_86);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]こんな状況なのに、アイツまだ帰ってこないのよ。
[tab]私の事…心配じゃないのかな？[delay(30)]
[tab]ただしーッ、[delay(30)]どこ行っちゃったのーッ！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_5a5);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_5b2);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_5ae);
    b(label_5b1);
  label_5ae:
    bne(var_0, 1, label_5b1);
    shopOverlayInit();
    b(label_5b1);
  label_5b1:
    b(label_5b4);
  label_5b2:
    bne(var_0, 1, label_5b4);
    b(label_5b4);
  label_5b4:
    dialogFree(ref_5a4);
    ref_5b5 = bustupFade(ref_5a2, rgb(0,0,0), 10);
    bustupWait(ref_5b5);
    bustupFree(ref_5a2);
    b(label_5f1);
  label_5b9:
    ref_5b9 = bustupLoad(bustup_e6);
    bustupWait(ref_5b9);
    ref_5bb = bustupAlloc(ref_5b9, right, rgb(0,0,0));
    bustupFade(ref_5bb, rgb(128,0,0), 30);
    ref_5bd = dialogAlloc();
    ref_5be = msgShow(msg_87);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]あれっ、南条君じゃない？
[tab]どうして天野さん達と一緒なの？
[tab]…え、エリーも？[tab]ふ～ん、そうなんだ。
[wait][clear]
***************************************/
    wait(ref_5be);
    unitAnimationPlay(unit_58, animation_24, 1);
    ref_5c1 = msgShow(msg_88);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]南条君とエリーはね、
[tab]わたしと同じエルミン学園卒業生なの。
[tab]みんな元気でなによりね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_5c1);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_5ce);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_5ca);
    b(label_5cd);
  label_5ca:
    bne(var_0, 1, label_5cd);
    shopOverlayInit();
    b(label_5cd);
  label_5cd:
    b(label_5d0);
  label_5ce:
    bne(var_0, 1, label_5d0);
    b(label_5d0);
  label_5d0:
    dialogFree(ref_5bd);
    ref_5d1 = bustupFade(ref_5bb, rgb(0,0,0), 10);
    bustupWait(ref_5d1);
    bustupFree(ref_5bb);
    b(label_5f1);
  label_5d5:
    ref_5d5 = bustupLoad(bustup_e6);
    bustupWait(ref_5d5);
    ref_5d7 = bustupAlloc(ref_5d5, right, rgb(0,0,0));
    bustupFade(ref_5d7, rgb(128,0,0), 30);
    ref_5d9 = dialogAlloc();
    ref_5da = msgShow(msg_89);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]あれっ、エリーじゃない？
[tab]どうして天野さん達と一緒なの？
[tab]…え、南条君も？[tab]ふ～ん、そうなんだ。
[wait][clear]
***************************************/
    wait(ref_5da);
    unitAnimationPlay(unit_58, animation_24, 1);
    ref_5dd = msgShow(msg_90);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]エリーと南条君はね、
[tab]わたしと同じエルミン学園卒業生なの。
[tab]みんな元気でなによりね。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_5dd);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_5ea);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_5e6);
    b(label_5e9);
  label_5e6:
    bne(var_0, 1, label_5e9);
    shopOverlayInit();
    b(label_5e9);
  label_5e9:
    b(label_5ec);
  label_5ea:
    bne(var_0, 1, label_5ec);
    b(label_5ec);
  label_5ec:
    dialogFree(ref_5d9);
    ref_5ed = bustupFade(ref_5d7, rgb(0,0,0), 10);
    bustupWait(ref_5ed);
    bustupFree(ref_5d7);
    b(label_5f1);
  label_5f1:
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bnz(var_0, label_34b);
    bez(var_0, label_607);
  label_5f4:
    ref_5f4 = bustupLoad(bustup_e6);
    bustupWait(ref_5f4);
    ref_5f6 = bustupAlloc(ref_5f4, right, rgb(0,0,0));
    bustupFade(ref_5f6, rgb(128,0,0), 30);
    ref_5f8 = dialogAlloc();
    ref_5f9 = msgShow(msg_91);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]何かあったら言ってくださいね。
[tab]わたしにできる事なら、お手伝いしますから。
[tab][delay(30)]…できる事だけですよ？
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_5f9);
    unitAnimationPlay(unit_58, animation_0, 1);
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_600);
    b(label_603);
  label_600:
    bne(var_0, 1, label_603);
    shopOverlayInit();
    b(label_603);
  label_603:
    dialogFree(ref_5f8);
    ref_604 = bustupFade(ref_5f6, rgb(0,0,0), 10);
    bustupWait(ref_604);
    bustupFree(ref_5f6);
  label_607:
    unitRestoreFacing(unit_58);
    controlEnable();
}

function MAN1()
{
    li(var_5, 0);
    li(var_6, 0);
    li(var_7, 0);
    li(var_8, 0);
    bitGet(var_0, MBIT_KUZU_HATUNEKO);
    bne(var_0, 0, label_614);
    bitSet(MBIT_KUZU_HATUNEKO);
    envTriggerClear(collision_1, coll_1);
    b(label_626);
    b(label_626);
  label_614:
    bne(var_0, 1, label_626);
    controlDisable();
    playerConvertToUnit(maya, sprite_0, north);
    playerHide();
    unitFaceUnit(maya, npc1);
    sndMusicPlay(sound_30db, 127);
    sndVolumeFadeOff(sound_3005, 120);
    objAnimRotate(obj_6, 0, 110, 0, 30, 0);
    objAnimWait(obj_6);
    ref_61d = cameraRotateTo(3, 45);
    unitMove(maya, 300, -150, face_east, fast);
    cameraFollow(maya);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_30de, 127);
    wait(ref_61d);
    b(label_632);
    b(label_626);
  label_626:
    ref_626 = dialogAlloc();
    ref_627 = msgShow(msg_92);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]あらためて…はじめましてニャー
[tab]アタシは噂好きのネコマタなのニャ♥
[tab]ヒトの知らない噂を集めてるのニャー
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_8, 1);
    wait(ref_627);
    ref_62a = msgShow(msg_93);
/***************************************
[color(yellow)]ネコマタ[color(green)]
[tab]デビルサマナーであるたまきちゃんの仲魔。
[tab]いたずら好きでお金に目が無い困り者。
[tab]悪魔のあいだに広まる特殊な噂に詳しい。[color(white)]
[wait][clear]
***************************************/
    wait(ref_62a);
    ref_62c = msgShow(msg_94);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ところで…
[tab]今日はどんニャ用なのかニャー？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_62c);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_626);
    b(label_63c);
  label_632:
    ref_632 = dialogAlloc();
    ref_633 = msgShow(msg_95);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ニャニャ♥[tab]また来たニャ！？
[tab]アタシの話を聞きたいのかニャ～？
[tab]でも、[delay(30)]ドアを開ける時はノックを忘れるニャ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_633);
    ref_636 = msgShow(msg_96);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ところで…
[tab]今日はどんニャ用なのかニャー？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_636);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_632);
    b(label_63c);
  label_63c:
    choiceSetResult(2);
    ref_63d = bustupLoad(bustup_1);
    bustupWait(ref_63d);
    ref_63f = bustupAlloc(ref_63d, center, rgb(0,0,0));
    bustupFade(ref_63f, rgb(128,0,0), 30);
    ref_641 = dialogChoiceAlloc();
    ref_642 = msgShow(msg_97);
/***************************************
[tab]今日はどんニャ用なのかニャー？
[choice(3)]噂話を聞きたい
話を聞きたい
用はない
[end_choice][clear]
***************************************/
    wait(ref_642);
    dialogFree(ref_641);
    ref_645 = bustupFade(ref_63f, rgb(0,0,0), 10);
    bustupWait(ref_645);
    bustupFree(ref_63f);
    choiceGetResult(var_0);
    bne(var_0, 0, label_64c);
    b(label_652);
    b(label_652);
  label_64c:
    bne(var_0, 1, label_64f);
    b(label_6de);
    b(label_652);
  label_64f:
    bne(var_0, 2, label_652);
    b(label_704);
    b(label_652);
  label_652:
    bitGet(var_0, EBIT_E0046);
    bez(var_0, label_661);
    bitGet(var_0, MBIT_TRI_ISATU);
    bez(var_0, label_661);
    bitGet(var_0, MBIT_HI_TRISHOKUJI);
    bez(var_0, label_661);
    bitGet(var_0, MBIT_KE_TRIKAISIN);
    bitGet(var_1, MBIT_KI_TRIKAISIN);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_65f);
    li(var_5, 1);
    b(label_68a);
    b(label_661);
  label_65f:
    boutrange(var_1, 1, 2, label_661);
    b(label_661);
  label_661:
    bitGet(var_0, EBIT_E0018);
    bez(var_0, label_683);
    bitGet(var_0, MBIT_KE_KAORIAROMA);
    bitGet(var_1, MBIT_KI_KAORIAROMA);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_66a);
    li(var_6, 1);
    b(label_68a);
    b(label_66c);
  label_66a:
    boutrange(var_1, 1, 2, label_66c);
    b(label_66c);
  label_66c:
    bitGet(var_0, MBIT_KE_ETEESTHE);
    bitGet(var_1, MBIT_KI_ETEESTHE);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_673);
    li(var_7, 1);
    b(label_68a);
    b(label_675);
  label_673:
    boutrange(var_1, 1, 2, label_675);
    b(label_675);
  label_675:
    bitGet(var_0, MBIT_TRI_ISATU);
    bne(var_0, 0, label_678);
    b(label_683);
  label_678:
    bne(var_0, 1, label_683);
    bitGet(var_0, MBIT_KE_TRISHOKUJI);
    bitGet(var_1, MBIT_KI_TRISHOKUJI);
    add(var_1, var_1, var_0);
    bne(var_1, 0, label_680);
    li(var_8, 1);
    b(label_68a);
    b(label_682);
  label_680:
    boutrange(var_1, 1, 2, label_682);
    b(label_682);
  label_682:
    b(label_683);
  label_683:
    ref_683 = dialogAlloc();
    ref_684 = msgShow(msg_98);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]話せる噂はもうないニャ～
[tab]…ごめんニャ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_684);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_683);
    b(label_6dd);
  label_68a:
    ref_68a = dialogAlloc();
    unitAnimationPlay(npc1, animation_1a, 1);
    rand(var_0, 11);
    boutrange(var_0, 0, 3, label_691);
    ref_68e = msgShow(msg_99);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]噂を聞きたいのかニャ？
[tab]そうだニャ～
[tab]そっちも何か噂を教えてくれニャ！
[wait][clear]
***************************************/
    wait(ref_68e);
    b(label_699);
  label_691:
    boutrange(var_0, 4, 7, label_695);
    ref_692 = msgShow(msg_100);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ニャンと、噂を教えろと言うのか！
[tab]じゃあ、かわりの噂を教えてくれニャ！
[tab]アタシと情報交換ニャ～！
[wait][clear]
***************************************/
    wait(ref_692);
    b(label_699);
  label_695:
    boutrange(var_0, 8, 11, label_699);
    ref_696 = msgShow(msg_101);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]アタシの情報は特別ニャー♥
[tab]それに見合った噂はお持ちかニャ？
[wait][clear]
***************************************/
    wait(ref_696);
    b(label_699);
  label_699:
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_68a);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(maya, animation_2d, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_1a, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc1, animation_1a, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc1, animation_0, 1);
    delayClear();
    delayWait(15);
    ref_6b0 = dialogAlloc();
    unitAnimationPlay(npc1, animation_1a, 1);
    rand(var_0, 11);
    boutrange(var_0, 0, 3, label_6b7);
    ref_6b4 = msgShow(msg_102);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]そ、それはホントかニャー！？
[tab]スゴイことを知ってしまったニャ！
[tab]…約束通り、アタシも教えるニャ。
[wait][clear]
***************************************/
    wait(ref_6b4);
    b(label_6bf);
  label_6b7:
    boutrange(var_0, 4, 7, label_6bb);
    ref_6b8 = msgShow(msg_103);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]へー、あのヒトにそんな噂まであるんニャ。
[tab]ふーん、人間って面白いニャー
[tab]じゃ、次はアタシの番ニャ♥
[wait][clear]
***************************************/
    wait(ref_6b8);
    b(label_6bf);
  label_6bb:
    boutrange(var_0, 8, 11, label_6bf);
    ref_6bc = msgShow(msg_104);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]それって良く聞く噂ニャ～
[tab]ま、今日はそれで勘弁してやるかニャ？
[wait][clear]
***************************************/
    wait(ref_6bc);
    b(label_6bf);
  label_6bf:
    bnz(var_5, label_6c3);
    bnz(var_6, label_6c9);
    bnz(var_7, label_6cf);
    bnz(var_8, label_6d5);
  label_6c3:
    ref_6c3 = msgShow(msg_105);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab][color(orange)]トリッシュ[color(white)]って悪魔は知ってるニャ？
[tab]嘘かホントか、[color(orange)]改心した[color(white)]って評判ニャ！
[tab]アタシにはどうしても信じられないニャー
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6c3);
    bitSet(MBIT_KI_TRIKAISIN);
    li(var_5, 0);
    b(label_6db);
  label_6c9:
    ref_6c9 = msgShow(msg_106);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab][color(orange)]かおり[color(white)]ってお店、知ってるかニャー？
[tab]じゃ、そこで[color(orange)]アロマテラピーを始めた[color(white)]の知ってる？
[tab]アレはキクのニャ。悪魔もびっくりニャー！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6c9);
    bitSet(MBIT_KI_KAORIAROMA);
    li(var_6, 0);
    b(label_6db);
  label_6cf:
    ref_6cf = msgShow(msg_107);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]あやしいエステの店…ニャんだっけ？[tab]そうそう！
[tab]あの[color(orange)]エテーリア[color(white)]のエステに、[color(orange)]新たなエステコース[color(white)]が
[tab]追加されたらしいニャ。悪魔もうっとりニャー
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6cf);
    bitSet(MBIT_KI_ETEESTHE);
    li(var_7, 0);
    b(label_6db);
  label_6d5:
    ref_6d5 = msgShow(msg_108);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab][color(orange)]トリッシュ[color(white)]って悪魔に会った事あるかニャ？
[tab]噂によると、ダンジョンの中で[color(orange)]アイスを売り始めた[color(white)]
[tab]らしいのニャ。きっと金儲けの為ニャー
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6d5);
    bitSet(MBIT_KI_TRISHOKUJI);
    li(var_8, 0);
    b(label_6db);
  label_6db:
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_6b0);
  label_6dd:
    b(label_63c);
  label_6de:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_6fc);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_6f5);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_6eb);
    ref_6e4 = dialogAlloc();
    ref_6e5 = msgShow(msg_109);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]最近、悪魔はないがしろにされてるニャー
[tab]ねぇ、アタシたち悪魔の事、どーおもってるの？
[tab]…昔は「仲魔」って呼んでニャかった？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6e5);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_6e4);
    b(label_703);
  label_6eb:
    ref_6eb = dialogAlloc();
    ref_6ec = msgShow(msg_110);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]最近、みんな大騒ぎニャのね？
[tab]ニャにニャに？[tab]外でニャんかあったの？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6ec);
    ref_6ef = msgShow(msg_111);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]…ニャーんだ、新世塾のことか。
[tab]アタシニャんか前から知ってたニャ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6ef);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_6eb);
    b(label_703);
  label_6f5:
    ref_6f5 = dialogAlloc();
    ref_6f6 = msgShow(msg_112);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]世界が滅亡したらどうなるのかニャー？
[tab]そして…アタシたちは？
[tab]ニャーんて、心配なんか全然してないニャ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6f6);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_6f5);
    b(label_703);
  label_6fc:
    ref_6fc = dialogAlloc();
    ref_6fd = msgShow(msg_113);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]…え、にゃ、にゃ、ニャルラトホテプ～！！
[tab]そ、その件に関してはノーコメントなのニャー！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_6fd);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_6fc);
    b(label_703);
  label_703:
    b(label_63c);
  label_704:
    ref_704 = dialogAlloc();
    ref_705 = msgShow(msg_114);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]それじゃまたニャー♥
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_8, 1);
    wait(ref_705);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_704);
    unitRestoreFacing(npc1);
    ref_70b = cameraRotateTo(5, 45);
    sndVolumeFadeOff(sound_30de, 120);
    unitMove(maya, 480, -150, face_west, fast);
    cameraFollow(maya);
    wait(ref_70b);
    sndMusicPlay(sound_3005, 127);
    sndMusicPlay(sound_30dc, 127);
    objAnimRotate(obj_6, 0, -110, 0, 30, 0);
    objAnimWait(obj_6);
    unitWait(maya);
    unitDespawn(maya, none);
    playerInit(west);
    controlEnable();
}

function SHOP()
{
    controlDisable();
    ref_71a = shopOverlayInit();
    unitFacePlayer(shopkeeper);
    bitGet(var_0, MBIT_AIS_19);
    bne(var_0, 0, label_720);
    b(label_723);
    b(label_723);
  label_720:
    bne(var_0, 1, label_723);
    b(label_73a);
    b(label_723);
  label_723:
    ref_723 = bustupLoad(bustup_e5);
    bustupWait(ref_723);
    ref_725 = bustupAlloc(ref_723, right, rgb(0,0,0));
    bustupFade(ref_725, rgb(128,0,0), 30);
    ref_727 = dialogAlloc();
    ref_728 = msgShow(msg_115);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]来たか…

[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitWait(shopkeeper);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_19, 1);
    wait(ref_728);
    dialogFree(ref_727);
    unitWait(shopkeeper);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitWait(shopkeeper);
    ref_733 = bustupFade(ref_725, rgb(0,0,0), 10);
    bustupWait(ref_733);
    bustupFree(ref_725);
    wait(ref_71a);
    shopInventory(14, shopInventory_0);
    shopRate(100);
    b(label_753);
  label_73a:
    ref_73a = bustupLoad(bustup_e5);
    bustupWait(ref_73a);
    ref_73c = bustupAlloc(ref_73a, right, rgb(0,0,0));
    bustupFade(ref_73c, rgb(128,0,0), 30);
    ref_73e = dialogAlloc();
    ref_73f = msgShow(msg_116);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]よぉ、来たな。
[tab]…どうした？[tab]何か困り事か？
[tab]よし、今日は特別に力になってやる。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_73f);
    ref_742 = msgShow(msg_117);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]ただし、依頼料金はいつも通りだぞ。
[tab]…な～に、全ては気持ちの問題だ。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitWait(shopkeeper);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_19, 1);
    wait(ref_742);
    dialogFree(ref_73e);
    unitWait(shopkeeper);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitWait(shopkeeper);
    ref_74d = bustupFade(ref_73c, rgb(0,0,0), 10);
    bustupWait(ref_74d);
    bustupFree(ref_73c);
    wait(ref_71a);
    shopInventory(14, shopInventory_0);
    shopRate(100);
  label_753:
    ref_753 = bustupLoad(bustup_e5);
    bustupWait(ref_753);
    ref_755 = bustupAlloc(ref_753, right, rgb(0,0,0));
    bustupFade(ref_755, rgb(128,0,0), 30);
    choiceSetResult(3);
    ref_758 = dialogAlloc();
    ref_759 = msgShow(msg_118);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]今日の用件はなんだ？
[choice(5)]噂の依頼
噂の確認
話を聞く
やめる
探偵事務所から出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitWait(shopkeeper);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_19, 1);
    wait(ref_759);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_765);
    li(var_5, 0);
    b(label_77d);
  label_765:
    bne(var_0, 1, label_768);
    li(var_5, 1);
    b(label_77d);
  label_768:
    bne(var_0, 2, label_777);
    choiceSetResult(2);
    ref_76a = msgShow(msg_119);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]何について聞きたいんだ？
[choice(3)]世間話を聞く
噂について説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_76a);
    choiceGetResult(var_0);
    bne(var_0, 0, label_770);
    li(var_5, 2);
    b(label_776);
  label_770:
    bne(var_0, 1, label_773);
    li(var_5, 2000);
    b(label_776);
  label_773:
    bne(var_0, 2, label_776);
    li(var_5, 1000);
    b(label_776);
  label_776:
    b(label_77d);
  label_777:
    bne(var_0, 3, label_77a);
    li(var_5, 3);
    b(label_77d);
  label_77a:
    bne(var_0, 4, label_77d);
    li(var_5, 4);
    b(label_77d);
  label_77d:
    dialogFree(ref_758);
    unitWait(shopkeeper);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitWait(shopkeeper);
    ref_781 = bustupFade(ref_755, rgb(0,0,0), 10);
    bustupWait(ref_781);
    bustupFree(ref_755);
    ref_784 = shopOpen(15);
    wait(ref_784);
}

function HA_SHOP_RESTART_0()
{
    choiceSetResult(3);
    ref_788 = bustupLoad(bustup_e5);
    bustupWait(ref_788);
    ref_78a = bustupAlloc(ref_788, right, rgb(0,0,0));
    bustupFade(ref_78a, rgb(128,0,0), 30);
    ref_78c = dialogAlloc();
    ref_78d = msgShow(msg_120);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]他に何かあるか？
[choice(5)]噂の依頼
噂の確認
話を聞く
やめる
探偵事務所から出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_1f, 1);
    wait(ref_78d);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_796);
    li(var_5, 0);
    b(label_7ae);
  label_796:
    bne(var_0, 1, label_799);
    li(var_5, 1);
    b(label_7ae);
  label_799:
    bne(var_0, 2, label_7a8);
    choiceSetResult(2);
    ref_79b = msgShow(msg_121);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]何について聞きたいんだ？
[choice(3)]世間話を聞く
噂について説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_79b);
    choiceGetResult(var_0);
    bne(var_0, 0, label_7a1);
    li(var_5, 2);
    b(label_7a7);
  label_7a1:
    bne(var_0, 1, label_7a4);
    li(var_5, 2000);
    b(label_7a7);
  label_7a4:
    bne(var_0, 2, label_7a7);
    li(var_5, 1000);
    b(label_7a7);
  label_7a7:
    b(label_7ae);
  label_7a8:
    bne(var_0, 3, label_7ab);
    li(var_5, 3);
    b(label_7ae);
  label_7ab:
    bne(var_0, 4, label_7ae);
    li(var_5, 4);
    b(label_7ae);
  label_7ae:
    dialogFree(ref_78c);
    ref_7af = bustupFade(ref_78a, rgb(0,0,0), 10);
    bustupWait(ref_7af);
    bustupFree(ref_78a);
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, EBIT_E0046);
    bne(var_0, 0, label_7b6);
    b(label_7c4);
  label_7b6:
    bne(var_0, 1, label_7c4);
    bitGet(var_0, EBIT_E009F);
    bne(var_0, 0, label_7c1);
    bitGet(var_0, MBIT_KUZU_T_TALK_N);
    bitGet(var_1, MBIT_KUZU_T_TALK_E);
    add(var_0, var_0, var_1);
    bne(var_0, 0, label_7bf);
    b(label_802);
    b(label_7c0);
  label_7bf:
    b(label_7c0);
  label_7c0:
    b(label_7c3);
  label_7c1:
    bne(var_0, 1, label_7c3);
    b(label_7c3);
  label_7c3:
    b(label_7c4);
  label_7c4:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_7f4);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_7e6);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_7d8);
    ref_7ca = bustupLoad(bustup_e5);
    bustupWait(ref_7ca);
    ref_7cc = bustupAlloc(ref_7ca, right, rgb(0,0,0));
    bustupFade(ref_7cc, rgb(128,0,0), 30);
    ref_7ce = dialogAlloc();
    ref_7cf = msgShow(msg_122);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]新世塾…それが事件の裏にいる組織…
[tab]なかなか面白そうな話だな。
[tab]少し探りを入れてみるかな？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_7cf);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7ce);
    ref_7d4 = bustupFade(ref_7cc, rgb(0,0,0), 10);
    bustupWait(ref_7d4);
    bustupFree(ref_7cc);
    b(label_80f);
  label_7d8:
    ref_7d8 = bustupLoad(bustup_e5);
    bustupWait(ref_7d8);
    ref_7da = bustupAlloc(ref_7d8, right, rgb(0,0,0));
    bustupFade(ref_7da, rgb(128,0,0), 30);
    ref_7dc = dialogAlloc();
    ref_7dd = msgShow(msg_123);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]新世塾の連中とまともにやりあう気か？
[tab]フン、素人がどこまでやれるか…見物ではあるな。
[tab]心配するな、お前達の事は忘れずにいてやる。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_7dd);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7dc);
    ref_7e2 = bustupFade(ref_7da, rgb(0,0,0), 10);
    bustupWait(ref_7e2);
    bustupFree(ref_7da);
    b(label_80f);
  label_7e6:
    ref_7e6 = bustupLoad(bustup_e5);
    bustupWait(ref_7e6);
    ref_7e8 = bustupAlloc(ref_7e6, right, rgb(0,0,0));
    bustupFade(ref_7e8, rgb(128,0,0), 30);
    ref_7ea = dialogAlloc();
    ref_7eb = msgShow(msg_124);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]戦いに必要なのは徹底した現実主義と冷静な判断。
[tab]若さに任せて無茶をするのは馬鹿な証拠だ。
[tab]大人なんだ…それくらいわかるな？
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_7eb);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7ea);
    ref_7f0 = bustupFade(ref_7e8, rgb(0,0,0), 10);
    bustupWait(ref_7f0);
    bustupFree(ref_7e8);
    b(label_80f);
  label_7f4:
    ref_7f4 = bustupLoad(bustup_e5);
    bustupWait(ref_7f4);
    ref_7f6 = bustupAlloc(ref_7f4, right, rgb(0,0,0));
    bustupFade(ref_7f6, rgb(128,0,0), 30);
    ref_7f8 = dialogAlloc();
    ref_7f9 = msgShow(msg_125);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]龍が現れた時、皆、心の底から怯えていた。
[tab]罪の意識があるから懺悔せずにはいられなかった。
[tab]…我々は、滅ぶべき種なのかもしれんな。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_7f9);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_7f8);
    ref_7fe = bustupFade(ref_7f6, rgb(0,0,0), 10);
    bustupWait(ref_7fe);
    bustupFree(ref_7f6);
    b(label_80f);
  label_802:
    ref_802 = bustupLoad(bustup_e5);
    bustupWait(ref_802);
    ref_804 = bustupAlloc(ref_802, right, rgb(0,0,0));
    bustupFade(ref_804, rgb(128,0,0), 30);
    ref_806 = dialogAlloc();
    ref_807 = msgShow(msg_126);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]たまきとお前の連れが知り合いだったとはな…
[tab]世の中は狭いもんだ。もっとも、俺がそうした
[tab]人間に出会うことは無いだろうがな…
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_807);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_806);
    ref_80c = bustupFade(ref_804, rgb(0,0,0), 10);
    bustupWait(ref_80c);
    bustupFree(ref_804);
  label_80f:
}

function HA_SHOP_END_0()
{
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bne(var_0, 0, label_815);
    bitGet(var_0, MBIT_DBATOLU);
    bnz(var_0, label_826);
    b(label_817);
  label_815:
    bne(var_0, 1, label_817);
    b(label_817);
  label_817:
    ref_817 = bustupLoad(bustup_e5);
    bustupWait(ref_817);
    ref_819 = bustupAlloc(ref_817, right, rgb(0,0,0));
    bustupFade(ref_819, rgb(128,0,0), 30);
    ref_81b = dialogAlloc();
    ref_81c = msgShow(msg_127);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]俺達が力になれるのは、噂を操作するまでだ。
[tab]後はお前達しだい。
[tab]じゃあ…あばよ。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_81c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopOverlayInit();
    dialogFree(ref_81b);
    ref_822 = bustupFade(ref_819, rgb(0,0,0), 10);
    bustupWait(ref_822);
    bustupFree(ref_819);
    b(label_835);
  label_826:
    ref_826 = bustupLoad(bustup_e5);
    bustupWait(ref_826);
    ref_828 = bustupAlloc(ref_826, right, rgb(0,0,0));
    bustupFade(ref_828, rgb(128,0,0), 30);
    ref_82a = dialogAlloc();
    ref_82b = msgShow(msg_128);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]懸賞か…
[tab]応募は、たまきに頼めばいいだろう。
[tab]彼女に相談してみろ。
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_24, 1);
    wait(ref_82b);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopOverlayInit();
    dialogFree(ref_82a);
    ref_831 = bustupFade(ref_828, rgb(0,0,0), 10);
    bustupWait(ref_831);
    bustupFree(ref_828);
    bitSet(MBIT_KUZU_KENSHOU);
  label_835:
    bitSet(MBIT_KUZU_HATURAITEN);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_83b);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    b(label_83e);
  label_83b:
    bne(var_0, 1, label_83e);
    call(GOOUT);
    b(label_83e);
  label_83e:
}

function BIGNEKO()
{
    controlDisable();
    bitGet(var_0, MBIT_SH_S_15);
    bne(var_0, 0, label_843);
    b(label_850);
  label_843:
    bne(var_0, 1, label_850);
    bitGet(var_0, MBIT_SH_H_15);
    bne(var_0, 0, label_84d);
    bitGet(var_0, MBIT_NEKOMATA_GET);
    bne(var_0, 0, label_84a);
    b(label_851);
    b(label_84c);
  label_84a:
    bne(var_0, 1, label_84c);
    b(label_84c);
  label_84c:
    b(label_84f);
  label_84d:
    bne(var_0, 1, label_84f);
    b(label_84f);
  label_84f:
    b(label_850);
  label_850:
    b(label_89c);
  label_851:
    add(var_a, var_a, 1);
    boutrange(var_a, 0, 1, label_855);
    b(label_859);
    b(label_859);
  label_855:
    bne(var_a, 2, label_859);
    sub(var_a, var_a, 2);
    b(label_85f);
    b(label_859);
  label_859:
    ref_859 = dialogAlloc();
    ref_85a = msgShow(msg_129);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]大人だから、千円入れてニャー♥
[tab]さぁさぁ、迷わずにガツーンと入れるニャ！！
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d4, 127);
    wait(ref_85a);
    dialogFree(ref_859);
    b(label_8b0);
  label_85f:
    ref_85f = dialogAlloc();
    ref_860 = msgShow(msg_130);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]ニャ、ニャッ！？
[tab][delay(15)]…[delay(15)]…[delay(15)]…[delay(15)]ニャ、[delay(15)]ニャー♥
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d4, 127);
    wait(ref_860);
    dialogFree(ref_85f);
    choiceSetResult(2);
    ref_865 = bustupLoad(bustup_1);
    bustupWait(ref_865);
    ref_867 = bustupAlloc(ref_865, center, rgb(0,0,0));
    bustupFade(ref_867, rgb(128,0,0), 30);
    ref_869 = dialogChoiceAlloc();
    ref_86a = msgShow(msg_131);
/***************************************
[tab]……ニャ、ニャー♥
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear]
***************************************/
    ref_86b = textInputInit();
    wait(ref_86a);
    dialogFree(ref_869);
    ref_86e = bustupFade(ref_867, rgb(0,0,0), 10);
    bustupWait(ref_86e);
    bustupFree(ref_867);
    wait(ref_86b);
    choiceGetResult(var_0);
    bne(var_0, 0, label_876);
    b(label_87d);
    b(label_87d);
  label_876:
    bne(var_0, 1, label_879);
    b(label_89c);
    b(label_87d);
  label_879:
    bne(var_0, 2, label_87d);
    controlEnable();
    b(label_9c9);
    b(label_87d);
  label_87d:
    ref_87d = textInputPrompt();
    wait(ref_87d);
    textInputCompare(msg_132, var_0);
    bne(var_0, 0, label_889);
    ref_881 = dialogAlloc();
    ref_882 = msgShow(msg_133);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]ニャニャニャ！？
[tab]ア、アタシはただの置物ニャー♥
[tab]…変な名前で呼ぶニャー！！
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d4, 127);
    wait(ref_882);
    dialogFree(ref_881);
    controlEnable();
    b(label_9c9);
    b(label_89c);
  label_889:
    bne(var_0, 1, label_89c);
    ref_88a = cameraRotateTo(2, 30);
    wait(ref_88a);
    playerConvertToUnit(maya, sprite_0, east);
    playerHide();
    unitFace(maya, west);
    ref_88f = dialogAlloc();
    ref_890 = msgShow(msg_134);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]このアタシを見付けるとはニャ…
[tab]つ、ついにこの日が来てしまったニャ。
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d7, 127);
    unitAnimationHold(maya, animation_22, -1);
    wait(ref_890);
    ref_894 = msgShow(msg_135);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]お前にはアタシの正体を明かそう。
[tab]ただし、たまきちゃんには内緒ニャ！
[tab]さぁ…[delay(15)]こっちに来いニャー！
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d8, 127);
    wait(ref_894);
    dialogFree(ref_88f);
    bitSet(MBIT_NEKOMATA_GET);
    bitSet(MBIT_SH_HH);
    b(label_91e);
    b(label_89c);
  label_89c:
    bitGet(var_0, MBIT_KUZU_HATUBIGNEKO);
    bne(var_0, 0, label_8a9);
    countGet(var_0, nekomata);
    bez(var_0, label_8ab);
    div(var_0, var_0, 10);
    countSet(nekomata, var_0);
    ref_8a2 = dialogAlloc();
    ref_8a3 = msgShow(msg_136);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]久しぶりニャー♥
[tab]今回は大人だから、千円入れてニャー♥
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d4, 127);
    wait(ref_8a3);
    dialogFree(ref_8a2);
    b(label_8b0);
    b(label_8ab);
  label_8a9:
    bne(var_0, 1, label_8ab);
    b(label_8ab);
  label_8ab:
    ref_8ab = dialogAlloc();
    ref_8ac = msgShow(msg_137);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]大人だから、千円入れてニャー♥
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d4, 127);
    wait(ref_8ac);
    dialogFree(ref_8ab);
  label_8b0:
    bitSet(MBIT_KUZU_HATUBIGNEKO);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    choiceSetResult(1);
    ref_8b4 = bustupLoad(bustup_1);
    bustupWait(ref_8b4);
    ref_8b6 = bustupAlloc(ref_8b4, center, rgb(0,0,0));
    bustupFade(ref_8b6, rgb(128,0,0), 30);
    ref_8b8 = dialogChoiceAlloc();
    ref_8b9 = msgShow(msg_138);
/***************************************
[tab]ここに千円入れて欲しいニャー♥
[choice(2)]入れる
入れない
[end_choice][clear]
***************************************/
    wait(ref_8b9);
    dialogFree(ref_8b8);
    ref_8bc = bustupFade(ref_8b6, rgb(0,0,0), 10);
    bustupWait(ref_8bc);
    bustupFree(ref_8b6);
    choiceGetResult(var_7);
    bne(var_7, 0, label_8ef);
    partyMoneyGet(var_6);
    boutrange(var_6, 0, 999, label_8ca);
    ref_8c3 = dialogAlloc();
    ref_8c4 = msgShow(msg_139);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]あっ、持ってないニャー♥
[tab]うそつきは泥棒の始まりニャー♥
[tab]おととい来るニャー♥[wait][clear]
***************************************/
    wait(ref_8c4);
    dialogFree(ref_8c3);
    shopCurrencyDisplay(-110, 150, true);
    controlEnable();
    b(label_8ee);
  label_8ca:
    sndMusicPlay(sound_30d5, 127);
    partyMoneyAdd(-1000);
    delayClear();
    delayWait(60);
    shopCurrencyDisplay(-110, 150, true);
    countGet(var_0, nekomata);
    add(var_0, var_0, 1);
    countSet(nekomata, var_0);
    bne(var_0, 20, label_8d8);
    ref_8d3 = dialogAlloc();
    ref_8d4 = msgShow(msg_140);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]感激ニャ～♥[delay(15)]
[tab]もう２０回も千円入れてもらったニャ～♥[delay(15)]
[tab]今後に期待するニャ～♥[wait][clear]
***************************************/
    wait(ref_8d4);
    dialogFree(ref_8d3);
    b(label_8ec);
  label_8d8:
    bne(var_0, 50, label_8de);
    ref_8d9 = dialogAlloc();
    ref_8da = msgShow(msg_141);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]ニャニャニャ～♥[delay(15)]
[tab]なんともう５０回も千円入れてもらったニャ～♥[delay(15)]
[tab]お姉さん、とっても太っ腹ニャ～♥[wait][clear]
***************************************/
    wait(ref_8da);
    dialogFree(ref_8d9);
    b(label_8ec);
  label_8de:
    bne(var_0, 80, label_8e4);
    ref_8df = dialogAlloc();
    ref_8e0 = msgShow(msg_142);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]凄いニャ～！[tab]凄いニャ～！！[delay(15)]
[tab]もう、８０回も千円入れてもらったニャ～♥[delay(15)]
[tab]何か下心があるニャ？[wait][clear]
***************************************/
    wait(ref_8e0);
    dialogFree(ref_8df);
    b(label_8ec);
  label_8e4:
    bne(var_0, 100, label_8e7);
    b(label_8f9);
    b(label_8ec);
  label_8e7:
    ref_8e7 = dialogAlloc();
    ref_8e8 = msgShow(msg_143);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]ありがとニャー♥[wait][clear]
***************************************/
    wait(ref_8e8);
    dialogFree(ref_8e7);
    b(label_8ec);
  label_8ec:
    controlEnable();
    b(label_8ee);
  label_8ee:
    b(label_8f8);
  label_8ef:
    bne(var_7, 1, label_8f8);
    sndMusicPlay(sound_30d6, 127);
    ref_8f1 = dialogAlloc();
    ref_8f2 = msgShow(msg_144);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]…[delay(15)]ケチ。[wait][clear]
***************************************/
    wait(ref_8f2);
    dialogFree(ref_8f1);
    shopCurrencyDisplay(-110, 150, true);
    controlEnable();
    b(label_8f8);
  label_8f8:
    b(label_9c9);
  label_8f9:
    ref_8f9 = cameraRotateTo(2, 30);
    wait(ref_8f9);
    playerConvertToUnit(maya, sprite_0, east);
    playerHide();
    unitFace(maya, west);
    ref_8fe = dialogAlloc();
    ref_8ff = msgShow(msg_145);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]つ、ついにこの時を迎えてしまったニャ…[delay(15)]
[tab]記念すべき、１００回目…[delay(15)]
[tab]１０００００円も溜まってしまったニャ～[wait][clear]
***************************************/
    sndMusicPlay(sound_30d7, 127);
    unitAnimationHold(maya, animation_22, -1);
    wait(ref_8ff);
    ref_903 = msgShow(msg_146);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]こんなに只で貰ってしまっては
[tab]さすがに悪い気がするニャ～[delay(30)]
[tab]だから特別に…[delay(15)]こっちに来いニャー！
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d8, 127);
    wait(ref_903);
    dialogFree(ref_8fe);
    bitGet(var_0, MBIT_NEKO_SAGASI);
    bne(var_0, 0, label_90a);
    b(label_91e);
  label_90a:
    bne(var_0, 1, label_91e);
    bitGet(var_0, MBIT_SH_S_15);
    bne(var_0, 0, label_90f);
    bitSet(MBIT_SH_H_15);
    b(label_91d);
  label_90f:
    bne(var_0, 1, label_91d);
    bitGet(var_0, MBIT_SH_H_15);
    bne(var_0, 0, label_91a);
    bitGet(var_0, MBIT_NEKOMATA_GET);
    bne(var_0, 0, label_917);
    bitSet(MBIT_NEKOMATA_GET);
    bitSet(MBIT_SH_HH);
    b(label_919);
  label_917:
    bne(var_0, 1, label_919);
    b(label_919);
  label_919:
    b(label_91c);
  label_91a:
    bne(var_0, 1, label_91c);
    b(label_91c);
  label_91c:
    b(label_91d);
  label_91d:
    b(label_91e);
  label_91e:
    unitAnimationPlay(maya, animation_0, 1);
    unitWait(maya);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_12, 1);
    unitWait(maya);
    unitWait(maya);
    delayClear();
    delayWait(15);
    unitMove(maya, 640, -1160, face_south, fast);
    ref_928 = cameraRotateTo(3, 60);
    cameraFollow(maya);
    wait(ref_928);
    unitWait(maya);
    unitAnimationPlay(maya, animation_28, 2);
    wait(ref_928);
    delayClear();
    delayWait(30);
    ref_930 = dialogAlloc();
    ref_931 = msgShow(msg_147);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]こっち、こっちニャー♥
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d8, 127);
    wait(ref_931);
    dialogFree(ref_930);
    unitAnimationPlay(maya, animation_0, 1);
    unitWait(maya);
    delayClear();
    delayWait(15);
    ref_939 = cameraRotateTo(1, 60);
    unitMove(maya, 640, -630, face_south, fast);
    cameraFollow(maya);
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_93f);
    unitMove(katsuya, 515, -740, face_south, medium);
  label_93f:
    wait(ref_939);
    unitWait(maya);
    unitMove(maya, 760, -380, face_south, fast);
    cameraFollow(maya);
    wait(ref_939);
    unitWait(maya);
    unitAnimationPlay(maya, animation_28, 2);
    delayClear();
    delayWait(30);
    ref_948 = dialogAlloc();
    ref_949 = msgShow(msg_148);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]もう～わかんないかニャ～
[tab]こっち、こっちニャ！！
[wait][clear]
***************************************/
    sndMusicPlay(sound_30d8, 127);
    wait(ref_949);
    dialogFree(ref_948);
    unitAnimationPlay(maya, animation_0, 1);
    unitWait(maya);
    delayClear();
    delayWait(15);
    ref_951 = cameraRotateTo(7, 60);
    unitMove(maya, 760, -150, face_east, fast);
    cameraFollow(maya);
    wait(ref_951);
    ref_955 = cameraRotateTo(5, 60);
    unitWait(maya);
    wait(ref_955);
    unitMove(maya, 455, -150, face_east, fast);
    cameraFollow(maya);
    wait(ref_955);
    unitWait(maya);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_30db, 127);
    sndVolumeFadeOff(sound_3005, 120);
    objAnimRotate(obj_6, 0, 110, 0, 30, 0);
    objAnimWait(obj_6);
    objVisible(obj_1b, false);
    unitMove(maya, 300, -150, face_east, fast);
    cameraFollow(maya);
    delayClear();
    delayWait(30);
    ref_967 = cameraRotateTo(3, 90);
    sndMusicPlay(sound_30de, 127);
    wait(ref_967);
    unitSpawn(unit_58, sprite_a9, 760, 0, -470, north, none);
    unitMove(unit_58, 760, -150, face_east, fast);
    unitWait(unit_58);
    unitWait(maya);
    unitMove(unit_58, 370, -150, face_east, fast);
    delayClear();
    delayWait(15);
    ref_971 = dialogAlloc();
    ref_972 = msgShow(msg_149);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]はじめまして…[delay(30)]ニャニャ！！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_8, 1);
    delayClear();
    delayWait(30);
    unitFace(maya, west);
    wait(ref_972);
    unitAnimationPlay(npc1, animation_1c, 1);
    dialogFree(ref_971);
    unitWait(unit_58);
    unitMove(unit_58, 330, -150, face_east, fast);
    unitMove(maya, 300, -250, face_south, fast);
    unitWait(unit_58);
    unitWait(maya);
    delayClear();
    delayWait(10);
    unitFaceUnit(unit_58, npc1);
    ref_982 = bustupLoad(bustup_e6);
    bustupWait(ref_982);
    ref_984 = bustupAlloc(ref_982, right, rgb(0,0,0));
    bustupFade(ref_984, rgb(128,0,0), 30);
    ref_986 = dialogAlloc();
    ref_987 = msgShow(msg_150);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]こらっ、あんた何してんの！！
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_26, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_1d, 1);
    wait(ref_987);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_986);
    ref_98f = bustupFade(ref_984, rgb(0,0,0), 10);
    bustupWait(ref_98f);
    bustupFree(ref_984);
    delayClear();
    delayWait(10);
    ref_994 = dialogAlloc();
    ref_995 = msgShow(msg_151);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]た、[delay(30)]たまきちゃん！！
[tab]ご…ごめんニャ～
[tab]あんまり退屈ニャもんで…つい…
[wait][clear]
***************************************/
    wait(ref_995);
    dialogFree(ref_994);
    delayClear();
    delayWait(10);
    ref_99a = bustupLoad(bustup_e6);
    bustupWait(ref_99a);
    ref_99c = bustupAlloc(ref_99a, right, rgb(0,0,0));
    bustupFade(ref_99c, rgb(128,0,0), 30);
    unitFace(unit_58, north);
    ref_99f = dialogAlloc();
    ref_9a0 = msgShow(msg_152);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]ごめんなさいね～舞耶さん。
[tab]コイツ、いたずら好きで困ってるんです。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_0, 1);
    wait(ref_9a0);
    unitFace(unit_58, east);
    ref_9a7 = msgShow(msg_153);
/***************************************
[color(yellow)]たまきちゃん[color(white)]
[tab]もうっ！！
[tab]舞耶さんにもちゃんとあやまんなさいよ！
[tab]…まったくぅ。
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_26, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc1, animation_1d, 1);
    wait(ref_9a7);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_99f);
    ref_9af = bustupFade(ref_99c, rgb(0,0,0), 10);
    bustupWait(ref_9af);
    bustupFree(ref_99c);
    unitAnimationPlay(unit_58, animation_a, 1);
    unitWait(unit_58);
    unitFace(unit_58, west);
    unitMove(unit_58, 760, -150, face_north, fast);
    delayClear();
    delayWait(30);
    unitMove(maya, 300, -150, face_east, fast);
    unitWait(maya);
    unitAnimationPlay(npc1, animation_0, 1);
    unitWait(unit_58);
    unitMove(unit_58, 760, -470, face_north, fast);
    ref_9bd = dialogAlloc();
    ref_9be = msgShow(msg_154);
/***************************************
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ご、ごめんニャニャイ…
[tab]おわびに、とっておきの噂を教えるニャ！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_1a, 1);
    wait(ref_9be);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_9bd);
    unitWait(unit_58);
    unitSpawn(unit_58, sprite_a9, 510, 0, -1220, south, none);
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_9c8);
    unitSpawn(katsuya, sprite_d, 650, 30, -740, north, none);
  label_9c8:
    call(MAN1);
  label_9c9:
}

function OKUNOHEYA()
{
    bitGet(var_0, MBIT_KUZU_HATUNEKO);
    bne(var_0, 0, label_9d4);
    controlDisable();
    ref_9cd = dialogAlloc();
    ref_9ce = msgShow(msg_155);
/***************************************
[color(yellow)]招きネコ[color(white)]
[tab]そこはきっと開かないニャー
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_9ce);
    dialogFree(ref_9cd);
    controlEnable();
    b(label_9d7);
  label_9d4:
    bne(var_0, 1, label_9d7);
    call(MAN1);
    b(label_9d7);
  label_9d7:
}

function MESTEST1()
{
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bnz(var_0, label_9e0);
    bitSet(MBIT_HI_NANJOTOUJO);
    ref_9db = dialogAlloc();
    ref_9dc = msgShow(msg_156);
/***************************************
ＭＢＩＴ[tab]ＨＩ[tab]ＮＡＮＪＯＴＯＵＪＯ
南条出現噂：広げた
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9dc);
    dialogFree(ref_9db);
    b(label_a18);
  label_9e0:
    bitGet(var_0, MBIT_KUZU_KENSHOU);
    bnz(var_0, label_9e8);
    bitSet(MBIT_KUZU_KENSHOU);
    ref_9e3 = dialogAlloc();
    ref_9e4 = msgShow(msg_157);
/***************************************
懸賞の噂依頼
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_9e4);
    dialogFree(ref_9e3);
    b(label_a18);
  label_9e8:
    bitGet(var_0, LBIT_0010);
    bnz(var_0, label_9f4);
    bitSet(LBIT_0010);
    bitSet(MBIT_DMAGICK);
    li(var_b, 99);
    li(var_c, 0);
    li(var_d, 99);
    ref_9ef = dialogAlloc();
    ref_9f0 = msgShow(msg_158);
/***************************************
懸賞本[tab]９９・０・９９
[wait][clear]
***************************************/
    wait(ref_9f0);
    dialogFree(ref_9ef);
    b(label_a18);
  label_9f4:
    bitGet(var_0, LBIT_0011);
    bnz(var_0, label_a00);
    bitSet(LBIT_0011);
    bitSet(MBIT_DPELPEL);
    li(var_b, 1);
    li(var_c, 50);
    li(var_d, 0);
    ref_9fb = dialogAlloc();
    ref_9fc = msgShow(msg_159);
/***************************************
懸賞本[tab]１・５０・０
ミラクル応募可
[wait][clear]
***************************************/
    wait(ref_9fc);
    dialogFree(ref_9fb);
    b(label_a18);
  label_a00:
    bitGet(var_0, LBIT_0012);
    bnz(var_0, label_a0b);
    bitSet(LBIT_0012);
    countGet(var_0, nekomata);
    add(var_0, var_0, 49);
    countSet(nekomata, var_0);
    ref_a06 = dialogAlloc();
    ref_a07 = msgShow(msg_160);
/***************************************
ネコカウント４９増加
[wait][clear]
***************************************/
    wait(ref_a07);
    dialogFree(ref_a06);
    b(label_a18);
  label_a0b:
    bitClear(LBIT_0010);
    bitClear(LBIT_0011);
    bitClear(LBIT_0012);
    bitGet(var_0, LBIT_0013);
    bnz(var_0, label_a18);
    bitSet(LBIT_0013);
    countGet(var_0, nekomata);
    add(var_0, var_0, 49);
    countSet(nekomata, var_0);
    ref_a14 = dialogAlloc();
    ref_a15 = msgShow(msg_161);
/***************************************
ネコカウント
さらに４９増加
[wait][clear]
***************************************/
    wait(ref_a15);
    dialogFree(ref_a14);
  label_a18:
}

function MESTEST()
{
    bitGet(var_0, MBIT_AIS_19);
    bnz(var_0, label_a21);
    bitSet(MBIT_AIS_19);
    ref_a1c = dialogAlloc();
    ref_a1d = msgShow(msg_162);
/***************************************
ＭＢＩＴ[tab]ＡＩＳ[tab]１９
相性占いの
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a1d);
    dialogFree(ref_a1c);
    b(label_a70);
  label_a21:
    bitGet(var_0, MBIT_AIS_25);
    bnz(var_0, label_a29);
    bitSet(MBIT_AIS_25);
    ref_a24 = dialogAlloc();
    ref_a25 = msgShow(msg_163);
/***************************************
ＭＢＩＴ[tab]ＡＩＳ[tab]２５
相性占いの
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a25);
    dialogFree(ref_a24);
    b(label_a70);
  label_a29:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_a31);
    bitSet(EBIT_E006F);
    ref_a2c = dialogAlloc();
    ref_a2d = msgShow(msg_164);
/***************************************
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a2d);
    dialogFree(ref_a2c);
    b(label_a70);
  label_a31:
    bitGet(var_0, EBIT_E0077);
    bnz(var_0, label_a39);
    bitSet(EBIT_E0077);
    ref_a34 = dialogAlloc();
    ref_a35 = msgShow(msg_165);
/***************************************
ＥＢＩＴ[tab]Ｅ００７７
「スマイル平坂クリア・克哉離脱」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a35);
    dialogFree(ref_a34);
    b(label_a70);
  label_a39:
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_a41);
    bitSet(EBIT_E007A);
    ref_a3c = dialogAlloc();
    ref_a3d = msgShow(msg_166);
/***************************************
ＥＢＩＴ[tab]Ｅ００７Ａ
「野音クリア・克哉編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a3d);
    dialogFree(ref_a3c);
    b(label_a70);
  label_a41:
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_a49);
    bitSet(EBIT_E007B);
    ref_a44 = dialogAlloc();
    ref_a45 = msgShow(msg_167);
/***************************************
ＥＢＩＴ[tab]Ｅ００７Ｂ
「竜蔵と殺し屋の電話を盗聴」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a45);
    dialogFree(ref_a44);
    b(label_a70);
  label_a49:
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_a51);
    bitSet(EBIT_E007F);
    ref_a4c = dialogAlloc();
    ref_a4d = msgShow(msg_168);
/***************************************
ＥＢＩＴ[tab]Ｅ００７Ｆ
「廃工場クリア・パオフゥ編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a4d);
    dialogFree(ref_a4c);
    b(label_a70);
  label_a51:
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_a59);
    bitSet(EBIT_E008C);
    ref_a54 = dialogAlloc();
    ref_a55 = msgShow(msg_169);
/***************************************
ＥＢＩＴ[tab]Ｅ００８Ｃ
「海底遺跡クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a55);
    dialogFree(ref_a54);
    b(label_a70);
  label_a59:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_a61);
    bitSet(EBIT_E009F);
    ref_a5c = dialogAlloc();
    ref_a5d = msgShow(msg_170);
/***************************************
ＥＢＩＴ[tab]Ｅ００９Ｆ
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a5d);
    dialogFree(ref_a5c);
    b(label_a70);
  label_a61:
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_a69);
    bitSet(EBIT_E00AF);
    ref_a64 = dialogAlloc();
    ref_a65 = msgShow(msg_171);
/***************************************
ＥＢＩＴ[tab]Ｅ００ＡＦ
「アメノトリフネクリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a65);
    dialogFree(ref_a64);
    b(label_a70);
  label_a69:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_a70);
    bitSet(EBIT_E00B8);
    ref_a6c = dialogAlloc();
    ref_a6d = msgShow(msg_172);
/***************************************
ＥＢＩＴ[tab]Ｅ００Ｂ８
「珠「瑠城クリア」
びっとお～んッ！！
[wait][clear]
***************************************/
    wait(ref_a6d);
    dialogFree(ref_a6c);
  label_a70:
}

function DOORBOX()
{
    controlDisable();
    sndMusicPlay(sound_30d9, 127);
    objAnimRotate(obj_5b, 0, 70, 0, 30, 0);
    objAnimRotate(obj_5a, 0, -70, 0, 30, 0);
    objAnimWait(obj_5b);
    objAnimWait(obj_5a);
    call(GOOUT);
}

function GOOUT()
{
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_a7c);
    b(label_a84);
  label_a7c:
    bne(var_0, 1, label_a84);
    bitGet(var_0, MBIT_KE_SKYMAP);
    bne(var_0, 0, label_a80);
    b(label_a83);
  label_a80:
    bne(var_0, 1, label_a83);
    bitSet(TBIT_KARI014);
    b(label_a83);
  label_a83:
    b(label_a84);
  label_a84:
    bitGet(var_0, LBIT_0014);
    bez(var_0, label_a87);
    bitSet(MBIT_KUZU_T_TALK_N);
  label_a87:
    bitGet(var_0, LBIT_0015);
    bez(var_0, label_a8a);
    bitSet(MBIT_KUZU_T_TALK_E);
  label_a8a:
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function warp1()
{
    call(DOORBOX);
}

function HA_SHOP_EXPLAIN_0()
{
    ref_a8f = dialogAlloc();
    ref_a90 = msgShow(msg_173);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]「噂」についての説明だな。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]「噂の依頼」を選択し、どの噂を流すか選べ。
[tab]そうしたら、その噂話を珠聞瑠中に広めてやる。
[tab]仕事として請け負う以上、金銭は要求させてもらうがな。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]噂の元ネタは「噂屋」から聞いて持ってこい。
[tab]やつらは、珠聞瑠のあちこちにいる。
[tab]がんばって探してみるんだな。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]それから、すでに広めた噂については
[tab]「噂の確認」から確認できるぞ。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]俺に依頼した噂以外にも、悪魔共の中で
[tab]流行ってる噂も確認できる。
[tab]…まあ、こんなところだな。
[wait][clear]
***************************************/
    wait(ref_a90);
    dialogFree(ref_a8f);
}

function HONDANA()
{
    bitGet(var_0, EBIT_E0038);
    bne(var_0, 0, label_a9d);
    controlDisable();
    ref_a97 = dialogAlloc();
    ref_a98 = msgShow(msg_174);
/***************************************
[color(yellow)]本棚[color(white)]
[tab][color(green)]スライド式の本棚。
[tab]動きそうだが…[color(white)]
[wait][clear]
***************************************/
    wait(ref_a98);
    dialogFree(ref_a97);
    controlEnable();
    b(label_abb);
  label_a9d:
    bne(var_0, 1, label_abb);
    bitGet(var_0, MBIT_KUZUNOHA_MAG);
    bne(var_0, 0, label_ab2);
    bitGet(var_0, LBIT_0010);
    bne(var_0, 0, label_aa9);
    controlDisable();
    sndMusicPlay(sound_30dd, 127);
    objAnimTranslate(obj_11, 0, 0, 90, 30);
    objAnimWait(obj_11);
    bitSet(LBIT_0010);
    controlEnable();
    b(label_ab1);
  label_aa9:
    bne(var_0, 1, label_ab1);
    controlDisable();
    ref_aab = dialogAlloc();
    ref_aac = msgShow(msg_175);
/***************************************
[color(yellow)]本棚[color(white)]
[tab][color(green)]スライド式の本棚だが、動きそうにない。[color(white)]
[wait][clear]
***************************************/
    wait(ref_aac);
    dialogFree(ref_aab);
    controlEnable();
    b(label_ab1);
  label_ab1:
    b(label_aba);
  label_ab2:
    bne(var_0, 1, label_aba);
    controlDisable();
    ref_ab4 = dialogAlloc();
    ref_ab5 = msgShow(msg_176);
/***************************************
[color(yellow)]本棚[color(white)]
[tab][color(green)]スライド式の本棚だが、動きそうにない。[color(white)]
[wait][clear]
***************************************/
    wait(ref_ab5);
    dialogFree(ref_ab4);
    controlEnable();
    b(label_aba);
  label_aba:
    b(label_abb);
  label_abb:
}

function MAGAZIN()
{
    bitGet(var_0, EBIT_E0038);
    bne(var_0, 0, label_abf);
    b(label_acf);
  label_abf:
    bne(var_0, 1, label_acf);
    bitGet(var_0, MBIT_KUZUNOHA_MAG);
    bne(var_0, 0, label_acc);
    controlDisable();
    msgVarSet(msgvar_1, 87);
    ref_ac4 = dialogAlloc();
    ref_ac5 = msgShow(msg_177);
/***************************************
[color(yellow)]本棚[color(white)]
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear]
***************************************/
    wait(ref_ac5);
    dialogFree(ref_ac4);
    partyItemAdd(sumaru_magazine, 1);
    bitSet(MBIT_KUZUNOHA_MAG);
    controlEnable();
    b(label_ace);
  label_acc:
    bne(var_0, 1, label_ace);
    b(label_ace);
  label_ace:
    b(label_acf);
  label_acf:
}

function UWASABIT()
{
    bitGet(var_0, MBIT_zody_2F);
    bne(var_0, 0, label_ad3);
    b(label_ae0);
  label_ad3:
    bne(var_0, 1, label_ae0);
    bitGet(var_0, MBIT_KI_ZODI2F);
    bne(var_0, 0, label_ad7);
    b(label_adf);
  label_ad7:
    bne(var_0, 1, label_adf);
    bitGet(var_0, MBIT_KE_ZODI2F);
    bne(var_0, 0, label_adc);
    bitClear(MBIT_KI_ZODI2F);
    b(label_ade);
  label_adc:
    bne(var_0, 1, label_ade);
    b(label_ade);
  label_ade:
    b(label_adf);
  label_adf:
    b(label_ae0);
  label_ae0:
    bitGet(var_0, EBIT_E007A);
    bne(var_0, 0, label_ae3);
    b(label_af0);
  label_ae3:
    bne(var_0, 1, label_af0);
    bitGet(var_0, MBIT_KE_HANAKOTOBA);
    bne(var_0, 0, label_aed);
    bitGet(var_0, MBIT_KI_HANAKOTOBA);
    bne(var_0, 0, label_ae9);
    b(label_aec);
  label_ae9:
    bne(var_0, 1, label_aec);
    bitClear(MBIT_KI_HANAKOTOBA);
    b(label_aec);
  label_aec:
    b(label_aef);
  label_aed:
    bne(var_0, 1, label_aef);
    b(label_aef);
  label_aef:
    b(label_af0);
  label_af0:
    bitGet(var_0, EBIT_E0088);
    bne(var_0, 0, label_af3);
    b(label_b04);
  label_af3:
    bne(var_0, 1, label_b04);
    bitGet(var_0, MBIT_KE_DEVIL6);
    bitGet(var_1, MBIT_KE_DEVIL7);
    add(var_0, var_0, var_1);
    bne(var_0, 0, label_b02);
    bitGet(var_0, MBIT_KI_DEVIL6);
    bitGet(var_1, MBIT_KI_DEVIL7);
    add(var_0, var_0, var_1);
    bne(var_0, 0, label_afd);
    b(label_b01);
  label_afd:
    bne(var_0, 1, label_b01);
    bitClear(MBIT_KI_DEVIL6);
    bitClear(MBIT_KI_DEVIL7);
    b(label_b01);
  label_b01:
    b(label_b03);
  label_b02:
    b(label_b03);
  label_b03:
    b(label_b04);
  label_b04:
    bitGet(var_0, EBIT_E006F);
    bne(var_0, 0, label_b07);
    b(label_b14);
  label_b07:
    bne(var_0, 1, label_b14);
    bitGet(var_0, MBIT_KE_DEVIL3);
    bne(var_0, 0, label_b11);
    bitGet(var_0, MBIT_KI_DEVIL3);
    bne(var_0, 0, label_b0d);
    b(label_b10);
  label_b0d:
    bne(var_0, 1, label_b10);
    bitClear(MBIT_KI_DEVIL3);
    b(label_b10);
  label_b10:
    b(label_b13);
  label_b11:
    bne(var_0, 1, label_b13);
    b(label_b13);
  label_b13:
    b(label_b14);
  label_b14:
    bitGet(var_0, EBIT_E004E);
    bne(var_0, 0, label_b17);
    b(label_b24);
  label_b17:
    bne(var_0, 1, label_b24);
    bitGet(var_0, MBIT_KE_DEVIL2);
    bne(var_0, 0, label_b21);
    bitGet(var_0, MBIT_KI_DEVIL2);
    bne(var_0, 0, label_b1d);
    b(label_b20);
  label_b1d:
    bne(var_0, 1, label_b20);
    bitClear(MBIT_KI_DEVIL2);
    b(label_b20);
  label_b20:
    b(label_b23);
  label_b21:
    bne(var_0, 1, label_b23);
    b(label_b23);
  label_b23:
    b(label_b24);
  label_b24:
}

function DECIDE_ROHA()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_b28 = bustupLoad(bustup_e5);
    bustupWait(ref_b28);
    ref_b2a = bustupAlloc(ref_b28, left, rgb(0,0,0));
    bustupFade(ref_b2a, rgb(128,0,0), 30);
    ref_b2c = dialogAlloc();
    ref_b2d = msgShow(msg_178);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]この噂操作には、[var(msg_var_0)]円かかるが、依頼するか？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_b2d);
    choiceGetResult(var_7);
    bne(var_7, 0, label_b33);
    li(var_7, 1);
    b(label_b36);
  label_b33:
    bne(var_7, 1, label_b36);
    li(var_7, 0);
    b(label_b36);
  label_b36:
    wait(ref_b2d);
    dialogFree(ref_b2c);
    ref_b38 = bustupFade(ref_b2a, rgb(0,0,0), 10);
    bustupWait(ref_b38);
    bustupFree(ref_b2a);
}

function DECIDE()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_b3f = bustupLoad(bustup_e5);
    bustupWait(ref_b3f);
    ref_b41 = bustupAlloc(ref_b3f, left, rgb(0,0,0));
    bustupFade(ref_b41, rgb(128,0,0), 30);
    ref_b43 = dialogAlloc();
    ref_b44 = msgShow(msg_179);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]この噂操作には、[var(msg_var_0)]円かかるが、依頼するか？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_b44);
    choiceGetResult(var_7);
    bne(var_7, 0, label_b4a);
    li(var_7, 1);
    b(label_b4d);
  label_b4a:
    bne(var_7, 1, label_b4d);
    li(var_7, 0);
    b(label_b4d);
  label_b4d:
    wait(ref_b44);
    dialogFree(ref_b43);
    ref_b4f = bustupFade(ref_b41, rgb(0,0,0), 10);
    bustupWait(ref_b4f);
    bustupFree(ref_b41);
}

function DECIDE_2()
{
    choiceSetResult(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_b56 = bustupLoad(bustup_e5);
    bustupWait(ref_b56);
    ref_b58 = bustupAlloc(ref_b56, left, rgb(0,0,0));
    bustupFade(ref_b58, rgb(128,0,0), 30);
    ref_b5a = dialogAlloc();
    ref_b5b = msgShow(msg_180);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]この噂はどう広まるか分からんな…。
[tab][var(msg_var_0)]円かかるが、それでもいいか？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_b5b);
    choiceGetResult(var_7);
    bne(var_7, 0, label_b61);
    li(var_7, 1);
    b(label_b64);
  label_b61:
    bne(var_7, 1, label_b64);
    li(var_7, 0);
    b(label_b64);
  label_b64:
    wait(ref_b5b);
    dialogFree(ref_b5a);
    ref_b66 = bustupFade(ref_b58, rgb(0,0,0), 10);
    bustupWait(ref_b66);
    bustupFree(ref_b58);
}

function NOMONEY()
{
    unitFacePlayer(shopkeeper);
    ref_b6b = bustupLoad(bustup_e5);
    bustupWait(ref_b6b);
    ref_b6d = bustupAlloc(ref_b6b, left, rgb(0,0,0));
    bustupFade(ref_b6d, rgb(128,0,0), 30);
    ref_b6f = dialogAlloc();
    ref_b70 = msgShow(msg_181);
/***************************************
[color(yellow)]轟所長[color(white)]
[tab]お前達の所持金では、依頼料を払えないぞ。[wait][clear]
***************************************/
    wait(ref_b70);
    dialogFree(ref_b6f);
    ref_b73 = bustupFade(ref_b6d, rgb(0,0,0), 10);
    bustupWait(ref_b73);
    bustupFree(ref_b6d);
}
