
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ＪＯＫＥＲって、あんなヤツだったんだ。
[tab]殺人鬼って実在するんだねぇ。この目で見て納得！
[tab]…ＪＯＫＥＲ呪いって、ヤバイのかな？
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]ここの所長って、何か不思議な感じしない？
[tab]外見からは想像出来ない切れ者ぶりっていうか、
[tab]見かけと中身が一致してないような？
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]ねぇマーヤ、早くノリコちゃんを助けに行こう。
[tab]早くしなきゃ…早くしなきゃダメだよ！
[tab]あんな若いコをＪＯＫＥＲなんかにしちゃダメ！
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]ゾディアックでのパオフゥ、怖かったよね。
[tab]人には言えない過去があるみたいだけど、
[tab]それが原因なのかなぁ？
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]大臣が率いる悪の組織…そう言えば昔のマンガに、
[tab]悪の組織の正体が、その国の政府だった！
[tab]…ってのがあったねぇ。
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]ねぇ、私の作戦で上手くいったでしょう？
[tab]何、マーヤ？[tab]…それって尊敬の眼差し？
[tab]やだぁ、なに見てんのよ！？
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]天野君…
[tab]店への噂操作は、業務妨害にあたるんじゃないか？
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]とは言ってみたものの、
[tab]裁判の判例にもこんな例はないだろうし…
[tab]何か法と自分の限界を感じるよ…
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]…かわいいなぁ～あの大きな招き猫。
[tab]え！？[tab]僕の外見と中身が一致しない？
[tab]僕が猫好きだと…変なのか？
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]ＪＯＫＥＲ呪いによるＪＯＫＥＲ化…
[tab]須藤が死に際に言い残したのは、
[tab]この事だったのか。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]結婚詐欺の余罪追求？
[tab]罪を見逃す気は無いが、今は人命優先！
[tab]当然、そんな事は後回しだ！
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]天野君、芹沢君の言う通りだ。
[tab]彼女にこれ以上罪を重ねさせてはいけない！
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]なぁパオフゥ…
[tab]いい加減、隠し事はやめにしないか？
[tab]自分に出来る事であれば、協力は惜しまないぞ。
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]確かに外務大臣である須藤の影響力は大きい。
[tab]しかし、それに屈しない奴もいるって事を
[tab]思い知らせてやる！
[wait][clear][end]

msg_15:
[color(yellow)]克哉[color(white)]
[tab]無事、南条君や桐島君と接触が取れたな。
[tab]噂を利用するなんて、僕には考えもつかなかった。
[tab]芹沢君の発想力には驚かされるよ。
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]ネット上にも似たようなヤツがいるな。
[tab]掲示板やメールでは雄弁なクセに、現実社会では
[tab]何も言えないヤツ。…あれ、ちょっと違うか？
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]いいか天野！[tab]もう誰もあてには出来ねぇぞ！
[tab]この社会も、信頼している仲間も、先ず疑え！
[tab]頼れるのは自分だけだ…いいな！？
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]「ＪＯＫＥＲは死なない」ねぇ…
[tab]確かにあの野郎が死んでも、事件は終らねぇな。
[tab]フン、よく言ったもんだぜ。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]へへへ、あのサギ野郎開き直りやがった。
[tab]どうすんだ[suou]？
[tab]徹底的に絞りあげるか？
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]例え未成年の少女であろうと…
[tab]例えＪＯＫＥＲ呪いによる間接的殺人であっても、
[tab]罪は償わなきゃいけねぇ。
[wait][clear][end]

msg_21:
[color(yellow)]パオフゥ[color(white)]
[tab]…何も話す事は無いぜ。
[tab]それに、俺にかまってるヒマなんかねぇだろ？
[wait][clear][end]

msg_22:
[color(yellow)]パオフゥ[color(white)]
[tab]しかし黒い噂の絶えない男だよな、
[tab]須藤[tab]竜蔵ってヤツは。
[tab]…昔っからな。
[wait][clear][end]

msg_23:
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢の作戦、確かにスゲー発想だよな。
[tab]普通の頭じゃ思い付かねぇよ。
[tab]…しかし、本当に上手く行ってんのか？
[wait][clear][end]

msg_24:
[color(yellow)]南条[color(white)]
[tab]ほう、懐かしい顔だな。
[tab]君は確か大学へ進んだ筈では…
[tab]…バイト？[tab]こんな所でか？
[wait][clear][end]

msg_25:
[color(yellow)]南条[color(white)]
[tab]噂を操作して俺達を捜し出すとは…
[tab]良く思いついたと言うか、何と言うか…
[tab]溺れる者はわらをも掴むと言うやつか？
[wait][clear][end]

msg_26:
[color(yellow)]エリー[color(white)]
[tab]Ｏｈ！[tab]久しぶりですわ、Ｍｓ．Ｔａｍａｋｉ！
[tab]お元気でした？
[wait][clear][end]

msg_27:
[color(yellow)]エリー[color(white)]
[tab]新世塾が言霊を操っているのなら、
[tab]私達が皆さんとＣｏｎｔａｃｔを取る事も
[tab]阻止出来た筈なのに…Ｗｈｙ？
[wait][clear][end]

msg_28:
[color(yellow)]たまきちゃん[color(white)]
[tab]おつかれー！
[tab]さて、ご用件はなにかしら？
[wait][clear][end]

msg_29:
[tab]あ、こんにちは～！
[tab]あっれぇ～？[tab]天野さん最近なんかありました？
[tab]…だって、すっごくキレイになったもん！
[wait][clear][end]

msg_30:
[color(yellow)]たまきちゃん[color(white)]
[tab]はっは～ん？[tab]さては…
[tab]な～んてね！！[tab]エヘヘ。
[wait][clear][end]

msg_31:
[color(yellow)]たまきちゃん[color(white)]
[tab]これで、懸賞に関する噂も現実になるはず。
[tab]それでは、応募は私が引き受けますね。
[tab]天野さん達、忙しいでしょ？
[wait][clear][end]

msg_32:
[color(yellow)]たまきちゃん[color(white)]
[tab]さて、どうします？
[choice(4)]話をする
応募したい
懸賞とは？
用はない
[end_choice][clear][end]

msg_33:
[color(yellow)]たまきちゃん[color(white)]
[tab]ＯＫ、応募ですね。
[tab]え～と、月刊バトルマスターは…[delay(30)]
[tab]ブッブーッ！！[tab]ダメで～す。
[wait][clear][end]

msg_34:
[color(yellow)]たまきちゃん[color(white)]
[tab]この前応募した分、確認してませんね？
[tab]受け取りはキスメット出版の編集部ですから、
[tab]当たってるか確認してから来てくださいね。
[wait][clear][end]

msg_35:
[color(yellow)]たまきちゃん[color(white)]
[end]

msg_36:
[tab]ＯＫ、応募ですね。
[end]

msg_37:
[tab]お、続けて応募ですね。
[end]

msg_38:
[tab]え～と、別冊ミラクルは…[delay(30)]
[tab]ブッブーッ！！[tab]ダメで～す。
[wait][clear][end]

msg_39:
[color(yellow)]たまきちゃん[color(white)]
[tab]この前応募した分、確認してませんね？
[tab]受け取りはキスメット出版の編集部ですから、
[tab]当たってるか確認してから来てくださいね。
[wait][clear][end]

msg_40:
[color(yellow)]たまきちゃん[color(white)]
[end]

msg_41:
[tab]ＯＫ、応募ですね。
[end]

msg_42:
[tab]お、続けて応募ですね。
[end]

msg_43:
[tab]え～と、ファンタジーワールドは…[delay(30)]
[tab]ブッブーッ！！[tab]ダメで～す。
[wait][clear][end]

msg_44:
[color(yellow)]たまきちゃん[color(white)]
[tab]この前応募した分、確認してませんね？
[tab]受け取りはキスメット出版の編集部ですから、
[tab]当たってるか確認してから来てくださいね。
[wait][clear][end]

msg_45:
[color(yellow)]たまきちゃん[color(white)]
[tab]ＯＫ、応募ですね。
[tab]え～と、月刊バトルマスターは…[delay(30)]
[tab][var(msg_var_1)]冊分ですね。
[wait][clear][end]

msg_46:
[color(yellow)]たまきちゃん[color(white)]
[tab]受け取りは…
[tab]キスメット出版の編集部…っと。
[wait][clear][end]

msg_47:
[color(yellow)]たまきちゃん[color(white)]
[end]

msg_48:
[tab]ＯＫ、応募ですね。
[end]

msg_49:
[tab]お、続けて応募ですね。
[end]

msg_50:
[tab]え～と、別冊ミラクルは…[delay(30)]
[tab][var(msg_var_2)]冊分ですね。
[wait][clear][end]

msg_51:
[color(yellow)]たまきちゃん[color(white)]
[tab]受け取りは…
[tab]キスメット出版の編集部…っと。
[wait][clear][end]

msg_52:
[color(yellow)]たまきちゃん[color(white)]
[end]

msg_53:
[tab]ＯＫ、応募ですね。
[end]

msg_54:
[tab]お、続けて応募ですね。
[end]

msg_55:
[tab]え～と、ファンタジーワールドは…[delay(30)]
[tab][var(msg_var_3)]冊分ですね。
[wait][clear][end]

msg_56:
[color(yellow)]たまきちゃん[color(white)]
[tab]受け取りは…
[tab]キスメット出版の編集部…っと。
[wait][clear][end]

msg_57:
[color(yellow)]たまきちゃん[color(white)]
[tab]本当にいいんですか～？
[choice(2)]ＯＫ
やっぱりやめる
[end_choice][clear][end]

msg_58:
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]ちゃーんと応募しときますよ。
[tab]なんか当たるといいですね！
[wait][clear][end]

msg_59:
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！[tab]ちゃーんと応募しますね。
[tab]え～と、あとは…
[wait][clear][end]

msg_60:
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！[tab]ちゃーんと応募しますね。
[tab]え～と、あとは…
[wait][clear][end]

msg_61:
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]応募したくなったらまた来てくださいね。
[wait][clear][end]

msg_62:
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]応募したくなったら言ってくださいね。
[tab]え～と、あとは…
[wait][clear][end]

msg_63:
[color(yellow)]たまきちゃん[color(white)]
[tab]ラジャー！
[tab]応募したくなったら言ってくださいね。
[tab]え～と、あとは…
[wait][clear][end]

msg_64:
[color(yellow)]たまきちゃん[color(white)]
[tab]ＯＫ！[delay(30)]
[tab]…って天野さ～ん、１冊も持ってないですよ～
[tab]サトミタダシで買ってから来てくださいね。
[wait][clear][end]

msg_65:
[color(yellow)]たまきちゃん[color(white)]
[tab]…これで終わりみたいですよ。
[tab]なんか当たるといいですね！
[wait][clear][end]

msg_66:
[color(yellow)]たまきちゃん[color(white)]
[tab]懸賞は抽選で何々を差し上げますってヤツ。
[tab]本を買って応募すれば、ある程度の確率で
[tab]アイテムが貰えるの。当たればラッキー！
[wait][clear][end]

msg_67:
[color(yellow)]たまきちゃん[color(white)]
[tab]手順は、懸賞のついた雑誌をサトミタダシで購入。
[tab]私に雑誌を渡す。私がかわって応募。
[tab]キスメット出版編集部で受け取る…ってカンジ。
[wait][clear][end]

msg_68:
[color(yellow)]たまきちゃん[color(white)]
[tab]ここでルール！！[tab]まず応募は一回ずつ。
[tab]先の当選結果が出るまで次の応募はできないの。
[tab]…なぜって？[tab]そういうモノなの！
[wait][clear][end]

msg_69:
[color(yellow)]たまきちゃん[color(white)]
[tab]それから、一度に応募できるのは、９９冊分まで。
[tab]やっぱ、たくさん送った方が当たりやすいわ。
[tab]私的には毎回９９冊分での挑戦がオススメ！
[wait][clear][end]

msg_70:
[color(yellow)]たまきちゃん[color(white)]
[tab]最後に、結果が出るまでにはある程度時間が必要。
[tab]ジッとしててもダメダメ。
[tab]ひたすらダンジョンを歩く歩く。
[wait][clear][end]

msg_71:
[color(yellow)]たまきちゃん[color(white)]
[tab]後は根気と運しだい！
[tab]夢を捨てない天野さんなら、
[tab]レアなアイテムが取れるかも…
[wait][clear][end]

msg_72:
[color(yellow)]たまきちゃん[color(white)]
[tab]あっれぇ～？[tab]天野さん最近なんかありました？
[tab]…だって、すっごくキレイになったもん！
[wait][clear][end]

msg_73:
[color(yellow)]たまきちゃん[color(white)]
[tab]はっは～ん？[tab]さては…
[tab]な～んてね！！[tab]エヘヘ。
[wait][clear][end]

msg_74:
[color(yellow)]たまきちゃん[color(white)]
[tab]まさか噂が現実化するなんてね。
[tab]でも今の時代、何が起きても不思議じゃない！！
[tab]その変化についていけるのも若さゆえ…ですね。
[wait][clear][end]

msg_75:
[color(yellow)]たまきちゃん[color(white)]
[tab]アイツ、殺し屋に追われてるって言ってたけど、
[tab]まさかＪＯＫＥＲに追われていたのかしら？
[tab]…アイツを呪うような暇なヤツ、いるのかな？
[wait][clear][end]

msg_76:
[color(yellow)]たまきちゃん[color(white)]
[tab]あ、気にしないで下さい。
[tab]ただの独り言ですから…
[wait][clear][end]

msg_77:
[color(yellow)]たまきちゃん[color(white)]
[tab]わたし達の方でもいろいろ調べてるんだけど、
[tab]なーんにも分かってないの。
[tab]行方不明者の増加は関係あるかしら？
[wait][clear][end]

msg_78:
[color(yellow)]たまきちゃん[color(white)]
[tab]新世塾かぁ。ゼンゼン聞いたことないけど、
[tab]財界の大物とかが参加してるんでしょ？
[tab]じゃあ、すぐに尻尾は掴めそうね。
[wait][clear][end]

msg_79:
[color(yellow)]たまきちゃん[color(white)]
[tab]あれっ、南条君じゃない？
[tab]どうして天野さん達と一緒なの？
[tab]…え、エリーも？[tab]ふ～ん、そうなんだ。
[wait][clear][end]

msg_80:
[color(yellow)]たまきちゃん[color(white)]
[tab]南条君とエリーはね、
[tab]わたしと同じエルミン学園の卒業生なの。
[tab]みんな元気でなによりね。
[wait][clear][end]

msg_81:
[color(yellow)]たまきちゃん[color(white)]
[tab]あれっ、エリーじゃない？
[tab]どうして天野さん達と一緒なの？
[tab]…え、南条君も？[tab]ふ～ん、そうなんだ。
[wait][clear][end]

msg_82:
[color(yellow)]たまきちゃん[color(white)]
[tab]エリーと南条君はね、
[tab]わたしと同じエルミン学園卒業生なの。
[tab]みんな元気でなによりね。
[wait][clear][end]

msg_83:
[color(yellow)]たまきちゃん[color(white)]
[tab]何かあったら言ってくださいね。
[tab]わたしにできる事なら、お手伝いしますから。
[tab][delay(30)]…できる事だけですよ？
[wait][clear][end]

msg_84:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]あらためて…はじめましてニャー
[tab]アタシは噂好きのネコマタなのニャ♥
[tab]ヒトの知らない噂を集めてるのニャー
[wait][clear][end]

msg_85:
[color(yellow)]ネコマタ[color(green)]
[tab]デビルサマナーであるたまきちゃんの仲魔。
[tab]いたずら好きでお金に目が無い困り者。
[tab]悪魔のあいだに広まる特殊な噂に詳しい。[color(white)]
[wait][clear][end]

msg_86:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ところで…
[tab]今日はどんニャ用なのかニャー？
[wait][clear][end]

msg_87:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ニャニャ♥[tab]また来たニャ！？
[tab]アタシの話を聞きたいのかニャ～？
[tab]でも、[delay(30)]ドアを開ける時はノックを忘れるニャ！
[wait][clear][end]

msg_88:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ところで…
[tab]今日はどんニャ用なのかニャー？
[wait][clear][end]

msg_89:
[tab]今日はどんニャ用なのかニャー？
[choice(3)]噂話を聞きたい
話を聞きたい
用はない
[end_choice][clear][end]

msg_90:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]話せる噂はもうないニャ～
[tab]…ごめんニャ。
[wait][clear][end]

msg_91:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]噂を聞きたいのかニャ？
[tab]そうだニャ～
[tab]そっちも何か噂を教えてくれニャ！
[wait][clear][end]

msg_92:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ニャンと、噂を教えろと言うのか！
[tab]じゃあ、かわりの噂を教えてくれニャ！
[tab]アタシと情報交換ニャ～！
[wait][clear][end]

msg_93:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]アタシの情報は特別ニャー♥
[tab]それに見合った噂はお持ちかニャ？
[wait][clear][end]

msg_94:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]そ、それはホントかニャー！？
[tab]スゴイことを知ってしまったニャ！
[tab]…約束通り、アタシも教えるニャ。
[wait][clear][end]

msg_95:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]へー、あのヒトにそんな噂まであるんニャ。
[tab]ふーん、人間って面白いニャー
[tab]じゃ、次はアタシの番ニャ♥
[wait][clear][end]

msg_96:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]それって良く聞く噂ニャ～
[tab]ま、今日はそれで勘弁してやるかニャ？
[wait][clear][end]

msg_97:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab][color(orange)]トリッシュ[color(white)]って悪魔は知ってるニャ？
[tab]嘘かホントか、[color(orange)]改心した[color(white)]って評判ニャ！
[tab]アタシにはどうしても信じられないニャー
[wait][clear][end]

msg_98:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab][color(orange)]かおり[color(white)]ってお店、知ってるかニャー？
[tab]じゃ、そこで[color(orange)]アロマテラピーを始めた[color(white)]の知ってる？
[tab]アレはキクのニャ。悪魔もびっくりニャー！
[wait][clear][end]

msg_99:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]あやしいエステの店…ニャんだっけ？[tab]そうそう！
[tab]あの[color(orange)]エテーリア[color(white)]のエステに、[color(orange)]新たなエステコース[color(white)]が
[tab]追加されたらしいニャ。悪魔もうっとりニャー
[wait][clear][end]

msg_100:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab][color(orange)]トリッシュ[color(white)]って悪魔に会った事あるかニャ？
[tab]噂によると、ダンジョンの中で[color(orange)]アイスを売り始めた[color(white)]
[tab]らしいのニャ。きっと金儲けの為ニャー
[wait][clear][end]

msg_101:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]知ってるかニャー？
[tab]たまちゃんはね、実はデビルサマナーなのニャー♥
[tab]アタシはね、たまちゃんの仲魔ニャー
[wait][clear][end]

msg_102:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ＪＯＫＥＲはね、悪魔を酷使するのニャー
[tab]だから嫌なの。ホンキでムカツクのニャー！！
[tab]増えたら困るのニャ～
[wait][clear][end]

msg_103:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]あぁ！！[tab]アナタ、気付いてるかニャ！？
[tab]アナタの新しい仲間、ペルソナ使いなのニャー！！
[tab]…え、知ってたの？[tab]ニャーんだ、がっかり。
[wait][clear][end]

msg_104:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]最近、悪魔はないがしろにされてるニャー
[tab]ねぇ、アタシたち悪魔の事、どーおもってるの？
[tab]…昔は「仲魔」って呼んでニャかった？
[wait][clear][end]

msg_105:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]それじゃまたニャー♥
[wait][clear][end]

msg_106:
[color(yellow)]牧村[color(white)]
[tab]探偵事務所？
[tab]なんだよ、いまさら俺の女性遍歴でも調べる気か？
[tab]余罪でも追及する気かい、刑事さんよぉ？
[wait][clear][end]

msg_107:
[color(yellow)]轟所長[color(white)]
[tab]来たか…

[wait][clear][end]

msg_108:
[color(yellow)]轟所長[color(white)]
[tab]よぉ、来たな。
[tab]…どうした？[tab]何か困り事か？
[tab]よし、今日は特別に力になってやる。
[wait][clear][end]

msg_109:
[color(yellow)]轟所長[color(white)]
[tab]ただし、依頼料金はいつも通りだぞ。
[tab]…な～に、全ては気持ちの問題だ。
[wait][clear][end]

msg_110:
[color(yellow)]轟所長[color(white)]
[tab]今日の用件はなんだ？
[choice(5)]噂の依頼
噂の確認
話を聞く
やめる
探偵事務所から出る
[end_choice][clear][end]

msg_111:
[color(yellow)]轟所長[color(white)]
[tab]何について聞きたいんだ？
[choice(3)]世間話を聞く
噂について説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_112:
[color(yellow)]轟所長[color(white)]
[tab]他に何かあるか？
[choice(5)]噂の依頼
噂の確認
話を聞く
やめる
探偵事務所から出る
[end_choice][clear][end]

msg_113:
[color(yellow)]轟所長[color(white)]
[tab]何について聞きたいんだ？
[choice(3)]世間話を聞く
噂について説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_114:
[color(yellow)]轟所長[color(white)]
[tab]噂とは、そう簡単に広まるものではない。
[tab]それを耳にし、口にする人々の心理が
[tab]大きく関係するからだ。
[wait][clear][end]

msg_115:
[color(yellow)]轟所長[color(white)]
[tab]この街には噂好き…噂屋と呼ばれる連中がいる。
[tab]そいつらの持っている噂なら、人々に広まり易く、
[tab]現実化も楽に出来るかもしれんな。
[wait][clear][end]

msg_116:
[color(yellow)]轟所長[color(white)]
[tab]目の前の出来事に振り回されていては駄目だ。
[tab]この一連の騒動には、必ず裏がある。
[tab]いいか、それだけは忘れるなよ。
[wait][clear][end]

msg_117:
[color(yellow)]轟所長[color(white)]
[tab]ＪＯＫＥＲとなる者が増えているのならば、
[tab]この街はもっと騒がしくなる筈…
[tab]それが感じられないのは、何故だ？
[wait][clear][end]

msg_118:
[color(yellow)]轟所長[color(white)]
[tab]新世塾…それが事件の裏にいる組織…
[tab]なかなか面白そうな話だな。
[tab]少し探りを入れてみるかな？
[wait][clear][end]

msg_119:
[color(yellow)]轟所長[color(white)]
[tab]たまきとお前の連れが知り合いだったとはな…
[tab]世の中は狭いもんだ。もっとも、俺がそうした
[tab]人間に出会うことは無いだろうがな…
[wait][clear][end]

msg_120:
[color(yellow)]轟所長[color(white)]
[tab]俺達が力になれるのは、噂を操作するまでだ。
[tab]後はお前達しだい。
[tab]じゃあ…あばよ。
[wait][clear][end]

msg_121:
[color(yellow)]轟所長[color(white)]
[tab]懸賞か…
[tab]応募は、たまきに頼めばいいだろう。
[tab]彼女に相談してみろ。
[wait][clear][end]

msg_122:
[color(yellow)]招きネコ[color(white)]
[tab]久しぶりニャー♥
[tab]今回は大人だから、千円入れてニャー♥
[wait][clear][end]

msg_123:
[color(yellow)]招きネコ[color(white)]
[tab]大人だから、千円入れてニャー♥
[wait][clear][end]

msg_124:
[tab]ここに千円入れて欲しいニャー♥
[choice(2)]入れる
入れない
[end_choice][clear][end]

msg_125:
[color(yellow)]招きネコ[color(white)]
[tab]あっ、持ってないニャー♥
[tab]うそつきは泥棒の始まりニャー♥
[tab]おととい来るニャー♥[wait][clear][end]

msg_126:
[color(yellow)]招きネコ[color(white)]
[tab]感激ニャ～♥[delay(15)]
[tab]もう２０回も千円入れてもらったニャ～♥[delay(15)]
[tab]今後に期待するニャ～♥[wait][clear][end]

msg_127:
[color(yellow)]招きネコ[color(white)]
[tab]ニャニャニャ～♥[delay(15)]
[tab]なんともう５０回も千円入れてもらったニャ～♥[delay(15)]
[tab]お姉さん、とっても太っ腹ニャ～♥[wait][clear][end]

msg_128:
[color(yellow)]招きネコ[color(white)]
[tab]凄いニャ～！[tab]凄いニャ～！！[delay(15)]
[tab]もう、８０回も千円入れてもらったニャ～♥[delay(15)]
[tab]何か下心があるニャ？[wait][clear][end]

msg_129:
[color(yellow)]招きネコ[color(white)]
[tab]ありがとニャー♥[wait][clear][end]

msg_130:
[color(yellow)]招きネコ[color(white)]
[tab]…[delay(15)]ケチ。[wait][clear][end]

msg_131:
[color(yellow)]招きネコ[color(white)]
[tab]つ、ついにこの時を迎えてしまったニャ…[delay(15)]
[tab]記念すべき、１００回目…[delay(15)]
[tab]１０００００円も溜まってしまったニャ～[wait][clear][end]

msg_132:
[color(yellow)]招きネコ[color(white)]
[tab]こんなに只で貰ってしまっては
[tab]さすがに悪い気がするニャ～[delay(30)]
[tab]だから特別に…[delay(15)]こっちに来いニャー！
[wait][clear][end]

msg_133:
[color(yellow)]招きネコ[color(white)]
[tab]こっち、こっちニャー♥
[wait][clear][end]

msg_134:
[color(yellow)]招きネコ[color(white)]
[tab]もう～わかんないかニャ～
[tab]こっち、こっちニャ！！
[wait][clear][end]

msg_135:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]はじめまして…[delay(30)]ニャニャ！！
[wait][clear][end]

msg_136:
[color(yellow)]たまきちゃん[color(white)]
[tab]こらっ、あんた何してんの！！
[wait][clear][end]

msg_137:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]た、[delay(30)]たまきちゃん！！
[tab]ご…ごめんニャ～
[tab]あんまり退屈ニャもんで…つい…
[wait][clear][end]

msg_138:
[color(yellow)]たまきちゃん[color(white)]
[tab]ごめんなさいね～舞耶さん。
[tab]コイツ、いたずら好きで困ってるんです。
[wait][clear][end]

msg_139:
[color(yellow)]たまきちゃん[color(white)]
[tab]もうっ！！
[tab]舞耶さんにもちゃんとあやまんなさいよ！
[tab]…まったくぅ。
[wait][clear][end]

msg_140:
[color(yellow)]悪魔噂屋ネコマタ[color(white)]
[tab]ご、ごめんニャニャイ…
[tab]おわびに、とっておきの噂を教えるニャ！
[wait][clear][end]

msg_141:
[color(yellow)]招きネコ[color(white)]
[tab]そこはきっと開かないニャー
[sync][wait][clear][end]

msg_142:
懸賞の噂依頼
びっとお～んッ！！
[wait][clear][end]

msg_143:
懸賞本[tab]９９・０・９９
[wait][clear][end]

msg_144:
懸賞本[tab]１・５０・０
ミラクル応募可
[wait][clear][end]

msg_145:
ネコカウント４９増加
[wait][clear][end]

msg_146:
ネコカウント
さらに４９増加
[wait][clear][end]

msg_147:
ＭＢＩＴ[tab]ＡＩＳ[tab]１９
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_148:
ＭＢＩＴ[tab]ＡＩＳ[tab]２５
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_149:
ＥＢＩＴ[tab]Ｅ００１５
七姉妹学園クリア
びっとお～んッ！！
[wait][clear][end]

msg_150:
ＥＢＩＴ[tab]Ｅ００１８
バー終了・パオフゥ初参加
びっとお～んッ！！
[wait][clear][end]

msg_151:
ＥＢＩＴ[tab]Ｅ００３３
「パオフゥ編入」
びっとお～んッ！！
[wait][clear][end]

msg_152:
ＥＢＩＴ[tab]Ｅ００３７
警察署[half_tab]受付、終了
びっとお～んッ！！
[wait][clear][end]

msg_153:
ＥＢＩＴ[tab]Ｅ００３８
「詐欺男を確保」
びっとお～んッ！！
[wait][clear][end]

msg_154:
ＥＢＩＴ[tab]Ｅ００３Ｅ
「ゴールドクリア」「うらら編入」
びっとお～んッ！！
[wait][clear][end]

msg_155:
ＥＢＩＴ[tab]Ｅ００４３
「クラブクリア」
びっとお～んッ！！
[wait][clear][end]

msg_156:
ＥＢＩＴ[tab]Ｅ００４４
「青葉公園クリア」
びっとお～んッ！！
[wait][clear][end]

msg_157:
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear][end]

msg_158:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_159:
[color(yellow)]轟所長[color(white)]
[tab]「噂」についての説明だな。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]「噂の依頼」を選択し、どの噂を流すか選べ。
[tab]そうしたら、その噂話を珠聞瑠中に広めてやる。
[tab]仕事として請け負う以上、金銭は要求させてもらうがな。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]噂の元ネタは「噂屋」から聞いて持ってこい。
[tab]やつらは、珠聞瑠のあちこちにいる。
[tab]がんばって探してみるんだな。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]それから、すでに広めた噂については
[tab]「噂の確認」から確認できるぞ。
[wait][clear][color(yellow)]轟所長[color(white)]
[tab]俺に依頼した噂以外にも、悪魔共の中で
[tab]流行ってる噂も確認できる。
[tab]…まあ、こんなところだな。
[wait][clear][end]

msg_160:
[color(yellow)]本棚[color(white)]
[tab][color(green)]スライド式の本棚。
[tab]動きそうだが…[color(white)]
[wait][clear][end]

msg_161:
[color(yellow)]本棚[color(white)]
[tab][color(green)]スライド式の本棚だが、動きそうにない。[color(white)]
[wait][clear][end]

msg_162:
[color(yellow)]本棚[color(white)]
[tab][color(green)]スライド式の本棚だが、動きそうにない。[color(white)]
[wait][clear][end]

msg_163:
[color(yellow)]本棚[color(white)]
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear][end]

msg_164:
[color(yellow)]轟所長[color(white)]
[tab]この噂操作には、[var(msg_var_0)]円かかるが、依頼するか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_165:
[color(yellow)]轟所長[color(white)]
[tab]この噂操作には、[var(msg_var_0)]円かかるが、依頼するか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_166:
[color(yellow)]轟所長[color(white)]
[tab]この噂はどう広まるか分からんな…。
[tab][var(msg_var_0)]円かかるが、それでもいいか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_167:
[color(yellow)]轟所長[color(white)]
[tab]お前達の所持金では、依頼料を払えないぞ。[wait][clear][end]
