
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]殺されたセブンスの校長って、
[tab]ワンロン占いに凝ってたらしいじゃない？
[tab]…あの結果もわかってたのかな。
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]私の守護龍はねぇ、神秘的な皎龍ぅ！
[tab]マーヤの守護龍は？[tab]え、知らないの？
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]マーヤって何で原稿書いてるの？
[tab]ワープロ？[tab]パソコン？
[tab]私、ブラインドタッチ出来ないのよね～
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab][suou]さんも、パオも…
[tab]みんな目的を持って生きてるんだよねぇ。
[tab]やっぱ男と女って違うのかなぁ～
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]今気付いたけどさぁ、私、高校時代からマーヤに
[tab]振りまわされっぱなしじゃない？
[tab]高三の時のＷデートだってさぁ、マーヤが……
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]やっぱワンロン占いって当たるよね。
[tab]こんな状況でも気になっちゃうのは…
[tab]女のコだモン！[tab]仕方ないよね？
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]ワンロン占いの影響力は異常だな。
[tab]あの杏奈って子も悪い結果に振りまわされて…
[tab]噂の件と関係があるのか？
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]僕の守護龍？[tab]あぁ、ワンロン占いか。
[tab]占いによると直感的な紫龍らしいが…
[tab]僕はあまり信じてないな。
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]あの占い師がＪＯＫＥＲを語ったのは偶然か？
[tab]それとも…事件に関係しているのか？
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]天野君、彼を…牧村君を黙らせてくれないか？
[tab]ちょっとね、彼の言動を見ていたらね、
[tab]怒りを抑えきれそうになくってね！！
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]警察だってネットワーク化は進んでいる。
[tab]事務処理の効率化は当然として、
[tab]ネットワーク犯罪への対応が主な目的だ。
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]生きて行く目的か。…考えた事も無かったな。
[tab]僕は自分の思うままに生きているだけだ。
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]ふっくらとキメ細かく焼くコツ。
[tab]ツノが立つまで泡立て…手早く軽く混ぜ合わせる。
[tab]あ、気にしないでくれ、独り言だ。
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]珠閒瑠警察でも、事件捜査にワンロン占いを
[tab]導入する予定があったな。
[tab]それも、今になって思うと…
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]ワンロン占い？
[tab]芹沢がぎゃーぎゃー言ってるヤツか？
[tab]開放的な紺龍がどうとかいってたぜ？
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]コンピューターを使えるヤツが偉いわけじゃねぇ。
[tab]でもなぁ、今の社会では重要視されんだよ。
[tab]…時代の流れには逆らえねぇもんなぁ。
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]女媧とＪＯＫＥＲねぇ。
[tab]確かに怪しいが…
[tab]言葉遊びで話題に便乗しただけかもな。
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]結婚詐欺ってのは、女を騙す為なら
[tab]何でも利用するんだな。
[tab]節操ねぇなぁ…色んな意味で。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]パソコンと酒の事なら任せろ。何を知りてぇんだ？
[tab]…はぁ？[tab]入力は…かな入力か？…だとぉ？
[tab]はぁー、俺はローマ字入力だよ。
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]生きて行くのになぁ、男も女も関係ねぇだろ？
[tab]他人を特別視して、逃げ道を確保しようなんて
[tab]甘いんだよ。…ホントは気付いてんだろ？
[wait][clear][end]

msg_21:
[color(yellow)]パオフゥ[color(white)]
[tab]天野が人を振りまわす存在ねぇ。
[tab]へへへ、当たってんじゃねぇのか、それ？
[tab]じゃあ俺は、軽～くステアする程度にしとくか？
[wait][clear][end]

msg_22:
[color(yellow)]パオフゥ[color(white)]
[tab]おいおい、この状況でワンロン占いかぁ？
[tab]…あんたものんきだねぇ。
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]俺の守護龍なら中庸的な銀龍だ。
[tab]もっとも、人を１２種に分けられるとは思わんが、
[tab]とりあえず、銀龍だそうだ。
[wait][clear][end]

msg_24:
[color(yellow)]エリー[color(white)]
[tab]守護龍…ですか？
[tab]知的なＢｌａｃｋ[tab]Ｄｒａｇｏｎらしいですわ。
[tab]…あってます？
[wait][clear][end]

msg_25:
[color(yellow)]中年サラリーマン[color(white)]
[tab]わ、分かる…分かるようになった。くーッ！
[tab]ワシにもパソコンが使えるようになったんだぁ。
[tab]これが熱心に勉強した成果なんだぁー！
[wait][clear][end]

msg_26:
[color(yellow)]中年サラリーマン[color(white)]
[tab]ハハハ、これで会社の若僧どもに偉そうな顔を
[tab]される事は無い。アナクロと虐げられる事も無い！
[tab]ワシにだってパソコンくらい使えるんだぁ！
[wait][clear][end]

msg_27:
[color(yellow)]中年サラリーマン[color(white)]
[tab]武器販売をするお店ねぇ。
[tab]以前のワシなら…危なかったなぁ。
[tab]即購入し、馬鹿にした連中を殺っちゃったかも？
[wait][clear][end]

msg_28:
[color(yellow)]中年サラリーマン[color(white)]
[tab]やらなくて良かったー、ＪＯＫＥＲ呪い！！
[tab]人を呪っても、パソコンがわかる訳じゃないから
[tab]やめたけど…何度かやろうと思ったんだよ。
[wait][clear][end]

msg_29:
[color(yellow)]中年サラリーマン[color(white)]
[tab]ネット上には色んな掲示板があるんだけど、
[tab]最近は尋ね人の掲示板がホットだね。
[tab]…行方不明者急増中って知ってた？
[wait][clear][end]

msg_30:
[color(yellow)]太った男[color(white)]
[tab]やっぱネットって面白いよねェ。
[tab]特にオススメは、パオフゥって人のホームページ。
[tab]巷の噂を色々と集めてんだァ。
[wait][clear][end]

msg_31:
[color(yellow)]太った男[color(white)]
[tab]ネットで見たんだけどね、
[tab]どっかのバーで本物の武器を売ってるらしいネェ。
[tab]だけど武器なんて売っちゃっていいのかなァ。
[wait][clear][end]

msg_32:
[color(yellow)]太った男[color(white)]
[tab]パオフゥって人、オフではどんな生活してんだろ？
[tab]ホームページの更新がないと思ったら、
[tab]閉鎖しちゃったし。…なんかあったのかなァ？
[wait][clear][end]

msg_33:
[color(yellow)]太った男[color(white)]
[tab]ちょっと、邪魔しないでよ！
[tab]今、インターネットのＪＯＫＥＲ目撃ページに
[tab]書き込みをしてるんだ。
[wait][clear][end]

msg_34:
[color(yellow)]太った男[color(white)]
[tab]え～と…
[tab]わたし、テレビきょくでみました♥[tab]ウフッ♥
[tab]…っと。へへ…禁断の女性モードで入力だ。
[wait][clear][end]

msg_35:
[color(yellow)]牧村[color(white)]
[tab]女のコって占い好きだよな。
[tab]当然、利用させてもらったよ。
[wait][clear][end]

msg_36:
[color(yellow)]パソコン[color(white)]
[tab]当ほーむぺーじハ、管理人ノ都合ニヨリ、
[tab]現在閉鎖中トナッテオリマス。
[tab]ナオ、噂掲示板ハ従来通リ運営中デス。
[wait][clear][end]

msg_37:
[tab]めにゅーヲ選択シテクダサイ。
[choice(2)]噂掲示板を見る
終了
[end_choice][clear][end]

msg_38:
[tab]めにゅーヲ選択シテクダサイ。
[choice(2)]噂掲示板を見る
終了
[end_choice][clear][end]

msg_39:
[color(yellow)]投稿者：スマルキング[color(white)]
[tab]セブンスの校長が、あのＪＯＫＥＲに殺されたそう
[tab]です。（セブンスに通う従兄弟に聞きました）
[tab]ケーサツが来て大変だったそうです。では！
[wait][clear][end]

msg_40:
[color(yellow)]投稿者：（不明）[color(white)]
[tab]パラベラムで武器が売られていました。
[tab]あそこの店長、その筋では有名なガンマニアらしく
[tab]ずっと前から噂にはなっていたようです。
[wait][clear][end]

msg_41:
[color(yellow)]投稿者：ホントだ！[color(white)]
[tab]＞パラベラムで武器が売られていました。
[tab]この書き込み、本当でした。早速購入しました。
[tab]…店名が既に怪しかったのね。
[wait][clear][end]

msg_42:
[color(yellow)]投稿者：スマルキング[color(white)]
[tab]前に、地下鉄の工事現場から遺跡が出たとの報道が
[tab]ありましたが、あれは工事の遅れを隠すためのデマ
[tab]だったそうです。（叔父に聞きました）[tab]では！
[wait][clear][end]

msg_43:
[color(yellow)]投稿者：コレもホント！[color(white)]
[tab]この秋、[color(orange)]ロサカンディータ[color(white)]では[color(orange)]本物の防具[color(white)]を売り始
[tab]めるそうです。あの店らしく、ぶっ飛んだセンスの
[tab]鎧がラインナップに入っているそうです。
[wait][clear][end]

msg_44:
[color(yellow)]投稿者：（不明）[color(white)]
[tab][color(orange)]月刊バトルマスター[color(white)]って知ってます？
[tab]あの本の懸賞で[color(orange)]本物の防具[color(white)]が当たるそうなんですが
[tab]詳しい事を知ってる方、レスお願いします。
[wait][clear][end]

msg_45:
[color(yellow)]投稿者：スマルキング[color(white)]
[tab]ゲームセンターの[color(orange)]ムー大陸[color(white)]、実は[color(orange)]カジノ[color(white)]だったって
[tab]噂です。（メル友から聞きました）
[tab][color(orange)]スロットが揃いやすい[color(white)]そうです。では！
[wait][clear][end]

msg_46:
[color(yellow)]投稿者：ＫＡＹ[color(white)]
[tab][color(orange)]特殊なアイテム[color(white)]がもらえると噂の雑誌を発見！
[tab]雑誌の名前は[color(orange)]ファンタジーワールド[color(white)]です。
[tab]ただし、懸賞に応募・当選しないと駄目です。
[wait][clear][end]

msg_47:
[color(yellow)]投稿者：コレはホント？[color(white)]
[tab]あの[color(orange)]ロサカンディータ[color(white)]の名物マヌカンが、旅行先で
[tab][color(orange)]波にのまれた[color(white)]らしいです。真相は謎のままですが、
[tab]マヌカンに何かあった事だけは確実です！
[wait][clear][end]

msg_48:
[color(yellow)]パソコン[color(white)]
[tab]終了シマス。
[tab]ソノママ、オ待チクダサイ。
[tab][delay(15)]…[delay(15)]…[delay(15)]…[delay(15)]終了。
[sync][wait][clear][end]

msg_49:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]ねぇねぇ、お姉さんは何龍の人ぉ？
[tab]…え、わからない！？[tab]だってワンロン占いだよ？
[tab]お姉さんヤバ過ぎぃ、遅れ過ぎぃ！！
[wait][clear][end]

msg_50:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]いたしかたない…既にワンロン占いを極め、
[tab]その源流、望龍術にも迫る私が占ってしんぜよう！
[tab]あ～おほん！！[tab]お主は何月生まれかね？
[wait][clear][end]

msg_51:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]あ、お姉さん！[tab]なに？[tab]私に占ってほしいの？
[tab]う～ん…万物流転、ワンロン占いまた然り！
[tab]前と結果が違っちゃうかも？[tab]それでもいい？
[wait][clear][end]

msg_52:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]…あ、そう。ならば…既にワンロン占いを極め、
[tab]その源流、望龍術にも迫る私が占ってしんぜよう！
[tab]あ～おほん！！[tab]お主は何月生まれかね？
[sync][wait][clear][end]

msg_53:
１
イチ
イチガツ
１ガツ
ＪＡＮ
２
ニ
ニガツ
２ガツ
ＦＥＢ
３
サン
サンガツ
３ガツ
ＭＡＲ
４
シ
シガツ
ヨン
ヨンガツ
４ガツ
ＡＰＲ
５
ゴ
ゴガツ
５ガツ
ＭＡＹ
６
ロク
ロクガツ
６ガツ
ＪＵＮ
７
シチ
シチガツ
ナナ
ナナガツ
７ガツ
ＪＵＬ
８
ハチ
ハチガツ
８ガツ
ＡＵＧ
９
ク
クガツ
キュウ
キュウガツ
９ガツ
ＳＥＰ
１０
ジュウ
ジュウガツ
１０ガツ
ＯＣＴ
１１
ジュウイチ
ジュウイチガツ
１１ガツ
ＮＯＶ
１２
ジュウニ
ジュウニガツ
１２ガツ
ＤＥＣ
イアイアハスタア
[end]

msg_54:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]え？[tab]…何？
[tab]ちゃんと教えてくれなきゃ占えないよ？
[tab]では改めて。…お主は何月生まれかね？
[sync][wait][clear][end]

msg_55:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、１月生まれのあなたの守護龍は、
[tab]十二の龍において安定を守る「黄龍」じゃな。
[wait][clear][end]

msg_56:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]責任感があり、辛抱強いあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_57:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、２月生まれのあなたの守護龍は、
[tab]十二の龍において変革を好む「青龍」じゃな。
[wait][clear][end]

msg_58:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]理知的で、物静かなあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_59:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、３月生まれのあなたの守護龍は、
[tab]十二の龍において情緒を司る「白龍」じゃな。
[wait][clear][end]

msg_60:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]人情に厚く、涙もろいあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_61:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、４月生まれのあなたの守護龍は、
[tab]十二の龍において戦いを導く「緋龍」じゃな。
[wait][clear][end]

msg_62:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]向こう見ずで性急、強情なあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_63:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、５月生まれのあなたの守護龍は、
[tab]十二の龍において現世を守る「金龍」じゃな。
[wait][clear][end]

msg_64:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]現実的で、無理を好まぬあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_65:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、６月生まれのあなたの守護龍は、
[tab]十二の龍において開放を生む「紺龍」じゃな。
[wait][clear][end]

msg_66:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]活発で、頭の回転が早いあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_67:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、７月生まれのあなたの守護龍は、
[tab]十二の龍において道義を尊ぶ「光龍」じゃな。
[wait][clear][end]

msg_68:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]感受性が鋭く、同情心のあるあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_69:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、８月生まれのあなたの守護龍は、
[tab]十二の龍において情熱を司る「赤龍」じゃな。
[wait][clear][end]

msg_70:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]自信にあふれ、冒険を好むあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_71:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、９月生まれのあなたの守護龍は、
[tab]十二の龍において知を授ける「黒龍」じゃな。
[wait][clear][end]

msg_72:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]真面目で、何事にも熱心なあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_73:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、１０月生まれのあなたの守護龍は、
[tab]十二の龍において中庸を守る「銀龍」じゃな。
[wait][clear][end]

msg_74:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]芸術家肌で、争いを好まぬあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_75:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、１１月生まれのあなたの守護龍は、
[tab]十二の龍において神秘を生む「皎龍」じゃな。
[wait][clear][end]

msg_76:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]心の中に情熱を秘めるあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_77:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]うむ、１２月生まれのあなたの守護龍は、
[tab]十二の龍において正義を尊ぶ「紫龍」じゃな。
[wait][clear][end]

msg_78:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]正直で、常に自由を求めるあなた。
[tab]そんなあなたの今日の運勢は…
[sync][wait][clear][end]

msg_79:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]…！！！！！！！
[wait][clear][end]

msg_80:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]幸運の活龍、伏羲の加護も得て最高の１日じゃ。
[tab]失敗を恐れず何事にもチャレンジすべし！
[tab]黒龍の男性がより強い運気を運んでくるぞよ。
[sync][wait][clear][end]

msg_81:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]活龍に愛され、健やかなる１日を送れるようじゃ。
[tab]ただし、健康にだけは注意が必要だぞ！
[tab]勉強や仕事は、皎龍の異性と協力するのが吉。
[sync][wait][clear][end]

msg_82:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]活龍の支援を得て、幸福を実感できる１日となる。
[tab]しかし、真の幸福を得るには努力が不可欠。
[tab]学校や職場で、異属龍の攻撃に会うかもよ？
[sync][wait][clear][end]

msg_83:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]同属三龍の協力により、運気が上昇する１日じゃ。
[tab]ここは一つ、積極的に動いて見るべき！
[tab]ガイコツのキーホルダーが出会いのきっかけに。
[sync][wait][clear][end]

msg_84:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]活龍の吐息に包まれ、穏やかな１日となるぞ。
[tab]ただし、青龍の友達には注意が必要じゃな。
[tab]好き嫌いをハッキリと言えると吉！
[sync][wait][clear][end]

msg_85:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]同属龍の囁きに惑わされ、混乱の１日となるぞ。
[tab]あまり外には出ずに、家でコツコツとやるべき。
[tab]レモングラスの香りが平穏のカギじゃ。
[sync][wait][clear][end]

msg_86:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]逆属龍の企みに巻き込まれ、イマイチな１日に。
[tab]スポーツ＆ギャンブルで活龍を呼び込めたら、
[tab]一転して最高の日に！[tab]爪は切っておく事！
[sync][wait][clear][end]

msg_87:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]死龍の影がちらつく、困った１日となるようじゃ。
[tab]異属龍の協力があれば少しはマシに。
[tab]学校の近くは要注意。走って通りぬけろ！
[sync][wait][clear][end]

msg_88:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]逆属龍の恨みを買い、かなりヤバイ１日。
[tab]全てが裏目に出そうじゃが、金龍の異性からの
[tab]電話が運気逆転のチャンスかも？
[sync][wait][clear][end]

msg_89:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]死龍の怒りに触れ、悲しい１日になりそうじゃ。
[tab]逆属龍の助けも役に立ちそうになく処置無し。
[tab]嫉妬が状況を悪化させる原因に！
[sync][wait][clear][end]

msg_90:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]死龍に愛される困った１日となるぞ。
[tab]全ての事柄が希望の逆となる。何もしないのが吉。
[tab]何もしなくていい分、ある意味幸せかも？
[sync][wait][clear][end]

msg_91:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]穢れの死龍、女媧の呪いを受け最悪の１日じゃ。
[tab]十二龍全てがあなたの敵となる。
[tab]何も言わん…家で寝ていろ…
[sync][wait][clear][end]

msg_92:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]…ってカンジかしら？
[sync][wait][clear][end]

msg_93:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]クックックッ…
[tab]その言葉を口にした事、悔いる時が訪れるぞ。
[wait][clear][end]

msg_94:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]深入りするのは止めておけ。
[tab]…わかるか？[tab]これは忠告だぞ！
[wait][clear][end]

msg_95:
[color(yellow)]ワンロン占いマニア[color(white)]
[tab]…忠告した筈だ……
[tab]ふざけるな！！
[wait][clear][end]

msg_96:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]いらっしゃい。
[tab]つーか、こんな昼間からインターネット？
[tab]お客さんって結構ヒマなの？[tab]まぁいいけど。
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_97:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]あぁ、いらっしゃい。
[tab]つーかお客さんって、ほんとヒマなんだね。
[tab]…なんかこっちが哀しくなるよ。
[wait][clear][end]

msg_98:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]自分ちでインターネット出来るようにすれば？
[tab]…えー、簡単じゃん！？[tab]それマズイよ～
[tab]…哀しいから、今日は少し安くしたげるよ。
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_99:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]そんで、何が聞きたいんだ？
[choice(3)]世間話をする
食事の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_100:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]はい…
[tab]んで、まだなんかあんの？
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_101:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]そんで、何が聞きたいんだ？
[choice(3)]世間話をする
食事の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_102:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]セブンスの校長が死んだんだって。知ってた？
[tab]まあ、生きてる事自体、意味なんて無いからね。
[tab]いつ死んでも同じだし。違うかな～
[wait][clear][end]

msg_103:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]どこかのＨＰにあったんだけど、なんかさぁ、
[tab]この青葉区に武器を売るショップがあるんだって。
[tab]店名までは出てなかったけど、バカな噂だよね。
[wait][clear][end]

msg_104:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]まぁ話の種にはなったけど、つまんないね。
[tab]…ていうか、つまんな過ぎて死んだ方がマシ。
[tab]俺ってかなり前向きでしょ？
[wait][clear][end]

msg_105:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]あ～ＪＯＫＥＲのやつ、ココに来てくんないかな。
[tab]なんか来たら楽そうじゃん？[tab]刺されたりして。
[tab]…ていうか、俺前向きだよね？
[wait][clear][end]

msg_106:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]なんかさぁ、今度はＭＵＳＥＳだっけ？
[tab]佐々木[tab]銀次プロデュースってだけで人気だよね。
[tab]今売れてんの、あいつの曲ばっかじゃん。
[wait][clear][end]

msg_107:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]とりあえずこっちもヒマだし、また来てよ。
[tab]なんだったら、ごちそう出すからさ。
[tab]まぁ冗談だけどね…いいんだよ、そんなこたぁ。
[wait][clear][end]

msg_108:
ＭＢＩＴ[tab]ＡＩＳ[tab]１２
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_109:
ＥＢＩＴ[tab]Ｅ００１５
七姉妹学園クリア
びっとお～んッ！！
[wait][clear][end]

msg_110:
ＥＢＩＴ[tab]Ｅ００１８
バー終了・パオフゥ初参加
びっとお～んッ！！
[wait][clear][end]

msg_111:
ＥＢＩＴ[tab]Ｅ００１Ｆ
病院クリア
びっとお～んッ！！
[wait][clear][end]

msg_112:
ＥＢＩＴ[tab]Ｅ００３３
「パオフゥ編入」
びっとお～んッ！！
[wait][clear][end]

msg_113:
ＥＢＩＴ[tab]Ｅ００３７
警察署[half_tab]受付、終了
びっとお～んッ！！
[wait][clear][end]

msg_114:
ＥＢＩＴ[tab]Ｅ００３８
「詐欺男を確保」
びっとお～んッ！！
[wait][clear][end]

msg_115:
ＥＢＩＴ[tab]Ｅ００３Ｅ
「ゴールドクリア」「うらら編入」
びっとお～んッ！！
[wait][clear][end]

msg_116:
ＥＢＩＴ[tab]Ｅ００４３
「クラブクリア」
びっとお～んッ！！
[wait][clear][end]

msg_117:
ＥＢＩＴ[tab]Ｅ００４４
「青葉公園クリア」
びっとお～んッ！！
[wait][clear][end]

msg_118:
ＥＢＩＴ[tab]Ｅ００４５
「事件の情報を握る男ｏｒ女の噂を拡散」
びっとお～んッ！！
[wait][clear][end]

msg_119:
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear][end]

msg_120:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_121:
[color(yellow)]やる気のないボーイ[color(white)]
[tab]ああ、「食事」の説明ね…
[tab]うちで、「食事をする」を選ぶと食事ができるよ。
[tab]…全部レトルトとインスタントだけど。
[wait][clear][color(yellow)]やる気のないボーイ[color(white)]
[tab]でも一応、なんか食べたり飲んだりすると
[tab]しばらく能力をあげることができるそうだぜ。
[tab]で、物によって効果が違うらしいよ、よく知らんけど。
[wait][clear][color(yellow)]やる気のないボーイ[color(white)]
[tab]ああそれから、一度飲み食いしたら、
[tab]その効果が切れるまで次の食事はできないからな。
[wait][clear][end]

msg_122:
[color(yellow)]やる気のないボーイ[color(white)]
[tab][var(msg_var_0)]円だけど、いいかぁ？
[choice(2)]はい
いいえ
[end_choice][clear][end]
