
msg_0:
[tab]パーティの人数が四人を超えています。
[tab]金田・片岡に連絡してください。
[tab][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ハァ…
[tab]ついこの間、ゴミ出ししたばっかりなのに…
[end]

msg_2:
[tab]分別するのだって楽じゃないんだからね！
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]そう言えば、マーヤと
[tab]この部屋で暮らし始めて、もう何年目かな？
[tab]ホント、がさつな二人暮らし…だよね。
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]どうでもいいけど、
[tab]この部屋、壁薄すぎよねぇ。
[tab]隣の声筒抜けだもん。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]ねぇマーヤ、[tatsuya]君、この部屋に入れたことって
[tab]今までにある？[tab]無いよね？
[end]

msg_6:
[tab]なんで彼、部屋の様子知ってたんだろ…
[wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab][tatsuya]君が知ってたのって…
[tab]「向こう側」のこの部屋ってこと…？
[tab]それじゃあ、やっぱり…
[wait][clear][end]

msg_8:
[color(yellow)]うらら[color(white)]
[tab]そう言えばマーヤ、
[tab]玄関の掃除してないでしょ？
[tab]当番制って言い出したのはマーヤなんだからね！
[wait][clear][end]

msg_9:
[color(yellow)]うらら[color(white)]
[tab]ハァ…
[tab]この部屋無事で良かったわ…
[end]

msg_10:
[tab]事件解決しても帰る所無しじゃたまんないもの。
[wait][clear][end]

msg_11:
[color(yellow)]うらら[color(white)]
[tab]またこの部屋に戻ってこれるのかな…
[tab]…ふふ…らしくないか。
[tab]死にに行くんじゃないんだから。
[wait][clear][end]

msg_12:
[color(yellow)]うらら[color(white)]
[tab]そう言えば、マーヤには教えてなかったけど、
[tab]私、最近フラメンコ習い始めたのよ。
[tab]今度、見せたげようか？[tab]うまいんだから♥
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]仕事に熱心なのは分かるが、
[tab]ここまで私生活を犠牲にするのも考え物だぞ。
[tab]仕事のために生きてる訳でもあるまい。
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]済まん、そこの書きかけの原稿…読んでしまった。
[tab]「噂の高校生の夢」か…
[tab]アイツにはどんな夢があったのかな…
[wait][clear][end]

msg_15:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]のヤツどうしたんだ？
[tab]先程から何も言わんが…
[tab]体調でも悪いのか？
[wait][clear][end]

msg_16:
[color(yellow)]克哉[color(white)]
[tab]「向こう側」でも
[tab]この部屋の状態は変わらんようだな。
[tab]聞かなくても[tatsuya]の様子を見ればわかる。
[wait][clear][end]

msg_17:
[color(yellow)]克哉[color(white)]
[tab]トリフネが浮上しただけでも、
[tab]周囲の被害は想像がつかん…
[tab]…人の命を何だと思っているんだ！
[wait][clear][end]

msg_18:
[color(yellow)]克哉[color(white)]
[tab]僕は父を尊敬していた。自分を犠牲にしてでも、
[tab]人々の生活を守ろうとする
[tab]父の後姿に憧れていた。
[wait][clear][end]

msg_19:
[color(yellow)]克哉[color(white)]
[tab]君達は絶対に死なせやしない。
[tab]誰一人、僕の前では…二度と。
[tab]父と僕の名誉にかけて…
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]取り敢えずこの部屋に盗聴機はなさそうだな…
[end]

msg_21:
[tab]…ん？[tab]何やってんだ俺は？
[tab]つい普段の仕事の癖が…
[wait][clear][end]

msg_22:
[color(yellow)]パオフゥ[color(white)]
[tab]今の俺をあいつが見たらどう言うかな…
[tab]ふん…いい気なものだと罵るかもな。
[tab]…違いねぇ…
[wait][clear][end]

msg_23:
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢のヤツ、
[tab]この部屋が禁煙だと？
[tab]手前はスパスパ吸っといてよく言うぜ。
[wait][clear][end]

msg_24:
[color(yellow)]パオフゥ[color(white)]
[tab]冷蔵庫の中のカニ缶の山は何だ？
[tab]あれ全部食べるつもりなのか？
[tab]…ん？[tab]勝手に覗くなって？
[wait][clear][end]

msg_25:
[color(yellow)]パオフゥ[color(white)]
[tab]神事が実行されれば、被害はこれどころじゃねぇ。
[tab]ヤツ等の望みを叶える為には、
[tab]人類が死滅するしかねぇからな…
[wait][clear][end]

msg_26:
[color(yellow)]パオフゥ[color(white)]
[tab]人の命が限られてるのはなぜだと思う？
[tab]人間には、変わる力があるからさ。
[tab]死ねない奴より死ねる奴の方が、ずっと強いんだ
[wait][clear][end]

msg_27:
[color(yellow)]南条[color(white)]
[tab]もっぱら掃除役は自分だと、
[tab]Ｍｓ．芹沢がぼやいてましたよ。
[tab]そうなんですか？
[wait][clear][end]

msg_28:
[color(yellow)]南条[color(white)]
[tab]ベランダは綺麗ですね。
[tab]ガーデニングでも始めてみてはどうです。
[tab]少しは女性らしく…[end]

msg_29:
ゴホッ、ゴホッ。
[wait][clear][end]

msg_30:
[color(yellow)]南条[color(white)]
[tab]あの少年、言葉を失っていますよ。
[tab]やはりこの部屋、
[tab]刺激が強過ぎたのではないですか？
[wait][clear][end]

msg_31:
[color(yellow)]南条[color(white)]
[tab]入った事の無い部屋の様子を知っている…
[tab]やはり、「向こう側」という世界の存在は
[tab]本当なのか…
[wait][clear][end]

msg_32:
[color(yellow)]エリー[color(white)]
[tab]もっぱら掃除役は自分だと、
[tab]Ｍｓ．Ｕｒａｒａが言ってましたわ。
[tab]そうなんですの？
[wait][clear][end]

msg_33:
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．ＡｍａｎｏもＡｒｏｍａ[tab]ｔｈｅｒａｐｙを
[tab]始めてはいかがです？
[tab]きっと部屋の雰囲気も変わりますわ。
[wait][clear][end]

msg_34:
[color(yellow)]エリー[color(white)]
[tab][tatsuya]…言葉を失ってますわ。
[tab]やはりこの部屋、
[tab]彼には刺激が強過ぎたのではありません？
[wait][clear][end]

msg_35:
[color(yellow)]エリー[color(white)]
[tab]彼…入ったことの無い部屋の様子を
[tab]知っているということは…
[tab]やはり、「向こう側」の話は本当なんですの…？
[wait][clear][end]

msg_36:
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．Ｕｒａｒａは、
[tab]Ｆｌａｍｅｎｃｏを習ってたそうですわね。
[tab]実は私も少しばかり心得がありますの。
[wait][clear][end]

msg_37:
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．Ｕｒａｒａとどちらが上手かしら…
[tab]そのうち、ご覧に入れますわ。
[tab]ご期待下さいね。
[wait][clear][end]

msg_38:
[color(yellow)][tatsuya][color(white)]
[tab]この世界でも同じか…
[wait][clear][end]

msg_39:
[color(yellow)][tatsuya][color(white)]
[tab]この部屋のことは知っている…
[tab]「こちら側」でも、変わらないんだな…
[wait][clear][end]

msg_40:
[color(yellow)][tatsuya][color(white)]
[tab]もう二度と、
[tab]ここに来るつもりは無かったんだ…
[tab]…本当は…
[wait][clear][end]

msg_41:
[color(yellow)][tatsuya][color(white)]
[tab]シバルバー…
[tab]アメノトリフネ…
[tab]またこの姿を見る事になるなんて…
[wait][clear][end]

msg_42:
[color(yellow)][tatsuya][color(white)]
[tab]今度こそ、
[tab]俺は皆との約束を守ってみせる…
[tab]そして…今度こそ…
[wait][clear][end]

msg_43:
[color(green)][tab]鍵がかかっている。[color(white)]
[wait][clear][end]

msg_44:
[color(yellow)]うらら[color(white)]
[tab]こりゃ、マーヤ！！
[tab]人の部屋に勝手に入ろうとするでないよ！
[tab]そっから先は私の聖域なのよ。
[wait][clear][end]

msg_45:
[color(yellow)]コンポ[color(white)]
[color(green)][tab]最新型のコンポ。
[tab]これだけはまだキレイだ。[color(white)]
[wait][clear][end]

msg_46:
[color(green)][tab]ＣＤを聞きますか？[color(white)]
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_47:
[color(green)][tab]グループを選んでください。[color(white)]
[choice(9)][if_any(MBIT_CD_CD01, MBIT_CD_CD02, MBIT_CD_CD03, MBIT_CD_CD04, MBIT_CD_KACD01)]エーアスト
[if_all(!MBIT_CD_CD01, !MBIT_CD_CD02, !MBIT_CD_CD03, !MBIT_CD_CD04, !MBIT_CD_KACD01)][color(gray)]未購入[color(white)]
[if_any(MBIT_CD_CD05, MBIT_CD_CD06, MBIT_CD_CD07, MBIT_CD_CD08, MBIT_CD_KACD02)]ツヴァイト
[if_all(!MBIT_CD_CD05, !MBIT_CD_CD06, !MBIT_CD_CD07, !MBIT_CD_CD08, !MBIT_CD_KACD02)][color(gray)]未購入[color(white)]
[if_any(MBIT_CD_CD09, MBIT_CD_CD10, MBIT_CD_CD11, MBIT_CD_CD12, MBIT_CD_CD13)]ドリット
[if_all(!MBIT_CD_CD09, !MBIT_CD_CD10, !MBIT_CD_CD11, !MBIT_CD_CD12, !MBIT_CD_CD13)][color(gray)]未購入[color(white)]
[if_any(MBIT_CD_CD14, MBIT_CD_CD15, MBIT_CD_CD16, MBIT_CD_CD17, MBIT_CD_CD18)]フィーアト
[if_all(!MBIT_CD_CD14, !MBIT_CD_CD15, !MBIT_CD_CD16, !MBIT_CD_CD17, !MBIT_CD_CD18)][color(gray)]未購入[color(white)]
やめる
[end_choice][clear][end]

msg_48:
[color(green)][tab]このグループのＣＤは、
[tab]まだ一枚も購入していません。[color(white)]
[wait][clear][end]

msg_49:
[color(green)][tab]ＣＤを選んでください。[color(white)]
[choice(11)][if_all(MBIT_CD_CD01)]ＣＤ１
[if_all(!MBIT_CD_CD01)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD02)]ＣＤ２
[if_all(!MBIT_CD_CD02)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD03)]ＣＤ３
[if_all(!MBIT_CD_CD03)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD04)]ＣＤ４
[if_all(!MBIT_CD_CD04)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_KACD01)]隠しＣＤ１
[if_all(!MBIT_CD_KACD01)][color(gray)]未購入[color(white)]
やめる
[end_choice][clear][end]

msg_50:
[color(green)][tab]このＣＤは、
[tab]まだ購入していません。[color(white)]
[wait][clear][end]

msg_51:
[color(green)][tab]ＣＤを選んでください。[color(white)]
[choice(11)][if_all(MBIT_CD_CD05)]ＣＤ５
[if_all(!MBIT_CD_CD05)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD06)]ＣＤ６
[if_all(!MBIT_CD_CD06)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD07)]ＣＤ７
[if_all(!MBIT_CD_CD07)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD08)]ＣＤ８
[if_all(!MBIT_CD_CD08)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_KACD02)]隠しＣＤ２
[if_all(!MBIT_CD_KACD02)][color(gray)]未購入[color(white)]
やめる
[end_choice][clear][end]

msg_52:
[color(green)][tab]このＣＤは、
[tab]まだ購入していません。[color(white)]
[wait][clear][end]

msg_53:
[color(green)][tab]ＣＤを選んでください。[color(white)]
[choice(11)][if_all(MBIT_CD_CD09)]ＣＤ９
[if_all(!MBIT_CD_CD09)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD10)]ＣＤ１０
[if_all(!MBIT_CD_CD10)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD11)]ＣＤ１１
[if_all(!MBIT_CD_CD11)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD12)]ＣＤ１２
[if_all(!MBIT_CD_CD12)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD13)]ＣＤ１３
[if_all(!MBIT_CD_CD13)][color(gray)]未購入[color(white)]
やめる
[end_choice][clear][end]

msg_54:
[color(green)][tab]このＣＤは、
[tab]まだ購入していません。[color(white)]
[wait][clear][end]

msg_55:
[color(green)][tab]ＣＤを選んでください。[color(white)]
[choice(11)][if_all(MBIT_CD_CD14)]ＣＤ１４
[if_all(!MBIT_CD_CD14)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD15)]ＣＤ１５
[if_all(!MBIT_CD_CD15)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD16)]ＣＤ１６
[if_all(!MBIT_CD_CD16)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD17)]ＣＤ１７
[if_all(!MBIT_CD_CD17)][color(gray)]未購入[color(white)]
[if_all(MBIT_CD_CD18)]ＣＤ１８
[if_all(!MBIT_CD_CD18)][color(gray)]未購入[color(white)]
やめる
[end_choice][clear][end]

msg_56:
[color(green)][tab]このＣＤは、
[tab]まだ購入していません。[color(white)]
[wait][clear][end]

msg_57:
[tab][color(green)]ＣＤ１再生中。[color(white)]
[end]

msg_58:
[tab][color(green)]ＣＤ２再生中。[color(white)]
[end]

msg_59:
[tab][color(green)]ＣＤ３再生中。[color(white)]
[end]

msg_60:
[tab][color(green)]ＣＤ４再生中。[color(white)]
[end]

msg_61:
[tab][color(green)]隠しＣＤ１再生中。[color(white)]
[end]

msg_62:
[tab][color(green)]ＣＤ５再生中。[color(white)]
[end]

msg_63:
[tab][color(green)]ＣＤ６再生中。[color(white)]
[end]

msg_64:
[tab][color(green)]ＣＤ７再生中。[color(white)]
[end]

msg_65:
[tab][color(green)]ＣＤ８再生中。[color(white)]
[end]

msg_66:
[tab][color(green)]隠しＣＤ２再生中。[color(white)]
[end]

msg_67:
[tab][color(green)]ＣＤ９再生中。[color(white)]
[end]

msg_68:
[tab][color(green)]ＣＤ１０再生中。[color(white)]
[end]

msg_69:
[tab][color(green)]ＣＤ１１再生中。[color(white)]
[end]

msg_70:
[tab][color(green)]ＣＤ１２再生中。[color(white)]
[end]

msg_71:
[tab][color(green)]ＣＤ１３再生中。[color(white)]
[end]

msg_72:
[tab][color(green)]ＣＤ１４再生中。[color(white)]
[end]

msg_73:
[tab][color(green)]ＣＤ１５再生中。[color(white)]
[end]

msg_74:
[tab][color(green)]ＣＤ１６再生中。[color(white)]
[end]

msg_75:
[tab][color(green)]ＣＤ１７再生中。[color(white)]
[end]

msg_76:
[tab][color(green)]ＣＤ１８再生中。[color(white)]
[end]

msg_77:
[color(green)][tab]𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮
[tab]○ボタンか×ボタンを押すと、演奏終了します。
[tab]𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮𝅘𝅥𝅮[color(white)]
[wait][clear][end]
