
msg_0:
[tab]金田・片岡に連絡してください。
[tab][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]ここの占いは信じて大丈夫かな？
[tab]望龍術の件もあるし…
[tab]ちょっと慎重なぐらいが丁度良い？
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]パオとあの云豹って、
[tab]どんな因縁があるんだろうね？
[tab]パオは相当恨んでるみたいだけど…
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]なんだかんだ言って、
[tab][suou]さんとパオっていいコンビかもねぇ。
[tab]凸凹しててさ。
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]どうして[tatsuya]君、あんなに私達の事避けるかな？
[tab][suou]さんなんか、お兄さんでしょ？
[tab]なんだかなぁ…よく分からんよあたしゃ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab][tatsuya]君が、刑事さんの弟じゃないって
[tab]言ってたのって…ああいう事だったんだ…
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab][suou]兄弟…[suou][tab][tatsuya]と[suou][tab]克哉…
[tab]なんか適当に呼んでたら紛らわしいね。
[end]

msg_7:
[tab]よし！[tab]今日から[suou]さんは[suou]兄だ。
[wait][clear][end]

msg_8:
[color(yellow)]うらら[color(white)]
[tab]キャーーー！！
[tab][tatsuya]君って、「向こう側」じゃ、
[tab][tatsu]って呼ばれてたんだって。
[wait][clear][end]

msg_9:
[color(yellow)]うらら[color(white)]
[tab]そりゃさ、神様も占いも、
[tab]結局人の作ったものだし、
[tab]ただの思い込みって言われればそれまでだけど…
[wait][clear][color(yellow)]うらら[color(white)]
[tab]私は、それはそれで良いと思うのよねぇ。
[tab]そうやってみんな、今の自分を支えているんだし…
[tab]全てを否定しちゃ、つまらないもの。
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]占い自体、新世塾の布石だった…
[tab]今更その占いをどうこうしても、
[tab]状況を変えることはできんだろうな。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]パオフゥも一人で踏み込んで行く程
[tab]馬鹿じゃないだろう。
[tab]きっと我々の到着を待っているはずだ。
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]人間の神経組織を移植した、二足歩行戦車…
[tab]あれがそうなのか。
[tab]急がねば、パオフゥの奴が危ないぞ。
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]言っておくが、
[tab]僕は竜蔵も嵯峨に殺させるつもりはない。
[tab]罪を裁くのは法だ。僕達じゃない。
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]いつの頃からだったかな…
[tab][tatsuya]がああなったのは。
[tab]まあ…何も教えてない僕にも責任はあるか…
[wait][clear][end]

msg_15:
[color(yellow)]克哉[color(white)]
[tab]頼む天野君…僕は真実が知りたいんだ…
[tab]岩戸山へ行ってくれ…
[wait][clear][end]

msg_16:
[color(yellow)]克哉[color(white)]
[tab]芹沢君…
[tab]どう呼んでもらっても構わんが…
[tab][suou]兄…というのも安直すぎやせんか…
[wait][clear][end]

msg_17:
[color(yellow)]克哉[color(white)]
[tab][tatsu]か…
[tab]悪くないニックネームだ。
[tab]ん？[tab]だとすると僕はどうなるんだ？
[wait][clear][end]

msg_18:
[color(yellow)]克哉[color(white)]
[tab]諸悪の根源…
[tab]奴にはピッタリの言葉だな。
[tab]それが僕達人間の影そのものか…
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]俺は神様同様、占いも信じてないんでな。
[tab]占ってもらうなら勝手にやってくれ。
[tab]あまり無駄遣いするなよ。
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]ちっ、あの甘ちゃんは
[tab]まだ逮捕にこだわるつもりか？
[tab]…ったく…石頭のコンコンチキが…
[wait][clear][end]

msg_21:
[color(yellow)]パオフゥ[color(white)]
[tab]どうした？
[tab]あの坊主の話を聞いてやるんじゃないのか？
[tab]先に占ってみる程、気を使った話でもねぇだろ？
[wait][clear][end]

msg_22:
[color(yellow)]パオフゥ[color(white)]
[tab][tatsuya]に聞いたんだが、「向こう側」じゃ、
[tab]あの占い師が噂屋をしていたそうだ。
[tab]やはり微妙に違うもんだな。
[wait][clear][end]

msg_23:
[color(yellow)]パオフゥ[color(white)]
[tab]ったく、あいつら、
[tab]くだらん話で盛り上がりやがって。
[tab]今はそれどころじゃねぇだろ。
[wait][clear][end]

msg_24:
[color(yellow)]パオフゥ[color(white)]
[tab]なさけねぇ話だが、
[tab]奴を見た時、とても勝てるって気がしなかった。
[tab]まるで…子供と大人だぜ…
[wait][clear][end]

msg_25:
[color(yellow)]南条[color(white)]
[tab]最近は、自ら決断する勇気が無く、
[tab]大切な選択さえ占いに委ねてしまう人が多いとか。
[tab]まさか…天野さんまでそうなのですか？
[wait][clear][end]

msg_26:
[color(yellow)]南条[color(white)]
[tab]云豹の役目は、布石となる数件の猟奇殺人事件と、
[tab]ＪＯＫＥＲ狩りでしょう。それらも今回の
[tab]情報流布を成功させる為のものだったとしたら…
[wait][clear][end]

msg_27:
[color(yellow)]南条[color(white)]
[tab]ふふん。
[tab][suou]巡査部長とＭｒ．パオフゥを足して二で割れば
[tab]ちょうど良いかも知れませんね。
[wait][clear][end]

msg_28:
[color(yellow)]南条[color(white)]
[tab]要石…か。
[tab]もっと望龍術に関して調べておくべきだったな…
[tab]そうすれば、他の封印は守れたかもしれん…
[wait][clear][end]

msg_29:
[color(yellow)]エリー[color(white)]
[tab]あの占い師さんの声…どこかおかしいですわ…
[tab]無理にか細い声にしているような…
[end]

msg_30:
[tab]…ま…まさか、実はおと…
[wait][clear][end]

msg_31:
[color(yellow)]エリー[color(white)]
[tab]新世塾によるものと思われる数件の事件。
[tab]これらが全て、例の情報流布を成功させるための
[tab]下準備だったとしたら…それが終わった今は…
[wait][clear][end]

msg_32:
[color(yellow)]エリー[color(white)]
[tab]Ｍｒ．ＫａｔｕｙａとＭｒ．Ｂａｏｆｕ。
[tab]足して二つに分ければ、
[tab]ちょうどよろしいんじゃないかしら。
[wait][clear][end]

msg_33:
[color(yellow)]エリー[color(white)]
[tab]Ｗａｎｇｌｏｎｇ千鶴…彼女はＭｒ．神取に
[tab]何かを見出していたのかも知れませんね。
[tab]一人の女として…
[wait][clear][end]

msg_34:
[color(yellow)][tatsuya][color(white)]
[tab]あの占い師…
[tab]「向こう側」じゃ噂屋をしていたが…
[tab]「こちら側」は違うのか。
[wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]俺はまた…
[tab]みんなを裏切った事になるのか…
[end]

msg_36:
[tab]済まない…一人にしてくれ。
[wait][clear][end]

msg_37:
[color(yellow)][tatsuya][color(white)]
[tab]うららさんが、
[tab]「向こう側」で何て呼ばれてたか聞くから…
[tab]正直に答えただけなのに…
[wait][clear][end]

msg_38:
[color(yellow)][tatsuya][color(white)]
[tab]奴を見た途端…
[tab]理性も何も消し飛んでしまった…
[tab]これほど…怒りを感じた事はないよ。
[wait][clear][end]

msg_39:
[color(yellow)]気の小さな男[color(white)]
[tab]ボクってネ…
[tab]気が小さいもんだから…ダメなんだよネ…
[tab]何がダメかって…決断するの苦手なんだよネ…
[wait][clear][color(yellow)]気の小さな男[color(white)]
[tab]だからいつもこうして、
[tab]占ってもらうのよネ…
[tab]誰だって失敗は怖いもんネ。
[wait][clear][end]

msg_40:
[color(yellow)]気の小さな男[color(white)]
[tab]あの…何なのかな？
[tab]ボクに何か用なのかな？
[tab]だったらサッサと言ってほしいのネ。
[wait][clear][end]

msg_41:
[tab]んで…何の用かな？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_42:
イケナカユウタ
[end]

msg_43:
[color(yellow)]気の小さな男[color(white)]
[tab]それって誰かな？
[tab]ボクの知らない名前だけれど…
[tab]誰かと勘違いしてるんでない？
[wait][clear][end]

msg_44:
[color(yellow)]気の小さな男[color(white)]
[tab]ドキッ！？
[tab]どうしてボクの名前しってるのかな？
[tab]もしかしてキミ、超能力な人？
[wait][clear][color(yellow)]イケナカ[tab]ユウタ[color(white)]
[tab]なになに、人捜し？
[tab]ボクの捜索願が出てたの？
[tab]こりゃまたビックリなのネ。
[wait][clear][color(yellow)]イケナカ[tab]ユウタ[color(white)]
[tab]まあ事情はわかったから、了解なのネ。
[tab]しらいしさんにはボクから連絡しておくし、
[tab]とりあえずありがとサンネ。
[wait][clear][end]

msg_45:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_46:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_47:
[tab]最近ここでワンロン占いを始めたらしいんだよネ。
[tab]しかも良く当たるって、既に評判なんだよネ。
[tab]だから来てみたんだけど…やっぱドキドキするネ。
[wait][clear][end]

msg_48:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_49:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_50:
[tab]あの占い師さん、何でもやっちゃうんだネ。
[tab]今度は相性占いを始めたんだってネ。
[tab]だけど、男と相性良くなってもボクは悲しいネ。
[wait][clear][end]

msg_51:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_52:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_53:
[tab]ここでは相性占いもよく当たると評判だよネ。
[tab]店主さんと相性良くしておくと、
[tab]ホントにオマケしてもらえたりするもんネ。
[wait][clear][end]

msg_54:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_55:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_56:
[tab]だけどネ、
[tab]相性が良くなったからって、
[tab]必ず見返りがあるとは限らないのよネ。
[wait][clear][end]

msg_57:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_58:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_59:
[tab]相性なんて気にしない人だっているし、
[tab]例えそれを感じていても、
[tab]表に出さない人もいるもんネ。
[wait][clear][end]

msg_60:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_61:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_62:
[tab]占い師さんがパワーアップしたみたいだネ。
[tab]どうパワーアップしたかって、相性占いだネ。
[tab]答えで出てくる人が増えたらしいんだよネ。
[wait][clear][end]

msg_63:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_64:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_65:
[tab]サトミタダシのおばちゃんが出てきたという人…
[tab]今がチャンスなのネ。
[tab]意外な人と会えるかもネ。
[wait][clear][end]

msg_66:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_67:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_68:
[tab]本当に、ここのワンロン占いは良く当たるのネ。
[tab]それで占ってもらったんだけど。
[tab]どうやらボクは結婚できないらしいのネ…
[wait][clear][end]

msg_69:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_70:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_71:
[tab]望龍術では、全１２匹いる龍が、
[tab]一箇所に集まると大惨事が起こると言ってるのネ。
[tab]世界が滅びるとしたら、きっとそれが原因だネ。
[wait][clear][end]

msg_72:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_73:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_74:
[tab]さ…さっきから地震が凄いのネ。
[tab]何度も何度も揺れてるのネ。
[tab]きっとこれもトリフネのせいなのネ！？
[wait][clear][end]

msg_75:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_76:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_77:
[tab]ト…トリフネ伝説は本当だったのネ！
[tab]これで１２匹の龍が集まれば…
[tab]世界は滅亡してしまうのネ！！
[wait][clear][end]

msg_78:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_79:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_80:
[tab]だ、だけど、何が起こるのかは知らないのネ…
[tab]も…もしかしてポールシフトでも起こるんじゃ…
[tab]た…大変なのネ！
[wait][clear][end]

msg_81:
[color(yellow)]気の小さな男[color(white)]
[end]

msg_82:
[color(yellow)]イケナカ[tab]ユウタ[color(white)]
[end]

msg_83:
[tab]りゅ、龍が消えちゃったのネ！！
[tab]それで、それで、空が真っ赤に…
[tab]こんな事、占いでも言ってなかったのよネ！
[wait][clear][end]

msg_84:
[color(yellow)]若い男[color(white)]
[tab]なぁ、新世塾って聞いたことある？
[tab]なんか、そう名乗ってる連中がいるんだってさ。
[tab]…あれ…でも前にも、そういう話なかったっけ？
[wait][clear][end]

msg_85:
[color(yellow)]若い男[color(white)]
[tab]廃工場の方に、
[tab]黒い車が何台も走って行ったけど…
[tab]あそこで何かあるのかな？
[wait][clear][end]

msg_86:
[color(yellow)]若い男[color(white)]
[tab]なんでも、
[tab]廃工場の中で銃撃戦があったんだってさ。
[tab]なんかこの街も物騒になってきたな…
[wait][clear][end]

msg_87:
[color(yellow)]若い男[color(white)]
[tab]穢れを持ってると、新世塾に殺されるって本当か？
[tab]だって、奴等この世界から、
[tab]穢れを消そうとしてんだろ？
[wait][clear][end]

msg_88:
[color(yellow)]若い男[color(white)]
[tab]トリフネにいれば、俺達死ぬことはないんだよな？
[tab]だ…だけど、やっぱり穢れていたら
[tab]いずれ新世塾の奴等に…
[wait][clear][end]

msg_89:
[color(yellow)]若い男[color(white)]
[tab]洗脳受けた連中、妙な事言ってたなぁ…
[tab]これは聞いていた新世界とは違う…とかなんとか。
[tab]何も聞いてないこっちは、よけいパニックだぜ。
[wait][clear][end]

msg_90:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]他にご用はあるかな？
[tab]何なりと打ち明けるが良い。
[sync][wait][clear][end]

msg_91:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ここは人生という迷宮に迷った者が訪れる場所。
[tab]暗澹たる未来に一筋の光明を放ち、進むべき道筋を
[tab]指し示す場所。妾はその番人、珠閒瑠ジニー。
[sync][wait][clear][end]

msg_92:
[color(yellow)]珠閒瑠ジニー[color(green)]
[tab]ハスキーボイスが、美人を連想させる占い師。
[tab]最近は、あまり当たらないと人気も低迷気味。
[tab]夜の街で、よく似た後姿を見かけたという噂も…[color(white)]
[sync][wait][clear][end]

msg_93:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ほう、汝、ここを訪れるは初めてか？
[tab]ならば安心してその胸中、打ち明けるがよい。
[tab]この水晶とカードが必ずや光明を齎そうぞ。
[sync][wait][clear][end]

msg_94:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお、先日の客人じゃな。
[tab]実は最近、妾がワンロン占いを始めたらしいと、
[tab]どこからともなく噂が流れてな。
[sync][wait][clear][end]

msg_95:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]仕方ないからそれに合わせてたら、
[tab]本当に占いが当たるようになったのじゃ！！
[tab]これぞ神の思し召し！[tab]超ラッキー！！
[sync][wait][clear][end]

msg_96:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]これからは妾の齎す答え全てが現実となろう！
[tab]ささ、今度は大丈夫じゃ。
[tab]安心してその胸中、打ち明けるがよい。
[sync][wait][clear][end]

msg_97:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うーむ…
[tab]妾は相性占いもしておったのか？
[tab]いや…していたような気もするが…
[sync][wait][clear][end]

msg_98:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ま…まあ、何事も挑戦じゃ。
[tab]ワンロン占いもそれで始めたようなものじゃしな。
[tab]では、気を取りなおして…
[sync][wait][clear][end]

msg_99:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]新たに相性占いを始めたぞよ。
[tab]汝が望むならば、汝と相性がピタリと合う人物を、
[tab]この水晶に映し出してみせよう。
[sync][wait][clear][end]

msg_100:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]最近、妾に関して妙な噂ばかり流れて困る。
[tab]今度は、妾がパワーアップしたそうじゃ…
[tab]パワーアップって…つまりどうすれば良いのじゃ。
[sync][wait][clear][end]

msg_101:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]まぁ…やってやれない事はなし…
[tab]ワンロン占いもそうだったしな。
[tab]ここは開き直るしかないか。
[sync][wait][clear][end]

msg_102:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]新たに始めた相性占い。日頃の修行が実を結び、
[tab]更に多くの相性を感じ取れるようになったぞ。
[tab]百聞は一見にしかず。まずは試してみるがよい。
[sync][wait][clear][end]

msg_103:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]よく来たな。

[sync][wait][clear][end]

msg_104:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]して、本日はいかなる用件じゃ？
[choice(4)]占い
話を聞く
用は無い
店の外に出る
[end_choice][clear][end]

msg_105:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear][end]

msg_106:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]して、本日はいかなる用件じゃ？
[choice(5)]占い
相性占い
話を聞く
用は無い
店の外に出る
[end_choice][clear][end]

msg_107:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear][end]

msg_108:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]他にご用はあるかな？
[tab]何なりと打ち明けるが良い。
[sync][wait][clear][end]

msg_109:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ぶつぶつ…やはりこれからはワンロン占いかしら…
[tab]あれの方がよく当たるって噂なのよね…ぶつぶつ。
[tab]占い、変えようかしら…ぶつぶつ。
[sync][wait][clear][end]

msg_110:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]また占いが当たるようになってなによりじゃ。
[tab]これを機に新しい占いに挑戦してみるか…
[tab]うーむ…やはり占いと言えば…
[sync][wait][clear][end]

msg_111:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]講演会で人間を洗脳してるというのは真の事か？
[tab]もしそうなら、あのワンロン千鶴も、
[tab]新世塾の仲間という事にはならぬか？
[sync][wait][clear][end]

msg_112:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]望龍術といえばワンロン占いの原形…
[tab]占いの術に世界を滅ぼすほどの力が
[tab]あるのじゃろうか…
[sync][wait][clear][end]

msg_113:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ん…？[tab]あの赤き少年…
[tab]しばらく前に夢に出てきた少年と瓜二つじゃ…
[tab]これは…何か運命的なものを感じるのぉ。
[sync][wait][clear][end]

msg_114:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]わ…妾は高い所が苦手での…
[tab]街が空を飛んでいると思うと…
[tab]どうもお尻のあたりがスースーして…
[sync][wait][clear][end]

msg_115:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]外で何があったのじゃ？
[tab]妾はずっとここにいたので解らぬのじゃが…
[tab]龍がどうかしたのか？
[sync][wait][clear][end]

msg_116:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]済まんな…実はワンロン占いが流行り出してから、
[tab]なぜか妾の占いは
[tab]当たらなくなってしまったのじゃ。
[sync][wait][clear][end]

msg_117:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]鳴かず飛ばずの占い師…
[tab]これでは閑古鳥さえ近づかん…
[tab]なんとかせねば…
[sync][wait][clear][end]

msg_118:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]己が道を見失いし時は、
[tab]いつでも来るが良い。
[sync][wait][clear][end]

msg_119:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ちなみに妾の相性占いはコンタクトとは無関係。
[tab]コマンドが変化したりはせんぞ。
[tab]誤解せぬようにな。
[sync][wait][clear][end]

msg_120:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ちなみにパワーアップしても、
[tab]妾の相性占いはコンタクトとは無関係じゃ。
[tab]コマンドが変化したりはせんぞ。
[sync][wait][clear][end]

msg_121:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]では、占ってしんぜよう。
[tab]アムアムアム…ロイスキャロルプレミアム…
[tab]水晶よ、この者の未来を映し出すがよい…
[sync][wait][clear][end]

msg_122:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…なんと、実はソナタ男じゃな？
[tab]その服装も髪型も全てはカモフラージュ、
[tab]もてぬ腹癒せに、他の男を騙して……
[sync][wait][clear][end]

msg_123:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear][end]

msg_124:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……違うわよね…
[tab]そんな訳無いわよね…
[sync][wait][clear][end]

msg_125:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]なるほどな。
[tab]ソナタには二人の子供がいるな。
[tab]一人は元気溌剌、小学一年生！！
[sync][wait][clear][end]

msg_126:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear][end]

msg_127:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……いないのね…
[tab]…独身なのよねきっと…
[tab]……分かってるわよそんなの…
[sync][wait][clear][end]

msg_128:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]なるほど…どうやらソナタ、異国の民か？
[tab]アメリカ…いや、フランス…
[tab]そう、フランス人じゃ！！
[sync][wait][clear][end]

msg_129:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear][end]

msg_130:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…日本人よね。
[tab]…日本人なんでしょ？[tab]やっぱり。
[tab]……分かってるわよそんなの…
[sync][wait][clear][end]

msg_131:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]むむっ、ソナタ…
[tab]実は胸にパットを入れておるな！！
[tab]偽ナイスバデーで、男の視線を我が物に…
[sync][wait][clear][end]

msg_132:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear][end]

msg_133:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]じょ…冗談じゃ。
[tab]ホンキにするでない。
[tab]ほ…本物じゃな…やっぱり。
[sync][wait][clear][end]

msg_134:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ほう…ソナタ、教師を生業としているな？
[tab]…たぶん、英語の教師じゃろう。
[tab]そう顔に書いてある。
[sync][wait][clear][end]

msg_135:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear][end]

msg_136:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…ちがう？[tab]…ちがってた？
[tab]…え？[tab]雑誌記者…
[tab]ハハ…全然違うわね…
[sync][wait][clear][end]

msg_137:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]よかろう。
[tab]では代金として３０００円頂くが…
[sync][wait][clear][end]

msg_138:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]それでも、かまわぬか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_139:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]むむ…だが、代金が足らぬようじゃぞ。
[tab]阿弥陀の光も金次第。地獄の沙汰も金次第。
[tab]出直して来るがよい。
[sync][wait][clear][end]

msg_140:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]いや待て。まだ汝は[end]

msg_141:
光龍[end]

msg_142:
黒龍[end]

msg_143:
黄龍[end]

msg_144:
青龍[end]

msg_145:
赤龍[end]

msg_146:
銀龍[end]

msg_147:
の呪縛から逃れておらぬ。
[tab]まずはその因果から抜け出し、
[tab]真の己を取り戻すことが肝要じゃ。
[sync][wait][clear][end]

msg_148:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]では、占ってしんぜよう。
[tab]ワンロン、ワンロン、ワンローン！！
[end]

msg_149:
[tab]ローン、ローーーーン！！！
[sync][wait][clear][end]

msg_150:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお…光り輝く息吹を感じる…光龍じゃ…
[tab]汝しばしの間、多くの経験を積むことができようが
[tab]金運は下がりぎみ。節約を心がけよ。
[sync][wait][clear][end]

msg_151:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお…地の底を駆け巡る黒き気配…黒龍か…
[tab]汝しばしの間、金銭面では裕福となれようが、
[tab]大した経験は積めぬようじゃ。自重いたせ。
[sync][wait][clear][end]

msg_152:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお…この活発な龍は…黄龍か…
[tab]汝、しばし幸運に恵まれ、ラッキー続きじゃ。
[tab]今のうちに賭け事に走るのも良いじゃろう。
[sync][wait][clear][end]

msg_153:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うむ…この潮流の如き静かな流動…青龍か…
[tab]汝しばしの間、他者の意外な面を見る事となろう。
[tab]弱気は強気へ、皆性格が対極へ流れるはずじゃ。
[sync][wait][clear][end]

msg_154:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うむ…情熱に染まった真紅の奔流…赤龍…
[tab]汝とその仲間、しばしの間、興奮ぎみとなり、
[tab]勝利した後には、快哉を叫ぶ事となろう。
[sync][wait][clear][end]

msg_155:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うむ…真意を込めた白き輝き…銀龍…
[tab]汝しばしの間、口下手となり、
[tab]他者との交渉事も梃子摺る事となろう。
[sync][wait][clear][end]

msg_156:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]さて…他にご用はあるかな？
[tab]何なりと打ち明けるが良い。
[choice(4)]占い
話を聞く
用は無い
店の外に出る
[end_choice][clear][end]

msg_157:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear][end]

msg_158:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]して、本日はいかなる用件じゃ？
[choice(5)]占い
相性占い
話を聞く
用は無い
店の外に出る
[end_choice][clear][end]

msg_159:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear][end]

msg_160:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]よかろう。
[tab]では代金として５０００円頂くが…
[sync][wait][clear][end]

msg_161:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]それでも、かまわぬか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_162:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]むむ…だが、代金が足らぬようじゃぞ。
[tab]阿弥陀の光も金次第。地獄の沙汰も金次第。
[tab]出直して来るがよい。
[sync][wait][clear][end]

msg_163:
えらんで
[choice(5)][color(pink)]ワンロン始めた[color(white)]
[color(blue)]相性占い広めた[color(white)]
[color(green)]パワーアップ[color(white)]
[color(orange)]お金[color(white)]
[color(gray)]終了[color(white)]
[end_choice][clear][end]

msg_164:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]占い
[if_all(MBIT_HI_GYPAISHO1)]相性占い
やめる
[end_choice][clear][end]

msg_165:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]「占い」についての説明じゃな。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]当店で「占い」を選択すれば
[tab]妾が汝らの未来を占ってしんぜよう。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]占いの結果は、良い効果を得ることもあれば、
[tab]逆に悪い効果が出る場合もある。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]なお、一度占うと、その効果が切れるまで、
[tab]再度未来を占うことはできんぞ。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]未来を知るかの選択は汝ら次第だ。
[tab]何が見えても妾は責任は負わんからな。
[wait][clear][end]

msg_166:
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]「相性占い」の説明じゃな。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]当店で「相性占い」を選択すると
[tab]妾の水晶がいくつか汝に質問を投げかける。
[tab]汝はそれに正直に答えるのじゃ。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]さすれば、汝と相性がぴったりの人物を
[tab]この水晶が示してくれるぞよ。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…その後、示された相手に会えば
[tab]何か良いことがあるかも知れぬな。
[wait][clear][end]
