
msg_0:
[color(pink)]このままじゃハングする[color(white)][wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]サイコセラピーって…マーヤ、悩みでもあんの？
[tab]たぁー…っく水臭いなぁ。
[tab]そういう時は私に一言相談してくれれば…
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]え？[tab]違うの？[tab]ハ…ハハハ…そうだよねぇ。
[tab]アンタは何でもレッツ・ポジティブシンキング…
[tab]だもんねぇ。心配するだけ野暮か。
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]私…何のために今まで拳を鍛えてきたのかな…
[tab]あの牧村に恨みの鉄拳を食らわす事だけ考えて、
[tab]必死にサンドバッグ叩いてたけど…
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]結局それはマーヤに向いちゃって、
[tab]肝心の牧村は…顔見たら気が抜けちゃって…
[tab]ホント、私は馬鹿だ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]ところでマーヤ、私、前にもＧＯＬＤの中で
[tab]牧村に会ったことあるんじゃないかな？
[tab]なんかそんな気がすんのよ。初めての筈だけど…
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]なんかこの内装…
[tab]落ち着くって言うより、照れくさいなぁ…
[tab]私も大人になっちゃったってことか。
[wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]あれ？[tab]そういえば麻希ちゃんは？
[tab]どこ行ったんだろ…今日はお休み？
[end]

msg_8:
[tab]ハッ、まさかＪＯＫＥＲ狩りにあって！？
[wait][clear][end]

msg_9:
[color(yellow)]うらら[color(white)]
[tab]…って、んな訳ないか。
[tab]私じゃあるまいし。
[wait][clear][end]

msg_10:
[color(yellow)]うらら[color(white)]
[tab]なんか南条君達は、
[tab]私達とは違う世界で戦ってる気がするんだ。
[tab]昔の因縁…かな。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]ん…？[tab]共鳴…
[tab]ペルソナの共鳴がする。
[tab]ここに僕達以外のペルソナ使いがいるぞ。
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]将来の為に今からカウンセラーの勉強か…
[tab]あの若さで確固たる志を持ち邁進できるとは、
[tab]実に素晴らしい。
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]アイツにも少しは見習って欲しいものだ。
[tab]爪のアカでも貰って帰るか…
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]既に警察にも、ＪＯＫＥＲ事件と思われる通報が
[tab]多数寄せられているようだ。
[tab]呪いの波紋は確実に、この街に広がりつつある。
[wait][clear][end]

msg_15:
[color(yellow)]克哉[color(white)]
[tab]カウンセリングか…
[tab]思い切ってここに[tatsuya]を連れてくるか。
[tab]少しは何を考えているか分かるかもしれん。
[wait][clear][end]

msg_16:
[color(yellow)]克哉[color(white)]
[tab]これほど大々的に講演会を開けば、
[tab]当然そこに我々が来ることも予想しているはずだ。
[tab]佐々木[tab]銀次は捨て駒かも知れんな…
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]あの女がそうなのか…
[tab]フッ…やはり人間、見かけじゃ分からねえもんだ。
[tab]あの華奢な体で、とんでもねぇ力を秘めてやがる。
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]ペルソナって奴は気まぐれでな。
[tab]強い味方ともなれば、最悪の敵にもなる。
[tab]…よく似てないか？[tab]自分自身のそれとよ。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]…にしてもペルソナ使いの多い街だな、ここは。
[tab]ペルソナ嫌いの俺としちゃ、たまんねぇぜ。
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]竜蔵の行方は一向に掴めないままだ。
[tab]講演会に出てくるとも思えんしな…
[tab]今ごろどこで何の準備をしているやら…
[wait][clear][end]

msg_21:
[color(yellow)]南条[color(white)]
[tab]そうか…園村は今ここで働いているのか…
[tab]…良くも悪くも、あいつらしい選択かもしれん。
[tab]強くなったものだ…
[wait][clear][end]

msg_22:
[color(yellow)]南条[color(white)]
[tab]ん？
[tab]そう言えば、桐島はこの事を知っていたのか？
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]ここで昔の学友が働いているはずなんだが…
[tab]今日は休みのようだ。
[wait][clear][end]

msg_24:
[color(yellow)]南条[color(white)]
[tab]奴は本気で栄吉を殺すつもりだったのか…
[tab]確かに、[tatsuya]という少年が割って入らねば、
[tab]栄吉は殺されていた…しかし…
[wait][clear][end]

msg_25:
[color(yellow)]エリー[color(white)]
[tab]…Ｍａｋｉ…もう行ったようですわね…
[tab]Ｋｅｉには申し訳ないけど、
[tab]やはりこのままではいけない。
[wait][clear][end]

msg_26:
[color(yellow)]エリー[color(white)]
[tab]本当の決着は、彼女たち自身でつけないと。
[tab]それは…ＫｅｉがＭｒ．神取を追う理由と同じ。
[tab]でもＭｒ．神取は本当に生きているのかしら。
[wait][clear][end]

msg_27:
[color(yellow)]エリー[color(white)]
[tab]やはりＭｒ．神取は生きていたのですね。
[tab]だけど、彼が同じ過ちを犯すとは私には思えない。
[tab]もうセベクスキャンダルは終わったのだから…
[wait][clear][end]

msg_28:
[color(yellow)]牧村[color(white)]
[tab]おや…あのショートヘアーの娘、いいなぁ…
[tab]こんな所に、あんなイケた娘がいたなんて！
[tab]よし、次はあの娘に…[wait][clear][end]

msg_29:
[color(yellow)]牧村[color(white)]
[tab]…生きて戻れたらの話だけど…
[wait][clear][end]

msg_30:
[color(yellow)]黎子さん[color(white)]
[tab]こんにちは。柊サイコセラピーへようこそ。
[tab]私は、ここのカウンセラーで黎子といいます。
[tab]よろしくお願いします。
[wait][clear][end]

msg_31:
[color(yellow)]黎子さん[color(white)]
[tab]ところで…どこかでお会いした事がありませんか？
[tab]こんなに親近感を覚えるなんて…
[tab]きっと余程相性が良いのでしょうね。
[wait][clear][end]

msg_32:
[color(yellow)]黎子さん[color(white)]
[tab]あら、こんにちは。

[wait][clear][end]

msg_33:
[color(yellow)]黎子さん[color(white)]
[tab]あなたって、私の友人か誰かに似ているのかしら…
[tab]こんなに親近感を覚える相手は初めて…
[tab]フフ、きっと余程相性がいいのね。
[wait][clear][end]

msg_34:
[color(yellow)]黎子さん[color(white)]
[tab]今日はどうしたのかしら？
[choice(4)]回復してもらう
話をしたい
悩みはない
店の外に出る
[end_choice][clear][end]

msg_35:
[color(yellow)]黎子さん[color(white)]
[tab]何について聞きたいのかしら？
[choice(3)]世間話をする
回復の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_36:
[color(yellow)]黎子さん[color(white)]
[tab]他には何かないかしら？
[wait][clear][end]

msg_37:
[color(yellow)]黎子さん[color(white)]
[tab]麻希さんは本当に良く手伝ってくれてるわ。
[tab]あれだけ献身的に患者さんと接する事ができるなら
[tab]プロのカウンセラーとして十分やっていける。
[wait][clear][end]

msg_38:
[color(yellow)]黎子さん[color(white)]
[tab]もしかしたら、患者さん達に
[tab]昔の自分を重ね見ているのかも知れないわね。
[tab]優しすぎるのよ、彼女は。
[wait][clear][end]

msg_39:
[color(yellow)]黎子さん[color(white)]
[tab]あなたもＪＯＫＥＲ呪いは知ってるでしょ？
[tab]最初はふざけ半分だったかも知れないけど、
[tab]今は明らかにそれと関係する殺人が起きている。
[wait][clear][color(yellow)]黎子さん[color(white)]
[tab]それでも、呪いをする人は減らない。
[tab]むしろ確信を持って使う人まで出てきた。
[tab]悲しいことね。
[wait][clear][end]

msg_40:
[color(yellow)]黎子さん[color(white)]
[tab]ワンロン千鶴…どこか危険な感じがします。
[tab]決して間違った事を言っているとは思わないけど、
[tab]あれほど脅迫的な暗示をしなくても…
[wait][clear][color(yellow)]黎子さん[color(white)]
[tab]人間なら誰でも妬みや嫉みを持っているわ。
[tab]ＪＯＫＥＲ呪いをした人だってきっと沢山いる。
[tab]その人達が、今どんな気持ちでいるか…
[wait][clear][end]

msg_41:
[color(yellow)]黎子さん[color(white)]
[tab]最近街中で、普通の人が突然暴れ出す、
[tab]奇妙な事件が起きているようです。
[tab]ストレスの影響も考えられるけど…
[wait][clear][color(yellow)]黎子さん[color(white)]
[tab]でもこれほど頻繁に起きるのはへんね…
[tab]何か、外的要因が関係しているとしか…
[tab]でもそうなら、もっと被害は出ているはずだし…
[wait][clear][end]

msg_42:
[color(yellow)]黎子さん[color(white)]
[tab]今日は、アルバイトの子が、急用でお休みなの。
[tab]だけどこんなこと珍しいわね…
[tab]何かあったのかしら。
[wait][clear][end]

msg_43:
[color(yellow)]黎子さん[color(white)]
[tab]園村さんなら、今日はお休みですよ。
[tab]なんでも大切な用事ができたからって。
[tab]ごめんなさい、詳しい事は聞いていないの。
[wait][clear][end]

msg_44:
[color(yellow)]黎子さん[color(white)]
[tab]園村さん…どうしたのかしら。
[tab]なんだか思いつめた顔をして。
[tab]私が相談に乗ってあげられると良いのだけど…
[wait][clear][end]

msg_45:
[color(yellow)]黎子さん[color(white)]
[tab]誰しも自分の心が一番分からないものなの。
[tab]だから、困った時はいつでもいらっしゃい。
[tab]相談にのるわ。
[wait][clear][end]

msg_46:
[color(yellow)]麻希[color(white)]
[tab]こんにちは。
[tab]柊サイコセラピーへ、ようこ…
[end]

msg_47:
[tab]…あれ？
[wait][clear][end]

msg_48:
[color(yellow)]麻希[color(white)]
[tab]あの…もしかしてペルソナが使えるんじゃ…
[tab]それに、この共鳴…ゆきの？
[tab]あの…ゆきの知ってるんですか？
[wait][clear][end]

msg_49:
[tab]黛[tab]ゆきの…知ってますよね？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_50:
[color(yellow)]麻希[color(white)]
[tab]やっぱり！[tab]あなたの共鳴の中に、
[tab]ゆきのの気配があったの！
[tab]だからもしかして、と思って。
[wait][clear][end]

msg_51:
[color(yellow)]麻希[color(white)]
[tab]ふふふっ、嘘ついてもダーメ。
[tab]あなたの共鳴の中には、彼女の気配があるもの。
[tab]…う～ん、もしかして職場の同僚とか。
[wait][clear][end]

msg_52:
[color(yellow)]麻希[color(white)]
[tab]あ、ゴメンなさい、一方的に喋っちゃって。
[end]

msg_53:
[tab]わたしは園村[tab]麻希。ゆきのは大親友なの。
[tab]しかも！[tab]あなたと同じ、ペルソナ使いよ。[wait][clear][end]

msg_54:
[color(yellow)]園村[tab]麻希（そのむら[tab]まき）[color(green)]
[tab]カウンセラーを目指す、ゆきのの親友。
[tab]どうやら、過去に罪の意識を感じているらしい。
[tab]高校時代に、ペルソナ使いとして覚醒している。[color(white)]
[wait][clear][end]

msg_55:
[color(yellow)]麻希[color(white)]
[tab]天野…舞耶…さん？[tab]天野さんね、うん、覚えた！
[end]

msg_56:
[tab]ゆきのの友達なら、わたしにとっても友達よ。
[tab]どうぞよろしく！
[wait][clear][color(yellow)]麻希[color(white)]
[tab]わたしはここで、カウンセリングの勉強も兼ねて
[tab]黎子先生の手伝いをしてるの。
[end]

msg_57:
[tab]今度はわたしが、みんなの力になりたいから…
[wait][clear][end]

msg_58:
[color(yellow)]麻希[color(white)]
[tab]だから、いつでもここにいるわ。
[tab]何か困った事があったら、何でも相談して。
[tab]力になるからね。
[wait][clear][end]

msg_59:
[color(yellow)]麻希[color(white)]
[tab]黎子先生はその道では有名なカウンセラーなの。
[tab]先生にかかれば、怪我や病気もすぐ治るって
[tab]噂まで流れたんだから。
[wait][clear][color(yellow)]麻希[color(white)]
[tab]もちろん、怪我の治療まではしてないんだけど、
[tab]きっとそう思える程、心が楽になったって事よね。
[tab]やっぱり黎子先生ってスゴイわ。
[wait][clear][end]

msg_60:
[color(yellow)]麻希[color(white)]
[tab]最近、街でペルソナの共鳴を感じることが多いの。
[tab]どれも狂暴で危険な気配を出していた…
[tab]この街で何かが起ころうとしている…
[wait][clear][color(yellow)]麻希[color(white)]
[tab]なんでだろう？
[tab]前にもこんな事があったような気がする…
[tab]だから分かるの。これが何かの前兆だって。
[wait][clear][end]

msg_61:
[color(yellow)]麻希[color(white)]
[tab]ＪＯＫＥＲ事件が頻発するにつれて、
[tab]街で感じるペルソナの共鳴も多くなってきた。
[tab]もしかしてＪＯＫＥＲってペルソナなんじゃ…
[wait][clear][end]

msg_62:
[color(yellow)]麻希[color(white)]
[tab]神取さんは生きていた…でも何で新世塾の幹部に…
[tab]まさか…あの人も操られて…
[tab]それとも…
[wait][clear][end]

msg_63:
[color(yellow)]若い男[color(white)]
[tab]アンタ、自分の記憶を消したいと思った事ないか？
[tab]誰だって思い出したくない嫌な記憶ってあるだろ？
[tab]それを消したいとは思わないか？
[wait][clear][color(yellow)]若い男[color(white)]
[tab]過ぎてしまった事はどうしようも無い。
[tab]なのに…心に残った傷はいつまでも俺を苦しめる…
[tab]そんなの辛いじゃないか…
[wait][clear][end]

msg_64:
[color(yellow)]若い男[color(white)]
[tab]まだ俺に用なのか？
[tab]放っておいてくれよ…
[tab]人と関わると、ろくな事はないんだ…
[wait][clear][end]

msg_65:
[tab]俺なんかに何の用だよ？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_66:
サイトウジュン
[end]

msg_67:
[color(yellow)]若い男[color(white)]
[tab]え？[tab]そりゃ誰の事だい？
[tab]俺はそんな名前じゃない。
[tab]まぁ…名前なんざどうでもいいけどな。
[wait][clear][end]

msg_68:
[color(yellow)]若い男[color(white)]
[tab]…っ！？[tab]俺の事を知っているのか？
[tab]俺はアンタなんか知らないぜ？
[tab]アンタ、何者なんだ？
[wait][clear][end]

msg_69:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[tab]俺の…捜索願が…
[tab]そうか…アイツが出したんだな…
[tab]余計なことしやがって…
[wait][clear][color(yellow)]サイトウ[tab]ジュン[color(white)]
[tab]取り敢えず礼は言っとくよ。
[tab]そのマンサーチャーとやらにも連絡しておく。
[tab]だからもう、放っておいてくれ…
[wait][clear][end]

msg_70:
[color(yellow)]若い男[color(white)]
[end]

msg_71:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_72:
[tab]ここの内装、かわってるだろ？
[tab]童話には大人の心を和ませる効果があるとかで、
[tab]それを取り入れてこうなったそうだ…
[wait][clear][end]

msg_73:
[color(yellow)]若い男[color(white)]
[end]

msg_74:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_75:
[tab]ま、あまり俺には効果が無いようだけど…
[tab]…ああ、誰か俺の記憶を消してくれないかな…
[tab]この胸につかえた罪悪感…消してくれないかな…
[wait][clear][end]

msg_76:
[color(yellow)]若い男[color(white)]
[end]

msg_77:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_78:
[tab]誰にでも失敗はある。だけど…
[tab]誰もがその失敗から立ち直れるとは限らないだろ？
[tab]俺がそうさ…いつまでも過去の失敗を悔んでる…
[wait][clear][end]

msg_79:
[color(yellow)]若い男[color(white)]
[end]

msg_80:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_81:
[tab]情けないだろ？[tab]カッコ悪いよな…
[tab]だけど駄目なんだよ…
[tab]いつも突然…たまらなく辛くなるんだ。
[wait][clear][end]

msg_82:
[color(yellow)]若い男[color(white)]
[end]

msg_83:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_84:
[tab]それが怖くて…そうなるのが嫌で…
[tab]俺はここに逃げ込んだんだ。
[tab]藁をも縋る思いで…
[wait][clear][end]

msg_85:
[color(yellow)]若い男[color(white)]
[end]

msg_86:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_87:
[tab]俺の願いはただ一つ。
[tab]過去の記憶を消すことだ…
[tab]それが無ければ…またやり直せる。
[wait][clear][end]

msg_88:
[color(yellow)]若い男[color(white)]
[end]

msg_89:
[color(yellow)]サイトウ[tab]ジュン[color(white)]
[end]

msg_90:
[tab]あのテレビ見たか？
[tab]俺はＪＯＫＥＲ呪いなんてしてないけど…
[tab]誰よりも汚れている…いつかは俺も…
[wait][clear][end]

msg_91:
[color(yellow)]やつれた男[color(white)]
[tab]ブツブツブツ…俺…見たんだ…
[tab]ブツブツ…目の前で人が…
[tab]あれが…ＪＯＫＥＲなのか…ブツブツ…
[sync][wait][clear][end]

msg_92:
[color(yellow)]やつれた男[color(white)]
[tab]ブツブツブツ…ＪＯＫＥＲだ…
[tab]みんなＪＯＫＥＲになってしまう…ブツブツ…
[tab]ブツブツ…ＪＯＫＥＲが…殺しに来る…
[sync][wait][clear][end]

msg_93:
[color(yellow)]黎子さん[color(white)]
[tab]ふふ…でもあなたは心身ともに健康みたいよ。
[tab]また、辛くなったらいつでもいらっしゃい。
[tab]私はずっと、ここで待ってるから…[wait][clear][end]

msg_94:
[color(yellow)]黎子さん[color(white)]
[tab]分かったわ。
[tab]でも、カウンセリングの料金として、
[tab]３０００円ほどかかるんだけど…[wait][clear][end]

msg_95:
[color(yellow)]黎子さん[color(white)]
[tab]一応、治療代は３０００円なんだけど…
[tab]フフ…そうね。
[tab]あなたなら１５００円でいいわ。
[wait][clear][end]

msg_96:
[color(yellow)]黎子さん[color(white)]
[tab]どうかしら？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_97:
[color(green)][tab]舞耶達は回復した。[color(white)][wait][clear][end]

msg_98:
[color(yellow)]黎子さん[color(white)]
[tab]あら…でもお金が足りないみたいね…
[tab]ごめんなさい。[wait][clear][end]

msg_99:
[color(yellow)]黎子さん[color(white)]
[tab]他には何かないかしら？
[choice(4)]回復してもらう
話をしたい
悩みはない
店の外に出る
[end_choice][clear][end]

msg_100:
[color(yellow)]黎子さん[color(white)]
[tab]何について聞きたいのかしら？
[choice(3)]世間話をする
回復の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_101:
[color(yellow)]黎子さん[color(white)]
[tab]あなたは他人の目を気にしすぎてないかしら？
[tab]だけど相手も、あなたの目を気にしているのよ。
[tab]だから…プレッシャーを感じる必要は無いわ。
[wait][clear][end]

msg_102:
[color(yellow)]黎子さん[color(white)]
[tab]人は誰でも、自分の事が一番分からないの。
[tab]だから、あなたが自分に抱いているイメージが
[tab]あなたの全てでは決してないのよ。
[wait][clear][end]

msg_103:
[color(yellow)]黎子さん[color(white)]
[tab]他人を受け入れるのは難しいものね。
[tab]だけど、自分の良さを受け入れるのは、
[tab]もっと難しいものなのよ。
[wait][clear][end]

msg_104:
[color(yellow)]黎子さん[color(white)]
[tab]今あなたを追い込んでいる物は何なのかしら？
[tab]外の事象に、あなたを傷つける力はないわ。
[tab]あなたを傷つけられるのは、あなただけなのよ。
[wait][clear][end]

msg_105:
[color(yellow)]黎子さん[color(white)]
[tab]人は大人になるにつれ、
[tab]プライドという名の心の壁を作ってしまう。
[tab]人に助けを求めることも、勇気なのよ。
[wait][clear][end]

msg_106:
[color(yellow)]黎子さん[color(white)]
[tab]「回復」についてね。
[wait][clear][color(yellow)]黎子さん[color(white)]
[tab]当店で「回復してもらう」を選んでくれれば
[tab]貴方たちの心をケアすることで「ＨＰ」と「ＳＰ」そして
[tab]「猛毒」などのステータス異常も回復してあげるわ。
[wait][clear][color(yellow)]黎子さん[color(white)]
[tab]当然料金はいただくけど、全員まとめて診てあげるし
[tab]薬に頼るよりはお安いと思うわ。
[wait][clear][end]
