
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]穢れ祓いを受けてる人ってさぁ、
[tab]自分が穢れてるって思ってるのかねぇ？
[tab]何を根拠にそう思うんだろ？
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]他の人はみんな大騒ぎしてるってのに、
[tab]ここのギャルソンってば、落ち着いてるよね？
[tab]…やっぱ出来る男は違うねぇ。
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab][suou]さん、弟さんの為に貯金してたんでしょ。
[tab]一体いくら貯めたのかねぇ？
[tab]…いくら貯めたの金ぇ？[tab]アハハ…[delay(15)]はぁ～
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab][tatsuya]君、結構抱え込むタイプ？
[tab]私だったら全部打ち明けて、
[tab]みんなに協力してもらうけどなぁ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]あの須藤[tab]竜蔵ってば、自分の息子まで
[tab]ＪＯＫＥＲとして利用したんだよね？
[tab]まったく、なんて親だ！！
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]あそこの二人、ノンキよねぇ～
[tab]あんなの見ちゃうとさぁ、
[tab]闘ってるのが馬鹿馬鹿しくなるわよ！
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]なにも悪い事はしていなくても、
[tab]警察官を見ると緊張するという人がいる。
[tab]やはり皆、何かしら後ろめたい所があるのか？
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]絶えず冷静さを失わない…
[tab]地獄のギャルソンという通り名も、
[tab]元フランス外人部隊という噂も伊達ではないな。
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]プライベートな事を人前で公表するとは…
[tab]パオフゥ！[tab]名誉毀損だぞ！！
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]兄である僕にも相談出来なかったと言うのか？
[tab]…馬鹿な…本当に馬鹿な弟だ。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]目的の為なら手段を選ばぬ男。
[tab]須藤[tab]竜蔵は本当に強い人なのかも知れないな。
[tab]…僕にはとても真似出来そうにない。
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]まだ何も終わってはいないが、
[tab]人々の心に余裕が戻って来た事は非常にうれしい。
[tab]それだけで、自分の行動が報われた気がするよ。
[wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]人には罪の意識ってものがあるからな。
[tab]身に覚えは無くても、穢れというものに対する
[tab]恐怖感があるんだろ？
[wait][clear][end]

msg_14:
[color(yellow)]パオフゥ[color(white)]
[tab]おい天野、ちょっと想像してみろ。
[tab]慌てふためくギャルソン副島…どうだ？
[tab]ジタバタしてんだぜ？[tab]なんかおかしいだろ？
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]彼は貯金してますよ～で３年以下の懲役、
[tab]もしくは禁錮、または５０万円以下の罰金かよ？
[tab]…その前にそんなんで傷付いたのか、[suou]？
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]あの野郎、ガキのくせに大人の振りしやがって。
[tab]兄貴ってのは弟の面倒を見る為にいるんだぜ？
[tab]…ったく、少しは兄貴を立ててやれよな。
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]息子があんなだったからな…
[tab]親父の方もイッちまってるんじゃねぇか？
[tab]そんなら…この馬鹿げた計画も納得できるだろ？
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]人々の心に余裕か…悪くねぇな。
[tab]しかし皆を安心させているのは俺達じゃねぇだろ？
[tab]これは実際に皆を助けてる桐島達の手柄だな。
[wait][clear][end]

msg_19:
[color(yellow)]南条[color(white)]
[tab]穢れ祓いの講演会に参加するのは、
[tab]自らの罪の意識を軽減する為ですか。
[tab]…免罪符を買うようなものですね。
[wait][clear][end]

msg_20:
[color(yellow)]南条[color(white)]
[tab]あのギャルソンの落ち着き、噂のせいだけとは
[tab]とても思えませんね。恐らくは、彼のプロ意識…
[tab]接客のプロとしての意識が関係しているのでは？
[wait][clear][end]

msg_21:
[color(yellow)]南条[color(white)]
[tab]俺は[suou]巡査部長の身辺を調べただけです。
[tab]それもＭｒ．パオフゥからの依頼があった為…
[tab]別に貯金の事だけを調べた訳じゃないですよ？
[wait][clear][end]

msg_22:
[color(yellow)]エリー[color(white)]
[tab]穢れ祓いの講演会に参加するのは、
[tab]自らの罪の意識を軽減する為なのですね。
[tab]…免罪符を買うようなものですわ。
[wait][clear][end]

msg_23:
[color(yellow)]エリー[color(white)]
[tab]出来る人とは、自分の能力をＡｐｐｅａｌ出来る、
[tab]積極的な人の事を言うのではないのですか？
[tab]Ｈｍｍ…日本の感覚、まだ理解できませんわ。
[wait][clear][end]

msg_24:
[color(yellow)]エリー[color(white)]
[tab]ウフフフ、Ｍｒ．Ｂａｏｆｕも人が悪いですよね。
[tab]人のＰｒｉｖａｔｅを探るなんて。
[tab]…それを調べたＫｅｉは、暇なのでしょうね。
[wait][clear][end]

msg_25:
[color(yellow)][tatsuya][color(white)]
[tab]兄さ…[delay(30)]あの人が何をしていようと、
[tab]「向こう側」の俺には関係無い事だ。
[wait][clear][end]

msg_26:
[color(yellow)][tatsuya][color(white)]
[tab]自分の犯した過ち…償えるのは自分だけだろう？
[tab]だから、俺は一人を選んだ。
[tab]…それだけの事だ。
[wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]恐らく、全てはヤツの仕業…
[tab]だが、今は竜蔵を、神事を止めなければ！
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]ギンコ…栄吉…淳…
[tab]待っていてくれ…ケリは必ず…
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]栄吉…リサ…淳…
[tab]待っていてくれ…ケリは必ず…
[wait][clear][end]

msg_30:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]アハハッ、過去に囚われてちゃいけないのよ！
[tab]アイドルだった昔なんて忘れるの！
[tab]そう、芸能人だった過去なんてイミ無いもの！
[wait][clear][end]

msg_31:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]私には使命がある…皆の為にすべき事があるのよ！
[tab]そうだわ、私はその為に生まれて来たのね！？
[end]

msg_32:
[tab]レーッツ、ポジティブシンキング！！
[wait][clear][end]

msg_33:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]皆さん大丈夫です。全てを受け入れましょう。
[tab]ポールシフトなど恐れる必要はありません。
[tab]その先を見て…
[wait][clear][end]

msg_34:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]レッツ・ポジティブシンキングよ！！
[wait][clear][end]

msg_35:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]アハハッ、龍が来る…あなたにも見えるでしょう？
[tab]世界の浄化が始まるわ。そして私達は礎となる。
[tab]新世の礎となるの…
[wait][clear][end]

msg_36:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]レッツ・ポジティブシンキングよ！！
[wait][clear][end]

msg_37:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]りゅ、龍が消えた…新世はどうなったのですか？
[tab]世界の浄化は…ん！？
[wait][clear][end]

msg_38:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]レーッツ・ポジティブシンキング！
[tab]浄化は終わったのよ。きっと今が新世なのよ～！
[wait][clear][end]

msg_39:
[color(yellow)]キザな男[color(white)]
[tab]なんだいベイビー？
[tab]君も業界入りを夢見るコなのかい？
[tab]…なんなら僕が紹介してあげようか？
[wait][clear][end]

msg_40:
[color(yellow)]ＯＬ[color(white)]
[tab]この人の話、信じちゃダメよ。
[tab]業界人気取ってるけど、証拠も無いのよ？
[tab]…名刺の電話番号もニセモノだったし。
[wait][clear][end]

msg_41:
[color(yellow)]キザな男[color(white)]
[tab]おぉ、君は僕を信じてくれるんだね！？
[tab]僕に出来ることなら何でも協力するよ。
[tab]…なんでも言ってみてよ？
[wait][clear][end]

msg_42:
[tab]…なんでも言ってみてよ？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_43:
ナカタニケンイチ
[end]

msg_44:
[color(yellow)]キザな男[color(white)]
[tab]え、誰？
[tab]あ～あの俳優のことでしょ？
[tab]ごめんごめん、彼とは面識無いんだよね～
[wait][clear][end]

msg_45:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[tab]おー、僕の名前も有名になったもんだね。
[tab]…違う？[tab]従兄弟が僕を捜してる！？
[wait][clear][end]

msg_46:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[tab]やっべー！！
[tab]あいつの電話番号使ってるの、もうバレたか。
[tab]…早めにあやまっとこ。
[wait][clear][end]

msg_47:
[color(yellow)]キザな男[color(white)]
[tab]どうだいハニー？
[tab]この間のＴＶ番組、見学に行かなくて正解だろ？
[tab]僕だけが持つ予知能力…のおかげなんだぜ。
[wait][clear][end]

msg_48:
[color(yellow)]ＯＬ[color(white)]
[tab]…予知能力って、突然お腹の調子が悪くなった事？
[tab]その前に、あの番組のディレクターと親友って
[tab]本当の話だったの？
[wait][clear][end]

msg_49:
[color(yellow)]ＯＬ[color(white)]
[tab]…またウソ言ってるでしょ？
[wait][clear][end]

msg_50:
[color(yellow)]キザな男[color(white)]
[end]

msg_51:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_52:
[tab]ハニー、知ってるかい？[tab]このレストランの
[tab]床にはムーンストーンが埋め込まれているんだ。
[tab]ほら、青白く光ってるのがそれさ。
[wait][clear][end]

msg_53:
[color(yellow)]キザな男[color(white)]
[end]

msg_54:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_55:
[tab]ムーンストーンは恋心を伝達してくれる石。
[tab]だからここで共に食事をした男女は、
[tab]必ず結ばれるって噂があるんだよ。
[wait][clear][end]

msg_56:
[color(yellow)]ＯＬ[color(white)]
[tab]ふ～ん、そうなんだぁ…って、ちょっと！！
[tab]それでいつも私をここに連れて来るのね！
[tab]もーウソばっかりついて、絶対に許せないっ！
[wait][clear][end]

msg_57:
[color(yellow)]ＯＬ[color(white)]
[tab]マッタクもー！[tab]（…でも何かしら？）
[tab]いいかげんにしてよ！[tab]（この胸の苦しみは？）
[tab]あなたには興味無いの！[tab]（もしかして…）
[wait][clear][end]

msg_58:
[color(yellow)]キザな男[color(white)]
[end]

msg_59:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_60:
[tab]世界滅亡がなんだ！[tab]な、何だと言うんだい？
[tab]あああ、安心しておくれ、ハニー
[tab]ぼぼ、僕が君を守る！[tab]命に代えても！
[wait][clear][end]

msg_61:
[color(yellow)]ＯＬ[color(white)]
[tab]あーん！[tab]あなたったら、なんて勇ましいのぉ！
[tab]声はガチガチ、足も震えてて無理がバレバレ。
[tab]だけど、なぜかそれも素敵に見えちゃう！
[wait][clear][end]

msg_62:
[color(yellow)]キザな男[color(white)]
[end]

msg_63:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_64:
[tab]あぁ、君は助かったんだね…
[tab]よかった…ゲフゲフっ…君が無事なら…
[tab]僕は…き…み……を………
[wait][clear][end]

msg_65:
[color(yellow)]ＯＬ[color(white)]
[tab]…いや！[tab]いやよ！！[tab]私を一人にしないでー！
[tab]って、あなた何にもしてないじゃない。
[tab]でも、なぜか素敵に見えちゃう！
[wait][clear][end]

msg_66:
[color(yellow)]キザな男[color(white)]
[end]

msg_67:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_68:
[tab]どうだいハニー？
[tab]この青葉店も前と変わらず素敵だろ？
[wait][clear][end]

msg_69:
[color(yellow)]キザな男[color(white)]
[end]

msg_70:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_71:
[tab]そう、美しいもの、素晴らしいものは不変なんだ。
[tab]だから…僕の…君への想いも変わらないのさ。
[wait][clear][end]

msg_72:
[color(yellow)]ＯＬ[color(white)]
[tab]このお店が素敵なのは納得するけど…
[tab]あなたクサイわ。クサすぎる！
[tab]…なのに、それなのに素敵に見えるのは何故？
[wait][clear][end]

msg_73:
[color(yellow)]キザな男[color(white)]
[end]

msg_74:
[color(yellow)]ナカタニ[tab]ケンイチ[color(white)]
[end]

msg_75:
[tab]ね、ここで軍備品を売ってるって話は
[tab]ホントだっただろ？
[tab]ど～～だい、ハニー？
[wait][clear][end]

msg_76:
[color(yellow)]ＯＬ[color(white)]
[tab]あら、ホントだわぁ。
[tab]あなたもたまにはホントの事言うのね。
[tab]…私を誘う口実にしては上出来じゃない？
[wait][clear][end]

msg_77:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]クレール・ド・リュンヌへようこそ。
[tab]本日はこちらのコースなどいかがでしょうか？
[wait][clear][end]

msg_78:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール。
[tab]クレール・ド・リュンヌ青葉店へようこそ。
[tab]本日はこちらのコースなどいかがでしょうか？
[wait][clear][end]

msg_79:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_80:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな防具を用意しました。

[wait][clear][end]

msg_81:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌ
[tab]青葉店へようこそ。
[wait][clear][end]

msg_82:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな防具を用意しました。

[wait][clear][end]

msg_83:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_84:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな武器を用意しました。

[wait][clear][end]

msg_85:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌ
[tab]青葉店へようこそ。
[wait][clear][end]

msg_86:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな武器を用意しました。

[wait][clear][end]

msg_87:
[color(yellow)]ギャルソン副島[color(white)]
[tab]クレール・ド・リュンヌへようこそ。
[tab]今日は何を？[tab][delay(30)]…オォ、トレビア～ン！！
[tab]私もお薦めしようと思っていたところです。
[wait][clear][end]

msg_88:
[color(yellow)]ギャルソン副島[color(white)]
[tab]…ギャルソンとして、とても幸せな気分です。
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。
[wait][clear][end]

msg_89:
[color(yellow)]ギャルソン副島[color(white)]
[tab]クレール・ド・リュンヌ青葉店へようこそ。
[tab]今日は何を？[tab][delay(30)]…オォ、トレビア～ン！！
[tab]私もお薦めしようと思っていたところです。
[wait][clear][end]

msg_90:
[color(yellow)]ギャルソン副島[color(white)]
[tab]…ギャルソンとして、とても幸せな気分です。
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。
[wait][clear][end]

msg_91:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_92:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな防具を用意しました。
[tab]…いえいえ、ギャルソンとして当然の仕事です。
[wait][clear][end]

msg_93:
[color(yellow)]ギャルソン副島[color(white)]
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。

[wait][clear][end]

msg_94:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌ
[tab]青葉店へようこそ。
[wait][clear][end]

msg_95:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな防具を用意しました。
[tab]…いえいえ、ギャルソンとして当然の仕事です。
[wait][clear][end]

msg_96:
[color(yellow)]ギャルソン副島[color(white)]
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。
[tab]どうぞ、ゆっくりとご覧になって下さい。
[wait][clear][end]

msg_97:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_98:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな武器を用意しました。
[tab]…いえいえ、ギャルソンとして当然の仕事です。
[wait][clear][end]

msg_99:
[color(yellow)]ギャルソン副島[color(white)]
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。

[wait][clear][end]

msg_100:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌ
[tab]青葉店へようこそ。
[wait][clear][end]

msg_101:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな武器を用意しました。
[tab]…いえいえ、ギャルソンとして当然の仕事です。
[wait][clear][end]

msg_102:
[color(yellow)]ギャルソン副島[color(white)]
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。

[wait][clear][end]

msg_103:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どうぞ、ゆっくりとご覧になって下さい。
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_104:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_105:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どうぞ、ゆっくりとご覧になって下さい。
[choice(7)][if_none(MBIT_HI_CLEARM)]防具を買う
[if_all(MBIT_HI_CLEARM)]武器を買う
アイテムを売る
食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_106:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どちらをお売りになられますか？
[choice(7)][if_all(EBIT_SINARIOFF)]非表示項目
消費物を売る
武器を売る
[if_all(EBIT_SINARIOFF)]頭防具を売る
防具を売る
[if_all(EBIT_SINARIOFF)]脚防具を売る
アクセサリーを売る
[end_choice][clear][end]

msg_107:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_108:
[color(yellow)]ギャルソン副島[color(white)]
[tab]他に御用はございませんか？
[tab]なんなりとお申しつけ下さい。
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_109:
[color(yellow)]ギャルソン副島[color(white)]
何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_110:
[color(yellow)]ギャルソン副島[color(white)]
[tab]他に御用はございませんか？
[tab]なんなりとお申しつけ下さい。
[choice(7)][if_none(MBIT_HI_CLEARM)]防具を買う
[if_all(MBIT_HI_CLEARM)]武器を買う
アイテムを売る
食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_111:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どちらをお売りになられますか？
[choice(7)][if_all(EBIT_SINARIOFF)]非表示項目
消費物を売る
武器を売る
[if_all(EBIT_SINARIOFF)]頭防具を売る
防具を売る
[if_all(EBIT_SINARIOFF)]脚防具を売る
アクセサリーを売る
[end_choice][clear][end]

msg_112:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_113:
[color(yellow)]ギャルソン副島[color(white)]
[tab]無闇に明るいお客様がいらっしゃいますね。
[tab]当店のムードにはそぐわぬようですが…
[tab]お帰り頂くべきか…？[tab]判断に悩むところです。
[wait][clear][end]

msg_114:
[color(yellow)]ギャルソン副島[color(white)]
[tab]たとえいかなる場合においても、
[tab]レストランと共にあるのがギャルソンです。
[tab]私は、この店を離れません。
[wait][clear][end]

msg_115:
[color(yellow)]ギャルソン副島[color(white)]
[tab]いつまでも皆さんのご来店をお待ちしていますよ。
[tab]白いナプキンと、透明なグラスを並べながら…
[tab]あなた方の心に、この店がある限り…
[wait][clear][end]

msg_116:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ここにいらっしゃるとは思いも寄らなかった。
[tab]店主としてはとても嬉しく思いますが、
[tab]お客様の身を考えると…素直には喜べません。
[wait][clear][end]

msg_117:
[color(yellow)]ギャルソン副島[color(white)]
[tab]皆が無事である事、皆でテーブルを囲める事、
[tab]これを素直に喜びませんか？
[tab]先の事はわかりませんが、きっと大丈夫ですよ。
[wait][clear][end]

msg_118:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そうですか、そのような噂が…
[tab]私の過去を知る方がいらっしゃいましたか。
[tab]実は…その噂の通りなのです。
[wait][clear][end]

msg_119:
[color(yellow)]ギャルソン副島[color(white)]
[tab]任務遂行だけを生き甲斐とする外人部隊。
[tab]私の戦いには目的など必要なかった。
[tab]…全ては過去、…若かりし頃の話です。
[wait][clear][end]

msg_120:
[color(yellow)]ギャルソン副島[color(white)]
[tab]その頃の記憶は、はっきりしていませんが…
[tab]まぁ、そのような過去を持つからこそ、
[tab]お客様のご要望にお答えできたわけです。
[wait][clear][end]

msg_121:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ここにいらっしゃるとは思いも寄らなかった。
[tab]店主としてはとても嬉しく思いますが、
[tab]お客様の身を考えると…[delay(30)]素直には喜べませんね。
[wait][clear][end]

msg_122:
[color(yellow)]ギャルソン副島[color(white)]
[tab]オールヴォワール…[delay(15)]
[tab]またのご来店を心よりお待ち申し上げております。
[wait][clear][end]

msg_123:
噂による変化
びっとお～んッ！！
[wait][clear][end]

msg_124:
ＭＢＩＴ[tab]ＨＩ[tab]ＮＡＮＪＯＴＯＵＪＯ
南条出現噂：広げた
びっとお～んッ！！
[wait][clear][end]

msg_125:
ＭＢＩＴ[tab]ＫＥ[tab]ＣＬＥＡＯＢＡ
リュンヌ：青葉区に移転の噂
びっとお～んッ！！
[wait][clear][end]

msg_126:
魔法武器販売広めた
びっとお～んッ！！
[wait][clear][end]

msg_127:
ＭＢＩＴ[tab]ＫＥ[tab]ＣＬＥ
びっとお～んッ！！
[wait][clear][end]

msg_128:
魔法防具販売広めた
びっとお～んッ！！
[wait][clear][end]

msg_129:
ＭＢＩＴ[tab]ＡＩＳ[tab]４８
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_130:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_131:
ＥＢＩＴ[tab]Ｅ００７７
「スマイル平坂クリア・克哉離脱」
びっとお～んッ！！
[wait][clear][end]

msg_132:
ＥＢＩＴ[tab]Ｅ００７Ａ
「野音クリア・克哉編入」
びっとお～んッ！！
[wait][clear][end]

msg_133:
ＥＢＩＴ[tab]Ｅ００７Ｂ
「竜蔵と殺し屋の電話を盗聴」
びっとお～んッ！！
[wait][clear][end]

msg_134:
ＥＢＩＴ[tab]Ｅ００７Ｆ
「廃工場クリア・パオフゥ編入」
びっとお～んッ！！
[wait][clear][end]

msg_135:
ＥＢＩＴ[tab]Ｅ００８Ｃ
「海底遺跡クリア」
びっとお～んッ！！
[wait][clear][end]

msg_136:
ＥＢＩＴ[tab]Ｅ００９Ｆ
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお～んッ！！
[wait][clear][end]

msg_137:
ＥＢＩＴ[tab]Ｅ００ＡＦ
「アメノトリフネクリア」
びっとお～んッ！！
[wait][clear][end]

msg_138:
ＥＢＩＴ[tab]Ｅ００Ｂ８
「珠「瑠城クリア」
びっとお～んッ！！
[wait][clear][end]

msg_139:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)][if_all(MBIT_KE_CLE)]売買
食事
やめる
[end_choice][clear][end]

msg_140:
[color(yellow)]ギャルソン副島[color(white)]
[tab]それでは「売買」について説明させていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]まず初めに、購入の説明になります。
[tab]当店で「防具を買う」を選択します事で
[tab]防具を購入することができます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]防具は、種類により装備できる対象が
[tab]決まっておりますので、よく確認してから購入してください。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]つぎに、売却の説明になります。
[tab]「アイテムを売る」を選択しますと、
[tab]売却する種類の選択になります。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]種類を選択しまして、売却物を決定しますと
[tab]元値の約半額くらいで買い取らせていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]なお、装備中の物の他、一部の特別な物は
[tab]売却することができません。
[tab]ご了承下さい。
[wait][clear][end]

msg_141:
[color(yellow)]ギャルソン副島[color(white)]
[tab]それでは「売買」について説明させていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]まず初めに、購入の説明になります。
[tab]当店で「武器を買う」を選択します事で
[tab]武器を購入することができます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]武器は、種類により装備できる対象が
[tab]決まっておりますので、よく確認してから購入してください。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]つぎに、売却の説明になります。
[tab]「アイテムを売る」を選択しますと、
[tab]売却する種類の選択になります。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]種類を選択しまして、売却物を決定しますと
[tab]元値の約半額くらいで買い取らせていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]なお、装備中の物の他、一部の特別な物は
[tab]売却することができません。
[tab]ご了承下さい。
[wait][clear][end]

msg_142:
[color(yellow)]ギャルソン副島[color(white)]
[tab]それでは「食事」の説明をさせていただきます。
[tab]当店で「食事をする」を選択しますと
[tab]食事をとることができます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]食事には、一時的に能力を高める効果がありまして、
[tab]効果は、メニューによって異なります。
[tab]色々食されて確認されると良いでしょう。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]それと一度食事を取りますと、その効果が切れるまで
[tab]次の食事をとる事はできません。
[tab]ご了承下さい。
[wait][clear][end]

msg_143:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そちらの料理は[var(msg_var_0)]円になりますが、
[tab]ご注文なさいますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_144:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どうやら、当店で買い取れるアイテムを
[tab]お持ちでないようですね。
[wait][clear][end]

msg_145:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そちらは[var(msg_var_0)]円になりますが、
[tab]お買い上げになりますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_146:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そちらの買取価格は[var(msg_var_0)]円になりますが、
[tab]お売りになられますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_147:
[color(green)]未成年は飲酒できません。
[wait][clear][end]
