function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    levelFootstepSet(sfx_15);
    sndMusicPlay(sound_3043, 127);
    envTriggerSet(DOORBOX, 131, 1, line, coll_0);
    li(var_0, 0);
    partyMemberCheck(var_0, ulala);
    add(var_5, var_5, var_0);
    bez(var_0, label_d);
    ref_9 = spriteLoad(sprite_6);
    wait(ref_9);
    unitSpawn(ulala, sprite_6, 298, 0, -424, south, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_d:
    partyMemberCheck(var_0, katsuya);
    add(var_5, var_5, var_0);
    bez(var_0, label_14);
    ref_10 = spriteLoad(sprite_d);
    wait(ref_10);
    unitSpawn(katsuya, sprite_d, 657, 0, -956, north, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_14:
    partyMemberCheck(var_0, baofu);
    add(var_5, var_5, var_0);
    bez(var_0, label_1b);
    ref_17 = spriteLoad(sprite_13);
    wait(ref_17);
    unitSpawn(baofu, sprite_13, 43, 0, -1047, east, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_1b:
    partyMemberCheck(var_0, nanjo);
    add(var_5, var_5, var_0);
    bez(var_0, label_22);
    ref_1e = spriteLoad(sprite_1f);
    wait(ref_1e);
    unitSpawn(nanjo, sprite_1f, 1180, 0, -1409, west, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
  label_22:
    partyMemberCheck(var_0, elly);
    add(var_5, var_5, var_0);
    bez(var_0, label_29);
    ref_25 = spriteLoad(sprite_23);
    wait(ref_25);
    unitSpawn(elly, sprite_23, 447, 0, -763, west, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
  label_29:
    partyMemberCheck(var_0, tatsuya);
    add(var_5, var_5, var_0);
    bez(var_0, label_31);
    ref_2c = spriteLoad(sprite_18);
    wait(ref_2c);
    unitSpawn(tatsuya, sprite_18, 37, 0, -737, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_3a);
  label_31:
    bitGet(var_0, EBIT_E008C);
    bne(var_0, 0, label_34);
    b(label_3a);
  label_34:
    bne(var_0, 1, label_3a);
    ref_35 = spriteLoad(sprite_18);
    wait(ref_35);
    unitSpawn(tatsuya, sprite_18, 37, 0, -737, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_3a);
  label_3a:
    boutrange(var_5, 0, 4, label_3d);
    li(var_0, 0);
    b(label_42);
  label_3d:
    ref_3d = dialogAlloc();
    ref_3e = msgShow(msg_0);
/***************************************
[tab]パーティの人数が四人を超えています。
[tab]このままじゃハングします。
[tab]金田・片岡に連絡してください。
[tab][wait][clear]
***************************************/
    wait(ref_3e);
    dialogFree(ref_3d);
    b(label_42);
  label_42:
    bitGet(var_0, MBIT_KEISATU_FUKEI);
    bne(var_0, 0, label_4b);
    ref_44 = spriteLoad(sprite_ce);
    wait(ref_44);
    unitSpawn(npc1, sprite_ce, 532, 0, -358, north, none);
    unitTriggerSet(npc1, FUKEI, 255, 1);
    unitSpawn(npc2, sprite_ce, 532, 0, -441, south, none);
    unitTriggerSet(npc2, FUKEI, 255, 1);
    b(label_51);
  label_4b:
    bne(var_0, 1, label_51);
    envTriggerSet(HISOHISO, 14, 1, line, coll_24);
    envTriggerSet(HISOHISO, 14, 1, line, coll_23);
    envTriggerSet(HISOHISO, 14, 1, line, coll_3);
    envTriggerSet(HISOHISO, 14, 1, line, coll_4);
    b(label_51);
  label_51:
    ref_51 = spriteLoad(sprite_cc);
    wait(ref_51);
    unitSpawn(npc3, sprite_cc, 980, 0, -200, east, none);
    envTriggerSet(KEISATU01, 224, 1, circle, coll_2);
    unitSpawn(npc4, sprite_cc, 980, 0, -492, east, none);
    envTriggerSet(KEISATU02, 224, 1, circle, coll_3);
    unitSpawn(npc5, sprite_cc, 980, 0, -798, east, none);
    envTriggerSet(KEISATU03, 224, 1, circle, coll_1);
    unitSpawn(npc6, sprite_cc, 1101, 0, -943, north, none);
    envTriggerSet(KEISATU04, 56, 1, circle, coll_0);
    envTriggerSet(POPI, 56, 1, circle, coll_4);
    envTriggerSet(ANNAI, 224, 1, line, coll_21);
    envTriggerSet(OKORU, 224, 1, line, coll_1);
    cameraSet(southeast, 703, 0, -1542);
    ref_5f = spriteLoad(sprite_0);
    wait(ref_5f);
    ref_61 = spriteLoad(sprite_2);
    wait(ref_61);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function OKORU()
{
    controlDisable();
    ref_6e = cameraRotateTo(3, 30);
    wait(ref_6e);
    ref_70 = unitMove(npc6, 1257, -943, face_west, fast);
    wait(ref_70);
    unitFace(npc6, north);
    delayClear();
    delayWait(30);
    ref_75 = dialogAlloc();
    ref_76 = msgShow(msg_1);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]ピ～～～～～～～～～～～～～～～～～～～！！
[tab]そこから先は関係者以外、立ち入り禁止ッス！
[tab]入っちゃダメダメッス！！
[sync][wait][clear]
***************************************/
    sndMusicPlay(sound_3082, 127);
    unitAnimationPlay(npc6, animation_26, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_76);
    dialogFree(ref_75);
    unitAnimationPlay(npc6, animation_0, 1);
    ref_7f = unitMove(npc6, 1101, -943, face_east, medium);
    wait(ref_7f);
    unitFace(npc6, north);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_f7);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_e7);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_d7);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_c4);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_b4);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_a1);
    unitFacePlayer(ulala);
    ref_92 = bustupLoad(bustup_17);
    bustupWait(ref_92);
    ref_94 = bustupAlloc(ref_92, left, rgb(0,0,0));
    bustupFade(ref_94, rgb(128,0,0), 30);
    ref_96 = dialogAlloc();
    ref_97 = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]１００円入れてワーン。
[tab]１００円入れてワーン。
[tab]……どうマーヤ、似てた？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_97);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_96);
    ref_9c = bustupFade(ref_94, rgb(0,0,0), 10);
    bustupWait(ref_9c);
    bustupFree(ref_94);
    unitRestoreFacing(ulala);
    b(label_106);
  label_a1:
    unitFacePlayer(ulala);
    ref_a2 = bustupLoad(bustup_17);
    bustupWait(ref_a2);
    ref_a4 = bustupAlloc(ref_a2, left, rgb(0,0,0));
    bustupFade(ref_a4, rgb(128,0,0), 30);
    ref_a6 = dialogAlloc();
    ref_a7 = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]パオの奴、
[tab]一人で大丈夫なのかな？

***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_a7);
    ref_aa = msgShow(msg_4);
/***************************************
[tab]べ、別に心配なわけじゃないけどさ…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2c, 1);
    wait(ref_aa);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_a6);
    ref_af = bustupFade(ref_a4, rgb(0,0,0), 10);
    bustupWait(ref_af);
    bustupFree(ref_a4);
    unitRestoreFacing(ulala);
    b(label_106);
  label_b4:
    unitFacePlayer(ulala);
    ref_b5 = bustupLoad(bustup_18);
    bustupWait(ref_b5);
    ref_b7 = bustupAlloc(ref_b5, left, rgb(0,0,0));
    bustupFade(ref_b7, rgb(128,0,0), 30);
    ref_b9 = dialogAlloc();
    ref_ba = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab][suou]さんって、
[tab]署内でも信頼厚いんだねぇ…
[tab]カリスマ刑事って感じ？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_ba);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_b9);
    ref_bf = bustupFade(ref_b7, rgb(0,0,0), 10);
    bustupWait(ref_bf);
    bustupFree(ref_b7);
    unitRestoreFacing(ulala);
    b(label_106);
  label_c4:
    unitFacePlayer(ulala);
    ref_c5 = bustupLoad(bustup_17);
    bustupWait(ref_c5);
    ref_c7 = bustupAlloc(ref_c5, left, rgb(0,0,0));
    bustupFade(ref_c7, rgb(128,0,0), 30);
    ref_c9 = dialogAlloc();
    ref_ca = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ねぇ、マーヤ、
[tab][tatsuya]君って指名手配されたことない？

***************************************/
    unitAnimationPlay(ulala, animation_1a, 1);
    wait(ref_ca);
    ref_cd = msgShow(msg_7);
/***************************************
[tab]ゴメン…あるわけないよね…私どうかしてるわ…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_6, 1);
    wait(ref_cd);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_c9);
    ref_d2 = bustupFade(ref_c7, rgb(0,0,0), 10);
    bustupWait(ref_d2);
    bustupFree(ref_c7);
    unitRestoreFacing(ulala);
    b(label_106);
  label_d7:
    unitFacePlayer(ulala);
    ref_d8 = bustupLoad(bustup_17);
    bustupWait(ref_d8);
    ref_da = bustupAlloc(ref_d8, left, rgb(0,0,0));
    bustupFade(ref_da, rgb(128,0,0), 30);
    ref_dc = dialogAlloc();
    ref_dd = msgShow(msg_8);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]やっぱり兄弟かなぁ…
[tab][tatsuya]君にも、[suou]兄と似たとこあるわ。
[tab]一途なところ…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_dd);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_dc);
    ref_e2 = bustupFade(ref_da, rgb(0,0,0), 10);
    bustupWait(ref_e2);
    bustupFree(ref_da);
    unitRestoreFacing(ulala);
    b(label_106);
  label_e7:
    unitFacePlayer(ulala);
    ref_e8 = bustupLoad(bustup_18);
    bustupWait(ref_e8);
    ref_ea = bustupAlloc(ref_e8, left, rgb(0,0,0));
    bustupFade(ref_ea, rgb(128,0,0), 30);
    ref_ec = dialogAlloc();
    ref_ed = msgShow(msg_9);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なんかここの人達って、
[tab]みんな頼もしいねぇ。
[tab]惚れ惚れしちゃうよ私。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_30, 1);
    wait(ref_ed);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ec);
    ref_f2 = bustupFade(ref_ea, rgb(0,0,0), 10);
    bustupWait(ref_f2);
    bustupFree(ref_ea);
    unitRestoreFacing(ulala);
    b(label_106);
  label_f7:
    unitFacePlayer(ulala);
    ref_f8 = bustupLoad(bustup_1f);
    bustupWait(ref_f8);
    ref_fa = bustupAlloc(ref_f8, left, rgb(0,0,0));
    bustupFade(ref_fa, rgb(128,0,0), 30);
    ref_fc = dialogAlloc();
    ref_fd = msgShow(msg_10);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あのニャルって、人の心の一部なんでしょ？
[tab]つまり私達って、悪魔でも怪物でもない、
[tab]人間を相手にしてるわけよね…
[wait][clear][color(yellow)]うらら[color(white)]
[tab]なんか、そう考えると気が重いなぁ…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2e, 1);
    wait(ref_fd);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_fc);
    ref_102 = bustupFade(ref_fa, rgb(0,0,0), 10);
    bustupWait(ref_102);
    bustupFree(ref_fa);
    unitRestoreFacing(ulala);
  label_106:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_187);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_177);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_167);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_157);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_147);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_137);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_127);
    unitFacePlayer(katsuya);
    ref_118 = bustupLoad(bustup_21);
    bustupWait(ref_118);
    ref_11a = bustupAlloc(ref_118, left, rgb(0,0,0));
    bustupFade(ref_11a, rgb(128,0,0), 30);
    ref_11c = dialogAlloc();
    ref_11d = msgShow(msg_11);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ペルソナが発現してからか…
[tab]射撃が以前より随分と上達したんだ。
[tab]君にも、そんな心当たりはないか？
[wait][clear][color(yellow)]克哉[color(white)]
[tab]召喚するまでもなく、
[tab]我々は、様々なところで、
[tab]ペルソナの恩恵を受けているのかもしれん。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_11d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_11c);
    ref_122 = bustupFade(ref_11a, rgb(0,0,0), 10);
    bustupWait(ref_122);
    bustupFree(ref_11a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_127:
    unitFacePlayer(katsuya);
    ref_128 = bustupLoad(bustup_21);
    bustupWait(ref_128);
    ref_12a = bustupAlloc(ref_128, left, rgb(0,0,0));
    bustupFade(ref_12a, rgb(128,0,0), 30);
    ref_12c = dialogAlloc();
    ref_12d = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]署長と管理官の事は、仲間に報告しておいた。
[tab]警察組織にまだ新世塾幹部がいる可能性は高いが…
[tab]報告しない訳にもいかんのでな。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_12d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_12c);
    ref_132 = bustupFade(ref_12a, rgb(0,0,0), 10);
    bustupWait(ref_132);
    bustupFree(ref_12a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_137:
    unitFacePlayer(katsuya);
    ref_138 = bustupLoad(bustup_21);
    bustupWait(ref_138);
    ref_13a = bustupAlloc(ref_138, left, rgb(0,0,0));
    bustupFade(ref_13a, rgb(128,0,0), 30);
    ref_13c = dialogAlloc();
    ref_13d = msgShow(msg_13);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]一応、出動準備だけは頼んでおいた。
[tab]上からは待機命令が出ているそうだが…
[tab]準備だけなら問題あるまい。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_13d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_13c);
    ref_142 = bustupFade(ref_13a, rgb(0,0,0), 10);
    bustupWait(ref_142);
    bustupFree(ref_13a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_147:
    unitFacePlayer(katsuya);
    ref_148 = bustupLoad(bustup_21);
    bustupWait(ref_148);
    ref_14a = bustupAlloc(ref_148, left, rgb(0,0,0));
    bustupFade(ref_14a, rgb(128,0,0), 30);
    ref_14c = dialogAlloc();
    ref_14d = msgShow(msg_14);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]僕は今も、そしてこれからも、
[tab]公僕であり続けるつもりだ。
[tab]それが自分の決めた道なのだからな。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_14d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_14c);
    ref_152 = bustupFade(ref_14a, rgb(0,0,0), 10);
    bustupWait(ref_152);
    bustupFree(ref_14a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_157:
    unitFacePlayer(katsuya);
    ref_158 = bustupLoad(bustup_21);
    bustupWait(ref_158);
    ref_15a = bustupAlloc(ref_158, left, rgb(0,0,0));
    bustupFade(ref_15a, rgb(128,0,0), 30);
    ref_15c = dialogAlloc();
    ref_15d = msgShow(msg_15);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]今はパニックを起こすのが一番危険だ。
[tab]署の連中にも、街に出てもらった方が
[tab]いいかもしれんな…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_15d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_15c);
    ref_162 = bustupFade(ref_15a, rgb(0,0,0), 10);
    bustupWait(ref_162);
    bustupFree(ref_15a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_167:
    unitFacePlayer(katsuya);
    ref_168 = bustupLoad(bustup_21);
    bustupWait(ref_168);
    ref_16a = bustupAlloc(ref_168, left, rgb(0,0,0));
    bustupFade(ref_16a, rgb(128,0,0), 30);
    ref_16c = dialogAlloc();
    ref_16d = msgShow(msg_16);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]いつまでも感傷に浸っている訳にはいかんな。
[tab][tatsuya]の言う通りなら、こうしている間にも、
[tab]この世界は消えかけているんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_16d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_16c);
    ref_172 = bustupFade(ref_16a, rgb(0,0,0), 10);
    bustupWait(ref_172);
    bustupFree(ref_16a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_177:
    unitFacePlayer(katsuya);
    ref_178 = bustupLoad(bustup_21);
    bustupWait(ref_178);
    ref_17a = bustupAlloc(ref_178, left, rgb(0,0,0));
    bustupFade(ref_17a, rgb(128,0,0), 30);
    ref_17c = dialogAlloc();
    ref_17d = msgShow(msg_17);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]僕は負けるわけにはいかない。
[tab]父を越えるためにも…
[tab]同僚達の気持ちに応えるためにも…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2f, 1);
    wait(ref_17d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_17c);
    ref_182 = bustupFade(ref_17a, rgb(0,0,0), 10);
    bustupWait(ref_182);
    bustupFree(ref_17a);
    unitRestoreFacing(katsuya);
    b(label_196);
  label_187:
    unitFacePlayer(katsuya);
    ref_188 = bustupLoad(bustup_23);
    bustupWait(ref_188);
    ref_18a = bustupAlloc(ref_188, left, rgb(0,0,0));
    bustupFade(ref_18a, rgb(128,0,0), 30);
    ref_18c = dialogAlloc();
    ref_18d = msgShow(msg_18);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]奴に人生を狂わされたのは
[tab][tatsuya]だけじゃない。僕も…そして父もだ。
[tab]許せる事ではない…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2f, 1);
    wait(ref_18d);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_18c);
    ref_192 = bustupFade(ref_18a, rgb(0,0,0), 10);
    bustupWait(ref_192);
    bustupFree(ref_18a);
    unitRestoreFacing(katsuya);
  label_196:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_1f6);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1e6);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_1d6);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_1c6);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_1b6);
    ref_1a3 = bustupLoad(bustup_2d);
    bustupWait(ref_1a3);
    ref_1a5 = bustupAlloc(ref_1a3, left, rgb(0,0,0));
    bustupFade(ref_1a5, rgb(128,0,0), 30);
    ref_1a7 = dialogAlloc();
    ref_1a8 = msgShow(msg_19);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ちっ、指名手配すんなら、
[tab]もう少しましな奴を捜したらどうだってんだ。

***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1a8);
    unitFacePlayer(baofu);
    ref_1ac = msgShow(msg_20);
/***************************************
[tab]ここに竜蔵の写真でも貼っとくか？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1ac);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1a7);
    ref_1b1 = bustupFade(ref_1a5, rgb(0,0,0), 10);
    bustupWait(ref_1b1);
    bustupFree(ref_1a5);
    unitRestoreFacing(baofu);
    b(label_205);
  label_1b6:
    unitFacePlayer(baofu);
    ref_1b7 = bustupLoad(bustup_31);
    bustupWait(ref_1b7);
    ref_1b9 = bustupAlloc(ref_1b7, left, rgb(0,0,0));
    bustupFade(ref_1b9, rgb(128,0,0), 30);
    ref_1bb = dialogAlloc();
    ref_1bc = msgShow(msg_21);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ふん、どうやら[suou]は
[tab]刑事って仕事が向いてるらしいな。
[tab]道理で俺とは相性が悪いわけだぜ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1bc);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1bb);
    ref_1c1 = bustupFade(ref_1b9, rgb(0,0,0), 10);
    bustupWait(ref_1c1);
    bustupFree(ref_1b9);
    unitRestoreFacing(baofu);
    b(label_205);
  label_1c6:
    unitFacePlayer(baofu);
    ref_1c7 = bustupLoad(bustup_2d);
    bustupWait(ref_1c7);
    ref_1c9 = bustupAlloc(ref_1c7, left, rgb(0,0,0));
    bustupFade(ref_1c9, rgb(128,0,0), 30);
    ref_1cb = dialogAlloc();
    ref_1cc = msgShow(msg_22);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]まさかここで取り調べをするつもりじゃないよな？
[tab]本人が話すと言ってるんだ。
[tab]言う通りにしてやろうや。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_1cc);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1cb);
    ref_1d1 = bustupFade(ref_1c9, rgb(0,0,0), 10);
    bustupWait(ref_1d1);
    bustupFree(ref_1c9);
    unitRestoreFacing(baofu);
    b(label_205);
  label_1d6:
    unitFacePlayer(baofu);
    ref_1d7 = bustupLoad(bustup_2d);
    bustupWait(ref_1d7);
    ref_1d9 = bustupAlloc(ref_1d7, left, rgb(0,0,0));
    bustupFade(ref_1d9, rgb(128,0,0), 30);
    ref_1db = dialogAlloc();
    ref_1dc = msgShow(msg_23);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]トリフネとやらが、
[tab]動き出してしまう前に決着をつけられるといいが…
[tab]果たして間に合うのか…
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1dc);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1db);
    ref_1e1 = bustupFade(ref_1d9, rgb(0,0,0), 10);
    bustupWait(ref_1e1);
    bustupFree(ref_1d9);
    unitRestoreFacing(baofu);
    b(label_205);
  label_1e6:
    unitFacePlayer(baofu);
    ref_1e7 = bustupLoad(bustup_2d);
    bustupWait(ref_1e7);
    ref_1e9 = bustupAlloc(ref_1e7, left, rgb(0,0,0));
    bustupFade(ref_1e9, rgb(128,0,0), 30);
    ref_1eb = dialogAlloc();
    ref_1ec = msgShow(msg_24);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ふん…
[tab]ここの警察は、満更捨てたもんでもねえか…
[tab]若い頃の自分を見てるようで嫌だがな。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1ec);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1eb);
    ref_1f1 = bustupFade(ref_1e9, rgb(0,0,0), 10);
    bustupWait(ref_1f1);
    bustupFree(ref_1e9);
    unitRestoreFacing(baofu);
    b(label_205);
  label_1f6:
    unitFacePlayer(baofu);
    ref_1f7 = bustupLoad(bustup_2d);
    bustupWait(ref_1f7);
    ref_1f9 = bustupAlloc(ref_1f7, left, rgb(0,0,0));
    bustupFade(ref_1f9, rgb(128,0,0), 30);
    ref_1fb = dialogAlloc();
    ref_1fc = msgShow(msg_25);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]善悪、両方背負ってんのが人の心だ。
[tab]奴を倒せたとしても人が人である限り、
[tab]奴という存在が消えることはありえねぇ…
[wait][clear][color(yellow)]パオフゥ[color(white)]
[tab]だが、それでも今戦う意味はある。
[tab]少なくとも俺はそう思ってるぜ。
[tab]でなきゃ、気がおさまらねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1fc);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1fb);
    ref_201 = bustupFade(ref_1f9, rgb(0,0,0), 10);
    bustupWait(ref_201);
    bustupFree(ref_1f9);
    unitRestoreFacing(baofu);
  label_205:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_23e);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_22e);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_21e);
    unitFacePlayer(nanjo);
    ref_20f = bustupLoad(bustup_36);
    bustupWait(ref_20f);
    ref_211 = bustupAlloc(ref_20f, left, rgb(0,0,0));
    bustupFade(ref_211, rgb(128,0,0), 30);
    ref_213 = dialogAlloc();
    ref_214 = msgShow(msg_26);
/***************************************
[color(yellow)]南条[color(white)]
[tab]芹沢さんはどうしたのですか？
[tab]さっきからずっとあの犬の人形を見ていますが。
[tab]余程気に入ったのか…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_214);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_213);
    ref_219 = bustupFade(ref_211, rgb(0,0,0), 10);
    bustupWait(ref_219);
    bustupFree(ref_211);
    unitRestoreFacing(nanjo);
    b(label_24d);
  label_21e:
    unitFacePlayer(nanjo);
    ref_21f = bustupLoad(bustup_36);
    bustupWait(ref_21f);
    ref_221 = bustupAlloc(ref_21f, left, rgb(0,0,0));
    bustupFade(ref_221, rgb(128,0,0), 30);
    ref_223 = dialogAlloc();
    ref_224 = msgShow(msg_27);
/***************************************
[color(yellow)]南条[color(white)]
[tab]法と正義…
[tab]これが必ずしも一致するとは限らない。
[tab]最終的に巡査部長はどちらを選ぶのでしょう。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_224);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_223);
    ref_229 = bustupFade(ref_221, rgb(0,0,0), 10);
    bustupWait(ref_229);
    bustupFree(ref_221);
    unitRestoreFacing(nanjo);
    b(label_24d);
  label_22e:
    unitFacePlayer(nanjo);
    ref_22f = bustupLoad(bustup_36);
    bustupWait(ref_22f);
    ref_231 = bustupAlloc(ref_22f, left, rgb(0,0,0));
    bustupFade(ref_231, rgb(128,0,0), 30);
    ref_233 = dialogAlloc();
    ref_234 = msgShow(msg_28);
/***************************************
[color(yellow)]南条[color(white)]
[tab]誇りと志を持って努力する者には、
[tab]自ずと、人を統率する能力が宿るものです。
[tab][suou]巡査部長がそうであるように。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_234);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_233);
    ref_239 = bustupFade(ref_231, rgb(0,0,0), 10);
    bustupWait(ref_239);
    bustupFree(ref_231);
    unitRestoreFacing(nanjo);
    b(label_24d);
  label_23e:
    unitFacePlayer(nanjo);
    ref_23f = bustupLoad(bustup_36);
    bustupWait(ref_23f);
    ref_241 = bustupAlloc(ref_23f, left, rgb(0,0,0));
    bustupFade(ref_241, rgb(128,0,0), 30);
    ref_243 = dialogAlloc();
    ref_244 = msgShow(msg_29);
/***************************************
[color(yellow)]南条[color(white)]
[tab]そう言えばこの警察署で、
[tab]過去に火災が起きたことはありませんか？
[tab]なんなんだ…この違和感は…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_244);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_243);
    ref_249 = bustupFade(ref_241, rgb(0,0,0), 10);
    bustupWait(ref_249);
    bustupFree(ref_241);
    unitRestoreFacing(nanjo);
  label_24d:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_286);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_276);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_266);
    unitFacePlayer(elly);
    ref_257 = bustupLoad(bustup_3d);
    bustupWait(ref_257);
    ref_259 = bustupAlloc(ref_257, left, rgb(0,0,0));
    bustupFade(ref_259, rgb(128,0,0), 30);
    ref_25b = dialogAlloc();
    ref_25c = msgShow(msg_30);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．Ｕｒａｒａはどうしたのでしょう…
[tab]さっきからずっと、
[tab]ああしてポーピー君を眺めてますの。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_25c);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_25b);
    ref_261 = bustupFade(ref_259, rgb(0,0,0), 10);
    bustupWait(ref_261);
    bustupFree(ref_259);
    unitRestoreFacing(elly);
    b(label_295);
  label_266:
    unitFacePlayer(elly);
    ref_267 = bustupLoad(bustup_3d);
    bustupWait(ref_267);
    ref_269 = bustupAlloc(ref_267, left, rgb(0,0,0));
    bustupFade(ref_269, rgb(128,0,0), 30);
    ref_26b = dialogAlloc();
    ref_26c = msgShow(msg_31);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｍｒ．Ｋａｔｕｙａは立派な刑事だと思います。
[tab]でも、法と正義が必ずしも一致するとは限らない。
[tab]その時、彼はどちらを選ぶのでしょう。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_26c);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_26b);
    ref_271 = bustupFade(ref_269, rgb(0,0,0), 10);
    bustupWait(ref_271);
    bustupFree(ref_269);
    unitRestoreFacing(elly);
    b(label_295);
  label_276:
    unitFacePlayer(elly);
    ref_277 = bustupLoad(bustup_3d);
    bustupWait(ref_277);
    ref_279 = bustupAlloc(ref_277, left, rgb(0,0,0));
    bustupFade(ref_279, rgb(128,0,0), 30);
    ref_27b = dialogAlloc();
    ref_27c = msgShow(msg_32);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]誇りと志を持って努力する方には、
[tab]自然と、人を統率する能力が宿るもの。
[tab]Ｍｒ．Ｋａｔｕｙａがそうであるように。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_6, 1);
    wait(ref_27c);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_27b);
    ref_281 = bustupFade(ref_279, rgb(0,0,0), 10);
    bustupWait(ref_281);
    bustupFree(ref_279);
    unitRestoreFacing(elly);
    b(label_295);
  label_286:
    unitFacePlayer(elly);
    ref_287 = bustupLoad(bustup_3d);
    bustupWait(ref_287);
    ref_289 = bustupAlloc(ref_287, left, rgb(0,0,0));
    bustupFade(ref_289, rgb(128,0,0), 30);
    ref_28b = dialogAlloc();
    ref_28c = msgShow(msg_33);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]あの…この警察署、
[tab]一度火事になった事はありませんか？
[tab]なぜか…そんな気がして…
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_28c);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_28b);
    ref_291 = bustupFade(ref_289, rgb(0,0,0), 10);
    bustupWait(ref_291);
    bustupFree(ref_289);
    unitRestoreFacing(elly);
  label_295:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_2df);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2d1);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_2ad);
    ref_29e = bustupLoad(bustup_b);
    bustupWait(ref_29e);
    ref_2a0 = bustupAlloc(ref_29e, right, rgb(0,0,0));
    bustupFade(ref_2a0, rgb(128,0,0), 30);
    bustupFlip(ref_2a0, true);
    ref_2a3 = dialogAlloc();
    ref_2a4 = msgShow(msg_34);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]そうか…
[tab]須藤[tab]竜也がいないから、
[tab]ここも無事なんだな…
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_28, 1);
    wait(ref_2a4);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2a3);
    ref_2a9 = bustupFade(ref_2a0, rgb(0,0,0), 10);
    bustupWait(ref_2a9);
    bustupFree(ref_2a0);
    b(label_2ec);
  label_2ad:
    bitGet(var_0, EBIT_WARP);
    bne(var_0, 0, label_2bf);
    unitFacePlayer(tatsuya);
    ref_2b0 = bustupLoad(bustup_b);
    bustupWait(ref_2b0);
    ref_2b2 = bustupAlloc(ref_2b0, left, rgb(0,0,0));
    bustupFade(ref_2b2, rgb(128,0,0), 30);
    ref_2b4 = dialogAlloc();
    ref_2b5 = msgShow(msg_35);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]これだけ噂が広がってしまった以上、
[tab]既にこの街の下にはトリフネが出現している。
[tab]ヤツにはそれができるんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2b5);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2b4);
    ref_2ba = bustupFade(ref_2b2, rgb(0,0,0), 10);
    bustupWait(ref_2ba);
    bustupFree(ref_2b2);
    unitRestoreFacing(tatsuya);
    b(label_2d0);
  label_2bf:
    bne(var_0, 1, label_2d0);
    unitFacePlayer(tatsuya);
    ref_2c1 = bustupLoad(bustup_d);
    bustupWait(ref_2c1);
    ref_2c3 = bustupAlloc(ref_2c1, left, rgb(0,0,0));
    bustupFade(ref_2c3, rgb(128,0,0), 30);
    ref_2c5 = dialogAlloc();
    ref_2c6 = msgShow(msg_36);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]トリフネが浮上するまで、
[tab]もう時間はないはずだ。
[tab]急ごう。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2c6);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2c5);
    ref_2cb = bustupFade(ref_2c3, rgb(0,0,0), 10);
    bustupWait(ref_2cb);
    bustupFree(ref_2c3);
    unitRestoreFacing(tatsuya);
    b(label_2d0);
  label_2d0:
    b(label_2ec);
  label_2d1:
    ref_2d1 = bustupLoad(bustup_b);
    bustupWait(ref_2d1);
    ref_2d3 = bustupAlloc(ref_2d1, left, rgb(0,0,0));
    bustupFade(ref_2d3, rgb(128,0,0), 30);
    ref_2d5 = dialogAlloc();
    ref_2d6 = msgShow(msg_37);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]これが兄さんの…仲間…
[tab]…仲間か…
[tab]そうだ…俺だって、一人じゃない。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_28, 1);
    wait(ref_2d6);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2d5);
    ref_2db = bustupFade(ref_2d3, rgb(0,0,0), 10);
    bustupWait(ref_2db);
    bustupFree(ref_2d3);
    b(label_2ec);
  label_2df:
    ref_2df = bustupLoad(bustup_b);
    bustupWait(ref_2df);
    ref_2e1 = bustupAlloc(ref_2df, left, rgb(0,0,0));
    bustupFade(ref_2e1, rgb(128,0,0), 30);
    ref_2e3 = dialogAlloc();
    ref_2e4 = msgShow(msg_38);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]人はその身に善と悪を宿す矛盾した存在だ…
[tab]奴はそんな人間が、矛盾なき存在になれるのか、
[tab]その可能性を試そうとしている。
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2e4);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2e3);
    ref_2e9 = bustupFade(ref_2e1, rgb(0,0,0), 10);
    bustupWait(ref_2e9);
    bustupFree(ref_2e1);
  label_2ec:
    controlEnable();
}

function FUKEI()
{
    controlDisable();
    bitGet(var_0, MBIT_KEISATU_FUKEI);
    bnz(var_0, label_324);
    playerConvertToUnit(maya, sprite_0, east);
    playerHide();
    unitFaceUnit(maya, npc1);
    unitFaceUnit(npc1, npc2);
    unitFaceUnit(npc2, npc1);
    cameraRotateTo(1, 60);
    ref_2f7 = dialogAlloc();
    ref_2f8 = msgShow(msg_39);
/***************************************
[color(yellow)]婦警さん[color(white)]
[tab]ねえ聞いて聞いて！
[tab]あの克哉さんがね！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2f8);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2f7);
    ref_2fd = dialogAlloc();
    unitAnimationHold(npc2, animation_1c, -1);
    ref_2ff = msgShow(msg_40);
/***************************************
[color(yellow)]婦警さん[color(white)]
[tab]ちょ…ちょっと、ここじゃダメよ…

***************************************/
    wait(ref_2ff);
    unitAnimationStop(npc2);
    ref_302 = msgShow(msg_41);
/***************************************
[tab]そ、そうねえ…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_1, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(npc2, animation_2, 1);
    sync();
    wait(ref_302);
    dialogFree(ref_2fd);
    ref_30a = cameraMoveTo(-28, 0, -470, 60);
    ref_30b = cameraRotateTo(7, 60);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(npc2, animation_0, 1);
    wait(ref_30a);
    wait(ref_30b);
    ref_310 = dialogAlloc();
    ref_311 = msgShow(msg_42);
/***************************************
[color(yellow)]婦警さん[color(white)]
[tab]後であの裏で聞かせて。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_311);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_310);
    ref_316 = dialogAlloc();
    ref_317 = msgShow(msg_43);
/***************************************
[color(yellow)]婦警さん[color(white)]
[tab]ＯＫ♥
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_14, 1);
    wait(ref_317);
    dialogFree(ref_316);
    unitAnimationPlay(npc1, animation_0, 1);
    unitAnimationPlay(npc2, animation_0, 1);
    bitSet(MBIT_KEISATU_FUKEI);
    ref_31e = cameraLookAtUnit(maya, 0, 60);
    wait(ref_31e);
    unitDespawn(maya, none);
    playerInit(south);
    controlDisable();
    b(label_332);
  label_324:
    unitFaceUnit(npc1, npc2);
    unitFaceUnit(npc2, npc1);
    ref_326 = dialogAlloc();
    ref_327 = msgShow(msg_44);
/***************************************
[color(yellow)]婦警さん[color(white)]
[tab]う～
[tab]早く喋りたい！
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_327);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_326);
    ref_32c = dialogAlloc();
    ref_32d = msgShow(msg_45);
/***************************************
[color(yellow)]婦警さん[color(white)]
[tab]う～
[tab]早く聞きたい！
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_32d);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_32c);
  label_332:
    controlEnable();
}

function HISOHISO()
{
    controlDisable();
    screenNarrow(0);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_397);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_361);
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_382);
    ref_33c = dialogAlloc();
    ref_33d = msgShow(msg_46);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]ねえ、あなたバレンタインどうしたの？
[tab]克哉さんにチョコ渡したの？[tab]ひそひそ…
[wait][clear]
***************************************/
    wait(ref_33d);
    dialogFree(ref_33c);
    ref_340 = dialogAlloc();
    ref_341 = msgShow(msg_47);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…うん。
[tab]チョコレートケーキ作ってプレゼントしたの…
[tab]ひそひそ…
[wait][clear]
***************************************/
    wait(ref_341);
    dialogFree(ref_340);
    ref_344 = dialogAlloc();
    ref_345 = msgShow(msg_48);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…え？[tab]ケーキ？[tab]手作りケーキ？
[tab]あんたやるわねぇ…男はその手のヤツに弱いのよ。
[tab]で？[tab]どうだった？[tab]ひそひそ…
[wait][clear]
***************************************/
    wait(ref_345);
    dialogFree(ref_344);
    ref_348 = dialogAlloc();
    ref_349 = msgShow(msg_49);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]それが…
[tab]食べてはくれたんだけど…
[wait][clear]
***************************************/
    wait(ref_349);
    dialogFree(ref_348);
    ref_34c = dialogAlloc();
    ref_34d = msgShow(msg_50);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]どうだったのよ？
[wait][clear]
***************************************/
    wait(ref_34d);
    dialogFree(ref_34c);
    ref_350 = dialogAlloc();
    ref_351 = msgShow(msg_51);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]バターは無塩バター、
[tab]チョコはスイートチョコを使え。
[tab]それとココアを入れれば味に深みが出るぞ。
[wait][clear][color(yellow)]婦警さんの声[color(white)]
[tab]次はラム酒も少し入れてみるといいだろう。
[tab]食べた時の印象が大きく変わる。
[tab]それからマジパンの使いすぎだ。…だって。
[wait][clear]
***************************************/
    wait(ref_351);
    dialogFree(ref_350);
    ref_354 = dialogAlloc();
    ref_355 = msgShow(msg_52);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]…なによそれ？
[tab]ホントに克哉さんがそう言ったの？
[wait][clear]
***************************************/
    wait(ref_355);
    dialogFree(ref_354);
    ref_358 = dialogAlloc();
    ref_359 = msgShow(msg_53);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]最後に、誕生日でもないのにケーキとは、
[tab]キミも面白いな…だって…
[tab]私もう立ち直れない…
[wait][clear]
***************************************/
    wait(ref_359);
    dialogFree(ref_358);
    ref_35c = dialogAlloc();
    ref_35d = msgShow(msg_54);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]……
[tab]な…なんか…慰めにくいわね…
[wait][clear]
***************************************/
    wait(ref_35d);
    dialogFree(ref_35c);
    b(label_3af);
  label_361:
    ref_361 = dialogAlloc();
    ref_362 = msgShow(msg_55);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]ねぇ、克哉さんって何が好きなのかな？
[tab]ひそひそ…
[wait][clear]
***************************************/
    wait(ref_362);
    dialogFree(ref_361);
    ref_365 = dialogAlloc();
    ref_366 = msgShow(msg_56);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…基本的に辛いのダメみたい。
[tab]だけどカレーは好きらしいよ。
[tab]ひそひそ…
[wait][clear]
***************************************/
    wait(ref_366);
    dialogFree(ref_365);
    ref_369 = dialogAlloc();
    ref_36a = msgShow(msg_57);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]カレーは辛いでしょ？
[wait][clear]
***************************************/
    wait(ref_36a);
    dialogFree(ref_369);
    ref_36d = dialogAlloc();
    ref_36e = msgShow(msg_58);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]だから甘口頼んでるらしいの。
[tab]それがこの前、大失敗しちゃったみたいで…
[wait][clear][color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]カレー食べ終わった後、
[tab]コーヒー飲んじゃったんだって。
[wait][clear]
***************************************/
    wait(ref_36e);
    dialogFree(ref_36d);
    ref_371 = dialogAlloc();
    ref_372 = msgShow(msg_59);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]…それって大変なの？
[wait][clear]
***************************************/
    wait(ref_372);
    dialogFree(ref_371);
    ref_375 = dialogAlloc();
    ref_376 = msgShow(msg_60);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]カレー食べた後にコーヒー飲むと、
[tab]余計に辛く感じちゃうのよ。
[wait][clear]
***************************************/
    wait(ref_376);
    dialogFree(ref_375);
    ref_379 = dialogAlloc();
    ref_37a = msgShow(msg_61);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]へぇ…そうなんだ…
[tab]…で？[tab]克哉さんどうなったの？
[wait][clear]
***************************************/
    wait(ref_37a);
    dialogFree(ref_379);
    ref_37d = dialogAlloc();
    ref_37e = msgShow(msg_62);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]それなりに悲惨だったらしいよ…
[tab]ひそひそ…
[wait][clear]
***************************************/
    wait(ref_37e);
    dialogFree(ref_37d);
    b(label_3af);
  label_382:
    ref_382 = dialogAlloc();
    ref_383 = msgShow(msg_63);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]克哉さんって、婦警に人気だけど、
[tab]いっつも厳しい顔してるよね。鉄仮面って感じ。
[wait][clear]
***************************************/
    wait(ref_383);
    dialogFree(ref_382);
    ref_386 = dialogAlloc();
    ref_387 = msgShow(msg_64);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]ふふふ。でも私見ちゃったんだぁ。
[tab]その鉄仮面が崩れる瞬間を♥
[wait][clear][color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…
[tab]あの克哉さんがね、
[tab]道端で子猫を抱いてニコニコしてたの！！
[wait][clear]
***************************************/
    wait(ref_387);
    dialogFree(ref_386);
    ref_38a = dialogAlloc();
    ref_38b = msgShow(msg_65);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]きゃーーっ！！[tab]まじまじ？
[tab]あれ…だけど、克哉さんって、
[tab]アレルギーなんじゃ…
[wait][clear]
***************************************/
    wait(ref_38b);
    dialogFree(ref_38a);
    ref_38e = dialogAlloc();
    ref_38f = msgShow(msg_66);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ひそひそ…うん。
[tab]その後大変だったみたい。
[tab]例の鉄仮面で表には出てなかったけど…
[wait][clear]
***************************************/
    wait(ref_38f);
    dialogFree(ref_38e);
    ref_392 = dialogAlloc();
    ref_393 = msgShow(msg_67);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ネコ好きなのに、アレルギーなんだ…
[tab]なんか大変ね…それも…
[wait][clear]
***************************************/
    wait(ref_393);
    dialogFree(ref_392);
    b(label_3af);
  label_397:
    ref_397 = dialogAlloc();
    ref_398 = msgShow(msg_68);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]ところでさ…
[tab]街が大変な事になってるのに、
[tab]私達、こんな所で立ち話してていいのかな？
[wait][clear]
***************************************/
    wait(ref_398);
    dialogFree(ref_397);
    ref_39b = dialogAlloc();
    ref_39c = msgShow(msg_69);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]…良くは…ないわよね…ひそひそ…
[tab]だけど、天誅軍って武器持ってるでしょ…
[tab]外出てそんなのに出くわしたらピンチじゃない…
[wait][clear]
***************************************/
    wait(ref_39c);
    dialogFree(ref_39b);
    ref_39f = dialogAlloc();
    ref_3a0 = msgShow(msg_70);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]でも、克哉さん、
[tab]今その天誅軍と戦ってるらしいわよ！
[wait][clear]
***************************************/
    wait(ref_3a0);
    dialogFree(ref_39f);
    ref_3a3 = dialogAlloc();
    ref_3a4 = msgShow(msg_71);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]さすが、正義の人って感じよねぇ～
[tab]って…あれ…克哉さん、
[tab]２週間の謹慎処分受けてなかった？
[wait][clear]
***************************************/
    wait(ref_3a4);
    dialogFree(ref_3a3);
    ref_3a7 = dialogAlloc();
    ref_3a8 = msgShow(msg_72);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]……
[tab]ほら、正義の人だから。
[tab]仕方ないわよ。
[wait][clear]
***************************************/
    wait(ref_3a8);
    dialogFree(ref_3a7);
    ref_3ab = dialogAlloc();
    ref_3ac = msgShow(msg_73);
/***************************************
[color(yellow)]婦警さんの声[color(white)]
[tab]そっか～
[tab]そうよねぇ。
[tab]…ひそひそ…
[wait][clear]
***************************************/
    wait(ref_3ac);
    dialogFree(ref_3ab);
  label_3af:
    screenNarrow(-1);
    controlEnable();
}

function KEISATU01()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_3f5);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_3ec);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_3e3);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_3da);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_3d1);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_3c8);
    unitFacePlayer(npc3);
    ref_3c0 = dialogAlloc();
    ref_3c1 = msgShow(msg_74);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]凄い情報が入ってきましたよ！
[tab]最近巷で行われている講演会、
[tab]実は新世塾が人々を洗脳する為のものだとか。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3c1);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3c0);
    unitRestoreFacing(npc3);
    b(label_3fd);
  label_3c8:
    unitFacePlayer(npc3);
    ref_3c9 = dialogAlloc();
    ref_3ca = msgShow(msg_75);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]か…克哉さんから報告を受けました…
[tab]署長とあの管理官が新世塾のメンバーだったと…
[tab]し、しかし、どうしたものでしょう？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3ca);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3c9);
    unitRestoreFacing(npc3);
    b(label_3fd);
  label_3d1:
    unitFacePlayer(npc3);
    ref_3d2 = dialogAlloc();
    ref_3d3 = msgShow(msg_76);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]廃工場に不審な車が入っていくのを見たとの
[tab]通報がありました。
[tab]…調べに行きたいのは山々なのですが…
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3d3);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3d2);
    unitRestoreFacing(npc3);
    b(label_3fd);
  label_3da:
    unitFacePlayer(npc3);
    ref_3db = dialogAlloc();
    ref_3dc = msgShow(msg_77);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]廃工場で銃撃戦があったそうですね。
[tab]こうなっては我々も動かぬ訳にはいきません！
[tab]先程、調査に数名送りました。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3dc);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3db);
    unitRestoreFacing(npc3);
    b(label_3fd);
  label_3e3:
    unitFacePlayer(npc3);
    ref_3e4 = dialogAlloc();
    ref_3e5 = msgShow(msg_78);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]最近、鳴海区の工事現場で、
[tab]アメノトリフネを発掘しているという
[tab]根も葉もない噂が、巷に流れているようでして…
[wait][clear][color(yellow)]生真面目な警察官[color(white)]
[tab]そんなはずは無いんですがねぇ…
[tab]ちゃんと説明しようにも、
[tab]放っておけと上から言われてますし…う～ん…
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3e5);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3e4);
    unitRestoreFacing(npc3);
    b(label_3fd);
  label_3ec:
    unitFacePlayer(npc3);
    ref_3ed = dialogAlloc();
    ref_3ee = msgShow(msg_79);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]克哉さんが今何をしているのか、
[tab]詳しい話は聞かされていません。
[tab]ですが…それは知る必要の無い事です。
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3ee);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3ed);
    unitRestoreFacing(npc3);
    b(label_3fd);
  label_3f5:
    unitFacePlayer(npc3);
    ref_3f6 = dialogAlloc();
    ref_3f7 = msgShow(msg_80);
/***************************************
[color(yellow)]生真面目な警察官[color(white)]
[tab]多少の被害は出ているようですが、
[tab]まだ地上は無事だそうです。
[tab]新世塾の企みは失敗したのでしょうか？
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_3f7);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3f6);
    unitRestoreFacing(npc3);
  label_3fd:
    controlEnable();
}

function KEISATU02()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_437);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_42e);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_425);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_41c);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_413);
    unitFacePlayer(npc4);
    ref_40b = dialogAlloc();
    ref_40c = msgShow(msg_81);
/***************************************
[color(yellow)]色白な警察官[color(white)]
[tab]新世塾とはどういった組織なのでしょう？
[tab]本庁のデータバンクにも無いなんて。
[tab]こんな時に管理官は居ないし…
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_40c);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_40b);
    unitRestoreFacing(npc4);
    b(label_43f);
  label_413:
    unitFacePlayer(npc4);
    ref_414 = dialogAlloc();
    ref_415 = msgShow(msg_82);
/***************************************
[color(yellow)]色白な警察官[color(white)]
[tab]参りました…
[tab]街がこれだけ混乱している時に、
[tab]署長も、管理官も…
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_415);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_414);
    unitRestoreFacing(npc4);
    b(label_43f);
  label_41c:
    unitFacePlayer(npc4);
    ref_41d = dialogAlloc();
    ref_41e = msgShow(msg_83);
/***************************************
[color(yellow)]色白な警察官[color(white)]
[tab]おかしいですねぇ…
[tab]自衛隊が廃工場に向ったそうです。
[tab]しかしどうしてあんな所に…
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_41e);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_41d);
    unitRestoreFacing(npc4);
    b(label_43f);
  label_425:
    unitFacePlayer(npc4);
    ref_426 = dialogAlloc();
    ref_427 = msgShow(msg_84);
/***************************************
[color(yellow)]色白な警察官[color(white)]
[tab]克哉さんに言われました。
[tab]公僕である事に誇りを持ち、
[tab]その誇りに恥じない行動をとれと。
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_427);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_426);
    unitRestoreFacing(npc4);
    b(label_43f);
  label_42e:
    unitFacePlayer(npc4);
    ref_42f = dialogAlloc();
    ref_430 = msgShow(msg_85);
/***************************************
[color(yellow)]色白な警察官[color(white)]
[tab]克哉さんがいなくても、
[tab]街は我々が必ず守って見せます。
[tab]自分達は、その為にここにいるのです！
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_430);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_42f);
    unitRestoreFacing(npc4);
    b(label_43f);
  label_437:
    unitFacePlayer(npc4);
    ref_438 = dialogAlloc();
    ref_439 = msgShow(msg_86);
/***************************************
[color(yellow)]色白な警察官[color(white)]
[tab]空が赤く染まる直前の地震と強風で、
[tab]街のあちこちにも被害が出ています。
[tab]なかなか対応が追いつかない状態でして…
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_439);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_438);
    unitRestoreFacing(npc4);
  label_43f:
    controlEnable();
}

function KEISATU03()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_479);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_470);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_467);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_45e);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_455);
    unitFacePlayer(npc5);
    ref_44d = dialogAlloc();
    ref_44e = msgShow(msg_87);
/***************************************
[color(yellow)]ベテラン警察官[color(white)]
[tab]どうやら克哉の野郎、
[tab]謹慎処分を無視してるみたいだな…
[tab]いや…俺は何も知らねえよ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_44e);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_44d);
    unitRestoreFacing(npc5);
    b(label_481);
  label_455:
    unitFacePlayer(npc5);
    ref_456 = dialogAlloc();
    ref_457 = msgShow(msg_88);
/***************************************
[color(yellow)]ベテラン警察官[color(white)]
[tab]組織ってのは意外と脆いもんでな、
[tab]トップがいないと、何も出来なくなっちまうんだ。
[tab]俺達も後任が来るまでは待機だろうな…
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_457);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_456);
    unitRestoreFacing(npc5);
    b(label_481);
  label_45e:
    unitFacePlayer(npc5);
    ref_45f = dialogAlloc();
    ref_460 = msgShow(msg_89);
/***************************************
[color(yellow)]ベテラン警察官[color(white)]
[tab]上から待機命令が出てな、
[tab]俺達は動けないんだ…
[tab]こんな時のための警察だってのに…情けねぇ…
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_460);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_45f);
    unitRestoreFacing(npc5);
    b(label_481);
  label_467:
    unitFacePlayer(npc5);
    ref_468 = dialogAlloc();
    ref_469 = msgShow(msg_90);
/***************************************
[color(yellow)]ベテラン警察官[color(white)]
[tab]克哉の奴、何時の間にか
[tab]らしい事を言うようになりやがって…
[tab]もしかしたら、あんた達の影響かもな。
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_469);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_468);
    unitRestoreFacing(npc5);
    b(label_481);
  label_470:
    unitFacePlayer(npc5);
    ref_471 = dialogAlloc();
    ref_472 = msgShow(msg_91);
/***************************************
[color(yellow)]ベテラン警察官[color(white)]
[tab]まったく…もうすぐ定年だってのに、
[tab]人使いの荒い街だぜここは…
[tab]まあ…文字通り乗りかかった船ってヤツか。
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_472);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_471);
    unitRestoreFacing(npc5);
    b(label_481);
  label_479:
    unitFacePlayer(npc5);
    ref_47a = dialogAlloc();
    ref_47b = msgShow(msg_92);
/***************************************
[color(yellow)]ベテラン警察官[color(white)]
[tab]お嬢サン、克哉の野郎を頼むぜ。
[tab]あいつぁ、あれで短気なところがあっからな。
[tab]まぁ、根は良い奴なんだが…
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_47b);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_47a);
    unitRestoreFacing(npc5);
  label_481:
    controlEnable();
}

function KEISATU04()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_4bb);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_4b2);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_4a9);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_4a0);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_497);
    unitFacePlayer(npc6);
    ref_48f = dialogAlloc();
    ref_490 = msgShow(msg_93);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]署長はどこに行ったんスかねぇ…
[tab]こんな時に管理官も連絡がつかないし…
[tab]くぅぅ…動けぬ我が身が忌まわしいッス！
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_490);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_48f);
    unitRestoreFacing(npc6);
    b(label_4c3);
  label_497:
    unitFacePlayer(npc6);
    ref_498 = dialogAlloc();
    ref_499 = msgShow(msg_94);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]困ったッス～！
[tab]トリフネ伝説だの世界滅亡だの…
[tab]大変な街に来てしまったッス～
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_499);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_498);
    unitRestoreFacing(npc6);
    b(label_4c3);
  label_4a0:
    unitFacePlayer(npc6);
    ref_4a1 = dialogAlloc();
    ref_4a2 = msgShow(msg_95);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]誘拐事件の次は、洗脳…
[tab]くぅ…こんな時に自分達はどうしたらいいんスか？
[tab]署長…帰ってきてほしいッスー！
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_4a2);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_4a1);
    unitRestoreFacing(npc6);
    b(label_4c3);
  label_4a9:
    unitFacePlayer(npc6);
    ref_4aa = dialogAlloc();
    ref_4ab = msgShow(msg_96);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]うう…自分はどうしたらいいんスか？
[tab]先輩達の行動は正しいと信じてるッス。
[tab]だけどそれは命令違反ッス…自分はどうしたら…
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_4ab);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_4aa);
    unitRestoreFacing(npc6);
    b(label_4c3);
  label_4b2:
    unitFacePlayer(npc6);
    ref_4b3 = dialogAlloc();
    ref_4b4 = msgShow(msg_97);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]自分も覚悟を決めたッス。
[tab]先輩達と共に、街を守るため戦うッス。
[tab]それができるなら例えクビになっても本望ッス！
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_4b4);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_4b3);
    unitRestoreFacing(npc6);
    b(label_4c3);
  label_4bb:
    unitFacePlayer(npc6);
    ref_4bc = dialogAlloc();
    ref_4bd = msgShow(msg_98);
/***************************************
[color(yellow)]新米警察官[color(white)]
[tab]我々以外にも、
[tab]天誅軍と戦っている人達がいるそうッス。
[tab]なんでも、手も使わずに相手を倒すとか…
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_24, 1);
    wait(ref_4bd);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_4bc);
    unitRestoreFacing(npc6);
  label_4c3:
    controlEnable();
}

function POPI()
{
    controlDisable();
    ref_4c6 = dialogAlloc();
    ref_4c7 = msgShow(msg_99);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]百円入れてワーン♥
[tab]百円入れてワーン♥
[tab]百円入れてワーン♥[wait][clear]
***************************************/
    sndMusicPlay(sound_307f, 127);
    wait(ref_4c7);
    dialogFree(ref_4c6);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    choiceSetResult(1);
    ref_4ce = bustupLoad(bustup_1);
    bustupWait(ref_4ce);
    ref_4d0 = bustupAlloc(ref_4ce, center, rgb(0,0,0));
    bustupFade(ref_4d0, rgb(128,0,0), 30);
    ref_4d2 = dialogChoiceAlloc();
    ref_4d3 = msgShow(msg_100);
/***************************************
[tab]ここに百円入れて欲しいワーン♥
[choice(2)]入れる
入れない
[end_choice][clear]
***************************************/
    wait(ref_4d3);
    dialogFree(ref_4d2);
    ref_4d6 = bustupFade(ref_4d0, rgb(0,0,0), 10);
    bustupWait(ref_4d6);
    bustupFree(ref_4d0);
    choiceGetResult(var_7);
    bne(var_7, 0, label_506);
    partyMoneyGet(var_6);
    boutrange(var_6, 0, 99, label_4e3);
    ref_4dd = dialogAlloc();
    ref_4de = msgShow(msg_101);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]あっ、持ってないワーン♥
[tab]うそつきは泥棒の始まりワーン♥
[tab]姉ちゃん、出直してきな。[wait][clear]
***************************************/
    sndMusicPlay(sound_3081, 127);
    wait(ref_4de);
    dialogFree(ref_4dd);
    b(label_505);
  label_4e3:
    partyMoneyAdd(-100);
    countGet(var_0, panta);
    add(var_0, var_0, 1);
    countSet(panta, var_0);
    bne(var_0, 50, label_4ee);
    ref_4e8 = dialogAlloc();
    ref_4e9 = msgShow(msg_102);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]ワン！[delay(15)]
[tab]もう５０００円溜まったワン！[delay(15)]
[tab]ワーンダフル！！[wait][clear]
***************************************/
    sndMusicPlay(sound_3080, 127);
    wait(ref_4e9);
    dialogFree(ref_4e8);
    b(label_504);
  label_4ee:
    bne(var_0, 100, label_4fe);
    ref_4ef = dialogAlloc();
    ref_4f0 = msgShow(msg_103);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]ワン！[delay(10)]
[tab]ついに１００００円も募金が集まったワン！[delay(15)]
[tab]これもひとえに、お姉さんのおかげワン！！[wait][clear]
***************************************/
    sndMusicPlay(sound_3080, 127);
    wait(ref_4f0);
    msgVar_Item(msgvar_0, hihi_irokane);
    ref_4f4 = msgShow(msg_104);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]これはそのお礼ワン！
[tab][color(green)][var(msg_var_0)][color(white)]。
[tab]どど～んとプレゼントワン♥[wait][clear]
***************************************/
    wait(ref_4f4);
    dialogFree(ref_4ef);
    partyItemAdd(hihi_irokane, 1);
    msgVarSet(msgvar_0, 99);
    ref_4f9 = dialogAlloc();
    ref_4fa = msgShow(msg_105);
/***************************************
[color(green)][tab]舞耶達は、
[tab][item_with_type(item_ffff)]を手に入れた。[color(white)]
[wait][clear]
***************************************/
    wait(ref_4fa);
    dialogFree(ref_4f9);
    b(label_504);
  label_4fe:
    ref_4fe = dialogAlloc();
    ref_4ff = msgShow(msg_106);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]ありがとワーン♥[wait][clear]
***************************************/
    sndMusicPlay(sound_3080, 127);
    wait(ref_4ff);
    dialogFree(ref_4fe);
    b(label_504);
  label_504:
    b(label_505);
  label_505:
    b(label_50d);
  label_506:
    bne(var_7, 1, label_50d);
    ref_507 = dialogAlloc();
    ref_508 = msgShow(msg_107);
/***************************************
[color(yellow)]ポーピーくん[color(white)]
[tab]…[delay(15)]ケチ。[wait][clear]
***************************************/
    sndMusicPlay(sound_3081, 127);
    wait(ref_508);
    dialogFree(ref_507);
    b(label_50d);
  label_50d:
    shopCurrencyDisplay(-110, 150, true);
    controlEnable();
}

function ANNAI()
{
    controlDisable();
    ref_511 = dialogAlloc();
    ref_512 = msgShow(msg_108);
/***************************************
[color(yellow)]ご案内[color(white)]
[tab]Ｂ１Ｆ[tab]総合相談センター、外国人困りごと相談
[tab]１Ｆ[tab]遺失物管理所、免許更新受付、相談コーナー
[tab]２Ｆ[tab]犯罪被害者相談、災害対策課、交通捜査課[wait][clear]
***************************************/
    wait(ref_512);
    ref_514 = msgShow(msg_109);
/***************************************
[color(yellow)]ご案内[color(white)]
[tab]３Ｆ[tab]捜査二課聴訴室、防犯総務課、家事相談室
[tab]４Ｆ[tab]鑑識課身元不明相談室、少年第一課
[tab]５Ｆ[tab]家出人相談室、特捜第一課[wait][clear]
***************************************/
    wait(ref_514);
    dialogFree(ref_511);
    controlEnable();
}

function DOORBOX()
{
    controlDisable();
    objAnimTranslate(obj_31, 80, 0, 0, 30);
    objAnimTranslate(obj_30, -80, 0, 0, 30);
    sndMusicPlay(sound_307e, 127);
    objAnimWait(obj_31);
    objAnimWait(obj_30);
    mapLoad(kounan, 35, 2);
}
