
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]南条君とエリーちゃんもペルソナ使い！
[tab]はぁ～この世の中にそんなに大勢いるもんなのぉ？
[tab]ちょっとがっかりよねぇ。
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]オヤ？[tab]あそこにいる化粧の濃いおばさん、
[tab]ポジティブシンキングとか言ってるよ。
[tab]あれって、マーヤの影響？[tab]…それとも！？
[wait][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]年齢はともかく、ペルソナに関しては
[tab]南条君と桐島君の方が先輩だな。
[tab]…勉強させてもらうよ。
[wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]このままでは新世塾の思うままだ！
[tab]我々に、連中を抑える術は無いのか。
[tab]…まさか、我々の行動も全て…計算の内？
[wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
[tab]ちょっと待て[suou]！
[tab]ペルソナに関しては俺の方が先輩なんだぜ？
[tab]学ぶべきは、俺の戦い方なんじゃねぇか？
[wait][clear][end]

msg_6:
[color(yellow)]パオフゥ[color(white)]
[tab]マスコミを抱き込んで悪事を行うたぁ、
[tab]新世塾の連中も結構やるねぇ。
[tab]…大衆を敵に回すと怖いからな。
[wait][clear][end]

msg_7:
[color(yellow)]南条[color(white)]
[tab]…ミ、Ｍｒ．パオフゥ？
[tab]この件に関して、あまり先輩後輩は関係無いと…
[tab]そんな鬼の首を取ったように言わなくても？
[wait][clear][end]

msg_8:
[color(yellow)]南条[color(white)]
[tab]自重自戒は大事な事だが、
[tab]自分を誤魔化す為のプラス思考は愚の骨頂。
[tab]そうは思いませんか？
[wait][clear][end]

msg_9:
[color(yellow)]エリー[color(white)]
[tab]Ｍｓ．Ｕｒａｒａに悪いお知らせがありますの。
[tab]私の友人…Ｋｅｉを含む９人の友人達も
[tab]ＰＥＲＳＯＮＡ使いですわ。
[wait][clear][end]

msg_10:
[color(yellow)]エリー[color(white)]
[tab]Ｐｏｓｉｔｉｖｅ[tab]Ｔｈｉｎｋｉｎｇって
[tab]誰にでも上手く作用するものではありませんわ。
[tab]結局、その人の性格が根底にありますから。
[wait][clear][end]

msg_11:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]あら、バレちゃった？
[tab]はいはい、わかったわよ。サインでしょ？
[tab][delay(30)]…えーっ違うの？
[wait][clear][end]

msg_12:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]そりゃそうよね。
[tab]私はもう、過去の人間なのよね…
[wait][clear][end]

msg_13:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]アハハッ、過去に囚われてちゃいけないのよ！
[tab]アイドルだった昔なんて忘れるの！
[tab]そう、芸能人だった過去なんてイミ無いもの！
[wait][clear][end]

msg_14:
[color(yellow)]化粧の濃いおばさん[color(white)]
[tab]私には使命がある…皆の為にすべき事があるのよ！
[tab]そうだわ、私はその為に生まれて来たのね！？
[end]

msg_15:
[tab]レーッツ、ポジティブシンキング！！
[wait][clear][end]

msg_16:
[color(yellow)]キザな男[color(white)]
[tab]あのギャルソン、元フランス外人部隊らしくてね、
[tab]巷じゃ地獄のギャルソンなんて呼ばれてるのさ。
[tab]…ここで軍備品を売ってる事は内緒だよ。
[wait][clear][end]

msg_17:
[color(yellow)]ＯＬ[color(white)]
[tab]ここで軍備品を売ってる？[tab]何が内緒よ！
[tab]メニューにも普通の料理しかなかったじゃない。
[tab]…もしかして私を誘う口実だったの？
[wait][clear][end]

msg_18:
[color(yellow)]ＯＬ[color(white)]
[tab]あら、ホントだわぁ。
[tab]あなたもたまにはホントの事言うのね。
[tab]…私を誘う口実にしては上出来じゃない？
[wait][clear][end]

msg_19:
[color(yellow)]キザな男[color(white)]
[tab]どうだいハニー？
[tab]この間のＴＶ番組、見学に行かなくて正解だろ？
[tab]僕だけが持つ予知能力…のおかげなんだぜ。
[wait][clear][end]

msg_20:
[color(yellow)]ＯＬ[color(white)]
[tab]…予知能力って、突然お腹の調子が悪くなった事？
[tab]その前に、あの番組のディレクターと親友って
[tab]本当の話だったの？
[wait][clear][end]

msg_21:
[color(yellow)]ＯＬ[color(white)]
[tab]…またウソ言ってるでしょ？
[wait][clear][end]

msg_22:
[color(yellow)]キザな男[color(white)]
[tab]ね、ここで軍備品を売ってるって話は
[tab]ホントだっただろ？
[tab]ど～～だい、ハニー？
[wait][clear][end]

msg_23:
[color(yellow)]ＯＬ[color(white)]
[tab]あら、ホントだわぁ。
[tab]あなたもたまにはホントの事言うのね。
[tab]…私を誘う口実にしては上出来じゃない？
[wait][clear][end]

msg_24:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]クレール・ド・リュンヌへようこそ。
[tab]本日はこちらのコースなどいかがでしょうか？
[wait][clear][end]

msg_25:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_26:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな防具を用意しました。

[wait][clear][end]

msg_27:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_28:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな武器を用意しました。

[wait][clear][end]

msg_29:
[color(yellow)]ギャルソン副島[color(white)]
[tab]クレール・ド・リュンヌへようこそ。
[tab]今日は何を？[tab][delay(30)]…オォ、トレビア～ン！！
[tab]私もお薦めしようと思っていたところです。
[wait][clear][end]

msg_30:
[color(yellow)]ギャルソン副島[color(white)]
[tab]…ギャルソンとして、とても幸せな気分です。
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。
[wait][clear][end]

msg_31:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_32:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな防具を用意しました。
[tab]…いえいえ、ギャルソンとして当然の仕事です。
[wait][clear][end]

msg_33:
[color(yellow)]ギャルソン副島[color(white)]
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。

[wait][clear][end]

msg_34:
[color(yellow)]ギャルソン副島[color(white)]
[tab]ボンジュール、マドモアゼル。
[tab]生まれ変わったクレール・ド・リュンヌへ
[tab]ようこそ。
[wait][clear][end]

msg_35:
[color(yellow)]ギャルソン副島[color(white)]
[tab]この度、当店ではお客様のニーズにお答えすべく、
[tab]最高の料理とトレビア～ンな武器を用意しました。
[tab]…いえいえ、ギャルソンとして当然の仕事です。
[wait][clear][end]

msg_36:
[color(yellow)]ギャルソン副島[color(white)]
[tab]せっかくですから、今日は特別料金にて
[tab]お持て成しさせていただきましょう。

[wait][clear][end]

msg_37:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どうぞ、ゆっくりとご覧になって下さい。
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_38:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_39:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どうぞ、ゆっくりとご覧になって下さい。
[choice(7)][if_none(MBIT_HI_CLEARM)]防具を買う
[if_all(MBIT_HI_CLEARM)]武器を買う
アイテムを売る
食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_40:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どちらをお売りになられますか？
[choice(7)][if_all(EBIT_SINARIOFF)]非表示項目
消費物を売る
武器を売る
[if_all(EBIT_SINARIOFF)]頭防具を売る
防具を売る
[if_all(EBIT_SINARIOFF)]脚防具を売る
アクセサリーを売る
[end_choice][clear][end]

msg_41:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_42:
[color(yellow)]ギャルソン副島[color(white)]
[tab]他に御用はございませんか？
[tab]なんなりとお申しつけ下さい。
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_43:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_44:
[color(yellow)]ギャルソン副島[color(white)]
[tab]他に御用はございませんか？
[tab]なんなりとお申しつけ下さい。
[choice(7)][if_none(MBIT_HI_CLEARM)]防具を買う
[if_all(MBIT_HI_CLEARM)]武器を買う
アイテムを売る
食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_45:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どちらをお売りになられますか？
[choice(7)][if_all(EBIT_SINARIOFF)]非表示項目
消費物を売る
武器を売る
[if_all(EBIT_SINARIOFF)]頭防具を売る
防具を売る
[if_all(EBIT_SINARIOFF)]脚防具を売る
アクセサリーを売る
[end_choice][clear][end]

msg_46:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_47:
[color(yellow)]ギャルソン副島[color(white)]
[tab]当店では無粋なお客様にお帰り願う事もあります。
[tab]このムードを守るのも、ギャルソンたる私の役目で
[tab]ございますから。
[wait][clear][end]

msg_48:
[color(yellow)]ギャルソン副島[color(white)]
[tab]無闇に明るいお客様がいらっしゃいますね。
[tab]当店のムードにはそぐわぬようですが…
[tab]お帰り頂くべきか…？[tab]判断に悩むところです。
[wait][clear][end]

msg_49:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そうですか、そのような噂が…
[tab]私の過去を知る方がいらっしゃいましたか。
[tab]実は…その噂の通りなのです。
[wait][clear][end]

msg_50:
[color(yellow)]ギャルソン副島[color(white)]
[tab]任務遂行だけを生き甲斐とする外人部隊。
[tab]私の戦いには目的など必要なかった。
[tab]…全ては過去、…若かりし頃の話です。
[wait][clear][end]

msg_51:
[color(yellow)]ギャルソン副島[color(white)]
[tab]その頃の記憶は、はっきりしていませんが…
[tab]まぁ、そのような過去を持つからこそ、
[tab]お客様のご要望にお答えできたわけです。
[wait][clear][end]

msg_52:
[color(yellow)]ギャルソン副島[color(white)]
[tab]オールヴォワール…[delay(15)]
[tab]またのご来店を心よりお待ち申し上げております。
[wait][clear][end]

msg_53:
噂による変化
びっとお～んッ！！
[wait][clear][end]

msg_54:
魔法武器販売
びっとお～んッ！！
[wait][clear][end]

msg_55:
ＭＢＩＴ[tab]ＫＥ[tab]ＣＬＥ
びっとお～んッ！！
[wait][clear][end]

msg_56:
魔法防具販売
びっとお～んッ！！
[wait][clear][end]

msg_57:
ＭＢＩＴ[tab]ＡＩＳ[tab]４８
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_58:
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear][end]

msg_59:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_60:
[color(yellow)]ギャルソン副島[color(white)]
[tab]何をお聞きになりますか？
[choice(3)][if_all(MBIT_KE_CLE)]売買
食事
やめる
[end_choice][clear][end]

msg_61:
[color(yellow)]ギャルソン副島[color(white)]
[tab]それでは「売買」について説明させていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]まず初めに、購入の説明になります。
[tab]当店で「防具を買う」を選択します事で
[tab]防具を購入することができます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]防具は、種類により装備できる対象が
[tab]決まっておりますので、よく確認してから購入してください。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]つぎに、売却の説明になります。
[tab]「アイテムを売る」を選択しますと、
[tab]売却する種類の選択になります。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]種類を選択しまして、売却物を決定しますと
[tab]元値の約半額くらいで買い取らせていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]なお、装備中の物の他、一部の特別な物は
[tab]売却することができません。
[tab]ご了承下さい。
[wait][clear][end]

msg_62:
[color(yellow)]ギャルソン副島[color(white)]
[tab]それでは「売買」について説明させていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]まず初めに、購入の説明になります。
[tab]当店で「武器を買う」を選択します事で
[tab]武器を購入することができます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]武器は、種類により装備できる対象が
[tab]決まっておりますので、よく確認してから購入してください。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]つぎに、売却の説明になります。
[tab]「アイテムを売る」を選択しますと、
[tab]売却する種類の選択になります。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]種類を選択しまして、売却物を決定しますと
[tab]元値の約半額くらいで買い取らせていただきます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]なお、装備中の物の他、一部の特別な物は
[tab]売却することができません。
[tab]ご了承下さい。
[wait][clear][end]

msg_63:
[color(yellow)]ギャルソン副島[color(white)]
[tab]それでは「食事」の説明をさせていただきます。
[tab]当店で「食事をする」を選択しますと
[tab]食事をとることができます。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]食事には、一時的に能力を高める効果がありまして、
[tab]効果は、メニューによって異なります。
[tab]色々食されて確認されると良いでしょう。
[wait][clear][color(yellow)]ギャルソン副島[color(white)]
[tab]それと一度食事を取りますと、その効果が切れるまで
[tab]次の食事をとる事はできません。
[tab]ご了承下さい。
[wait][clear][end]

msg_64:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そちらの料理は[var(msg_var_0)]円になりますが、
[tab]ご注文なさいますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_65:
[color(yellow)]ギャルソン副島[color(white)]
[tab]どうやら、当店で買い取れるアイテムを
[tab]お持ちでないようですね。
[wait][clear][end]

msg_66:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そちらは[var(msg_var_0)]円になりますが、
[tab]お買い上げになりますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_67:
[color(yellow)]ギャルソン副島[color(white)]
[tab]そちらの買取価格は[var(msg_var_0)]円になりますが、
[tab]お売りになられますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_68:
[color(green)]未成年は飲酒できません。
[wait][clear][end]
