
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]やっぱ甘え上手な女の方が得なのかな？
[tab]はぁ～私ってば面倒見がいいからねぇ。
[tab]…大分、損しちゃってるかも。
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]パオフゥのヤツ、[suou]さんの時は
[tab]さんざん言ってたくせに、自分も同じじゃん。
[tab]…困った人だねぇ。
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]過去に色々あった事はわかったけど、
[tab]パオったら、少しは反省とかしてんのかねぇ？
[tab]…前と変わってないように見えるけど。
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
[tab]あの神取って男、前にも大きな事件に
[tab]関係してたんだっけ？[tab]根っからの悪人なんだね。
[tab]…でも、他の連中とは雰囲気違ってたなぁ。
[wait][clear][end]

msg_5:
[color(yellow)]うらら[color(white)]
[tab]栄吉君達と[tatsuya]君は
[tab]「向こう側」の世界でつながってたんだね。
[tab]でも、一方的に忘れられるのって哀しいよ。
[wait][clear][end]

msg_6:
[color(yellow)]うらら[color(white)]
[tab]推測も何も、背中に「１」を背負うのなんか
[tab]南条君しかいないでしょ！？
[tab]…と言う事は、街の人の事は心配いらないね。
[wait][clear][end]

msg_7:
[color(yellow)]うらら[color(white)]
[tab]な～んかみんな、好き勝手言ってるね。
[tab]こんな状況だから、ホンネが出てるのかも？
[wait][clear][end]

msg_8:
[color(yellow)]克哉[color(white)]
[tab]タチの悪いたかり？
[tab]うむ、脅迫罪の疑いがあるな。
[tab]どこだ！[tab]この店にいるのかい！？
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]皆、話したくない過去を持っているだろう？
[tab]パオフゥにも過去がある…それだけの事だよ。
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]理性では抑えきれない感情…犯罪に結び付く事も
[tab]多いが、人である以上ある程度は仕方ないか。
[tab]…あまり人の事は言えないし。
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
[tab]龍が実在のものとは思わないが、
[tab]地中を移動するエネルギーと言われると
[tab]納得してしまうのは…僕が無知だからか？
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab][tatsuya]はずっと戦っていたんだな。
[tab]「向こう側」でも…僕の知らないところで…
[wait][clear][end]

msg_13:
[color(yellow)]克哉[color(white)]
[tab]あそこにいる二人が話しているのは、
[tab]もしかして彼の事なのか？
[tab]証言から推測すると…うむ、間違い無いな。
[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]苦しい時、不安な時だからこそ本音がでる…か。
[tab]確かにその通りだろうな。
[tab]…破滅的な本音が無くて安心したよ。
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
[tab]…甘え上手な女？
[tab]芹沢のヤツ、あそこの女を見て言ってんのか？
[tab]ありゃどう見たって、タチの悪ぃたかりだろう。
[wait][clear][end]

msg_16:
[color(yellow)]パオフゥ[color(white)]
[tab]そこに罠があろうと、己の信念に従い進む。
[tab]これが漢ってもんだろぉ？
[tab]…女子供にゃ理解できねぇか。
[wait][clear][end]

msg_17:
[color(yellow)]パオフゥ[color(white)]
[tab]龍を抑える要石…もしかすると世界中に数多くある
[tab]巨石文明ってのは、要石そのものかもな。
[tab]…レイラインってのも龍脈と同じだろ、きっと。
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
[tab]這い寄る混沌たぁ大層な名前だな。
[tab]新世塾といい、でかい事をするヤツってのは
[tab]ネーミングのセンスも普通と違うんだな。
[wait][clear][end]

msg_19:
[color(yellow)]パオフゥ[color(white)]
[tab]背中に「１」ねぇ。
[tab]あいつの他には…昔、嫁売ジャイアンズにいた
[tab]ホームラン王ぐらいじゃねぇか？
[wait][clear][end]

msg_20:
[color(yellow)]パオフゥ[color(white)]
[tab]「こちら側」に来てから、ずっと独り…
[tab]理解者もいねぇ、想いを伝える事も出来ねぇ…か。
[tab][tatsuya]の奴…辛かったんだな。
[wait][clear][end]

msg_21:
[color(yellow)]南条[color(white)]
[tab]損得があると言う事は利益が関係すると言う事か？
[tab]Ｍｓ．天野、恋愛にも損得があるのですか？
[tab]そして、得られるものとは！？[tab][delay(30)]…困ってます？
[wait][clear][end]

msg_22:
[color(yellow)]南条[color(white)]
[tab]先程盗聴したあの電話の内容…
[tab]何か裏があるとしか思えない。
[tab]急ぎましょう、天野さん！
[wait][clear][end]

msg_23:
[color(yellow)]南条[color(white)]
[tab]先程盗聴したあの電話の内容…
[tab]新世塾の行動…やはりＭｒ．パオフゥは…
[tab]急ぎましょう、天野さん！
[wait][clear][end]

msg_24:
[color(yellow)]南条[color(white)]
[tab]プライベート部分を調べるのは気が引けましたが、
[tab]俺もＭｒ．パオフゥの素性には疑問を
[tab]感じていましたから…
[wait][clear][end]

msg_25:
[color(yellow)]南条[color(white)]
[tab]神取…あいつは自分に与えられた役割を
[tab]演じていただけなのかも知れない…
[wait][clear][end]

msg_26:
[color(yellow)]エリー[color(white)]
[tab]ウフフフ、Ｍｓ．Ｕｒａｒａの面倒見の良さは
[tab]Ｍｓ．Ａｍａｎｏが実感してますわよね？
[tab]…お二人の間に利害関係はありますの？
[wait][clear][end]

msg_27:
[color(yellow)]エリー[color(white)]
[tab]先程盗聴したあの電話の内容…
[tab]Ｈｍｍ…何か嫌な予感がしますわ。
[tab]急ぎましょう、Ｍｓ．Ａｍａｎｏ！
[wait][clear][end]

msg_28:
[color(yellow)]エリー[color(white)]
[tab]先程盗聴したあの電話の内容…
[tab]新世塾の行動…やはりＴｒａｐでしたか。
[tab]急がないと、Ｍｒ．Ｂａｏｆｕが危険ですわ！
[wait][clear][end]

msg_29:
[color(yellow)]エリー[color(white)]
[tab]Ｍｒ．Ｂａｏｆｕの過去…
[tab]Ｈａｒｄ[tab]ｂｏｉｌｅｄですわ。
[tab]それを感じさせないのも、すごい事です。
[wait][clear][end]

msg_30:
[color(yellow)]エリー[color(white)]
[tab]神取…彼は自分に与えられた役割を
[tab]演じていただけなのかも知れませんね…
[wait][clear][end]

msg_31:
[color(yellow)][tatsuya][color(white)]
[tab]神取…あの男も俺と同じ…なのか…？
[wait][clear][end]

msg_32:
[color(yellow)][tatsuya][color(white)]
[tab]俺は一人に馴れ過ぎてしまったのか？
[tab]…共に進む仲間がいる事に違和感を感じている。
[wait][clear][end]

msg_33:
[color(yellow)][tatsuya][color(white)]
[tab]誰にも夢を掴む権利がある。
[tab]「向こう側」の舞耶姉はそういってくれたけど、
[tab]俺は、夢を掴む事が出来るだろうか…
[wait][clear][end]

msg_34:
[color(yellow)][tatsuya][color(white)]
[tab]本音を言える相手がいる…
[tab]それは…とても幸せな事だと思う。
[wait][clear][end]

msg_35:
[color(yellow)]派手なおばさん[color(white)]
[tab]私ね、最近好調なのよ。
[tab]体の調子はいいし、契約はたくさん取れたし。
[tab]やっぱりワンロン占いのおかげかしら？
[wait][clear][end]

msg_36:
[color(yellow)]派手なおばさん[color(white)]
[tab]…なになに？
[tab]私がどうかしたの？
[wait][clear][end]

msg_37:
[tab]私がどうかしたの？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear][end]

msg_38:
キムラヤヨイ
[end]

msg_39:
[color(yellow)]派手なおばさん[color(white)]
[tab]まっ、失礼しちゃうわ！
[tab]人の名前を間違えるのは、とても失礼な事なのよ！
[tab]あなた、セールスマンとして失格よ！？
[wait][clear][end]

msg_40:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[tab]あらやだ、どうして私の名前を知ってるの？
[tab]…え、私がお客をダマした？
[tab]…ＭＵＳＥＳの販促物をエサに契約！？
[wait][clear][end]

msg_41:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[tab]な、何を根拠に、そんな事を。
[tab]たまたま、手元に無かったから渡せないでいる
[tab]だけじゃない。ダマしたわけじゃないわよ！
[wait][clear][end]

msg_42:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[tab]だいたい保険に入るのに販促物で…
[tab]あ、あなたに言っても仕方ないわね。
[tab]ふ、ふんっ。今から販促物もって行くわよ。
[wait][clear][end]

msg_43:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_44:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_45:
[tab]穢れ祓いの講演会に参加した人に会った事ある？
[tab]いきなり「レッツ・ポジティブシンキング！」
[tab]とか大声で叫ぶのよ。…しかも路上で。
[wait][clear][end]

msg_46:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_47:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_48:
[tab]それに講演会へ行こうってしつこいのよ。
[tab]そうそう、講演会に行って行方不明になった
[tab]人もいるらしいわよ。…怖いわぁ。
[wait][clear][end]

msg_49:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_50:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_51:
[tab]大変、大変！[tab]ニュース見た？[tab]ポールシフトよ！
[tab]え～まずは親戚に電話して、水と保存食を買って、
[tab]…あっ、ローソクも買わなきゃ。
[wait][clear][end]

msg_52:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_53:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_54:
[tab]地下鉄の工事中に見つかった遺跡が
[tab]空に浮かぶなんて、思いもよらなかったわ～
[tab]ねぇ貴方、空へ行く準備は整ったの？
[wait][clear][end]

msg_55:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_56:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_57:
[tab]…私？[tab]完璧よ！
[tab]あっ、余ったお金で貴金属買っとこ～
[wait][clear][end]

msg_58:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_59:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_60:
[tab]あら久しぶり…え、大丈夫だったかって？
[tab]大丈夫よ～私の家は青葉区だもの。
[tab]ええと…今週の赤龍のラッキーアイテムは……
[wait][clear][end]

msg_61:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_62:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_63:
[tab]ポールシフトは起きなかったけど、世界は大混乱。
[tab]でも、こんな時に役立つのが貴金属よ！
[tab]価値は変わらないし、世界で通用するハズだし。
[wait][clear][end]

msg_64:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_65:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_66:
[tab]このお店、もうかってないのかしら？
[tab]最近、武器や防具のオーダーまで受けてるのよ。
[tab]…まっ、私には関係無い話ね。
[wait][clear][end]

msg_67:
[color(yellow)]派手なおばさん[color(white)]
[end]

msg_68:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[end]

msg_69:
[tab]このお店、私のお気に入りなのよ。
[tab]こんなに早く営業が再開されるなんて感激だわ！
[tab]…前と変わらぬ作りがうれしいわよね。
[wait][clear][end]

msg_70:
[color(yellow)]キムラ[tab]ヤヨイ[color(white)]
[tab]ねぇ貴方、蓮華台の[color(orange)]かおり[color(white)]ってお店ご存知？
[tab]あのお店ねぇ、[color(orange)]ここ何日かずっと閉まってた[color(white)]のよ。
[tab]休業している理由も謎なの。…心配よねぇ？
[wait][clear][end]

msg_71:
[color(yellow)]瞳を輝かせる女[color(white)]
[tab]ネェ、石には秘められた力があるって知ってる？
[tab]身に付けた人を守るらしいの。ホントの話よ。
[tab]…最近事件が多くて、私、スッゴク怖いの～
[wait][clear][end]

msg_72:
[color(yellow)]困り顔の男[color(white)]
[tab]…つまり君はキレイな石のついたアクセサリーが
[tab]欲しいんだね。…決して欲しいとは言わない君。
[tab]…僕は君が、…君が怖いよ。
[wait][clear][end]

msg_73:
[color(yellow)]瞳を輝かせる女[color(white)]
[tab]ネェ…私達、もうすぐ死ぬのかな…
[tab]だって、絶対に助かるって言えるッ！？
[tab]…どうせ死ぬならキレイに死にたいの。
[wait][clear][end]

msg_74:
[color(yellow)]困り顔の男[color(white)]
[tab]だ、大丈夫だよ。珠閒瑠市は大丈夫だって。
[tab]ニュ、ニュースでも言ってたじゃないか。
[tab]（…これは新手のおねだり？[tab]それともマジ？）
[wait][clear][end]

msg_75:
[color(yellow)]瞳を輝かせる女[color(white)]
[tab]ゴメンネェ、取り乱したりして…
[tab]でも、貴方の前だと感情を押さえきれないの。
[tab][delay(30)]…あっ、これカワイイー！[tab]欲しいー！
[wait][clear][end]

msg_76:
[color(yellow)]困り顔の男[color(white)]
[tab]も、もっとじっくり考えた方がいいんじゃないか？
[tab]衝動買いなんかすると、きっと後悔する事になる。
[tab]…ね、良～く考えてみてよ。
[wait][clear][end]

msg_77:
[color(yellow)]瞳を輝かせる女[color(white)]
[tab]ああーん、怖かったー
[tab]あの人が来てくれなかったら私、死んでたかも。
[tab]それに比べて貴方…頼り無いわね！
[wait][clear][end]

msg_78:
[color(yellow)]困り顔の男[color(white)]
[tab]そんな事言ったって、相手は新世塾の人間だよ？
[tab]無理言うなって。…確かにあの人は強かったけど、
[tab]背中に大きく「１」ってのはどうかと思うよ。
[wait][clear][end]

msg_79:
[color(yellow)]瞳を輝かせる女[color(white)]
[tab]私、あの龍を見ても怖くなかったの。
[tab]いいえ、むしろ美しいって思えたわ。
[tab]…これって私が穢れている証拠？
[wait][clear][end]

msg_80:
[color(yellow)]困り顔の男[color(white)]
[tab]馬鹿言うなよ。君が穢れている訳無いじゃないか。
[tab]君は他のコより純粋なだけなんだよ。
[tab]僕にはわかる。…君の事は誰よりも良く……
[wait][clear][end]

msg_81:
[color(yellow)]瞳を輝かせる女[color(white)]
[tab]…ホント？[tab]ホントにー！？
[tab]じゃあ、私が今欲しいモノもわかるわよネェ？
[tab]ヒントは～１９歳の誕生日にもらいたいモノ！
[wait][clear][end]

msg_82:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、いらっしゃい。

[wait][clear][end]

msg_83:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、いらっしゃい。
[tab]今日は何の用…え？[tab]…武器？[tab]…防具？
[tab]そんなものは扱っていないゼ？
[wait][clear][end]

msg_84:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]レディメイドのアクセサリーだけじゃ不満か？
[tab]どうしてもって言うんなら、オーダーメイドだな。
[tab]…但し、材料はソッチ持ちとさせてもらうゼ。
[wait][clear][end]

msg_85:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、キミも無事だったか！
[tab]前の店同様、よろしく頼むゼ。
[tab]…前の店？[tab]下でガレキに埋もれてるよ。[wait][clear][end]

msg_86:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、キミも無事だったか！
[tab]前の店同様、よろしく頼むゼ。
[tab]…前の店？[tab]下でガレキに埋もれてるよ。[wait][clear][end]

msg_87:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ところで今日は何の用…
[tab]え？[tab]…武器？[tab]…防具？
[tab]そんなものは扱っていないゼ？
[wait][clear][end]

msg_88:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]レディメイドのアクセサリーだけじゃ不満か？
[tab]どうしてもって言うんなら、オーダーメイドだな。
[tab]…但し、材料はソッチ持ちとさせてもらうゼ。
[wait][clear][end]

msg_89:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、いらっしゃい。
[tab]どうだい？[tab]オレの作ったアクセサリーは？[delay(30)]
[tab]…ホウ、キミの感性はオレの作品と合うらしい。
[wait][clear][end]

msg_90:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]そう！[tab]大事なのは互いの相性なんだ。
[tab]この出会いは大事にしなきゃな…
[tab]イイよ…今日だけは安くしておく。
[wait][clear][end]

msg_91:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、いらっしゃい。
[tab]どうだい？[tab]オレの作ったアクセサリーは？[delay(30)]
[tab]…ホウ、キミの感性はオレの作品と合うらしい。
[wait][clear][end]

msg_92:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]そう！[tab]大事なのは互いの相性なんだ。
[tab]この出会いは大事にしなきゃな…
[tab]イイよ…今日だけは安くしておく。
[wait][clear][end]

msg_93:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ところで今日は何の用…
[tab]え？[tab]…武器？[tab]…防具？
[tab]そんなものは扱っていないゼ？
[wait][clear][end]

msg_94:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]レディメイドのアクセサリーだけじゃ不満か？
[tab]どうしてもって言うんなら、オーダーメイドだな。
[tab]…但し、材料はソッチ持ちとさせてもらうゼ。
[wait][clear][end]

msg_95:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、キミも無事だったか！
[tab]前の店同様、よろしく頼むゼ。
[tab]…前の店？[tab]下でガレキに埋もれてるよ。
[wait][clear][end]

msg_96:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ところでどうだい？
[tab]オレの作ったアクセサリーは？[delay(30)]
[tab]…ホウ、キミの感性はオレの作品と合うらしい。
[wait][clear][end]

msg_97:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]そう！[tab]大事なのは互いの相性なんだ。
[tab]この出会いは大事にしなきゃな…
[tab]イイよ…今日だけは安くしておく。
[wait][clear][end]

msg_98:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]やぁ、キミも無事だったか！
[tab]前の店同様、よろしく頼むゼ。
[tab]…前の店？[tab]下でガレキに埋もれてるよ。
[wait][clear][end]

msg_99:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ところで今日は何の用…
[tab]え？[tab]…武器？[tab]…防具？
[tab]そんなものは扱っていないゼ？
[wait][clear][end]

msg_100:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]レディメイドのアクセサリーだけじゃ不満か？
[tab]どうしてもって言うんなら、オーダーメイドだな。
[tab]但し、材料はソッチ持ち…
[wait][clear][end]

msg_101:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]…にしようと思ったが
[tab]キミとは感性が合うようだしなぁ。
[tab]イイよ…今日だけは安くしておく。
[wait][clear][end]

msg_102:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]…何、それ？
[tab]伝説の武器職人！？[tab]秘伝書～！？
[tab]な～んか怪しいな、ソレ。
[wait][clear][end]

msg_103:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]どれどれ…[delay(15)]…[delay(15)]…[delay(15)]！！！！
[tab]ス、スゲェよコイツは！！
[tab]この通り造れたら…強力なのが出来るゼ！
[wait][clear][end]

msg_104:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]…しかし、オレの持つ裏のルートでも
[tab]この素材は手に入らねぇな。
[wait][clear][end]

msg_105:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]コレに載ってる武器を造りたいのなら、
[tab]必要な素材を持って来てくれよ。
[tab]…モノさえあれば、造るゼ！！
[wait][clear][end]

msg_106:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]今日は何の用だい？[tab]…んん？
[choice(6)]アクセサリーを購入
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_107:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ドレを売ってくれるんだ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_108:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ナニについて聞きたいんだ？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_109:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]今日は何の用だい？[tab]…んん？
[choice(7)]開発を依頼する
アクセサリーを購入
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_110:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ドレを売ってくれるんだ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_111:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ナニについて聞きたいんだ？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_112:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]全てオレの自信作！
[tab]もっと良く見ていってくれ。
[choice(6)]アクセサリーを購入
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_113:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ドレを売ってくれるんだ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_114:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ナニについて聞きたいんだ？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_115:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]今日は何の用だい？[tab]…んん？
[choice(7)]開発を依頼する
アクセサリーを購入
アイテムを売る
話をする
[if_all(EBIT_SINARIOFF)]アイテムの確認
やめる
店の外に出る
[end_choice][clear][end]

msg_116:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ドレを売ってくれるんだ？
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]非表示項目
[dbl_tab]消費物を売る
[dbl_tab]武器を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]頭防具を売る
[dbl_tab]防具を売る
[dbl_tab][if_all(EBIT_SINARIOFF)]脚防具を売る
[dbl_tab]アクセサリーを売る
[end_choice][clear][end]

msg_117:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ナニについて聞きたいんだ？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_118:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]個性の無い連中って多いよな。最近特に感じるゼ。
[tab]ファッションじゃねぇぞ。考え方や生き方の事だ。
[tab]…なぁ、個性って大事だと思わないか？
[wait][clear][end]

msg_119:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]アメノトリフネの中には何があるんだろうな。
[tab]未発見のレアメタルやオーパーツがゴロゴロっと…
[tab]あーなんかワクワクするゼ。…不謹慎か？
[wait][clear][end]

msg_120:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]気に入ったモノを見つけた時、キミならどうする？
[tab]オレは迷わず手に入れるね。どんなに高くてもだ！
[tab]それがオレのスタイル…恋だって一緒だゼ？
[wait][clear][end]

msg_121:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ここにいる連中、もう助かったつもりなんだな。
[tab]まぁワンロン占い、いや望龍術に間違いは無いか。
[tab]…やっぱ下に残された連中、死んじまうのかな？
[wait][clear][end]

msg_122:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]何も起きなかったが…新世塾の企みは失敗か？
[tab]まぁ何にしても、世の中全部仕切り直しだな。
[tab]あー手に職付けといて、良かったゼ。
[wait][clear][end]

msg_123:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]アクセサリーのオーダーメイドはお手のモンだが、
[tab]武器や防具のオーダーは初めてのケースだゼ。
[tab]…しかし、何で引き受けちまったんだ？
[wait][clear][end]

msg_124:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]どんな美しい宝石も、オレにとっては只の素材。
[tab]加工して欲しいモノがあったら言ってくれ。
[tab]…どんなモノでも作るゼ。
[wait][clear][end]

msg_125:
ＭＢＩＴ[tab]ＨＩ[tab]ＮＡＮＪＯＴＯＵＪＯ
南条出現噂：広げた
びっとお～んッ！！
[wait][clear][end]

msg_126:
噂による変化
びっとお～んッ！！
[wait][clear][end]

msg_127:
ＭＢＩＴ[tab]ＫＥ[tab]ＪＥＷＫＯＵＮＡＮ
噂による港南区移転
びっとお～んッ！！
[wait][clear][end]

msg_128:
ＭＢＩＴ[tab]ＡＩＳ[tab]３３
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_129:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_130:
ＥＢＩＴ[tab]Ｅ００７７
「スマイル平坂クリア・克哉離脱」
びっとお～んッ！！
[wait][clear][end]

msg_131:
ＥＢＩＴ[tab]Ｅ００７Ａ
「野音クリア・克哉編入」
びっとお～んッ！！
[wait][clear][end]

msg_132:
ＥＢＩＴ[tab]Ｅ００７Ｂ
「竜蔵と殺し屋の電話を盗聴」
びっとお～んッ！！
[wait][clear][end]

msg_133:
ＥＢＩＴ[tab]Ｅ００７Ｆ
「廃工場クリア・パオフゥ編入」
びっとお～んッ！！
[wait][clear][end]

msg_134:
ＥＢＩＴ[tab]Ｅ００８Ｃ
「海底遺跡クリア」
びっとお～んッ！！
[wait][clear][end]

msg_135:
ＥＢＩＴ[tab]Ｅ００９Ｆ
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお～んッ！！
[wait][clear][end]

msg_136:
ＥＢＩＴ[tab]Ｅ００ＡＦ
「アメノトリフネクリア」
びっとお～んッ！！
[wait][clear][end]

msg_137:
ＥＢＩＴ[tab]Ｅ００Ｂ８
「珠「瑠城クリア」
びっとお～んッ！！
[wait][clear][end]

msg_138:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]何について聞きたいんだ？
[choice(3)][if_all(MBIT_KE_JEWDEVE)]開発依頼
売買
やめる
[end_choice][clear][end]

msg_139:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]「開発依頼」だな。
[wait][clear][color(yellow)]ジュエリーデザイナー[color(white)]
[tab]「開発を依頼する」を選んで、さらにリストから
[tab]作りたい武器や防具を選んでくれれば、
[tab]それを作ってやるぞ。
[wait][clear][color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ただし、素材が無ければ当然作れない。
[tab]いくらオレでも、材料が無いとどうしようもないからな。
[tab]それから、開発費もかかるから注意しろよ。
[wait][clear][color(yellow)]ジュエリーデザイナー[color(white)]
[tab]素材はなかなか手に入りにくいと思うが……
[tab]そのかわり、出来上がったモノの品質は保証するゼ。
[tab]その辺で売ってるモンとは別格のブツを提供しよう。
[wait][clear][end]

msg_140:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]「売買」だな。
[wait][clear][color(yellow)]ジュエリーデザイナー[color(white)]
[tab]「アクセサリーを購入」を選んでくれれば、店の商品を
[tab]買えるぞ。主に貴金属…だから当然、安くは無いけどな。
[tab]値段見てビビるなよ。
[wait][clear][color(yellow)]ジュエリーデザイナー[color(white)]
[tab]それから「アイテムを売る」で買い取りもできる。
[tab]まず売却するモノの種類を選んでから、
[tab]何を売るか決めてくれ。
[wait][clear][color(yellow)]ジュエリーデザイナー[color(white)]
[tab]価格は元値の約半分だ。
[tab]それから、装備しているモノや、一部特殊なヤツは
[tab]買い取れないんで、注意してくれ。
[wait][clear][end]

msg_141:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]…んん？[tab]残念だが、今キミは
[tab]ウチで買い取れるモノを持っていないな。
[wait][clear][end]

msg_142:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ソレは[var(msg_var_0)]円になるが、イイかい？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_143:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]ソレを買い取るなら、[var(msg_var_0)]円だな。
[tab]売るかい？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_144:
[color(yellow)]ジュエリーデザイナー[color(white)]
[tab]よし、じゃあこれで作らせてもらうけど
[tab]イイかい？
[choice(2)]はい
いいえ
[end_choice][clear][end]
