function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    bitGet(var_0, MBIT_ZIPMODORI);
    bne(var_0, 0, label_8);
    ref_4 = sndLoad(sound_305b);
    wait(ref_4);
    sndMusicPlay(sound_305b, 127);
    b(label_a);
  label_8:
    bne(var_0, 1, label_a);
    b(label_a);
  label_a:
    envTriggerSet(DOORBOX, 131, 1, line, coll_1e);
    li(var_0, 0);
    partyMemberCheck(var_0, ulala);
    add(var_5, var_5, var_0);
    bez(var_0, label_13);
    ref_f = spriteLoad(sprite_6);
    wait(ref_f);
    unitSpawn(ulala, sprite_6, 427, 0, -1034, south, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_13:
    partyMemberCheck(var_0, katsuya);
    add(var_5, var_5, var_0);
    bez(var_0, label_1a);
    ref_16 = spriteLoad(sprite_d);
    wait(ref_16);
    unitSpawn(katsuya, sprite_d, 771, 0, -1063, south, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_1a:
    partyMemberCheck(var_0, baofu);
    add(var_5, var_5, var_0);
    bez(var_0, label_21);
    ref_1d = spriteLoad(sprite_13);
    wait(ref_1d);
    unitSpawn(baofu, sprite_13, 402, 0, -1330, south, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_21:
    partyMemberCheck(var_0, nanjo);
    add(var_5, var_5, var_0);
    bez(var_0, label_28);
    ref_24 = spriteLoad(sprite_1f);
    wait(ref_24);
    unitSpawn(nanjo, sprite_1f, 828, 0, -1330, south, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
  label_28:
    partyMemberCheck(var_0, elly);
    add(var_5, var_5, var_0);
    bez(var_0, label_2f);
    ref_2b = spriteLoad(sprite_23);
    wait(ref_2b);
    unitSpawn(elly, sprite_23, 664, 0, -923, south, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
  label_2f:
    partyMemberCheck(var_0, tatsuya);
    add(var_5, var_5, var_0);
    bez(var_0, label_36);
    ref_32 = spriteLoad(sprite_18);
    wait(ref_32);
    unitSpawn(tatsuya, sprite_18, 856, 0, -1138, north, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
  label_36:
    boutrange(var_5, 0, 4, label_39);
    li(var_0, 0);
    b(label_3e);
  label_39:
    ref_39 = dialogAlloc();
    ref_3a = msgShow(msg_0);
/***************************************
[tab]パーティの人数が四人を超えています。
[tab]このままじゃハングします。
[tab]金田・片岡に連絡してください。
[tab][wait][clear]
***************************************/
    wait(ref_3a);
    dialogFree(ref_39);
    b(label_3e);
  label_3e:
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_46);
    bitGet(var_0, EBIT_E0038);
    bez(var_0, label_46);
    ref_42 = spriteLoad(sprite_6a);
    wait(ref_42);
    unitSpawn(makimura, sprite_6a, 229, 0, -1368, south, none);
    unitTriggerSet(makimura, SAGIBOX, 255, 1);
  label_46:
    bitGet(var_0, MBIT_HI_GYPSTART);
    bne(var_0, 0, label_49);
    b(label_53);
  label_49:
    bne(var_0, 1, label_53);
    ref_4a = spriteLoad(sprite_bb);
    wait(ref_4a);
    unitSpawn(npc1, sprite_bb, 993, 0, -902, west, none);
    unitTriggerSet(npc1, KIGATIISAI, 255, 1);
    ref_4e = spriteLoad(sprite_c0);
    wait(ref_4e);
    unitSpawn(npc2, sprite_c0, 351, 0, -1142, west, none);
    unitTriggerSet(npc2, WAKAIOTOKO, 255, 1);
    b(label_53);
  label_53:
    ref_53 = spriteLoad(sprite_9d);
    wait(ref_53);
    unitSpawn(shopkeeper, sprite_9d, 595, -40, -185, north, none);
    unitRevolveAnimationPlay(shopkeeper, animrevolve_f);
    envTriggerSet(SHOPBOX, 224, 1, line, coll_d);
    envTriggerSet(SHOPBOX, 112, 1, line, coll_c);
    envTriggerSet(SHOPBOX, 56, 1, line, coll_18);
    envTriggerSet(SHOPBOX, 56, 1, line, coll_19);
    envTriggerSet(SHOPBOX, 28, 1, line, coll_b);
    envTriggerSet(SHOPBOX, 14, 1, line, coll_a);
    bitGet(var_0, MBIT_ZIPMODORI);
    bne(var_0, 0, label_61);
    call(NOMALSTAT);
    b(label_64);
  label_61:
    bne(var_0, 1, label_64);
    call(ISYOUSTART);
    b(label_64);
  label_64:
}

function NOMALSTAT()
{
    bitGet(var_0, MBIT_SUMARURIYOU);
    bne(var_0, 0, label_69);
    cameraSet(southeast, 598, 0, -1329);
    b(label_6c);
  label_69:
    bne(var_0, 1, label_6c);
    cameraSet(northeast, 617, -40, -462);
    b(label_6c);
  label_6c:
    ref_6c = spriteLoad(sprite_0);
    wait(ref_6c);
    ref_6e = spriteLoad(sprite_2);
    wait(ref_6e);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    unitRevolveAnimationPlay(shopkeeper, animrevolve_f);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function ISYOUSTART()
{
    cameraSet(northeast, 583, 0, -427);
    ref_7c = spriteLoad(sprite_1);
    wait(ref_7c);
    unitSpawn3d(maya, sprite_1, 613, -50, -493, south, none);
    unitAnimationPlay(maya, animation_12, 1);
    ref_80 = spriteLoad(sprite_0);
    wait(ref_80);
    ref_82 = spriteLoad(sprite_2);
    wait(ref_82);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    call(SHOPBOX);
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, MBIT_HI_GYPSTART);
    bne(var_0, 0, label_93);
    bitGet(var_0, MBIT_ZIPUTALKURARA_01);
    bne(var_0, 0, label_90);
    b(label_9e);
    b(label_92);
  label_90:
    bne(var_0, 1, label_92);
    b(label_92);
  label_92:
    b(label_95);
  label_93:
    bne(var_0, 1, label_95);
    b(label_95);
  label_95:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_ef);
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_df);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_cf);
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_bf);
    b(label_af);
  label_9e:
    unitFacePlayer(ulala);
    ref_9f = bustupLoad(bustup_18);
    bustupWait(ref_9f);
    ref_a1 = bustupAlloc(ref_9f, left, rgb(0,0,0));
    bustupFade(ref_a1, rgb(128,0,0), 30);
    ref_a3 = dialogAlloc();
    ref_a4 = msgShow(msg_1);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あれ？[tab]マーヤ占い受けたいの？
[tab]だったらワンロンにしときなよ。
[tab]あっちの方が絶対によく当たるんだから。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_a4);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_a3);
    ref_a9 = bustupFade(ref_a1, rgb(0,0,0), 10);
    bustupWait(ref_a9);
    bustupFree(ref_a1);
    unitRestoreFacing(ulala);
    bitSet(MBIT_ZIPUTALKURARA_01);
    b(label_111);
  label_af:
    unitFacePlayer(ulala);
    ref_b0 = bustupLoad(bustup_17);
    bustupWait(ref_b0);
    ref_b2 = bustupAlloc(ref_b0, left, rgb(0,0,0));
    bustupFade(ref_b2, rgb(128,0,0), 30);
    ref_b4 = dialogAlloc();
    ref_b5 = msgShow(msg_2);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]これって私の勘なんだけど、
[tab]アイツが言ってた「あのガキ」って…
[tab]ひょっとしてデジャ・ヴュの少年の事じゃない？
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_b5);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_b4);
    ref_ba = bustupFade(ref_b2, rgb(0,0,0), 10);
    bustupWait(ref_ba);
    bustupFree(ref_b2);
    unitRestoreFacing(ulala);
    b(label_111);
  label_bf:
    unitFacePlayer(ulala);
    ref_c0 = bustupLoad(bustup_1f);
    bustupWait(ref_c0);
    ref_c2 = bustupAlloc(ref_c0, left, rgb(0,0,0));
    bustupFade(ref_c2, rgb(128,0,0), 30);
    ref_c4 = dialogAlloc();
    ref_c5 = msgShow(msg_3);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]そう言えば、
[tab]牧村の居場所を占って貰った事もあったっけ…
[tab]それももう、必要なくなっちゃったねぇ。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_c5);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_c4);
    ref_ca = bustupFade(ref_c2, rgb(0,0,0), 10);
    bustupWait(ref_ca);
    bustupFree(ref_c2);
    unitRestoreFacing(ulala);
    b(label_111);
  label_cf:
    unitFacePlayer(ulala);
    ref_d0 = bustupLoad(bustup_17);
    bustupWait(ref_d0);
    ref_d2 = bustupAlloc(ref_d0, left, rgb(0,0,0));
    bustupFade(ref_d2, rgb(128,0,0), 30);
    ref_d4 = dialogAlloc();
    ref_d5 = msgShow(msg_4);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あのノリコって子は助けられたけど…
[tab]運が良かったんだよね。
[tab]他にも攫われてる人はいるだろうけど…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_d5);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_d4);
    ref_da = bustupFade(ref_d2, rgb(0,0,0), 10);
    bustupWait(ref_da);
    bustupFree(ref_d2);
    unitRestoreFacing(ulala);
    b(label_111);
  label_df:
    unitFacePlayer(ulala);
    ref_e0 = bustupLoad(bustup_17);
    bustupWait(ref_e0);
    ref_e2 = bustupAlloc(ref_e0, left, rgb(0,0,0));
    bustupFade(ref_e2, rgb(128,0,0), 30);
    ref_e4 = dialogAlloc();
    ref_e5 = msgShow(msg_5);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なんかあの南条君って、
[tab]私らより年上に見えない？
[tab]出来すぎてる…というか、ちゃんとしすぎててさ
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_e5);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_e4);
    ref_ea = bustupFade(ref_e2, rgb(0,0,0), 10);
    bustupWait(ref_ea);
    bustupFree(ref_e2);
    unitRestoreFacing(ulala);
    b(label_111);
  label_ef:
    bitGet(var_0, MBIT_ZIPUTALKURARA_02);
    bnz(var_0, label_102);
    unitFacePlayer(ulala);
    ref_f2 = bustupLoad(bustup_1f);
    bustupWait(ref_f2);
    ref_f4 = bustupAlloc(ref_f2, left, rgb(0,0,0));
    bustupFade(ref_f4, rgb(128,0,0), 30);
    ref_f6 = dialogAlloc();
    ref_f7 = msgShow(msg_6);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ワンロン占いまで新世塾の企みだったなんて…
[tab]ハァ…なんで私はこう騙され易いんだろ…
[tab]男運だけじゃなく占い運まで無いなんて…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_6, 1);
    wait(ref_f7);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_f6);
    ref_fc = bustupFade(ref_f4, rgb(0,0,0), 10);
    bustupWait(ref_fc);
    bustupFree(ref_f4);
    unitRestoreFacing(ulala);
    bitSet(MBIT_ZIPUTALKURARA_02);
    b(label_111);
  label_102:
    unitFacePlayer(ulala);
    ref_103 = bustupLoad(bustup_1f);
    bustupWait(ref_103);
    ref_105 = bustupAlloc(ref_103, left, rgb(0,0,0));
    bustupFade(ref_105, rgb(128,0,0), 30);
    ref_107 = dialogAlloc();
    ref_108 = msgShow(msg_7);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]なんだかんだ言って、
[tab]マーヤ達と一緒に行動してて正解だったかもね。
[tab]前の私なら喜んで講演会に行ってただろうし。
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_108);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_107);
    ref_10d = bustupFade(ref_105, rgb(0,0,0), 10);
    bustupWait(ref_10d);
    bustupFree(ref_105);
    unitRestoreFacing(ulala);
  label_111:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_15c);
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_14c);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_13c);
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_12c);
    unitFacePlayer(katsuya);
    ref_11d = bustupLoad(bustup_21);
    bustupWait(ref_11d);
    ref_11f = bustupAlloc(ref_11d, left, rgb(0,0,0));
    bustupFade(ref_11f, rgb(128,0,0), 30);
    ref_121 = dialogAlloc();
    ref_122 = msgShow(msg_8);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]竜也の言っていた「あのガキ」とは誰のことだ？
[tab]奴の口ぶりから言って、
[tab]天野君とも関係があるようだが…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_122);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_121);
    ref_127 = bustupFade(ref_11f, rgb(0,0,0), 10);
    bustupWait(ref_127);
    bustupFree(ref_11f);
    unitRestoreFacing(katsuya);
    b(label_169);
  label_12c:
    unitFacePlayer(katsuya);
    ref_12d = bustupLoad(bustup_21);
    bustupWait(ref_12d);
    ref_12f = bustupAlloc(ref_12d, left, rgb(0,0,0));
    bustupFade(ref_12f, rgb(128,0,0), 30);
    ref_131 = dialogAlloc();
    ref_132 = msgShow(msg_9);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]あの後、部下に海岸を探させたんだが、
[tab][tatsuya]は見つからなかったそうだ…
[tab]あいつ、どこに隠れてるんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_132);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_131);
    ref_137 = bustupFade(ref_12f, rgb(0,0,0), 10);
    bustupWait(ref_137);
    bustupFree(ref_12f);
    unitRestoreFacing(katsuya);
    b(label_169);
  label_13c:
    unitFacePlayer(katsuya);
    ref_13d = bustupLoad(bustup_21);
    bustupWait(ref_13d);
    ref_13f = bustupAlloc(ref_13d, left, rgb(0,0,0));
    bustupFade(ref_13f, rgb(128,0,0), 30);
    ref_141 = dialogAlloc();
    ref_142 = msgShow(msg_10);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]多勢に無勢。
[tab]僕達だけで全ての誘拐を防ぐことは不可能だ。
[tab]せめて、捕まっている場所がわかれば…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_142);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_141);
    ref_147 = bustupFade(ref_13f, rgb(0,0,0), 10);
    bustupWait(ref_147);
    bustupFree(ref_13f);
    unitRestoreFacing(katsuya);
    b(label_169);
  label_14c:
    unitFacePlayer(katsuya);
    ref_14d = bustupLoad(bustup_21);
    bustupWait(ref_14d);
    ref_14f = bustupAlloc(ref_14d, left, rgb(0,0,0));
    bustupFade(ref_14f, rgb(128,0,0), 30);
    ref_151 = dialogAlloc();
    ref_152 = msgShow(msg_11);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]あの南条君はあれで二十歳か。
[tab][tatsuya]は十八だから…二つ違い…
[tab]それにしては雲泥の差だな…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_152);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_151);
    ref_157 = bustupFade(ref_14f, rgb(0,0,0), 10);
    bustupWait(ref_157);
    bustupFree(ref_14f);
    unitRestoreFacing(katsuya);
    b(label_169);
  label_15c:
    ref_15c = bustupLoad(bustup_24);
    bustupWait(ref_15c);
    ref_15e = bustupAlloc(ref_15c, left, rgb(0,0,0));
    bustupFade(ref_15e, rgb(128,0,0), 30);
    ref_160 = dialogAlloc();
    ref_161 = msgShow(msg_12);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ペントハウスの一件…
[tab]スニークの仕業なのか…
[tab]…しかし…
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_161);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_160);
    ref_166 = bustupFade(ref_15e, rgb(0,0,0), 10);
    bustupWait(ref_166);
    bustupFree(ref_15e);
  label_169:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_1b8);
    bitGet(var_0, EBIT_E0046);
    bnz(var_0, label_1a8);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_198);
    bitGet(var_0, EBIT_E0033);
    bnz(var_0, label_184);
    unitFacePlayer(baofu);
    ref_175 = bustupLoad(bustup_31);
    bustupWait(ref_175);
    ref_177 = bustupAlloc(ref_175, left, rgb(0,0,0));
    bustupFade(ref_177, rgb(128,0,0), 30);
    ref_179 = dialogAlloc();
    ref_17a = msgShow(msg_13);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]結局奴は、街の誰かがＪＯＫＥＲ呪いをするたびに
[tab]病室を抜け出し出張していた訳か…
[tab]ご苦労なこったぜ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_17a);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_179);
    ref_17f = bustupFade(ref_177, rgb(0,0,0), 10);
    bustupWait(ref_17f);
    bustupFree(ref_177);
    unitRestoreFacing(baofu);
    b(label_1c7);
  label_184:
    unitFacePlayer(baofu);
    ref_185 = bustupLoad(bustup_2e);
    bustupWait(ref_185);
    ref_187 = bustupAlloc(ref_185, left, rgb(0,0,0));
    bustupFade(ref_187, rgb(128,0,0), 30);
    ref_189 = dialogAlloc();
    ref_18a = msgShow(msg_14);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]占いだの神さんだの、
[tab]何かに頼らなきゃ何もできねぇのか、この連中は？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_18a);
    unitWait(baofu);
    unitAnimationPlay(baofu, animation_a, 1);
    ref_18f = msgShow(msg_15);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]あん？[tab]ペルソナはいいのかだと？
[tab]前にも言わなかったか？
[tab]ペルソナなんざ道具だ。道具はいいんだよ…
[wait][clear]
***************************************/
    wait(ref_18f);
    dialogFree(ref_189);
    ref_192 = bustupFade(ref_187, rgb(0,0,0), 10);
    bustupWait(ref_192);
    bustupFree(ref_187);
    unitAnimationPlay(baofu, animation_a, 1);
    unitRestoreFacing(baofu);
    b(label_1c7);
  label_198:
    unitFacePlayer(baofu);
    ref_199 = bustupLoad(bustup_31);
    bustupWait(ref_199);
    ref_19b = bustupAlloc(ref_199, left, rgb(0,0,0));
    bustupFade(ref_19b, rgb(128,0,0), 30);
    ref_19d = dialogAlloc();
    ref_19e = msgShow(msg_16);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]あ？[tab]２５人殺したというのは本当かって？
[tab]２５匹の間違いじゃねぇか？
[tab]俺は人を殺めたつもりはねえぜ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_19e);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_19d);
    ref_1a3 = bustupFade(ref_19b, rgb(0,0,0), 10);
    bustupWait(ref_1a3);
    bustupFree(ref_19b);
    unitRestoreFacing(baofu);
    b(label_1c7);
  label_1a8:
    unitFacePlayer(baofu);
    ref_1a9 = bustupLoad(bustup_2d);
    bustupWait(ref_1a9);
    ref_1ab = bustupAlloc(ref_1a9, left, rgb(0,0,0));
    bustupFade(ref_1ab, rgb(128,0,0), 30);
    ref_1ad = dialogAlloc();
    ref_1ae = msgShow(msg_17);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]女って奴は、怒り出すと手がつけられんな…
[tab]それとも芹沢が特別なのか？
[tab]ったく…二度とあんな役は御免だからな。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1ae);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1ad);
    ref_1b3 = bustupFade(ref_1ab, rgb(0,0,0), 10);
    bustupWait(ref_1b3);
    bustupFree(ref_1ab);
    unitRestoreFacing(baofu);
    b(label_1c7);
  label_1b8:
    unitFacePlayer(baofu);
    ref_1b9 = bustupLoad(bustup_31);
    bustupWait(ref_1b9);
    ref_1bb = bustupAlloc(ref_1b9, left, rgb(0,0,0));
    bustupFade(ref_1bb, rgb(128,0,0), 30);
    ref_1bd = dialogAlloc();
    ref_1be = msgShow(msg_18);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]もしかしたら、あのスニークって野郎は、
[tab]坊ちゃんやお嬢ちゃんの居所をつきとめる為に、
[tab]俺達に情報を流したのかもなぁ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1be);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1bd);
    ref_1c3 = bustupFade(ref_1bb, rgb(0,0,0), 10);
    bustupWait(ref_1c3);
    bustupFree(ref_1bb);
    unitRestoreFacing(baofu);
  label_1c7:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_1dc);
    unitFacePlayer(nanjo);
    ref_1cd = bustupLoad(bustup_36);
    bustupWait(ref_1cd);
    ref_1cf = bustupAlloc(ref_1cd, left, rgb(0,0,0));
    bustupFade(ref_1cf, rgb(128,0,0), 30);
    ref_1d1 = dialogAlloc();
    ref_1d2 = msgShow(msg_19);
/***************************************
[color(yellow)]南条[color(white)]
[tab]所詮、運は天にあり…
[tab]どのような手法を用いて占おうと、
[tab]その理は変わりません。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_1d2);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1d1);
    ref_1d7 = bustupFade(ref_1cf, rgb(0,0,0), 10);
    bustupWait(ref_1d7);
    bustupFree(ref_1cf);
    unitRestoreFacing(nanjo);
    b(label_1eb);
  label_1dc:
    unitFacePlayer(nanjo);
    ref_1dd = bustupLoad(bustup_36);
    bustupWait(ref_1dd);
    ref_1df = bustupAlloc(ref_1dd, left, rgb(0,0,0));
    bustupFade(ref_1df, rgb(128,0,0), 30);
    ref_1e1 = dialogAlloc();
    ref_1e2 = msgShow(msg_20);
/***************************************
[color(yellow)]南条[color(white)]
[tab]我々のやり方に、疑問を抱く事もあるでしょう。
[tab]だが、全ては故あっての事と理解して欲しい。
[tab]こちらにも守らねばならぬ物がある。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_1e2);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1e1);
    ref_1e7 = bustupFade(ref_1df, rgb(0,0,0), 10);
    bustupWait(ref_1e7);
    bustupFree(ref_1df);
    unitRestoreFacing(nanjo);
  label_1eb:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_212);
    bitGet(var_0, MBIT_HI_GYPSTART);
    bnz(var_0, label_202);
    unitFacePlayer(elly);
    ref_1f3 = bustupLoad(bustup_3d);
    bustupWait(ref_1f3);
    ref_1f5 = bustupAlloc(ref_1f3, left, rgb(0,0,0));
    bustupFade(ref_1f5, rgb(128,0,0), 30);
    ref_1f7 = dialogAlloc();
    ref_1f8 = msgShow(msg_21);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｔａｒｏｔと水晶を同時に使うなんて、
[tab]変わった占い師さんですわね。
[tab]到底…当たるとは思えませんけど…
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_1a, 1);
    wait(ref_1f8);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_1f7);
    ref_1fd = bustupFade(ref_1f5, rgb(0,0,0), 10);
    bustupWait(ref_1fd);
    bustupFree(ref_1f5);
    unitRestoreFacing(elly);
    b(label_22c);
  label_202:
    unitFacePlayer(elly);
    ref_203 = bustupLoad(bustup_41);
    bustupWait(ref_203);
    ref_205 = bustupAlloc(ref_203, left, rgb(0,0,0));
    bustupFade(ref_205, rgb(128,0,0), 30);
    ref_207 = dialogAlloc();
    ref_208 = msgShow(msg_22);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]あら…
[tab]確かここは、Ｔａｒｏｔ占いだったんじゃ…
[tab]路線、変えたんでしょうか…
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_208);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_207);
    ref_20d = bustupFade(ref_205, rgb(0,0,0), 10);
    bustupWait(ref_20d);
    bustupFree(ref_205);
    unitRestoreFacing(elly);
    b(label_22c);
  label_212:
    unitFacePlayer(elly);
    ref_213 = bustupLoad(bustup_3d);
    bustupWait(ref_213);
    ref_215 = bustupAlloc(ref_213, left, rgb(0,0,0));
    bustupFade(ref_215, rgb(128,0,0), 30);
    ref_217 = dialogAlloc();
    ref_218 = msgShow(msg_23);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]ＪＯＫＥＲという恐ろしい存在を背景に出し、
[tab]救いの道として、ある行動を提示する
[tab]彼女のお告げは、脅迫と同じですわ。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_218);
    ref_21b = bustupFade(ref_215, rgb(0,0,0), 10);
    bustupWait(ref_21b);
    bustupFree(ref_215);
    unitAnimationPlay(elly, animation_a, 1);
    ref_21f = bustupLoad(bustup_42);
    bustupWait(ref_21f);
    ref_221 = bustupAlloc(ref_21f, left, rgb(0,0,0));
    bustupFade(ref_221, rgb(128,0,0), 30);
    ref_223 = msgShow(msg_24);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]けれど人々は、先の占いを通して、
[tab]Ｗａｎｇｌｏｎｇ千鶴に絶対の信頼を持ってる…
[tab]このままでは、全てが新世塾の思うがままです。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_6, 1);
    wait(ref_223);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_217);
    ref_228 = bustupFade(ref_221, rgb(0,0,0), 10);
    bustupWait(ref_228);
    bustupFree(ref_221);
    unitRestoreFacing(elly);
  label_22c:
    controlEnable();
}

function B_TATU()
{
}

function SAGIBOX()
{
    controlDisable();
    unitFacePlayer(makimura);
    ref_231 = bustupLoad(bustup_d4);
    bustupWait(ref_231);
    ref_233 = bustupAlloc(ref_231, right, rgb(0,0,0));
    bustupFade(ref_233, rgb(128,0,0), 30);
    ref_235 = dialogAlloc();
    ref_236 = msgShow(msg_25);
/***************************************
[color(yellow)]牧村[color(white)]
[tab]あの占い師の声…
[tab]どこかで聞いたことがあるような気が…
[tab]何か、それで酷い目にあったような…
[wait][clear]
***************************************/
    unitAnimationPlay(makimura, animation_24, 1);
    wait(ref_236);
    unitAnimationPlay(makimura, animation_0, 1);
    dialogFree(ref_235);
    ref_23b = bustupFade(ref_233, rgb(0,0,0), 10);
    bustupWait(ref_23b);
    bustupFree(ref_233);
    controlEnable();
}

function KIGATIISAI()
{
    controlDisable();
    bitGet(var_0, MBIT_SH_S_07);
    bne(var_0, 0, label_244);
    b(label_251);
  label_244:
    bne(var_0, 1, label_251);
    bitGet(var_0, MBIT_SH_H_07);
    bne(var_0, 0, label_24e);
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_24b);
    b(label_252);
    b(label_24d);
  label_24b:
    bne(var_0, 1, label_24d);
    b(label_24d);
  label_24d:
    b(label_250);
  label_24e:
    bne(var_0, 1, label_250);
    b(label_250);
  label_250:
    b(label_251);
  label_251:
    b(label_29c);
  label_252:
    add(var_a, var_a, 1);
    boutrange(var_a, 0, 1, label_256);
    b(label_25a);
    b(label_25a);
  label_256:
    bne(var_a, 2, label_25a);
    sub(var_a, var_a, 2);
    b(label_263);
    b(label_25a);
  label_25a:
    unitFacePlayer(npc1);
    ref_25b = dialogAlloc();
    ref_25c = msgShow(msg_26);
/***************************************
[color(yellow)]気の小さな男[color(white)]
[tab]ボクってネ…
[tab]気が小さいもんだから…ダメなんだよネ…
[tab]何がダメかって…決断するの苦手なんだよネ…
[wait][clear][color(yellow)]気の小さな男[color(white)]
[tab]だからいつもこうして、
[tab]占ってもらうのよネ…
[tab]誰だって失敗は怖いもんネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_25c);
    dialogFree(ref_25b);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    b(label_35f);
  label_263:
    unitFacePlayer(npc1);
    ref_264 = dialogAlloc();
    ref_265 = msgShow(msg_27);
/***************************************
[color(yellow)]気の小さな男[color(white)]
[tab]あの…何なのかな？
[tab]ボクに何か用なのかな？
[tab]だったらサッサと言ってほしいのネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_265);
    dialogFree(ref_264);
    unitAnimationPlay(npc1, animation_0, 1);
    choiceSetResult(2);
    ref_26b = bustupLoad(bustup_1);
    bustupWait(ref_26b);
    ref_26d = bustupAlloc(ref_26b, center, rgb(0,0,0));
    bustupFade(ref_26d, rgb(128,0,0), 30);
    ref_26f = dialogChoiceAlloc();
    ref_270 = msgShow(msg_28);
/***************************************
[tab]んで…何の用かな？
[choice(3)]名前を言い当てる
話をする
用はない
[end_choice][clear]
***************************************/
    ref_271 = textInputInit();
    wait(ref_270);
    dialogFree(ref_26f);
    ref_274 = bustupFade(ref_26d, rgb(0,0,0), 10);
    bustupWait(ref_274);
    bustupFree(ref_26d);
    wait(ref_271);
    choiceGetResult(var_0);
    bne(var_0, 0, label_27c);
    b(label_284);
    b(label_284);
  label_27c:
    bne(var_0, 1, label_280);
    unitRestoreFacing(npc1);
    b(label_29c);
    b(label_284);
  label_280:
    bne(var_0, 2, label_284);
    unitRestoreFacing(npc1);
    b(label_35f);
    b(label_284);
  label_284:
    ref_284 = textInputPrompt();
    wait(ref_284);
    textInputCompare(msg_29, var_0);
    bne(var_0, 0, label_290);
    ref_288 = dialogAlloc();
    ref_289 = msgShow(msg_30);
/***************************************
[color(yellow)]気の小さな男[color(white)]
[tab]それって誰かな？
[tab]ボクの知らない名前だけれど…
[tab]誰かと勘違いしてるんでない？
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_289);
    dialogFree(ref_288);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    b(label_29b);
  label_290:
    bne(var_0, 1, label_29b);
    ref_291 = dialogAlloc();
    ref_292 = msgShow(msg_31);
/***************************************
[color(yellow)]気の小さな男[color(white)]
[tab]ドキッ！？
[tab]どうしてボクの名前しってるのかな？
[tab]もしかしてキミ、超能力な人？
[wait][clear][color(yellow)]イケナカ[tab]ユウタ[color(white)]
[tab]なになに、人捜し？
[tab]ボクの捜索願が出てたの？
[tab]こりゃまたビックリなのネ。
[wait][clear][color(yellow)]イケナカ[tab]ユウタ[color(white)]
[tab]まあ事情はわかったから、了解なのネ。
[tab]しらいしさんにはボクから連絡しておくし、
[tab]とりあえずありがとサンネ。
[wait][clear]
***************************************/
    bitSet(MBIT_IKENAKA_GET);
    bitSet(MBIT_SH_HH);
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_292);
    dialogFree(ref_291);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    b(label_29b);
  label_29b:
    b(label_35f);
  label_29c:
    bitGet(var_0, MBIT_ZIPUMIHA_01);
    bnz(var_0, label_304);
    bitGet(var_0, MBIT_HI_GYPAISHO2);
    bnz(var_0, label_2ea);
    bitGet(var_0, MBIT_ZIPUMIHA_02);
    bnz(var_0, label_304);
    bitGet(var_0, MBIT_ZIPUMIHA_03);
    bnz(var_0, label_2c7);
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bnz(var_0, label_2b6);
    unitFacePlayer(npc1);
    ref_2a7 = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2ac);
    msgShow(msg_32);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2af);
  label_2ac:
    bne(var_0, 1, label_2af);
    msgShow(msg_33);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2af);
  label_2af:
    ref_2af = msgShow(msg_34);
/***************************************
[tab]最近ここでワンロン占いを始めたらしいんだよネ。
[tab]しかも良く当たるって、既に評判なんだよネ。
[tab]だから来てみたんだけど…やっぱドキドキするネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_2af);
    dialogFree(ref_2a7);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    b(label_35f);
  label_2b6:
    unitFacePlayer(npc1);
    ref_2b7 = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2bc);
    msgShow(msg_35);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2bf);
  label_2bc:
    bne(var_0, 1, label_2bf);
    msgShow(msg_36);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2bf);
  label_2bf:
    ref_2bf = msgShow(msg_37);
/***************************************
[tab]あの占い師さん、何でもやっちゃうんだネ。
[tab]今度は相性占いを始めたんだってネ。
[tab]だけど、男と相性良くなってもボクは悲しいネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_2bf);
    dialogFree(ref_2b7);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    bitSet(MBIT_ZIPUMIHA_03);
    b(label_35f);
  label_2c7:
    unitFacePlayer(npc1);
    ref_2c8 = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2cd);
    msgShow(msg_38);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2d0);
  label_2cd:
    bne(var_0, 1, label_2d0);
    msgShow(msg_39);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2d0);
  label_2d0:
    ref_2d0 = msgShow(msg_40);
/***************************************
[tab]ここでは相性占いもよく当たると評判だよネ。
[tab]店主さんと相性良くしておくと、
[tab]ホントにオマケしてもらえたりするもんネ。
[wait][clear]
***************************************/
    wait(ref_2d0);
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2d6);
    msgShow(msg_41);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2d9);
  label_2d6:
    bne(var_0, 1, label_2d9);
    msgShow(msg_42);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2d9);
  label_2d9:
    ref_2d9 = msgShow(msg_43);
/***************************************
[tab]だけどネ、
[tab]相性が良くなったからって、
[tab]必ず見返りがあるとは限らないのよネ。
[wait][clear]
***************************************/
    wait(ref_2d9);
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2df);
    msgShow(msg_44);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2e2);
  label_2df:
    bne(var_0, 1, label_2e2);
    msgShow(msg_45);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2e2);
  label_2e2:
    ref_2e2 = msgShow(msg_46);
/***************************************
[tab]相性なんて気にしない人だっているし、
[tab]例えそれを感じていても、
[tab]表に出さない人もいるもんネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_2e2);
    dialogFree(ref_2c8);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    bitSet(MBIT_ZIPUMIHA_02);
    b(label_35f);
  label_2ea:
    unitFacePlayer(npc1);
    ref_2eb = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2f0);
    msgShow(msg_47);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2f3);
  label_2f0:
    bne(var_0, 1, label_2f3);
    msgShow(msg_48);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2f3);
  label_2f3:
    ref_2f3 = msgShow(msg_49);
/***************************************
[tab]占い師さんがパワーアップしたみたいだネ。
[tab]どうパワーアップしたかって、相性占いだネ。
[tab]答えで出てくる人が増えたらしいんだよネ。
[wait][clear]
***************************************/
    wait(ref_2f3);
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_2f9);
    msgShow(msg_50);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_2fc);
  label_2f9:
    bne(var_0, 1, label_2fc);
    msgShow(msg_51);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_2fc);
  label_2fc:
    ref_2fc = msgShow(msg_52);
/***************************************
[tab]サトミタダシのおばちゃんが出てきたという人…
[tab]今がチャンスなのネ。
[tab]意外な人と会えるかもネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_2fc);
    dialogFree(ref_2eb);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    bitSet(MBIT_ZIPUMIHA_01);
    b(label_35f);
  label_304:
    bitGet(var_0, MBIT_ZIPUMIHA_04);
    bne(var_0, 0, label_314);
    bitGet(var_0, MBIT_ZIPUMIHA_05);
    bne(var_0, 0, label_310);
    bitGet(var_0, MBIT_ZIPUMIHA_06);
    bne(var_0, 0, label_30c);
    b(label_31d);
    b(label_30f);
  label_30c:
    bne(var_0, 1, label_30f);
    b(label_32e);
    b(label_30f);
  label_30f:
    b(label_313);
  label_310:
    bne(var_0, 1, label_313);
    b(label_33f);
    b(label_313);
  label_313:
    b(label_31d);
  label_314:
    bne(var_0, 1, label_31d);
    bitGet(var_0, EBIT_E0043);
    bne(var_0, 0, label_319);
    b(label_33f);
    b(label_31c);
  label_319:
    bne(var_0, 1, label_31c);
    b(label_350);
    b(label_31c);
  label_31c:
    b(label_31d);
  label_31d:
    unitFacePlayer(npc1);
    ref_31e = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_323);
    msgShow(msg_53);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_326);
  label_323:
    bne(var_0, 1, label_326);
    msgShow(msg_54);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_326);
  label_326:
    ref_326 = msgShow(msg_55);
/***************************************
[tab]ボクは１２月生まれだから、
[tab]ワンロン占いで言うと紫龍になるんだよネ。
[tab]とっても直感的なタイプらしいんだよネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_326);
    dialogFree(ref_31e);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    bitSet(MBIT_ZIPUMIHA_06);
    b(label_35f);
  label_32e:
    unitFacePlayer(npc1);
    ref_32f = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_334);
    msgShow(msg_56);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_337);
  label_334:
    bne(var_0, 1, label_337);
    msgShow(msg_57);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_337);
  label_337:
    ref_337 = msgShow(msg_58);
/***************************************
[tab]ワンロン占いはネ、元は望龍術らしいんだよネ。
[tab]望龍術って言うのはネ…よく分からないのよネ。
[tab]まあ、当たるなら何でもいいんだけどネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_337);
    dialogFree(ref_32f);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    bitSet(MBIT_ZIPUMIHA_05);
    b(label_35f);
  label_33f:
    unitFacePlayer(npc1);
    ref_340 = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_345);
    msgShow(msg_59);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_348);
  label_345:
    bne(var_0, 1, label_348);
    msgShow(msg_60);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_348);
  label_348:
    ref_348 = msgShow(msg_61);
/***************************************
[tab]ぼ…ボクはＪＯＫＥＲ呪いなんかしてないのネ。
[tab]いや…したいと思ったことはあるけど、
[tab]やっぱり止めといたのネ。正解だったネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_348);
    dialogFree(ref_340);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
    bitSet(MBIT_ZIPUMIHA_04);
    b(label_35f);
  label_350:
    unitFacePlayer(npc1);
    ref_351 = dialogAlloc();
    bitGet(var_0, MBIT_IKENAKA_GET);
    bne(var_0, 0, label_356);
    msgShow(msg_62);
/***************************************
[color(yellow)]気の小さな男[color(white)]

***************************************/
    b(label_359);
  label_356:
    bne(var_0, 1, label_359);
    msgShow(msg_63);
/***************************************
[color(yellow)]イケナカ[tab]ユウタ[color(white)]

***************************************/
    b(label_359);
  label_359:
    ref_359 = msgShow(msg_64);
/***************************************
[tab]望龍術によると、
[tab]地脈は全て、龍に例えられるようなのネ。
[tab]その龍は１２匹もいるらしいんだよネ。
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_21, 1);
    wait(ref_359);
    dialogFree(ref_351);
    unitAnimationPlay(npc1, animation_0, 1);
    unitRestoreFacing(npc1);
  label_35f:
    controlEnable();
}

function WAKAIOTOKO()
{
    controlDisable();
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_38f);
    bitGet(var_0, EBIT_E0033);
    bnz(var_0, label_386);
    bitGet(var_0, EBIT_E002B);
    bnz(var_0, label_37d);
    bitGet(var_0, MBIT_ZIPTALKOTOKT_01);
    bnz(var_0, label_374);
    unitFacePlayer(npc2);
    ref_36b = dialogAlloc();
    ref_36c = msgShow(msg_65);
/***************************************
[color(yellow)]若い男[color(white)]
[tab]噂聞いて来たんだけどさ、
[tab]ここもワンロン占い始めたんだって？
[tab]つーか、占いってそんなコロコロ変えられんの？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_21, 1);
    wait(ref_36c);
    dialogFree(ref_36b);
    unitAnimationPlay(npc2, animation_0, 1);
    unitRestoreFacing(npc2);
    bitSet(MBIT_ZIPTALKOTOKT_01);
    b(label_397);
  label_374:
    unitFacePlayer(npc2);
    ref_375 = dialogAlloc();
    ref_376 = msgShow(msg_66);
/***************************************
[color(yellow)]若い男[color(white)]
[tab]ワンロン占いってあんな呪文だったっけな？
[tab]なんか違う気がする…
[tab]もしかして、ワンロンって言ってるだけか？
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_21, 1);
    wait(ref_376);
    dialogFree(ref_375);
    unitAnimationPlay(npc2, animation_0, 1);
    unitRestoreFacing(npc2);
    b(label_397);
  label_37d:
    unitFacePlayer(npc2);
    ref_37e = dialogAlloc();
    ref_37f = msgShow(msg_67);
/***************************************
[color(yellow)]若い男[color(white)]
[tab]俺見ちまったよ！
[tab]何をって、飛んでたんだよ飛行船が！
[tab]い…いや、飛行船は飛ぶモノだけど…つまり…
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_21, 1);
    wait(ref_37f);
    dialogFree(ref_37e);
    unitAnimationPlay(npc2, animation_0, 1);
    unitRestoreFacing(npc2);
    b(label_397);
  label_386:
    unitFacePlayer(npc2);
    ref_387 = dialogAlloc();
    ref_388 = msgShow(msg_68);
/***************************************
[color(yellow)]若い男[color(white)]
[tab]あのテレビ見てから、知り合い大慌てでさ。
[tab]なんでも恋敵にＪＯＫＥＲ呪いしたらしいんだ。
[tab]だからって、ＪＯＫＥＲになる訳無いだろっての。
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_21, 1);
    wait(ref_388);
    dialogFree(ref_387);
    unitAnimationPlay(npc2, animation_0, 1);
    unitRestoreFacing(npc2);
    b(label_397);
  label_38f:
    unitFacePlayer(npc2);
    ref_390 = dialogAlloc();
    ref_391 = msgShow(msg_69);
/***************************************
[color(yellow)]若い男[color(white)]
[tab]やべぇよ。俺の知り合いが警察に捕まっちまった。
[tab]なんでも、暴行の現行犯だって…
[tab]大人しいヤツだったのに、どうして…
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_21, 1);
    wait(ref_391);
    dialogFree(ref_390);
    unitAnimationPlay(npc2, animation_0, 1);
    unitRestoreFacing(npc2);
  label_397:
    controlEnable();
}

function SHOPBOX()
{
    bitGet(var_0, MBIT_ZIPMODORI);
    bne(var_0, 0, label_3b5);
    controlDisable();
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    playerConvertToUnit(maya, sprite_0, east);
    playerHide();
    unitDespawn(maya, none);
    ref_3a5 = cameraRotateTo(1, 10);
    ref_3a6 = cameraMoveTo(583, 0, -427, 10);
    wait(ref_3a5);
    wait(ref_3a6);
    ref_3a9 = spriteLoad(sprite_1);
    wait(ref_3a9);
    unitSpawn3d(maya, sprite_1, 613, -50, -493, south, none);
    unitAnimationPlay(maya, animation_12, 1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_3b2 = shopOverlayInit();
    wait(ref_3b2);
    b(label_3d1);
  label_3b5:
    bne(var_0, 1, label_3d1);
    shopInventory(3, shopInventory_384);
    ref_3b7 = shopOverlayInit();
    wait(ref_3b7);
    bitClear(MBIT_ZIPMODORI);
    ref_3ba = bustupLoad(bustup_ea);
    bustupWait(ref_3ba);
    ref_3bc = bustupAlloc(ref_3ba, right, rgb(0,0,0));
    bustupFade(ref_3bc, rgb(128,0,0), 30);
    ref_3be = dialogAlloc();
    ref_3bf = msgShow(msg_70);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]他にご用はあるかな？
[tab]何なりと打ち明けるが良い。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_3bf);
    dialogFree(ref_3be);
    ref_3c7 = bustupFade(ref_3bc, rgb(0,0,0), 10);
    bustupWait(ref_3c7);
    bustupFree(ref_3bc);
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bne(var_0, 0, label_3cd);
    b(label_3cf);
  label_3cd:
    bne(var_0, 1, label_3cf);
    b(label_3cf);
  label_3cf:
    b(label_4d5);
    b(label_3d1);
  label_3d1:
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitGet(var_0, MBIT_HI_GYPAISHO2);
    bne(var_0, 0, label_3f8);
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bne(var_0, 0, label_3ed);
    bitGet(var_0, MBIT_HI_GYPSTART);
    bne(var_0, 0, label_3e2);
    bitSet(LBIT_0004);
    bitGet(var_0, MBIT_ZIPZIPISATU);
    bne(var_0, 0, label_3de);
    b(label_402);
    b(label_3e1);
  label_3de:
    bne(var_0, 1, label_3e1);
    b(label_4c0);
    b(label_3e1);
  label_3e1:
    b(label_3ec);
  label_3e2:
    bne(var_0, 1, label_3ec);
    bitSet(LBIT_0003);
    bitGet(var_0, MBIT_ZIPZIPWANRON);
    bne(var_0, 0, label_3e8);
    b(label_42a);
    b(label_3eb);
  label_3e8:
    bne(var_0, 1, label_3eb);
    b(label_4c0);
    b(label_3eb);
  label_3eb:
    b(label_3ec);
  label_3ec:
    b(label_3f7);
  label_3ed:
    bne(var_0, 1, label_3f7);
    bitSet(LBIT_0003);
    bitGet(var_0, MBIT_ZIPZIPISYOUAISATU);
    bne(var_0, 0, label_3f3);
    b(label_45c);
    b(label_3f6);
  label_3f3:
    bne(var_0, 1, label_3f6);
    b(label_4c0);
    b(label_3f6);
  label_3f6:
    b(label_3f7);
  label_3f7:
    b(label_402);
  label_3f8:
    bne(var_0, 1, label_402);
    bitSet(LBIT_0003);
    bitGet(var_0, MBIT_ZIPZIPPOWEUP);
    bne(var_0, 0, label_3fe);
    b(label_48e);
    b(label_401);
  label_3fe:
    bne(var_0, 1, label_401);
    b(label_4c0);
    b(label_401);
  label_401:
    b(label_402);
  label_402:
    ref_402 = bustupLoad(bustup_ea);
    bustupWait(ref_402);
    ref_404 = bustupAlloc(ref_402, right, rgb(0,0,0));
    bustupFade(ref_404, rgb(128,0,0), 30);
    ref_406 = dialogAlloc();
    ref_407 = msgShow(msg_71);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ここは人生という迷宮に迷った者が訪れる場所。
[tab]暗澹たる未来に一筋の光明を放ち、進むべき道筋を
[tab]指し示す場所。妾はその番人、珠閒瑠ジニー。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_407);
    ref_414 = msgShow(msg_72);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(green)]
[tab]ハスキーボイスが、美人を連想させる占い師。
[tab]最近は、あまり当たらないと人気も低迷気味。
[tab]夜の街で、よく似た後姿を見かけたという噂も…[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_414);
    ref_417 = msgShow(msg_73);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ほう、汝、ここを訪れるは初めてか？
[tab]ならば安心してその胸中、打ち明けるがよい。
[tab]この水晶とカードが必ずや光明を齎そうぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_417);
    dialogFree(ref_406);
    ref_425 = bustupFade(ref_404, rgb(0,0,0), 10);
    bustupWait(ref_425);
    bustupFree(ref_404);
    bitSet(MBIT_ZIPZIPISATU);
    b(label_4d5);
  label_42a:
    ref_42a = bustupLoad(bustup_ea);
    bustupWait(ref_42a);
    ref_42c = bustupAlloc(ref_42a, right, rgb(0,0,0));
    bustupFade(ref_42c, rgb(128,0,0), 30);
    ref_42e = dialogAlloc();
    ref_42f = msgShow(msg_74);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお、先日の客人じゃな。
[tab]実は最近、妾がワンロン占いを始めたらしいと、
[tab]どこからともなく噂が流れてな。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_42f);
    ref_43c = msgShow(msg_75);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]仕方ないからそれに合わせてたら、
[tab]本当に占いが当たるようになったのじゃ！！
[tab]これぞ神の思し召し！[tab]超ラッキー！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_43c);
    ref_449 = msgShow(msg_76);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]これからは妾の齎す答え全てが現実となろう！
[tab]ささ、今度は大丈夫じゃ。
[tab]安心してその胸中、打ち明けるがよい。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_449);
    dialogFree(ref_42e);
    ref_457 = bustupFade(ref_42c, rgb(0,0,0), 10);
    bustupWait(ref_457);
    bustupFree(ref_42c);
    bitSet(MBIT_ZIPZIPWANRON);
    b(label_4d5);
  label_45c:
    ref_45c = bustupLoad(bustup_ea);
    bustupWait(ref_45c);
    ref_45e = bustupAlloc(ref_45c, right, rgb(0,0,0));
    bustupFade(ref_45e, rgb(128,0,0), 30);
    ref_460 = dialogAlloc();
    ref_461 = msgShow(msg_77);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うーむ…
[tab]妾は相性占いもしておったのか？
[tab]いや…していたような気もするが…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_461);
    ref_46e = msgShow(msg_78);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ま…まあ、何事も挑戦じゃ。
[tab]ワンロン占いもそれで始めたようなものじゃしな。
[tab]では、気を取りなおして…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_46e);
    ref_47b = msgShow(msg_79);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]新たに相性占いを始めたぞよ。
[tab]汝が望むならば、汝と相性がピタリと合う人物を、
[tab]この水晶に映し出してみせよう。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_47b);
    dialogFree(ref_460);
    ref_489 = bustupFade(ref_45e, rgb(0,0,0), 10);
    bustupWait(ref_489);
    bustupFree(ref_45e);
    bitSet(MBIT_ZIPZIPISYOUAISATU);
    b(label_4d5);
  label_48e:
    ref_48e = bustupLoad(bustup_ea);
    bustupWait(ref_48e);
    ref_490 = bustupAlloc(ref_48e, right, rgb(0,0,0));
    bustupFade(ref_490, rgb(128,0,0), 30);
    ref_492 = dialogAlloc();
    ref_493 = msgShow(msg_80);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]最近、妾に関して妙な噂ばかり流れて困る。
[tab]今度は、妾がパワーアップしたそうじゃ…
[tab]パワーアップって…つまりどうすれば良いのじゃ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_493);
    ref_4a0 = msgShow(msg_81);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]まぁ…やってやれない事はなし…
[tab]ワンロン占いもそうだったしな。
[tab]ここは開き直るしかないか。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_4a0);
    ref_4ad = msgShow(msg_82);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]新たに始めた相性占い。日頃の修行が実を結び、
[tab]更に多くの相性を感じ取れるようになったぞ。
[tab]百聞は一見にしかず。まずは試してみるがよい。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_4ad);
    dialogFree(ref_492);
    ref_4bb = bustupFade(ref_490, rgb(0,0,0), 10);
    bustupWait(ref_4bb);
    bustupFree(ref_490);
    bitSet(MBIT_ZIPZIPPOWEUP);
    b(label_4d5);
  label_4c0:
    ref_4c0 = bustupLoad(bustup_ea);
    bustupWait(ref_4c0);
    ref_4c2 = bustupAlloc(ref_4c0, right, rgb(0,0,0));
    bustupFade(ref_4c2, rgb(128,0,0), 30);
    ref_4c4 = dialogAlloc();
    ref_4c5 = msgShow(msg_83);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]よく来たな。

[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_4c5);
    dialogFree(ref_4c4);
    ref_4cd = bustupFade(ref_4c2, rgb(0,0,0), 10);
    bustupWait(ref_4cd);
    bustupFree(ref_4c2);
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bne(var_0, 0, label_4d3);
    b(label_4d5);
  label_4d3:
    bne(var_0, 1, label_4d5);
    b(label_4d5);
  label_4d5:
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bne(var_0, 0, label_503);
    choiceSetResult(2);
    ref_4d8 = bustupLoad(bustup_ea);
    bustupWait(ref_4d8);
    ref_4da = bustupAlloc(ref_4d8, right, rgb(0,0,0));
    bustupFade(ref_4da, rgb(128,0,0), 30);
    ref_4dc = dialogAlloc();
    ref_4dd = msgShow(msg_84);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]して、本日はいかなる用件じゃ？
[choice(4)]占い
話を聞く
用は無い
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    wait(ref_4dd);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4e8);
    call(HA_SHOP_FORTUNE_0);
    b(label_4fe);
  label_4e8:
    bne(var_0, 1, label_4f7);
    choiceSetResult(2);
    ref_4ea = msgShow(msg_85);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear]
***************************************/
    wait(ref_4ea);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4f0);
    call(HA_SHOP_TALK_0);
    b(label_4f6);
  label_4f0:
    bne(var_0, 1, label_4f3);
    call(HA_SHOP_EXPLAIN_0);
    b(label_4f6);
  label_4f3:
    bne(var_0, 2, label_4f6);
    call(HOKANI_SELECT);
    b(label_4f6);
  label_4f6:
    b(label_4fe);
  label_4f7:
    bne(var_0, 2, label_4fa);
    call(HA_SHOP_END_0);
    b(label_4fe);
  label_4fa:
    bne(var_0, 3, label_4fe);
    bitSet(MBIT_EXITBIT);
    call(HA_SHOP_END_0);
    b(label_4fe);
  label_4fe:
    dialogFree(ref_4dc);
    ref_4ff = bustupFade(ref_4da, rgb(0,0,0), 10);
    bustupWait(ref_4ff);
    bustupFree(ref_4da);
    b(label_533);
  label_503:
    bne(var_0, 1, label_533);
    choiceSetResult(3);
    ref_505 = bustupLoad(bustup_ea);
    bustupWait(ref_505);
    ref_507 = bustupAlloc(ref_505, right, rgb(0,0,0));
    bustupFade(ref_507, rgb(128,0,0), 30);
    ref_509 = dialogAlloc();
    ref_50a = msgShow(msg_86);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]して、本日はいかなる用件じゃ？
[choice(5)]占い
相性占い
話を聞く
用は無い
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    wait(ref_50a);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_515);
    call(HA_SHOP_FORTUNE_0);
    b(label_52e);
  label_515:
    bne(var_0, 1, label_518);
    call(HA_SHOP_FRIEND_0);
    b(label_52e);
  label_518:
    bne(var_0, 2, label_527);
    choiceSetResult(2);
    ref_51a = msgShow(msg_87);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear]
***************************************/
    wait(ref_51a);
    choiceGetResult(var_0);
    bne(var_0, 0, label_520);
    call(HA_SHOP_TALK_0);
    b(label_526);
  label_520:
    bne(var_0, 1, label_523);
    call(HA_SHOP_EXPLAIN_0);
    b(label_526);
  label_523:
    bne(var_0, 2, label_526);
    call(HOKANI_SELECT);
    b(label_526);
  label_526:
    b(label_52e);
  label_527:
    bne(var_0, 3, label_52a);
    call(HA_SHOP_END_0);
    b(label_52e);
  label_52a:
    bne(var_0, 4, label_52e);
    bitSet(MBIT_EXITBIT);
    call(HA_SHOP_END_0);
    b(label_52e);
  label_52e:
    dialogFree(ref_509);
    ref_52f = bustupFade(ref_507, rgb(0,0,0), 10);
    bustupWait(ref_52f);
    bustupFree(ref_507);
    b(label_533);
  label_533:
}

function HA_SHOP_RESTART_0()
{
    ref_534 = bustupLoad(bustup_ea);
    bustupWait(ref_534);
    ref_536 = bustupAlloc(ref_534, right, rgb(0,0,0));
    bustupFade(ref_536, rgb(128,0,0), 30);
    ref_538 = dialogAlloc();
    ref_539 = msgShow(msg_88);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]他にご用はあるかな？
[tab]何なりと打ち明けるが良い。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_539);
    dialogFree(ref_538);
    ref_541 = bustupFade(ref_536, rgb(0,0,0), 10);
    bustupWait(ref_541);
    bustupFree(ref_536);
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, MBIT_HI_GYPSTART);
    bez(var_0, label_550);
    bitGet(var_0, MBIT_ZIPTALKATARI);
    bez(var_0, label_567);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_5ad);
    bitGet(var_0, EBIT_E0033);
    bnz(var_0, label_596);
    bitGet(var_0, EBIT_E002B);
    bnz(var_0, label_57f);
    b(label_567);
  label_550:
    ref_550 = bustupLoad(bustup_ea);
    bustupWait(ref_550);
    ref_552 = bustupAlloc(ref_550, right, rgb(0,0,0));
    bustupFade(ref_552, rgb(128,0,0), 30);
    ref_554 = dialogAlloc();
    ref_555 = msgShow(msg_89);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ぶつぶつ…やはりこれからはワンロン占いかしら…
[tab]あれの方がよく当たるって噂なのよね…ぶつぶつ。
[tab]占い、変えようかしら…ぶつぶつ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_555);
    dialogFree(ref_554);
    ref_563 = bustupFade(ref_552, rgb(0,0,0), 10);
    bustupWait(ref_563);
    bustupFree(ref_552);
    b(label_5c3);
  label_567:
    ref_567 = bustupLoad(bustup_ea);
    bustupWait(ref_567);
    ref_569 = bustupAlloc(ref_567, right, rgb(0,0,0));
    bustupFade(ref_569, rgb(128,0,0), 30);
    ref_56b = dialogAlloc();
    ref_56c = msgShow(msg_90);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]また占いが当たるようになってなによりじゃ。
[tab]これを機に新しい占いに挑戦してみるか…
[tab]うーむ…やはり占いと言えば…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_56c);
    dialogFree(ref_56b);
    ref_57a = bustupFade(ref_569, rgb(0,0,0), 10);
    bustupWait(ref_57a);
    bustupFree(ref_569);
    bitSet(MBIT_ZIPTALKATARI);
    b(label_5c3);
  label_57f:
    ref_57f = bustupLoad(bustup_ea);
    bustupWait(ref_57f);
    ref_581 = bustupAlloc(ref_57f, right, rgb(0,0,0));
    bustupFade(ref_581, rgb(128,0,0), 30);
    ref_583 = dialogAlloc();
    ref_584 = msgShow(msg_91);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…占いのしすぎで少々疲れたか…
[tab]あの科学館の火災事故…前にも起きたような…
[tab]い、いや、そんなはずは無い。しっかりせねば。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_584);
    dialogFree(ref_583);
    ref_592 = bustupFade(ref_581, rgb(0,0,0), 10);
    bustupWait(ref_592);
    bustupFree(ref_581);
    b(label_5c3);
  label_596:
    ref_596 = bustupLoad(bustup_ea);
    bustupWait(ref_596);
    ref_598 = bustupAlloc(ref_596, right, rgb(0,0,0));
    bustupFade(ref_598, rgb(128,0,0), 30);
    ref_59a = dialogAlloc();
    ref_59b = msgShow(msg_92);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]テレビでワンロン千鶴なる人物を拝見したが…
[tab]妾もああいう服装に変えた方が良いかな？
[tab]呪文だけ変えてもどうも雰囲気に欠ける…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_59b);
    dialogFree(ref_59a);
    ref_5a9 = bustupFade(ref_598, rgb(0,0,0), 10);
    bustupWait(ref_5a9);
    bustupFree(ref_598);
    b(label_5c3);
  label_5ad:
    ref_5ad = bustupLoad(bustup_ea);
    bustupWait(ref_5ad);
    ref_5af = bustupAlloc(ref_5ad, right, rgb(0,0,0));
    bustupFade(ref_5af, rgb(128,0,0), 30);
    ref_5b1 = dialogAlloc();
    ref_5b2 = msgShow(msg_93);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]最近、街で神隠しが起きておるようじゃ。
[tab]被害者に共通点は無く、無差別誘拐とも聞く。
[tab]汝もか弱き乙女なれば、気をつけよ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_5b2);
    dialogFree(ref_5b1);
    ref_5c0 = bustupFade(ref_5af, rgb(0,0,0), 10);
    bustupWait(ref_5c0);
    bustupFree(ref_5af);
  label_5c3:
    call(HOKANI_SELECT);
}

function HA_SHOP_END_0()
{
    bitGet(var_0, MBIT_HI_GYPAISHO2);
    bne(var_0, 0, label_5e7);
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bne(var_0, 0, label_5d7);
    bitGet(var_0, MBIT_HI_GYPSTART);
    bne(var_0, 0, label_5d3);
    bitGet(var_0, MBIT_ZIPDAMEDAME);
    bne(var_0, 0, label_5cf);
    b(label_61b);
    b(label_5d2);
  label_5cf:
    bne(var_0, 1, label_5d2);
    b(label_5f6);
    b(label_5d2);
  label_5d2:
    b(label_5d6);
  label_5d3:
    bne(var_0, 1, label_5d6);
    b(label_61b);
    b(label_5d6);
  label_5d6:
    b(label_5e6);
  label_5d7:
    bne(var_0, 1, label_5e6);
    bitGet(var_0, MBIT_ZIPTRYAMODE);
    bne(var_0, 0, label_5dc);
    b(label_61b);
    b(label_5e5);
  label_5dc:
    bne(var_0, 1, label_5e5);
    bitGet(var_0, MBIT_ZIPCHUAMODE);
    bne(var_0, 0, label_5e1);
    b(label_633);
    b(label_5e4);
  label_5e1:
    bne(var_0, 1, label_5e4);
    b(label_61b);
    b(label_5e4);
  label_5e4:
    b(label_5e5);
  label_5e5:
    b(label_5e6);
  label_5e6:
    b(label_5f6);
  label_5e7:
    bne(var_0, 1, label_5f6);
    bitGet(var_0, MBIT_ZIPTRYBMODE);
    bne(var_0, 0, label_5ec);
    b(label_61b);
    b(label_5f5);
  label_5ec:
    bne(var_0, 1, label_5f5);
    bitGet(var_0, MBIT_ZIPCHUBMODE);
    bne(var_0, 0, label_5f1);
    b(label_64c);
    b(label_5f4);
  label_5f1:
    bne(var_0, 1, label_5f4);
    b(label_61b);
    b(label_5f4);
  label_5f4:
    b(label_5f5);
  label_5f5:
    b(label_5f6);
  label_5f6:
    ref_5f6 = bustupLoad(bustup_ea);
    bustupWait(ref_5f6);
    ref_5f8 = bustupAlloc(ref_5f6, right, rgb(0,0,0));
    bustupFade(ref_5f8, rgb(128,0,0), 30);
    ref_5fa = dialogAlloc();
    ref_5fb = msgShow(msg_94);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]済まんな…実はワンロン占いが流行り出してから、
[tab]なぜか妾の占いは
[tab]当たらなくなってしまったのじゃ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_5fb);
    ref_608 = msgShow(msg_95);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]鳴かず飛ばずの占い師…
[tab]これでは閑古鳥さえ近づかん…
[tab]なんとかせねば…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_608);
    shopOverlayInit();
    dialogFree(ref_5fa);
    ref_617 = bustupFade(ref_5f8, rgb(0,0,0), 10);
    bustupWait(ref_617);
    bustupFree(ref_5f8);
    b(label_664);
  label_61b:
    ref_61b = bustupLoad(bustup_ea);
    bustupWait(ref_61b);
    ref_61d = bustupAlloc(ref_61b, right, rgb(0,0,0));
    bustupFade(ref_61d, rgb(128,0,0), 30);
    ref_61f = dialogAlloc();
    ref_620 = msgShow(msg_96);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]己が道を見失いし時は、
[tab]いつでも来るが良い。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_620);
    shopOverlayInit();
    dialogFree(ref_61f);
    ref_62f = bustupFade(ref_61d, rgb(0,0,0), 10);
    bustupWait(ref_62f);
    bustupFree(ref_61d);
    b(label_664);
  label_633:
    ref_633 = bustupLoad(bustup_ea);
    bustupWait(ref_633);
    ref_635 = bustupAlloc(ref_633, right, rgb(0,0,0));
    bustupFade(ref_635, rgb(128,0,0), 30);
    ref_637 = dialogAlloc();
    ref_638 = msgShow(msg_97);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ちなみに妾の相性占いはコンタクトとは無関係。
[tab]コマンドが変化したりはせんぞ。
[tab]誤解せぬようにな。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_638);
    shopOverlayInit();
    dialogFree(ref_637);
    ref_647 = bustupFade(ref_635, rgb(0,0,0), 10);
    bustupWait(ref_647);
    bustupFree(ref_635);
    bitSet(MBIT_ZIPCHUAMODE);
    b(label_664);
  label_64c:
    ref_64c = bustupLoad(bustup_ea);
    bustupWait(ref_64c);
    ref_64e = bustupAlloc(ref_64c, right, rgb(0,0,0));
    bustupFade(ref_64e, rgb(128,0,0), 30);
    ref_650 = dialogAlloc();
    ref_651 = msgShow(msg_98);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ちなみにパワーアップしても、
[tab]妾の相性占いはコンタクトとは無関係じゃ。
[tab]コマンドが変化したりはせんぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_651);
    shopOverlayInit();
    dialogFree(ref_650);
    ref_660 = bustupFade(ref_64e, rgb(0,0,0), 10);
    bustupWait(ref_660);
    bustupFree(ref_64e);
    bitSet(MBIT_ZIPCHUBMODE);
  label_664:
    bitSet(MBIT_SUMARURIYOU);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_67b);
    ref_667 = spriteLoad(sprite_0);
    wait(ref_667);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    ref_66b = cameraMoveTo(485, -40, -538, 30);
    unitCollisionDisable(maya, false);
    unitMove(maya, 600, -454, face_north, fastest);
    unitWait(maya);
    unitMove(maya, 500, -454, face_north, medium);
    unitWait(maya);
    unitMove(maya, 485, -538, face_north, medium);
    unitWait(maya);
    wait(ref_66b);
    ref_674 = spriteLoad(sprite_2);
    wait(ref_674);
    unitDespawn(maya, none);
    playerInit(north);
    controlEnable();
    unitRevolveAnimationPlay(shopkeeper, animrevolve_f);
    b(label_67e);
  label_67b:
    bne(var_0, 1, label_67e);
    call(EXITBOX);
    b(label_67e);
  label_67e:
}

function HA_SHOP_FORTUNE_0()
{
    bitGet(var_0, MBIT_HI_GYPSTART);
    bnz(var_0, label_770);
    ref_681 = bustupLoad(bustup_ea);
    bustupWait(ref_681);
    ref_683 = bustupAlloc(ref_681, right, rgb(0,0,0));
    bustupFade(ref_683, rgb(128,0,0), 30);
    ref_685 = dialogAlloc();
    ref_686 = msgShow(msg_99);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]では、占ってしんぜよう。
[tab]アムアムアム…ロイスキャロルプレミアム…
[tab]水晶よ、この者の未来を映し出すがよい…
[sync][wait][clear]
***************************************/
    bitSet(MBIT_ZIPDAMEDAME);
    unitAnimationPlay(shopkeeper, animation_9, 1);
    sync();
    wait(ref_686);
    dialogFree(ref_685);
    ref_68c = bustupFade(ref_683, rgb(0,0,0), 10);
    bustupWait(ref_68c);
    bustupFree(ref_683);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), add);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), add);
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    rand(var_0, 4);
    bne(var_0, 0, label_6c7);
    ref_69d = bustupLoad(bustup_ea);
    bustupWait(ref_69d);
    ref_69f = bustupAlloc(ref_69d, right, rgb(0,0,0));
    bustupFade(ref_69f, rgb(128,0,0), 30);
    ref_6a1 = dialogAlloc();
    ref_6a2 = msgShow(msg_100);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…なんと、実はソナタ男じゃな？
[tab]その服装も髪型も全てはカモフラージュ、
[tab]もてぬ腹癒せに、他の男を騙して……
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_6a2);
    ref_6af = msgShow(msg_101);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_6af);
    ref_6b5 = msgShow(msg_102);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……違うわよね…
[tab]そんな訳無いわよね…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_6b5);
    dialogFree(ref_6a1);
    ref_6c3 = bustupFade(ref_69f, rgb(0,0,0), 10);
    bustupWait(ref_6c3);
    bustupFree(ref_69f);
    b(label_76f);
  label_6c7:
    bne(var_0, 1, label_6f2);
    ref_6c8 = bustupLoad(bustup_ea);
    bustupWait(ref_6c8);
    ref_6ca = bustupAlloc(ref_6c8, right, rgb(0,0,0));
    bustupFade(ref_6ca, rgb(128,0,0), 30);
    ref_6cc = dialogAlloc();
    ref_6cd = msgShow(msg_103);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]なるほどな。
[tab]ソナタには二人の子供がいるな。
[tab]一人は元気溌剌、小学一年生！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_6cd);
    ref_6da = msgShow(msg_104);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_6da);
    ref_6e0 = msgShow(msg_105);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……いないのね…
[tab]…独身なのよねきっと…
[tab]……分かってるわよそんなの…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_6e0);
    dialogFree(ref_6cc);
    ref_6ee = bustupFade(ref_6ca, rgb(0,0,0), 10);
    bustupWait(ref_6ee);
    bustupFree(ref_6ca);
    b(label_76f);
  label_6f2:
    bne(var_0, 2, label_71d);
    ref_6f3 = bustupLoad(bustup_ea);
    bustupWait(ref_6f3);
    ref_6f5 = bustupAlloc(ref_6f3, right, rgb(0,0,0));
    bustupFade(ref_6f5, rgb(128,0,0), 30);
    ref_6f7 = dialogAlloc();
    ref_6f8 = msgShow(msg_106);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]なるほど…どうやらソナタ、異国の民か？
[tab]アメリカ…いや、フランス…
[tab]そう、フランス人じゃ！！
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_6f8);
    ref_705 = msgShow(msg_107);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_705);
    ref_70b = msgShow(msg_108);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…日本人よね。
[tab]…日本人なんでしょ？[tab]やっぱり。
[tab]……分かってるわよそんなの…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_70b);
    dialogFree(ref_6f7);
    ref_719 = bustupFade(ref_6f5, rgb(0,0,0), 10);
    bustupWait(ref_719);
    bustupFree(ref_6f5);
    b(label_76f);
  label_71d:
    bne(var_0, 3, label_746);
    ref_71e = bustupLoad(bustup_ea);
    bustupWait(ref_71e);
    ref_720 = bustupAlloc(ref_71e, right, rgb(0,0,0));
    bustupFade(ref_720, rgb(128,0,0), 30);
    ref_722 = dialogAlloc();
    ref_723 = msgShow(msg_109);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]むむっ、ソナタ…
[tab]実は胸にパットを入れておるな！！
[tab]偽ナイスバデーで、男の視線を我が物に…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_723);
    ref_730 = msgShow(msg_110);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_730);
    ref_734 = msgShow(msg_111);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]じょ…冗談じゃ。
[tab]ホンキにするでない。
[tab]ほ…本物じゃな…やっぱり。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_734);
    dialogFree(ref_722);
    ref_742 = bustupFade(ref_720, rgb(0,0,0), 10);
    bustupWait(ref_742);
    bustupFree(ref_720);
    b(label_76f);
  label_746:
    bne(var_0, 4, label_76f);
    ref_747 = bustupLoad(bustup_ea);
    bustupWait(ref_747);
    ref_749 = bustupAlloc(ref_747, right, rgb(0,0,0));
    bustupFade(ref_749, rgb(128,0,0), 30);
    ref_74b = dialogAlloc();
    ref_74c = msgShow(msg_112);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]ほう…ソナタ、教師を生業としているな？
[tab]…たぶん、英語の教師じゃろう。
[tab]そう顔に書いてある。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_74c);
    ref_759 = msgShow(msg_113);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]……
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_759);
    ref_75d = msgShow(msg_114);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…ちがう？[tab]…ちがってた？
[tab]…え？[tab]雑誌記者…
[tab]ハハ…全然違うわね…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_75d);
    dialogFree(ref_74b);
    ref_76b = bustupFade(ref_749, rgb(0,0,0), 10);
    bustupWait(ref_76b);
    bustupFree(ref_749);
    b(label_76f);
  label_76f:
    b(label_8be);
  label_770:
    shopInventory(3, shopInventory_-bb8);
    ref_771 = bustupLoad(bustup_ea);
    bustupWait(ref_771);
    ref_773 = bustupAlloc(ref_771, right, rgb(0,0,0));
    bustupFade(ref_773, rgb(128,0,0), 30);
    ref_775 = dialogAlloc();
    ref_776 = msgShow(msg_115);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]よかろう。
[tab]では代金として３０００円頂くが…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_776);
    dialogFree(ref_775);
    ref_784 = bustupFade(ref_773, rgb(0,0,0), 10);
    bustupWait(ref_784);
    bustupFree(ref_773);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    choiceSetResult(1);
    ref_78a = bustupLoad(bustup_1);
    bustupWait(ref_78a);
    ref_78c = bustupAlloc(ref_78a, center, rgb(0,0,0));
    bustupFade(ref_78c, rgb(128,0,0), 30);
    ref_78e = dialogChoiceAlloc();
    ref_78f = msgShow(msg_116);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]それでも、かまわぬか？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_78f);
    dialogFree(ref_78e);
    ref_792 = bustupFade(ref_78c, rgb(0,0,0), 10);
    bustupWait(ref_792);
    bustupFree(ref_78c);
    choiceGetResult(var_0);
    bne(var_0, 0, label_7b4);
    partyMoneyGet(var_0);
    boutrange(var_0, 0, 2999, label_7b1);
    ref_799 = bustupLoad(bustup_ea);
    bustupWait(ref_799);
    ref_79b = bustupAlloc(ref_799, right, rgb(0,0,0));
    bustupFade(ref_79b, rgb(128,0,0), 30);
    ref_79d = dialogAlloc();
    ref_79e = msgShow(msg_117);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]むむ…だが、代金が足らぬようじゃぞ。
[tab]阿弥陀の光も金次第。地獄の沙汰も金次第。
[tab]出直して来るがよい。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_79e);
    shopCurrencyDisplay(-110, 150, true);
    dialogFree(ref_79d);
    ref_7ad = bustupFade(ref_79b, rgb(0,0,0), 10);
    bustupWait(ref_7ad);
    bustupFree(ref_79b);
    b(label_7b3);
  label_7b1:
    b(label_7ba);
    b(label_7b3);
  label_7b3:
    b(label_7b9);
  label_7b4:
    bne(var_0, 1, label_7b9);
    shopCurrencyDisplay(-110, 150, true);
    delayClear();
    delayWait(20);
    b(label_7b9);
  label_7b9:
    b(label_8be);
  label_7ba:
    bitGet(var_0, MBIT_URANAI_01);
    bne(var_0, 0, label_7dc);
    bitGet(var_0, MBIT_URANAI_02);
    bne(var_0, 0, label_7d8);
    bitGet(var_0, MBIT_URANAI_03);
    bne(var_0, 0, label_7d4);
    bitGet(var_0, MBIT_URANAI_04);
    bne(var_0, 0, label_7d0);
    bitGet(var_0, MBIT_URANAI_05);
    bne(var_0, 0, label_7cc);
    bitGet(var_0, MBIT_URANAI_06);
    bne(var_0, 0, label_7c8);
    b(label_80a);
    b(label_7cb);
  label_7c8:
    bne(var_0, 1, label_7cb);
    li(var_5, 6);
    b(label_7cb);
  label_7cb:
    b(label_7cf);
  label_7cc:
    bne(var_0, 1, label_7cf);
    li(var_5, 5);
    b(label_7cf);
  label_7cf:
    b(label_7d3);
  label_7d0:
    bne(var_0, 1, label_7d3);
    li(var_5, 4);
    b(label_7d3);
  label_7d3:
    b(label_7d7);
  label_7d4:
    bne(var_0, 1, label_7d7);
    li(var_5, 3);
    b(label_7d7);
  label_7d7:
    b(label_7db);
  label_7d8:
    bne(var_0, 1, label_7db);
    li(var_5, 2);
    b(label_7db);
  label_7db:
    b(label_7df);
  label_7dc:
    bne(var_0, 1, label_7df);
    li(var_5, 1);
    b(label_7df);
  label_7df:
    ref_7df = bustupLoad(bustup_ea);
    bustupWait(ref_7df);
    ref_7e1 = bustupAlloc(ref_7df, right, rgb(0,0,0));
    bustupFade(ref_7e1, rgb(128,0,0), 30);
    ref_7e3 = dialogAlloc();
    msgShow(msg_118);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]いや待て。まだ汝は
***************************************/
    bne(var_5, 1, label_7e8);
    msgShow(msg_119);
/***************************************
光龍
***************************************/
    b(label_7f7);
  label_7e8:
    bne(var_5, 2, label_7eb);
    msgShow(msg_120);
/***************************************
黒龍
***************************************/
    b(label_7f7);
  label_7eb:
    bne(var_5, 3, label_7ee);
    msgShow(msg_121);
/***************************************
黄龍
***************************************/
    b(label_7f7);
  label_7ee:
    bne(var_5, 4, label_7f1);
    msgShow(msg_122);
/***************************************
青龍
***************************************/
    b(label_7f7);
  label_7f1:
    bne(var_5, 5, label_7f4);
    msgShow(msg_123);
/***************************************
赤龍
***************************************/
    b(label_7f7);
  label_7f4:
    bne(var_5, 6, label_7f7);
    msgShow(msg_124);
/***************************************
銀龍
***************************************/
    b(label_7f7);
  label_7f7:
    ref_7f7 = msgShow(msg_125);
/***************************************
の呪縛から逃れておらぬ。
[tab]まずはその因果から抜け出し、
[tab]真の己を取り戻すことが肝要じゃ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_7f7);
    shopCurrencyDisplay(-110, 150, true);
    dialogFree(ref_7e3);
    ref_806 = bustupFade(ref_7e1, rgb(0,0,0), 10);
    bustupWait(ref_806);
    bustupFree(ref_7e1);
    b(label_8be);
  label_80a:
    partyMoneyAdd(-3000);
    ref_80b = bustupLoad(bustup_ea);
    bustupWait(ref_80b);
    ref_80d = bustupAlloc(ref_80b, right, rgb(0,0,0));
    bustupFade(ref_80d, rgb(128,0,0), 30);
    ref_80f = dialogAlloc();
    unitAnimationPlay(shopkeeper, animation_9, 1);
    ref_811 = msgShow(msg_126);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]では、占ってしんぜよう。
[tab]ワンロン、ワンロン、ワンローン！！

***************************************/
    wait(ref_811);
    shopCurrencyDisplay(-110, 150, true);
    ref_814 = msgShow(msg_127);
/***************************************
[tab]ローン、ローーーーン！！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_814);
    dialogFree(ref_80f);
    ref_818 = bustupFade(ref_80d, rgb(0,0,0), 10);
    bustupWait(ref_818);
    bustupFree(ref_80d);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), add);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), add);
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    rand(var_0, 5);
    bne(var_0, 0, label_841);
    ref_829 = bustupLoad(bustup_ea);
    bustupWait(ref_829);
    ref_82b = bustupAlloc(ref_829, right, rgb(0,0,0));
    bustupFade(ref_82b, rgb(128,0,0), 30);
    ref_82d = dialogAlloc();
    ref_82e = msgShow(msg_128);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお…光り輝く息吹を感じる…光龍じゃ…
[tab]汝しばしの間、多くの経験を積むことができようが
[tab]金運は下がりぎみ。節約を心がけよ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_82e);
    dialogFree(ref_82d);
    ref_83c = bustupFade(ref_82b, rgb(0,0,0), 10);
    bustupWait(ref_83c);
    bustupFree(ref_82b);
    bitSet(MBIT_URANAI_01);
    b(label_8be);
  label_841:
    bne(var_0, 1, label_85a);
    ref_842 = bustupLoad(bustup_ea);
    bustupWait(ref_842);
    ref_844 = bustupAlloc(ref_842, right, rgb(0,0,0));
    bustupFade(ref_844, rgb(128,0,0), 30);
    ref_846 = dialogAlloc();
    ref_847 = msgShow(msg_129);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお…地の底を駆け巡る黒き気配…黒龍か…
[tab]汝しばしの間、金銭面では裕福となれようが、
[tab]大した経験は積めぬようじゃ。自重いたせ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_847);
    dialogFree(ref_846);
    ref_855 = bustupFade(ref_844, rgb(0,0,0), 10);
    bustupWait(ref_855);
    bustupFree(ref_844);
    bitSet(MBIT_URANAI_02);
    b(label_8be);
  label_85a:
    bne(var_0, 2, label_873);
    ref_85b = bustupLoad(bustup_ea);
    bustupWait(ref_85b);
    ref_85d = bustupAlloc(ref_85b, right, rgb(0,0,0));
    bustupFade(ref_85d, rgb(128,0,0), 30);
    ref_85f = dialogAlloc();
    ref_860 = msgShow(msg_130);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]おお…この活発な龍は…黄龍か…
[tab]汝、しばし幸運に恵まれ、ラッキー続きじゃ。
[tab]今のうちに賭け事に走るのも良いじゃろう。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_860);
    dialogFree(ref_85f);
    ref_86e = bustupFade(ref_85d, rgb(0,0,0), 10);
    bustupWait(ref_86e);
    bustupFree(ref_85d);
    bitSet(MBIT_URANAI_03);
    b(label_8be);
  label_873:
    bne(var_0, 3, label_88c);
    ref_874 = bustupLoad(bustup_ea);
    bustupWait(ref_874);
    ref_876 = bustupAlloc(ref_874, right, rgb(0,0,0));
    bustupFade(ref_876, rgb(128,0,0), 30);
    ref_878 = dialogAlloc();
    ref_879 = msgShow(msg_131);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うむ…この潮流の如き静かな流動…青龍か…
[tab]汝しばしの間、他者の意外な面を見る事となろう。
[tab]弱気は強気へ、皆性格が対極へ流れるはずじゃ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_879);
    dialogFree(ref_878);
    ref_887 = bustupFade(ref_876, rgb(0,0,0), 10);
    bustupWait(ref_887);
    bustupFree(ref_876);
    bitSet(MBIT_URANAI_04);
    b(label_8be);
  label_88c:
    bne(var_0, 4, label_8a5);
    ref_88d = bustupLoad(bustup_ea);
    bustupWait(ref_88d);
    ref_88f = bustupAlloc(ref_88d, right, rgb(0,0,0));
    bustupFade(ref_88f, rgb(128,0,0), 30);
    ref_891 = dialogAlloc();
    ref_892 = msgShow(msg_132);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うむ…情熱に染まった真紅の奔流…赤龍…
[tab]汝とその仲間、しばしの間、興奮ぎみとなり、
[tab]勝利した後には、快哉を叫ぶ事となろう。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_892);
    dialogFree(ref_891);
    ref_8a0 = bustupFade(ref_88f, rgb(0,0,0), 10);
    bustupWait(ref_8a0);
    bustupFree(ref_88f);
    bitSet(MBIT_URANAI_05);
    b(label_8be);
  label_8a5:
    bne(var_0, 5, label_8be);
    ref_8a6 = bustupLoad(bustup_ea);
    bustupWait(ref_8a6);
    ref_8a8 = bustupAlloc(ref_8a6, right, rgb(0,0,0));
    bustupFade(ref_8a8, rgb(128,0,0), 30);
    ref_8aa = dialogAlloc();
    ref_8ab = msgShow(msg_133);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]うむ…真意を込めた白き輝き…銀龍…
[tab]汝しばしの間、口下手となり、
[tab]他者との交渉事も梃子摺る事となろう。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_8ab);
    dialogFree(ref_8aa);
    ref_8b9 = bustupFade(ref_8a8, rgb(0,0,0), 10);
    bustupWait(ref_8b9);
    bustupFree(ref_8a8);
    bitSet(MBIT_URANAI_06);
    b(label_8be);
  label_8be:
    call(HOKANI_SELECT);
}

function HOKANI_SELECT()
{
  label_8c0:
    bitGet(var_0, MBIT_HI_GYPAISHO1);
    bne(var_0, 0, label_8ee);
    choiceSetResult(2);
    ref_8c3 = bustupLoad(bustup_ea);
    bustupWait(ref_8c3);
    ref_8c5 = bustupAlloc(ref_8c3, right, rgb(0,0,0));
    bustupFade(ref_8c5, rgb(128,0,0), 30);
    ref_8c7 = dialogAlloc();
    ref_8c8 = msgShow(msg_134);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]さて…他にご用はあるかな？
[tab]何なりと打ち明けるが良い。
[choice(4)]占い
話を聞く
用は無い
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    wait(ref_8c8);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8d3);
    call(HA_SHOP_FORTUNE_0);
    b(label_8e9);
  label_8d3:
    bne(var_0, 1, label_8e2);
    choiceSetResult(2);
    ref_8d5 = msgShow(msg_135);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear]
***************************************/
    wait(ref_8d5);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8db);
    call(HA_SHOP_TALK_0);
    b(label_8e1);
  label_8db:
    bne(var_0, 1, label_8de);
    call(HA_SHOP_EXPLAIN_0);
    b(label_8e1);
  label_8de:
    bne(var_0, 2, label_8e1);
    b(label_8c0);
    b(label_8e1);
  label_8e1:
    b(label_8e9);
  label_8e2:
    bne(var_0, 2, label_8e5);
    call(HA_SHOP_END_0);
    b(label_8e9);
  label_8e5:
    bne(var_0, 3, label_8e9);
    bitSet(MBIT_EXITBIT);
    call(HA_SHOP_END_0);
    b(label_8e9);
  label_8e9:
    dialogFree(ref_8c7);
    ref_8ea = bustupFade(ref_8c5, rgb(0,0,0), 10);
    bustupWait(ref_8ea);
    bustupFree(ref_8c5);
    b(label_91e);
  label_8ee:
    bne(var_0, 1, label_91e);
    choiceSetResult(3);
    ref_8f0 = bustupLoad(bustup_ea);
    bustupWait(ref_8f0);
    ref_8f2 = bustupAlloc(ref_8f0, right, rgb(0,0,0));
    bustupFade(ref_8f2, rgb(128,0,0), 30);
    ref_8f4 = dialogAlloc();
    ref_8f5 = msgShow(msg_136);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]して、本日はいかなる用件じゃ？
[choice(5)]占い
相性占い
話を聞く
用は無い
店の外に出る
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    wait(ref_8f5);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_900);
    call(HA_SHOP_FORTUNE_0);
    b(label_919);
  label_900:
    bne(var_0, 1, label_903);
    call(HA_SHOP_FRIEND_0);
    b(label_919);
  label_903:
    bne(var_0, 2, label_912);
    choiceSetResult(2);
    ref_905 = msgShow(msg_137);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]世間話をする
[if_all(LBIT_0003)]施設の説明を聞く
[if_all(LBIT_0004)]やめる
[end_choice][clear]
***************************************/
    wait(ref_905);
    choiceGetResult(var_0);
    bne(var_0, 0, label_90b);
    call(HA_SHOP_TALK_0);
    b(label_911);
  label_90b:
    bne(var_0, 1, label_90e);
    call(HA_SHOP_EXPLAIN_0);
    b(label_911);
  label_90e:
    bne(var_0, 2, label_911);
    b(label_8c0);
    b(label_911);
  label_911:
    b(label_919);
  label_912:
    bne(var_0, 3, label_915);
    call(HA_SHOP_END_0);
    b(label_919);
  label_915:
    bne(var_0, 4, label_919);
    bitSet(MBIT_EXITBIT);
    call(HA_SHOP_END_0);
    b(label_919);
  label_919:
    dialogFree(ref_8f4);
    ref_91a = bustupFade(ref_8f2, rgb(0,0,0), 10);
    bustupWait(ref_91a);
    bustupFree(ref_8f2);
    b(label_91e);
  label_91e:
}

function HA_SHOP_FRIEND_0()
{
    shopInventory(3, shopInventory_-1388);
    ref_920 = bustupLoad(bustup_ea);
    bustupWait(ref_920);
    ref_922 = bustupAlloc(ref_920, right, rgb(0,0,0));
    bustupFade(ref_922, rgb(128,0,0), 30);
    ref_924 = dialogAlloc();
    ref_925 = msgShow(msg_138);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]よかろう。
[tab]では代金として５０００円頂くが…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_925);
    dialogFree(ref_924);
    ref_92d = bustupFade(ref_922, rgb(0,0,0), 10);
    bustupWait(ref_92d);
    bustupFree(ref_922);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    choiceSetResult(1);
    ref_933 = bustupLoad(bustup_1);
    bustupWait(ref_933);
    ref_935 = bustupAlloc(ref_933, center, rgb(0,0,0));
    bustupFade(ref_935, rgb(128,0,0), 30);
    ref_937 = dialogChoiceAlloc();
    ref_938 = msgShow(msg_139);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]それでも、かまわぬか？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_938);
    dialogFree(ref_937);
    ref_93b = bustupFade(ref_935, rgb(0,0,0), 10);
    bustupWait(ref_93b);
    bustupFree(ref_935);
    choiceGetResult(var_0);
    bne(var_0, 0, label_967);
    partyMoneyGet(var_0);
    boutrange(var_0, 0, 4999, label_95d);
    ref_942 = bustupLoad(bustup_ea);
    bustupWait(ref_942);
    ref_944 = bustupAlloc(ref_942, right, rgb(0,0,0));
    bustupFade(ref_944, rgb(128,0,0), 30);
    ref_946 = dialogAlloc();
    ref_947 = msgShow(msg_140);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]むむ…だが、代金が足らぬようじゃぞ。
[tab]阿弥陀の光も金次第。地獄の沙汰も金次第。
[tab]出直して来るがよい。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_8, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_947);
    shopCurrencyDisplay(-110, 150, true);
    dialogFree(ref_946);
    ref_956 = bustupFade(ref_944, rgb(0,0,0), 10);
    bustupWait(ref_956);
    bustupFree(ref_944);
    delayClear();
    delayWait(10);
    call(HOKANI_SELECT);
    b(label_966);
  label_95d:
    shopOverlayInit();
    partyMoneyAdd(-5000);
    delayClear();
    delayWait(30);
    shopCurrencyDisplay(-110, 150, true);
    delayClear();
    delayWait(30);
    eventLoad(event_e5);
    b(label_966);
  label_966:
    b(label_96d);
  label_967:
    bne(var_0, 1, label_96d);
    shopCurrencyDisplay(-110, 150, true);
    delayClear();
    delayWait(20);
    call(HOKANI_SELECT);
    b(label_96d);
  label_96d:
}

function DOORBOX()
{
    controlDisable();
    objAnimRotate(obj_6, 0, 80, 0, 30, 0);
    objAnimRotate(obj_7, 0, -80, 0, 30, 0);
    sndMusicPlay(sound_307a, 127);
    objAnimWait(obj_6);
    objAnimWait(obj_7);
    call(EXITBOX);
}

function EXITBOX()
{
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function DEBAGBOX()
{
    controlDisable();
    choiceSetResult(4);
    ref_97b = dialogChoiceAlloc();
    ref_97c = msgShow(msg_141);
/***************************************
えらんで
[choice(5)][color(pink)]ワンロン始めた[color(white)]
[color(blue)]相性占い広めた[color(white)]
[color(green)]パワーアップ[color(white)]
[color(orange)]お金[color(white)]
[color(gray)]終了[color(white)]
[end_choice][clear]
***************************************/
    wait(ref_97c);
    dialogFree(ref_97b);
    choiceGetResult(var_0);
    bne(var_0, 0, label_983);
    bitSet(MBIT_HI_GYPSTART);
    b(label_98e);
  label_983:
    bne(var_0, 1, label_986);
    bitSet(MBIT_HI_GYPAISHO1);
    b(label_98e);
  label_986:
    bne(var_0, 2, label_989);
    bitSet(MBIT_HI_GYPAISHO2);
    b(label_98e);
  label_989:
    bne(var_0, 3, label_98c);
    partyMoneyAdd(15000);
    b(label_98e);
  label_98c:
    bne(var_0, 4, label_98e);
    b(label_98e);
  label_98e:
    controlEnable();
}

function HA_SHOP_EXPLAIN_0()
{
    choiceSetResult(2);
    ref_991 = dialogChoiceAlloc();
    ref_992 = msgShow(msg_142);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]妾に何を聞きたいのだ？
[choice(3)]占い
[if_all(MBIT_HI_GYPAISHO1)]相性占い
やめる
[end_choice][clear]
***************************************/
    wait(ref_992);
    dialogFree(ref_991);
    choiceGetResult(var_0);
    bne(var_0, 0, label_99c);
    ref_997 = dialogAlloc();
    ref_998 = msgShow(msg_143);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]「占い」についての説明じゃな。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]当店で「占い」を選択すれば
[tab]妾が汝らの未来を占ってしんぜよう。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]占いの結果は、良い効果を得ることもあれば、
[tab]逆に悪い効果が出る場合もある。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]なお、一度占うと、その効果が切れるまで、
[tab]再度未来を占うことはできんぞ。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]未来を知るかの選択は汝ら次第だ。
[tab]何が見えても妾は責任は負わんからな。
[wait][clear]
***************************************/
    wait(ref_998);
    dialogFree(ref_997);
    b(label_9a4);
  label_99c:
    bne(var_0, 1, label_9a2);
    ref_99d = dialogAlloc();
    ref_99e = msgShow(msg_144);
/***************************************
[color(yellow)]珠閒瑠ジニー[color(white)]
[tab]「相性占い」の説明じゃな。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]当店で「相性占い」を選択すると
[tab]妾の水晶がいくつか汝に質問を投げかける。
[tab]汝はそれに正直に答えるのじゃ。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]さすれば、汝と相性がぴったりの人物を
[tab]この水晶が示してくれるぞよ。
[wait][clear][color(yellow)]珠閒瑠ジニー[color(white)]
[tab]…その後、示された相手に会えば
[tab]何か良いことがあるかも知れぬな。
[wait][clear]
***************************************/
    wait(ref_99e);
    dialogFree(ref_99d);
    b(label_9a4);
  label_9a2:
    bne(var_0, 2, label_9a4);
    b(label_9a4);
  label_9a4:
    call(HOKANI_SELECT);
}
