
msg_0:
パーティの人数が四人を超えています。
このままじゃハングします。
金田・片岡に連絡してください。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
[tab]このお店、前にマーヤと一緒に来たよね。
[tab]ほら、グルメ雑誌の紹介記事見て来たじゃん！
[tab]…覚えてないの？[tab]…ったくアンタは！！
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
[tab]それにしても、
[tab]鳴海区はセンスのいい店が多い！
[tab]…南条君、いいトコ住んでんなぁ。
[wait][clear][end]

msg_3:
[color(yellow)]うらら[color(white)]
[tab]あのカクテル、キレイねぇ～
[tab]やっぱお酒もキレイな方がいいよね？
[wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]鳴海区は落ち着きのある街だな。
[tab]交通量も少ないし、犯罪の報告も少ない。
[tab]生活するにはいい環境だろう。
[wait][clear][end]

msg_5:
[color(yellow)]克哉[color(white)]
[tab]僕は外見も重要な要素だと思うな。
[tab]料理やお菓子のように、目で楽しむって所もある。
[tab]…決して外見が全てと言ってるわけではないよ！
[wait][clear][end]

msg_6:
[color(yellow)]パオフゥ[color(white)]
[tab]芹沢が気にいるのも無理はない。
[tab]鳴海区はここ十年で開発された新しい地域。
[tab]珠閒瑠市の新しい顔とも言える街だからな。
[wait][clear][end]

msg_7:
[color(yellow)]パオフゥ[color(white)]
[tab]キレイなカクテルねぇ…どうして女ってのは、
[tab]こうキレイなものが好きなんだろうねぇ？
[tab]問題は中身だろぉ？
[wait][clear][end]

msg_8:
[color(yellow)]南条[color(white)]
[tab]古くから住む者がなく、俺や桐島のような
[tab]タイプの人間でも目立たずに行動出来る。
[tab]だから鳴海区にいる。それだけだ。
[wait][clear][end]

msg_9:
[color(yellow)]南条[color(white)]
[tab]あのバーテンダー、中々いい事を言う。
[tab]しかし、清濁併せ呑む事は難しい事だ。
[wait][clear][end]

msg_10:
[color(yellow)]エリー[color(white)]
[tab]ここ鳴海区には、いわゆる業界関係者が数多く
[tab]暮らしていますわ。私のＭｏｄｅｌ仲間達も皆、
[tab]この辺に住んでいますよ。
[wait][clear][end]

msg_11:
[color(yellow)]エリー[color(white)]
[tab]美味しくて、美しい。その両方を兼ね備えた
[tab]Ｃｏｃｋｔａｉｌって少ないのですか？
[tab]…確かに、才色兼備って人も少ないですね。
[wait][clear][end]

msg_12:
[color(yellow)]噂愛好者[color(white)]
[tab]ねぇキミ、あそこの外国人の噂、知ってるかい？
[tab]表向きは世界を舞台に慈善事業を展開する大富豪。
[tab]…でも裏ではテロリストを支援してるって話さ。
[wait][clear][end]

msg_13:
[color(yellow)]噂愛好者[color(white)]
[tab]ちまたの噂通り、あの外人さんは
[tab]地図収集をしている大金持ちなんだって。
[wait][clear][end]

msg_14:
[color(yellow)]噂愛好者[color(white)]
[tab]そして、悪魔と呼ばれる裏社会の実力者…
[tab]いや、噂じゃないって。ほんとだよ！
[wait][clear][end]

msg_15:
[color(yellow)]噂愛好者[color(white)]
[tab]ねぇキミ、デジャ・ヴュって感じたことある？
[tab]記憶障害かも知れないけど、最近多いらしいよ。
[tab]かく言う私もその一人。…仮面党って何だっけ？
[wait][clear][end]

msg_16:
[color(yellow)]噂愛好者[color(white)]
[tab]ちまたの噂通り、あの外人さんは
[tab]地図収集をしている大金持ちなんだって。
[wait][clear][end]

msg_17:
[color(yellow)]噂愛好者[color(white)]
[tab]そして、悪魔と呼ばれる裏社会の実力者…
[tab]いや、噂じゃないって。ほんとだよ！
[wait][clear][end]

msg_18:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]アラー、キレーナオ嬢サン！
[tab]…ナニ？[tab]地図集メ？
[tab]何デワタシノ趣味知ッテル？
[wait][clear][end]

msg_19:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ワタシ、オ金モウ飽キタ。興味無イデッス。
[tab]今ヤ地図収集ダケガ生キ甲斐。
[tab]…トコロデ、今日ハ何ダ？
[wait][clear][end]

msg_20:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]アラー、キレーナオ嬢サン！
[tab]マタワタシノ所ニ来テクレタカ。ウレシイデッス。
[tab]トコロデ、今日ハ何ダ？
[wait][clear][end]

msg_21:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]トコロデ、今日ハ何ダ？
[choice(4)][if_all(!LBIT_0000)]依頼を受ける
話を聞きたい
説明
用はない
[end_choice][clear][end]

msg_22:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]トコロデ、今日ハ何ダ？
[choice(4)][if_all(!LBIT_0000)]地図を渡す
話を聞きたい
説明
用はない
[end_choice][clear][end]

msg_23:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ワタシノ依頼ヲ受ケテクレタラ、依頼シタ場所の
[tab]白地図ヲ渡スヨ。ソレ持ッテルト、ソコニ入ッタ時
[tab]イツモト違ウマップガ見レルネ。
[wait][clear][color(yellow)]サラーム・ラディーン[color(white)]
[tab]歩イタコトナイ場所、灰色ニナッテルカラ
[tab]歩イテソレ消シテッテ。
[tab]消シ忘レガアルト後デ大変ダカラ、丁寧ニネ。
[wait][clear][color(yellow)]サラーム・ラディーン[color(white)]
[tab]ゼンブ消セレバ、地図ノ完成ネ。
[tab]ココニ持ッテキテクレレバ、イイ物ト交換シテアゲルヨ！
[tab]スゴクイイ物トダヨ！
[wait][clear][color(yellow)]サラーム・ラディーン[color(white)]
[tab]アーチナミニ、ソノ場所ニ入レナクナッタラ地図作成ハ
[tab]終了ネ。諦メテ未完成ノヲ持ッテキナサーイ。
[tab]何ニモアゲナイケド。
[wait][clear][end]

msg_24:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ、ソコノ地図ハモウモラッタヨ？
[tab]今度ハ別ノ所ヲオ願イシタイネ。
[wait][clear][end]

msg_25:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ～？[tab]青葉公園～？[tab]アソコハ遠慮スルヨ。
[tab]ダッテ、公園ナンカ珍シクナイダロ？
[wait][clear][end]

msg_26:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]ナ～ンダ、ソンナ所カァ～
[tab]ソコノ地図ハ…イラナイヨ。
[wait][clear][end]

msg_27:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ、神社？[tab]興味無イナァ～
[tab]ソコノ地図ハ…イラナイヨ。
[wait][clear][end]

msg_28:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]エ、珠閒瑠城？[tab]ア、アソコハ遠慮スルヨ。
[tab]ダッテ、殿サマノ怒リヲ買ッタラ腹切リダロ？
[wait][clear][end]

msg_29:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]…ワタシ、オ金モウ飽キタ。興味無イデッス。
[tab]今ヤ地図収集ダケガ生キ甲斐。
[tab]オ嬢サン、コレカラドコ行ク？
[wait][clear][end]

msg_30:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]…[delay(10)]…[delay(10)]…[delay(1)]フム、ワタシノ知ラナイ所ダナ。
[tab]ソコ珍シイ所！[tab]ソコ調ベテクレナイカ？
[tab]オ嬢サン、ソコノ地図ヲ作ッテ来テクレ！
[wait][clear][end]

msg_31:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、今度ハドコ行ク？
[tab]…[delay(10)]…[delay(10)]…[delay(1)]フム、又モワタシノ知ラナイ所ダ。
[tab]オ嬢サン、ソコノ地図ヲ作ッテ来テクレ！
[wait][clear][end]

msg_32:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]地図ヲ作ッテ来テクレルカ？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_33:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ソウカ！[tab]地図作ッテ来テクレルカ！
[tab]ホンットニ頼ンダヨ、オ嬢サン。
[tab]デハ、コノ白地図ヲ渡ソウ。
[wait][clear][end]

msg_34:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ヒタスラ歩イテ、地図ヲ完成サセテクレ。
[tab]出来ガ良カッタラ、ワタシノ大事ナかーどト
[tab]交換シテアゲルカラネ。
[wait][clear][end]

msg_35:
[tab][color(green)][item_with_type(item_fffe)]を手に入れた。[color(white)]
[wait][clear][end]

msg_36:
[tab][color(green)][item_with_type(item_fffe)]と
[tab][item_with_type(item_fffd)]を手に入れた。[color(white)]
[wait][clear][end]

msg_37:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]…ソウカ…地図作ッテ来テクレナイノカ。
[tab]出来ガ良ケレバ珍シイかーどト交換シタノニ。
[tab]非常ニ残念デッスヨ、オ嬢サン。
[wait][clear][end]

msg_38:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オォ、珍シイ地図ヲ持ッテ来テクレタカ！
[tab]今ヤ地図収集ダケガ生キ甲斐。
[tab]ドレドレ……
[wait][clear][end]

msg_39:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]確カニ珍シイ地図ダ…ガ…未完成ダゾ？
[tab]かーどト交換スルワケニハイカナイナァ。
[tab]…ゼヒ、完成サセテ欲シイデッス！
[wait][clear][end]

msg_40:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]確カニ珍シイ地図ダ…ガ…未完成デハナァ。
[tab]かーどト交換スルワケニハイカナイデッス。
[tab]…コノ地図ハ受ケ取ッテオクケドネ！
[wait][clear][end]

msg_41:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]コレハ確カニ珍シイ地図ダ！
[tab]ゼヒ、ゼヒかーどト交換サセテモラウゾ！！
[wait][clear][end]

msg_42:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ソウカ！[tab]地図作ッテ来テクレルカ！
[tab]デハ、コノ白紙ノ地図ヲ渡ソ……
[tab]ナニ！？[tab]モウ行ッテ来タノカ？
[wait][clear][end]

msg_43:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ドレドレ……
[tab]コレハ確カニ珍シイ地図ダ！
[tab]ゼヒ、ゼヒかーどト交換サセテモラウゾ！！
[wait][clear][end]

msg_44:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット[tab]ＦＩＮＡＬ
[tab]を受け取った。[color(white)]
[sync][wait][clear][end]

msg_45:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット
[tab]ＴＡＲＯＴ[tab]ＳＰＥＣＩＡＬ
[tab]を受け取った。[color(white)]
[sync][wait][clear][end]

msg_46:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・スキルカードセット[tab]Ｐａｒｔ２
[tab]を受け取った。[color(white)]
[sync][wait][clear][end]

msg_47:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・スキルカードセット
[tab]を受け取った。[color(white)]
[sync][wait][clear][end]

msg_48:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット[tab]ブースターパック
[tab]を受け取った。[color(white)]
[sync][wait][clear][end]

msg_49:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセット[tab]Ｐａｒｔ２
[tab]を受け取った。[color(white)]
[sync][wait][clear][end]

msg_50:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセットを受け取った。[color(white)]
[sync][wait][clear][end]

msg_51:
[tab][color(green)]地図作成の報酬として、
[tab]サラーム特選・カードセットを受け取った。[color(white)]
[sync][wait][clear][end]

msg_52:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]他ニ何カアルカ？
[tab]何デモ言ッテクダサイヨ。
[wait][clear][end]

msg_53:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]マタ来テネ、キレーナオ嬢サン。
[tab]デモ、ワタシノ事ハ内緒ネ。
[tab]ワタシ、裏社会ニ敵ガ多イカラ…アッハッハ。
[wait][clear][end]

msg_54:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]オ嬢サン、トッテモキレーネー！
[tab]今ヒマカ？[tab]ワタシノ部屋来ナイカ？
[tab]ワタシノコレクション、見タクハナイカ？
[wait][clear][end]

msg_55:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ワタシ、オ金ナラ一杯持ッテルヨー
[tab]心配イラナイ、ワタシハ信心深イ事業家。
[tab]変ナ事シナイデッス。…ダメカ？
[wait][clear][end]

msg_56:
[color(yellow)]サラーム・ラディーン[color(white)]
[tab]ＴＶ局ヤ理学研究所ノ事件、アレハ誰ノ仕業カ？
[tab]何ガ目的カ知ッテルカ？[tab]怖イネー
[tab]…日本ナラ落チ着ケルト思ッタノニ。
[wait][clear][end]

msg_57:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]いらっしゃいませ。
[tab]もし良かったら、今日の気分を教えて頂けますぅ？
[tab]…お客様の心に合うものをお作りしますわ。
[wait][clear][end]

msg_58:
[color(yellow)]バーテン[color(green)]
[tab]ホテル・プレアデス最上階のラウンジ、
[tab]エボニーを取り仕切る女性バーテンダー
[tab]職業柄噂に詳しく、様々な噂を提供してくれる。[color(white)]
[wait][clear][end]

msg_59:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]…お客様と私の相性がいいんですか？
[tab]うふふ、光栄ですわ。
[tab]記念に今日はサービスさせていただきますネ。
[wait][clear][end]

msg_60:
[color(yellow)]バーテン[color(green)]
[tab]ホテル・プレアデス最上階のラウンジ、
[tab]エボニーを取り仕切る女性バーテンダー
[tab]職業柄噂に詳しく、様々な噂を提供してくれる。[color(white)]
[wait][clear][end]

msg_61:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]今日は何にいたしますぅ？
[wait][clear][end]

msg_62:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]今日は何にいたしますぅ？
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_63:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]どんな話がいいかしら？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_64:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]他にご注文はありますぅ？
[tab]あ、でも無理なさらないでネ。
[tab]お話しているだけでもかまわないから…
[choice(4)]食事をする
話をする
やめる
店の外に出る
[end_choice][clear][end]

msg_65:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]どんな話がいいかしら？
[choice(3)]世間話をする
施設の説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear][end]

msg_66:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]どんな話がいいかしら？
[choice(3)]噂話を聞きたい
話を聞きたい
用はない
[end_choice][clear][end]

msg_67:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]噂話ですか？[tab]う～ん、ごめんなさい！
[tab]持ちネタが切れちゃいました。
[tab]おもしろい噂、また集めておきますネ。
[wait][clear][end]

msg_68:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]噂話ですか？[tab]いいですけど…
[tab]かわりに何か知ってる噂を教えてもらえます？
[wait][clear][end]

msg_69:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]ふふふっ。
[tab]今日の為にとっておいた、いい噂があるんですよ。
[tab]おっと、その前にお客様の噂を教えてください。
[wait][clear][end]

msg_70:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]テレビや雑誌のゴシップって情報が古いですよね？
[tab]私、新鮮な噂が知りたいなぁ。
[tab]…いいネタ、持ってます？
[wait][clear][end]

msg_71:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]ふ～ん、そうなんですかぁ。
[tab]おもしろい噂、ありがとうございます。
[tab]それでは、私が入手した噂をお話ししますネ。
[wait][clear][end]

msg_72:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]あら、そうなんですか！？
[tab]私、ゼンゼン知りませんでしたよ。
[tab]う～ん、私の噂はですネ…
[wait][clear][end]

msg_73:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]おや？
[tab]その話に似た噂を聞いた事がありますよ？
[tab]ちょっと残念ですネ。さて…
[wait][clear][end]

msg_74:
[color(yellow)]噂好きのバーテン[color(white)]
[tab][color(orange)]クレール・ド・リュンヌ[color(white)]ってお店、ご存知ですか？
[tab]あのお店、[color(orange)]武器の販売[color(white)]を始めたらしいですネ。
[tab]でも、売ってるのは[color(orange)]不思議な武器[color(white)]って噂ですよ。
[wait][clear][end]

msg_75:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]ジュエリーショップの[color(orange)]パパラチャ[color(white)]って
[tab]あるじゃないですか？[tab]あそこのデザイナーさん、
[tab][color(orange)]武器や防具のオーダーメイド[color(white)]もしてるって噂ネ。
[wait][clear][end]

msg_76:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]このホテルのスィートに滞在する外国人の方、
[tab]…あ、あそこの方！
[tab]あの方の噂って、ご存知です？
[wait][clear][end]

msg_77:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]あの方…[color(orange)]サラーム[color(white)]さんって言うんですけど、
[tab]世界中の[color(orange)]地図を集めている[color(white)]大富豪らしいですよ。
[tab]地図の為なら悪魔とでも取引するって噂ですネ。
[wait][clear][end]

msg_78:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]近くに理学なんとかって建物がありますよね？
[tab]あそこ、研究内容が明かされていないんです。
[tab]最近は事件が多いから、ちょっと怖いですよネ。
[wait][clear][end]

msg_79:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]穢れ祓いって盛んなようですね。…知ってます？
[tab]私ネ、人に穢れがあるのは当然だと思うんですよ。
[tab]だって、キレイなままじゃ生きていけないもの。
[wait][clear][end]

msg_80:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]そりゃキレイなまま生きられたらいいですけど…
[tab]でもね、色んなものが交じり合ってこそ
[tab]味わいが出るのかなって。カクテルのようにネ。
[wait][clear][end]

msg_81:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]またいらしてくださいネ。
[tab]嫌な事があった日でも構いませんよ。
[tab]暗い気持ちも、私が軽～くステアいたしますわ。
[wait][clear][end]

msg_82:
マップ屋の噂・決定
びっとお～んッ！！
[wait][clear][end]

msg_83:
マップ屋の依頼を受けた
びっとお～んッ！！
[wait][clear][end]

msg_84:
マップ屋の依頼を受けた
びっとお～ふッ！！
びっとお～ふッ！！
[wait][clear][end]

msg_85:
マップ完成
びっとお～んッ！！
[wait][clear][end]

msg_86:
マップ完成
びっとお～ふッ！！
びっとお～ふッ！！
[wait][clear][end]

msg_87:
ＭＢＩＴ[tab]ＡＩＳ[tab]５０
相性占いの
びっとお～んッ！！
[wait][clear][end]

msg_88:
ＥＢＩＴ[tab]Ｅ００４６
「南条ｏｒエリー編入」
びっとお～んッ！！
[wait][clear][end]

msg_89:
ＥＢＩＴ[tab]Ｅ００６Ｆ
「研究施設・ＴＶ局クリア」
びっとお～んッ！！
[wait][clear][end]

msg_90:
ＥＢＩＴ[tab]Ｅ００７７
スマイル平坂クリア・踏破
びっとお～んッ！！
[wait][clear][end]

msg_91:
白地図所有
びっとお～んッ！！
[wait][clear][end]

msg_92:
白地図所有
びっとお～ふッ！！
びっとお～ふッ！！
[wait][clear][end]

msg_93:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]どんな話がいいかしら？
[choice(2)]食事
やめる
[end_choice][clear][end]

msg_94:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]「食事」の説明ですネ。
[tab]私に「食事をする」と伝えていただければ
[tab]カクテルをすぐに作らせていただきます！
[wait][clear][color(yellow)]噂好きのバーテン[color(white)]
[tab]私のカクテルを飲むと、
[tab]一時的に能力を高める効果がありますよ。
[wait][clear][color(yellow)]噂好きのバーテン[color(white)]
[tab]効果はカクテルごとに違いますから、
[tab]たくさん飲んで、効果を調べてみてくださいネ。
[wait][clear][color(yellow)]噂好きのバーテン[color(white)]
[tab]それから、効果が切れるまで、
[tab]次の飲食はできないので、注意してくださいネ。
[wait][clear][end]

msg_95:
[color(yellow)]噂好きのバーテン[color(white)]
[tab]そちらのカクテルは[var(msg_var_0)]円になりますが、
[tab]お召し上がりになりますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_96:
[color(green)]未成年は飲酒できません。
[wait][clear][end]
