
msg_0:
[color(yellow)]うらら[color(white)]
[tab]ありゃ…
[tab]このポスター、口の所がふやけてる…
[end]

msg_1:
[tab]……まぁ…いっか。
[wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]ここにあった時計台の鍵が消えたそうだ。
[tab]窃盗の可能性が高いな…
[tab]取り敢えず鑑識に連絡しておくか…
[wait][clear][end]

msg_3:
[color(yellow)]克哉[color(white)]
[tab]ここに時計台の鍵がある事を知っているのは、
[tab]校務員さんと教員…そして生徒…か。
[tab]まさかあの娘が鍵を…
[wait][clear][end]

msg_4:
[color(yellow)]校務員さん[color(white)]
[tab]はぁ…
[tab]この歳で、大時計の手入れは大変じゃわい…
[tab]…ところで…飯はまだかの？
[wait][clear][end]

msg_5:
[color(yellow)]保健のオバチャン[color(white)]
[tab]まったくお爺ちゃんったら、
[tab]さっき食べたばかりじゃない。
[tab]しょうがないわねぇ。
[wait][clear][end]

msg_6:
[color(yellow)]校務員さん[color(white)]
[tab]時計台の鍵が見当たらんのじゃ。
[tab]どこにしまったかのぉ…
[wait][clear][end]

msg_7:
[color(yellow)]保健のオバチャン[color(white)]
[tab]いつも机の上に
[tab]置いておいたじゃありませんか。
[wait][clear][end]

msg_8:
[color(yellow)]校務員さん[color(white)]
[tab]それが無いんじゃよ。
[tab]誰かが持って行ったんじゃろうか…
[wait][clear][end]

msg_9:
[color(yellow)]校務員さん[color(white)]
[tab]あの鍵が無くては、時計台に入れん…
[tab]困ったのぉ…
[wait][clear][end]

msg_10:
[color(yellow)]保健のオバチャン[color(white)]
[tab]たしか…職員室に予備がなかったかしら？
[tab]先生に聞いてみたらどうです？
[wait][clear][end]

msg_11:
[color(yellow)]保健のオバチャン[color(white)]
[tab]あらあら？
[tab]怪我してるようね？
[tab]ちょっと見せてごらんなさい。
[wait][clear][end]

msg_12:
[color(green)][tab]舞耶達は回復した。[color(white)][wait][clear][end]

msg_13:
[color(yellow)]保健のオバチャン[color(white)]
[tab]さぁこれで大丈夫。
[tab]性分かしらねぇ、怪我人は放っておけないの。
[tab]何かあったら、またいつでもいらっしゃいね。
[wait][clear][end]
