function START()
{
    op_107();
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    levelFootstepSet(sfx_10);
    disableMap();
    op_118();
    bitGet(var_0, MBIT_SUN_BEL03);
    bnz(var_0, label_d);
    bitGet(var_0, MBIT_SUN_BEL02);
    bnz(var_0, label_12);
    bitGet(var_0, MBIT_SUN_BEL01);
    bnz(var_0, label_15);
    b(label_18);
  label_d:
    bitClear(MBIT_SUN_BEL03);
    bitClear(MBIT_SUN_BEL02);
    bitClear(MBIT_SUN_BEL01);
    sndMusicPlay(sound_3003, 127);
    b(label_1a);
  label_12:
    bitSet(MBIT_SUN_BEL03);
    sndMusicPlay(sound_3002, 127);
    b(label_1a);
  label_15:
    bitSet(MBIT_SUN_BEL02);
    sndMusicPlay(sound_3001, 127);
    b(label_1a);
  label_18:
    bitSet(MBIT_SUN_BEL01);
    sndMusicPlay(sound_3000, 127);
  label_1a:
    objVisible(obj_29, false);
    objVisible(obj_2a, false);
    ref_1c = todLoad(tod_e);
    wait(ref_1c);
    todRun(tod_e, 1);
    ref_1f = spriteLoad(sprite_0);
    wait(ref_1f);
    ref_21 = spriteLoad(sprite_2);
    wait(ref_21);
    ref_23 = spriteLoad(sprite_a4);
    wait(ref_23);
    unitSpawn(shopkeeper, sprite_a4, 1088, -60, -968, north, none);
    envTriggerSet(IGORU, 56, 1, collision_5, coll_3);
    ref_27 = spriteLoad(sprite_a6);
    wait(ref_27);
    unitSpawn(npc1, sprite_a6, 1269, -60, -695, north, none);
    unitTriggerSet(npc1, BERADONNA, 255, 1);
    ref_2b = spriteLoad(sprite_a5);
    wait(ref_2b);
    unitSpawn(npc2, sprite_a5, 1028, -60, -740, north, none);
    ref_2e = spriteLoad(sprite_a7);
    wait(ref_2e);
    unitSpawn(unit_76, sprite_a7, 750, -60, -1250, north, none);
    unitTriggerSet(unit_76, ESI, 255, 1);
    cameraSet(northwest, 111, 0, -996);
    ref_33 = spriteLoad(sprite_6);
    wait(ref_33);
    unitSpawn(ulala, sprite_6, 851, -30, -1662, south, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
    ref_37 = spriteLoad(sprite_d);
    wait(ref_37);
    unitSpawn(katsuya, sprite_d, 316, 0, -1256, west, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
    ref_3b = spriteLoad(sprite_13);
    wait(ref_3b);
    unitSpawn(baofu, sprite_13, 91, 0, -756, west, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
    ref_3f = spriteLoad(sprite_1f);
    wait(ref_3f);
    unitSpawn(nanjo, sprite_1f, 287, 0, -899, west, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
    ref_43 = spriteLoad(sprite_23);
    wait(ref_43);
    unitSpawn(elly, sprite_23, 1009, -30, -1624, south, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
    ref_47 = spriteLoad(sprite_18);
    wait(ref_47);
    unitSpawn(tatsuya, sprite_18, 147, 0, -1408, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    envTriggerSet(DOORBOX, 14, 1, collision_5, coll_2);
    envTriggerSet(HIDARI, 56, 1, collision_5, coll_0);
    envTriggerSet(MIGI, 131, 1, collision_5, coll_1);
    bitGet(var_0, MBIT_EXE_MOVE);
    bne(var_0, 0, label_51);
    b(label_55);
  label_51:
    bne(var_0, 1, label_55);
    call(MOVEKARA);
    b(label_70);
    b(label_55);
  label_55:
    bitGet(var_0, MBIT_CHARENG_START);
    bne(var_0, 0, label_59);
    call(STARTEVT);
    b(label_70);
  label_59:
    bne(var_0, 1, label_70);
    unknownVar1(var_0);
    bne(var_0, 6152, label_64);
    bitGet(var_0, MBIT_EXE_CHUUKAN);
    bne(var_0, 0, label_60);
    call(CHUUKAN);
    b(label_63);
  label_60:
    bne(var_0, 1, label_63);
    call(NOMAL);
    b(label_63);
  label_63:
    b(label_6f);
  label_64:
    bne(var_0, 7425, label_6d);
    bitGet(var_0, MBIT_EXE_CHUUKAN);
    bne(var_0, 0, label_69);
    call(CHUUKAN);
    b(label_6c);
  label_69:
    bne(var_0, 1, label_6c);
    call(NOMAL);
    b(label_6c);
  label_6c:
    b(label_6f);
  label_6d:
    call(NOMAL);
    b(label_6f);
  label_6f:
    b(label_70);
  label_70:
}

function MOVEKARA()
{
    cameraSet(northwest, 1054, -60, -682);
    delayClear();
    delayWait(5);
    playerInit(north);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    unitIdleOnAll();
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationPlay(npc1, animation_7, 1);
    unitAnimationPlay(unit_76, animation_b, 1);
    call(MIGI);
}

function CHUUKAN()
{
    timerClear();
    bitClear(EBIT_NOSAVE_B);
    cameraSet(northwest, 1107, -60, -1148);
    unitSpawn(maya, sprite_0, 1107, -60, -1148, south, none);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    unitIdleOnAll();
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationPlay(npc1, animation_7, 1);
    unitAnimationPlay(unit_76, animation_b, 1);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(60);
    ref_91 = bustupLoad(bustup_e0);
    bustupWait(ref_91);
    ref_93 = bustupAlloc(ref_91, right, rgb(0,0,0));
    bustupFade(ref_93, rgb(128,0,0), 30);
    ref_95 = dialogAlloc();
    ref_96 = msgShow(msg_0);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ご理解いただけましたかな？
[tab]この迷宮は、あなたの知る世界でありながら、
[tab]決して存在しない、もう一つの世界。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_96);
    ref_9a = msgShow(msg_1);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]現実と虚構が綯交ぜになった架空の世界なのです。
[tab]しかしあなたは、これとよく似た世界を
[tab]もう一つご存知のはず。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_9a);
    ref_9e = msgShow(msg_2);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]あなた方が、
[tab]眠りの中でのみ体験する世界。
[tab]そう…「夢」です。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_9e);
    ref_a2 = msgShow(msg_3);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]フィレモン様が生み出されたこの世界は、
[tab]正しく普遍的無意識の産物と言えましょう。
[tab]それが、あなた方の見る夢とよく似ている…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_a2);
    ref_a6 = msgShow(msg_4);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]これが何を意味するのかは、
[tab]あなたの判断にお任せいたしましょう。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_a6);
    ref_aa = msgShow(msg_5);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]しかし、夢に終わりがあるように
[tab]この世界にもまたゴールがある。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_aa);
    ref_ae = msgShow(msg_6);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]さぁ、頑張ってください。
[tab]ここは迷宮の中間地点。
[tab]あと半分ですぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_ae);
    ref_b2 = msgShow(msg_7);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]そうそう、最後に注意を一つ。一度外に出ると、
[tab]しばらくの間、この部屋は使えません。
[tab]心して、お出かけ下さい。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_b2);
    dialogFree(ref_95);
    ref_b7 = bustupFade(ref_93, rgb(0,0,0), 10);
    bustupWait(ref_b7);
    bustupFree(ref_93);
    unitAnimationPlay(shopkeeper, animation_11, 1);
    unitDespawn(maya, none);
    playerInit(south);
    controlDisable();
    bitSet(MBIT_EXE_CHUUKAN);
    controlEnable();
    cameraControlDisable();
}

function STARTEVT()
{
    cameraSet(northwest, 1107, -60, -1148);
    unitSpawn(maya, sprite_0, 1107, -60, -1148, south, none);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    unitIdleOnAll();
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationPlay(npc1, animation_7, 1);
    unitAnimationPlay(unit_76, animation_b, 1);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(60);
    dngRoomSet(293);
    dngRoomDraw();
    bitSet(CBIT_TUTORIAL);
    bitSet(DBIT_NPC_JACK1);
    bitSet(DBIT_NPC_JACK2);
    bitSet(DBIT_NPC_JACK3);
    bitSet(DBIT_NPC_JACK4);
    bitSet(MBIT_EXE_WHIT_01);
    bitSet(MBIT_EXE_WHIT_02);
    bitSet(MBIT_EXE_WHIT_03);
    bitSet(MBIT_EXE_WHIT_04);
    bitSet(MBIT_EXE_WHIT_05);
    bitSet(MBIT_EXE_KATUYA);
    bitSet(MBIT_EXE_1A_OKU);
    bitSet(MBIT_EXE_1D);
    bitSet(MBIT_EXE_2A);
    bitSet(MBIT_EXE_2B);
    bitSet(EBIT_E0010);
    bitSet(MBIT_BEL_ESI);
    ref_e3 = bustupLoad(bustup_e0);
    bustupWait(ref_e3);
    ref_e5 = bustupAlloc(ref_e3, right, rgb(0,0,0));
    bustupFade(ref_e5, rgb(128,0,0), 30);
    ref_e7 = dialogAlloc();
    ref_e8 = msgShow(msg_8);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ようこそベルベットルームへ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_e8);
    ref_ec = msgShow(msg_9);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]今この部屋は、
[tab]我等が主、フィレモン様の作られた、
[tab]未開の迷宮へと通じております。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_ec);
    ref_f0 = msgShow(msg_10);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]フィレモン様は、この迷宮をもって、
[tab]今一度あなた方の力量を
[tab]確かめるおつもりなのです。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_f0);
    ref_f4 = msgShow(msg_11);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]まずは迷宮に隠された、
[tab]光の渦をお探しなさい。
[tab]それがこの迷宮を攻略する鍵ですぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_f4);
    ref_f8 = msgShow(msg_12);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]どなたと行動を共にするかは、あなたの自由です。
[tab]さぁ、お行きなさい。
[tab]私も陰ながら応援しておりますぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_f8);
    bitGet(var_0, MBIT_EXTRARANK_E);
    bez(var_0, label_10e);
    ref_fe = msgShow(msg_13);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]そうそう…私から、
[tab]あなたに、ささやかな贈り物がございます。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_fe);
    ref_102 = msgShow(msg_14);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ここは現世から離れた異世界。
[tab]あなたも時には、元の世界の友人と、
[tab]お話をしたいと思う事もあるでしょう。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_102);
    ref_106 = msgShow(msg_15);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]私に言っていただければ、
[tab]イビルホンにて、そうした方々に、
[tab]電話をかけてさしあげます。ご利用下さい。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_106);
    ref_10a = msgShow(msg_16);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]それでは…
[tab]健闘を祈りますぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_10a);
  label_10e:
    dialogFree(ref_e7);
    ref_10f = bustupFade(ref_e5, rgb(0,0,0), 10);
    bustupWait(ref_10f);
    bustupFree(ref_e5);
    unitAnimationPlay(shopkeeper, animation_11, 1);
    bitSet(MBIT_CHARENG_START);
    unitDespawn(maya, none);
    playerInit(south);
    controlDisable();
    bitSet(LBIT_0010);
    controlEnable();
    cameraControlDisable();
}

function NOMAL()
{
    cameraSet(northwest, 111, 0, -996);
    playerInit(west);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    unitAnimationPlay(shopkeeper, animation_11, 1);
    unitAnimationPlay(npc2, animation_0, 1);
    unitAnimationPlay(npc1, animation_7, 1);
    unitAnimationPlay(unit_76, animation_b, 1);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
    cameraControlDisable();
}

function B_URARATI()
{
    controlDisable();
    unitFacePlayer(ulala);
    partyMemberCheck(var_0, ulala);
    bnz(var_0, label_1c3);
    ref_12f = bustupLoad(bustup_18);
    bustupWait(ref_12f);
    ref_131 = bustupAlloc(ref_12f, left, rgb(0,0,0));
    bustupFade(ref_131, rgb(128,0,0), 30);
    ref_133 = dialogAlloc();
    ref_134 = msgShow(msg_17);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]おっ！[tab]いよいよ私の出番かしらん♥
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1e, 1);
    wait(ref_134);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_133);
    ref_139 = bustupFade(ref_131, rgb(0,0,0), 10);
    bustupWait(ref_139);
    bustupFree(ref_131);
    choiceSetResult(1);
    ref_13d = bustupLoad(bustup_1);
    bustupWait(ref_13d);
    ref_13f = bustupAlloc(ref_13d, center, rgb(0,0,0));
    bustupFade(ref_13f, rgb(128,0,0), 30);
    ref_141 = dialogChoiceAlloc();
    ref_142 = msgShow(msg_18);
/***************************************
[tab]私の出番かしらん♥
[choice(2)]一緒に行きましょう。
留守番ヨロシク。
[end_choice][clear]
***************************************/
    wait(ref_142);
    dialogFree(ref_141);
    ref_145 = bustupFade(ref_13f, rgb(0,0,0), 10);
    bustupWait(ref_145);
    bustupFree(ref_13f);
    choiceGetResult(var_0);
    bnz(var_0, label_1b5);
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    li(var_1, 0);
    li(var_2, 0);
    partyMemberCheck(var_2, ulala);
    bne(var_2, 0, label_156);
    b(label_159);
  label_156:
    bne(var_2, 1, label_159);
    bitSet(LBIT_0000);
    b(label_159);
  label_159:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, katsuya);
    bne(var_2, 0, label_15d);
    b(label_160);
  label_15d:
    bne(var_2, 1, label_160);
    bitSet(LBIT_0001);
    b(label_160);
  label_160:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, baofu);
    bne(var_2, 0, label_164);
    b(label_167);
  label_164:
    bne(var_2, 1, label_167);
    bitSet(LBIT_0002);
    b(label_167);
  label_167:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, nanjo);
    bne(var_2, 0, label_16b);
    b(label_16e);
  label_16b:
    bne(var_2, 1, label_16e);
    bitSet(LBIT_0003);
    b(label_16e);
  label_16e:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, elly);
    bne(var_2, 0, label_172);
    b(label_175);
  label_172:
    bne(var_2, 1, label_175);
    bitSet(LBIT_0004);
    b(label_175);
  label_175:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, tatsuya);
    bne(var_2, 0, label_179);
    b(label_17c);
  label_179:
    bne(var_2, 1, label_17c);
    bitSet(LBIT_0005);
    b(label_17c);
  label_17c:
    add(var_1, var_1, var_2);
    boutrange(var_1, 0, 3, label_180);
    b(label_1a6);
    b(label_1a5);
  label_180:
    choiceSetResult(5);
    ref_181 = bustupLoad(bustup_1);
    bustupWait(ref_181);
    ref_183 = bustupAlloc(ref_181, center, rgb(0,0,0));
    bustupFade(ref_183, rgb(128,0,0), 30);
    ref_185 = dialogChoiceAlloc();
    ref_186 = msgShow(msg_19);
/***************************************
[tab]んじゃあ、誰と交代すればいい？
[choice(6)][if_all(LBIT_0001)]克哉
[if_all(LBIT_0002)]パオフゥ
[if_all(LBIT_0003)]南条
[if_all(LBIT_0004)]エリー
[if_all(LBIT_0005)][tatsuya]
やめる
[end_choice][clear]
***************************************/
    wait(ref_186);
    dialogFree(ref_185);
    ref_189 = bustupFade(ref_183, rgb(0,0,0), 10);
    bustupWait(ref_189);
    bustupFree(ref_183);
    choiceGetResult(var_0);
    bne(var_0, 0, label_191);
    partyMemberRemove(katsuya);
    b(label_1a6);
    b(label_1a4);
  label_191:
    bne(var_0, 1, label_195);
    partyMemberRemove(baofu);
    b(label_1a6);
    b(label_1a4);
  label_195:
    bne(var_0, 2, label_199);
    partyMemberRemove(nanjo);
    b(label_1a6);
    b(label_1a4);
  label_199:
    bne(var_0, 3, label_19d);
    partyMemberRemove(elly);
    b(label_1a6);
    b(label_1a4);
  label_19d:
    bne(var_0, 4, label_1a1);
    partyMemberRemove(tatsuya);
    b(label_1a6);
    b(label_1a4);
  label_1a1:
    bne(var_0, 5, label_1a4);
    b(label_1b5);
    b(label_1a4);
  label_1a4:
    b(label_1a5);
  label_1a5:
    b(label_1f0);
  label_1a6:
    ref_1a6 = bustupLoad(bustup_17);
    bustupWait(ref_1a6);
    ref_1a8 = bustupAlloc(ref_1a6, left, rgb(0,0,0));
    bustupFade(ref_1a8, rgb(128,0,0), 30);
    ref_1aa = dialogAlloc();
    ref_1ab = msgShow(msg_20);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]おおうっ、嬉しい事言ってくれるじゃ～ん𝅘𝅥𝅮
[tab]私がいれば百人力よぉ。
[tab]バーンと任せといてぇ！
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_30, 1);
    partyMemberAdd(ulala);
    wait(ref_1ab);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_1aa);
    ref_1b1 = bustupFade(ref_1a8, rgb(0,0,0), 10);
    bustupWait(ref_1b1);
    bustupFree(ref_1a8);
    b(label_1f0);
  label_1b5:
    ref_1b5 = bustupLoad(bustup_1a);
    bustupWait(ref_1b5);
    ref_1b7 = bustupAlloc(ref_1b5, left, rgb(0,0,0));
    bustupFade(ref_1b7, rgb(128,0,0), 30);
    ref_1b9 = dialogAlloc();
    ref_1ba = msgShow(msg_21);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ガクッ。
[tab]こんなトコにいつまでもいたら、
[tab]鼻が伸びちゃうわよぉ！
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2e, 1);
    wait(ref_1ba);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_1b9);
    ref_1bf = bustupFade(ref_1b7, rgb(0,0,0), 10);
    bustupWait(ref_1bf);
    bustupFree(ref_1b7);
    b(label_1f0);
  label_1c3:
    ref_1c3 = bustupLoad(bustup_1f);
    bustupWait(ref_1c3);
    ref_1c5 = bustupAlloc(ref_1c3, left, rgb(0,0,0));
    bustupFade(ref_1c5, rgb(128,0,0), 30);
    ref_1c7 = dialogAlloc();
    ref_1c8 = msgShow(msg_22);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]あ…嫌な予感する…
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_6, 1);
    wait(ref_1c8);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_1c7);
    ref_1cd = bustupFade(ref_1c5, rgb(0,0,0), 10);
    bustupWait(ref_1cd);
    bustupFree(ref_1c5);
    choiceSetResult(1);
    ref_1d1 = bustupLoad(bustup_1);
    bustupWait(ref_1d1);
    ref_1d3 = bustupAlloc(ref_1d1, center, rgb(0,0,0));
    bustupFade(ref_1d3, rgb(128,0,0), 30);
    ref_1d5 = dialogChoiceAlloc();
    ref_1d6 = msgShow(msg_23);
/***************************************
[tab]嫌な予感する…
[choice(2)]留守番ヨロシク。
用はない。
[end_choice][clear]
***************************************/
    wait(ref_1d6);
    dialogFree(ref_1d5);
    ref_1d9 = bustupFade(ref_1d3, rgb(0,0,0), 10);
    bustupWait(ref_1d9);
    bustupFree(ref_1d3);
    choiceGetResult(var_0);
    bne(var_0, 0, label_1e1);
    partyMemberRemove(ulala);
    b(label_1b5);
    b(label_1f0);
  label_1e1:
    bne(var_0, 1, label_1f0);
    ref_1e2 = bustupLoad(bustup_18);
    bustupWait(ref_1e2);
    ref_1e4 = bustupAlloc(ref_1e2, left, rgb(0,0,0));
    bustupFade(ref_1e4, rgb(128,0,0), 30);
    ref_1e6 = dialogAlloc();
    ref_1e7 = msgShow(msg_24);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ホッ…[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1f, 1);
    wait(ref_1e7);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_1e6);
    ref_1ec = bustupFade(ref_1e4, rgb(0,0,0), 10);
    bustupWait(ref_1ec);
    bustupFree(ref_1e4);
    b(label_1f0);
  label_1f0:
    unitRestoreFacing(ulala);
    controlEnable();
    cameraControlDisable();
}

function B_KATUYYY()
{
    controlDisable();
    unitFacePlayer(katsuya);
    partyMemberCheck(var_0, katsuya);
    bnz(var_0, label_28b);
    ref_1f8 = bustupLoad(bustup_21);
    bustupWait(ref_1f8);
    ref_1fa = bustupAlloc(ref_1f8, left, rgb(0,0,0));
    bustupFade(ref_1fa, rgb(128,0,0), 30);
    ref_1fc = dialogAlloc();
    ref_1fd = msgShow(msg_25);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]僕も一緒に行こうか？
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_1fd);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_1fc);
    ref_202 = bustupFade(ref_1fa, rgb(0,0,0), 10);
    bustupWait(ref_202);
    bustupFree(ref_1fa);
    choiceSetResult(1);
    ref_206 = bustupLoad(bustup_1);
    bustupWait(ref_206);
    ref_208 = bustupAlloc(ref_206, center, rgb(0,0,0));
    bustupFade(ref_208, rgb(128,0,0), 30);
    ref_20a = dialogChoiceAlloc();
    ref_20b = msgShow(msg_26);
/***************************************
[tab]僕も一緒に行こうか？
[choice(2)]一緒に行きましょう。
留守番ヨロシク。
[end_choice][clear]
***************************************/
    wait(ref_20b);
    dialogFree(ref_20a);
    ref_20e = bustupFade(ref_208, rgb(0,0,0), 10);
    bustupWait(ref_20e);
    bustupFree(ref_208);
    choiceGetResult(var_0);
    bnz(var_0, label_27d);
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    li(var_1, 0);
    li(var_2, 0);
    partyMemberCheck(var_2, ulala);
    bne(var_2, 0, label_21f);
    b(label_222);
  label_21f:
    bne(var_2, 1, label_222);
    bitSet(LBIT_0000);
    b(label_222);
  label_222:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, katsuya);
    bne(var_2, 0, label_226);
    b(label_229);
  label_226:
    bne(var_2, 1, label_229);
    bitSet(LBIT_0001);
    b(label_229);
  label_229:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, baofu);
    bne(var_2, 0, label_22d);
    b(label_230);
  label_22d:
    bne(var_2, 1, label_230);
    bitSet(LBIT_0002);
    b(label_230);
  label_230:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, nanjo);
    bne(var_2, 0, label_234);
    b(label_237);
  label_234:
    bne(var_2, 1, label_237);
    bitSet(LBIT_0003);
    b(label_237);
  label_237:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, elly);
    bne(var_2, 0, label_23b);
    b(label_23e);
  label_23b:
    bne(var_2, 1, label_23e);
    bitSet(LBIT_0004);
    b(label_23e);
  label_23e:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, tatsuya);
    bne(var_2, 0, label_242);
    b(label_245);
  label_242:
    bne(var_2, 1, label_245);
    bitSet(LBIT_0005);
    b(label_245);
  label_245:
    add(var_1, var_1, var_2);
    boutrange(var_1, 0, 3, label_249);
    b(label_26e);
    b(label_26e);
  label_249:
    choiceSetResult(5);
    ref_24a = bustupLoad(bustup_1);
    bustupWait(ref_24a);
    ref_24c = bustupAlloc(ref_24a, center, rgb(0,0,0));
    bustupFade(ref_24c, rgb(128,0,0), 30);
    ref_24e = dialogChoiceAlloc();
    ref_24f = msgShow(msg_27);
/***************************************
[tab]だが定員オーバーだな。誰と交代すればいい？
[choice(6)][if_all(LBIT_0000)]うらら
[if_all(LBIT_0002)]パオフゥ
[if_all(LBIT_0003)]南条
[if_all(LBIT_0004)]エリー
[if_all(LBIT_0005)][tatsuya]
やめる
[end_choice][clear]
***************************************/
    wait(ref_24f);
    dialogFree(ref_24e);
    ref_252 = bustupFade(ref_24c, rgb(0,0,0), 10);
    bustupWait(ref_252);
    bustupFree(ref_24c);
    choiceGetResult(var_0);
    bne(var_0, 0, label_25a);
    partyMemberRemove(ulala);
    b(label_26e);
    b(label_26d);
  label_25a:
    bne(var_0, 1, label_25e);
    partyMemberRemove(baofu);
    b(label_26e);
    b(label_26d);
  label_25e:
    bne(var_0, 2, label_262);
    partyMemberRemove(nanjo);
    b(label_26e);
    b(label_26d);
  label_262:
    bne(var_0, 3, label_266);
    partyMemberRemove(elly);
    b(label_26e);
    b(label_26d);
  label_266:
    bne(var_0, 4, label_26a);
    partyMemberRemove(tatsuya);
    b(label_26e);
    b(label_26d);
  label_26a:
    bne(var_0, 5, label_26d);
    b(label_27d);
    b(label_26d);
  label_26d:
    b(label_26e);
  label_26e:
    ref_26e = bustupLoad(bustup_21);
    bustupWait(ref_26e);
    ref_270 = bustupAlloc(ref_26e, left, rgb(0,0,0));
    bustupFade(ref_270, rgb(128,0,0), 30);
    ref_272 = dialogAlloc();
    ref_273 = msgShow(msg_28);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]市民を守る事こそ僕の勤めだ！
[tab]任せておきたまえ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1e, 1);
    partyMemberAdd(katsuya);
    wait(ref_273);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_272);
    ref_279 = bustupFade(ref_270, rgb(0,0,0), 10);
    bustupWait(ref_279);
    bustupFree(ref_270);
    b(label_2ac);
  label_27d:
    ref_27d = bustupLoad(bustup_21);
    bustupWait(ref_27d);
    ref_27f = bustupAlloc(ref_27d, left, rgb(0,0,0));
    bustupFade(ref_27f, rgb(128,0,0), 30);
    ref_281 = dialogAlloc();
    ref_282 = msgShow(msg_29);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]そうか…
[tab]ではここで待機していよう。
[tab]無理はするなよ。
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_282);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_281);
    ref_287 = bustupFade(ref_27f, rgb(0,0,0), 10);
    bustupWait(ref_287);
    bustupFree(ref_27f);
    b(label_2ac);
  label_28b:
    ref_28b = bustupLoad(bustup_21);
    bustupWait(ref_28b);
    ref_28d = bustupAlloc(ref_28b, left, rgb(0,0,0));
    bustupFade(ref_28d, rgb(128,0,0), 30);
    ref_28f = dialogAlloc();
    ref_290 = msgShow(msg_30);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ん？
[tab]何か用か？[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_290);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_28f);
    ref_295 = bustupFade(ref_28d, rgb(0,0,0), 10);
    bustupWait(ref_295);
    bustupFree(ref_28d);
    choiceSetResult(1);
    ref_299 = bustupLoad(bustup_1);
    bustupWait(ref_299);
    ref_29b = bustupAlloc(ref_299, center, rgb(0,0,0));
    bustupFade(ref_29b, rgb(128,0,0), 30);
    ref_29d = dialogChoiceAlloc();
    ref_29e = msgShow(msg_31);
/***************************************
[tab]何か用か？
[choice(2)]留守番ヨロシク。
用はない。
[end_choice][clear]
***************************************/
    wait(ref_29e);
    dialogFree(ref_29d);
    ref_2a1 = bustupFade(ref_29b, rgb(0,0,0), 10);
    bustupWait(ref_2a1);
    bustupFree(ref_29b);
    choiceGetResult(var_0);
    bne(var_0, 0, label_2a9);
    partyMemberRemove(katsuya);
    b(label_27d);
    b(label_2ac);
  label_2a9:
    bne(var_0, 1, label_2ac);
    b(label_2ac);
    b(label_2ac);
  label_2ac:
    unitRestoreFacing(katsuya);
    controlEnable();
    cameraControlDisable();
}

function B_PAO()
{
    controlDisable();
    unitFacePlayer(baofu);
    partyMemberCheck(var_0, baofu);
    bnz(var_0, label_347);
    ref_2b4 = bustupLoad(bustup_2d);
    bustupWait(ref_2b4);
    ref_2b6 = bustupAlloc(ref_2b4, left, rgb(0,0,0));
    bustupFade(ref_2b6, rgb(128,0,0), 30);
    ref_2b8 = dialogAlloc();
    ref_2b9 = msgShow(msg_32);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]どうも頼りねぇなぁ。
[tab]俺がいなくて大丈夫か？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_2b9);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_2b8);
    ref_2be = bustupFade(ref_2b6, rgb(0,0,0), 10);
    bustupWait(ref_2be);
    bustupFree(ref_2b6);
    choiceSetResult(1);
    ref_2c2 = bustupLoad(bustup_1);
    bustupWait(ref_2c2);
    ref_2c4 = bustupAlloc(ref_2c2, center, rgb(0,0,0));
    bustupFade(ref_2c4, rgb(128,0,0), 30);
    ref_2c6 = dialogChoiceAlloc();
    ref_2c7 = msgShow(msg_33);
/***************************************
[tab]俺がいなくて大丈夫か？
[choice(2)]一緒に行きましょう。
留守番ヨロシク。
[end_choice][clear]
***************************************/
    wait(ref_2c7);
    dialogFree(ref_2c6);
    ref_2ca = bustupFade(ref_2c4, rgb(0,0,0), 10);
    bustupWait(ref_2ca);
    bustupFree(ref_2c4);
    choiceGetResult(var_0);
    bnz(var_0, label_339);
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    li(var_1, 0);
    li(var_2, 0);
    partyMemberCheck(var_2, ulala);
    bne(var_2, 0, label_2db);
    b(label_2de);
  label_2db:
    bne(var_2, 1, label_2de);
    bitSet(LBIT_0000);
    b(label_2de);
  label_2de:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, katsuya);
    bne(var_2, 0, label_2e2);
    b(label_2e5);
  label_2e2:
    bne(var_2, 1, label_2e5);
    bitSet(LBIT_0001);
    b(label_2e5);
  label_2e5:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, baofu);
    bne(var_2, 0, label_2e9);
    b(label_2ec);
  label_2e9:
    bne(var_2, 1, label_2ec);
    bitSet(LBIT_0002);
    b(label_2ec);
  label_2ec:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, nanjo);
    bne(var_2, 0, label_2f0);
    b(label_2f3);
  label_2f0:
    bne(var_2, 1, label_2f3);
    bitSet(LBIT_0003);
    b(label_2f3);
  label_2f3:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, elly);
    bne(var_2, 0, label_2f7);
    b(label_2fa);
  label_2f7:
    bne(var_2, 1, label_2fa);
    bitSet(LBIT_0004);
    b(label_2fa);
  label_2fa:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, tatsuya);
    bne(var_2, 0, label_2fe);
    b(label_301);
  label_2fe:
    bne(var_2, 1, label_301);
    bitSet(LBIT_0005);
    b(label_301);
  label_301:
    add(var_1, var_1, var_2);
    boutrange(var_1, 0, 3, label_305);
    b(label_32a);
    b(label_32a);
  label_305:
    choiceSetResult(5);
    ref_306 = bustupLoad(bustup_1);
    bustupWait(ref_306);
    ref_308 = bustupAlloc(ref_306, center, rgb(0,0,0));
    bustupFade(ref_308, rgb(128,0,0), 30);
    ref_30a = dialogChoiceAlloc();
    ref_30b = msgShow(msg_34);
/***************************************
[tab]じゃあ、代わりの留守番を決めてくれや。
[choice(6)][if_all(LBIT_0000)]うらら
[if_all(LBIT_0001)]克哉
[if_all(LBIT_0003)]南条
[if_all(LBIT_0004)]エリー
[if_all(LBIT_0005)][tatsuya]
やめる
[end_choice][clear]
***************************************/
    wait(ref_30b);
    dialogFree(ref_30a);
    ref_30e = bustupFade(ref_308, rgb(0,0,0), 10);
    bustupWait(ref_30e);
    bustupFree(ref_308);
    choiceGetResult(var_0);
    bne(var_0, 0, label_316);
    partyMemberRemove(ulala);
    b(label_32a);
    b(label_329);
  label_316:
    bne(var_0, 1, label_31a);
    partyMemberRemove(katsuya);
    b(label_32a);
    b(label_329);
  label_31a:
    bne(var_0, 2, label_31e);
    partyMemberRemove(nanjo);
    b(label_32a);
    b(label_329);
  label_31e:
    bne(var_0, 3, label_322);
    partyMemberRemove(elly);
    b(label_32a);
    b(label_329);
  label_322:
    bne(var_0, 4, label_326);
    partyMemberRemove(tatsuya);
    b(label_32a);
    b(label_329);
  label_326:
    bne(var_0, 5, label_329);
    b(label_339);
    b(label_329);
  label_329:
    b(label_32a);
  label_32a:
    ref_32a = bustupLoad(bustup_2d);
    bustupWait(ref_32a);
    ref_32c = bustupAlloc(ref_32a, left, rgb(0,0,0));
    bustupFade(ref_32c, rgb(128,0,0), 30);
    ref_32e = dialogAlloc();
    ref_32f = msgShow(msg_35);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]へっ、最初から素直にそう言えや。
[tab]まぁ、任せときな。
[tab]俺の指弾はチャカより速いんだ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_30, 1);
    partyMemberAdd(baofu);
    wait(ref_32f);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_32e);
    ref_335 = bustupFade(ref_32c, rgb(0,0,0), 10);
    bustupWait(ref_335);
    bustupFree(ref_32c);
    b(label_367);
  label_339:
    ref_339 = bustupLoad(bustup_2d);
    bustupWait(ref_339);
    ref_33b = bustupAlloc(ref_339, left, rgb(0,0,0));
    bustupFade(ref_33b, rgb(128,0,0), 30);
    ref_33d = dialogAlloc();
    ref_33e = msgShow(msg_36);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]チッ…留守番か…
[tab]退屈で腕がなまっちまうぜ。
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_33e);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_33d);
    ref_343 = bustupFade(ref_33b, rgb(0,0,0), 10);
    bustupWait(ref_343);
    bustupFree(ref_33b);
    b(label_367);
  label_347:
    ref_347 = bustupLoad(bustup_2d);
    bustupWait(ref_347);
    ref_349 = bustupAlloc(ref_347, left, rgb(0,0,0));
    bustupFade(ref_349, rgb(128,0,0), 30);
    ref_34b = dialogAlloc();
    ref_34c = msgShow(msg_37);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]あん？[tab]何の用だ？
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_34c);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_34b);
    ref_351 = bustupFade(ref_349, rgb(0,0,0), 10);
    bustupWait(ref_351);
    bustupFree(ref_349);
    choiceSetResult(1);
    ref_355 = bustupLoad(bustup_1);
    bustupWait(ref_355);
    ref_357 = bustupAlloc(ref_355, center, rgb(0,0,0));
    bustupFade(ref_357, rgb(128,0,0), 30);
    ref_359 = dialogChoiceAlloc();
    ref_35a = msgShow(msg_38);
/***************************************
[tab]何の用だ？
[choice(2)]留守番ヨロシク。
用はない。
[end_choice][clear]
***************************************/
    wait(ref_35a);
    dialogFree(ref_359);
    ref_35d = bustupFade(ref_357, rgb(0,0,0), 10);
    bustupWait(ref_35d);
    bustupFree(ref_357);
    choiceGetResult(var_0);
    bne(var_0, 0, label_365);
    partyMemberRemove(baofu);
    b(label_339);
    b(label_367);
  label_365:
    bne(var_0, 1, label_367);
    b(label_367);
  label_367:
    unitRestoreFacing(baofu);
    controlEnable();
    cameraControlDisable();
}

function B_NANJ()
{
    controlDisable();
    unitFacePlayer(nanjo);
    partyMemberCheck(var_0, nanjo);
    bnz(var_0, label_402);
    ref_36f = bustupLoad(bustup_36);
    bustupWait(ref_36f);
    ref_371 = bustupAlloc(ref_36f, left, rgb(0,0,0));
    bustupFade(ref_371, rgb(128,0,0), 30);
    ref_373 = dialogAlloc();
    ref_374 = msgShow(msg_39);
/***************************************
[color(yellow)]南条[color(white)]
[tab]和を以って貴しとなす。
[tab]俺も行こう。
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_374);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_373);
    ref_379 = bustupFade(ref_371, rgb(0,0,0), 10);
    bustupWait(ref_379);
    bustupFree(ref_371);
    choiceSetResult(1);
    ref_37d = bustupLoad(bustup_1);
    bustupWait(ref_37d);
    ref_37f = bustupAlloc(ref_37d, center, rgb(0,0,0));
    bustupFade(ref_37f, rgb(128,0,0), 30);
    ref_381 = dialogChoiceAlloc();
    ref_382 = msgShow(msg_40);
/***************************************
[tab]俺も行こう。
[choice(2)]一緒に行きましょう。
留守番ヨロシク。
[end_choice][clear]
***************************************/
    wait(ref_382);
    dialogFree(ref_381);
    ref_385 = bustupFade(ref_37f, rgb(0,0,0), 10);
    bustupWait(ref_385);
    bustupFree(ref_37f);
    choiceGetResult(var_0);
    bnz(var_0, label_3f4);
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    li(var_1, 0);
    li(var_2, 0);
    partyMemberCheck(var_2, ulala);
    bne(var_2, 0, label_396);
    b(label_399);
  label_396:
    bne(var_2, 1, label_399);
    bitSet(LBIT_0000);
    b(label_399);
  label_399:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, katsuya);
    bne(var_2, 0, label_39d);
    b(label_3a0);
  label_39d:
    bne(var_2, 1, label_3a0);
    bitSet(LBIT_0001);
    b(label_3a0);
  label_3a0:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, baofu);
    bne(var_2, 0, label_3a4);
    b(label_3a7);
  label_3a4:
    bne(var_2, 1, label_3a7);
    bitSet(LBIT_0002);
    b(label_3a7);
  label_3a7:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, nanjo);
    bne(var_2, 0, label_3ab);
    b(label_3ae);
  label_3ab:
    bne(var_2, 1, label_3ae);
    bitSet(LBIT_0003);
    b(label_3ae);
  label_3ae:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, elly);
    bne(var_2, 0, label_3b2);
    b(label_3b5);
  label_3b2:
    bne(var_2, 1, label_3b5);
    bitSet(LBIT_0004);
    b(label_3b5);
  label_3b5:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, tatsuya);
    bne(var_2, 0, label_3b9);
    b(label_3bc);
  label_3b9:
    bne(var_2, 1, label_3bc);
    bitSet(LBIT_0005);
    b(label_3bc);
  label_3bc:
    add(var_1, var_1, var_2);
    boutrange(var_1, 0, 3, label_3c0);
    b(label_3e5);
    b(label_3e5);
  label_3c0:
    choiceSetResult(5);
    ref_3c1 = bustupLoad(bustup_1);
    bustupWait(ref_3c1);
    ref_3c3 = bustupAlloc(ref_3c1, center, rgb(0,0,0));
    bustupFade(ref_3c3, rgb(128,0,0), 30);
    ref_3c5 = dialogChoiceAlloc();
    ref_3c6 = msgShow(msg_41);
/***************************************
[tab]では、誰と交代しようか？
[choice(6)][if_all(LBIT_0000)]うらら
[if_all(LBIT_0001)]克哉
[if_all(LBIT_0002)]パオフゥ
[if_all(LBIT_0004)]エリー
[if_all(LBIT_0005)][tatsuya]
やめる
[end_choice][clear]
***************************************/
    wait(ref_3c6);
    dialogFree(ref_3c5);
    ref_3c9 = bustupFade(ref_3c3, rgb(0,0,0), 10);
    bustupWait(ref_3c9);
    bustupFree(ref_3c3);
    choiceGetResult(var_0);
    bne(var_0, 0, label_3d1);
    partyMemberRemove(ulala);
    b(label_3e5);
    b(label_3e4);
  label_3d1:
    bne(var_0, 1, label_3d5);
    partyMemberRemove(katsuya);
    b(label_3e5);
    b(label_3e4);
  label_3d5:
    bne(var_0, 2, label_3d9);
    partyMemberRemove(baofu);
    b(label_3e5);
    b(label_3e4);
  label_3d9:
    bne(var_0, 3, label_3dd);
    partyMemberRemove(elly);
    b(label_3e5);
    b(label_3e4);
  label_3dd:
    bne(var_0, 4, label_3e1);
    partyMemberRemove(tatsuya);
    b(label_3e5);
    b(label_3e4);
  label_3e1:
    bne(var_0, 5, label_3e4);
    b(label_3f4);
    b(label_3e4);
  label_3e4:
    b(label_3e5);
  label_3e5:
    ref_3e5 = bustupLoad(bustup_36);
    bustupWait(ref_3e5);
    ref_3e7 = bustupAlloc(ref_3e5, left, rgb(0,0,0));
    bustupFade(ref_3e7, rgb(128,0,0), 30);
    ref_3e9 = dialogAlloc();
    ref_3ea = msgShow(msg_42);
/***************************************
[color(yellow)]南条[color(white)]
[tab]承知した。[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_24, 1);
    partyMemberAdd(nanjo);
    wait(ref_3ea);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_3e9);
    ref_3f0 = bustupFade(ref_3e7, rgb(0,0,0), 10);
    bustupWait(ref_3f0);
    bustupFree(ref_3e7);
    b(label_422);
  label_3f4:
    ref_3f4 = bustupLoad(bustup_36);
    bustupWait(ref_3f4);
    ref_3f6 = bustupAlloc(ref_3f4, left, rgb(0,0,0));
    bustupFade(ref_3f6, rgb(128,0,0), 30);
    ref_3f8 = dialogAlloc();
    ref_3f9 = msgShow(msg_43);
/***************************************
[color(yellow)]南条[color(white)]
[tab]承知…した…
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_6, 1);
    wait(ref_3f9);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_3f8);
    ref_3fe = bustupFade(ref_3f6, rgb(0,0,0), 10);
    bustupWait(ref_3fe);
    bustupFree(ref_3f6);
    b(label_422);
  label_402:
    ref_402 = bustupLoad(bustup_36);
    bustupWait(ref_402);
    ref_404 = bustupAlloc(ref_402, left, rgb(0,0,0));
    bustupFade(ref_404, rgb(128,0,0), 30);
    ref_406 = dialogAlloc();
    ref_407 = msgShow(msg_44);
/***************************************
[color(yellow)]南条[color(white)]
[tab]駿足長阪を思う。
[tab]で…何か？
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_407);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_406);
    ref_40c = bustupFade(ref_404, rgb(0,0,0), 10);
    bustupWait(ref_40c);
    bustupFree(ref_404);
    choiceSetResult(1);
    ref_410 = bustupLoad(bustup_1);
    bustupWait(ref_410);
    ref_412 = bustupAlloc(ref_410, center, rgb(0,0,0));
    bustupFade(ref_412, rgb(128,0,0), 30);
    ref_414 = dialogChoiceAlloc();
    ref_415 = msgShow(msg_45);
/***************************************
[tab]何か？
[choice(2)]留守番ヨロシク。
用はない。
[end_choice][clear]
***************************************/
    wait(ref_415);
    dialogFree(ref_414);
    ref_418 = bustupFade(ref_412, rgb(0,0,0), 10);
    bustupWait(ref_418);
    bustupFree(ref_412);
    choiceGetResult(var_0);
    bne(var_0, 0, label_420);
    partyMemberRemove(nanjo);
    b(label_3f4);
    b(label_422);
  label_420:
    bne(var_0, 1, label_422);
    b(label_422);
  label_422:
    unitRestoreFacing(nanjo);
    controlEnable();
    cameraControlDisable();
}

function B_ERI()
{
    controlDisable();
    unitFacePlayer(elly);
    partyMemberCheck(var_0, elly);
    bnz(var_0, label_4bd);
    ref_42a = bustupLoad(bustup_3d);
    bustupWait(ref_42a);
    ref_42c = bustupAlloc(ref_42a, left, rgb(0,0,0));
    bustupFade(ref_42c, rgb(128,0,0), 30);
    ref_42e = dialogAlloc();
    ref_42f = msgShow(msg_46);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｈｉ！
[tab]私の出番でしょうか？
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_42f);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_42e);
    ref_434 = bustupFade(ref_42c, rgb(0,0,0), 10);
    bustupWait(ref_434);
    bustupFree(ref_42c);
    choiceSetResult(1);
    ref_438 = bustupLoad(bustup_1);
    bustupWait(ref_438);
    ref_43a = bustupAlloc(ref_438, center, rgb(0,0,0));
    bustupFade(ref_43a, rgb(128,0,0), 30);
    ref_43c = dialogChoiceAlloc();
    ref_43d = msgShow(msg_47);
/***************************************
[tab]私の出番でしょうか？
[choice(2)]一緒に行きましょう。
留守番ヨロシク。
[end_choice][clear]
***************************************/
    wait(ref_43d);
    dialogFree(ref_43c);
    ref_440 = bustupFade(ref_43a, rgb(0,0,0), 10);
    bustupWait(ref_440);
    bustupFree(ref_43a);
    choiceGetResult(var_0);
    bnz(var_0, label_4af);
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    li(var_1, 0);
    li(var_2, 0);
    partyMemberCheck(var_2, ulala);
    bne(var_2, 0, label_451);
    b(label_454);
  label_451:
    bne(var_2, 1, label_454);
    bitSet(LBIT_0000);
    b(label_454);
  label_454:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, katsuya);
    bne(var_2, 0, label_458);
    b(label_45b);
  label_458:
    bne(var_2, 1, label_45b);
    bitSet(LBIT_0001);
    b(label_45b);
  label_45b:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, baofu);
    bne(var_2, 0, label_45f);
    b(label_462);
  label_45f:
    bne(var_2, 1, label_462);
    bitSet(LBIT_0002);
    b(label_462);
  label_462:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, nanjo);
    bne(var_2, 0, label_466);
    b(label_469);
  label_466:
    bne(var_2, 1, label_469);
    bitSet(LBIT_0003);
    b(label_469);
  label_469:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, elly);
    bne(var_2, 0, label_46d);
    b(label_470);
  label_46d:
    bne(var_2, 1, label_470);
    bitSet(LBIT_0004);
    b(label_470);
  label_470:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, tatsuya);
    bne(var_2, 0, label_474);
    b(label_477);
  label_474:
    bne(var_2, 1, label_477);
    bitSet(LBIT_0005);
    b(label_477);
  label_477:
    add(var_1, var_1, var_2);
    boutrange(var_1, 0, 3, label_47b);
    b(label_4a0);
    b(label_4a0);
  label_47b:
    choiceSetResult(5);
    ref_47c = bustupLoad(bustup_1);
    bustupWait(ref_47c);
    ref_47e = bustupAlloc(ref_47c, center, rgb(0,0,0));
    bustupFade(ref_47e, rgb(128,0,0), 30);
    ref_480 = dialogChoiceAlloc();
    ref_481 = msgShow(msg_48);
/***************************************
[tab]では、どなたとＣｈａｎｇｅしましょう？
[choice(6)][if_all(LBIT_0000)]うらら
[if_all(LBIT_0001)]克哉
[if_all(LBIT_0002)]パオフゥ
[if_all(LBIT_0003)]南条
[if_all(LBIT_0005)][tatsuya]
やめる
[end_choice][clear]
***************************************/
    wait(ref_481);
    dialogFree(ref_480);
    ref_484 = bustupFade(ref_47e, rgb(0,0,0), 10);
    bustupWait(ref_484);
    bustupFree(ref_47e);
    choiceGetResult(var_0);
    bne(var_0, 0, label_48c);
    partyMemberRemove(ulala);
    b(label_4a0);
    b(label_49f);
  label_48c:
    bne(var_0, 1, label_490);
    partyMemberRemove(katsuya);
    b(label_4a0);
    b(label_49f);
  label_490:
    bne(var_0, 2, label_494);
    partyMemberRemove(baofu);
    b(label_4a0);
    b(label_49f);
  label_494:
    bne(var_0, 3, label_498);
    partyMemberRemove(nanjo);
    b(label_4a0);
    b(label_49f);
  label_498:
    bne(var_0, 4, label_49c);
    partyMemberRemove(tatsuya);
    b(label_4a0);
    b(label_49f);
  label_49c:
    bne(var_0, 5, label_49f);
    b(label_4af);
    b(label_49f);
  label_49f:
    b(label_4a0);
  label_4a0:
    ref_4a0 = bustupLoad(bustup_3d);
    bustupWait(ref_4a0);
    ref_4a2 = bustupAlloc(ref_4a0, left, rgb(0,0,0));
    bustupFade(ref_4a2, rgb(128,0,0), 30);
    ref_4a4 = dialogAlloc();
    ref_4a5 = msgShow(msg_49);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｙｅｓ！
[tab]退屈で、うずうずしてましたの。
[tab]頑張らせていただきますわ！
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_1e, 1);
    partyMemberAdd(elly);
    wait(ref_4a5);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_4a4);
    ref_4ab = bustupFade(ref_4a2, rgb(0,0,0), 10);
    bustupWait(ref_4ab);
    bustupFree(ref_4a2);
    b(label_4dd);
  label_4af:
    ref_4af = bustupLoad(bustup_3d);
    bustupWait(ref_4af);
    ref_4b1 = bustupAlloc(ref_4af, left, rgb(0,0,0));
    bustupFade(ref_4b1, rgb(128,0,0), 30);
    ref_4b3 = dialogAlloc();
    ref_4b4 = msgShow(msg_50);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｏｈ…
[tab]残念ですわ。
[tab]では、ここで待ってますわね。
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_6, 1);
    wait(ref_4b4);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_4b3);
    ref_4b9 = bustupFade(ref_4b1, rgb(0,0,0), 10);
    bustupWait(ref_4b9);
    bustupFree(ref_4b1);
    b(label_4dd);
  label_4bd:
    ref_4bd = bustupLoad(bustup_3d);
    bustupWait(ref_4bd);
    ref_4bf = bustupAlloc(ref_4bd, left, rgb(0,0,0));
    bustupFade(ref_4bf, rgb(128,0,0), 30);
    ref_4c1 = dialogAlloc();
    ref_4c2 = msgShow(msg_51);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｈｅｌｌｏ．
[tab]何かご用ですか？[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_4c2);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_4c1);
    ref_4c7 = bustupFade(ref_4bf, rgb(0,0,0), 10);
    bustupWait(ref_4c7);
    bustupFree(ref_4bf);
    choiceSetResult(1);
    ref_4cb = bustupLoad(bustup_1);
    bustupWait(ref_4cb);
    ref_4cd = bustupAlloc(ref_4cb, center, rgb(0,0,0));
    bustupFade(ref_4cd, rgb(128,0,0), 30);
    ref_4cf = dialogChoiceAlloc();
    ref_4d0 = msgShow(msg_52);
/***************************************
[tab]何かご用ですか？
[choice(2)]留守番ヨロシク。
用はない。
[end_choice][clear]
***************************************/
    wait(ref_4d0);
    dialogFree(ref_4cf);
    ref_4d3 = bustupFade(ref_4cd, rgb(0,0,0), 10);
    bustupWait(ref_4d3);
    bustupFree(ref_4cd);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4db);
    partyMemberRemove(elly);
    b(label_4af);
    b(label_4dd);
  label_4db:
    bne(var_0, 1, label_4dd);
    b(label_4dd);
  label_4dd:
    unitRestoreFacing(elly);
    controlEnable();
    cameraControlDisable();
}

function B_TATU()
{
    controlDisable();
    unitFacePlayer(tatsuya);
    partyMemberCheck(var_0, tatsuya);
    bnz(var_0, label_572);
    ref_4e5 = bustupLoad(bustup_b);
    bustupWait(ref_4e5);
    ref_4e7 = bustupAlloc(ref_4e5, left, rgb(0,0,0));
    bustupFade(ref_4e7, rgb(128,0,0), 30);
    ref_4e9 = dialogAlloc();
    ref_4ea = msgShow(msg_53);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]やはり心配だ。
[tab]俺も行くよ。
[wait][clear]
***************************************/
    wait(ref_4ea);
    dialogFree(ref_4e9);
    ref_4ed = bustupFade(ref_4e7, rgb(0,0,0), 10);
    bustupWait(ref_4ed);
    bustupFree(ref_4e7);
    choiceSetResult(1);
    ref_4f1 = bustupLoad(bustup_1);
    bustupWait(ref_4f1);
    ref_4f3 = bustupAlloc(ref_4f1, center, rgb(0,0,0));
    bustupFade(ref_4f3, rgb(128,0,0), 30);
    ref_4f5 = dialogChoiceAlloc();
    ref_4f6 = msgShow(msg_54);
/***************************************
[tab]俺も行くよ。
[choice(2)]一緒に行きましょう。
留守番ヨロシク。
[end_choice][clear]
***************************************/
    wait(ref_4f6);
    dialogFree(ref_4f5);
    ref_4f9 = bustupFade(ref_4f3, rgb(0,0,0), 10);
    bustupWait(ref_4f9);
    bustupFree(ref_4f3);
    choiceGetResult(var_0);
    bnz(var_0, label_566);
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    bitClear(LBIT_0006);
    li(var_1, 0);
    li(var_2, 0);
    partyMemberCheck(var_2, ulala);
    bne(var_2, 0, label_50a);
    b(label_50d);
  label_50a:
    bne(var_2, 1, label_50d);
    bitSet(LBIT_0000);
    b(label_50d);
  label_50d:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, katsuya);
    bne(var_2, 0, label_511);
    b(label_514);
  label_511:
    bne(var_2, 1, label_514);
    bitSet(LBIT_0001);
    b(label_514);
  label_514:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, baofu);
    bne(var_2, 0, label_518);
    b(label_51b);
  label_518:
    bne(var_2, 1, label_51b);
    bitSet(LBIT_0002);
    b(label_51b);
  label_51b:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, nanjo);
    bne(var_2, 0, label_51f);
    b(label_522);
  label_51f:
    bne(var_2, 1, label_522);
    bitSet(LBIT_0003);
    b(label_522);
  label_522:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, elly);
    bne(var_2, 0, label_526);
    b(label_529);
  label_526:
    bne(var_2, 1, label_529);
    bitSet(LBIT_0004);
    b(label_529);
  label_529:
    add(var_1, var_1, var_2);
    partyMemberCheck(var_2, tatsuya);
    bne(var_2, 0, label_52d);
    b(label_530);
  label_52d:
    bne(var_2, 1, label_530);
    bitSet(LBIT_0005);
    b(label_530);
  label_530:
    add(var_1, var_1, var_2);
    boutrange(var_1, 0, 3, label_534);
    b(label_559);
    b(label_559);
  label_534:
    choiceSetResult(5);
    ref_535 = bustupLoad(bustup_1);
    bustupWait(ref_535);
    ref_537 = bustupAlloc(ref_535, center, rgb(0,0,0));
    bustupFade(ref_537, rgb(128,0,0), 30);
    ref_539 = dialogChoiceAlloc();
    ref_53a = msgShow(msg_55);
/***************************************
[tab]誰と交代すればいい？
[choice(6)][if_all(LBIT_0000)]うらら
[if_all(LBIT_0001)]克哉
[if_all(LBIT_0002)]パオフゥ
[if_all(LBIT_0003)]南条
[if_all(LBIT_0004)]エリー
やめる
[end_choice][clear]
***************************************/
    wait(ref_53a);
    dialogFree(ref_539);
    ref_53d = bustupFade(ref_537, rgb(0,0,0), 10);
    bustupWait(ref_53d);
    bustupFree(ref_537);
    choiceGetResult(var_0);
    bne(var_0, 0, label_545);
    partyMemberRemove(ulala);
    b(label_559);
    b(label_558);
  label_545:
    bne(var_0, 1, label_549);
    partyMemberRemove(katsuya);
    b(label_559);
    b(label_558);
  label_549:
    bne(var_0, 2, label_54d);
    partyMemberRemove(baofu);
    b(label_559);
    b(label_558);
  label_54d:
    bne(var_0, 3, label_551);
    partyMemberRemove(nanjo);
    b(label_559);
    b(label_558);
  label_551:
    bne(var_0, 4, label_555);
    partyMemberRemove(elly);
    b(label_559);
    b(label_558);
  label_555:
    bne(var_0, 5, label_558);
    b(label_566);
    b(label_558);
  label_558:
    b(label_559);
  label_559:
    ref_559 = bustupLoad(bustup_b);
    bustupWait(ref_559);
    ref_55b = bustupAlloc(ref_559, left, rgb(0,0,0));
    bustupFade(ref_55b, rgb(128,0,0), 30);
    ref_55d = dialogAlloc();
    ref_55e = msgShow(msg_56);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]ありがとう。
[tab]仲間達と約束したんだ。
[tab]舞耶姉を守るって…
[wait][clear]
***************************************/
    partyMemberAdd(tatsuya);
    wait(ref_55e);
    dialogFree(ref_55d);
    ref_562 = bustupFade(ref_55b, rgb(0,0,0), 10);
    bustupWait(ref_562);
    bustupFree(ref_55b);
    b(label_590);
  label_566:
    ref_566 = bustupLoad(bustup_b);
    bustupWait(ref_566);
    ref_568 = bustupAlloc(ref_566, left, rgb(0,0,0));
    bustupFade(ref_568, rgb(128,0,0), 30);
    ref_56a = dialogAlloc();
    ref_56b = msgShow(msg_57);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]……
[tab]分かった。
[tab]ここで待ってるよ。
[wait][clear]
***************************************/
    wait(ref_56b);
    dialogFree(ref_56a);
    ref_56e = bustupFade(ref_568, rgb(0,0,0), 10);
    bustupWait(ref_56e);
    bustupFree(ref_568);
    b(label_590);
  label_572:
    ref_572 = bustupLoad(bustup_b);
    bustupWait(ref_572);
    ref_574 = bustupAlloc(ref_572, left, rgb(0,0,0));
    bustupFade(ref_574, rgb(128,0,0), 30);
    ref_576 = dialogAlloc();
    ref_577 = msgShow(msg_58);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]どうしたんだ…？
[wait][clear]
***************************************/
    wait(ref_577);
    dialogFree(ref_576);
    ref_57a = bustupFade(ref_574, rgb(0,0,0), 10);
    bustupWait(ref_57a);
    bustupFree(ref_574);
    choiceSetResult(1);
    ref_57e = bustupLoad(bustup_1);
    bustupWait(ref_57e);
    ref_580 = bustupAlloc(ref_57e, center, rgb(0,0,0));
    bustupFade(ref_580, rgb(128,0,0), 30);
    ref_582 = dialogChoiceAlloc();
    ref_583 = msgShow(msg_59);
/***************************************
[tab]どうしたんだ…？
[choice(2)]留守番ヨロシク。
用はない。
[end_choice][clear]
***************************************/
    wait(ref_583);
    dialogFree(ref_582);
    ref_586 = bustupFade(ref_580, rgb(0,0,0), 10);
    bustupWait(ref_586);
    bustupFree(ref_580);
    choiceGetResult(var_0);
    bne(var_0, 0, label_58e);
    partyMemberRemove(tatsuya);
    b(label_566);
    b(label_590);
  label_58e:
    bne(var_0, 1, label_590);
    b(label_590);
  label_590:
    unitRestoreFacing(tatsuya);
    controlEnable();
    cameraControlDisable();
}

function IGORU()
{
    controlDisable();
    ref_595 = shopOverlayInit();
    bitGet(var_0, VBIT_MUTATION_ON);
    bne(var_0, 0, label_59a);
    b(label_5d3);
    b(label_5a3);
  label_59a:
    bne(var_0, 1, label_5a3);
    bitGet(var_0, VBIT_MUT_MES_OFF);
    bne(var_0, 0, label_59f);
    b(label_5a3);
    b(label_5a2);
  label_59f:
    bne(var_0, 1, label_5a2);
    b(label_5d3);
    b(label_5a2);
  label_5a2:
    b(label_5a3);
  label_5a3:
    ref_5a3 = bustupLoad(bustup_e0);
    bustupWait(ref_5a3);
    ref_5a5 = bustupAlloc(ref_5a3, right, rgb(0,0,0));
    bustupFade(ref_5a5, rgb(128,0,0), 30);
    ref_5a7 = dialogAlloc();
    ref_5a8 = msgShow(msg_60);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]おや？
[tab]新しい姿に生まれ変わろうとしている
[tab]ペルソナがいるようですな。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_5a8);
    ref_5ac = msgShow(msg_61);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]おっと、説明するのを忘れていましたが…
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_5ac);
    ref_5b0 = msgShow(msg_62);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]合体スキルというものを、ご存じですかな？
[tab]これを使うと、たまにペルソナが突然変異を
[tab]起こすことがあります。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_5b0);
    ref_5b4 = msgShow(msg_63);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]それは基本能力の上昇であったり、新しい
[tab]スキルの取得であったりするのですが、中には
[tab]別のペルソナに生まれ変わる場合もあります。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_8, 1);
    sync();
    wait(ref_5b4);
    ref_5b8 = msgShow(msg_64);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ただ、この場合は、私の手助けが
[tab]必要となりますので、ペルソナにこのような変化が
[tab]起こった場合は私の所へおいでください。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_5b8);
    ref_5bc = msgShow(msg_65);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]もちろん、
[tab]必ず変異させねばならないわけでは
[tab]ありません。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_5bc);
    ref_5c0 = msgShow(msg_66);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]変異後のペルソナはランク１に
[tab]戻ってしまいますから、変異させるかどうかは、
[tab]あなた方自身で判断してください。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_a, 1);
    sync();
    wait(ref_5c0);
    ref_5c4 = msgShow(msg_67);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]そうそう、[delay(15)]変異後のペルソナと同じペルソナが
[tab]既にいるような場合、変異させられないことも
[tab]ありますので、注意が必要ですぞ。
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    sync();
    wait(ref_5c4);
    dialogFree(ref_5a7);
    ref_5c9 = bustupFade(ref_5a5, rgb(0,0,0), 10);
    bustupWait(ref_5c9);
    bustupFree(ref_5a5);
    wait(ref_595);
    bitSet(VBIT_MUT_MES_OFF);
    shopInventory(3, shopInventory_0);
    shopInventory(4, shopInventory_0);
    shopInventory(2, shopInventory_0);
    shopInventory(8, shopInventory_0);
    b(label_5d3);
  label_5d3:
    ref_5d3 = bustupLoad(bustup_e0);
    bustupWait(ref_5d3);
    ref_5d5 = bustupAlloc(ref_5d3, right, rgb(0,0,0));
    bustupFade(ref_5d5, rgb(128,0,0), 30);
    choiceSetResult(6);
    ref_5d8 = dialogAlloc();
    ref_5d9 = msgShow(msg_68);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ようこそベルベットルームへ。
[tab]今日は、どんな御用ですかな？
[choice(8)]ペルソナを召喚する
ペルソナを降魔する
ペルソナの帰還
[if_all(VBIT_MUTATION_ON)]ペルソナの変異
話をする
[if_all(EBIT_SINARIOFF)]アディショナルシナリオ
やめる
ベルベットルームから出る
[end_choice][clear]
***************************************/
    sync();
    wait(ref_5d9);
    dialogFree(ref_5d8);
    ref_5dd = bustupFade(ref_5d5, rgb(0,0,0), 10);
    bustupWait(ref_5dd);
    bustupFree(ref_5d5);
    wait(ref_595);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_5e6);
    li(var_5, 0);
    b(label_5fb);
  label_5e6:
    bne(var_0, 1, label_5e9);
    li(var_5, 1);
    b(label_5fb);
  label_5e9:
    bne(var_0, 2, label_5ec);
    li(var_5, 2);
    b(label_5fb);
  label_5ec:
    bne(var_0, 3, label_5ef);
    li(var_5, 3);
    b(label_5fb);
  label_5ef:
    bne(var_0, 4, label_5f2);
    li(var_5, 4);
    b(label_5fb);
  label_5f2:
    bne(var_0, 5, label_5f5);
    li(var_5, 5);
    b(label_5fb);
  label_5f5:
    bne(var_0, 6, label_5f8);
    li(var_5, 6);
    b(label_5fb);
  label_5f8:
    bne(var_0, 7, label_5fb);
    li(var_5, 7);
    b(label_5fb);
  label_5fb:
    shopInventory(3, shopInventory_0);
    shopInventory(4, shopInventory_0);
    shopInventory(2, shopInventory_0);
    shopInventory(8, shopInventory_0);
    bitGet(var_0, VBIT_MUTATION_ON);
    bne(var_0, 0, label_604);
    ref_601 = shopOpen(6);
    wait(ref_601);
    b(label_608);
  label_604:
    bne(var_0, 1, label_608);
    ref_605 = shopOpen(7);
    wait(ref_605);
    b(label_608);
  label_608:
}

function HA_SHOP_RESTART_0()
{
    choiceSetResult(6);
    ref_60a = bustupLoad(bustup_e0);
    bustupWait(ref_60a);
    ref_60c = bustupAlloc(ref_60a, right, rgb(0,0,0));
    bustupFade(ref_60c, rgb(128,0,0), 30);
    ref_60e = dialogAlloc();
    ref_60f = msgShow(msg_69);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]他に御用はありますかな？
[choice(8)]ペルソナを召喚する
ペルソナを降魔する
ペルソナの帰還
[if_all(VBIT_MUTATION_ON)]ペルソナの変異
話をする
[if_all(EBIT_SINARIOFF)]アディショナルシナリオ
やめる
ベルベットルームから出る
[end_choice][clear]
***************************************/
    sync();
    wait(ref_60f);
    dialogFree(ref_60e);
    ref_613 = bustupFade(ref_60c, rgb(0,0,0), 10);
    bustupWait(ref_613);
    bustupFree(ref_60c);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_61b);
    li(var_5, 0);
    b(label_630);
  label_61b:
    bne(var_0, 1, label_61e);
    li(var_5, 1);
    b(label_630);
  label_61e:
    bne(var_0, 2, label_621);
    li(var_5, 2);
    b(label_630);
  label_621:
    bne(var_0, 3, label_624);
    li(var_5, 3);
    b(label_630);
  label_624:
    bne(var_0, 4, label_627);
    li(var_5, 4);
    b(label_630);
  label_627:
    bne(var_0, 5, label_62a);
    li(var_5, 5);
    b(label_630);
  label_62a:
    bne(var_0, 6, label_62d);
    li(var_5, 6);
    b(label_630);
  label_62d:
    bne(var_0, 7, label_630);
    li(var_5, 7);
    b(label_630);
  label_630:
}

function HA_SHOP_TALK_0()
{
    choiceSetResult(2);
    ref_632 = bustupLoad(bustup_e0);
    bustupWait(ref_632);
    ref_634 = bustupAlloc(ref_632, left, rgb(0,0,0));
    bustupFade(ref_634, rgb(128,0,0), 30);
    ref_636 = dialogAlloc();
    ref_637 = msgShow(msg_70);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]何か、聞きたいことがおありのようですな？
[choice(3)]世間話を聞く
説明を聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_637);
    dialogFree(ref_636);
    ref_63a = bustupFade(ref_634, rgb(0,0,0), 10);
    bustupWait(ref_63a);
    bustupFree(ref_634);
    choiceGetResult(var_0);
    bne(var_0, 0, label_640);
    b(label_647);
  label_640:
    bne(var_0, 1, label_643);
    b(label_8bc);
    b(label_647);
  label_643:
    bne(var_0, 2, label_647);
    li(var_5, 1000);
    b(label_941);
    b(label_647);
  label_647:
    bitGet(var_0, MBIT_EXTRARANK_E);
    bnz(var_0, label_660);
    bitGet(var_0, MBIT_EXTRARANK_D);
    bnz(var_0, label_660);
    bitGet(var_0, MBIT_EXTRARANK_C);
    bnz(var_0, label_660);
    bitGet(var_0, MBIT_EXTRARANK_B);
    bnz(var_0, label_660);
    bitGet(var_0, MBIT_EXTRARANK_A);
    bnz(var_0, label_660);
    bitGet(var_0, MBIT_EXTRARANK_S);
    bnz(var_0, label_660);
    ref_653 = bustupLoad(bustup_e0);
    bustupWait(ref_653);
    ref_655 = bustupAlloc(ref_653, right, rgb(0,0,0));
    bustupFade(ref_655, rgb(128,0,0), 30);
    ref_657 = dialogAlloc();
    ref_658 = msgShow(msg_71);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]フィレモン様は、あなた方に、人のみが持つ
[tab]無限の可能性を見出されたのかもしれません。
[tab]恐らくは、この趣向もその為のもの…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_658);
    dialogFree(ref_657);
    ref_65c = bustupFade(ref_655, rgb(0,0,0), 10);
    bustupWait(ref_65c);
    bustupFree(ref_655);
    b(label_941);
  label_660:
    ref_660 = bustupLoad(bustup_e0);
    bustupWait(ref_660);
    ref_662 = bustupAlloc(ref_660, right, rgb(0,0,0));
    bustupFade(ref_662, rgb(128,0,0), 30);
    ref_664 = dialogAlloc();
    ref_665 = msgShow(msg_72);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]では、どなたとお話なさいますかな？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_665);
    dialogFree(ref_664);
    ref_669 = bustupFade(ref_662, rgb(0,0,0), 10);
    bustupWait(ref_669);
    bustupFree(ref_662);
  label_66c:
    choiceSetResult(4);
    ref_66d = bustupLoad(bustup_1);
    bustupWait(ref_66d);
    ref_66f = bustupAlloc(ref_66d, center, rgb(0,0,0));
    bustupFade(ref_66f, rgb(128,0,0), 30);
    ref_671 = dialogChoiceAlloc();
    ref_672 = msgShow(msg_73);
/***************************************
[tab]どなたとお話なさいますかな？
[choice(5)]電話帳１
電話帳２
電話帳３
電話帳４
やめる
[end_choice][clear]
***************************************/
    wait(ref_672);
    dialogFree(ref_671);
    ref_675 = bustupFade(ref_66f, rgb(0,0,0), 10);
    bustupWait(ref_675);
    bustupFree(ref_66f);
    choiceGetResult(var_0);
    bne(var_0, 0, label_67c);
    b(label_712);
    b(label_688);
  label_67c:
    bne(var_0, 1, label_67f);
    b(label_6e2);
    b(label_688);
  label_67f:
    bne(var_0, 2, label_682);
    b(label_6b2);
    b(label_688);
  label_682:
    bne(var_0, 3, label_685);
    b(label_688);
    b(label_688);
  label_685:
    bne(var_0, 4, label_688);
    b(label_941);
    b(label_688);
  label_688:
    li(var_5, 0);
    choiceSetResult(6);
    ref_68a = bustupLoad(bustup_1);
    bustupWait(ref_68a);
    ref_68c = bustupAlloc(ref_68a, center, rgb(0,0,0));
    bustupFade(ref_68c, rgb(128,0,0), 30);
    ref_68e = dialogChoiceAlloc();
    ref_68f = msgShow(msg_74);
/***************************************
[tab][color(yellow)]電話帳４[color(white)]
[choice(7)][if_all(MBIT_EXTRARANK_S)]須藤
[if_all(!MBIT_EXTRARANK_S)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_S)]アポロ
[if_all(!MBIT_EXTRARANK_S)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_S)]裏・管理官
[if_all(!MBIT_EXTRARANK_S)][color(pink)]？？？？[color(white)]
もどる
[end_choice][clear]
***************************************/
    wait(ref_68f);
    dialogFree(ref_68e);
    ref_692 = bustupFade(ref_68c, rgb(0,0,0), 10);
    bustupWait(ref_692);
    bustupFree(ref_68c);
    choiceGetResult(var_0);
    bne(var_0, 0, label_699);
    li(var_5, 9);
    b(label_6b0);
  label_699:
    bne(var_0, 2, label_69c);
    li(var_5, 15);
    b(label_6b0);
  label_69c:
    bne(var_0, 4, label_69f);
    li(var_5, 6);
    b(label_6b0);
  label_69f:
    bne(var_0, 6, label_6a2);
    b(label_66c);
    b(label_6b0);
  label_6a2:
    ref_6a2 = bustupLoad(bustup_e0);
    bustupWait(ref_6a2);
    ref_6a4 = bustupAlloc(ref_6a2, right, rgb(0,0,0));
    bustupFade(ref_6a4, rgb(128,0,0), 30);
    ref_6a6 = dialogAlloc();
    ref_6a7 = msgShow(msg_75);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]はて…その方はどなたでしょう？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6a7);
    dialogFree(ref_6a6);
    ref_6ab = bustupFade(ref_6a4, rgb(0,0,0), 10);
    bustupWait(ref_6ab);
    bustupFree(ref_6a4);
    b(label_688);
    b(label_6b0);
  label_6b0:
    bitSet(LBIT_0004);
    b(label_742);
  label_6b2:
    li(var_5, 0);
    choiceSetResult(10);
    ref_6b4 = bustupLoad(bustup_1);
    bustupWait(ref_6b4);
    ref_6b6 = bustupAlloc(ref_6b4, center, rgb(0,0,0));
    bustupFade(ref_6b6, rgb(128,0,0), 30);
    ref_6b8 = dialogChoiceAlloc();
    ref_6b9 = msgShow(msg_76);
/***************************************
[tab][color(yellow)]電話帳３[color(white)]
[choice(11)][if_all(MBIT_EXTRARANK_B)]銀次
[if_all(!MBIT_EXTRARANK_B)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_B)]千鶴
[if_all(!MBIT_EXTRARANK_B)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_A)]ニャルラトホテプ
[if_all(!MBIT_EXTRARANK_A)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_A)]南条
[if_all(!MBIT_EXTRARANK_A)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_A)]フィレモン
[if_all(!MBIT_EXTRARANK_A)][color(pink)]？？？？[color(white)]
もどる
[end_choice][clear]
***************************************/
    wait(ref_6b9);
    dialogFree(ref_6b8);
    ref_6bc = bustupFade(ref_6b6, rgb(0,0,0), 10);
    bustupWait(ref_6bc);
    bustupFree(ref_6b6);
    choiceGetResult(var_0);
    bne(var_0, 0, label_6c3);
    li(var_5, 5);
    b(label_6e0);
  label_6c3:
    bne(var_0, 2, label_6c6);
    li(var_5, 7);
    b(label_6e0);
  label_6c6:
    bne(var_0, 4, label_6c9);
    li(var_5, 2);
    b(label_6e0);
  label_6c9:
    bne(var_0, 6, label_6cc);
    li(var_5, 17);
    b(label_6e0);
  label_6cc:
    bne(var_0, 8, label_6cf);
    li(var_5, 18);
    b(label_6e0);
  label_6cf:
    bne(var_0, 10, label_6d2);
    b(label_66c);
    b(label_6e0);
  label_6d2:
    ref_6d2 = bustupLoad(bustup_e0);
    bustupWait(ref_6d2);
    ref_6d4 = bustupAlloc(ref_6d2, right, rgb(0,0,0));
    bustupFade(ref_6d4, rgb(128,0,0), 30);
    ref_6d6 = dialogAlloc();
    ref_6d7 = msgShow(msg_77);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]はて…その方はどなたでしょう？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6d7);
    dialogFree(ref_6d6);
    ref_6db = bustupFade(ref_6d4, rgb(0,0,0), 10);
    bustupWait(ref_6db);
    bustupFree(ref_6d4);
    b(label_6b2);
    b(label_6e0);
  label_6e0:
    bitSet(LBIT_0003);
    b(label_742);
  label_6e2:
    li(var_5, 0);
    choiceSetResult(10);
    ref_6e4 = bustupLoad(bustup_1);
    bustupWait(ref_6e4);
    ref_6e6 = bustupAlloc(ref_6e4, center, rgb(0,0,0));
    bustupFade(ref_6e6, rgb(128,0,0), 30);
    ref_6e8 = dialogChoiceAlloc();
    ref_6e9 = msgShow(msg_78);
/***************************************
[tab][color(yellow)]電話帳２[color(white)]
[choice(11)][if_all(MBIT_EXTRARANK_D)]舞耶
[if_all(!MBIT_EXTRARANK_D)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_C)]淳
[if_all(!MBIT_EXTRARANK_C)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_C)]エリー
[if_all(!MBIT_EXTRARANK_C)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_C)][tatsuya]
[if_all(!MBIT_EXTRARANK_C)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_B)]神取
[if_all(!MBIT_EXTRARANK_B)][color(pink)]？？？？[color(white)]
もどる
[end_choice][clear]
***************************************/
    wait(ref_6e9);
    dialogFree(ref_6e8);
    ref_6ec = bustupFade(ref_6e6, rgb(0,0,0), 10);
    bustupWait(ref_6ec);
    bustupFree(ref_6e6);
    choiceGetResult(var_0);
    bne(var_0, 0, label_6f3);
    li(var_5, 10);
    b(label_710);
  label_6f3:
    bne(var_0, 2, label_6f6);
    li(var_5, 1);
    b(label_710);
  label_6f6:
    bne(var_0, 4, label_6f9);
    li(var_5, 16);
    b(label_710);
  label_6f9:
    bne(var_0, 6, label_6fc);
    li(var_5, 14);
    b(label_710);
  label_6fc:
    bne(var_0, 8, label_6ff);
    li(var_5, 3);
    b(label_710);
  label_6ff:
    bne(var_0, 10, label_702);
    b(label_66c);
    b(label_710);
  label_702:
    ref_702 = bustupLoad(bustup_e0);
    bustupWait(ref_702);
    ref_704 = bustupAlloc(ref_702, right, rgb(0,0,0));
    bustupFade(ref_704, rgb(128,0,0), 30);
    ref_706 = dialogAlloc();
    ref_707 = msgShow(msg_79);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]はて…その方はどなたでしょう？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_707);
    dialogFree(ref_706);
    ref_70b = bustupFade(ref_704, rgb(0,0,0), 10);
    bustupWait(ref_70b);
    bustupFree(ref_704);
    b(label_6e2);
    b(label_710);
  label_710:
    bitSet(LBIT_0002);
    b(label_742);
  label_712:
    li(var_5, 0);
    choiceSetResult(10);
    ref_714 = bustupLoad(bustup_1);
    bustupWait(ref_714);
    ref_716 = bustupAlloc(ref_714, center, rgb(0,0,0));
    bustupFade(ref_716, rgb(128,0,0), 30);
    ref_718 = dialogChoiceAlloc();
    ref_719 = msgShow(msg_80);
/***************************************
[tab][color(yellow)]電話帳１[color(white)]
[choice(11)][if_all(MBIT_EXTRARANK_E)]克哉
[if_all(!MBIT_EXTRARANK_E)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_E)]うらら
[if_all(!MBIT_EXTRARANK_E)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_E)]栄吉
[if_all(!MBIT_EXTRARANK_E)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_D)]ギンコ
[if_all(!MBIT_EXTRARANK_D)][color(pink)]？？？？[color(white)]
[if_all(MBIT_EXTRARANK_D)]パオフゥ
[if_all(!MBIT_EXTRARANK_D)][color(pink)]？？？？[color(white)]
もどる
[end_choice][clear]
***************************************/
    wait(ref_719);
    dialogFree(ref_718);
    ref_71c = bustupFade(ref_716, rgb(0,0,0), 10);
    bustupWait(ref_71c);
    bustupFree(ref_716);
    choiceGetResult(var_0);
    bne(var_0, 0, label_723);
    li(var_5, 12);
    b(label_740);
  label_723:
    bne(var_0, 2, label_726);
    li(var_5, 11);
    b(label_740);
  label_726:
    bne(var_0, 4, label_729);
    li(var_5, 4);
    b(label_740);
  label_729:
    bne(var_0, 6, label_72c);
    li(var_5, 8);
    b(label_740);
  label_72c:
    bne(var_0, 8, label_72f);
    li(var_5, 13);
    b(label_740);
  label_72f:
    bne(var_0, 10, label_732);
    b(label_66c);
    b(label_740);
  label_732:
    ref_732 = bustupLoad(bustup_e0);
    bustupWait(ref_732);
    ref_734 = bustupAlloc(ref_732, right, rgb(0,0,0));
    bustupFade(ref_734, rgb(128,0,0), 30);
    ref_736 = dialogAlloc();
    ref_737 = msgShow(msg_81);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]はて…その方はどなたでしょう？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_737);
    dialogFree(ref_736);
    ref_73b = bustupFade(ref_734, rgb(0,0,0), 10);
    bustupWait(ref_73b);
    bustupFree(ref_734);
    b(label_712);
    b(label_740);
  label_740:
    bitSet(LBIT_0001);
    b(label_742);
  label_742:
    bitGet(var_0, MBIT_SUN_BEL03);
    bne(var_0, 0, label_752);
    bitGet(var_0, MBIT_SUN_BEL02);
    bne(var_0, 0, label_74e);
    bitGet(var_0, MBIT_SUN_BEL01);
    bne(var_0, 0, label_74a);
    sndVolumeFadeTo(sound_3003, 0, 30);
    b(label_74d);
  label_74a:
    bne(var_0, 1, label_74d);
    sndVolumeFadeTo(sound_3000, 0, 30);
    b(label_74d);
  label_74d:
    b(label_751);
  label_74e:
    bne(var_0, 1, label_751);
    sndVolumeFadeTo(sound_3001, 0, 30);
    b(label_751);
  label_751:
    b(label_755);
  label_752:
    bne(var_0, 1, label_755);
    sndVolumeFadeTo(sound_3002, 0, 30);
    b(label_755);
  label_755:
    bne(var_5, 1, label_766);
    ref_756 = bustupLoad(bustup_10e);
    bustupWait(ref_756);
    ref_758 = bustupAlloc(ref_756, center, rgb(0,0,0));
    bustupFade(ref_758, rgb(128,0,0), 30);
    ref_75a = dialogAlloc();
    sndVoicePlay(sound_b4, 128);
    sndWaitStart();
    ref_75d = msgShow(msg_82);
/***************************************
[color(yellow)]淳[color(white)]
[tab]今は留守です。ごめんなさい。
[tab]よかったら、伝言をどうぞ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_75d);
    sndMusicFree();
    dialogFree(ref_75a);
    ref_762 = bustupFade(ref_758, rgb(0,0,0), 10);
    bustupWait(ref_762);
    bustupFree(ref_758);
    b(label_880);
  label_766:
    bne(var_5, 2, label_777);
    ref_767 = bustupLoad(bustup_6b);
    bustupWait(ref_767);
    ref_769 = bustupAlloc(ref_767, center, rgb(0,0,0));
    bustupFade(ref_769, rgb(128,0,0), 30);
    ref_76b = dialogAlloc();
    sndVoicePlay(sound_b7, 128);
    sndWaitStart();
    ref_76e = msgShow(msg_83);
/***************************************
[color(yellow)]ニャルラトホテプ[color(white)]
[tab]フハハハハハハッ！
[tab]言いたき事があるなら聞いてやろう！！
[tab]そのつたない口で語って見せろ！！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_76e);
    sndMusicFree();
    dialogFree(ref_76b);
    ref_773 = bustupFade(ref_769, rgb(0,0,0), 10);
    bustupWait(ref_773);
    bustupFree(ref_769);
    b(label_880);
  label_777:
    bne(var_5, 3, label_788);
    ref_778 = bustupLoad(bustup_51);
    bustupWait(ref_778);
    ref_77a = bustupAlloc(ref_778, center, rgb(0,0,0));
    bustupFade(ref_77a, rgb(128,0,0), 30);
    ref_77c = dialogAlloc();
    sndVoicePlay(sound_b2, 128);
    sndWaitStart();
    ref_77f = msgShow(msg_84);
/***************************************
[color(yellow)]神取[color(white)]
[tab]語るには飽いた…メッセージを入れたまえ…
[tab]私を、失望させないようにな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_77f);
    sndMusicFree();
    dialogFree(ref_77c);
    ref_784 = bustupFade(ref_77a, rgb(0,0,0), 10);
    bustupWait(ref_784);
    bustupFree(ref_77a);
    b(label_880);
  label_788:
    bne(var_5, 4, label_799);
    ref_789 = bustupLoad(bustup_119);
    bustupWait(ref_789);
    ref_78b = bustupAlloc(ref_789, center, rgb(0,0,0));
    bustupFade(ref_78b, rgb(128,0,0), 30);
    ref_78d = dialogAlloc();
    sndVoicePlay(sound_bd, 128);
    sndWaitStart();
    ref_790 = msgShow(msg_85);
/***************************************
[color(yellow)]栄吉[color(white)]
[tab]ホォォォォウ！
[tab]このボクにラブコォールなのか～い？
[tab]今は忙しくてねぇ～[tab]ソ～リィベイビィ～
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_790);
    sndMusicFree();
    dialogFree(ref_78d);
    ref_795 = bustupFade(ref_78b, rgb(0,0,0), 10);
    bustupWait(ref_795);
    bustupFree(ref_78b);
    b(label_880);
  label_799:
    bne(var_5, 5, label_7aa);
    ref_79a = bustupLoad(bustup_dd);
    bustupWait(ref_79a);
    ref_79c = bustupAlloc(ref_79a, center, rgb(0,0,0));
    bustupFade(ref_79c, rgb(128,0,0), 30);
    ref_79e = dialogAlloc();
    sndVoicePlay(sound_b0, 128);
    sndWaitStart();
    ref_7a1 = msgShow(msg_86);
/***************************************
[color(yellow)]銀次[color(white)]
[tab]連絡なら事務所を通してくれたまえ。
[tab]女性なら別だがね。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7a1);
    sndMusicFree();
    dialogFree(ref_79e);
    ref_7a6 = bustupFade(ref_79c, rgb(0,0,0), 10);
    bustupWait(ref_7a6);
    bustupFree(ref_79c);
    b(label_880);
  label_7aa:
    bne(var_5, 6, label_7bb);
    ref_7ab = bustupLoad(bustup_4e);
    bustupWait(ref_7ab);
    ref_7ad = bustupAlloc(ref_7ab, center, rgb(0,0,0));
    bustupFade(ref_7ad, rgb(128,0,0), 30);
    ref_7af = dialogAlloc();
    sndVoicePlay(sound_ad, 128);
    sndWaitStart();
    ref_7b2 = msgShow(msg_87);
/***************************************
[color(yellow)]裏・管理官[color(white)]
[tab]いよぉーどうもこんにちワンコソバ！
[tab]今は留守にしてるんで、用件のあるクサレ野郎は
[tab]メッセージを入れてくれ！[tab]よろしく頼んだぞ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7b2);
    sndMusicFree();
    dialogFree(ref_7af);
    ref_7b7 = bustupFade(ref_7ad, rgb(0,0,0), 10);
    bustupWait(ref_7b7);
    bustupFree(ref_7ad);
    b(label_880);
  label_7bb:
    bne(var_5, 7, label_7cc);
    ref_7bc = bustupLoad(bustup_54);
    bustupWait(ref_7bc);
    ref_7be = bustupAlloc(ref_7bc, center, rgb(0,0,0));
    bustupFade(ref_7be, rgb(128,0,0), 30);
    ref_7c0 = dialogAlloc();
    sndVoicePlay(sound_ba, 128);
    sndWaitStart();
    ref_7c3 = msgShow(msg_88);
/***************************************
[color(yellow)]千鶴[color(white)]
[tab]ひとふたみよ、いつむななや、ここのたり
[tab]語れ、ゆらゆらと語れ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7c3);
    sndMusicFree();
    dialogFree(ref_7c0);
    ref_7c8 = bustupFade(ref_7be, rgb(0,0,0), 10);
    bustupWait(ref_7c8);
    bustupFree(ref_7be);
    b(label_880);
  label_7cc:
    bne(var_5, 8, label_7dd);
    ref_7cd = bustupLoad(bustup_111);
    bustupWait(ref_7cd);
    ref_7cf = bustupAlloc(ref_7cd, center, rgb(0,0,0));
    bustupFade(ref_7cf, rgb(128,0,0), 30);
    ref_7d1 = dialogAlloc();
    sndVoicePlay(sound_cb, 128);
    sndWaitStart();
    ref_7d4 = msgShow(msg_89);
/***************************************
[color(yellow)]ギンコ[color(white)]
[tab]哎呀（アイヤー）、今電話に出れないの。
[tab]メッセージ入れといて。
[tab]Ｓｏｒｒｙ呀～
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7d4);
    sndMusicFree();
    dialogFree(ref_7d1);
    ref_7d9 = bustupFade(ref_7cf, rgb(0,0,0), 10);
    bustupWait(ref_7d9);
    bustupFree(ref_7cf);
    b(label_880);
  label_7dd:
    bne(var_5, 9, label_7ee);
    ref_7de = bustupLoad(bustup_4a);
    bustupWait(ref_7de);
    ref_7e0 = bustupAlloc(ref_7de, center, rgb(0,0,0));
    bustupFade(ref_7e0, rgb(128,0,0), 30);
    ref_7e2 = dialogAlloc();
    sndVoicePlay(sound_b1, 128);
    sndWaitStart();
    ref_7e5 = msgShow(msg_90);
/***************************************
[color(yellow)]須藤[tab]竜也[color(white)]
[tab]ヒャーハハハハァー！！
[tab]電話電話電話電話ァァァ！！
[tab]俺は電波専門だ！[tab]電話にゃ出られねぇぞぉ！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7e5);
    sndMusicFree();
    dialogFree(ref_7e2);
    ref_7ea = bustupFade(ref_7e0, rgb(0,0,0), 10);
    bustupWait(ref_7ea);
    bustupFree(ref_7e0);
    b(label_880);
  label_7ee:
    bne(var_5, 10, label_7ff);
    ref_7ef = bustupLoad(bustup_2);
    bustupWait(ref_7ef);
    ref_7f1 = bustupAlloc(ref_7ef, center, rgb(0,0,0));
    bustupFade(ref_7f1, rgb(128,0,0), 30);
    ref_7f3 = dialogAlloc();
    sndVoicePlay(sound_b5, 128);
    sndWaitStart();
    ref_7f6 = msgShow(msg_91);
/***************************************
[color(yellow)]舞耶[color(white)]
[tab]レッツ・ポジティブスピーキン！
[tab]メッセージは前向きにね♥
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_7f6);
    sndMusicFree();
    dialogFree(ref_7f3);
    ref_7fb = bustupFade(ref_7f1, rgb(0,0,0), 10);
    bustupWait(ref_7fb);
    bustupFree(ref_7f1);
    b(label_880);
  label_7ff:
    bne(var_5, 11, label_810);
    ref_800 = bustupLoad(bustup_18);
    bustupWait(ref_800);
    ref_802 = bustupAlloc(ref_800, center, rgb(0,0,0));
    bustupFade(ref_802, rgb(128,0,0), 30);
    ref_804 = dialogAlloc();
    sndVoicePlay(sound_bb, 128);
    sndWaitStart();
    ref_807 = msgShow(msg_92);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]チャ～オ♥[tab]アンタ男？[tab]ねぇねぇねぇ？
[tab]イケてる男だったら、メッセージ♥
[tab]入れといてぇ～ん♥
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_807);
    sndMusicFree();
    dialogFree(ref_804);
    ref_80c = bustupFade(ref_802, rgb(0,0,0), 10);
    bustupWait(ref_80c);
    bustupFree(ref_802);
    b(label_880);
  label_810:
    bne(var_5, 12, label_821);
    ref_811 = bustupLoad(bustup_23);
    bustupWait(ref_811);
    ref_813 = bustupAlloc(ref_811, center, rgb(0,0,0));
    bustupFade(ref_813, rgb(128,0,0), 30);
    ref_815 = dialogAlloc();
    sndVoicePlay(sound_b3, 128);
    sndWaitStart();
    ref_818 = msgShow(msg_93);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]只今留守にしております。メッセージをどうぞ。
[tab]なお、あまり短いと逆探できないので
[tab]長めにお願いします。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_818);
    sndMusicFree();
    dialogFree(ref_815);
    ref_81d = bustupFade(ref_813, rgb(0,0,0), 10);
    bustupWait(ref_81d);
    bustupFree(ref_813);
    b(label_880);
  label_821:
    bne(var_5, 13, label_832);
    ref_822 = bustupLoad(bustup_2d);
    bustupWait(ref_822);
    ref_824 = bustupAlloc(ref_822, center, rgb(0,0,0));
    bustupFade(ref_824, rgb(128,0,0), 30);
    ref_826 = dialogAlloc();
    sndVoicePlay(sound_b8, 128);
    sndWaitStart();
    ref_829 = msgShow(msg_94);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]悪いが今は留守だ。
[tab]気が向いたら聞いてやるから、
[tab]メッセージでも入れとくんだな…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_829);
    sndMusicFree();
    dialogFree(ref_826);
    ref_82e = bustupFade(ref_824, rgb(0,0,0), 10);
    bustupWait(ref_82e);
    bustupFree(ref_824);
    b(label_880);
  label_832:
    bne(var_5, 14, label_843);
    ref_833 = bustupLoad(bustup_b);
    bustupWait(ref_833);
    ref_835 = bustupAlloc(ref_833, center, rgb(0,0,0));
    bustupFade(ref_835, rgb(128,0,0), 30);
    ref_837 = dialogAlloc();
    sndVoicePlay(sound_b9, 128);
    sndWaitStart();
    ref_83a = msgShow(msg_95);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]今は出られない…
[tab]よかったらメッセージを入れてくれ…
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_83a);
    sndMusicFree();
    dialogFree(ref_837);
    ref_83f = bustupFade(ref_835, rgb(0,0,0), 10);
    bustupWait(ref_83f);
    bustupFree(ref_835);
    b(label_880);
  label_843:
    bne(var_5, 15, label_84d);
    ref_844 = dialogAlloc();
    sndVoicePlay(sound_bc, 128);
    sndWaitStart();
    ref_847 = msgShow(msg_96);
/***************************************
[color(yellow)]アポロ[color(white)]
[tab]我は汝、汝は我！
[tab]我は電子の海より出でし者！
[tab]現代社会の必需品、便利至極な留守番電話なり！
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_847);
    sndMusicFree();
    dialogFree(ref_844);
    b(label_880);
  label_84d:
    bne(var_5, 16, label_85e);
    ref_84e = bustupLoad(bustup_3e);
    bustupWait(ref_84e);
    ref_850 = bustupAlloc(ref_84e, center, rgb(0,0,0));
    bustupFade(ref_850, rgb(128,0,0), 30);
    ref_852 = dialogAlloc();
    sndVoicePlay(sound_ae, 128);
    sndWaitStart();
    ref_855 = msgShow(msg_97);
/***************************************
[color(yellow)]エリー[color(white)]
[tab]Ｈａｌｌｏ！[tab]申し訳ありませんけれど、
[tab]今電話にでられませんの。
[tab]Ｍｅｓｓａｇｅお願いしますわ♥
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_855);
    sndMusicFree();
    dialogFree(ref_852);
    ref_85a = bustupFade(ref_850, rgb(0,0,0), 10);
    bustupWait(ref_85a);
    bustupFree(ref_850);
    b(label_880);
  label_85e:
    bne(var_5, 17, label_86f);
    ref_85f = bustupLoad(bustup_36);
    bustupWait(ref_85f);
    ref_861 = bustupAlloc(ref_85f, center, rgb(0,0,0));
    bustupFade(ref_861, rgb(128,0,0), 30);
    ref_863 = dialogAlloc();
    sndVoicePlay(sound_b6, 128);
    sndWaitStart();
    ref_866 = msgShow(msg_98);
/***************************************
[color(yellow)]南条[color(white)]
[tab]何の用だ？[tab]「少年老い易く学成りがたし、
[tab]一寸の光陰軽んずべからず」だ。
[tab]伝言があるなら手短に入れておけ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_866);
    sndMusicFree();
    dialogFree(ref_863);
    ref_86b = bustupFade(ref_861, rgb(0,0,0), 10);
    bustupWait(ref_86b);
    bustupFree(ref_861);
    b(label_880);
  label_86f:
    bne(var_5, 18, label_880);
    ref_870 = bustupLoad(bustup_de);
    bustupWait(ref_870);
    ref_872 = bustupAlloc(ref_870, center, rgb(0,0,0));
    bustupFade(ref_872, rgb(128,0,0), 30);
    ref_874 = dialogAlloc();
    sndVoicePlay(sound_af, 128);
    sndWaitStart();
    ref_877 = msgShow(msg_99);
/***************************************
[color(yellow)]フィレモン[color(white)]
[tab]私は電話の狭間に住まう者…
[tab]君は自分の名を告げる事ができるかね？
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_877);
    sndMusicFree();
    dialogFree(ref_874);
    ref_87c = bustupFade(ref_872, rgb(0,0,0), 10);
    bustupWait(ref_87c);
    bustupFree(ref_872);
    b(label_880);
  label_880:
    bitGet(var_0, MBIT_SUN_BEL03);
    bne(var_0, 0, label_890);
    bitGet(var_0, MBIT_SUN_BEL02);
    bne(var_0, 0, label_88c);
    bitGet(var_0, MBIT_SUN_BEL01);
    bne(var_0, 0, label_888);
    sndMusicPlay(sound_3003, 127);
    b(label_88b);
  label_888:
    bne(var_0, 1, label_88b);
    sndMusicPlay(sound_3000, 127);
    b(label_88b);
  label_88b:
    b(label_88f);
  label_88c:
    bne(var_0, 1, label_88f);
    sndMusicPlay(sound_3001, 127);
    b(label_88f);
  label_88f:
    b(label_893);
  label_890:
    bne(var_0, 1, label_893);
    sndMusicPlay(sound_3002, 127);
    b(label_893);
  label_893:
    bitGet(var_0, LBIT_0001);
    bne(var_0, 0, label_8af);
    bitGet(var_0, LBIT_0002);
    bne(var_0, 0, label_8a7);
    bitGet(var_0, LBIT_0003);
    bne(var_0, 0, label_89f);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    b(label_688);
    b(label_8a6);
  label_89f:
    bne(var_0, 1, label_8a6);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    b(label_6b2);
    b(label_8a6);
  label_8a6:
    b(label_8ae);
  label_8a7:
    bne(var_0, 1, label_8ae);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    b(label_6e2);
    b(label_8ae);
  label_8ae:
    b(label_8b6);
  label_8af:
    bne(var_0, 1, label_8b6);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    b(label_712);
    b(label_8b6);
  label_8b6:
    b(label_941);
    ref_8b7 = bustupLoad(bustup_e0);
    bustupWait(ref_8b7);
    ref_8b9 = bustupAlloc(ref_8b7, left, rgb(0,0,0));
    bustupFade(ref_8b9, rgb(128,0,0), 30);
    ref_8bb = dialogAlloc();
  label_8bc:
    choiceSetResult(6);
    ref_8bd = msgShow(msg_100);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]何なりと御質問を。
[choice(7)]ペルソナについて
降魔と発動について
アルカナについて
ペルソナの成長について
ペルソナとの相性について
次のページへ
[if(EBIT_SINARIOFF)]非表示項目・戻る
[end_choice][clear]
***************************************/
    wait(ref_8bd);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8c3);
    b(label_910);
    b(label_8d6);
  label_8c3:
    bne(var_0, 1, label_8c6);
    b(label_913);
    b(label_8d6);
  label_8c6:
    bne(var_0, 2, label_8c9);
    b(label_916);
    b(label_8d6);
  label_8c9:
    bne(var_0, 3, label_8cc);
    b(label_919);
    b(label_8d6);
  label_8cc:
    bne(var_0, 4, label_8cf);
    b(label_91c);
    b(label_8d6);
  label_8cf:
    bne(var_0, 5, label_8d2);
    b(label_8d7);
    b(label_8d6);
  label_8d2:
    bne(var_0, 6, label_8d6);
    li(var_5, 1000);
    b(label_93d);
    b(label_8d6);
  label_8d6:
    wait(ref_8bd);
  label_8d7:
    choiceSetResult(7);
    ref_8d8 = msgShow(msg_101);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]何なりと御質問を。
[choice(8)]タロットカードについて
マテリアルカードについて
スキルカードについて
インセンスカードについて
ペルソナカードについて
次のページへ
前のページへ
[if(EBIT_SINARIOFF)]非表示項目・戻る
[end_choice][clear]
***************************************/
    wait(ref_8d8);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8de);
    b(label_91f);
    b(label_8f4);
  label_8de:
    bne(var_0, 1, label_8e1);
    b(label_922);
    b(label_8f4);
  label_8e1:
    bne(var_0, 2, label_8e4);
    b(label_925);
    b(label_8f4);
  label_8e4:
    bne(var_0, 3, label_8e7);
    b(label_928);
    b(label_8f4);
  label_8e7:
    bne(var_0, 4, label_8ea);
    b(label_92b);
    b(label_8f4);
  label_8ea:
    bne(var_0, 5, label_8ed);
    b(label_8f5);
    b(label_8f4);
  label_8ed:
    bne(var_0, 6, label_8f0);
    b(label_8bc);
    b(label_8f4);
  label_8f0:
    bne(var_0, 7, label_8f4);
    li(var_5, 1000);
    b(label_93d);
    b(label_8f4);
  label_8f4:
    wait(ref_8d8);
  label_8f5:
    choiceSetResult(6);
    ref_8f6 = msgShow(msg_102);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]何なりと御質問を。
[choice(7)]召喚の基本について
魔晶変化について
ミューテーションについて
コンタクトについて
悪魔の個性について
前のページへ
[if(EBIT_SINARIOFF)]非表示項目・戻る
[end_choice][clear]
***************************************/
    wait(ref_8f6);
    choiceGetResult(var_0);
    bne(var_0, 0, label_8fc);
    b(label_92e);
    b(label_90f);
  label_8fc:
    bne(var_0, 1, label_8ff);
    b(label_931);
    b(label_90f);
  label_8ff:
    bne(var_0, 2, label_902);
    b(label_934);
    b(label_90f);
  label_902:
    bne(var_0, 3, label_905);
    b(label_937);
    b(label_90f);
  label_905:
    bne(var_0, 4, label_908);
    b(label_93a);
    b(label_90f);
  label_908:
    bne(var_0, 5, label_90b);
    b(label_8d7);
    b(label_90f);
  label_90b:
    bne(var_0, 6, label_90f);
    li(var_5, 1000);
    b(label_93d);
    b(label_90f);
  label_90f:
    wait(ref_8f6);
  label_910:
    ref_910 = msgShow(msg_103);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]神の様に慈愛に満ちた自分…、悪魔の如き残酷な自分…
[tab]人は、様々な仮面を着けて生きております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]今の貴方の姿も無数の仮面の１つに過ぎません。
[tab]「ペルソナ」は、心の奥底に潜む
[tab]貴方の姿の１つになります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]そして、「ペルソナ」を形ある姿で召喚し
[tab]その力を行使する者の事を「ペルソナ使い」と
[tab]申します。
[wait][clear]
***************************************/
    wait(ref_910);
    b(label_8bc);
  label_913:
    ref_913 = msgShow(msg_104);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]召喚されたペルソナを「発動」…
[tab]すなわち、ペルソナを呼び出しその力を行使するには
[tab]「降魔」することが必要です。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]「降魔」とは、召喚したペルソナを貴方のような
[tab]ペルソナ使いの体に降ろすことです。
[tab]「ペルソナカード」を所持しているだけではダメですぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ペルソナを「降魔」すると、ペルソナ使い自身の
[tab]ステータスにも変化が生じます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ペルソナは貴方の隠れた一面…
[tab]それに相応しい状態に変化するというわけですな。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]「降魔」は１度に１体しか出来ません。
[tab]ですが、「ペルソナカード」があれば、
[tab]いつでも別のペルソナを降魔する事が出来ます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]その場合、それまで降魔していたペルソナは、
[tab]「ペルソナカード」の状態に戻ります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ペルソナは、その種類によって持っている能力が違い
[tab]メリットだけではなく、デメリットもありますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それぞれのペルソナの能力を良く理解し、
[tab]状況に応じて使い分けることが、戦闘で生き延び、
[tab]勝利を収める鍵ですな。
[wait][clear]
***************************************/
    wait(ref_913);
    b(label_8bc);
  label_916:
    ref_916 = msgShow(msg_105);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ペルソナも悪魔と同じように種族がございます。[wait][clear][color(yellow)]イゴール[color(white)]
[tab]種族は「魔術師」や「皇帝」、「戦車」など…
[tab]タロットのアルカナで表され、２６種類に
[tab]分類されております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]アルカナによっては、私の召喚では出会えないものも
[tab]ございまして…それらのアルカナに出会う為には、
[tab]ご自身の手で色々と試されるのが宜しいでしょう。
[wait][clear]
***************************************/
    wait(ref_916);
    b(label_8bc);
  label_919:
    ref_919 = msgShow(msg_106);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ペルソナが人の隠れた一面であるとはいえ、
[tab]意識していなかった、もう１人の自分に触れるのは、
[tab]驚きもあるでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]誰でも初めのうちは、ペルソナの力を十二分に
[tab]出し切ることは出来ません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それは新しく召喚したペルソナほど、
[tab]その傾向が顕著に現れます…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]そのため最初の内は、ペルソナが持つ本来の能力の
[tab]一部しか発揮することが出来ないでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]しかし、ペルソナを発動させればさせる程、
[tab]次第に使いこなせるようになります。
[tab]能力が増え、より強力な攻撃も可能になります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]もちろんそれは、ペルソナを使いこなせるようになった
[tab]結果なので、発動に必要なＳＰに変わりはありません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]多少ニュアンスは違いますが、この貴方自身の慣れを
[tab]「ペルソナの成長」と考えてもいいでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ペルソナの成長には８段階の節目があります。
[tab]その節目毎に、ペルソナに変化が現れるでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]また、ペルソナは貴方自身の成長にも、
[tab]わずかながら影響を与えます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]貴方の能力のどの部分に影響を与えるかは、
[tab]降魔しているペルソナの種類によって異なります。
[tab]その点も考慮すると良いでしょうな。
[wait][clear]
***************************************/
    wait(ref_919);
    b(label_8bc);
  label_91c:
    ref_91c = msgShow(msg_107);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ペルソナは貴方の半身…
[tab]全てのペルソナは、貴方と繋がっております…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]とはいえ、貴方に近い存在もあれば、
[tab]遠い存在もおりますでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]繋がりが希薄なペルソナの場合、貴方には扱えないかも
[tab]しれません。
[tab]そう、中には降魔すら出来ない場合もあります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]逆に近い存在である場合、楽に扱えることも
[tab]あるでしょう。
[tab]これらの影響は、特にＳＰの消費に現れます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]本来より少ないＳＰでスキルを発動出来ることもあれば
[tab]より多くのＳＰを消費する場合もあります。
[tab]それらの事柄は誰でも同じ条件とは限りませんぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]…色々試されて確認されると良いでしょう。
[wait][clear]
***************************************/
    wait(ref_91c);
    b(label_8bc);
  label_91f:
    ref_91f = msgShow(msg_108);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]私が新たにペルソナを召喚するのに必要な媒体として
[tab]「タロットカード」が必要でございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ペルソナは、タロットのアルカナ、
[tab]「魔術師」や「皇帝」などに種別されておりまして…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]アルカナ「太陽」に属するペルソナを召喚したければ、
[tab]同じアルカナのカードでなければなりません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]また、集めるタロットの枚数も、
[tab]そのペルソナのレベルに見合った分だけ
[tab]必要となりますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]そう、レベルが高いペルソナほど、
[tab]必要なタロットの枚数も増えるわけですな。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]タロットカードの多くは悪魔が所持してまして…
[tab]彼らが持つカードは、その悪魔の種族と同じアルカナの
[tab]タロットになっております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]つまり、召喚したいペルソナと同じ種族の悪魔から、
[tab]タロットを手に入れればよいわけですな。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]但し、同じ悪魔とだけ交渉していてもダメですぞ。
[tab]レベルの高い悪魔ほど、所持しているタロットの枚数も
[tab]多いのです。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]高レベルのペルソナを召喚したいのであれば、
[tab]同じく高レベルの悪魔と交渉することが必要です。
[tab]それが、効率よくタロットを集めるコツですな。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]また、一部のタロットは悪魔からは手に入れることは
[tab]出来ません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]「フリータロット」と呼ばれるカードを入手したら
[tab]そちらの「悪魔絵師」に相談されると良いでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]そうそう、たとえカードを所持されていても、
[tab]貴方達の「最高レベル＋５」を超えるレベルのペルソナは
[tab]召喚出来ませんぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それをお忘れなく…
[wait][clear]
***************************************/
    wait(ref_91f);
    b(label_8d7);
  label_922:
    ref_922 = msgShow(msg_109);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]私がペルソナを召喚する際に追加出来るカードに
[tab]「マテリアルカード」というものがございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]マテリアルカードは１度の召喚で１枚だけ使用出来まして
[tab]特定のマテリアルカードを追加することで
[tab]特殊なペルソナを召喚する事が可能となります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]また、マテリアルカードを所持していると、
[tab]がい当するペルソナが青色で召喚リストに表示されます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]「マテリアルカード」は、強力なペルソナを
[tab]作り出すためにも欠かすことのできない物なので
[tab]ございます…
[wait][clear]
***************************************/
    wait(ref_922);
    b(label_8d7);
  label_925:
    ref_925 = msgShow(msg_110);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]私がペルソナを召喚する際に追加出来るカードに
[tab]「スキルカード」というものがございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]スキルカードは１度の召喚で１枚だけ使用出来まして、
[tab]カードに封じられたスキルを新たに召喚する
[tab]ペルソナに覚えさせる事が出来ます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]そう…「アギカード」を新たなペルソナの
[tab]召喚時に加えれば、そのペルソナは「アギ」を
[tab]覚えるということです…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]普通の成長では覚えることがないスキルであっても
[tab]カードで習得させられますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ただし、スキルカードとペルソナの間には
[tab]相性が存在しておりまして、相性が悪いと
[tab]そのスキルカードを加えることは出来ません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]なお、スキルカードの多くは悪魔が所持しております。
[tab]悪魔と遭遇した時にコンタクトなどを行って
[tab]入手されるのが良いでしょうな…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]珍しいスキルカードは入手手段が異なるようです
[tab]…色々試されると良いでしょう。
[wait][clear]
***************************************/
    wait(ref_925);
    b(label_8d7);
  label_928:
    ref_928 = msgShow(msg_111);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]私がペルソナを召喚する際に追加出来るカードに
[tab]「インセンスカード」というものがございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]インセンスカードは１度の召喚で１枚だけ使用出来まして
[tab]カードに関連したペルソナの能力を伸ばす事が出来ます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]あくまでも、新たに召喚するペルソナにしか
[tab]使用出来ませんので、よく考えて追加されると
[tab]良いでしょうな…
[wait][clear]
***************************************/
    wait(ref_928);
    b(label_8d7);
  label_92b:
    ref_92b = msgShow(msg_112);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]召喚されたペルソナで降魔していないものは、
[tab]通常、カードの姿をとって待機しておりまして
[tab]そのカードを「ペルソナカード」と申します。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]貴方は、ペルソナカードを複数所持出来ますが、
[tab]所持できる枚数には限りがございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]所持するカードには、降魔中のペルソナも含まれますので
[tab]注意が必要ですぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ペルソナの力は、冒険に欠く事のできぬもの。
[tab]必要に応じて、ペルソナカードを入れ替えるのが
[tab]宜しいでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]また、こちらで新たに召喚したペルソナは、
[tab]私が大切に預かっております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]お預かりできる数には限りがございますが、
[tab]新しく召喚したペルソナだけでなく、
[tab]それまで貴方が所持していたペルソナも預りますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]お預かりできる最大数のカードをお預かりしている時は
[tab]新たにペルソナを召喚する事は出来ませんぞ。
[tab]お忘れ無きよう…
[wait][clear]
***************************************/
    wait(ref_92b);
    b(label_8d7);
  label_92e:
    ref_92e = msgShow(msg_113);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]私の役目は、新たなペルソナを召喚すること…
[tab]お持ちのタロットカードを媒体にして、
[tab]心の奥底に眠るペルソナを召喚する事でございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]タロットカードを多く用えば、レベルの高いペルソナが
[tab]召喚されるでしょう。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ですが、タロットカードさえ集めれば、
[tab]全てのペルソナを召喚出来る…というわけでは
[tab]ありません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]中には特別な条件が必要な場合もあります。
[tab]それらの一部は、無意識の奥底に眠っており…
[tab]召喚する為には、何かしらのきっかけが必要になります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]そのきっかけの１つは、「マテリアルカード」を合わせた
[tab]召喚になります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]その他にも、きっかけはペルソナの成長などに
[tab]潜んでおります…
[tab]ご自身の手で色々と試されるのが宜しいでしょう。
[wait][clear]
***************************************/
    wait(ref_92e);
    b(label_8f5);
  label_931:
    ref_931 = msgShow(msg_114);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]ランクが上がりきり、ランクが８となったペルソナは
[tab]それ以上に育つことはありません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]非常に強力なペルソナではありますが、
[tab]そのようなペルソナをこのベルベットルームで
[tab]無意識の海に帰還いたしますと…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それまで共に戦ったペルソナの力は解放され、
[tab]代わりに、戦いの証として、何がしかのアイテムを
[tab]残していってくれるのでございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それは、時に武器であり、防具であり、消耗品であり
[tab]非常に珍しい、ここでしか手に入らない物もございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]どのような不思議な物を手に入れる事が出来るかは
[tab]ご自分の目でお確かめ下さいませ…
[wait][clear]
***************************************/
    wait(ref_931);
    b(label_8f5);
  label_934:
    ref_934 = msgShow(msg_115);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]戦闘で合体スキルを多用いたしておりますと
[tab]稀にペルソナがミューテーション…
[tab]つまりは「変異」する事がございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]変異が発生する確率はペルソナとの相性が
[tab]深く関わっておりまして…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]相性が良いペルソナほど変異する確率は
[tab]高くなっております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]変異の内容はペルソナのランクで異なりまして、
[tab]ランクが低い時は、「ランクの２ランクアップ」や
[tab]「基礎能力強化」などですが…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]高ランクになりますと、「スキルの習得」や
[tab]ペルソナによっては「別ペルソナへの変身」が
[tab]可能となります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]なお、ペルソナによっては、私の召喚では呼び出せない
[tab]アルカナのペルソナに変身する場合もございます。
[tab]色々試されると良いでしょう。[wait][clear]
***************************************/
    wait(ref_934);
    b(label_8f5);
  label_937:
    ref_937 = msgShow(msg_116);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]悪魔は、貴方達と同じで「喜び」や「怒り」など
[tab]様々な感情を持っておりまして…
[tab]話しかけることでコンタクトを取る事が出来ます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]悪魔達は気持ちを「言葉」「音」「動作」
[tab]それから「光」で表現いたしまして、視覚で判断出来る
[tab]感情の光は次のようになっております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]まず初めに「喜び」は「緑の光」で表されます。
[tab]この感情が最大になりますと
[tab]悪魔と「契約」をする事が出来ますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]悪魔と「契約」を行いますと、
[tab]貴方に様々なメリットがございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それは、悪魔から「珍しいタロットカード」を頂いたり
[tab]「面白い話」を聞かせて頂けます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ですが、それらは契約中とはいえ、
[tab]ただでは頂く事は出来ません。
[tab]ほしい時は、再度コンタクトをお取り下さい。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]次に「怒り」は「赤い光」で表されます。
[tab]この感情が最大になりますと
[tab]すぐに悪魔との会話は打ち切られてしまいます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]こうなりますと悪魔はもう聞く耳を持ちません。
[tab]ヘタをすると、攻撃されてしまいます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それは「契約」を行っている悪魔でも同じでして、
[tab]良い事はありません…
[tab]怒らせない様に気をつけた方がいいですな。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]次に「恐怖」は「青い光」で表されます。
[tab]この感情が最大になりますと
[tab]悪魔は怯えて逃げ出してしまいます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]最後に「興味」は「黄色い光」で表されます。
[tab]この感情を最大に高める事はとても意味がありますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]私の召喚で必要な媒体であるタロットカードを
[tab]頂ける場合があるのです。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]強力なペルソナを召喚される場合、
[tab]数多くのタロットカードが必要となりますので
[tab]悪魔と頻繁にコンタクトを行い集めると良いでしょう…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]それから…「喜び」「怒り」「恐怖」の３つは
[tab]「興味」が同時に上がる事がございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]たとえば…「喜び」と「興味」が同時に最大になった場合
[tab]「契約」を行う事は出来ません。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]「怒り」と「恐怖」も「興味」と同時に最大になった時、
[tab]普段とは異なる結果になります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]これら４つの感情は、普通３段階で最大になります。
[tab]私からのアドバイスとしては、普段はなるべく１つの
[tab]感情を上げる事をお奨めいたします。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]基本的な事はこれくらいですな。
[tab]この他にも、貴方達に対して悪魔が質問してきたり
[tab]遭遇直後に話しかけてきたりする場合もございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]まぁそれらは、数多くコンタクトをすれば
[tab]わかってくるでしょうな…
[wait][clear]
***************************************/
    wait(ref_937);
    b(label_8f5);
  label_93a:
    ref_93a = msgShow(msg_117);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]それでは、悪魔の「個性」について説明しますかな…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]人間でもそうですが、悪魔にもいろいろな者が
[tab]おりまして…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]賢い者、短気な者、弱気な者…
[tab]それぞれ好き嫌いがございます。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]貴方達は、それらを見抜いて
[tab]悪魔とコンタクトを行うのです。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]悪魔の「個性」は全部で８種類に分類されます。
[tab]賢い[tab]愚か[tab]陽気[tab]陰気
[tab]強気[tab]弱気[tab]短気[tab]高慢…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]各悪魔が、この中のいずれか１個、又は複数
[tab]持っております。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]持っている「個性」の組み合わせによって、
[tab]コンタクトの時の反応が全然異なりますぞ。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]コンタクトを行った事が無い悪魔の「個性」は
[tab]知ることは出来ませんが、
[tab]一度でもコンタクトすれば判るようになります。
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]色々試されてご自分の目でお確かめ下さいませ…
[wait][clear]
***************************************/
    wait(ref_93a);
    b(label_8f5);
  label_93d:
    dialogFree(ref_8bb);
    ref_93e = bustupFade(ref_8b9, rgb(0,0,0), 10);
    bustupWait(ref_93e);
    bustupFree(ref_8b9);
  label_941:
}

function HA_SHOP_END_0()
{
    ref_942 = bustupLoad(bustup_e0);
    bustupWait(ref_942);
    ref_944 = bustupAlloc(ref_942, right, rgb(0,0,0));
    bustupFade(ref_944, rgb(128,0,0), 30);
    ref_946 = dialogAlloc();
    ref_947 = msgShow(msg_118);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]では、更なるタロットを手に入れるまで、
[tab]しばしのお別れですな。[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_10, 1);
    wait(ref_947);
    shopOverlayInit();
    dialogFree(ref_946);
    ref_94c = bustupFade(ref_944, rgb(0,0,0), 10);
    bustupWait(ref_94c);
    bustupFree(ref_944);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_956);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    unitAnimationPlay(shopkeeper, animation_11, 1);
    cameraControlDisable();
    b(label_959);
  label_956:
    bne(var_0, 1, label_959);
    call(EXITBOX);
    b(label_959);
  label_959:
}

function BERADONNA()
{
    controlDisable();
    unitFacePlayer(npc1);
    ref_95c = bustupLoad(bustup_e2);
    bustupWait(ref_95c);
    ref_95e = bustupAlloc(ref_95c, right, rgb(0,0,0));
    bustupFade(ref_95e, rgb(128,0,0), 30);
    ref_960 = dialogAlloc();
    ref_961 = msgShow(msg_119);
/***************************************
[color(yellow)]ベラドンナ[color(white)]
[tab]光の渦とは～𝅘𝅥𝅮
[tab]フィレモン様の残した軌跡～𝅘𝅥𝅮
[tab]ふれれば新たな道が開きます～𝅘𝅥𝅮
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_8, 1);
    wait(ref_961);
    dialogFree(ref_960);
    ref_965 = bustupFade(ref_95e, rgb(0,0,0), 10);
    bustupWait(ref_965);
    bustupFree(ref_95e);
    unitRestoreFacing(npc1);
    controlEnable();
    cameraControlDisable();
    unitAnimationPlay(npc1, animation_7, 1);
}

function NANASI()
{
    controlDisable();
    ref_96e = bustupLoad(bustup_e1);
    bustupWait(ref_96e);
    ref_970 = bustupAlloc(ref_96e, right, rgb(0,0,0));
    bustupFade(ref_970, rgb(128,0,0), 30);
    ref_972 = dialogAlloc();
    ref_973 = msgShow(msg_120);
/***************************************
[color(yellow)]ナナシ[color(white)]
[tab]この迷宮を攻略できた者は、まだ一人もいない。
[tab]お前は、最果てに待つフィレモン様の元へ
[tab]辿りつけるだろうか…
[wait][clear]
***************************************/
    wait(ref_973);
    dialogFree(ref_972);
    ref_976 = bustupFade(ref_970, rgb(0,0,0), 10);
    bustupWait(ref_976);
    bustupFree(ref_970);
    controlEnable();
    cameraControlDisable();
    unitAnimationPlay(npc2, animation_0, 1);
}

function ESI()
{
    controlDisable();
    ref_97e = shopOverlayInit();
    unitFacePlayer(unit_76);
    ref_980 = bustupLoad(bustup_e3);
    bustupWait(ref_980);
    ref_982 = bustupAlloc(ref_980, right, rgb(0,0,0));
    bustupFade(ref_982, rgb(128,0,0), 30);
    choiceSetResult(2);
    ref_985 = dialogAlloc();
    bitGet(var_0, MBIT_BEL_ESI);
    bne(var_0, 0, label_98e);
    ref_988 = msgShow(msg_121);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]僕は悪魔絵師。
[tab]人の内に住まう、神と悪魔を描く絵師。
[tab]どうぞよろしく。
[tab][sync][wait][clear]
***************************************/
    bitSet(MBIT_BEL_ESI);
    sync();
    wait(ref_988);
    wait(ref_97e);
    b(label_994);
  label_98e:
    bne(var_0, 1, label_994);
    ref_98f = msgShow(msg_122);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]タロットは心の雛形だ。心が人の運命を回す。
[tab]さて、何か描いて欲しいのかな？
[choice(4)]タロット作成依頼
話す
やめる
ベルベットルームから出る
[end_choice][clear]
***************************************/
    sync();
    wait(ref_98f);
    wait(ref_97e);
    b(label_994);
  label_994:
    dialogFree(ref_985);
    ref_995 = bustupFade(ref_982, rgb(0,0,0), 10);
    bustupWait(ref_995);
    bustupFree(ref_982);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_99d);
    li(var_5, 0);
    b(label_9a6);
  label_99d:
    bne(var_0, 1, label_9a0);
    li(var_5, 1);
    b(label_9a6);
  label_9a0:
    bne(var_0, 2, label_9a3);
    li(var_5, 2);
    b(label_9a6);
  label_9a3:
    bne(var_0, 3, label_9a6);
    li(var_5, 3);
    b(label_9a6);
  label_9a6:
    shopInventory(3, shopInventory_1);
    ref_9a7 = shopOpen(8);
    wait(ref_9a7);
}

function HA_SHOP_RESTART_1()
{
    choiceSetResult(2);
    ref_9ab = bustupLoad(bustup_e3);
    bustupWait(ref_9ab);
    ref_9ad = bustupAlloc(ref_9ab, left, rgb(0,0,0));
    bustupFade(ref_9ad, rgb(128,0,0), 30);
    ref_9af = dialogAlloc();
    ref_9b0 = msgShow(msg_123);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]他に、何かあるかな？
[choice(4)]タロット作成依頼
話す
やめる
ベルベットルームから出る
[end_choice][clear]
***************************************/
    wait(ref_9b0);
    dialogFree(ref_9af);
    ref_9b3 = bustupFade(ref_9ad, rgb(0,0,0), 10);
    bustupWait(ref_9b3);
    bustupFree(ref_9ad);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_9bb);
    li(var_5, 0);
    b(label_9c4);
  label_9bb:
    bne(var_0, 1, label_9be);
    li(var_5, 1);
    b(label_9c4);
  label_9be:
    bne(var_0, 2, label_9c1);
    li(var_5, 2);
    b(label_9c4);
  label_9c1:
    bne(var_0, 3, label_9c4);
    li(var_5, 3);
    b(label_9c4);
  label_9c4:
}

function HA_SHOP_TALK_1()
{
    ref_9c5 = bustupLoad(bustup_e3);
    bustupWait(ref_9c5);
    ref_9c7 = bustupAlloc(ref_9c5, right, rgb(0,0,0));
    bustupFade(ref_9c7, rgb(128,0,0), 30);
    ref_9c9 = dialogAlloc();
    choiceSetResult(2);
    ref_9cb = msgShow(msg_124);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]さて、何について語ろうか。
[choice(3)]世間話を聞く
カード作成について聞く
[if_all(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_9cb);
    dialogFree(ref_9c9);
    ref_9ce = bustupFade(ref_9c7, rgb(0,0,0), 10);
    bustupWait(ref_9ce);
    bustupFree(ref_9c7);
    choiceGetResult(var_0);
    bne(var_0, 0, label_9d4);
    b(label_9db);
  label_9d4:
    bne(var_0, 1, label_9d7);
    b(label_9e8);
    b(label_9db);
  label_9d7:
    bne(var_0, 2, label_9db);
    li(var_5, 1000);
    b(label_a26);
    b(label_9db);
  label_9db:
    ref_9db = bustupLoad(bustup_e3);
    bustupWait(ref_9db);
    ref_9dd = bustupAlloc(ref_9db, right, rgb(0,0,0));
    bustupFade(ref_9dd, rgb(128,0,0), 30);
    ref_9df = dialogAlloc();
    ref_9e0 = msgShow(msg_125);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]どうやらフィレモン様は、
[tab]君達が余程気に入ったらしい。
[tab]頑張れよ。
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_9e0);
    dialogFree(ref_9df);
    ref_9e4 = bustupFade(ref_9dd, rgb(0,0,0), 10);
    bustupWait(ref_9e4);
    bustupFree(ref_9dd);
    b(label_a26);
  label_9e8:
    choiceSetResult(3);
    ref_9e9 = bustupLoad(bustup_e3);
    bustupWait(ref_9e9);
    ref_9eb = bustupAlloc(ref_9e9, left, rgb(0,0,0));
    bustupFade(ref_9eb, rgb(128,0,0), 30);
    ref_9ed = dialogAlloc();
    ref_9ee = msgShow(msg_126);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]それで、何が聞きたいのかな？
[choice(3)]フリータロット
入手するには
効率の良い使い方
[end_choice][clear]
***************************************/
    wait(ref_9ee);
    dialogFree(ref_9ed);
    unitAnimationPlay(unit_76, animation_0, 1);
    unitWait(unit_76);
    ref_9f3 = bustupFade(ref_9eb, rgb(0,0,0), 10);
    bustupWait(ref_9f3);
    bustupFree(ref_9eb);
    choiceGetResult(var_3);
    bne(var_3, 0, label_a06);
    ref_9f8 = bustupLoad(bustup_e3);
    bustupWait(ref_9f8);
    ref_9fa = bustupAlloc(ref_9f8, right, rgb(0,0,0));
    bustupFade(ref_9fa, rgb(128,0,0), 30);
    ref_9fc = dialogAlloc();
    ref_9fd = msgShow(msg_127);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]フリータロットは、何も描かれていない特殊な
[tab]タロットカードなんだ。
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]どんなタロットカードにも変化させることが
[tab]できる不思議なカードさ。
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]僕なら、フリータロットに絵を描き、
[tab]いろんなタロットカードを作ることができる。
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]フリータロットを手に入れたら、
[tab]僕の所へ持ってくるといい。
[wait][clear]
***************************************/
    wait(ref_9fd);
    dialogFree(ref_9fc);
    unitAnimationPlay(unit_76, animation_9, 1);
    ref_a01 = bustupFade(ref_9fa, rgb(0,0,0), 10);
    bustupWait(ref_a01);
    bustupFree(ref_9fa);
    b(label_9e8);
    b(label_a26);
  label_a06:
    bne(var_3, 1, label_a15);
    ref_a07 = bustupLoad(bustup_e3);
    bustupWait(ref_a07);
    ref_a09 = bustupAlloc(ref_a07, right, rgb(0,0,0));
    bustupFade(ref_a09, rgb(128,0,0), 30);
    ref_a0b = dialogAlloc();
    ref_a0c = msgShow(msg_128);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]どんな悪魔も、必ずフリータロットを持っている。
[tab]でも、普通の交渉ではもらえないんだ。
[tab]フリータロットは、悪魔にとっても貴重なものだからね。
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]フリータロットをもらうには、
[tab]悪魔から特別な信頼を得なければならない。
[tab]ま、そんなところは人間も悪魔も同じなのさ。
[wait][clear]
***************************************/
    wait(ref_a0c);
    dialogFree(ref_a0b);
    unitAnimationPlay(unit_76, animation_9, 1);
    ref_a10 = bustupFade(ref_a09, rgb(0,0,0), 10);
    bustupWait(ref_a10);
    bustupFree(ref_a09);
    b(label_9e8);
    b(label_a26);
  label_a15:
    bne(var_3, 2, label_a24);
    ref_a16 = bustupLoad(bustup_e3);
    bustupWait(ref_a16);
    ref_a18 = bustupAlloc(ref_a16, right, rgb(0,0,0));
    bustupFade(ref_a18, rgb(128,0,0), 30);
    ref_a1a = dialogAlloc();
    ref_a1b = msgShow(msg_129);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]ペルソナを召喚するには、同じ種族の悪魔から
[tab]タロットカードを手に入れればいいのだけど…
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]困ったことに、悪魔として出現しない種族の
[tab]ペルソナもいるんだ。
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]こういう特別な種族のペルソナを召喚するには
[tab]どうしたらいいか？
[tab]こんな時に役に立つのがフリータロットさ。
[wait][clear][color(yellow)]悪魔絵師[color(white)]
[tab]枚数の補助、といった使い方もあるけど、
[tab]できるだけよく考えて使ってほしい。
[wait][clear]
***************************************/
    wait(ref_a1b);
    dialogFree(ref_a1a);
    unitAnimationPlay(unit_76, animation_9, 1);
    ref_a1f = bustupFade(ref_a18, rgb(0,0,0), 10);
    bustupWait(ref_a1f);
    bustupFree(ref_a18);
    b(label_9e8);
    b(label_a26);
  label_a24:
    bne(var_3, 3, label_a26);
    b(label_a26);
  label_a26:
}

function HA_SHOP_END_1()
{
    ref_a27 = bustupLoad(bustup_e3);
    bustupWait(ref_a27);
    ref_a29 = bustupAlloc(ref_a27, right, rgb(0,0,0));
    bustupFade(ref_a29, rgb(128,0,0), 30);
    ref_a2b = dialogAlloc();
    ref_a2c = msgShow(msg_130);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]僕はいつでもここにいる。
[tab]また気が向いたら立ち寄るといい。
[tab]ここでは、時間は意味を成さないからな。[sync][wait][clear]
***************************************/
    sync();
    wait(ref_a2c);
    shopOverlayInit();
    dialogFree(ref_a2b);
    ref_a31 = bustupFade(ref_a29, rgb(0,0,0), 10);
    bustupWait(ref_a31);
    bustupFree(ref_a29);
    shopInventory(3, shopInventory_0);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_a3c);
    unitRestoreFacing(unit_76);
    controlEnable();
    unitAnimationPlay(unit_76, animation_b, 1);
    cameraControlDisable();
    b(label_a3f);
  label_a3c:
    bne(var_0, 1, label_a3f);
    call(EXITBOX);
    b(label_a3f);
  label_a3f:
}

function DOORBOX()
{
    controlDisable();
    objAnimRotate(obj_0, 0, -70, 0, 30, 0);
    sndMusicPlay(sound_3006, 127);
    objAnimWait(obj_0);
    call(EXITBOX);
}

function EXITBOX()
{
    bitClear(MBIT_EXITBIT);
    unknownVar1(var_0);
    bne(var_0, 6144, label_a4d);
    dngRoomSet(293);
    dngRoomDraw();
    dngLoad2(ex_sevens1-0);
    b(label_a60);
  label_a4d:
    bne(var_0, 6161, label_a52);
    dngRoomSet(294);
    dngRoomDraw();
    dngLoad2(ex_sevens1-17);
    b(label_a60);
  label_a52:
    bne(var_0, 6152, label_a57);
    dngRoomSet(294);
    dngRoomDraw();
    dngLoad2(ex_sevens1-7);
    b(label_a60);
  label_a57:
    bne(var_0, 7425, label_a5c);
    dngRoomSet(294);
    dngRoomDraw();
    dngLoad2(ex_sevens1-7);
    b(label_a60);
  label_a5c:
    dngRoomSet(293);
    dngRoomDraw();
    dngLoad2(ex_sevens1-0);
    b(label_a60);
  label_a60:
}

function warp1()
{
    call(DOORBOX);
}

function HA_SHOP_EXPLAIN_0()
{
}

function HA_SHOP_EXPLAIN_1()
{
}

function HIDARI()
{
    call(NANASI);
    unitAnimationPlay(npc2, animation_3, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(npc2, animation_4, 1);
}

function MIGI()
{
    call(NANASI);
    unitAnimationPlay(npc2, animation_1, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(npc2, animation_2, 1);
}

function DECIDE_PAINT()
{
    ref_a71 = bustupLoad(bustup_e3);
    bustupWait(ref_a71);
    ref_a73 = bustupAlloc(ref_a71, left, rgb(0,0,0));
    bustupFade(ref_a73, rgb(128,0,0), 30);
    choiceSetResult(1);
    ref_a76 = dialogAlloc();
    ref_a77 = msgShow(msg_131);
/***************************************
[color(yellow)]悪魔絵師[color(white)]
[tab]これで良いかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_a77);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_a7e);
    li(var_7, 1);
    b(label_a81);
  label_a7e:
    bne(var_0, 1, label_a81);
    li(var_7, 0);
    b(label_a81);
  label_a81:
    dialogFree(ref_a76);
    ref_a82 = bustupFade(ref_a73, rgb(0,0,0), 10);
    bustupWait(ref_a82);
    bustupFree(ref_a73);
}

function DECIDE_PERSONA()
{
    ref_a86 = bustupLoad(bustup_e0);
    bustupWait(ref_a86);
    ref_a88 = bustupAlloc(ref_a86, left, rgb(0,0,0));
    bustupFade(ref_a88, rgb(128,0,0), 30);
    choiceSetResult(1);
    ref_a8b = dialogAlloc();
    ref_a8c = msgShow(msg_132);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]このペルソナでよろしいですかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_a8c);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_a94);
    li(var_7, 1);
    unitAnimationPlay(shopkeeper, animation_e, 1);
    b(label_a97);
  label_a94:
    bne(var_0, 1, label_a97);
    li(var_7, 0);
    b(label_a97);
  label_a97:
    dialogFree(ref_a8b);
    ref_a98 = bustupFade(ref_a88, rgb(0,0,0), 10);
    bustupWait(ref_a98);
    bustupFree(ref_a88);
}

function DECIDE_PERSONA_NG()
{
    ref_a9c = bustupLoad(bustup_e0);
    bustupWait(ref_a9c);
    ref_a9e = bustupAlloc(ref_a9c, left, rgb(0,0,0));
    bustupFade(ref_a9e, rgb(128,0,0), 30);
    ref_aa0 = dialogAlloc();
    ref_aa1 = msgShow(msg_133);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]降魔しているペルソナの変異はできませんぞ。
[wait][clear]
***************************************/
    wait(ref_aa1);
    dialogFree(ref_aa0);
    ref_aa4 = bustupFade(ref_a9e, rgb(0,0,0), 10);
    bustupWait(ref_aa4);
    bustupFree(ref_a9e);
    li(var_7, 0);
}

function DECIDE_PERSONA_FAIL()
{
    ref_aa9 = bustupLoad(bustup_e0);
    bustupWait(ref_aa9);
    ref_aab = bustupAlloc(ref_aa9, left, rgb(0,0,0));
    bustupFade(ref_aab, rgb(128,0,0), 30);
    choiceSetResult(1);
    ref_aae = dialogAlloc();
    ref_aaf = msgShow(msg_134);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]このペルソナでよろしいですかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_aaf);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_ab8);
    ref_ab4 = msgShow(msg_135);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]おや、既に同じペルソナがいるようですな。
[wait][clear]
***************************************/
    wait(ref_ab4);
    li(var_7, 0);
    b(label_abb);
  label_ab8:
    bne(var_0, 1, label_abb);
    li(var_7, 0);
    b(label_abb);
  label_abb:
    dialogFree(ref_aae);
    ref_abc = bustupFade(ref_aab, rgb(0,0,0), 10);
    bustupWait(ref_abc);
    bustupFree(ref_aab);
}

function DECIDE_DELETE()
{
    ref_ac0 = bustupLoad(bustup_e0);
    bustupWait(ref_ac0);
    ref_ac2 = bustupAlloc(ref_ac0, left, rgb(0,0,0));
    bustupFade(ref_ac2, rgb(128,0,0), 30);
    choiceSetResult(1);
    ref_ac5 = dialogAlloc();
    ref_ac6 = msgShow(msg_136);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]このペルソナを本当に消してよろしいですかな？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_ac6);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_acd);
    li(var_7, 1);
    b(label_ad0);
  label_acd:
    bne(var_0, 1, label_ad0);
    li(var_7, 0);
    b(label_ad0);
  label_ad0:
    dialogFree(ref_ac5);
    ref_ad1 = bustupFade(ref_ac2, rgb(0,0,0), 10);
    bustupWait(ref_ad1);
    bustupFree(ref_ac2);
}

function DEL_MES()
{
    ref_ad5 = bustupLoad(bustup_e0);
    bustupWait(ref_ad5);
    ref_ad7 = bustupAlloc(ref_ad5, left, rgb(0,0,0));
    bustupFade(ref_ad7, rgb(128,0,0), 30);
    ref_ad9 = dialogAlloc();
    ref_ada = msgShow(msg_137);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]呼び覚まされたる古き心のカタチ、
[tab][color(gray_inv)][var(msg_var_0)][color(white)]を解き放つ時が来ましたか…
[wait][clear][color(yellow)]イゴール[color(white)]
[tab]ならば共に戦いしその別なる心
[tab][color(green)][var(msg_var_1)][color(white)]に替えて、
[tab]あなたに返しましょうかな…
[wait][clear]
***************************************/
    wait(ref_ada);
    dialogFree(ref_ad9);
    ref_add = bustupFade(ref_ad7, rgb(0,0,0), 10);
    bustupWait(ref_add);
    bustupFree(ref_ad7);
}

function GET_MES()
{
    ref_ae1 = msgShow(msg_138);
/***************************************
[color(green)][tab]舞耶達は、[var(msg_var_1)][var(msg_var_2)]を
[tab]手に入れた。[wait][clear]
***************************************/
    wait(ref_ae1);
}

function SMN_NG_LV()
{
    ref_ae4 = bustupLoad(bustup_e0);
    bustupWait(ref_ae4);
    ref_ae6 = bustupAlloc(ref_ae4, right, rgb(0,0,0));
    bustupFade(ref_ae6, rgb(128,0,0), 30);
    ref_ae8 = dialogAlloc();
    ref_ae9 = msgShow(msg_139);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]このペルソナを呼び出すには、
[tab]まだ貴方方のレベルが足りないようですな…
[wait][clear]
***************************************/
    wait(ref_ae9);
    dialogFree(ref_ae8);
    ref_aec = bustupFade(ref_ae6, rgb(0,0,0), 10);
    bustupWait(ref_aec);
    bustupFree(ref_ae6);
}

function SMN_NG_PST()
{
    ref_af0 = bustupLoad(bustup_e0);
    bustupWait(ref_af0);
    ref_af2 = bustupAlloc(ref_af0, right, rgb(0,0,0));
    bustupFade(ref_af2, rgb(128,0,0), 30);
    ref_af4 = dialogAlloc();
    ref_af5 = msgShow(msg_140);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]同じペルソナを既にお持ちですぞ。
[wait][clear]
***************************************/
    wait(ref_af5);
    dialogFree(ref_af4);
    ref_af8 = bustupFade(ref_af2, rgb(0,0,0), 10);
    bustupWait(ref_af8);
    bustupFree(ref_af2);
}

function SMN_NG_VST()
{
    ref_afc = bustupLoad(bustup_e0);
    bustupWait(ref_afc);
    ref_afe = bustupAlloc(ref_afc, right, rgb(0,0,0));
    bustupFade(ref_afe, rgb(128,0,0), 30);
    ref_b00 = dialogAlloc();
    ref_b01 = msgShow(msg_141);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]同じペルソナをお預かりしておりますぞ。
[wait][clear]
***************************************/
    wait(ref_b01);
    dialogFree(ref_b00);
    ref_b04 = bustupFade(ref_afe, rgb(0,0,0), 10);
    bustupWait(ref_b04);
    bustupFree(ref_afe);
}

function SMN_NG_FULL()
{
    ref_b08 = bustupLoad(bustup_e0);
    bustupWait(ref_b08);
    ref_b0a = bustupAlloc(ref_b08, right, rgb(0,0,0));
    bustupFade(ref_b0a, rgb(128,0,0), 30);
    ref_b0c = dialogAlloc();
    ref_b0d = msgShow(msg_142);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]これ以上ペルソナを預かれませんな。
[wait][clear]
***************************************/
    wait(ref_b0d);
    dialogFree(ref_b0c);
    ref_b10 = bustupFade(ref_b0a, rgb(0,0,0), 10);
    bustupWait(ref_b10);
    bustupFree(ref_b0a);
}

function SMN_NG_TAROT()
{
    ref_b14 = bustupLoad(bustup_e0);
    bustupWait(ref_b14);
    ref_b16 = bustupAlloc(ref_b14, right, rgb(0,0,0));
    bustupFade(ref_b16, rgb(128,0,0), 30);
    ref_b18 = dialogAlloc();
    ref_b19 = msgShow(msg_143);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]このペルソナを呼び出す為に必要な
[tab]「タロットカード」が足りませんな。
[wait][clear]
***************************************/
    wait(ref_b19);
    dialogFree(ref_b18);
    ref_b1c = bustupFade(ref_b16, rgb(0,0,0), 10);
    bustupWait(ref_b1c);
    bustupFree(ref_b16);
}

function SMN_NG_MTRL()
{
    ref_b20 = bustupLoad(bustup_e0);
    bustupWait(ref_b20);
    ref_b22 = bustupAlloc(ref_b20, right, rgb(0,0,0));
    bustupFade(ref_b22, rgb(128,0,0), 30);
    ref_b24 = dialogAlloc();
    ref_b25 = msgShow(msg_144);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]このペルソナを呼び出す為に必要な
[tab]「マテリアルカード」が足りませんな。
[wait][clear]
***************************************/
    wait(ref_b25);
    dialogFree(ref_b24);
    ref_b28 = bustupFade(ref_b22, rgb(0,0,0), 10);
    bustupWait(ref_b28);
    bustupFree(ref_b22);
}

function SMN_NG_RIDATU()
{
    ref_b2c = bustupLoad(bustup_e0);
    bustupWait(ref_b2c);
    ref_b2e = bustupAlloc(ref_b2c, right, rgb(0,0,0));
    bustupFade(ref_b2e, rgb(128,0,0), 30);
    ref_b30 = dialogAlloc();
    ref_b31 = msgShow(msg_145);
/***************************************
[color(yellow)]イゴール[color(white)]
[tab]現在離脱しているお仲間が
[tab]すでに同じペルソナを降魔中ですな
[wait][clear]
***************************************/
    wait(ref_b31);
    dialogFree(ref_b30);
    ref_b34 = bustupFade(ref_b2e, rgb(0,0,0), 10);
    bustupWait(ref_b34);
    bustupFree(ref_b2e);
}
