
msg_0:
ワンロン占いの
リセット機能を追加しました。
[sync][wait][clear][end]

msg_1:
[tab]ワンロン占いの効果をリセットしますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_2:
相性占いテスト用デバックイベント
実行しますか？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_3:
１
２
３
４
５
６
７
８
９
１０
１１
１２
１３
１４
１５
１６
１７
１８
１９
２０
２１
２２
２３
２４
２５
２６
２７
２８
２９
３０
３１
３２
３３
３４
３５
３６
３７
３８
３９
４０
４１
４２
４３
４４
４５
４６
４７
４８
４９
５０
５１
５２
５３
５４
５５
５６
５７
５８
５９
６０
[end]

msg_4:
該当しない番号です。[wait][clear][end]

msg_5:
達哉
の
相性を良くしました。[wait][clear][end]

msg_6:
時間城伯爵
の
相性を良くしました。[wait][clear][end]

msg_7:
うらら
の
相性を良くしました。[wait][clear][end]

msg_8:
Ｍｒ．富
の
相性を良くしました。[wait][clear][end]

msg_9:
チカリン
の
相性を良くしました。[wait][clear][end]

msg_10:
Ｗａｎｇｌｏｎｇ千鶴
の
相性を良くしました。[wait][clear][end]

msg_11:
珠閒瑠ジニー
の
相性を良くしました。[wait][clear][end]

msg_12:
ハナジー
の
相性を良くしました。[wait][clear][end]

msg_13:
板さん
の
相性を良くしました。[wait][clear][end]

msg_14:
黎子さん
の
相性を良くしました。[wait][clear][end]

msg_15:
佐々木
の
相性を良くしました。[wait][clear][end]

msg_16:
やる気の無いボーイ
の
相性を良くしました。[wait][clear][end]

msg_17:
レオ
の
相性を良くしました。[wait][clear][end]

msg_18:
あんちゃん
の
相性を良くしました。[wait][clear][end]

msg_19:
杉本
の
相性を良くしました。[wait][clear][end]

msg_20:
パオフゥ
の
相性を良くしました。[wait][clear][end]

msg_21:
バー
の
相性を良くしました。[wait][clear][end]

msg_22:
麻希
の
相性を良くしました。[wait][clear][end]

msg_23:
轟所長
の
相性を良くしました。[wait][clear][end]

msg_24:
南条
の
相性を良くしました。[wait][clear][end]

msg_25:
ケン
の
相性を良くしました。[wait][clear][end]

msg_26:
トリッシュ
の
相性を良くしました。[wait][clear][end]

msg_27:
トニー
の
相性を良くしました。[wait][clear][end]

msg_28:
ブラウン
の
相性を良くしました。[wait][clear][end]

msg_29:
たまき
の
相性を良くしました。[wait][clear][end]

msg_30:
ムー大陸
の
相性を良くしました。[wait][clear][end]

msg_31:
リサ
の
相性を良くしました。[wait][clear][end]

msg_32:
ロサカンディータ
の
相性を良くしました。[wait][clear][end]

msg_33:
しらいし
の
相性を良くしました。[wait][clear][end]

msg_34:
エステティシャン
の
相性を良くしました。[wait][clear][end]

msg_35:
ナナシ
の
相性を良くしました。[wait][clear][end]

msg_36:
ゆきの
の
相性を良くしました。[wait][clear][end]

msg_37:
ジュエリーデザイナー
の
相性を良くしました。[wait][clear][end]

msg_38:
玲司
の
相性を良くしました。[wait][clear][end]

msg_39:
エリー
の
相性を良くしました。[wait][clear][end]

msg_40:
イゴール
の
相性を良くしました。[wait][clear][end]

msg_41:
口笛店主
の
相性を良くしました。[wait][clear][end]

msg_42:
管理官
の
相性を良くしました。[wait][clear][end]

msg_43:
神取
の
相性を良くしました。[wait][clear][end]

msg_44:
トロ
の
相性を良くしました。[wait][clear][end]

msg_45:
云豹
の
相性を良くしました。[wait][clear][end]

msg_46:
みーぽ
の
相性を良くしました。[wait][clear][end]

msg_47:
栄吉
の
相性を良くしました。[wait][clear][end]

msg_48:
トクさん
の
相性を良くしました。[wait][clear][end]

msg_49:
香さん
の
相性を良くしました。[wait][clear][end]

msg_50:
ギャルソン副島
の
相性を良くしました。[wait][clear][end]

msg_51:
バーテン
の
相性を良くしました。[wait][clear][end]

msg_52:
冴子先生
の
相性を良くしました。[wait][clear][end]

msg_53:
イシュキック
の
相性を良くしました。[wait][clear][end]

msg_54:
ジョリーロジャー
の
相性を良くしました。[wait][clear][end]

msg_55:
アルバイター
の
相性を良くしました。[wait][clear][end]

msg_56:
黒須
の
相性を良くしました。[wait][clear][end]

msg_57:
あさっち
の
相性を良くしました。[wait][clear][end]

msg_58:
克哉
の
相性を良くしました。[wait][clear][end]

msg_59:
ベラドンナ
の
相性を良くしました。[wait][clear][end]

msg_60:
おばちゃん長女・青葉区
の
相性を良くしました。[wait][clear][end]

msg_61:
おばちゃん次女・港南区
の
相性を良くしました。[wait][clear][end]

msg_62:
おばちゃん五女・平坂区
の
相性を良くしました。[wait][clear][end]

msg_63:
おばちゃん六女・蓮華台
の
相性を良くしました。[wait][clear][end]

msg_64:
おばちゃん七女・夢崎区
の
相性を良くしました。[wait][clear][end]

msg_65:
[tab]何を継続した状態にしますか？
[choice(6)]ギターが引ける
ゆきのと杏奈がいる
チンヤンと呼ぶ
メタル栄吉が話す
メタルギンコが話す
メタル黒須が話す
[end_choice][clear][end]

msg_66:
[color(yellow)]金田[color(white)]
追伸・選択肢「メタル黒須が話す」は、
継続ＢＩＴ全ての
リセット機能も兼ねています。
[wait][clear][end]
