function START()
{
    controlDisable();
    levelHide();
    ref_2 = evtbgLoad(evtbg_1b);
    wait(ref_2);
    evtbgInit(evtbg_handle_1b, evtbg_1b, 0, 0, rgb(0,0,0), true);
    evtbgFade(evtbg_handle_1b, rgb(128,128,128), 4, false);
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    shopOverlayInit();
    bitClear(LBIT_0025);
    ref_f = bustupLoad(bustup_13e);
    bustupWait(ref_f);
    ref_11 = bustupAlloc(ref_f, right, rgb(0,0,0));
    bustupFade(ref_11, rgb(128,0,0), 30);
    shopInventory(3, shopInventory_276);
    bne(var_4, 0, label_17);
    b(label_1d);
    b(label_1d);
  label_17:
    bne(var_4, 1, label_1a);
    b(label_a4);
    b(label_1d);
  label_1a:
    bne(var_4, 2, label_1d);
    b(label_ab);
    b(label_1d);
  label_1d:
    ref_1d = dialogAlloc();
    shopInventory(3, shopInventory_26c);
    bne(var_3, 0, label_27);
    ref_20 = msgShow(msg_0);
/***************************************
[color(yellow)]？？？？[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆
[tab]当施設のご利用は初めてでしょうか？[wait][clear][color(yellow)]？？？？[color(white)]
[tab]当シアターを案内させていただいています、
[tab]ミツギと申します！[tab]以後お見知りおきを。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ここでは、最新鋭の映像技術を使用した
[tab]映像作品をご覧になることが出来ます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]巷では、その映像のリアルから
[tab]まるで[color(pink)]本当に体験しているよう[color(white)]だ、
[tab]なんて噂になっています。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]また、こちらでは映画ご視聴終了毎に、
[tab]ポイントが加算されるシステムを
[tab]採用しております。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ランクは、「ストアフロント」から開始され、
[tab]徐々に「上映施設名」がゴージャスになっていきます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ランクが上がることで、ミツギの対応が変化していく
[tab]素敵なシステムとなっております。
[tab]是非上位ランクを目指してください！[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]待遇は良いから値引いてくれ、と？
[tab]何をおっしゃいますお客様。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]我々は最新鋭の映像技術により、世界で唯一
[tab]この場所でのみ味わえる体験を
[tab]提供させていただいております。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]安易な安売りはブランド力を貶めるだけでございます。
[tab]決して高い金額ではございません。
[tab]あきらめて、こちらの提示額をお支払いくださいませ。[wait][clear]
***************************************/
    wait(ref_20);
    choiceSetResult(3);
    ref_23 = msgShow(msg_1);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]それでは、当シアターでクライマックスな体験を
[tab]お楽しみください。
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_23);
    choiceGetResult(var_0);
    b(label_6d);
  label_27:
    bne(var_3, 1, label_2f);
    ref_28 = msgShow(msg_2);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]あら、先日いらっしゃった
[tab]舞耶さん…でよろしかったでしょうか。[wait][clear]
***************************************/
    wait(ref_28);
    choiceSetResult(3);
    ref_2b = msgShow(msg_3);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]本日はどうなさいますか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_2b);
    choiceGetResult(var_0);
    b(label_6d);
  label_2f:
    bne(var_3, 2, label_38);
    msgVar_Item(msgvar_0, item_4000);
    ref_31 = msgShow(msg_4);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]先日[color(pink)][var(msg_var_0)][color(white)]会員になられた
[tab]舞耶さんですね？[wait][clear]
***************************************/
    wait(ref_31);
    choiceSetResult(3);
    ref_34 = msgShow(msg_5);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]では、本日はどうなさいますか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_34);
    choiceGetResult(var_0);
    b(label_6d);
  label_38:
    bne(var_3, 3, label_41);
    msgVar_Item(msgvar_0, item_4000);
    ref_3a = msgShow(msg_6);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員の
[tab]舞耶さんですね、
[tab]いつもありがとうございます。[wait][clear]
***************************************/
    wait(ref_3a);
    choiceSetResult(3);
    ref_3d = msgShow(msg_7);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]さて、本日はいかがなさいますか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_3d);
    choiceGetResult(var_0);
    b(label_6d);
  label_41:
    bne(var_3, 4, label_4a);
    msgVar_Item(msgvar_0, item_4000);
    ref_43 = msgShow(msg_8);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！[tab]本日もありがとうございます。
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員の
[tab]舞耶様でございますね。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]手荷物等ございましたら、お預かりいたします。[wait][clear]
***************************************/
    wait(ref_43);
    choiceSetResult(3);
    ref_46 = msgShow(msg_9);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]本日はいかがなさいますか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_46);
    choiceGetResult(var_0);
    b(label_6d);
  label_4a:
    bne(var_3, 5, label_53);
    msgVar_Item(msgvar_0, item_4000);
    ref_4c = msgShow(msg_10);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ハ！[tab]いえ、失礼…[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員でおられます、
[tab]舞耶様ですね。[wait][clear]
***************************************/
    wait(ref_4c);
    choiceSetResult(3);
    ref_4f = msgShow(msg_11);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ようこそいらっしゃいました。
[tab]本日はどんな映画を御所望でしょうか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_4f);
    choiceGetResult(var_0);
    b(label_6d);
  label_53:
    bne(var_3, 6, label_5c);
    msgVar_Item(msgvar_0, item_4000);
    ref_55 = msgShow(msg_12);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員であらせられます、
[tab]舞耶様ですね。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]本日も当シアターをご利用いただき
[tab]ありがとうございます。[wait][clear]
***************************************/
    wait(ref_55);
    choiceSetResult(3);
    ref_58 = msgShow(msg_13);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]御所望の映画はございますでしょうか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_58);
    choiceGetResult(var_0);
    b(label_6d);
  label_5c:
    bne(var_3, 7, label_65);
    msgVar_Item(msgvar_0, item_4000);
    ref_5e = msgShow(msg_14);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]お待ちしておりました、
[tab][color(pink)][var(msg_var_0)][color(white)]会員の
[tab]舞耶様。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]本日御所望の映画はどのようなものでしょうか？[wait][clear]
***************************************/
    wait(ref_5e);
    choiceSetResult(3);
    ref_61 = msgShow(msg_15);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]当シアターが全力を持って
[tab]ご提供させていただきます。
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_61);
    choiceGetResult(var_0);
    b(label_6d);
  label_65:
    msgVar_Item(msgvar_0, item_4000);
    ref_66 = msgShow(msg_16);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アクション！
[tab]珠閒瑠クライマックスシアターへようこそ☆[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]お待ちしておりました、
[tab][color(pink)][var(msg_var_0)][color(white)]会員の
[tab]舞耶様。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]本日御所望の映画はどのようなものでしょうか？[wait][clear]
***************************************/
    wait(ref_66);
    choiceSetResult(3);
    ref_69 = msgShow(msg_17);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]当シアターが全力を持って
[tab]ご提供させていただきます。
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_69);
    choiceGetResult(var_0);
    b(label_6d);
  label_6d:
    bne(var_0, 0, label_87);
    choiceSetResult(4);
    ref_6f = msgShow(msg_18);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ご覧になる映画のジャンルは
[tab]どちらになさいますか？
[choice(5)][if(EBIT_SINARIOFF)]上映中映画
自主制作映画
単館系映画
輸入映画
[if(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_6f);
    choiceGetResult(var_0);
    bne(var_0, 0, label_76);
    bitSet(LBIT_0025);
    li(var_5, 600);
    b(label_86);
  label_76:
    bne(var_0, 1, label_7a);
    bitSet(LBIT_0025);
    li(var_5, 601);
    b(label_86);
  label_7a:
    bne(var_0, 2, label_7e);
    bitSet(LBIT_0025);
    li(var_5, 602);
    b(label_86);
  label_7e:
    bne(var_0, 3, label_82);
    bitSet(LBIT_0025);
    li(var_5, 603);
    b(label_86);
  label_82:
    bne(var_0, 4, label_86);
    bitClear(LBIT_0025);
    li(var_5, 1000);
    b(label_86);
  label_86:
    b(label_a2);
  label_87:
    bne(var_0, 1, label_8c);
    ref_88 = msgShow(msg_19);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]資料にフローが存在しないので、
[tab]この項目は無くなるカモです。
[tab][color(pink)]他に何かありますか？[color(white)]にジャンプします。[wait][clear]
***************************************/
    wait(ref_88);
    li(var_5, 1000);
    b(label_a2);
  label_8c:
    bne(var_0, 2, label_9f);
    choiceSetResult(3);
    ref_8e = msgShow(msg_20);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]何についてお話いたしましょうか？
[choice(4)]世間話をする
映画館の説明を聞く
会員ランクの説明を聞く
[if(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_8e);
    choiceGetResult(var_0);
    bne(var_0, 0, label_94);
    li(var_5, 2);
    b(label_9e);
  label_94:
    bne(var_0, 1, label_97);
    li(var_5, 2000);
    b(label_9e);
  label_97:
    bne(var_0, 2, label_9b);
    bitSet(LBIT_0010);
    li(var_5, 2000);
    b(label_9e);
  label_9b:
    bne(var_0, 3, label_9e);
    li(var_5, 1000);
    b(label_9e);
  label_9e:
    b(label_a2);
  label_9f:
    bne(var_0, 3, label_a2);
    li(var_5, 3);
    b(label_a2);
  label_a2:
    dialogFree(ref_1d);
    b(label_b2);
  label_a4:
    ref_a4 = dialogAlloc();
    ref_a5 = msgShow(msg_21);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]はい、カットです！[tab]映画はいかがでしたか？
[tab]それではポイントを加算させていただきます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]またのお越しをお待ちしております。[wait][clear]
***************************************/
    wait(ref_a5);
    dialogFree(ref_a4);
    shopInventory(3, shopInventory_295);
    li(var_5, 1000);
    b(label_b2);
  label_ab:
    ref_ab = dialogAlloc();
    ref_ac = msgShow(msg_22);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]…カット！[tab]この映画はイマイチでしたかね…
[tab]またのお越しをお待ちしております。[wait][clear]
***************************************/
    wait(ref_ac);
    dialogFree(ref_ab);
    shopInventory(3, shopInventory_294);
    li(var_5, 1000);
    b(label_b2);
  label_b2:
    ref_b2 = bustupFade(ref_11, rgb(0,0,0), 10);
    bustupWait(ref_b2);
    bustupFree(ref_11);
    shopInventory(3, shopInventory_0);
    ref_b6 = shopOpen(25);
    wait(ref_b6);
}

function HA_SHOP_RESTART_0()
{
    shopInventory(3, shopInventory_0);
    ref_ba = bustupLoad(bustup_13e);
    bustupWait(ref_ba);
    ref_bc = bustupAlloc(ref_ba, right, rgb(0,0,0));
    bustupFade(ref_bc, rgb(128,0,0), 30);
    choiceSetResult(3);
    ref_bf = dialogAlloc();
    bitGet(var_0, LBIT_0025);
    bne(var_0, 0, label_c6);
    ref_c2 = msgShow(msg_23);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]他に御用件はございますか？
[choice(4)]作品を選ぶ
[if(EBIT_SINARIOFF)]クライマックスシアター
話を聞く
シアターの外に出る
[end_choice][clear]
***************************************/
    wait(ref_c2);
    choiceGetResult(var_0);
    b(label_c9);
  label_c6:
    bne(var_0, 1, label_c9);
    li(var_0, 0);
    b(label_c9);
  label_c9:
    bne(var_0, 0, label_e3);
    choiceSetResult(4);
    ref_cb = msgShow(msg_24);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ご覧になる映画のジャンルは
[tab]どちらになさいますか？
[choice(5)][if(EBIT_SINARIOFF)]上映中映画
自主制作映画
単館系映画
輸入映画
[if(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_cb);
    choiceGetResult(var_0);
    bne(var_0, 0, label_d2);
    bitSet(LBIT_0025);
    li(var_5, 600);
    b(label_e2);
  label_d2:
    bne(var_0, 1, label_d6);
    bitSet(LBIT_0025);
    li(var_5, 601);
    b(label_e2);
  label_d6:
    bne(var_0, 2, label_da);
    bitSet(LBIT_0025);
    li(var_5, 602);
    b(label_e2);
  label_da:
    bne(var_0, 3, label_de);
    bitSet(LBIT_0025);
    li(var_5, 603);
    b(label_e2);
  label_de:
    bne(var_0, 4, label_e2);
    bitClear(LBIT_0025);
    li(var_5, 1000);
    b(label_e2);
  label_e2:
    b(label_fe);
  label_e3:
    bne(var_0, 1, label_e8);
    ref_e4 = msgShow(msg_25);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]資料にフローが存在しないので、
[tab]この項目は無くなるカモです。
[color(green_inv)]＆５他に何かありますか？[color(green_inv)]＆１にジャンプします。[wait][clear]
***************************************/
    wait(ref_e4);
    li(var_5, 1000);
    b(label_fe);
  label_e8:
    bne(var_0, 2, label_fb);
    choiceSetResult(3);
    ref_ea = msgShow(msg_26);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]何についてお話いたしましょうか？
[choice(4)]世間話をする
映画館の説明を聞く
会員ランクの説明を聞く
[if(EBIT_SINARIOFF)]非表示項目
[end_choice][clear]
***************************************/
    wait(ref_ea);
    choiceGetResult(var_0);
    bne(var_0, 0, label_f0);
    li(var_5, 2);
    b(label_fa);
  label_f0:
    bne(var_0, 1, label_f3);
    li(var_5, 2000);
    b(label_fa);
  label_f3:
    bne(var_0, 2, label_f7);
    bitSet(LBIT_0010);
    li(var_5, 2000);
    b(label_fa);
  label_f7:
    bne(var_0, 3, label_fa);
    li(var_5, 1000);
    b(label_fa);
  label_fa:
    b(label_fe);
  label_fb:
    bne(var_0, 3, label_fe);
    li(var_5, 3);
    b(label_fe);
  label_fe:
    dialogFree(ref_bf);
    ref_ff = bustupFade(ref_bc, rgb(0,0,0), 10);
    bustupWait(ref_ff);
    bustupFree(ref_bc);
}

function HA_SHOP_TALK_0()
{
    shopInventory(3, shopInventory_26c);
    ref_104 = dialogAlloc();
    bne(var_3, 0, label_109);
    ref_106 = msgShow(msg_27);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]映画を最後までご覧になりますと、
[tab]会員ポイントが加算されます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]是非一度、ご覧になってください。[wait][clear]
***************************************/
    wait(ref_106);
    b(label_12e);
  label_109:
    bne(var_3, 1, label_10d);
    ref_10a = msgShow(msg_28);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]映画を最後までご覧になりますと、
[tab]会員ポイントが加算されます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]是非一度、ご覧になってください。[wait][clear]
***************************************/
    wait(ref_10a);
    b(label_12e);
  label_10d:
    bne(var_3, 2, label_112);
    msgVar_Item(msgvar_0, item_4000);
    ref_10f = msgShow(msg_29);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]あまり広くない部屋の中央に置かれた映写機。
[tab]その周りには多くの折りたたみ椅子が並ぶ。
[tab]窓を暗幕で覆われたその部屋に入ってきたのは…[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員になられた
[tab]舞耶さんですね？[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]いつもありがとうございます。
[tab]ミツギは物覚えが良いのです。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]会員名はポイント加算でよりゴージャスに
[tab]なっていきます。[tab]是非当シアターをご贔屓に。[wait][clear]
***************************************/
    wait(ref_10f);
    b(label_12e);
  label_112:
    bne(var_3, 3, label_117);
    msgVar_Item(msgvar_0, item_4000);
    ref_114 = msgShow(msg_30);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]シーン××２。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]暗い劇場内、サイレント映画に合わせピアノを奏でる
[tab]女性。[tab]やがて映画が終わり、立ち上がる彼女の
[tab]そばへ行き演奏を賞賛するあなたは…
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員の
[tab]舞耶さんですね。
[tab]本日もありがとうございます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]会員ランクが上がったのですね、
[tab]おめでとうございます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]…その長い前フリは何、ですか？
[tab]はて、何のことやらミツギにはさっぱり。[wait][clear]
***************************************/
    wait(ref_114);
    b(label_12e);
  label_117:
    bne(var_3, 4, label_11c);
    msgVar_Item(msgvar_0, item_4000);
    ref_119 = msgShow(msg_31);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]シーン××３。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]真夏の暑いとある夜、高い塀に囲まれただけの広場。
[tab]汗を吹き出しながら、映写機の準備をする彼女が
[tab]ふと顔を上げると、タオルを持った女性が目の前に…[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)][var(msg_var_0)][color(white)]会員になられた、
[tab]舞耶さんではありませんか。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]本日も来館ありがとうございます。
[tab]すっかり顔なじみとなりましたね、嬉しい限りです。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]接客以外で話しかけてくださるのは、
[tab]舞耶さんくらいなので、印象深いですよ。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]これからもよろしくお願いいたします。
[tab]はて、タオル？[tab]何のことでしょうか？[wait][clear]
***************************************/
    wait(ref_119);
    b(label_12e);
  label_11c:
    bne(var_3, 5, label_121);
    msgVar_Item(msgvar_0, item_4000);
    ref_11e = msgShow(msg_32);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]シーン××４。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]大きくはないが、意匠を凝らしたデザインの映画館。
[tab]館内のスクリーンには前衛的な映像が流れている。
[tab]受付嬢は、近づいてくる客とおぼしき女性に向かって…[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]こほん、ようこそいらっしゃいました。
[tab][color(pink)][var(msg_var_0)][color(white)]会員になられたのですね。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]そろそろ来る頃かと思っていました。
[tab]ああいえ、その、待っていたわけではないのです。
[tab]何となく、です。[tab]何となく。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ミツギはそういう、カンが冴えているのです。[wait][clear]
***************************************/
    wait(ref_11e);
    b(label_12e);
  label_121:
    bne(var_3, 6, label_126);
    msgVar_Item(msgvar_0, item_4000);
    ref_123 = msgShow(msg_33);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]シーン××５。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]宮殿の如き豪華絢爛な建物。[tab]入口にはドアマンが。
[tab]扉を抜け中に入り、案内係に連れられて自分の席へ。
[tab]座ろうといた所で、手にしたパンフレットを落とすが…[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]親切にも、隣の席の女性が拾ってくれた。[tab]
[tab]彼女の差し出すパンフレットを受け取り、お礼を
[tab]言おうとした所で、オーケストラによる序曲が始まり…[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ようこそいらっしゃいませ、
[tab]舞耶さん。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ついに[color(pink)][var(msg_var_0)][color(white)]会員になれましたね。
[tab]流石です、おめでとうございます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ミツギ以外の店員も、あなたの噂で
[tab]もちきりでしたよ。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]まあ、ミツギは最初から
[tab]こうなることはわかっていましたよ？[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]皆人を見る目がナイのですから…[tab]ふふっ！[wait][clear]
***************************************/
    wait(ref_123);
    b(label_12e);
  label_126:
    bne(var_3, 7, label_12b);
    msgVar_Item(msgvar_0, item_4000);
    ref_128 = msgShow(msg_34);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]シーン××６。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]繁華街の一角にあるビルに入る女性。混雑した
[tab]エレベーターに乗り４階で降りると、そこは
[tab]いくつもの映画を上映する大きな映画館だった。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]彼女は人であふれるロビーを眺め、やがて今日の相手を
[tab]見つけた。目当ての映画の受付前で佇むその人に
[tab]駆け寄り、彼女はカバンから出したチケットを差し出す…[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]舞耶さん、
[tab]当シアター史上初[color(pink)][var(msg_var_0)][color(white)]会員、
[tab]おめでとうございます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]ミツギの前にフレームインしてから、
[tab]あっという間でしたね。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]今ではシアター関係者の目線を
[tab]フォローパンさせ続ける存在となってしまいました。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]まあでも、いつもあなたはミツギに
[tab]話しかけてくれますので、
[tab]今ではミツギもちょっとした有名人ですよ？[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]これからも当シアターを是非ご贔屓に。
[tab]ミツギはいつもあなたをフォローし続けておりますゆえ。[wait][clear]
***************************************/
    wait(ref_128);
    b(label_12e);
  label_12b:
    ref_12b = msgShow(msg_35);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]シーン……[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]このメッセージは表示されないハズなのですが…[wait][clear]
***************************************/
    wait(ref_12b);
    b(label_12e);
  label_12e:
    dialogFree(ref_104);
}

function HA_SHOP_EXPLAIN_0()
{
    ref_130 = dialogAlloc();
    bitGet(var_0, LBIT_0010);
    bne(var_0, 0, label_136);
    ref_133 = msgShow(msg_36);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]当[color(pink)]シアター[color(white)]の説明ですね、畏まりました。
[tab]当シアターでは、[color(pink)]作品を選ぶ[color(white)]ことで、
[tab]映画を鑑賞することが出来ます。
[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)]自主制作映画[color(white)]では、あなたが作成した映画を
[tab]上映いたします。
[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)]単館系映画[color(white)]では、あなたがご友人などから受け取った
[tab]映画を確認、鑑賞することが出来ます。
[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab][color(pink)]輸入映画[color(white)]では、
[tab]それ以外の、[color(pink)]輸入[color(white)]いたしました
[tab]映画をご確認することが出来ます。
[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]映画の上映中、途中での退席は可能ですが、
[tab]途中退席された場合は、来店ポイントは
[tab]加算されませんので、ご注意くださいませ。
[wait][clear]
***************************************/
    wait(ref_133);
    b(label_13a);
  label_136:
    bne(var_0, 1, label_13a);
    ref_137 = msgShow(msg_37);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]当シアターの会員制度についてですか、畏まりました。
[tab]ではミツギが答えさせていただきます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]下のランクから、ストアフロント会員、
[tab]ニッケルオデオン会員、エアドーム会員。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]アートハウス会員、ピクチュアパレス会員、
[tab]最上位として、シネプレックス会員
[tab]が用意されております。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]会員ランクをあげるには、
[tab]当シアターの作品を最後まで鑑賞していただく
[tab]必要がございます。[wait][clear][color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]是非とも、上位を目指してくださいませ。
[tab]何かが貰える、というわけではありませんが…[wait][clear]
***************************************/
    wait(ref_137);
    b(label_13a);
  label_13a:
    dialogFree(ref_130);
    bitClear(LBIT_0010);
}

function HA_SHOP_END_0()
{
    ref_13d = dialogAlloc();
    ref_13e = msgShow(msg_38);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]では、またのお越しを
[tab]お待ちしております。
[tab]フェードアウト！[wait][clear]
***************************************/
    wait(ref_13e);
    shopInventory(3, shopInventory_262);
    shopOverlayInit();
    dialogFree(ref_13d);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    evtbgFree(evtbg_handle_1b);
    levelShow();
    enableSaving(true);
}

function HA_SHOP_END_1()
{
    shopInventory(3, shopInventory_262);
    ref_14e = dialogAlloc();
    shopOverlayInit();
    dialogFree(ref_14e);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    evtbgFree(evtbg_handle_1b);
    levelShow();
}

function warp1()
{
    controlDisable();
    mapLoad(rengedai, 0, 0);
}

function DECIDE_QUE()
{
    ref_15d = bustupLoad(bustup_13e);
    bustupWait(ref_15d);
    ref_15f = bustupAlloc(ref_15d, right, rgb(0,0,0));
    bustupFade(ref_15f, rgb(128,0,0), 30);
    msgVar_Number(msgvar_0, var_6);
    ref_162 = dialogAlloc();
    choiceSetResult(1);
    ref_164 = msgShow(msg_39);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]チケット料金が[var(msg_var_0)]円となりますが
[tab]こちらでよろしいでしょうか？
[choice(2)]はい
いいえ
[end_choice][clear]
***************************************/
    wait(ref_164);
    choiceGetResult(var_0);
    bne(var_0, 0, label_16a);
    li(var_7, 1);
    b(label_16d);
  label_16a:
    bne(var_0, 1, label_16d);
    li(var_7, 0);
    b(label_16d);
  label_16d:
    dialogFree(ref_162);
    ref_16e = bustupFade(ref_15f, rgb(0,0,0), 10);
    bustupWait(ref_16e);
    bustupFree(ref_15f);
}

function DECIDE_QUE_NG()
{
    ref_172 = bustupLoad(bustup_13e);
    bustupWait(ref_172);
    ref_174 = bustupAlloc(ref_172, right, rgb(0,0,0));
    bustupFade(ref_174, rgb(128,0,0), 30);
    ref_176 = dialogAlloc();
    choiceSetResult(1);
    ref_178 = msgShow(msg_40);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]残念ながら、こちらのチケットは
[tab]お求めいただけないようですね。
[tab]他のチケットをお選びください。
[wait][clear]
***************************************/
    wait(ref_178);
    dialogFree(ref_176);
    ref_17b = bustupFade(ref_174, rgb(0,0,0), 10);
    bustupWait(ref_17b);
    bustupFree(ref_174);
}

function GOYUKKURI()
{
    ref_17f = bustupLoad(bustup_13e);
    bustupWait(ref_17f);
    ref_181 = bustupAlloc(ref_17f, right, rgb(0,0,0));
    bustupFade(ref_181, rgb(128,0,0), 30);
    ref_183 = dialogAlloc();
    ref_184 = msgShow(msg_41);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]それでは、ごゆっくりお楽しみください。[wait][clear]
***************************************/
    wait(ref_184);
    dialogFree(ref_183);
    ref_187 = bustupFade(ref_181, rgb(0,0,0), 10);
    bustupWait(ref_187);
    bustupFree(ref_181);
    shopInventory(3, shopInventory_1);
}

function NOITEM()
{
    ref_18c = bustupLoad(bustup_13e);
    bustupWait(ref_18c);
    ref_18e = bustupAlloc(ref_18c, right, rgb(0,0,0));
    bustupFade(ref_18e, rgb(128,0,0), 30);
    ref_190 = dialogAlloc();
    ref_191 = msgShow(msg_42);
/***************************************
[color(yellow)]シアターガイド・ミツギ[color(white)]
[tab]当シアターには、ネットワークから輸入した映画を
[tab]まだ入荷しておりません。
[tab]入荷し次第、舞耶様をご案内いたします。[wait][clear]
***************************************/
    wait(ref_191);
    dialogFree(ref_190);
    ref_194 = bustupFade(ref_18e, rgb(0,0,0), 10);
    bustupWait(ref_194);
    bustupFree(ref_18e);
}
