
msg_0:
[end]

msg_1:
[end]

msg_2:
[end]

msg_3:
[end]

msg_4:
[end]

msg_5:
[end]

msg_6:
[end]

msg_7:
[end]

msg_8:
[end]

msg_9:
[end]

msg_10:
[end]

msg_11:
[end]

msg_12:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ 初対面
 デモ 馴レ馴レシイ 不思議 フシギ
[wait][clear][end]

msg_13:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ マイク 初メテ…
 旨ソウナ 香リ…
[wait][clear][end]

msg_14:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ インタビュー
 オレサマ イイ奴 何デモ 聞ケ
[wait][clear][end]

msg_15:





[end]

msg_16:





[end]

msg_17:





[end]

msg_18:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 棒 向ケタ
 ソレ キット 敵意ノ シルシ！
[wait][clear][end]

msg_19:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 何カ 魂胆アル！
 オレサマ 何モ 喋ラナイ！
[wait][clear][end]

msg_20:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 賢イ 世渡リ上手！
 ウマイ話 毒 アル オマエ 悪人！
[wait][clear][end]

msg_21:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 緊張…
[wait][clear][end]

msg_22:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 口下手…
[wait][clear][end]

msg_23:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ オレサマ 何 聞ク ツモリ…
 オレサマ 何モ 知ラナイ…
[wait][clear][end]

msg_24:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 占イ 結構好キ
 オマエ モット 占ウ！
[wait][clear][end]

msg_25:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 占イ 長老ノ業
 オマエ 若イ 見タ目ダケ？
[wait][clear][end]

msg_26:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 占イ オレサマ 種族ノ 神秘
 オマエ オレサマ 種族 同ジカ？
[wait][clear][end]

msg_27:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 占イスル 偉イ奴
 オレサマ 出会エテ 嬉シイ！
[wait][clear][end]

msg_28:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 占イ 特別ノ 儀式
 オマエ オレサマ 占ウ アリガトウ！
[wait][clear][end]

msg_29:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ オレサマ 道シメス
 オレサマ 感激 何モ 言エナイ
[wait][clear][end]

msg_30:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 若過ギ 信用デキナイ
 占イ タクサン 修行必要！
[wait][clear][end]

msg_31:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 占イ 空ト 大地ト 生キ物ノ 神秘！
 オマエ 占イ 馬鹿ニシタ！
[wait][clear][end]

msg_32:
[end]

msg_33:
[end]

msg_34:
[end]

msg_35:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ ヨウギシャ オマエ 刑事
 オマエ オレサマ 何 知リタイ？
[wait][clear][end]

msg_36:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 調ベル オレサマ 答エル
 オレサマ 無実 本当ニ 良イ奴！！
[wait][clear][end]

msg_37:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ 聞キタイ事 アル
 オレサマ 答エル 無罪ホウメン！
[wait][clear][end]

msg_38:
[end]

msg_39:
[end]

msg_40:
[end]

msg_41:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 疑ウ
 オレサマ オマエ マルカジリ！
[wait][clear][end]

msg_42:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 刑事 オレサマ 悪魔
 刑事 悪魔 悪魔 エライ！
[wait][clear][end]

msg_43:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 偉イ 人間 偉クナイ
 オマエ 失礼 オレサマ カンカン！
[wait][clear][end]

msg_44:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 何モ 知ラナイ…
 事件モ 場所モ 「メス」ノ事モ…
[wait][clear][end]

msg_45:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ アリバイ 家ニ イタ
 ヒガイシャ「メス」 無関係
[wait][clear][end]

msg_46:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 事件 無関係…
 何モ 見テナイ 凶器モ 「メス」モ…
[wait][clear][end]

msg_47:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 ソノ声 オレサマ…
 モット 聞カセロ！
[wait][clear][end]

msg_48:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 ソノ道具 誰 喋ル？
 不思議 フシギ？
[wait][clear][end]

msg_49:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 初メテ 聞ク オレサマノ声
 コイツ モノマネ上手！
[wait][clear][end]

msg_50:
[end]

msg_51:
[end]

msg_52:
[end]

msg_53:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 秘密 知ッテル
 生カシテ オケナイ！
[wait][clear][end]

msg_54:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル オマエ ペテン師
 絶対 許サナイ！
[wait][clear][end]

msg_55:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 脅ス 無駄！
 オレサマ オマエ 食イ殺ス
[wait][clear][end]

msg_56:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ソレ オレサマノ声
 気持チ悪イ…
[wait][clear][end]

msg_57:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ オレサマ 悪事 知ッテル
 誰ニモ 言ワナイ コレ 約束…
[wait][clear][end]

msg_58:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 賢イ モット聞カセロ
[wait][clear][end]

msg_59:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 口下手 人間 上手
 オレサマ 尊敬 偉イ エライ！
[wait][clear][end]

msg_60:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 賢イ 異邦人
 オマエ 村来ル ミンナ 歓迎！
[wait][clear][end]

msg_61:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 難シイ話スル
 オレサマ 賢クナッタ気分！
[wait][clear][end]

msg_62:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 賢イ オレサマ 賢イ
 オナジ オナジ！
[wait][clear][end]

msg_63:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 口ダケ人間 質悪イ！
 悪魔モ 怒ル！
[wait][clear][end]

msg_64:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 難シイ事 難シク言ウ 誰デモデキル！
 オマエ 努力 足リナイ
[wait][clear][end]

msg_65:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル オマエ 口ダケ
 デキル奴 ソレ 口ニ シナイ！
[wait][clear][end]

msg_66:





[end]

msg_67:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 賢イ オレサマ 愚カ…
[wait][clear][end]

msg_68:





[end]

msg_69:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 歩キ方 変！
 医者 診テモラエ
[wait][clear][end]

msg_70:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 近ヅク オレサマ 悪魔
 デモ 怖ガラナイ タイシタ奴
[wait][clear][end]

msg_71:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 近ヅク 不用心
 オレサマ 悪魔 用心肝心！
[wait][clear][end]

msg_72:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ オレサマ 無警戒
 オマエ オレサマ キット友達
[wait][clear][end]

msg_73:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 近ヅク オレサマ 悪魔
 オマエ オレサマ キット 好キ
[wait][clear][end]

msg_74:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 知ッテル ソノ歩キ方
 好キナ オス 近ヅク時ノ 歩キ方！
[wait][clear][end]

msg_75:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル ソノ歩キ方
 狩リノ時 獲物ニ 近ヅク 歩キ方！
[wait][clear][end]

msg_76:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 近ヅク オレサマ 恐レナイ
 生意気 人間 マルカジリ！
[wait][clear][end]

msg_77:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 何様 オレサマ 悪魔
 気軽ニ 近ヅク 馴レ馴レシイ！
[wait][clear][end]

msg_78:
[end]

msg_79:
[end]

msg_80:
[end]

msg_81:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ 興味アル
 オレサマ オマエ 興味アル
[wait][clear][end]

msg_82:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ ナニ 見テル
 オレサマ ソンナニ 気ニナルカ
[wait][clear][end]

msg_83:
[end]

msg_84:
[end]

msg_85:
[end]

msg_86:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 目 気ニイラナイ
[wait][clear][end]

msg_87:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ サギ師ノ目
 信ジラレナイ
[wait][clear][end]

msg_88:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ ナニ 見テル
 オレサマ 馬鹿ニ サレテル気分
[wait][clear][end]

msg_89:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ オトコ オレサマ オトコ
 オレサマ ソッチ 興味 ナイ
[wait][clear][end]

msg_90:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 実ハ 気ガ 弱イ…
[wait][clear][end]

msg_91:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ナニカ 気ニ サワッタカ
 許シテクレ
[wait][clear][end]

msg_92:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ メス 大好キ
 オスヨリ 肉 ヤワラカイ！
[wait][clear][end]

msg_93:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 同族 オス アピール
 オマエ達 人間 メス アピール？
[wait][clear][end]

msg_94:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 乳 ヨク出ル 子供 ヨク育ツ
 ヨッテ 頭 赤クナイ メス！
[wait][clear][end]

msg_95:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 同族 メス モテモテ
 ソノウエ 人間 メス モテモテ！
[wait][clear][end]

msg_96:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 聞カレル 頼ラレル 嬉シイ
[wait][clear][end]

msg_97:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ オレサマ 信頼
 ナカナカ 見ル目 アル！
[wait][clear][end]

msg_98:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ達 人間 下等
 好ミ 聞ク 五億年 早イ！
[wait][clear][end]

msg_99:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 人間 蟻 違イ 判ラナイ！
 オレサマ オマエ達 違イ 判ラナイ！
[wait][clear][end]

msg_100:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ達 タダノ 食イモノ！
 色気 出ス 生意気！
[wait][clear][end]

msg_101:




[end]

msg_102:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 強気ナ メス 苦手…
[wait][clear][end]

msg_103:





[end]

msg_104:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ オマエ達 敵同士
 デモ 心配 不思議 フシギ
[wait][clear][end]

msg_105:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 オレサマ 心配スル
 初メテノ 体験 不思議 フシギ
[wait][clear][end]

msg_106:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 悩ミ 今 出来タ
 ソレ 人間ノ事 不思議 フシギ
[wait][clear][end]

msg_107:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 悩ミ 話ス ミンナ 友達
 オレサマ 孤独 違ウ！
[wait][clear][end]

msg_108:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 全然 悩ミ 無イ
 デモ 嬉シイ！
[wait][clear][end]

msg_109:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 悩ミ アッタ 友達 イナイ
 デモ オマエ達 友達 悩ミ 無シ
[wait][clear][end]

msg_110:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 心配スル 人間 何サマ！
 人間 オレサマ 名誉キソン！
[wait][clear][end]

msg_111:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ達 ソレ キット 嘘！
 嘘ツキ イツカ 腹ノ中！
[wait][clear][end]

msg_112:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 嘘 スグ 判ル
 オマエ達 詐欺師 ペテン師 カラス口！
[wait][clear][end]

msg_113:
[end]

msg_114:
[end]

msg_115:
[end]

msg_116:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 話ノ準備 イツデモ ＯＫ！
[wait][clear][end]

msg_117:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 本当ハ オレサマ 話 聞キタイ
 デモ チョット テレテル！
[wait][clear][end]

msg_118:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ 話 聞キタイ
 遠慮スルナ オレサマ 答エル！
[wait][clear][end]

msg_119:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 キット 次 オレサマ 出番！
[wait][clear][end]

msg_120:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 次 オレサマ 話スル ゴ褒美 モラウ
 ゴ褒美 ウマイ エサ ヨダレ 出ル！
[wait][clear][end]

msg_121:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ オレサマ 話 聞キタイ
 デモ テレテル カワイイ奴！
[wait][clear][end]

msg_122:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 無視サレタ
 オレサマ 怒リ気味！
[wait][clear][end]

msg_123:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 人間 下等 オレサマ 上等
 オレサマ 先 アタリマエ！
[wait][clear][end]

msg_124:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 人間 イツデモ 自分中心
 オレサマ ナイガシロ 許セナイ！
[wait][clear][end]

msg_125:





[end]

msg_126:




[end]

msg_127:





[end]

msg_128:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 踊ル
 何ノ 儀式？
[wait][clear][end]

msg_129:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 踊リ子 不思議ナ 力…
[wait][clear][end]

msg_130:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 踊リ 意味アル イロンナ意味
 ソレ ドンナ意味 オレサマ 考エル…
[wait][clear][end]

msg_131:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 同族 踊ル 祭リ！
 ゴチソウ タクサン トテモ 嬉シイ！
[wait][clear][end]

msg_132:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ オレサマ 踊リ 捧ゲル
 オレサマ 神様 トテモ偉イ！
[wait][clear][end]

msg_133:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 踊リ 捧ゲル 敬意ノ証
 オマエ 踊ル オレサマ 喜ブ！
[wait][clear][end]

msg_134:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 踊リ 心 無イ
 オレサマ 不快 怒リ気味！
[wait][clear][end]

msg_135:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 踊リ 神聖！
 オマエ 踊リ 汚ス 悪イ奴！
[wait][clear][end]

msg_136:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 捧ゲル 不気味ナ踊リ
 オレサマ ブジョク 許セナイ！
[wait][clear][end]

msg_137:
[end]

msg_138:
[end]

msg_139:
[end]

msg_140:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 カケル 優シイ 言葉
 オレサマ 迷ウ…
[wait][clear][end]

msg_141:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 人間 食ウ…
 デモ 優シイ オレサマ 困惑…
[wait][clear][end]

msg_142:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 牛 食ウ 牛 人間 心配シナイ
 人間 オレサマ 心配スル 不思議 フシギ
[wait][clear][end]

msg_143:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 優シイ オレサマ 感動！
[wait][clear][end]

msg_144:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 オレサマ 心配！
 オレサマ 人間 信頼！
[wait][clear][end]

msg_145:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 真剣 オレサマ 嬉シイ！
[wait][clear][end]

msg_146:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 人間 イカサマ師！
 オレサマ 悪魔 ダマサレナイ！
[wait][clear][end]

msg_147:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル サギ師ノ 手口
 オレサマ 賢イ ダマサレナイ！
[wait][clear][end]

msg_148:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ ドキドキ 嘘ツキ 小僧
 胸ノ 高鳴リ 隠セナイ！！
[wait][clear][end]

msg_149:





[end]

msg_150:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ イイ奴 ヨク ダマサレル…
[wait][clear][end]

msg_151:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 人間 何 企ム…
 オレサマ 不安…
[wait][clear][end]

msg_152:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 正義 ウマイカ？
[wait][clear][end]

msg_153:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 正義 難シイ 牛 １０頭分
 １０頭 食ッテモ 解ラナイ
[wait][clear][end]

msg_154:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 正義 何ダ 魚カ 肉カ？
 オレサマ 魚ヨリ 肉ガ 好キ！
[wait][clear][end]

msg_155:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 セーギ 知ッテル 甘イ 飲ミ物
 アワ立ツ 牛乳 オレサマ 大好キ！
[wait][clear][end]

msg_156:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 セーギ 判ッタ ２１セーギ
 羽バタク 未来 オレサマ 楽シミ！
[wait][clear][end]

msg_157:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 悪魔 正義 敵
 オマエ 正義 マルカジリ！
[wait][clear][end]

msg_158:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 正義 ヒビキ 嫌ナ ヒビキ！
 オレサマ 不快 ドウシテ クレル！
[wait][clear][end]

msg_159:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル 正義ハ 力！
 オマエ マルカジリ オレサマ 正義！
[wait][clear][end]

msg_160:





[end]

msg_161:





[end]

msg_162:





[end]

msg_163:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 兄弟 思イ出シタ…
 兄弟 ３６匹 スベテ オス！
[wait][clear][end]

msg_164:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 死ンダ兄弟 思イ出シタ…
 兄弟 元々４０匹 ４匹 食ベテ アト３６匹！
[wait][clear][end]

msg_165:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 知ッテル 反抗期！
 兄 心配 スルナ！
[wait][clear][end]

msg_166:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 兄 イイ奴 オレサマ 感動！
 オレサマ 長男 ヨク 解ル
[wait][clear][end]

msg_167:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 思イ出ス 弟ノ事…
 トテモ 可愛イ ソレニ ウマイ！
[wait][clear][end]

msg_168:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 長男 兄 イナイ！
 オマエ イイ兄 弟 ナリタイ！
[wait][clear][end]

msg_169:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 弟 良クナイ 反抗期！
 言ウコト 聞カナイ マルカジリ！
[wait][clear][end]

msg_170:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 兄弟 元々４０匹 今３６匹
 弟 ４匹 オレサマ 反抗 マルカジリ！
[wait][clear][end]

msg_171:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 弟 心配！
 兄ニ 逆ラウ 許セナイ！
[wait][clear][end]

msg_172:





[end]

msg_173:





[end]

msg_174:
[end]

msg_175:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 酒好キ
 オマエ達 イツカ ゴチソウ！
[wait][clear][end]

msg_176:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 黒メガネ ナカナカ 上手イ 酒話！
 オマエ オレサマ 気ガ 合イソウ！
[wait][clear][end]

msg_177:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 解ッタ 酒 人生！
 トコロデ 人生 何？
[wait][clear][end]

msg_178:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 酒好キ 人間 酒好キ
 同ジ オナジ！
[wait][clear][end]

msg_179:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 酒 ウマイ 人間 ツマミ
 オレサマ シアワセ！
[wait][clear][end]

msg_180:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 酒 呑ム ミンナ 陽気
 オレサマ 陽気 ミンナ シアワセ！
[wait][clear][end]

msg_181:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 酒話スル オレサマ 酒 呑ミタイ
 デモ 酒無イ オレサマ 欲求不満！
[wait][clear][end]

msg_182:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 酒呑ミスギ 酒臭イ
 オレサマ 食ウ気失セル 許セナイ！
[wait][clear][end]

msg_183:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル 酒 大敵
 酔ワセテ 首斬ル ヨクアル話！
[wait][clear][end]

msg_184:
[end]

msg_185:
[end]

msg_186:
[end]

msg_187:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 解ラナイ ケンカノ理由
 モット 詳シク 説明シロ
[wait][clear][end]

msg_188:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 頼ム オレサマ ケンカ仲裁
 オレサマ オマエ アイツ 敵 ドイツ？
[wait][clear][end]

msg_189:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 知ッテル 喧嘩ノ元 宗教多イ
 オマエ達 キット 神様 違ウ
[wait][clear][end]

msg_190:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 敵！
 コレダケ 忘レルナ！
[wait][clear][end]

msg_191:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ オマエ 協力シナイ！
 調子ニ 乗ルナ！
[wait][clear][end]

msg_192:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 命令 偉ソウ！
 絶対 オマエ マルカジリ！
[wait][clear][end]

msg_193:




[end]

msg_194:





[end]

msg_195:
[end]

msg_196:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 成長 デカクナル
 人間 成長 考エ 変ワル 不思議 フシギ
[wait][clear][end]

msg_197:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 子供 大人 人間 ドッチ偉イ？
[wait][clear][end]

msg_198:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 判ッタ 大人ト子供違ウ 生キ物！
 オレサマ 偉イ！
[wait][clear][end]

msg_199:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 無関心！
[wait][clear][end]

msg_200:
[end]

msg_201:
[end]

msg_202:
[end]

msg_203:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ 質問
 オレサマ 答エル 頭イイ
[wait][clear][end]

msg_204:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 聞カレタ 重要問題
 人間 キット オレサマ 尊敬
[wait][clear][end]

msg_205:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 聞ク オレサマ 意見
 オレサマ 答エル 問題解決
[wait][clear][end]

msg_206:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ソレ 人間ノ 問題！
 オレサマ 巻キ込ム 不愉快！
[wait][clear][end]

msg_207:




[end]

msg_208:




[end]

msg_209:




[end]

msg_210:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 言ウ オレサマノ事
 キット 褒メテル オレサマ 嬉シイ
[wait][clear][end]

msg_211:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 褒メテル オレサマノ事
 オレサマ ナカナカ 人気者
[wait][clear][end]

msg_212:
[end]

msg_213:
[end]

msg_214:
[end]

msg_215:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル ソレ 皮肉！
 オレサマ 皮 肉 マルカジリ！
[wait][clear][end]

msg_216:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 解ッタ オマエ等 ヒドイ奴
 覚悟ハ 良イカ マルカジリ！
[wait][clear][end]

msg_217:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ等 ヒドイ…
 オレサマ 悲シイ…
[wait][clear][end]

msg_218:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ イイ奴 馬鹿ニサレル…
 オマエ等モ キット ミンナト 同ジ…
[wait][clear][end]

msg_219:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ オス メス 大事
 オマエ等 大変 同情スル
[wait][clear][end]

msg_220:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 意外ト フェミニスト
 オマエ等 意見 尊重スル
[wait][clear][end]

msg_221:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 メス ナカナカ 賢イ
 オレサマ 感心
[wait][clear][end]

msg_222:
[end]

msg_223:
[end]

msg_224:
[end]

msg_225:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマモ オス
 面目ナイ…
[wait][clear][end]

msg_226:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 オス ロクナ奴 イナイ
 オレサマ イイ奴 チョット違ウ
[wait][clear][end]

msg_227:
[end]

msg_228:
[end]

msg_229:
[end]

msg_230:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ッテル ソレ 自分 原因
 ナンデモ 他人 原因 駄目ナ奴！
[wait][clear][end]

msg_231:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オス 前出タ 変ナ奴…
 ソンナニ 食ワレル 楽シミカ？
[wait][clear][end]

msg_232:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ ゴチソウ 献身的
 ナカナカ 旨ソウ イイ気分！
[wait][clear][end]

msg_233:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 食ワレル 積極的
 オレサマ 狩 楽 理想的！
[wait][clear][end]

msg_234:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 オス メス 守ル オレサマ メス 守ル
 オナジ オナジ！
[wait][clear][end]

msg_235:




[end]

msg_236:





[end]

msg_237:





[end]

msg_238:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 思イ出 アル
 オレサマ スグ 忘レル 思イ出 ナイ 
[wait][clear][end]

msg_239:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 ソウイエバ オレサマ 思イ出 アル
 キノウ タクサン 食ベタ
[wait][clear][end]

msg_240:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 思イ出 イッパイ 満足
 オレサマ 腹イッパイ 満足
[wait][clear][end]

msg_241:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ達 昔 子供 オレサマ 昔 子供
 オレサマ オマエ達 オナジ オナジ！
[wait][clear][end]

msg_242:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 昔 子供 カワイイ
 オマエ達 昔 子供 キット カワイイ
[wait][clear][end]

msg_243:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ等 思イ出 興味ナイ！
 オレサマ アキアキ！
[wait][clear][end]

msg_244:
[end]

msg_245:
[end]

msg_246:
[end]

msg_247:
[end]

msg_248:
[end]

msg_249:
[end]

msg_250:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 普通 エサ 自分 アピール シナイ
 人間 チョット 変ナ エサ
[wait][clear][end]

msg_251:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ達 アピール シタ
 ソコ ウマイ 場所カ？
[wait][clear][end]

msg_252:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 全部 旨ソウ…
 オレサマ 迷ウ…
[wait][clear][end]

msg_253:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ達 自分 差シ出ス
 オレサマ キット 王様 偉イ！
[wait][clear][end]

msg_254:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 夢 人間ミナ 食ウ
 オマエ達 三人 食ウ 簡単！
[wait][clear][end]

msg_255:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ達 三人 旨ソウ
 オレサマ 上機嫌！
[wait][clear][end]

msg_256:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ達 骨ト皮
 食ウ所 マルデ 無シ！
[wait][clear][end]

msg_257:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ達 努力シテナイ！
 モット太ル ウマクナル！
[wait][clear][end]

msg_258:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ソレ キット 求愛行為！
 人間 思イアガルナ！
[wait][clear][end]

msg_259:





[end]

msg_260:





[end]

msg_261:





[end]

msg_262:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 同族 メス一匹 オス イッパイ！
 人間 オス一匹 メス イッパイ？
[wait][clear][end]

msg_263:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ達 オス選ブ
 オレサマ 候補 入レル！
[wait][clear][end]

msg_264:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 メス オス選ブ 一番イイ オス アト回シ
 キット オレサマ アト回シ
[wait][clear][end]

msg_265:





[end]

msg_266:





[end]

msg_267:





[end]

msg_268:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 メス オス選ブ オレサマ 入レナイ
 不満イッパイ マルカジリ！
[wait][clear][end]

msg_269:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 今 決闘ノ時間
 オマエ達 ノン気 許セナイ！
[wait][clear][end]

msg_270:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 同族 ヤッパリ メス オス選ブ
 オレサマ 不満 トテモ 不快！
[wait][clear][end]

msg_271:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ナイショ話 オレサマ 悪口…
[wait][clear][end]

msg_272:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 酒誘ウ 人間ノ酒
 オレサマ 初メテ 興味シンシン！
[wait][clear][end]

msg_273:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 初メテ 酔ウ人間！
 オレサマ 観察 モット 飲メ！
[wait][clear][end]

msg_274:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 ミンナ 酒アル メス 大瓶…
 ドコニ隠ス 不思議 フシギ…
[wait][clear][end]

msg_275:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 宴会 オレサマ 不愉快！
[wait][clear][end]

msg_276:





[end]

msg_277:
[end]

msg_278:
[end]

msg_279:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ達 オレサマ ヨク 知ッテル
 感心 カンシン！
[wait][clear][end]

msg_280:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ達 モットモ
 オレサマ 反省！
[wait][clear][end]

msg_281:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 指摘 イイトコ 突イテル
 人間 ナカナカ 頭 イイ！
[wait][clear][end]

msg_282:
[end]

msg_283:
[end]

msg_284:
[end]

msg_285:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 上等 人間 下等
 オレサマ 言ワレル 筋合イ ナイ！
[wait][clear][end]

msg_286:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ等 偉ソウ オレサマ 偉イ
 ドッチ 偉イカ ヨク 考エロ！
[wait][clear][end]

msg_287:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ等 ナニ言ウ オレサマ 悪魔
 オマエ等 指摘 的外レ！
[wait][clear][end]

msg_288:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 人間 怒ル
 オレサマ 悪イカ…
[wait][clear][end]

msg_289:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 愚カ デモ 解ル…
 人間 怒ル オレサマ 悪イ…
[wait][clear][end]

msg_290:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 人間 怒ル オレサマ 食ウカ…
[wait][clear][end]

msg_291:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 怖イ話スル ヤッパリ怖イ
 デモ 怖イ話好キ 不思議 フシギ
[wait][clear][end]

msg_292:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 知ッテル 怖イ話
 オレサマ 母 怖イ コワイ
[wait][clear][end]

msg_293:
[end]

msg_294:
[end]

msg_295:
[end]

msg_296:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 怖イ話スル オレサマ モット怖イ
 オレサマ コレカラ 解ラセル！
[wait][clear][end]

msg_297:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 怖イ話 嘘臭イ
 オレサマ 判ル オレサマ 悪魔！
[wait][clear][end]

msg_298:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 悪魔 怖イ奴
 オマエ 怖イ話 必要ナイ！
[wait][clear][end]

msg_299:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 苦手 怖イ話…
[wait][clear][end]

msg_300:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 怖イ話スル
 アイツ キット来ル…
[wait][clear][end]

msg_301:
[end]

msg_302:
[end]

msg_303:
[end]

msg_304:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 勇マシイ
 勇気アル 人間 大好物！
[wait][clear][end]

msg_305:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 脅ス オレサマ オマエ 倒ス
 オレサマ 勇者！
[wait][clear][end]

msg_306:
[end]

msg_307:
[end]

msg_308:
[end]

msg_309:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 死人ト 話ス
 オマエ スゴイ奴！
[wait][clear][end]

msg_310:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 死人 喋ルカ？
 人間 面白イ！
[wait][clear][end]

msg_311:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 悲シム…
 オレサマ 悪イカ…
[wait][clear][end]

msg_312:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 許セ…
[wait][clear][end]

msg_313:
[end]

msg_314:
[end]

msg_315:
[end]

msg_316:
[end]

msg_317:
[end]

msg_318:
[end]

msg_319:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 仲間割レ！
 オレサマ 勝利確実！
[wait][clear][end]

msg_320:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 同感
 死ンダ奴 自分ガ悪イ！
[wait][clear][end]

msg_321:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 死ンダ奴 悪ク言ウ
 許セナイ奴！
[wait][clear][end]

msg_322:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 死ンダ奴 悪ク言ウ奴
 オレサマ 信用デキナイ
[wait][clear][end]

msg_323:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 死ンダ仲間 悪ク言ウ
 悪魔ヨリ 悪イ奴…
[wait][clear][end]

msg_324:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 死ヌ オマエ 悪口言ウ…
[wait][clear][end]

msg_325:
[end]

msg_326:
[end]

msg_327:
[end]

msg_328:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 強イ オマエ 弱イ
 状況ハアク オマエ 偉イ！
[wait][clear][end]

msg_329:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 命乞イ オレサマ 強イ！
[wait][clear][end]

msg_330:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ エステ 行ク 旨クナル
 オレサマ 嬉シイ！
[wait][clear][end]

msg_331:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 エステ 行ク オレサマ 食ウ
 人間 キレイ キット 腹コワサナイ！
[wait][clear][end]

msg_332:
 オマエ 何 聞キタイ？
[choice(3)]好きな女の子のタイプは？
好きな食べ物は何？
弱点は何処なの？
[end_choice][clear][end]

msg_333:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 太ッタ メス 好キ
 子供 ヨク産ム！
[wait][clear][end]

msg_334:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ テレ屋
 ソンナ事 言エナイ…
[wait][clear][end]

msg_335:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ 好物 聞ク
 キット オマエ 食イ物 プレゼント
[wait][clear][end]

msg_336:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 人間 大好キ！
[wait][clear][end]

msg_337:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 弱点 言ウ
 オマエ オレサマ 殺ス…
[wait][clear][end]

msg_338:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 賢イ！
 ソノ手 ノラナイ
[wait][clear][end]

msg_339:
 オマエ達 何故 オレサマ 心配スル？
[choice(3)]人類皆兄弟って言うじゃない！
あなたが可愛いからよ！
あなたを油断させる為よ！
[end_choice][clear][end]

msg_340:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人類ミナ兄弟 デモ オレサマ 人類違ウ
 不思議 フシギ？
[wait][clear][end]

msg_341:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 人類違ウ…
[wait][clear][end]

msg_342:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ カワイイ！
[wait][clear][end]

msg_343:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 詐欺師ノ目！
[wait][clear][end]

msg_344:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 策士 オレサマ ダマサレタ…
[wait][clear][end]

msg_345:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 嘘ツキ キライ 許セナイ！
[wait][clear][end]

msg_346:
[color(yellow)][var(msg_var_0)][color(white)]
 動物 オスメス 「アピール」スル方
 違ウ形 多イ ソコ アピール
 クジャク オス 羽根 キレイ！
[wait][clear][end]

msg_347:
 人間 メス 何処 アピール？
[choice(3)]胸かな…
顔で勝負ね
やっぱ性格でしょ！
[end_choice][clear][end]

msg_348:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 メス 子供 乳ヤル
 胸 アピール 合理的！
[wait][clear][end]

msg_349:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 胸 見ル
 オナジ オナジ！
[wait][clear][end]

msg_350:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 人間 顔 同ジ
 オレサマ 判ラナイ…
[wait][clear][end]

msg_351:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 人間 顔 同ジ
 ソレ 嘘ニ 違イナイ！
[wait][clear][end]

msg_352:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 性格見エナイ 判リニクイ…
 人間 性格見エル 不思議 フシギ…
[wait][clear][end]

msg_353:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 オス メスノ性格 判ル
 オモシロイ！
[wait][clear][end]

msg_354:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ 迷ッタ オマエ達 原因！
 オレサマ 余計 腹ヘッタ！
[wait][clear][end]

msg_355:
 オレサマ グルメ オマエ ナニ味？
[choice(4)]甘い
しょっぱい
辛い
苦い
[end_choice][clear][end]

msg_356:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 甘イ 糖分 糖尿病…
 オマエ 早ク 病院 行ケ！
[wait][clear][end]

msg_357:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 甘イモノ 好キ！
[wait][clear][end]

msg_358:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 生キ物 塩分 必要！
[wait][clear][end]

msg_359:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ショッパイ 塩分 高血圧
 オレサマ 心配…
[wait][clear][end]

msg_360:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 辛イ 唐辛子 カプサイシン！
 体ニイイ オレサマ 大好キ！
[wait][clear][end]

msg_361:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 辛イ 種類イロイロ
 オマエ 種類言ワナイ 不親切！
[wait][clear][end]

msg_362:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 良イ薬 口 苦イ
 オマエ 薬 オレサマ 健康！
[wait][clear][end]

msg_363:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 苦イ 嫌イ…
 苦イ 食ベ物 毒アル…
[wait][clear][end]

msg_364:
 オレサマ イイ奴 何 聞キタイ
[choice(4)]好きな女の子のタイプ
好きな食べ物
弱点
聞きたい事など無い
[end_choice][clear][end]

msg_365:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 ヤッパリ テレ屋 良イ事 教エル
 聞クハ 一時ノ恥 聞カヌハ 一生ノ恥！
[wait][clear][end]

msg_366:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 冷タイ…
[wait][clear][end]

msg_367:
 オレサマ 答エル 何デモ 聞ケ
[choice(3)]先ずはアリバイから聞いておこうか
率直に聞くが、お前が犯人だな！
カツ丼でも食うか？
[end_choice][clear][end]

msg_368:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ オレサマ アリバイ 判ルカ？
 オレサマ 激シイ モノ忘レ 判レバ教エロ！
[wait][clear][end]

msg_369:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 激シイ モノ忘レ…
 昔ノ事 覚エテナイ…
[wait][clear][end]

msg_370:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 無実…
 信ジテ 欲シイ…
[wait][clear][end]

msg_371:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 失礼！
 オレサマ 無実！
[wait][clear][end]

msg_372:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ イイ奴 オレサマ 食ウ！
[wait][clear][end]

msg_373:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ カツ丼 ナイ！
[wait][clear][end]

msg_374:
 オレサマ ドウスレバ良イ…
[choice(3)]無駄な争いはやめよう…
僕達に力を貸してくれないか
ならば死んでもらおうか…
[end_choice][clear][end]

msg_375:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 争イ キライ
 平和解決 コレ 一番！
[wait][clear][end]

msg_376:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 臆病者！
 オレサマ 臆病者 大キライ！
[wait][clear][end]

msg_377:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 力 貸ス…
 デモ 何 貸ス？
[wait][clear][end]

msg_378:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 結局 ソレ 目的！
 オレサマ 力 貸ス気 ナイ！
[wait][clear][end]

msg_379:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ オマエ 信ジタ…
 デモ 酷イ奴 オレサマ 悲シイ…
[wait][clear][end]

msg_380:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ヤッパリ 人間 酷イ奴
 オレサマ オマエ 許サナイ！
[wait][clear][end]

msg_381:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 誰デモ 一度 反抗期
 デモ イツカ 忘レル…
[wait][clear][end]

msg_382:
 オマエ 反抗期 無カッタカ？
[choice(3)]そう言えば僕にもあったな…
僕はずっと素直だったさ
そんな昔の事は忘れたよ
[end_choice][clear][end]

msg_383:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 昔 反抗期 弟 今 反抗期
 オマエ 大目ニ 見ロ
[wait][clear][end]

msg_384:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 素直 ナカナカ イイ奴！
[wait][clear][end]

msg_385:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 反抗期ナイカ？
 悪魔 人間 チョット違ウ…
[wait][clear][end]

msg_386:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ソレ キット 嘘！
 オレサマ 嘘ツキ 大キライ！
[wait][clear][end]

msg_387:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 忘レル オレサマ オナジ！
 似タ者同士 会エテ 嬉シイ！
[wait][clear][end]

msg_388:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 覚エテル
 格好ツケル オレサマ キライ！
[wait][clear][end]

msg_389:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 肉好キ 太リ気味…
[wait][clear][end]

msg_390:
 オレサマ ドウスレバ 良イ？
[choice(3)]ならば運動をする事だな
栄養バランスも考えた方が良い
その方が旨そうだ
[end_choice][clear][end]

msg_391:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 運動 大キライ…
[wait][clear][end]

msg_392:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ソンナ事 誰デモ 知ッテル！
 モット 気ノ利イタ事 言エ！
[wait][clear][end]

msg_393:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 栄養バランス 初メテ 聞イタ…
 オレサマ チョット 賢クナッタ！
[wait][clear][end]

msg_394:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 栄養バランス 知ラナイ 言葉…
 オレサマ マダマダ 勉強不足…
[wait][clear][end]

msg_395:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 旨ソウ コノママ ＯＫ！
 ……ン？
[wait][clear][end]

msg_396:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ オレサマ 食ウ気カ…
[wait][clear][end]

msg_397:
 オマエ 本当ハ 歳 イクツ？
[choice(3)]まだ２４歳よ！失礼なやっちゃ！
ピチピチの１６歳でーす♥
もう歳の事なんて忘れたわ
[end_choice][clear][end]

msg_398:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ ２４歳 人間５０年！
 オマエ ヤッパリ 年寄リ！
[wait][clear][end]

msg_399:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 答エ 反抗的！
[wait][clear][end]

msg_400:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ １６ チョット 無理
 本当ナラバ コノ世ノ 神秘
[wait][clear][end]

msg_401:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ １６ 見エナイ
 ソレ キット 何カノ 呪イ…
[wait][clear][end]

msg_402:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 歳 忘レル 多分 長生キ
 オレサマ 年寄リ 尊敬スル
[wait][clear][end]

msg_403:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 歳 隠ス！
 オレサマ 嘘ツキ 大キライ！
[wait][clear][end]

msg_404:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 人間 ウラヤマシイ…
 オレサマ メス イッパイ 好キ
[wait][clear][end]

msg_405:
 オレサマ 人間 ナレルカ？
[choice(3)]生まれ変わったらなれるんじゃない
無理にきまってるじゃ～ん！
アンタも好きねぇ♥
[end_choice][clear][end]

msg_406:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 死ヌ 次 人間！
 オレサマ チョット 死ヌ 楽シミ！
[wait][clear][end]

msg_407:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 生マレ変ワル 死ヌ 必要…
 デモ オレサマ 死ヌ 怖イ…
[wait][clear][end]

msg_408:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ヤッパリ 無理カ…
 オレサマ 悲シイ…
[wait][clear][end]

msg_409:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 冷タイ オレサマ 怒リ気味！
[wait][clear][end]

msg_410:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 何好キ？
[wait][clear][end]

msg_411:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 聞イタ 人間 ナレルカ
 オマエ ソレ 答エ 違ウ！
[wait][clear][end]

msg_412:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 考エタ デモ 判ラナイ…
[wait][clear][end]

msg_413:
 オレサマ 降参 意味 教エロ
[choice(3)]悲しみと情熱を表現したのよ
愛してるって意味♥
ふふふ！アンタを殺すって意味さ！
[end_choice][clear][end]

msg_414:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 踊リ 表ス 自分ノ 気持チ
 オマエ 何 悲シイ？
[wait][clear][end]

msg_415:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 判ッタ 悲シミ 情熱！
 オマエ ナカナカ 見所アル！
[wait][clear][end]

msg_416:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ モテモテ イイ気分！
[wait][clear][end]

msg_417:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 詐欺師ノ目
 オレサマ 少シ 傷ツイタ！
[wait][clear][end]

msg_418:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 踊リ 知ッテル 呪イノ踊リ…
 見タ者 絶対 死ガ 訪レル…
[wait][clear][end]

msg_419:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ イイ度胸
 オレサマ 絶対 オマエ 殺ス！
[wait][clear][end]

msg_420:
 ソノ道具 他ニ 何デキル？
[choice(3)]他には何も出来ねぇな…
料理なんか出来るぜ…お前さんのな！
そいつは企業秘密、教えられねぇな…
[end_choice][clear][end]

msg_421:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 残念…
[wait][clear][end]

msg_422:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ソノ道具 モノマネ スルダケ 役立タズ！
[wait][clear][end]

msg_423:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 食ベル 大好キ
 初メテ 食ベル オレサマ料理 …ン？
[wait][clear][end]

msg_424:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 秘密 魅力的 オレサマ 余計 知リタイ…
[wait][clear][end]

msg_425:
 オマエ 人生 知ッテルカ？
[choice(3)]人が生きると書いて人生だ
そんなもん、いくら歳食っても判らねぇさ…
「人生」なんざ意味のねぇ言葉だな…
[end_choice][clear][end]

msg_426:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人 生キル 人生 悪魔 生キル 何？
 新シイ 疑問 不思議 フシギ？
[wait][clear][end]

msg_427:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 解ッタ 人 生キル 人生
 オレサマ 少シ 賢ク ナッタ！
[wait][clear][end]

msg_428:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 歳食ウ 不思議ナ 人間
 オレサマ 食ッタ事ナイ ソレ 旨イカ？
[wait][clear][end]

msg_429:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ ソレ 食ッタ事ナイ
 オマエダケ 食ウ ズルイ奴！
[wait][clear][end]

msg_430:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 意味ナイカ…
[wait][clear][end]

msg_431:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 本当ハ 知ラナイダケ！
[wait][clear][end]

msg_432:
 一体 ドコ 隠シテタ？
[choice(3)]私のポケットは異次元に繋がってるんだ
折り畳んで胸のポケットに…
アンタなんかに教えられないよ
[end_choice][clear][end]

msg_433:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 次元ノ扉開ク オマエ 大魔術師
 オレサマ 会エテ 嬉シイ！
[wait][clear][end]

msg_434:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 次元ノ扉開ク ソレ 自然狂ワス 魔法ノ力…
 村ノ 長老 恐レタ オレサマモ…
[wait][clear][end]

msg_435:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 ソノ瓶 折リタタメル 魔法ノ瓶…
[wait][clear][end]

msg_436:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ
 オマエ 胸ニ ポケット 無イ！
[wait][clear][end]

msg_437:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ 何デモ 答エル
[wait][clear][end]

msg_438:
 オマエ 何デモ 聞ケ！
[choice(3)]日本経済は、どうすれば回復するのだ？
予期される食糧危機を如何に回避する？
貴様になど答えられそうもないな…
[end_choice][clear][end]

msg_439:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 難シイ話 オレサマ 実ハ 解ラナイ
 デモ 考エル振リ ムムムムム…
[wait][clear][end]

msg_440:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 食イ物以外 関心ナイ！
 食イ物ノ 話ニ シロ！
[wait][clear][end]

msg_441:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 タクサン オレサマ 満腹！
 オマエ ソレ 勘違イ
[wait][clear][end]

msg_442:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ 素直 悪イ所 直ス
[wait][clear][end]

msg_443:
 モット オレサマ 悪イ所 言エ
[choice(3)]もっと勉学に励まなくてはならんな
整形手術でも受けたらどうだ？
とにかく性格が悪いな
[end_choice][clear][end]

msg_444:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 強イ！
 勉強デキレバ モット 凄イ！
[wait][clear][end]

msg_445:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 勉強苦手…
[wait][clear][end]

msg_446:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 セイケイシュジュツ 初メテ聞ク 言葉…
 旨イカ？
[wait][clear][end]

msg_447:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 手術 知ッテル カイゾウ手術
 オマエ オレサマ カイゾウ スル気！
[wait][clear][end]

msg_448:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 知ッテル 性格 悪イ…
 デモ ナカナカ 直セナイ…
[wait][clear][end]

msg_449:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 失礼 オレサマ ゴ立腹
[wait][clear][end]

msg_450:
 オマエ オレサマ モット 褒メロ！
[choice(2)]神々しき馬鹿面、私は笑いを禁じ得ません！
皮肉すら判らないとは相当なものだな…
[end_choice][clear][end]

msg_451:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 馬鹿面 オレサマ 偉イ …ン？
[wait][clear][end]

msg_452:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 皮肉 イッタイ 何ノ肉
 オレサマ 興味シンシン！
[wait][clear][end]

msg_453:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 解ッタ 皮肉 悪口
 オレサマ 喜ブ 格好ワルイ…
[wait][clear][end]

msg_454:
 オマエ 母 怖クナイカ？
[choice(3)]私のＭａｍは優しいですわよ
私も怖いですわ
ＭａｍよりＤａｄｄｙの方が怖いですわ
[end_choice][clear][end]

msg_455:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 母 優シイ
 オレサマ ウラヤマシイ！
[wait][clear][end]

msg_456:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 母 優シイ
 オレサマ 損シタ気分 許セナイ！
[wait][clear][end]

msg_457:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ オマエ 母 怖イ
 オナジ オナジ
[wait][clear][end]

msg_458:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ヤッパリ 母 怖イカ…
 母 恐ロシイ…
[wait][clear][end]

msg_459:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 父 イナイ
 ソレ ウラヤマシイ…
[wait][clear][end]

msg_460:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 父 イナイ
 オレサマ兄弟 産ム時 母 父 食ッタ
[wait][clear][end]

msg_461:
[color(yellow)][var(msg_var_0)][color(white)]
 マズ ジコショウカイ
 オレサマ [var(msg_var_0)]
[wait][clear][end]

msg_462:
 オマエ ナマエ 言エ
[choice(3)][suou][tab][tatsuya]
[var(msg_var_0)]
答えない
[end_choice][clear][end]

msg_463:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ [suou][tab][tatsuya]カ…
 初メテ 聞ク 名前
[wait][clear][end]

msg_464:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 名前モ 顔モ オモシロイ
[wait][clear][end]

msg_465:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ オレサマ オレサマ オマエ！
 コレモ キット ナニカノ縁！
[wait][clear][end]

msg_466:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ オレサマ オレサマ オマエ
 自分ニ 出会ウ 死ノ 予兆…
[wait][clear][end]

msg_467:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ ナニモ 言ワナイ
 オレサマ イライラ
[wait][clear][end]

msg_468:
[color(yellow)][var(msg_var_0)][color(white)]
 オマエ 自分 オススメ
 キット 旨イ場所 知ッテル！
[wait][clear][end]

msg_469:
 オマエ ドコ ウマイ？
[choice(4)]腕
脚
脳
美味しくない
[end_choice][clear][end]

msg_470:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 腕 オススメ！
 イツカ 食ワセロ！
[wait][clear][end]

msg_471:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 腕 マズソウ！
[wait][clear][end]

msg_472:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 確カニ 脚 肉タクサン 旨ソウ！
[wait][clear][end]

msg_473:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 確カニ 旨ソウ…
 デモ 臭ソウ…
[wait][clear][end]

msg_474:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ ソレ 食ッタコトナイ！
 興味シンシン！
[wait][clear][end]

msg_475:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 脚 好キ
 脳 イラナイ！
[wait][clear][end]

msg_476:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 確カニ オマエ マズソウ…
 オマエ 正直モノ
[wait][clear][end]

msg_477:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ！
 オレサマ オマエ マルカジリ！ 
[wait][clear][end]

msg_478:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 [var(msg_var_0)] 思イ出 大事
 デモ イツカ 忘レル
[wait][clear][end]

msg_479:
 時間 ナゼ 思イ出 消ス？
[choice(3)]新たな思い出を作る為の準備
記憶の検索性を保つ為の脳の仕組み
忘れっぽいだけ
[end_choice][clear][end]

msg_480:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 アタラシイ 思イ出 ツクル
 キット 楽シイ 思イ出！
[wait][clear][end]

msg_481:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ フルイ 思イ出モ 大切！
 忘レル 余計ナ事！
[wait][clear][end]

msg_482:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 難シイ事 言ウ
 キット 頭 イイ！
[wait][clear][end]

msg_483:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 説明 難シイ…
 ヒョットシテ エライ奴…
[wait][clear][end]

msg_484:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ スグ 忘レル
 ヒョットシテ 病気…
[wait][clear][end]

msg_485:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ ダマサレナイ
 オレサマ アタマ イイ
[wait][clear][end]

msg_486:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 トコロデ オレサマ 聞キタイ事 アル
 オレサマ [var(msg_var_0)] オマエ 人間
[wait][clear][end]

msg_487:
 ドコガ 違ウ
[choice(4)]違わない
名前
種族
根本的に違う
[end_choice][clear][end]

msg_488:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 人間 オレサマ ナニモ 違ワナイ
 オレサマ 悩ム 必要ナイ
[wait][clear][end]

msg_489:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 人間 違ウ
 人間 下等 一緒ニ スルナ
[wait][clear][end]

msg_490:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 名前 チガウ イイ 意見
 オマエ ナカナカ ミドコロアル
[wait][clear][end]

msg_491:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 「人間」 ナマエ チガウ
 オマエ 言ウ事 ケントウチガイ
[wait][clear][end]

msg_492:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 意見 テキカク
 ナカナカ アタマ イイ
[wait][clear][end]

msg_493:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 意見 ツマラナイ
 オレサマ タイクツ
[wait][clear][end]

msg_494:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ イイコト 言ッタ
 オレサマ オマエ ゼンゼン違ウ
[wait][clear][end]

msg_495:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 前カラ 聞キタイ事 アル
 人間 家デ シカクイ箱 見ル
[wait][clear][end]

msg_496:
 アレ ナンダ？
[choice(4)]タンス
テレビ
金魚の水そう
見ない
[end_choice][clear][end]

msg_497:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 タンス 人 シマウ
 不思議 フシギ
[wait][clear][end]

msg_498:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 アレ タンス 違ウ
 オマエ オレサマ ダマス ワルイ奴！
[wait][clear][end]

msg_499:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 アレガ テレビ
 興味シンシン イツカ 見セロ
[wait][clear][end]

msg_500:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 テレビ 知ッテル 毒電波
 オレサマ 恐ロシイ
[wait][clear][end]

msg_501:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 金魚 イツカ 食ウ
 オマエ オレサマ ゴチソウ
[wait][clear][end]

msg_502:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 金魚 食ウ 一人ジメ！
[wait][clear][end]

msg_503:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 知ラナイ
 オレサマ 寝レナイ…
[wait][clear][end]

msg_504:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ ソレ 知ラナイ フリ！
[wait][clear][end]

msg_505:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ イツモ 不思議
[wait][clear][end]

msg_506:
 人間 ナゼ 頭ダケ 毛 ハエル
[choice(3)]大切な脳を守る為
服を着るから他の部分に毛は要らない
実は頭以外にも生えている
[end_choice][clear][end]

msg_507:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 難シイコト 言ウ
 実ハ カシコイ！
[wait][clear][end]

msg_508:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 言ウコト 難シイ
 オレサマ 馬鹿ニ シテル！
[wait][clear][end]

msg_509:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 毛 ハエル 服 イラナイ！
 オレサマ カシコイ！
[wait][clear][end]

msg_510:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 服 着ル 毛 抜ケル…
 服 呪イノ 道具…
[wait][clear][end]

msg_511:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 見タイ 興味シンシン！
[wait][clear][end]

msg_512:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ ソンナ毛 見タコト ナイ
 オマエ オレサマ ダマシテル！
[wait][clear][end]

msg_513:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 人間 コトバ 色々 アル
 オレサマ 覚エル 大変！
[wait][clear][end]

msg_514:
 オレサマ ドコノ コトバ 覚エレバ イイ？
[choice(4)]英語
中国語
日本語
エスペラント語
[end_choice][clear][end]

msg_515:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 英語 知ッテル 「アイ ラブ ユー」
 オレサマ スゴイ
[wait][clear][end]

msg_516:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 英語 知ッテル 「ユー シャル ダイ！」
 オレサマ イツカ オマエ 殺ス！
[wait][clear][end]

msg_517:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 中国 人 タクサン！
 覚エル タクサン 話セル！
[wait][clear][end]

msg_518:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 中国語 タクサン 全部 覚エル 大変！
[wait][clear][end]

msg_519:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 日本語 ハナス！
 オマエ オレサマ 教エル！
[wait][clear][end]

msg_520:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 日本語 難シイ…
 オレサマ 無理…
[wait][clear][end]

msg_521:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 エスペラント ドコノ国？
 オレサマ 知ラナイ！
[wait][clear][end]

msg_522:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 知ラナイ エスペラント
 オマエ オレサマ ダマシテル！
[wait][clear][end]

msg_523:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ チョット 怒リ気味
 コレ以上 怒ラセル オマエ 食ウ！
[wait][clear][end]

msg_524:
 オマエ ドコ ウマイ？
[choice(4)]腕
脚
脳
美味しくない
[end_choice][clear][end]

msg_525:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 腕 オススメ！
 イツカ 食ワセロ！
[wait][clear][end]

msg_526:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ 腕 マズソウ！
[wait][clear][end]

msg_527:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 確カニ 脚 肉タクサン 旨ソウ！
[wait][clear][end]

msg_528:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 確カニ 旨ソウ…
 デモ 臭ソウ…
[wait][clear][end]

msg_529:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ ソレ 食ッタコトナイ！
 興味シンシン！
[wait][clear][end]

msg_530:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 脚 好キ
 脳 イラナイ！
[wait][clear][end]

msg_531:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 確カニ オマエ マズソウ…
 オマエ 正直モノ
[wait][clear][end]

msg_532:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 嘘ツキ！
 オレサマ オマエ マルカジリ！ 
[wait][clear][end]

msg_533:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ [var(msg_var_0)] オマエ 人間
[wait][clear][end]

msg_534:
 オマエ ドッチ 偉イト 思ウ！
[choice(3)][var(msg_var_0)]
人間
同じくらい
[end_choice][clear][end]

msg_535:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 偉イ 当リ前
[wait][clear][end]

msg_536:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ ビンカン
 オマエ ズルイ奴
[wait][clear][end]

msg_537:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ 多分 アタマ オカシイ
 医者ニ 行ケ
[wait][clear][end]

msg_538:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 実ハ 気ガ ヨワイ
[wait][clear][end]

msg_539:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ オマエ 同ジ
 ミンナ 平等 悪クナイ！
[wait][clear][end]

msg_540:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ 人間 下等 オレサマ 悪魔 偉イ
 調子ニ ノルナ！！
[wait][clear][end]

msg_541:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ オレサマ 怒ラセル
 恐イモノ知ラズ！
[wait][clear][end]

msg_542:
 オマエ 恐イモノ ナイカ？
[choice(4)]無い
母親が恐い
悪魔が恐い
まんじゅう恐い
[end_choice][clear][end]

msg_543:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 ナラ 仕方ナイ…
[wait][clear][end]

msg_544:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 ソレナラ オレサマ オマエ 恐ガラセル！
[wait][clear][end]

msg_545:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 母親 恐イ
 オレサマ オマエ オナジ オナジ
[wait][clear][end]

msg_546:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 母親 恐イ 思イ出ス…
 嫌ナ 思イ出…
[wait][clear][end]

msg_547:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ 悪魔！
 オマエ オレサマ 恐イ！
[wait][clear][end]

msg_548:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 悪魔 モット 恐レロ！
[wait][clear][end]

msg_549:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 マンジュウ ウマイ
 ナゼ 恐イ 不思議 フシギ
[wait][clear][end]

msg_550:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ ダマサレナイ
 オレサマ アタマ イイ
[wait][clear][end]

msg_551:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ オマエ イッパイ 話シタ
 オマエ オレサマ 理解シタ！
[wait][clear][end]

msg_552:
 オレサマ ドンナ奴？
[choice(4)]優しい悪魔
強い悪魔
愚かな悪魔
分からない
[end_choice][clear][end]

msg_553:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オマエ 良ク理解 アタマ良イ！
[wait][clear][end]

msg_554:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 話シタダケ ソレ 分カラナイ！
 オマエ 嘘ツキ 悪イ奴！
[wait][clear][end]

msg_555:
[color(yellow)][var(msg_var_0)][color(white)]
 愚カ 知ッテル 英語デ ＦＯＯＬ！
[wait][clear][end]

msg_556:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ オレサマ 嫌イカ？
 オレサマ 悲シイ…
[wait][clear][end]

msg_557:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)]占札／ＦＯＯＬノ カード[color(white)] ヤル！
 オレサマ 愚カ オマエ ＦＯＯＬ！
 オナジ オナジ 大事ニ シロ！
[wait][clear][end]

msg_558:
[color(yellow)][var(msg_var_0)][color(white)]
 人間 ナカナカ オモシロイ
 オレサマ 興味シンシン
 オレサマ カード ヤル
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_4)][color(white)]ノカード [color(green)][var(msg_var_5)]枚[color(white)]
[wait][clear][end]

msg_559:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ 人間 興味 ワイタ
 デモ ツイテイク 約束イハン
 代ワリニ カード ヤル
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_4)][color(white)]ノカード [color(green)][var(msg_var_5)]枚[color(white)]
[wait][clear][end]

msg_560:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)]フリータロット[color(white)]モ [color(green)][var(msg_var_6)]枚[color(white)] ヤル
 キット 役ダツ
[wait][clear][end]

msg_561:
[color(yellow)][var(msg_var_0)][color(white)]
 オマエ達 カード イッパイイッパイ
 オレサマ チョット ガッカリ
 カード マタ 今度 オレサマ 帰ル
[wait][clear][end]

msg_562:
[color(yellow)][var(msg_var_0)][color(white)]
 ソノ カード 友達ノ シルシ
 大切ニ シロ
[wait][clear][end]

msg_563:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ オマエ達 キニイッタ
 オマエ達 オレサマ [color(green)]契約[color(white)] ダメ
 デモ オレサマ ココロ 広イ
[wait][clear][end]

msg_564:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オマエ マダ [color(green)]レベル 低イ[color(white)]
 契約 デキナイ… 代ワリニ…
[wait][clear][end]

msg_565:
[color(yellow)][var(msg_var_0)][color(white)]
 オマエ 強クナル オレサマ 契約
 楽シミ タノシミ！
 マタ 会オウ
[wait][clear][end]

msg_566:
 [color(green)]契約[color(white)] スルカ？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_567:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ オマエ達 コレデ トモダチ
 次ニ 出会ウ 楽シミ
[wait][clear][end]

msg_568:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 残念…
 機会 アッタラ マタ 会オウ
[wait][clear][end]

msg_569:
[color(yellow)][var(msg_var_0)][color(white)]
 オマエ 契約 イッパイイッパイ
 オレサマ 契約 デキナイ
 ドレカ [color(green)]契約ハキ[color(white)] オレサマ 契約
[wait][clear][end]

msg_570:
 ドノ[color(green)]契約 ハキ[color(white)] スル
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
やっぱりやめる
[end_choice][clear][end]

msg_571:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オマエ達 オレサマ 怒ラセタ
 オマエ達 契約 値シナイ！
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 モウ オレサマ アキアキ
 [color(green)]契約 ヤメル[color(white)]
 次ニ 会ッタラ 覚悟シロ！
[wait][clear][end]

msg_572:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ オマエ [color(green)]契約ヤメル[color(white)]…
 オマエ 恐イ オレサマ イツカ 殺サレル…
[wait][clear][end]

msg_573:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 急ニ 腹 痛イ
 コレデ 帰ル
[wait][clear][end]

msg_574:
[color(yellow)][var(msg_var_0)][color(white)]
 ガァーー！
 オレサマ 怒リ サイコウチョウ！
 オレサマ オマエ達 マルカジリ！！
[wait][clear][end]

msg_575:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 人間 カナワナイ
 オマエ達 オレサマ 好キニシロ
[wait][clear][end]

msg_576:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ 人間 タンノウ
 ナカナカ イイ奴
 ナニカ ヤル
[wait][clear][end]

msg_577:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_1)][color(white)] ヤル
 コレ オレサマ 宝物
[wait][clear][end]

msg_578:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)]￥[var(msg_var_2)][color(white)] ヤル
 人間 不ケイキ
 オレサマ ケーキ好キ
[wait][clear][end]

msg_579:
[color(yellow)][var(msg_var_0)][color(white)]
 残念 オレサマ ナニモ モッテナイ
 代ワリニ [color(green)]回復[color(white)]
 オレサマ イイ奴
[wait][clear][end]

msg_580:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ コレデ オサラバ
 マタ 会ウ日マデ！！
[wait][clear][end]

msg_581:





[end]

msg_582:





[end]

msg_583:





[end]

msg_584:





[end]

msg_585:





[end]

msg_586:





[end]

msg_587:





[end]

msg_588:





[end]

msg_589:









[end]

msg_590:
[end]

msg_591:
[end]

msg_592:





[end]

msg_593:





[end]

msg_594:





[end]

msg_595:





[end]

msg_596:





[end]

msg_597:





[end]

msg_598:





[end]

msg_599:





[end]

msg_600:





[end]

msg_601:





[end]

msg_602:




[end]

msg_603:



[end]

msg_604:




[end]

msg_605:





[end]

msg_606:





[end]

msg_607:





[end]

msg_608:





[end]

msg_609:





[end]

msg_610:





[end]

msg_611:





[end]

msg_612:





[end]

msg_613:
[color(yellow)][var(msg_var_0)][color(white)]
 オレサマ 何カ 教エヨウト 思ッタ
 デモ 何モ 知ラナイ
 ヤッパリ 違ウモノ ヤル…
[wait][clear][end]

msg_614:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 オレサマ オマエ 契約
 オレサマ オマエ 役ダツ
[wait][clear][end]

msg_615:
 オレサマ 何スル？
[choice(4)]アイテムが欲しい
お金が欲しい
情報が欲しい
[if(CBIT_HEAR_RUMOR)]噂を流して欲しい
[end_choice][clear][end]

msg_616:
 オレサマ 何スル？
[choice(5)]アイテムが欲しい
お金が欲しい
情報が欲しい
[if(CBIT_HEAR_RUMOR)]噂を流して欲しい
[if(CBIT_HEAR_CRUSHER)][if_not(DBIT_ISEKI_KABE)]宝物庫の壁を壊して
[end_choice][clear][end]

msg_617:
 オレサマ 何スル？
[choice(5)]アイテムが欲しい
お金が欲しい
情報が欲しい
[if(CBIT_HEAR_RUMOR)]噂を流して欲しい
[if(CBIT_HEAR_BOUKUU_1)][if_not(VBIT_BOKUGO_ROCK_1)]邪魔な岩を壊して
[end_choice][clear][end]

msg_618:
 オレサマ 何スル？
[choice(5)]アイテムが欲しい
お金が欲しい
情報が欲しい
[if(CBIT_HEAR_RUMOR)]噂を流して欲しい
[if(CBIT_HEAR_BOUKUU_3)][if_not(VBIT_BOKUGO_ROCK_3)]邪魔な岩を壊して
[end_choice][clear][end]

msg_619:
 噂 言エ
[choice(3)][if(CBIT_HEAR_WEPON)]伝説の武器関連
[if(CBIT_HEAR_MAGIC)]魔法関連
特に無い
[end_choice][clear][end]

msg_620:
 噂 言エ
[choice(4)][if(CBIT_HEAR_WEPON)]伝説の武器関連
[if(CBIT_HEAR_MAGIC)]魔法関連
[if(CBIT_HEAR_MAP1)]このダンジョンの噂
特に無い
[end_choice][clear][end]

msg_621:
[color(yellow)][var(msg_var_0)][color(white)]
 アオーン！
 ソノ話 初メテ 聞ク 面白イ
 ミンナニ 教エル！
[wait][clear][end]

msg_622:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 [var(msg_var_0)] オレサマ
 オレサマ 噂 サレテル…
[wait][clear][end]

msg_623:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オマエ 噂 ナイ 手伝エナイ 残念…
 マタノ機会 期待…
[wait][clear][end]

msg_624:
[color(yellow)][var(msg_var_0)][color(white)]
 ソレ 有名 ツマラナイ
 他ノ 噂 ナイカ？
[wait][clear][end]

msg_625:
 武器 ナンダ？
[choice(6)][if(CBIT_HEAR_SWD)]伝説の日本刀
[if(CBIT_HEAR_GUN)]伝説のハンドガン
[if(CBIT_HEAR_GTR)]伝説のコイン
[if(CBIT_HEAR_FST)]伝説のグラブ
[if(CBIT_HEAR_FLW)]伝説のレイピア
やっぱりやめる
[end_choice][clear][end]

msg_626:
 ソレ 誰ノ 魔法？
[choice(6)][if(CBIT_HEAR_AGI)]ジャックランタン
[if(CBIT_HEAR_BUF)]ジャックフロスト
[if(CBIT_HEAR_GAR)]スチュパリデス
[if(CBIT_HEAR_MAG)]バルバトス
[if(CBIT_RESERVE_Ff)]他の悪魔
やっぱりやめる
[end_choice][clear][end]

msg_627:
 ソレ 誰ノ 魔法？
[choice(6)][if(CBIT_HEAR_JIO)]アンクウ
[if(CBIT_HEAR_AQU)]カナロア
[if(CBIT_HEAR_FRA)]デメテール
[if(CBIT_HEAR_MEG)]サキュバス
[if(CBIT_RESERVE_Fe)]他の悪魔
やっぱりやめる
[end_choice][clear][end]

msg_628:






[end]

msg_629:
 日本刀 ドウシタ？
[choice(4)][if(CBIT_HEAR_SWD_G)][if_not(IBIT_SWD_LGND_G)]実は最強？
[if(CBIT_HEAR_SWD_L)][if_not(IBIT_SWD_LGND_S)]隠された力がある
[if_not(IBIT_SWD_LGND_N)]やっぱり普通
[if_not(IBIT_SWD_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_630:
 ハンドガン ドウシタ？
[choice(4)][if(CBIT_HEAR_GUN_G)][if_not(IBIT_GUN_LGND_G)]実は最強？
[if(CBIT_HEAR_GUN_L)][if_not(IBIT_GUN_LGND_S)]隠された力がある
[if_not(IBIT_GUN_LGND_N)]やっぱり普通
[if_not(IBIT_GUN_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_631:
 コイン ドウシタ？
[choice(4)][if(CBIT_HEAR_GTR_G)][if_not(IBIT_CON_LGND_G)]実は最強？
[if(CBIT_HEAR_GTR_L)][if_not(IBIT_CON_LGND_S)]隠された力がある
[if_not(IBIT_CON_LGND_N)]やっぱり普通
[if_not(IBIT_CON_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_632:
 グラブ ドウシタ？
[choice(4)][if(CBIT_HEAR_FST_G)][if_not(IBIT_FST_LGND_G)]実は最強？
[if(CBIT_HEAR_FST_L)][if_not(IBIT_FST_LGND_S)]隠された力がある
[if_not(IBIT_FST_LGND_N)]やっぱり普通
[if_not(IBIT_FST_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_633:
 レイピア ドウシタ？
[choice(4)][if(CBIT_HEAR_FLW_G)][if_not(IBIT_NSW_LGND_G)]実は最強？
[if(CBIT_HEAR_FLW_L)][if_not(IBIT_NSW_LGND_S)]隠された力がある
[if_not(IBIT_NSW_LGND_N)]やっぱり普通
[if_not(IBIT_NSW_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_634:
 ジャックランタン ドウシタ？
[choice(6)][if(CBIT_HEAR_AGI_L)][if_not(BBIT_D_AGIRAO_L)]Ｄアギラオは強い
[if(CBIT_HEAR_AGI_M)][if_not(CBIT_HEAR_AGI_S)]ダイナミックアギラオを使う
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_M)]Ｄアギラオは普通
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_S)]Ｄアギラオは弱い
[if(CBIT_HEAR_AGI_C)][if_not(BBIT_D_AGIRAO_C)]Ｄアギラオは合体する
やっぱりやめる
[end_choice][clear][end]

msg_635:
 ジャックフロスト ドウシタ？
[choice(6)][if(CBIT_HEAR_BUF_L)][if_not(BBIT_A_BUFURA_L)]Ａブフーラは強い
[if(CBIT_HEAR_BUF_M)][if_not(CBIT_HEAR_BUF_S)]アトミックブフーラを使う
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_M)]Ａブフーラは普通
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_S)]Ａブフーラは弱い
[if(CBIT_HEAR_BUF_C)][if_not(BBIT_A_BUFURA_C)]Ａブフーラは合体する
やっぱりやめる
[end_choice][clear][end]

msg_636:
 スチュパリデス ドウシタ？
[choice(6)][if(CBIT_HEAR_GAR_L)][if_not(BBIT_D_GARURA_L)]Ｄガルーラは強い
[if(CBIT_HEAR_GAR_M)][if_not(CBIT_HEAR_GAR_S)]デンジャラスガルーラを使う
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_M)]Ｄガルーラは普通
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_S)]Ｄガルーラは弱い
[if(CBIT_HEAR_GAR_C)][if_not(BBIT_D_GARURA_C)]Ｄガルーラは合体する
やっぱりやめる
[end_choice][clear][end]

msg_637:
 バルバトス ドウシタ？
[choice(6)][if(CBIT_HEAR_MAG_L)][if_not(BBIT_G_MAGNAS_L)]Ｇマグナスは強い
[if(CBIT_HEAR_MAG_M)][if_not(CBIT_HEAR_MAG_S)]グレイトマグナスを使う
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_M)]Ｇマグナスは普通
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_S)]Ｇマグナスは弱い
[if(CBIT_HEAR_MAG_C)][if_not(BBIT_G_MAGNAS_C)]Ｇマグナスは合体する
やっぱりやめる
[end_choice][clear][end]

msg_638:
 アンクウ ドウシタ？
[choice(6)][if(CBIT_HEAR_JIO_L)][if_not(BBIT_H_JIONGA_L)]Ｈジオンガは強い
[if(CBIT_HEAR_JIO_M)][if_not(CBIT_HEAR_JIO_S)]ハイパージオンガを使う
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_M)]Ｈジオンガは普通
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_S)]Ｈジオンガは弱い
[if(CBIT_HEAR_JIO_C)][if_not(BBIT_H_JIONGA_C)]Ｈジオンガは合体する
やっぱりやめる
[end_choice][clear][end]

msg_639:
 カナロア ドウシタ？
[choice(6)][if(CBIT_HEAR_AQU_L)][if_not(BBIT_W_AQUES_L)]Ｗアクエスは強い
[if(CBIT_HEAR_AQU_M)][if_not(CBIT_HEAR_AQU_S)]ワンダフルアクエスを使う
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_M)]Ｗアクエスは普通
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_S)]Ｗアクエスは弱い
[if(CBIT_HEAR_AQU_C)][if_not(BBIT_W_AQUES_C)]Ｗアクエスは合体する
やっぱりやめる
[end_choice][clear][end]

msg_640:
 デメテール ドウシタ？
[choice(6)][if(CBIT_HEAR_FRA_L)][if_not(BBIT_U_FRAIRA_L)]Ｕフレイラは強い
[if(CBIT_HEAR_FRA_M)][if_not(CBIT_HEAR_FRA_S)]ウルトラフレイラを使う
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_M)]Ｕフレイラは普通
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_S)]Ｕフレイラは弱い
[if(CBIT_HEAR_FRA_C)][if_not(BBIT_U_FRAIRA_C)]Ｕフレイラは合体する
やっぱりやめる
[end_choice][clear][end]

msg_641:
 サキュバス ドウシタ？
[choice(6)][if(CBIT_HEAR_MEG_L)][if_not(BBIT_C_MEGIDO_L)]超メギドは強い
[if(CBIT_HEAR_MEG_M)][if_not(CBIT_HEAR_MEG_S)]超メギドを使う
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_M)]超メギドは普通
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_S)]超メギドは弱い
[if(CBIT_HEAR_MEG_C)][if_not(BBIT_C_MEGIDO_C)]超メギドは合体する
やっぱりやめる
[end_choice][clear][end]

msg_642:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 知ッテル [color(orange)]ヘッポコ日本刀[color(white)]
 言イフラス オマエ 困ル ザマアミロ…
[wait][clear][end]

msg_643:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 知ッテル [color(orange)]ヘッポコ銃[color(white)]
 言イフラス オマエ 困ル ザマアミロ…
[wait][clear][end]

msg_644:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 知ッテル [color(orange)]ヘッポコ コイン[color(white)]
 言イフラス オマエ 困ル ザマアミロ…
[wait][clear][end]

msg_645:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 知ッテル [color(orange)]ヘッポコ グラブ[color(white)]
 言イフラス オマエ 困ル ザマアミロ…
[wait][clear][end]

msg_646:
[color(yellow)][var(msg_var_0)][color(white)]
 グゥ…
 オレサマ 知ッテル [color(orange)]ヘッポコ レイピア[color(white)]
 言イフラス オマエ 困ル ザマアミロ…
[wait][clear][end]

msg_647:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 壊ス！
 オマエ 喜ブ！
[wait][clear][end]

msg_648:
[color(yellow)][var(msg_var_0)][color(white)]
 ヌゥ…
 オレサマ 人間 ヒサシブリ！
[wait][clear][end]

msg_649:
[color(green)]選択肢ジャンプの挙動エラーです[color(white)]
[end]
