
msg_0:
[end]

msg_1:
[end]

msg_2:
[end]

msg_3:
[end]

msg_4:
[end]

msg_5:
[end]

msg_6:
[end]

msg_7:
[end]

msg_8:
[end]

msg_9:
[end]

msg_10:
[end]

msg_11:
[end]

msg_12:
[color(yellow)][var(msg_var_0)][color(white)]
 それってやっぱりぃ、
 あたしニンキモノってことぉ？
[wait][clear][end]

msg_13:
[color(yellow)][var(msg_var_0)][color(white)]
 やぁだ～困っちゃう～♥
 なぁんの雑誌ですかぁ？
 超ドキドキするぅ！
[wait][clear][end]

msg_14:
[color(yellow)][var(msg_var_0)][color(white)]
 うんうん、わかるよぉ♥
 あたし、カワイイからしょーがないよネ！
[wait][clear][end]

msg_15:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしのコト、そ～んなに気になるぅ？
[wait][clear][end]

msg_16:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしみたいになりたいのぉ～？
 ム・リ・デ・ス♥
[wait][clear][end]

msg_17:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 じゃあ、とっておきのヒミツぅ！
 あたし、恋人ボシューチューなのぉ～！
[wait][clear][end]

msg_18:
[color(yellow)][var(msg_var_0)][color(white)]
 超キモー！
 あんたダレ？ ストーカー？
 フザけてっと、マジ殺すよぉ？
[wait][clear][end]

msg_19:
[color(yellow)][var(msg_var_0)][color(white)]
 超ムカツクぅ！
 ヘンな雑誌だったら殺すからねっ！
[wait][clear][end]

msg_20:
[color(yellow)][var(msg_var_0)][color(white)]
 うっさいなぁ！
 超なれなれしーんだよ！
[wait][clear][end]

msg_21:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 ストーカーじゃないよねぇ…？
[wait][clear][end]

msg_22:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたし、なにされちゃうんだろ…
 マジ帰りたい…
[wait][clear][end]

msg_23:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 なんか企んでんのぉ…？
[wait][clear][end]

msg_24:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、それ知ってる！
 うちらの間でも、今ハヤってるよぉ！
[wait][clear][end]

msg_25:
[color(yellow)][var(msg_var_0)][color(white)]
 ねぇねぇ、もしかして、ユーメーな占い師？
 サインほしいな～！
 …ダメ？
[wait][clear][end]

msg_26:
[color(yellow)][var(msg_var_0)][color(white)]
 そんなのより、死んだおじいちゃん呼んでよ！
 あ、そーゆーのじゃないんだ…
[wait][clear][end]

msg_27:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 当たってるかも～！
[wait][clear][end]

msg_28:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 おねーさん、超ヤバイって！
[wait][clear][end]

msg_29:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超当たってるぅ！
[wait][clear][end]

msg_30:
[color(yellow)][var(msg_var_0)][color(white)]
 ちょっとちょっとぉ！
 勝手にヘンなコトしないでよぉ！
 誰も許可してないでしょぉ？
[wait][clear][end]

msg_31:
[color(yellow)][var(msg_var_0)][color(white)]
 寝言は死んでから言ってよね！
[wait][clear][end]

msg_32:
[color(yellow)][var(msg_var_0)][color(white)]
 はぁ？
 あたし的に超ツマンナイんですけどぉ？
 時間とらせないでくれるぅ？
[wait][clear][end]

msg_33:
[color(yellow)][var(msg_var_0)][color(white)]
 やだぁ…
 なんか憑いちゃってるよ…
 こっち来ないでネ！
[wait][clear][end]

msg_34:
[color(yellow)][var(msg_var_0)][color(white)]
 人間に占われるってブキミ…
[wait][clear][end]

msg_35:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なに…？
 なんかキマっちゃってんの…？
[wait][clear][end]

msg_36:
[color(yellow)][var(msg_var_0)][color(white)]
 へぇ～！
 マジで刑事！？
 いっつもそぉやって口割らせてるワケ？
[wait][clear][end]

msg_37:
[color(yellow)][var(msg_var_0)][color(white)]
 えぇ？ なに？ ドラマかなんかぁ？
 あたし、もしかして犯人役なのぉ？
 もぉ～早く言ってよぉ！
[wait][clear][end]

msg_38:
[color(yellow)][var(msg_var_0)][color(white)]
 いいなぁ～！
 刑事ってあこがれるぅ！
 ちっちゃい頃なりたかったんだよねぇ！
[wait][clear][end]

msg_39:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あんたの頭ン中の方が
 よっぽど犯罪だって！
[wait][clear][end]

msg_40:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 なに勝手に話し進めちゃってんのぉ？
 目ぇイっちゃってない？
[wait][clear][end]

msg_41:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 頭ン中、ど～なってんのぉ？
[wait][clear][end]

msg_42:
[color(yellow)][var(msg_var_0)][color(white)]
 超ムカー！
 勝手に進めないでよぉ！
 あたし台本もらってないよぉ？
[wait][clear][end]

msg_43:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしを犯人にして、事件解決ぅ？
 さっすが、エリートさんは違うねぇ～！
[wait][clear][end]

msg_44:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なによぉ…
 あ、あたし、そんな女知らない…
[wait][clear][end]

msg_45:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 あんたには、関わりたくない…
 そんな女、知らないったら…
[wait][clear][end]

msg_46:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なによぉ…
 あたしは犯人じゃないし…
 そ、そんな女も知らないもん！
[wait][clear][end]

msg_47:
[color(yellow)][var(msg_var_0)][color(white)]
 おにーさん、ホントは悪魔じゃないのぉ？
[wait][clear][end]

msg_48:
[color(yellow)][var(msg_var_0)][color(white)]
 人間のクセに、超ヒキョー！
 ミコミあるじゃん！
[wait][clear][end]

msg_49:
[color(yellow)][var(msg_var_0)][color(white)]
 自分の声ってさぁ、
 ジッサイ聞くと超ヘンだよねぇ！
[wait][clear][end]

msg_50:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 それ、あたしじゃないよぉ！
[wait][clear][end]

msg_51:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしならぁ、もぉ～っと
 スゴイコトしちゃうのになぁ～！
[wait][clear][end]

msg_52:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 乙女のピーンチ！
[wait][clear][end]

msg_53:
[color(yellow)][var(msg_var_0)][color(white)]
 言いたいコトあんなら、ハッキリ言えばぁ？
[wait][clear][end]

msg_54:
[color(yellow)][var(msg_var_0)][color(white)]
 超超ユルせない～っ！
 マジ殺すんだから！
[wait][clear][end]

msg_55:
[color(yellow)][var(msg_var_0)][color(white)]
 超サイアクぅ！
 マジ死んで！
 つーか殺すッ！
[wait][clear][end]

msg_56:
[color(yellow)][var(msg_var_0)][color(white)]
 カネなら持ってないよぉ…
[wait][clear][end]

msg_57:
[color(yellow)][var(msg_var_0)][color(white)]
 そ、そんなコト言われても…
 あたし、こー見えても悪魔だもん…
 悪いコトしてて、トーゼンなんだもん…
[wait][clear][end]

msg_58:
[color(yellow)][var(msg_var_0)][color(white)]
 新しいシューキョー？
[wait][clear][end]

msg_59:
[color(yellow)][var(msg_var_0)][color(white)]
 清き１票を～よろしくおねがいしまぁす！
 ってヤツでしょぉ！
[wait][clear][end]

msg_60:
[color(yellow)][var(msg_var_0)][color(white)]
 えぇ～っ！
 もしかして、ユーメージン！？
 誰か知らないけどぉ、サインくださぁい♥
[wait][clear][end]

msg_61:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 そんなコト言ってっと、
 すぅぐハゲちゃうよぉ？
[wait][clear][end]

msg_62:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 さっすが、イイとこ育ちは
 言うコト違うネェ～！
[wait][clear][end]

msg_63:
[color(yellow)][var(msg_var_0)][color(white)]
 うっさいなぁ！
 そぉんなの、全ッ然キョーミないのっ！
[wait][clear][end]

msg_64:
[color(yellow)][var(msg_var_0)][color(white)]
 お、落ちついて、ね？ ね？
[wait][clear][end]

msg_65:
[color(yellow)][var(msg_var_0)][color(white)]
 こわぁぃ…
 張りきんないでよぉ…
[wait][clear][end]

msg_66:
[color(yellow)][var(msg_var_0)][color(white)]
 超カッコイ～♥
[wait][clear][end]

msg_67:
[color(yellow)][var(msg_var_0)][color(white)]
 超おもしろそぉ！
 あたしにもやらして！
[wait][clear][end]

msg_68:
[color(yellow)][var(msg_var_0)][color(white)]
 化粧うまくない？
[wait][clear][end]

msg_69:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 意外とケバいよねぇ？
[wait][clear][end]

msg_70:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしの方が、絶対サマになるって！
[wait][clear][end]

msg_71:
[color(yellow)][var(msg_var_0)][color(white)]
 そんぐらいでイバんないでよぉ！
[wait][clear][end]

msg_72:
[color(yellow)][var(msg_var_0)][color(white)]
 だからなんなワケェ？
[wait][clear][end]

msg_73:
[color(yellow)][var(msg_var_0)][color(white)]
 超つまんない！！
[wait][clear][end]

msg_74:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なんか超アヤシー…
[wait][clear][end]

msg_75:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、うん…ス、スゴイね…
[wait][clear][end]

msg_76:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なにが始まっちゃうのかなぁ…
[wait][clear][end]

msg_77:
[color(yellow)][var(msg_var_0)][color(white)]
 人間の男かぁ…
 どうしよっかな～♥
[wait][clear][end]

msg_78:
[color(yellow)][var(msg_var_0)][color(white)]
 ちょーどカレシいないんだよね！
[wait][clear][end]

msg_79:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 な～んかドキドキしちゃうよぉ！
[wait][clear][end]

msg_80:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 や～っぱあたしってモテちゃうんだよねぇ！
[wait][clear][end]

msg_81:
[color(yellow)][var(msg_var_0)][color(white)]
 ガンくれてんじゃねーよっ！
[wait][clear][end]

msg_82:
[color(yellow)][var(msg_var_0)][color(white)]
 あんたなんかシュミじゃないのっ！
[wait][clear][end]

msg_83:
[color(yellow)][var(msg_var_0)][color(white)]
 キ、キモチ悪ぅい…
[wait][clear][end]

msg_84:
[color(yellow)][var(msg_var_0)][color(white)]
 チ、チカンかなぁ…
[wait][clear][end]

msg_85:
[color(yellow)][var(msg_var_0)][color(white)]
 ニラまないでよぉ…
[wait][clear][end]

msg_86:
[color(yellow)][var(msg_var_0)][color(white)]
 ひょっとして、ナンパぁ？
 やぁだ～困っちゃう～♥
[wait][clear][end]

msg_87:
[color(yellow)][var(msg_var_0)][color(white)]
 なぁに？ なんかのアンケート？
[wait][clear][end]

msg_88:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしに気があんのぉ？
[wait][clear][end]

msg_89:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしに意見求めるなんて
 見る目あるじゃん！
[wait][clear][end]

msg_90:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 絶対あたしの方がカワイイって！
[wait][clear][end]

msg_91:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしがイチバンに決まってんじゃん！
[wait][clear][end]

msg_92:
[color(yellow)][var(msg_var_0)][color(white)]
 はぁ？
 あたしの５万倍くらいブッサイクのくせに
 なに言ってんのぉ？
[wait][clear][end]

msg_93:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 そういうシュミないんだよねぇ…
[wait][clear][end]

msg_94:
[color(yellow)][var(msg_var_0)][color(white)]
 ヘントー次第じゃ殺されちゃうかも…
[wait][clear][end]

msg_95:
[color(yellow)][var(msg_var_0)][color(white)]
 悩みぃ？
 んーそぉだなぁ…別にないよぉ？
[wait][clear][end]

msg_96:
[color(yellow)][var(msg_var_0)][color(white)]
 おねーさん、聞いてくれるぅ？
 あ、あたしさぁ、実はね…
 …なぁんて、別に悩みないんだよねぇ。
[wait][clear][end]

msg_97:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしが気になるのはわかるけどぉ、
 しつっこいとキラっちゃうよぉ？
[wait][clear][end]

msg_98:
[color(yellow)][var(msg_var_0)][color(white)]
 バッカじゃないのぉ？
[wait][clear][end]

msg_99:
[color(yellow)][var(msg_var_0)][color(white)]
 人間のクセにチョーシのんないでよねっ！
[wait][clear][end]

msg_100:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、それって何の雑誌ぃ～？
 あたし買おっかなぁ～！
[wait][clear][end]

msg_101:
[color(yellow)][var(msg_var_0)][color(white)]
 なになにぃ？ その人の特集組んじゃうのぉ？
 んもぉ～、あたしの特集にしときなって！
 超売れるよぉ、マジで！
[wait][clear][end]

msg_102:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超イイねぇ～その真剣な顔ぉ！
[wait][clear][end]

msg_103:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 なぁに熱くなっちゃってんのぉ？
 超笑えるぅ～！
[wait][clear][end]

msg_104:
[color(yellow)][var(msg_var_0)][color(white)]
 サムイから死んで？
[wait][clear][end]

msg_105:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたしのコト、完全ムシ？
[wait][clear][end]

msg_106:
[color(yellow)][var(msg_var_0)][color(white)]
 へぇ～！
 おねーさん、それ結構スゴイよ！
 ………あ、フラメンコだったの！？
[wait][clear][end]

msg_107:
[color(yellow)][var(msg_var_0)][color(white)]
 も一回やって！
 今度踊りに行く約束あるから、
 それ覚えたいな！
[wait][clear][end]

msg_108:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 ストレスたまってんのぉ？
[wait][clear][end]

msg_109:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 すごいすご～い！
[wait][clear][end]

msg_110:
[color(yellow)][var(msg_var_0)][color(white)]
 あーもう、超メーワクぅ！
 目ェくさるっつーの！
[wait][clear][end]

msg_111:
[color(yellow)][var(msg_var_0)][color(white)]
 もっと泣かせるコト言ってみてよぉ！
[wait][clear][end]

msg_112:
[color(yellow)][var(msg_var_0)][color(white)]
 うっわ～！
 刑事ドラマっぽ～い！
 あ、ひょっとしてマジで刑事だったり？
[wait][clear][end]

msg_113:
[color(yellow)][var(msg_var_0)][color(white)]
 なんかドラマみた～い！
 スミマセンでしたオヤッサン…
 …ホラァ！ 続き言ってよぉ～！
[wait][clear][end]

msg_114:
[color(yellow)][var(msg_var_0)][color(white)]
 意外とアタマいいんだね～！
 今度カテキョーしてよ！
[wait][clear][end]

msg_115:
[color(yellow)][var(msg_var_0)][color(white)]
 人間って、いっつもそんなコト考えてるのぉ？
[wait][clear][end]

msg_116:
[color(yellow)][var(msg_var_0)][color(white)]
 へぇ～！
 そんなの、考えたコトもなかったなぁ。
 悪魔の正義についても、考えといてよ！
[wait][clear][end]

msg_117:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 正義だって！ 英雄だね英雄！
 エラソーなのもここまでくるとソンケーだよ！
[wait][clear][end]

msg_118:
[color(yellow)][var(msg_var_0)][color(white)]
 キョーダイでカッコイイなんて
 なんかちょっと得したカンジ！
[wait][clear][end]

msg_119:
[color(yellow)][var(msg_var_0)][color(white)]
 で？ ど～ゆう結末？
 あれ、ドラマじゃなかったの？
[wait][clear][end]

msg_120:
[color(yellow)][var(msg_var_0)][color(white)]
 なに？ おままごと？
 あたしもやりたいナー！
[wait][clear][end]

msg_121:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 なんかのドラマみたい！
 続き見た～い！
[wait][clear][end]

msg_122:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 人間って、超ヘ～ン！
[wait][clear][end]

msg_123:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 も～大人でしょぉ？
[wait][clear][end]

msg_124:
[color(yellow)][var(msg_var_0)][color(white)]
 超イライラする！！
[wait][clear][end]

msg_125:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしが言うのもナンだけどさぁ！
 自分のコト心配してるヒトに、
 それはないんじゃないのぉ？
[wait][clear][end]

msg_126:
[color(yellow)][var(msg_var_0)][color(white)]
 こんなウルサイお兄ちゃん
 いたらヤだなぁ…
[wait][clear][end]

msg_127:
[color(yellow)][var(msg_var_0)][color(white)]
 きょ、兄弟なんだよね…
 単なる兄弟愛にしちゃ、行き過ぎてない…？
[wait][clear][end]

msg_128:
[color(yellow)][var(msg_var_0)][color(white)]
 人間の作ったサケはおいしいのかなぁ…
[wait][clear][end]

msg_129:
[color(yellow)][var(msg_var_0)][color(white)]
 おねーさん、酔うと変わりそーだねぇ？
[wait][clear][end]

msg_130:
[color(yellow)][var(msg_var_0)][color(white)]
 サケって、どこがおいしいのぉ？
[wait][clear][end]

msg_131:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 人間のサケって、なんかおもしろそ～！
[wait][clear][end]

msg_132:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 「サケ好きはバカ」って名言、知らないのぉ？
 あ、あたしが言ったんだけどネ！
[wait][clear][end]

msg_133:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 人間のサケ、ちょっと飲んでみたいナー！
[wait][clear][end]

msg_134:
[color(yellow)][var(msg_var_0)][color(white)]
 サケなんか超マズイじゃん！
 …って今！ あたしのコト、
 ガキだと思ったでしょぉっ！
[wait][clear][end]

msg_135:
[color(yellow)][var(msg_var_0)][color(white)]
 おにーさんたち、酔ったら怖そぉ…
[wait][clear][end]

msg_136:
[color(yellow)][var(msg_var_0)][color(white)]
 サケ飲めないのは、やっぱガキかなぁ…
[wait][clear][end]

msg_137:
[color(yellow)][var(msg_var_0)][color(white)]
 …野球って、５人でやるんだっけ？
[wait][clear][end]

msg_138:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしは宙日ドラガンズだなぁ～！
 あ、ない？
[wait][clear][end]

msg_139:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なに？
 酔ってんの…？
[wait][clear][end]

msg_140:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしも、も～ちょいオトナになったら
 わかんのかなぁ？
[wait][clear][end]

msg_141:
[color(yellow)][var(msg_var_0)][color(white)]
 どぉしてこんなに
 ヒネくれちゃったかなぁ？
 このヒトはぁ。
[wait][clear][end]

msg_142:
[color(yellow)][var(msg_var_0)][color(white)]
 ふぅ～ん、そ～ゆうもん？
[wait][clear][end]

msg_143:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 な～んか超ニゲ入ってな～い？
[wait][clear][end]

msg_144:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 な～んか、オトナってズルイねぇ！
[wait][clear][end]

msg_145:
[color(yellow)][var(msg_var_0)][color(white)]
 ちょっとちょっとぉ！
 なにムシしてんのぉ？
 ５万年早いよマジ！
[wait][clear][end]

msg_146:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なんかオトナになりたくないなぁ…
[wait][clear][end]

msg_147:
[color(yellow)][var(msg_var_0)][color(white)]
 オトナってタイヘンそぉ…
[wait][clear][end]

msg_148:
[color(yellow)][var(msg_var_0)][color(white)]
 えっ、なに？ テレビ？ サツエー中？
 あたし、映っちゃう～？
 やぁだ、マユかいてないのにぃ～！
[wait][clear][end]

msg_149:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしもトーロンしたぁい！
[wait][clear][end]

msg_150:
[color(yellow)][var(msg_var_0)][color(white)]
 テレビカメラ、どこぉ？
[wait][clear][end]

msg_151:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 頭イイあたしに聞きたい気持ちは
 よぉ～くわかるよぉ！
[wait][clear][end]

msg_152:
[color(yellow)][var(msg_var_0)][color(white)]
 全ッ然、意味わかんないんだけどぉ？
 あたしのコト、バカにしてない？
[wait][clear][end]

msg_153:
[color(yellow)][var(msg_var_0)][color(white)]
 な、何語しゃべってんのぉ…？
[wait][clear][end]

msg_154:
[color(yellow)][var(msg_var_0)][color(white)]
 ニヒルなんて、も～ウケないよぉ？
[wait][clear][end]

msg_155:
[color(yellow)][var(msg_var_0)][color(white)]
 ひ、ひどぉい…
[wait][clear][end]

msg_156:
[color(yellow)][var(msg_var_0)][color(white)]
 わかるわかる～！
[wait][clear][end]

msg_157:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 じゃあ働かなきゃイイじゃん！
[wait][clear][end]

msg_158:
[color(yellow)][var(msg_var_0)][color(white)]
 そぉんなコト言ってっから
 モテないんだって！
[wait][clear][end]

msg_159:
[color(yellow)][var(msg_var_0)][color(white)]
 そ～そ～！ 男って、ウザくな～い？
[wait][clear][end]

msg_160:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 それは、おねーさんたちが
 モテないだけでしょぉ！
[wait][clear][end]

msg_161:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 そぉんなコト言ってっと、すぐババァだよぉ？
 ていうか、すでに？
[wait][clear][end]

msg_162:
[color(yellow)][var(msg_var_0)][color(white)]
 ギャーギャーうるさいなぁ！
 黙らしてあげよっかぁ？
[wait][clear][end]

msg_163:
[color(yellow)][var(msg_var_0)][color(white)]
 バイト？
 時給いくらもらってんの？
[wait][clear][end]

msg_164:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしも王子サマ欲し～い！
[wait][clear][end]

msg_165:
[color(yellow)][var(msg_var_0)][color(white)]
 人間のキョーダイって、そんななんだぁ。
[wait][clear][end]

msg_166:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 こぉんなトコで、なに語り入ってんのぉ？
[wait][clear][end]

msg_167:
[color(yellow)][var(msg_var_0)][color(white)]
 な～んか、おにーさんカワイイ♥
[wait][clear][end]

msg_168:
[color(yellow)][var(msg_var_0)][color(white)]
 そ～ゆうコトしてて
 よく恥ずかしくないねぇ～？
[wait][clear][end]

msg_169:
[color(yellow)][var(msg_var_0)][color(white)]
 それでフェロモン出してるつもりぃ？
 言っとくけどぉ、昆虫以下っ！
[wait][clear][end]

msg_170:
[color(yellow)][var(msg_var_0)][color(white)]
 いいヤツ紹介したげるよ！
 悪魔だけど、別にいいでしょ？
[wait][clear][end]

msg_171:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 おねーさんもさぁ、若いってコトしか
 武器ないんだから、アセったほうがイイよ！
[wait][clear][end]

msg_172:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしだったら、おねーさんと
 結婚したくな～い♥
[wait][clear][end]

msg_173:
[color(yellow)][var(msg_var_0)][color(white)]
 あんたじゃ結婚できるワケないじゃん！
 ちょっとはカガミ見たらぁ？
[wait][clear][end]

msg_174:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたしを選ばないでね…
[wait][clear][end]

msg_175:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたしはダメだからね！
 カネもないし！ 家もないし！ ね？
[wait][clear][end]

msg_176:
[color(yellow)][var(msg_var_0)][color(white)]
 ふだん、ヤなコトばっかなのかなぁ？
[wait][clear][end]

msg_177:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超楽しそぉ！
 あたしも飲めればなぁ～！
[wait][clear][end]

msg_178:
[color(yellow)][var(msg_var_0)][color(white)]
 酔っ払い、超キライ！
 クサイし吐くしワケわかんないしぃ！
 もぉ～とにかくぅ、ヤなのぉっ！
[wait][clear][end]

msg_179:
[color(yellow)][var(msg_var_0)][color(white)]
 の、飲まされちゃうのかなぁ…
[wait][clear][end]

msg_180:
[color(yellow)][var(msg_var_0)][color(white)]
 悪口大会～？
 あたしも混ぜてよぉ！
 超ムカツク人間がいるんだもん！
[wait][clear][end]

msg_181:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 悪口言ってっとぉ
 ますますブサイクになっちゃうよぉ？
[wait][clear][end]

msg_182:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしのコト指してぇ、
 「オバケが出たぁ！」なんて
 オチじゃないよねぇ？
[wait][clear][end]

msg_183:
[color(yellow)][var(msg_var_0)][color(white)]
 う、うしろにダレかいるぅ！
[wait][clear][end]

msg_184:
[end]

msg_185:
[end]

msg_186:
[end]

msg_187:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 やれるもんなら、やってみな～！
[wait][clear][end]

msg_188:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 な～んか、おもしろくなってきたねぇ！
[wait][clear][end]

msg_189:
[color(yellow)][var(msg_var_0)][color(white)]
 ヨワっちークセに、なに言ってんのぉ？
 殺してあげるから、会ってきなっ！
[wait][clear][end]

msg_190:
[color(yellow)][var(msg_var_0)][color(white)]
 ちょ、ちょっと待ってよぉ～！
[wait][clear][end]

msg_191:
[color(yellow)][var(msg_var_0)][color(white)]
 い、いいって！
 エンリョしとくよぉ…
[wait][clear][end]

msg_192:
[end]

msg_193:
[end]

msg_194:
[end]

msg_195:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 安心しなよ、す～ぐ会わせてあげるって！
[wait][clear][end]

msg_196:
[color(yellow)][var(msg_var_0)][color(white)]
 イヤミっぽいなぁ！
[wait][clear][end]

msg_197:
[color(yellow)][var(msg_var_0)][color(white)]
 後追わせてあげようかぁ？
[wait][clear][end]

msg_198:
[color(yellow)][var(msg_var_0)][color(white)]
 メソメソしちゃって超キモいんだよ！
[wait][clear][end]

msg_199:
[color(yellow)][var(msg_var_0)][color(white)]
 こ、こーゆぅの、苦手なんだよネ…
[wait][clear][end]

msg_200:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたし悪者…？
[wait][clear][end]

msg_201:
[end]

msg_202:
[end]

msg_203:
[end]

msg_204:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 ひたってる場合じゃないんじゃないのぉ？
[wait][clear][end]

msg_205:
[color(yellow)][var(msg_var_0)][color(white)]
 こんぐらいで死ぬヤツだったってだけでしょぉ？
[wait][clear][end]

msg_206:
[color(yellow)][var(msg_var_0)][color(white)]
 し、死人と話しできんの…？
[wait][clear][end]

msg_207:
[end]

msg_208:
[end]

msg_209:
[end]

msg_210:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 うちら、気が合いそぉ！
[wait][clear][end]

msg_211:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 やっぱカゲグチたたいてるときって
 超シアワセ感じない？
[wait][clear][end]

msg_212:
[color(yellow)][var(msg_var_0)][color(white)]
 超カンジわるーい！！
[wait][clear][end]

msg_213:
[color(yellow)][var(msg_var_0)][color(white)]
 なんか超エラソーじゃない？
 あんたも殺してあげるよ！
[wait][clear][end]

msg_214:
[color(yellow)][var(msg_var_0)][color(white)]
 そ、そこまで言うことないじゃん…
 このヒトなりによくやったって！ ね？
[wait][clear][end]

msg_215:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、悪魔だって、そこまでひどくないよぉ…
[wait][clear][end]

msg_216:
[end]

msg_217:
[end]

msg_218:
[end]

msg_219:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超ダッサー！
 ブシドー精神はどこいっちゃったのぉ？
[wait][clear][end]

msg_220:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 どぉ～しよっかなぁ～！
[wait][clear][end]

msg_221:
[color(yellow)][var(msg_var_0)][color(white)]
 いまさらナニ言ってんのぉ？
 このヒト超ムカツク！！
[wait][clear][end]

msg_222:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 何のマネ…？
[wait][clear][end]

msg_223:
[color(yellow)][var(msg_var_0)][color(white)]
 ねえねえ、それで、なんかキャッチみたいの
 つけてくれんでしょ？
 「超人気の[var(msg_var_0)]さん！」とかさぁ！
[wait][clear][end]

msg_224:
 なんの「[var(msg_var_0)]さん」？
[choice(3)]「ファッションリーダーの」
「ハイテクメカの」
「カリスマ悪魔の」
[end_choice][clear][end]

msg_225:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 みんな、あたしがモクヒョー？
 ま、トーゼンだよネ！
[wait][clear][end]

msg_226:
[color(yellow)][var(msg_var_0)][color(white)]
 え、マジでぇ！？
 その特集、超おもしろそぉ～！
[wait][clear][end]

msg_227:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 なにそれ～？ センスなくない？
 あたしが考えたげよっかぁ？
[wait][clear][end]

msg_228:
[color(yellow)][var(msg_var_0)][color(white)]
 はぁ？
 いまさらカリスマぁ？
 何世紀前の雑誌なワケェ！？
[wait][clear][end]

msg_229:
[color(yellow)][var(msg_var_0)][color(white)]
 悩みとかって、よくわかんないなぁ。
 だいたい悪魔に悩みって、似合わなくない？
 人間は、そのへん、どーなの？
[wait][clear][end]

msg_230:
 おにーさんは、どんなことで悩むの？
[choice(3)]僕の悩みは家族の事が多いな…
恋の悩みだ…
仕事上の悩みは尽きないよ…
[end_choice][clear][end]

msg_231:
[color(yellow)][var(msg_var_0)][color(white)]
 んー、そーだなぁ…
 「どっちも好みじゃないです」 以上！
 ホラ！ 早くちょ～だい！
[wait][clear][end]

msg_232:
 答えてあげた、お・れ・い♥
[choice(3)]ポ、ポケットティッシュでいい？
特製ストラップを差し上げま～す！
は、発表は、発送を持って…なんちゃって！
[end_choice][clear][end]

msg_233:
[color(yellow)][var(msg_var_0)][color(white)]
 あっ、これ、あたしの人形がついてる～！！
 やだぁ～超カワイイ♥
 おねーさん、ありがとね！
[wait][clear][end]

msg_234:
[color(yellow)][var(msg_var_0)][color(white)]
 つまんないなぁ！
 そんなの死ぬほど持ってるよぉ！
[wait][clear][end]

msg_235:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 悪魔がイチバン喜ぶもの、持ってんじゃん！
 体だよ、か・ら・だ！
[wait][clear][end]

msg_236:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしだったら、絶対できな～い！
 ハジライあるしぃ、そんな面の皮あつくないしね！
[wait][clear][end]

msg_237:
 おねーさんのこと、ソンケーしちゃう！
[choice(3)]お、サンキュ！
まぁ、アンタじゃ誘惑にならんでしょ…
交渉だから仕方ないのよねぇ…
[end_choice][clear][end]

msg_238:
[color(yellow)][var(msg_var_0)][color(white)]
 イヤミのつもり？
 ５万年早いんだよ！
[wait][clear][end]

msg_239:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたし、そんなコトしなくっても
 モテるんだも～ん♥
[wait][clear][end]

msg_240:
[color(yellow)][var(msg_var_0)][color(white)]
 利益のためだったらなんだってするんだね…
 こわぁぃ…
[wait][clear][end]

msg_241:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、写真とってないのか…
 な～んだ…後ろにあたし写ってたりしたら、
 それがキッカケでデビューとかさぁ…
[wait][clear][end]

msg_242:
 ね、おねーさんにそんなケンリョクないの？
[choice(3)]任せといて！
ええ、残念だけど…
あなたがデビュー？
[end_choice][clear][end]

msg_243:
[color(yellow)][var(msg_var_0)][color(white)]
 えっウソ！ マジでぇ～！？
[wait][clear][end]

msg_244:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 おねーさん、仕事できなさそーだもんね！
[wait][clear][end]

msg_245:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なによぅ…
 も、もうちょっとヤセるったら！
[wait][clear][end]

msg_246:
 ね、ね、あたしも刑事役がいい～！
[choice(3)]コンビでも組むか？
ならば僕が犯人役になろう…
指紋採る役くらいなら任せても良いが…
[end_choice][clear][end]

msg_247:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 タイホしたらソッコー死刑♥
 ガンバって逃げてね～！
[wait][clear][end]

msg_248:
[color(yellow)][var(msg_var_0)][color(white)]
 え、マジでぇ！？
 あの粉はたくの、やってみたかったんだ！
 ムセないよう、がんばりま～す♥
[wait][clear][end]

msg_249:
[color(yellow)][var(msg_var_0)][color(white)]
 じゃあさ、じゃあさぁ！
 署内でのニックネームみたいの、あんの？
 「半ズボン」とか「忍者」とか！
[wait][clear][end]

msg_250:
 ニックネーム、なぁに？
[choice(4)]メガネ
長さん
内緒
そんなものない
[end_choice][clear][end]

msg_251:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 なにそれ～？ 超ヤバイって！
[wait][clear][end]

msg_252:
[color(yellow)][var(msg_var_0)][color(white)]
 超知りたーい！
 んーんー、……わかった！
 「バンビ」でしょぉ？
[wait][clear][end]

msg_253:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超カワイソー！ あたしが付けたげるよぉ！
 そーだなー、……「トム」でどぉ？
[wait][clear][end]

msg_254:
[color(yellow)][var(msg_var_0)][color(white)]
 ウソつきっ！
 超ムカツクよぉ！
[wait][clear][end]

msg_255:
 カテキョー、してくれるぅ？
[choice(3)]フン、良かろう！
断固として断る！
カテキョーとは何だ？
[end_choice][clear][end]

msg_256:
[color(yellow)][var(msg_var_0)][color(white)]
 鼻の下のばしちゃって、バッカじゃないのぉ？
 ジョーダンに決まってんでしょ！
 チョーシにのんないでよね！
[wait][clear][end]

msg_257:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なによぅ…
 ちゃ、ちゃんと勉強するったら！
[wait][clear][end]

msg_258:
[color(yellow)][var(msg_var_0)][color(white)]
 そーいえば、最近ドラマつまんなくない？
 あたしが出れば、ソッコー
 シチョーリツ上がんのに…
[wait][clear][end]

msg_259:
 そしたらさ、おにーさんは何の役がいい？
[choice(3)]温かい家族の役だな
優しい恋人の役だな
可愛い犬の役だな
[end_choice][clear][end]

msg_260:
[color(yellow)][var(msg_var_0)][color(white)]
 そ～ゆうのは、できないのぉ？
 あたし、死んだおじいちゃんに
 会いたいんだけど…
[wait][clear][end]

msg_261:
 おじいちゃんに、会わせてよぉ～！
[choice(3)]殺してあげるから、あの世で会っといで！
アラ？アンタの後ろにいるじゃない？
ホイホイ、じいちゃんぢゃよぉ～！
[end_choice][clear][end]

msg_262:
[color(yellow)][var(msg_var_0)][color(white)]
 えっマジ！？
 あたしを守ってくれてるってコト？
[wait][clear][end]

msg_263:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 背中になんか気配感じるぅ…
[wait][clear][end]

msg_264:
 で、おねーさん的には男のどこ重視？
[choice(3)]やっぱ顔よねぇ…
将来を考えたら経済力かな？
ハートよ、は・あ・と！
[end_choice][clear][end]

msg_265:
[color(yellow)][var(msg_var_0)][color(white)]
 そ、そんなコト言える顔かぁ…？
[wait][clear][end]

msg_266:
 そのヘンなヤツ、続き踊ってよ！
[choice(3)]後でみっちり教えてア・ゲ・ル！
エーッ、ヤダって！
ゴメン、足くじいちゃって…
[end_choice][clear][end]

msg_267:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 よろしくね～！
[wait][clear][end]

msg_268:
[color(yellow)][var(msg_var_0)][color(white)]
 えっ、その足で踊ってたのぉ？
 ソレってなんかカンドーだよぉ！
[wait][clear][end]

msg_269:
 ね、ホント～は、悪魔なんでしょ？
[choice(2)]意外とそうかも知れねぇなぁ…
あぁ？俺ぁ人間だぜぇ…
[end_choice][clear][end]

msg_270:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 ジョーダンだよ、わかってるってば！
[wait][clear][end]

msg_271:
 酔うと、どーなるタイプ？
[choice(3)]なぁんか手が出ちゃうのよねぇ、グーで…
困った事に涙が止まんなくなんのよ
ひたすら吐く！
[end_choice][clear][end]

msg_272:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたしの前で絶対飲まないでね…
[wait][clear][end]

msg_273:
[color(yellow)][var(msg_var_0)][color(white)]
 でもさぁ、あたしってぇ、
 こ～見えても、おにーさんより
 年上なんだよぉ？
[wait][clear][end]

msg_274:
 もっとウヤマって欲しいよねぇ？
[choice(3)]そいつぁ悪かったな、敬ってやるぜぇ…
ただ生きてりゃ良いってモンじゃねぇぜ…
俺の方が年上だろうが！
[end_choice][clear][end]

msg_275:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 実はあたしもそぉ思うよ！
 歳なんて、どぉでもいーんじゃん？
[wait][clear][end]

msg_276:
[color(yellow)][var(msg_var_0)][color(white)]
 え、マジでぇ？
 おにーさん、超若作り？
 そのテク教えてよぉ！
[wait][clear][end]

msg_277:
[color(yellow)][var(msg_var_0)][color(white)]
 ふだん、どんなセーカツしてたら
 サケがウマイって感じるのぉ？
 あたし、マズイとしか思えないんだけどぉ。
[wait][clear][end]

msg_278:
 ね、どーしたらサケがウマイって感じるぅ？
[choice(3)]心が病んでる時の酒は美味ぇな…
心配事が何も無ぇ時の酒は美味ぇぜ
どんな時でも酒ほど美味ぇモンはねぇな
[end_choice][clear][end]

msg_279:
[color(yellow)][var(msg_var_0)][color(white)]
 じゃぁあたし、サケを飲める日は
 来ないってコトぉ！？
 超ムカツクぅ！
[wait][clear][end]

msg_280:
[color(yellow)][var(msg_var_0)][color(white)]
 マジでぇ？
 じゃぁあたし、今ごろシュゴーじゃないのぉ？
 ちょっと練習してみよっかなぁ…
[wait][clear][end]

msg_281:
[color(yellow)][var(msg_var_0)][color(white)]
 超ウソだよぉ！
 そんなんだったら、あたし飲めるはずだもん！
 テキトーなコト言わないでよねっ！
[wait][clear][end]

msg_282:
[color(yellow)][var(msg_var_0)][color(white)]
 …な、なによぉ！
 ちょぉっと知ったかぶりしただけじゃん！
 だ、大体ねぇ、野球なんてどぉでもいいの！
[wait][clear][end]

msg_283:
 あんなの、たかがアソビじゃん！
[choice(3)]カァ…こいつも解ってねぇな！
人生つぅのも遊びみてぇなもんだぜ…
いや、それもそうだけどよぉ…
[end_choice][clear][end]

msg_284:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 悪いけどぉ、[var(msg_var_0)]、
 オンナノコだもん♥
[wait][clear][end]

msg_285:
[color(yellow)][var(msg_var_0)][color(white)]
 そ、そんな風に言わなくても…
[wait][clear][end]

msg_286:
[color(yellow)][var(msg_var_0)][color(white)]
 ふ、不良中年…
[wait][clear][end]

msg_287:
[color(yellow)][var(msg_var_0)][color(white)]
 あれ、悪魔の世界にはないんだけどさぁ、
 なにやってんのぉ？
[wait][clear][end]

msg_288:
 なんかのシューキョー？
[choice(3)]選挙と言う、民主主義社会のシステムだ
その通りだ
世の中には知らなくて良い事もある…
[end_choice][clear][end]

msg_289:
[color(yellow)][var(msg_var_0)][color(white)]
 そぉ言われると、知りたくなっちゃうのが
 悪魔のツネってもんでしょぉ～！
[wait][clear][end]

msg_290:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしって、悪魔でしょぉ？
 でも、ちょっとカワイすぎない？
 つーか、悪魔にしとくのはもったいなくない？
[wait][clear][end]

msg_291:
 てワケで、貴方の意見をお聞きしたいっ！
[choice(3)]実に勿体無い…
容姿など重要ではない！
真似するな！
[end_choice][clear][end]

msg_292:
[color(yellow)][var(msg_var_0)][color(white)]
 やっぱ、そ～思うよねぇ？
 も～素直なんだから！
[wait][clear][end]

msg_293:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超マジメ～！
 ソッコーハゲるよぉ？
[wait][clear][end]

msg_294:
[color(yellow)][var(msg_var_0)][color(white)]
 ブスってことぉ？
 あんたなんか救いよぉないじゃん！
 その顔、マジ見たくないっ！
[wait][clear][end]

msg_295:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 超似てたでしょぉ？
[wait][clear][end]

msg_296:
[color(yellow)][var(msg_var_0)][color(white)]
 そいつらってぇ、体からヘンなもん出して
 悪魔を殺したりしてんだってぇ～！
 もー超ムカツクよぉ！
[wait][clear][end]

msg_297:
 あんたら、その人間のコト知ってるぅ？
[choice(3)]さぁ、知らんな…
俺達の事か？
さっきすれ違ったな…
[end_choice][clear][end]

msg_298:
[color(yellow)][var(msg_var_0)][color(white)]
 ホントは、あんたらだったりして！
 な～んて、ジョーダンだよ、ジョーダン！
[wait][clear][end]

msg_299:
[color(yellow)][var(msg_var_0)][color(white)]
 おにーさん、知ってんだぁ！？
 ね、ね、どんなヤツ？ カッコよかった？
 …じゃなくて、やっぱムカツク感じだったぁ？
[wait][clear][end]

msg_300:
[color(yellow)][var(msg_var_0)][color(white)]
 なぁんで捕まえとかないワケェ！？
 代わりにあんたら殺すよぉ？
[wait][clear][end]

msg_301:
 おにーさんたち、オクレてんねぇ？
[choice(3)]遅れて等いないぞ！
流行に左右されんだけだ！
貴様、人の事が言えるのか？
[end_choice][clear][end]

msg_302:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたし、オクレてんのかなぁ…？
[wait][clear][end]

msg_303:
 歩き方のコツ、教えてよ！
[choice(3)]足を一直線に出す事ですわ！
Ｓｅｘｙに振る舞う事ですわ！
自分に自信を持つ事ですわ！
[end_choice][clear][end]

msg_304:
[color(yellow)][var(msg_var_0)][color(white)]
 へぇ～！
 今度やってみよ～っと！
[wait][clear][end]

msg_305:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 な～んだ、それだけなのぉ？
 おねーさんも、意外とたいしたことないネ！
[wait][clear][end]

msg_306:
[color(yellow)][var(msg_var_0)][color(white)]
 男にバカにされんのって、
 超クヤシくない？
[wait][clear][end]

msg_307:
 だって男って、超バカじゃん？
[choice(3)]その通りですわね…
そ、そこまでは…
それも差別ですわ！
[end_choice][clear][end]

msg_308:
[color(yellow)][var(msg_var_0)][color(white)]
 で、でも、そっちのケはないからね？
[wait][clear][end]

msg_309:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 甘い顔見してちゃダメなんだって～！
[wait][clear][end]

msg_310:
[color(yellow)][var(msg_var_0)][color(white)]
 は？ なんでぇ？
 なに言ってんのこのヒト？
 バッカじゃないのぉ！？
[wait][clear][end]

msg_311:
[color(yellow)][var(msg_var_0)][color(white)]
 怖い話って、超たのしくない？
 あとさぁ、ムカシ、七不思議とかって
 ハヤんなかったぁ？
[wait][clear][end]

msg_312:
 人間にも、やっぱ七不思議とかってあんの？
[choice(3)]Ｙｅｓ！今度お話しして差し上げますわ。
Ｈｕｕｍ…聞いたことありませんわ…
今、目の前にその一つが…
[end_choice][clear][end]

msg_313:
[color(yellow)][var(msg_var_0)][color(white)]
 え、あたし？
 あ～あれね、カワイすぎってコトでしょ？
[wait][clear][end]

msg_314:
 男なんて死んでいいよねぇ？
[choice(3)]賛成！
そ、それは困るわ…
いたぶる位ならねぇ
[end_choice][clear][end]

msg_315:
[color(yellow)][var(msg_var_0)][color(white)]
 ジョ、ジョーダンなのにぃ…
[wait][clear][end]

msg_316:
 あ、でもさぁ、モテないワケじゃないよぉ？
[choice(3)]信じられないな…
あぁ…もてそうだな
お前に興味はない
[end_choice][clear][end]

msg_317:
 あたし、意外とオトメでしょ♥
[choice(3)]女なら当然だ…
乙女が聞いて呆れるな…
……………
[end_choice][clear][end]

msg_318:
[color(yellow)][var(msg_var_0)][color(white)]
 あたしの王子サマになってもいいヨ♥
[wait][clear][end]

msg_319:
[color(yellow)][var(msg_var_0)][color(white)]
 ま、真顔で言われちゃうと、怖い…
[wait][clear][end]

msg_320:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしほどオトメはいないよぉ？
[wait][clear][end]

msg_321:
[color(yellow)][var(msg_var_0)][color(white)]
 そーいえば、ちょっと聞いたんだけどさぁ、
 人間のキョーダイって、結婚できないってマジ？
[wait][clear][end]

msg_322:
 キョーダイ同士は、結婚できないの？
[choice(3)]できるさ…
できない
異性ならな
[end_choice][clear][end]

msg_323:
[color(yellow)][var(msg_var_0)][color(white)]
 でもさぁ、ちょ～っと
 コドモっぽくない？
 あ、ひょっとして…
[wait][clear][end]

msg_324:
 ホントの恋、したコトないんでしょぉ？
[choice(3)]ある…
ないかも知れない…
恋って何だ…
[end_choice][clear][end]

msg_325:
[color(yellow)][var(msg_var_0)][color(white)]
 えっえっ、超聞きた～い！
[wait][clear][end]

msg_326:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、やばい…
 なんか超ブルー入ってきた…
 はぁ、なんかドーデモいいや…
[wait][clear][end]

msg_327:
 あたし、生きてる価値ってあるのかなぁ？
[choice(3)]有る
無い
聞かれても困る
[end_choice][clear][end]

msg_328:
[color(yellow)][var(msg_var_0)][color(white)]
 あたし、これでもシンケンなんですけどぉ？
 もっと優しくしてくれてもよくない！？
 もぉ～超ムカツクよぉ！
[wait][clear][end]

msg_329:
[color(yellow)][var(msg_var_0)][color(white)]
 そ～そ～、人間のイケン聞きたいんだけどぉ、
 人間から見て、悪魔って、どぉなの？
 ていうか～、ハッキリ言っちゃうとね、
[wait][clear][end]

msg_330:
 あたしって、人間から見てもカワイイよねぇ？
[choice(4)]可愛い
可愛くない
興味がない
言えない
[end_choice][clear][end]

msg_331:
[color(yellow)][var(msg_var_0)][color(white)]
 でっしょ～！
 やっぱ、わかるヒトはわかるんだねぇ～！
 も～！ 超ラブ！！
[wait][clear][end]

msg_332:
[color(yellow)][var(msg_var_0)][color(white)]
 超ムカツク！
 目が笑ってるよぉ！
[wait][clear][end]

msg_333:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 人間って、見る目ないんだね～！
 ま、人間に好かれても困るしぃ。
[wait][clear][end]

msg_334:
[color(yellow)][var(msg_var_0)][color(white)]
 アッタマきた！！
 も～殺す！！
[wait][clear][end]

msg_335:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしもあんたにキョーミないんだよね！
 意外と気ィ合っちゃったりして～！
[wait][clear][end]

msg_336:
[color(yellow)][var(msg_var_0)][color(white)]
 え～なになに？ 言ってよぉ！
 超気になるぅ！！
[wait][clear][end]

msg_337:
[color(yellow)][var(msg_var_0)][color(white)]
 そー言えば！ 超カンジ悪い女がいてさぁ、
 裏じゃ犬を丸飲みするクセにぃ、男の前じゃ
 「ワンちゃんカワイ♥」とか言ってんの！
[wait][clear][end]

msg_338:
 そ～ゆう生き方って、超サムくない？
[choice(4)]寒い
寒くない
どうでもいい
暑い
[end_choice][clear][end]

msg_339:
[color(yellow)][var(msg_var_0)][color(white)]
 でっしょ～！
 よかったぁ、超安心したよぉ！
[wait][clear][end]

msg_340:
[color(yellow)][var(msg_var_0)][color(white)]
 な、なんでそんなに素直なの…
[wait][clear][end]

msg_341:
[color(yellow)][var(msg_var_0)][color(white)]
 あんたも言ってんの？
[wait][clear][end]

msg_342:
[color(yellow)][var(msg_var_0)][color(white)]
 ちょ、ちょっとは関心もってよぉ…
[wait][clear][end]

msg_343:
[color(yellow)][var(msg_var_0)][color(white)]
 ん……、なんか……
 うわっ！ 超クサッ！！
 くさい！ くさいくさいくさい死ぬッ！！！
[wait][clear][end]

msg_344:
 あんたのニオイ、これなにぃっ！？
[choice(4)]昨日食べたニンニク
薫り立つフェロモン
二日酔いで酒臭い
内緒
[end_choice][clear][end]

msg_345:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたしもニンニク、超好き～！
 あのウマさはマジでヤバイよねぇ？
[wait][clear][end]

msg_346:
[color(yellow)][var(msg_var_0)][color(white)]
 だからドキドキしちゃったんだ～
 なーんて、ウッソー♥
[wait][clear][end]

msg_347:
[color(yellow)][var(msg_var_0)][color(white)]
 あたし、サケ飲めないからさぁ、
 二日酔いとかって、ちょ～っと
 うらやましいんだよねぇ。
[wait][clear][end]

msg_348:
[color(yellow)][var(msg_var_0)][color(white)]
 そーそー、人間に聞いときたいんだけど
 人間って、ふだんなに食べてんの？
 草かなんか？
[wait][clear][end]

msg_349:
 ね、ふだんなに食べてんの？
[choice(4)]肉
野菜
霞
悪魔
[end_choice][clear][end]

msg_350:
[color(yellow)][var(msg_var_0)][color(white)]
 へぇ～！
 なんか意外かも～！
 うちらとあんま変わんないんだね。
[wait][clear][end]

msg_351:
[color(yellow)][var(msg_var_0)][color(white)]
 はぁ？
 マトモに答えられても
 全ッ然、おもしろくないんだけどぉ？
[wait][clear][end]

msg_352:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 やっぱ草食べてんだ？
 そりゃ弱いはずだって～！
[wait][clear][end]

msg_353:
[color(yellow)][var(msg_var_0)][color(white)]
 ねぇねぇ、それってヤセる！？
[wait][clear][end]

msg_354:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたしはダメだからね！
 ほ、ほんとは悪魔じゃないから！
 こんなカワイイ悪魔いないでしょ？ ね？
[wait][clear][end]

msg_355:
[color(yellow)][var(msg_var_0)][color(white)]
 なんか超ムカツク！
 ど～ゆうつもりぃ？
[wait][clear][end]

msg_356:
 あたしのコト、バカにしてんのぉ？
[choice(4)]してる
してない
元々バカだ
興味がない
[end_choice][clear][end]

msg_357:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたし、たしかにバカだけどぉ、
 あんたほどじゃないもん♥
[wait][clear][end]

msg_358:
[color(yellow)][var(msg_var_0)][color(white)]
 ホントにぃ～？
 ま、ユルしたげるかぁ。
[wait][clear][end]

msg_359:
[color(yellow)][var(msg_var_0)][color(white)]
 実は、あたしもそぉ思うんだよねぇ。
[wait][clear][end]

msg_360:
[color(yellow)][var(msg_var_0)][color(white)]
 そ、そうなのかなぁ…
[wait][clear][end]

msg_361:
[color(yellow)][var(msg_var_0)][color(white)]
 超ムカツク！！
 マジ、寝て起きて死んできて？
[wait][clear][end]

msg_362:
[color(yellow)][var(msg_var_0)][color(white)]
 つーか超ウザい…
 なんか会って損したキブン～！
 こんなことなら○○してた方がマシだよぉ！
[wait][clear][end]

msg_363:
 さ～！ ○○に入る言葉、なぁ～んだ？
[choice(4)]勉強
カラオケ
デート
王様ゲーム
[end_choice][clear][end]

msg_364:
[color(yellow)][var(msg_var_0)][color(white)]
 あたし、そんなアタマよさげ～？
[wait][clear][end]

msg_365:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたし超ウマイよぉ～！
 ね、こんどいっしょに行こっかぁ？
[wait][clear][end]

msg_366:
[color(yellow)][var(msg_var_0)][color(white)]
 あんたなんかとは
 行かないからねっ！
[wait][clear][end]

msg_367:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 あたし、超モテんだけどぉ、
 男ってバカだし、つまんないんだよねぇ～！
[wait][clear][end]

msg_368:
[color(yellow)][var(msg_var_0)][color(white)]
 うちらの間でもジミに人気だよ～！
 ね、こんどいっしょにやろっか～？
[wait][clear][end]

msg_369:
 な～んか、あたしにウラミでもあるワケェ？
[choice(3)]ある
ない
理由は言えない
[end_choice][clear][end]

msg_370:
[color(yellow)][var(msg_var_0)][color(white)]
 ウ、ウソでしょ…？
 あたし、なんもしてないよぉ…
[wait][clear][end]

msg_371:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 な～んだ！ イジメられる美少女ってのも
 おもしろいと思ったのにぃ～！
[wait][clear][end]

msg_372:
[color(yellow)][var(msg_var_0)][color(white)]
 じゃあなんでムカツかせるワケェ？
 あたしマジでキレるよぉ？
[wait][clear][end]

msg_373:
[color(yellow)][var(msg_var_0)][color(white)]
 ひょっとして、ダレかにたのまれてるとか？
 ええ～すごぉい！ 仕事人みた～い！
[wait][clear][end]

msg_374:
[color(yellow)][var(msg_var_0)][color(white)]
 や、やだぁ…
 理由言ってよぉ…
[wait][clear][end]

msg_375:
[color(yellow)][var(msg_var_0)][color(white)]
 あんたって、意外とおもしろいね！
 そぉだ、これあげるよぉ！
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_4)][color(white)]のカードを[color(green)][var(msg_var_5)]枚[color(white)]も！
 あたしってば超優しくな～い？
[wait][clear][end]

msg_376:
[color(yellow)][var(msg_var_0)][color(white)]
 あんたのコト、超気に入ったよぉ！
 でも、付いてけないんだよねぇ。
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 超残念だろうけど、これでガマンして！
 [color(green)][var(msg_var_4)][color(white)]のカード、[color(green)][var(msg_var_5)]枚[color(white)]で
 いいでしょぉ？
[wait][clear][end]

msg_377:
[color(yellow)][var(msg_var_0)][color(white)]
 あんた、意外とイイヤツだね！
 あ、そぉだ、これあげるよぉ。
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_4)][color(white)]のカード、[color(green)][var(msg_var_5)]枚[color(white)]ね！
 このあたしがあげたんだからね？
 捨てたりしたらマジ殺すよぉ？
[wait][clear][end]

msg_378:
[color(yellow)][var(msg_var_0)][color(white)]
 え～い！ オマケにこれもつけちゃう♥
 [color(green)]フリータロット[color(white)]、[color(green)][var(msg_var_6)]枚[color(white)]ね！
 太っ腹～！ って、デブじゃないからね！
[wait][clear][end]

msg_379:
[color(yellow)][var(msg_var_0)][color(white)]
 なによぉ、あんたって、カード
 マックスじゃん！
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 あげようと思ったのに、超ガッカリ！
 次はないかもよぉ？
[wait][clear][end]

msg_380:
[color(yellow)][var(msg_var_0)][color(white)]
 大切にしてよね！
[wait][clear][end]

msg_381:
[color(yellow)][var(msg_var_0)][color(white)]
 気が向いちゃったからぁ、
 あんたと[color(green)]契約[color(white)]してあげよっかなぁ。
[wait][clear][end]

msg_382:
[color(yellow)][var(msg_var_0)][color(white)]
 な～んか、ほっとけないんだよねぇ。
 しょぉがないから[color(green)]契約[color(white)]してあげるよぉ。
[wait][clear][end]

msg_383:
[color(yellow)][var(msg_var_0)][color(white)]
 あんた、かなり好きかも！
 [color(green)]契約[color(white)]してあげるよぉ！
[wait][clear][end]

msg_384:
[color(yellow)][var(msg_var_0)][color(white)]
 って、あんたの[color(green)]レベル超低い[color(white)]じゃん！
 そんなヒトと、契約できまっせ～ん！
 まぁでも、かわいそ～だから、代わりに…
[wait][clear][end]

msg_385:
[color(yellow)][var(msg_var_0)][color(white)]
 じゃ、そのうちね、そのうち！
 それじゃぁねぇ～バイバイ♥
[wait][clear][end]

msg_386:
 [color(green)]契約[color(white)]するぅ？
[choice(2)]はい
いいえ
[end_choice][clear][end]

msg_387:
[color(yellow)][var(msg_var_0)][color(white)]
 オッケ！
 あたし、あんたに味方しちゃお～っと！
 楽しみに待っててネ！
[wait][clear][end]

msg_388:
[color(yellow)][var(msg_var_0)][color(white)]
 あっそ…
 ま、こ～ゆう日もあるよネ…
 じゃ、バイバ～イ…
[wait][clear][end]

msg_389:
[color(yellow)][var(msg_var_0)][color(white)]
 あっ！ あんた、契約しすぎぃ！
 あたしと契約したいんなら
 [color(green)]契約ハキ[color(white)]してよねっ！
[wait][clear][end]

msg_390:
 どれ[color(green)]ハキ[color(white)]すんのぉ？
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
やっぱりやめる
[end_choice][clear][end]

msg_391:
[color(yellow)][var(msg_var_0)][color(white)]
 マジでムカツクぅぅっ！
 契約したの、超コーカイだよぉっ！
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 あんたの[color(green)]契約[color(white)]なんか[color(green)]ハキ[color(white)]だよっ！
 次会ったら、殺しちゃうかもね！
[wait][clear][end]

msg_392:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あんたとの契約さぁ、
 [color(green)]なかったことにして[color(white)]欲しいな～なんて…
[wait][clear][end]

msg_393:
[color(yellow)][var(msg_var_0)][color(white)]
 も、もう顔見たくないだけだよっ！
[wait][clear][end]

msg_394:
[color(yellow)][var(msg_var_0)][color(white)]
 も、もうヤだぁっ！
[wait][clear][end]

msg_395:
[color(yellow)][var(msg_var_0)][color(white)]
 に、逃げるワケじゃないからねっ！
[wait][clear][end]

msg_396:
[color(yellow)][var(msg_var_0)][color(white)]
 マジ、キレたよぉっ！
 あんたが悪いんだからねっ！
[wait][clear][end]

msg_397:
[color(yellow)][var(msg_var_0)][color(white)]
 怒り超マックスだよぉっ！
[wait][clear][end]

msg_398:
[color(yellow)][var(msg_var_0)][color(white)]
 もーダメ！ もー殺すっ！
 [var(msg_var_0)]の顔も三度までだよぉっ！
[wait][clear][end]

msg_399:
[color(yellow)][var(msg_var_0)][color(white)]
 言うコト聞いちゃう♥
[wait][clear][end]

msg_400:
[color(yellow)][var(msg_var_0)][color(white)]
 超イイ…
[wait][clear][end]

msg_401:
[color(yellow)][var(msg_var_0)][color(white)]
 参りましたっ！
[wait][clear][end]

msg_402:
[color(yellow)][var(msg_var_0)][color(white)]
 あんた、イイねぇ！
 超楽しかったよぉ！
 あっ、そぉだ！
[wait][clear][end]

msg_403:
[color(yellow)][var(msg_var_0)][color(white)]
 あ～おもしろかったぁ！
 お礼ってほどじゃないけどぉ…
[wait][clear][end]

msg_404:
[color(yellow)][var(msg_var_0)][color(white)]
 あたし、あんたのコト好きかも～！
[wait][clear][end]

msg_405:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)][var(msg_var_1)][color(white)]あげるよぉ！
 あたしのキ・モ・チ♥
[wait][clear][end]

msg_406:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)]￥[var(msg_var_2)][color(white)]あげる！
 超リッチでしょ～？
[wait][clear][end]

msg_407:
[color(yellow)][var(msg_var_0)][color(white)]
 [color(green)]元気にして[color(white)]あげるよぉ！
 あたし、超優しくな～い？
[wait][clear][end]

msg_408:
[color(yellow)][var(msg_var_0)][color(white)]
 じゃね、バイバ～イ！
[wait][clear][end]

msg_409:
[color(yellow)][var(msg_var_0)][color(white)]
 そぉ言えば、裏道のどっかに、
 なんとかってのがあるらしいよぉ。
 え～っと、「ブショーのホコラ」だっけ？
[wait][clear][end]

msg_410:
[color(yellow)][var(msg_var_0)][color(white)]
 キヨヒメって悪魔、知ってるぅ？
 超ケッペキショーなんだよ、あんな顔でぇ！
 あのユカも、キレーにしてって感じだよねぇ。
[wait][clear][end]

msg_411:
[color(yellow)][var(msg_var_0)][color(white)]
 さっき聞いたんだけどぉ、「Ｂ２ルート」は
 宝がメチャメチャあんだって～！
 埋蔵金どころじゃないってよぉ？
[wait][clear][end]

msg_412:
[color(yellow)][var(msg_var_0)][color(white)]
 さっき聞いたんだけどぉ、「Ｂ３ルート」は
 宝がメチャメチャあんだって～！
 埋蔵金どころじゃないってよぉ？
[wait][clear][end]

msg_413:
[color(yellow)][var(msg_var_0)][color(white)]
 そ～そ～、ラスプーチンってオヤジがさぁ、
 配電バンのカギ拾ったって超ジマンしてんのぉ！
 なんでジマンなんだか、全ッ然わかんないよぉ。
[wait][clear][end]

msg_414:
[color(yellow)][var(msg_var_0)][color(white)]
 きのう思ったんだけどぉ、カガミって、
 なんで左右逆なのぉ？ 別にさぁ、
 わざわざ逆にしなくても、よくな～い？
[wait][clear][end]

msg_415:
[color(yellow)][var(msg_var_0)][color(white)]
 ここの一番下って、宝の部屋らしいんだけどぉ、
 出てきた者はいないんだって…
 なぜなら入口ないから入れない…だってさ！
[wait][clear][end]

msg_416:
[color(yellow)][var(msg_var_0)][color(white)]
 宝の部屋、入りたい～？
 そぉだなぁ、リヴァイアサンにたのめば、
 カベをハカイしてくれるかもね！
[wait][clear][end]

msg_417:
[color(yellow)][var(msg_var_0)][color(white)]
 そ～そ～、あそこに渡れない橋あるじゃん？
 あれ、だれも渡んないから、こっち側の
 スイッチ壊れっぱなしなんだよねぇ。
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 渡りたかったら、セケルって悪魔に頼んだら？
 あいつトリだからさぁ、飛んでって
 向こう岸のスイッチ入れてくれるよ、きっと！
[wait][clear][end]

msg_418:
[end]

msg_419:
[end]

msg_420:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説の日本刀[color(white)]には
 [color(orange)]隠れた力が宿ってる[color(white)]んだって～！
[wait][clear][end]

msg_421:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説の日本刀[color(white)]は
 [color(orange)]サイキョー[color(white)]なんだって～！
[wait][clear][end]

msg_422:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のハンドガン[color(white)]には
 [color(orange)]隠れた力が宿ってる[color(white)]んだって～！
[wait][clear][end]

msg_423:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のハンドガン[color(white)]は
 [color(orange)]サイキョー[color(white)]なんだって～！
[wait][clear][end]

msg_424:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のコイン[color(white)]には
 [color(orange)]隠れた力が宿ってる[color(white)]んだって～！
[wait][clear][end]

msg_425:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のコイン[color(white)]は
 [color(orange)]サイキョー[color(white)]なんだって～！
[wait][clear][end]

msg_426:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のグラブ[color(white)]には
 [color(orange)]隠れた力が宿ってる[color(white)]んだって～！
[wait][clear][end]

msg_427:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のグラブ[color(white)]は
 [color(orange)]サイキョー[color(white)]なんだって～！
[wait][clear][end]

msg_428:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のレイピア[color(white)]には
 [color(orange)]隠れた力が宿ってる[color(white)]んだって～！
[wait][clear][end]

msg_429:
[color(yellow)][var(msg_var_0)][color(white)]
 みんなには絶対言わないでよぉ？
 ウワサなんだけどぉ、[color(orange)]伝説のレイピア[color(white)]は
 [color(orange)]サイキョー[color(white)]なんだって～！
[wait][clear][end]

msg_430:
[color(yellow)][var(msg_var_0)][color(white)]
 しかもしかも～[color(orange)]超強い[color(white)]らしいよぉ～！
[wait][clear][end]

msg_431:
[color(yellow)][var(msg_var_0)][color(white)]
 でもでも～、
 [color(orange)]超ヨワヨワ[color(white)]らしいよぉ～！
 ヤバくな～い？
[wait][clear][end]

msg_432:
[color(yellow)][var(msg_var_0)][color(white)]
 なんかそれってぇ、あんま強くないんだけどぉ、
 [color(orange)]秘密のなんとか魔法と合体する[color(white)]んだって～！
 超よくな～い？
[wait][clear][end]

msg_433:
[color(yellow)][var(msg_var_0)][color(white)]
 ジャックランタンって知ってるぅ？
 アイツ、なにげに[color(orange)]ダイナミックアギラオ[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_434:
[color(yellow)][var(msg_var_0)][color(white)]
 ジャックフロストって知ってるぅ？
 アイツ、なにげに[color(orange)]アトミックブフーラ[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_435:
[color(yellow)][var(msg_var_0)][color(white)]
 スチュパリデスって知ってるぅ？
 アイツ、なにげに[color(orange)]デンジャラスガルーラ[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_436:
[color(yellow)][var(msg_var_0)][color(white)]
 バルバトスって知ってるぅ？
 アイツ、なにげに[color(orange)]グレイトマグナス[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_437:
[color(yellow)][var(msg_var_0)][color(white)]
 アンクウって知ってるぅ？
 アイツ、なにげに[color(orange)]ハイパージオンガ[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_438:
[color(yellow)][var(msg_var_0)][color(white)]
 カナロアって知ってるぅ？
 アイツ、なにげに[color(orange)]ワンダフルアクエス[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_439:
[color(yellow)][var(msg_var_0)][color(white)]
 デメテールって知ってるぅ？
 アイツ、なにげに[color(orange)]ウルトラフレイラ[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_440:
[color(yellow)][var(msg_var_0)][color(white)]
 サキュバスって知ってるぅ？
 アイツ、なにげに[color(orange)]超メギド[color(white)]って
 魔法、持ってるらしいよぉ？
[wait][clear][end]

msg_441:
[color(yellow)][var(msg_var_0)][color(white)]
 悪いんだけどぉ、今日のあたし、
 あんま語っちゃうキブンじゃないんだよねぇ…
 あ、でもでも、その代わりにさぁ…
[wait][clear][end]

msg_442:
[color(yellow)][var(msg_var_0)][color(white)]
 あ、あたしと契約してんじゃん！
 しょ～がないなぁ…なんか
 キョーリョクしてあげるよぉ。
[wait][clear][end]

msg_443:
 なにキョーリョクしてほしい～？
[choice(4)]アイテムが欲しい
お金が欲しい
情報が欲しい
[if(CBIT_HEAR_RUMOR)]噂を流して欲しい
[end_choice][clear][end]

msg_444:
 なんか流しときたいウワサとか、ないのぉ？
[choice(3)][if(CBIT_HEAR_WEPON)]伝説の武器関連
[if(CBIT_HEAR_MAGIC)]魔法関連
特に無い
[end_choice][clear][end]

msg_445:
 なんか流しときたいウワサとか、ないのぉ？
[choice(4)][if(CBIT_HEAR_WEPON)]伝説の武器関連
[if(CBIT_HEAR_MAGIC)]魔法関連
[if(CBIT_HEAR_MAP1)]このダンジョンの噂
特に無い
[end_choice][clear][end]

msg_446:
[color(yellow)][var(msg_var_0)][color(white)]
 そんなウワサ、ダレだって知ってるって！
 もっと新しくって、おもしろいの、ないのぉ？
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
 ほかにウワサ、ないワケェ？
[wait][clear][end]

msg_447:
 武器って、どんな武器？
[choice(6)][if(CBIT_HEAR_SWD)]伝説の日本刀
[if(CBIT_HEAR_GUN)]伝説のハンドガン
[if(CBIT_HEAR_GTR)]伝説のコイン
[if(CBIT_HEAR_FST)]伝説のグラブ
[if(CBIT_HEAR_FLW)]伝説のレイピア
やっぱりやめる
[end_choice][clear][end]

msg_448:
 魔法って、ダレのぉ？
[choice(6)][if(CBIT_HEAR_AGI)]ジャックランタン
[if(CBIT_HEAR_BUF)]ジャックフロスト
[if(CBIT_HEAR_GAR)]スチュパリデス
[if(CBIT_HEAR_MAG)]バルバトス
[if(CBIT_RESERVE_Ff)]他の悪魔
やっぱりやめる
[end_choice][clear][end]

msg_449:
 魔法って、ダレのぉ？
[choice(6)][if(CBIT_HEAR_JIO)]アンクウ
[if(CBIT_HEAR_AQU)]カナロア
[if(CBIT_HEAR_FRA)]デメテール
[if(CBIT_HEAR_MEG)]サキュバス
[if(CBIT_RESERVE_Fe)]他の悪魔
やっぱりやめる
[end_choice][clear][end]

msg_450:
 どんなウワサ？
[choice(3)][if(CBIT_HEAR_MAP1)]管制室の配電盤が隠し部屋に通じている
[if(CBIT_HEAR_MAP2)]制御室の開かずの扉から廃液処理場に行ける
やっぱりやめる
[end_choice][clear][end]

msg_451:
 その日本刀が、ど～したのぉ？
[choice(4)][if(CBIT_HEAR_SWD_G)][if_not(IBIT_SWD_LGND_G)]実は最強？
[if(CBIT_HEAR_SWD_L)][if_not(IBIT_SWD_LGND_S)]隠された力がある
[if_not(IBIT_SWD_LGND_N)]やっぱり普通
[if_not(IBIT_SWD_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_452:
 そのハンドガンが、ど～したのぉ？
[choice(4)][if(CBIT_HEAR_GUN_G)][if_not(IBIT_GUN_LGND_G)]実は最強？
[if(CBIT_HEAR_GUN_L)][if_not(IBIT_GUN_LGND_S)]隠された力がある
[if_not(IBIT_GUN_LGND_N)]やっぱり普通
[if_not(IBIT_GUN_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_453:
 そのコインが、ど～したのぉ？
[choice(4)][if(CBIT_HEAR_GTR_G)][if_not(IBIT_CON_LGND_G)]実は最強？
[if(CBIT_HEAR_GTR_L)][if_not(IBIT_CON_LGND_S)]隠された力がある
[if_not(IBIT_CON_LGND_N)]やっぱり普通
[if_not(IBIT_CON_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_454:
 そのグラブが、ど～したのぉ？
[choice(4)][if(CBIT_HEAR_FST_G)][if_not(IBIT_FST_LGND_G)]実は最強？
[if(CBIT_HEAR_FST_L)][if_not(IBIT_FST_LGND_S)]隠された力がある
[if_not(IBIT_FST_LGND_N)]やっぱり普通
[if_not(IBIT_FST_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_455:
 そのレイピアが、ど～したのぉ？
[choice(4)][if(CBIT_HEAR_FLW_G)][if_not(IBIT_NSW_LGND_G)]実は最強？
[if(CBIT_HEAR_FLW_L)][if_not(IBIT_NSW_LGND_S)]隠された力がある
[if_not(IBIT_NSW_LGND_N)]やっぱり普通
[if_not(IBIT_NSW_LGND_B)]やっぱりやめる
[end_choice][clear][end]

msg_456:
 ジャックランタンが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_AGI_L)][if_not(BBIT_D_AGIRAO_L)]Ｄアギラオは強い
[if(CBIT_HEAR_AGI_M)][if_not(CBIT_HEAR_AGI_S)]ダイナミックアギラオを使う
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_M)]Ｄアギラオは普通
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_S)]Ｄアギラオは弱い
[if(CBIT_HEAR_AGI_C)][if_not(BBIT_D_AGIRAO_C)]Ｄアギラオは合体する
やっぱりやめる
[end_choice][clear][end]

msg_457:
 ジャックフロストが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_BUF_L)][if_not(BBIT_A_BUFURA_L)]Ａブフーラは強い
[if(CBIT_HEAR_BUF_M)][if_not(CBIT_HEAR_BUF_S)]アトミックブフーラを使う
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_M)]Ａブフーラは普通
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_S)]Ａブフーラは弱い
[if(CBIT_HEAR_BUF_C)][if_not(BBIT_A_BUFURA_C)]Ａブフーラは合体する
やっぱりやめる
[end_choice][clear][end]

msg_458:
 スチュパリデスが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_GAR_L)][if_not(BBIT_D_GARURA_L)]Ｄガルーラは強い
[if(CBIT_HEAR_GAR_M)][if_not(CBIT_HEAR_GAR_S)]デンジャラスガルーラを使う
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_M)]Ｄガルーラは普通
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_S)]Ｄガルーラは弱い
[if(CBIT_HEAR_GAR_C)][if_not(BBIT_D_GARURA_C)]Ｄガルーラは合体する
やっぱりやめる
[end_choice][clear][end]

msg_459:
 バルバトスが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_MAG_L)][if_not(BBIT_G_MAGNAS_L)]Ｇマグナスは強い
[if(CBIT_HEAR_MAG_M)][if_not(CBIT_HEAR_MAG_S)]グレイトマグナスを使う
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_M)]Ｇマグナスは普通
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_S)]Ｇマグナスは弱い
[if(CBIT_HEAR_MAG_C)][if_not(BBIT_G_MAGNAS_C)]Ｇマグナスは合体する
やっぱりやめる
[end_choice][clear][end]

msg_460:
 アンクウが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_JIO_L)][if_not(BBIT_H_JIONGA_L)]Ｈジオンガは強い
[if(CBIT_HEAR_JIO_M)][if_not(CBIT_HEAR_JIO_S)]ハイパージオンガを使う
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_M)]Ｈジオンガは普通
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_S)]Ｈジオンガは弱い
[if(CBIT_HEAR_JIO_C)][if_not(BBIT_H_JIONGA_C)]Ｈジオンガは合体する
やっぱりやめる
[end_choice][clear][end]

msg_461:
 カナロアが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_AQU_L)][if_not(BBIT_W_AQUES_L)]Ｗアクエスは強い
[if(CBIT_HEAR_AQU_M)][if_not(CBIT_HEAR_AQU_S)]ワンダフルアクエスを使う
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_M)]Ｗアクエスは普通
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_S)]Ｗアクエスは弱い
[if(CBIT_HEAR_AQU_C)][if_not(BBIT_W_AQUES_C)]Ｗアクエスは合体する
やっぱりやめる
[end_choice][clear][end]

msg_462:
 デメテールが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_FRA_L)][if_not(BBIT_U_FRAIRA_L)]Ｕフレイラは強い
[if(CBIT_HEAR_FRA_M)][if_not(CBIT_HEAR_FRA_S)]ウルトラフレイラを使う
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_M)]Ｕフレイラは普通
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_S)]Ｕフレイラは弱い
[if(CBIT_HEAR_FRA_C)][if_not(BBIT_U_FRAIRA_C)]Ｕフレイラは合体する
やっぱりやめる
[end_choice][clear][end]

msg_463:
 サキュバスが、ど～したのぉ？
[choice(6)][if(CBIT_HEAR_MEG_L)][if_not(BBIT_C_MEGIDO_L)]超メギドは強い
[if(CBIT_HEAR_MEG_M)][if_not(CBIT_HEAR_MEG_S)]超メギドを使う
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_M)]超メギドは普通
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_S)]超メギドは弱い
[if(CBIT_HEAR_MEG_C)][if_not(BBIT_C_MEGIDO_C)]超メギドは合体する
やっぱりやめる
[end_choice][clear][end]

msg_464:
[color(yellow)][var(msg_var_0)][color(white)]
 へぇ～！
 知らなかったぁ！
 みんなにジマンしちゃお～っと♥
[wait][clear][end]

msg_465:
[color(yellow)][var(msg_var_0)][color(white)]
 はぁ？ ウワサないワケェ？
 超つまんない！
 次もソレだったら殺すからね！
[wait][clear][end]

msg_466:
[color(yellow)][var(msg_var_0)][color(white)]
 し、知ってんだからね！
 おにーさんの[color(orange)]日本刀[color(white)]、[color(orange)]ダメダメ[color(white)]なんでしょ！
 みんなに言っちゃうんだから！
[wait][clear][end]

msg_467:
[color(yellow)][var(msg_var_0)][color(white)]
 し、知ってんだからね！
 おねーさんの[color(orange)]ハンドガン[color(white)]、[color(orange)]ダメダメ[color(white)]なんでしょ！
 みんなに言っちゃうんだから！
[wait][clear][end]

msg_468:
[color(yellow)][var(msg_var_0)][color(white)]
 し、知ってんだからね！
 おにーさんの[color(orange)]コイン[color(white)]、[color(orange)]ダメダメ[color(white)]なんでしょ！
 みんなに言っちゃうんだから！
[wait][clear][end]

msg_469:
[color(yellow)][var(msg_var_0)][color(white)]
 し、知ってんだからね！
 おねーさんの[color(orange)]グラブ[color(white)]、[color(orange)]ダメダメ[color(white)]なんでしょ！
 みんなに言っちゃうんだから！
[wait][clear][end]

msg_470:
[color(yellow)][var(msg_var_0)][color(white)]
 し、知ってんだからね！
 おねーさんの[color(orange)]レイピア[color(white)]、[color(orange)]ダメダメ[color(white)]なんでしょ！
 みんなに言っちゃうんだから！
[wait][clear][end]

msg_471:
[color(yellow)][var(msg_var_0)][color(white)]
 でもさぁ、アレだよねぇ。
 人間って、バカだバカだとは聞いてたけどぉ、
 ホンット～にバカなんだねぇ。
[wait][clear][end]

msg_472:
 ね、はずかしくないのぉ？
[choice(3)]たまに…
馬鹿で何が悪い
悪魔のほうが馬鹿
[end_choice][clear][end]

msg_473:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 人間ってマジやばいよ！
[wait][clear][end]

msg_474:
[color(yellow)][var(msg_var_0)][color(white)]
 開き直っちゃってんのぉ？
 もしかして、あたしよりバカかも～！
[wait][clear][end]

msg_475:
[color(yellow)][var(msg_var_0)][color(white)]
 はぁ？
 あたしのコト言ってんのぉ？
 こいつ超ムカツク！！
[wait][clear][end]

msg_476:
[color(yellow)][var(msg_var_0)][color(white)]
 じゃ、これはあんたの方がふさわしいよね！
 ジャ～ン！！ [color(green)]占札／ＦＯＯＬのカード[color(white)]！
 ガンバってもっとバカになってね！
[wait][clear][end]

msg_477:
[color(yellow)][var(msg_var_0)][color(white)]
 な～んか、ヘンなトコで
 ヘンなのに会っちゃったなぁ。
[wait][clear][end]

msg_478:
[color(green)]選択肢ジャンプの挙動エラーです[color(white)]
[end]

msg_479:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 おにーさん、超カッコイイけど
 それってエステ効果なのぉ～？
[wait][clear][end]

msg_480:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 いいな～エステって！
 あたしも行ってみたいんだよね～！
[wait][clear][end]

msg_481:
[color(yellow)][var(msg_var_0)][color(white)]
 アハハッ！
 やっぱエステっていいねぇ～！
 おにーさん、超フェロモン出てるよぉ？
[wait][clear][end]

msg_482:
[color(yellow)][var(msg_var_0)][color(white)]
 言っとくけどさぁ！
 そんな顔じゃ、エステに行くカネ
 もったいないよぉ！
[wait][clear][end]

msg_483:
[color(yellow)][var(msg_var_0)][color(white)]
 なんか超ハラ立つ！
 あたしだってエステ行ってみたいのにさぁ！
[wait][clear][end]

msg_484:
[color(yellow)][var(msg_var_0)][color(white)]
 エステなんて超ズルだよぉ！
 カネにモノ言わせちゃってさぁ！
[wait][clear][end]
