
msg_0:
[color(yellow)]克哉[color(white)]
 [tatsuya]…
 食事は、ちゃんととってるのか？
 母さんが…心配していたぞ。
[wait][clear][end]

msg_1:
[color(yellow)][tatsuya][color(white)]
 ああ…
 俺もガキじゃない…
 放っておいてくれ…
[wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
 [tatsuya]…
 学校には、行っておいた方が良いぞ。
 将来の為にもな…
[wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
 俺の人生だ…
 構わないでくれないか…
[wait][clear][end]

msg_4:
[load_sound(sndeff_13)][sync][color(yellow)]克哉[color(white)]
 [tatsuya]…
 [play_sound(sndeff_13)][sync]人間、一人では生きていけないんだぞ…[sync]
 解かってるのか？
[wait][clear][end]

msg_5:
[color(yellow)][tatsuya][color(white)]
 ………………………………
[wait][clear][end]

msg_6:
[color(yellow)]克哉[color(white)]
 [var(msg_var_0)]さん…
 まずは、君の同時刻におけるアリバイを
 聞かせてもらいたいな…
[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
 ほう…それは妙だな…
 君は今、犯人しか知らない事を口にした。
 気がついたかな…
[wait][clear][end]

msg_8:
[load_sound(sndeff_10)][sync][color(yellow)]克哉[color(white)]
 先程君は、こう言わなかったかな？
 「そんな女は知らない」と。
 妙だね…[play_sound(sndeff_10)][sync]女性とは一言も言っていないんだが…[sync]
[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
 貴様…よくも弟をっ！
 貴様だけは、絶対に許さん！！
[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
 傷害罪だ！！
 法の裁きを受けろ！！
[wait][clear][end]

msg_11:
[color(yellow)]克哉[color(white)]
 僕の目の前で、やってくれたな…
 覚悟はできてるだろうな！？
[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
 [tatsuya]…
 下がっていろ…
[wait][clear][end]

msg_13:
[color(yellow)][tatsuya][color(white)]
 ………………。
[wait][clear][end]
