
msg_0:
[color(yellow)]南条[color(white)]
 フン…貴様、随分間の抜けた面をしているな。
 頭の程も、推して知るべしというところか。
[wait][clear][end]

msg_1:
[color(yellow)]パオフゥ[color(white)]
 へへ…違いねぇ。
 俺も、そう思ってたところだ。
[wait][clear][end]

msg_2:
[color(yellow)]パオフゥ[color(white)]
 おいおい、ここは人間様の世界だぜ…？
 来るとこ間違えてんじゃねぇか～？
[wait][clear][end]

msg_3:
[color(yellow)]南条[color(white)]
 むしろ帰りたくても帰れないというところか…
 ならば俺達が送り返してやろう。
 あの世へな。
[wait][clear][end]

msg_4:
[load_sound(sndeff_24)][sync][color(yellow)]南条[color(white)]
 貴公のような位の高い悪魔と
 相まみえようとは、[play_sound(sndeff_24)][sync]光栄の至り…[sync]
[wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
 そんな坊ちゃんにぴったりのカクテルがあるぜ。
 ブランデーベースで名前はスティンガー…
 酒言葉は、皮肉屋さ…
[wait][clear][end]

msg_6:
[color(yellow)]南条[color(white)]
 日本経済の基盤は人材だ。
 不況の原因は、人材育成を怠った事にある！
 早急に頭を切り替える事が必要なのだ！
[wait][clear][end]

msg_7:
[color(yellow)]南条[color(white)]
 武力を持たぬと言う以上、
 諸外国との対等関係の構築には、
 経済力と威風堂々たる外交姿勢が必要だ！
[wait][clear][end]

msg_8:
[load_sound(sndeff_21)][sync][color(yellow)]南条[color(white)]
 日本の教育制度は破綻の兆しを見せつつある。
 保守的な制度では、時代の変化についていけない！
 [play_sound(sndeff_21)][sync]抜本的な改革が必要だ！[sync]
[wait][clear][end]

msg_9:
[color(yellow)]南条[color(white)]
 貴方は精一杯生きた…見事でしたよ
[wait][clear][end]

msg_10:
[color(yellow)]南条[color(white)]
 真に誇り高き男、ここに眠る…
 そう墓標に刻ませましょう。
 安らかに…
[wait][clear][end]

msg_11:
[color(yellow)]南条[color(white)]
 貴方の名は、この南条 圭の胸に永遠に刻まれた。
 しかと後世に伝えましょう
[wait][clear][end]

msg_12:
[color(yellow)]南条[color(white)]
 Ｍｒ．パオフゥ…
 この場は、俺一人に任せては頂けませんか？
[wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
 そりゃあ、願ってもねぇ…
 俺も面倒臭ぇのはごめんだからな。
 せぇぜぇ一人で頑張れや。
[wait][clear][end]
