
msg_0:
[color(yellow)]うらら[color(white)]
 ねぇ、アンタさぁ…
 私とマーヤ、どっちが好み？
[wait][clear][end]

msg_1:
[color(yellow)][tatsuya][color(white)]
 …舞耶姉
[wait][clear][end]

msg_2:
[color(yellow)]うらら[color(white)]
 マーヤ！
 あの悪魔が私とアンタ、どっちを選ぶか
 勝負よ、勝負！
[wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
 わかり切った事を聞かないでくれ…
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
 女の良し悪しは乳で決まる訳じゃないんだからね！
 あそこの悪魔に、どっちがイイ女か
 決めてもらおうじゃないさ！
[wait][clear][end]

msg_5:
[play_sound(sndeff_2)][sync] [color(green)]舞耶は挑戦に応じた。[color(white)][sync]
[wait][clear][end]

msg_6:
[color(yellow)][tatsuya][color(white)]
 舞耶姉ったら舞耶姉…
[wait][clear][end]
