
msg_0:
 [color(green)]舞耶は悪魔に人気の秘密について
 インタビューした。[color(white)]
[wait][clear][end]

msg_1:
 [color(green)]舞耶は悪魔をおだてつつインタビューした。[color(white)]
[wait][clear][end]

msg_2:
[play_sound(sndeff_0)][sync] [color(green)]舞耶は悪魔にインタビューを試みた。[color(white)][sync]
[wait][clear][end]

msg_3:
 [color(green)]舞耶は、自分一人でやると二人に言った。[color(white)]
[wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
 へへっ、そうかい。
 なら任せたぜ…
[wait][clear][end]

msg_5:
[color(yellow)]南条[color(white)]
 
[wait][clear][end]
