
msg_0:
[color(yellow)]パオフゥ[color(white)]
 いいから聞きなよ。
 あんまり調子乗ってっと、コイツばら撒くぜ…？
[wait][clear][end]

msg_1:
[color(yellow)]パオフゥ[color(white)]
 どうだ、このテープ？
 良く録れてるだろうが？
 都合…悪いんじゃねぇのかい？
[wait][clear][end]

msg_2:
[color(yellow)]パオフゥ[color(white)]
 おっと、ちょいと待ちな…
 コイツをよ～く聞いてみなよ…
[wait][clear][end]

msg_3:
[color(yellow)]パオフゥ[color(white)]
 全く…あんたも隅に置けないねぇ…
 おっと、勘違いすんなよ！
 こいつぁ取引だぜ…
[wait][clear][end]

msg_4:
[color(yellow)]パオフゥ[color(white)]
 おっと、まだ手ぇ出しちゃイケねぇぜ…
 その前に、こいつを聞いてもらおうか…
[wait][clear][end]

msg_5:
[load_sound(sndeff_18)][sync][color(yellow)]パオフゥ[color(white)]
 こんな面白ぇ事、[play_sound(sndeff_18)][sync]秘密にしておくにゃ
 ちょいと勿体ねぇ…[sync]
 コイツをばら撒かせてもらっても良いかい？
[wait][clear][end]

msg_6:
[color(yellow)]パオフゥ[color(white)]
 へへ…
 子供にゃ荷が重いんじゃねぇか？
 ここは、俺一人で充分だぜぇ。
[wait][clear][end]

msg_7:
[color(yellow)]エリー[color(white)]
 Ｏｋａｙ！
 ここは、Ｍｒ．Ｂａｏｆｕにお任せしますわ。
[wait][clear][end]

msg_8:
[load_sound(sndeff_33)][sync][sync]
[end]

msg_9:
[play_sound(sndeff_33)][sync][sync]
[end]
