
msg_0:
[color(yellow)]南条[color(white)]
 日本経済の基盤は人材だ。
 不況の原因は、人材育成を怠った事にある！
 早急に頭を切り替える事が必要なのだ！
[wait][clear][end]

msg_1:
[color(yellow)]南条[color(white)]
 武力を持たぬと言う以上、
 諸外国との対等関係の構築には、
 経済力と威風堂々たる外交姿勢が必要だ！
[wait][clear][end]

msg_2:
[load_sound(sndeff_21)][sync][color(yellow)]南条[color(white)]
 日本の教育制度は破綻の兆しを見せつつある。
 保守的な制度では、時代の変化についていけない！
 [play_sound(sndeff_21)][sync]抜本的な改革が必要だ！[sync]
[wait][clear][end]

msg_3:
[color(yellow)]南条[color(white)]
 Ｍｓ．芹沢、[suou]…
 この場は、俺一人に任せては頂けませんか？
[wait][clear][end]

msg_4:
[color(yellow)][tatsuya][color(white)]
 あぁ…
 あんたに任せるよ。
[wait][clear][end]
