
msg_0:
[color(yellow)]エリー[color(white)]
 先ずは、私の番ですわね。
[wait][clear][end]

msg_1:
[color(yellow)]うらら[color(white)]
 先ずは、私の番ね。
[wait][clear][end]

msg_2:
[color(yellow)]パオフゥ[color(white)]
 先ずは、俺からだな。
[wait][clear][end]

msg_3:
[color(yellow)]エリー[color(white)]
 次は、私の番ですわね。
[wait][clear][end]

msg_4:
[color(yellow)]うらら[color(white)]
 次は、私の番ね。
[wait][clear][end]

msg_5:
[color(yellow)]パオフゥ[color(white)]
 次は、俺の番だ。
[wait][clear][end]

msg_6:
[load_sound(sndeff_28)][sync][color(yellow)]エリー[color(white)]
 [play_sound(sndeff_28)][sync]私の番ですわね。[sync]
[load_sound(sndeff_3d)][sync][wait][clear][end]

msg_7:
[color(yellow)]エリー[color(white)]
 Ｍｓ．Ｙの家の床には、いつも長い髪の毛が
 落ちているんです。その髪の長さはハンパでなく…
 短いときでも、５Ｍｅｔｅｒはあるとか…！！
[wait][clear][end]

msg_8:
[color(yellow)]うらら[color(white)]
 Ｉくんは、道で拾った小刀を机の引き出しの中に
 大切にしまってあるんだけど……そのせいかな？
 毎晩、枕元に女の人が現れるようになったのは。
[wait][clear][color(yellow)]うらら[color(white)]
 だってその小刀、通り魔殺人事件の犯人が
 道に捨てていった物なのよねぇ…
 ああ、気持ちわるぅっ！！
[wait][clear][end]

msg_9:
[color(yellow)]パオフゥ[color(white)]
 海の近くで盗聴やってるとなぁ、聞えてくんだよ…
 海底深くに沈められたままの
 殺人事件の被害者の叫びとかがよぉ…
[wait][clear][color(yellow)]パオフゥ[color(white)]
 まったく「浮かばれない」話だよな…
[wait][clear][end]

msg_10:
[color(yellow)]エリー[color(white)]
 市内の高級ＭＡＮＳＩＯＮに住むＭｒ．Ｆ…
 ある晩、上の階が騒がしいので注意しに行こうと
 部屋のドアを開けた瞬間、彼はハッとしました
[wait][clear][color(yellow)]エリー[color(white)]
 彼はそのＭＡＮＳＩＯＮの…
 …最上階に住んでいたのです。
[wait][clear][end]

msg_11:
[color(yellow)]うらら[color(white)]
 市の郊外にあるＪ公園のブランコは
 深夜零時になると勝手に揺れ始めるんだって…
 キャー！！
[wait][clear][end]

msg_12:
[color(yellow)]パオフゥ[color(white)]
 海で盗聴やってると時々ヤバいのが入るんだ。
 何年も前に沈没した
 幽霊船のＳＯＳコールとかな…
[wait][clear][end]

msg_13:
[color(yellow)]エリー[color(white)]
 電車が予定より早く到着したので
 Ｍｓ．Ｋは変だなぁ…と思いながらも
 すぐに乗りこみ、ＳＥＡＴに座りました。
[wait][clear][color(yellow)]エリー[color(white)]
 すると、前に立っていた男が
 突然大声で怒鳴り始めたんですの…
 「そんなところで何やってんだ！！」
[wait][clear][color(yellow)]エリー[color(white)]
 ハッと気が付くと、彼女は
 電車には乗っておらず、なぜか線路の上に
 座りこんでいたそうですわ…
[wait][clear][end]

msg_14:
[color(yellow)]うらら[color(white)]
 「不幸の化粧品」って知ってる？
 それをつけると肌が荒れて、どんどん老けて
 早死にしちゃうんだって…
[wait][clear][color(yellow)]うらら[color(white)]
 化粧品は選ばなくちゃね…
[wait][clear][end]

msg_15:
[color(yellow)]パオフゥ[color(white)]
 ある晩、Ｙが会社で残業していると
 窓の外を人がウロウロしているのが見えた。
[wait][clear][color(yellow)]パオフゥ[color(white)]
 「あ～あ、忘年会シーズンだしなぁ…
  ２次会の帰りとか、そんなんだろ…」
 そう思った瞬間、Ｙは背筋が凍りついた！！
[wait][clear][color(yellow)]パオフゥ[color(white)]
 そう、Ｙのいるオフィスは高層ビルの２７階。
 窓の外を人がウロつくなんて、絶対にあり得ねぇ…
[wait][clear][end]

msg_16:
[color(yellow)]エリー[color(white)]
 先日、高速道路で奇妙なＢＩＫＥを見ましたわ…
 乗っていたＤｒｉｖｅｒは…
[wait][clear][color(yellow)]エリー[color(white)]
 首が無かったんですの…
[wait][clear][end]

msg_17:
[color(yellow)]うらら[color(white)]
 友達に聞いたんだけどぉ、アメフトの試合中に
 事故死した選手が、今も自分のいたチームの
 試合を応援しに行ってるんだって…
[wait][clear][color(yellow)]うらら[color(white)]
 客席の方に、おっきな肩パッドつけてる人いたら
 たぶんその人だから…って言われてもねぇ。
[wait][clear][end]

msg_18:
[color(yellow)]パオフゥ[color(white)]
 大きな事故でグチャグチャになった
 クルマって、どこへ行くか知ってるか？
 あるんだよ、クルマ専用の墓地がさ…
[wait][clear][color(yellow)]パオフゥ[color(white)]
 夜な夜な聞えてくるんだよな…
 事故直後の、断末魔のうめき声がさ…
[wait][clear][end]

msg_19:
[color(yellow)]エリー[color(white)]
 ある古本屋さんに突然、大量の古書が格安で
 持ち込まれたそうですわ。店主はもちろん大喜び！
 でもその翌日、店は火事で全焼したんですの…
[wait][clear][color(yellow)]エリー[color(white)]
 どうやらその本、亡くなった学者の遺族が
 本人の遺志を無視して勝手に売ってしまったもの
 だったそうですわ…
[wait][clear][end]

msg_20:
[color(yellow)]うらら[color(white)]
 自殺の名所として知られるＡ渓谷。
 なんでこんなに自殺が多いかって？
 それはねぇ…
[wait][clear][color(yellow)]うらら[color(white)]
 最初に自殺した人の亡霊が
 観光客を下から引きずり落としてるからよ！
 ヒヒヒ…
[wait][clear][end]

msg_21:
[color(yellow)]パオフゥ[color(white)]
 Ｕの部屋には、毎晩ラップ音が響き渡るそうだ。
 …で、よしゃあいいのに、興味をもった馬鹿野郎が
 テープに収めてやるなどと言い出しやがった。
[wait][clear][color(yellow)]パオフゥ[color(white)]
 そいつがラジカセを取り出し録音ボタンを押すと…
 「バーーーーーーーーーーーーーンッ！！」
 物凄い音がしてラジカセは大破。
[wait][clear][color(yellow)]パオフゥ[color(white)]
 それ以来ラップ音は聞こえなくなったそうだ。
 もっとも………………そこに居合わせた全員が
 耳の鼓膜を破っちまった、ってオチなんだがな。
[wait][clear][end]

msg_22:
[color(yellow)]エリー[color(white)]
 Ｍｒ．ＥがＢＩＫＥである村を訪れたときのこと…
 田んぼの畦道を走っていると、田んぼの中で子供が
 走っているのが見えたそうですわ。
[wait][clear][color(yellow)]エリー[color(white)]
 いえ……その子は走っていたのではなく、
 田んぼの少し上を「平行移動」していたんですの…
 Ｍｒ．Ｅは腰が抜けてしばらく立てなかったとか
[wait][clear][end]

msg_23:
[color(yellow)]うらら[color(white)]
 Ｋ高校の近くにあるプリクラは
 ４０９６分の１の確率で「心霊写真」が
 写るって噂よ！
[wait][clear][color(yellow)]うらら[color(white)]
 写真の端っこの方に、ホワァ～っと
 少女の顔が写るらしいんだけど…いやぁ、
 メーカーも話題作りに苦労してるみたいねぇ…
[wait][clear][end]

msg_24:
[color(yellow)]パオフゥ[color(white)]
 Ｆが駅に着いた時には、もう終電が
 出ちまってた。Ｆが諦めて帰ろうとすると
 ホームに黒い電車が入ってくる。黒…！？
[wait][clear][color(yellow)]パオフゥ[color(white)]
 なんとそいつはＳＬだった！ ＳＬは駅を通過し
 そのまま闇の中へ…。翌朝駅に問い合わせると
 「時々ね、出るんですよ。幽霊列車って…」
[wait][clear][end]

msg_25:
[color(yellow)]エリー[color(white)]
 Ｔ君は、かくれんぼが大好きな５歳のＢｏｙ。
 彼はある日、家の仏間にある「開けてはいけない」
 というＤＲＡＷＥＲを開けて、中に隠れました。
[wait][clear][color(yellow)]エリー[color(white)]
 扉を閉めたその瞬間、誰かが腕をつかみました！
 彼は怖くなって外に出ようとしましたが、その
 得体の知れない物は、腕をつかんで離しません…
[wait][clear][color(yellow)]エリー[color(white)]
 Ｔ君はＤＲＡＷＥＲの中で気絶してしまいました。
 彼の腕に付いた大きな赤い手形は、十年たった今も
 クッキリと彼の腕に残っているそうですわ…
[wait][clear][end]

msg_26:
[color(yellow)]うらら[color(white)]
 ３０年前に火事で全焼したＱデパート。
 その跡地に４階建ての雑居ビルができたんだけど、
 このビル、どうも変なのよねぇ…
[wait][clear][color(yellow)]うらら[color(white)]
 だって、毎晩ある時刻になると４階からさらに
 上に続く階段が現れて、それを上ると、なんと！
 「婦人服売り場」に着くんだって。ね、変でしょ
[wait][clear][end]

msg_27:
[color(yellow)]パオフゥ[color(white)]
 この間、俺…、鏡に映らなかったんだ。
 もしやと思って寝室に戻ると、俺が寝てやがった。
 いわゆる「幽体離脱」ってヤツだ…
[wait][clear][end]

msg_28:
[color(yellow)]エリー[color(white)]
 Ｍｓ．Ｉが家に帰ると見知らぬＢｏｙがいました。
 「どこから来たの？」そう聞くと、Ｂｏｙは彼女の
 お腹を指差し、すぅーっと消えてしまいました。
[wait][clear][color(yellow)]エリー[color(white)]
 彼女は５年前にＢａｂｙを
 堕ろしたことがあるのですが、その時きちんと
 水子供養をしなかったそうですわ…
[wait][clear][end]

msg_29:
[color(yellow)]うらら[color(white)]
 ＯＬのＴさんは時々「予知夢」を見るんだって。
 この前もねぇ、知らない人から手紙を貰うっていう
 気味の悪い夢見たら…
[wait][clear][color(yellow)]うらら[color(white)]
 ２ヶ月後にまったく同じ内容の手紙が
 郵便受けに入ってて、差出し人の住所、名前も
 夢で見たのとま～ったく同じ！！
[wait][clear][color(yellow)]うらら[color(white)]
 市役所に行って差出し人の住所を調べてもらうと…
 「その方、２ヶ月前に死亡届が出されてますね。
  …えっ、２ヶ月前がどうかされたんですか？」
[wait][clear][end]

msg_30:
[color(yellow)]パオフゥ[color(white)]
 人形浄瑠璃の人形ってのは古いものになると
 その辺の人間より、ずっと長生きしてるんだ。
 １００年とか２００年とかな…
[wait][clear][color(yellow)]パオフゥ[color(white)]
 人形とはいえ、そのくれぇ長生きすると魂を持つ
 ようになる。夜中に出歩いて酒も呑むようになる。
 芝居に生気を感じるのは、つまりそういうことだ
[wait][clear][end]

msg_31:
[color(yellow)]エリー[color(white)]
 心霊Ｓｐｏｔとして有名なＡ渓谷。
 ある番組制作会社のＳｔａｆｆが
 そこを取材に訪れたところ…
[wait][clear][color(yellow)]エリー[color(white)]
 突然カミナリが落ちて機材は丸焦げ！！
 Ｓｔａｆｆは一目散に逃げ帰ったそうですわ。
[wait][clear][end]

msg_32:
[color(yellow)]？？？[color(white)]
 知ってたぁ？
 怖い話って霊を呼び寄せるって…
[wait][clear][color(yellow)]？？？[color(white)]
 私の知ってる子も百物語をやってたんだけど
 百話終わった時、最初は８人だったのに
 終わってみると、５人になってたんだって…
[wait][clear][color(yellow)]？？？[color(white)]
 ふふふ…
[wait][clear][end]

msg_33:
[color(yellow)]うらら[color(white)]
 だ、誰、今の…
 もしかして１０１話目じゃ？
[wait][clear][end]

msg_34:
[color(yellow)]エリー[color(white)]
 私のＷａｌｋｉｎｇ、堪能して頂けました？
[wait][clear][end]

msg_35:
[load_sound(sndeff_25)][sync][color(yellow)]エリー[color(white)]
 [play_sound(sndeff_25)][sync]Ｏｈ！ Ｅｌｅｇａｎｔですわ！[sync]
[wait][clear][end]

msg_36:
[color(yellow)]エリー[color(white)]
 パリコレでも通用すると思いません？
[wait][clear][end]

msg_37:
[color(yellow)]うらら[color(white)]
 エリーちゃんもさ、
 ストーカーなんて散々だったねぇ…
[wait][clear][end]

msg_38:
[color(yellow)]エリー[color(white)]
 まったくですわ…
 Ｍｓ．Ｕｒａｒａの結婚詐欺といい
 私、男性不信になってしまいそうですわ…
[wait][clear][end]

msg_39:
[color(yellow)]うらら[color(white)]
 まったく男ってのは、どいつもこいつも…
 そこのアンタも、そう思うでしょ！
[wait][clear][end]

msg_40:
[color(yellow)]うらら[color(white)]
 結婚詐欺にストーカーでしょ？
 ドメスティック・バイオレンスにセクハラ…
 いつだって女は、男に泣かされてきたのよ！
[wait][clear][end]

msg_41:
[load_sound(sndeff_29)][sync][color(yellow)]エリー[color(white)]
 [play_sound(sndeff_29)][sync]その通りですわ！[sync]
[wait][clear][end]

msg_42:
[color(yellow)]うらら[color(white)]
 ちょっと、そこのアンタは、どう思ってるワケ？
[wait][clear][end]

msg_43:
[color(yellow)]うらら[color(white)]
 男って一体何様？
 子供も産めないクセして偉そうに…
 結婚詐欺する暇あったら産んでみろっての！
[wait][clear][end]

msg_44:
[color(yellow)]エリー[color(white)]
 ま、まぁ、そこまでは言いませんけど
 Ｍｓ．Ｕｒａｒａの言い分にも一理ありますわ。
[wait][clear][end]

msg_45:
[color(yellow)]うらら[color(white)]
 そうでしょ、ね、そうでしょ！
 ほら、そこのアンタも何か言いなさいよ！
[wait][clear][end]

msg_46:
[load_sound(sndeff_34)][sync][sync]
[end]

msg_47:
[play_sound(sndeff_34)][sync]
[end]

msg_48:
[load_sound(sndeff_3d)][sync][sync]
[end]

msg_49:
[play_sound(sndeff_3d)][sync]
[end]

msg_50:
[color(yellow)]エリー[color(white)]
 Ｍｓ．Ｕｒａｒａ、Ｍｒ．Ｂａｏｆｕ！
 ここは、私の出番ですわ！
 お二人は下がってらして！
[wait][clear][end]

msg_51:
[color(yellow)]うらら[color(white)]
 じゃ、じゃあ頼んだわ…
[wait][clear][end]

msg_52:
[color(yellow)]エリー[color(white)]
 Ｍｓ．Ｕｒａｒａと女同士のお話がありますの。
 Ｍｒ．Ｂａｏｆｕは少々、ご遠慮して
 頂けません？
[wait][clear][end]

msg_53:
[color(yellow)]パオフゥ[color(white)]
 そうか？
 じゃあ、頼んだぜぇ…
[wait][clear][end]
