persona_0_name:
(Blank)[end]

persona_0_descr:
[end]

persona_1_name:
Rangda[end]

persona_1_descr:
Witch of Bali that represents Evil.
Holy beast Barong's eternal rival.[end]

persona_2_name:
Isis[end]

persona_2_descr:
Mother goddess and wife of
Osiris, Egyptian god of rebirth.[end]

persona_3_name:
Manannan[end]

persona_3_descr:
Celtic ocean god with an invisible
cape and magical silver staff.[end]

persona_4_name:
Abe no Seimei[end]

persona_4_descr:
Ancestor of Tsuchimikado Family
ruling over Japan's most powerful onmoyuji.
[end]

persona_5_name:
Agrippa[end]

persona_5_descr:
Greatest sorcerer of the Middle Ages
and an influential writer.[end]

persona_6_name:
Tengu[end]

persona_6_descr:
A red-faced, long-nosed youkai.
His nose shows arrogance.
[end]

persona_7_name:
Lakshmi[end]

persona_7_descr:
Hindu goddess presiding over beauty,
fertility, and good fortune.[end]

persona_8_name:
Scathach[end]

persona_8_descr:
Citizen of "Land of Shadows".
Finishes young hero's training.[end]

persona_9_name:
Hathor[end]

persona_9_descr:
Egyptian goddess of love and wife of Horus
Depicted as a cow headed woman.
[end]

persona_10_name:
Izanami[end]

persona_10_descr:
Goddess who gave birth to Japan
and all its gods.[end]

persona_11_name:
Parvati[end]

persona_11_descr:
A goddess said to be the
reincarnation of Sati, Shiva's wife.
[end]

persona_12_name:
Sif[end]

persona_12_descr:
Wife of Thor in Norse lore. A goddess
with beautiful golden hair.[end]

persona_13_name:
Tensen Nyannyan[end]

persona_13_descr:
Popular goddess worshipped at Mt. Tai.
Also called Tianxian Shengmu Bixia Yuanjun.[end]

persona_14_name:
Gaia[end]

persona_14_descr:
Earth goddess of Greek lore who gave
birth to many gods with Uranus.[end]

persona_15_name:
Kali[end]

persona_15_descr:
Hindu goddess of destruction
born from Durga's anger.
[end]

persona_16_name:
Linog[end]

persona_16_descr:
Filipino goddess of war and maternity
created to destroy demons.[end]

persona_17_name:
Seioubo[end]

persona_17_descr:
Taoist goddess living atop the Kunlun
Mountains who leads all nymphs.[end]

persona_18_name:
Nemesis[end]

persona_18_descr:
Greek goddess of destiny.
[end]

persona_19_name:
Arianrhod[end]

persona_19_descr:
Welsh goddess who used rainbows
to purge violence from the earth.[end]

persona_20_name:
Vishnu[end]

persona_20_descr:
One of the trinity of supreme Hindu gods. 
Good-natured, fair, and benevolent.
[end]

persona_21_name:
Lugh[end]

persona_21_descr:
A Celtic light god who kills the demon lord Balor.
Father of Cu Chulainn.[end]

persona_22_name:
Odin[end]

persona_22_descr:
The Norse All-father.
Fenrir swallowed him at Ragnarok.
[end]

persona_23_name:
Indra[end]

persona_23_descr:
Hindu god of war and lightning.
Called Sakra in Buddhism.[end]

persona_24_name:
Huracan[end]

persona_24_descr:
Mayan creator god who presides over
winds and storms.[end]

persona_25_name:
Baal[end]

persona_25_descr:
Mesopotamian deity denounced
as a false god by Christianity.[end]

persona_26_name:
Marduk[end]

persona_26_descr:
Babylonian creator god who made 
heaven and earth from Tiamat's body.
[end]

persona_27_name:
Airgetlam[end]

persona_27_descr:
King of Tuatha De Danann in Celtic lore.
Another name for the brave god Nuada.[end]

persona_28_name:
Brahma[end]

persona_28_descr:
Fundamental Hindu god of space
and creator of the world.[end]

persona_29_name:
Yamaoka[end]

persona_29_descr:
Nanjo's butler.  He still looks
after him, even in death.[end]

persona_30_name:
Varuna[end]

persona_30_descr:
Hindu water god who rules over
order and ethics.[end]

persona_31_name:
Mithra[end]

persona_31_descr:
Zoroastrian war god who is also
god of justice and light.[end]

persona_32_name:
Yama[end]

persona_32_descr:
Hindu ancestor of humanity.
Called Yanluowang in Buddhism.[end]

persona_33_name:
Sakya[end]

persona_33_descr:
Founder of Buddhism. Siddhartha Gautama.
[end]

persona_34_name:
Umayadono-Ouji[end]

persona_34_descr:
Another name for Prince Shotoku,
writer of the 17-Article Constitution.
[end]

persona_35_name:
Aizen Myouou[end]

persona_35_descr:
Three-eyed king who changes evil
passions to understanding.[end]

persona_36_name:
Xuanzang[end]

persona_36_descr:
Important author and famous monk
by the name of Sanzang Fashi.[end]

persona_37_name:
Alice[end]

persona_37_descr:
A mysterious girl.[end]

persona_38_name:
Vivian[end]

persona_38_descr:
Lake fairy and guardian of Lancelot
in Arthurian lore.[end]

persona_39_name:
Pyro Jack[end]

persona_39_descr:
A ghostly light of English lore, said
to have once been a man named Jack.[end]

persona_40_name:
Jack Frost[end]

persona_40_descr:
Friendly frost fairy with a body made
of ice and snow.[end]

persona_41_name:
Robin Goodfellow[end]

persona_41_descr:
Mischievous English half-fairy
who helps with housework in the night.
[end]

persona_42_name:
Pixie[end]

persona_42_descr:
A mischievous English fairy who
dances in forests at night.[end]

persona_43_name:
Shiva[end]

persona_43_descr:
One of the trinity of Hindu gods who
presides over death and rebirth.[end]

persona_44_name:
Mahakala[end]

persona_44_descr:
An incarnation of Shiva. Known as
Daikokuten in Buddhism.[end]

persona_45_name:
Ares[end]

persona_45_descr:
Greek god of war. Hated by the other gods
for his savagery.[end]

persona_46_name:
Susano-o[end]

persona_46_descr:
Violent god born when Izanagi washed his
nose. Brother to Amaterasu and Tsukuyomi.[end]

persona_47_name:
Seiten Taisei[end]

persona_47_descr:
Another name for Sun Wukong, companion
to Sanzang Fashi in Journey to the West.[end]

persona_48_name:
Taranis[end]

persona_48_descr:
Ruthless Celtic thunder god who
symbolizes destructive storms.[end]

persona_49_name:
Minotaur[end]

persona_49_descr:
Half-bull, half-man monster of Greek myth.
Trapped in Cretan labyrinth.
[end]

persona_50_name:
Wong Long[end]

persona_50_descr:
One of the 5 dragons of nature, the yellow
dragon that represents the center of the world.[end]

persona_51_name:
Vritra[end]

persona_51_descr:
A dragon born from flames when the
sage Kashyapa prayed to defeat Indra.[end]

persona_52_name:
Takshaka[end]

persona_52_descr:
Cunning king of snakes in Indian lore.[end]

persona_53_name:
Culebre[end]

persona_53_descr:
Winged Spanish lake dragon that sucks
the blood of young animals.[end]

persona_54_name:
Otohime[end]

persona_54_descr:
Daughter of the water god Owatatsumi.
Her true form is a gigantic shark.[end]

persona_55_name:
Longma[end]

persona_55_descr:
Dragon that accompanied Sanzang Fashi
as a horse in his journey west.[end]

persona_56_name:
Tishtrya[end]

persona_56_descr:
Persian rain god, enemy of the demon
Apaosha.[end]

persona_57_name:
Kinich Ahau[end]

persona_57_descr:
Mayan sun god who transforms into a
jaguar and stalks the underworld.[end]

persona_58_name:
Genbu[end]

persona_58_descr:
One of the Four Symbols. A holy
beast that protects the north.[end]

persona_59_name:
Byakko[end]

persona_59_descr:
One of the Four Symbols. A holy
beast that protects the west.[end]

persona_60_name:
Gullinbursti[end]

persona_60_descr:
A golden boar owned by Freyr, Norse
god of fertility.[end]

persona_61_name:
Marshal Tianpeng[end]

persona_61_descr:
Another name for Zhu Bajie,
companion on Sanzang Fashi's journey west.
[end]

persona_62_name:
Nekomata[end]

persona_62_descr:
A cat spirit with a split tail. It has
gained magic powers over its long life.[end]

persona_63_name:
Gyokukou Joutei[end]

persona_63_descr:
Taoist deity who controls the fate
of all living things.[end]

persona_64_name:
Fenrir[end]

persona_64_descr:
A gigantic wolf that swallowed Odin at
Ragnarok in Norse lore.[end]

persona_65_name:
Skuld[end]

persona_65_descr:
One of the three Norse goddesses of
fate. Presides over the future.[end]

persona_66_name:
Verdandi[end]

persona_66_descr:
One of the three Norse goddesses of
fate. Presides over the present.[end]

persona_67_name:
Urd[end]

persona_67_descr:
One of the three Norse goddesses of
fate. Presides over the past.[end]

persona_68_name:
Cerberus[end]

persona_68_descr:
Guard dog of Hades in Greek lore.
Has three heads and a snake tail.[end]

persona_69_name:
Pallas Athena[end]

persona_69_descr:
One of the twelve gods of Olympus.
Presides over wisdom and craft.[end]

persona_70_name:
Hyperion[end]

persona_70_descr:
One of the twelve titans.
Helios' father.[end]

persona_71_name:
Bishamonten[end]

persona_71_descr:
One of the Four Devas and
Seven Lucky Gods of Buddhism.[end]

persona_72_name:
Skanda[end]

persona_72_descr:
A Hindu war god. As Idaten, also a
defender of Buddhist doctrine.[end]

persona_73_name:
Kundali Vidyaraja[end]

persona_73_descr:
One of the Five Wisdom Kings in Buddhism.
An incarnation of Ratnasambhava.[end]

persona_74_name:
Nezha[end]

persona_74_descr:
An expert fighter with three heads and eight
arms who battles with Pao-Pei.
[end]

persona_75_name:
Mars[end]

persona_75_descr:
Roman god of war and agriculture.[end]

persona_76_name:
Helios[end]

persona_76_descr:
Sun god in Greek mythology.
Rides a golden-wheeled sun chariot.[end]

persona_77_name:
Azazel[end]

persona_77_descr:
Leader of the fallen angels known as Grigori.
Brought enlightenment to humans.[end]

persona_78_name:
Prometheus[end]

persona_78_descr:
Bound to a rock for hundreds of years
for disobeying Zeus by giving man fire.[end]

persona_79_name:
Adramelech[end]

persona_79_descr:
Scribe of hell and head executive of the
demons. Seen as a peacock.
[end]

persona_80_name:
Barbatos[end]

persona_80_descr:
Duke of Hell in the form of a hunter.
Knows the past and the future.[end]

persona_81_name:
Kabandha[end]

persona_81_descr:
Former Hindu spirit, but angered
Indra and was cast to Asura.[end]

persona_82_name:
Shax[end]

persona_82_descr:
The Great Marquis of Hell who appears
in the form of a bird.[end]

persona_83_name:
Odysseus[end]

persona_83_descr:
Trojan war hero and protagonist of 
Homer's Odyssey.[end]

persona_84_name:
Mot[end]

persona_84_descr:
Babylonian god of death. Killed Baal to
end their struggle.[end]

persona_85_name:
Charon[end]

persona_85_descr:
Ferryman of Hades in Greek lore. Carries
the dead across the river Styx.[end]

persona_86_name:
Ankou[end]

persona_86_descr:
French god of death with a large scythe,
dragging a wagon for the deceased.[end]

persona_87_name:
Hel[end]

persona_87_descr:
Daughter of Loki and ruler of Hel,
Norse land of the dead.[end]

persona_88_name:
Suzaku[end]

persona_88_descr:
One of the Four Symbols. A holy
beast that protects the south.[end]

persona_89_name:
Phoenix[end]

persona_89_descr:
Immortal bird that immolates itself
every 500 years to be reborn.[end]

persona_90_name:
Stymphalides[end]

persona_90_descr:
Crane-like monster with a bronze beak. 
One of Hercules' 12 labors.
[end]

persona_91_name:
Fjalar[end]

persona_91_descr:
A rooster of Norse lore that crows a
warning when Ragnarok draws near.[end]

persona_92_name:
Harpy[end]

persona_92_descr:
Half-woman, half-bird
monster from Greek lore.
[end]

persona_93_name:
Lucifer[end]

persona_93_descr:
One of the seven Overlords of Hell who
presides over the deadly sin of Pride.[end]

persona_94_name:
Beelzebub[end]

persona_94_descr:
Prince of demons often called the
Lord of the Flies.[end]

persona_95_name:
Surt[end]

persona_95_descr:
A giant of Norse lore who incinerates
everything in the world at Ragnarok.[end]

persona_96_name:
Poltergeist[end]

persona_96_descr:
A ghost who levitates furniture.
German for noisy ghost.
[end]

persona_97_name:
Seth[end]

persona_97_descr:
One of the nine Egyptian gods of
the desert and foreigners.[end]

persona_98_name:
Hastur[end]

persona_98_descr:
A Great Old One of the Cthulhu mythos,
Lord of the Byakhees.[end]

persona_99_name:
Seker[end]

persona_99_descr:
Egyptian god of funerals, darkness,
and waning.[end]

persona_100_name:
Aeshma[end]

persona_100_descr:
Zoroastrian demon of rage who lures
men to violence through inebriation.[end]

persona_101_name:
Loki[end]

persona_101_descr:
Trickster of Norse lore
opposes the gods and initiates Ragnarok.
[end]

persona_102_name:
Kanaloa[end]

persona_102_descr:
Obsessive Polynesian creator god in
the form of a squid.[end]

persona_103_name:
Fariedone[end]

persona_103_descr:
A hero of Persian mythology. Deafeated
the snake king Zahhark to become king.[end]

persona_104_name:
Hanuman[end]

persona_104_descr:
A simian warrior who appears in
the Ramayana to help Rama.[end]

persona_105_name:
Asteria[end]

persona_105_descr:
Greek goddess
whose name means "constellation".[end]

persona_106_name:
Valkyrie[end]

persona_106_descr:
Maidens of Norse lore 
who took warriors' souls to Valhalla.
[end]

persona_107_name:
Hoenir[end]

persona_107_descr:
Odin's long-legged attendant in Norse lore.
Known for his indecisiveness.
[end]

persona_108_name:
Juanlian Dajiang[end]

persona_108_descr:
Another name of Sha Wujing, companion
to Sanzang Fashi on his journey west.[end]

persona_109_name:
Gandharva[end]

persona_109_descr:
Half-human, half-bird musician
who serves Indra in Hindu lore.
[end]

persona_110_name:
Iris[end]

persona_110_descr:
Greek goddess of rainbows
who doubles as the gods' messenger.
[end]

persona_111_name:
Kinnara[end]

persona_111_descr:
Half-human, half-horse
god of music in Indian lore.
[end]

persona_112_name:
Callisto[end]

persona_112_descr:
A nymph of Greek Mythology.
Servant of the moon goddess Artemis.[end]

persona_113_name:
Nanna[end]

persona_113_descr:
Sumerian moon god.[end]

persona_114_name:
Artemis[end]

persona_114_descr:
One of the twelve gods of Olympus.
Goddess of hunting and the moon.[end]

persona_115_name:
Maihime Amano[end]

persona_115_descr:
Princess of the Kiyotada family. 
Maya's ancestor...?
[end]

persona_116_name:
Tsukuyomi[end]

persona_116_descr:
Male god born when Izanagi washed
his right eye in Japanese lore.[end]

persona_117_name:
Succubus[end]

persona_117_descr:
A demoness who drains men of their
energy through sex.[end]

persona_118_name:
Maia Prime[end]

persona_118_descr:
Oldest of the seven Pleiades sisters
in Greek lore and mother of Hermes.[end]

persona_119_name:
Pairika[end]

persona_119_descr:
Beautiful Zoroastrian demoness
associated with shooting stars.[end]

persona_120_name:
Maia[end]

persona_120_descr:
Oldest of the seven Pleiades sisters
in Greek lore and mother of Hermes.[end]

persona_121_name:
Virochana[end]

persona_121_descr:
Hindu sun god and king of the Asuras.[end]

persona_122_name:
Apollo[end]

persona_122_descr:
Sun god of Greco-Roman lore.[end]

persona_123_name:
Tatsunoshin [suou][end]

persona_123_descr:
Warlord of the Kiyotada family.
The [suou] brothers' ancestor...?
[end]

persona_124_name:
Ildanach[end]

persona_124_descr:
Another name for Lugh, Celtic god of
light who carries the sword Fragarach.[end]

persona_125_name:
Heimdall[end]

persona_125_descr:
Watchman god of Norse lore who
sounds a horn at Ragnarok.[end]

persona_126_name:
Kinich Kakmo[end]

persona_126_descr:
Sun god of Mayan lore who takes
the form of a macaw.[end]

persona_127_name:
Surya[end]

persona_127_descr:
Hindu sun god that rides the heavens
in a carriage.[end]

persona_128_name:
Satan[end]

persona_128_descr:
King of all demons in Christianity.
Also known as Lucifer.[end]

persona_129_name:
Michael[end]

persona_129_descr:
Leader of the angels,
judges the souls of the dead.
[end]

persona_130_name:
Gabriel[end]

persona_130_descr:
Angel overseeing the garden of Eden.
Visited the Virgin Mary.[end]

persona_131_name:
Ameretat[end]

persona_131_descr:
One of Zoroaster's seven pillars
whose name means immortal.
[end]

persona_132_name:
Armaiti[end]

persona_132_descr:
Daughter of the Persian god Ahura Mazda,
guardian angel protecting the earth.
[end]

persona_133_name:
Melchizedek[end]

persona_133_descr:
Angel that presides over peace
and justice in Gnosticism.[end]

persona_134_name:
Nike[end]

persona_134_descr:
Greek goddess of victory.[end]

persona_135_name:
Phaleg[end]

persona_135_descr:
One of the angels of Olympia.
His planet is Mars.[end]

persona_136_name:
Zhu Yin[end]

persona_136_descr:
A Chinese snake god. With eyes open,
day comes. With eyes closed, night falls.[end]

persona_137_name:
Ouroboros[end]

persona_137_descr:
A snake eating its own tail symbolising
eternity. A worm of Greek lore.[end]

persona_138_name:
Seiryu[end]

persona_138_descr:
One of the Four Symbols. A holy
beast that protects the east.[end]

persona_139_name:
Mucalinda[end]

persona_139_descr:
Snake god who protected Buddha
from a storm while he meditated.[end]

persona_140_name:
Hunab Ku[end]

persona_140_descr:
Supreme god of Mayan lore and
father of Itzamna.[end]

persona_141_name:
Njord[end]

persona_141_descr:
Fertility god of Norse lore.
Associated with the wind and sea.[end]

persona_142_name:
Demeter[end]

persona_142_descr:
One of the twelve gods of Olympus.
Goddess of fertility.[end]

persona_143_name:
Fuuma Kotarou[end]

persona_143_descr:
Ninja leader of the Fuuma Clan
who lived in Fuuma Valley.[end]

persona_144_name:
Junnosuke Kuroda[end]

persona_144_descr:
Tatsunoshin [suou]'s vassal. After his
master's death he hid at Mt. Katatsumuri.[end]

persona_145_name:
Tobi Katou[end]

persona_145_descr:
Another name for Katou Danzou, known as
an illusionist for his agility.[end]

persona_146_name:
Tenjiku Tokubei[end]

persona_146_descr:
A ninja in the Kabuki whose father
taught him toad spells.[end]

persona_147_name:
Sarutobi Sasuke[end]

persona_147_descr:
A Kouga-style ninja who was 
one of the Sanada Ten Braves.
[end]

persona_148_name:
Quetzalcoatl[end]

persona_148_descr:
Mayan water god of fertility
whose name means feathered serpent.
[end]

persona_149_name:
Nodens[end]

persona_149_descr:
An "Outer God" from the Cthulhu mythos
nicknamed the "Lord of the Abyss".[end]

persona_150_name:
Shou Shen[end]

persona_150_descr:
A god of longevity known as Fukurokuju,
one of the Seven Lucky Gods.[end]

persona_151_name:
Budai[end]

persona_151_descr:
One of the Seven Lucky Gods.
He teaches patience and peace.[end]

persona_152_name:
Dagda[end]

persona_152_descr:
Danann god presiding over the
earth, knowledge, and fertility.[end]

persona_153_name:
Bacchus[end]

persona_153_descr:
God of wine in Roman lore.[end]

persona_154_name:
Galahad[end]

persona_154_descr:
Virtuous knight who found the Holy Grail.
Lancelot's son.
[end]

persona_155_name:
Matsuo-sama[end]

persona_155_descr:
The goddess of sake revered at
Matsuo shrine.[end]

persona_156_name:
Futsuno Mitama[end]

persona_156_descr:
God of swords who subjugated Nakatsukuni
with Take-Mikazuchi.
[end]

persona_157_name:
Arthur[end]

persona_157_descr:
Legendary English hero who repelled
the Saxons.[end]

persona_158_name:
Cu Chulainn[end]

persona_158_descr:
Hero of Celtic lore whose battle
rage gives him monstrous power.[end]

persona_159_name:
Kanshou[end]

persona_159_descr:
The Chinese swordsmiths Gan Jiang and Mo Ye
forged the paired swords Kanshou and Bakuya.[end]

persona_160_name:
Sarasvati[end]

persona_160_descr:
Hindu goddess of knowledge and art.
Also called Benzaiten.[end]

persona_161_name:
Peri[end]

persona_161_descr:
Persian fairy with white wings
living in the garden of Peri.[end]

persona_162_name:
Ebisu[end]

persona_162_descr:
One of the Seven Lucky Gods who
brings good luck to fishermen.[end]

persona_163_name:
Fukurokuju[end]

persona_163_descr:
One of the Seven Lucky Gods of
longevity. Also called Jurojin.[end]
