
msg_0:
[color(yellow)]Lazy Boy[color(white)]
[tab]Welcome.
[tab]Rabbit, yes, I’ve heard.
[tab]Use that red machine over there.
[sync][wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]Rabbit, I see how you survived.
[tab]I didn’t imagine 3 Persona users.
[sync][wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Wai...
[tab]How’d you know that!?
[sync][wait][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab]This is... a Persona...!?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]You people have just become Persona users...
[tab]You don’t know how to use your "Chi".
[tab]It’s obvious...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Baofu[color(white)]
[tab][color(green)]He is a Tap Buster, and has a
[tab]webpage that collects all the city’s rumors.
[tab]He says he’s from Taiwan...[color(white)]
[sync][wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]Follow me...
[sync][wait][clear][end]
