
msg_0:
[color(yellow)]Ulala[color(white)]
[tab]There he is!
[sync][wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Hey, you!
[tab]Why’d you disappear when we needed you!?
[tab]Because of you...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Katsuya[color(white)]
[tab]You seem to have a reason...
[tab]Did you know him?
[sync][wait][clear][end]

msg_3:
[color(yellow)]Baofu[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]Knock it off... They’ll find out without
[tab]a report from us. Besides, how are you
[tab]gonna explain this?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]I am an officer of the law.
[tab]I can’t just let it go...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]Heh...
[tab]You can’t look the other way, huh...?
[tab]You’re too soft...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Let the firemen and police handle this,
[tab]and let’s head to the Aerospace Museum.
[tab]We can’t let Sudou stay on the loose...
[sync][wait][clear][end]
