
msg_0:
[color(yellow)]TV Announcer[color(white)]
[tab]...There has been a terrible development!
[tab]It seems the Joker is not just one person...
[sync][wait][clear][end]

msg_1:
[color(yellow)]TV Announcer[color(white)]
[tab]Ah... We have just received news...
[sync][wait][clear][end]

msg_2:
[color(yellow)]TV Announcer[color(white)]
[tab]Earlier today, there was a fire caused by
[tab]a gas explosion at the Morimoto sanitarium.
[sync][wait][clear][end]

msg_3:
[color(yellow)]TV Announcer[color(white)]
[tab]The bodies of workers and patients have been
[tab]recovered from the rubble. There are no
[tab]survivors... the death toll is...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_5:
[color(yellow)]Yukino[color(white)]
[tab]The people who performed the Joker curse
[tab]become Jokers, too...?
[tab]That’s impossible...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Fujii[color(white)]
[tab]They say what goes around comes around...
[tab]But, it’s still hard to believe.
[sync][wait][clear][end]

msg_7:
[color(yellow)]Veteran Reporter[color(white)]
[tab]You never know. I heard Wang Long Chizuru’s
[tab]fortunes are pretty accurate...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Veteran Reporter[color(white)]
[tab]They say the patient’s condition can
[tab]affect the counselor’s mindset too...
[tab]Insanity could spread in this way...
[sync][wait][clear][end]

msg_9:
[color(yellow)]Reporter[color(white)]
[tab]This’ll make a great story... 
[tab]So, that’s what the Chief was investigating. 
[tab]There’s still time... Gotta stop the presses!
[sync][wait][clear][end]

msg_10:
[color(yellow)]Emergency Staircase[color(green)]
[tab]You cannot enter here.[color(white)]
[sync][wait][clear][end]

msg_11:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Battle Master magazine.[color(white)]
[sync][wait][clear][end]

msg_12:
[color(yellow)]Letter from Battle Master[color(white)]
[tab]"Thank you for entering our contest. 
[tab]I am sorry to inform you that you did not win.
[tab]We will be waiting for your next entry."[wait][clear][end]

msg_13:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Miracle magazine.[color(white)]
[sync][wait][clear][end]

msg_14:
[color(yellow)]Letter from Miracle magazine[color(white)]
[tab]"Thank you for entering our contest. 
[tab]I am sorry to inform you that you did not win.
[tab]We will be waiting for your next entry."[wait][clear][end]

msg_15:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Fantasy World.[color(white)]
[sync][wait][clear][end]

msg_16:
[color(yellow)]Letter from Fantasy World[color(white)]
[tab]"Thank you for entering our contest. 
[tab]I am sorry to inform you that you did not win.
[tab]We will be waiting for your next entry."[wait][clear][end]

msg_17:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Battle Master magazine.[color(white)]
[sync][wait][clear][end]

msg_18:
[color(yellow)]Letter from Battle Master[color(white)]
[tab]"Thank you for entering our contest.
[tab] You have been selected as a winner.
[tab] Congratulations!!"[wait][clear][end]

msg_19:
[color(yellow)]Letter from Battle Master[color(white)]
[tab]"Your prize is
[tab] [color(green)][var(msg_var_0)][color(white)].
[tab]We will be waiting for your next entry."[wait][clear][end]

msg_20:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_21:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Miracle magazine.[color(white)]
[sync][wait][clear][end]

msg_22:
[color(yellow)]Letter from Miracle magazine[color(white)]
[tab]"Thank you for entering our contest.
[tab] You have been selected as a winner.
[tab] Congratulations!!"[wait][clear][end]

msg_23:
[color(yellow)]Letter from Miracle magazine[color(white)]
[tab]"Your prize is
[tab] [color(green)][var(msg_var_0)][color(white)].
[tab]We will be waiting for your next entry."[wait][clear][end]

msg_24:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_25:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Fantasy World.[color(white)]
[sync][wait][clear][end]

msg_26:
[color(yellow)]Letter from Fantasy World[color(white)]
[tab]"Thank you for entering our contest.
[tab] You have been selected as a winner.
[tab] Congratulations!!"[wait][clear][end]

msg_27:
[color(yellow)]Letter from Fantasy World[color(white)]
[tab]"Your prize is
[tab][color(green)][var(msg_var_0)][color(white)].
[tab]We will be waiting for your next entry."[wait][clear][end]

msg_28:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_29:
[color(yellow)]In The Box[color(white)]
[tab][color(green)]There is a letter.[color(white)]
[sync][wait][clear][end]

msg_30:
[color(yellow)]Letter from Unknown[color(white)]
[tab]Are you the one worthy of this?
[wait][clear][end]

msg_31:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[sync][wait][clear][end]
