
msg_0:
[color(yellow)]Tatsuya Sudou[color(white)]
[tab]Dammit, dammit... dammitdammitdammitdammit...[delay(30)]
[end]

msg_1:
[tab]My face... Again, my face-------!![delay(30)]
[end]

msg_2:
[tab]You’re saying this is destiny too!! Huh!?
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]No...
[end]

msg_4:
[tab]There is no predestined path one follows...
[end]

msg_5:
[tab]Don’t be fooled by him!
[sync][wait][clear][end]

msg_6:
[color(yellow)]Tatsuya Sudou[color(white)]
[tab]Stupid fools... everyone’s wrong...[delay(30)]
[end]

msg_7:
[tab]You! That bitch! And my fuckin’ dad!!
[end]

msg_8:
[tab]You’re supposed to correct mistakes!!
[sync][wait][clear][end]

msg_9:
[color(yellow)]Tatsuya Sudou[color(white)]
[tab]Hyaha...!![delay(30)] It’s the Voices, the Voice--s!![delay(30)]
[end]

msg_10:
[tab]VoicesVoicesVoicesVoicesVoices!![delay(30)]
[end]

msg_11:
[tab]You can’t run from the Voices----!!
[sync][wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[tab]Stay back, everyone...
[tab]I’ll... take care of him...
[sync][wait][clear][end]
