function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    cameraSet(northeast, 730, 0, -1130);
    objCollisionLink(collision_2, coll_e, obj_4d);
    objVisible(obj_4d, false);
    ref_5 = spriteLoad(sprite_0);
    wait(ref_5);
    ref_7 = spriteLoad(sprite_35);
    wait(ref_7);
    ref_9 = spriteLoad(sprite_6b);
    wait(ref_9);
    ref_b = spriteLoad(sprite_c0);
    wait(ref_b);
    ref_d = spriteLoad(sprite_c2);
    wait(ref_d);
    ref_f = spriteLoad(sprite_46);
    wait(ref_f);
    unitSpawn(yukino, sprite_35, 700, 0, -1030, north, none);
    unitAnimationPlay(yukino, animation_b, 1);
    unitSpawn(fujii, sprite_6b, 600, 0, -1070, west, none);
    unitSpawn(enemy1, sprite_c0, 600, 0, -1190, west, none);
    unitPalette(enemy1, 1);
    unitSpawn(enemy2, sprite_c2, 700, 0, -1250, south, none);
    unitAnimationPlay(enemy2, animation_3, 1);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 4, true);
    screenFadeOuter(rgb(0,0,0), 4, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(60);
    ref_1f = bustupLoad(bustup_12f);
    bustupWait(ref_1f);
    ref_21 = bustupAlloc(ref_1f, right, rgb(0,0,0));
    bustupFade(ref_21, rgb(128,0,0), 30);
    ref_23 = dialogAlloc();
    ref_24 = msgShow(msg_0);
/***************************************
[color(yellow)]TV Announcer[color(white)]
[tab]I see. Wang Long fortune telling
[tab]sure is amazing.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_24);
    dialogFree(ref_23);
    ref_28 = bustupFade(ref_21, rgb(0,0,0), 10);
    bustupWait(ref_28);
    bustupFree(ref_21);
    delayClear();
    delayWait(60);
    ref_2d = cameraRotateTo(5, 1);
    ref_2e = cameraMoveTo(480, 0, -1530, 1);
    wait(ref_2d);
    wait(ref_2e);
    delayClear();
    delayWait(90);
    objAnimRotate(obj_15, 0, 80, 0, 60, 0);
    sndMusicPlay(sound_3110, 127);
    objAnimWait(obj_15);
    delayClear();
    delayWait(10);
    unitAnimationPlay(yukino, animation_a, 1);
    unitAnimationPlay(fujii, animation_1, 1);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitAnimationPlay(enemy2, animation_0, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(fujii, animation_2, 1);
    unitAnimationPlay(enemy1, animation_2, 1);
    unitAnimationPlay(enemy2, animation_1, 1);
    delayClear();
    delayWait(7);
    unitFace(enemy2, east);
    unitAnimationPlay(enemy2, animation_0, 1);
    delayClear();
    delayWait(7);
    unitFace(enemy2, north);
    unitAnimationPlay(enemy2, animation_3, 1);
    objAnimWait(obj_15);
    unitSpawn(unit_15, sprite_46, 300, 0, -1850, south, fade);
    unitMove(unit_15, 300, -1650, face_south, medium);
    unitWait(unit_15);
    objAnimRotate(obj_15, 0, -80, 0, 60, 0);
    sndMusicPlay(sound_3111, 127);
    ref_4f = call(BORYUMOVE1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(fujii, animation_1, 1);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitAnimationPlay(enemy2, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_b, 1);
    unitAnimationPlay(enemy2, animation_1, 1);
    wait(ref_4f);
    ref_5a = call(BORYUMOVE2);
    delayClear();
    delayWait(30);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(fujii, animation_0, 1);
    unitFace(enemy2, west);
    unitAnimationPlay(enemy2, animation_0, 1);
    unitFace(yukino, west);
    unitAnimationPlay(yukino, animation_b, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(enemy1, animation_3, 1);
    unitAnimationPlay(enemy2, animation_3, 1);
    unitAnimationPlay(yukino, animation_a, 1);
    unitAnimationPlay(fujii, animation_0, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(yukino, animation_d, 1);
    unitAnimationPlay(fujii, animation_3, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(enemy1, animation_4, 1);
    unitAnimationPlay(enemy2, animation_4, 1);
    unitAnimationPlay(fujii, animation_4, 1);
    unitAnimationPlay(yukino, animation_e, 1);
    wait(ref_5a);
    ref_74 = call(BORYUMOVE3);
    unitFace(enemy1, south);
    unitFace(enemy2, south);
    unitFace(fujii, south);
    unitFace(yukino, south);
    unitAnimationPlay(enemy1, animation_3, 1);
    unitAnimationPlay(enemy2, animation_3, 1);
    unitAnimationPlay(fujii, animation_3, 1);
    unitAnimationPlay(yukino, animation_d, 1);
    wait(ref_74);
    ref_7e = call(BORYUMOVE4);
    wait(ref_7e);
    delayClear();
    delayWait(60);
    ref_82 = cameraMoveTo(700, -250, -1100, 1);
    ref_83 = cameraRotateTo(5, 1);
    wait(ref_82);
    wait(ref_83);
    delayClear();
    delayWait(60);
    objAnimRotate(obj_15, 0, 80, 0, 60, 0);
    sndMusicPlay(sound_3110, 127);
    objAnimWait(obj_15);
    delayClear();
    delayWait(10);
    unitSpawn(maya, sprite_0, 300, 0, -1850, south, fade);
    unitMove(maya, 300, -1650, face_south, medium);
    unitWait(maya);
    objAnimRotate(obj_15, 0, -80, 0, 60, 0);
    sndMusicPlay(sound_3111, 127);
    delayClear();
    delayWait(10);
    cameraMoveTo(700, 0, -1100, 120);
    ref_95 = call(MAYAMOVE);
    unitAnimationPlay(yukino, animation_0, 1);
    unitAnimationPlay(fujii, animation_4, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_2, 1);
    delayClear();
    delayWait(30);
    unitFace(yukino, east);
    unitFace(fujii, west);
    unitAnimationPlay(yukino, animation_0, 1);
    unitAnimationPlay(fujii, animation_0, 1);
    delayClear();
    delayWait(7);
    unitFace(yukino, north);
    unitFace(fujii, north);
    delayClear();
    delayWait(20);
    unitAnimationPlay(enemy2, animation_0, 1);
    unitAnimationPlay(enemy1, animation_4, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(enemy2, animation_1, 1);
    unitFace(enemy1, west);
    unitAnimationPlay(enemy1, animation_1, 1);
    delayClear();
    delayWait(7);
    unitFace(enemy2, east);
    unitAnimationPlay(enemy2, animation_3, 1);
    unitAnimationPlay(enemy1, animation_2, 1);
    wait(ref_95);
    ref_b7 = bustupLoad(bustup_11a);
    bustupWait(ref_b7);
    ref_b9 = bustupAlloc(ref_b7, right, rgb(0,0,0));
    bustupFade(ref_b9, rgb(128,0,0), 30);
    ref_bb = dialogAlloc();
    ref_bc = msgShow(msg_1);
/***************************************
[color(yellow)]Yukino[color(white)]
[tab]Maya-san... What were you talking about
[tab]with Wang Long Chizuru?
[sync][wait][clear]
***************************************/
    unitAnimationPlay(yukino, animation_2d, 1);
    unitAnimationPlay(maya, animation_3, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_bc);
    dialogFree(ref_bb);
    ref_c4 = bustupFade(ref_b9, rgb(0,0,0), 10);
    bustupWait(ref_c4);
    bustupFree(ref_b9);
    unitAnimationPlay(yukino, animation_a, 1);
    ref_c8 = bustupLoad(bustup_d5);
    bustupWait(ref_c8);
    ref_ca = bustupAlloc(ref_c8, right, rgb(0,0,0));
    bustupFade(ref_ca, rgb(128,0,0), 30);
    ref_cc = dialogAlloc();
    ref_cd = msgShow(msg_2);
/***************************************
[color(yellow)]Fujii[color(white)]
[tab]I was just watching a TV show she was in.
[tab]She said she will reveal who the Joker is...
[sync][wait][clear]
***************************************/
    unitAnimationPlay(fujii, animation_24, 1);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_cd);
    dialogFree(ref_cc);
    ref_d5 = bustupFade(ref_ca, rgb(0,0,0), 10);
    bustupWait(ref_d5);
    bustupFree(ref_ca);
    unitAnimationPlay(fujii, animation_0, 1);
    delayClear();
    delayWait(30);
    ref_db = cameraRotateTo(1, 1);
    wait(ref_db);
    delayClear();
    delayWait(30);
    ref_df = bustupLoad(bustup_12f);
    bustupWait(ref_df);
    ref_e1 = bustupAlloc(ref_df, right, rgb(0,0,0));
    bustupFade(ref_e1, rgb(128,0,0), 30);
    ref_e3 = dialogAlloc();
    ref_e4 = msgShow(msg_3);
/***************************************
[color(yellow)]TV Announcer[color(white)]
[tab]...So then...
[tab]Who exactly is the Joker?
[sync][wait][clear]
***************************************/
    unitAnimationPlay(yukino, animation_b, 1);
    unitAnimationPlay(fujii, animation_1, 1);
    unitAnimationPlay(enemy1, animation_1, 1);
    unitAnimationPlay(enemy2, animation_0, 1);
    unitAnimationPlay(maya, animation_d, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(fujii, animation_2, 1);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(enemy2, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(enemy2, animation_2, 1);
    delayClear();
    delayWait(45);
    sync();
    wait(ref_e4);
    ref_f6 = bustupFade(ref_e1, rgb(0,0,0), 10);
    bustupWait(ref_f6);
    bustupFree(ref_e1);
    ref_f9 = bustupLoad(bustup_53);
    bustupWait(ref_f9);
    ref_fb = bustupAlloc(ref_f9, right, rgb(0,0,0));
    bustupFade(ref_fb, rgb(128,0,0), 30);
    ref_fd = msgShow(msg_4);
/***************************************
[color(yellow)]Wang Long Chizuru[color(white)]
[tab]In Wang Long, the Joker is "Joka", 
[tab]which denotes a human possesed by Kegare, 
[tab]a negative energy such as sin or jealousy.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_fd);
    ref_100 = msgShow(msg_5);
/***************************************
[color(yellow)]Wang Long Chizuru[color(white)]
[tab]Joka is a dragon, filled with Kegare.
[tab]The Guardian Dragons will absorb bad
[tab]luck during this cycle...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_100);
    ref_103 = msgShow(msg_6);
/***************************************
[color(yellow)]Wang Long Chizuru[color(white)]
[tab]It is a much more powerful negative trend
[tab]than that of "Tenchusatsu" or "Ankensatsu".
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_103);
    ref_106 = msgShow(msg_7);
/***************************************
[color(yellow)]Wang Long Chizuru[color(white)]
[tab]Kegare calls forth further Kegare, and Joka 
[tab]causes sin to increase... The more people sin, 
[tab]the greater Kegare’s power becomes.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_106);
    ref_109 = msgShow(msg_8);
/***************************************
[color(yellow)]Wang Long Chizuru[color(white)]
[tab]It is cause and effect... You must not let 
[tab]jealousy and petty grudges consume you!
[tab]You must not perform the JOKER curse!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_109);
    ref_10c = msgShow(msg_9);
/***************************************
[color(yellow)]Wang Long Chizuru[color(white)]
[tab]If you do, you will be possessed by Joka.  
[tab]Thus, those who perform the curse will 
[tab]end up becoming a JOKER themselves.
[sync][wait][clear]
***************************************/
    sndVolumeFadeOff(sound_3035, 300);
    sync();
    wait(ref_10c);
    dialogFree(ref_e3);
    ref_111 = bustupFade(ref_fb, rgb(0,0,0), 10);
    bustupWait(ref_111);
    bustupFree(ref_fb);
    unitAnimationHold(yukino, animation_21, 60);
    unitAnimationHold(fujii, animation_1b, 60);
    unitAnimationHold(maya, animation_21, 60);
    unitAnimationHold(enemy1, animation_1b, 60);
    unitAnimationHold(enemy2, animation_1b, 60);
    ref_119 = bustupLoad(bustup_12f);
    bustupWait(ref_119);
    ref_11b = bustupAlloc(ref_119, right, rgb(0,0,0));
    bustupFade(ref_11b, rgb(128,0,0), 30);
    ref_11d = dialogAlloc();
    ref_11e = msgShow(msg_10);
/***************************************
[color(yellow)]TV Announcer[color(white)]
[tab]Wow...!
[tab]So then, the Joker isn’t just
[tab]one particular person...!?
[sync][wait][clear]
***************************************/
    unitWait(yukino);
    unitWait(fujii);
    unitWait(maya);
    unitWait(enemy1);
    unitWait(enemy2);
    unitAnimationPlay(yukino, animation_b, 1);
    unitAnimationPlay(fujii, animation_2, 1);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(enemy2, animation_2, 1);
    unitAnimationPlay(maya, animation_3, 1);
    sync();
    wait(ref_11e);
    dialogFree(ref_11d);
    ref_12c = bustupFade(ref_11b, rgb(0,0,0), 10);
    bustupWait(ref_12c);
    bustupFree(ref_11b);
    delayClear();
    delayWait(90);
    unitAnimationPlay(yukino, animation_a, 1);
    unitAnimationPlay(fujii, animation_1, 1);
    unitAnimationPlay(maya, animation_a, 1);
    unitAnimationPlay(enemy1, animation_0, 1);
    unitAnimationPlay(enemy2, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(yukino, animation_d, 1);
    delayClear();
    delayWait(90);
    ref_13b = screenHorizontalFadeOut();
    wait(ref_13b);
    eventLoad(event_a7);
}

function BORYUMOVE1()
{
    cameraMoveTo(1000, 0, -100, 600);
    unitMove(unit_15, 1200, -1650, face_west, medium);
    unitWait(unit_15);
}

function BORYUMOVE2()
{
    unitMove(unit_15, 1200, -100, face_south, medium);
    unitWait(unit_15);
    cameraRotateTo(7, 1);
}

function BORYUMOVE3()
{
    unitMove(unit_15, 1000, -100, face_east, medium);
    unitWait(unit_15);
    unitFace(unit_15, south);
}

function BORYUMOVE4()
{
    delayClear();
    delayWait(60);
    sndMusicPlay(sound_310f, 127);
    objAnimTranslate(obj_13, 100, 0, 0, 60);
    objAnimTranslate(obj_14, -200, 0, 0, 60);
    objAnimWait(obj_13);
    objAnimWait(obj_14);
    unitMove(unit_15, 1000, 50, fade, medium);
    unitWait(unit_15);
    sndMusicPlay(sound_310f, 127);
    objAnimTranslate(obj_13, -100, 0, 0, 60);
    objAnimTranslate(obj_14, 200, 0, 0, 60);
    objAnimWait(obj_13);
    objAnimWait(obj_14);
    delayClear();
    delayWait(60);
}

function MAYAMOVE()
{
    unitMove(maya, 600, -1650, face_west, medium);
    unitWait(maya);
    unitMove(maya, 600, -1280, face_south, medium);
    unitWait(maya);
}
