function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    disableMap();
    levelFootstepSet(sfx_15);
    ref_4 = spriteLoad(sprite_0);
    wait(ref_4);
    ref_6 = spriteLoad(sprite_2);
    wait(ref_6);
    ref_8 = spriteLoad(sprite_d);
    wait(ref_8);
    ref_a = spriteLoad(sprite_13);
    wait(ref_a);
    ref_c = spriteLoad(sprite_cc);
    wait(ref_c);
    bitGet(var_1, EBIT_E0037_B);
    bne(var_1, 0, label_13);
    ref_10 = call(KYOUSEI);
    wait(ref_10);
    b(label_17);
  label_13:
    bne(var_1, 1, label_17);
    ref_14 = call(FREE);
    wait(ref_14);
    b(label_17);
  label_17:
}

function KYOUSEI()
{
    cameraSet(southeast, 1000, 0, -1400);
    unitSpawn(maya, sprite_0, 800, 0, -1500, south, none);
    unitAnimationHold(maya, animation_11, -1);
    unitSpawn(baofu, sprite_13, 900, 0, -1500, east, none);
    unitAnimationPlay(baofu, animation_a, 1);
    unitSpawn(katsuya, sprite_d, 850, 0, -1400, north, none);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitTriggerSet(katsuya, KATUYA, 255, 1);
    unitTriggerSet(baofu, PAOFU, 255, 1);
    unitSpawn(npc3, sprite_cc, 980, 0, -200, east, none);
    envTriggerSet(KEISATU01, 224, 1, circle, coll_2);
    unitSpawn(npc4, sprite_cc, 980, 0, -492, east, none);
    envTriggerSet(KEISATU02, 224, 1, circle, coll_3);
    unitSpawn(npc5, sprite_cc, 980, 0, -798, east, none);
    envTriggerSet(KEISATU03, 224, 1, circle, coll_1);
    unitSpawn(npc6, sprite_cc, 1101, 0, -943, north, none);
    envTriggerSet(KEISATU04, 56, 1, circle, coll_0);
    envTriggerSet(POPI, 56, 1, circle, coll_4);
    envTriggerSet(ANNAI, 224, 1, line, coll_21);
    envTriggerSet(EXIT, 131, 1, line, coll_0);
    envTriggerSet(OKORU, 224, 1, line, coll_1);
    delayClear();
    delayWait(60);
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndVolumeFadeOff(sound_3011, 180);
    delayClear();
    delayWait(120);
    ref_38 = bustupLoad(bustup_2c);
    bustupWait(ref_38);
    ref_3a = bustupAlloc(ref_38, left, rgb(0,0,0));
    bustupFade(ref_3a, rgb(128,0,0), 30);
    ref_3c = dialogAlloc();
    ref_3d = msgShow(msg_0);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Hey... what’s wrong?
[sync][wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_14, 1);
    unitWait(baofu);
    delayClear();
    delayWait(5);
    unitAnimationStop(maya);
    unitAnimationHold(maya, animation_21, -1);
    delayClear();
    delayWait(45);
    sync();
    wait(ref_3d);
    dialogFree(ref_3c);
    ref_49 = bustupFade(ref_3a, rgb(0,0,0), 10);
    bustupWait(ref_49);
    bustupFree(ref_3a);
    unitAnimationPlay(baofu, animation_a, 1);
    unitAnimationStop(maya);
    unitAnimationPlay(maya, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(maya, animation_2, 1);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_1, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(maya, animation_0, 1);
    delayClear();
    delayWait(7);
    delayClear();
    delayWait(60);
    unitAnimationPlay(maya, animation_2d, 1);
    delayClear();
    delayWait(120);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_62 = bustupLoad(bustup_21);
    bustupWait(ref_62);
    ref_64 = bustupAlloc(ref_62, left, rgb(0,0,0));
    bustupFade(ref_64, rgb(128,0,0), 30);
    ref_66 = dialogAlloc();
    ref_67 = msgShow(msg_1);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Huh...?
[tab]Are you saying you’ve never met this guy,
[tab]but you recognize his face?
[sync][wait][clear]
***************************************/
    sndMusicPlay(sound_3043, 0);
    sndVolumeFadeTo(sound_3043, 127, 60);
    unitAnimationHold(katsuya, animation_21, 60);
    unitWait(katsuya);
    unitAnimationPlay(katsuya, animation_2d, 1);
    delayClear();
    delayWait(45);
    sync();
    wait(ref_67);
    dialogFree(ref_66);
    ref_72 = bustupFade(ref_64, rgb(0,0,0), 10);
    bustupWait(ref_72);
    bustupFree(ref_64);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(maya, animation_10, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_7e = bustupLoad(bustup_2c);
    bustupWait(ref_7e);
    ref_80 = bustupAlloc(ref_7e, left, rgb(0,0,0));
    bustupFade(ref_80, rgb(128,0,0), 30);
    ref_82 = dialogAlloc();
    ref_83 = msgShow(msg_2);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]What do you mean...?
[sync][wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1f, 1);
    delayClear();
    delayWait(5);
    unitAnimationPlay(katsuya, animation_d, 1);
    unitAnimationPlay(maya, animation_b, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(maya, animation_c, 1);
    delayClear();
    delayWait(45);
    sync();
    wait(ref_83);
    dialogFree(ref_82);
    ref_91 = bustupFade(ref_80, rgb(0,0,0), 10);
    bustupWait(ref_91);
    bustupFree(ref_80);
    unitAnimationPlay(baofu, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_97 = bustupLoad(bustup_21);
    bustupWait(ref_97);
    ref_99 = bustupAlloc(ref_97, left, rgb(0,0,0));
    bustupFade(ref_99, rgb(128,0,0), 30);
    ref_9b = dialogAlloc();
    ref_9c = msgShow(msg_3);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]That "d五j二 vu" stuff again...
[tab]Anyway, let’s apprehend that con-artist.
[tab]We can’t let Serizawa-kun commit a crime.
[sync][wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_b, 1);
    unitAnimationPlay(baofu, animation_d, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_10, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(25);
    sync();
    wait(ref_9c);
    dialogFree(ref_9b);
    ref_b0 = bustupFade(ref_99, rgb(0,0,0), 10);
    bustupWait(ref_b0);
    bustupFree(ref_99);
    unitAnimationPlay(katsuya, animation_a, 1);
    delayClear();
    delayWait(30);
    ref_b6 = bustupLoad(bustup_2c);
    bustupWait(ref_b6);
    ref_b8 = bustupAlloc(ref_b6, left, rgb(0,0,0));
    bustupFade(ref_b8, rgb(128,0,0), 30);
    ref_ba = dialogAlloc();
    ref_bb = msgShow(msg_4);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]I don’t understand, but you can tell by
[tab]looking at his face, right?
[tab]What do you wanna do, just look around?
[sync][wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    unitAnimationPlay(katsuya, animation_d, 1);
    unitAnimationPlay(maya, animation_b, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(maya, animation_c, 1);
    delayClear();
    delayWait(50);
    sync();
    wait(ref_bb);
    ref_c6 = msgShow(msg_5);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Wait... Let’s drop by Hirasaka first. Rumor
[tab]says the head of an Izakaya bar has services
[tab]for locating people... There may be clues.
[sync][wait][clear]
***************************************/
    delayClear();
    delayWait(60);
    sync();
    wait(ref_c6);
    dialogFree(ref_ba);
    ref_cc = bustupFade(ref_b8, rgb(0,0,0), 10);
    bustupWait(ref_cc);
    bustupFree(ref_b8);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitAnimationPlay(baofu, animation_a, 1);
    unitAnimationPlay(maya, animation_b, 1);
    delayClear();
    delayWait(7);
    unitAnimationPlay(maya, animation_a, 1);
    delayClear();
    delayWait(60);
    ref_d7 = cameraLookAtUnit(maya, 0, 30);
    wait(ref_d7);
    unitDespawn(maya, none);
    playerInit(south);
    bitSet(EBIT_E0037_B);
    bitSet(EBIT_E0037);
    bitSet(EBIT_RESEERVE_0011);
    controlEnable();
}

function FREE()
{
    sndMusicPlay(sound_3043, 127);
    unitSpawn(baofu, sprite_13, 900, 0, -1500, east, none);
    unitAnimationPlay(baofu, animation_a, 1);
    unitSpawn(katsuya, sprite_d, 850, 0, -1400, north, none);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitTriggerSet(katsuya, KATUYA, 255, 1);
    unitTriggerSet(baofu, PAOFU, 255, 1);
    unitSpawn(npc3, sprite_cc, 980, 0, -200, east, none);
    envTriggerSet(KEISATU01, 224, 1, circle, coll_2);
    unitSpawn(npc4, sprite_cc, 980, 0, -492, east, none);
    envTriggerSet(KEISATU02, 224, 1, circle, coll_3);
    unitSpawn(npc5, sprite_cc, 980, 0, -798, east, none);
    envTriggerSet(KEISATU03, 224, 1, circle, coll_1);
    unitSpawn(npc6, sprite_cc, 1101, 0, -943, north, none);
    envTriggerSet(KEISATU04, 56, 1, circle, coll_0);
    envTriggerSet(POPI, 56, 1, circle, coll_4);
    envTriggerSet(ANNAI, 224, 1, line, coll_21);
    envTriggerSet(EXIT, 131, 1, line, coll_0);
    envTriggerSet(OKORU, 224, 1, line, coll_1);
    unitIdleOffAll();
    cameraSet(southeast, 700, 0, -1550);
    playerInit(south);
    controlDisable();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function KATUYA()
{
    controlDisable();
    unitFacePlayer(katsuya);
    ref_101 = bustupLoad(bustup_21);
    bustupWait(ref_101);
    ref_103 = bustupAlloc(ref_101, left, rgb(0,0,0));
    bustupFade(ref_103, rgb(128,0,0), 30);
    ref_105 = dialogAlloc();
    ref_106 = msgShow(msg_6);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]More Jokers...
[tab]And here we can’t even handle one...
[sync][wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_106);
    dialogFree(ref_105);
    ref_10d = bustupFade(ref_103, rgb(0,0,0), 10);
    bustupWait(ref_10d);
    bustupFree(ref_103);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitRestoreFacing(katsuya);
    controlEnable();
}

function PAOFU()
{
    controlDisable();
    unitFacePlayer(baofu);
    ref_116 = bustupLoad(bustup_2c);
    bustupWait(ref_116);
    ref_118 = bustupAlloc(ref_116, left, rgb(0,0,0));
    bustupFade(ref_118, rgb(128,0,0), 30);
    ref_11a = dialogAlloc();
    ref_11b = msgShow(msg_7);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Let’s go to Hirasaka first.
[tab]We gotta find that man-searcher.
[sync][wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_11b);
    dialogFree(ref_11a);
    ref_122 = bustupFade(ref_118, rgb(0,0,0), 10);
    bustupWait(ref_122);
    bustupFree(ref_118);
    unitAnimationPlay(baofu, animation_a, 1);
    unitRestoreFacing(baofu);
    controlEnable();
}

function KEISATU01()
{
    controlDisable();
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_14b);
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_142);
    bitGet(var_0, EBIT_E002B);
    bnz(var_0, label_139);
    unitFacePlayer(npc3);
    ref_131 = dialogAlloc();
    ref_132 = msgShow(msg_8);
/***************************************
[color(yellow)]Hard-Working Policeman[color(white)]
[tab]I see. You’re friends of Katsuya-san... 
[tab]He is the hardest working man with a true heart
[tab]for Justice. He is a worrywart though...
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_132);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_131);
    unitRestoreFacing(npc3);
    b(label_153);
  label_139:
    unitFacePlayer(npc3);
    ref_13a = dialogAlloc();
    ref_13b = msgShow(msg_9);
/***************************************
[color(yellow)]Hard-Working Policeman[color(white)]
[tab]What happened at the museum?
[tab]Katsuya-san came back soaking wet...
[tab]Why are we just waiting?
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_13b);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_13a);
    unitRestoreFacing(npc3);
    b(label_153);
  label_142:
    unitFacePlayer(npc3);
    ref_143 = dialogAlloc();
    ref_144 = msgShow(msg_10);
/***************************************
[color(yellow)]Hard-Working Policeman[color(white)]
[tab]The phones are ringing off the hook!
[tab]All of them talk about people going nuts!
[tab]We just can’t keep up with them!
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_144);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_143);
    unitRestoreFacing(npc3);
    b(label_153);
  label_14b:
    unitFacePlayer(npc3);
    ref_14c = dialogAlloc();
    ref_14d = msgShow(msg_11);
/***************************************
[color(yellow)]Hard-Working Policeman[color(white)]
[tab]Lately, there have been many incidents of
[tab]violence, but we have only one suspect.
[tab]I find that... kind of strange...
[wait][clear][color(yellow)]Hard-Working Policeman[color(white)]
[tab]When we arrived at the scene, the commotion
[tab]was over and the suspect was gone. Witnesses
[tab]say the victim was taken away by "someone".
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_24, 1);
    wait(ref_14d);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_14c);
    unitRestoreFacing(npc3);
  label_153:
    controlEnable();
}

function KEISATU02()
{
    controlDisable();
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_17b);
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_172);
    bitGet(var_0, EBIT_E002B);
    bnz(var_0, label_169);
    unitFacePlayer(npc4);
    ref_15d = dialogAlloc();
    ref_15e = msgShow(msg_12);
/***************************************
[color(yellow)]Pale Policeman[color(white)]
[tab]Lately there’s been a lot of creepy cases.
[tab]Especially the murder cases, where they’ve
[tab]been killed gruesomely... Oh, sorry.
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_24, 1);
    wait(ref_15e);
    unitAnimationPlay(npc4, animation_0, 1);
    ref_162 = msgShow(msg_13);
/***************************************
[color(yellow)]Pale Policeman[color(white)]
[tab]Can that really be the work of a human...?
[tab]Before, we could tell if it was a human
[tab]even if a crime was committed...
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_162);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_15d);
    unitRestoreFacing(npc4);
    b(label_183);
  label_169:
    unitFacePlayer(npc4);
    ref_16a = dialogAlloc();
    ref_16b = msgShow(msg_14);
/***************************************
[color(yellow)]Pale Policeman[color(white)]
[tab]Every time Katsuya-san comes back, 
[tab]he runs straight for the Chief’s room.
[tab]There’s gonna be sparks a flyin’ tonight!
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_25, 1);
    wait(ref_16b);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_16a);
    unitRestoreFacing(npc4);
    b(label_183);
  label_172:
    unitFacePlayer(npc4);
    ref_173 = dialogAlloc();
    ref_174 = msgShow(msg_15);
/***************************************
[color(yellow)]Pale Policeman[color(white)]
[tab]Try to stay indoors. Joker cases have
[tab]been popping up everywhere lately.
[tab]You don’t know when they’ll strike next!
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_24, 1);
    wait(ref_174);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_173);
    unitRestoreFacing(npc4);
    b(label_183);
  label_17b:
    unitFacePlayer(npc4);
    ref_17c = dialogAlloc();
    ref_17d = msgShow(msg_16);
/***************************************
[color(yellow)]Pale Policeman[color(white)]
[tab]Lately, kidnappings have been on the rise.
[tab]The witnesses say that men in black take
[tab]people... I wonder if these are organized.
[wait][clear]
***************************************/
    unitAnimationPlay(npc4, animation_24, 1);
    wait(ref_17d);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_17c);
    unitRestoreFacing(npc4);
  label_183:
    controlEnable();
}

function KEISATU03()
{
    controlDisable();
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_1a7);
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_19e);
    bitGet(var_0, EBIT_E002B);
    bnz(var_0, label_195);
    unitFacePlayer(npc5);
    ref_18d = dialogAlloc();
    ref_18e = msgShow(msg_17);
/***************************************
[color(yellow)]Veteran Policeman[color(white)]
[tab]Katsuya’s still young.
[tab]Even so, he pays for his punk of a younger
[tab]brother, and even takes care of him.
[wait][clear][color(yellow)]Veteran Policeman[color(white)]
[tab]They say he’s "shrewd" and "too serious",
[tab]but in the end, he ends up sacrificing
[tab]himself to protect something.
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_18e);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_18d);
    unitRestoreFacing(npc5);
    b(label_1af);
  label_195:
    unitFacePlayer(npc5);
    ref_196 = dialogAlloc();
    ref_197 = msgShow(msg_18);
/***************************************
[color(yellow)]Veteran Policeman[color(white)]
[tab]You know Tatsuzou Sudou? There’s been some
[tab]dark rumors about him. Lately, Katsuya’s
[tab]been trying to get to the bottom of it.
[wait][clear][color(yellow)]Veteran Policeman[color(white)]
[tab]For a guy who is always mellow to become so
[tab]hot when it comes to Tatsuzou... Can only a
[tab]strong sense of justice make him that way?
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_197);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_196);
    unitRestoreFacing(npc5);
    b(label_1af);
  label_19e:
    unitFacePlayer(npc5);
    ref_19f = dialogAlloc();
    ref_1a0 = msgShow(msg_19);
/***************************************
[color(yellow)]Veteran Policeman[color(white)]
[tab]The damn captain is the head of the
[tab]inspectors, yet, he doesn’t give us any
[tab]info! And he says we’re unreliable!?
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_1a0);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_19f);
    unitRestoreFacing(npc5);
    b(label_1af);
  label_1a7:
    unitFacePlayer(npc5);
    ref_1a8 = dialogAlloc();
    ref_1a9 = msgShow(msg_20);
/***************************************
[color(yellow)]Veteran Policeman[color(white)]
[tab]The Investigative Department is a mess.
[tab]They keep doing irrelevant investigations,
[tab]and intentionally leave us short-handed...
[wait][clear]
***************************************/
    unitAnimationPlay(npc5, animation_24, 1);
    wait(ref_1a9);
    unitAnimationPlay(npc5, animation_0, 1);
    dialogFree(ref_1a8);
    unitRestoreFacing(npc5);
  label_1af:
    controlEnable();
}

function KEISATU04()
{
    controlDisable();
    bitGet(var_0, EBIT_E0044);
    bnz(var_0, label_1e6);
    bitGet(var_0, EBIT_E0043);
    bnz(var_0, label_1dd);
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_1d4);
    bitGet(var_0, EBIT_E002B);
    bnz(var_0, label_1c7);
    unitFacePlayer(npc6);
    ref_1bb = dialogAlloc();
    ref_1bc = msgShow(msg_21);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]I want to work hard to become a detective!
[tab]Then I will work hard like Katsuya-san and
[tab]be popular among the female officers...
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_1bc);
    unitAnimationPlay(npc6, animation_0, 1);
    ref_1c0 = msgShow(msg_22);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]But Katsuya-san doesn’t have a girlfriend...
[tab]I guess his work is his love...
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_24, 1);
    wait(ref_1c0);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_1bb);
    unitRestoreFacing(npc6);
    b(label_1ee);
  label_1c7:
    unitFacePlayer(npc6);
    ref_1c8 = dialogAlloc();
    ref_1c9 = msgShow(msg_23);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]It’s strange. I had a dream that the
[tab]museum was burning. Could it have been
[tab]...a... prophecy...?
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_24, 1);
    wait(ref_1c9);
    unitAnimationPlay(npc6, animation_0, 1);
    ref_1cd = msgShow(msg_24);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]N-No, if that was true,
[tab]this police station should be burning too.
[tab]It, it’s probably nothing.
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_26, 1);
    wait(ref_1cd);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_1c8);
    unitRestoreFacing(npc6);
    b(label_1ee);
  label_1d4:
    unitFacePlayer(npc6);
    ref_1d5 = dialogAlloc();
    ref_1d6 = msgShow(msg_25);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]W-Well, we don’t have experience, but we
[tab]still want to assist in the investigations!
[tab]T-That captain is a putz!!
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_25, 1);
    wait(ref_1d6);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_1d5);
    unitRestoreFacing(npc6);
    b(label_1ee);
  label_1dd:
    unitFacePlayer(npc6);
    ref_1de = dialogAlloc();
    ref_1df = msgShow(msg_26);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]I just saw the Chief sneak out.
[tab]He hid his face, but it was definitely him.
[tab]What is he going to do? And where?
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_24, 1);
    wait(ref_1df);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_1de);
    unitRestoreFacing(npc6);
    b(label_1ee);
  label_1e6:
    unitFacePlayer(npc6);
    ref_1e7 = dialogAlloc();
    ref_1e8 = msgShow(msg_27);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]Chief...
[tab]Where’d you go...?
[tab]You looked kinda sad.
[wait][clear]
***************************************/
    unitAnimationPlay(npc6, animation_24, 1);
    wait(ref_1e8);
    unitAnimationPlay(npc6, animation_0, 1);
    dialogFree(ref_1e7);
    unitRestoreFacing(npc6);
  label_1ee:
    controlEnable();
}

function POPI()
{
    controlDisable();
    ref_1f1 = dialogAlloc();
    ref_1f2 = msgShow(msg_28);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]Give me ¥100, woof♥
[tab]Give me ¥100, woof♥
[tab]Give me ¥100, woof♥[wait][clear]
***************************************/
    sndMusicPlay(sound_3126, 127);
    wait(ref_1f2);
    dialogFree(ref_1f1);
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    choiceSetResult(1);
    op_105(1);
    ref_1fa = bustupLoad(bustup_1);
    bustupWait(ref_1fa);
    ref_1fc = bustupAlloc(ref_1fa, center, rgb(0,0,0));
    bustupFade(ref_1fc, rgb(128,0,0), 30);
    ref_1fe = dialogChoiceAlloc();
    ref_1ff = msgShow(msg_29);
/***************************************
[tab]Insert ¥100 here, woof♥
[choice(2)]Insert
Don’t insert
[end_choice][clear]
***************************************/
    wait(ref_1ff);
    dialogFree(ref_1fe);
    ref_202 = bustupFade(ref_1fc, rgb(0,0,0), 10);
    bustupWait(ref_202);
    bustupFree(ref_1fc);
    choiceGetResult(var_7);
    bne(var_7, 0, label_232);
    partyMoneyGet(var_6);
    boutrange(var_6, 0, 99, label_20f);
    ref_209 = dialogAlloc();
    ref_20a = msgShow(msg_30);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]You don’t have any money, woof♥
[tab]Lying is the start of all evil, woof♥
[tab]Come back some other time.[wait][clear]
***************************************/
    sndMusicPlay(sound_3128, 127);
    wait(ref_20a);
    dialogFree(ref_209);
    b(label_231);
  label_20f:
    partyMoneyAdd(-100);
    countGet(var_0, panta);
    add(var_0, var_0, 1);
    countSet(panta, var_0);
    bne(var_0, 50, label_21a);
    ref_214 = dialogAlloc();
    ref_215 = msgShow(msg_31);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]Woof![delay(15)]
[tab]I saved ¥5000, woof![delay(15)]
[tab]Wonderful, woof!![wait][clear]
***************************************/
    sndMusicPlay(sound_3127, 127);
    wait(ref_215);
    dialogFree(ref_214);
    b(label_230);
  label_21a:
    bne(var_0, 100, label_22a);
    ref_21b = dialogAlloc();
    ref_21c = msgShow(msg_32);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]Woof![delay(10)]
[tab]I’ve finally saved ¥10000, woof![delay(15)]
[tab]Thanks to you, woof!![wait][clear]
***************************************/
    sndMusicPlay(sound_3127, 127);
    wait(ref_21c);
    msgVar_Item(msgvar_0, hihi_irokane);
    ref_220 = msgShow(msg_33);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]Here’s a token of appreciation, woof!
[tab][color(green)][var(msg_var_0)][color(white)].
[tab]One "ruff" present, woof♥[wait][clear]
***************************************/
    wait(ref_220);
    dialogFree(ref_21b);
    partyItemAdd(hihi_irokane, 1);
    msgVarSet(msgvar_0, 99);
    ref_225 = dialogAlloc();
    ref_226 = msgShow(msg_34);
/***************************************
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear]
***************************************/
    wait(ref_226);
    dialogFree(ref_225);
    b(label_230);
  label_22a:
    ref_22a = dialogAlloc();
    ref_22b = msgShow(msg_35);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]Thanks, woof♥[wait][clear]
***************************************/
    sndMusicPlay(sound_3127, 127);
    wait(ref_22b);
    dialogFree(ref_22a);
    b(label_230);
  label_230:
    b(label_231);
  label_231:
    b(label_239);
  label_232:
    bne(var_7, 1, label_239);
    ref_233 = dialogAlloc();
    ref_234 = msgShow(msg_36);
/***************************************
[color(yellow)]Coppy[color(white)]
[tab]...[delay(15)]Cheapskate cat-lover![wait][clear]
***************************************/
    sndMusicPlay(sound_3128, 127);
    wait(ref_234);
    dialogFree(ref_233);
    b(label_239);
  label_239:
    shopCurrencyDisplay(-110, 150, true);
    controlEnable();
}

function ANNAI()
{
    controlDisable();
    ref_23d = dialogAlloc();
    ref_23e = msgShow(msg_37);
/***************************************
[color(yellow)]Guide[color(white)]
[tab]B1F General Counsel, Foreign Affairs
[tab]1F Lost and Found, Licenses
[tab]2F Criminal, Disaster, Traffic[wait][clear]
***************************************/
    wait(ref_23e);
    ref_240 = msgShow(msg_38);
/***************************************
[color(yellow)]Guide[color(white)]
[tab]3F Investigations, Domestic, Security
[tab]4F Criminal Identification, Juvenile
[tab]5F Missing Persons, Special Investigations[wait][clear]
***************************************/
    wait(ref_240);
    dialogFree(ref_23d);
    controlEnable();
}

function EXIT()
{
    controlDisable();
    objAnimTranslate(obj_30, -100, 0, 0, 60);
    objAnimTranslate(obj_31, 100, 0, 0, 60);
    sndMusicPlay(sound_3125, 127);
    objAnimWait(obj_30);
    objAnimWait(obj_31);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    mapLoad(kounan, 35, 2);
}

function OKORU()
{
    controlDisable();
    ref_254 = cameraRotateTo(3, 30);
    wait(ref_254);
    ref_256 = unitMove(npc6, 1257, -943, face_west, fast);
    wait(ref_256);
    unitFace(npc6, north);
    delayClear();
    delayWait(30);
    ref_25b = dialogAlloc();
    ref_25c = msgShow(msg_39);
/***************************************
[color(yellow)]Rookie Policeman[color(white)]
[tab]HE-------YYYY...!!
[tab]Employees only!
[tab]You can’t go in there!
[sync][wait][clear]
***************************************/
    sndMusicPlay(sound_3129, 127);
    unitAnimationPlay(npc6, animation_26, 1);
    delayClear();
    delayWait(60);
    sync();
    wait(ref_25c);
    dialogFree(ref_25b);
    unitAnimationPlay(npc6, animation_0, 1);
    ref_265 = unitMove(npc6, 1101, -943, face_east, medium);
    wait(ref_265);
    unitFace(npc6, north);
    controlEnable();
}
