
msg_0:
[color(yellow)]Manly Man[color(white)]
[tab]Let them in...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]You guys really put on a show...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Hmph!
[sync][wait][clear][end]

msg_3:
[color(yellow)]Baofu[color(white)]
[tab]Tch...!
[sync][wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]This is Kei Nanjo, he is renting this
[tab]room, and his friend, Eriko Kirishima.
[tab]I’ve told them our story.
[sync][wait][clear][end]

msg_5:
[color(yellow)]Nanjo[color(white)]
[tab]Nice to meet you... I’m Kei Nanjo.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Kei Nanjo[color(white)]
[tab][color(green)]Son of the head of some of Japan’s biggest
[tab]companies. A Persona user who "awakened" as
[tab]a result of the Sebec Scandal.[color(white)]
[sync][wait][clear][end]

msg_7:
[color(yellow)]Elly[color(white)]
[tab]Nice to meet you.
[tab]My name’s Eriko... Eriko Kirishima...
[tab]You can call me Elly.
[sync][wait][clear][end]

msg_8:
[color(yellow)]Eriko Kirishima[color(white)]
[tab][color(green)]Like Nanjo, she was "awakened" by a past
[tab]incident. She is a big fan of the occult.
[tab]She works as a model, but...[color(white)]
[sync][wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]So...
[tab]Why were you guys investigating the
[tab]New World Order?
[sync][wait][clear][end]

msg_10:
[color(yellow)]Nanjo[color(white)]
[tab]Do you know a guy named "Hisataka Shinjo"?
[sync][wait][clear][end]

msg_11:
[color(yellow)]Baofu[color(white)]
[tab]Just the name... He’s Tatsuzou’s secretary,
[tab]but his work history and his details come
[tab]up a blank... He’s like a shadow.
[sync][wait][clear][end]

msg_12:
[color(yellow)]Nanjo[color(white)]
[tab]The truth is that Shinjo... 
[tab]might actually be Takahisa Kandori. 
[tab]It’s a rumor circulating around political arenas...
[sync][wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Kandori, the president of the Sebec Corp. 
[tab]Wasn’t he responsible for that accident 
[tab]in Mikage-cho? Isn’t he dead?
[sync][wait][clear][end]

msg_14:
[color(yellow)]Nanjo[color(white)]
[tab]That’s what we thought... 
[tab]Three years ago he planned to 
[tab]destroy the world until we stopped him...
[sync][wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]While chasing the shadow of a dead man,
[tab]you arrived at Tatsuzou, huh...?
[sync][wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]The little girl over there, too?
[sync][wait][clear][end]

msg_17:
[color(yellow)]Elly[color(white)]
[tab]I was researching the relationship between
[tab]the popular Wang Long fortunes and the case.
[tab]Then, I ran into Kei by chance...
[sync][wait][clear][end]

msg_18:
[color(yellow)]Elly[color(white)]
[tab]But after listening to your stories,
[tab]I realized that all the incidents are
[tab]connected.
[sync][wait][clear][end]

msg_19:
[color(yellow)]Elly[color(white)]
[tab]It’s obvious that the New World Order
[tab]needs the Jokers for some reason.
[sync][wait][clear][end]

msg_20:
[color(yellow)]Elly[color(white)]
[tab]And the Joker craze has some tie-in to
[tab]Wang Long... I wonder if they’re using the
[tab]readings to spread information, rumors...
[sync][wait][clear][end]

msg_21:
[color(yellow)]Nanjo[color(white)]
[tab]They are creating Jokers and sorting out
[tab]people’s fortune, so the curse is used more.
[tab]Sounds ridiculous, but look at it now...
[sync][wait][clear][end]

msg_22:
[color(yellow)]Ulala[color(white)]
[tab]I see... There’s nothing as enviable as
[tab]another person’s good fortune...
[tab]But why...?
[sync][wait][clear][end]

msg_23:
[color(yellow)]Nanjo[color(white)]
[tab]That’s something we should ask the head
[tab]of the NWO...
[sync][wait][clear][end]

msg_24:
[color(yellow)]Nanjo[color(white)]
[tab]The kidnapped Jokers were supposedly
[tab]taken to a nearby science laboratory.
[tab]Shinjo goes in and out of there often...
[sync][wait][clear][end]

msg_25:
[color(yellow)]Elly[color(white)]
[tab]I got ahold of Wang Long Chizuru’s
[tab]schedule. She’s filming a TV show
[tab]later on today.
[sync][wait][clear][end]

msg_26:
[color(yellow)]Katsuya[color(white)]
[tab]We have to split up...
[sync][wait][clear][end]

msg_27:
[color(yellow)]Nanjo[color(white)]
[tab]It would be greatly appreciated if all of
[tab]you could help. Kirishima can handle
[tab]the fortune teller on her own.
[sync][wait][clear][end]

msg_28:
[color(yellow)]Elly[color(white)]
[tab]Alright.
[tab]Leave the TV station to me!
[sync][wait][clear][end]

msg_29:
[color(yellow)]Elly[color(white)]
[tab]If someone comes with me to the TV station,
[tab]Kei can then check out the lab...
[sync][wait][clear][end]

msg_30:
[color(yellow)]Nanjo[color(white)]
[tab]Sounds like a plan...
[tab]Just like old times, huh Kirishima?
[sync][wait][clear][end]

msg_31:
[color(yellow)]Manly Man[color(white)]
[tab]I am Matsuoka... I must warn you...
[tab]What Kei-sama is doing has nothing to
[tab]do with the Nanjo corporation. Remember this...
[sync][wait][clear][end]

msg_32:
[color(yellow)]Matsuoka[color(white)]
[tab][color(green)]With a built body and a mean glare,
[tab]he is Nanjo’s rather "rude" bodyguard...
[tab]He seems to be against Nanjo’s actions...[color(white)]
[sync][wait][clear][end]

msg_33:
[color(yellow)]Matsuoka[color(white)]
[tab]Of course, you will not speak of 
[tab]Kei-sama’s actions. If you do, you’ll regret it.
[tab]Do not forget that...
[sync][wait][clear][end]

msg_34:
[color(yellow)]Ulala[color(white)]
[tab]Wow, this is gorgeous... 
[tab]So, this is the Hotel Pleiades’ penthouse...
[tab]Rich people ARE different.
[sync][wait][clear][end]

msg_35:
[color(yellow)]Katsuya[color(white)]
[tab]Normally, I wouldn’t accept intervention
[tab]by normal civilians...
[tab]But I guess it’s fine for Persona users...
[sync][wait][clear][end]

msg_36:
[color(yellow)]Baofu[color(white)]
[tab]Hey Amano...
[tab]What the hell did you tell me to say...?
[tab]What does CD woman mean?
[sync][wait][clear][end]

msg_37:
[color(yellow)]Baofu[color(white)]
[tab]Y-You...
[tab]Of course she’d get angry...
[sync][wait][clear][end]

msg_38:
[color(yellow)]Nanjo[color(white)]
[tab]Rumors becoming real...
[tab]If that’s true...
[tab]Takahisa Kandori... are you really alive...?
[sync][wait][clear][end]

msg_39:
[color(yellow)]Nanjo[color(white)]
[tab]That laboratory has tight security. 
[tab]It’s impossible to infiltrate from the ground.
[tab]But, there’s a way in through the sewers.
[sync][wait][clear][end]

msg_40:
[color(yellow)]Nanjo[color(white)]
[tab]Let’s go to the sewage plant.
[sync][wait][clear][end]

msg_41:
[color(yellow)]Elly[color(white)]
[tab]I’m worried about Mr. Kandori, 
[tab]but if fortune telling is being used for evil, 
[tab]I can’t let Wang Long Chizuru get by with it.
[sync][wait][clear][end]

msg_42:
[color(yellow)]Elly[color(white)]
[tab]Actually, one of my friends is a celebrity.
[tab]I’ll ask him for a tour, so it’ll be easy
[tab]to get into the TV station.
[sync][wait][clear][end]

msg_43:
[color(yellow)]Elly[color(white)]
[tab]Now let’s go to Aoba!
[sync][wait][clear][end]

msg_44:
[color(yellow)]Manly Man[color(white)]
[tab]I must refuse...
[tab]What Kei-sama is doing has nothing to do
[tab]with the Nanjo corporation. Remember this...
[sync][wait][clear][end]

msg_45:
[color(yellow)]Matsuoka[color(white)]
[tab]Of course, you will not speak of 
[tab]Kei-sama’s actions. If you do, you’ll regret it.
[tab]Do not forget that...
[sync][wait][clear][end]

msg_46:
[color(yellow)]Private Investigator[color(white)]
[tab]I’ll monitor stocks and the happenings of
[tab]the political world from here.
[sync][wait][clear][end]

msg_47:
[color(yellow)]Private Investigator[color(white)]
[tab]We don’t know when they’ll strike next...
[sync][wait][clear][end]

msg_48:
[color(yellow)]Private Investigator[color(white)]
[tab]There are many trendy, high-class
[tab]stores in the Hotel Pleiades...
[tab]Did you already go?
[sync][wait][clear][end]

msg_49:
[color(yellow)]Private Investigator[color(white)]
[tab]There’s another entrance across from
[tab]here in the south wing...
[tab]Why don’t you go take a look?
[sync][wait][clear][end]
