
msg_0:
[color(yellow)]Ulala[color(white)]
[tab]That’s the media for you...
[tab]Just like Ma-ya said...
[tab]They’ve got ears everywhere.
[sync][wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Hey...
[tab]Don’t be a sore loser.
[tab]You’re the one who drew the short straw...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Baofu[color(white)]
[tab]This isn’t my style...
[tab]Why don’t you get [suou] to do this...
[tab][sync][wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Your style, huh...?
[tab]And what exactly is your style?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]You know what to do, right?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Baofu[color(white)]
[tab]Yeah, but...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Anyway, let’s talk about life or
[tab]what to do with it...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]I thought I’d figure it out when I became
[tab]an adult. But reality is harsh.
[tab]I just got more confused...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Baofu[color(white)]
[tab]...Why are you telling me this?
[sync][wait][clear][end]

msg_9:
[color(yellow)]Ulala[color(white)]
[tab]I don’t know... It’s just that you seem
[tab]to have a purpose. I was just wondering
[tab]what kind of life you’ve lived...
[sync][wait][clear][end]
