
msg_0:
[color(yellow)]Baofu[color(white)]
[tab]How I choose to live has nothing
[tab]to do with you...
[tab]If you want sympathy, ask someone else...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Nnn... Amano...?
[sync][wait][clear][end]

msg_2:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Where is that good-for-nothing little...?
[tab]She’s not going after the scoop!
[sync][wait][clear][end]

msg_3:
[color(yellow)]Baofu[color(white)]
[tab]Ch... Damn they’re quick...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]There’s nothing we can do now...
[tab]Let’s get this over with...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Yeah! You think you’re so smart!
[tab]Well, mister you’ve got another thing comin’!
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Well, you can just keep your damn secrets!
[tab]You know, the whole world doesn’t revolve
[tab]around you!
[sync][wait][clear][end]

msg_7:
[color(yellow)]Baofu[color(white)]
[tab]Those’re some mad acting skills you got...
[tab]O-Okay then...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Baofu[color(white)]
[tab]You’re too damned needy!
[tab]That’s why men always run away from you,
[tab]you CD woman.
[sync][wait][clear][end]

msg_9:
[color(yellow)]Ulala[color(white)]
[tab]What!?
[tab]What did you just say!?
[sync][wait][clear][end]

msg_10:
[color(yellow)]Baofu[color(white)]
[tab]Damn, girl... Watch that shit!
[tab]Are you still drunk!?
[sync][wait][clear][end]

msg_11:
[color(yellow)]Ulala[color(white)]
[tab]I see how it is!
[tab]I guess you want some more, huh!?
[sync][wait][clear][end]

msg_12:
[color(yellow)]Baofu[color(white)]
[tab]N-No... Amano said...
[sync][wait][clear][end]

msg_13:
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab]Hey!!
[tab]Fight somewhere else, will you!?
[tab]The story is getting away!!
[sync][wait][clear][end]

msg_14:
[color(yellow)]Media People[color(white)]
[tab]What!?
[tab]Where, where!?
[sync][wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]Gwa----!?
[sync][wait][clear][end]
