
msg_0:
[color(yellow)]Eikichi[color(white)]
[tab]Daaaah...!!
[tab]Hurry...!! Hurry!!
[tab]Everyone’s already in the car!?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]Hurry up and get your ass in, boy!
[sync][wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Ugyaaaaa!
[tab]They’ve caught up!!
[sync][wait][clear][end]

msg_3:
[color(yellow)]Demonized Sugimoto[color(white)]
[tab]Goaaaaaaaaaaaaaaaahhhhh!!
[tab]Ei----kichi-----!!
[sync][wait][clear][end]

msg_4:
[color(yellow)]Eikichi[color(white)]
[tab]S-Sugimoto!?
[tab]Is that you...?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Nanjo[color(white)]
[tab]Forgive me... young lad...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Eikichi[color(white)]
[tab]S-Stop it-------!
[sync][wait][clear][end]
