
msg_0:
[color(yellow)]Elly[color(white)]
[tab]What happened to them!?
[tab]Kei! Are you alright!?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Nanjo[color(white)]
[tab]We were too late...
[tab]By the time we got back...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Elly[color(white)]
[tab]The New World Order will pay for
[tab]what they’ve done...
[sync][wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Hey...
[tab]This all started when we talked to
[tab]that "Sneak" guy?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]Impossible...
[tab]We were never followed...!
[sync][wait][clear][end]

msg_5:
[color(yellow)]Baofu[color(white)]
[tab]Not this time...
[tab]But there were plenty of chances before...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]We can’t stay here...
[tab]Let’s go back to my place,
[tab]we’ll be safe there...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Nanjo[color(white)]
[tab]This is...!?
[sync][wait][clear][end]

msg_8:
[color(yellow)]Elly[color(white)]
[tab]Kei...
[sync][wait][clear][end]

msg_9:
[color(yellow)]Nanjo[color(white)]
[tab]Mishima...! Yamai...!!
[sync][wait][clear][end]

msg_10:
[color(yellow)]Matsuoka[color(white)]
[tab]Stop it...
[tab]By the time I got back, it was too late...
[sync][wait][clear][end]

msg_11:
[color(yellow)]Matsuoka[color(white)]
[tab]Hurry and give me an order to handle it.
[tab]It will become a nuisance if it doesn’t get
[tab]swept under the rug.
[sync][wait][clear][end]

msg_12:
[color(yellow)]Nanjo[color(white)]
[tab]Wh... why are you the only one still alive!? 
[tab]...You’re the traitor, aren’t you...!?
[sync][wait][clear][end]

msg_13:
[color(yellow)]Matsuoka[color(white)]
[tab]...You’re the one who ignored the warning
[tab]and went off to play with fire. If you plan
[tab]to kill your own men, make it worthwhile.
[sync][wait][clear][end]

msg_14:
[color(yellow)]Nanjo[color(white)]
[tab].........I apologize.
[tab]Please... take care of it...
[sync][wait][clear][end]

msg_15:
[color(yellow)]Ulala[color(white)]
[tab]Hey...
[tab]Couldn’t this have been the work
[tab]of that "Sneak" guy?
[sync][wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]Impossible...
[tab]We were never followed...!
[sync][wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]Not this time...
[tab]But there were plenty of chances before...
[sync][wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]We can’t stay here...
[tab]Let’s go back to my place,
[tab]we’ll be safe there...
[sync][wait][clear][end]
