
msg_0:
[color(yellow)]Matsuoka[color(white)]
[tab]According to our sources, the Nichirinmaru
[tab]is 10 km off the coast of Sumaru Bay...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Matsuoka[color(white)]
[tab]Its cover is a cruise ship, but it seems
[tab]the inside has been modified greatly.
[sync][wait][clear][end]

msg_2:
[color(yellow)]Matsuoka[color(white)]
[tab]The Civil Defense Force’s Troop 15 and
[tab]part of the Sea Division are in his pocket...
[sync][wait][clear][end]

msg_3:
[color(yellow)]Matsuoka[color(white)]
[tab]The government has finally realized it, and
[tab]the Public Safety board and the Defense
[tab]Agency are trying to grasp the situation...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Nanjo[color(white)]
[tab]This is taking too long...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Matsuoka[color(white)]
[tab]But what you are trying to do is not fit
[tab]for the future heir to
[tab]the Nanjo Conglomerate...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Matsuoka[color(white)]
[tab]"Nanjo" has power.
[tab]There are many ways to sink it.
[tab]So, please...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Nanjo[color(white)]
[tab]That’s why I must go.
[tab]It is important for me right now to
[tab]actually witness that power...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Nanjo[color(white)]
[tab]It’s not something I can just inherit.
[sync][wait][clear][end]

msg_9:
[color(yellow)]Matsuoka[color(white)]
[tab]...I understand.
[tab]Do as you wish.
[sync][wait][clear][end]

msg_10:
[color(yellow)]Matsuoka[color(white)]
[tab]Amano-sama...
[tab]Please look after Kei-sama.
[sync][wait][clear][end]

msg_11:
[color(yellow)]Matsuoka[color(white)]
[tab]Yamaoka-san...
[tab]The young master has grown up well.
[tab]It is all thanks to you and his friends...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Matsuoka[color(white)]
[tab]It’s me.
[tab]We are anticipating a confrontation.
[tab]Collect data however you can.
[sync][wait][clear][end]

msg_13:
[color(yellow)]Matsuoka[color(white)]
[tab]Erase any traces of the Nanjo name from
[tab]this incident. Nanjo is clean...
[sync][wait][clear][end]

msg_14:
[color(yellow)]Nanjo[color(white)]
[tab]According to our sources, the Nichirinmaru
[tab]is 10 km off the coast of Sumaru Bay...
[sync][wait][clear][end]

msg_15:
[color(yellow)]Nanjo[color(white)]
[tab]It looks like a cruise ship, but it seems
[tab]the inside has been modified greatly...
[sync][wait][clear][end]

msg_16:
[color(yellow)]Elly[color(white)]
[tab]The informants working for the Nanjo
[tab]Conglomerate are truly thorough...
[tab]Don’t worry about us.
[sync][wait][clear][end]

msg_17:
[color(yellow)]Ulala[color(white)]
[tab]What !? You’re driving !?
[sync][wait][clear][end]

msg_18:
[color(yellow)]Ulala[color(white)]
[tab]I’ve had enough of you and your driving!
[tab]There is no way in hell!!
[sync][wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Quit messin’ around and stand back...
[sync][wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]I’m driving and that’s that...
[sync][wait][clear][end]
