
msg_0:
[color(yellow)]Ulala[color(white)]
[tab]So, what are we gonna do?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Catch Sasaki, or destroy the machine...
[tab]Either way, with all those people, 
[tab]they are going to get mixed up in it!
[sync][wait][clear][end]

msg_2:
[tab]They are going to get mixed up in it!
[choice(2)]What should we do...?
Let’s start a fire!
[end_choice][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab]We’ll use this...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]A fire alarm...? You’re going to tear
[tab]it off and throw it at him?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]No... I meant...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Just joking, just joking.
[tab]I’m not much of a "Joker".
[sync][wait][clear][end]

msg_7:
[color(yellow)]Baofu[color(white)]
[tab]Idiot...
[tab]When you say it, it doesn’t sound like a joke...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab]What!?
[sync][wait][clear][end]

msg_9:
[color(yellow)]Elly[color(white)]
[tab]You’re causing a panic right?
[tab]So what if you send smoke in that duct?
[tab]It should be effective.
[sync][wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Let’s split into 2 groups, one sends smoke
[tab]and charges in, while the other sets off
[tab]the alarm.
[sync][wait][clear][end]

msg_11:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya...
[tab]Does everyone think I’m stupid?
[sync][wait][clear][end]

msg_12:
[color(yellow)]Ulala[color(white)]
[tab]Can’t those two understand that I’m just
[tab]trying to relax this tension?
[tab]Joke and Joker... Wasn’t it funny?
[sync][wait][clear][end]

msg_13:
[color(yellow)]Elly[color(white)]
[tab]Well those two are very rigid.
[sync][wait][clear][end]

msg_14:
[color(yellow)]Katsuya’s laugh[color(white)]
[tab](chuckle). . .
[sync][wait][clear][end]

msg_15:
[color(yellow)]Maya/Ulala/Elly[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_16:
[color(yellow)]Elly[color(white)]
[tab]He just got the joke...?
[sync][wait][clear][end]

msg_17:
[color(yellow)]Katsuya[color(white)]
[tab]We’ll use this...
[sync][wait][clear][end]

msg_18:
[color(yellow)]Ulala[color(white)]
[tab]A fire alarm...? You’re going to tear it off
[tab]and throw it at him?
[sync][wait][clear][end]

msg_19:
[color(yellow)]Katsuya[color(white)]
[tab]No... I meant...
[sync][wait][clear][end]

msg_20:
[color(yellow)]Ulala[color(white)]
[tab]Just joking, just joking.
[sync][wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]Idiot...
[tab]When you say it, it doesn’t sound like a joke...
[sync][wait][clear][end]

msg_22:
[color(yellow)]Ulala[color(white)]
[tab]What!?
[sync][wait][clear][end]

msg_23:
[color(yellow)]Nanjo[color(white)]
[tab]They just have to believe there is a fire.
[tab]So what if you send smoke up at that duct?
[tab]It should be better than just an alarm.
[sync][wait][clear][end]

msg_24:
[color(yellow)]Katsuya[color(white)]
[tab]Let’s split into 2 groups, one sends smoke
[tab]and charges in, while the other sets off
[tab]the alarm.
[sync][wait][clear][end]

msg_25:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya...
[tab]Does everyone think I’m stupid?
[sync][wait][clear][end]

msg_26:
[color(yellow)]Ulala[color(white)]
[tab]Can’t those two understand that I’m just
[tab]trying to relax this tension?
[sync][wait][clear][end]

msg_27:
[color(yellow)]Nanjo[color(white)]
[tab]Those two are very rigid.
[sync][wait][clear][end]

msg_28:
[color(yellow)]Maya/Ulala[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_29:
[color(yellow)]Nanjo[color(white)]
[tab]Is something the matter?
[sync][wait][clear][end]

msg_30:
[color(yellow)]Maya/Ulala[color(white)]
[tab]Nothing...
[sync][wait][clear][end]

msg_31:
[color(yellow)]Ulala[color(white)]
[tab]Haven’t you had enough fires? Besides, 
[tab]I don’t think [suou]-san would let you 
[tab]start one in front of him...
[sync][wait][clear][end]

msg_32:
[color(yellow)]Katsuya[color(white)]
[tab]Actually... I think it’s a good idea...
[sync][wait][clear][end]

msg_33:
[color(yellow)]Ulala[color(white)]
[tab]What the hell? ...Unbelievable...! You were
[tab]always yapping "justice, justice, justice",
[tab]but when it’s Ma-ya, anything is okay?
[sync][wait][clear][end]

msg_34:
[color(yellow)]Katsuya[color(white)]
[tab]No... I meant...
[sync][wait][clear][end]

msg_35:
[color(yellow)]Ulala[color(white)]
[tab]Ohhhh... Ahhhh... Now this is a big surprise.
[tab]With cops like this, this country really
[tab]is finished... I seeeeeee...
[sync][wait][clear][end]

msg_36:
[color(yellow)]Baofu[color(white)]
[tab]Hey stupid... Look up...
[sync][wait][clear][end]

msg_37:
[color(yellow)]Elly[color(white)]
[tab]A fire alarm...
[tab]All we have to do is cause a panic, and we
[tab]wouldn’t even have to burn anything.
[sync][wait][clear][end]

msg_38:
[color(yellow)]Elly[color(white)]
[tab]Though I would kind of like to see it.
[sync][wait][clear][end]

msg_39:
[color(yellow)]Baofu[color(white)]
[tab]We can also burn trash or something at the
[tab]duct. It’ll be better than just an alarm.
[sync][wait][clear][end]

msg_40:
[color(yellow)]Katsuya[color(white)]
[tab]Let’s split into 2 groups, one sends smoke
[tab]and charges in, while the other sets off
[tab]the alarm.
[sync][wait][clear][end]

msg_41:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya...
[tab]Does everyone think I’m stupid?
[sync][wait][clear][end]

msg_42:
[color(yellow)]Ulala[color(white)]
[tab]If you ask me, there’s something wrong with
[tab]you guys for being able to stay so calm
[tab]at a time like this...
[sync][wait][clear][end]

msg_43:
[color(yellow)]Elly[color(white)]
[tab]Don’t worry.
[tab]You seem so... natural, I’m envious...
[sync][wait][clear][end]

msg_44:
[color(yellow)]Elly[color(white)]
[tab]I hear women are more likable if
[tab]they’re a little air-headed.
[sync][wait][clear][end]

msg_45:
[color(yellow)]Ulala[color(white)]
[tab]Gee, thanks...
[sync][wait][clear][end]

msg_46:
[color(yellow)]Ulala[color(white)]
[tab]Haven’t you had enough fires? Besides, I
[tab]don’t think [suou]-san would let you start one
[tab]in front of him...
[sync][wait][clear][end]

msg_47:
[color(yellow)]Katsuya[color(white)]
[tab]Actually... I think it’s a good idea...
[sync][wait][clear][end]

msg_48:
[color(yellow)]Ulala[color(white)]
[tab]What the hell? ...Unbelievable...! You were
[tab]always yapping "justice, justice, justice",
[tab]but when it’s Ma-ya, anything is okay?
[sync][wait][clear][end]

msg_49:
[color(yellow)]Katsuya[color(white)]
[tab]No... I meant...
[sync][wait][clear][end]

msg_50:
[color(yellow)]Ulala[color(white)]
[tab]Ohhhh... Ahhhh... Now this is a big surprise.
[tab]With cops like this, this country really
[tab]is finished... I seeeeeee...
[sync][wait][clear][end]

msg_51:
[color(yellow)]Baofu[color(white)]
[tab]Hey stupid... Look up...
[sync][wait][clear][end]

msg_52:
[color(yellow)]Nanjo[color(white)]
[tab]A fire alarm, huh...
[tab]As long as people BELIEVE there is a
[tab]fire, we don’t actually need to set one.
[sync][wait][clear][end]

msg_53:
[color(yellow)]Nanjo[color(white)]
[tab]How about burning some trash at the duct
[tab]too? If we make a little smoke, it should
[tab]be much more effective than just an alarm.
[sync][wait][clear][end]

msg_54:
[color(yellow)]Katsuya[color(white)]
[tab]Let’s split into 2 groups, one sends smoke
[tab]and charges in, while the other sets off
[tab]the alarm.
[sync][wait][clear][end]

msg_55:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya...
[tab]Does everyone think I’m stupid?
[sync][wait][clear][end]

msg_56:
[color(yellow)]Ulala[color(white)]
[tab]If you ask me, there’s something wrong with
[tab]you guys for being able to stay so calm
[tab]at a time like this...
[sync][wait][clear][end]

msg_57:
[color(yellow)]Nanjo[color(white)]
[tab]Your reaction is relatively normal.
[tab]Everybody is just used to these situations...
[sync][wait][clear][end]

msg_58:
[color(yellow)]Nanjo[color(white)]
[tab]What I don’t understand is Ms. Amano...
[tab]Where does your "d五j二 vu" originate from?
[sync][wait][clear][end]

msg_59:
[color(yellow)]Ulala[color(white)]
[tab]Damn, that Baofu pisses me off...
[tab]He calls me an idiot all the time!
[sync][wait][clear][end]

msg_60:
[color(yellow)]Elly[color(white)]
[tab]Let’s go...
[tab]The guys are waiting.
[sync][wait][clear][end]

msg_61:
[color(yellow)]Nanjo[color(white)]
[tab]Let’s go now.
[tab]The guys are waiting for us.
[sync][wait][clear][end]

msg_62:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_63:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_64:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_65:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_66:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_67:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_68:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_69:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_70:
[color(yellow)]Toilet[color(green)]
[tab]No one is inside. [color(white)]
[sync][wait][clear][end]

msg_71:
[color(yellow)]Janitor’s Closet[color(green)]
[tab]It won’t open.[color(white)]
[sync][wait][clear][end]
