
msg_0:
[color(yellow)]Yung Pao[color(white)]
[tab]X-1, General Sugawara’s pride and joy...
[tab]Such accuracy...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Yung Pao[color(white)]
[tab]Tatsuzou must be at sea now... 
[tab]He releasing Blue Dragon in Undersea ruins...
[tab]His ship the Nichirinmaru...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Yung Pao[color(white)]
[tab]You see Tatsuzou...
[tab]Tell him... I be waiting for him in Hell...
[sync][wait][clear][end]

msg_3:
[color(yellow)]Baofu[color(white)]
[tab]Don’t worry, he’ll be joining you shortly...
[tab]I’ll make sure of that...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]What were you going to do if I shot...?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]I know you wouldn’t...
[tab]It’s not your style...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]Ha...
[tab]Maybe... Maybe not...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_8:
[color(yellow)]Elly[color(white)]
[tab]Come on! You heard what the dead guy said...
[end]

msg_9:
[tab]We have to go after Tatsuzou...
[sync][wait][clear][end]

msg_10:
[color(yellow)]Elly[color(white)]
[tab]Kei’s cruiser is at the harbor...
[end]

msg_11:
[tab]Let’s try to get a hold of him.
[sync][wait][clear][end]

msg_12:
[color(yellow)]Nanjo[color(white)]
[tab]Well, we have no time to lose.
[end]

msg_13:
[tab]Let us pursue Tatsuzou at once.
[tab]My cruiser is docked at the harbor.
[sync][wait][clear][end]
