
msg_0:
[color(yellow)]Ulala[color(white)]
[tab]I’m going to call the guys in.
[tab]Take the vent cover off...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Hey guys, you can come in now...
[tab]We found it...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Katsuya[color(white)]
[tab]Let’s move... I don’t want to get caught
[tab]hanging around in a women’s restroom...
[sync][wait][clear][end]
