
msg_0:
[color(yellow)]Elly[color(white)]
[tab]Maki, aren’t Brown and Mark here yet?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Maki[color(white)]
[tab]Yeah, they’re still at Ms. Saeko’s.
[end]

msg_2:
[tab]Yuka started crying and it’s all a mess.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Nanjo[color(white)]
[tab]Do not mind me.
[end]

msg_4:
[tab]Today’s my last day...
[tab]There just won’t be enough time.
[sync][wait][clear][end]

msg_5:
[color(yellow)]Elly[color(white)]
[tab]This school holds so many memories...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Maki[color(white)]
[tab]But, you’re going away to England...
[end]

msg_7:
[tab]That’s so far away...
[sync][wait][clear][end]

msg_8:
[color(yellow)]Nanjo[color(white)]
[tab]Yeah, we won’t be able to meet.
[end]

msg_9:
[tab]But the distance amidst us will never change...
[end]

msg_10:
[tab]Right?
[sync][wait][clear][end]

msg_11:
[color(yellow)]Boy with Earring[color(white)]
[tab]...Yeah.
[sync][wait][clear][end]

msg_12:
[color(yellow)]Matsuoka[color(white)]
[tab]I’ve come to pick you up.
[sync][wait][clear][end]

msg_13:
[color(yellow)]Maki[color(white)]
[tab]Hey, let’s make a pact!
[end]

msg_14:
[tab]If our dreams come true, we’ll meet again!
[sync][wait][clear][end]

msg_15:
[color(yellow)]Nanjo[color(white)]
[tab]Hmm... that’s a splendid idea...
[sync][wait][clear][end]

msg_16:
[color(yellow)]Nanjo[color(white)]
[tab]I’ll one day be the No. 1 man in the world.
[end]

msg_17:
[tab]Promise me you’ll have a great dream, too.
[sync][wait][clear][end]

msg_18:
[color(yellow)]Boy with Earring[color(white)]
[tab]Yeah... I promise.
[sync][wait][clear][end]
