
msg_0:
[color(yellow)]Philemon[color(white)]
[tab]Has playing the role of a father made you soft,
[tab]Crawling Chaos... Nyarlathotep? I think now
[tab]you should better understand what I said.
[delay(30)][end]

msg_1:
You should be able to understand what I say.
[sync][wait][clear][end]

msg_2:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Ha...[delay(30)]
[tab]You were right that these humans may
[tab]make for good test cases...
[sync][wait][clear][end]

msg_3:
[color(yellow)]Ginko[color(white)]
[tab]What is he saying...? Philemon!?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Philemon[color(white)]
[tab]We are the sources of people’s souls...[delay(30)]
[tab]Incarnations of the collective unconsciousness,
[tab]indivisible from one another...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Philemon[color(white)]
[tab]We have watched man’s strivings for eons...[delay(30)]
[tab]I lead those with strong hearts, and the
[tab]Crawling Chaos drags the weak into the abyss.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Philemon[color(white)]
[tab]All of this is to ascertain if man’s souls,
[tab]riddled with contradictions as they are,
[tab]can evolve into something whole.
[sync][wait][clear][end]

msg_7:
[color(yellow)]Philemon[color(white)]
[tab]You all showed that potential. If there were
[tab]more like you, man could someday reach a
[tab]perfect state that understood its purpose.
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]Everything...[delay(30)]
[tab]This is all part of your experiment!?
[sync][wait][clear][end]

msg_9:
[color(yellow)]Nyarlathotep[color(white)]
[tab]You should show more respect to me.[delay(30)]
[end]

msg_10:
[tab]The best HE can do is watch. But me...
[tab]I’m different.
[sync][wait][clear][end]

msg_11:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . !?
[sync][wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[tab]Maya-nee!!
[sync][wait][clear][end]

msg_13:
[color(yellow)]Eikichi[color(white)]
[tab]Dammit, Ginko, hurry up and bust out a
[tab]Dia or something here!
[sync][wait][clear][end]

msg_14:
[color(yellow)]Ginko[color(white)]
[tab]I’m trying!
[end]

msg_15:
[tab]But... But...
[tab]The bleeding won’t stop!
[sync][wait][clear][end]

msg_16:
[color(yellow)]Ginko[color(white)]
[tab]Why...[delay(30)]
[end]

msg_17:
[tab]Why aren’t my spells working!?
[tab]Philemon!
[sync][wait][clear][end]

msg_18:
[color(yellow)]Philemon[color(white)]
[tab]Nyarlathotep...[delay(30)]
[tab]This was your reason for creating the 
[tab]legend of the Spear of Destiny...
[sync][wait][clear][end]

msg_19:
[color(yellow)]Nyarlathotep[color(white)]
[tab]They say that when Jesus Christ’s corpse was
[tab]pierced with that spear, blood continued to
[tab]spill endlessly...
[sync][wait][clear][end]

msg_20:
[color(yellow)]Nyarlathotep[color(white)]
[tab]You humans have passed that legend down for
[tab]2,000 years... It’s one hell of a strong rumor.
[tab]A fatal wound would take effect immediately.
[sync][wait][clear][end]

msg_21:
[color(yellow)]Maya[color(white)]
[tab]. . . . .
[sync][wait][clear][end]

msg_22:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . .
[sync][wait][clear][end]

msg_23:
[color(yellow)][tatsuya][color(white)]
[tab]"Hurry up and forget about me?"...
[tab]Don’t be ridiculous...!!
[tab]How could I ever forget...!!?
[sync][wait][clear][end]

msg_24:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . .
[sync][wait][clear][end]

msg_25:
[color(yellow)][tatsuya][color(white)]
[tab]Yeah... I’ll grab it...
[tab]You taught me...
[tab]I’ll grab hold of my dream... so...
[sync][wait][clear][end]

msg_26:
[color(yellow)][tatsuya][color(white)]
[tab]. . . . . .
[end]

msg_27:
[tab]Noooooooooooooooooooooooooo!!!
[sync][wait][clear][end]

msg_28:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Haha... Anyone has the power to achieve their
[tab]dreams, eh?[delay(30)] Your namesake, deluded to the end,
[tab]has been sacrificed. The dream is fulfilled!
[sync][wait][clear][end]

msg_29:
[color(yellow)]Nyarlathotep[color(white)]
[tab]And out of respect for that, I’ll grant you
[tab]the dream of destruction that you humans
[tab]always wanted!
[sync][wait][clear][end]
