
msg_0:
[color(yellow)]Eikichi[color(white)]
[tab]Goddamn cursed creeps!
[tab]What’s with this school!? 
[tab]What did I do to deserve this!?[wait][clear][end]

msg_1:
[color(yellow)]Lisa[color(white)]
[tab]Serves you right for coming to Sevens
[tab]with a Cuss High emblem on![wait][clear][end]

msg_2:
[color(yellow)]Eikichi[color(white)]
[tab]WHAT!?
[tab]Okay, back up! This whole thing
[tab]happened because YOU summoned that Joker![wait][clear][end]

msg_3:
[color(yellow)]Eikichi[color(white)]
[tab]So take some responsibility and do
[tab]something about this!
[wait][clear][end]

msg_4:
[color(yellow)]Lisa[color(white)]
[tab]Kehhei! Now you’ve crossed a line, buster!
[tab]How was I supposed to know at the time
[tab]what would happen!?
[wait][clear][end]

msg_5:
[color(yellow)]Lisa[color(white)]
[tab]And what’s with all your big talk!? You’re
[tab]just an Undie Boss who pervs on people
[tab]by yanking their pants down!
[wait][clear][end]

msg_6:
[color(yellow)]Lisa[color(white)]
[tab]You frickin’ Undie Boss...!!
[tab]Undie Boss! Undie Boss!
[wait][clear][end]

msg_7:
[color(yellow)]Eikichi[color(white)]
[tab]That’s rich, coming from you! You’re a
[tab]frickin’ white girl but you talk Japanese,
[tab]when you’re not spouting nonsense words!
[wait][clear][end]

msg_8:
[color(yellow)]Eikichi[color(white)]
[tab]Do you even know what country you’re from!?
[tab]Maybe I should give you a name you can
[tab]understand easier!
[wait][clear][end]

msg_9:
[color(yellow)]Eikichi[color(white)]
[tab]You’re Ginko from now on!
[tab]Ginko Ginko Ginko!
[wait][clear][end]

msg_10:
[color(yellow)]Ginko[color(white)]
[tab]Fanna! No you don’t! You’re not saddling
[tab]me with a lame nickname like that!
[wait][clear][end]

msg_11:
[color(yellow)][tatsuya]’s Voice[color(white)]
[tab]We used the Master Joker, who was said to
[tab]make dreams come true, and became targets
[tab]of revenge by the Joker...
[wait][clear][color(yellow)][tatsuya]’s Voice[color(white)]
[tab]While we were looking for the Principal
[tab]who was said to be connected to the Joker...
[tab]Maya-nee appeared before us...[wait][clear][color(yellow)][tatsuya]’s Voice[color(white)]
[tab]We decided to go after Joker together...
[wait][clear][end]
