
msg_0:
[color(yellow)]System[color(white)]
[tab]Effectのテストを開始します。
[tab][choice(8)][tab]はじめから
[tab]Aから
[tab]10から
[tab]1Aから
[tab]20から
[tab]2Aから
[tab]30から
[tab]3Aから
[tab][end_choice][clear][sync][wait][clear][end]

msg_1:
Effect00[sync][wait][clear][end]

msg_2:
Effect01[sync][wait][clear][end]

msg_3:
Effect02[sync][wait][clear][end]

msg_4:
Effect03[sync][wait][clear][end]

msg_5:
Effect04[sync][wait][clear][end]

msg_6:
Effect05[sync][wait][clear][end]

msg_7:
Effect06[sync][wait][clear][end]

msg_8:
Effect07[sync][wait][clear][end]

msg_9:
Effect08[sync][wait][clear][end]

msg_10:
Effect09[sync][wait][clear][end]

msg_11:
Effect0A[sync][wait][clear][end]

msg_12:
Effect0B[sync][wait][clear][end]

msg_13:
Effect0C[sync][wait][clear][end]

msg_14:
Effect0D[sync][wait][clear][end]

msg_15:
Effect0E[sync][wait][clear][end]

msg_16:
Effect0F[sync][wait][clear][end]

msg_17:
Effect10[sync][wait][clear][end]

msg_18:
Effect11[sync][wait][clear][end]

msg_19:
Effect12[sync][wait][clear][end]

msg_20:
Effect13[sync][wait][clear][end]

msg_21:
Effect14[sync][wait][clear][end]

msg_22:
Effect15[sync][wait][clear][end]

msg_23:
Effect16[sync][wait][clear][end]

msg_24:
Effect17[sync][wait][clear][end]

msg_25:
Effect18[sync][wait][clear][end]

msg_26:
Effect19[sync][wait][clear][end]

msg_27:
Effect1A[sync][wait][clear][end]

msg_28:
Effect1B[sync][wait][clear][end]

msg_29:
Effect1C[sync][wait][clear][end]

msg_30:
Effect1D[sync][wait][clear][end]

msg_31:
Effect1E[sync][wait][clear][end]

msg_32:
Effect1F[sync][wait][clear][end]

msg_33:
Effect20[sync][wait][clear][end]

msg_34:
Effect21[sync][wait][clear][end]

msg_35:
Effect22[sync][wait][clear][end]

msg_36:
Effect23[sync][wait][clear][end]

msg_37:
Effect24[sync][wait][clear][end]

msg_38:
Effect25[sync][wait][clear][end]

msg_39:
Effect26[sync][wait][clear][end]

msg_40:
Effect27[sync][wait][clear][end]

msg_41:
Effect28[sync][wait][clear][end]

msg_42:
Effect29[sync][wait][clear][end]

msg_43:
Effect2A[sync][wait][clear][end]

msg_44:
Effect2B[sync][wait][clear][end]

msg_45:
Effect2C[sync][wait][clear][end]

msg_46:
Effect2D[sync][wait][clear][end]

msg_47:
Effect2E[sync][wait][clear][end]

msg_48:
Effect2F[sync][wait][clear][end]

msg_49:
Effect30[sync][wait][clear][end]

msg_50:
Effect31[sync][wait][clear][end]

msg_51:
Effect32[sync][wait][clear][end]

msg_52:
Effect33[sync][wait][clear][end]

msg_53:
Effect34[sync][wait][clear][end]

msg_54:
Effect35[sync][wait][clear][end]

msg_55:
Effect36[sync][wait][clear][end]

msg_56:
Effect37[sync][wait][clear][end]

msg_57:
Effect38[sync][wait][clear][end]

msg_58:
Effect39[sync][wait][clear][end]

msg_59:
Effect3A[sync][wait][clear][end]

msg_60:
Effect3B[sync][wait][clear][end]

msg_61:
Effect3C[sync][wait][clear][end]

msg_62:
Effect3D[sync][wait][clear][end]

msg_63:
Effect3E[sync][wait][clear][end]

msg_64:
Effect3F[sync][wait][clear][end]

msg_65:
[color(yellow)]System[color(white)]
[tab]Effectのテストを終了します
[sync][wait][clear][end]
