
msg_0:
[color(yellow)]Katsuya[color(white)]
[tab]The Kegare they got from the people...
[tab]They’re transporting it... somewhere...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]We can’t just destroy that thing without
[tab]giving it some thought first...
[tab]They saved up some pretty nasty things.
[sync][wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]How much is in there...?
[tab]The back is all hazy, so I can’t see...
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]I cannot run away from my sin...
[tab]so easily...
[tab]I have to atone for my sin by myself...
[sync][wait][clear][end]
