
msg_0:
[color(yellow)]Baofu[color(white)]
[tab]I’m sorry... Miki...
[tab]I finally understand...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]The person I couldn’t forgive...
[tab]was... me...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Baofu[color(white)]
[tab]Back then, I was just a hot-shot...
[tab]I wasn’t able to do anything...
[end]

msg_3:
[tab]In the end, I got you killed...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]It wasn’t the Persona, it wasn’t the law...
[end]

msg_5:
[tab]It was me who couldn’t think of
[tab]anything but myself...!!
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Bao... fu...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Baofu[color(white)]
[tab]Now you see...[delay(30)]
[end]

msg_8:
[tab]I was planning to use you guys from
[tab]the beginning!
[sync][wait][clear][end]

msg_9:
[color(yellow)]Ulala[color(white)]
[tab]That’s... enough...
[sync][wait][clear][end]

msg_10:
[color(yellow)]Baofu[color(white)]
[tab]Go ahead and laugh...
[end]

msg_11:
[tab]My attempt at revenge was pointless...
[end]

msg_12:
[tab]I’m no different from Tatsuzou!!
[sync][wait][clear][end]

msg_13:
[color(yellow)]Ulala[color(white)]
[tab]Stop it...!!
[sync][wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]Get a hold of yourself!
[end]

msg_15:
[tab]Why did you even come here...?
[tab]Tatsuzou is dead... You got your wish.
[sync][wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]If you can’t say it, I will.
[end]

msg_17:
[tab]You knew all along that you were stuck in
[tab]the past... That’s why you came here.
[sync][wait][clear][end]

msg_18:
[color(yellow)]Katsuya[color(white)]
[tab]Stop looking down on yourself...
[end]

msg_19:
[tab]Isn’t it... about time to start over...?
[sync][wait][clear][end]

msg_20:
[color(yellow)]Katusya[color(white)]
[tab]Let it go, Baofu!
[tab]You ought to cherish those
[tab]memories you had with her.
[sync][wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]Alright... I’m okay now...
[sync][wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]Did you all like my acting skills?
[tab]That was pretty good, huh?
[sync][wait][clear][end]

msg_24:
[color(yellow)]Baofu[color(white)]
[tab]Serizawa...
[sync][wait][clear][end]

msg_25:
[color(yellow)]Ulala[color(white)]
[tab]What...?
[sync][wait][clear][end]

msg_26:
[color(yellow)]Baofu[color(white)]
[tab]That was for the time at the bar.
[end]

msg_27:
[tab]Fooled y’all, didn’t I?
[sync][wait][clear][end]

msg_28:
[color(yellow)]Ulala[color(white)]
[tab].........It looks that way.
[sync][wait][clear][end]

msg_29:
[color(yellow)]Baofu[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_30:
[color(yellow)]Katsuya/Maya/[tatsuya][color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_31:
[color(yellow)]Baofu[color(white)]
[tab]How pathetic...
[tab]Everything’s... out in the open...
[sync][wait][clear][end]

msg_32:
[color(yellow)]Baofu[color(white)]
[tab]Now you see...
[end]

msg_33:
[tab]I was planning to use you guys from
[tab]the beginning!
[sync][wait][clear][end]

msg_34:
[color(yellow)]Baofu[color(white)]
[tab]Somewhere inside, I knew...
[tab]That I couldn’t do anything by myself...
[sync][wait][clear][end]

msg_35:
[color(yellow)]Baofu[color(white)]
[tab]Heh... I wanted revenge so bad...
[tab]But I couldn’t do it by myself...
[end]

msg_36:
[tab]I didn’t even give you my real name...
[sync][wait][clear][end]

msg_37:
[color(yellow)]Ulala[color(white)]
[tab]...I ...I think that’s a nice... name...!
[end]

msg_38:
[tab]I... I think it’s a cool name...!
[tab]It has a nice ring to it...
[sync][wait][clear][end]

msg_39:
[color(yellow)]Katsuya[color(white)]
[tab]I was thinking... and now it’s clear...[delay(30)]
[end]

msg_40:
[tab]"Kaoru Saga" died on duty 5 years ago...
[sync][wait][clear][end]

msg_41:
[color(yellow)]Katsuya[color(white)]
[tab]The man in front of me is a completely
[tab]different person than the one we saw...
[sync][wait][clear][end]

msg_42:
[color(yellow)]Katsuya[color(white)]
[tab]A bit misguided, perhaps...[delay(30)]
[end]

msg_43:
[tab]A "free spirit"...
[tab]A "loveable lush"...
[sync][wait][clear][end]

msg_44:
[color(yellow)]Ulala[color(white)]
[tab]...Didn’t you forget "twisted person"?
[sync][wait][clear][end]

msg_45:
[color(yellow)]Baofu[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_46:
[color(yellow)]Baofu[color(white)]
[tab]Ch... Don’t put me in the same shot glass
[tab]as those sentimental wussies...
[sync][wait][clear][end]

msg_47:
[color(yellow)]Baofu[color(white)]
[tab]And you know what, [suou]?
[end]

msg_48:
[tab]You’re not cut out to be a police officer.
[end]

msg_49:
[tab]Investigations are supposed to be...
[sync][wait][clear][end]

msg_50:
[color(yellow)]Ulala[color(white)]
[tab]Ma-ya...
[tab]Remember when I was all jazzed
[tab]about that match-making party...?
[sync][wait][clear][end]

msg_51:
[color(yellow)]Ulala[color(white)]
[tab]Well... the Wang Long came up with:
[tab]"Today’s a day of fateful meetings."
[tab]Maybe... it was right...
[sync][wait][clear][end]

msg_52:
[color(yellow)]Ulala[color(white)]
[tab]Ma-ya... You remember that fortune
[tab]I told you about in the beginning?
[end]

msg_53:
[tab]I think... it’s right...
[sync][wait][clear][end]

msg_54:
[color(yellow)]Katsuya[color(white)]
[tab]Geez, what an antisocial Baofu...
[tab]Serizawa-kun must have a difficult time.
[sync][wait][clear][end]

msg_55:
[color(yellow)]Baofu[color(white)]
[tab]Well... um... ya know...[delay(30)]
[end]

msg_56:
[tab]There’s a lot... in life...[delay(30)]
[sync][wait][clear][end]

msg_57:
[color(yellow)][tatsuya][color(white)]
[tab]I’ve never met anyone like this
[tab]guy before...
[sync][wait][clear][end]
