
msg_0:
[color(yellow)]Nyarlathotep[color(white)]
[tab]I’m glad you made it here without dying.
[tab]Of course, it would be dull for you to die
[tab]so easily.
[sync][wait][clear][end]

msg_1:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Now, Maya Amano...
[tab]After coming here, what are you angry at?
[sync][wait][clear][end]

msg_2:
[tab]After coming here, what are you angry at?
[choice(2)]At you...!
I’m just... very sad...
[end_choice][clear][end]

msg_3:
[color(yellow)]Nyarlathotep[color(white)]
[tab]It’s an honor. Well then, you can move on ahead. 
[tab]I shall watch you struggle a little while longer.
[sync][wait][clear][end]

msg_4:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Hmph... How sentimental...
[tab]What are you so sad about?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Now, go ahead and shoot.
[tab]Deep down inside, I know you hate me. 
[tab]Pull the trigger.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Well then, I’ll say the one thing 
[tab]you want to hear the least. 
[tab]The young man who holds your heart... He’s mine.
[sync][wait][clear][end]

msg_7:
[color(yellow)]Nyarlathotep[color(white)]
[tab]He’s a toy in the shape of a human!
[tab]He’ll never be yours! Never!!
[sync][wait][clear][end]

msg_8:
[tab]He’ll never be yours! Never!!
[choice(2)]Pull the trigger.
Don’t pull the trigger.
[end_choice][clear][end]

msg_9:
[color(yellow)][tatsuya][color(white)]
[tab]Wh... at...?
[sync][wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]!?
[sync][wait][clear][end]

msg_11:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Hahahahahaha!
[tab]You simply don’t learn, do you?
[tab]I told you that I am you...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Nyarlathotep[color(white)]
[tab]People who think that they are strong are weak, 
[tab]especially when their loved ones suffer...
[sync][wait][clear][end]

msg_13:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_14:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Yes, that’s good...
[sync][wait][clear][end]

msg_15:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Let your impulses control you!
[tab]That is what it means to be a human!!
[tab]Hahaha...!!
[sync][wait][clear][end]

msg_16:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Hmph... This will be something to watch.
[tab]How long can you keep this up?
[sync][wait][clear][end]

msg_17:
[color(yellow)]Ulala[color(white)]
[tab]Going through all this, and you’re not
[tab]supposed to get upset!? 
[tab]I ain’t no nun or priest! I can’t stand it!!
[sync][wait][clear][end]

msg_18:
[color(yellow)]Katsuya[color(white)]
[tab]Amano-kun, I know exactly how it feels...
[tab]But calm down...
[tab]I finally understand...
[sync][wait][clear][end]

msg_19:
[color(yellow)]Katsuya[color(white)]
[tab]Anger, ignorance, vengeance...
[tab]He is trying to coax the shadows of our
[tab]hearts to gain power... Don’t listen to him.
[sync][wait][clear][end]

msg_20:
[color(yellow)]Katsuya[color(white)]
[tab]Amano-kun, stay strong...
[tab]He is trying to coax the shadows of our
[tab]hearts to gain power... I finally understand.
[sync][wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]That’s definitely a human...
[tab]The way he looks down on others,
[tab]that’s something only humans can do...
[sync][wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]Heh... All right... I’ll tango with ya.
[tab]As another human...
[sync][wait][clear][end]

msg_23:
[color(yellow)][tatsuya][color(white)]
[tab]You don’t... have to worry...
[tab]I said it before...
[tab]I can withstand this pain...
[sync][wait][clear][end]

msg_24:
[color(yellow)][tatsuya][color(white)]
[tab]I’ve never seen such an angry face...
[tab]...since that time...
[sync][wait][clear][end]

msg_25:
[color(yellow)][tatsuya][color(white)]
[tab]It’s alright...
[tab]That sadness... will end soon...
[sync][wait][clear][end]
