
msg_0:
[color(yellow)]Mummy of Tatsunoshin [suou][color(white)]
[tab]Who calls me back to this world...?
[sync][wait][clear][end]

msg_1:
[color(yellow)]Mummy of Tatsunoshin [suou][color(white)]
[tab]How...! Damn you Kiyotada...
[tab]If you are saying that you will defeat Kiyotada...
[tab]I will gladly lend my power...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Mummy of Tatsunoshin [suou][color(white)]
[tab]Junnosuke... Is Junnosuke there...?
[sync][wait][clear][end]

msg_3:
[color(yellow)]Ghost of Junnosuke Kuroda[color(white)]
[tab]Junnosuke... is here...
[sync][wait][clear][end]

msg_4:
[color(yellow)]Mummy of Tatsunoshin [suou][color(white)]
[tab]Junnosuke... it’s off to battle...!
[sync][wait][clear][end]

msg_5:
[color(yellow)]Ghost of Junnosuke Kuroda[color(white)]
[tab]Understood...
[sync][wait][clear][end]

msg_6:
[color(green)]The Persona of Tatsunoshin [suou]
can now be summoned in the Velvet Room.[color(white)]
[sync][wait][clear][end]

msg_7:
[color(green)]The Personas of Tatsunoshin [suou] and
Junnosuke Kuroda can now be summoned
in the Velvet Room.[color(white)]
[sync][wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]A legend returns as a rumor...
[tab]It doesn’t make me feel good being
[tab]forced to call upon the dead...
[sync][wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]His name being [suou] means that
[tab]he’s [tatsuya] and Katsuya’s ancestor...?
[tab]Couldn’t be...
[sync][wait][clear][end]

msg_10:
[color(yellow)]Ulala[color(white)]
[tab]We gotta hold a memorial service later
[tab]so we won’t be damned.
[sync][wait][clear][end]

msg_11:
[color(yellow)][tatsuya][color(white)]
[tab]I feel... like I knew him from before...
[sync][wait][clear][end]
