
msg_0:
[color(yellow)]Tatsuzou[color(white)]
[tab]Mad you say...?
[end]

msg_1:
[tab]This world is what’s gone mad!
[end]

msg_2:
[tab]Tell me what is stirring this country!!
[sync][wait][clear][end]

msg_3:
[color(yellow)]Tatsuzou[color(white)]
[tab]Fronts, fatigue, and contradictions...
[end]

msg_4:
[tab]People think only of themselves!! 
[tab]And so, punishment will be yours again!!
[sync][wait][clear][end]

msg_5:
[color(yellow)]Tatsuzou[color(white)]
[tab]This world is decayed...
[tab]The law, the system, and all humans
[tab]who live off of it!!
[sync][wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]Damn you, Tatsuzou!
[end]

msg_7:
[tab]What right do you have to judge us!?
[sync][wait][clear][end]

msg_8:
[color(yellow)]Baofu[color(white)]
[tab]That’s bullshit...
[tab]Deceiving people with stupid curses...
[end]

msg_9:
[tab]Your deception ends here, old man!
[sync][wait][clear][end]

msg_10:
[color(yellow)]Tatsuzou[color(white)]
[tab]Fools... You don’t understand human nature.
[tab]Curses and fortunes were things you wanted!
[sync][wait][clear][end]

msg_11:
[color(yellow)]Tatsuzou[color(white)]
[tab]Look down there!
[end]

msg_12:
[tab]People are still curious about fortunes,
[tab]jinxes, and wish for good luck...
[sync][wait][clear][end]

msg_13:
[color(yellow)]Tatsuzou[color(white)]
[tab]You cannot stop a heart that involuntarily
[tab]pumps its blood for curses...!
[tab]Or the pulsing power of life it brings!
[sync][wait][clear][end]

msg_14:
[color(yellow)]Tatsuzou[color(white)]
[tab]Arise, Gozen! I have delivered you the
[tab]Kegare of my sinful compatriots!
[end]

msg_15:
[tab]Let people’s words become a reality!!
[sync][wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]Sudou...!? You bastard...!!
[sync][wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]You’ve finally gone mad... Tatsuzou!!
[sync][wait][clear][end]
