
msg_0:
[color(yellow)]Ulala/Maya[color(white)]
[tab]Oh my God!
[sync][wait][clear][end]

msg_1:
[color(yellow)]Tatsuzou[color(white)]
[tab]Hahaha!! Hya--hahaha!!
[end]

msg_2:
[tab]Behold!! The Earth Dragon will
[tab]destroy Earth along with Joka!!
[sync][wait][clear][end]

msg_3:
[color(yellow)]Tatsuzou[color(white)]
[tab]The axis will shift and people shall die!!
[end]

msg_4:
[tab]I have transformed history!!
[end]

msg_5:
[tab]What is life if you can’t even bear this!?
[sync][wait][clear][end]

msg_6:
[color(yellow)]Tatsuzou[color(white)]
[tab]Gwo...!?
[tab]GGGGGGG... G-Gozen...
[tab]Why me too------!?
[sync][wait][clear][end]

msg_7:
[color(yellow)]Detested Hunter[color(white)]
[tab]SHAGYAAAAAAA!!
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]Another one... has fallen...
[sync][wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]What a pathetic sight... Tatsuzou...
[tab]THIS is the result of deceiving people!?
[sync][wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Your dirty sins... We shall cleanse them!
[sync][wait][clear][end]
