
msg_0:
[color(yellow)]Katsuya[color(white)]
[tab]What do you want, calling me here...?
[sync][wait][clear][end]

msg_1:
[color(yellow)][tatsuya] from This Side[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_2:
[color(yellow)]Katsuya[color(white)]
[tab]...That’s rare.
[tab]I think it’s gonna start raining.
[sync][wait][clear][end]

msg_3:
[color(yellow)][tatsuya] from This Side[color(white)]
[tab]...My hand moved on its own.
[sync][wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_5:
[color(yellow)][tatsuya] from This Side[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_6:
[color(yellow)][tatsuya] from This Side[color(white)]
[tab]Hey... Bro...
[tab]Is it hard... to become a detective?
[sync][wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya] from This Side[color(white)]
[tab]...Won’t Pops... get upset...?
[sync][wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]Yeah right...
[sync][wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Alright, I’ll teach you the ways
[tab]of a detective...
[sync][wait][clear][end]

msg_11:
[color(yellow)][tatsuya] from This Side[color(white)]
[tab]You started up smoking again...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Yeah... With all that’s happened...
[sync][wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Listen up, a detective is...
[sync][clear][end]
