
msg_0:
[color(yellow)]Nyarlathotep[color(white)]
[tab]It... can’t be...!?
[tab]It’s not possible...!!
[tab]This contradiction... I won’t accept i---t!!
[sync][wait][clear][end]

msg_1:
[color(yellow)]Philemon[color(white)]
[tab]Crawling Chaos, accept your defeat...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Philemon!!
[sync][wait][clear][end]

msg_3:
[color(yellow)]Philemon[color(white)]
[tab]They represent the potential of mankind.
[tab]You, the dark side of the collective
[tab]unconsciousness, are linked to all humans.
[sync][wait][clear][end]

msg_4:
[color(yellow)]Philemon[color(white)]
[tab]THAT is why...
[tab]They... moved the hearts of the people...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]All potential is born from chaos...
[tab]I see... That’s right...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Hmph...
[sync][wait][clear][end]

msg_7:
[color(yellow)]Nyarlathotep[color(white)]
[tab]Muhahaha...!!
[tab]What irony!!
[tab]THIS is my FATE...!?
[sync][wait][clear][end]

msg_8:
[color(yellow)]Nyarlathotep[color(white)]
[tab]But... remember this...!
[tab]The masses of idiocy that squirm in the
[tab]center of the cosmos are yourselves...!!
[sync][wait][clear][end]

msg_9:
[color(yellow)]Nyarlathotep[color(white)]
[tab]As long as you exist... so too shall I...!!
[sync][wait][clear][end]

msg_10:
[color(yellow)]Baofu[color(white)]
[tab]You’re too damn stubborn...
[tab]There’s no such thing as a human
[tab]without shadows...
[sync][wait][clear][end]

msg_11:
[color(yellow)]Baofu[color(white)]
[tab]We’ll make you remember that your
[tab]place is here...
[tab]Just go to Hell and be done with it...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Ulala[color(white)]
[tab]It’s over...
[sync][wait][clear][end]

msg_13:
[color(yellow)][tatsuya][color(white)]
[tab]No...
[tab]There’s... still one more thing...
[sync][wait][clear][end]

msg_14:
[color(yellow)][tatsuya][color(white)]
[tab]The fact remains that I’m the Paradox...
[tab]If I stay here... then "This Side" will
[tab]be engulfed by the "Other Side"...
[sync][wait][clear][end]

msg_15:
[color(yellow)]Baofu/Katsuya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_16:
[color(yellow)]Ulala/Maya[color(white)]
[tab][tatsuya]-kun... You’re not...
[sync][wait][clear][end]

msg_17:
[color(yellow)][tatsuya][color(white)]
[tab]I’m going home...
[sync][wait][clear][end]

msg_18:
[tab]I’m going home...
[choice(2)]Take me with you!
[tatsuya]... Thank you for everything...
[end_choice][clear][end]

msg_19:
[color(yellow)][tatsuya][color(white)]
[tab]We are connected by this ocean...
[tab]We can... meet again...
[sync][wait][clear][end]

msg_20:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_21:
[color(yellow)][tatsuya][color(white)]
[tab]I’m sorry... Maya-nee...
[sync][wait][clear][end]

msg_22:
[color(yellow)][tatsuya][color(white)]
[tab]Nii-san...
[sync][wait][clear][end]

msg_23:
[color(yellow)][tatsuya][color(white)]
[tab]Ulala-san...
[tab]Baofu-san...
[sync][wait][clear][end]

msg_24:
[color(yellow)][tatsuya][color(white)]
[tab]Take care of Maya-nee... and everyone...
[sync][wait][clear][end]

msg_25:
[color(yellow)][tatsuya][color(white)]
[tab]The only thing left on the Other Side is
[tab]our city. We’ll rebuild a great world...
[sync][wait][clear][end]

msg_26:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]... You...
[tab]were planning to do that from the start...
[sync][wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]I made a promise to Jun...
[tab]He kept his word...
[tab]Now it’s my turn...
[sync][wait][clear][end]

msg_28:
[color(yellow)]Baofu[color(white)]
[tab][tatsuya]...
[tab]There’s one thing I forgot to tell you...
[sync][wait][clear][end]

msg_29:
[color(yellow)]Baofu[color(white)]
[tab]There are good things even when
[tab]you become an adult...
[tab]Just a few...
[sync][wait][clear][end]

msg_30:
[color(yellow)][tatsuya][color(white)]
[tab]Yeah... I know...
[sync][wait][clear][end]

msg_31:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]...!
[sync][wait][clear][end]

msg_32:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun...!
[sync][wait][clear][end]

msg_33:
[color(yellow)][tatsuya] from the Other Side[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_34:
[color(yellow)][tatsuya][color(white)]
[tab]I made a promise to Jun...
[tab]He kept his word...
[tab]Now it’s my turn...
[sync][wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]The only thing left on the Other Side is
[tab]our city. We’ll rebuild a great world...
[sync][wait][clear][end]

msg_36:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]... You...
[sync][wait][clear][end]

msg_37:
[color(yellow)]Baofu[color(white)]
[tab][tatsuya]...
[tab]There’s one thing I forgot to tell you...
[sync][wait][clear][end]

msg_38:
[color(yellow)]Baofu[color(white)]
[tab]There are good things even when
[tab]you become an adult...
[tab]Just a few...
[sync][wait][clear][end]

msg_39:
[color(yellow)][tatsuya][color(white)]
[tab]Yeah... I know...
[sync][wait][clear][end]

msg_40:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]...!
[sync][wait][clear][end]

msg_41:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun...!
[sync][wait][clear][end]

msg_42:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_43:
[color(yellow)][tatsuya] from the Other Side[color(white)]
[tab]We are connected by this ocean...
[tab]We can... meet again...
[sync][wait][clear][end]
