
msg_0:
[color(yellow)][tatsuya][color(white)]
[end]

msg_1:
[tab]Lisa...!
[end]

msg_2:
[tab]Ginko...!
[end]

msg_3:
[sync][wait][clear][end]

msg_4:
[color(yellow)]Shadow Maya[color(white)]
[tab]Are you relieved... little boy?
[tab]But we can’t let you have her back
[tab]quite so easily.
[sync][wait][clear][end]

msg_5:
[color(yellow)]Shadow Baofu[color(white)]
[tab]Heh... Such being the case...
[tab]I’ll be sure to teach her a lesson,
[tab]so you can die in peace.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . .
[sync][wait][clear][end]

msg_7:
[color(yellow)]Baofu[color(white)]
[tab]Try picking on someone your own size...
[end]

msg_8:
[tab]How about me?
[sync][wait][clear][end]

msg_9:
[color(yellow)]Shadow Maya[color(white)]
[tab](snicker)
[tab]You make me laugh...
[sync][wait][clear][end]

msg_10:
[color(yellow)]Shadow Baofu[color(white)]
[tab]Yeah, that makes me laugh!!
[sync][wait][clear][end]

msg_11:
[color(yellow)]Lisa[color(white)]
[tab]Chinyan (darling)!?
[sync][wait][clear][end]

msg_12:
[color(yellow)][tatsuya][color(white)]
[end]

msg_13:
[tab]Lisa... it’ll be alright!
[end]

msg_14:
[tab]Ginko... it’ll be alright!
[end]

msg_15:
[tab]I’ll get you down...
[wait][clear][end]

msg_16:
[color(yellow)]Shadow Maya[color(white)]
[tab]It’s a pity...
[tab]She remembered.
[wait][clear][end]

msg_17:
[color(yellow)]Shadow Baofu[color(white)]
[tab]How about giving it up, huh...?
[tab]There’s no point in living such a pathetic life!
[tab]Death is so much more fitting.
[wait][clear][end]

msg_18:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . .
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]No can do...
[tab]There’s just one more thing I need to do...
[end]

msg_20:
[tab]I just hafta kill your head honcho!!
[sync][wait][clear][end]

msg_21:
[color(yellow)]Shadow Maya[color(white)]
[tab](snicker)...
[tab]You make me laaaugh?
[sync][wait][clear][end]

msg_22:
[color(yellow)]Shadow Baofu[color(white)]
[tab]Yeah, that makes me laugh!!
[sync][wait][clear][end]
