
msg_0:
[color(yellow)]Philemon[color(white)]
[tab]Maya... Amano...
[tab]Are you going to finish...
[tab]without knowing the truth...?
[wait][clear][end]

msg_1:
[color(yellow)]Philemon[color(white)]
[tab]You are the only ones... who can help he who
[tab]is enchanted by the shadows... Now... Once
[tab]more... Walk from the inscribed path of time.
[wait][clear][end]

msg_2:
[color(yellow)]Philemon[color(white)]
[tab]Maya... Amano... The life they gave you in
[tab]return for their precious memories...
[tab]Are you going to let it slip away...
[wait][clear][end]

msg_3:
[color(yellow)]Philemon[color(white)]
[tab]You are the only ones... who can give light
[tab]to the dark heart of the people... Now, once
[tab]again, walk from the inscribed path of time...
[wait][clear][end]

msg_4:
[color(yellow)]Philemon[color(white)]
[tab]Maya Amano... Your power is much
[tab]greater than this... Now, once again,
[tab]walk from the inscribed path of time...
[wait][clear][end]
