
msg_0:
[color(yellow)]Elite Beret[color(white)]
[tab]I thought something weird was going on. 
[tab]So you’re the intruder!
[sync][wait][clear][end]

msg_1:
I made Eikichi wait outside, 
headed into the security control room, 
and walked into a faceful of guns. 
[wait][clear]I didn’t figure the security guards had noticed me. 
I guessed they came from another floor 
to check things out.
[sync][wait][clear][end]

msg_2:
[color(yellow)]Elite Beret[color(white)]
[tab]What, a kid? 
[tab]Where the hell did you-
[sync][wait][clear][end]

msg_3:
I was no hero. 
I didn’t need to wait for them to finish their lines. 
Before they finished babbling, 
I crouched down and dashed towards them.
[sync][wait][clear][end]
