
msg_0:
[color(green)]At the center of the tower, which resembled 
Philemon’s space, there stood an Abyssinian-like 
cat with a tail longer than its torso. 
Both the cat and their tail stood erect.[color(white)]
[sync][wait][clear][end]

msg_1:
[color(yellow)]Cat[color(white)]
[tab]Platoon, ten-hut!
[sync][wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]It talked!
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]...Wait, why say that now? 
[tab]We’ve talked to butterflies and made 
[tab]contact with demons and stuff.
[sync][wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]It looks like an Abyssinian. 
[tab]It’s so cute.
[sync][wait][clear][end]

msg_5:
[color(yellow)]Baofu[color(white)]
[tab]Hey, watch it. 
[tab]That looks like some kinda big shot cat.
[sync][wait][clear][end]

msg_6:
[color(yellow)]Cat[color(white)]
[tab]I am Lieutenant General Zula of the Ulthar Cat Army.
[wait][clear][end]

msg_7:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Carter has enlightened me about your situation. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Because I am experienced with 
[tab]the unconscious world, and you are not, 
[tab]I will graciously act as your guide.
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]Carter?
[sync][wait][clear][end]

msg_9:
[color(green)]Maya and [tatsuya] exchanged a glance.[color(white)]
[sync][wait][clear][end]

msg_10:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Salute if you understand! 
[tab]Be grateful, humans, and salute!
[sync][wait][clear][end]

msg_11:
[color(green)]Out of conditioned reflex, Katsuya saluted.[color(white)]
[wait][clear][end]

msg_12:
[color(green)]Zula returned it beautifully.[color(white)]
[sync][wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Lieutenant General, what is this "Ulthar"?
[sync][wait][clear][end]

msg_14:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]A most hallowed land in the middle 
[tab]of the Collective Unconscious, 
[tab]and the front lines of our war. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Our cat tribe battles the abominable 
[tab]Zoog tribe there.
[wait][clear][end]

msg_15:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]It is not helpful for you to worry about it. 
[tab]It’s of no concern to your campaign at this time. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Salute if you understand! 
[tab]Be grateful, humans, and salute!
[sync][wait][clear][end]

msg_16:
[color(green)]Katsuya again reflexively saluted.[color(white)]
[wait][clear][end]

msg_17:
[color(green)]Zula once again returned it splendidly.[color(white)]
[sync][wait][clear][end]

msg_18:
[color(yellow)][tatsuya][color(white)]
[tab]Where are the shards of Shiori-san’s psyche?
[sync][wait][clear][end]

msg_19:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]No need to rush.
[wait][clear][end]

msg_20:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]From this time on you will search for  
[tab]the fractured pieces of the psyche that 
[tab]constitute Shiori Miyashiro.
[wait][clear][end]

msg_21:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Her perception of the world around her; 
[tab]the manner in which she discerns reality, and how she 
[tab]delineates her experience from those around her.
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]"Perception", "Knowledge", "Memory".
[wait][clear][end]

msg_22:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]The matrix of her inner world which allows 
[tab]her to acknowledge herself and form a 
[tab]cohesive inwards identity. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]"Perseverance", "Emotion", "Drive", 
[tab]"Wisdom", "Will".
[wait][clear][end]

msg_23:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Finally, there is the way in which she 
[tab]integrates her perception of the outside world 
[tab]and the inner self she has acknowledged. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Her management of her own balance with society: 
[tab]"Reason", "Ethics" and that which is her complex: 
[tab]"Reflection".
[wait][clear][end]

msg_24:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Fail to obtain all eleven of these fragments,  
[tab]called Trapezohedrons, and Shiori Miyashiro 
[tab]will be unable to exist as herself.
[sync][wait][clear][end]

msg_25:
[color(yellow)]Baofu[color(white)]
[tab]This is gonna be some back-breaking labor, huh...
[sync][wait][clear][end]

msg_26:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Each of these Trapezohedrons has been found 
[tab]and claimed by a demon who now rules over them. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]You must retrieve them, either through 
[tab]bloodshed or negotiation.
[wait][clear][end]

msg_27:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]This place called Kadath Mandala is 
[tab]constructed in the shape of a hexagram, 
[tab]containing an older pentagram emblem.
[wait][clear][end]

msg_28:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]The hexagram represents the vast macrocosm 
[tab]of space and the pentagram is a symbol of the 
[tab]microcosm known as humanity.
[wait][clear][end]

msg_29:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]You will find the demons at the towers of each 
[tab]star-point. Should you lose yourself in Kadath, 
[tab]head for the point of the star. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Do you comprehend?
[sync][wait][clear][end]

msg_30:
[color(green)]Maya nodded and said she understood the gist of it.[color(white)]
[sync][wait][clear][end]

msg_31:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]I hope you realize that the demons in possession 
[tab]of these Trapezohedrons which surmise the 
[tab]psyche are all far more powerful than yourselves.
[wait][clear][end]

msg_32:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Similarly, though I am certain you know how to 
[tab]do this, take care to carve these memories
[tab]without disrupting the ones you had before. 
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]If you fail to do this, 
[tab]I will not be held responsible.
[sync][wait][clear][end]
