
msg_0:
At the same time that I opened the door 
towards Kandori, I heard a bullet or something 
strike it. Kandori was hidden behind the door, 
so I couldn’t see him.
[wait][clear][end]

msg_1:
Adrenaline raging, I saw the situation 
around me unfold with grim deliberation.
[wait][clear][end]

msg_2:
My senses were so honed I felt like a radar. 
I could see every movement clearly, 
and every noise was clear as a bell.
[wait][clear][end]

msg_3:
Immediately next to me, in the corner of my right eye, 
I saw Eikichi crouching down, and behind him, 
a security guard was pressing a gun to his head.
[wait][clear][end]

msg_4:
In the huge room before my eyes, there was a 
large apparatus like a revolver cylinder. 
Countless rows of test tube-like tanks filled 
with a bizarre sticky black goo lined up all around it.
[wait][clear][end]

msg_5:
In front of that machine, Maya-nee, my older brother 
and the others were surrounded by security guards 
who had guns trained on them from a stair landing 
a level above them. God dammit, I told you so!
[wait][clear][end]

msg_6:
Based on everyone’s relative positions, I got that 
Maya-nee and the others were on the third floor, while 
Eikichi, Kandori, the security guards and me were on 
the landing on the fourth floor leading into an atrium.
[wait][clear][end]

msg_7:
After that, my body moved before I could think.
[sync][wait][clear][end]

msg_8:
I ran past Eikichi, kicked him from behind with 
all my strength, and sent him flying towards the door. 
He hit the door face-first and went rolling down 
the middle of the hallway I’d come from.
[wait][clear][end]

msg_9:
I caught sight of the door slamming shut from the force
of the rebound in the corner of my eye. Using the
inertia from kicking Eikichi, I twisted my body to bisect
the security guard who’d been standing behind me.
[wait][clear][end]

msg_10:
I’ve heard that when another target jumps out in 
front of someone suddenly, they’ll be confused 
for an instant about which one they should shoot. 
[wait][clear]I ended that guy before he could 
come to a conclusion.
[wait][clear][end]

msg_11:
I immediately straightened again and turned past the 
door. A man in shades with a flashy scar on his face 
pointed a handgun at me, which was still trailing a 
faint line of smoke from the muzzle.
[wait][clear][end]

msg_12:
Not at all shaken, the corner of his mouth floated 
into a shallow smile. 
[wait][clear]If you blended cynicism with fatigue, 
affectation with caprice, 
and nihilism with an excess of talent, 
you’d probably end up with a man like this.
[wait][clear][end]

msg_13:
This must have been Kandori.
[sync][wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]!?
[sync][wait][clear][end]

msg_15:
From below, my older brother called out my name. 
In the time it took him to do so, the two of us could 
get taken out. Nothing for it; I gave him a push forward 
with a horribly clich五d line.
[sync][wait][clear][end]

msg_16:
[color(yellow)][tatsuya][color(white)]
[tab]Get out of here now...!
[sync][wait][clear][end]

msg_17:
It looked like everyone remembered what they 
should be doing. Maya-nee and the others 
escaped in a rush, and the guards started 
opening fire on them all together.
[sync][wait][clear][end]

msg_18:
[color(yellow)]Kandori[color(white)]
[tab]Hmph...
[sync][wait][clear][end]

msg_19:
[color(yellow)]Kandori[color(white)]
[tab]Regardless, neither you, nor they, 
[tab]can escape from fate...
[tab]Paradox boy...
[sync][wait][clear][end]

msg_20:
Paradox. 
With that one word, 
I understood what bound me to this man. 
I had got a job to do, too.
[sync][wait][clear][end]

msg_21:
[color(yellow)][tatsuya][color(white)]
[tab]I see...
[tab]You, too, were enchanted... by "him"...
[sync][wait][clear][end]

msg_22:
[color(yellow)][tatsuya][color(white)]
[tab]Then tell "him" for me... 
[tab]That I’ll protect...
[tab]Maya-nee and everyone else...!
[sync][wait][clear][end]

msg_23:
This man knew me and "him" on an even 
deeper level than Sudou. 
"Paradox." 
What kind of outcome was that even implying?
[sync][wait][clear][end]

msg_24:
[color(yellow)]Kandori[color(white)]
[tab]No need to pass on a message. 
[tab]He hears all - just so.
[sync][wait][clear][end]

msg_25:
[color(yellow)][tatsuya][color(white)]
[tab]!!
[sync][wait][clear][end]

msg_26:
It’s clear that the Persona Kandori 
bore was the incarnation of "him."
[wait][clear][end]

msg_27:
He almost completely erased the 
presence of his Persona, just like I did. 
I didn’t notice him until he was right under my nose. 
[wait][clear]Fury flowed through my veins, 
and I was completely awash in hatred.
[sync][wait][clear][end]

msg_28:
[color(yellow)]Kandori[color(white)]
[tab]Have you ever considered 
[tab]why the Moon you can never reach 
[tab]shines as beautifully as it does?
[sync][wait][clear][end]

msg_29:
I was burning up.
[sync][wait][clear][end]

msg_30:
[color(yellow)]Kandori[color(white)]
[tab]It is not because it reflects the light of the sun; 
[tab]it’s because it is embraced by darkness. The deeper 
[tab]the darkness, the brighter its light shines.
[sync][wait][clear][end]

msg_31:
My field of vision was narrowing.
[sync][wait][clear][end]

msg_32:
[color(yellow)]Kandori[color(white)]
[tab]Maya Amano, too, will inevitably fall into darkness. 
[tab]You, too, must become a black sun.
[sync][wait][clear][end]

msg_33:
[color(yellow)][tatsuya][color(white)]
[tab]RAAAARRRRRRGGGHHH!
[sync][wait][clear][end]
