
msg_0:
[color(green)]In the middle of the tower, 
there sat a Great One wreathed in profound sorrow.[color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]Izanami[color(white)]
[tab]I am Izanami... I learned about the flaw
[tab]of the souls at Yomotsu Hirasaka...
[wait][clear][color(yellow)]Izanami[color(white)]
[tab]Do you understand the reason why 
[tab]I wear a mask such as this?
[sync][wait][clear][end]

msg_2:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]This Great One, the Queen of Yomi, 
[tab]was betrayed by her husband and so birthed 
[tab]rage and sorrow and death into the world.
[wait][clear][color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Well now, what is your answer?
[sync][wait][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab]The myth of how Izanami and Izanagi 
[tab]created the country, and of Yomotsu Hirasaka 
[tab]and the Chibiki no Iwa door... 
[wait][clear][color(yellow)]Katsuya[color(white)]
[tab]Anyone Japanese knows this cruel tale.
[wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]Izanami died giving birth to her beloved 
[tab]Izanagi’s child and became a denizen 
[tab]of the Underworld. 
[wait][clear][color(yellow)]Katsuya[color(white)]
[tab]When her husband came to retrieve her, 
[tab]she resolved not to show him her rotted form.
[wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]However, Izanagi broke his vow and 
[tab]looked upon his wife’s hideous form.
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]In shock, Izanagi fled, and Izanami, 
[tab]maddened with humiliation and rage, 
[tab]sent the ogres of Yomi to chase him.
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Izanagi managed to get away and sealed away 
[tab]the door at Yomotsu Hirasaka, which led to  
[tab]the Land of the Dead, with the Chibiki no Iwa. 
[wait][clear][color(yellow)]Katsuya[color(white)]
[tab]However, Izanami’s rage was not quelled.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]She cursed him by declaring she’d kill 
[tab]a thousand of the people he 
[tab]governed on the earth each day. 
[wait][clear][color(yellow)]Katsuya[color(white)]
[tab]In response her husband declared eternal divorce 
[tab]by stating he’d ensure one thousand five hundred 
[tab]people were born each day.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]In total, Izanami was betrayed by her husband thrice... 
[tab]no, four times?
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]He looked when she told him not to, he ran away 
[tab]when he was supposed to have retrieved her, 
[tab]and he forced a divorce on her.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]She died giving birth to Kagutsuchi, the god of fire, 
[tab]so upon losing his wife, Izanagi cut off his head 
[tab]in a fit of rage and killed him.
[sync][wait][clear][end]

msg_12:
[color(yellow)]Ulala[color(white)]
[tab]That’s awful...! 
[tab]Even I’m better off than that...
[sync][wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]It’s a good example of how conceited people are, 
[tab]no matter where you go. Their feelings don’t work  
[tab]out the way they want them to.
[sync][wait][clear][end]

msg_14:
[color(yellow)][tatsuya][color(white)]
[tab]...What should Izanagi have done?
[sync][wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]He shouldn’t have gone to see his dead wife.  
[tab]It’s ridiculous, thinking it’d lead to anything good. 
[tab]Of course it just made things worse.
[sync][wait][clear][end]

msg_16:
[color(yellow)][tatsuya][color(white)]
[tab]. . . . . . .
[sync][wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]But you know, I like those kinds of idiots. 
[tab]They just reek of humanity.
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]You can’t help falling in love. 
[tab]Even when you can’t be together, you want to be.
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]The reason this goddess here’s hiding her 
[tab]face is probably something like that, too...
[sync][wait][clear][end]

msg_20:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]...You are an interesting lot. 
[tab]Now then, Maya Amano, what do you think?
[sync][wait][clear][end]

msg_21:
[tab]Now then, Maya Amano, what do you think?
[choice(2)]To smother the last of her emotions...
She doesn’t want him to see her rotted face 
[end_choice][clear][end]

msg_22:
[color(yellow)]Izanami[color(white)]
[tab]Yes, that’s it... 
[tab]He murdered my child and humiliated me, 
[tab]and for that, I hate him... I cannot forgive him...
[wait][clear][end]

msg_23:
[color(green)]The Great One’s hair stood on end and 
thunder appeared, coiling around her whole body.[color(white)]
[wait][clear][end]

msg_24:
[color(yellow)]Izanami[color(white)]
[tab]If you say you’ll cause 1,500 children to be born, 
[tab]then I will kill 2,000 people!
[wait][clear][end]

msg_25:
[color(yellow)]Izanami[color(white)]
[tab]Ouikazuchi! Honoikazuchi! Kuroikazuchi! 
[tab]Sakuikazuchi! Wakaikazuchi! Tsuchiikazuchi! 
[tab]Naruikazuchi! Fusuikazuchi! 
[wait][clear][color(yellow)]Izanami[color(white)]
[tab]Burn all humans above the ground to death!
[sync][wait][clear][end]

msg_26:
[color(yellow)]Izanami[color(white)]
[tab]Yes... 
[tab]I still yearn for him...
[wait][clear][end]

msg_27:
[color(yellow)]Izanami[color(white)]
[tab]Even if we are deeply separated by heaven and earth 
[tab]in this eternal divorce, I cannot forget the beautiful
[tab]days we spent creating this country together.
[wait][clear][end]

msg_28:
[color(yellow)]Izanami[color(white)]
[tab]My rage vanished long ago. 
[tab]My grudge, too, has long faded.
[wait][clear][end]

msg_29:
[color(yellow)]Izanami[color(white)]
[tab]But my sorrow and sense of pining alone will not fade. 
[tab]Therefore I have hidden my face.
[wait][clear][end]

msg_30:
[color(yellow)]Izanami[color(white)]
[tab]When he finally comes for me again, 
[tab]may it end without him looking 
[tab]upon this hideous face...
[wait][clear][end]

msg_31:
[color(green)]In the Great One’s hand, 
the Shining Emotion Trapezohedron appeared.[color(white)]
[wait][clear][end]

msg_32:
[color(yellow)]Izanami[color(white)]
[tab]This woman too may have had someone like that. 
[tab]Take this with you...
[wait][clear][end]

msg_33:
[color(green)]The great one disappeared.[color(white)]
[sync][wait][clear][end]

msg_34:
[color(green)]Maya and the others obtained 200 [var(msg_var_0)] cards.[color(white)]
[sync][wait][clear][end]

msg_35:
[color(green)]Maya and the others obtained 
Shiori’s Trapezohedron of Emotion, 
and left the Tower of Emotion behind.[color(white)]
[sync][wait][clear][end]
