
msg_0:
[color(green)]In the center of the tower, 
a great being sits in the shining moonlight. [color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]Sakya[color(white)]
[tab]I am Sakya... One awakened from "Maya". 
[tab]If the reality is an illusion bound by Jiva... 
[wait][clear][color(yellow)]Sakya[color(white)]
[tab]Let us preach enlightenment together so as to 
[tab]release living beings from their spiritual bondage.
[wait][clear][end]

msg_2:
[color(yellow)]Sakya[color(white)]
[tab]To the woman who bears the same name as 
[tab]my mother and the illusion that torments me: 
[tab]what is your "self" as far as you all are concerned?
[sync][wait][clear][end]

msg_3:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Ten-hut! This Great One, who founded Buddhism, 
[tab]is the Awakened One. 
[tab]Well now, what is your answer?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]It’s none other than a bad guy. 
[tab]Right, Serizawa?
[sync][wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]...Don’t ask me. I feel like I’ve been beating my 
[tab]head on a brick wall over this stuff.
[sync][wait][clear][end]

msg_6:
[color(yellow)][tatsuya][color(white)]
[tab]A bad guy, huh... 
[tab]Well, that’s true.
[sync][wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]I think what we are to ourselves 
[tab]is different for each person. 
[wait][clear][color(yellow)]Katsuya[color(white)]
[tab]But no matter what kind of person you might be, 
[tab]if you deny what you are, that’s enough to 
[tab]keep you from moving forward.
[sync][wait][clear][end]

msg_8:
[tab]What is your "self" as far as you all are concerned?
[choice(2)]An irreplaceable treasure. Right?
That which brings about doubt and suffering...
[end_choice][clear][end]

msg_9:
[color(yellow)]Sakya[color(white)]
[tab]Do you think so? 
[tab]As I thought, like your name implies, 
[tab]it appears you are still trapped by "Maya".
[wait][clear][end]

msg_10:
[color(yellow)]Sakya[color(white)]
[tab]By all rights, one should discover 
[tab]the state of Anatta by oneself, 
[tab]but I shall extend a helping hand to you.
[sync][wait][clear][end]

msg_11:
[color(yellow)]Sakya[color(white)]
[tab]Precisely. It is the egotism of gaining attachment to 
[tab]imprisonment by the non-existent illusion called "I" that 
[tab]ultimately brings suffering to yourself and the world.
[wait][clear][end]

msg_12:
[color(yellow)]Sakya[color(white)]
[tab]"All things lack inherent identity."
[wait][clear][end]

msg_13:
[color(yellow)]Sakya[color(white)]
[tab]Remember to accept that everything in this transient 
[tab]world changes from having no substance to having 
[tab]substance on the basis of dependent origination. 
[wait][clear][color(yellow)]Sakya[color(white)]
[tab]This understanding is what will bring 
[tab]an end to suffering.
[wait][clear][end]

msg_14:
[color(yellow)]Sakya[color(white)]
[tab]The woman whom you all seek is one 
[tab]still imprisoned by powerful egotism.
[wait][clear][end]

msg_15:
[color(yellow)]Sakya[color(white)]
[tab]I shall entrust unto you the "Perseverance" 
[tab]that is the source of her character and vitality. 
[wait][clear][color(yellow)]Sakya[color(white)]
[tab]Please do convey it to her so that she 
[tab]may refine the ability to understand 
[tab]the teachings of the Buddha.
[wait][clear][end]

msg_16:
[color(green)]The Great One vanished.[color(white)]
[sync][wait][clear][end]

msg_17:
[color(green)]Maya and the others obtained 200 [var(msg_var_0)] cards. [color(white)]
[sync][wait][clear][end]

msg_18:
[color(green)]Maya and the others obtained 
Shiori’s Trapezohedron of Perseverance, 
and left the Tower of Perseverance behind.[color(white)]
[sync][wait][clear][end]
