
msg_0:
[color(yellow)]The Faceless God[color(white)]
[tab]Heh heh... I’ll cut the entertainment off here. 
[tab]Now, hurry and return to the waking world. 
[wait][clear][color(yellow)]The Faceless God[color(white)]
[tab]Oppose me not as my avatar but as me 
[tab]in the flesh as soon as possible.
[wait][clear][end]

msg_1:
[color(yellow)]The Faceless God[color(white)]
[tab]I’m waiting. 
[tab]I’m waiting...
[sync][wait][clear][end]

msg_2:
[color(green)]The Mighty Messenger vanished, 
leaving behind the Emotion Trapezohedron of 
Randolph Carter.[color(white)]
[sync][wait][clear][end]

msg_3:
[color(green)]Maya and everyone else turned around. 
[tatsuya] was strangling Shiori.[color(white)]
[sync][wait][clear][end]

msg_4:
[color(yellow)][tatsuya][color(white)]
[tab]Gggkhhkkh!!
[sync][wait][clear][end]

msg_5:
[color(yellow)]Shiori[color(white)]
[tab]I’m... sorry...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya], stop!
[sync][wait][clear][end]

msg_7:
[color(green)]Katsuya pinned [tatsuya]’s arms behind his back.[color(white)]
[sync][wait][clear][end]

msg_8:
[color(yellow)][tatsuya][color(white)]
[tab]Huh...!?
[sync][wait][clear][end]

msg_9:
[color(green)]When [tatsuya] returned to his senses and 
released his hand, Shiori’s form shone black 
and returned to being the Trapezohedron of Reflection. 
It then tumbled down to [tatsuya]’s feet.[color(white)]
[sync][wait][clear][end]

msg_10:
[color(green)][tatsuya] fell into a crouch, snatched up the 
Trapezohedron in a panic, and clasped it to his chest.[color(white)]
[sync][wait][clear][end]

msg_11:
[color(yellow)][tatsuya][color(white)]
[tab]Guh...!! 
[tab]Uuuungh... 
[tab]I’m sorry... Shiori-san... I’m sorry...
[sync][wait][clear][end]

msg_12:
[color(yellow)]Maya[color(white)]
[tab]. . . . . . . . 
[sync][wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]. . . . . . . . 
[sync][wait][clear][end]

msg_14:
[color(yellow)]Ulala[color(white)]
[tab]. . . . . . . . 
[sync][wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]. . . . . . . . 
[sync][wait][clear][end]

msg_16:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]...Fortunately, the Trapezohedron didn’t shatter. 
[tab]Though it was a bitter victory, you have rescued 
[tab]Shiori Miyashiro’s psyche. Well done...
[sync][wait][clear][end]

msg_17:
[color(green)]The Ultimate Gate opened, 
and Swami Chandraputra appeared.[color(white)]
[sync][wait][clear][end]

msg_18:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Randolph Carter, these fellows have
[tab]splendidly recaptured the fragment of your self 
[tab]that had been captured by the Faceless God.
[sync][wait][clear][end]

msg_19:
[color(yellow)]Katsuya[color(white)]
[tab]Randolph Carter...? 
[tab]Wasn’t he your disciple?
[sync][wait][clear][end]

msg_20:
[color(yellow)]Randolph Carter[color(white)]
[tab]I BEG YOUR FORGIVENESS 
[tab]FOR REMAINING SILENT
[wait][clear][color(yellow)]Randolph Carter[color(white)]
[tab]IT WAS NOT MY INTENT 
[tab]TO DECEIVE YOU...
[sync][wait][clear][end]

msg_21:
[color(yellow)]Randolph Carter[color(white)]
[tab]I HAD NOT WANTED
[tab]TO SHOCK YOU
[tab]WITH MY APPEARANCE
[sync][wait][clear][end]

msg_22:
[color(yellow)]Ulala[color(white)]
[tab]Whoa... 
[tab]Could you be...?
[sync][wait][clear][end]

msg_23:
[color(yellow)]Randolph Carter[color(white)]
[tab]YES 
[tab]LIKE THE WOMAN YOU SAVED
[wait][clear][color(yellow)]Randolph Carter[color(white)]
[tab]MY BODY WAS POSSESSED 
[tab]BY A PERSONA
[sync][wait][clear][end]

msg_24:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]Though in Carter’s case, it was in the midst of his 
[tab]diligent quest through the Unconsciousness that 
[tab]he incurred the displeasure of the Crawling Chaos.
[wait][clear][end]

msg_25:
[color(yellow)]Cat Lieutenant General Zula[color(white)]
[tab]It was only through the force of Carter’s will that 
[tab]he was able to preserve his consciousness 
[tab]even after being transfigured into this form.
[sync][wait][clear][end]

msg_26:
[color(yellow)]Randolph Carter[color(white)]
[tab]THANKS TO YOU ALL 
[tab]AT LAST 
[tab]I CAN RETURN TO HUMAN FORM
[wait][clear][color(yellow)]Randolph Carter[color(white)]
[tab]HOW LONG IT HAS BEEN... 
[tab]THANK YOU SO MUCH
[wait][clear][end]

msg_27:
[color(yellow)]Randolph Carter[color(white)]
[tab]NOW THEN 
[tab]I SHALL RETURN YOU ALL 
[tab]TO THE WAKING WORLD 
[wait][clear][color(yellow)]Randolph Carter[color(white)]
[tab]YOU WILL NO DOUBT 
[tab]ALSO BE ABLE 
[wait][clear][color(yellow)]Randolph Carter[color(white)]
[tab]TO RETURN HER TO NORMAL 
[tab]WITH IGOR’S ASSISTANCE
[sync][wait][clear][end]

msg_28:
[color(green)]Maya and the others obtained 200 [var(msg_var_0)] cards.[color(white)]
[wait][clear][end]

msg_29:
[color(green)]Maya and the others obtained 200 [var(msg_var_0)] cards.[color(white)]
[wait][clear][end]

msg_30:
[color(green)]Maya and the others obtained 200 [var(msg_var_0)] cards.[color(white)]
[sync][wait][clear][end]
