
msg_0:
More than four in the party.
Hang time!
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]You shouldn’t trust men so easily.
[tab]Be careful, Ma-ya. Men are wolves!
[tab]It’ll be too late after you get hurt.
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]That Nanjo-kun is really something.
[tab]He’s younger than me and he has
[tab]so many lackeys? ...Wow.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]You know those dream diagnostics?
[tab]Isn’t it like you dream the opposite of
[tab]what’s in your heart? ...Or something.
[wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]...Extremists?!
[tab]No, I shouldn’t suspect innocent citizens.
[tab]Shame on myself...
[wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]...I feel sad.
[tab]Makimura-kun, have you no conscience?
[tab]What you did was clearly a crime!!
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]...Men are wolves.
[tab]I can’t deny that, but it’s unfortunate
[tab]that all men have to be labeled that way.
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Abducting people who’ve become Jokers...
[tab]Whatever their motives are, we cannot
[tab]let them do as they want.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]I had a dream once where many
[tab]incidents happened one after the other.
[tab]Could it have been a premonition?
[wait][clear][end]

msg_9:
[color(yellow)]Kataoka[color(white)]
[tab]He should not be here. Deleted.
[wait][clear][end]

msg_10:
[color(yellow)]Baofu[color(white)]
[tab]...Hey [suou], extremists
[tab]in this day and age?
[tab]What decade are you in, man?
[wait][clear][end]

msg_11:
[color(yellow)]Makimura[color(white)]
[tab]There! Officer, look at that man!
[tab]See, see all men are like that.
[tab]You’re a man too, so you understand, right?
[wait][clear][end]

msg_12:
[color(yellow)]Baofu[color(white)]
[tab]Hey [suou],
[tab]This con artist is talking to you.
[tab]Do you know how this guy feels?
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]Hey, Serizawa, aren’t you confused?
[tab]Don’t blame your foolishness on men.
[tab]...You understand right?
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab]I’m starting to think that the New World
[tab]Order really isn’t anything great if those
[tab]richies can find stuff on them.
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab][suou] had a dream where the
[tab]police station was bombed. 
[tab]Maybe he wants to kill his boss?
[wait][clear][end]

msg_16:
[color(yellow)]Nanjo[color(white)]
[tab]Mr. Baofu, perhaps it is not wise to
[tab]judge the enemy so lightly?
[tab]Or are you judging me lightly?
[wait][clear][end]

msg_17:
[color(yellow)]Nanjo[color(white)]
[tab]Dreams could reflect reality.
[tab]I have had dreams where the Satomi Tadashi
[tab]song was loved by everyone.
[wait][clear][end]

msg_18:
[color(yellow)]Elly[color(white)]
[tab]Mr. Baofu...
[tab]I don’t really care what you think,
[tab]but it’s pathetic to envy youth.
[wait][clear][end]

msg_19:
[color(yellow)]Elly[color(white)]
[tab]It is true that dreams are related to
[tab]a person’s heart. But it’s something deep,
[tab]and mere simple feelings are not reflected.
[wait][clear][end]

msg_20:
[color(yellow)]Young Man[color(white)]
[tab]Hey! I know you!
[tab]You’re from that magazine publisher, right?
[tab]Could you introduce me to a model?
[wait][clear][end]

msg_21:
[color(yellow)]Young Man[color(white)]
[tab]What the hell! Don’t you ignore me!
[tab]Damn it, everyone treats me like dirt!
[tab]...I’ll make you pay just like them!!
[wait][clear][end]

msg_22:
[color(yellow)]Positive Woman[color(white)]
[tab]"Let’s think positive!"...
[tab]Aren’t they wonderful words? Aren’t they?
[tab]These words’ll change the world! Won’t they?
[wait][clear][end]

msg_23:
[color(yellow)]Strange Woman[color(white)]
[tab]Oh, gross!
[tab]Why do I have to be hit on by a
[tab]creep like that? I wish I was a man...
[wait][clear][end]

msg_24:
[color(yellow)]Strange Woman[color(white)]
[tab]That creep all of a sudden went crazy.
[tab]I’m so glad those people came...
[tab]They shouldn’t let those people loose.
[wait][clear][end]

msg_25:
[color(yellow)]Strange Woman[color(white)]
[tab]Who were those people anyway?
[tab]...They must’ve been the police!
[tab]Good, they must have took him away!
[wait][clear][end]

msg_26:
[color(yellow)]Strange Woman[color(white)]
[tab]Why are men so unreliable?
[tab]I’m more fit to be a man than him!
[tab]Why do women fall for guys like that...
[wait][clear][end]

msg_27:
[color(yellow)]Strange Woman[color(white)]
[tab]I’ve been hearing rumors about it, 
[tab]but the owner’s tastes have really changed.
[tab]He started selling really odd armor.
[wait][clear][end]

msg_28:
[color(yellow)]Strange Woman[color(white)]
[tab]I’ve been hearing rumors about it, 
[tab]but the owner’s tastes have really changed.
[tab]He started selling really odd weapons.
[wait][clear][end]

msg_29:
[color(yellow)]Whistler[color(white)]
[tab]I’ve got new stuff.
[tab]It’s special... Go home if you’re not buying...
[wait][clear][end]

msg_30:
[color(yellow)]Whistler[color(white)]
[tab]First-time customers...
[tab]Do you want the special ones...?
[wait][clear][end]

msg_31:
[color(yellow)]Whistler[color(white)]
[tab]I’ll sell it to you cheap if you’re buying.
[tab]Only today though...
[tab]...tweettweettweet...
[wait][clear][end]

msg_32:
[color(yellow)]Whistler[color(white)]
[tab]I’ll sell it cheap, but only today...
[tab]I’ve got the special ones too...
[tab]...tweettweettweet...
[wait][clear][end]

msg_33:
[color(yellow)]Whistler[color(white)]
[tab]Yeah, what do you want?
[choice(6)][if_none(LBIT_0000)]Buy armor
[if_all(LBIT_0000)]Buy weapons
Sell items
Talk to Whistler
Never mind
Leave the store
[end_choice][clear][end]

msg_34:
[color(yellow)]Whistler[color(white)]
[tab]What have you got for me?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_35:
[color(yellow)]Whistler[color(white)]
[tab]What’s there to talk about?
[choice(3)]Make small talk
Ask about shopping
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_36:
[color(yellow)]Whistler[color(white)]
[tab]You still want something?
[choice(6)][if_none(LBIT_0000)]Buy armor
[if_all(LBIT_0000)]Buy weapons
Sell items
Talk to Whistler
Never mind
Leave the store
[end_choice][clear][end]

msg_37:
[color(yellow)]Whistler[color(white)]
[tab]What have you got for me?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_38:
[color(yellow)]Whistler[color(white)]
[tab]What’s there to talk about?
[choice(3)]Make small talk
Ask about shopping
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_39:
[color(yellow)]Whistler[color(white)]
[tab]Go home if you’re window-shopping...
[wait][clear][end]

msg_40:
[color(yellow)]Whistler[color(white)]
[tab]...Abduction?
[tab]You have to protect your own ass...
[wait][clear][end]

msg_41:
[color(yellow)]Whistler[color(white)]
[tab]Buy something or go home...
[wait][clear][end]

msg_42:
[color(yellow)]Whistler[color(white)]
[tab]Go home.
[wait][clear][end]

msg_43:
MBIT[tab]KE[tab]TOA
東亜ディフェンス・販売物決定
(噂による変化)
びっとお~んッ!!
[wait][clear][end]

msg_44:
MBIT[tab]AIS[tab]37
相性占いの
びっとお~んッ!!
[wait][clear][end]

msg_45:
EBIT[tab]E0037
警察署[half_tab]受付、終了
びっとお~んッ!!
[wait][clear][end]

msg_46:
EBIT[tab]E0038
「詐欺男を確保」
びっとお~んッ!!
[wait][clear][end]

msg_47:
EBIT[tab]E003E
「ゴールドクリア」「Ulala編入」
びっとお~んッ!!
[wait][clear][end]

msg_48:
EBIT[tab]E0043
「クラブクリア」
びっとお~んッ!!
[wait][clear][end]

msg_49:
EBIT[tab]E0046
「南条orエリー編入」
びっとお~んッ!!
[wait][clear][end]

msg_50:
EBIT[tab]E006F
「研究施設・TV局クリア」
びっとお~んッ!!
[wait][clear][end]

msg_51:
[color(yellow)]Whistler[color(white)]
[tab]You actually need me to explain how to shop?
[tab]Ffff. Choose "Buy armor" and you buy some armor.
[wait][clear][color(yellow)]Whistler[color(white)]
[tab]Only certain people can wear certain pieces
[tab]of armor. Check before you buy anything, 
[tab]because all sales here are final.
[wait][clear][color(yellow)]Whistler[color(white)]
[tab]Or you can choose "Sell items" if you have
[tab]something you want to get rid of. Pick which
[tab]kind of item, then choose what you wanna sell.
[wait][clear][color(yellow)]Whistler[color(white)]
[tab]I pay about half the retail price. Them’s the
[tab]breaks. And I won’t buy anything you got
[tab]equipped or anything I got no use for.
[wait][clear][end]

msg_52:
[color(yellow)]Whistler[color(white)]
[tab]You actually need me to explain how to shop?
[tab]Ffff. Choose "Buy weapons" 
[tab]and you buy some weapons.
[wait][clear][color(yellow)]Whistler[color(white)]
[tab]Only certain people can use certain weapons.
[tab]Check before you buy anything, because all
[tab]sales here are final.
[wait][clear][color(yellow)]Whistler[color(white)]
[tab]...There’s more than one weapon? 
[tab]There’s lots of them in the warehouse.
[tab]...Don’t worry about the details.
[wait][clear][color(yellow)][color(white)]
[tab]Or you can choose "Sell items" if you have
[tab]something you want to get rid of. Pick which
[tab]kind of item, then choose what you wanna sell.
[wait][clear][color(yellow)]Whistler[color(white)]
[tab]I pay about half the retail price. Them’s the
[tab]breaks. And I won’t buy anything you got
[tab]equipped or anything I got no use for.
[wait][clear][end]

msg_53:
[color(yellow)]Whistler[color(white)]
[tab]You don’t have anything to sell.[wait][clear][end]

msg_54:
[color(yellow)]Whistler[color(white)]
[tab]In total that’s ¥[var(msg_var_0)].
[choice(2)]Yes
No
[end_choice][clear][end]

msg_55:
[color(yellow)]Whistler[color(white)]
[tab]In total that’s ¥[var(msg_var_0)].
[choice(2)]Yes
No
[end_choice][clear][end]
