
msg_0:
There are more than 4 people in the party.
[tab]This will cause the game to hang.
[tab]Please contact Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Don’t ya think there have been a lot of
[tab]people who’ve experienced d五j二 vu lately?
[tab]A coincidence? I kinda doubt that...
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]I’ve had episodes of d五j二 vu lately, too...
[tab]...But it’s kinda different... 
[tab]It feels like I’m about to remember something.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun...
[tab]Looks like he’s finally about to talk but...
[tab]What is he going to do at a shrine?
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]I really think [tatsuya]-kun is
[tab]trying to tell you something, Ma-ya!
[tab]Doesn’t anything ring a bell?
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]A parallel world...
[tab]I always thought it happened in
[tab]books and movies, but...
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab](sigh)... The city is flying for real...
[tab]I don’t know if we can do anything
[tab]about it by ourselves...
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]!? What am I saying! This isn’t the
[tab]time to give up! This is my big chance
[tab]to do something before I’m 25!
[wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab]So he’s the one causing this whole thing.
[tab]Now’s the time to use the Fist of Justice
[tab]that I didn’t use against Makimura!
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]If we carelessly destroy the Kegare machine,
[tab]we’ll just end up like Ginji Sasaki...
[tab]How can we return the Kegare to the people?
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]The impure humans will be destroyed by
[tab]the New World Order... So they want to be
[tab]purified...? Why are they such followers?
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]Alaya Shrine...
[tab]When we were little I used to bring
[tab]him there for the festivals.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]But that was a long time ago...
[tab]All these years he never mentioned the
[tab]name of that shrine...
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Just out of curiosity, did you know 
[tab]about [tatsuya] before you met me?
[tab]Looking at him it seems to be that way...
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya] has known you from way before. 
[tab]But that occurred in a different parallel world...
[tab]Unbelievable... truly...
[wait][clear][end]

msg_15:
[color(yellow)]Katsuya[color(white)]
[tab]The one who stabbed Amano-kun in the Other Side... 
[tab]She was that teacher at Sevens...
[tab]Different world, different person...
[wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]This might be an odd question, but...
[tab]Do you think [tatsuya] and I are alike?
[tab]Just tell me what you think.
[wait][clear][end]

msg_17:
[tab]What do you think?
[choice(2)]Alike
Not alike
[end_choice][clear][end]

msg_18:
[color(yellow)]Katsuya[color(white)]
[tab]S-So you think... we’re alike... 
[tab]Then, I guess I don’t need to worry about it...
[tab]Sorry, don’t mind me.
[wait][clear][end]

msg_19:
[color(yellow)]Katsuya[color(white)]
[tab]...I see...
[tab]Right. I’m just me.
[tab]Being brothers isn’t an excuse.
[wait][clear][end]

msg_20:
[color(yellow)]Katsuya[color(white)]
[tab]People grow up with role models.
[tab]It’s not strange for an older brother
[tab]to look up to a younger brother, is it?
[wait][clear][end]

msg_21:
[color(yellow)]Katsuya[color(white)]
[tab]How dare you take the form of
[tab]my younger brother to play
[tab]in your twisted little game!
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]That Ginji Sasaki had eyes
[tab]like that woman over there.
[tab]I guess she’s already been brainwashed...
[wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]After all, people who only know peace do
[tab]not have the will to protect their lives.
[tab]They’ve even forgotten death’s reality.
[wait][clear][end]

msg_24:
[color(yellow)]Baofu[color(white)]
[tab]I wouldn’t say it’s bad.
[tab]’Cause there’s nothing better than peace.
[tab]But, it’s true that it caused this situation.
[wait][clear][end]

msg_25:
[color(yellow)]Baofu[color(white)]
[tab]I’m concerned about [tatsuya] too but,
[tab]as we speak the NWO’s plans are already set
[tab]in motion. There’s no time to screw around.
[wait][clear][end]

msg_26:
[color(yellow)]Baofu[color(white)]
[tab]The incident that happened on the "Other Side"... 
[tab]So the guy that was behind it is behind 
[tab]this one as well...
[wait][clear][end]

msg_27:
[color(yellow)]Baofu[color(white)]
[tab]Stopping the Ritual... 
[tab]Depending on how you look at it... 
[tab]It’s an immense thing to do... Perfect for me.
[wait][clear][end]

msg_28:
[color(yellow)]Baofu[color(white)]
[tab]So, after causing all this trouble,
[tab]he’s saying it’s all just a game...
[tab]He’s really something.
[wait][clear][end]

msg_29:
[color(yellow)]Nanjo[color(white)]
[tab]Not only do those joining in the seminar
[tab]get their Kegare divested, but they are also
[tab]brainwashed to obey the New World Order.
[wait][clear][end]

msg_30:
[color(yellow)]Nanjo[color(white)]
[tab]Brainwashing... How peculiar...
[tab]I have a feeling something similar to this
[tab]has happened before...
[wait][clear][end]

msg_31:
[color(yellow)]Nanjo[color(white)]
[tab]...That proprietor...
[tab]He calls himself a Count...
[tab]Something bothers me about him.
[wait][clear][end]

msg_32:
[color(yellow)]Nanjo[color(white)]
[tab]Kandori’s words... Was he trying to 
[tab]discover something about [tatsuya]? 
[tab]Or, did he want to entrust him with something...
[wait][clear][end]

msg_33:
[color(yellow)]Elly[color(white)]
[tab]That seminar had the purpose of getting people 
[tab]to obey the New World Order by brainwashing... 
[tab]At this rate...
[wait][clear][end]

msg_34:
[color(yellow)]Elly[color(white)]
[tab]That shop owner... I feel that he’s
[tab]different from a normal person...
[tab]I’m getting goosebumps... Why...
[wait][clear][end]

msg_35:
[color(yellow)]Elly[color(white)]
[tab]I think Mr. Kandori might’ve wanted to
[tab]entrust something to [tatsuya]...
[tab]Strange, I just have that feeling.
[wait][clear][end]

msg_36:
[color(yellow)][tatsuya][color(white)]
[tab]The people of the city are starting to be
[tab]affected as well...
[tab]There’s no time to lose.
[wait][clear][end]

msg_37:
[color(yellow)][tatsuya][color(white)]
[tab]By you remembering everything, 
[tab]the distortion between the two realities had
[tab]to have grown larger... We have no time...
[wait][clear][end]

msg_38:
[color(yellow)][tatsuya][color(white)]
[tab]Even now,
[tab]he is watching us from somewhere.
[tab]With a grin on his face...
[wait][clear][end]

msg_39:
[color(yellow)][tatsuya][color(white)]
[tab]Maya-nee... don’t you feel it...?
[tab]This man... he can’t be...
[wait][clear][end]

msg_40:
[color(yellow)]Count[color(white)]
[tab]I see... not accepting Fate,
[tab]you have turned back the wheels of time...
[tab]Humans are veritably pitiful beings...
[wait][clear][color(yellow)]Count[color(white)]
[tab]But, it seems there are no roles left for
[tab]me to play. I would like to have my reason
[tab]for my existence determined already...
[wait][clear][end]

msg_41:
[color(yellow)]Count[color(white)]
[tab]I see... not accepting Fate,
[tab]you have turned back the wheels of time...
[tab]Humans are veritably pitiful beings...
[wait][clear][color(yellow)]Count[color(white)]
[tab]But, it seems there are no roles left for
[tab]me to play. I would like to have my reason
[tab]for my existence determined already...
[wait][clear][color(yellow)]Count[color(white)]
[tab]No matter how good our affinity is,
[tab]without a role, nothing can be done...
[wait][clear][end]

msg_42:
[color(yellow)]Count[color(white)]
[tab]No matter how many times you come here it’s
[tab]always the same. I can’t help you right now.
[tab]Why don’t you go play with your "rumors"?
[wait][clear][end]

msg_43:
[color(yellow)]Count[color(white)]
[tab]No matter how many times you come here it’s
[tab]always the same. I can’t help you right now.
[tab]Why don’t you go play with your rumors?
[wait][clear][color(yellow)]Count[color(white)]
[tab]Affinity or whatever,
[tab]everything comes afterwards.
[wait][clear][end]

msg_44:
[color(yellow)]Count[color(white)]
[tab]Hahaha... I see.
[tab]It seems that my role has been determined.
[tab]Once again, am I to become a puppet of time?
[wait][clear][color(yellow)]Count[color(white)]
[tab]Welcome to the Time Castle.
[tab]We have many Skill Cards here.
[tab]What is your business here...?
[wait][clear][end]

msg_45:
[color(yellow)]Count[color(white)]
[tab]Hahaha... I see.
[tab]It seems that my role has been determined.
[tab]Once again, am I to become a puppet of time?
[wait][clear][color(yellow)]Count[color(white)]
[tab]Welcome to the Time Castle.
[tab]We have many Skill Cards here.
[tab]What is your business here...?
[wait][clear][color(yellow)]Count[color(white)]
[tab]...Ha ha... I see... Affinity Reading already.
[tab]Fine. I do feel something between us. 
[tab]Let us do business, I’ll give you a discount...
[wait][clear][end]

msg_46:
[color(yellow)]Count[color(white)]
[tab]Welcome to the Time Castle.
[tab]What is your business here...?
[wait][clear][end]

msg_47:
[color(yellow)]Count[color(white)]
[tab]You say you have affinity with me?
[tab]Ha ha... well that’s not entirely false...
[tab]Very well. I’ll give you a discount.
[wait][clear][end]

msg_48:
[color(yellow)]Count[color(white)]
[tab]Ha ha ha... Now we’re duplicating cards...
[tab]You amuse me quite well.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Finally, we can duplicate cards here. 
[tab]If you find a rare card, bring it here. 
[tab]I’ll make as many as you want and sell them.
[wait][clear][end]

msg_49:
[color(yellow)]Count[color(white)]
[tab]Ha ha ha... Now we’re duplicating cards...
[tab]You amuse me quite well.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Finally, we can duplicate cards here. 
[tab]If you find a rare card, bring it here. 
[tab]I’ll make as many as you want and sell them.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Of course... I’ll give a discount.
[tab]to my compatible friend.
[tab]Just a little extra service...
[wait][clear][end]

msg_50:
[color(yellow)]Count[color(white)]
[tab]Is there something else you would like?
[choice(6)]Buy Cards
Sell items
Talk to the Count
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_51:
[color(yellow)]Count[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_52:
[color(yellow)]Count[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about cards
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_53:
[color(yellow)]Count[color(white)]
[tab]Is there something else you would like?
[choice(7)]Buy Cards
Register Cards
Sell items
Talk to the Count
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_54:
[color(yellow)]Count[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_55:
[color(yellow)]Count[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about cards
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_56:
[color(yellow)]Count[color(white)]
[tab]Anything else?
[choice(6)]Buy Cards
Sell items
Talk to the Count
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_57:
[color(yellow)]Count[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_58:
[color(yellow)]Count[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about cards
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_59:
[color(yellow)]Count[color(white)]
[tab]Anything else?
[choice(7)]Buy Cards
Register Cards
Sell items
Talk to the Count
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_60:
[color(yellow)]Count[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_61:
[color(yellow)]Count[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about cards
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_62:
[color(yellow)]Count[color(white)]
[tab]That woman had been missing for a while...
[tab]She just came back safely.
[tab]She has become a purified citizen.
[wait][clear][end]

msg_63:
[color(yellow)]Count[color(white)]
[tab]Your actions bring chaos to the city,
[tab]and make things even worse...
[tab]It’s all the same. It all repeats itself.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Do you not realize that you are just
[tab]being made to stand in a time similar
[tab]to a past already gone by?
[wait][clear][end]

msg_64:
[color(yellow)]Count[color(white)]
[tab]Haha... this world is about to collapse. 
[tab]Even the final decision that you bet your life
[tab]on is nothing before the acts of humans.
[wait][clear][color(yellow)]Count[color(white)]
[tab]So...
[tab]Who will make the final move?
[tab]It seems that you hold the key...
[wait][clear][end]

msg_65:
[color(yellow)]Count[color(white)]
[tab]You should know everything now.
[tab]The existence of the "Other Side"
[tab]and the meaning behind "This Side".
[wait][clear][color(yellow)]Count[color(white)]
[tab]But why do you still struggle?
[tab]What meaning is there in a fleeting peace?
[wait][clear][color(yellow)]Count[color(white)]
[tab]It is a contradiction.
[tab]People will continue to live bearing
[tab]hypocrisy. They are an imperfect lifeform.
[wait][clear][end]

msg_66:
[color(yellow)]Count[color(white)]
[tab]Now... this is the last game.
[tab]Show me your final answer.
[tab]The stage should be adequate for it.
[wait][clear][end]

msg_67:
[color(yellow)]Count[color(white)]
[tab]Now once again, the rings of time spin...
[tab]You who pursues the time that has gone by...
[tab]We shall meet again...
[wait][clear][end]

msg_68:
[color(yellow)]Middle-Aged Lady[color(white)]
[tab]Let’s think positive...!!
[tab]A purified citizen is a happy citizen!
[tab]We will usher in a New World!
[wait][clear][end]

msg_69:
[color(yellow)]Middle-Aged Lady[color(white)]
[tab]Let’s think positive!!
[tab]The Torifune will bring us to a New World!
[tab]Let’s think positive!!
[wait][clear][end]

msg_70:
[color(yellow)]Middle-Aged Lady[color(white)]
[tab]Let’s think positive!!
[tab]The Torifune is about to be set in motion!
[tab]Death of the world! Birth of a new era!!
[wait][clear][end]

msg_71:
[color(yellow)]Middle-Aged Lady[color(white)]
[tab]Let’s think positive!!
[tab]The world will die soon!!
[tab]Only the purified will be saved!!
[wait][clear][end]

msg_72:
[color(yellow)]Middle-Aged Lady[color(white)]
[tab]Let’s think positive!!
[tab]But the dragons are gone!?
[tab]World death? New era? Where?!
[wait][clear][end]

msg_73:
[color(yellow)]Quiet Gentleman[color(white)]
[tab]It’s been 8 years since I became a
[tab]businessman... For my introverted self,
[tab]society was both harsh and cold.
[wait][clear][color(yellow)]Quiet Gentleman[color(white)]
[tab]Nowadays, I only get pleasure from quietly
[tab]looking at these antiques...
[tab]My sister may be worried though...
[wait][clear][end]

msg_74:
[color(yellow)]Quiet Gentleman[color(white)]
[tab]Excuse me...
[tab]Is there something else you
[tab]would like from me?
[wait][clear][end]

msg_75:
[tab]What do you want?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_76:
RYOICHI HONDA
[end]

msg_77:
[color(yellow)]Quiet Gentleman[color(white)]
[tab]Excuse me?
[tab]N-no, that’s not my name...
[tab]Perhaps you’ve mistaken me?
[wait][clear][end]

msg_78:
[color(yellow)]Ryoichi Honda[color(white)]
[tab]What!?
[tab]How do you know my name?
[tab]Eh?! There was a search going on for me?
[wait][clear][color(yellow)]Ryoichi Honda[color(white)]
[tab]I-Is that so...
[tab]My younger sister must have filed a report.
[tab]I must have made her worry.
[wait][clear][color(yellow)]Ryoichi Honda[color(white)]
[tab]Very well. I’ll contact her and Shiraishi.
[tab]Sorry to cause you trouble.
[wait][clear][end]

msg_79:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_80:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_81:
[tab]What’s wrong with that woman over there?
[tab]She seems to have come back safely, 
[tab]but now she just keeps repeating herself...
[wait][clear][end]

msg_82:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_83:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_84:
[tab]The New World Order is trying to cleanse
[tab]the Kegare of the world by destroying it.
[tab]People go to the seminar out of fear.
[wait][clear][end]

msg_85:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_86:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_87:
[tab]Do you know a book... um.."In"... something?
[tab]For some reason I just thought
[tab]of that book...
[wait][clear][end]

msg_88:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_89:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_90:
[tab]Cleansing the world means ending it...
[tab]How depressing...
[tab]Humans... myself... should we change?
[wait][clear][end]

msg_91:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_92:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_93:
[tab]What in the world will happen to our city...
[tab]I cannot stop trembling in fear.
[tab]But I am thinking of what I could do.
[wait][clear][end]

msg_94:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_95:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_96:
[tab]I’ve always been one to run...
[tab]I want to go out in a blaze of glory
[tab]before I die...
[wait][clear][end]

msg_97:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_98:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_99:
[tab]At this Time Castle, Skill Cards are sold...
[tab]I was surprised when I heard the rumor.
[wait][clear][end]

msg_100:
[color(yellow)]Quiet Gentleman[color(white)]
[end]

msg_101:
[color(yellow)]Ryoichi Honda[color(white)]
[end]

msg_102:
[tab]I heard that the Count can even duplicate Skill Cards.
[tab]He is no ordinary man...
[wait][clear][end]

msg_103:
[color(yellow)]Count[color(white)]
[tab]Is there something else you would like?
[choice(3)]Ask about shopping
[if_all(MBIT_HI_JIKANDUP)]Ask about registering cards
Never mind
[end_choice][clear][end]

msg_104:
[color(yellow)]Count[color(white)]
[tab]Shopping?
[tab]Let’s start with buying.
[tab]You can select "Buy Cards"
[wait][clear][color(yellow)]Count[color(white)]
[tab]to purchase skill cards.
[tab]Of course the more useful the card,
[tab]the more expensive it is.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Consider it carefully before buying.
[tab]Next I’ll explain selling.
[tab]Select "Sell items" and then the type.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Then select the specific item to sell.
[tab]I will purchase it for half its original price.
[tab]Equipped items cannot be sold.
[wait][clear][color(yellow)]Count[color(white)]
[tab]...So this is that kind of place?
[wait][clear][end]

msg_105:
[color(yellow)]Count[color(white)]
[tab]Registering cards?
[tab]You can increase the amount of cards
[tab]sold here by registering rare cards.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Select "Register Card"
[tab]and give me the card you want to register.
[wait][clear][color(yellow)]Count[color(white)]
[tab]Please note that one card will be
[tab]consumed to register it. After that 
[tab]I can duplicate it endlessly.
[wait][clear][color(yellow)]Count[color(white)]
[tab]After the card has been registered
[tab]you can buy as many as you need.
[wait][clear][color(yellow)]Count[color(white)]
[tab]...Do you think there is meaning in this?
[wait][clear][end]

msg_106:
[color(yellow)]Count[color(white)]
[tab]Unfortunately you don’t have anything to sell
[tab]Come back later.[wait][clear][end]

msg_107:
[color(yellow)]Count[color(white)]
[tab]It will cost ¥[var(msg_var_0)]
[tab]Is that okay?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_108:
[color(yellow)]Count[color(white)]
[tab]I will buy it for ¥[var(msg_var_0)]、
[tab]Is that okay?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_109:
[color(yellow)]Count[color(white)]
[tab]In exchange for registration,
[tab]I will need one card.
[tab]Is that okay?
[choice(2)]Yes
No
[end_choice][clear][end]
