function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3046, 127);
    bitGet(var_0, MBIT_HI_KAORIHENNI);
    bne(var_0, 0, label_6);
    b(label_1d);
  label_6:
    bne(var_0, 1, label_1d);
    bitGet(var_0, MBIT_KAHENIDIS);
    bne(var_0, 0, label_1a);
    rand(var_0, 1);
    bne(var_0, 0, label_e);
    bitSet(MBIT_KAHENIDIS);
    bitSet(MBIT_KAORIZOUKA);
    b(label_19);
  label_e:
    bne(var_0, 1, label_19);
    bitSet(MBIT_KAHENIDIS);
    bitSet(MBIT_KAORIKYUUKA);
    bitGet(var_0, MBIT_KAKYUKACHK);
    bne(var_0, 0, label_16);
    bitSet(MBIT_KAOYASUMI);
    bitSet(MBIT_KAKYUKACHK);
    b(label_18);
  label_16:
    bne(var_0, 1, label_18);
    b(label_18);
  label_18:
    b(label_19);
  label_19:
    b(label_1c);
  label_1a:
    bne(var_0, 1, label_1c);
    b(label_1c);
  label_1c:
    b(label_1d);
  label_1d:
    envTriggerSet(EXITBOX, 131, 1, line, coll_22);
    li(var_0, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, tatsuya);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_2e);
    li(var_0, 0);
    b(label_33);
  label_2e:
    ref_2e = dialogAlloc();
    ref_2f = msgShow(msg_0);
/***************************************
More than four.
Hang time!
[wait][clear]
***************************************/
    wait(ref_2f);
    dialogFree(ref_2e);
    b(label_33);
  label_33:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_39);
    ref_35 = spriteLoad(sprite_6);
    wait(ref_35);
    unitSpawn(ulala, sprite_6, 887, 0, -482, west, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_39:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_3f);
    ref_3b = spriteLoad(sprite_d);
    wait(ref_3b);
    unitSpawn(katsuya, sprite_d, 192, 0, -344, north, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_3f:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_45);
    ref_41 = spriteLoad(sprite_13);
    wait(ref_41);
    unitSpawn(baofu, sprite_13, 928, 0, -892, east, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_45:
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_4b);
    ref_47 = spriteLoad(sprite_1f);
    wait(ref_47);
    unitSpawn(nanjo, sprite_1f, 704, 0, -560, east, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
  label_4b:
    partyMemberCheck(var_0, elly);
    bez(var_0, label_51);
    ref_4d = spriteLoad(sprite_23);
    wait(ref_4d);
    unitSpawn(elly, sprite_23, 130, 0, -623, east, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
  label_51:
    partyMemberCheck(var_0, tatsuya);
    bez(var_0, label_58);
    ref_53 = spriteLoad(sprite_18);
    wait(ref_53);
    unitSpawn(tatsuya, sprite_18, 133, 0, -544, east, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_61);
  label_58:
    bitGet(var_0, EBIT_E008C);
    bne(var_0, 0, label_5b);
    b(label_61);
  label_5b:
    bne(var_0, 1, label_61);
    ref_5c = spriteLoad(sprite_18);
    wait(ref_5c);
    unitSpawn(tatsuya, sprite_18, 133, 0, -544, east, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_61);
  label_61:
    ref_61 = spriteLoad(sprite_8e);
    wait(ref_61);
    unitSpawn(shopkeeper, sprite_8e, 510, 0, -797, north, none);
    unitTriggerSet(shopkeeper, SHOPBOX, 255, 1);
    ref_65 = spriteLoad(sprite_ba);
    wait(ref_65);
    unitSpawn(npc1, sprite_ba, 96, 0, -835, west, none);
    unitPalette(npc1, 1);
    unitTriggerSet(npc1, WAKAMONO, 255, 1);
    ref_6a = spriteLoad(sprite_c5);
    wait(ref_6a);
    unitSpawn(npc2, sprite_c5, 457, 0, -251, north, none);
    unitPalette(npc2, 1);
    unitTriggerSet(npc2, OBASAN, 255, 1);
    bitGet(var_0, MBIT_KAORIRIYOU);
    bne(var_0, 0, label_73);
    cameraSet(southeast, 508, 0, -1089);
    b(label_76);
  label_73:
    bne(var_0, 1, label_76);
    cameraSet(southeast, 503, 0, -877);
    b(label_76);
  label_76:
    ref_76 = spriteLoad(sprite_0);
    wait(ref_76);
    ref_78 = spriteLoad(sprite_2);
    wait(ref_78);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_fd);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_ef);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_d3);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_c3);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_a9);
    unitFacePlayer(ulala);
    ref_90 = bustupLoad(bustup_1f);
    bustupWait(ref_90);
    ref_92 = bustupAlloc(ref_90, left, rgb(0,0,0));
    bustupFade(ref_92, rgb(128,0,0), 30);
    ref_94 = dialogAlloc();
    ref_95 = msgShow(msg_1);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Oh, it’s another world here.
[tab]I feel so relaxed!
[tab]I felt so sick after seeing that ooze.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_95);
    ref_98 = bustupFade(ref_92, rgb(0,0,0), 10);
    bustupWait(ref_98);
    bustupFree(ref_92);
    ref_9b = bustupLoad(bustup_1c);
    bustupWait(ref_9b);
    ref_9d = bustupAlloc(ref_9b, left, rgb(0,0,0));
    bustupFade(ref_9d, rgb(128,0,0), 30);
    ref_9f = msgShow(msg_2);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Just thinking that stuff is running through me...
[tab]Ugh... it’s disgusting...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_6, 1);
    wait(ref_9f);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_94);
    ref_a4 = bustupFade(ref_9d, rgb(0,0,0), 10);
    bustupWait(ref_a4);
    bustupFree(ref_9d);
    unitRestoreFacing(ulala);
    b(label_10c);
  label_a9:
    unitFacePlayer(ulala);
    ref_aa = bustupLoad(bustup_1f);
    bustupWait(ref_aa);
    ref_ac = bustupAlloc(ref_aa, left, rgb(0,0,0));
    bustupFade(ref_ac, rgb(128,0,0), 30);
    ref_ae = dialogAlloc();
    ref_af = msgShow(msg_3);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Hey, Ma-ya...
[tab]Sorry to bring up an old subject,
[tab]but... it bothers me...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1a, 1);
    wait(ref_af);
    ref_b2 = bustupFade(ref_ac, rgb(0,0,0), 10);
    bustupWait(ref_b2);
    bustupFree(ref_ac);
    ref_b5 = bustupLoad(bustup_17);
    bustupWait(ref_b5);
    ref_b7 = bustupAlloc(ref_b5, left, rgb(0,0,0));
    bustupFade(ref_b7, rgb(128,0,0), 30);
    ref_b9 = msgShow(msg_4);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Why do rumors become reality?
[tab]I was thinking about it myself...
[tab]It must be the cause of everything.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_b9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ae);
    ref_be = bustupFade(ref_b7, rgb(0,0,0), 10);
    bustupWait(ref_be);
    bustupFree(ref_b7);
    unitRestoreFacing(ulala);
    b(label_10c);
  label_c3:
    unitFacePlayer(ulala);
    ref_c4 = bustupLoad(bustup_18);
    bustupWait(ref_c4);
    ref_c6 = bustupAlloc(ref_c4, left, rgb(0,0,0));
    bustupFade(ref_c6, rgb(128,0,0), 30);
    ref_c8 = dialogAlloc();
    ref_c9 = msgShow(msg_5);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Just between you and me... both Nanjo-kun and
[tab][tatsuya]-kun don’t look younger than us.
[tab]I guess they’ve been through a lot?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_c9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_c8);
    ref_ce = bustupFade(ref_c6, rgb(0,0,0), 10);
    bustupWait(ref_ce);
    bustupFree(ref_c6);
    unitRestoreFacing(ulala);
    b(label_10c);
  label_d3:
    unitFacePlayer(ulala);
    ref_d4 = bustupLoad(bustup_1f);
    bustupWait(ref_d4);
    ref_d6 = bustupAlloc(ref_d4, left, rgb(0,0,0));
    bustupFade(ref_d6, rgb(128,0,0), 30);
    ref_d8 = dialogAlloc();
    ref_d9 = msgShow(msg_6);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Oh, I’m jealous of you, Ma-ya.
[tab]I wish I had someone who cared about me
[tab]as much as [tatsuya]-kun cares for you.
[wait][clear]
***************************************/
    wait(ref_d9);
    ref_db = bustupFade(ref_d6, rgb(0,0,0), 10);
    bustupWait(ref_db);
    bustupFree(ref_d6);
    ref_de = bustupLoad(bustup_18);
    bustupWait(ref_de);
    ref_e0 = bustupAlloc(ref_de, left, rgb(0,0,0));
    bustupFade(ref_e0, rgb(128,0,0), 30);
    ref_e2 = msgShow(msg_7);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Oops... I shouldn’t be jealous or else
[tab]I’ll become a Joker again, huh?
[tab]Hahahaha
[sync][wait][clear]
***************************************/
    unitAnimationHold(ulala, animation_21, 30);
    unitWait(ulala);
    unitAnimationPlay(ulala, animation_23, 1);
    sync();
    wait(ref_e2);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_d8);
    ref_ea = bustupFade(ref_e0, rgb(0,0,0), 10);
    bustupWait(ref_ea);
    bustupFree(ref_e0);
    unitRestoreFacing(ulala);
    b(label_10c);
  label_ef:
    ref_ef = bustupLoad(bustup_17);
    bustupWait(ref_ef);
    ref_f1 = bustupAlloc(ref_ef, left, rgb(0,0,0));
    bustupFade(ref_f1, rgb(128,0,0), 30);
    ref_f3 = dialogAlloc();
    ref_f4 = msgShow(msg_8);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]After we’re done with this...
[tab]Maybe I’ll try being more womanly?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1a, 1);
    wait(ref_f4);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_f3);
    ref_f9 = bustupFade(ref_f1, rgb(0,0,0), 10);
    bustupWait(ref_f9);
    bustupFree(ref_f1);
    b(label_10c);
  label_fd:
    unitFacePlayer(ulala);
    ref_fe = bustupLoad(bustup_18);
    bustupWait(ref_fe);
    ref_100 = bustupAlloc(ref_fe, left, rgb(0,0,0));
    bustupFade(ref_100, rgb(128,0,0), 30);
    ref_102 = dialogAlloc();
    ref_103 = msgShow(msg_9);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]I know! Hey Ma-ya, why don’t we start
[tab]gardening sometime?
[tab]We’ve got a nice veranda for it.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_30, 1);
    wait(ref_103);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_102);
    ref_108 = bustupFade(ref_100, rgb(0,0,0), 10);
    bustupWait(ref_108);
    bustupFree(ref_100);
    unitRestoreFacing(ulala);
  label_10c:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_17d);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_16d);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_15d);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_139);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_129);
    unitFacePlayer(katsuya);
    ref_11a = bustupLoad(bustup_21);
    bustupWait(ref_11a);
    ref_11c = bustupAlloc(ref_11a, left, rgb(0,0,0));
    bustupFade(ref_11c, rgb(128,0,0), 30);
    ref_11e = dialogAlloc();
    ref_11f = msgShow(msg_10);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]I just...
[tab]wanted to find out the truth.
[tab]...I don’t hate the Chief.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_11f);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_11e);
    ref_124 = bustupFade(ref_11c, rgb(0,0,0), 10);
    bustupWait(ref_124);
    bustupFree(ref_11c);
    unitRestoreFacing(katsuya);
    b(label_18c);
  label_129:
    unitFacePlayer(katsuya);
    ref_12a = bustupLoad(bustup_23);
    bustupWait(ref_12a);
    ref_12c = bustupAlloc(ref_12a, left, rgb(0,0,0));
    bustupFade(ref_12c, rgb(128,0,0), 30);
    ref_12e = dialogAlloc();
    ref_12f = msgShow(msg_11);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]I can’t believe that the information
[tab]the Chief risked his life to spread
[tab]turned out to help their plan...
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_12f);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_12e);
    ref_134 = bustupFade(ref_12c, rgb(0,0,0), 10);
    bustupWait(ref_134);
    bustupFree(ref_12c);
    unitRestoreFacing(katsuya);
    b(label_18c);
  label_139:
    bitGet(var_0, EBIT_E0096);
    bne(var_0, 0, label_14b);
    unitFacePlayer(katsuya);
    ref_13c = bustupLoad(bustup_21);
    bustupWait(ref_13c);
    ref_13e = bustupAlloc(ref_13c, left, rgb(0,0,0));
    bustupFade(ref_13e, rgb(128,0,0), 30);
    ref_140 = dialogAlloc();
    ref_141 = msgShow(msg_12);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]...[tatsuya] seems so different...
[tab]It’s not like we got along great,
[tab]but something feels different.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_141);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_140);
    ref_146 = bustupFade(ref_13e, rgb(0,0,0), 10);
    bustupWait(ref_146);
    bustupFree(ref_13e);
    unitRestoreFacing(katsuya);
    b(label_15c);
  label_14b:
    bne(var_0, 1, label_15c);
    unitFacePlayer(katsuya);
    unitAnimationPlay(katsuya, animation_10, 1);
    ref_14e = bustupLoad(bustup_24);
    bustupWait(ref_14e);
    ref_150 = bustupAlloc(ref_14e, left, rgb(0,0,0));
    bustupFade(ref_150, rgb(128,0,0), 30);
    ref_152 = dialogAlloc();
    ref_153 = msgShow(msg_13);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]From the "Other Side"...
[tab]No wonder why he seems different...
[tab]But..is it true...?
[wait][clear]
***************************************/
    wait(ref_153);
    dialogFree(ref_152);
    ref_156 = bustupFade(ref_150, rgb(0,0,0), 10);
    bustupWait(ref_156);
    bustupFree(ref_150);
    unitAnimationPlay(katsuya, animation_a, 1);
    unitRestoreFacing(katsuya);
    b(label_15c);
  label_15c:
    b(label_18c);
  label_15d:
    unitFacePlayer(katsuya);
    ref_15e = bustupLoad(bustup_24);
    bustupWait(ref_15e);
    ref_160 = bustupAlloc(ref_15e, left, rgb(0,0,0));
    bustupFade(ref_160, rgb(128,0,0), 30);
    ref_162 = dialogAlloc();
    ref_163 = msgShow(msg_14);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Your friends from then are just
[tab]strangers in "This Side"...
[tab]It’s a trying battle.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_163);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_162);
    ref_168 = bustupFade(ref_160, rgb(0,0,0), 10);
    bustupWait(ref_168);
    bustupFree(ref_160);
    unitRestoreFacing(katsuya);
    b(label_18c);
  label_16d:
    unitFacePlayer(katsuya);
    ref_16e = bustupLoad(bustup_21);
    bustupWait(ref_16e);
    ref_170 = bustupAlloc(ref_16e, left, rgb(0,0,0));
    bustupFade(ref_170, rgb(128,0,0), 30);
    ref_172 = dialogAlloc();
    ref_173 = msgShow(msg_15);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]An indomitable spirit that won’t give up.
[tab]This [tatsuya] gives us nothing but surprises.
[tab]He’s so different from the old [tatsuya]...
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_173);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_172);
    ref_178 = bustupFade(ref_170, rgb(0,0,0), 10);
    bustupWait(ref_178);
    bustupFree(ref_170);
    unitRestoreFacing(katsuya);
    b(label_18c);
  label_17d:
    unitFacePlayer(katsuya);
    ref_17e = bustupLoad(bustup_21);
    bustupWait(ref_17e);
    ref_180 = bustupAlloc(ref_17e, left, rgb(0,0,0));
    bustupFade(ref_180, rgb(128,0,0), 30);
    ref_182 = dialogAlloc();
    ref_183 = msgShow(msg_16);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]If we defeat Nyarlathotep...
[tab]This case might be solved...
[tab]But what will happen to this [tatsuya]?
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_183);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_182);
    ref_188 = bustupFade(ref_180, rgb(0,0,0), 10);
    bustupWait(ref_188);
    bustupFree(ref_180);
    unitRestoreFacing(katsuya);
  label_18c:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1d7);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_1c7);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_1b7);
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_1a7);
    unitFacePlayer(baofu);
    ref_198 = bustupLoad(bustup_2d);
    bustupWait(ref_198);
    ref_19a = bustupAlloc(ref_198, left, rgb(0,0,0));
    bustupFade(ref_19a, rgb(128,0,0), 30);
    ref_19c = dialogAlloc();
    ref_19d = msgShow(msg_17);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Sasaki was able to use the Joker Persona
[tab]because of the ooze put in him...
[tab]Kegare creates Personas, huh...
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_19d);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_19c);
    ref_1a2 = bustupFade(ref_19a, rgb(0,0,0), 10);
    bustupWait(ref_1a2);
    bustupFree(ref_19a);
    unitRestoreFacing(baofu);
    b(label_1e6);
  label_1a7:
    unitFacePlayer(baofu);
    ref_1a8 = bustupLoad(bustup_2d);
    bustupWait(ref_1a8);
    ref_1aa = bustupAlloc(ref_1a8, left, rgb(0,0,0));
    bustupFade(ref_1aa, rgb(128,0,0), 30);
    ref_1ac = dialogAlloc();
    ref_1ad = msgShow(msg_18);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]The New World Order’s plans are based
[tab]on meticulous calculations and such.
[tab]But without rumors, they’re nothing.
[wait][clear][color(yellow)]Baofu[color(white)]
[tab]They’re just depending on the power of rumors. 
[tab]So then... the New World Order isn’t involved 
[tab]in making rumors come true.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1ad);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1ac);
    ref_1b2 = bustupFade(ref_1aa, rgb(0,0,0), 10);
    bustupWait(ref_1b2);
    bustupFree(ref_1aa);
    unitRestoreFacing(baofu);
    b(label_1e6);
  label_1b7:
    unitFacePlayer(baofu);
    ref_1b8 = bustupLoad(bustup_2d);
    bustupWait(ref_1b8);
    ref_1ba = bustupAlloc(ref_1b8, left, rgb(0,0,0));
    bustupFade(ref_1ba, rgb(128,0,0), 30);
    ref_1bc = dialogAlloc();
    ref_1bd = msgShow(msg_19);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Smells soothe people’s hearts, huh...
[tab]It might be true.
[tab]Right now, I believe it.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1bd);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1bc);
    ref_1c2 = bustupFade(ref_1ba, rgb(0,0,0), 10);
    bustupWait(ref_1c2);
    bustupFree(ref_1ba);
    unitRestoreFacing(baofu);
    b(label_1e6);
  label_1c7:
    unitFacePlayer(baofu);
    ref_1c8 = bustupLoad(bustup_2d);
    bustupWait(ref_1c8);
    ref_1ca = bustupAlloc(ref_1c8, left, rgb(0,0,0));
    bustupFade(ref_1ca, rgb(128,0,0), 30);
    ref_1cc = dialogAlloc();
    ref_1cd = msgShow(msg_20);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]The boy is his brother and also a stranger
[tab]from another world at the same time.
[tab]He must be perplexed...
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1cd);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1cc);
    ref_1d2 = bustupFade(ref_1ca, rgb(0,0,0), 10);
    bustupWait(ref_1d2);
    bustupFree(ref_1ca);
    unitRestoreFacing(baofu);
    b(label_1e6);
  label_1d7:
    unitFacePlayer(baofu);
    ref_1d8 = bustupLoad(bustup_2d);
    bustupWait(ref_1d8);
    ref_1da = bustupAlloc(ref_1d8, left, rgb(0,0,0));
    bustupFade(ref_1da, rgb(128,0,0), 30);
    ref_1dc = dialogAlloc();
    ref_1dd = msgShow(msg_21);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Relax.
[tab]It’s not like we’re going there to die.
[tab]No need to strain ourselves.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1dd);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1dc);
    ref_1e2 = bustupFade(ref_1da, rgb(0,0,0), 10);
    bustupWait(ref_1e2);
    bustupFree(ref_1da);
    unitRestoreFacing(baofu);
  label_1e6:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_217);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_1fd);
    unitFacePlayer(nanjo);
    ref_1ee = bustupLoad(bustup_36);
    bustupWait(ref_1ee);
    ref_1f0 = bustupAlloc(ref_1ee, left, rgb(0,0,0));
    bustupFade(ref_1f0, rgb(128,0,0), 30);
    ref_1f2 = dialogAlloc();
    ref_1f3 = msgShow(msg_22);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]They must be holding seminars in other
[tab]places as well. I am hoping the information
[tab]we spread will keep people away from them...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_1f3);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1f2);
    ref_1f8 = bustupFade(ref_1f0, rgb(0,0,0), 10);
    bustupWait(ref_1f8);
    bustupFree(ref_1f0);
    unitRestoreFacing(nanjo);
    b(label_22d);
  label_1fd:
    unitFacePlayer(nanjo);
    ref_1fe = bustupLoad(bustup_36);
    bustupWait(ref_1fe);
    ref_200 = bustupAlloc(ref_1fe, left, rgb(0,0,0));
    bustupFade(ref_200, rgb(128,0,0), 30);
    ref_202 = dialogAlloc();
    ref_203 = msgShow(msg_23);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]The end of the world caused by Wang Long...
[tab]And the Torifune...
[tab]This is the rumor the Chief spread...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_203);
    ref_206 = bustupFade(ref_200, rgb(0,0,0), 10);
    bustupWait(ref_206);
    bustupFree(ref_200);
    ref_209 = bustupLoad(bustup_38);
    bustupWait(ref_209);
    ref_20b = bustupAlloc(ref_209, left, rgb(0,0,0));
    bustupFade(ref_20b, rgb(128,0,0), 30);
    ref_20d = msgShow(msg_24);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]It is true that the information we
[tab]spread has increased their credibility.
[tab]...How careless of us...!
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_20d);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_202);
    ref_212 = bustupFade(ref_20b, rgb(0,0,0), 10);
    bustupWait(ref_212);
    bustupFree(ref_20b);
    unitRestoreFacing(nanjo);
    b(label_22d);
  label_217:
    unitFacePlayer(nanjo);
    ref_218 = bustupLoad(bustup_39);
    bustupWait(ref_218);
    ref_21a = bustupAlloc(ref_218, left, rgb(0,0,0));
    bustupFade(ref_21a, rgb(128,0,0), 30);
    ref_21c = dialogAlloc();
    ref_21d = msgShow(msg_25);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]No matter who it is, it is painful
[tab]to see their death twice...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_21d);
    ref_220 = msgShow(msg_26);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]Kandori...
[tab]This time, veritably,
[tab]farewell.
[sync][wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1, 1);
    delayClear();
    delayWait(15);
    unitAnimationPlay(nanjo, animation_2, 1);
    sync();
    wait(ref_220);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_21c);
    ref_229 = bustupFade(ref_21a, rgb(0,0,0), 10);
    bustupWait(ref_229);
    bustupFree(ref_21a);
    unitRestoreFacing(nanjo);
  label_22d:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_254);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_244);
    unitFacePlayer(elly);
    ref_235 = bustupLoad(bustup_3d);
    bustupWait(ref_235);
    ref_237 = bustupAlloc(ref_235, left, rgb(0,0,0));
    bustupFade(ref_237, rgb(128,0,0), 30);
    ref_239 = dialogAlloc();
    ref_23a = msgShow(msg_27);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Is it alright that the information of the
[tab]New World Order was publicized?
[tab]I hope it will disrupt their seminars...
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_23a);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_239);
    ref_23f = bustupFade(ref_237, rgb(0,0,0), 10);
    bustupWait(ref_23f);
    bustupFree(ref_237);
    unitRestoreFacing(elly);
    b(label_263);
  label_244:
    unitFacePlayer(elly);
    ref_245 = bustupLoad(bustup_40);
    bustupWait(ref_245);
    ref_247 = bustupAlloc(ref_245, left, rgb(0,0,0));
    bustupFade(ref_247, rgb(128,0,0), 30);
    ref_249 = dialogAlloc();
    ref_24a = msgShow(msg_28);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Plans to destroy the world using Wang Long.
[tab]And then the Torifune...
[tab]The Chief must have spread this rumor...
[wait][clear][color(yellow)]Elly[color(white)]
[tab]It is true that the information we have
[tab]spread has made them more credible...
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_6, 1);
    wait(ref_24a);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_249);
    ref_24f = bustupFade(ref_247, rgb(0,0,0), 10);
    bustupWait(ref_24f);
    bustupFree(ref_247);
    unitRestoreFacing(elly);
    b(label_263);
  label_254:
    unitFacePlayer(elly);
    ref_255 = bustupLoad(bustup_40);
    bustupWait(ref_255);
    ref_257 = bustupAlloc(ref_255, left, rgb(0,0,0));
    bustupFade(ref_257, rgb(128,0,0), 30);
    ref_259 = dialogAlloc();
    ref_25a = msgShow(msg_29);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Wang Long Chizuru...
[tab]I wonder what Mr. Kandori’s
[tab]existence meant to her...
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_6, 1);
    wait(ref_25a);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_259);
    ref_25f = bustupFade(ref_257, rgb(0,0,0), 10);
    bustupWait(ref_25f);
    bustupFree(ref_257);
    unitRestoreFacing(elly);
  label_263:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_29b);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_28b);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_27d);
    unitFacePlayer(tatsuya);
    ref_26d = bustupLoad(bustup_b);
    bustupWait(ref_26d);
    ref_26f = bustupAlloc(ref_26d, right, rgb(0,0,0));
    bustupFade(ref_26f, rgb(128,0,0), 30);
    bustupFlip(ref_26f, true);
    ref_272 = dialogAlloc();
    ref_273 = msgShow(msg_30);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]Kandori...
[tab]Was he trying to tell me something...?
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_6, 1);
    wait(ref_273);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_272);
    ref_278 = bustupFade(ref_26f, rgb(0,0,0), 10);
    bustupWait(ref_278);
    bustupFree(ref_26f);
    unitRestoreFacing(tatsuya);
    b(label_2aa);
  label_27d:
    ref_27d = bustupLoad(bustup_c);
    bustupWait(ref_27d);
    ref_27f = bustupAlloc(ref_27d, left, rgb(0,0,0));
    bustupFade(ref_27f, rgb(128,0,0), 30);
    ref_281 = dialogAlloc();
    ref_282 = msgShow(msg_31);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]Natural Pheromone...
[tab]PheromaXX... huh...
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_6, 1);
    wait(ref_282);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_281);
    ref_287 = bustupFade(ref_27f, rgb(0,0,0), 10);
    bustupWait(ref_287);
    bustupFree(ref_27f);
    b(label_2aa);
  label_28b:
    unitFacePlayer(tatsuya);
    ref_28c = bustupLoad(bustup_b);
    bustupWait(ref_28c);
    ref_28e = bustupAlloc(ref_28c, left, rgb(0,0,0));
    bustupFade(ref_28e, rgb(128,0,0), 30);
    ref_290 = dialogAlloc();
    ref_291 = msgShow(msg_32);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]The dragons haven’t appeared.
[tab]It means that the Ritual hasn’t been held.
[tab]We can still make it!
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2f, 1);
    wait(ref_291);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_290);
    ref_296 = bustupFade(ref_28e, rgb(0,0,0), 10);
    bustupWait(ref_296);
    bustupFree(ref_28e);
    unitRestoreFacing(tatsuya);
    b(label_2aa);
  label_29b:
    unitFacePlayer(tatsuya);
    ref_29c = bustupLoad(bustup_12);
    bustupWait(ref_29c);
    ref_29e = bustupAlloc(ref_29c, left, rgb(0,0,0));
    bustupFade(ref_29e, rgb(128,0,0), 30);
    ref_2a0 = dialogAlloc();
    ref_2a1 = msgShow(msg_33);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]I always remember that scene...
[tab]If only... I... had more power...
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_6, 1);
    wait(ref_2a1);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2a0);
    ref_2a6 = bustupFade(ref_29e, rgb(0,0,0), 10);
    bustupWait(ref_2a6);
    bustupFree(ref_29e);
    unitRestoreFacing(tatsuya);
  label_2aa:
    controlEnable();
}

function SHOPBOX()
{
    controlDisable();
    bitGet(var_0, MBIT_KAOYASUMI);
    bne(var_0, 0, label_2b1);
    shopOverlayInit();
    b(label_2b3);
  label_2b1:
    bne(var_0, 1, label_2b3);
    b(label_2b3);
  label_2b3:
    unitFacePlayer(shopkeeper);
    bitGet(var_0, MBIT_KAHENIDIS);
    bne(var_0, 0, label_2d6);
    bitGet(var_0, MBIT_HI_KAORIAROMA);
    bne(var_0, 0, label_2c0);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_2bc);
    b(label_45e);
    b(label_2bf);
  label_2bc:
    bne(var_0, 1, label_2bf);
    b(label_479);
    b(label_2bf);
  label_2bf:
    b(label_2d5);
  label_2c0:
    bne(var_0, 1, label_2d5);
    bitGet(var_0, MBIT_SYOUAROMA);
    bne(var_0, 0, label_2cb);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_2c7);
    b(label_34a);
    b(label_2ca);
  label_2c7:
    bne(var_0, 1, label_2ca);
    b(label_361);
    b(label_2ca);
  label_2ca:
    b(label_2d4);
  label_2cb:
    bne(var_0, 1, label_2d4);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_2d0);
    b(label_45e);
    b(label_2d3);
  label_2d0:
    bne(var_0, 1, label_2d3);
    b(label_479);
    b(label_2d3);
  label_2d3:
    b(label_2d4);
  label_2d4:
    b(label_2d5);
  label_2d5:
    b(label_34a);
  label_2d6:
    bne(var_0, 1, label_34a);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_2ed);
    bitGet(var_0, MBIT_KAOYASUMI);
    bne(var_0, 0, label_2e3);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_2df);
    b(label_45e);
    b(label_2e2);
  label_2df:
    bne(var_0, 1, label_2e2);
    b(label_479);
    b(label_2e2);
  label_2e2:
    b(label_2ec);
  label_2e3:
    bne(var_0, 1, label_2ec);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_2e8);
    b(label_3a6);
    b(label_2eb);
  label_2e8:
    bne(var_0, 1, label_2eb);
    b(label_402);
    b(label_2eb);
  label_2eb:
    b(label_2ec);
  label_2ec:
    b(label_349);
  label_2ed:
    bne(var_0, 1, label_349);
    bitGet(var_0, MBIT_COUSZOU);
    bne(var_0, 0, label_33f);
    bitSet(TBIT_HE_KA);
    bitSet(TBIT_101);
    bitSet(TBIT_102);
    bitSet(TBIT_103);
    bitSet(TBIT_201);
    bitSet(TBIT_202);
    bitSet(TBIT_203);
    bitSet(TBIT_301);
    bitSet(TBIT_302);
    bitSet(TBIT_303);
    bitSet(TBIT_401);
    bitSet(TBIT_402);
    bitSet(TBIT_403);
    bitSet(TBIT_501);
    bitSet(TBIT_502);
    bitSet(TBIT_503);
    bitSet(TBIT_601);
    bitSet(TBIT_602);
    bitClear(TBIT_HE_RA);
    bitClear(TBIT_HE_RB);
    bitClear(MBIT_MI_MONSYOU);
    bitClear(MBIT_MI_ROSAHEN_A);
    bitClear(MBIT_MI_ROSAHEN_B);
    bitClear(MBIT_MI_KAOHEN_A);
    bitClear(MBIT_MI_KAOHEN_B);
    bitClear(MBIT_MI_JIKANSELL);
    bitClear(MBIT_MI_JIKANDUP);
    bitClear(MBIT_MI_KAORIAROMA);
    bitClear(MBIT_MI_KAORIHENNI);
    bitClear(MBIT_MI_SIRAMAN);
    bitClear(MBIT_MI_SIRAHENNI);
    bitClear(MBIT_MI_TOAARM);
    bitClear(MBIT_MI_TONYITEM);
    bitClear(MBIT_MI_MUSLOT);
    bitClear(MBIT_MI_GIGACD1);
    bitClear(MBIT_MI_GIGACD2);
    bitClear(MBIT_MI_BARARM);
    bitClear(MBIT_MI_BARHENNI);
    bitClear(MBIT_MI_ROSADEF);
    bitClear(MBIT_MI_ROSAHENNI);
    bitClear(MBIT_MI_ETEESTHE);
    bitClear(MBIT_MI_ETEHENNI);
    bitClear(MBIT_MI_GYPAISHO1);
    bitClear(MBIT_MI_GYPAISHO2);
    bitClear(MBIT_MI_CLEARM);
    bitClear(MBIT_MI_CLEAOBA);
    bitClear(MBIT_MI_JEWDEVE);
    bitClear(MBIT_MI_JEWKOUNAN);
    bitClear(MBIT_MI_SKYMAP);
    bitClear(MBIT_MI_TRISHOKUJI);
    bitClear(MBIT_MI_TRIKAISIN);
    bitClear(MBIT_MI_BATOLUBUKI);
    bitClear(MBIT_MI_MAGICKITEM);
    bitClear(MBIT_MI_PELPELBUKI);
    bitClear(MBIT_MI_DEVIL1);
    bitClear(MBIT_MI_DEVIL2);
    bitClear(MBIT_MI_DEVIL3);
    bitClear(MBIT_MI_DEVIL4);
    bitClear(MBIT_MI_DEVIL5);
    bitClear(MBIT_MI_DEVIL6);
    bitClear(MBIT_MI_DEVIL7);
    bitClear(MBIT_MI_DEVIL8);
    bitClear(MBIT_MI_DEVIL9);
    bitClear(MBIT_MI_DEVIL10);
    bitClear(MBIT_MI_DENNSETU);
    bitClear(MBIT_MI_NANJOTOUJO);
    bitClear(MBIT_MI_HANAKOTOBA);
    bitClear(MBIT_MI_TATUNOSIN);
    bitClear(MBIT_MI_MAIHIME);
    bitClear(MBIT_MI_ZODI2F);
    bitClear(MBIT_MI_GYPSTART);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_33b);
    b(label_378);
    b(label_33e);
  label_33b:
    bne(var_0, 1, label_33e);
    b(label_38f);
    b(label_33e);
  label_33e:
    b(label_348);
  label_33f:
    bne(var_0, 1, label_348);
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_344);
    b(label_45e);
    b(label_347);
  label_344:
    bne(var_0, 1, label_347);
    b(label_479);
    b(label_347);
  label_347:
    b(label_348);
  label_348:
    b(label_349);
  label_349:
    b(label_34a);
  label_34a:
    ref_34a = bustupLoad(bustup_f1);
    bustupWait(ref_34a);
    ref_34c = bustupAlloc(ref_34a, right, rgb(0,0,0));
    bustupFade(ref_34c, rgb(128,0,0), 30);
    ref_34e = dialogAlloc();
    ref_34f = msgShow(msg_34);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Welcome to my shop.
[tab]I’ve prepared a new fragrance course.
[tab]I call it the "Encounter Aroma".
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]By putting on a certain scent, it changes
[tab]your surroundings and you will have new
[tab]meetings. Please give it a try.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    bitSet(MBIT_SYOUAROMA);
    wait(ref_34f);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_34e);
    ref_355 = bustupFade(ref_34c, rgb(0,0,0), 10);
    bustupWait(ref_355);
    bustupFree(ref_34c);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_35c);
    shopInventory(22, shopInventory_0);
    b(label_35f);
  label_35c:
    bne(var_0, 1, label_35f);
    shopInventory(22, shopInventory_1);
    b(label_35f);
  label_35f:
    shopRate(100);
    b(label_493);
  label_361:
    ref_361 = bustupLoad(bustup_f1);
    bustupWait(ref_361);
    ref_363 = bustupAlloc(ref_361, right, rgb(0,0,0));
    bustupFade(ref_363, rgb(128,0,0), 30);
    ref_365 = dialogAlloc();
    ref_366 = msgShow(msg_35);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Welcome to my shop.
[tab]I’ve prepared a new fragrance course.
[tab]I call it the "Encounter Aroma".
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]By putting on a certain scent, it changes
[tab]your surroundings and you will have new
[tab]meetings. Please give it a try.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]I will lower the price just for you.
[tab]I feel a special connection to you...
[tab]Please give it a try.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    bitSet(MBIT_SYOUAROMA);
    wait(ref_366);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_365);
    ref_36c = bustupFade(ref_363, rgb(0,0,0), 10);
    bustupWait(ref_36c);
    bustupFree(ref_363);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_373);
    shopInventory(22, shopInventory_0);
    b(label_376);
  label_373:
    bne(var_0, 1, label_376);
    shopInventory(22, shopInventory_1);
    b(label_376);
  label_376:
    shopRate(80);
    b(label_493);
  label_378:
    ref_378 = bustupLoad(bustup_f1);
    bustupWait(ref_378);
    ref_37a = bustupAlloc(ref_378, right, rgb(0,0,0));
    bustupFade(ref_37a, rgb(128,0,0), 30);
    ref_37c = dialogAlloc();
    ref_37d = msgShow(msg_36);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Welcome to my shop.
[tab]The other day, I went abroad to look for
[tab]a new essential oil.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]After going through much trouble I was
[tab]able to get the finest scent.
[tab]I do recommend you try this at least once.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    bitSet(MBIT_COUSZOU);
    wait(ref_37d);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_37c);
    ref_383 = bustupFade(ref_37a, rgb(0,0,0), 10);
    bustupWait(ref_383);
    bustupFree(ref_37a);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_38a);
    shopInventory(22, shopInventory_0);
    b(label_38d);
  label_38a:
    bne(var_0, 1, label_38d);
    shopInventory(22, shopInventory_1);
    b(label_38d);
  label_38d:
    shopRate(100);
    b(label_493);
  label_38f:
    ref_38f = bustupLoad(bustup_f1);
    bustupWait(ref_38f);
    ref_391 = bustupAlloc(ref_38f, right, rgb(0,0,0));
    bustupFade(ref_391, rgb(128,0,0), 30);
    ref_393 = dialogAlloc();
    ref_394 = msgShow(msg_37);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Welcome to my shop.
[tab]The other day, I went abroad to look for
[tab]a new essential oil.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]After going through much trouble I was
[tab]able to get the finest scent.
[tab]I do recommend you try this at least once.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]I will lower the price just for you.
[tab]I feel a special connection to you...
[tab]Please give it a try.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    bitSet(MBIT_COUSZOU);
    wait(ref_394);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_393);
    ref_39a = bustupFade(ref_391, rgb(0,0,0), 10);
    bustupWait(ref_39a);
    bustupFree(ref_391);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_3a1);
    shopInventory(22, shopInventory_0);
    b(label_3a4);
  label_3a1:
    bne(var_0, 1, label_3a4);
    shopInventory(22, shopInventory_1);
    b(label_3a4);
  label_3a4:
    shopRate(80);
    b(label_493);
  label_3a6:
    ref_3a6 = bustupLoad(bustup_f1);
    bustupWait(ref_3a6);
    ref_3a8 = bustupAlloc(ref_3a6, right, rgb(0,0,0));
    bustupFade(ref_3a8, rgb(128,0,0), 30);
    ref_3aa = dialogAlloc();
    ref_3ab = msgShow(msg_38);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]I’m sorry... I’ve caught a cold
[tab]and I can’t smell anything...
[tab]I won’t be able to treat you today...
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_3ab);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_3aa);
    ref_3b0 = bustupFade(ref_3a8, rgb(0,0,0), 10);
    bustupWait(ref_3b0);
    bustupFree(ref_3a8);
    bitGet(var_0, MBIT_GAT_URARA_01);
    bne(var_0, 0, label_3fe);
    bitSet(MBIT_GAT_URARA_01);
    bitSet(TBIT_HE_KB);
    bitSet(TBIT_101);
    bitSet(TBIT_102);
    bitSet(TBIT_103);
    bitSet(TBIT_201);
    bitSet(TBIT_202);
    bitSet(TBIT_203);
    bitSet(TBIT_301);
    bitSet(TBIT_302);
    bitSet(TBIT_303);
    bitSet(TBIT_401);
    bitSet(TBIT_402);
    bitSet(TBIT_403);
    bitSet(TBIT_501);
    bitSet(TBIT_502);
    bitSet(TBIT_503);
    bitSet(TBIT_601);
    bitSet(TBIT_602);
    bitClear(TBIT_HE_RA);
    bitClear(TBIT_HE_RB);
    bitClear(MBIT_MI_MONSYOU);
    bitClear(MBIT_MI_ROSAHEN_A);
    bitClear(MBIT_MI_ROSAHEN_B);
    bitClear(MBIT_MI_KAOHEN_A);
    bitClear(MBIT_MI_KAOHEN_B);
    bitClear(MBIT_MI_JIKANSELL);
    bitClear(MBIT_MI_JIKANDUP);
    bitClear(MBIT_MI_KAORIAROMA);
    bitClear(MBIT_MI_KAORIHENNI);
    bitClear(MBIT_MI_SIRAMAN);
    bitClear(MBIT_MI_SIRAHENNI);
    bitClear(MBIT_MI_TOAARM);
    bitClear(MBIT_MI_TONYITEM);
    bitClear(MBIT_MI_MUSLOT);
    bitClear(MBIT_MI_GIGACD1);
    bitClear(MBIT_MI_GIGACD2);
    bitClear(MBIT_MI_BARARM);
    bitClear(MBIT_MI_BARHENNI);
    bitClear(MBIT_MI_ROSADEF);
    bitClear(MBIT_MI_ROSAHENNI);
    bitClear(MBIT_MI_ETEESTHE);
    bitClear(MBIT_MI_ETEHENNI);
    bitClear(MBIT_MI_GYPAISHO1);
    bitClear(MBIT_MI_GYPAISHO2);
    bitClear(MBIT_MI_CLEARM);
    bitClear(MBIT_MI_CLEAOBA);
    bitClear(MBIT_MI_JEWDEVE);
    bitClear(MBIT_MI_JEWKOUNAN);
    bitClear(MBIT_MI_SKYMAP);
    bitClear(MBIT_MI_TRISHOKUJI);
    bitClear(MBIT_MI_TRIKAISIN);
    bitClear(MBIT_MI_BATOLUBUKI);
    bitClear(MBIT_MI_MAGICKITEM);
    bitClear(MBIT_MI_PELPELBUKI);
    bitClear(MBIT_MI_DEVIL1);
    bitClear(MBIT_MI_DEVIL2);
    bitClear(MBIT_MI_DEVIL3);
    bitClear(MBIT_MI_DEVIL4);
    bitClear(MBIT_MI_DEVIL5);
    bitClear(MBIT_MI_DEVIL6);
    bitClear(MBIT_MI_DEVIL7);
    bitClear(MBIT_MI_DEVIL8);
    bitClear(MBIT_MI_DEVIL9);
    bitClear(MBIT_MI_DEVIL10);
    bitClear(MBIT_MI_DENNSETU);
    bitClear(MBIT_MI_NANJOTOUJO);
    bitClear(MBIT_MI_HANAKOTOBA);
    bitClear(MBIT_MI_TATUNOSIN);
    bitClear(MBIT_MI_MAIHIME);
    bitClear(MBIT_MI_ZODI2F);
    bitClear(MBIT_MI_GYPSTART);
    b(label_400);
  label_3fe:
    bne(var_0, 1, label_400);
    b(label_400);
  label_400:
    controlEnable();
    b(label_4f1);
  label_402:
    ref_402 = bustupLoad(bustup_f1);
    bustupWait(ref_402);
    ref_404 = bustupAlloc(ref_402, right, rgb(0,0,0));
    bustupFade(ref_404, rgb(128,0,0), 30);
    ref_406 = dialogAlloc();
    ref_407 = msgShow(msg_39);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]I’m sorry... I’ve caught a cold
[tab]and I can’t smell anything...
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]Even though I feel this special connection
[tab]with you I’m unable to offer a nice scent.
[tab]I need to rest a little while...
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_407);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_406);
    ref_40c = bustupFade(ref_404, rgb(0,0,0), 10);
    bustupWait(ref_40c);
    bustupFree(ref_404);
    bitGet(var_0, MBIT_GAT_URARA_01);
    bne(var_0, 0, label_45a);
    bitSet(MBIT_GAT_URARA_01);
    bitSet(TBIT_HE_KB);
    bitSet(TBIT_101);
    bitSet(TBIT_102);
    bitSet(TBIT_103);
    bitSet(TBIT_201);
    bitSet(TBIT_202);
    bitSet(TBIT_203);
    bitSet(TBIT_301);
    bitSet(TBIT_302);
    bitSet(TBIT_303);
    bitSet(TBIT_401);
    bitSet(TBIT_402);
    bitSet(TBIT_403);
    bitSet(TBIT_501);
    bitSet(TBIT_502);
    bitSet(TBIT_503);
    bitSet(TBIT_601);
    bitSet(TBIT_602);
    bitClear(TBIT_HE_RA);
    bitClear(TBIT_HE_RB);
    bitClear(MBIT_MI_MONSYOU);
    bitClear(MBIT_MI_ROSAHEN_A);
    bitClear(MBIT_MI_ROSAHEN_B);
    bitClear(MBIT_MI_KAOHEN_A);
    bitClear(MBIT_MI_KAOHEN_B);
    bitClear(MBIT_MI_JIKANSELL);
    bitClear(MBIT_MI_JIKANDUP);
    bitClear(MBIT_MI_KAORIAROMA);
    bitClear(MBIT_MI_KAORIHENNI);
    bitClear(MBIT_MI_SIRAMAN);
    bitClear(MBIT_MI_SIRAHENNI);
    bitClear(MBIT_MI_TOAARM);
    bitClear(MBIT_MI_TONYITEM);
    bitClear(MBIT_MI_MUSLOT);
    bitClear(MBIT_MI_GIGACD1);
    bitClear(MBIT_MI_GIGACD2);
    bitClear(MBIT_MI_BARARM);
    bitClear(MBIT_MI_BARHENNI);
    bitClear(MBIT_MI_ROSADEF);
    bitClear(MBIT_MI_ROSAHENNI);
    bitClear(MBIT_MI_ETEESTHE);
    bitClear(MBIT_MI_ETEHENNI);
    bitClear(MBIT_MI_GYPAISHO1);
    bitClear(MBIT_MI_GYPAISHO2);
    bitClear(MBIT_MI_CLEARM);
    bitClear(MBIT_MI_CLEAOBA);
    bitClear(MBIT_MI_JEWDEVE);
    bitClear(MBIT_MI_JEWKOUNAN);
    bitClear(MBIT_MI_SKYMAP);
    bitClear(MBIT_MI_TRISHOKUJI);
    bitClear(MBIT_MI_TRIKAISIN);
    bitClear(MBIT_MI_BATOLUBUKI);
    bitClear(MBIT_MI_MAGICKITEM);
    bitClear(MBIT_MI_PELPELBUKI);
    bitClear(MBIT_MI_DEVIL1);
    bitClear(MBIT_MI_DEVIL2);
    bitClear(MBIT_MI_DEVIL3);
    bitClear(MBIT_MI_DEVIL4);
    bitClear(MBIT_MI_DEVIL5);
    bitClear(MBIT_MI_DEVIL6);
    bitClear(MBIT_MI_DEVIL7);
    bitClear(MBIT_MI_DEVIL8);
    bitClear(MBIT_MI_DEVIL9);
    bitClear(MBIT_MI_DEVIL10);
    bitClear(MBIT_MI_DENNSETU);
    bitClear(MBIT_MI_NANJOTOUJO);
    bitClear(MBIT_MI_HANAKOTOBA);
    bitClear(MBIT_MI_TATUNOSIN);
    bitClear(MBIT_MI_MAIHIME);
    bitClear(MBIT_MI_ZODI2F);
    bitClear(MBIT_MI_GYPSTART);
    b(label_45c);
  label_45a:
    bne(var_0, 1, label_45c);
    b(label_45c);
  label_45c:
    controlEnable();
    b(label_4f1);
  label_45e:
    ref_45e = bustupLoad(bustup_f1);
    bustupWait(ref_45e);
    ref_460 = bustupAlloc(ref_45e, right, rgb(0,0,0));
    bustupFade(ref_460, rgb(128,0,0), 30);
    ref_462 = dialogAlloc();
    ref_463 = msgShow(msg_40);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Welcome to my shop.
[tab]What scent are you looking for today?
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_463);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_462);
    ref_468 = bustupFade(ref_460, rgb(0,0,0), 10);
    bustupWait(ref_468);
    bustupFree(ref_460);
    shopRate(100);
    bitGet(var_0, MBIT_HI_KAORIAROMA);
    bne(var_0, 0, label_46f);
    b(label_478);
  label_46f:
    bne(var_0, 1, label_478);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_474);
    shopInventory(22, shopInventory_0);
    b(label_477);
  label_474:
    bne(var_0, 1, label_477);
    shopInventory(22, shopInventory_1);
    b(label_477);
  label_477:
    b(label_478);
  label_478:
    b(label_493);
  label_479:
    ref_479 = bustupLoad(bustup_f1);
    bustupWait(ref_479);
    ref_47b = bustupAlloc(ref_479, right, rgb(0,0,0));
    bustupFade(ref_47b, rgb(128,0,0), 30);
    ref_47d = dialogAlloc();
    ref_47e = msgShow(msg_41);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]I sense... a mysterious scent from you.
[tab]A heartwarming, gentle smell...
[tab]I will reconsider the prices for you.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_47e);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_47d);
    ref_483 = bustupFade(ref_47b, rgb(0,0,0), 10);
    bustupWait(ref_483);
    bustupFree(ref_47b);
    shopRate(80);
    bitGet(var_0, MBIT_HI_KAORIAROMA);
    bne(var_0, 0, label_48a);
    b(label_493);
  label_48a:
    bne(var_0, 1, label_493);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_48f);
    shopInventory(22, shopInventory_0);
    b(label_492);
  label_48f:
    bne(var_0, 1, label_492);
    shopInventory(22, shopInventory_1);
    b(label_492);
  label_492:
    b(label_493);
  label_493:
    bitGet(var_0, MBIT_HI_KAORIAROMA);
    bne(var_0, 0, label_4c1);
    choiceSetResult(2);
    op_105(3);
    ref_497 = bustupLoad(bustup_f1);
    bustupWait(ref_497);
    ref_499 = bustupAlloc(ref_497, right, rgb(0,0,0));
    bustupFade(ref_499, rgb(128,0,0), 30);
    ref_49b = dialogAlloc();
    ref_49c = msgShow(msg_42);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]What fragrance have you come for today?
[choice(4)]Heal
Talk to Miss Kaori
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_49c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4a4);
    li(var_5, 0);
    b(label_4ba);
  label_4a4:
    bne(var_0, 1, label_4b4);
    choiceSetResult(2);
    op_105(2);
    ref_4a7 = msgShow(msg_43);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]And what do you propose we speak of?
[choice(2)]Make small talk
Ask about the shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear]
***************************************/
    wait(ref_4a7);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4ad);
    li(var_5, 1);
    b(label_4b3);
  label_4ad:
    bne(var_0, 1, label_4b0);
    li(var_5, 2000);
    b(label_4b3);
  label_4b0:
    bne(var_0, 2, label_4b3);
    li(var_5, 1000);
    b(label_4b3);
  label_4b3:
    b(label_4ba);
  label_4b4:
    bne(var_0, 2, label_4b7);
    li(var_5, 2);
    b(label_4ba);
  label_4b7:
    bne(var_0, 3, label_4ba);
    li(var_5, 3);
    b(label_4ba);
  label_4ba:
    dialogFree(ref_49b);
    ref_4bb = bustupFade(ref_499, rgb(0,0,0), 10);
    bustupWait(ref_4bb);
    bustupFree(ref_499);
    ref_4be = shopOpen(11);
    wait(ref_4be);
    b(label_4f1);
  label_4c1:
    bne(var_0, 1, label_4f1);
    choiceSetResult(3);
    op_105(3);
    ref_4c4 = bustupLoad(bustup_f1);
    bustupWait(ref_4c4);
    ref_4c6 = bustupAlloc(ref_4c4, right, rgb(0,0,0));
    bustupFade(ref_4c6, rgb(128,0,0), 30);
    ref_4c8 = dialogAlloc();
    ref_4c9 = msgShow(msg_44);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]What fragrance have you come for today?
[choice(4)]Heal
Aromatherapy
Talk to Miss Kaori
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_4c9);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4d1);
    li(var_5, 0);
    b(label_4ea);
  label_4d1:
    bne(var_0, 1, label_4d4);
    li(var_5, 1);
    b(label_4ea);
  label_4d4:
    bne(var_0, 2, label_4e4);
    choiceSetResult(2);
    op_105(2);
    ref_4d7 = msgShow(msg_45);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]And what do you propose we speak of?
[choice(2)]Make small talk
Ask about the shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear]
***************************************/
    wait(ref_4d7);
    choiceGetResult(var_0);
    bne(var_0, 0, label_4dd);
    li(var_5, 2);
    b(label_4e3);
  label_4dd:
    bne(var_0, 1, label_4e0);
    li(var_5, 2000);
    b(label_4e3);
  label_4e0:
    bne(var_0, 2, label_4e3);
    li(var_5, 1000);
    b(label_4e3);
  label_4e3:
    b(label_4ea);
  label_4e4:
    bne(var_0, 3, label_4e7);
    li(var_5, 3);
    b(label_4ea);
  label_4e7:
    bne(var_0, 4, label_4ea);
    li(var_5, 4);
    b(label_4ea);
  label_4ea:
    dialogFree(ref_4c8);
    ref_4eb = bustupFade(ref_4c6, rgb(0,0,0), 10);
    bustupWait(ref_4eb);
    bustupFree(ref_4c6);
    ref_4ee = shopOpen(3);
    wait(ref_4ee);
    b(label_4f1);
  label_4f1:
}

function HA_SHOP_RESTART_0()
{
    bitGet(var_0, MBIT_HI_KAORIAROMA);
    bne(var_0, 0, label_51e);
    choiceSetResult(2);
    op_105(3);
    ref_4f6 = bustupLoad(bustup_f1);
    bustupWait(ref_4f6);
    ref_4f8 = bustupAlloc(ref_4f6, right, rgb(0,0,0));
    bustupFade(ref_4f8, rgb(128,0,0), 30);
    ref_4fa = dialogAlloc();
    ref_4fb = msgShow(msg_46);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Is there anything else I can help you with?
[choice(4)]Heal
Talk to Miss Kaori
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_4fb);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_503);
    li(var_5, 0);
    b(label_519);
  label_503:
    bne(var_0, 1, label_513);
    choiceSetResult(2);
    op_105(2);
    ref_506 = msgShow(msg_47);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]And what do you propose we speak of?
[choice(2)]Make small talk
Ask about the shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear]
***************************************/
    wait(ref_506);
    choiceGetResult(var_0);
    bne(var_0, 0, label_50c);
    li(var_5, 1);
    b(label_512);
  label_50c:
    bne(var_0, 1, label_50f);
    li(var_5, 2000);
    b(label_512);
  label_50f:
    bne(var_0, 2, label_512);
    li(var_5, 1000);
    b(label_512);
  label_512:
    b(label_519);
  label_513:
    bne(var_0, 2, label_516);
    li(var_5, 2);
    b(label_519);
  label_516:
    bne(var_0, 3, label_519);
    li(var_5, 3);
    b(label_519);
  label_519:
    dialogFree(ref_4fa);
    ref_51a = bustupFade(ref_4f8, rgb(0,0,0), 10);
    bustupWait(ref_51a);
    bustupFree(ref_4f8);
    b(label_54c);
  label_51e:
    bne(var_0, 1, label_54c);
    choiceSetResult(3);
    op_105(3);
    ref_521 = bustupLoad(bustup_f1);
    bustupWait(ref_521);
    ref_523 = bustupAlloc(ref_521, right, rgb(0,0,0));
    bustupFade(ref_523, rgb(128,0,0), 30);
    ref_525 = dialogAlloc();
    ref_526 = msgShow(msg_48);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Is there anything else I can help you with?
[choice(4)]Heal
Aromatherapy
Talk to Miss Kaori
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_526);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_52e);
    li(var_5, 0);
    b(label_547);
  label_52e:
    bne(var_0, 1, label_531);
    li(var_5, 1);
    b(label_547);
  label_531:
    bne(var_0, 2, label_541);
    choiceSetResult(2);
    op_105(2);
    ref_534 = msgShow(msg_49);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]And what do you propose we speak of?
[choice(2)]Make small talk
Ask about the shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear]
***************************************/
    wait(ref_534);
    choiceGetResult(var_0);
    bne(var_0, 0, label_53a);
    li(var_5, 2);
    b(label_540);
  label_53a:
    bne(var_0, 1, label_53d);
    li(var_5, 2000);
    b(label_540);
  label_53d:
    bne(var_0, 2, label_540);
    li(var_5, 1000);
    b(label_540);
  label_540:
    b(label_547);
  label_541:
    bne(var_0, 3, label_544);
    li(var_5, 3);
    b(label_547);
  label_544:
    bne(var_0, 4, label_547);
    li(var_5, 4);
    b(label_547);
  label_547:
    dialogFree(ref_525);
    ref_548 = bustupFade(ref_523, rgb(0,0,0), 10);
    bustupWait(ref_548);
    bustupFree(ref_523);
    b(label_54c);
  label_54c:
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_57d);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_56f);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_561);
    ref_553 = bustupLoad(bustup_f1);
    bustupWait(ref_553);
    ref_555 = bustupAlloc(ref_553, right, rgb(0,0,0));
    bustupFade(ref_555, rgb(128,0,0), 30);
    ref_557 = dialogAlloc();
    ref_558 = msgShow(msg_50);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]When you think of him, your heart aches.
[tab]For you, I suggest Geranium and Rose.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]Geranium will balance out your heart,
[tab]and the rose will cheer you up.
[tab]I hope you have a nice day.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_558);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_557);
    ref_55d = bustupFade(ref_555, rgb(0,0,0), 10);
    bustupWait(ref_55d);
    bustupFree(ref_555);
    b(label_58a);
  label_561:
    ref_561 = bustupLoad(bustup_f1);
    bustupWait(ref_561);
    ref_563 = bustupAlloc(ref_561, right, rgb(0,0,0));
    bustupFade(ref_563, rgb(128,0,0), 30);
    ref_565 = dialogAlloc();
    ref_566 = msgShow(msg_51);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]What is the New World Order trying
[tab]to do by erasing the Kegare from
[tab]people’s hearts?
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]Isn’t the Kegare a part of the heart too?
[tab]If you lose it, it is the same as not being
[tab]human. What could be the consequences...
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_566);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_565);
    ref_56b = bustupFade(ref_563, rgb(0,0,0), 10);
    bustupWait(ref_56b);
    bustupFree(ref_563);
    b(label_58a);
  label_56f:
    ref_56f = bustupLoad(bustup_f1);
    bustupWait(ref_56f);
    ref_571 = bustupAlloc(ref_56f, right, rgb(0,0,0));
    bustupFade(ref_571, rgb(128,0,0), 30);
    ref_573 = dialogAlloc();
    ref_574 = msgShow(msg_52);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Good and bad can change depending
[tab]on your point of view.
[tab]Isn’t the Kegare of people like that too?
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]People’s hearts cannot be measured
[tab]by one standard alone.
[tab]I can’t understand their way of thinking.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_574);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_573);
    ref_579 = bustupFade(ref_571, rgb(0,0,0), 10);
    bustupWait(ref_579);
    bustupFree(ref_571);
    b(label_58a);
  label_57d:
    ref_57d = bustupLoad(bustup_f1);
    bustupWait(ref_57d);
    ref_57f = bustupAlloc(ref_57d, right, rgb(0,0,0));
    bustupFade(ref_57f, rgb(128,0,0), 30);
    ref_581 = dialogAlloc();
    ref_582 = msgShow(msg_53);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]It’s strange...
[tab]I feel that this happened before...
[tab]Maybe I dreamed the city was flying.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_582);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_581);
    ref_587 = bustupFade(ref_57f, rgb(0,0,0), 10);
    bustupWait(ref_587);
    bustupFree(ref_57f);
  label_58a:
}

function HA_SHOP_END_0()
{
    ref_58b = bustupLoad(bustup_f1);
    bustupWait(ref_58b);
    ref_58d = bustupAlloc(ref_58b, right, rgb(0,0,0));
    bustupFade(ref_58d, rgb(128,0,0), 30);
    ref_58f = dialogAlloc();
    ref_590 = msgShow(msg_54);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Please come again.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_590);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    ref_594 = bustupFade(ref_58d, rgb(0,0,0), 10);
    bustupWait(ref_594);
    bustupFree(ref_58d);
    shopOverlayInit();
    dialogFree(ref_58f);
    delayClear();
    delayWait(10);
    bitSet(MBIT_KAORIRIYOU);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_5a1);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    b(label_5a4);
  label_5a1:
    bne(var_0, 1, label_5a4);
    call(GOOUT);
    b(label_5a4);
  label_5a4:
}

function HA_SHOP_HEAL_0()
{
    ref_5a5 = call(KAIFUKUSURUBEKI);
    wait(ref_5a5);
    bitGet(var_1, LBIT_0000);
    bne(var_1, 0, label_5b8);
    ref_5a9 = bustupLoad(bustup_f1);
    bustupWait(ref_5a9);
    ref_5ab = bustupAlloc(ref_5a9, right, rgb(0,0,0));
    bustupFade(ref_5ab, rgb(128,0,0), 30);
    ref_5ad = dialogAlloc();
    ref_5ae = msgShow(msg_55);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]My...[delay(15)]
[tab]You all seem very healthy.[delay(15)]
[tab]You do not need treatment.[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_5ae);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_5ad);
    ref_5b3 = bustupFade(ref_5ab, rgb(0,0,0), 10);
    bustupWait(ref_5b3);
    bustupFree(ref_5ab);
    b(label_647);
    b(label_5ea);
  label_5b8:
    bne(var_1, 1, label_5ea);
    ref_5b9 = bustupLoad(bustup_f1);
    bustupWait(ref_5b9);
    ref_5bb = bustupAlloc(ref_5b9, right, rgb(0,0,0));
    bustupFade(ref_5bb, rgb(128,0,0), 30);
    ref_5bd = dialogAlloc();
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_5c5);
    shopInventory(3, shopInventory_-bb8);
    ref_5c1 = msgShow(msg_56);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Okay...
[tab]That will be ¥3000 for everyone...[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_5c1);
    b(label_5cb);
  label_5c5:
    bne(var_0, 1, label_5cb);
    shopInventory(3, shopInventory_-5dc);
    ref_5c7 = msgShow(msg_57);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Since you’re my special customers...
[tab]I’ll make it half that, ¥1500.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_5c7);
    b(label_5cb);
  label_5cb:
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_5bd);
    ref_5cd = bustupFade(ref_5bb, rgb(0,0,0), 10);
    bustupWait(ref_5cd);
    bustupFree(ref_5bb);
    choiceSetResult(1);
    op_105(1);
    ref_5d2 = bustupLoad(bustup_1);
    bustupWait(ref_5d2);
    ref_5d4 = bustupAlloc(ref_5d2, center, rgb(0,0,0));
    bustupFade(ref_5d4, rgb(128,0,0), 30);
    ref_5d6 = dialogChoiceAlloc();
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_5d9 = msgShow(msg_58);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Would you like it?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_5d9);
    dialogFree(ref_5d6);
    ref_5dc = bustupFade(ref_5d4, rgb(0,0,0), 10);
    bustupWait(ref_5dc);
    bustupFree(ref_5d4);
    choiceGetResult(var_0);
    bne(var_0, 0, label_5e3);
    b(label_5ea);
    b(label_5e9);
  label_5e3:
    bne(var_0, 1, label_5e9);
    shopCurrencyDisplay(-110, 150, true);
    delayClear();
    delayWait(30);
    b(label_647);
    b(label_5e9);
  label_5e9:
    b(label_5ea);
  label_5ea:
    bitGet(var_0, MBIT_AIS_47);
    bne(var_0, 0, label_5f5);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 2999, label_5f0);
    b(label_639);
    b(label_5f4);
  label_5f0:
    partyMoneyAdd(-3000);
    ref_5f1 = call(KAIFUKUMESS);
    wait(ref_5f1);
    b(label_5f4);
  label_5f4:
    b(label_5ff);
  label_5f5:
    bne(var_0, 1, label_5ff);
    partyMoneyGet(var_2);
    boutrange(var_2, 0, 1499, label_5fa);
    b(label_639);
    b(label_5fe);
  label_5fa:
    partyMoneyAdd(-1500);
    ref_5fb = call(KAIFUKUMESS);
    wait(ref_5fb);
    b(label_5fe);
  label_5fe:
    b(label_5ff);
  label_5ff:
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), add);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_3, 127);
    partyHealthRestore(maya);
    partySPRestore(maya);
    partyStatusClear(maya);
    partyMemberCheck(var_3, ulala);
    bez(var_3, label_60e);
    partyHealthRestore(ulala);
    partySPRestore(ulala);
    partyStatusClear(ulala);
  label_60e:
    partyMemberCheck(var_3, katsuya);
    bez(var_3, label_613);
    partyHealthRestore(katsuya);
    partySPRestore(katsuya);
    partyStatusClear(katsuya);
  label_613:
    partyMemberCheck(var_3, baofu);
    bez(var_3, label_618);
    partyHealthRestore(baofu);
    partySPRestore(baofu);
    partyStatusClear(baofu);
  label_618:
    partyMemberCheck(var_3, nanjo);
    bez(var_3, label_61d);
    partyHealthRestore(nanjo);
    partySPRestore(nanjo);
    partyStatusClear(nanjo);
  label_61d:
    partyMemberCheck(var_3, elly);
    bez(var_3, label_622);
    partyHealthRestore(elly);
    partySPRestore(elly);
    partyStatusClear(elly);
  label_622:
    partyMemberCheck(var_3, tatsuya);
    bez(var_3, label_627);
    partyHealthRestore(tatsuya);
    partySPRestore(tatsuya);
    partyStatusClear(tatsuya);
  label_627:
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), add);
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenEffectUnknown();
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_62d = bustupLoad(bustup_1);
    bustupWait(ref_62d);
    ref_62f = bustupAlloc(ref_62d, center, rgb(0,0,0));
    bustupFade(ref_62f, rgb(128,0,0), 30);
    ref_631 = dialogAlloc();
    ref_632 = msgShow(msg_59);
/***************************************
[color(green)]Maya’s party recovered.[color(white)][wait][clear]
***************************************/
    wait(ref_632);
    dialogFree(ref_631);
    ref_635 = bustupFade(ref_62f, rgb(0,0,0), 10);
    bustupWait(ref_635);
    bustupFree(ref_62f);
    b(label_647);
  label_639:
    ref_639 = bustupLoad(bustup_f1);
    bustupWait(ref_639);
    ref_63b = bustupAlloc(ref_639, right, rgb(0,0,0));
    bustupFade(ref_63b, rgb(128,0,0), 30);
    ref_63d = dialogAlloc();
    ref_63e = msgShow(msg_60);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Excuse me...
[tab]But you don’t have enough money...
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_63e);
    shopCurrencyDisplay(-110, 150, true);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_63d);
    ref_644 = bustupFade(ref_63b, rgb(0,0,0), 10);
    bustupWait(ref_644);
    bustupFree(ref_63b);
  label_647:
}

function KAIFUKUMESS()
{
    ref_648 = bustupLoad(bustup_f1);
    bustupWait(ref_648);
    ref_64a = bustupAlloc(ref_648, right, rgb(0,0,0));
    bustupFade(ref_64a, rgb(128,0,0), 30);
    ref_64c = dialogAlloc();
    rand(var_0, 4);
    bne(var_0, 0, label_653);
    ref_64f = msgShow(msg_61);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Today, the scent is asphodel.
[tab]This fragrance will set your spirit free
[tab]and send you on another journey.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_64f);
    b(label_667);
  label_653:
    bne(var_0, 1, label_658);
    ref_654 = msgShow(msg_62);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Today, the scent is mandrake.
[tab]The mandrake can take another’s life with
[tab]its screams. Its magic can give you power.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_654);
    b(label_667);
  label_658:
    bne(var_0, 2, label_65d);
    ref_659 = msgShow(msg_63);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Today, the scent is lily.
[tab]Lily represents rebirth and immortality.
[tab]This scent will regenerate you.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_659);
    b(label_667);
  label_65d:
    bne(var_0, 3, label_662);
    ref_65e = msgShow(msg_64);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Today, the scent is laurel.
[tab]Laurel represents victory and peace.
[tab]This scent will bring you to immortality.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_65e);
    b(label_667);
  label_662:
    bne(var_0, 4, label_667);
    ref_663 = msgShow(msg_65);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Today, the scent is iris.
[tab]The iris is the flower of the Virgin Mary.
[tab]This scent will empower you with light.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_663);
    b(label_667);
  label_667:
    shopCurrencyDisplay(-110, 150, true);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_64c);
    ref_66a = bustupFade(ref_64a, rgb(0,0,0), 10);
    bustupWait(ref_66a);
    bustupFree(ref_64a);
}

function KAIFUKUSURUBEKI()
{
    partyStatusHas(var_0, maya, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, maya, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, maya, maxHealth);
    partyInfoGet(var_5, maya, health);
    beq(var_4, var_5, label_676);
    b(label_6d0);
  label_676:
    partyInfoGet(var_4, maya, maxSP);
    partyInfoGet(var_5, maya, sp);
    beq(var_4, var_5, label_67a);
    b(label_6d0);
  label_67a:
    partyMemberCheck(var_4, ulala);
    bez(var_4, label_688);
    partyStatusHas(var_0, ulala, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, ulala, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, ulala, maxHealth);
    partyInfoGet(var_5, ulala, health);
    beq(var_4, var_5, label_684);
    b(label_6d0);
  label_684:
    partyInfoGet(var_4, ulala, maxSP);
    partyInfoGet(var_5, ulala, sp);
    beq(var_4, var_5, label_688);
    b(label_6d0);
  label_688:
    partyMemberCheck(var_4, katsuya);
    bez(var_4, label_696);
    partyStatusHas(var_0, katsuya, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, katsuya, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, katsuya, maxHealth);
    partyInfoGet(var_5, katsuya, health);
    beq(var_4, var_5, label_692);
    b(label_6d0);
  label_692:
    partyInfoGet(var_4, katsuya, maxSP);
    partyInfoGet(var_5, katsuya, sp);
    beq(var_4, var_5, label_696);
    b(label_6d0);
  label_696:
    partyMemberCheck(var_4, baofu);
    bez(var_4, label_6a4);
    partyStatusHas(var_0, baofu, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, baofu, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, baofu, maxHealth);
    partyInfoGet(var_5, baofu, health);
    beq(var_4, var_5, label_6a0);
    b(label_6d0);
  label_6a0:
    partyInfoGet(var_4, baofu, maxSP);
    partyInfoGet(var_5, baofu, sp);
    beq(var_4, var_5, label_6a4);
    b(label_6d0);
  label_6a4:
    partyMemberCheck(var_4, nanjo);
    bez(var_4, label_6b2);
    partyStatusHas(var_0, nanjo, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, nanjo, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, nanjo, maxHealth);
    partyInfoGet(var_5, nanjo, health);
    beq(var_4, var_5, label_6ae);
    b(label_6d0);
  label_6ae:
    partyInfoGet(var_4, nanjo, maxSP);
    partyInfoGet(var_5, nanjo, sp);
    beq(var_4, var_5, label_6b2);
    b(label_6d0);
  label_6b2:
    partyMemberCheck(var_4, elly);
    bez(var_4, label_6c0);
    partyStatusHas(var_0, elly, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, elly, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, elly, maxHealth);
    partyInfoGet(var_5, elly, health);
    beq(var_4, var_5, label_6bc);
    b(label_6d0);
  label_6bc:
    partyInfoGet(var_4, elly, maxSP);
    partyInfoGet(var_5, elly, sp);
    beq(var_4, var_5, label_6c0);
    b(label_6d0);
  label_6c0:
    partyMemberCheck(var_4, tatsuya);
    bez(var_4, label_6ce);
    partyStatusHas(var_0, tatsuya, poison);
    bnz(var_0, label_6d0);
    partyStatusHas(var_0, tatsuya, possesion);
    bnz(var_0, label_6d0);
    partyInfoGet(var_4, tatsuya, maxHealth);
    partyInfoGet(var_5, tatsuya, health);
    beq(var_4, var_5, label_6ca);
    b(label_6d0);
  label_6ca:
    partyInfoGet(var_4, tatsuya, maxSP);
    partyInfoGet(var_5, tatsuya, sp);
    beq(var_4, var_5, label_6ce);
    b(label_6d0);
  label_6ce:
    bitClear(LBIT_0000);
    b(label_6d2);
  label_6d0:
    bitSet(LBIT_0000);
    b(label_6d2);
  label_6d2:
}

function OBASAN()
{
    controlDisable();
    bitGet(var_0, MBIT_HI_KAORIHENNI);
    bne(var_0, 0, label_6e4);
    bitGet(var_0, MBIT_HI_KAORIAROMA);
    bne(var_0, 0, label_6da);
    b(label_718);
    b(label_6e3);
  label_6da:
    bne(var_0, 1, label_6e3);
    bitGet(var_0, MBIT_MIHAALOMA);
    bne(var_0, 0, label_6df);
    b(label_6fa);
    b(label_6e2);
  label_6df:
    bne(var_0, 1, label_6e2);
    b(label_718);
    b(label_6e2);
  label_6e2:
    b(label_6e3);
  label_6e3:
    b(label_6f9);
  label_6e4:
    bne(var_0, 1, label_6f9);
    bitGet(var_0, MBIT_KAORIZOUKA);
    bne(var_0, 0, label_6ef);
    bitGet(var_0, MBIT_MIHAKAHENI);
    bne(var_0, 0, label_6eb);
    b(label_704);
    b(label_6ee);
  label_6eb:
    bne(var_0, 1, label_6ee);
    b(label_718);
    b(label_6ee);
  label_6ee:
    b(label_6f8);
  label_6ef:
    bne(var_0, 1, label_6f8);
    bitGet(var_0, MBIT_MIHAKAHENI);
    bne(var_0, 0, label_6f4);
    b(label_70e);
    b(label_6f7);
  label_6f4:
    bne(var_0, 1, label_6f7);
    b(label_718);
    b(label_6f7);
  label_6f7:
    b(label_6f8);
  label_6f8:
    b(label_6f9);
  label_6f9:
    b(label_763);
  label_6fa:
    unitFacePlayer(npc2);
    ref_6fb = dialogAlloc();
    ref_6fc = msgShow(msg_66);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]Do you know?
[tab]They’ve started a new fragrance course here.
[tab]It’s called the "Encounter Aroma".
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_6fc);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_6fb);
    unitRestoreFacing(npc2);
    bitSet(MBIT_MIHAALOMA);
    b(label_763);
  label_704:
    unitFacePlayer(npc2);
    ref_705 = dialogAlloc();
    ref_706 = msgShow(msg_67);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]This place was closed for a while.
[tab]I heard that Miss Kaori had a cold.
[tab]She shouldn’t be working so hard.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_706);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_705);
    unitRestoreFacing(npc2);
    bitSet(MBIT_MIHAKAHENI);
    b(label_763);
  label_70e:
    unitFacePlayer(npc2);
    ref_70f = dialogAlloc();
    ref_710 = msgShow(msg_68);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]This place was closed for a while.
[tab]I heard that Miss Kaori was traveling to
[tab]find a new oil. She’s so dedicated.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_710);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_70f);
    unitRestoreFacing(npc2);
    bitSet(MBIT_MIHAKAHENI);
    b(label_763);
  label_718:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_75b);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_752);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_749);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_740);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_72b);
    unitFacePlayer(npc2);
    ref_723 = dialogAlloc();
    ref_724 = msgShow(msg_69);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]Have you heard of the "New World Order"?
[tab]Supposedly, there’s a group by that name!
[tab]But I wonder what they do...
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_724);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_723);
    unitRestoreFacing(npc2);
    b(label_763);
  label_72b:
    bitGet(var_0, MBIT_KAO_TALKOG);
    bnz(var_0, label_737);
    unitFacePlayer(npc2);
    ref_72e = dialogAlloc();
    ref_72f = msgShow(msg_70);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]Have you heard? Some group called the
[tab]"New World Order" is trying to destroy
[tab]the world using Wang Long!
[wait][clear][color(yellow)]Woman[color(white)]
[tab]According to Wang Long, when the 12
[tab]dragons that run below the earth are
[tab]gathered, there will be a catastrophe...
[wait][clear][color(yellow)]Woman[color(white)]
[tab]If they’re using Wang Long to destroy
[tab]the world, they’re probably depending on
[tab]that power... But what about us!?
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_72f);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_72e);
    unitRestoreFacing(npc2);
    bitSet(MBIT_KAO_TALKOG);
    b(label_763);
  label_737:
    unitFacePlayer(npc2);
    ref_738 = dialogAlloc();
    ref_739 = msgShow(msg_71);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]I wonder if that stuff about the Torifune
[tab]is true... If it is true, then even if the
[tab]world ends, we’ll be saved...
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_739);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_738);
    unitRestoreFacing(npc2);
    b(label_763);
  label_740:
    unitFacePlayer(npc2);
    ref_741 = dialogAlloc();
    ref_742 = msgShow(msg_72);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]We’re starting to have a bunch of
[tab]earthquakes! The Torifune underneath
[tab]must have begun to move!
[wait][clear][color(yellow)]Woman[color(white)]
[tab]But...
[tab]Didn’t something like this happen before?
[tab]...That can’t be...
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_742);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_741);
    unitRestoreFacing(npc2);
    b(label_763);
  label_749:
    unitFacePlayer(npc2);
    ref_74a = dialogAlloc();
    ref_74b = msgShow(msg_73);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]Do you know the Narumi construction site...?
[tab]I heard they’re not working on the subway,
[tab]but actually excavating the Torifune!
[wait][clear][color(yellow)]Woman[color(white)]
[tab]Oh...
[tab]The Torifune does exist!
[tab]I bet the world will end!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_74b);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_74a);
    unitRestoreFacing(npc2);
    b(label_763);
  label_752:
    unitFacePlayer(npc2);
    ref_753 = dialogAlloc();
    ref_754 = msgShow(msg_74);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]Have you gone to the purification seminar? 
[tab]If you haven’t, you should go!
[tab]You can’t stay here if you have Kegare!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_754);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_753);
    unitRestoreFacing(npc2);
    b(label_763);
  label_75b:
    unitFacePlayer(npc2);
    ref_75c = dialogAlloc();
    ref_75d = msgShow(msg_75);
/***************************************
[color(yellow)]Woman[color(white)]
[tab]Hey, hey wait a minute...!
[tab]What is going on here...!?
[tab]Anyone, do something about this!!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_75d);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_75c);
    unitRestoreFacing(npc2);
  label_763:
    controlEnable();
}

function WAKAMONO()
{
    controlDisable();
    bitGet(var_0, MBIT_SH_S_03);
    bne(var_0, 0, label_769);
    b(label_776);
  label_769:
    bne(var_0, 1, label_776);
    bitGet(var_0, MBIT_SH_H_03);
    bne(var_0, 0, label_773);
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_770);
    b(label_777);
    b(label_772);
  label_770:
    bne(var_0, 1, label_772);
    b(label_772);
  label_772:
    b(label_775);
  label_773:
    bne(var_0, 1, label_775);
    b(label_775);
  label_775:
    b(label_776);
  label_776:
    b(label_7c2);
  label_777:
    add(var_a, var_a, 1);
    boutrange(var_a, 0, 1, label_77b);
    b(label_77f);
    b(label_77f);
  label_77b:
    bne(var_a, 2, label_77f);
    sub(var_a, var_a, 2);
    b(label_788);
    b(label_77f);
  label_77f:
    unitFacePlayer(npc1);
    ref_780 = dialogAlloc();
    ref_781 = msgShow(msg_76);
/***************************************
[color(yellow)]Young Guy[color(white)]
[tab](sigh)...
[tab]I want to tell Miss Kaori my feelings...
[tab]But it’s no use...
[wait][clear][color(yellow)]Young Guy[color(white)]
[tab]I bet she keeps this shop open because
[tab]she can’t forget about her husband...
[tab]I have no right to say anything...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_781);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_780);
    unitRestoreFacing(npc1);
    b(label_82c);
  label_788:
    unitFacePlayer(npc1);
    ref_789 = dialogAlloc();
    ref_78a = msgShow(msg_77);
/***************************************
[color(yellow)]Young Guy[color(white)]
[tab]Oh... you’re still here.
[tab]Do you want something from me?
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_78a);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_789);
    choiceSetResult(2);
    op_105(2);
    ref_791 = bustupLoad(bustup_1);
    bustupWait(ref_791);
    ref_793 = bustupAlloc(ref_791, center, rgb(0,0,0));
    bustupFade(ref_793, rgb(128,0,0), 30);
    ref_795 = dialogChoiceAlloc();
    ref_796 = msgShow(msg_78);
/***************************************
[tab]Do you want something from me?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear]
***************************************/
    ref_797 = textInputInit();
    wait(ref_796);
    dialogFree(ref_795);
    ref_79a = bustupFade(ref_793, rgb(0,0,0), 10);
    bustupWait(ref_79a);
    bustupFree(ref_793);
    wait(ref_797);
    choiceGetResult(var_0);
    bne(var_0, 0, label_7a2);
    b(label_7aa);
    b(label_7a9);
  label_7a2:
    bne(var_0, 1, label_7a6);
    unitRestoreFacing(npc1);
    b(label_7c2);
    b(label_7a9);
  label_7a6:
    bne(var_0, 2, label_7a9);
    unitRestoreFacing(npc1);
    b(label_7a9);
  label_7a9:
    b(label_82c);
  label_7aa:
    ref_7aa = textInputPrompt();
    wait(ref_7aa);
    textInputCompare(msg_79, var_0);
    bne(var_0, 0, label_7b6);
    ref_7ae = dialogAlloc();
    ref_7af = msgShow(msg_80);
/***************************************
[color(yellow)]Young Guy[color(white)]
[tab]Huh? Who’s that?
[tab]That’s not me...
[tab]You must be thinking of someone else...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_7af);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_7ae);
    unitRestoreFacing(npc1);
    b(label_7c1);
  label_7b6:
    bne(var_0, 1, label_7c1);
    ref_7b7 = dialogAlloc();
    ref_7b8 = msgShow(msg_81);
/***************************************
[color(yellow)]Young Guy[color(white)]
[tab]Eh?
[tab]How do you know my name?
[tab]Have I introduced myself to you?
[wait][clear][color(yellow)]Takuya Murata[color(white)]
[tab]A search request? For me?
[tab]Must be my younger sister...
[tab]She should mind her own business!
[wait][clear][color(yellow)]Takuya Murata[color(white)]
[tab]Well thanks for letting me know.
[tab]I’ll contact her and Shiraishi.
[tab]Thanks for all your trouble.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_7b8);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_7b7);
    bitSet(MBIT_SH_HH);
    bitSet(MBIT_MURATA_GET);
    unitRestoreFacing(npc1);
    b(label_7c1);
  label_7c1:
    b(label_82c);
  label_7c2:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_813);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_803);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_7f3);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_7da);
    unitFacePlayer(npc1);
    ref_7cb = dialogAlloc();
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_7d0);
    msgShow(msg_82);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_7d3);
  label_7d0:
    bne(var_0, 1, label_7d3);
    msgShow(msg_83);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_7d3);
  label_7d3:
    ref_7d3 = msgShow(msg_84);
/***************************************
[tab]There was a fire at Smile Hirasaka?
[tab]Isn’t that the second time?
[tab]N..No, that can’t be...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_7d3);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_7cb);
    unitRestoreFacing(npc1);
    b(label_82c);
  label_7da:
    unitFacePlayer(npc1);
    ref_7db = dialogAlloc();
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_7e0);
    msgShow(msg_85);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_7e3);
  label_7e0:
    bne(var_0, 1, label_7e3);
    msgShow(msg_86);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_7e3);
  label_7e3:
    ref_7e3 = msgShow(msg_87);
/***************************************
[tab]Looks like there’s more people going
[tab]to the New World Order’s seminars, 
[tab]saying they’ll be killed if they’re impure...
[wait][clear]
***************************************/
    wait(ref_7e3);
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_7e9);
    msgShow(msg_88);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_7ec);
  label_7e9:
    bne(var_0, 1, label_7ec);
    msgShow(msg_89);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_7ec);
  label_7ec:
    ref_7ec = msgShow(msg_90);
/***************************************
[tab]I-I’m not going.
[tab]Because... 
[tab]Miss Kaori said she wasn’t going, so... I...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_7ec);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_7db);
    unitRestoreFacing(npc1);
    b(label_82c);
  label_7f3:
    unitFacePlayer(npc1);
    ref_7f4 = dialogAlloc();
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_7f9);
    msgShow(msg_91);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_7fc);
  label_7f9:
    bne(var_0, 1, label_7fc);
    msgShow(msg_92);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_7fc);
  label_7fc:
    ref_7fc = msgShow(msg_93);
/***************************************
[tab]I-I’m not going anywhere!
[tab]Even if the New World Order comes,
[tab]I’m going to protect Miss Kaori!!
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_7fc);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_7f4);
    unitRestoreFacing(npc1);
    b(label_82c);
  label_803:
    unitFacePlayer(npc1);
    ref_804 = dialogAlloc();
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_809);
    msgShow(msg_94);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_80c);
  label_809:
    bne(var_0, 1, label_80c);
    msgShow(msg_95);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_80c);
  label_80c:
    ref_80c = msgShow(msg_96);
/***************************************
[tab]The Grand Cross... that’s over already...
[tab]I have a feeling that something happened
[tab]during that time...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_80c);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_804);
    unitRestoreFacing(npc1);
    b(label_82c);
  label_813:
    unitFacePlayer(npc1);
    ref_814 = dialogAlloc();
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_819);
    msgShow(msg_97);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_81c);
  label_819:
    bne(var_0, 1, label_81c);
    msgShow(msg_98);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_81c);
  label_81c:
    ref_81c = msgShow(msg_99);
/***************************************
[tab]I’ll always stay here.
[tab]No matter where I am, 
[tab]I’ll die when I die. But Miss Kaori...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_81c);
    bitGet(var_0, MBIT_MURATA_GET);
    bne(var_0, 0, label_823);
    msgShow(msg_100);
/***************************************
[color(yellow)]Young Guy[color(white)]

***************************************/
    b(label_826);
  label_823:
    bne(var_0, 1, label_826);
    msgShow(msg_101);
/***************************************
[color(yellow)]Takuya Murata[color(white)]

***************************************/
    b(label_826);
  label_826:
    ref_826 = msgShow(msg_102);
/***************************************
[tab]Would you laugh at me for self-satisfaction?
[tab]But... that’s fine.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_826);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_814);
    unitRestoreFacing(npc1);
  label_82c:
    controlEnable();
}

function EXITBOX()
{
    controlDisable();
    bitGet(var_0, MBIT_KAOYASUMI01);
    bne(var_0, 0, label_83a);
    bitGet(var_0, MBIT_KAOYASUMI02);
    bne(var_0, 0, label_836);
    bitSet(MBIT_KAOYASUMI01);
    bitSet(MBIT_KAOYASUMI02);
    b(label_839);
  label_836:
    bne(var_0, 1, label_839);
    bitClear(MBIT_KAOYASUMI);
    b(label_839);
  label_839:
    b(label_845);
  label_83a:
    bne(var_0, 1, label_845);
    bitGet(var_0, MBIT_KAOYASUMI02);
    bne(var_0, 0, label_840);
    bitClear(MBIT_KAOYASUMI01);
    bitSet(MBIT_KAOYASUMI02);
    b(label_844);
  label_840:
    bne(var_0, 1, label_844);
    bitSet(MBIT_KAOYASUMI01);
    bitClear(MBIT_KAOYASUMI02);
    b(label_844);
  label_844:
    b(label_845);
  label_845:
    objAnimRotate(obj_16, 0, -70, 0, 30, 0);
    objAnimRotate(obj_15, 0, 70, 0, 30, 0);
    sndMusicPlay(sound_3068, 127);
    objAnimWait(obj_15);
    objAnimWait(obj_16);
    call(GOOUT);
}

function warp1()
{
    call(EXITBOX);
}

function GOOUT()
{
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function HA_SHOP_EXPLAIN_0()
{
    choiceSetResult(2);
    op_105(7);
    ref_853 = dialogChoiceAlloc();
    ref_854 = msgShow(msg_103);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]What would you like to hear?
[choice(3)]Ask about healing
[if_all(MBIT_HI_KAORIAROMA)]Ask about aromatherapy
Nothing
[end_choice][clear]
***************************************/
    wait(ref_854);
    dialogFree(ref_853);
    choiceGetResult(var_0);
    bne(var_0, 0, label_85e);
    ref_859 = dialogAlloc();
    ref_85a = msgShow(msg_104);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Healing it is, then.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]If you select "Heal" here, your HP, SP, and
[tab]status ailments such as poison will be
[tab]healed through breathing in fragrances.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]It does cost you, but since the healing aromas
[tab]affect everyone, it’s cheaper in the long run.
[wait][clear]
***************************************/
    wait(ref_85a);
    dialogFree(ref_859);
    b(label_866);
  label_85e:
    bne(var_0, 1, label_864);
    ref_85f = dialogAlloc();
    ref_860 = msgShow(msg_105);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Aromatherapy?
[tab]If you select "Aromatherapy" here then 
[tab]you’ll be treated with a special "scent".
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]As a result you will attract or repel
[tab]certain people.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]I heard that the incense has an effect 
[tab]on demons too. I wonder if it’s true.
[wait][clear][color(yellow)]Miss Kaori[color(white)]
[tab]One more thing, you cannot apply a new
[tab]scent until the previous one has worn off.
[wait][clear]
***************************************/
    wait(ref_860);
    dialogFree(ref_85f);
    b(label_866);
  label_864:
    bne(var_0, 2, label_866);
    b(label_866);
  label_866:
}

function DECIDE_EAT()
{
    choiceSetResult(1);
    op_105(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_86b = bustupLoad(bustup_f1);
    bustupWait(ref_86b);
    ref_86d = bustupAlloc(ref_86b, left, rgb(0,0,0));
    bustupFade(ref_86d, rgb(128,0,0), 30);
    ref_86f = dialogAlloc();
    choiceSetResult(1);
    op_105(1);
    ref_872 = msgShow(msg_106);
/***************************************
[color(yellow)]Miss Kaori[color(white)]
[tab]Understood. Then it will be a group rate of
[tab]¥[var(msg_var_0)]. Is that all right?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_872);
    choiceGetResult(var_7);
    bne(var_7, 0, label_879);
    sndMusicPlay(sound_3069, 127);
    li(var_7, 1);
    b(label_87c);
  label_879:
    bne(var_7, 1, label_87c);
    li(var_7, 0);
    b(label_87c);
  label_87c:
    wait(ref_872);
    dialogFree(ref_86f);
    ref_87e = bustupFade(ref_86d, rgb(0,0,0), 10);
    bustupWait(ref_87e);
    bustupFree(ref_86d);
    li(var_5, 20);
}
