
msg_0:
More than 4 in your party.
It’s hangtime.
Go to Kaneda, Kataoka
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]I’ve caused you all so much trouble...
[tab]I’m really sorry! Please forgive me!
[tab]...No?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]That kinda irritates me. It’s like they’re
[tab]saying they live in a different world
[tab]from us. Don’t you think so Ma-ya?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Ugh! What the heck?!
[tab]Look at this Ma-ya, "red bean gyoza"!
[tab]I’ve never even heard of that.
[wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]Is she the "man-searcher"?
[tab]I don’t want to judge anyone by their
[tab]appearance, but... Can we trust her?
[wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]You don’t seem to understand the position
[tab]you’re in. Listen, Makimura! If she didn’t
[tab]cooperate with us, you’d already be dead!
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]How should I say this... um... Serizawa-kun!
[tab]You must forget about that scum! 
[tab]Just think of it as being bitten by a stray dog...
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]I come to places like this often because of
[tab]my job, but I don’t think much of them. 
[tab]I guess you feel different in other places.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]What do the regulars come here for?
[tab]Her amusing tales? ...Or the special menu?
[tab]No... that’s nonsense.
[wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]The owner here is more suspicious than
[tab]what I’ve heard. Oh, wait, I shouldn’t be
[tab]saying that should I? I’m the same.
[wait][clear][end]

msg_10:
[color(yellow)]Baofu[color(white)]
[tab]Is that con-man enjoying playing the part
[tab]of the criminal? Normal people don’t say
[tab]stuff like that. He’s watched too much TV!
[wait][clear][end]

msg_11:
[color(yellow)]Baofu[color(white)]
[tab]Look at Serizawa straining herself.
[tab]Maybe she grew up a little now?
[tab]Hey Serizawa! Quit being easy on yourself!
[wait][clear][end]

msg_12:
[color(yellow)]Baofu[color(white)]
[tab]I bet people who were brought up well can’t
[tab]understand what’s good about this place.
[tab]...If you listen, you can hear...
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]Baseball game!? I forgot about it!
[tab]The Hankami Jaguars are playing today!
[tab]Damn, and I’ve never missed one before...
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab]"Banana ramen" and "red bean gyoza"?
[tab]They don’t even have stuff like that
[tab]in Hong Kong!
[wait][clear][end]

msg_15:
[color(yellow)]Nanjo[color(white)]
[tab]Personally, I do not care for shops like this. 
[tab]But it’s a good place to understand others.
[wait][clear][end]

msg_16:
[color(yellow)]Nanjo[color(white)]
[tab]There are foods here I have never eaten.
[tab]Hmm, Japanese cuisine is truly diverse.
[tab]I was getting tired of the same stuff...
[wait][clear][end]

msg_17:
[color(yellow)]Elly[color(white)]
[tab]So this is what an Izakaya is like?
[tab]Wow! I’m surprised.
[tab]Where’s the menu?
[wait][clear][end]

msg_18:
[color(yellow)]Elly[color(white)]
[tab]Oh, my! I never knew such cuisine existed.
[tab]There is so much more I need to learn.
[tab]But isn’t that a bizarre combination?
[wait][clear][end]

msg_19:
[color(yellow)]Makimura[color(white)]
[tab]You!
[tab]You’re the bitch who ratted me out, huh?
[tab]I’ll remember this!
[wait][clear][end]

msg_20:
[color(yellow)]Washout student[color(white)]
[tab]The food here really hits the spot.
[tab]I mean, my body starts to feel hot, 
[tab]and I feel I can take over the world!
[wait][clear][end]

msg_21:
[color(yellow)]Washout student[color(white)]
[tab]Oh, you found the con-man...?
[tab]The Ma’am’s information is amazing.
[tab]She’s really the best "man-searcher"!
[wait][clear][end]

msg_22:
[color(yellow)]Washout student[color(white)]
[tab]Now everyone will start to believe
[tab]her stories!
[wait][clear][end]

msg_23:
[color(yellow)]Washout student[color(white)]
[tab]I heard that there’s been many kidnappings.
[tab]I wonder what’ll happen to the Joker case...
[tab]It’s getting to be a dangerous world.
[wait][clear][end]

msg_24:
[color(yellow)]Washout student[color(white)]
[tab]Youths losing their individuality, huh...
[tab]I’d say the Ma’am’s lifestyle is too
[tab]extravagant. I wonder how much is true?
[wait][clear][end]

msg_25:
[color(yellow)]Washout student[color(white)]
[tab]The Ma’am started to do her
[tab]"man-searcher" business openly!
[tab]It’s not something you can hide forever.
[wait][clear][end]

msg_26:
[color(yellow)]Washout student[color(white)]
[tab]I’m amazed the Ma’am made her
[tab]dream come true.
[tab]I can’t wait for it to come out!
[wait][clear][end]

msg_27:
[color(yellow)]Washout student[color(white)]
[tab]I’m amazed the Ma’am made her
[tab]dream come true.
[tab]...But I’ll pass.
[wait][clear][end]

msg_28:
[color(yellow)]Bodyguard[color(white)]
[tab]Are you saying that Ma’am’s
[tab]a "man-searcher"? Ha ha ha ha ha.
[tab]Then I’m her bodyguard.
[wait][clear][end]

msg_29:
[color(yellow)]Bodyguard[color(white)]
[tab]Right, I’m the bodyguard!
[tab]It’s a secret, okay?
[tab]Ha ha ha ha ha!
[wait][clear][end]

msg_30:
[color(yellow)]Bodyguard[color(white)]
[tab]Didn’t I tell you?
[tab]That lady’s a "man-searcher".
[wait][clear][end]

msg_31:
[color(yellow)]Bodyguard[color(white)]
[tab]And that makes me the bodyguard!
[tab]Got it, nee-chan?
[tab]Ha ha ha ha ha!
[wait][clear][end]

msg_32:
[color(yellow)]Bodyguard[color(white)]
[tab]What’s with the Joker curse?
[tab]I don’t know what the fuss is about.
[tab]But what you don’t know is REALLY scary...
[wait][clear][end]

msg_33:
[color(yellow)]Bodyguard[color(white)]
[tab]So much bad stuff happens in Sumaru City.
[tab]That terrorist attack was pretty bad.
[tab]Huh? You don’t know? Come on!
[wait][clear][end]

msg_34:
[color(yellow)]Bodyguard[color(white)]
[tab]Hey! You forgot about my special
[tab]information?
[tab]...What am I gonna do with you?
[wait][clear][end]

msg_35:
[color(yellow)]Bodyguard[color(white)]
[tab]You looking for someone too?
[tab]Actually, I’m helping her
[tab]look for people too.
[wait][clear][end]

msg_36:
[color(yellow)]Bodyguard[color(white)]
[tab]Security man slash business partner.
[tab]...or something. Anyway, are you looking
[tab]for someone?
[wait][clear][end]

msg_37:
[color(yellow)]Bodyguard[color(white)]
[tab]If you’re having trouble finding someone,
[tab]I can give you some leads, eh?
[tab]How about... 20% of the reward?
[wait][clear][end]

msg_38:
[color(yellow)]Bodyguard[color(white)]
[tab]If you’re having trouble finding someone,
[tab]I can give you some leads, eh?
[tab]How about... 20% of the reward?
[wait][clear][end]

msg_39:
[tab]Wanna buy my info for ¥[var(msg_var_0)]?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_40:
[color(yellow)]Bodyguard[color(white)]
[tab]Alright, I’ll tell ya.
[tab]You’re looking for...
[wait][clear][end]

msg_41:
[color(yellow)]Bodyguard[color(white)]
[tab]Ryoichi Honda?
[tab]He’s into antiques lately. Maybe
[tab]he’s in that kinda shop?
[wait][clear][end]

msg_42:
[color(yellow)]Bodyguard[color(white)]
[tab]Osamitsu Tanaka...
[tab]He wanted to become a journalist.
[tab]Why don’t you try those kinda places?
[wait][clear][end]

msg_43:
[color(yellow)]Bodyguard[color(white)]
[tab]Takuya Murata. There aren’t many sightings.
[tab]But when he comes home once in a while,
[tab]he smells like perfume or something.
[wait][clear][end]

msg_44:
[color(yellow)]Bodyguard[color(white)]
[tab]Taichi Nagase, eh?
[tab]He’s really forgetful and says weird
[tab]things, but he’s pretty old, so...
[wait][clear][end]

msg_45:
[color(yellow)]Bodyguard[color(white)]
[tab]Gonzo Satsuma... what a name.
[tab]He goes around acting like a real gambler.
[tab]Where can you gamble around here...
[wait][clear][end]

msg_46:
[color(yellow)]Bodyguard[color(white)]
[tab]Yuuichi Suzuki... he was telling his friends
[tab]that he’s part of a nobility.
[tab]What’s that all about?
[wait][clear][end]

msg_47:
[color(yellow)]Bodyguard[color(white)]
[tab]Yuuta Ikenaka...
[tab]He’s into fortune telling lately.
[wait][clear][end]

msg_48:
[color(yellow)]Bodyguard[color(white)]
[tab]Oh, the guy with the nickname "Humphrey"?
[tab]He acts all hard-boiled, saying things like,
[tab]"It has nothing to do with me."
[wait][clear][end]

msg_49:
[color(yellow)]Bodyguard[color(white)]
[tab]Shoichi Shimizu and Shizue Tanaka.
[tab]They call each other by nicknames.
[tab]The girl is shy and introverted.
[wait][clear][end]

msg_50:
[color(yellow)]Bodyguard[color(white)]
[tab]Yayoi Kimura likes Wang Long fortunes and
[tab]fine metals. Just like any old lady.
[wait][clear][end]

msg_51:
[color(yellow)]Bodyguard[color(white)]
[tab]Um... Keiko Yokoyama. The homework
[tab]she talks about is to watch something.
[tab]I don’t know what she watches though.
[wait][clear][end]

msg_52:
[color(yellow)]Bodyguard[color(white)]
[tab]Saori Kudou. She doesn’t mind being
[tab]on her feet all day long. She sees
[tab]celebrities quite often I hear.
[wait][clear][end]

msg_53:
[color(yellow)]Bodyguard[color(white)]
[tab]Satomi Iida. She’s really into Wang Long
[tab]lately. It seems she knows a lot about it.
[wait][clear][end]

msg_54:
[color(yellow)]Bodyguard[color(white)]
[tab]Junji Kinoshita... He has a strong sense of
[tab]responsibility, but he’s still a high
[tab]schooler. Why’d he stay at school?
[wait][clear][end]

msg_55:
[color(yellow)]Bodyguard[color(white)]
[tab]Oh, Nekomata!! I don’t even know if this
[tab]one exists. Nobody’s seen her. 
[tab]I wonder if cats are connected...
[wait][clear][end]

msg_56:
[color(yellow)]Bodyguard[color(white)]
[tab]Setsu Nishitani... The client is a mother
[tab]of two, and it’s her mother, 
[tab]so she must be quite old.
[wait][clear][end]

msg_57:
[color(yellow)]Bodyguard[color(white)]
[tab]Kenichi Nakatani likes fads. He hangs out
[tab]in the popular places. He acts like he’s
[tab]in the industry, but no one believes him.
[wait][clear][end]

msg_58:
[color(yellow)]Bodyguard[color(white)]
[tab]Jun Saito... hmm. He was saying that he
[tab]wanted to erase his memory.
[tab]Maybe try a psychology kinda place?
[wait][clear][end]

msg_59:
[color(yellow)]Bodyguard[color(white)]
[tab]Oh, Hiromi Matsushita. She took a friend’s
[tab]advice "to become a man if you’re so scared
[tab]to talk to them" a bit too seriously...
[wait][clear][end]

msg_60:
[color(yellow)]Bodyguard[color(white)]
[tab]Junko Ikeda... The guy she wants is known
[tab]to be a womanizer. She blames his playboy
[tab]ways on the store owner.
[wait][clear][end]

msg_61:
[color(yellow)]Bodyguard[color(white)]
[tab]Oh, Takumi Asano. A kid filed this one,
[tab]right? ...Don’t take it too seriously.
[wait][clear][end]

msg_62:
[color(yellow)]Bodyguard[color(white)]
[tab]The Legendary Blacksmith?
[tab]Why would someone like that be around here?
[tab]...You want the info anyway?
[wait][clear][end]

msg_63:
[color(yellow)]Bodyguard[color(white)]
[tab]There was a rumor a pondering man at
[tab][color(orange)]Alaya Shrine[color(white)] used to be a [color(orange)]blacksmith[color(white)].
[tab]But it’s only a rumor!
[wait][clear][end]

msg_64:
[color(yellow)]Bodyguard[color(white)]
[tab]There was a rumor a pondering man at
[tab]Alaya Shrine used to be a blacksmith.
[tab]But it’s only a rumor!
[wait][clear][end]

msg_65:
[color(yellow)]Bodyguard[color(white)]
[tab]It’s too bad, but it looks like you
[tab]don’t have enough money.
[wait][clear][end]

msg_66:
[color(yellow)]Bodyguard[color(white)]
[tab]Talk to me if you need me.
[tab]See ya nee-chan.
[wait][clear][end]

msg_67:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Hmm?
[tab]What could a young person like you
[tab]want from a homeless man like me?
[wait][clear][end]

msg_68:
[color(yellow)]Rumormonger Toku-san[color(green)]
[tab]A bum who hangs out at Shiraishi. He knows
[tab]many rumors, and he seems to philosophize
[tab]everything. He’s actually quite intelligent.[color(white)]
[wait][clear][end]

msg_69:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]What? ...That lady is a "man-searcher"?
[tab]I know that rumor, but it’s probably a lie.
[tab]I didn’t think anyone’d believe her lies.
[wait][clear][end]

msg_70:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]So you came here believing that rumor...
[tab]Do you like rumors too?
[wait][clear][end]

msg_71:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]I’m just listening to society’s mumblings.
[tab]If you know an interesting rumor, could you
[tab]tell it to me? I’ll give you one in exchange.
[wait][clear][end]

msg_72:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Hmm?
[tab]What could a young person like you
[tab]want from a homeless man like me?
[wait][clear][end]

msg_73:
[color(yellow)]Rumormonger Toku-san[color(green)]
[tab]A bum who hangs out at Shiraishi. He knows
[tab]many rumors, and he seems to philosophize
[tab]everything. He’s actually quite intelligent.[color(white)]
[wait][clear][end]

msg_74:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]I’m just listening to society’s mumblings.
[tab]If you know an interesting rumor, could you
[tab]tell it to me? I’ll give you one in exchange.
[wait][clear][end]

msg_75:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Hey, so it’s you.[delay(10)]
[tab]Hello.[wait][clear][end]

msg_76:
[tab]What can I do for you today?
[choice(3)]Hear a rumor
Talk with Toku-san
Nothing
[end_choice][clear][end]

msg_77:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]That’s all the rumors I know for now.
[tab]If I get a new one, I’ll tell you.
[tab]So you have one ready for me too.
[wait][clear][end]

msg_78:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Rumors, eh... alright.
[tab]But before that...
[tab]Tell me the rumor you know first.
[wait][clear][end]

msg_79:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Not just any old rumor can satisfy a
[tab]rumormonger like me, you know?
[tab]So, tell me your rumor.
[wait][clear][end]

msg_80:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Lately, many people lie saying it’s a rumor.
[tab]It’s hard to tell apart the lies and the
[tab]rumors... Your rumor isn’t a lie, right?
[wait][clear][end]

msg_81:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Hmm, I see.
[tab]Now I’ll tell you mine.
[wait][clear][end]

msg_82:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Hmmm, that’s a pretty interesting rumor.
[tab]Now, shall I tell you mine?
[wait][clear][end]

msg_83:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Oh, that’s some good information.
[tab]I’ll tell you one that’s just as good.
[wait][clear][end]

msg_84:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]A shop named [color(orange)]Toua Defense[color(white)] here in Hirasaka
[tab]is selling a [color(orange)]very special weapon[color(white)]...
[tab]I wonder what’s so special?
[wait][clear][end]

msg_85:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]You know the arcade named [color(orange)]Mu Continent[color(white)]
[tab]in Yumezaki? That place is really a [color(orange)]casino[color(white)]
[tab]and the [color(orange)]poker game is profitable[color(white)].
[wait][clear][end]

msg_86:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]For a magazine called [color(orange)]Miracle[color(white)] you can
[tab]win a [color(orange)]special item[color(white)] in their contest.
[wait][clear][end]

msg_87:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]When you enter into a contest for a magazine
[tab]called [color(orange)]Fantasy World[color(white)], you can
[tab]win some [color(orange)]real armor[color(white)].
[wait][clear][end]

msg_88:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab][color(orange)]Clair De Lune[color(white)], the restaurant of Soejima,
[tab]otherwise known as "The Waiter from Hell", 
[tab]is selling [color(orange)]mysterious armor[color(white)] there.
[wait][clear][end]

msg_89:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]The lady here at [color(orange)]Shiraishi[color(white)] made her
[tab][color(orange)]dream come true[color(white)].
[tab]It’s not something that could be done easily.
[wait][clear][end]

msg_90:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]This is stale, but the [color(orange)]Shiraishi[color(white)] lady
[tab]is a [color(orange)]"man-searcher"[color(white)]. It’s actually true.
[wait][clear][end]

msg_91:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]She’s actually been asked to locate a
[tab]con-artist, and he was actually found.
[wait][clear][end]

msg_92:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Do you know a bar called "Parabellum"? 
[tab]That place is popular with young women, 
[tab]but the names of the original cocktails aren’t.
[wait][clear][end]

msg_93:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]There are lots of irritated people lately.
[tab]I hear the folks, who are scared of becoming
[tab]Jokers, are very frustrated.
[wait][clear][end]

msg_94:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]The lady here used to have a ramen shop.
[tab]But she started to lose customers.
[wait][clear][end]

msg_95:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]And then a truck drove into the shop.
[tab]Talk about being unlucky.
[wait][clear][end]

msg_96:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]So she closed down the ramen shop.
[tab]I bet you didn’t know that did ya?
[wait][clear][end]

msg_97:
[color(yellow)]Rumormonger Toku-san[color(white)]
[tab]Alright.
[tab]Come back if you want another rumor.
[tab]I’ll always be here.
[wait][clear][end]

msg_98:
[color(yellow)]Ma’am[color(white)]
[tab]Looks like you found’em alright.
[tab]The client called up a little while ago.
[tab]Here’s the reward. I’m counting on you.
[wait][clear][end]

msg_99:
[color(green)]Maya received a reward of ¥500.[color(white)]
[sync][wait][clear][end]

msg_100:
[color(green)]Maya received a reward of ¥50000.[color(white)]
[sync][wait][clear][end]

msg_101:
[color(green)]Maya received a reward of ¥40000.[color(white)]
[sync][wait][clear][end]

msg_102:
[color(green)]Maya received a reward of ¥30000.[color(white)]
[sync][wait][clear][end]

msg_103:
[color(green)]Maya received a reward of ¥20000.[color(white)]
[sync][wait][clear][end]

msg_104:
[color(green)]Maya received a reward of ¥10000.[color(white)]
[sync][wait][clear][end]

msg_105:
[color(yellow)]Ma’am[color(white)]
[tab]Man-searcher... what a fateful job.
[tab]I wanted to die an ordinary woman.
[tab]But society wouldn’t let me, y’know.
[wait][clear][end]

msg_106:
[color(yellow)]Ma’am[color(white)]
[tab]There’s no need for secrecy anymore, right?
[tab]Wanna help me find people?
[tab]Of course, there’s a reward.
[wait][clear][end]

msg_107:
[color(yellow)]Ma’am[color(white)]
[tab]All righty. What’ll it be today?
[tab]Oh, I’ve got a new dish on the menu.
[tab]Try out the food I’ve dreamt up.
[wait][clear][end]

msg_108:
[color(yellow)]Ma’am[color(white)]
[tab]Oh, a new customer?
[tab]I’m glad to have you here.
[tab]I’ll give you a special price today.
[wait][clear][end]

msg_109:
[color(yellow)]Ma’am[color(white)]
[tab]You came again today?
[tab]It makes me happy to see you here.
[tab]I’ll give you a special price today.
[wait][clear][end]

msg_110:
[color(yellow)]Ma’am[color(white)]
[tab]Man-searcher... what a fateful job.
[tab]I wanted to die an ordinary woman.
[tab]But society wouldn’t let me, y’know.
[wait][clear][end]

msg_111:
[color(yellow)]Ma’am[color(white)]
[tab]There’s no need for secrecy anymore, huh.
[tab]Wanna help me find people?
[tab]Of course, there’s a reward.
[wait][clear][end]

msg_112:
[color(yellow)]Ma’am[color(white)]
[tab]I get into such a good mood when you come.
[tab]I’ll give you a special price today.
[wait][clear][end]

msg_113:
[color(yellow)]Ma’am[color(white)]
[tab]You came again today?
[tab]It makes me happy to see you here.
[tab]...By the way, I’ve created a new dish.
[wait][clear][end]

msg_114:
[color(yellow)]Ma’am[color(white)]
[tab]Today, I’ll cut prices...
[tab]Try out my new dream dish.
[wait][clear][end]

msg_115:
[color(yellow)]Ma’am[color(white)]
[tab]All righty.
[tab]What’ll it be today, hun?
[choice(4)]Dine in
Talk to Ma’am
Never mind
Leave
[end_choice][clear][end]

msg_116:
[color(yellow)]Ma’am[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about the store
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_117:
[color(yellow)]Ma’am[color(white)]
[tab]All righty.
[tab]What’ll it be today, hun?
[choice(5)]Search
Dine in
Talk to Ma’am
Never mind
Leave
[end_choice][clear][end]

msg_118:
[color(yellow)]Ma’am[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about the store
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_119:
[color(yellow)]Ma’am[color(white)]
[tab]All righty.[delay(10)]
[tab]Come again, okay?
[wait][clear][end]

msg_120:
[color(yellow)]Ma’am[color(white)]
[tab]Anything else?
[choice(4)]Dine in
Talk to Ma’am
Never mind
Leave
[end_choice][clear][end]

msg_121:
[color(yellow)]Ma’am[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about the store
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_122:
[color(yellow)]Ma’am[color(white)]
[tab]Anything else?
[choice(5)]Search
Dine in
Talk to Ma’am
Never mind
Leave
[end_choice][clear][end]

msg_123:
[color(yellow)]Ma’am[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about the store
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_124:
[color(yellow)]Ma’am[color(white)]
[tab]Huh? Man-searcher?
[tab]Yeah, that’s something from my past.
[tab]But now I just run this pub.
[wait][clear][end]

msg_125:
[color(yellow)]Ma’am[color(white)]
[tab]So you want to know where a con-artist
[tab]might be... Oh, a bar called "Parabellum"
[tab]in Aoba is popular with girls lately.
[wait][clear][end]

msg_126:
[color(yellow)]Ma’am[color(white)]
[tab]Maybe he’ll be at places like that to fish
[tab]for girls to swindle?
[wait][clear][end]

msg_127:
[color(yellow)]Ma’am[color(white)]
[tab]The con-artist was really there?
[tab]I guess you can rely on me now.
[tab]I’m so good I scare myself sometimes.
[wait][clear][end]

msg_128:
[color(yellow)]Ma’am[color(white)]
[tab]My last job as a professional man-searcher
[tab]was finding the President’s old flame.
[tab]He was such a "clingy" guy.
[wait][clear][end]

msg_129:
[color(yellow)]Ma’am[color(white)]
[tab]Too many people are asking me to
[tab]find people for them lately.
[tab]They say the police won’t deal with them.
[wait][clear][end]

msg_130:
[color(yellow)]Ma’am[color(white)]
[tab]Young ones nowadays have no individuality.
[tab]Hollywood back then was different.
[tab]Everyone was full of personality.
[wait][clear][end]

msg_131:
[color(yellow)]Ma’am[color(white)]
[tab]Dreams have meaning when you chase them.
[tab]Didn’t I realize my dream, you ask?
[tab]Not yet, I’m still in the middle of it.
[wait][clear][end]

msg_132:
[color(yellow)]Ma’am[color(white)]
[tab]What? You’re saying I’ve realized my dream?
[tab]Don’t say it so loud.
[tab]It’s embarrassing.
[wait][clear][end]

msg_133:
[color(yellow)]Ma’am[color(white)]
[tab]...To write an autobiography.
[tab]That was my dream.
[wait][clear][end]

msg_134:
[color(yellow)]Ma’am[color(white)]
[tab]One of my customers works for a publisher
[tab]and they wanted to put my book out.
[tab]Oh I was so lucky.
[wait][clear][end]

msg_135:
[color(yellow)]Ma’am[color(white)]
[tab]You can’t just chase your dream.
[tab]You have to make it come true.
[tab]...Wanna read it? I’ll read some for you.
[wait][clear][end]

msg_136:
[color(green)]My Love, The Man with the Golden License
[tab]  The President’s Moon-Ball, Not Enough
[tab]       From Shiraishi, With Love
[wait][clear][end]

msg_137:
I had been a warrior since I can remember...
The one who saved me as a child at the last
moment of the Nomanov dynasty was a soldier
from the West. That was him...
[wait][clear][end]

msg_138:
Did he save me because it was his duty? Or...
No one knows for sure now. The last memory
I have is fighting together for Socialism.
I threw my past away and drifted to Paris...
[wait][clear][end]

msg_139:
[color(yellow)]Ma’am[color(white)]
[tab]Whew, that’s all for today.
[tab]I’ll read you the rest next time.
[wait][clear][end]

msg_140:
[color(yellow)]Ma’am[color(white)]
[tab]You wanna know what happens next?
[tab]Okay, okay, I’ll read it to you.
[wait][clear][end]

msg_141:
[color(green)]My Love, The Man with the Golden License
[tab]  The President’s Moon-Ball, Not Enough
[tab]       From Shiraishi, With Love
[wait][clear][end]

msg_142:
I put my life as a supermodel behind me to
be the last idol of the 20th century. It
was nobody’s fault... I just couldn’t
reciprocate the President’s feelings.
[wait][clear][end]

msg_143:
My only place was that glamorous stage.
An idol... That’s all I wanted to be...
I knew there was nowhere for me to live in
peace, but I couldn’t stay in this world...
[wait][clear][end]

msg_144:
[color(yellow)]Ma’am[color(white)]
[tab]That’s all for now. To find out the rest,
[tab]buy the book! Published by Kismet,
[tab]it’ll be ¥1600 when it comes out.
[wait][clear][end]

msg_145:
[color(yellow)]Ma’am[color(white)]
[tab]The rest of my book? Nope.
[tab]You have to buy the book. But a release
[tab]date hasn’t been determined.
[wait][clear][end]

msg_146:
MBIT KE SIRAMAN
Man-searcher’s rumor
Bit On!!
[wait][clear][end]

msg_147:
MBIT KE SIRAHENNI
Mutation rumor decided
Bit On!!
[wait][clear][end]

msg_148:
MBIT AIS 29
Affinity Reading’s
Bit On!!
[wait][clear][end]

msg_149:
EBIT E0037
End reception desk at police station
Bit On!!
[wait][clear][end]

msg_150:
EBIT E0038
Con artist arrested
Bit On!!
[wait][clear][end]

msg_151:
EBIT E003E
Cleared GOLD, admit Ulala
Bit On!!
[wait][clear][end]

msg_152:
EBIT E0043
Cleared Club
Bit On!!
[wait][clear][end]

msg_153:
EBIT E0046
Admit Nanjo or Elly
Bit On!!
[wait][clear][end]

msg_154:
EBIT E006F
Cleared Research facility/TV station
Bit On!!
[wait][clear][end]

msg_155:
[color(yellow)]Ma’am[color(white)]
[tab]What do you want to talk about?
[choice(3)][if_all(MBIT_KE_SIRAMAN)]Ask about searching
Ask about dining in
Never mind
[end_choice][clear][end]

msg_156:
[color(yellow)]Ma’am[color(white)]
[tab]You can take a job searching for someone.
[tab]You can earn a reward by finding a person
[tab]on the "Wanted" list.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]When you accept a request, the "Wanted"
[tab]person’s name and key features will be
[tab]displayed. Search using these as clues.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]You search by talking to the people of
[tab]the city. If someone seems to fit the
[tab]description, try talking to them again.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]If it is the "Wanted" person, they will ask
[tab]what you want from them. If you enter the
[tab]name correctly, the search is completed.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]You can only take one search request
[tab]at a time.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]Once you’ve found them, come back here
[tab]for your reward.
[wait][clear][end]

msg_157:
[color(yellow)]Ma’am[color(white)]
[tab]Dining in?
[tab]You can select "Dine in" here.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]Eating can temporarily raise your
[tab]character’s abilities.
[wait][clear][color(yellow)]Ma’am[color(white)]
[tab]The effects vary from menu to menu,
[tab]and until the effects of the last
[tab]meal wear off, you cannot eat again.
[wait][clear][end]

msg_158:
[color(yellow)]Ma’am[color(white)]
[tab]That’ll be ¥[var(msg_var_0)]
[tab]Will you dine in?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_159:
[color(yellow)]Ma’am[color(white)]
[tab]That will cost ¥[var(msg_var_0)]
[tab]Is that okay?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_160:
[color(yellow)]Ma’am[color(white)]
[tab]You have to solve the request 
[tab]before accepting a new one.
[wait][clear][end]

msg_161:
[color(yellow)]Ma’am[color(white)]
[tab]You can’t take a request if you
[tab]can’t pay the fee.
[wait][clear][end]

msg_162:
[color(yellow)]Ma’am[color(white)]
[tab]This case has already been solved.
[tab]Did you forget?
[wait][clear][end]

msg_163:
[color(green)]Minors may not drink!
[wait][clear][end]
