
msg_0:
Hang time!
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Hey, Ma-ya.
[tab]The one who helped us at the Clock
[tab]Tower was the "D五j二 Vu Boy", right?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Are you sure you don’t remember?
[tab]Why would someone who you just
[tab]ran into at the station do that?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Dammit, I never forget a guy’s face...
[tab]Especially that Makimura’s!!
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Say Ma-ya, wasn’t this place featured in
[tab]your magazine?
[tab]Like, this is a three-star sushi place.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]H... Hey... Ma-ya.
[tab]What if I did the Joker curse...?
[end]

msg_6:
[tab]N-No, it’s nothing. Never mind.
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]I turned back to normal thanks to you guys...
[tab]but what’ll happen to everyone else who did 
[tab]the Joker curse?
[wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab]Do you think it’s true that Bao killed 25 people? 
[tab]He doesn’t seem THAT bad...
[tab]Ah, it’s that. A woman’s intuition.
[wait][clear][end]

msg_9:
[color(yellow)]Ulala[color(white)]
[tab]We’ll fight back with rumors, too.
[tab]We can say like, Wang Long Chizuru is a
[tab]liar or there is no such thing as Kegare...
[wait][clear][end]

msg_10:
[color(yellow)]Ulala[color(white)]
[tab]...or not...
[tab]Rumors like that aren’t going to go far...
[tab]And besides, we don’t have enough time.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]The boy you say you saw at the Clock Tower...
[tab]You say the "D五j二 Vu Boy", but who is he?
[tab]Does he know something about this case?
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Either way, I’m surprised that you would go
[tab]for sushi at this time of day. 
[tab]Do you reporters have that good of a salary?
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]The resonance of Personas...
[tab]I never noticed it until Baofu said it...
[tab]If only I could use this power for interrogating...
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]What is [tatsuya] hiding?
[tab]Only he understood what Tatsuya Sudou
[tab]was talking about. Why is that...
[wait][clear][end]

msg_15:
[color(yellow)]Katsuya[color(white)]
[tab]Hmm?
[tab]The atmosphere seems odd...
[tab]Did something happen here?
[wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]Their son hasn’t come home yet.
[tab]Considering there have been more and more
[tab]Joker incidents... I hope nothing happened.
[wait][clear][end]

msg_17:
[color(yellow)]Katsuya[color(white)]
[tab]They say that if you do not attend the
[tab]seminars, you will eventually be
[tab]possessed by the Joker...
[wait][clear][end]

msg_18:
[color(yellow)]Katsuya[color(white)]
[tab]They’re way ahead of us.
[tab]This makes it quite bad for us.
[tab]Tatsuzou... what are you planning to do next?
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Hmm... That stout guy is a Persona user, huh.
[tab]It doesn’t seem fit for battles though...
[end]

msg_20:
[tab]You can get a lot from reading resonance.
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]What is this "Other Side" that Sudou’s
[tab]son was talking about...?
[tab]And what does that broadsword kid know...?
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]According to the guy there, one of the
[tab]customers all of a sudden went crazy.
[tab]Probably the same thing as Serizawa...
[wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]Their kid still hasn’t come home.
[tab]If he did the Joker curse, he may have
[tab]been abducted like the rest...
[wait][clear][end]

msg_24:
[color(yellow)]Baofu[color(white)]
[tab]That Matsuoka guy’s something. I’m surprised
[tab]that there’s a guy like that in this day and age. 
[tab]Perfect for that thickheaded rich boy.
[wait][clear][end]

msg_25:
[color(yellow)]Nanjo[color(white)]
[tab]That’s... Toro.
[tab]A friend of mine from my St. Hermelin days.
[tab]It’s been a while since I’ve seen him.
[wait][clear][color(yellow)]Nanjo[color(white)]
[tab]The Persona is another self.
[tab]It is an existence that could be called
[tab]one’s worst enemy.
[wait][clear][color(yellow)]Nanjo[color(white)]
[tab]Those who cannot overcome themselves can
[tab]be destroyed by the power of Persona.
[tab]This... is what I learned from him.
[wait][clear][end]

msg_26:
[color(yellow)]Nanjo[color(white)]
[tab]It seems that Kido was able to escape
[tab]safely. Still, even he is in this city...
[tab]Is this all mere coincidence?
[wait][clear][end]

msg_27:
[color(yellow)]Elly[color(white)]
[tab]Wow! That’s Toro!
[end]

msg_28:
[tab]He’s my classmate from high school.
[tab]I’m surprised to meet him here.
[wait][clear][end]

msg_29:
[color(yellow)]Elly[color(white)]
[tab]He still has his Persona power, 
[tab]but it seems a lot more stable now.
[end]

msg_30:
[tab]I’m glad. I can’t take any more outbursts.
[wait][clear][end]

msg_31:
[color(yellow)]Elly[color(white)]
[tab]That’s Reiji over there!
[tab]He’s also an old friend.
[tab]I’m surprised to see him here.
[wait][clear][end]

msg_32:
[color(yellow)]Elly[color(white)]
[tab]Wang Long is known to work,
[tab]and the Joker incidents are frightening.
[tab]It’s no wonder people go to the seminars.
[wait][clear][end]

msg_33:
[color(yellow)]Makimura[color(white)]
[tab]I-I think something happened here.
[tab]You’re a reporter, right? You should
[tab]c-check it out, it might be a big story!
[wait][clear][end]

msg_34:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Well, I’m a really good salesman, 
[tab]but I’ve become "friendly" with rumors.
[tab]Now they call me a "Rumormonger."
[wait][clear][end]

msg_35:
[color(yellow)]Kenta Yokouchi[color(white)]
[tab][color(green)]A graduate of St. Hermelin. A successful
[tab]salesman who knows much about rumors. 
[tab]His Persona seems to have helped his career.[color(white)]
[wait][clear][end]

msg_36:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Rumors come in handy for sales. 
[tab]So if you hear a good rumor, come tell me.
[tab]I’ll tell you one of mine in return.
[wait][clear][end]

msg_37:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Aaahh... mmmm...
[tab]I’m telling ya, fish fin is the best!!
[tab]...So, what’s up?
[wait][clear][end]

msg_38:
[tab]What do you want?
[end]

msg_39:
[tab]Is there anything else?
[end]

msg_40:
[choice(3)]Hear rumors
Talk with Toro
Nothing really
[end_choice][clear][end]

msg_41:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Hmm...
[tab]I don’t really have any info right now.
[tab]I’ll get some for next time.
[wait][clear][end]

msg_42:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Sorry.
[tab]I haven’t gotten anything new yet.
[tab]Could you come back later?
[wait][clear][end]

msg_43:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]A rumor?
[tab]I’ve got a perfect one.
[tab]Tell me your story first.
[wait][clear][end]

msg_44:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Mmmmm... sure...
[tab]Would you tell me your story first?
[tab]You have to give me a fresh one though.
[wait][clear][end]

msg_45:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]...Hmm. That’s pretty good.
[tab]In fact, you’re good.
[tab]So now, here’s my information...
[wait][clear][end]

msg_46:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Wow, I didn’t know about that one.
[tab]I think I just hit the motherload.
[tab]I’ll tell you mine now.
[wait][clear][end]

msg_47:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]At a shop called the [color(orange)]Time Castle[color(white)], 
[tab]they [color(orange)]sell Skill Cards[color(white)].
[tab]But do magic skills really exist?
[wait][clear][end]

msg_48:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]I’ve got another about the [color(orange)]Time Castle[color(white)].
[tab]The owner [color(orange)]duplicates Skill Cards[color(white)] too.
[wait][clear][end]

msg_49:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]You know the magazine [color(orange)]Battle Master[color(white)]?
[tab]When you enter their sweepstakes,
[tab]you could win a [color(orange)]real weapon[color(white)].
[wait][clear][end]

msg_50:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]You know the magazine [color(orange)]Fantasy World[color(white)]?
[tab]When you enter in their sweepstakes, you
[tab]could win a [color(orange)]real weapon[color(white)].
[wait][clear][end]

msg_51:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Not only am I a rumormonger, I am the
[tab]Baron of Sushi, a member of the
[tab]Sushi nobility. Do you want to join?
[wait][clear][end]

msg_52:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]You’re a Persona user, right?
[tab]Actually, I’m one too. I’m not as strong
[tab]as my colleague Reiji-kun though.
[wait][clear][end]

msg_53:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]The Joker rumor is all around town.
[tab]Don’t you think the people who did
[tab]the Joker curse are really worried now?
[wait][clear][end]

msg_54:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]The executive who was sitting there all
[tab]of a sudden started to attack me.
[tab]I was so surprised.
[wait][clear][color(yellow)]Rumormonger Toro[color(white)]
[tab]He made me drop my precious fish fin, 
[tab]so I got really mad and punched him hard.
[tab]You should never waste food.
[wait][clear][end]

msg_55:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Actually, right before that executive
[tab]left, there was a Persona resonance...
[tab]Was he a Persona user too?
[wait][clear][end]

msg_56:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Huh? Seminar?
[tab]I’m not going to that.
[tab]I’m too busy eating my fish fin.
[wait][clear][end]

msg_57:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Okay.
[tab]Well, return if you want to hear a rumor.
[tab]I’ll be sitting here eating fish fin.
[wait][clear][end]

msg_58:
[color(yellow)]Count Sushi[color(white)]
[tab]That guy there all of a sudden became
[tab]extravagant. He used to always complain
[tab]that the company president was in his way.
[wait][clear][end]

msg_59:
[color(yellow)]Count Sushi[color(white)]
[tab]Say, the boss here has a son.
[tab]A junior at Kasugayama High. 
[tab]He’s lucky that he has a successor.
[wait][clear][end]

msg_60:
[color(yellow)]Count Sushi[color(white)]
[tab]The guy next to me is all happy because
[tab]the company president was killed by the Joker. 
[tab]I never want to end up like him!
[wait][clear][end]

msg_61:
[color(yellow)]Count Sushi[color(white)]
[tab]There’s something wrong with
[tab]the guy next to me.
[tab]What’s happened to him?
[wait][clear][end]

msg_62:
[color(yellow)]Count Sushi[color(white)]
[tab]That guy snapped all of a sudden
[tab]and attacked Baron Toro.
[tab]But he got knocked out instead. How lame.
[wait][clear][color(yellow)]Count Sushi[color(white)]
[tab]...Huh?
[tab]Where’d that guy go?
[wait][clear][end]

msg_63:
[color(yellow)]Count Sushi[color(white)]
[tab]The boss’ son hasn’t come home since he
[tab]left for school. I think the boss is
[tab]actually a little worried.
[wait][clear][end]

msg_64:
[color(yellow)]Count Sushi[color(white)]
[tab]The boss’ son just came home, 
[tab]but he had blue hair and was wearing a skirt! 
[tab]Boss’ eyes bugged out, and he started yelling!
[wait][clear][color(yellow)]Count Sushi[color(white)]
[tab]...But something was wrong with the kid.
[tab]Seemed depressed and wandered out
[tab]saying he’s "going to the shrine".
[wait][clear][end]

msg_65:
[color(yellow)]Company President[color(white)]
[tab]Gah hah hah! I’ve finally become president.
[tab]I feel so important now, letting the
[tab]underlings do all the work while I eat!
[wait][clear][end]

msg_66:
[color(yellow)]Company President[color(white)]
[tab]A little while ago, the annoying president
[tab]was killed. So I was made president!
[tab]There is a God! Gah hah hah!
[wait][clear][end]

msg_67:
[color(yellow)]Company President[color(white)]
[tab]I-I killed the president with the Joker curse...
[tab]I can’t believe that rumors come true...
[tab]I’m gonna become a Joker too... Uggh.
[wait][clear][end]

msg_68:
[color(yellow)]Sushi Royalty[color(white)]
[tab]Sushi is the staple of the Sushi nobility!
[tab]I must keep on eating fish fin, 
[tab]or I could not call myself a nobleman!
[wait][clear][color(yellow)]Sushi Royalty[color(white)]
[tab]I’m so full now, I won’t be able to
[tab]eat when I get home. But that’s okay!
[tab]This is how the nobility lives!
[wait][clear][end]

msg_69:
[color(yellow)]Sushi Royalty[color(white)]
[tab]Hmm?
[tab]Do you still want something from me?
[tab]Do you want to join?
[wait][clear][end]

msg_70:
[tab]What is it?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_71:
YUUICHI SUZUKI
[end]

msg_72:
[color(yellow)]Sushi Royalty[color(white)]
[tab]Huh?
[tab]Who’s that?
[tab]I don’t know anyone like that.
[wait][clear][end]

msg_73:
[color(yellow)]Sushi Royalty[color(white)]
[tab]What?
[tab]How do you know my name?
[tab]Who are you...?
[wait][clear][color(yellow)]Yuuichi Suzuki[color(white)]
[tab]Eh? A search request for me!?
[tab]It must be Mama’s doing.
[tab]Mama worries so much...
[wait][clear][color(yellow)]Yuuichi Suzuki[color(white)]
[tab]Thanks for letting me know!
[tab]I will tell Shiraishi and Mama.
[tab]Thank you very much!
[wait][clear][end]

msg_74:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_75:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_76:
[tab]I am a member of the Sushi nobility. The
[tab]"Sushi Nobility", a club for sushi lovers,
[tab]uses this place to exchange information.
[wait][clear][end]

msg_77:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_78:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_79:
[tab]To be honest, I love sushi and rumors.
[tab]Even now, I was asking the Baron of Sushi,
[tab]Toro, for a rumor.
[wait][clear][end]

msg_80:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_81:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_82:
[tab]The boss has a son in High School.
[tab]His name is... "Eikichi", I think...
[tab]He’s a gang leader at Kasugayama High.
[wait][clear][end]

msg_83:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_84:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_85:
[tab]I believe rumors, but I’m wary of other things. 
[tab]That’s why I won’t believe
[tab]that ridiculous broadcast!
[wait][clear][end]

msg_86:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_87:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_88:
[tab]Baron Toro is really strong!
[tab]He knocked out that crazy executive
[tab]in one shot!!
[wait][clear][end]

msg_89:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_90:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_91:
[tab]The boss shook like a leaf in the back.
[tab]He says he has a total of 18 grades of
[tab]black belt in a bunch of martial arts.
[wait][clear][end]

msg_92:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_93:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_94:
[tab]I know the truth though.
[tab]Eikichi is quite a narcissist.
[tab]He must make his parents weep...
[wait][clear][end]

msg_95:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_96:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_97:
[tab]He’s probably having trouble
[tab]dressing up.
[wait][clear][end]

msg_98:
[color(yellow)]Sushi Royalty[color(white)]
[end]

msg_99:
[color(yellow)]Yuuichi Suzuki[color(white)]
[end]

msg_100:
[tab]It’s another world in here. Outside they’re
[tab]all going crazy because of that broadcast...
[tab]Maybe I should go to the seminar...
[wait][clear][end]

msg_101:
[color(yellow)]Reiji[color(white)]
[tab]Like I said... um... could you teach 
[tab]me how I could do better in sales?
[tab]I’m not doing well lately.
[wait][clear][end]

msg_102:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Like I said, you’re strong but you
[tab]have too many rough edges.
[wait][clear][end]

msg_103:
[color(yellow)]Reiji[color(white)]
[tab]You mean I have to be like you?
[wait][clear][end]

msg_104:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]You see, what’s important is love.
[tab]You have to love the customer.
[tab]If you do that, your Persona will help you.
[wait][clear][end]

msg_105:
[color(yellow)]Reiji[color(white)]
[tab]What do you mean, love?
[tab]You mean, be affectionate with them?
[wait][clear][end]

msg_106:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]You make it sound very weird,
[tab]you know.
[wait][clear][end]

msg_107:
[color(yellow)]Reiji[color(white)]
[tab]...Sushi at this time of day...
[tab]Well, you ARE #1 in the industry.
[wait][clear][end]

msg_108:
[color(yellow)]Rumormonger Toro[color(white)]
[tab]Why don’t you eat too?
[wait][clear][end]

msg_109:
[color(yellow)]Reiji[color(white)]
[tab]"Uh, hello, good afternoon. Um...
[tab]"I’m selling these fine kitchen knives..."
[tab]. . . . . .
[wait][clear][end]

msg_110:
[color(yellow)]Reiji[color(white)]
[tab]Ah, forget it...
[tab]There is no way in hell I could
[tab]talk that sweetly...
[wait][clear][end]

msg_111:
[color(yellow)]Reiji Kido[color(white)]
[tab][color(green)]A Persona user who fought alongside Nanjo and Elly.
[tab]A.K.A. "The Legendary Six-Pack Leader"
[tab]He is the half-brother of Kandori.[color(white)]
[wait][clear][end]

msg_112:
[color(yellow)]Reiji[color(white)]
[tab]Huh?
[tab]My Persona is resonating...
[tab]...So, you must be it.
[wait][clear][end]

msg_113:
[color(yellow)]Reiji[color(white)]
[tab]I’ve heard from Nanjo that you’ve been
[tab]helping my old pals.
[wait][clear][end]

msg_114:
[color(yellow)]Reiji[color(white)]
[tab]Just come to me if you have a problem.
[tab]I could help to some extent... 
[tab]By the way, can I interest you in some knives?
[wait][clear][end]

msg_115:
[color(yellow)]Kankichi[color(white)]
[tab]Welcome, welcome!
[tab]First time customers?
[tab]Thanks for coming!!
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]Gatten Sushi is known for the
[tab]fresh fish and the incredibly low prices!!
[tab]Come eat as much as you want!
[wait][clear][end]

msg_116:
[color(yellow)]Kankichi[color(white)]
[tab]...Hmm... for some odd reason,
[tab]You don’t feel like a stranger to me.
[tab]Alright! I’ll lower the price for you then!
[wait][clear][end]

msg_117:
[color(yellow)]Kankichi[color(white)]
[tab]Welcome, welcome!
[tab]You’ve got to greet your
[tab]customers with spirit, you know.
[wait][clear][end]

msg_118:
[color(yellow)]Kankichi[color(white)]
[tab]Hmm, I’m getting a strange feeling.
[tab]You seem familiar, nee-san.
[tab]Alright! Let me give you a good price!
[wait][clear][end]

msg_119:
[color(yellow)]Kankichi[color(white)]
[tab]Ah, welcome, welcome! Thanks for coming!
[choice(4)]Dine in
Talk to Kankichi
Never mind
Leave the store
[end_choice][clear][end]

msg_120:
[color(yellow)]Kankichi[color(white)]
[tab]Gotcha! What’s on your mind?
[choice(3)]Make small talk
Ask about dining in
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_121:
[color(yellow)]Kankichi[color(white)]
[tab]You want something else?
[tab]Feel free to ask me!!
[tab]I welcome spirited customers!!
[choice(4)]Dine in
Talk to Kankichi
Never mind
Leave the store
[end_choice][clear][end]

msg_122:
[color(yellow)]Kankichi[color(white)]
[tab]Gotcha! What’s on your mind?
[choice(3)]Make small talk
Ask about dining in
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_123:
[color(yellow)]Kankichi[color(white)]
[tab]I moved here just recently, but I used
[tab]to have this shop in Hirasaka.
[tab]Why’d I move, you ask?
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]It’s the fortune telling!
[tab]I was told that I’ll do good business if
[tab]I opened my shop here! I had to move here!
[wait][clear][end]

msg_124:
[color(yellow)]Kankichi[color(white)]
[tab]Hey nee-chan, have you heard this one?
[tab]You can’t spell adamant without man!
[tab]Heart, brains, and prawn! Yeah!
[wait][clear][end]

msg_125:
[color(yellow)]Kankichi[color(white)]
[tab]Do all youngsters these days want to
[tab]become singers? My stupid son was saying
[tab]he wants to be one.
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]He’s always wandering off every day doing
[tab]who knows what. I’m worried that he might
[tab]not take over the shop for me.
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]Huh? My son’s wishes?
[tab]Don’t be silly, nee-chan! There’s a rule
[tab]that sons have to succeed their fathers!
[wait][clear][end]

msg_126:
[color(yellow)]Kankichi[color(white)]
[tab]Some people dressed in black came a little
[tab]while ago and took away that executive who
[tab]was unconscious. What’s going on!?
[wait][clear][end]

msg_127:
[color(yellow)]Kankichi[color(white)]
[tab]Hm?
[tab]Say, where’s Eikichi?
[tab]He hasn’t come home from school!!
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]I bet he’s off somewhere ’cause he doesn’t
[tab]want to do delivery!! When he gets home he’s
[tab]getting my Hell Chopper!! Chop! Chop!!
[wait][clear][end]

msg_128:
[color(yellow)]Kankichi[color(white)]
[tab]What the hell was Eikichi wearing!?
[tab]I don’t believe I’ve brought up my son
[tab]to walk around looking like that!!
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]He said it was for a costume party
[tab]or something, but who knows!
[tab]I’m gonna get him when he comes home!!
[wait][clear][end]

msg_129:
[color(yellow)]Kankichi[color(white)]
[tab]Gotcha! 
[tab]Come back while our fish is fresh!
[tab]You’re always welcome! Come again!
[wait][clear][end]

msg_130:
[color(yellow)]Kankichi[color(white)]
[tab]So you want to know about eating here?
[tab]Select "Dine in" when you want a good meal!
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]Our food has different status-boosting effects
[tab]that are different with each dish, so try them
[tab]for yourself to see what happens!
[wait][clear][color(yellow)]Kankichi[color(white)]
[tab]Once you’ve had a plate, you won’t be able to
[tab]eat again until the effect wears off. And that
[tab]about wraps it up!
[wait][clear][end]

msg_131:
[color(yellow)]Kankichi[color(white)]
[tab]That comes to ¥[var(msg_var_0)]!
[tab]Is that okay?
[choice(2)]Yes
No
[end_choice][clear][end]
