
msg_0:
There are more than 4 people in the party.
[tab]This will cause the game to hang.
[tab]Please contact Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]At first glance this place looks dirty, but
[tab]if you look carefully, it’s kind of clean.
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]I’d like to make my room like this too,
[tab]what do you think?
[tab][delay(30)]Huh,[delay(15)] Ma[delay(15)]-ya?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]It’s nice having high school friends. They
[tab]say THAT friendship lasts the looooongest!
[tab]Ma-ya and I have known each other a while!
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun is still in high school right? 
[tab]But look at those sad eyes. Even an adult
[tab]can’t make an expression like that!
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Eikichi-kun wasn’t uninvolved.
[tab]...But, we have to leave it alone for now.
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Ahh, Miyabi-chan is such a fine little girl.
[tab]Eikichi-kun is so lucky.
[end]

msg_7:
[tab]...If I was a man, I would take her!
[wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab](sigh) When I’m with you, I always get in
[tab]some kind of mess, but... this one was
[tab]by far, the WORST EVER!!
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]Cleaning is basic to the sales business.
[tab]It’s not like you use your own rooms to do
[tab]business, so as long as it’s fairly neat.
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Trust, friendship...
[tab][tatsuya] must have friends as well...
[tab]Why does he choose to be all by himself...?
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]I haven’t told our parents about [tatsuya].
[tab]It’s impossible! How could I describe a
[tab]situation like this?
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Explaining the truth to them, wouldn’t
[tab]help them understand... Even we have
[tab]a hard time understanding.
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]I didn’t think they would be much help...
[tab]"Adversity makes a man, a man."... eh.
[tab]What my superior once told me was true.
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]!
[tab]Do you really have the time to be
[tab]regretting!? ...Let’s go!
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]Hehhehheh.
[tab]Amano, that must be pain to your ears, eh?
[tab]Your guys’ room... is way too dirty.
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]Don’t get too involved with others. That
[tab]makes the pain of losing them even worse.
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]...Amano...
[tab]Do you have any intention of listening to
[tab][tatsuya]’s story? We have no business here!
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]They must have...
[tab]a counterpart on the "Other Side" as well.
[tab]Probably not much different though.
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Sure it may be reliable for a man working
[tab]outside... She could be a "convenient"
[tab]woman for men... How will you turn out?
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]Let’s go, Amano!
[tab]We can’t keep [tatsuya] sad any longer, right?
[wait][clear][end]

msg_21:
[color(yellow)]Nanjo[color(white)]
[tab]Even if it is pretty, if it looks dirty,
[tab]wouldn’t it be a problem...?
[tab]Well, it’s better than really being dirty.
[wait][clear][end]

msg_22:
[color(yellow)]Nanjo[color(white)]
[tab]...My dream? I don’t have any dreams.
[tab]To become number one in this country
[tab]is a reality that I must accomplish.
[wait][clear][end]

msg_23:
[color(yellow)]Nanjo[color(white)]
[tab]...[suou] is feeling extreme longing for
[tab]this place. What happened here before?
[wait][clear][end]

msg_24:
[color(yellow)]Elly[color(white)]
[tab]By the way Ms. Amano...
[tab]You’ve been making a mess out of the
[tab]editor’s desks? (giggle)... I heard from Yukino.
[wait][clear][end]

msg_25:
[color(yellow)]Elly[color(white)]
[tab]You all have dreams right? Because it
[tab]is a time like this, you must be looking
[tab]back at yourselves and your dreams.
[wait][clear][end]

msg_26:
[color(yellow)]Elly[color(white)]
[tab]For that "cool boy", this place seems
[tab]to bring back memories for him... I wonder
[tab]if something happened in the past?
[wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]...Th-This is!?
[tab]Ahh, it’s been a while.
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]This is... the first place we met the Joker.
[tab]Not the same Joker from "This Side"...
[tab]I’m talking about my... our friend.
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]Huh, those guys... I didn’t expect them to
[tab]be very different from the "Other Side"...
[tab]But there IS quite a difference.
[wait][clear][end]

msg_30:
[color(yellow)][tatsuya][color(white)]
[tab]...It’s my fault.
[tab]...I’m sorry, ...Eikichi.
[wait][clear][end]

msg_31:
[color(yellow)][tatsuya][color(white)]
[tab]A live house...
[tab]I haven’t touched a guitar for a while.
[wait][clear][end]

msg_32:
[color(yellow)]Ken[color(white)]
[tab]No one knows where Sevens’s [suou]
[tab]went, and our leader is gone...
[tab]What are we supposed to do?
[wait][clear][end]

msg_33:
[color(yellow)]Ken[color(white)]
[tab]I want to become a boxer!
[tab]A world champ!! One-Two!! I’ll get back
[tab]at all of those who made fun of me!
[wait][clear][end]

msg_34:
[color(yellow)]Ken[color(white)]
[tab]...But that’s just a dream.
[tab]I know it won’t happen, but if it did, 
[tab]I wonder if Michel-san would be happy for me?
[wait][clear][end]

msg_35:
[color(yellow)]Ken[color(white)]
[tab]Wonder what happened to Michel-san!? 
[tab]When it is like this, we got to be worried!
[tab]But I bet Miyabi-san is even more worried.
[wait][clear][end]

msg_36:
[color(yellow)]Shogo[color(white)]
[tab]A sushi restaurant... Sounds like hard work.
[tab]Sounds smelly... and a pain in the ass.
[tab]The best thing is eating the stuff!
[wait][clear][end]

msg_37:
[color(yellow)]Shogo[color(white)]
[tab]Is that New World Order for real?
[tab]I can’t understand why they would do
[tab]something like that. Ahhh, I’m so worried!
[wait][clear][end]

msg_38:
[color(yellow)]Shogo[color(white)]
[tab]It-It’s gotten, kind of scary but, 
[tab]until Michel-san returns... awawa...
[tab]W-We... we’ve got to protect Miyabi-san...!
[wait][clear][end]

msg_39:
[color(yellow)]Takeshi[color(white)]
[tab]I wonder if Michel-san went home. I’m sure his
[tab]dad is worried. Though it may not seem it,
[tab]his dad is the worrying type...
[wait][clear][end]

msg_40:
[color(yellow)]Takeshi[color(white)]
[tab]A boxer and a Sushi store... future huh.
[tab]I wanted to become a doctor.
[tab]Because my house is poor...
[wait][clear][end]

msg_41:
[color(yellow)]Takeshi[color(white)]
[tab]I’m not mad at my parents or anything!
[tab]I want to ease the burdens of my mom...
[tab]And get her some nice clothes and makeup.
[wait][clear][end]

msg_42:
[color(yellow)]Takeshi[color(white)]
[tab]A doctor to become rich...
[tab]I guess it’s not a proper motive?
[wait][clear][end]

msg_43:
[color(yellow)]Takeshi[color(white)]
[tab]I’m worried about mom too, but repaying my
[tab]dues to Michel-san comes first.[delay(30)]
[tab]...Miyabi-nee, don’t worry!
[wait][clear][end]

msg_44:
[color(yellow)]Miyabi Hanakouji[color(white)]
[tab]Eikichi-kun just took off without giving
[tab]any details.
[wait][clear][end]

msg_45:
[color(yellow)]Miyabi Hanakouji[color(white)]
[tab]...I don’t know what happened, but he said
[tab]he feels he has been forgetting something
[tab]very important.
[wait][clear][end]

msg_46:
[color(yellow)]Miyabi Hanakouji[color(white)]
[tab]Everybody has wonderful dreams.
[tab]Some say it’s only a dream because it
[tab]won’t happen, but that’s not true is it?
[wait][clear][end]

msg_47:
[color(yellow)]Miyabi Hanakouji[color(white)]
[tab]Eikichi-kun is very lucky, isn’t he?
[tab]He has so many great companions. I will
[tab]believe in Eikichi-kun’s return and wait here.
[wait][clear][end]

msg_48:
MBIT HI NANJOTOUJO
Spread Nanjo rumor
Bit on
[wait][clear][end]

msg_49:
MBIT AIS 29
Affinity reading
Bit on
[wait][clear][end]

msg_50:
EBIT E006F
Cleared Lab
Bit on
[wait][clear][end]

msg_51:
EBIT E0077
Cleared Smile Hirasaka
Bit on
[wait][clear][end]

msg_52:
EBIT E007A
Cleared Concert Hall
Bit on
[wait][clear][end]

msg_53:
EBIT E007B
Tapped Tatsuzou
Bit on
[wait][clear][end]

msg_54:
EBIT E007F
Cleared Factory
Bit on
[wait][clear][end]

msg_55:
EBIT E008C
Cleared Ruins
Bit on
[wait][clear][end]

msg_56:
EBIT E009F
Cleared Mt. Iwato
Bit on
[wait][clear][end]

msg_57:
EBIT E00AF
Cleared Torifune
Bit on
[wait][clear][end]

msg_58:
EBIT E00B8
Cleared Sumaru Castle
Bit on!!
[wait][clear][end]

msg_59:
[color(yellow)]Miyabi Hanakouji[color(green)]
[tab]Student of Sevens and the lead editor of
[tab]the school newspaper. Seems to be dating the
[tab]son of Gatten Sushi’s chef, Eikichi Mishina.
[wait][clear][end]

msg_60:
[color(yellow)]Miyabi Hanakouji[color(green)]
[tab]A student of Seven Sisters High who is
[tab]dating Eikichi. Also she is the lead
[tab]editor of the school newspaper.
[wait][clear][end]
