
msg_0:
There is more than 4 members in the party.
[tab]It will hang at this rate.
[tab]Please inform Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]After all... I can’t talk about others.
[tab]I caused Ma-ya trouble too...
[tab]I can only talk bad about Makimura.
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Does Bao have something against the Mafia?
[tab]Judging by his actions at the club,
[tab]something must’ve happened in the past.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Why is Bao so skeptical? Did something bad
[tab]happen after being tricked by someone?
[tab]Ah... but... that’s the same with me.
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]It ends up we were saved by [tatsuya]-kun again.
[tab]He always shows up with perfect timing.
[tab]But, he’s sure not normal.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]The eyes say as much as the mouth...
[tab]That kid’s eyes are just so painful...
[tab]Like he is carrying everyone’s misery...
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab][suou]-san and [tatsuya]-kun... They seem to
[tab]be opposites, but they’re exactly alike
[tab]when it comes to clumsiness.
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Either way, it turned out just like that
[tab]owner said. The rumor about the
[tab]man-searcher could be true...
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]Service regulation violation...
[tab]It isn’t something an outsider would just
[tab]say regularly. Baofu... what is he?
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]I’m breaking my penitence disposal for now...
[tab]But I’m still a public servant! ...I won’t
[tab]even allow a colleague’s illegal actions.
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]How many members of the New World Order
[tab]are in the police department...? ...Ch...
[tab]Even relatives can’t be easily trusted.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]Is that... really [tatsuya]...?
[tab]Like that girl said, he is almost like
[tab]another person... What is he hiding...?
[wait][clear][end]

msg_12:
[color(yellow)]Baofu[color(white)]
[tab]Something seems strange... Why did Serizawa
[tab]call you? If she’s gonna kill the swindler,
[tab]she doesn’t need to get permission, right?
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]It may be because of the curse, but would a
[tab]person really have that kind of ability
[tab]when turning into a Joker?
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab]Silly how you were after a Joker to kill,
[tab]but ended up becoming one.
[tab]Try not to be a nuisance anymore, eh...
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]So? How many more Joker users do we have
[tab]to bring to the Velvet Room...?
[tab]I’m starting to get sick of this.
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]There is no proof that those two rich kids
[tab]aren’t members of the New World Order.
[tab]If they are... We’re all screwed.
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]It’s likely the work of the New World Order,
[tab]but why did they kill the boy’s underlings?
[tab]It wasn’t needed if they were just watching.
[wait][clear][color(yellow)]Baofu[color(white)]
[tab]They just wanted to get us away from there...
[tab]Or was it just to make their presence felt...
[tab]Or is it some kind of preparation...
[wait][clear][end]

msg_18:
[color(yellow)]Nanjo[color(white)]
[tab]To find out if Kandori is really alive, and
[tab]save the captured people. And, if we could
[tab]find out their plans, that would be perfect.
[wait][clear][end]

msg_19:
[color(yellow)]Nanjo[color(white)]
[tab]Though not as much as Matsuoka, 
[tab]the subordinates are all decently trained...
[tab]To think of defeating all of them...
[wait][clear][end]

msg_20:
[color(yellow)]Nanjo[color(white)]
[tab]It seems...
[tab]We might have been underestimating them...
[wait][clear][end]

msg_21:
[color(yellow)]Elly[color(white)]
[tab]According to Kei’s research, someone who
[tab]seems to be a New World Order executive,
[tab]has made numerous TV appearances.
[wait][clear][color(yellow)]Elly[color(white)]
[tab]It is a popular spot, so I doubt they will
[tab]try anything outrageous... But we should
[tab]still be careful nonetheless.
[wait][clear][end]

msg_22:
[color(yellow)]Elly[color(white)]
[tab]Ms. Amano!
[tab]We can’t just let Wang Long Chizuru
[tab]roam freely!
[wait][clear][end]

msg_23:
[color(yellow)]Elly[color(white)]
[tab]We must hurry back to the TV station!
[wait][clear][end]

msg_24:
[color(yellow)]Elly[color(white)]
[tab]Though he may not show it,
[tab]Kei really does respect
[tab]Mr. Matsuoka a lot.
[wait][clear][end]

msg_25:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Oh, for some reason my heart is dancing...
[tab]Maybe it’s because of you...
[tab]In that case I’ll give you a discount...
[wait][clear][end]

msg_26:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Hi Hi... Nice to meet you...
[tab]Finally making an appearance, Satomi
[tab]Sister’s final warrior, I’m the 7th Sister...
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]I too will join my sisters to attain the
[tab]Satomi clan’s goal of national conquest...
[tab]Take the Satomi Sound...!!
[wait][clear][end]

msg_27:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Hi Hi... Nice to meet you...
[tab]Finally making an appearance, Satomi
[tab]Sister’s final warrior, I’m the 7th Sister...
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]I too will join my sisters to attain the
[tab]Satomi clan’s goal of national conquest...
[tab]Take the Satomi Sound...!!
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]I’m giving you a discount because we are a
[tab]perfect match... I’m already doing wrong by
[tab]betraying the clan... Uhyohyohyo!!
[wait][clear][end]

msg_28:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Yes yeees.
[tab]Welcome to the 7th sister’s store!
[tab]May I help you?
[wait][clear][end]

msg_29:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Welcooooome...
[tab]Uhyohyohyo.
[choice(6)]Buy items
Sell items
Talk to Sister #7
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_30:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]So, what would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_31:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]So what do you want to talk about?
[choice(3)]Make small talk
Ask about shopping
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_32:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Now, let’s go, let’s go...
[tab]Is there anything else...?
[tab]Even if not, you must think...
[choice(6)]Buy items
Sell items
Talk to Sister #7
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_33:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]So, what would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_34:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]So what do you want to talk about?
[choice(3)]Make small talk
Ask about shopping
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_35:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Was it a mistake to take this area...?
[tab]Isn’t this place kind of dangerous...?
[tab]Like a Mafia headquarters or something?
[wait][clear][end]

msg_36:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Sheesh!! Sister #4 knew that all along and
[tab]gave me this store!! She’s so cunning!
[wait][clear][end]

msg_37:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]A meeting is the beginning of an
[tab]end, but that’s sad.
[tab]So please come again. Uhyohyohyo!
[wait][clear][end]

msg_38:
[color(yellow)]Makimura[color(white)]
[tab]Was Ulala saying anything about me...?
[tab]Maybe, "I hate him", or "I’ll kill him", or
[tab]"I’ll forgive him"... Anything like that...?
[wait][clear][end]

msg_39:
[color(yellow)]Cry baby[color(white)]
[tab]Urrr... my little angel that I finally found
[tab]...ran away... Reeee!! Why does it have to
[tab]be determined by fortune telling...!!
[wait][clear][end]

msg_40:
[color(yellow)]Observing girl[color(white)]
[tab]MM/DD/YY... I was told to observe for my
[tab]homework, so here I am writing a journal...
[tab]...period.
[wait][clear][end]

msg_41:
[color(yellow)]Observing girl[color(white)]
[tab]Some strange lady started talking to me,
[tab]so I greeted her... period.
[end]

msg_42:
[tab]What do you want from me?
[wait][clear][end]

msg_43:
[tab]What do you want?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_44:
KEIKO YOKOYAMA
[end]

msg_45:
[color(yellow)]Observing girl[color(white)]
[tab]It seems the strange lady thought I was
[tab]someone else...
[tab]Kind of awkward... period.
[wait][clear][end]

msg_46:
[color(yellow)]Observing girl[color(white)]
[tab]That strange lady, some reason,
[tab]knew my name...
[tab]Very weird... period.
[wait][clear][end]

msg_47:
[color(yellow)]Keiko Yokoyama[color(white)]
[tab]Huh...?
[tab]Mama is looking for Kei-chan?
[tab]Okay, I’ll go call home.
[wait][clear][end]

msg_48:
[color(yellow)]Keiko Yokoyama[color(white)]
[tab]That strange lady, seemed to be looking 
[tab]for me. She was glad to have found me...
[tab]...period.
[wait][clear][end]

msg_49:
[color(yellow)]Keiko Yokoyama[color(white)]
[tab]I was told by my teacher not to talk to
[tab]strangers. So I ignored her...
[tab]...period.
[wait][clear][end]

msg_50:
[color(yellow)]Observing girl[color(white)]
[end]

msg_51:
[color(yellow)]Keiko Yokoyama[color(white)]
[end]

msg_52:
[tab]MM/DD/YY... A guy was rejected by
[tab]his girlfriend through fortune telling.
[tab]Too bad for him... period.
[wait][clear][end]

msg_53:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Uhyohyohyo!
[tab]Okay, I’ll tell you a little about shopping.
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]First, buying things. 
[tab]If you select "Buy items" here
[tab]you can choose from our sundries.
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]Oh, and there’s a limit to how many of the
[tab]same item you can carry.
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]Next, selling.
[tab]Select "Sell items" first, and then
[tab]choose which type of item to sell. 
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]Then pick a particular item to sell us.
[tab]Our resale prices are around half the original
[tab]price. You can’t sell anything you have equipped,
[wait][clear][color(yellow)]Satomi Sister #7[color(white)]
[tab]and some special items are off-limits too.
[tab]That’s about it.
[tab]Uhyohyohyo!
[wait][clear][end]

msg_54:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]Oh, but you don’t have anything you can sell.[wait][clear][end]

msg_55:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]The total comes to ¥[var(msg_var_0)].
[tab]Is that all right?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_56:
[color(yellow)]Satomi Sister #7[color(white)]
[tab]The total comes to ¥[var(msg_var_0)].
[tab]Is that all right?
[choice(2)]Yes
No
[end_choice][clear][end]
