
msg_0:
Please contact Kaneda or Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya, that dude asked me to go out
[tab]with him for a meal...
[tab]He wishes...!
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Hmm... A "whitening" course.
[tab]Isn’t this a tanning salon?
[tab]How do they "whiten" you?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun must be either very powerful or
[tab]very reckless. I mean, would anyone normal
[tab]think of fighting those guys all alone?
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Isn’t [tatsuya]-kun’s body of This Side although
[tab]his consciousness is of the Other Side?
[tab]So [tatsuya]-kun’s consciousness is dormant here?
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Seeing how you worked that oven room, you
[tab]must have had it hard on the Other Side too.
[end]

msg_6:
[tab]Well, that’s so like you.
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]By the way, I forgot to thank you. 
[tab]If Amano-kun and everyone hadn’t come along, 
[tab]I probably would have been defeated.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]After all, even though we fight,
[tab]our reasons are all different...
[tab]...Well... maybe it’s only natural.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]But why is [tatsuya] after Tatsuzou...?
[tab]Does he know about father...?
[tab]Or is there some other reason...?
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]D五j二 vu is proof that the balance
[tab]between the two worlds is skewed.
[tab]And it’s continuing to get worse.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]If Tatsuzou begins his Dragon Ritual,
[tab]there will be no way to stop him.
[tab]We must stop him before he begins...
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]There are limitations as to what a person
[tab]can do by themselves... But by working
[tab]together, nothing is impossible...
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]Serizawa’s bad habit is she can’t ignore someone 
[tab]who angers her. It’s just a matter of time 
[tab]before she gets taken advantage of again.
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab]Something’s not right... The tin-plated doll
[tab]we saw at the factory. I feel I’ve seen a
[tab]thing like it before... I must be imagining it.
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]The reason for that kid chasing Tatsuzou
[tab]seems to be different than that of [suou]’s. 
[tab]Of course, it’s just a hunch...
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]With things like this happening, it’s just a
[tab]matter of time before the citizens remember
[tab]the "Other Side". We must hurry.
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]Compared to those who are careful and
[tab]calculating, we just move randomly. 
[tab]Can we really stop the Dragon Ritual like this?
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]He is the negative emotions of all humans.
[tab]Fighting against him could be like fighting
[tab]against the entire human race.
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Heh, heh... Such sarcasm. To think I
[tab]would get involved with someone like him.
[tab]Well, I feel no regrets.
[wait][clear][end]

msg_20:
[color(yellow)]Nanjo[color(white)]
[tab]I was surprised when returning to Japan,
[tab]to see so many tan women now. 
[tab]Are they putting something on their faces...?
[wait][clear][end]

msg_21:
[color(yellow)]Nanjo[color(white)]
[tab]But... Even for recovery purposes, 
[tab]I feel uncomfortable coming in here. 
[tab]I have no desire to tan my skin for looks...
[wait][clear][end]

msg_22:
[color(yellow)]Nanjo[color(white)]
[tab]Sometimes, I confuse [suou] for Kandori
[tab]and vice versa...
[tab]...I wonder why...?
[wait][clear][end]

msg_23:
[color(yellow)]Elly[color(white)]
[tab](giggle) I was just asked to go to dinner
[tab]by that store owner...
[tab]Of course, I politely declined the offer.
[wait][clear][end]

msg_24:
[color(yellow)]Elly[color(white)]
[tab]Umm...
[tab]I do not wish to be tanned very much...
[tab]Is this place... really safe?
[wait][clear][end]

msg_25:
[color(yellow)]Elly[color(white)]
[tab]What was Mr. Kandori’s intent...?
[tab]I feel his was different from that of
[tab]the New World Order...
[wait][clear][end]

msg_26:
[color(yellow)][tatsuya][color(white)]
[tab]I wished...
[tab]When we met at Sevens...
[tab]You would have forgotten the entire thing...
[wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]This world is definitely headed towards
[tab]destruction just as the Other Side is.
[tab]That must be stopped, no matter the cost!
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]It is lucky that at least the temple didn’t
[tab]come out. Even the slightest difference
[tab]from the Other Side is good.
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]We are in at a disadvantage, but...
[tab]I don’t feel that I will lose.
[tab]I am... no longer alone...
[wait][clear][end]

msg_30:
[color(yellow)]Bro[color(white)]
[tab]Hi, how goes it? Am I cool or what?
[tab]Wel-come to Bikini Line♥
[tab]Now, what would you like?
[wait][clear][end]

msg_31:
[color(yellow)]Bro[color(white)]
[tab]Hmmm... What is this pounding of my
[tab]heart... We might be the perfect match.
[tab]I might have to think about prices...
[wait][clear][end]

msg_32:
[color(yellow)]Bro[color(white)]
[tab]Which course did you have in mind today?
[choice(4)]Heal
Talk to Bro
Never mind
Leave the store
[end_choice][clear][end]

msg_33:
[color(yellow)]Bro[color(white)]
[tab]Oh yeah? What should we talk about?
[choice(3)]Make small talk
Ask about healing
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_34:
[color(yellow)]Bro[color(white)]
[tab]Is there anything else?
[tab]Say, say, say what you need!
[tab]I’m at your service.
[wait][clear][end]

msg_35:
[color(yellow)]Bro[color(white)]
[tab]By the way, how about going out for a bite
[tab]with me? I know this delicious place..
[tab]I’m friends with the chef there...
[wait][clear][end]

msg_36:
[color(yellow)]Bro[color(white)]
[tab]Your daily actions are very important.
[tab]I’m perfect in that category, so I’ll get
[tab]to be on the Torifune...
[wait][clear][end]

msg_37:
[color(yellow)]Bro[color(white)]
[tab]Hey, can I ask you something? ...You and
[tab]that guy in red, do you know each other?
[tab]I feel like I’ve met him before...
[wait][clear][end]

msg_38:
[color(yellow)]Bro[color(white)]
[tab]What happened to me? ...A while ago, 
[tab]I had a dream this city was flying in the air...
[tab]Could it have been a prophecy?
[wait][clear][end]

msg_39:
[color(yellow)]Bro[color(white)]
[tab]Hey-Hey-Hey, where is this?
[tab]Why is the sky all red!?
[tab]Is this a sign of some sort...
[wait][clear][end]

msg_40:
[color(yellow)]Bro[color(white)]
[tab]Huh... You’re leaving?
[tab]I’ll miss you... I’ll be lonely.
[tab]So please come again...
[wait][clear][end]

msg_41:
[color(yellow)]Bro[color(white)]
[tab]Huh? Everyone looks healthy. If you
[tab]bask in our light, won’t you become
[tab]too healthy?
[wait][clear][end]

msg_42:
[color(yellow)]Bro[color(white)]
[tab]Then... a special price just for you.
[tab]Only ¥3000.[wait][clear][end]

msg_43:
[color(yellow)]Bro[color(white)]
[tab]Hmm, I can’t take money from someone
[tab]who is a perfect match with me.
[tab]So I’ll give you half price, ¥1,500.
[wait][clear][end]

msg_44:
[color(yellow)]Bro[color(white)]
[tab]You will heal right?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_45:
[color(yellow)]Bro[color(white)]
[tab]Huh? ...Are you sure...?
[tab]Don’t you think you should recover?
[tab]I’m so lonely...
[wait][clear][end]

msg_46:
[color(green)]Maya and her party recovered.[color(white)][wait][clear][end]

msg_47:
[color(yellow)]Bro[color(white)]
[tab]Mmmmmm?
[tab]Looks like you don’t have enough money.
[tab]Too bad.
[wait][clear][end]

msg_48:
[color(yellow)]Bro[color(white)]
[tab]Is there anything else?
[tab]Say, say, say what you need!
[tab]I’m at your service.
[choice(4)]Heal
Talk to Bro
Never mind
Leave the store
[end_choice][clear][end]

msg_49:
[color(yellow)]Bro[color(white)]
[tab]Oh yeah? What should we talk about?
[choice(3)]Make small talk
Ask about healing
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_50:
[color(yellow)]Bro[color(white)]
[tab]Yoohoo!! Guide our little kittens...
[tab]I mean our [var(msg_var_1)]customers!
[tab]Enjoy the tanning of your body and soul!
[wait][clear][end]

msg_51:
[color(yellow)]Bro[color(white)]
[tab]Guide our [var(msg_var_1)] little kittens, and [var(msg_var_2)] guys.
[tab]Enjoy the tanning of your body and soul!
[wait][clear][end]

msg_52:
[color(yellow)]Pale girl[color(white)]
[tab]That pisses me off! I went to Smile Hirasaka 
[tab]to see Ginji Sasaki... Then they wouldn’t
[tab]let me in because of some frickin’ fire!
[wait][clear][end]

msg_53:
[color(yellow)]Pale girl[color(white)]
[tab]There’s that Torifune under here, right?
[tab]If I don’t get in I’ll get destroyed too...
[tab]I’ll be okay if I stay here, so I’m lucky.
[wait][clear][end]

msg_54:
[color(yellow)]Pale girl[color(white)]
[tab]Hey, who is that in the red clothes?
[tab]He’s kind of cool!
[tab]Maybe I’ll ask him out.
[wait][clear][end]

msg_55:
[color(yellow)]Pale girl[color(white)]
[tab]I heard this rumor, that in Narumi, the
[tab]Ameno Torifune is being excavated, right?
[tab]They claim it’s just subway construction.
[wait][clear][end]

msg_56:
[color(yellow)]Pale girl[color(white)]
[tab]What is that castle in Rengedai anyway? 
[tab]Does it have something to do with the 
[tab]Legend of Torifune also? I don’t get this.
[wait][clear][end]

msg_57:
[color(yellow)]Pale girl[color(white)]
[tab]I was attacked by the Tenchu Army and in
[tab]big danger, but then I was saved by this
[tab]really cool guy!!
[wait][clear][color(yellow)]Pale girl[color(white)]
[tab]He was some salesman, but he beat up the
[tab]Tenchu Army with his bare hands... He said,
[tab]"Amateurs should hide in the back."
[wait][clear][end]

msg_58:
[color(yellow)]Expressionless woman[color(white)]
[tab](Mumble Mumble)... Damn him!
[tab]Flirting with the female customers...!
[tab]He told me I was the best...(Mumble)...
[wait][clear][end]

msg_59:
[color(yellow)]Expressionless woman[color(white)]
[tab]Hey, why are you staring at me?!
[tab]What! What is it...!?
[tab]What do you want from me?
[wait][clear][end]

msg_60:
[tab]What do you want!?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_61:
JUNKO IKEDA
[end]

msg_62:
[color(yellow)]Expressionless woman[color(white)]
[tab]WHA? Who the hell is that?
[tab]If you’re looking for someone, ask elsewhere.
[tab]I don’t have the time.
[wait][clear][end]

msg_63:
[color(yellow)]Expressionless woman[color(white)]
[tab]Huh? How do you know my name?
[tab]Wh... what, you’re so freaky...
[tab]What are you?
[wait][clear][end]

msg_64:
[color(yellow)]Junko Ikeda[color(white)]
[tab]Searching... but...
[tab]Does that mean there is a search for me?
[tab]But... Why?
[wait][clear][color(yellow)]Junko Ikeda[color(white)]
[tab]Oh, well.
[tab]I’ll just ask that man-searcher.
[tab]I’ll tell her about you too.
[wait][clear][color(yellow)]Junko Ikeda[color(white)]
[tab]I’m surprised you knew I was here...
[tab]Was it hard to find me?
[tab]I’ll say thanks for now. Thank you.
[wait][clear][end]

msg_65:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_66:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_67:
[tab]You should be careful.
[tab]That store owner hits on every single woman
[tab]that walks into the store!
[wait][clear][end]

msg_68:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_69:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_70:
[tab]How stupid!
[tab]There can’t be a Torifune.
[tab]There’s something wrong with these people!
[wait][clear][end]

msg_71:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_72:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_73:
[tab]There’s been this long earthquake, and the
[tab]people in the city are screaming it’s the
[tab]sign of the Torifune! They’re all dreaming!
[wait][clear][end]

msg_74:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_75:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_76:
[tab]But... the Legend of Torifune was real...
[tab]Then, the world is really going to end?
[tab]What, what should I do...?
[wait][clear][end]

msg_77:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_78:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_79:
[tab]This world might end...
[tab]Even at a time like this, I’m at the side
[tab]of HIM... I’m so stupid... really...
[wait][clear][end]

msg_80:
[color(yellow)]Bro[color(white)]
[tab]Sure, I’ll tell you how this works.
[wait][clear][color(yellow)]Bro[color(white)]
[tab]If you select "Heal" our tanning beds will
[tab]restore your HP and SP, plus cure any status
[tab]ailments like poison in the bargain.
[wait][clear][color(yellow)]Bro[color(white)]
[tab]Yeah, it’s a little expensive, but since it
[tab]heals all of you, it’s cheaper in the end.
[wait][clear][end]
