
msg_0:
There are more than 4 people in the party.
[tab]This will cause the game to hang.
[tab]Please contact Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Didn’t he say he has villas overseas?
[tab]Don’t believe it, it’s all a lie. He just
[tab]made it seem so, getting tanned locally.
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]The key to judging a man is, his shoes!
[end]

msg_3:
[tab]Guys with cheap, dirty shoes are no
[tab]good, even if the rest is okay. Beware!
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Must be able to get a lot of Kegare from that guy. 
[tab]Should we take him to the seminar?
[wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]I’ve heard of a tanning salon that treats
[tab]wounds and illness...
[tab]This must be the one.
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]Well... the fact is, that rumor has
[tab]been spread. The part of it coming
[tab]true is just full of it...
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Isn’t that pale girl still a student? 
[tab]Should she be here at a time like this? 
[tab]It’s not my department, but I should report this.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]But... even if collecting Kegare is possible, 
[tab]what are they going to use it for...
[tab]What kind of power does it have?
[wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]Makimura and that storekeeper...
[tab]Don’t they seem like similar types?
[tab]He might be buying hate from women too.
[wait][clear][end]

msg_10:
[color(yellow)]Baofu[color(white)]
[tab]Wanna make a bet? To see if Serizawa will
[tab]be tricked by a man again. 
[tab]I’ll bet that she does get tricked.
[wait][clear][end]

msg_11:
[color(yellow)]Baofu[color(white)]
[tab]Even rumors become true. 
[tab]It’s no surprise if people’s kegare 
[tab]has some sort of power.
[wait][clear][end]

msg_12:
[color(yellow)]Nanjo[color(white)]
[tab]They used to say a fair complexion
[tab]compensates for poor features...
[tab]They don’t seem to anymore.
[wait][clear][end]

msg_13:
[color(yellow)]Nanjo[color(white)]
[tab]They realize our existence. The seminar
[tab]must be the showing of their restlessness.
[tab]...Or maybe they don’t even see us...
[wait][clear][end]

msg_14:
[color(yellow)]Elly[color(white)]
[tab]Being under the sun is good for your
[tab]body. Overseas, some hospitals use
[tab]sunlight to cure.
[wait][clear][end]

msg_15:
[color(yellow)]Elly[color(white)]
[tab]The machine Kei saw that absorbs
[tab]people’s Kegare, might be a device
[tab]that takes people’s Personas...
[wait][clear][end]

msg_16:
[color(yellow)]Makimura[color(white)]
[tab]H... Hey...
[tab]Are you interested in an overseas trip?
[tab]I’ll invite you to my villa.
[wait][clear][end]

msg_17:
[color(yellow)]Makimura[color(white)]
[tab]...So... So please help me!
[tab]I’ll get killed by Ulala...
[wait][clear][end]

msg_18:
[color(yellow)]Bro[color(white)]
[tab]Hi, how goes it? Am I cool or what?
[tab]Wel-come to Bikini Line♥
[tab]Now, what would you like?
[wait][clear][end]

msg_19:
[color(yellow)]Bro[color(white)]
[tab]Hmmm... What is this pounding of my
[tab]heart... We might be the perfect match.
[tab]I might have to think about the prices...
[wait][clear][end]

msg_20:
[color(yellow)]Bro[color(white)]
[tab]Which course did you have in mind today?
[choice(4)]Heal
Talk to Bro
Never mind
Leave the store
[end_choice][clear][end]

msg_21:
[color(yellow)]Bro[color(white)]
[tab]Oh yeah? What should we talk about?
[choice(3)]Make small talk
Ask about healing
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_22:
[color(yellow)]Bro[color(white)]
[tab]Is there anything else?
[tab]Say, say, say what you need!
[tab]I’m at your service.
[wait][clear][end]

msg_23:
[color(yellow)]Bro[color(white)]
[tab]They say tanning is not good for your
[tab]skin, but we use a special kind of
[tab]light that causes no problems.
[wait][clear][color(yellow)]Bro[color(white)]
[tab]Not only does it give a tan, it also
[tab]makes you healthy for real. Any kind
[tab]of wound or illness, gonzo...
[wait][clear][end]

msg_24:
[color(yellow)]Bro[color(white)]
[tab]Huh? Why don’t I go to the seminar?
[tab]It’s all good...!
[tab]Because I have no Kegare.
[wait][clear][color(yellow)]Bro[color(white)]
[tab]So honest and innocent!
[tab]Pure, shy and delicate... What kind
[tab]of defilement could I possibly have?
[wait][clear][end]

msg_25:
[color(yellow)]Bro[color(white)]
[tab]Huh... You’re leaving?
[tab]I’ll miss you... I’ll be lonely.
[tab]So please come again...
[wait][clear][end]

msg_26:
[color(yellow)]Bro[color(white)]
[tab]Huh? Everyone looks healthy. If you
[tab]bask in our light, won’t you become
[tab]too healthy?
[wait][clear][end]

msg_27:
[color(yellow)]Bro[color(white)]
[tab]Then... a special price just for you.
[tab]Only ¥3000.
[wait][clear][end]

msg_28:
[color(yellow)]Bro[color(white)]
[tab]Hmm, I can’t take money from someone
[tab]who is a perfect match with me.
[tab]So I’ll give you half price, ¥1500.
[wait][clear][end]

msg_29:
[color(yellow)]Bro[color(white)]
[tab]You will heal right?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_30:
[color(yellow)]Bro[color(white)]
[tab]Huh? ...Are you sure...?
[tab]Don’t you think you should recover?
[tab]I’m so lonely...
[wait][clear][end]

msg_31:
[color(green)]Maya and her party recovered.[color(white)][wait][clear][end]

msg_32:
[color(yellow)]Bro[color(white)]
[tab]Mmmmmm?
[tab]Looks like you don’t have enough money.
[tab]Too bad.
[wait][clear][end]

msg_33:
[color(yellow)]Bro[color(white)]
[tab]Is there anything else?
[tab]Say, say, say what you need!
[tab]I am at your service.
[choice(4)]Heal
Talk to Bro
Never mind
Leave the store
[end_choice][clear][end]

msg_34:
[color(yellow)]Bro[color(white)]
[tab]Oh yeah? What should we talk about?
[choice(3)]Make small talk
Ask about healing
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_35:
[color(yellow)]Bro[color(white)]
[tab]Yoohoo!! Guide our little kittens...
[tab]I mean our [var(msg_var_1)]customers!
[tab]Enjoy the tanning of your body and soul!
[wait][clear][end]

msg_36:
[color(yellow)]Bro[color(white)]
[tab]Guide our [var(msg_var_1)] little kittens, and [var(msg_var_2)] guys.
[tab]Enjoy the tanning of your body and soul!
[wait][clear][end]

msg_37:
[color(yellow)]Pale girl[color(white)]
[tab]There are Mafia at the Zodiac...
[tab]This is a just a rumor,
[tab]but secret casinos, sounds interesting...
[wait][clear][end]

msg_38:
[color(yellow)]Pale girl[color(white)]
[tab]I also want a boyfriend,
[tab]and I’m kind of light-skinned...
[tab]That’s why I come here.
[wait][clear][end]

msg_39:
[color(yellow)]Pale girl[color(white)]
[tab]Kegare is scary too, but if I go to
[tab]the seminar, I get to see Ginji, right?
[tab]That sounds so fun.
[wait][clear][end]

msg_40:
[color(yellow)]Expressionless woman[color(white)]
[tab](Mumble Mumble)... Damn him!
[tab]Flirting with the female customers...!
[tab]He told me I was the best...(Mumble)...
[wait][clear][end]

msg_41:
[color(yellow)]Expressionless woman[color(white)]
[tab]Hey, why are you staring at me?!
[tab]What! What is it...!?
[tab]What do you want from me?
[wait][clear][end]

msg_42:
[tab]What do you want!?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_43:
JUNKO IKEDA
[end]

msg_44:
[color(yellow)]Expressionless woman[color(white)]
[tab]WHA? Who the hell is that?
[tab]If you’re looking for someone, ask elsewhere.
[tab]I don’t have the time.
[wait][clear][end]

msg_45:
[color(yellow)]Expressionless woman[color(white)]
[tab]Huh? How do you know my name?
[tab]Wh... what, that’s so freaky...
[tab]What are you?
[wait][clear][end]

msg_46:
[color(yellow)]Junko Ikeda[color(white)]
[tab]Searching... but...
[tab]Does that mean there is a search for me?
[tab]But... Why?
[wait][clear][color(yellow)]Junko Ikeda[color(white)]
[tab]Oh, well.
[tab]I’ll just ask that man-searcher.
[tab]I’ll tell her about you too.
[wait][clear][color(yellow)]Junko Ikeda[color(white)]
[tab]I’m surprised you knew I was here...
[tab]Was it hard to find me?
[tab]I’ll say thanks for now. Thank you.
[wait][clear][end]

msg_47:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_48:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_49:
[tab]That store keeper is a former high school
[tab]all-star tennis player... Does he look like
[tab]it though? ...I bet it is bull.
[wait][clear][end]

msg_50:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_51:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_52:
[tab]The other day they were saying they use a
[tab]special light and can fix any wound or
[tab]illness. Those school girls believe it too.
[wait][clear][end]

msg_53:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_54:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_55:
[tab]And that pale girl over there is so into
[tab]the store owner too...
[tab]Hope she doesn’t get fooled.
[wait][clear][end]

msg_56:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_57:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_58:
[tab]The world is full of nothing but deception...
[tab]Men trick women, and women trick men back...
[tab]Love isn’t as pretty as the word may sound.
[wait][clear][end]

msg_59:
[color(yellow)]Expressionless woman[color(white)]
[end]

msg_60:
[color(yellow)]Junko Ikeda[color(white)]
[end]

msg_61:
[tab]That store owner is so full of it...
[tab]He’s been lying all this time, and now
[tab]he says he doesn’t have any Kegare!
[wait][clear][end]

msg_62:
[color(yellow)]Bro[color(white)]
[tab]Sure, I’ll tell you how this works.
[wait][clear][color(yellow)]Bro[color(white)]
[tab]If you select "Heal" our tanning beds will
[tab]restore your HP and SP, plus cure any status
[tab]ailments like poison in the bargain.
[wait][clear][color(yellow)]Bro[color(white)]
[tab]Yeah, it’s a little expensive, but since it
[tab]heals all of you, it’s cheaper in the end.
[wait][clear][end]
