function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3059, 127);
    ref_3 = todLoad(tod_b);
    wait(ref_3);
    todRun(tod_b, 1);
    envTriggerSet(DOORBOX, 131, 1, line, coll_32);
    envTriggerSet(PCHIT, 14, 1, line, coll_1f);
    bitGet(var_0, MBIT_W_HATURAITEN);
    bnz(var_0, label_c);
    cameraSet(southwest, 500, 0, -1500);
    b(label_d);
  label_c:
    cameraSet(northwest, 700, 0, -360);
  label_d:
    li(var_0, 0);
    li(var_1, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, tatsuya);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_1e);
    li(var_0, 0);
    b(label_23);
  label_1e:
    ref_1e = dialogAlloc();
    ref_1f = msgShow(msg_0);
/***************************************
That’s over 4 people in the party.
In this condition, it will hang.
Get a hold of Kaneda and Kataoka.
[wait][clear]
***************************************/
    wait(ref_1f);
    dialogFree(ref_1e);
    b(label_23);
  label_23:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_28);
    bitGet(var_0, EBIT_E008C);
    bez(var_0, label_2e);
    bnz(var_0, label_2a);
  label_28:
    partyMemberCheck(var_0, tatsuya);
    bez(var_0, label_2e);
  label_2a:
    ref_2a = spriteLoad(sprite_18);
    wait(ref_2a);
    unitSpawn(tatsuya, sprite_18, 650, 0, -1470, east, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
  label_2e:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_41);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_39);
    partyMemberCheck(var_0, elly);
    bez(var_0, label_41);
    ref_34 = spriteLoad(sprite_23);
    wait(ref_34);
    unitSpawn(elly, sprite_23, 1110, 0, -1270, east, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
    b(label_41);
  label_39:
    bne(var_0, 1, label_41);
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_41);
    ref_3c = spriteLoad(sprite_1f);
    wait(ref_3c);
    unitSpawn(nanjo, sprite_1f, 960, 0, -1400, west, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
    b(label_41);
  label_41:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_47);
    ref_43 = spriteLoad(sprite_6);
    wait(ref_43);
    unitSpawn(ulala, sprite_6, 330, 0, -340, west, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_47:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_4d);
    ref_49 = spriteLoad(sprite_d);
    wait(ref_49);
    unitSpawn(katsuya, sprite_d, 1050, 0, -440, north, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_4d:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_53);
    ref_4f = spriteLoad(sprite_13);
    wait(ref_4f);
    unitSpawn(baofu, sprite_13, 800, 0, -1200, south, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_53:
    ref_53 = spriteLoad(sprite_9b);
    wait(ref_53);
    unitSpawn(shopkeeper, sprite_9b, 700, 0, -150, north, none);
    unitTriggerSet(shopkeeper, SHOP, 255, 1);
    envTriggerSet(SHOP, 56, 1, line, coll_0);
    envTriggerSet(SHOP, 112, 1, line, coll_1);
    envTriggerSet(SHOP, 224, 1, line, coll_2);
    envTriggerSet(SHOP, 14, 1, line, coll_3);
    envTriggerSet(SHOP, 28, 1, line, coll_4);
    envTriggerSet(SHOP, 131, 1, line, coll_5);
    ref_5d = spriteLoad(sprite_c8);
    wait(ref_5d);
    unitSpawn(npc1, sprite_c8, 340, 0, -900, north, none);
    unitPalette(npc1, 2);
    unitTriggerSet(npc1, MAN1, 255, 1);
    ref_62 = spriteLoad(sprite_d2);
    wait(ref_62);
    unitSpawn(npc2, sprite_d2, 590, 0, -700, west, none);
    unitPalette(npc2, 2);
    unitTriggerSet(npc2, MAN2, 255, 1);
    ref_67 = spriteLoad(sprite_bd);
    wait(ref_67);
    unitSpawn(unit_58, sprite_bd, 260, 0, -1330, east, none);
    unitTriggerSet(unit_58, GIRL, 255, 1);
    ref_6b = spriteLoad(sprite_0);
    wait(ref_6b);
    ref_6d = spriteLoad(sprite_2);
    wait(ref_6d);
    ref_6f = spriteLoad(sprite_1);
    wait(ref_6f);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_de);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_ce);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_b6);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_a6);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_96);
    unitFacePlayer(ulala);
    ref_87 = bustupLoad(bustup_1d);
    bustupWait(ref_87);
    ref_89 = bustupAlloc(ref_87, left, rgb(0,0,0));
    bustupFade(ref_89, rgb(128,0,0), 30);
    ref_8b = dialogAlloc();
    ref_8c = msgShow(msg_1);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab][suou]-san went alone, but I wonder if
[tab]it’s a trap... I think it is.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_8c);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_8b);
    ref_91 = bustupFade(ref_89, rgb(0,0,0), 10);
    bustupWait(ref_91);
    bustupFree(ref_89);
    unitRestoreFacing(ulala);
    b(label_ee);
  label_96:
    unitFacePlayer(ulala);
    ref_97 = bustupLoad(bustup_17);
    bustupWait(ref_97);
    ref_99 = bustupAlloc(ref_97, left, rgb(0,0,0));
    bustupFade(ref_99, rgb(128,0,0), 30);
    ref_9b = dialogAlloc();
    ref_9c = msgShow(msg_2);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab][suou]-san’s brother seems to know
[tab]a lot, but do you think he knows about
[tab]his father as well?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_9c);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_9b);
    ref_a1 = bustupFade(ref_99, rgb(0,0,0), 10);
    bustupWait(ref_a1);
    bustupFree(ref_99);
    unitRestoreFacing(ulala);
    b(label_ee);
  label_a6:
    unitFacePlayer(ulala);
    ref_a7 = bustupLoad(bustup_17);
    bustupWait(ref_a7);
    ref_a9 = bustupAlloc(ref_a7, left, rgb(0,0,0));
    bustupFade(ref_a9, rgb(128,0,0), 30);
    ref_ab = dialogAlloc();
    ref_ac = msgShow(msg_3);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Ma-ya, it seems like the New World Order
[tab]rumor is the big news on the net...
[tab]What are we gonna do?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_ac);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ab);
    ref_b1 = bustupFade(ref_a9, rgb(0,0,0), 10);
    bustupWait(ref_b1);
    bustupFree(ref_a9);
    unitRestoreFacing(ulala);
    b(label_ee);
  label_b6:
    unitFacePlayer(ulala);
    ref_b7 = bustupLoad(bustup_17);
    bustupWait(ref_b7);
    ref_b9 = bustupAlloc(ref_b7, left, rgb(0,0,0));
    bustupFade(ref_b9, rgb(128,0,0), 30);
    ref_bb = dialogAlloc();
    bitGet(var_0, EBIT_E0096);
    bne(var_0, 0, label_c2);
    ref_be = msgShow(msg_4);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Looks like he’s hiding something
[tab]that relates to you, Ma-ya.
[tab]...Maybe d五j二 vu does exist.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_be);
    b(label_c7);
  label_c2:
    bne(var_0, 1, label_c7);
    ref_c3 = msgShow(msg_5);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya, what happened on the
[tab]"Other Side"? How were you related
[tab]to him? Hey... You can’t remember?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_c3);
    b(label_c7);
  label_c7:
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_bb);
    ref_c9 = bustupFade(ref_b9, rgb(0,0,0), 10);
    bustupWait(ref_c9);
    bustupFree(ref_b9);
    unitRestoreFacing(ulala);
    b(label_ee);
  label_ce:
    unitFaceUnit(ulala, tatsuya);
    ref_cf = bustupLoad(bustup_1b);
    bustupWait(ref_cf);
    ref_d1 = bustupAlloc(ref_cf, left, rgb(0,0,0));
    bustupFade(ref_d1, rgb(128,0,0), 30);
    ref_d3 = dialogAlloc();
    ref_d4 = msgShow(msg_6);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]I see, New World Order is the only
[tab]difference with the "Other Side".[delay(30)]
[tab]Hey, that’s a BIG difference, [tatsuya]-kun!!
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_d4);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_d3);
    ref_d9 = bustupFade(ref_d1, rgb(0,0,0), 10);
    bustupWait(ref_d9);
    bustupFree(ref_d1);
    unitRestoreFacing(ulala);
    b(label_ee);
  label_de:
    unitFacePlayer(ulala);
    ref_df = bustupLoad(bustup_17);
    bustupWait(ref_df);
    ref_e1 = bustupAlloc(ref_df, left, rgb(0,0,0));
    bustupFade(ref_e1, rgb(128,0,0), 30);
    ref_e3 = dialogAlloc();
    ref_e4 = msgShow(msg_7);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Okay, Ma-ya! I’m ready anytime!
[tab]My life right now is pretty exciting,
[tab]but it can’t be like this forever!
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_e4);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_e3);
    ref_e9 = bustupFade(ref_e1, rgb(0,0,0), 10);
    bustupWait(ref_e9);
    bustupFree(ref_e1);
    unitRestoreFacing(ulala);
    b(label_ee);
  label_ee:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_152);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_142);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_11e);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_10e);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_fb);
  label_fb:
    unitFacePlayer(katsuya);
    ref_fc = bustupLoad(bustup_29);
    bustupWait(ref_fc);
    ref_fe = bustupAlloc(ref_fc, left, rgb(0,0,0));
    bustupFade(ref_fe, rgb(128,0,0), 30);
    ref_100 = dialogAlloc();
    ref_101 = msgShow(msg_8);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]If my father wasn’t involved, [tatsuya]
[tab]wouldn’t have been the way he is now.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_101);
    ref_104 = msgShow(msg_9);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]...Father, me, [tatsuya]... We were
[tab]all involved in the New World Order’s plan.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_104);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_100);
    ref_109 = bustupFade(ref_fe, rgb(0,0,0), 10);
    bustupWait(ref_109);
    bustupFree(ref_fe);
    unitRestoreFacing(katsuya);
    b(label_162);
  label_10e:
    unitFacePlayer(katsuya);
    ref_10f = bustupLoad(bustup_21);
    bustupWait(ref_10f);
    ref_111 = bustupAlloc(ref_10f, left, rgb(0,0,0));
    bustupFade(ref_111, rgb(128,0,0), 30);
    ref_113 = dialogAlloc();
    ref_114 = msgShow(msg_10);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Is it possible that the New World Order is
[tab]manipulating information on the net!?
[tab]They must be... It was a blind spot.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_114);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_113);
    ref_119 = bustupFade(ref_111, rgb(0,0,0), 10);
    bustupWait(ref_119);
    bustupFree(ref_111);
    unitRestoreFacing(katsuya);
    b(label_162);
  label_11e:
    bitGet(var_0, EBIT_E0096);
    bne(var_0, 0, label_130);
    unitFacePlayer(katsuya);
    ref_121 = bustupLoad(bustup_27);
    bustupWait(ref_121);
    ref_123 = bustupAlloc(ref_121, left, rgb(0,0,0));
    bustupFade(ref_123, rgb(128,0,0), 30);
    ref_125 = dialogAlloc();
    ref_126 = msgShow(msg_11);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]...Why?
[tab]Why is [tatsuya] avoiding me?
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1f, 1);
    wait(ref_126);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_125);
    ref_12b = bustupFade(ref_123, rgb(0,0,0), 10);
    bustupWait(ref_12b);
    bustupFree(ref_123);
    unitRestoreFacing(katsuya);
    b(label_141);
  label_130:
    bne(var_0, 1, label_141);
    unitFacePlayer(katsuya);
    ref_132 = bustupLoad(bustup_27);
    bustupWait(ref_132);
    ref_134 = bustupAlloc(ref_132, left, rgb(0,0,0));
    bustupFade(ref_134, rgb(128,0,0), 30);
    ref_136 = dialogAlloc();
    ref_137 = msgShow(msg_12);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Even if [tatsuya] may be from another
[tab]world, he’s still my brother...
[tab]Nothing will change between us... Nothing...
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1f, 1);
    wait(ref_137);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_136);
    ref_13c = bustupFade(ref_134, rgb(0,0,0), 10);
    bustupWait(ref_13c);
    bustupFree(ref_134);
    unitRestoreFacing(katsuya);
    b(label_141);
  label_141:
    b(label_162);
  label_142:
    unitFacePlayer(katsuya);
    ref_143 = bustupLoad(bustup_21);
    bustupWait(ref_143);
    ref_145 = bustupAlloc(ref_143, left, rgb(0,0,0));
    bustupFade(ref_145, rgb(128,0,0), 30);
    ref_147 = dialogAlloc();
    ref_148 = msgShow(msg_13);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]What’s the matter, Amano-kun?
[tab]...[tatsuya] is talking... strange?
[tab]Huh? What’s so strange about it?
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_148);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_147);
    ref_14d = bustupFade(ref_145, rgb(0,0,0), 10);
    bustupWait(ref_14d);
    bustupFree(ref_145);
    unitRestoreFacing(katsuya);
    b(label_162);
  label_152:
    unitFacePlayer(katsuya);
    ref_153 = bustupLoad(bustup_21);
    bustupWait(ref_153);
    ref_155 = bustupAlloc(ref_153, left, rgb(0,0,0));
    bustupFade(ref_155, rgb(128,0,0), 30);
    ref_157 = dialogAlloc();
    ref_158 = msgShow(msg_14);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Police badge holder... 
[tab]Maybe this should have been returned... 
[tab]But we can’t go back now. Let’s move on.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_158);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_157);
    ref_15d = bustupFade(ref_155, rgb(0,0,0), 10);
    bustupWait(ref_15d);
    bustupFree(ref_155);
    unitRestoreFacing(katsuya);
    b(label_162);
  label_162:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1bf);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_1af);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_19f);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_18f);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_17f);
    unitFacePlayer(baofu);
    ref_170 = bustupLoad(bustup_2d);
    bustupWait(ref_170);
    ref_172 = bustupAlloc(ref_170, left, rgb(0,0,0));
    bustupFade(ref_172, rgb(128,0,0), 30);
    ref_174 = dialogAlloc();
    ref_175 = msgShow(msg_15);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Serizawa, if you think it’s a trap,
[tab]don’t suggest chasing [suou]!
[tab]...I don’t want any trouble, you hear me?
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_175);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_174);
    ref_17a = bustupFade(ref_172, rgb(0,0,0), 10);
    bustupWait(ref_17a);
    bustupFree(ref_172);
    unitRestoreFacing(baofu);
    b(label_1cf);
  label_17f:
    unitFacePlayer(baofu);
    ref_180 = bustupLoad(bustup_2d);
    bustupWait(ref_180);
    ref_182 = bustupAlloc(ref_180, left, rgb(0,0,0));
    bustupFade(ref_182, rgb(128,0,0), 30);
    ref_184 = dialogAlloc();
    ref_185 = msgShow(msg_16);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Can you imagine how many people fell
[tab]victim to the New World Order?
[tab]Don’t think we’re the only ones.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_185);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_184);
    ref_18a = bustupFade(ref_182, rgb(0,0,0), 10);
    bustupWait(ref_18a);
    bustupFree(ref_182);
    unitRestoreFacing(baofu);
    b(label_1cf);
  label_18f:
    unitFacePlayer(baofu);
    ref_190 = bustupLoad(bustup_31);
    bustupWait(ref_190);
    ref_192 = bustupAlloc(ref_190, left, rgb(0,0,0));
    bustupFade(ref_192, rgb(128,0,0), 30);
    ref_194 = dialogAlloc();
    ref_195 = msgShow(msg_17);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]People on the net generally tend to
[tab]like rumors. Nobody will leave such
[tab]a hot topic alone.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_195);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_194);
    ref_19a = bustupFade(ref_192, rgb(0,0,0), 10);
    bustupWait(ref_19a);
    bustupFree(ref_192);
    unitRestoreFacing(baofu);
    b(label_1cf);
  label_19f:
    unitFacePlayer(baofu);
    ref_1a0 = bustupLoad(bustup_2d);
    bustupWait(ref_1a0);
    ref_1a2 = bustupAlloc(ref_1a0, left, rgb(0,0,0));
    bustupFade(ref_1a2, rgb(128,0,0), 30);
    ref_1a4 = dialogAlloc();
    ref_1a5 = msgShow(msg_18);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]That brat, is he really gonna talk?
[tab]...Well, I guess he’s not the type to lie.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1a5);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1a4);
    ref_1aa = bustupFade(ref_1a2, rgb(0,0,0), 10);
    bustupWait(ref_1aa);
    bustupFree(ref_1a2);
    unitRestoreFacing(baofu);
    b(label_1cf);
  label_1af:
    unitFaceUnit(baofu, tatsuya);
    ref_1b0 = bustupLoad(bustup_2d);
    bustupWait(ref_1b0);
    ref_1b2 = bustupAlloc(ref_1b0, left, rgb(0,0,0));
    bustupFade(ref_1b2, rgb(128,0,0), 30);
    ref_1b4 = dialogAlloc();
    ref_1b5 = msgShow(msg_19);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Are you making an ass out of adults,
[tab][tatsuya]? That’s a BIG discrepancy.
[tab]You’re not... [delay(30)]an airhead, are you!?
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1b5);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1b4);
    ref_1ba = bustupFade(ref_1b2, rgb(0,0,0), 10);
    bustupWait(ref_1ba);
    bustupFree(ref_1b2);
    unitRestoreFacing(baofu);
    b(label_1cf);
  label_1bf:
    unitFacePlayer(baofu);
    ref_1c0 = bustupLoad(bustup_2d);
    bustupWait(ref_1c0);
    ref_1c2 = bustupAlloc(ref_1c0, left, rgb(0,0,0));
    bustupFade(ref_1c2, rgb(128,0,0), 30);
    ref_1c4 = dialogAlloc();
    ref_1c5 = msgShow(msg_20);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]I feel like having a drink. How about we
[tab]all go together after we finish this, Amano?
[tab]...Oops, can’t take [tatsuya].
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1c5);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1c4);
    ref_1ca = bustupFade(ref_1c2, rgb(0,0,0), 10);
    bustupWait(ref_1ca);
    bustupFree(ref_1c2);
    unitRestoreFacing(baofu);
    b(label_1cf);
  label_1cf:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_208);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_1f8);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_1e8);
    unitFacePlayer(nanjo);
    ref_1d9 = bustupLoad(bustup_36);
    bustupWait(ref_1d9);
    ref_1db = bustupAlloc(ref_1d9, left, rgb(0,0,0));
    bustupFade(ref_1db, rgb(128,0,0), 30);
    ref_1dd = dialogAlloc();
    ref_1de = msgShow(msg_21);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]Regardless of the situation, I think it is
[tab]too dangerous to use the same location for
[tab]the rendezvous.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_1de);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1dd);
    ref_1e3 = bustupFade(ref_1db, rgb(0,0,0), 10);
    bustupWait(ref_1e3);
    bustupFree(ref_1db);
    unitRestoreFacing(nanjo);
    b(label_218);
  label_1e8:
    unitFacePlayer(nanjo);
    ref_1e9 = bustupLoad(bustup_36);
    bustupWait(ref_1e9);
    ref_1eb = bustupAlloc(ref_1e9, left, rgb(0,0,0));
    bustupFade(ref_1eb, rgb(128,0,0), 30);
    ref_1ed = dialogAlloc();
    ref_1ee = msgShow(msg_22);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]Men are expected to exceed their fathers.
[tab]Regardless of the truth, the confrontation of
[tab]that boy and his father was inevitable.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_1ee);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1ed);
    ref_1f3 = bustupFade(ref_1eb, rgb(0,0,0), 10);
    bustupWait(ref_1f3);
    bustupFree(ref_1eb);
    unitRestoreFacing(nanjo);
    b(label_218);
  label_1f8:
    unitFacePlayer(nanjo);
    ref_1f9 = bustupLoad(bustup_36);
    bustupWait(ref_1f9);
    ref_1fb = bustupAlloc(ref_1f9, left, rgb(0,0,0));
    bustupFade(ref_1fb, rgb(128,0,0), 30);
    ref_1fd = dialogAlloc();
    ref_1fe = msgShow(msg_23);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]I would assume that the New World Order has
[tab]already manipulated the information over the net... 
[tab]so that everybody would talk about it.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_1fe);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_1fd);
    ref_203 = bustupFade(ref_1fb, rgb(0,0,0), 10);
    bustupWait(ref_203);
    bustupFree(ref_1fb);
    unitRestoreFacing(nanjo);
    b(label_218);
  label_208:
    unitFacePlayer(nanjo);
    ref_209 = bustupLoad(bustup_3b);
    bustupWait(ref_209);
    ref_20b = bustupAlloc(ref_209, left, rgb(0,0,0));
    bustupFade(ref_20b, rgb(128,0,0), 30);
    ref_20d = dialogAlloc();
    ref_20e = msgShow(msg_24);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]I think our paths are about to diverge.
[tab]...No, I just felt that way, for some reason.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_20e);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_20d);
    ref_213 = bustupFade(ref_20b, rgb(0,0,0), 10);
    bustupWait(ref_213);
    bustupFree(ref_20b);
    unitRestoreFacing(nanjo);
    b(label_218);
  label_218:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_251);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_241);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_231);
    unitFacePlayer(elly);
    ref_222 = bustupLoad(bustup_3d);
    bustupWait(ref_222);
    ref_224 = bustupAlloc(ref_222, left, rgb(0,0,0));
    bustupFade(ref_224, rgb(128,0,0), 30);
    ref_226 = dialogAlloc();
    ref_227 = msgShow(msg_25);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Whether it’s a trap or not,
[tab]isn’t it dangerous to meet at the
[tab]same place again?
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_227);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_226);
    ref_22c = bustupFade(ref_224, rgb(0,0,0), 10);
    bustupWait(ref_22c);
    bustupFree(ref_224);
    unitRestoreFacing(elly);
    b(label_261);
  label_231:
    unitFacePlayer(elly);
    ref_232 = bustupLoad(bustup_3d);
    bustupWait(ref_232);
    ref_234 = bustupAlloc(ref_232, left, rgb(0,0,0));
    bustupFade(ref_234, rgb(128,0,0), 30);
    ref_236 = dialogAlloc();
    ref_237 = msgShow(msg_26);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]The Chief was also a victim... With his burden,
[tab]his life must have been very painful. Death
[tab]won’t erase his crime, but... he was honorable.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_237);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_236);
    ref_23c = bustupFade(ref_234, rgb(0,0,0), 10);
    bustupWait(ref_23c);
    bustupFree(ref_234);
    unitRestoreFacing(elly);
    b(label_261);
  label_241:
    unitFacePlayer(elly);
    ref_242 = bustupLoad(bustup_3d);
    bustupWait(ref_242);
    ref_244 = bustupAlloc(ref_242, left, rgb(0,0,0));
    bustupFade(ref_244, rgb(128,0,0), 30);
    ref_246 = dialogAlloc();
    ref_247 = msgShow(msg_27);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]I’m sure the New World Order is cautious
[tab]enough to have information manipulated on
[tab]the network. This is part of their plan.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_247);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_246);
    ref_24c = bustupFade(ref_244, rgb(0,0,0), 10);
    bustupWait(ref_24c);
    bustupFree(ref_244);
    unitRestoreFacing(elly);
    b(label_261);
  label_251:
    unitFacePlayer(elly);
    ref_252 = bustupLoad(bustup_42);
    bustupWait(ref_252);
    ref_254 = bustupAlloc(ref_252, left, rgb(0,0,0));
    bustupFade(ref_254, rgb(128,0,0), 30);
    ref_256 = dialogAlloc();
    ref_257 = msgShow(msg_28);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]I see a parting in my future...
[tab]I think our bond right now is only temporary.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_257);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_256);
    ref_25c = bustupFade(ref_254, rgb(0,0,0), 10);
    bustupWait(ref_25c);
    bustupFree(ref_254);
    unitRestoreFacing(elly);
    b(label_261);
  label_261:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_28b);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_27b);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_26a);
  label_26a:
    unitFacePlayer(tatsuya);
    ref_26b = bustupLoad(bustup_b);
    bustupWait(ref_26b);
    ref_26d = bustupAlloc(ref_26b, right, rgb(0,0,0));
    bustupFade(ref_26d, rgb(128,0,0), 30);
    bustupFlip(ref_26d, true);
    ref_270 = dialogAlloc();
    ref_271 = msgShow(msg_29);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]The truth cannot be obtained here.
[tab]Let’s go...
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_271);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_270);
    ref_276 = bustupFade(ref_26d, rgb(0,0,0), 10);
    bustupWait(ref_276);
    bustupFree(ref_26d);
    unitRestoreFacing(tatsuya);
    b(label_29b);
  label_27b:
    unitFacePlayer(tatsuya);
    ref_27c = bustupLoad(bustup_b);
    bustupWait(ref_27c);
    ref_27e = bustupAlloc(ref_27c, left, rgb(0,0,0));
    bustupFade(ref_27e, rgb(128,0,0), 30);
    ref_280 = dialogAlloc();
    ref_281 = msgShow(msg_30);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]There’s not much difference between the two
[tab]worlds. If anything... I guess the existence of
[tab]the New World Order.
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_281);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_280);
    ref_286 = bustupFade(ref_27e, rgb(0,0,0), 10);
    bustupWait(ref_286);
    bustupFree(ref_27e);
    unitRestoreFacing(tatsuya);
    b(label_29b);
  label_28b:
    unitFacePlayer(tatsuya);
    ref_28c = bustupLoad(bustup_b);
    bustupWait(ref_28c);
    ref_28e = bustupAlloc(ref_28c, left, rgb(0,0,0));
    bustupFade(ref_28e, rgb(128,0,0), 30);
    ref_290 = dialogAlloc();
    ref_291 = msgShow(msg_31);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]I’m not going to look away from reality
[tab]anymore... Let’s go, Maya-nee.
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_291);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_290);
    ref_296 = bustupFade(ref_28e, rgb(0,0,0), 10);
    bustupWait(ref_296);
    bustupFree(ref_28e);
    unitRestoreFacing(tatsuya);
    b(label_29b);
  label_29b:
    controlEnable();
}

function MAN1()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_2cd);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2c4);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_2b8);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_2af);
    unitFacePlayer(npc1);
    ref_2a7 = dialogAlloc();
    ref_2a8 = msgShow(msg_32);
/***************************************
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]There are many bulletin boards on the net,
[tab]but the missing persons board is very hot.
[tab]...Yeah, the number is skyrocketing.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2a8);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2a7);
    unitRestoreFacing(npc1);
    b(label_2d6);
  label_2af:
    unitFacePlayer(npc1);
    ref_2b0 = dialogAlloc();
    ref_2b1 = msgShow(msg_33);
/***************************************
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Ameno Torifune, the riddle to be solved! 
[tab]So this is why the construction was delayed...
[tab]Yeah, I’m really into this kind of stuff.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_27, 1);
    wait(ref_2b1);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2b0);
    unitRestoreFacing(npc1);
    b(label_2d6);
  label_2b8:
    unitFacePlayer(npc1);
    ref_2b9 = dialogAlloc();
    ref_2ba = msgShow(msg_34);
/***************************************
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Ameno Torifune... How’s it like inside?
[tab]I wonder if I should sneak into the
[tab]subway construction site...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2ba);
    ref_2bd = msgShow(msg_35);
/***************************************
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]...But I heard a rumor that you can’t come
[tab]back alive. Hmm... What should I do...?
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2bd);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2b9);
    unitRestoreFacing(npc1);
    b(label_2d6);
  label_2c4:
    unitFacePlayer(npc1);
    ref_2c5 = dialogAlloc();
    ref_2c6 = msgShow(msg_36);
/***************************************
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I’m on top of the Ameno Torifune? I’m glad,
[tab]but scared at the same time!! The dragon is
[tab]coming here? The axis, the earth’s axis...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2c6);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2c5);
    unitRestoreFacing(npc1);
    b(label_2d6);
  label_2cd:
    unitFacePlayer(npc1);
    ref_2ce = dialogAlloc();
    ref_2cf = msgShow(msg_37);
/***************************************
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I’m moved... I learned how to use a computer,
[tab]and the true ancient history has been
[tab]revealed. Now what? ...My family, I guess.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2cf);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2ce);
    unitRestoreFacing(npc1);
    b(label_2d6);
  label_2d6:
    controlEnable();
}

function MAN2()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_300);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2f7);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_2eb);
    unitFacePlayer(npc2);
    ref_2e0 = dialogAlloc();
    ref_2e1 = msgShow(msg_38);
/***************************************
[color(yellow)]Fat Guy[color(white)]
[tab]Hey, don’t bother me! I’m trying to
[tab]drop a line to the Joker-sightings
[tab]page on the internet right now.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_26, 1);
    wait(ref_2e1);
    ref_2e4 = msgShow(msg_39);
/***************************************
[color(yellow)]Fat Guy[color(white)]
[tab]Let’s see... "Uh-huh, I saw him at the
[tab]TV station. That was, like, so cool!"
[tab]Hehe... Enter girl mode.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_2e4);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2e0);
    unitRestoreFacing(npc2);
    b(label_309);
  label_2eb:
    unitFacePlayer(npc2);
    ref_2ec = dialogAlloc();
    ref_2ed = msgShow(msg_40);
/***************************************
[color(yellow)]Fat Guy[color(white)]
[tab]The day New World Order was on the news,
[tab]only 5 sites were up on the net...
[tab]But now, there are over 30000!!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_2ed);
    ref_2f0 = msgShow(msg_41);
/***************************************
[color(yellow)]Fat Guy[color(white)]
[tab]It’s increasing every day, along with
[tab]the Pole Shift and Ameno Torifune.
[tab]Figures, it’s the buzz of the moment!!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_2f0);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2ec);
    unitRestoreFacing(npc2);
    b(label_309);
  label_2f7:
    unitFacePlayer(npc2);
    ref_2f8 = dialogAlloc();
    ref_2f9 = msgShow(msg_42);
/***************************************
[color(yellow)]Fat Guy[color(white)]
[tab]If you’re on the net, everything feels like
[tab]someone else’s problem. I was just having fun
[tab]at first, but I didn’t think this would happen!!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_25, 1);
    wait(ref_2f9);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_2f8);
    unitRestoreFacing(npc2);
    b(label_309);
  label_300:
    unitFacePlayer(npc2);
    ref_301 = dialogAlloc();
    ref_302 = msgShow(msg_43);
/***************************************
[color(yellow)]Fat Guy[color(white)]
[tab]Today’s lesson!! How to distinguish accurate
[tab]information from bad ones! ...Do you think
[tab]the internet is still functioning?
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_302);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_301);
    unitRestoreFacing(npc2);
    b(label_309);
  label_309:
    controlEnable();
}

function PCHIT()
{
    controlDisable();
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 9, false);
    screenFadeOuter(rgb(255,255,255), 9, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_312 = cameraRotateTo(5, 10);
    playerConvertToUnit(maya, sprite_0, east);
    playerHide();
    ref_315 = cameraMoveTo(636, 0, -1107, 10);
    unitMove(maya, 805, -950, face_north, fastest);
    unitWait(maya);
    wait(ref_315);
    wait(ref_312);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_1);
    unitFace(maya, east);
    unitAnimationPlay(maya, animation_12, 1);
    unitFace(maya, east);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 9, true);
    screenFadeOuter(rgb(0,0,0), 9, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    delayClear();
    delayWait(30);
    sndMusicPlay(sound_3079, 127);
    ref_327 = dialogAlloc();
    ref_328 = msgShow(msg_44);
/***************************************
[color(yellow)]Computer[color(white)]
[tab]This homepage is currently shut down
[tab]due to host server error... 
[tab]The rumor bulletin board is still operational.
[wait][clear]
***************************************/
    wait(ref_328);
    dialogFree(ref_327);
    delayClear();
    delayWait(30);
    ref_32d = dialogChoiceAlloc();
    choiceSetResult(1);
    op_105(1);
    ref_330 = msgShow(msg_45);
/***************************************
[tab]Please select from the menu.
[choice(2)]Take a look at the bulletin board
Quit
[end_choice][clear]
***************************************/
    wait(ref_330);
    dialogFree(ref_32d);
    choiceGetResult(var_0);
    bne(var_0, 0, label_337);
    b(label_346);
    b(label_33a);
  label_337:
    bne(var_0, 1, label_33a);
    b(label_444);
    b(label_33a);
  label_33a:
    choiceSetResult(1);
    op_105(1);
    ref_33c = dialogChoiceAlloc();
    ref_33d = msgShow(msg_46);
/***************************************
[tab]Please select from the menu.
[choice(2)]Take a look at the bulletin board
Quit
[end_choice][clear]
***************************************/
    wait(ref_33d);
    dialogFree(ref_33c);
    choiceGetResult(var_0);
    bne(var_0, 0, label_343);
    b(label_346);
  label_343:
    bne(var_0, 1, label_346);
    b(label_444);
    b(label_346);
  label_346:
    bitGet(var_0, EBIT_E0016);
    bne(var_0, 0, label_349);
    b(label_35c);
  label_349:
    bne(var_0, 1, label_35c);
    bitGet(var_0, MBIT_KI_ROSADEF);
    bne(var_0, 0, label_34e);
    b(label_414);
    b(label_35b);
  label_34e:
    bne(var_0, 1, label_35b);
    bitGet(var_0, LBIT_0001);
    bne(var_0, 0, label_352);
    b(label_35a);
  label_352:
    bne(var_0, 1, label_35a);
    bitGet(var_0, LBIT_0006);
    bne(var_0, 0, label_357);
    b(label_414);
    b(label_359);
  label_357:
    bne(var_0, 1, label_359);
    b(label_359);
  label_359:
    b(label_35a);
  label_35a:
    b(label_35b);
  label_35b:
    b(label_35c);
  label_35c:
    bitGet(var_0, EBIT_E001F);
    bne(var_0, 0, label_35f);
    b(label_377);
  label_35f:
    bne(var_0, 1, label_377);
    bitGet(var_0, MBIT_DBATOLU);
    bne(var_0, 0, label_374);
    bitGet(var_0, MBIT_KI_BATOLUBOUGU);
    bne(var_0, 0, label_366);
    b(label_41c);
    b(label_373);
  label_366:
    bne(var_0, 1, label_373);
    bitGet(var_0, LBIT_0002);
    bne(var_0, 0, label_36a);
    b(label_372);
  label_36a:
    bne(var_0, 1, label_372);
    bitGet(var_0, LBIT_0007);
    bne(var_0, 0, label_36f);
    b(label_41c);
    b(label_371);
  label_36f:
    bne(var_0, 1, label_371);
    b(label_371);
  label_371:
    b(label_372);
  label_372:
    b(label_373);
  label_373:
    b(label_376);
  label_374:
    bne(var_0, 1, label_376);
    b(label_376);
  label_376:
    b(label_377);
  label_377:
    bitGet(var_0, EBIT_E0038);
    bne(var_0, 0, label_37a);
    b(label_392);
  label_37a:
    bne(var_0, 1, label_392);
    bitGet(var_0, MBIT_KE_MU);
    bne(var_0, 0, label_38f);
    bitGet(var_0, MBIT_KI_MUSLOT);
    bne(var_0, 0, label_381);
    b(label_424);
    b(label_38e);
  label_381:
    bne(var_0, 1, label_38e);
    bitGet(var_0, LBIT_0003);
    bne(var_0, 0, label_385);
    b(label_38d);
  label_385:
    bne(var_0, 1, label_38d);
    bitGet(var_0, LBIT_0008);
    bne(var_0, 0, label_38a);
    b(label_424);
    b(label_38c);
  label_38a:
    bne(var_0, 1, label_38c);
    b(label_38c);
  label_38c:
    b(label_38d);
  label_38d:
    b(label_38e);
  label_38e:
    b(label_391);
  label_38f:
    bne(var_0, 1, label_391);
    b(label_391);
  label_391:
    b(label_392);
  label_392:
    bitGet(var_0, EBIT_E0043);
    bitGet(var_1, MBIT_DMAGICKCADE);
    bitGet(var_2, MBIT_DMAGICK);
    add(var_0, var_0, var_1);
    add(var_0, var_0, var_2);
    boutrange(var_0, 0, 2, label_399);
    b(label_3b1);
  label_399:
    bne(var_0, 3, label_3b1);
    bitGet(var_0, MBIT_DPELPEL);
    bne(var_0, 0, label_3ae);
    bitGet(var_0, MBIT_KI_PELPELITEM);
    bne(var_0, 0, label_3a0);
    b(label_42c);
    b(label_3ad);
  label_3a0:
    bne(var_0, 1, label_3ad);
    bitGet(var_0, LBIT_0004);
    bne(var_0, 0, label_3a4);
    b(label_3ac);
  label_3a4:
    bne(var_0, 1, label_3ac);
    bitGet(var_0, LBIT_0009);
    bne(var_0, 0, label_3a9);
    b(label_42c);
    b(label_3ab);
  label_3a9:
    bne(var_0, 1, label_3ab);
    b(label_3ab);
  label_3ab:
    b(label_3ac);
  label_3ac:
    b(label_3ad);
  label_3ad:
    b(label_3b0);
  label_3ae:
    bne(var_0, 1, label_3b0);
    b(label_3b0);
  label_3b0:
    b(label_3b1);
  label_3b1:
    bitGet(var_0, EBIT_E0045);
    bne(var_0, 0, label_3b4);
    b(label_3cc);
  label_3b4:
    bne(var_0, 1, label_3cc);
    bitGet(var_0, MBIT_KE_ROSADEF);
    bne(var_0, 0, label_3b8);
    b(label_3cb);
  label_3b8:
    bne(var_0, 1, label_3cb);
    bitGet(var_0, MBIT_KI_ROSAHENNI);
    bne(var_0, 0, label_3bd);
    b(label_434);
    b(label_3ca);
  label_3bd:
    bne(var_0, 1, label_3ca);
    bitGet(var_0, LBIT_0005);
    bne(var_0, 0, label_3c1);
    b(label_3c9);
  label_3c1:
    bne(var_0, 1, label_3c9);
    bitGet(var_0, LBIT_0010);
    bne(var_0, 0, label_3c6);
    b(label_434);
    b(label_3c8);
  label_3c6:
    bne(var_0, 1, label_3c8);
    b(label_3c8);
  label_3c8:
    b(label_3c9);
  label_3c9:
    b(label_3ca);
  label_3ca:
    b(label_3cb);
  label_3cb:
    b(label_3cc);
  label_3cc:
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_3cf);
    b(label_3e2);
  label_3cf:
    bne(var_0, 1, label_3e2);
    bitGet(var_0, MBIT_KI_CLEAOBA);
    bne(var_0, 0, label_3d4);
    b(label_43c);
    b(label_3e1);
  label_3d4:
    bne(var_0, 1, label_3e1);
    bitGet(var_0, LBIT_0012);
    bne(var_0, 0, label_3d8);
    b(label_3e0);
  label_3d8:
    bne(var_0, 1, label_3e0);
    bitGet(var_0, LBIT_0011);
    bne(var_0, 0, label_3dd);
    b(label_43c);
    b(label_3df);
  label_3dd:
    bne(var_0, 1, label_3df);
    b(label_3df);
  label_3df:
    b(label_3e0);
  label_3e0:
    b(label_3e1);
  label_3e1:
    b(label_3e2);
  label_3e2:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_409);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_3fe);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_3f3);
    ref_3e8 = dialogAlloc();
    ref_3e9 = msgShow(msg_47);
/***************************************
[color(yellow)]Posted by: Sumaru King[color(white)]
[tab]There’s news of the ruins that was discovered
[tab]at a subway construction site, but my uncle
[tab]said that it’s a lie to conceal the delay.
[wait][clear]
***************************************/
    wait(ref_3e9);
    dialogFree(ref_3e8);
    bitClear(LBIT_0006);
    bitClear(LBIT_0007);
    bitClear(LBIT_0008);
    bitClear(LBIT_0009);
    bitClear(LBIT_0010);
    bitClear(LBIT_0011);
    b(label_33a);
  label_3f3:
    ref_3f3 = dialogAlloc();
    ref_3f4 = msgShow(msg_48);
/***************************************
[color(yellow)]Posted by: Well Informed[color(white)]
[tab]Did you know that Sumaru TV was the first
[tab]to introduce Wang Long fortunes? They have
[tab]connections to the New World Order.
[wait][clear]
***************************************/
    wait(ref_3f4);
    dialogFree(ref_3f3);
    bitClear(LBIT_0006);
    bitClear(LBIT_0007);
    bitClear(LBIT_0008);
    bitClear(LBIT_0009);
    bitClear(LBIT_0010);
    bitClear(LBIT_0011);
    b(label_33a);
  label_3fe:
    ref_3fe = dialogAlloc();
    ref_3ff = msgShow(msg_49);
/***************************************
[color(yellow)]Posted by: Earth to Sumaru[color(white)]
[tab]People in Sumaru City, can you see this
[tab]message? Are you really up in the sky?
[tab]...I wonder if the phone line’s still working.
[wait][clear]
***************************************/
    wait(ref_3ff);
    dialogFree(ref_3fe);
    bitClear(LBIT_0006);
    bitClear(LBIT_0007);
    bitClear(LBIT_0008);
    bitClear(LBIT_0009);
    bitClear(LBIT_0010);
    bitClear(LBIT_0011);
    b(label_33a);
  label_409:
    ref_409 = dialogAlloc();
    ref_40a = msgShow(msg_50);
/***************************************
[color(yellow)]Posted by: Sumaru King[color(white)]
[tab]The dragon disappeared because the head of
[tab]the New World Order was assassinated
[tab](I heard from my friend’s friend’s cousin).
[wait][clear]
***************************************/
    wait(ref_40a);
    dialogFree(ref_409);
    bitClear(LBIT_0006);
    bitClear(LBIT_0007);
    bitClear(LBIT_0008);
    bitClear(LBIT_0009);
    bitClear(LBIT_0010);
    bitClear(LBIT_0011);
    b(label_33a);
  label_414:
    ref_414 = dialogAlloc();
    ref_415 = msgShow(msg_51);
/***************************************
[color(yellow)]Posted by: This is true, too![color(white)]
[tab]This fall, [color(orange)]real armor[color(white)] will be sold at
[tab][color(orange)]Rosa Candida[color(white)]. Tacky-looking
[tab]armor will be in stock.
[wait][clear]
***************************************/
    wait(ref_415);
    dialogFree(ref_414);
    bitSet(MBIT_KI_ROSADEF);
    bitSet(LBIT_0006);
    bitSet(LBIT_0001);
    b(label_33a);
  label_41c:
    ref_41c = dialogAlloc();
    ref_41d = msgShow(msg_52);
/***************************************
[color(yellow)]Posted by: Anonymous[color(white)]
[tab]Do you know [color(orange)]Battle Master[color(white)] mag?
[tab][color(orange)]Real armor[color(white)] are sweepstakes prizes...
[tab]Whoever has any details, please respond.
[wait][clear]
***************************************/
    wait(ref_41d);
    dialogFree(ref_41c);
    bitSet(MBIT_KI_BATOLUBOUGU);
    bitSet(LBIT_0007);
    bitSet(LBIT_0002);
    b(label_33a);
  label_424:
    ref_424 = dialogAlloc();
    ref_425 = msgShow(msg_53);
/***************************************
[color(yellow)]Posted by: Sumaru King[color(white)]
[tab][color(orange)]Mu Continent[color(white)] is rumored to be a
[tab]real [color(orange)]casino[color(white)] (heard from a friend).
[tab]I heard the [color(orange)]slots pay out liberally[color(white)]...
[wait][clear]
***************************************/
    wait(ref_425);
    dialogFree(ref_424);
    bitSet(MBIT_KI_MUSLOT);
    bitSet(LBIT_0008);
    bitSet(LBIT_0003);
    b(label_33a);
  label_42c:
    ref_42c = dialogAlloc();
    ref_42d = msgShow(msg_54);
/***************************************
[color(yellow)]Posted by: KAY[color(white)]
[tab]Found the magazine that’s giving out [color(orange)]special
[tab]items[color(white)]! It’s called [color(orange)]Fantasy World[color(white)]. But, you must
[tab]enter the sweepstakes to win a prize.
[wait][clear]
***************************************/
    wait(ref_42d);
    dialogFree(ref_42c);
    bitSet(MBIT_KI_PELPELITEM);
    bitSet(LBIT_0009);
    bitSet(LBIT_0004);
    b(label_33a);
  label_434:
    ref_434 = dialogAlloc();
    ref_435 = msgShow(msg_55);
/***************************************
[color(yellow)]Posted by: Is this true?[color(white)]
[tab]I heard the Saleswoman at [color(orange)]Rosa Candida[color(white)] was
[tab][color(orange)]engulfed by a wave[color(white)] on vacation... 
[tab]It’s unconfirmed, but something must’ve happened!
[wait][clear]
***************************************/
    wait(ref_435);
    dialogFree(ref_434);
    bitSet(MBIT_KI_ROSAHENNI);
    bitSet(LBIT_0010);
    bitSet(LBIT_0005);
    b(label_33a);
  label_43c:
    ref_43c = dialogAlloc();
    ref_43d = msgShow(msg_56);
/***************************************
[color(yellow)]Posted by: This is true![color(white)]
[tab]I heard that [color(orange)]Clair De Lune reopened business[color(white)]
[tab][color(orange)]in Aoba[color(white)]. It didn’t share its fate with
[tab]the Narumi Ward!
[wait][clear]
***************************************/
    wait(ref_43d);
    dialogFree(ref_43c);
    bitSet(MBIT_KI_CLEAOBA);
    bitSet(LBIT_0011);
    bitSet(LBIT_0012);
    b(label_33a);
  label_444:
    ref_444 = dialogAlloc();
    ref_445 = msgShow(msg_57);
/***************************************
[color(yellow)]Computer[color(white)]
[tab]Preparing to shut down. Please wait.
[tab][delay(15)]. . . [delay(15)]. . . [delay(15)]. . .[delay(15)]
[tab]It is now safe to turn off the computer.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_445);
    dialogFree(ref_444);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 9, false);
    screenFadeOuter(rgb(255,255,255), 9, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    unitSpriteClear(maya);
    unitSpriteSet(maya, sprite_0);
    unitMove(maya, 915, -950, face_south, fastest);
    unitWait(maya);
    ref_453 = cameraLookAtUnit(maya, 0, 10);
    wait(ref_453);
    unitDespawn(maya, none);
    playerInit(southwest);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 9, true);
    screenFadeOuter(rgb(0,0,0), 9, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function GIRL()
{
    controlDisable();
    bitGet(var_0, MBIT_W_HATUMANIA);
    bne(var_0, 0, label_464);
    b(label_467);
    b(label_467);
  label_464:
    boutrange(var_0, 1, 2, label_467);
    b(label_476);
    b(label_467);
  label_467:
    ref_467 = textInputInit();
    wait(ref_467);
    unitFacePlayer(unit_58);
    ref_46a = dialogAlloc();
    ref_46b = msgShow(msg_58);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hey hey, onee-san... What dragon are you? What?
[tab]You don’t know?! We’re talking Wang Long
[tab]fortunes here! You’ve been missing out, girl!!
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_46b);
    unitAnimationPlay(unit_58, animation_0, 1);
    ref_46f = msgShow(msg_59);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Very well... Then allow me, the master
[tab]of Wang Long, to tell your fortune!
[tab](ahem) What month were you born?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_46f);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_46a);
    bitSet(MBIT_W_HATUMANIA);
    b(label_486);
  label_476:
    ref_476 = textInputInit();
    wait(ref_476);
    unitFacePlayer(unit_58);
    ref_479 = dialogAlloc();
    ref_47a = msgShow(msg_60);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Ah, onee-san! Wish to have your fortune told? Um...
[tab]Things change, and Wang Long’s no exception!
[tab]Results may differ from before... Okay?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_47a);
    unitAnimationPlay(unit_58, animation_0, 1);
    ref_47e = msgShow(msg_61);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Oh, really... Then allow me, the master
[tab]of Wang Long, to tell your fortune!
[tab](ahem) What month were you born?
[sync][wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    sync();
    wait(ref_47e);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_479);
  label_484:
    delayClear();
    delayWait(30);
  label_486:
    ref_486 = textInputPrompt();
    wait(ref_486);
    textInputCompare(msg_62, var_a);
    bne(var_a, 0, label_491);
    ref_48a = dialogAlloc();
    ref_48b = msgShow(msg_63);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Huh? ...What? I can’t tell your
[tab]fortune unless you tell me! 
[tab]Once again... What month were you born?
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_48b);
    dialogFree(ref_48a);
    b(label_484);
    b(label_504);
  label_491:
    boutrange(var_a, 1, 5, label_49a);
    ref_492 = dialogAlloc();
    ref_493 = msgShow(msg_64);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]January is the Yellow Dragon,
[tab]which protects balance.
[wait][clear]
***************************************/
    wait(ref_493);
    ref_495 = msgShow(msg_65);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are responsible and patient.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_495);
    dialogFree(ref_492);
    b(label_504);
  label_49a:
    boutrange(var_a, 6, 10, label_4a3);
    ref_49b = dialogAlloc();
    ref_49c = msgShow(msg_66);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]February is the Blue Dragon,
[tab]which prefers reform.
[wait][clear]
***************************************/
    wait(ref_49c);
    ref_49e = msgShow(msg_67);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are intellectual and calm.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_49e);
    dialogFree(ref_49b);
    b(label_504);
  label_4a3:
    boutrange(var_a, 11, 15, label_4ac);
    ref_4a4 = dialogAlloc();
    ref_4a5 = msgShow(msg_68);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]March is the White Dragon,
[tab]which rules the emotion.
[wait][clear]
***************************************/
    wait(ref_4a5);
    ref_4a7 = msgShow(msg_69);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are warm-hearted and easily moved to
[tab]tears. Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4a7);
    dialogFree(ref_4a4);
    b(label_504);
  label_4ac:
    boutrange(var_a, 16, 22, label_4b5);
    ref_4ad = dialogAlloc();
    ref_4ae = msgShow(msg_70);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]April is the Scarlet Dragon,
[tab]which leads battle.
[wait][clear]
***************************************/
    wait(ref_4ae);
    ref_4b0 = msgShow(msg_71);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are rash, hasty, and stubborn.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4b0);
    dialogFree(ref_4ad);
    b(label_504);
  label_4b5:
    boutrange(var_a, 23, 27, label_4be);
    ref_4b6 = dialogAlloc();
    ref_4b7 = msgShow(msg_72);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]May is the Gold Dragon,
[tab]which protects the world.
[wait][clear]
***************************************/
    wait(ref_4b7);
    ref_4b9 = msgShow(msg_73);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are realistic and reasonable.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4b9);
    dialogFree(ref_4b6);
    b(label_504);
  label_4be:
    boutrange(var_a, 28, 32, label_4c7);
    ref_4bf = dialogAlloc();
    ref_4c0 = msgShow(msg_74);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]June is the Navy Blue Dragon,
[tab]which gives rise to liberation.
[wait][clear]
***************************************/
    wait(ref_4c0);
    ref_4c2 = msgShow(msg_75);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are lively and witty.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4c2);
    dialogFree(ref_4bf);
    b(label_504);
  label_4c7:
    boutrange(var_a, 33, 39, label_4d0);
    ref_4c8 = dialogAlloc();
    ref_4c9 = msgShow(msg_76);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]July is the Light Dragon,
[tab]which values morals.
[wait][clear]
***************************************/
    wait(ref_4c9);
    ref_4cb = msgShow(msg_77);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are sensitive and caring.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4cb);
    dialogFree(ref_4c8);
    b(label_504);
  label_4d0:
    boutrange(var_a, 40, 44, label_4d9);
    ref_4d1 = dialogAlloc();
    ref_4d2 = msgShow(msg_78);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]August is the Red Dragon,
[tab]which rules passion.
[wait][clear]
***************************************/
    wait(ref_4d2);
    ref_4d4 = msgShow(msg_79);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are confident and adventurous.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4d4);
    dialogFree(ref_4d1);
    b(label_504);
  label_4d9:
    boutrange(var_a, 45, 51, label_4e2);
    ref_4da = dialogAlloc();
    ref_4db = msgShow(msg_80);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]September is the Black Dragon,
[tab]which grants wisdom.
[wait][clear]
***************************************/
    wait(ref_4db);
    ref_4dd = msgShow(msg_81);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are earnest and enthusiastic.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4dd);
    dialogFree(ref_4da);
    b(label_504);
  label_4e2:
    boutrange(var_a, 51, 56, label_4eb);
    ref_4e3 = dialogAlloc();
    ref_4e4 = msgShow(msg_82);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]October is the Silver Dragon,
[tab]which protects moderation.
[wait][clear]
***************************************/
    wait(ref_4e4);
    ref_4e6 = msgShow(msg_83);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are artistic and pacifistic.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4e6);
    dialogFree(ref_4e3);
    b(label_504);
  label_4eb:
    boutrange(var_a, 57, 61, label_4f4);
    ref_4ec = dialogAlloc();
    ref_4ed = msgShow(msg_84);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]November is the Moon Dragon,
[tab]which creates mysticism.
[wait][clear]
***************************************/
    wait(ref_4ed);
    ref_4ef = msgShow(msg_85);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You trap passion inside your heart.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4ef);
    dialogFree(ref_4ec);
    b(label_504);
  label_4f4:
    boutrange(var_a, 62, 66, label_4fd);
    ref_4f5 = dialogAlloc();
    ref_4f6 = msgShow(msg_86);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Hmmm... The guardian dragon for
[tab]December is the Purple Dragon,
[tab]which honors justice.
[wait][clear]
***************************************/
    wait(ref_4f6);
    ref_4f8 = msgShow(msg_87);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]You are honest and wish to be free.
[tab]Your fortune for today is...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4f8);
    dialogFree(ref_4f5);
    b(label_504);
  label_4fd:
    boutrange(var_a, 67, 68, label_434);
    ref_4fe = dialogAlloc();
    ref_4ff = msgShow(msg_88);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]. . . ! ! ! ! ! ! !
[wait][clear]
***************************************/
    wait(ref_4ff);
    bitSet(LBIT_0013);
    dialogFree(ref_4fe);
    b(label_504);
  label_504:
    delayClear();
    delayWait(45);
    bitGet(var_0, LBIT_0013);
    bnz(var_0, label_54c);
    b(label_509);
  label_509:
    li(var_b, 0);
    rand(var_b, 12);
    ref_50b = dialogAlloc();
    bne(var_b, 0, label_511);
    ref_50d = msgShow(msg_89);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Lively dragon and Fukugi offer you their
[tab]divine protection. Don’t be afraid to
[tab]challenge! Black Dragon brings even more luck.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_50d);
    b(label_547);
  label_511:
    bne(var_b, 1, label_516);
    ref_512 = msgShow(msg_90);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]A lively dragon’s love makes the day nice...
[tab]But, stay healthy! Harmony with a White
[tab]Dragon will aid your studies and job.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_512);
    b(label_547);
  label_516:
    bne(var_b, 3, label_51b);
    ref_517 = msgShow(msg_91);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]The lively dragon’s support will make you
[tab]happy. But, effort brings true happiness...
[tab]Another dragon may strike at school or work.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_517);
    b(label_547);
  label_51b:
    bne(var_b, 4, label_520);
    ref_51c = msgShow(msg_92);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]The harmony of 3 dragons will increase your
[tab]luck... So act positively! A skull key chain
[tab]means a chance of an encounter.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_51c);
    b(label_547);
  label_520:
    bne(var_b, 5, label_525);
    ref_521 = msgShow(msg_93);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Lively dragon’s breath will calm the day.
[tab]But, beware of the Blue Dragon...
[tab]Stating your likes and dislikes is good!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_521);
    b(label_547);
  label_525:
    bne(var_b, 6, label_52a);
    ref_526 = msgShow(msg_94);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]A dragon’s tempting whisper confuses you...
[tab]Work hard at home instead of going out.
[tab]The scent of lemongrass is a key to peace.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_526);
    b(label_547);
  label_52a:
    bne(var_b, 7, label_52f);
    ref_52b = msgShow(msg_95);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]A so-so day is drawn into a dragon’s plan,
[tab]but a lively dragon summoned during sports
[tab]or gambling will make your day great!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_52b);
    b(label_547);
  label_52f:
    bne(var_b, 8, label_534);
    ref_530 = msgShow(msg_96);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]The death dragon haunts your day...
[tab]A different dragon can make it better. 
[tab]Be cautious around school... RUN past it!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_530);
    b(label_547);
  label_534:
    bne(var_b, 9, label_539);
    ref_535 = msgShow(msg_97);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]A grudging, defiant dragon hurts your day...
[tab]All will result unfavorably, but a call from
[tab]a Gold Dragon may turn your luck.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_535);
    b(label_547);
  label_539:
    bne(var_b, 10, label_53e);
    ref_53a = msgShow(msg_98);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]The death dragon’s anger will sadden your
[tab]day. Not even an opposing dragon can help.
[tab]Jealousy will worsen the situation!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_53a);
    b(label_547);
  label_53e:
    bne(var_b, 11, label_543);
    ref_53f = msgShow(msg_99);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]The death dragon’s love will trouble you...
[tab]All wishes will be reversed. Do nothing...
[tab]Happiness may be not having to do anything.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_53f);
    b(label_547);
  label_543:
    ref_543 = msgShow(msg_100);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]The curse of Joka, the death dragon, brings
[tab]a bad day. All 12 dragons oppose you.
[tab]I won’t say anything... Just stay home...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_543);
    b(label_547);
  label_547:
    ref_547 = msgShow(msg_101);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]...How’s that?
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_547);
    dialogFree(ref_50b);
    b(label_561);
  label_54c:
    bitGet(var_0, MBIT_W_PASS);
    bne(var_0, 0, label_559);
    ref_54e = dialogAlloc();
    ref_54f = msgShow(msg_102);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Keh, Keh, Keh...
[tab]You will regret what you have said.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_6, 1);
    wait(ref_54f);
    ref_552 = msgShow(msg_103);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]Don’t get too involved.
[tab]...Understand? This is a warning!
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_19, 1);
    wait(ref_552);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_54e);
    bitSet(MBIT_W_PASS);
    b(label_561);
  label_559:
    bne(var_0, 1, label_561);
    ref_55a = dialogAlloc();
    ref_55b = msgShow(msg_104);
/***************************************
[color(yellow)]Wang Long Fortune Maniac[color(white)]
[tab]...I warned you...
[tab]Stop your nonsense!!
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_19, 1);
    wait(ref_55b);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_55a);
    b(label_561);
  label_561:
    bitClear(LBIT_0013);
    unitRestoreFacing(unit_58);
    controlEnable();
}

function SHOP()
{
    controlDisable();
    ref_566 = shopOverlayInit();
    unitFacePlayer(shopkeeper);
    bitGet(var_0, MBIT_AIS_12);
    bne(var_0, 0, label_56c);
    b(label_56f);
    b(label_56f);
  label_56c:
    bne(var_0, 1, label_56f);
    b(label_57e);
    b(label_56f);
  label_56f:
    ref_56f = bustupLoad(bustup_fa);
    bustupWait(ref_56f);
    ref_571 = bustupAlloc(ref_56f, right, rgb(0,0,0));
    bustupFade(ref_571, rgb(128,0,0), 30);
    choiceSetResult(2);
    op_105(3);
    ref_575 = dialogAlloc();
    ref_576 = msgShow(msg_105);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Welcome, but... Going on the internet at
[tab]this time of the day? What, you’ve got
[tab]nothing to do? ...It’s all good, I suppose.
[choice(4)]Dine in
Talk to the lazy boy
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_576);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_575);
    shopInventory(12, shopInventory_a);
    shopRate(100);
    b(label_58f);
  label_57e:
    ref_57e = bustupLoad(bustup_fa);
    bustupWait(ref_57e);
    ref_580 = bustupAlloc(ref_57e, right, rgb(0,0,0));
    bustupFade(ref_580, rgb(128,0,0), 30);
    ref_582 = dialogAlloc();
    ref_583 = msgShow(msg_106);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Ah, welcome. I mean, you really
[tab]seem to have time on your hands.
[tab]...I’m starting to pity you.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_583);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceSetResult(2);
    op_105(3);
    ref_589 = msgShow(msg_107);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Why don’t you set up your PC so you can go
[tab]online at home? ...Huh!? It’s easy! ...Here, I’ll
[tab]give you a discount cuz I feel sorry for you.
[choice(4)]Dine in
Talk to the lazy boy
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_589);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopInventory(12, shopInventory_a);
    shopRate(80);
  label_58f:
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_594);
    li(var_5, 0);
    b(label_5aa);
  label_594:
    bne(var_0, 1, label_5a4);
    choiceSetResult(2);
    op_105(2);
    ref_597 = msgShow(msg_108);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Yeah, what’s up.
[choice(3)]Make small talk
Ask about dining in
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear]
***************************************/
    wait(ref_597);
    choiceGetResult(var_0);
    bne(var_0, 0, label_59d);
    li(var_5, 1);
    b(label_5a3);
  label_59d:
    bne(var_0, 1, label_5a0);
    li(var_5, 2000);
    b(label_5a3);
  label_5a0:
    bne(var_0, 2, label_5a3);
    li(var_5, 1000);
    b(label_5a3);
  label_5a3:
    b(label_5aa);
  label_5a4:
    bne(var_0, 2, label_5a7);
    li(var_5, 2);
    b(label_5aa);
  label_5a7:
    bne(var_0, 3, label_5aa);
    li(var_5, 3);
    b(label_5aa);
  label_5aa:
    dialogFree(ref_582);
    ref_5ab = bustupFade(ref_580, rgb(0,0,0), 10);
    bustupWait(ref_5ab);
    bustupFree(ref_580);
    wait(ref_566);
    ref_5af = shopOpen(4);
    wait(ref_5af);
}

function HA_SHOP_RESTART_0()
{
    ref_5b2 = bustupLoad(bustup_fa);
    bustupWait(ref_5b2);
    ref_5b4 = bustupAlloc(ref_5b2, right, rgb(0,0,0));
    bustupFade(ref_5b4, rgb(128,0,0), 30);
    choiceSetResult(2);
    op_105(3);
    ref_5b8 = dialogAlloc();
    ref_5b9 = msgShow(msg_109);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]So... Is there something else?
[choice(4)]Dine in
Talk to the lazy boy
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_5b9);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    li(var_1, 0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_5c2);
    li(var_5, 0);
    b(label_5d8);
  label_5c2:
    bne(var_0, 1, label_5d2);
    choiceSetResult(2);
    op_105(2);
    ref_5c5 = msgShow(msg_110);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Yeah, what’s up.
[choice(3)]Make small talk
Ask about dining in
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear]
***************************************/
    wait(ref_5c5);
    choiceGetResult(var_0);
    bne(var_0, 0, label_5cb);
    li(var_5, 1);
    b(label_5d1);
  label_5cb:
    bne(var_0, 1, label_5ce);
    li(var_5, 2000);
    b(label_5d1);
  label_5ce:
    bne(var_0, 2, label_5d1);
    li(var_5, 1000);
    b(label_5d1);
  label_5d1:
    b(label_5d8);
  label_5d2:
    bne(var_0, 2, label_5d5);
    li(var_5, 2);
    b(label_5d8);
  label_5d5:
    bne(var_0, 3, label_5d8);
    li(var_5, 3);
    b(label_5d8);
  label_5d8:
    dialogFree(ref_5b8);
    ref_5d9 = bustupFade(ref_5b4, rgb(0,0,0), 10);
    bustupWait(ref_5d9);
    bustupFree(ref_5b4);
}

function HA_SHOP_TALK_0()
{
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_616);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_603);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_5f3);
    unitFacePlayer(shopkeeper);
    ref_5e4 = bustupLoad(bustup_fa);
    bustupWait(ref_5e4);
    ref_5e6 = bustupAlloc(ref_5e4, right, rgb(0,0,0));
    bustupFade(ref_5e6, rgb(128,0,0), 30);
    ref_5e8 = dialogAlloc();
    ref_5e9 = msgShow(msg_111);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Anyway, it’s Muses this time? They’re popular
[tab]just because the producer is Ginji Sasaki.
[tab]Nowadays, all the songs selling well are his.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_5e9);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_5e8);
    ref_5ee = bustupFade(ref_5e6, rgb(0,0,0), 10);
    bustupWait(ref_5ee);
    bustupFree(ref_5e6);
    unitRestoreFacing(shopkeeper);
    b(label_626);
  label_5f3:
    unitFacePlayer(shopkeeper);
    ref_5f4 = bustupLoad(bustup_fa);
    bustupWait(ref_5f4);
    ref_5f6 = bustupAlloc(ref_5f4, right, rgb(0,0,0));
    bustupFade(ref_5f6, rgb(128,0,0), 30);
    ref_5f8 = dialogAlloc();
    ref_5f9 = msgShow(msg_112);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]Everybody’s making a fuss about Wang Long,
[tab]but that’ll just make them happy, right?
[tab]It’s better to just ignore them.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_5f9);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_5f8);
    ref_5fe = bustupFade(ref_5f6, rgb(0,0,0), 10);
    bustupWait(ref_5fe);
    bustupFree(ref_5f6);
    unitRestoreFacing(shopkeeper);
    b(label_626);
  label_603:
    unitFacePlayer(shopkeeper);
    ref_604 = bustupLoad(bustup_fa);
    bustupWait(ref_604);
    ref_606 = bustupAlloc(ref_604, right, rgb(0,0,0));
    bustupFade(ref_606, rgb(128,0,0), 30);
    ref_608 = dialogAlloc();
    ref_609 = msgShow(msg_113);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]This town is gone if a dragon comes...
[tab]Forget it. I don’t wanna work anymore.
[tab]...Does a pole shift hurt?
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_609);
    ref_60c = msgShow(msg_114);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]My life holds no meaning, but I don’t wanna
[tab]feel pain. Suicide’s dumb, too.
[tab]...Hey, wait a moment. I’m being positive.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_60c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_608);
    ref_611 = bustupFade(ref_606, rgb(0,0,0), 10);
    bustupWait(ref_611);
    bustupFree(ref_606);
    unitRestoreFacing(shopkeeper);
    b(label_626);
  label_616:
    unitFacePlayer(shopkeeper);
    ref_617 = bustupLoad(bustup_fa);
    bustupWait(ref_617);
    ref_619 = bustupAlloc(ref_617, right, rgb(0,0,0));
    bustupFade(ref_619, rgb(128,0,0), 30);
    ref_61b = dialogAlloc();
    ref_61c = msgShow(msg_115);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]It’s like we’ve died once, right? That makes
[tab]me wonder what the hell I was talking about.
[tab]I guess I was optimistic!!
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_61c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_61b);
    ref_621 = bustupFade(ref_619, rgb(0,0,0), 10);
    bustupWait(ref_621);
    bustupFree(ref_619);
    unitRestoreFacing(shopkeeper);
    b(label_626);
  label_626:
}

function HA_SHOP_END_0()
{
    ref_627 = bustupLoad(bustup_fa);
    bustupWait(ref_627);
    ref_629 = bustupAlloc(ref_627, right, rgb(0,0,0));
    bustupFade(ref_629, rgb(128,0,0), 30);
    ref_62b = dialogAlloc();
    ref_62c = msgShow(msg_116);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]I’m bored all the time, so come again.
[tab]I’ll even treat you for a meal.
[tab]Just joking... Don’t take it seriously.
[wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_21, 1);
    wait(ref_62c);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    shopOverlayInit();
    dialogFree(ref_62b);
    ref_632 = bustupFade(ref_629, rgb(0,0,0), 10);
    bustupWait(ref_632);
    bustupFree(ref_629);
    delayClear();
    delayWait(10);
    bitSet(MBIT_W_HATURAITEN);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_63d);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    b(label_640);
  label_63d:
    bne(var_0, 1, label_640);
    call(GOOUT);
    b(label_640);
  label_640:
}

function MESTEST01()
{
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bnz(var_0, label_648);
    bitSet(MBIT_HI_NANJOTOUJO);
    ref_644 = dialogAlloc();
    ref_645 = msgShow(msg_117);
/***************************************
MBIT[tab]HI[tab]NANJOTOUJO
南条出現噂:広げた
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_645);
    dialogFree(ref_644);
  label_648:
}

function MESTEST()
{
    bitGet(var_0, MBIT_AIS_12);
    bnz(var_0, label_651);
    bitSet(MBIT_AIS_12);
    ref_64c = dialogAlloc();
    ref_64d = msgShow(msg_118);
/***************************************
MBIT[tab]AIS[tab]12
相性占いの
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_64d);
    dialogFree(ref_64c);
    b(label_698);
  label_651:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_659);
    bitSet(EBIT_E006F);
    ref_654 = dialogAlloc();
    ref_655 = msgShow(msg_119);
/***************************************
EBIT[tab]E006F
「研究施設・TV局クリア」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_655);
    dialogFree(ref_654);
    b(label_698);
  label_659:
    bitGet(var_0, EBIT_E0077);
    bnz(var_0, label_661);
    bitSet(EBIT_E0077);
    ref_65c = dialogAlloc();
    ref_65d = msgShow(msg_120);
/***************************************
EBIT[tab]E0077
「スマイル平坂クリア・Katsuya離脱」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_65d);
    dialogFree(ref_65c);
    b(label_698);
  label_661:
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_669);
    bitSet(EBIT_E007A);
    ref_664 = dialogAlloc();
    ref_665 = msgShow(msg_121);
/***************************************
EBIT[tab]E007A
「野音クリア・Katsuya編入」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_665);
    dialogFree(ref_664);
    b(label_698);
  label_669:
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_671);
    bitSet(EBIT_E007B);
    ref_66c = dialogAlloc();
    ref_66d = msgShow(msg_122);
/***************************************
EBIT[tab]E007B
「竜蔵と殺し屋の電話を盗聴」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_66d);
    dialogFree(ref_66c);
    b(label_698);
  label_671:
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_679);
    bitSet(EBIT_E007F);
    ref_674 = dialogAlloc();
    ref_675 = msgShow(msg_123);
/***************************************
EBIT[tab]E007F
「廃工場クリア・Baofu編入」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_675);
    dialogFree(ref_674);
    b(label_698);
  label_679:
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_681);
    bitSet(EBIT_E008C);
    ref_67c = dialogAlloc();
    ref_67d = msgShow(msg_124);
/***************************************
EBIT[tab]E008C
「海底遺跡クリア」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_67d);
    dialogFree(ref_67c);
    b(label_698);
  label_681:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_689);
    bitSet(EBIT_E009F);
    ref_684 = dialogAlloc();
    ref_685 = msgShow(msg_125);
/***************************************
EBIT[tab]E009F
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_685);
    dialogFree(ref_684);
    b(label_698);
  label_689:
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_691);
    bitSet(EBIT_E00AF);
    ref_68c = dialogAlloc();
    ref_68d = msgShow(msg_126);
/***************************************
EBIT[tab]E00AF
「アメノトリフネクリア」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_68d);
    dialogFree(ref_68c);
    b(label_698);
  label_691:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_698);
    bitSet(EBIT_E00B8);
    ref_694 = dialogAlloc();
    ref_695 = msgShow(msg_127);
/***************************************
EBIT[tab]E00B8
「珠「瑠城クリア」
びっとお~んッ!!
[wait][clear]
***************************************/
    wait(ref_695);
    dialogFree(ref_694);
  label_698:
}

function DOORBOX()
{
    controlDisable();
    sndMusicPlay(sound_3078, 127);
    objAnimRotate(obj_4, 0, 70, 0, 30, 0);
    objAnimRotate(obj_3, 0, -70, 0, 30, 0);
    objAnimWait(obj_4);
    objAnimWait(obj_3);
    call(GOOUT);
}

function GOOUT()
{
    bitClear(MBIT_EXITBIT);
    mapLoad(rengedai, 0, 0);
}

function warp1()
{
    call(DOORBOX);
}

function HA_SHOP_EXPLAIN_0()
{
    ref_6a6 = dialogAlloc();
    ref_6a7 = msgShow(msg_128);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]So you want me to tell you how to eat.
[tab]Okay... Just choose "Dine in"
[wait][clear][color(yellow)]Lazy boy[color(white)]
[tab]Food can raise your stats for a while.
[tab]Different food does different things.
[tab]Are you getting all this?
[wait][clear][color(yellow)]Lazy boy[color(white)]
[tab]Once you’ve eaten, you can’t eat again
[tab]until the effects wear off. That’s it.
[wait][clear]
***************************************/
    wait(ref_6a7);
    dialogFree(ref_6a6);
}

function DECIDE_EAT()
{
    choiceSetResult(1);
    op_105(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_6af = bustupLoad(bustup_fa);
    bustupWait(ref_6af);
    ref_6b1 = bustupAlloc(ref_6af, left, rgb(0,0,0));
    bustupFade(ref_6b1, rgb(128,0,0), 30);
    ref_6b3 = dialogAlloc();
    ref_6b4 = msgShow(msg_129);
/***************************************
[color(yellow)]Lazy boy[color(white)]
[tab]That’s, what, ¥[var(msg_var_0)]. Yeah?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_6b4);
    choiceGetResult(var_7);
    bne(var_7, 0, label_6ba);
    li(var_7, 1);
    b(label_6bd);
  label_6ba:
    bne(var_7, 1, label_6bd);
    li(var_7, 0);
    b(label_6bd);
  label_6bd:
    wait(ref_6b4);
    dialogFree(ref_6b3);
    ref_6bf = bustupFade(ref_6b1, rgb(0,0,0), 10);
    bustupWait(ref_6bf);
    bustupFree(ref_6b1);
    li(var_5, 20);
}
