
msg_0:
[color(yellow)]Yukino[color(white)]
[tab]I was worried what was going to happen,
[tab]but I’m glad we’re all safe. Still... 
[tab]I don’t believe that Kandori’s still alive...
[wait][clear][end]

msg_1:
[color(yellow)]Yukino[color(white)]
[tab]I heard from Elly!
[tab]You’re also a Persona user, huh?
[wait][clear][end]

msg_2:
[color(yellow)]Yukino[color(white)]
[tab]That strange feeling when we first met...
[tab]I guess that really was resonance.
[wait][clear][end]

msg_3:
[color(yellow)]Yukino[color(white)]
[tab]I’m sorry, Maya-san.
[tab]I couldn’t hide it from Shunsuke-san...
[wait][clear][end]

msg_4:
[color(yellow)]Yukino[color(white)]
[tab]Dude, what did you do...!?
[wait][clear][end]

msg_5:
[color(yellow)]Yukino[color(white)]
[tab]Dude, what did you do...!?
[wait][clear][end]

msg_6:
[color(yellow)]Fujii[color(white)]
[tab]What happened at the TV station?
[tab]Yukki won’t explain it to me...
[tab]Is it something you can’t tell me?
[wait][clear][end]

msg_7:
[color(yellow)]Fujii[color(white)]
[tab]What happened at Sumaru TV?
[tab]Makki, do you know anything?
[wait][clear][end]

msg_8:
[color(yellow)]Fujii[color(white)]
[tab]Yukki and Brown were with me, but they
[tab]won’t tell me what they know about
[tab]what happened.
[wait][clear][end]

msg_9:
[color(yellow)]Fujii[color(white)]
[tab]I heard from Yukki.
[tab]You’re the ones fighting against
[tab]the New World Order.
[wait][clear][end]

msg_10:
[color(yellow)]Fujii[color(white)]
[tab]It’s still settling in...
[tab]Should I say this?[delay(30)]
[tab]...Good luck, Makki!
[wait][clear][end]

msg_11:
[color(yellow)]Fujii[color(white)]
[tab]...Eh, Yukki?
[tab]Yukki went out to protect everybody.
[tab]...To stop the Tenchu Army.
[wait][clear][end]

msg_12:
[color(yellow)]Fujii[color(white)]
[tab]I’m going to record this real event in its
[tab]entirety on film. That’s the only thing
[tab]I can do... That is my cause.
[wait][clear][end]

msg_13:
[color(yellow)]Fujii[color(white)]
[tab]I don’t really understand what’s going on,
[tab]but you, Makki, Yukki, and your friends are... 
[tab]walking the path you all believe in.
[wait][clear][end]

msg_14:
[color(yellow)]Fujii[color(white)]
[tab]...Makki, reach for the stars.
[wait][clear][end]

msg_15:
[color(yellow)]Rookie Reporter[color(white)]
[tab]Since you didn’t come back for a while, 
[tab]I thought that you got wrapped up in the
[tab]kidnapping incident. Be careful.
[wait][clear][end]

msg_16:
[color(yellow)]Rookie Reporter[color(white)]
[tab]What are you going to do? What do you mean
[tab]"What"? ...It’s the end of the world!
[tab](sigh) ...Should I quit and screw around?
[wait][clear][end]

msg_17:
[color(yellow)]Rookie Reporter[color(white)]
[tab]Ahh, senpai!? We’re really floating!?
[tab]It’s not that I didn’t believe in
[tab]Wang Long fortunes, but...
[wait][clear][end]

msg_18:
[color(yellow)]Rookie Reporter[color(white)]
[tab]What should I do...?
[tab]Tell me, senpai!
[wait][clear][end]

msg_19:
[color(yellow)]Rookie Reporter[color(white)]
[tab]Ah, senpai... It’s great that everyone’s safe! 
[tab]I feel so relieved. 
[tab]...Eh? Work? ...I completely forgot.
[wait][clear][end]

msg_20:
[color(yellow)]Rookie Reporter[color(white)]
[tab]Ah, welcome back, senpai.
[tab]There’s a package for you.
[wait][clear][end]

msg_21:
[color(yellow)]Rookie Reporter[color(white)]
[tab]I put it in the box next to your desk,
[tab]so please make sure you check it.
[wait][clear][end]

msg_22:
[color(yellow)]Colleague[color(white)]
[tab]Amano... Stop going outside,
[tab]and help with the other task sometimes!
[wait][clear][end]

msg_23:
[color(yellow)]Colleague[color(white)]
[tab]Ah, but you don’t have to clean up.
[tab]It just gets dirtier when you clean.
[wait][clear][end]

msg_24:
[color(yellow)]Colleague[color(white)]
[tab]"End of the world"? ..."Pole shift"?
[tab]It’ll make for a good headline,
[tab]but I don’t want to deal with complaints!?
[wait][clear][end]

msg_25:
[color(yellow)]Colleague[color(white)]
[tab]...Let’s pick our stories carefully.
[wait][clear][end]

msg_26:
[color(yellow)]Colleague[color(white)]
[tab]What the heck, it IS the end of the world!
[tab]It’s just not the "Grand Cross"! We should
[tab]have thought of using the lunar calendar!
[wait][clear][end]

msg_27:
[color(yellow)]Colleague[color(white)]
[tab](sigh)... I’m so pissed that I actually
[tab]replied to those complaints seriously!
[wait][clear][end]

msg_28:
[color(yellow)]Colleague[color(white)]
[tab](sigh) My senpai’s so hard-working...
[tab]An editor to the bone...
[tab]Can I possibly keep up with them?
[wait][clear][end]

msg_29:
[color(yellow)]Co-Worker[color(white)]
[tab]Since that TV show, people think of Wang
[tab]Long as more of an occult thing.
[tab]It’s like it has a different kind of fan.
[wait][clear][end]

msg_30:
[color(yellow)]Co-Worker[color(white)]
[tab]What’s the next feature article...?
[tab]What kind of scoop can we get in this
[tab]situation? ...Hmm, that’s hard.
[wait][clear][end]

msg_31:
[color(yellow)]Co-Worker[color(white)]
[tab]Alright, Wang Long...!
[tab]As predicted, we really are floating...
[tab]...Destruction? You’re worried about that?
[wait][clear][end]

msg_32:
[color(yellow)]Co-Worker[color(white)]
[tab]Sumaru... No, the Ameno Torifune
[tab]will be alright! Amano, you should read
[tab]the newspaper every once in a while.
[wait][clear][end]

msg_33:
[color(yellow)]Co-Worker[color(white)]
[tab]Huh, what happened to the "pole shift"?
[tab]Wang Long missed? No way?
[tab]I don’t believe it.
[wait][clear][end]

msg_34:
[color(yellow)]Reporter[color(white)]
[tab]It’s a scary world...
[tab]You living with your parents?
[tab]...Eh? No!?
[wait][clear][end]

msg_35:
[color(yellow)]Reporter[color(white)]
[tab]It’s dangerous living alone!
[tab]It’s okay because you’re not alone, huh?
[tab]Hmmm... You’re okay... huh...
[wait][clear][end]

msg_36:
[color(yellow)]Reporter[color(white)]
[tab]Amano, did you go to the seminar to rid
[tab]yourself of Kegare? ...Eh? No?
[tab]That’s not good.
[wait][clear][end]

msg_37:
[color(yellow)]Reporter[color(white)]
[tab]I’m in trouble because I haven’t gone
[tab]either, but you should go, too.
[wait][clear][end]

msg_38:
[color(yellow)]Reporter[color(white)]
[tab]Oh no! I’ll be erased!
[tab]Ah, Amano!! Did you get purified?
[tab]No!? That’s not good!
[wait][clear][end]

msg_39:
[color(yellow)]Reporter[color(white)]
[tab]New World Order... No, Tenchu Army is killing
[tab]anyone who has Kegare in their hearts!
[tab]...I’ve been so busy I haven’t gone yet...
[wait][clear][end]

msg_40:
[color(yellow)]Reporter[color(white)]
[tab](sigh)... What’ll happen to Sumaru?
[tab]What are you going to do, Amano...?
[tab]Huh? ...The "Nyarlat-Ho Two-step"?
[wait][clear][end]

msg_41:
[color(yellow)]Reporter[color(white)]
[tab]Going square-dancing with someone, huh.
[tab]You seem so happy. I’m jealous.
[wait][clear][end]

msg_42:
[color(yellow)]Tasaki[color(white)]
[tab]Hey, where’d that manuscript go? Huh, who
[tab]put back the next issue’s color contrast!?
[tab]Geez... Amano-san! ...You were here?
[wait][clear][end]

msg_43:
[color(yellow)]Tasaki[color(white)]
[tab]...Stay calm... T-h-i-n-k...
[tab]What do high-schoolers want these days...!?
[tab]Survival info!?
[wait][clear][end]

msg_44:
[color(yellow)]Tasaki[color(white)]
[tab]No, no.
[tab]It should be more... transient...
[wait][clear][end]

msg_45:
[color(yellow)]Tasaki[color(white)]
[tab](sigh)... I never thought that
[tab]the content of my article would come
[tab]back to haunt me.
[wait][clear][end]

msg_46:
[color(yellow)]Tasaki[color(white)]
[tab]What biased information did I send out...
[tab]Have you ever thought like that?
[wait][clear][end]

msg_47:
[color(yellow)]Tasaki[color(white)]
[tab]I thought that the most important thing
[tab]was to raise the circulation of Coolest.
[tab]But isn’t that a bit selfish?
[wait][clear][end]

msg_48:
[color(yellow)]Tasaki[color(white)]
[tab]...I’m sorry.
[tab]That was boring, wasn’t it?
[wait][clear][end]

msg_49:
[color(yellow)]Veteran Reporter[color(white)]
[tab]First bizarre murders, now kidnappings in
[tab]broad daylight... Sumaru’s becoming a crime
[tab]capital... What kidnappings, you say?
[wait][clear][end]

msg_50:
[color(yellow)]Veteran Reporter[color(white)]
[tab]Read the newspaper!
[tab]...N-E-W-S-P-A-P-E-R!!
[wait][clear][end]

msg_51:
[color(yellow)]Veteran Reporter[color(white)]
[tab]New World Order’s plan for destruction...?
[tab]So the Wang Long AND the ancient history
[tab]craze were all New World Order’s plan?
[wait][clear][end]

msg_52:
[color(yellow)]Veteran Reporter[color(white)]
[tab]That’s even more impressive than an agency.
[wait][clear][end]

msg_53:
[color(yellow)]Veteran Reporter[color(white)]
[tab]Hey, hey, so the Ameno Torifune IS
[tab]Sumaru City...?
[tab]...Is my kid alright?
[wait][clear][end]

msg_54:
[color(yellow)]Veteran Reporter[color(white)]
[tab]...What? ...My kid?
[tab]You’re worried about him?
[tab]Yeah, he’s fine. ...Thanks.
[wait][clear][end]

msg_55:
[color(yellow)]Senior Reporter[color(white)]
[tab]I hate magazines for teeny-boppers.
[tab]If you’re aiming to be a real journalist,
[tab]you can’t work as an editor for Coolest.
[wait][clear][end]

msg_56:
[color(yellow)]Senior Reporter[color(white)]
[tab]...What, Amano?
[tab]What do you want?
[wait][clear][end]

msg_57:
[tab]What do you want?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_58:
OSAMITSU TANAKA
[end]

msg_59:
[color(yellow)]Senior Reporter[color(white)]
[tab]Amano-kun...?
[tab]You don’t know my name?
[tab]...Geez, young people today...
[wait][clear][end]

msg_60:
[color(yellow)]Osamitsu Tanaka[color(white)]
[tab]What’s up, being so formal all of a
[tab]sudden. What? ...Classmate...?
[tab]From high school? He’s looking for me?
[wait][clear][end]

msg_61:
[color(yellow)]Osamitsu Tanaka[color(white)]
[tab]...Hmmmmmm.
[tab]I haven’t seen him for 10 years.
[tab]Man, that brings back old times.
[wait][clear][end]

msg_62:
[color(yellow)]Osamitsu Tanaka[color(white)]
[tab]Alright, I’ll give him a buzz...
[tab]By the way, Amano...[delay(30)]
[tab]...No moonlighting.
[wait][clear][end]

msg_63:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_64:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_65:
[tab]Unmasking the corruption of the current
[tab]Foreign Minister, huh... I was drinking
[tab]with the author of this the other day.
[wait][clear][end]

msg_66:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_67:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_68:
[tab]He looked so alive.
[tab]Man, I want to work in the social
[tab]department...
[wait][clear][end]

msg_69:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_70:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_71:
[tab]I wonder what my friend is doing?
[tab]He started at the same time I did, 
[tab]but he went to the social department.
[wait][clear][end]

msg_72:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_73:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_74:
[tab]He’s probably writing away happily...
[tab](sigh)... Social department...
[wait][clear][end]

msg_75:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_76:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_77:
[tab]Chance! Write a bunch of articles now, 
[tab]so when everything’s back to normal... 
[tab]What if it doesn’t, you say? So...[delay(15)]be it!
[wait][clear][end]

msg_78:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_79:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_80:
[tab]Who cares about brats!? I’m gonna get
[tab]this commotion all summed up! I’m going
[tab]to submit it by the end of this week!
[wait][clear][end]

msg_81:
[color(yellow)]Senior Reporter[color(white)]
[end]

msg_82:
[color(yellow)]Osamitsu Tanaka[color(white)]
[end]

msg_83:
[tab]Arrange for a manuscript from an archeolo...
[tab]No, a mythologist, the front picture will be... 
[tab]Fujii! ...Where’s that picture!?
[wait][clear][end]

msg_84:
[color(yellow)]Chief Editor’s Room[color(white)]
[tab][color(green)]...She’s having a meeting.[color(white)]
[sync][wait][clear][end]

msg_85:
[color(yellow)]Chief Editor’s Room[color(white)]
[tab][color(green)]... She’s off today.[color(white)]
[sync][wait][clear][end]

msg_86:
[color(yellow)]Emergency Staircase[color(white)]
[tab][color(green)]You cannot enter here.[color(white)]
[sync][wait][clear][end]

msg_87:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Battle Master magazine.[color(white)]
[sync][wait][clear][end]

msg_88:
[color(yellow)]Letter from Battle Master[color(white)]
[tab]"Thank you for entering in our contest.
[tab] I am sorry to inform you that you did not
[tab] win. We are waiting for your next entry."[wait][clear][end]

msg_89:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Miracle magazine.[color(white)]
[sync][wait][clear][end]

msg_90:
[color(yellow)]Letter from Miracle magazine[color(white)]
[tab]"Thank you for entering in our contest.
[tab] I am sorry to inform you that you did not
[tab] win. We are waiting for your next entry."[wait][clear][end]

msg_91:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Fantasy World magazine.[color(white)]
[sync][wait][clear][end]

msg_92:
[color(yellow)]Letter from Fantasy World[color(white)]
[tab]"Thank you for entering in our contest.
[tab] I am sorry to inform you that you did not
[tab] win. We are waiting for your next entry."[wait][clear][end]

msg_93:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Battle Master magazine.[color(white)]
[sync][wait][clear][end]

msg_94:
[color(yellow)]Letter from Battle Master[color(white)]
[tab]"Thank you for entering in our contest.
[tab] You have been selected as a winner.
[tab] Congratulations!!"[wait][clear][end]

msg_95:
[color(yellow)]Letter from Battle Master[color(white)]
[tab]"Your prize is
[tab] [color(green)][var(msg_var_0)][color(white)].
[tab] We are waiting for your next entry."[wait][clear][end]

msg_96:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_97:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Miracle magazine.[color(white)]
[sync][wait][clear][end]

msg_98:
[color(yellow)]Letter from Miracle magazine[color(white)]
[tab]"Thank you for entering in our contest.
[tab] You have been selected as a winner.
[tab] Congratulations!!"[wait][clear][end]

msg_99:
[color(yellow)]Letter from Miracle magazine[color(white)]
[tab]"Your prize is
[tab] [color(green)][var(msg_var_0)][color(white)].
[tab] We are waiting for your next entry."[wait][clear][end]

msg_100:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_101:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter from
[tab]Fantasy World magazine.[color(white)]
[sync][wait][clear][end]

msg_102:
[color(yellow)]Letter from Fantasy World[color(white)]
[tab]"Thank you for entering in our contest.
[tab] You have been selected as a winner.
[tab] Congratulations!!"[wait][clear][end]

msg_103:
[color(yellow)]Letter from Fantasy World[color(white)]
[tab]"Your prize is
[tab] [color(green)][var(msg_var_0)][color(white)].
[tab] We are waiting for your next entry."[wait][clear][end]

msg_104:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[wait][clear][end]

msg_105:
[color(yellow)]In the Box[color(white)]
[tab][color(green)]There is a letter.[color(white)]
[sync][wait][clear][end]

msg_106:
[color(yellow)]Letter from ???[color(white)]
[tab]Are you the one worthy of this?
[wait][clear][end]

msg_107:
[color(green)]Maya got [item_with_type(item_ffff)].[color(white)]
[sync][wait][clear][end]

msg_108:
Prize Contest - Battle/World
Bit on!!
[wait][clear][end]

msg_109:
Prize Contest - Miracle
Bit on!!
[wait][clear][end]

msg_110:
Prize Contest - Miracle
Bit on!!
[wait][clear][end]

msg_111:
MBIT AIS 32
Compatibility Fortune
Bit on!!
[wait][clear][end]

msg_112:
EBIT E006F
"Lab/TV station clear"
Bit on!!
[wait][clear][end]

msg_113:
EBIT E0077
"Smile Hirasaka clear - Katsuya escape"
Bit on!!
[wait][clear][end]

msg_114:
EBIT E007A
"Concert Hall clear - Katsuya back"
Bit on!!
[wait][clear][end]

msg_115:
EBIT E007B
"Tatsuzou and assassin’s phone tapped"
Bit on!!
[wait][clear][end]

msg_116:
EBIT E007F
"Factory clear - Baofu back"
Bit on!!
[wait][clear][end]

msg_117:
EBIT E008C
"Ocean Floor Ruins clear"
Bit on!!
[wait][clear][end]

msg_118:
EBIT E009F
"Mt Iwato clear - Nanjo/Elly out, [tatsuya] in
[wait][clear][end]

msg_119:
EBIT E00AF
"Ameno Torifune clear"
Bit on!!
[wait][clear][end]

msg_120:
EBIT E00B8
"Sumaru Castle clear"
Bit on!!
[wait][clear][end]
