
msg_0:
There are more than 4 people.
It will hang.
Get a hold of Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]A Persona is part of one’s personality...?
[tab]Huh... that means...
[tab]Uh, a part of me is like that?!
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]I hear Satomi Tadashi is an expanding franchise. 
[tab]They don’t have any competition.
[tab]Oh, are high school girls the competition?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Sorry, I’m sorry? ...But look,
[tab]we confirmed that a person who did
[tab]the Joker curse turned into a Joker!
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]It’s hard to become honest when
[tab]a companion’s feelings are too strong. 
[tab]Anna-chan was probably like that.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]I’ve seen this girl in the picture
[tab]somewhere. You recognize her, Ma-ya?
[tab]Hmmm, who is she? A celebrity?
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Ahhh, that’s a new one...
[tab]Did something happen with [suou]-san?
[tab]Hey Ma-ya! Tell me!
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]You’re so composed. I think the
[tab]strength of this Persona is just
[tab]too much for the human body...
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]I heard there are many theft cases here by
[tab]students, but in such a wide open area...?
[tab]There’s absolutely no crime control.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]...Exactly what Baofu said. It doesn’t
[tab]matter to me what the law deems as just.
[tab]I’m going to do what’s right...
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]What a criminal says can be a benefit. 
[tab]It may go awry in the way a person acts...
[tab]However, you don’t need to preach it.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]The Persona symbolizing the
[tab]human sin... Joker...
[tab]So anybody can have that trait.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Noriko-kun’s strong feelings for Anna-kun...
[tab]It cannot be forgiven...
[tab]Using a youth’s innocent feelings...
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]The two in the picture...
[tab]No one came up a match in our files.
[tab]It seems there is no previous offense.
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]Oh, Amano-kun, what’s wrong?
[tab]M-Me?
[tab]I was just looking at the merchandise...
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]Wouldn’t juvenile crimes rise if adults
[tab]couldn’t scold their children...?
[tab]The wrongs of sin need to be instilled in children.
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]All cases we get into are "accidents". 
[tab]It is handling information by using various
[tab]means. Is the young [suou] alright?
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]So [suou], are you satisfied at how
[tab]corrupt the police system is? 
[tab]Aren’t you disgusted by being a sucker?
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]Cheap stuff has surely gotten better, but,
[tab]it just substitutes the good stuff, right?
[tab]That shouldn’t make anybody happy.
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Everyone has the potential of
[tab]becoming a Joker. Serizawa has
[tab]proven it. That’s just too bad.
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]There’s too many weak-willed people.
[tab]Those that take advantage... are they
[tab]geniuses... or fools? That’s debatable.
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]We should look at that picture again.
[tab]You guys are just looking at the faces.
[tab]There’s a lot more information on it!
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]What...!
[tab]That [suou], turning red...
[tab]Amano, what did you do?
[wait][clear][end]

msg_23:
[color(yellow)]Nanjo[color(white)]
[tab]Sergeant [suou] even makes that
[tab]kind of a face... I thought he was an
[tab]emotionless and unflappable guy...
[wait][clear][end]

msg_24:
[color(yellow)]Elly[color(white)]
[tab]Why is Mr. Katsuya in a flurry?
[tab]Did something bad happen?
[wait][clear][end]

msg_25:
[color(yellow)]Composer[color(white)]
[tab]Those who live creating as I, occasionally
[tab]travel into worlds unseen by laymen...
[tab]A special world beyond the sleepless days.
[wait][clear][end]

msg_26:
[color(yellow)]Composer[color(white)]
[tab]And it can be seen right there...
[tab]Nope, it IS right there...
[tab]A blue door called the Velvet Room...
[wait][clear][end]

msg_27:
[color(yellow)]Composer[color(white)]
[tab]So real weapons are being sold...
[tab]Which would you buy if a Muses’ concert
[tab]ticket and a weapon cost the same?
[wait][clear][end]

msg_28:
[color(yellow)]Composer[color(white)]
[tab]I...
[tab]Embarrassingly, I want both!!
[wait][clear][end]

msg_29:
[color(yellow)]Composer[color(white)]
[tab]The Joker curse gives rise to a new Joker...
[tab]Humans are making various speculations...
[tab]I feel the influential power of Wang Long.
[wait][clear][end]

msg_30:
[color(yellow)]Composer[color(white)]
[tab]Hm, being relied on by evil, sin, and envy!
[tab]To be an artist is to face such intrusion!
[tab]So I should make something... soothing?
[wait][clear][end]

msg_31:
[color(yellow)]Aloof Man[color(white)]
[tab]Hey, did you hear? The principal
[tab]at Sevens got knocked off.
[tab]Do people despise principals that much?
[wait][clear][end]

msg_32:
[color(yellow)]Aloof Man[color(white)]
[tab]Buying weapons at the bar? 
[tab]I heard the rumor but didn’t know it was true...
[tab]I’m not surprised, but, what a racket...
[wait][clear][end]

msg_33:
[color(yellow)]Aloof Man[color(white)]
[tab]Wang Long here also...
[tab]When insecure, you tend to rely on something...
[tab]But, shouldn’t you divide reality and imagination?
[wait][clear][end]

msg_34:
[color(yellow)]Aloof Man[color(white)]
[tab]Joker, huh? Are they really increasing?
[tab]I feel the press is just having fun...
[tab]Above all, I’ve never seen one.
[wait][clear][end]

msg_35:
[color(yellow)]Makimura[color(white)]
[tab]The economy has been bad, right? 
[tab]So, my advice is a date at the ¥100 store!
[tab]Is it popular among frugal girls...?
[wait][clear][end]

msg_36:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]HeeHeeHee... Welcome to Satomi Tadashi
[tab]in Aoba... Now now, how can I help you?
[tab]HeeHeeHee.
[wait][clear][end]

msg_37:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Welcome to Satomi Tadashi in Aoba.
[tab]Oh my! This is your first time... 
[tab]I’ll give you a discount today for stopping by.
[wait][clear][end]

msg_38:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Welcome to Satomi Tadashi in Aoba... Oh my!
[tab]HeeHeeHee!! Thank you for shopping here
[tab]frequently. I’ll give you a discount today.
[wait][clear][end]

msg_39:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Welcooooome...
[tab]Uhyohyohyo.
[choice(6)]Buy items
Sell items
Talk to Sister #1
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_40:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]So, what would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_41:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]So what do you want to talk about?
[choice(3)]Make small talk
Ask about shopping
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_42:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Is there anything else I can do for you?
[tab]...HeeHeeHee.
[choice(6)]Buy items
Sell items
Talk to Sister #1
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_43:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]So, what would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_44:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]So what do you want to talk about?
[choice(3)]Make small talk
Ask about shopping
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_45:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]What? You’ve seen me before? ...HeeHeeHee.
[tab]My younger sisters look just like me.
[tab]I’m the eldest of the 7 Satomi Sisters.
[wait][clear][end]

msg_46:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]HeeHeeHee!!
[tab]Anyway, I hope that you will also
[tab]shop at my sisters’ stores.
[wait][clear][end]

msg_47:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]As long as this song exists, Satomi Tadashi
[tab]will thrive! I can’t shut down even if a
[tab]Joker appears! I’d rather make money.
[wait][clear][end]

msg_48:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Did ya know? The recent Wang Long fortunes
[tab]are scary. I was told my friend may be a
[tab]Joker... It was in a magazine...
[wait][clear][end]

msg_49:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Thank you, hon...
[tab]Please come again.
[tab]HeeHeeHee.
[wait][clear][end]

msg_50:
MBIT[tab]AIS[tab]65
相性占いの
びっとお~んッ!!
[wait][clear][end]

msg_51:
EBIT[tab]E0015
7姉妹学園クリア
びっとお~んッ!!
[wait][clear][end]

msg_52:
EBIT[tab]E0018
バー終了・Baofu初参加
びっとお~んッ!!
[wait][clear][end]

msg_53:
EBIT[tab]E0033
「Baofu編入」
びっとお~んッ!!
[wait][clear][end]

msg_54:
EBIT[tab]E0037
警察署[half_tab]受付、終了
びっとお~んッ!!
[wait][clear][end]

msg_55:
EBIT[tab]E0038
「詐欺男を確保」
びっとお~んッ!!
[wait][clear][end]

msg_56:
EBIT[tab]E003E
「ゴールドクリア」「Ulala編入」
びっとお~んッ!!
[wait][clear][end]

msg_57:
EBIT[tab]E0043
「クラブクリア」
びっとお~んッ!!
[wait][clear][end]

msg_58:
EBIT[tab]E0044
「青葉公園クリア」
びっとお~んッ!!
[wait][clear][end]

msg_59:
EBIT[tab]E0046
「南条orエリー編入」
びっとお~んッ!!
[wait][clear][end]

msg_60:
EBIT[tab]E006F
「研究施設・TV局クリア」
びっとお~んッ!!
[wait][clear][end]

msg_61:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Uhyohyohyo!
[tab]Okay, I’ll tell you a little about shopping.
[wait][clear][color(yellow)]Satomi Sister #1[color(white)]
[tab]First, buying things. 
[tab]If you select "Buy items" here
[tab]you can choose from our sundries.
[wait][clear][color(yellow)]Satomi Sister #1[color(white)]
[tab]Oh, and there’s a limit to how many of the
[tab]same item you can carry.
[wait][clear][color(yellow)]Satomi Sister #1[color(white)]
[tab]Next, selling.
[tab]Select "Sell items" first, and then
[tab]choose which type of item to sell. 
[wait][clear][color(yellow)]Satomi Sister #1[color(white)]
[tab]Then pick a particular item to sell us.
[tab]Our resale prices are around half the original
[tab]price. You can’t sell anything you have equipped,
[wait][clear][color(yellow)]Satomi Sister #1[color(white)]
[tab]and some special items are off-limits too.
[tab]That’s about it.
[tab]Uhyohyohyo!
[wait][clear][end]

msg_62:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]Oh, but you don’t have anything you can sell.[wait][clear][end]

msg_63:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]The total comes to ¥[var(msg_var_0)].
[tab]Is that all right?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_64:
[color(yellow)]Satomi Sister #1[color(white)]
[tab]The total comes to ¥[var(msg_var_0)].
[tab]Is that all right?
[choice(2)]Yes
No
[end_choice][clear][end]
