
msg_0:
That’s over 4 people in the party.
In this condition, it will hang.
Get a hold of Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]So that’s what the Joker looks like. 
[tab]I didn’t think it actually existed! 
[tab]...Do you think the Joker curse is, um, bad?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Isn’t the Chief kind of weird? I mean...
[tab]To me, his appearance doesn’t seem to match
[tab]his intelligence.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya, let’s hurry. We have to...
[tab]We have to help Noriko-chan!  We can’t let such
[tab]a young girl turn into a Joker!
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Baofu was scary at Zodiac, huh? It seems he
[tab]has a shady past, but I wonder if that has
[tab]anything to do with it...
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Evil organization led by the Foreign Minister...
[tab]Sounds like that one comic book, where the
[tab]bad guys turned out to be the government.
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]See? My plan worked!
[tab]...What, Ma-ya? Is that the look of admiration?
[tab]Oh, cut it out!
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Amano-kun... Won’t spreading rumors about
[tab]shops be considered as obstruction of
[tab]business?
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]Though said, there has probably been no case
[tab]of judicial precedent in court...
[tab]I feel the limits of the law and myself.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]...That’s a cute lucky cat statue...
[tab]What? That’s not what you expect me to say?
[tab]Is it that weird... for me to be a cat lover?
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]The Joker curse that turns people into Jokers...
[tab] So this is what Sudou’s last words meant.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]Question him about his other crimes? 
[tab]I don’t intend to let him go, but his safety has a
[tab]higher priority! I’ll take care of that later!
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Amano-kun, I agree with what Serizawa-kun said... 
[tab]We can’t allow her to commit any more crimes!
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Baofu... Why don’t we stop hiding things? 
[tab]If there’s something I can do, 
[tab]I won’t regret helping.
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]It is true that Foreign Minister Sudou’s
[tab]influence is big. However, he needs to know
[tab]that there are those who don’t yield to him!
[wait][clear][end]

msg_15:
[color(yellow)]Katsuya[color(white)]
[tab]I would never have thought of using rumors
[tab]to contact Nanjo-kun and Kirishima-kun.
[tab]Serizawa-kun’s ingenuity is simply amazing.
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]There’s people like that on the net. 
[tab]Outspoken online, but can’t say shit in real life.
[tab]...Wait, did I screw up somewhere?
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]Listen, Amano! You can’t depend on anyone!
[tab]Never trust the society... even your friends!
[tab]You can only rely on yourself... Got it!?
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]"Joker won’t die", huh...
[tab]He’s right, his death won’t end this case.
[tab]Hmph, too bad for us.
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Hehehe, that swindler is rebellious now.
[tab]What are you gonna do, [suou]?
[tab]Grill him thoroughly?
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]It doesn’t matter if she’s a minor, or if she
[tab]indirectly committed murder with the Joker
[tab]curse... She must pay for her crime.
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]...There’s nothing to talk about.
[tab]And you don’t have time to waste
[tab]on me, right?
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]That Tatsuzou Sudou has never been free
[tab]from black rumors... since way back then.
[wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]Serizawa’s plan is really something.
[tab]A normal brain won’t come up with that.
[tab]...But, is it really working?
[wait][clear][end]

msg_24:
[color(yellow)]Nanjo[color(white)]
[tab]Hmm, I haven’t seen you in ages.
[tab]I thought you were in college...
[tab]...Working part-time? Here?
[wait][clear][end]

msg_25:
[color(yellow)]Nanjo[color(white)]
[tab]So, you found us by manipulating rumors...
[tab]It reminds me of that one saying...
[tab]"A drowning man will clutch at straws."
[wait][clear][end]

msg_26:
[color(yellow)]Elly[color(white)]
[tab]Oh! It’s been a while, Ms. Tamaki!
[tab]How have you been?
[wait][clear][end]

msg_27:
[color(yellow)]Elly[color(white)]
[tab]If New World Order is manipulating Kotodama,
[tab]they could’ve stopped us from contacting
[tab]you... Why didn’t they?
[wait][clear][end]

msg_28:
[color(yellow)]Tamaki[color(white)]
[tab]Hi there!
[tab]How can I help you today?
[wait][clear][end]

msg_29:
[tab]Oh, hi there!
[tab]Huh...? Did something happen recently?
[tab]...You’ve become so pretty!
[wait][clear][end]

msg_30:
[color(yellow)]Tamaki[color(white)]
[tab]Oh, I know... Hmm, I see...
[tab]Just kidding!! Teehee...
[wait][clear][end]

msg_31:
[color(yellow)]Tamaki[color(white)]
[tab]The rumor about the sweepstakes should
[tab]become real now. I know you’re busy, so let me
[tab]take care of the entries for you, okay?
[wait][clear][end]

msg_32:
[color(yellow)]Tamaki[color(white)]
[tab]Now, what are you going to do?
[choice(4)]Talk to Tamaki
Enter magazine sweepstakes
Ask about the sweepstakes
Nothing
[end_choice][clear][end]

msg_33:
[color(yellow)]Tamaki[color(white)]
[tab]You want to enter the sweepstakes?
[tab]Let’s see, Battle Master...[delay(30)]
[tab]Oops!! No can do.
[wait][clear][end]

msg_34:
[color(yellow)]Tamaki[color(white)]
[tab]Did you check if you won anything from the
[tab]last sweepstakes? If not, you should do so
[tab]at Kismet’s editorial department.
[wait][clear][end]

msg_35:
[color(yellow)]Tamaki[color(white)]
[end]

msg_36:
[tab]You want to enter the sweepstakes?
[end]

msg_37:
[tab]Oh, you want to enter another one?
[end]

msg_38:
[tab]Let’s see, Miracle...[delay(30)]
[tab]Oops!! No can do.
[wait][clear][end]

msg_39:
[color(yellow)]Tamaki[color(white)]
[tab]Did you check if you won anything from the
[tab]last sweepstakes? If not, you should do so
[tab]at Kismet’s editorial department.
[wait][clear][end]

msg_40:
[color(yellow)]Tamaki[color(white)]
[end]

msg_41:
[tab]You want to enter the sweepstakes?
[end]

msg_42:
[tab]Oh, you want to enter another one?
[end]

msg_43:
[tab]Let’s see, Fantasy World...[delay(30)]
[tab]Oops!! No can do.
[wait][clear][end]

msg_44:
[color(yellow)]Tamaki[color(white)]
[tab]Did you check if you won anything from the
[tab]last sweepstakes? If not, you should do so
[tab]at Kismet’s editorial department.
[wait][clear][end]

msg_45:
[color(yellow)]Tamaki[color(white)]
[tab]Okay, you want to enter, right?
[tab]Hmmm... Battle Master is...[delay(30)]
[tab]For [var(msg_var_1)] magazines, right?
[wait][clear][end]

msg_46:
[color(yellow)]Tamaki[color(white)]
[tab]Send to...
[tab]Kismet Editorial Department...
[wait][clear][end]

msg_47:
[color(yellow)]Tamaki[color(white)]
[end]

msg_48:
[tab]You want to enter the sweepstakes?
[end]

msg_49:
[tab]Oh, you want to enter another one?
[end]

msg_50:
[tab]Hmmm... Miracle magazine is...[delay(30)]
[tab]For [var(msg_var_2)] magazines, right?
[wait][clear][end]

msg_51:
[color(yellow)]Tamaki[color(white)]
[tab]Send to...
[tab]Kismet Editorial Department...
[wait][clear][end]

msg_52:
[color(yellow)]Tamaki[color(white)]
[end]

msg_53:
[tab]You want to enter the sweepstakes?
[end]

msg_54:
[tab]Oh, you want to enter another one?
[end]

msg_55:
[tab]Hmmm... Fantasy World is...[delay(30)]
[tab]For [var(msg_var_3)] magazines, right?
[wait][clear][end]

msg_56:
[color(yellow)]Tamaki[color(white)]
[tab]Send to...
[tab]Kismet Editorial Department...
[wait][clear][end]

msg_57:
[tab]Are you sure?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_58:
[color(yellow)]Tamaki[color(white)]
[tab]Roger!
[tab]I’ll send it in.
[tab]Hope you win something!
[wait][clear][end]

msg_59:
[color(yellow)]Tamaki[color(white)]
[tab]Roger! I’ll send it in.
[tab]Let’s see, what else is there...?
[wait][clear][end]

msg_60:
[color(yellow)]Tamaki[color(white)]
[tab]Roger! I’ll send it in.
[tab]Let’s see, what else is there...?
[wait][clear][end]

msg_61:
[color(yellow)]Tamaki[color(white)]
[tab]Roger!
[tab]Come back when you want to enter.
[wait][clear][end]

msg_62:
[color(yellow)]Tamaki[color(white)]
[tab]Roger!
[tab]Come back when you want to enter.
[tab]Let’s see, what else is there...?
[wait][clear][end]

msg_63:
[color(yellow)]Tamaki[color(white)]
[tab]Roger!
[tab]Come back when you want to enter.
[tab]Let’s see, what else is there...?
[wait][clear][end]

msg_64:
[color(yellow)]Tamaki[color(white)]
[tab]Okay![delay(30)]
[tab]...But you don’t have any magazines...
[tab]Buy them at Satomi Tadashi.
[wait][clear][end]

msg_65:
[color(yellow)]Tamaki[color(white)]
[tab]...I guess that’s it.
[tab]Hope you win something!
[wait][clear][end]

msg_66:
[color(yellow)]Tamaki[color(white)]
[tab]A sweepstakes is kind of like a raffle. 
[tab]You send in magazines for chances to win a 
[tab]cool prize. It takes luck to win!
[wait][clear][end]

msg_67:
[color(yellow)]Tamaki[color(white)]
[tab]What you do is buy a magazine at Satomi
[tab]Tadashi and give the magazine to me. 
[tab]I send it in, and you check at Kismet.
[wait][clear][end]

msg_68:
[color(yellow)]Tamaki[color(white)]
[tab]Now, you can enter a particular sweepstakes
[tab]only once. You must check the results before
[tab]entering the next one. ...Why? Because!
[wait][clear][end]

msg_69:
[color(yellow)]Tamaki[color(white)]
[tab]You can enter up to 99 magazines at once.
[tab]The more you send in, the better your
[tab]chances of winning. More is better!
[wait][clear][end]

msg_70:
[color(yellow)]Tamaki[color(white)]
[tab]There’s a wait before the results come in.
[tab]You can’t just stand there... Go explore
[tab]dungeons and such before checking back.
[wait][clear][end]

msg_71:
[color(yellow)]Tamaki[color(white)]
[tab]The rest is perseverance and luck!
[tab]Be hopeful and you might be able to
[tab]get a rare item...
[wait][clear][end]

msg_72:
[color(yellow)]Tamaki[color(white)]
[tab]Huh...? Did something happen recently?
[tab]...You’ve become so pretty!
[wait][clear][end]

msg_73:
[color(yellow)]Tamaki[color(white)]
[tab]Oh, I know... Hmm, I see...
[tab]Just kidding!! Teehee...
[wait][clear][end]

msg_74:
[color(yellow)]Tamaki[color(white)]
[tab]I never thought a rumor would become real.
[tab]But, anything can happen these days!!
[tab]And only the young can keep up...
[wait][clear][end]

msg_75:
[color(yellow)]Tamaki[color(white)]
[tab]He said an assassin was after him, 
[tab]but was it the Joker?
[tab]...Who’d waste their time to curse him?
[wait][clear][end]

msg_76:
[color(yellow)]Tamaki[color(white)]
[tab]Oh, don’t worry.
[tab]I’m just talking to myself...
[wait][clear][end]

msg_77:
[color(yellow)]Tamaki[color(white)]
[tab]We’re doing everything to find out, but
[tab]nothing yet. Does it have anything
[tab]to do with the rise in missing people?
[wait][clear][end]

msg_78:
[color(yellow)]Tamaki[color(white)]
[tab]"New World Order"? Never heard of them, but
[tab]they’re all VIP-types, right? ...Then, I’m
[tab]sure their weak points can be found soon.
[wait][clear][end]

msg_79:
[color(yellow)]Tamaki[color(white)]
[tab]Hey, is that you, Nanjo-kun?
[tab]Why are you with Amano-san?
[tab]Huh, and Elly? Hmmm, I see...
[wait][clear][end]

msg_80:
[color(yellow)]Tamaki[color(white)]
[tab]Nanjo-kun and Elly are alumni of St. Hermelin also.
[tab]It’s good to see that everybody’s doing fine.
[wait][clear][end]

msg_81:
[color(yellow)]Tamaki[color(white)]
[tab]Hey, is that you, Elly?
[tab]Why are you with Amano-san?
[tab]Huh, and Nanjo-kun? Hmmm, I see...
[wait][clear][end]

msg_82:
[color(yellow)]Tamaki[color(white)]
[tab]Nanjo-kun and Elly are alumni of St. Hermelin also.
[tab]It’s good to see that everybody’s doing fine.
[wait][clear][end]

msg_83:
[color(yellow)]Tamaki[color(white)]
[tab]Let me know if you need help.
[tab]I will help you as much as I can.
[tab][delay(30)]...Only what I can, okay?
[wait][clear][end]

msg_84:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Let me start over... How do you do, meow?
[tab]I’m the rumor-loving Nekomata, meow.
[tab]I collect rumors unknown to humans, meow.
[wait][clear][end]

msg_85:
[color(yellow)]Nekomata[color(green)]
[tab]Demon friend of the Devil Summoner Tamaki.
[tab]Likes pranks and has a weakness for money.
[tab]She knows much about rumors among demons.[color(white)]
[wait][clear][end]

msg_86:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]By the way...
[tab]What do you need today, meow?
[wait][clear][end]

msg_87:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Meow! You’ve come again, meow!?
[tab]Did you want to hear my story, meow?
[tab]But, [delay(30)]don’t forget to knock, meow!
[wait][clear][end]

msg_88:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]By the way...
[tab]What do you need today, meow?
[wait][clear][end]

msg_89:
[tab]What do you need today, meow?
[choice(3)]I want to hear rumors
I want to talk to you
Nothing
[end_choice][clear][end]

msg_90:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]I don’t have any more rumors to tell, meow.
[tab]...Sorry, meow.
[wait][clear][end]

msg_91:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]You want to hear a rumor, meow?
[tab]Let’s see, meow.
[tab]You tell me a rumor also, meow!
[wait][clear][end]

msg_92:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]You want me to tell you a rumor, meow!?
[tab]Then, tell me a rumor also, meow!
[tab]We’ll trade information, meow!
[wait][clear][end]

msg_93:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]My information is special, meow♥
[tab]You have a rumor that will match it, meow?
[wait][clear][end]

msg_94:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Is, is that true, meow!? 
[tab]I’ve just heard something big, meow! 
[tab]As promised, I will tell you also, meow.
[wait][clear][end]

msg_95:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Oh, a rumor about THAT person, meow?
[tab]Hmmm, humans are strange, meow.
[tab]Now, it’s my turn, meow♥
[wait][clear][end]

msg_96:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]I hear that rumor a lot, meow.
[tab]But I guess that’s good enough for
[tab]today, meow.
[wait][clear][end]

msg_97:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]You know a demon [color(orange)]Trish[color(white)], meow?
[tab]I heard she’s [color(orange)]reformed[color(white)]!
[tab]I just can’t believe it, meow.
[wait][clear][end]

msg_98:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]You know a store [color(orange)]Kaori[color(white)], meow? Then,
[tab]do you know they [color(orange)]started aromatherapy[color(white)]?
[tab]I’m surprised that it works, meow!
[wait][clear][end]

msg_99:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]That suspicious shop... What was it, meow?
[tab]Oh yeah! The beauty spa [color(orange)]Etheria[color(white)] has a
[tab][color(orange)]new beauty treatment[color(white)]. I’m excited, meow.
[wait][clear][end]

msg_100:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Have you ever met [color(orange)]Trish[color(white)], meow?
[tab]Rumor is that [color(orange)]she’s started to sell
[tab]ice cream[color(white)] in the dungeon for a profit, meow.
[wait][clear][end]

msg_101:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Did you know? Tamaki-chan’s actually
[tab]a devil summoner, meow.
[tab]And I’m Tamaki-chan’s demon friend, meow.
[wait][clear][end]

msg_102:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Jokers overwork demons, meow. That’s
[tab]why I hate them. They piss me off, meow!!
[tab]We can’t have more of ’em, meow.
[wait][clear][end]

msg_103:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Ahhh!! Did you know, meow!? Your new
[tab]friend is a Persona user, meow!!
[tab]What, you knew? Awww, phooey, meow.
[wait][clear][end]

msg_104:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Demons are being neglected recently,
[tab]meow. What do you think of us demons?
[tab]You used to call us "comrades", meow?
[wait][clear][end]

msg_105:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]See you later, meow♥
[wait][clear][end]

msg_106:
[color(yellow)]Makimura[color(white)]
[tab]Investigative agency? You intend
[tab]to look into my past affairs?
[tab]And even other crimes, Mr. Cop?
[wait][clear][end]

msg_107:
[color(yellow)]Chief Todoroki[color(white)]
[tab]So you’re here...

[wait][clear][end]

msg_108:
[color(yellow)]Chief Todoroki[color(white)]
[tab]Hey, you’re here. What’s wrong?
[tab]Is something troubling you? ...Okay,
[tab]I’ll help you today as a favor.
[wait][clear][end]

msg_109:
[color(yellow)]Chief Todoroki[color(white)]
[tab]But, the fee is as per usual.
[tab]You know, it’s all in the heart...
[wait][clear][end]

msg_110:
[color(yellow)]Chief Todoroki[color(white)]
[tab]What business do you have with
[tab]us today?
[choice(5)]Spread rumors
Check Rumors
Talk with the Chief
Cancel
Leave the detective agency
[end_choice][clear][end]

msg_111:
[color(yellow)]Chief Todoroki[color(white)]
[tab]What’s on your mind?
[choice(3)]Make small talk
Ask about rumors
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_112:
[color(yellow)]Chief Todoroki[color(white)]
[tab]Anything else?
[choice(5)]Spread rumors
Check Rumors
Talk with the Chief
Cancel
Leave the detective agency
[end_choice][clear][end]

msg_113:
[color(yellow)]Chief Todoroki[color(white)]
[tab]What’s on your mind?
[choice(3)]Make small talk
Ask about rumors
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_114:
[color(yellow)]Chief Todoroki[color(white)]
[tab]Rumors don’t spread that easily...
[tab]It’s closely related to the mentality of
[tab]the people who hear and talk about them.
[wait][clear][end]

msg_115:
[color(yellow)]Chief Todoroki[color(white)]
[tab]There are rumormongers in this town...
[tab]Their on-hand rumors could be easily
[tab]spread among people and materialize.
[wait][clear][end]

msg_116:
[color(yellow)]Chief Todoroki[color(white)]
[tab]Look at the big picture. There’s always
[tab]something behind this chain of commotions.
[tab]Keep that in mind...
[wait][clear][end]

msg_117:
[color(yellow)]Chief Todoroki[color(white)]
[tab]If more people are becoming Jokers, 
[tab]this town should become even more chaotic...
[tab]Then how come it’s still relatively quiet?
[wait][clear][end]

msg_118:
[color(yellow)]Chief Todoroki[color(white)]
[tab]New World Order... The organization behind
[tab]the incident... Sounds interesting.
[tab]Shall we do some research?
[wait][clear][end]

msg_119:
[color(yellow)]Chief Todoroki[color(white)]
[tab]Tamaki and your friend knew each other,
[tab]huh... What a small world.
[tab]That would never happen to me, though...
[wait][clear][end]

msg_120:
[color(yellow)]Chief Todoroki[color(white)]
[tab]We can only help you manipulate rumors.
[tab]The rest is up to you.
[tab]Then... see you later.
[wait][clear][end]

msg_121:
[color(yellow)]Chief Todoroki[color(white)]
[tab]The sweepstakes... I see.
[tab]You should ask Tamaki about that.
[tab]Discuss it with her.
[wait][clear][end]

msg_122:
[color(yellow)]Lucky Cat[color(white)]
[tab]Long time no see, meow♥
[tab]Adults insert ¥1000, meow♥
[wait][clear][end]

msg_123:
[color(yellow)]Lucky Cat[color(white)]
[tab]Adults insert ¥1000, meow♥
[wait][clear][end]

msg_124:
[tab]Please insert ¥1000, meow♥
[choice(2)]Insert
Don’t insert
[end_choice][clear][end]

msg_125:
[color(yellow)]Lucky Cat[color(white)]
[tab]You don’t have any money, meow♥
[tab]Lying is the root of evil, meow♥
[tab]You’re days late and dollars short♥
[wait][clear][end]

msg_126:
[color(yellow)]Lucky Cat[color(white)]
[tab]I’m impressed, meow♥[delay(15)]
[tab]Received ¥1000 20 times already, meow![delay(15)]
[tab]I’ll expect more from now on, meow♥
[wait][clear][end]

msg_127:
[color(yellow)]Lucky Cat[color(white)]
[tab]Meow meow meow♥[delay(15)]
[tab]Received ¥1000 50 times already, meow![delay(15)]
[tab]How generous, onee-san! Meow♥
[wait][clear][end]

msg_128:
[color(yellow)]Lucky Cat[color(white)]
[tab]Wonderful! Great! Meowww.[delay(15)]
[tab]Received ¥1000 80 times already, meow♥[delay(15)]
[tab]Are you scheming something, meow?
[wait][clear][end]

msg_129:
[color(yellow)]Lucky Cat[color(white)]
[tab]Thank you, meow♥
[wait][clear][end]

msg_130:
[color(yellow)]Lucky Cat[color(white)]
[tab]...[delay(15)]Cheaps-cat.
[wait][clear][end]

msg_131:
[color(yellow)]Lucky Cat[color(white)]
[tab]Finally the time has come, meow...[delay(15)]
[tab]The commemorative 100th time...[delay(15)]
[tab]I’ve saved up ¥100000, meow!
[wait][clear][end]

msg_132:
[color(yellow)]Lucky Cat[color(white)]
[tab]I feel guilty from receiving your
[tab]contributions for nothing, meow.[delay(30)]
[tab]So... [delay(15)]come over here, meow!
[wait][clear][end]

msg_133:
[color(yellow)]Lucky Cat[color(white)]
[tab]Over here, over here, meow♥
[wait][clear][end]

msg_134:
[color(yellow)]Lucky Cat[color(white)]
[tab]Don’t you understand, meow?
[tab]Over here, over here, meow!!
[wait][clear][end]

msg_135:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Nice to meet you... [delay(30)]Meow meow!!
[wait][clear][end]

msg_136:
[color(yellow)]Tamaki[color(white)]
[tab]Hey! What are you doing!?
[wait][clear][end]

msg_137:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]Ta, [delay(30)]Tamaki-chan!!
[tab]S... Sorry, meow.
[tab]I was so bored... I...
[wait][clear][end]

msg_138:
[color(yellow)]Tamaki[color(white)]
[tab]I’m sorry, Maya-san.
[tab]She just likes playing tricks on people.
[wait][clear][end]

msg_139:
[color(yellow)]Tamaki[color(white)]
[tab]Geez!!
[tab]Apologize to Maya-san too!
[tab]...My gosh!
[wait][clear][end]

msg_140:
[color(yellow)]Demon Rumormonger Nekomata[color(white)]
[tab]S-So-wee... As a token of
[tab]apology, I’ll tell you my most
[tab]treasured rumor, meow!
[wait][clear][end]

msg_141:
[color(yellow)]Lucky Cat[color(white)]
[tab]That probably won’t open, meow.
[sync][wait][clear][end]

msg_142:
懸賞の噂依頼
びっとお~んッ!!
[wait][clear][end]

msg_143:
懸賞本[tab]99・0・99
[wait][clear][end]

msg_144:
懸賞本[tab]1・50・0
ミラクル応募可
[wait][clear][end]

msg_145:
ネコカウント49増加
[wait][clear][end]

msg_146:
ネコカウント
さらに49増加
[wait][clear][end]

msg_147:
MBIT[tab]AIS[tab]19
相性占いの
びっとお~んッ!!
[wait][clear][end]

msg_148:
MBIT[tab]AIS[tab]25
相性占いの
びっとお~んッ!!
[wait][clear][end]

msg_149:
EBIT[tab]E0015
7姉妹学園クリア
びっとお~んッ!!
[wait][clear][end]

msg_150:
EBIT[tab]E0018
バー終了・Baofu初参加
びっとお~んッ!!
[wait][clear][end]

msg_151:
EBIT[tab]E0033
「Baofu編入」
びっとお~んッ!!
[wait][clear][end]

msg_152:
EBIT[tab]E0037
警察署[half_tab]受付、終了
びっとお~んッ!!
[wait][clear][end]

msg_153:
EBIT[tab]E0038
「詐欺男を確保」
びっとお~んッ!!
[wait][clear][end]

msg_154:
EBIT[tab]E003E
「ゴールドクリア」「Ulala編入」
びっとお~んッ!!
[wait][clear][end]

msg_155:
EBIT[tab]E0043
「クラブクリア」
びっとお~んッ!!
[wait][clear][end]

msg_156:
EBIT[tab]E0044
「青葉公園クリア」
びっとお~んッ!!
[wait][clear][end]

msg_157:
EBIT[tab]E0046
「南条orエリー編入」
びっとお~んッ!!
[wait][clear][end]

msg_158:
EBIT[tab]E006F
「研究施設・TV局クリア」
びっとお~んッ!!
[wait][clear][end]

msg_159:
[color(yellow)]Chief Todoroki[color(white)]
[tab]Want the lowdown on rumors?
[wait][clear][color(yellow)]Chief Todoroki[color(white)]
[tab]Ask me to spread a rumor of your choice and
[tab]I’ll do it. Not for free, mind you.
[wait][clear][color(yellow)]Chief Todoroki[color(white)]
[tab]You’ll need to bring me rumors you hear from
[tab]rumormongers.
[wait][clear][color(yellow)]Chief Todoroki[color(white)]
[tab]There are rumormongers everywhere in Sumaru.
[tab]Dig a little and you’ll find them.
[wait][clear][color(yellow)]Chief Todoroki[color(white)]
[tab]You can remind yourself which rumors are
[tab]already circulating by asking me to Check
[tab]rumors.
[wait][clear][color(yellow)]Chief Todoroki[color(white)]
[tab]Not only can you remember which rumors I’ve
[tab]been putting out there for you, you can see
[tab]which ones demons are spreading.
[wait][clear][end]

msg_160:
[color(yellow)]Bookshelf[color(white)]
[tab][color(green)]A sliding bookshelf.
[tab]It looks like it can move...[color(white)]
[wait][clear][end]

msg_161:
[color(yellow)]Bookshelf[color(white)]
[tab][color(green)]A sliding shelf, but it doesn’t seem to move.[color(white)]
[wait][clear][end]

msg_162:
[color(yellow)]Bookshelf[color(white)]
[tab][color(green)]A sliding shelf, but it doesn’t seem to move.[color(white)]
[wait][clear][end]

msg_163:
[color(yellow)]Bookshelf[color(white)]
[tab][color(green)]Maya got [item_with_type(item_fffe)].[color(white)]
[wait][clear][end]

msg_164:
[color(yellow)]Chief Todoroki[color(white)]
[tab]I need ¥[var(msg_var_0)] to spread this rumor.
[tab]Do you want me to do it?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_165:
[color(yellow)]Chief Todoroki[color(white)]
[tab]I need ¥[var(msg_var_0)] to spread this rumor.
[tab]Do you want me to do it?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_166:
[color(yellow)]Chief Todoroki[color(white)]
[tab]I don’t know the outcome of this rumor...
[tab]I need ¥[var(msg_var_0)] to spread this rumor.
[tab]Do you want me to do it?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_167:
[color(yellow)]Chief Todoroki[color(white)]
[tab]You don’t have enough money. [wait][clear][end]
