
msg_0:
There is more than 4 members in the party.
[tab]It will hang at this rate.
[tab]Please inform Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]...I’ve never seen a dead body before...
[tab]I’m speechless...
[tab]To think if I knew the person... Eew!!
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya! An ether treatment.
[tab]Ahahahaha! That’s so fishy, isn’t it?
[tab]You want to give it a try?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]It’s about the inside of a person, inside!
[tab]Men and women are both about the inside!
[tab]This is the lesson of the day!
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Anna-chan and [tatsuya]-kun seemed very close.
[tab]Looks like they used to go to clubs together.
[tab]What do you think of that?
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]That Sneak person said something important
[tab]to [suou]-san, didn’t he? ...Something about
[tab]ending up just like his dad. What was that?
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Huh, you’ve been stalked before? 
[tab]A middle-aged... naked man... running around... 
[tab]at night? ...Ma-ya, that’s called "streaking".
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Police work is nothing flashy. Many people
[tab]confuse it with TV dramas. ...Do you think
[tab]a murder case occurs every week?
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]As Serizawa-kun says, it does seem abnormal... 
[tab]Could they have been running business illegally?
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]I had a feeling there was something behind
[tab]Serizawa-kun’s bright personality...
[tab]I hope she does not make any mistakes.
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Maybe not beauty spa, but men wear make-up
[tab]nowadays too. I even trim my eye brows...
[tab]Baofu’s a rather "old-fashioned" guy.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]How touching... Serizawa-kun... I guess she
[tab]can think of it as a costly bride training...
[tab]No, I’m not thinking of forgiving a criminal.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya] was going in and out of that club...
[tab]I thought I understood about my brother,
[tab]but I actually... knew nothing.
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Father was...
[tab]...My father was...
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]Not many women can handle stalkers alone,
[tab]like Kirishima-kun can. The law must crack
[tab]down on them, or else there’ll be more victims.
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]If you ask me, beauty spas are suspicious.
[tab]All they’re doing is soothing customer’s
[tab]complexes... It’s the same as drinking.
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab][suou]! HEY, [suou]!!
[tab]...Amano, it doesn’t look like [suou] is here!
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]Even Serizawa would have a shady side.
[tab]Getting caught up in a marriage scam is a
[tab]part of it. Nowadays, everyone has problems.
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]They didn’t have beauty spa for men when I
[tab]was young. You even needed guts just to buy
[tab]men’s cologne. ...What happened to manliness?
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]People all grow from getting hurt.
[tab]If it taught you a lesson, at least you
[tab]got something out of it.
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]The older brother’s love isn’t reaching the younger. 
[tab]Maybe that love is just the elder’s ego? 
[tab]It’s important to see both ends...
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab][suou]!
[tab]Talking to people about it won’t
[tab]solve it, right?
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]Or, do you just want to tell someone to make
[tab]yourself feel better? In that case, you’re not
[tab]taking life seriously at all!
[wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]It’s too bad for that stalker to target
[tab]a Persona user... I guess if he had known,
[tab]he wouldn’t have in the first place.
[wait][clear][end]

msg_24:
[color(yellow)]Nanjo[color(white)]
[tab]I heard that Kirishima was stalked before,
[tab]but what is the motivation for stalkers?
[tab]Just the thrill of chasing after women?
[wait][clear][end]

msg_25:
[color(yellow)]Elly[color(white)]
[tab]I ran into a stalker the other day. I did
[tab]report it to the police, but... Unless
[tab]the law is enforced, it is useless.
[wait][clear][end]

msg_26:
[color(yellow)]Young Woman[color(white)]
[tab]"Luck is at the recently-rumored store", huh...
[tab]According to Wang Long, this is the lucky place! 
[tab]But... What’s "ether aesthetics"?
[wait][clear][end]

msg_27:
[color(yellow)]Young Woman[color(white)]
[tab]This beauty spa isn’t just for beauty.
[tab]They treat wounds and improve your health.
[tab]Amazing! I’m glad I trusted Wang Long.
[wait][clear][end]

msg_28:
[color(yellow)]Young Woman[color(white)]
[tab]What’s up with that scary lady?
[tab]Why is she so mad?
[wait][clear][end]

msg_29:
[color(yellow)]Young Woman[color(white)]
[tab]...Wh-What the... She’s staring at me.
[wait][clear][end]

msg_30:
[color(yellow)]Young Woman[color(white)]
[tab]That lady that was there, could it be...
[tab]She did the Joker curse? She was about
[tab]to turn into a killer! Scary!
[wait][clear][end]

msg_31:
[color(yellow)]Young Woman[color(white)]
[tab]I’m so glad "ether aesthetics" are powered
[tab]up more than ever! But what does it mean
[tab]for "demon-like" enemies?
[wait][clear][end]

msg_32:
[color(yellow)]Young Woman[color(white)]
[tab]This store changed to make itself
[tab]different from other stores... It seemed
[tab]different enough the way it was, huh?
[wait][clear][end]

msg_33:
[color(yellow)]Model[color(white)]
[tab]I work as a model, but it’s a very
[tab]competitive world... It’s more like a battle...
[tab]You can’t get by on just looks.
[wait][clear][end]

msg_34:
[color(yellow)]Model[color(white)]
[tab]Ahh, if the lively dragon didn’t move, I’d been... 
[tab]Wang Long is too accurate! That’s it...
[tab]The end justifies the means! I’m gonna do it!
[wait][clear][end]

msg_35:
[color(yellow)]Model[color(white)]
[tab]Huh? Why am I at a beauty spa?
[tab]To become beautiful, of course! I will do
[tab]anything to become a supermodel!
[wait][clear][end]

msg_36:
[color(yellow)]Model[color(white)]
[tab]Gaaaa! Why can’t it be done!?
[tab]It’s easy to fix a nose, is it not!?
[tab]Wasn’t "ether aesthetics" almighty!?
[wait][clear][end]

msg_37:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]Lately, there are women who start to shine
[tab]after the age of thirty, don’t you think?
[tab]Like that actress, Junko Kurosu.
[wait][clear][end]

msg_38:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]Nothing good comes from blaming everything
[tab]on your age. I decided to give it a shot
[tab]by coming here.
[wait][clear][end]

msg_39:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]A first rate actress and a good mother...
[tab](sigh) How does she do it?
[tab]Kurosu-san... She’s an incredible person.
[wait][clear][end]

msg_40:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]Will you listen? I wanted to escape from
[tab]everyday life to find a new identity...
[tab]I moved here to become my ideal person.
[wait][clear][end]

msg_41:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]I was hasty, thinking if I didn’t act fast,
[tab]then the time would just fly by... Is that
[tab]foolish of me? But you understand, don’t you?
[wait][clear][end]

msg_42:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]What is the motive for people in using the
[tab]Joker curse? What changes by its use?
[tab]I too... No, I must live more positively!
[wait][clear][end]

msg_43:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]Ahh, I was a fool only caring about myself.
[tab]Everything is for a world without Kegare.
[wait][clear][end]

msg_44:
[color(yellow)]Middle-Aged Woman[color(white)]
[tab]...Let’s think positive!
[wait][clear][end]

msg_45:
[color(yellow)]Makimura[color(white)]
[tab]Beauty spa... Nice. Making women in this
[tab]world as beautiful as possible...
[tab]Of course I use the ones for men.
[wait][clear][end]

msg_46:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥

[wait][clear][end]

msg_47:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥
[tab]You’re from that magazine place, right?
[tab]...You are! That’s great!!
[wait][clear][end]

msg_48:
[color(yellow)]Esthetician[color(white)]
[tab]Today, I want to give a special discount.
[tab]No special reason, I just want you to get
[tab]beautiful at this spa♥
[wait][clear][end]

msg_49:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥
[tab]We started some new treatments this week.
[tab]Please give one a try.
[wait][clear][end]

msg_50:
[color(yellow)]Esthetician[color(white)]
[tab]We have special results only available from
[tab]this spa! Every treatment brings out your
[tab]charm. No demon will be a match for you!!
[wait][clear][end]

msg_51:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥ We started some new
[tab]treatments this week. Of course they have
[tab]special results, exclusive to this spa!
[wait][clear][end]

msg_52:
[color(yellow)]Esthetician[color(white)]
[tab]Every treatment brings out your charm.
[tab]No demon will be a match for you!!
[tab]...I’ll cut you a deal!
[wait][clear][end]

msg_53:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥
[tab]Thank you for choosing us.
[tab]You’ve come at a very good time.
[wait][clear][end]

msg_54:
[color(yellow)]Esthetician[color(white)]
[tab]Today, ether aesthetics is powered up!!
[tab]The prices? ...Do not worry!
[tab]The prices are... the same as always!
[wait][clear][end]

msg_55:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥
[tab]Thank you for choosing us.
[tab]You’ve come at a very good time.
[wait][clear][end]

msg_56:
[color(yellow)]Esthetician[color(white)]
[tab]Today, ether aesthetics is powered up!!
[tab]Of course, the prices are no different!
[tab]...I’ll cut you a deal!
[wait][clear][end]

msg_57:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥
[tab]Thank you for choosing us.
[tab]You’ve come at a very good time.
[wait][clear][end]

msg_58:
[color(yellow)]Esthetician[color(white)]
[tab]Today, ether aesthetics is powered up!!
[tab]The treatments are enhanced further.
[tab]But, we stopped the men’s line. Sorry♥
[wait][clear][end]

msg_59:
[color(yellow)]Esthetician[color(white)]
[tab]Welcome to Etheria♥
[tab]Thank you for choosing us.
[tab]You’ve come at a very good time.
[wait][clear][end]

msg_60:
[color(yellow)]Esthetician[color(white)]
[tab]Today, ether aesthetics is powered up! 
[tab]The treatments are enhanced. I’ll cut you a
[tab]deal, but no more men’s line. Sorry♥
[wait][clear][end]

msg_61:
[color(yellow)]Esthetician[color(white)]
[tab]What can we do for you today?
[choice(4)]Heal
Talk to the esthetician
Never mind
Leave
[end_choice][clear][end]

msg_62:
[color(yellow)]Esthetician[color(white)]
[tab]Ask away.
[choice(2)]Make small talk
Ask about treatments
[end_choice][clear][end]

msg_63:
[color(yellow)]Esthetician[color(white)]
[tab]What can we do for you today?
[choice(5)]Heal
Treatment
Talk to the esthetician
Never mind
Leave
[end_choice][clear][end]

msg_64:
[color(yellow)]Esthetician[color(white)]
[tab]Ask away.
[choice(2)]Make small talk
Ask about treatments
[end_choice][clear][end]

msg_65:
[color(yellow)]Esthetician[color(white)]
[tab]Fusing the names "ether" and "materia"...
[tab]That is "Etheria". Isn’t it wonderful?
[tab]...Can I help you with anything else?
[choice(4)]Heal
Talk to the esthetician
Never mind
Leave
[end_choice][clear][end]

msg_66:
[color(yellow)]Esthetician[color(white)]
[tab]Ask away.
[choice(2)]Make small talk
Ask about treatments
[end_choice][clear][end]

msg_67:
[color(yellow)]Esthetician[color(white)]
[tab]Fusing the names "ether" and "materia"...
[tab]That is "Etheria". Isn’t it wonderful?
[tab]...Can I help you with anything else?
[choice(5)]Heal
Treatment
Talk to the esthetician
Never mind
Leave
[end_choice][clear][end]

msg_68:
[color(yellow)]Esthetician[color(white)]
[tab]Ask away.
[choice(2)]Make small talk
Ask about treatments
[end_choice][clear][end]

msg_69:
[color(yellow)]Esthetician[color(white)]
[tab]We work on ether, which is the life source,
[tab]and activate the beauty process of the body.
[tab]That’s why it is so effective.
[wait][clear][end]

msg_70:
[color(yellow)]Esthetician[color(white)]
[tab]We even combine it with alchemy to treat not
[tab]only beauty, but wounds and illness as well!
[tab]That’s right, it’ll fix anything!
[wait][clear][end]

msg_71:
[color(yellow)]Esthetician[color(white)]
[tab]Are you doubting the effects?  
[tab]Everyone does at first. But the rumors are true... 
[tab]The curing methods have already been proven.
[wait][clear][end]

msg_72:
[color(yellow)]Esthetician[color(white)]
[tab]Some customers misunderstand. They ask us
[tab]to fix their nose, or make them taller...
[tab]They’re mixing up beauty with surgery.
[wait][clear][end]

msg_73:
[color(yellow)]Esthetician[color(white)]
[tab]Word of mouth is incredible. With a little
[tab]bit, business picks up so much... And now,
[tab]we can heal wounds and illness as well.
[wait][clear][end]

msg_74:
[color(yellow)]Esthetician[color(white)]
[tab]Lately, there’s a lot of competition in this
[tab]industry. So we specialized in just women
[tab]to distinguish ourselves... Was it wrong?
[wait][clear][end]

msg_75:
[color(yellow)]Esthetician[color(white)]
[tab]Competition in this industry is toughening.
[tab]We try our best to be different... We still
[tab]have low prices compared to other stores.
[wait][clear][end]

msg_76:
[color(yellow)]Esthetician[color(white)]
[tab]If you ever get ill, don’t wait to stop
[tab]by. You too can gain beauty and health
[tab]from ether aesthetics.
[wait][clear][end]

msg_77:
[color(yellow)]Esthetician[color(white)]
[tab]Hmm...? But everyone looks so
[tab]healthy. I don’t see why
[tab]you would want to get treatment...
[wait][clear][end]

msg_78:
[color(yellow)]Esthetician[color(white)]
[tab]I understand.
[tab]Hmm... Let’s see...
[tab]It’ll be ¥3000 for everyone.
[wait][clear][end]

msg_79:
[color(yellow)]Esthetician[color(white)]
[tab]I understand.
[tab]Hmm... Let’s see... Okay! I’ll make it
[tab]¥1,500. Of course, for everyone♥
[wait][clear][end]

msg_80:
[color(yellow)]Esthetician[color(white)]
[tab]Is this good?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_81:
[color(green)]Maya and the party got healed.[color(white)][wait][clear][end]

msg_82:
[color(yellow)]Esthetician[color(white)]
[tab]Oh, my! It looks like you don’t
[tab]have enough money...
[tab]I mean, this is business. Sorry♥
[wait][clear][end]

msg_83:
[color(yellow)]Esthetician[color(white)]
[tab]Huh? ...Why?
[tab]You don’t trust ether aesthetics?
[tab]Believers will be saved. No, really.
[wait][clear][end]

msg_84:
[color(yellow)]Esthetician[color(white)]
[tab]Okay! Now, relax...[delay(15)]
[tab]This is our original treatment!
[tab]"ether aesthetics"!
[wait][clear][end]

msg_85:
噂によりエステ開始
びっとお~んッ!!
[wait][clear][end]

msg_86:
変異噂の
びっとお~んッ!!
[wait][clear][end]

msg_87:
MBIT[tab]AIS[tab]65
相性占いの
びっとお~んッ!!
[wait][clear][end]

msg_88:
EBIT[tab]E0015
7姉妹学園クリア
びっとお~んッ!!
[wait][clear][end]

msg_89:
EBIT[tab]E0018
バー終了・Baofu初参加
びっとお~んッ!!
[wait][clear][end]

msg_90:
EBIT[tab]E0033
「Baofu編入」
びっとお~んッ!!
[wait][clear][end]

msg_91:
EBIT[tab]E0037
警察署[half_tab]受付、終了
びっとお~んッ!!
[wait][clear][end]

msg_92:
EBIT[tab]E0038
「詐欺男を確保」
びっとお~んッ!!
[wait][clear][end]

msg_93:
EBIT[tab]E003E
「ゴールドクリア」「Ulala編入」
びっとお~んッ!!
[wait][clear][end]

msg_94:
EBIT[tab]E0043
「クラブクリア」
びっとお~んッ!!
[wait][clear][end]

msg_95:
EBIT[tab]E0044
「青葉公園クリア」
びっとお~んッ!!
[wait][clear][end]

msg_96:
EBIT[tab]E0046
「南条orエリー編入」
びっとお~んッ!!
[wait][clear][end]

msg_97:
EBIT[tab]E006F
「研究施設・TV局クリア」
びっとお~んッ!!
[wait][clear][end]

msg_98:
[color(yellow)]Esthetician[color(white)]
[tab]Ask away.
[choice(3)][if_all(MBIT_KE_ETEESTHE)]Ask about treatment
Ask about healing
Nothing
[end_choice][clear][end]

msg_99:
[color(yellow)]Esthetician[color(white)]
[tab]Okay! I’ll explain our special treatments.
[wait][clear][color(yellow)]Esthetician[color(white)]
[tab]If you request the esthetic "Treatment"
[tab]your charm will increase.
[wait][clear][color(yellow)]Esthetician[color(white)]
[tab]As a result you will be more popular
[tab]with certain types.
[wait][clear][color(yellow)]Esthetician[color(white)]
[tab]Like being more appealing to old people or youths.
[tab]Isn’t it amazing?
[wait][clear][color(yellow)]Esthetician[color(white)]
[tab]It even works with non-humans!
[wait][clear][end]

msg_100:
[color(yellow)]Esthetician[color(white)]
[tab]Okay! I’ll give you the general outline of
[tab]how we operate.
[wait][clear][color(yellow)]Esthetician[color(white)]
[tab]If you request us to "Heal" you, you can
[tab]recover HP, SP, and be cured of any status
[tab]ailments such as poison.
[wait][clear][color(yellow)]Esthetician[color(white)]
[tab]There is a cost involved, but our methods
[tab]affect all of you at once. Believe me, in
[tab]the long run, you’ll save money.
[wait][clear][end]

msg_101:
[color(yellow)]Esthetician[color(white)]
[tab]That will be ¥[var(msg_var_0)] for the whole group. 
[tab]Do you accept?
[choice(2)]Yes
No
[end_choice][clear][end]
