function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    levelFootstepSet(sfx_15);
    sndMusicPlay(sound_3023, 127);
    envTriggerSet(DOORBOX, 131, 1, line, coll_22);
    envTriggerSet(CDBOX, 224, 1, line, coll_25);
    li(var_0, 0);
    partyMemberCheck(var_0, ulala);
    add(var_5, var_5, var_0);
    bez(var_0, label_10);
    ref_a = spriteLoad(sprite_6);
    wait(ref_a);
    unitSpawn(ulala, sprite_6, 282, 0, -347, north, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
    envTriggerSet(URARAIKARI, 14, 1, line, coll_21);
    b(label_11);
  label_10:
    envTriggerSet(KAGIGA, 14, 1, line, coll_21);
  label_11:
    partyMemberCheck(var_0, katsuya);
    add(var_5, var_5, var_0);
    bez(var_0, label_18);
    ref_14 = spriteLoad(sprite_d);
    wait(ref_14);
    unitSpawn(katsuya, sprite_d, 748, 0, -714, east, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_18:
    partyMemberCheck(var_0, baofu);
    add(var_5, var_5, var_0);
    bez(var_0, label_1f);
    ref_1b = spriteLoad(sprite_13);
    wait(ref_1b);
    unitSpawn(baofu, sprite_13, 500, 0, -979, west, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_1f:
    partyMemberCheck(var_0, nanjo);
    add(var_5, var_5, var_0);
    bez(var_0, label_26);
    ref_22 = spriteLoad(sprite_1f);
    wait(ref_22);
    unitSpawn(nanjo, sprite_1f, 216, 0, -776, north, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
  label_26:
    partyMemberCheck(var_0, elly);
    add(var_5, var_5, var_0);
    bez(var_0, label_2d);
    ref_29 = spriteLoad(sprite_23);
    wait(ref_29);
    unitSpawn(elly, sprite_23, 469, 0, -342, south, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
  label_2d:
    partyMemberCheck(var_0, tatsuya);
    add(var_5, var_5, var_0);
    bez(var_0, label_34);
    ref_30 = spriteLoad(sprite_18);
    wait(ref_30);
    unitSpawn(tatsuya, sprite_18, 711, 0, -861, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
  label_34:
    boutrange(var_5, 0, 4, label_37);
    li(var_0, 0);
    b(label_3c);
  label_37:
    ref_37 = dialogAlloc();
    ref_38 = msgShow(msg_0);
/***************************************
There’s more than 4 people in your party.
[tab]At this rate it’ll hang.
[tab]Contact Kaneda or Kataoka.
[wait][clear]
***************************************/
    wait(ref_38);
    dialogFree(ref_37);
    b(label_3c);
  label_3c:
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_44);
    bitGet(var_0, EBIT_E0038);
    bez(var_0, label_44);
    ref_40 = spriteLoad(sprite_6a);
    wait(ref_40);
    unitSpawn(makimura, sprite_6a, 417, 0, -592, north, none);
    unitTriggerSet(makimura, SAGIBOX, 255, 1);
  label_44:
    cameraSet(southeast, 650, 0, -1150);
    ref_45 = spriteLoad(sprite_0);
    wait(ref_45);
    ref_47 = spriteLoad(sprite_2);
    wait(ref_47);
    playerInit(south);
    controlDisable();
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, MBIT_CNT_URARA);
    bez(var_0, label_96);
    bitGet(var_0, MBIT_GAT_URARA_02);
    bez(var_0, label_85);
    bitGet(var_0, EBIT_E003E);
    bnz(var_0, label_75);
    unitFacePlayer(ulala);
    ref_5b = bustupLoad(bustup_17);
    bustupWait(ref_5b);
    ref_5d = bustupAlloc(ref_5b, left, rgb(0,0,0));
    bustupFade(ref_5d, rgb(128,0,0), 30);
    ref_5f = dialogAlloc();
    ref_60 = msgShow(msg_1);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]You know, Ma-ya...
[tab]If you’re going to bring a man into
[tab]your room, at least clean up first...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_60);
    ref_63 = bustupFade(ref_5d, rgb(0,0,0), 10);
    bustupWait(ref_63);
    bustupFree(ref_5d);
    unitAnimationPlay(ulala, animation_a, 1);
    ref_67 = bustupLoad(bustup_1f);
    bustupWait(ref_67);
    ref_69 = bustupAlloc(ref_67, left, rgb(0,0,0));
    bustupFade(ref_69, rgb(128,0,0), 30);
    ref_6b = msgShow(msg_2);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]...No ...forget it. They’re not really the
[tab]type to care about this kind of stuff...
[tab]Half of this is my fault, too...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_6, 1);
    wait(ref_6b);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_5f);
    ref_70 = bustupFade(ref_69, rgb(0,0,0), 10);
    bustupWait(ref_70);
    bustupFree(ref_69);
    unitRestoreFacing(ulala);
    b(label_a6);
  label_75:
    unitFacePlayer(ulala);
    ref_76 = bustupLoad(bustup_18);
    bustupWait(ref_76);
    ref_78 = bustupAlloc(ref_76, left, rgb(0,0,0));
    bustupFade(ref_78, rgb(128,0,0), 30);
    ref_7a = dialogAlloc();
    ref_7b = msgShow(msg_3);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Eh? Don’t smoke in here? ...Don’t be so uptight, 
[tab]Ma-ya... If you worry about little things, 
[tab]you’ll get more wrinkles.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_7b);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_7a);
    ref_80 = bustupFade(ref_78, rgb(0,0,0), 10);
    bustupWait(ref_80);
    bustupFree(ref_78);
    unitRestoreFacing(ulala);
    b(label_a6);
  label_85:
    unitFacePlayer(ulala);
    ref_86 = bustupLoad(bustup_1f);
    bustupWait(ref_86);
    ref_88 = bustupAlloc(ref_86, left, rgb(0,0,0));
    bustupFade(ref_88, rgb(128,0,0), 30);
    ref_8a = dialogAlloc();
    ref_8b = msgShow(msg_4);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Come to think of it, how many years has
[tab]it been since we began rooming together?
[tab]Really, what a rough life...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_8b);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_8a);
    ref_90 = bustupFade(ref_88, rgb(0,0,0), 10);
    bustupWait(ref_90);
    bustupFree(ref_88);
    unitRestoreFacing(ulala);
    bitSet(MBIT_GAT_URARA_02);
    b(label_a6);
  label_96:
    unitFacePlayer(ulala);
    ref_97 = bustupLoad(bustup_18);
    bustupWait(ref_97);
    ref_99 = bustupAlloc(ref_97, left, rgb(0,0,0));
    bustupFade(ref_99, rgb(128,0,0), 30);
    ref_9b = dialogAlloc();
    ref_9c = msgShow(msg_5);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Oh, yeah, I didn’t tell you, but recently
[tab]I’ve started to learn the flamenco dance.
[tab]Wanna see it later? I’m really good♥...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_30, 1);
    wait(ref_9c);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_9b);
    ref_a1 = bustupFade(ref_99, rgb(0,0,0), 10);
    bustupWait(ref_a1);
    bustupFree(ref_99);
    unitRestoreFacing(ulala);
    bitSet(MBIT_CNT_URARA);
  label_a6:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E0037);
    bnz(var_0, label_d1);
    bitGet(var_0, MBIT_LUNATALKKATU);
    bnz(var_0, label_c1);
    ref_ad = bustupLoad(bustup_25);
    bustupWait(ref_ad);
    ref_af = bustupAlloc(ref_ad, left, rgb(0,0,0));
    bustupFade(ref_af, rgb(128,0,0), 30);
    ref_b1 = dialogAlloc();
    unitAnimationPlay(katsuya, animation_21, 1);
    ref_b3 = msgShow(msg_6);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]T... This is... the work of a burglar!?

***************************************/
    wait(ref_b3);
    unitFacePlayer(katsuya);
    unitAnimationPlay(katsuya, animation_2d, 1);
    ref_b7 = msgShow(msg_7);
/***************************************
[tab]Is anything missing? You should
[tab]check immediately. I’ll begin a search!
[wait][clear]
***************************************/
    wait(ref_b7);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_b1);
    ref_bb = bustupFade(ref_af, rgb(0,0,0), 10);
    bustupWait(ref_bb);
    bustupFree(ref_af);
    unitRestoreFacing(katsuya);
    bitSet(MBIT_LUNATALKKATU);
    b(label_e0);
  label_c1:
    unitFacePlayer(katsuya);
    ref_c2 = bustupLoad(bustup_25);
    bustupWait(ref_c2);
    ref_c4 = bustupAlloc(ref_c2, left, rgb(0,0,0));
    bustupFade(ref_c4, rgb(128,0,0), 30);
    ref_c6 = dialogAlloc();
    ref_c7 = msgShow(msg_8);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]What? It was like this to begin with...?
[tab]But... this is just so dreadful...
[tab]Well... But... Was it...?
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_28, 1);
    wait(ref_c7);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_c6);
    ref_cc = bustupFade(ref_c4, rgb(0,0,0), 10);
    bustupWait(ref_cc);
    bustupFree(ref_c4);
    unitRestoreFacing(katsuya);
    b(label_e0);
  label_d1:
    unitFacePlayer(katsuya);
    ref_d2 = bustupLoad(bustup_21);
    bustupWait(ref_d2);
    ref_d4 = bustupAlloc(ref_d2, left, rgb(0,0,0));
    bustupFade(ref_d4, rgb(128,0,0), 30);
    ref_d6 = dialogAlloc();
    ref_d7 = msgShow(msg_9);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]What I’m saying is, our rooms are much cleaner. 
[tab]It might be a bit prejudiced, but
[tab]...a woman should be a bit more... like...
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_d7);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_d6);
    ref_dc = bustupFade(ref_d4, rgb(0,0,0), 10);
    bustupWait(ref_dc);
    bustupFree(ref_d4);
    unitRestoreFacing(katsuya);
  label_e0:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    unitFacePlayer(baofu);
    ref_e4 = bustupLoad(bustup_31);
    bustupWait(ref_e4);
    ref_e6 = bustupAlloc(ref_e4, left, rgb(0,0,0));
    bustupFade(ref_e6, rgb(128,0,0), 30);
    ref_e8 = dialogAlloc();
    unitAnimationPlay(baofu, animation_1a, 1);
    ref_ea = msgShow(msg_10);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Hmmm... That’s a nice stereo.
[tab]It’s a decent addition to this room.

***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_ea);
    bitGet(var_0, EBIT_E0038);
    bez(var_0, label_f1);
    ref_ef = msgShow(msg_11);
/***************************************
[tab]They got nice CDs down at Giga Macho.

***************************************/
    wait(ref_ef);
  label_f1:
    ref_f1 = msgShow(msg_12);
/***************************************
[wait][clear]
***************************************/
    wait(ref_f1);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_e8);
    ref_f5 = bustupFade(ref_e6, rgb(0,0,0), 10);
    bustupWait(ref_f5);
    bustupFree(ref_e6);
    unitRestoreFacing(baofu);
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    ref_fc = bustupLoad(bustup_36);
    bustupWait(ref_fc);
    ref_fe = bustupAlloc(ref_fc, left, rgb(0,0,0));
    bustupFade(ref_fe, rgb(128,0,0), 30);
    ref_100 = dialogAlloc();
    ref_101 = msgShow(msg_13);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]T... This is a room of a maiden...?
[tab]Even if you’re busy with work... you should
[tab]make arrangements for a good butler.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_101);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_100);
    ref_106 = bustupFade(ref_fe, rgb(0,0,0), 10);
    bustupWait(ref_106);
    bustupFree(ref_fe);
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, MBIT_CNT_URARA);
    bne(var_0, 0, label_10f);
    b(label_11c);
  label_10f:
    bne(var_0, 1, label_11c);
    bitGet(var_0, MBIT_CNT_KATUYA);
    bne(var_0, 0, label_113);
    b(label_11b);
  label_113:
    bne(var_0, 1, label_11b);
    bitGet(var_0, MBIT_CNT_ERI);
    bne(var_0, 0, label_118);
    b(label_12c);
    b(label_11a);
  label_118:
    bne(var_0, 1, label_11a);
    b(label_11a);
  label_11a:
    b(label_11b);
  label_11b:
    b(label_11c);
  label_11c:
    unitFacePlayer(elly);
    ref_11d = bustupLoad(bustup_3e);
    bustupWait(ref_11d);
    ref_11f = bustupAlloc(ref_11d, left, rgb(0,0,0));
    bustupFade(ref_11f, rgb(128,0,0), 30);
    ref_121 = dialogAlloc();
    ref_122 = msgShow(msg_14);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]So this is where you live with Ms. Ulala...
[tab]It seems very fun to live with a friend.
[tab]I’m jealous...
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_28, 1);
    wait(ref_122);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_121);
    ref_127 = bustupFade(ref_11f, rgb(0,0,0), 10);
    bustupWait(ref_127);
    bustupFree(ref_11f);
    unitRestoreFacing(elly);
    b(label_13f);
  label_12c:
    unitFacePlayer(elly);
    ref_12d = bustupLoad(bustup_3e);
    bustupWait(ref_12d);
    ref_12f = bustupAlloc(ref_12d, left, rgb(0,0,0));
    bustupFade(ref_12f, rgb(128,0,0), 30);
    ref_131 = dialogAlloc();
    ref_132 = msgShow(msg_15);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Ms. Ulala says that she is
[tab]learning the flamenco dance.
[tab]Actually I know a little, too.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_132);
    ref_135 = msgShow(msg_16);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Ms. Ulala or I, who’s better...?
[tab]We’ll find out sometime...
[tab]Look forward to it.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_30, 1);
    wait(ref_135);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_131);
    ref_13a = bustupFade(ref_12f, rgb(0,0,0), 10);
    bustupWait(ref_13a);
    bustupFree(ref_12f);
    bitSet(MBIT_CNT_ERI);
    unitRestoreFacing(elly);
  label_13f:
    controlEnable();
}

function B_TATU()
{
}

function SAGIBOX()
{
    controlDisable();
    unitFacePlayer(makimura);
    ref_144 = bustupLoad(bustup_d4);
    bustupWait(ref_144);
    ref_146 = bustupAlloc(ref_144, right, rgb(0,0,0));
    bustupFade(ref_146, rgb(128,0,0), 30);
    ref_148 = dialogAlloc();
    ref_149 = msgShow(msg_17);
/***************************************
[color(yellow)]Makimura[color(white)]
[tab]Hahaha! I’m not surprised...
[tab]I don’t think you know this, 
[tab]but Ulala invited me here several times.
[wait][clear]
***************************************/
    unitAnimationPlay(makimura, animation_24, 1);
    wait(ref_149);
    unitAnimationPlay(makimura, animation_0, 1);
    dialogFree(ref_148);
    ref_14e = bustupFade(ref_146, rgb(0,0,0), 10);
    bustupWait(ref_14e);
    bustupFree(ref_146);
    choiceSetResult(1);
    op_105(1);
    ref_153 = bustupLoad(bustup_1);
    bustupWait(ref_153);
    ref_155 = bustupAlloc(ref_153, center, rgb(0,0,0));
    bustupFade(ref_155, rgb(128,0,0), 30);
    ref_157 = dialogChoiceAlloc();
    ref_158 = msgShow(msg_18);
/***************************************
[tab]She said that you did all of this?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_158);
    dialogFree(ref_157);
    ref_15b = bustupFade(ref_155, rgb(0,0,0), 10);
    bustupWait(ref_15b);
    bustupFree(ref_155);
    choiceGetResult(var_0);
    bne(var_0, 0, label_16e);
    ref_160 = bustupLoad(bustup_d4);
    bustupWait(ref_160);
    ref_162 = bustupAlloc(ref_160, right, rgb(0,0,0));
    bustupFade(ref_162, rgb(128,0,0), 30);
    ref_164 = dialogAlloc();
    ref_165 = msgShow(msg_19);
/***************************************
[color(yellow)]Makimura[color(white)]
[tab]I don’t mind that.
[tab]In fact, this uncleanliness only
[tab]sets off your beauty...
[wait][clear]
***************************************/
    unitAnimationPlay(makimura, animation_24, 1);
    wait(ref_165);
    unitAnimationPlay(makimura, animation_0, 1);
    dialogFree(ref_164);
    ref_16a = bustupFade(ref_162, rgb(0,0,0), 10);
    bustupWait(ref_16a);
    bustupFree(ref_162);
    b(label_17d);
  label_16e:
    bne(var_0, 1, label_17d);
    ref_16f = bustupLoad(bustup_d4);
    bustupWait(ref_16f);
    ref_171 = bustupAlloc(ref_16f, right, rgb(0,0,0));
    bustupFade(ref_171, rgb(128,0,0), 30);
    ref_173 = dialogAlloc();
    ref_174 = msgShow(msg_20);
/***************************************
[color(yellow)]Makimura[color(white)]
[tab]So it was a lie, huh...
[tab]She can’t say much about me, then.
[tab]She used you to make herself look better.
[wait][clear]
***************************************/
    unitAnimationPlay(makimura, animation_24, 1);
    wait(ref_174);
    unitAnimationPlay(makimura, animation_0, 1);
    dialogFree(ref_173);
    ref_179 = bustupFade(ref_171, rgb(0,0,0), 10);
    bustupWait(ref_179);
    bustupFree(ref_171);
    b(label_17d);
  label_17d:
    unitRestoreFacing(makimura);
    controlEnable();
}

function KAGIGA()
{
    controlDisable();
    ref_181 = dialogAlloc();
    ref_182 = msgShow(msg_21);
/***************************************
[color(green)]The door is locked.[color(white)]
[wait][clear]
***************************************/
    wait(ref_182);
    dialogFree(ref_181);
    controlEnable();
}

function URARAIKARI()
{
    controlDisable();
    unitFacePlayer(ulala);
    ref_189 = bustupLoad(bustup_19);
    bustupWait(ref_189);
    ref_18b = bustupAlloc(ref_189, left, rgb(0,0,0));
    bustupFade(ref_18b, rgb(128,0,0), 30);
    ref_18d = dialogAlloc();
    ref_18e = msgShow(msg_22);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Hey Ma-ya...!!
[tab]Don’t try to go into someone else’s room!
[tab]From there on is my sacred domain...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1b, 1);
    wait(ref_18e);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_18d);
    ref_193 = bustupFade(ref_18b, rgb(0,0,0), 10);
    bustupWait(ref_193);
    bustupFree(ref_18b);
    unitRestoreFacing(ulala);
    controlEnable();
}

function CDBOX()
{
    controlDisable();
    li(var_b, 0);
    bitGet(var_0, MBIT_CD_CD01);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD02);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD03);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD04);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD05);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD06);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD07);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD08);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD09);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD10);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD11);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD12);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD13);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD14);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD15);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD16);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD17);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_CD18);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_KACD01);
    bnz(var_0, label_1c9);
    bitGet(var_0, MBIT_CD_KACD02);
    bnz(var_0, label_1c9);
    ref_1c3 = dialogAlloc();
    ref_1c4 = msgShow(msg_23);
/***************************************
[color(yellow)]Stereo[color(white)]
[tab][color(green)]The latest stereo system...
[tab]This is the only thing still clean.[color(white)]
[wait][clear]
***************************************/
    wait(ref_1c4);
    dialogFree(ref_1c3);
    controlEnable();
    b(label_3ca);
  label_1c9:
    li(var_5, 0);
    ref_1ca = shopOverlayInit();
    wait(ref_1ca);
    ref_1cc = shopOpen(24);
    wait(ref_1cc);
    b(label_3ca);
    choiceSetResult(1);
    op_105(1);
    ref_1d1 = bustupLoad(bustup_1);
    bustupWait(ref_1d1);
    ref_1d3 = bustupAlloc(ref_1d1, center, rgb(0,0,0));
    bustupFade(ref_1d3, rgb(128,0,0), 30);
    ref_1d5 = dialogChoiceAlloc();
    ref_1d6 = msgShow(msg_24);
/***************************************
[color(green)]Will you listen to a CD?[color(white)]
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_1d6);
    dialogFree(ref_1d5);
    ref_1d9 = bustupFade(ref_1d3, rgb(0,0,0), 10);
    bustupWait(ref_1d9);
    bustupFree(ref_1d3);
    choiceGetResult(var_0);
    bne(var_0, 0, label_1e0);
    b(label_1e3);
    b(label_1e3);
  label_1e0:
    bne(var_0, 1, label_1e3);
    b(label_3c2);
    b(label_1e3);
  label_1e3:
    choiceSetResult(8);
    op_105(8);
    ref_1e5 = bustupLoad(bustup_1);
    bustupWait(ref_1e5);
    ref_1e7 = bustupAlloc(ref_1e5, center, rgb(0,0,0));
    bustupFade(ref_1e7, rgb(128,0,0), 30);
    ref_1e9 = dialogChoiceAlloc();
    ref_1ea = msgShow(msg_25);
/***************************************
[color(green)]Select a band.[color(white)]
[choice(9)][if_any(MBIT_CD_CD01, MBIT_CD_CD02, MBIT_CD_CD03, MBIT_CD_CD04, MBIT_CD_KACD01)]Erste
[if_all(!MBIT_CD_CD01, !MBIT_CD_CD02, !MBIT_CD_CD03, !MBIT_CD_CD04, !MBIT_CD_KACD01)][color(gray)]N/A[color(white)]
[if_any(MBIT_CD_CD05, MBIT_CD_CD06, MBIT_CD_CD07, MBIT_CD_CD08, MBIT_CD_KACD02)]Zweite
[if_all(!MBIT_CD_CD05, !MBIT_CD_CD06, !MBIT_CD_CD07, !MBIT_CD_CD08, !MBIT_CD_KACD02)][color(gray)]N/A[color(white)]
[if_any(MBIT_CD_CD09, MBIT_CD_CD10, MBIT_CD_CD11, MBIT_CD_CD12, MBIT_CD_CD13)]Dritte
[if_all(!MBIT_CD_CD09, !MBIT_CD_CD10, !MBIT_CD_CD11, !MBIT_CD_CD12, !MBIT_CD_CD13)][color(gray)]N/A[color(white)]
[if_any(MBIT_CD_CD14, MBIT_CD_CD15, MBIT_CD_CD16, MBIT_CD_CD17, MBIT_CD_CD18)]Vierte
[if_all(!MBIT_CD_CD14, !MBIT_CD_CD15, !MBIT_CD_CD16, !MBIT_CD_CD17, !MBIT_CD_CD18)][color(gray)]N/A[color(white)]
Quit
[end_choice][clear]
***************************************/
    wait(ref_1ea);
    dialogFree(ref_1e9);
    ref_1ed = bustupFade(ref_1e7, rgb(0,0,0), 10);
    bustupWait(ref_1ed);
    bustupFree(ref_1e7);
    choiceGetResult(var_0);
    bne(var_0, 0, label_1f4);
    b(label_211);
    b(label_20c);
  label_1f4:
    bne(var_0, 1, label_1f7);
    b(label_20c);
    b(label_20c);
  label_1f7:
    bne(var_0, 2, label_1fa);
    b(label_24a);
    b(label_20c);
  label_1fa:
    bne(var_0, 3, label_1fd);
    b(label_20c);
    b(label_20c);
  label_1fd:
    bne(var_0, 4, label_200);
    b(label_283);
    b(label_20c);
  label_200:
    bne(var_0, 5, label_203);
    b(label_20c);
    b(label_20c);
  label_203:
    bne(var_0, 6, label_206);
    b(label_2bc);
    b(label_20c);
  label_206:
    bne(var_0, 7, label_209);
    b(label_20c);
    b(label_20c);
  label_209:
    bne(var_0, 8, label_20c);
    b(label_3c2);
    b(label_20c);
  label_20c:
    ref_20c = dialogAlloc();
    ref_20d = msgShow(msg_26);
/***************************************
[color(green)]You haven’t bought any
of this group’s CDs yet.[color(white)]
[wait][clear]
***************************************/
    wait(ref_20d);
    dialogFree(ref_20c);
    b(label_1e3);
  label_211:
    choiceSetResult(10);
    op_105(10);
    ref_213 = bustupLoad(bustup_1);
    bustupWait(ref_213);
    ref_215 = bustupAlloc(ref_213, center, rgb(0,0,0));
    bustupFade(ref_215, rgb(128,0,0), 30);
    ref_217 = dialogChoiceAlloc();
    ref_218 = msgShow(msg_27);
/***************************************
[color(green)]Pick a CD.[color(white)]
[choice(11)][if_all(MBIT_CD_CD01)]CD 1
[if_all(!MBIT_CD_CD01)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD02)]CD 2
[if_all(!MBIT_CD_CD02)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD03)]CD 3
[if_all(!MBIT_CD_CD03)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD04)]CD 4
[if_all(!MBIT_CD_CD04)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_KACD01)]Secret CD 1
[if_all(!MBIT_CD_KACD01)][color(gray)]N/A[color(white)]
Quit
[end_choice][clear]
***************************************/
    wait(ref_218);
    dialogFree(ref_217);
    ref_21b = bustupFade(ref_215, rgb(0,0,0), 10);
    bustupWait(ref_21b);
    bustupFree(ref_215);
    choiceGetResult(var_0);
    bne(var_0, 0, label_223);
    li(var_a, 1);
    b(label_2f5);
    b(label_245);
  label_223:
    bne(var_0, 1, label_226);
    b(label_245);
    b(label_245);
  label_226:
    bne(var_0, 2, label_22a);
    li(var_a, 2);
    b(label_2f5);
    b(label_245);
  label_22a:
    bne(var_0, 3, label_22d);
    b(label_245);
    b(label_245);
  label_22d:
    bne(var_0, 4, label_231);
    li(var_a, 3);
    b(label_2f5);
    b(label_245);
  label_231:
    bne(var_0, 5, label_234);
    b(label_245);
    b(label_245);
  label_234:
    bne(var_0, 6, label_238);
    li(var_a, 4);
    b(label_2f5);
    b(label_245);
  label_238:
    bne(var_0, 7, label_23b);
    b(label_245);
    b(label_245);
  label_23b:
    bne(var_0, 8, label_23f);
    li(var_a, 5);
    b(label_2f5);
    b(label_245);
  label_23f:
    bne(var_0, 9, label_242);
    b(label_245);
    b(label_245);
  label_242:
    bne(var_0, 10, label_245);
    b(label_1e3);
    b(label_245);
  label_245:
    ref_245 = dialogAlloc();
    ref_246 = msgShow(msg_28);
/***************************************
[color(green)]You have not bought
this CD yet.[color(white)]
[wait][clear]
***************************************/
    wait(ref_246);
    dialogFree(ref_245);
    b(label_211);
  label_24a:
    choiceSetResult(10);
    op_105(10);
    ref_24c = bustupLoad(bustup_1);
    bustupWait(ref_24c);
    ref_24e = bustupAlloc(ref_24c, center, rgb(0,0,0));
    bustupFade(ref_24e, rgb(128,0,0), 30);
    ref_250 = dialogChoiceAlloc();
    ref_251 = msgShow(msg_29);
/***************************************
[color(green)]Pick a CD.[color(white)]
[choice(11)][if_all(MBIT_CD_CD05)]CD 5
[if_all(!MBIT_CD_CD05)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD06)]CD 6
[if_all(!MBIT_CD_CD06)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD07)]CD 7
[if_all(!MBIT_CD_CD07)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD08)]CD 8
[if_all(!MBIT_CD_CD08)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_KACD02)]Secret CD 2
[if_all(!MBIT_CD_KACD02)][color(gray)]N/A[color(white)]
Quit
[end_choice][clear]
***************************************/
    wait(ref_251);
    dialogFree(ref_250);
    ref_254 = bustupFade(ref_24e, rgb(0,0,0), 10);
    bustupWait(ref_254);
    bustupFree(ref_24e);
    choiceGetResult(var_0);
    bne(var_0, 0, label_25c);
    li(var_a, 11);
    b(label_2f5);
    b(label_27e);
  label_25c:
    bne(var_0, 1, label_25f);
    b(label_27e);
    b(label_27e);
  label_25f:
    bne(var_0, 2, label_263);
    li(var_a, 12);
    b(label_2f5);
    b(label_27e);
  label_263:
    bne(var_0, 3, label_266);
    b(label_27e);
    b(label_27e);
  label_266:
    bne(var_0, 4, label_26a);
    li(var_a, 13);
    b(label_2f5);
    b(label_27e);
  label_26a:
    bne(var_0, 5, label_26d);
    b(label_27e);
    b(label_27e);
  label_26d:
    bne(var_0, 6, label_271);
    li(var_a, 14);
    b(label_2f5);
    b(label_27e);
  label_271:
    bne(var_0, 7, label_274);
    b(label_27e);
    b(label_27e);
  label_274:
    bne(var_0, 8, label_278);
    li(var_a, 15);
    b(label_2f5);
    b(label_27e);
  label_278:
    bne(var_0, 9, label_27b);
    b(label_27e);
    b(label_27e);
  label_27b:
    bne(var_0, 10, label_27e);
    b(label_1e3);
    b(label_27e);
  label_27e:
    ref_27e = dialogAlloc();
    ref_27f = msgShow(msg_30);
/***************************************
[color(green)]You have not bought
this CD yet.[color(white)]
[wait][clear]
***************************************/
    wait(ref_27f);
    dialogFree(ref_27e);
    b(label_24a);
  label_283:
    choiceSetResult(10);
    op_105(10);
    ref_285 = bustupLoad(bustup_1);
    bustupWait(ref_285);
    ref_287 = bustupAlloc(ref_285, center, rgb(0,0,0));
    bustupFade(ref_287, rgb(128,0,0), 30);
    ref_289 = dialogChoiceAlloc();
    ref_28a = msgShow(msg_31);
/***************************************
[color(green)]Pick a CD.[color(white)]
[choice(11)][if_all(MBIT_CD_CD09)]CD9
[if_all(!MBIT_CD_CD09)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD10)]CD10
[if_all(!MBIT_CD_CD10)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD11)]CD11
[if_all(!MBIT_CD_CD11)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD12)]CD12
[if_all(!MBIT_CD_CD12)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD13)]CD13
[if_all(!MBIT_CD_CD13)][color(gray)]N/A[color(white)]
Quit
[end_choice][clear]
***************************************/
    wait(ref_28a);
    dialogFree(ref_289);
    ref_28d = bustupFade(ref_287, rgb(0,0,0), 10);
    bustupWait(ref_28d);
    bustupFree(ref_287);
    choiceGetResult(var_0);
    bne(var_0, 0, label_295);
    li(var_a, 21);
    b(label_2f5);
    b(label_2b7);
  label_295:
    bne(var_0, 1, label_298);
    b(label_2b7);
    b(label_2b7);
  label_298:
    bne(var_0, 2, label_29c);
    li(var_a, 22);
    b(label_2f5);
    b(label_2b7);
  label_29c:
    bne(var_0, 3, label_29f);
    b(label_2b7);
    b(label_2b7);
  label_29f:
    bne(var_0, 4, label_2a3);
    li(var_a, 23);
    b(label_2f5);
    b(label_2b7);
  label_2a3:
    bne(var_0, 5, label_2a6);
    b(label_2b7);
    b(label_2b7);
  label_2a6:
    bne(var_0, 6, label_2aa);
    li(var_a, 24);
    b(label_2f5);
    b(label_2b7);
  label_2aa:
    bne(var_0, 7, label_2ad);
    b(label_2b7);
    b(label_2b7);
  label_2ad:
    bne(var_0, 8, label_2b1);
    li(var_a, 25);
    b(label_2f5);
    b(label_2b7);
  label_2b1:
    bne(var_0, 9, label_2b4);
    b(label_2b7);
    b(label_2b7);
  label_2b4:
    bne(var_0, 10, label_2b7);
    b(label_1e3);
    b(label_2b7);
  label_2b7:
    ref_2b7 = dialogAlloc();
    ref_2b8 = msgShow(msg_32);
/***************************************
[color(green)]You have not bought
this CD yet.[color(white)]
[wait][clear]
***************************************/
    wait(ref_2b8);
    dialogFree(ref_2b7);
    b(label_283);
  label_2bc:
    choiceSetResult(10);
    op_105(10);
    ref_2be = bustupLoad(bustup_1);
    bustupWait(ref_2be);
    ref_2c0 = bustupAlloc(ref_2be, center, rgb(0,0,0));
    bustupFade(ref_2c0, rgb(128,0,0), 30);
    ref_2c2 = dialogChoiceAlloc();
    ref_2c3 = msgShow(msg_33);
/***************************************
[color(green)]Pick a CD.[color(white)]
[choice(11)][if_all(MBIT_CD_CD14)]CD 14
[if_all(!MBIT_CD_CD14)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD15)]CD 15
[if_all(!MBIT_CD_CD15)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD16)]CD 16
[if_all(!MBIT_CD_CD16)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD17)]CD 17
[if_all(!MBIT_CD_CD17)][color(gray)]N/A[color(white)]
[if_all(MBIT_CD_CD18)]CD 18
[if_all(!MBIT_CD_CD18)][color(gray)]N/A[color(white)]
Quit
[end_choice][clear]
***************************************/
    wait(ref_2c3);
    dialogFree(ref_2c2);
    ref_2c6 = bustupFade(ref_2c0, rgb(0,0,0), 10);
    bustupWait(ref_2c6);
    bustupFree(ref_2c0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_2ce);
    li(var_a, 31);
    b(label_2f5);
    b(label_2f0);
  label_2ce:
    bne(var_0, 1, label_2d1);
    b(label_2f0);
    b(label_2f0);
  label_2d1:
    bne(var_0, 2, label_2d5);
    li(var_a, 32);
    b(label_2f5);
    b(label_2f0);
  label_2d5:
    bne(var_0, 3, label_2d8);
    b(label_2f0);
    b(label_2f0);
  label_2d8:
    bne(var_0, 4, label_2dc);
    li(var_a, 33);
    b(label_2f5);
    b(label_2f0);
  label_2dc:
    bne(var_0, 5, label_2df);
    b(label_2f0);
    b(label_2f0);
  label_2df:
    bne(var_0, 6, label_2e3);
    li(var_a, 34);
    b(label_2f5);
    b(label_2f0);
  label_2e3:
    bne(var_0, 7, label_2e6);
    b(label_2f0);
    b(label_2f0);
  label_2e6:
    bne(var_0, 8, label_2ea);
    li(var_a, 35);
    b(label_2f5);
    b(label_2f0);
  label_2ea:
    bne(var_0, 9, label_2ed);
    b(label_2f0);
    b(label_2f0);
  label_2ed:
    bne(var_0, 10, label_2f0);
    b(label_1e3);
    b(label_2f0);
  label_2f0:
    ref_2f0 = dialogAlloc();
    ref_2f1 = msgShow(msg_34);
/***************************************
[color(green)]You have not bought
this CD yet.[color(white)]
[wait][clear]
***************************************/
    wait(ref_2f1);
    dialogFree(ref_2f0);
    b(label_2bc);
  label_2f5:
    ref_2f5 = dialogAlloc();
    sndVolumeFadeTo(sound_3023, 0, 30);
    li(var_b, 1);
    bne(var_a, 1, label_2ff);
    ref_2f9 = msgShow(msg_35);
/***************************************
[color(green)]Now playing CD 1...[color(white)]

***************************************/
    ref_2fa = sndLoad(sound_1020);
    wait(ref_2fa);
    sndMusicPlay(sound_1020, 127);
    wait(ref_2f9);
    b(label_382);
  label_2ff:
    bne(var_a, 2, label_306);
    ref_300 = msgShow(msg_36);
/***************************************
[color(green)]Now playing CD 2...[color(white)]

***************************************/
    ref_301 = sndLoad(sound_1040);
    wait(ref_301);
    sndMusicPlay(sound_1040, 127);
    wait(ref_300);
    b(label_382);
  label_306:
    bne(var_a, 3, label_30d);
    ref_307 = msgShow(msg_37);
/***************************************
[color(green)]Now playing CD 3...[color(white)]

***************************************/
    ref_308 = sndLoad(sound_3007);
    wait(ref_308);
    sndMusicPlay(sound_3007, 127);
    wait(ref_307);
    b(label_382);
  label_30d:
    bne(var_a, 4, label_314);
    ref_30e = msgShow(msg_38);
/***************************************
[color(green)]Now playing CD 4...[color(white)]

***************************************/
    ref_30f = sndLoad(sound_3008);
    wait(ref_30f);
    sndMusicPlay(sound_3008, 127);
    wait(ref_30e);
    b(label_382);
  label_314:
    bne(var_a, 5, label_31a);
    ref_315 = msgShow(msg_39);
/***************************************
[color(green)]Now playing Secret CD 1...[color(white)]

***************************************/
    sndVoicePlay(sound_cd, 127);
    sndWaitStart();
    wait(ref_315);
    b(label_382);
  label_31a:
    bne(var_a, 11, label_321);
    ref_31b = msgShow(msg_40);
/***************************************
[color(green)]Now playing CD 5...[color(white)]

***************************************/
    ref_31c = sndLoad(sound_10a0);
    wait(ref_31c);
    sndMusicPlay(sound_10a0, 127);
    wait(ref_31b);
    b(label_382);
  label_321:
    bne(var_a, 12, label_328);
    ref_322 = msgShow(msg_41);
/***************************************
[color(green)]Now playing CD 6...[color(white)]

***************************************/
    ref_323 = sndLoad(sound_1100);
    wait(ref_323);
    sndMusicPlay(sound_1100, 127);
    wait(ref_322);
    b(label_382);
  label_328:
    bne(var_a, 13, label_32f);
    ref_329 = msgShow(msg_42);
/***************************************
[color(green)]Now playing CD 7...[color(white)]

***************************************/
    ref_32a = sndLoad(sound_1120);
    wait(ref_32a);
    sndMusicPlay(sound_1120, 127);
    wait(ref_329);
    b(label_382);
  label_32f:
    bne(var_a, 14, label_336);
    ref_330 = msgShow(msg_43);
/***************************************
[color(green)]Now playing CD 8...[color(white)]

***************************************/
    ref_331 = sndLoad(sound_1140);
    wait(ref_331);
    sndMusicPlay(sound_1140, 127);
    wait(ref_330);
    b(label_382);
  label_336:
    bne(var_a, 15, label_33c);
    ref_337 = msgShow(msg_44);
/***************************************
[color(green)]Now playing Secret CD 2...[color(white)]

***************************************/
    sndVoicePlay(sound_cc, 127);
    sndWaitStart();
    wait(ref_337);
    b(label_382);
  label_33c:
    bne(var_a, 21, label_343);
    ref_33d = msgShow(msg_45);
/***************************************
[color(green)]Now playing CD 9...[color(white)]

***************************************/
    ref_33e = sndLoad(sound_1180);
    wait(ref_33e);
    sndMusicPlay(sound_1180, 127);
    wait(ref_33d);
    b(label_382);
  label_343:
    bne(var_a, 22, label_34a);
    ref_344 = msgShow(msg_46);
/***************************************
[color(green)]Now playing CD 10...[color(white)]

***************************************/
    ref_345 = sndLoad(sound_11a0);
    wait(ref_345);
    sndMusicPlay(sound_11a0, 127);
    wait(ref_344);
    b(label_382);
  label_34a:
    bne(var_a, 23, label_351);
    ref_34b = msgShow(msg_47);
/***************************************
[color(green)]Now playing CD 11...[color(white)]

***************************************/
    ref_34c = sndLoad(sound_11c0);
    wait(ref_34c);
    sndMusicPlay(sound_11c0, 127);
    wait(ref_34b);
    b(label_382);
  label_351:
    bne(var_a, 24, label_358);
    ref_352 = msgShow(msg_48);
/***************************************
[color(green)]Now playing CD 12...[color(white)]

***************************************/
    ref_353 = sndLoad(sound_1200);
    wait(ref_353);
    sndMusicPlay(sound_1200, 127);
    wait(ref_352);
    b(label_382);
  label_358:
    bne(var_a, 25, label_35f);
    ref_359 = msgShow(msg_49);
/***************************************
[color(green)]Now playing CD 13...[color(white)]

***************************************/
    ref_35a = sndLoad(sound_3014);
    wait(ref_35a);
    sndMusicPlay(sound_3014, 127);
    wait(ref_359);
    b(label_382);
  label_35f:
    bne(var_a, 31, label_366);
    ref_360 = msgShow(msg_50);
/***************************************
[color(green)]Now playing CD 14...[color(white)]

***************************************/
    ref_361 = sndLoad(sound_1220);
    wait(ref_361);
    sndMusicPlay(sound_1220, 127);
    wait(ref_360);
    b(label_382);
  label_366:
    bne(var_a, 32, label_36d);
    ref_367 = msgShow(msg_51);
/***************************************
[color(green)]Now playing CD 15...[color(white)]

***************************************/
    ref_368 = sndLoad(sound_1240);
    wait(ref_368);
    sndMusicPlay(sound_1240, 127);
    wait(ref_367);
    b(label_382);
  label_36d:
    bne(var_a, 33, label_374);
    ref_36e = msgShow(msg_52);
/***************************************
[color(green)]Now playing CD 16...[color(white)]

***************************************/
    ref_36f = sndLoad(sound_1260);
    wait(ref_36f);
    sndMusicPlay(sound_1260, 127);
    wait(ref_36e);
    b(label_382);
  label_374:
    bne(var_a, 34, label_37b);
    ref_375 = msgShow(msg_53);
/***************************************
[color(green)]Now playing CD 17...[color(white)]

***************************************/
    ref_376 = sndLoad(sound_300a);
    wait(ref_376);
    sndMusicPlay(sound_300a, 127);
    wait(ref_375);
    b(label_382);
  label_37b:
    bne(var_a, 35, label_382);
    ref_37c = msgShow(msg_54);
/***************************************
[color(green)]Now playing CD 18...[color(white)]

***************************************/
    ref_37d = sndLoad(sound_300c);
    wait(ref_37d);
    sndMusicPlay(sound_300c, 127);
    wait(ref_37c);
    b(label_382);
  label_382:
    ref_382 = msgShow(msg_55);
/***************************************
[color(green)]♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪
[tab]Push × or ○ button to stop the music.
[tab]♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪♪[color(white)]
[wait][clear]
***************************************/
    wait(ref_382);
    dialogFree(ref_2f5);
    bne(var_a, 1, label_388);
    sndStop(sound_1020);
    b(label_3c1);
  label_388:
    bne(var_a, 2, label_38b);
    sndStop(sound_1040);
    b(label_3c1);
  label_38b:
    bne(var_a, 3, label_38e);
    sndStop(sound_3007);
    b(label_3c1);
  label_38e:
    bne(var_a, 4, label_391);
    sndStop(sound_3008);
    b(label_3c1);
  label_391:
    bne(var_a, 5, label_394);
    sndMusicFree();
    b(label_3c1);
  label_394:
    bne(var_a, 11, label_397);
    sndStop(sound_10a0);
    b(label_3c1);
  label_397:
    bne(var_a, 12, label_39a);
    sndStop(sound_1100);
    b(label_3c1);
  label_39a:
    bne(var_a, 13, label_39d);
    sndStop(sound_1120);
    b(label_3c1);
  label_39d:
    bne(var_a, 14, label_3a0);
    sndStop(sound_1140);
    b(label_3c1);
  label_3a0:
    bne(var_a, 15, label_3a3);
    sndMusicFree();
    b(label_3c1);
  label_3a3:
    bne(var_a, 21, label_3a6);
    sndStop(sound_1180);
    b(label_3c1);
  label_3a6:
    bne(var_a, 22, label_3a9);
    sndStop(sound_11a0);
    b(label_3c1);
  label_3a9:
    bne(var_a, 23, label_3ac);
    sndStop(sound_11c0);
    b(label_3c1);
  label_3ac:
    bne(var_a, 24, label_3af);
    sndStop(sound_1200);
    b(label_3c1);
  label_3af:
    bne(var_a, 25, label_3b2);
    sndStop(sound_3014);
    b(label_3c1);
  label_3b2:
    bne(var_a, 31, label_3b5);
    sndStop(sound_1220);
    b(label_3c1);
  label_3b5:
    bne(var_a, 32, label_3b8);
    sndStop(sound_1240);
    b(label_3c1);
  label_3b8:
    bne(var_a, 33, label_3bb);
    sndStop(sound_1260);
    b(label_3c1);
  label_3bb:
    bne(var_a, 34, label_3be);
    sndStop(sound_300a);
    b(label_3c1);
  label_3be:
    bne(var_a, 35, label_3c1);
    sndStop(sound_300c);
    b(label_3c1);
  label_3c1:
    b(label_1e3);
  label_3c2:
    bne(var_b, 0, label_3c4);
    b(label_3c9);
  label_3c4:
    bne(var_b, 1, label_3c9);
    ref_3c5 = sndLoad(sound_3023);
    wait(ref_3c5);
    sndMusicPlay(sound_3023, 127);
    b(label_3c9);
  label_3c9:
    controlEnable();
  label_3ca:
}

function DOORBOX()
{
    controlDisable();
    objAnimRotate(obj_1e, 0, 80, 0, 30, 0);
    sndMusicPlay(sound_307d, 127);
    objAnimWait(obj_1e);
    mapLoad(kounan, 10, 6);
}

function CD_PLAY()
{
    bne(var_1, 1, label_3d6);
    ref_3d2 = sndLoad(sound_1020);
    wait(ref_3d2);
    sndMusicPlay(sound_1020, 127);
    b(label_431);
  label_3d6:
    bne(var_1, 2, label_3db);
    ref_3d7 = sndLoad(sound_1040);
    wait(ref_3d7);
    sndMusicPlay(sound_1040, 127);
    b(label_431);
  label_3db:
    bne(var_1, 3, label_3e0);
    ref_3dc = sndLoad(sound_3007);
    wait(ref_3dc);
    sndMusicPlay(sound_3007, 127);
    b(label_431);
  label_3e0:
    bne(var_1, 4, label_3e5);
    ref_3e1 = sndLoad(sound_3008);
    wait(ref_3e1);
    sndMusicPlay(sound_3008, 127);
    b(label_431);
  label_3e5:
    bne(var_1, 5, label_3e8);
    sndMusicPlay(sound_40ad, 127);
    b(label_431);
  label_3e8:
    bne(var_1, 6, label_3ed);
    ref_3e9 = sndLoad(sound_10a0);
    wait(ref_3e9);
    sndMusicPlay(sound_10a0, 127);
    b(label_431);
  label_3ed:
    bne(var_1, 7, label_3f2);
    ref_3ee = sndLoad(sound_1100);
    wait(ref_3ee);
    sndMusicPlay(sound_1100, 127);
    b(label_431);
  label_3f2:
    bne(var_1, 8, label_3f7);
    ref_3f3 = sndLoad(sound_1120);
    wait(ref_3f3);
    sndMusicPlay(sound_1120, 127);
    b(label_431);
  label_3f7:
    bne(var_1, 9, label_3fc);
    ref_3f8 = sndLoad(sound_1140);
    wait(ref_3f8);
    sndMusicPlay(sound_1140, 127);
    b(label_431);
  label_3fc:
    bne(var_1, 10, label_3ff);
    sndMusicPlay(sound_40ae, 127);
    b(label_431);
  label_3ff:
    bne(var_1, 11, label_404);
    ref_400 = sndLoad(sound_1180);
    wait(ref_400);
    sndMusicPlay(sound_1180, 127);
    b(label_431);
  label_404:
    bne(var_1, 12, label_409);
    ref_405 = sndLoad(sound_11a0);
    wait(ref_405);
    sndMusicPlay(sound_11a0, 127);
    b(label_431);
  label_409:
    bne(var_1, 13, label_40e);
    ref_40a = sndLoad(sound_11c0);
    wait(ref_40a);
    sndMusicPlay(sound_11c0, 127);
    b(label_431);
  label_40e:
    bne(var_1, 14, label_413);
    ref_40f = sndLoad(sound_1200);
    wait(ref_40f);
    sndMusicPlay(sound_1200, 127);
    b(label_431);
  label_413:
    bne(var_1, 15, label_418);
    ref_414 = sndLoad(sound_3014);
    wait(ref_414);
    sndMusicPlay(sound_3014, 127);
    b(label_431);
  label_418:
    bne(var_1, 16, label_41d);
    ref_419 = sndLoad(sound_1220);
    wait(ref_419);
    sndMusicPlay(sound_1220, 127);
    b(label_431);
  label_41d:
    bne(var_1, 17, label_422);
    ref_41e = sndLoad(sound_1240);
    wait(ref_41e);
    sndMusicPlay(sound_1240, 127);
    b(label_431);
  label_422:
    bne(var_1, 18, label_427);
    ref_423 = sndLoad(sound_1260);
    wait(ref_423);
    sndMusicPlay(sound_1260, 127);
    b(label_431);
  label_427:
    bne(var_1, 19, label_42c);
    ref_428 = sndLoad(sound_300a);
    wait(ref_428);
    sndMusicPlay(sound_300a, 127);
    b(label_431);
  label_42c:
    bne(var_1, 20, label_431);
    ref_42d = sndLoad(sound_300c);
    wait(ref_42d);
    sndMusicPlay(sound_300c, 127);
    b(label_431);
  label_431:
}

function CD_STOP()
{
    bne(var_1, 1, label_435);
    sndStop(sound_1020);
    b(label_46e);
  label_435:
    bne(var_1, 2, label_438);
    sndStop(sound_1040);
    b(label_46e);
  label_438:
    bne(var_1, 3, label_43b);
    sndStop(sound_3007);
    b(label_46e);
  label_43b:
    bne(var_1, 4, label_43e);
    sndStop(sound_3008);
    b(label_46e);
  label_43e:
    bne(var_1, 5, label_441);
    sndStop(sound_40ad);
    b(label_46e);
  label_441:
    bne(var_1, 6, label_444);
    sndStop(sound_10a0);
    b(label_46e);
  label_444:
    bne(var_1, 7, label_447);
    sndStop(sound_1100);
    b(label_46e);
  label_447:
    bne(var_1, 8, label_44a);
    sndStop(sound_1120);
    b(label_46e);
  label_44a:
    bne(var_1, 9, label_44d);
    sndStop(sound_1140);
    b(label_46e);
  label_44d:
    bne(var_1, 10, label_450);
    sndStop(sound_40ae);
    b(label_46e);
  label_450:
    bne(var_1, 11, label_453);
    sndStop(sound_1180);
    b(label_46e);
  label_453:
    bne(var_1, 12, label_456);
    sndStop(sound_11a0);
    b(label_46e);
  label_456:
    bne(var_1, 13, label_459);
    sndStop(sound_11c0);
    b(label_46e);
  label_459:
    bne(var_1, 14, label_45c);
    sndStop(sound_1200);
    b(label_46e);
  label_45c:
    bne(var_1, 15, label_45f);
    sndStop(sound_3014);
    b(label_46e);
  label_45f:
    bne(var_1, 16, label_462);
    sndStop(sound_1220);
    b(label_46e);
  label_462:
    bne(var_1, 17, label_465);
    sndStop(sound_1240);
    b(label_46e);
  label_465:
    bne(var_1, 18, label_468);
    sndStop(sound_1260);
    b(label_46e);
  label_468:
    bne(var_1, 19, label_46b);
    sndStop(sound_300a);
    b(label_46e);
  label_46b:
    bne(var_1, 20, label_46e);
    sndStop(sound_300c);
    b(label_46e);
  label_46e:
    sndMusicPlay(sound_3023, 127);
}

function HA_SHOP_END_0()
{
    shopOverlayInit();
    li(var_5, 0);
    controlEnable();
}

function HA_SHOP_TALK_0()
{
}

function HA_SHOP_RESTART_1()
{
}

function HA_SHOP_RESTART_0()
{
    li(var_5, 1);
}
