
msg_0:
More than 4 in your party
[tab]Hang time!
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Do needy women have an advantage?
[tab](sigh)... I look after people too much...
[tab]I think I’ve lost much...
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]That Bao, complaining so much about
[tab]Detective [suou], but he’s doing the same...
[tab]What a troubled guy.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]I know that there’s been a lot in the past, 
[tab]but has Bao thought anything over...?
[tab]I see no change in him though.
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Wasn’t that guy Kandori involved in a
[tab]larger scandal? He’s such a villain...
[tab]But, he was different from others.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun, Eikichi-kun, and others were
[tab]connected by the "Other Side".
[tab]But, it’s sad to the forgotten one...
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Inferring my ass! Only Nanjo-kun would wear a
[tab]"No. 1" on his back!! ...Then we don’t need
[tab]to worry about the townspeople.
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]Everyone seems to be saying whatever.
[tab]Given a situation like this, they
[tab]might be expressing their true feelings.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]Vicious extorsion...?
[tab]Hmm, I suspect it could be blackmail.
[tab]Where? Are they in this store!?
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]Everyone has a past they don’t want
[tab]talked about, right...?
[tab]Baofu has a past... That’s all.
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Feelings that can’t be held back...
[tab]That leads to crime, but we’re human...
[tab]I can’t say much about others.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]I don’t believe dragons exist, but as far
[tab]as energy moving underground, I’m sold...
[tab]Is that because I’m ignorant...?
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya] was always fighting.
[tab]Even on the "Other Side"...
[tab]In places I never knew about...
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Are those two talking about him?
[tab]Inferring from their testimony...
[tab]Hmm, there is no mistake.
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]In times of anxiety, true feelings
[tab]surface... That is true. At least
[tab]there are no destructive feelings.
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]...Needy women? Is Serizawa saying that
[tab]while looking at that woman there? Any way
[tab]I look at it, that is vicious extorsion.
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]Even if there are traps, you press onward
[tab]with your beliefs. That’s a true man...
[tab]Women and children can’t understand.
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]Keystones holding dragons... 
[tab]Megalith cultures of the world are probably 
[tab]the same... The Ley Line may be the same, too.
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]Crawling Chaos is such a grand name, 
[tab]just like New World Order... Those with big
[tab]plans like big names...
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]A "1" on the back, huh? ...Besides him...
[tab]There’s only that one athlete who
[tab]used to be in...
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]Always alone, ever since coming to "This Side"...
[tab]No one understands, no one to share...
[tab][tatsuya]... no one to feel his pain.
[wait][clear][end]

msg_21:
[color(yellow)]Nanjo[color(white)]
[tab]Gains and losses meaning profit?
[tab]Amano-san, does love have gains and losses?
[tab]And, what can be gained!?[delay(30)]...Trouble?
[wait][clear][end]

msg_22:
[color(yellow)]Nanjo[color(white)]
[tab]That phone we tapped earlier...
[tab]There must be something behind it.
[tab]Let us hurry, Amano-san!
[wait][clear][end]

msg_23:
[color(yellow)]Nanjo[color(white)]
[tab]That phone we tapped earlier... 
[tab]New World Order’s movement... Mr. Baofu...
[tab]Let us hurry, Amano-san!
[wait][clear][end]

msg_24:
[color(yellow)]Nanjo[color(white)]
[tab]Investigating one’s private life did
[tab]hold me back, but I did have doubts
[tab]about Mr. Baofu’s true nature...
[wait][clear][end]

msg_25:
[color(yellow)]Nanjo[color(white)]
[tab]Kandori... He might have just been playing
[tab]the role given to him...
[wait][clear][end]

msg_26:
[color(yellow)]Elly[color(white)]
[tab](giggle)... Ms. Ulala’s knack for taking care of
[tab]people must be understood by you.
[tab]Is there an advantageous relationship?
[wait][clear][end]

msg_27:
[color(yellow)]Elly[color(white)]
[tab]That phone we tapped earlier...
[tab]Hmm... I have a bad feeling.
[tab]Let’s hurry, Ms. Amano!
[wait][clear][end]

msg_28:
[color(yellow)]Elly[color(white)]
[tab]That phone we tapped earlier...
[tab]New World Order’s movement... It was a trap.
[tab]Mr. Baofu is in danger!
[wait][clear][end]

msg_29:
[color(yellow)]Elly[color(white)]
[tab]Mr. Baofu’s past... It’s so hard boiled.
[tab]It is amazing that he doesn’t seem
[tab]that way at all.
[wait][clear][end]

msg_30:
[color(yellow)]Elly[color(white)]
[tab]Mr. Kandori... He could have just been playing
[tab]the role given to him...
[wait][clear][end]

msg_31:
[color(yellow)][tatsuya][color(white)]
[tab]Kandori... Is that man the same as... as me?
[wait][clear][end]

msg_32:
[color(yellow)][tatsuya][color(white)]
[tab]Am I too accustomed to being alone...?
[tab]It feels awkward to be walking with
[tab]comrades now.
[wait][clear][end]

msg_33:
[color(yellow)][tatsuya][color(white)]
[tab]"Everyone has the right to grasp a dream."
[tab]That is what you said on the Other Side, but
[tab]do I really have the right to grasp one...?
[wait][clear][end]

msg_34:
[color(yellow)][tatsuya][color(white)]
[tab]Having someone to share their true
[tab]feelings with...
[tab]That is... very fortunate.
[wait][clear][end]

msg_35:
[color(yellow)]Extravagant Woman[color(white)]
[tab]These days, I’m doing great. My body
[tab]feels great, and I made many contracts.
[tab]Is it because of Wang Long...?
[wait][clear][end]

msg_36:
[color(yellow)]Extravagant Woman[color(white)]
[tab]...What, what?
[tab]Is there something wrong?
[wait][clear][end]

msg_37:
[tab]Is there something wrong?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_38:
YAYOI KIMURA
[end]

msg_39:
[color(yellow)]Extravagant Woman[color(white)]
[tab]Hmph, well excuse me...!
[tab]Misstating someone’s name is very rude!
[tab]You would fail as a salesman!
[wait][clear][end]

msg_40:
[color(yellow)]Yayoi Kimura[color(white)]
[tab]Oh, how do you know my name?
[tab]...Eh, I tricked a customer? ...I used Muses’
[tab]goods as bait for making a contract!?
[wait][clear][end]

msg_41:
[color(yellow)]Yayoi Kimura[color(white)]
[tab]W-What proof do you have? I just don’t
[tab]have the goods on hand to give.
[tab]I didn’t trick them!
[wait][clear][end]

msg_42:
[color(yellow)]Yayoi Kimura[color(white)]
[tab]Getting insurance just for goods is...
[tab]Oh, it’s no use telling you. H-Hmph...
[tab]I’ll deliver the goods right now.
[wait][clear][end]

msg_43:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_44:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_45:
[tab]Have you met people who’ve been to that
[tab]seminar? They yell "Let’s think positive!" all
[tab]of a sudden... in the middle of the street.
[wait][clear][end]

msg_46:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_47:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_48:
[tab]And they keep on telling me to go, too.
[tab]Oh, there’s also been people that have
[tab]disappeared at the seminar. I’m scared...
[wait][clear][end]

msg_49:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_50:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_51:
[tab]Did you see the news!? A pole shift...!
[tab]I need to buy water, food, and candles...!
[tab]Wait... I have leftovers from the Y2K hoax.
[wait][clear][end]

msg_52:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_53:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_54:
[tab]I never thought the ruins found at the
[tab]subway construction site would fly...
[tab]Have you prepared yet for the sky?
[wait][clear][end]

msg_55:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_56:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_57:
[tab]Me? ...A-OKAY!
[tab]Ah, I’ll buy some precious metals
[tab]with my extra cash...
[wait][clear][end]

msg_58:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_59:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_60:
[tab]Long time no see, eh... Am I okay, you ask?
[tab]I’m dandy. My house is in Aoba. Let’s see,
[tab]this week’s Red Dragon lucky item is...
[wait][clear][end]

msg_61:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_62:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_63:
[tab]A pole shift didn’t occur, but the world’s
[tab]in a panic. Now is the time for precious
[tab]metals! Their value won’t change!
[wait][clear][end]

msg_64:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_65:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_66:
[tab]I wonder if this store is not doing well?
[tab]They’ve been taking orders for weapons and
[tab]armor lately. Well, it’s not my business...
[wait][clear][end]

msg_67:
[color(yellow)]Extravagant Woman[color(white)]
[end]

msg_68:
[color(yellow)]Yayoi Kimura[color(white)]
[end]

msg_69:
[tab]I like this store. I’m stunned it reopened
[tab]so quickly! I like how it looks exactly
[tab]the same as the old store did.
[wait][clear][end]

msg_70:
[color(yellow)]Yayoi Kimura[color(white)]
[tab]Do you know [color(orange)]Kaori[color(white)] in Rengedai?
[tab]That store has [color(orange)]been closed for some time[color(white)].
[tab]It’s a mystery as to why it has closed.
[wait][clear][end]

msg_71:
[color(yellow)]Glittery-Eyed Girl[color(white)]
[tab]Did you know that stones have secret
[tab]powers? They seem to protect people.
[tab]I’m so scared of the crimes these days.
[wait][clear][end]

msg_72:
[color(yellow)]Distressed Man[color(white)]
[tab]...So, you want an accessory with a
[tab]beautiful stone... You never say you
[tab]want it... I’m scared of YOU.
[wait][clear][end]

msg_73:
[color(yellow)]Glittery-Eyed Girl[color(white)]
[tab]Hey... Are we going to die...?
[tab]Can you say that we won’t!? ...If I’m
[tab]going to die, I wanna die beautiful.
[wait][clear][end]

msg_74:
[color(yellow)]Distressed Man[color(white)]
[tab]D-Don’t worry. Sumaru City is alright.
[tab]They said that on the news...(Is this a
[tab]new way of coaxing, or is she serious?)
[wait][clear][end]

msg_75:
[color(yellow)]Glittery-Eyed Girl[color(white)]
[tab]I’m sorry for losing it there... but I can
[tab]not hold back my emotions in front of you.
[tab][delay(30)]... Ah, this is sooo cute! I want it!
[wait][clear][end]

msg_76:
[color(yellow)]Distressed Man[color(white)]
[tab]S-Shouldn’t you think it over...?
[tab]Compulsive buying can lead to regrets...
[tab]Come on, think about it carefully.
[wait][clear][end]

msg_77:
[color(yellow)]Glittery-Eyed Girl[color(white)]
[tab]I was so scared!! If that person
[tab]didn’t come, I might’ve been killed...
[tab]You turned out to be unreliable!
[wait][clear][end]

msg_78:
[color(yellow)]Distressed Man[color(white)]
[tab]But they were New World Order? I had no
[tab]chance... That guy was strong, but I don’t
[tab]know about that "1" thing on his back...
[wait][clear][end]

msg_79:
[color(yellow)]Glittery-Eyed Girl[color(white)]
[tab]I wasn’t scared when I saw that dragon.
[tab]In fact, I thought it was beautiful...
[tab]Does that mean I’m impure?
[wait][clear][end]

msg_80:
[color(yellow)]Distressed Man[color(white)]
[tab]Don’t be foolish. There’s no way you’re
[tab]impure. You’re more pure than anyone.
[tab]I know... better than anyone...
[wait][clear][end]

msg_81:
[color(yellow)]Glittery-Eyed Girl[color(white)]
[tab]...Really? Really...!?
[tab]Then you know what I want, right...?
[tab]Here’s a hint: I want it for my birthday!
[wait][clear][end]

msg_82:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome...

[wait][clear][end]

msg_83:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. What do you...
[tab]...Eh? ...Weapons? ...Armor?
[tab]We don’t handle any of those here?
[wait][clear][end]

msg_84:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Ready-made accessories not enough for ya?
[tab]If you want, you can get ones custom made.
[tab]...But, you gotta supply the materials.
[wait][clear][end]

msg_85:
[color(yellow)]Jewelry Designer[color(white)]
[tab]So, you were safe too! Just like before,
[tab]I’m counting on your business... 
[tab]The last store? It’s under a heap of rubble now.[wait][clear][end]

msg_86:
[color(yellow)]Jewelry Designer[color(white)]
[tab]So, you were safe too! Just like before,
[tab]I’m counting on your business... 
[tab]The last store? It’s under a heap of rubble now.[wait][clear][end]

msg_87:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. What do you...
[tab]...Eh? ...Weapons? ...Armor?
[tab]We don’t handle any of those here?
[wait][clear][end]

msg_88:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Ready-made accessories not enough for ya?
[tab]If you want, you can get ones custom made.
[tab]...But, you gotta supply the materials.
[wait][clear][end]

msg_89:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. So, how are the accessories
[tab]I made?[delay(30)] ...Aaah, it seems
[tab]my products match you well.
[wait][clear][end]

msg_90:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Yes! Compatibility is important.
[tab]You find treasure in this meeting...
[tab]Okay... I’ll give you a discount today.
[wait][clear][end]

msg_91:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. So, how are the accessories
[tab]I made?[delay(30)] ...Aaah, it seems
[tab]my products match you well.
[wait][clear][end]

msg_92:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Yes! Compatibility is important.
[tab]You find treasure in this meeting...
[tab]Okay... I’ll give you a discount today.
[wait][clear][end]

msg_93:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. What do you...
[tab]...Eh? ...Weapons? ...Armor?
[tab]We don’t handle any of those here?
[wait][clear][end]

msg_94:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Ready-made accessories not enough for ya?
[tab]If you want, you can get ones custom made.
[tab]...But, you gotta supply the materials.
[wait][clear][end]

msg_95:
[color(yellow)]Jewelry Designer[color(white)]
[tab]So, you were safe too! Just like before,
[tab]I’m counting on your business... 
[tab]The last store? It’s under a heap of rubble now.[wait][clear][end]

msg_96:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. So, how are the accessories
[tab]I made?[delay(30)] ...Aaah, it seems
[tab]my products match you well.
[wait][clear][end]

msg_97:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Yes! Compatibility is important.
[tab]You find treasure in this meeting...
[tab]Okay... I’ll give you a discount today.
[wait][clear][end]

msg_98:
[color(yellow)]Jewelry Designer[color(white)]
[tab]So, you were safe too! Just like before,
[tab]I’m counting on your business... 
[tab]The last store? It’s under a heap of rubble now.
[wait][clear][end]

msg_99:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome. What do you...
[tab]...Eh? ...Weapons? ...Armor?
[tab]We don’t handle any of those here?
[wait][clear][end]

msg_100:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Ready-made accessories not enough for ya?
[tab]If you want, you can get ones custom made.
[tab]...But, you gotta supply the materials.
[wait][clear][end]

msg_101:
[color(yellow)]Jewelry Designer[color(white)]
[tab]I thought as much, but they do seem
[tab]to match your tastes...
[tab]Okay... I’ll give you a discount today.
[wait][clear][end]

msg_102:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What’s that? ...Legendary Blacksmith!?
[tab]Secret Document!? Sounds suspicious...
[tab]Here, let me see.
[wait][clear][end]

msg_103:
[color(yellow)]Jewelry Designer[color(white)]
[tab]. . . [delay(15)]. . . [delay(15)]. . . [delay(15)]! ! ! !
[tab]Holy crap!!
[tab]If I made it like this... it’d be powerful!
[wait][clear][end]

msg_104:
[color(yellow)]Jewelry Designer[color(white)]
[tab]But I know even the black market doesn’t
[tab]carry those materials...
[wait][clear][end]

msg_105:
[color(yellow)]Jewelry Designer[color(white)]
[tab]If you want me to forge you this weapon,
[tab]then bring me the necessary materials...
[tab]If you’ve got the goods, I can make it!!
[wait][clear][end]

msg_106:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Welcome...
[tab]What do you want today? ...Hmm?
[choice(6)]Buy accessories
Sell items
Talk to the Designer
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_107:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_108:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about his shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_109:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want today? ...Hmm?
[choice(7)]Develop
Buy accessories
Sell items
Talk to the Designer
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_110:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_111:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about his shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_112:
[color(yellow)]Jewelry Designer[color(white)]
[tab]These are all my finest creations!
[tab]Take a close look at them.
[choice(6)]Buy accessories
Sell items
Talk to the Designer
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_113:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_114:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about his shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_115:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want today? ...Hmm?
[choice(7)]Develop
Buy accessories
Sell items
Talk to the Designer
[if_all(EBIT_SINARIOFF)]Check items
Never mind
Leave the store
[end_choice][clear][end]

msg_116:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What would you like to sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear][end]

msg_117:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want to talk about?
[choice(3)]Make small talk
Ask about his shop
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_118:
[color(yellow)]Jewelry Designer[color(white)]
[tab]I notice individuality lacking these days.
[tab]Not in fashion, but in ways of living and
[tab]thinking. Don’t you agree...?
[wait][clear][end]

msg_119:
[color(yellow)]Jewelry Designer[color(white)]
[tab]I wonder what’s inside the Ameno Torifune?
[tab]Undiscovered metals and O-Parts abound...
[tab]I’m so excited... Is that inappropriate?
[wait][clear][end]

msg_120:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What would YOU do if you found something
[tab]you wanted? ...I’d nab it without a thought.
[tab]Despite the cost! It’s like love, ya know?
[wait][clear][end]

msg_121:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Everyone here believes they are safe. 
[tab]Well, I guess Wang Long fortunes never miss...
[tab]So the people below are gonna die?
[wait][clear][end]

msg_122:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Nothing happened... Did the New World Order
[tab]plans fail? The world needs to be rebuilt
[tab]anyway. Good thing I learned a trade.
[wait][clear][end]

msg_123:
[color(yellow)]Jewelry Designer[color(white)]
[tab]I’m used to getting ready-made accessories,
[tab]but weapons and armor are different...
[tab]But why did I accept it?
[wait][clear][end]

msg_124:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Beautiful stones are only materials to me.
[tab]Tell me if you want to craft something...
[tab]I’ll make anything.
[wait][clear][end]

msg_125:
MBIT[tab]HI[tab]NANJOTOUJO
南条出現噂:広げた
びっとお~んッ!!
[wait][clear][end]

msg_126:
噂による変化
びっとお~んッ!!
[wait][clear][end]

msg_127:
MBIT[tab]KE[tab]JEWKOUNAN
噂による港南区移転
びっとお~んッ!!
[wait][clear][end]

msg_128:
MBIT[tab]AIS[tab]33
相性占いの
びっとお~んッ!!
[wait][clear][end]

msg_129:
EBIT[tab]E006F
「研究施設・TV局クリア」
びっとお~んッ!!
[wait][clear][end]

msg_130:
EBIT[tab]E0077
「スマイル平坂クリア・Katsuya離脱」
びっとお~んッ!!
[wait][clear][end]

msg_131:
EBIT[tab]E007A
「野音クリア・Katsuya編入」
びっとお~んッ!!
[wait][clear][end]

msg_132:
EBIT[tab]E007B
「竜蔵と殺し屋の電話を盗聴」
びっとお~んッ!!
[wait][clear][end]

msg_133:
EBIT[tab]E007F
「廃工場クリア・Baofu編入」
びっとお~んッ!!
[wait][clear][end]

msg_134:
EBIT[tab]E008C
「海底遺跡クリア」
びっとお~んッ!!
[wait][clear][end]

msg_135:
EBIT[tab]E009F
「岩戸山クリア・南条かエリー離脱・達哉編入」
びっとお~んッ!!
[wait][clear][end]

msg_136:
EBIT[tab]E00AF
「アメノトリフネクリア」
びっとお~んッ!!
[wait][clear][end]

msg_137:
EBIT[tab]E00B8
「珠「瑠城クリア」
びっとお~んッ!!
[wait][clear][end]

msg_138:
[color(yellow)]Jewelry Designer[color(white)]
[tab]What do you want to talk about?
[choice(3)][if_all(MBIT_KE_JEWDEVE)]Ask about development
Ask about shopping
Never mind
[end_choice][clear][end]

msg_139:
[color(yellow)]Jewelry Designer[color(white)]
[tab]You want to hear about development?
[wait][clear][color(yellow)]Jewelry Designer[color(white)]
[tab]Select "Develop" here at the store and 
[tab]you can request custom-made weapons and
[tab]armors for me to craft.
[wait][clear][color(yellow)]Jewelry Designer[color(white)]
[tab]However, you have to provide the materials.
[tab]No matter how skilled I am, I cannot craft
[tab]anything without the proper materials. 
[wait][clear][color(yellow)]Jewelry Designer[color(white)]
[tab]There’s also a fee for crafting. 
[tab]The materials may be hard to find but I 
[tab]guarantee that the products will be of high quality.
[wait][clear][end]

msg_140:
[color(yellow)]Jewelry Designer[color(white)]
[tab]You want to hear about shopping?
[wait][clear][color(yellow)]Jewelry Designer[color(white)]
[tab]You can "Buy accessories" here at the store.
[tab]I mainly sell jewelry with precious stones
[tab]so it won’t be cheap. Look carefully at the prices.
[wait][clear][color(yellow)]Jewelry Designer[color(white)]
[tab]You can also "Sell items" here. First, select 
[tab]the type of item you want to sell and then
[tab]select the specific item.
[wait][clear][color(yellow)]Jewelry Designer[color(white)]
[tab]I will buy it for around half the buying price.
[tab]I also won’t buy anything you currently have
[tab]equipped.
[wait][clear][end]

msg_141:
[color(yellow)]Jewelry Designer[color(white)]
[tab]...Hmm? Unfortunately you don’t have 
[tab]anything to sell.
[wait][clear][end]

msg_142:
[color(yellow)]Jewelry Designer[color(white)]
[tab]That’ll be ¥[var(msg_var_0)] Is that okay?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_143:
[color(yellow)]Jewelry Designer[color(white)]
[tab]I could buy that for ¥[var(msg_var_0)].
[tab]Do you want to sell it?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_144:
[color(yellow)]Jewelry Designer[color(white)]
[tab]Alright, I could craft that.
[tab]Is this okay?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_145:
[color(yellow)]Jewelry Designer[color(white)]
[tab]...Hmm? Unfortunately you can’t afford
[tab]my development fee.
[choice(1)]Ok
[end_choice][clear][end]
