
msg_0:
Contact Kaneda / Kataoka.
[tab][wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Is it okay to believe in this place?
[tab]There was that incident with Wang Long...
[tab]Shouldn’t we be a little more careful?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]What kind of connection do
[tab]Bao and Yung Pao have from their past?
[tab]Bao seems to hate him really bad...
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]I think that in the end,
[tab]Bao and Detective [suou] make a great duo. 
[tab]They’re so opposite.
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Why does [tatsuya]-kun try to dodge us so much?
[tab][tatsuya]-kun is Detective [suou]’s brother, right?
[tab]I just don’t know...
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]So that’s what [tatsuya]-kun meant by saying
[tab]that he wasn’t the Detective’s brother...
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya] [suou] and Katsuya [suou]...
[tab]The [suou] Brothers... That’s kinda confusing.
[end]

msg_7:
[tab]From now on, Katsuya is "[suou]-nii".
[wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab]Awwwwwwwwwe...
[tab][tatsuya]-kun was called "[tatsu]"
[tab]over on the "Other Side".
[wait][clear][end]

msg_9:
[color(yellow)]Ulala[color(white)]
[tab]Well, yeah, gods and fortune tellings
[tab]are all figments of the imagination...
[wait][clear][color(yellow)]Ulala[color(white)]
[tab]I think it’s fine like that.
[tab]That’s how people today keep on going...
[tab]It’d be boring having everything settled.
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Fortune telling itself was a foundation of
[tab]New World Order. We can’t do anything now
[tab]with the power of fortune telling.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]Baofu is not foolish enough to go in
[tab]alone. He’s most likely waiting
[tab]for us to get there.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]A 2-legged weapon implanted with human
[tab]nerve tissue. So that’s it. We must hurry,
[tab]or Baofu’s going to be in trouble.
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Let me say that I have no intention of
[tab]letting Saga kill Tatsuzou.
[tab]The law will judge him... not us.
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]I wonder when it was that [tatsuya] became
[tab]like that... Well... it’s partly my fault
[tab]for not teaching him otherwise...
[wait][clear][end]

msg_15:
[color(yellow)]Katsuya[color(white)]
[tab]Please Amano-kun... 
[tab]I want to know the truth...
[tab]Let’s go to Mt. Iwato...
[wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]Serizawa-kun... I don’t mind what you call me, but... 
[tab]Don’t you think that...
[tab]"[suou]-nii" is a bit too informal...?
[wait][clear][end]

msg_17:
[color(yellow)]Katsuya[color(white)]
[tab]"[tatsu]", huh...
[tab]It’s not a bad nickname.
[tab]Hmm? Then what about me?
[wait][clear][end]

msg_18:
[color(yellow)]Katsuya[color(white)]
[tab]The root of all evil...
[tab]It fits him perfectly.
[tab]That is the shadow of us humans...
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Like God, I don’t believe in fortunes either. 
[tab]Do whatever you want, 
[tab]but don’t waste too much cash.
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]Ch, the wuss is still trying
[tab]to only arrest?
[tab]...Geez... That stupid lunk head...
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]What’s wrong? Aren’t we going to listen to
[tab]what that kid’s gotta say...?
[tab]We don’t need to have a fortune told.
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]I heard from [tatsuya], on the "Other Side", 
[tab]that mystic was a rumormonger.
[tab]As I thought, it’s slightly different.
[wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]Geez, they’re getting all hyped
[tab]about some stupid crap...
[tab]That’s not what we need to worry about.
[wait][clear][end]

msg_24:
[color(yellow)]Baofu[color(white)]
[tab]It’s pathetic, but when I saw him,
[tab]I didn’t feel like I could beat him...
[tab]It was like... a kid and an adult...
[wait][clear][end]

msg_25:
[color(yellow)]Nanjo[color(white)]
[tab]Lately, people lack the courage to decide
[tab]for themselves, and rely on fortunes for
[tab]their life decisions.
[wait][clear][end]

msg_26:
[color(yellow)]Nanjo[color(white)]
[tab]Yung Pao’s roles were the murders and the
[tab]Joker-hunts. If this is to make the
[tab]circulation of information a success, then...
[wait][clear][end]

msg_27:
[color(yellow)]Nanjo[color(white)]
[tab]Hmmmm... If you add Sergeant [suou]
[tab]and Mr. Baofu, then divvy them up,
[tab]it may work out well.
[wait][clear][end]

msg_28:
[color(yellow)]Nanjo[color(white)]
[tab]Keystone... I should have investigated into
[tab]Wang Long more... That way, I might have
[tab]been able to protect the other seals...
[wait][clear][end]

msg_29:
[color(yellow)]Elly[color(white)]
[tab]That fortune teller’s voice... Something’s
[tab]wrong... Like she’s making it be weak...
[end]

msg_30:
[tab]...C-Could it be, she’s really a ma...
[wait][clear][end]

msg_31:
[color(yellow)]Elly[color(white)]
[tab]If all those cases New World Order did
[tab]were to prepare to circulate information,
[tab]then with it completed...
[wait][clear][end]

msg_32:
[color(yellow)]Elly[color(white)]
[tab]If you add Mr. Katsuya and
[tab]Mr. Baofu, then split them in 
[tab]half, it might turn out fine.
[wait][clear][end]

msg_33:
[color(yellow)]Elly[color(white)]
[tab]Wang Long Chizuru... She may have seen
[tab]something in Mr. Kandori...
[tab]As a woman...
[wait][clear][end]

msg_34:
[color(yellow)][tatsuya][color(white)]
[tab]That fortune teller...
[tab]She was a rumormonger on the Other Side...
[tab]So she’s not on This Side...
[wait][clear][end]

msg_35:
[color(yellow)][tatsuya][color(white)]
[tab]I’ve...
[tab]betrayed everyone again...
[end]

msg_36:
[tab]I’m sorry... Leave me be.
[wait][clear][end]

msg_37:
[color(yellow)][tatsuya][color(white)]
[tab]Ulala-san asked me what I was called
[tab]on the "Other Side"...
[tab]All I did was answer...
[wait][clear][end]

msg_38:
[color(yellow)][tatsuya][color(white)]
[tab]As soon as I saw him...
[tab]All my reasoning was blown away...
[tab]I’ve... never been so angry before.
[wait][clear][end]

msg_39:
[color(yellow)]Cowardly man[color(white)]
[tab]You know...
[tab]I’m timid so... I’m no good...
[tab]What I’m no good at... is deciding...
[wait][clear][color(yellow)]Cowardly man[color(white)]
[tab]That’s why I’m here to have
[tab]my fortune told to me...
[tab]I’m scared of messing up.
[wait][clear][end]

msg_40:
[color(yellow)]Cowardly man[color(white)]
[tab]Um... What do you want?
[tab]Is there something you want?
[tab]Then can you make it quick?
[wait][clear][end]

msg_41:
[tab]So... what do you want?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_42:
YUUTA IKENAKA
[end]

msg_43:
[color(yellow)]Cowardly man[color(white)]
[tab]Who’s that...?
[tab]I don’t know anyone by that name...
[tab]Are you mistaking me for someone?
[wait][clear][end]

msg_44:
[color(yellow)]Cowardly man[color(white)]
[tab]...!?
[tab]How’d you know my name...?
[tab]Are you a psychic?
[wait][clear][color(yellow)]Yuuta Ikenaka[color(white)]
[tab]What? Man-search?
[tab]A search for me?
[tab]That’s surprising.
[wait][clear][color(yellow)]Yuuta Ikenaka[color(white)]
[tab]Well, I got it.
[tab]I’ll call Shiraishi.
[tab]Thanks.
[wait][clear][end]

msg_45:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_46:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_47:
[tab]They’re starting to do Wang Long fortunes here. 
[tab]And everyone says they come true.
[tab]That’s why I’m here, but I’m nervous.
[wait][clear][end]

msg_48:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_49:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_50:
[tab]That fortune teller does it all. Now she’s
[tab]starting to do Affinity Readings. But
[tab]I’m sad that I have good affinity with men.
[wait][clear][end]

msg_51:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_52:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_53:
[tab]They say that her readings come true.
[tab]If you have affinity with owners of stores,
[tab]you can get discounts and stuff.
[wait][clear][end]

msg_54:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_55:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_56:
[tab]But just because you have compatibility
[tab]doesn’t mean that you’ll always get
[tab]something in return.
[wait][clear][end]

msg_57:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_58:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_59:
[tab]There are people who don’t care about
[tab]affinity, and others don’t let it show
[tab]on the outside.
[wait][clear][end]

msg_60:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_61:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_62:
[tab]Looks like she has increased her powers.
[tab]How, you ask? ...By her "Affinity Readings".
[tab]There are more ones to be compatible with.
[wait][clear][end]

msg_63:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_64:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_65:
[tab]There are people who’ve had the ladies from
[tab]Satomi Tadashi come out. You may
[tab]meet someone you’ve never expected.
[wait][clear][end]

msg_66:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_67:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_68:
[tab]This place’s fortunes really do come true.
[tab]So I had mine told...
[tab]It looks like I can’t get married...
[wait][clear][end]

msg_69:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_70:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_71:
[tab]When the 12 Dragons meet at one spot,
[tab]something very tragic will happen. If the
[tab]world was ending, that would be the cause.
[wait][clear][end]

msg_72:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_73:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_74:
[tab]Th... That earthquake was big.
[tab]It kept shaking and shaking.
[tab]This must be from the Torifune, huh!?
[wait][clear][end]

msg_75:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_76:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_77:
[tab]The Torifune legend is true!
[tab]So if the 12 Dragons gather together...
[tab]the world will end!!
[wait][clear][end]

msg_78:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_79:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_80:
[tab]B-But I don’t know what is going on...
[tab]A... Are the earth’s poles shifting...?
[tab]Th... That’s not good!
[wait][clear][end]

msg_81:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_82:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_83:
[tab]The dragons disappeared!!
[tab]And then, the sky turned blood red...
[tab]Even the fortunes didn’t mention that!
[wait][clear][end]

msg_84:
[color(yellow)]Young Man[color(white)]
[tab]You’ve heard of "New World Order"? 
[tab]There’s a group calling themselves that... Huh?
[tab]...Wasn’t there something like this before?
[wait][clear][end]

msg_85:
[color(yellow)]Young Man[color(white)]
[tab]I saw a bunch of black cars heading
[tab]toward the Abandoned Factory...
[tab]Is something going on there?
[wait][clear][end]

msg_86:
[color(yellow)]Young Man[color(white)]
[tab]There seems to have been a gunfight
[tab]at the Factory...
[tab]This city’s getting dangerous...
[wait][clear][end]

msg_87:
[color(yellow)]Young Man[color(white)]
[tab]Is it true that the Tenchu Army is killing
[tab]people with "sin"? Their objective is to
[tab]rid the world of this "Kegare", right...?
[wait][clear][end]

msg_88:
[color(yellow)]Young Man[color(white)]
[tab]As long as we’re on the Torifune, 
[tab]we won’t die, right? B... But eventually 
[tab]we’ll be killed by the New World Order... 
[wait][clear][end]

msg_89:
[color(yellow)]Young Man[color(white)]
[tab]The brainwashed people were saying strange
[tab]things... "This isn’t the promised land"...
[tab]They were in more of a panic than we were.
[wait][clear][end]

msg_90:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is there anything else...?
[tab]Speak as thou wish.
[sync][wait][clear][end]

msg_91:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Those who are lost in the maze of life gather here...
[tab]The ray of light in the darkness of future, 
[tab]I am the Sumaru Genie.
[sync][wait][clear][end]

msg_92:
[color(yellow)]Sumaru Genie[color(green)]
[tab]A fortune teller with a husky voice. 
[tab]Her fortunes haven’t been accurate lately. 
[tab]They say her double roams the city at night.[color(white)]
[sync][wait][clear][end]

msg_93:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmmm... This is thy first time here...
[tab]Then disclose what is in thy heart. 
[tab]The crystal and the card shall reveal the light...
[sync][wait][clear][end]

msg_94:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Oh, the customers from the other day...
[tab]Actually, there was a rumor that
[tab]I have started Wang Long fortune telling.
[sync][wait][clear][end]

msg_95:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I decided to do it, and now my fortunes
[tab]actually do come true!! This is a gift
[tab]from above! ...Is that great or what!?
[sync][wait][clear][end]

msg_96:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Now all my answers shall become reality!
[tab]It is all right this time...
[tab]Disclose what is in thy heart.
[sync][wait][clear][end]

msg_97:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmmmm...
[tab]Did I do Affinity Readings?
[tab]Wait... I feel that I did...
[sync][wait][clear][end]

msg_98:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It is best to try anything.
[tab]I started Wang Long in the same fashion.
[tab]Let me start over...
[sync][wait][clear][end]

msg_99:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I’ve begun doing Affinity Readings.
[tab]If it is thy wish, I shall reveal to thou
[tab]a well-suited match in this crystal.
[sync][wait][clear][end]

msg_100:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Recently, there have been many strange
[tab]rumors about me. This time they say I have
[tab]gained power... What can I do to match that.
[sync][wait][clear][end]

msg_101:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Well... It is not that I cannot do it...
[tab]It was the same with Wang Long.
[tab]I must take the initiative.
[sync][wait][clear][end]

msg_102:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Through daily training, I am now able to
[tab]sense more compatibilities...
[tab]Seeing is believing. It is best to try it.
[sync][wait][clear][end]

msg_103:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Welcome...

[sync][wait][clear][end]

msg_104:
[color(yellow)]Sumaru Genie[color(white)]
[tab]For what have you sought me out today?
[choice(4)]Hear your fortune
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_105:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_106:
[color(yellow)]Sumaru Genie[color(white)]
[tab]For what have you sought me out today?
[choice(5)]Hear your fortune
Affinity Reading
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_107:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_108:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is there anything else...?
[tab]Speak as thou wish.
[sync][wait][clear][end]

msg_109:
[color(yellow)]Sumaru Genie[color(white)]
[tab]From now on Wang Long is the way...
[tab]They say that it really works...
[tab]Perhaps I should change it...
[sync][wait][clear][end]

msg_110:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It is great having my fortunes come true
[tab]again. I should start something new...
[tab]Hmmm... Speaking of fortunes...
[sync][wait][clear][end]

msg_111:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is it true those who went to the seminar
[tab]were brainwashed? Then, is Wang Long
[tab]Chizuru an ally of New World Order...?
[sync][wait][clear][end]

msg_112:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Feng Shui is the foundation of Wang Long...
[tab]Do the techniques of fortune telling have
[tab]enough power to destroy the world...
[sync][wait][clear][end]

msg_113:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmm...? That red-clothed young man...
[tab]He appeared in a dream I had earlier...
[tab]I feel... this is a meeting of fate.
[sync][wait][clear][end]

msg_114:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I... I am not fond of high places...
[tab]When I think about this city as floating...
[tab]I just feel a draft down below...
[sync][wait][clear][end]

msg_115:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What happened outside...?
[tab]I have been here the entire time...
[tab]What about dragons?
[sync][wait][clear][end]

msg_116:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I’m sorry... Since Wang Long became famous,
[tab]my fortunes have stopped working
[tab]all of a sudden.
[sync][wait][clear][end]

msg_117:
[color(yellow)]Sumaru Genie[color(white)]
[tab]A fortune teller without fortunes...
[tab]I must do something about this...
[sync][wait][clear][end]

msg_118:
[color(yellow)]Sumaru Genie[color(white)]
[tab]When thou waverest off of thy path,
[tab]come again at any opportunity...
[sync][wait][clear][end]

msg_119:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Also, my Affinity Reading has nothing to do
[tab]with contacts. There shall be no change in
[tab]the commands. Do not be mistaken.
[sync][wait][clear][end]

msg_120:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Even after gaining power, my affinities
[tab]have nothing to do with contacts. There
[tab]shall be no change in the commands.
[sync][wait][clear][end]

msg_121:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I shall tell thy fortune.
[tab]Amu amu amu... bymo rea tlus...
[tab]Crystal ball, reveal to us the future...
[sync][wait][clear][end]

msg_122:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...Thou art a man!? Those clothes
[tab]are all camouflage, and thou plannest to
[tab]get even for not getting any...
[sync][wait][clear][end]

msg_123:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_124:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...That’s not it...
[tab]There’s no way that can be...
[sync][wait][clear][end]

msg_125:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I see...
[tab]Thou bearest two children.
[tab]One is a high-spirited first-grader!!
[sync][wait][clear][end]

msg_126:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_127:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...You don’t have any, huh...
[tab]...You’re probably single...
[tab]...I know that already...
[sync][wait][clear][end]

msg_128:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I see... Thou art from a land far away.
[tab]America... No, France...
[tab]Yes, thou art French!!
[sync][wait][clear][end]

msg_129:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_130:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...You’re Japanese.
[tab]...You’re Japanese, right? Figures.
[tab]...I know that already...
[sync][wait][clear][end]

msg_131:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...! Thou usest pads in thy shirt...!!
[tab]Thou art planning to entice all the
[tab]the men with that sexy, but fake, body...
[sync][wait][clear][end]

msg_132:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_133:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It... It’s a joke...
[tab]Do not take it seriously.
[tab]It-It’s real, isn’t it...?
[sync][wait][clear][end]

msg_134:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmm... Thou art a teacher.
[tab]...I believe an English teacher.
[tab]It is written on thy face.
[sync][wait][clear][end]

msg_135:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_136:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...No? ...That wasn’t it?
[tab]...Eh? Magazine editor...
[tab]Haha... That’s completely different...
[sync][wait][clear][end]

msg_137:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Very well.
[tab]It shall cost you ¥3000.
[sync][wait][clear][end]

msg_138:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is that fine?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_139:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It seems thou dost not have enough money.
[tab]Money is the key that opens all doors.
[tab]Come back again.
[sync][wait][clear][end]

msg_140:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Wait. Thou still hast the spell of
[tab]the [end]

msg_141:
Light Dragon[end]

msg_142:
Black Dragon[end]

msg_143:
Yellow Dragon[end]

msg_144:
Blue Dragon[end]

msg_145:
Red Dragon[end]

msg_146:
Silver Dragon[end]

msg_147:
 cast upon thee.
[tab]Return when thou hast regained oneself.
[sync][wait][clear][end]

msg_148:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Let us begin...
[tab]Wang Long, Wang Long, Wang Looong!!
[end]

msg_149:
[tab]Looong, Looooooong!!!
[sync][wait][clear][end]

msg_150:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I sense bright light, the Light Dragon...
[tab]Thou shalt receive much experience, but
[tab]thy luck with money is down.
[sync][wait][clear][end]

msg_151:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I sense dark earth... the Black Dragon...
[tab]Thou shalt have no problem with money,
[tab]but thou shall gain little experience.
[sync][wait][clear][end]

msg_152:
[color(yellow)]Sumaru Genie[color(white)]
[tab]This lively dragon... the Yellow Dragon...
[tab]Thou shalt be engulfed in luck.
[tab]Now is the time to take chances.
[sync][wait][clear][end]

msg_153:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I sense quiet tides... the Blue Dragon...
[tab]Thou shalt see a hidden side of others.
[tab]There shall be a change of personalities.
[sync][wait][clear][end]

msg_154:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Full of passion... the Red Dragon...
[tab]Thou and thy friends shall be excited,
[tab]and shall shout victoriously after battle.
[sync][wait][clear][end]

msg_155:
[color(yellow)]Sumaru Genie[color(white)]
[tab]This light of truth... the Silver Dragon...
[tab]Thou shalt become at a loss for words,
[tab]and shall have no luck with negotiations...
[sync][wait][clear][end]

msg_156:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Now... Is there anything else...?
[tab]Speak as thou wish.
[choice(4)]Hear your fortune
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_157:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_158:
[color(yellow)]Sumaru Genie[color(white)]
[tab]For what have you sought me out today?
[choice(5)]Hear your fortune
Affinity Reading
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_159:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_160:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Very well.
[tab]It shall cost you ¥5000.
[sync][wait][clear][end]

msg_161:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is that fine?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_162:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It seems thou dost not have enough money.
[tab]Money is the key that opens all doors.
[tab]Come back again.
[sync][wait][clear][end]

msg_163:
Pick
[choice(5)][color(pink)]Wang Long[color(white)]
[color(blue)]Affinity Reading[color(white)]
[color(green)]Power up[color(white)]
[color(orange)]Money[color(white)]
[color(gray)]Done[color(white)]
[end_choice][clear][end]

msg_164:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Ask about fortune telling
[if_all(MBIT_HI_GYPAISHO1)]Ask about affinity reading.
Never mind.
[end_choice][clear][end]

msg_165:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Then I shall explain what I do here.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]Ask to "Hear your fortune" and I will take
[tab]a glimpse into your future.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]The reading may result in good fortune or
[tab]bad fortune for you.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]I cannot peer into your future again until
[tab]the effect of the previous reading wears off.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]The choice is yours. And I am not responsible
[tab]for the visions I see.
[wait][clear][end]

msg_166:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I’ll explain affinity readings to you.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]Ask for an "Affinity reading" and I will
[tab]ask you some questions. Based on your answers
[tab]I will match you with a compatible person.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]That person may respond more positively 
[tab]to you when you meet them again.
[wait][clear][end]
