
msg_0:
More than four in party.
[tab]It’s gonna hang.
[tab]Contact Kaneda or Kataoka.
[tab][wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Huh? You want your fortune told, Ma-ya?
[tab]Then use Wang Long.
[tab]That one works way better.
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]I just get the feeling "that brat" he mentioned...
[tab]Could that be the D五j二 Vu Boy?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Come to think of it, I tried a psychic
[tab]network to track Makimura down...
[tab]I don’t need it anymore.
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]We saved that girl Noriko-chan...
[tab]But she was lucky.
[tab]There probably are many others kidnapped...
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Doesn’t that Nanjo-kun look older than I do?
[tab]He’s just too good... way too proper.
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Wang Long was a ploy...(sigh)... 
[tab]Why am I so easily duped? I have no luck...
[tab]Not just with men, but with fortunes, too.
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]On some level or another, I was right to
[tab]go along with you. Before, I would’ve
[tab]cheerfully gone to the seminar.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]Who was "that brat" Sudou spoke of...?
[tab]From what I heard, this seems to be
[tab]related to you, Amano-kun...
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]After that, I had my men search the beach,
[tab]but I couldn’t find [tatsuya]...
[tab]Where is he hiding...?
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Many versus a few...
[tab]We can’t stop all of the kidnappings.
[tab]If we only know where they’re being held...
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]Nanjo-kun is 20 years old, and [tatsuya] is 18.
[tab]Only 2 years difference... But still,
[tab]there’s a gap as wide as heaven and hell...
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]The penthouse incident...
[tab]Was that the work of Sneak...?
[tab]...But...
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]So whenever someone did the Joker curse,
[tab]he slipped out of that sanitarium room...
[tab]Thanks for your trouble, buddy.
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab]Be it fortunes or be it gods,
[tab]can these guys do anything without having
[tab]to rely on something?
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]Huh? How about Persona, you say...?
[tab]Didn’t I mention it before...?
[tab]Persona’s just a tool, nothing more...
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]Ah? Did I really kill 25 people, you ask?
[tab]Don’t you mean 25 things...?
[tab]I have no inclination that I killed people.
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]You can’t touch an angry woman, huh...
[tab]Or is that just Serizawa?
[tab]Geez... I’m never playing that role again.
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]That Sneak may have leaked information to
[tab]get us to find rich boy and rich girl.
[wait][clear][end]

msg_19:
[color(yellow)]Nanjo[color(white)]
[tab]In the end, Fate is in Heaven’s hands...
[tab]No matter what you use to predict with,
[tab]the principle will not change.
[wait][clear][end]

msg_20:
[color(yellow)]Nanjo[color(white)]
[tab]People may question our methods, 
[tab]but everything has its useful purpose...
[tab]We have something we must protect.
[wait][clear][end]

msg_21:
[color(yellow)]Elly[color(white)]
[tab]What a strange fortune teller, using tarot
[tab]cards and a crystal ball at the same time.
[tab]I don’t think it can possibly work...
[wait][clear][end]

msg_22:
[color(yellow)]Elly[color(white)]
[tab]Hmm...?
[tab]Wasn’t this place a tarot mystic...
[tab]I wonder if she changed her style...
[wait][clear][end]

msg_23:
[color(yellow)]Elly[color(white)]
[tab]Bringing out the Joker in the background,
[tab]and telling people to do things to save
[tab]themselves. That’s the same as a threat.
[wait][clear][end]

msg_24:
[color(yellow)]Elly[color(white)]
[tab]But the people believe Chizuru up through
[tab]that last fortune... At this rate, 
[tab]it’s just what New World Order wants...
[wait][clear][end]

msg_25:
[color(yellow)]Makimura[color(white)]
[tab]That fortune teller’s voice...
[tab]I feel that I’ve heard it before...
[tab]and also that something bad happened to me...
[wait][clear][end]

msg_26:
[color(yellow)]Cowardly man[color(white)]
[tab]You know...
[tab]I’m timid so... I’m no good...
[tab]What I’m no good at... is deciding...
[wait][clear][color(yellow)]Cowardly man[color(white)]
[tab]That’s why I’m here to have
[tab]my fortune told to me...
[tab]I’m scared of messing up.
[wait][clear][end]

msg_27:
[color(yellow)]Cowardly man[color(white)]
[tab]Um... What do you want?
[tab]Is there something you want?
[tab]Then can you make it quick?
[wait][clear][end]

msg_28:
[tab]So... What do you want?
[choice(3)]Guess name
Talk
Nothing
[end_choice][clear][end]

msg_29:
YUUTA IKENAKA
[end]

msg_30:
[color(yellow)]Cowardly man[color(white)]
[tab]Who’s that...?
[tab]I don’t know anyone by that name...
[tab]Are you mistaking me for someone?
[wait][clear][end]

msg_31:
[color(yellow)]Cowardly man[color(white)]
[tab]...!?
[tab]How’d you know my name...?
[tab]Are you a psychic?
[wait][clear][color(yellow)]Yuuta Ikenaka[color(white)]
[tab]What? Man-search?
[tab]A search for me?
[tab]That’s surprising.
[wait][clear][color(yellow)]Yuuta Ikenaka[color(white)]
[tab]Well, I got it.
[tab]I’ll call Shiraishi.
[tab]Thanks.
[wait][clear][end]

msg_32:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_33:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_34:
[tab]They’re starting to do Wang Long fortunes here. 
[tab]And everyone says they come true.
[tab]That’s why I’m here, but I’m nervous.
[wait][clear][end]

msg_35:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_36:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_37:
[tab]That fortune teller does it all. Now she’s
[tab]starting to do Affinity Readings. But
[tab]I’m sad that I have good affinity with men.
[wait][clear][end]

msg_38:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_39:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_40:
[tab]They say that her readings come true.
[tab]If you have affinity with owners of stores,
[tab]you can get discounts and stuff.
[wait][clear][end]

msg_41:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_42:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_43:
[tab]But just because you have compatibility
[tab]doesn’t mean that you’ll always get
[tab]something in return.
[wait][clear][end]

msg_44:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_45:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_46:
[tab]There are people who don’t care about
[tab]affinity, and others don’t let it show
[tab]on the outside.
[wait][clear][end]

msg_47:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_48:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_49:
[tab]Looks like she has increased her powers.
[tab]How, you ask? ...By her "Affinity Readings".
[tab]There are more ones to be compatible with.
[wait][clear][end]

msg_50:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_51:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_52:
[tab]There are people who’ve had the ladies from
[tab]Satomi Tadashi come out. You may
[tab]meet someone you’ve never expected.
[wait][clear][end]

msg_53:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_54:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_55:
[tab]I’m born in December, so in
[tab]Wang Long terms I’m a Purple Dragon.
[tab]I’m supposedly very straightforward...
[wait][clear][end]

msg_56:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_57:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_58:
[tab]Wang Long originally came from Feng Shui.
[tab]I don’t really know what that is, but
[tab]it doesn’t matter, as long as it works.
[wait][clear][end]

msg_59:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_60:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_61:
[tab]I... I never did the Joker curse. There was
[tab]a time when I wanted to do it, but I
[tab]stopped myself. That was the right choice.
[wait][clear][end]

msg_62:
[color(yellow)]Cowardly man[color(white)]
[end]

msg_63:
[color(yellow)]Yuuta Ikenaka[color(white)]
[end]

msg_64:
[tab]All the underground rivers are transformed
[tab]and amalgamated as Dragons...
[tab]There are 12 Dragons in all.
[wait][clear][end]

msg_65:
[color(yellow)]Young Man[color(white)]
[tab]I heard that this place started doing
[tab]Wang Long fortune readings...
[tab]Does fortune telling change that often?
[wait][clear][end]

msg_66:
[color(yellow)]Young Man[color(white)]
[tab]Does Wang Long fortune telling use those
[tab]chants...?
[tab]Does she just say Wang Long repeatedly?
[wait][clear][end]

msg_67:
[color(yellow)]Young Man[color(white)]
[tab]I saw it! ...A flying blimp!
[tab]W... Well, blimps are supposed
[tab]to fly... but... what I mean is...
[wait][clear][end]

msg_68:
[color(yellow)]Young Man[color(white)]
[tab]After seeing that TV show, my friend began
[tab]to panic. He said he used the Joker curse on
[tab]his rival. There’s no way he can be a Joker.
[wait][clear][end]

msg_69:
[color(yellow)]Young Man[color(white)]
[tab]My friend was arrested by the police.
[tab]He was arrested for aggravated assault...
[tab]He was always so quiet. Why...?
[wait][clear][end]

msg_70:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is there anything else...?
[tab]Speak as thou wish.
[sync][wait][clear][end]

msg_71:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Those who are lost in the maze of life gather here...
[tab]The ray of light in the darkness of future, 
[tab]I am the Sumaru Genie.
[sync][wait][clear][end]

msg_72:
[color(yellow)]Sumaru Genie[color(green)]
[tab]A fortune teller with a husky voice. 
[tab]Her fortunes haven’t been accurate lately. 
[tab]They say her double roams the city at night.[color(white)]
[sync][wait][clear][end]

msg_73:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmmm... This is thy first time here...
[tab]Then disclose what is in thy heart. 
[tab]The crystal and the card shall reveal the light...
[sync][wait][clear][end]

msg_74:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Oh, the customers from the other day...
[tab]Actually, there was a rumor that
[tab]I have started Wang Long fortune telling.
[sync][wait][clear][end]

msg_75:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I decided to do it, and now my fortunes
[tab]actually do come true!! This is a gift
[tab]from above! ...Is that great or what!?
[sync][wait][clear][end]

msg_76:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Now all my answers shall become reality!
[tab]It is all right this time...
[tab]Disclose what is in thy heart.
[sync][wait][clear][end]

msg_77:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmmmm...
[tab]Did I do Affinity Readings?
[tab]Wait... I feel that I did...
[sync][wait][clear][end]

msg_78:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It is best to try anything.
[tab]I started Wang Long in the same fashion.
[tab]Let me start over...
[sync][wait][clear][end]

msg_79:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I’ve begun doing Affinity Readings.
[tab]If it is thy wish, I shall reveal to thou
[tab]a well-suited match in this crystal.
[sync][wait][clear][end]

msg_80:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Recently, there have been many strange
[tab]rumors about me. This time they say I have
[tab]gained power... What can I do to match that.
[sync][wait][clear][end]

msg_81:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Well... It is not that I cannot do it...
[tab]It was the same with Wang Long.
[tab]I must take the initiative.
[sync][wait][clear][end]

msg_82:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Through daily training, I am now able to
[tab]sense more compatibilities...
[tab]Seeing is believing. It is best to try it.
[sync][wait][clear][end]

msg_83:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Welcome...

[sync][wait][clear][end]

msg_84:
[color(yellow)]Sumaru Genie[color(white)]
[tab]For what have you sought me out today?
[choice(4)]Hear your fortune
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_85:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_86:
[color(yellow)]Sumaru Genie[color(white)]
[tab]For what have you sought me out today?
[choice(5)]Hear your fortune
Affinity Reading
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_87:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_88:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is there anything else...?
[tab]Speak as thou wish.
[sync][wait][clear][end]

msg_89:
[color(yellow)]Sumaru Genie[color(white)]
[tab]From now on, Wang Long is the way...
[tab]They say that it really works...
[tab]Perhaps I should change it...
[sync][wait][clear][end]

msg_90:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It is great having my fortunes come true
[tab]again. I should start something new...
[tab]Hmmm... Speaking of fortunes...
[sync][wait][clear][end]

msg_91:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I am weary from telling too many fortunes...
[tab]That museum fire... I feel that it has
[tab]happened before... No, it couldn’t have.
[sync][wait][clear][end]

msg_92:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I watched Wang Long Chizuru on TV... 
[tab]Should I change the way I dress? By just 
[tab]changing the chant, there is something missing...
[sync][wait][clear][end]

msg_93:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Lately, there have been many kidnappings.
[tab]I hear it is a random-patterned crime.
[tab]Thou must be careful, too.
[sync][wait][clear][end]

msg_94:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I’m sorry... Since Wang Long became famous,
[tab]my fortunes have stopped working
[tab]all of a sudden.
[sync][wait][clear][end]

msg_95:
[color(yellow)]Sumaru Genie[color(white)]
[tab]A fortune teller without fortunes...
[tab]I must do something about this...
[sync][wait][clear][end]

msg_96:
[color(yellow)]Sumaru Genie[color(white)]
[tab]When thou waverest off of thy path,
[tab]come again at any opportunity...
[sync][wait][clear][end]

msg_97:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Also, my Affinity Reading has nothing to do
[tab]with contacts. There shall be no change in
[tab]the commands. Do not be mistaken.
[sync][wait][clear][end]

msg_98:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Even after gaining power, my Affinity
[tab]Reading has nothing to do with contacts.
[tab]There shall be no change in the commands.
[sync][wait][clear][end]

msg_99:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I shall tell thy fortune.
[tab]Amu amu amu... buymo reat lus...
[tab]Crystal ball, reveal to us the future...
[sync][wait][clear][end]

msg_100:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...Thou art a man!? Those clothes
[tab]are all camouflage, and thou plannest to
[tab]get even for not getting any...
[sync][wait][clear][end]

msg_101:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_102:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...That’s not it...
[tab]There’s no way that can be...
[sync][wait][clear][end]

msg_103:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I see...
[tab]Thou bearest two children.
[tab]One is a high-spirited first-grader!!
[sync][wait][clear][end]

msg_104:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_105:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...You don’t have any, huh...
[tab]...You’re probably single...
[tab]...I know that already...
[sync][wait][clear][end]

msg_106:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I see... Thou art from a land far away.
[tab]United States... No, France...
[tab]Yes, thou art French!!
[sync][wait][clear][end]

msg_107:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_108:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...You’re Japanese.
[tab]...You’re Japanese, right? Figures.
[tab]...I know that already...
[sync][wait][clear][end]

msg_109:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...! Thou usest pads in thy shirt...!!
[tab]Thou art planning to entice all the
[tab]the men with that sexy, but fake, body...
[sync][wait][clear][end]

msg_110:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_111:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It... It’s a joke...
[tab]Do not take it seriously.
[tab]I-It’s real, isn’t it...?
[sync][wait][clear][end]

msg_112:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Hmm... Thou art a teacher.
[tab]...I believe an English teacher.
[tab]It is written on thy face.
[sync][wait][clear][end]

msg_113:
[color(yellow)]Sumaru Genie[color(white)]
[tab]. . . . . .
[sync][wait][clear][end]

msg_114:
[color(yellow)]Sumaru Genie[color(white)]
[tab]...No? ...That wasn’t it?
[tab]...Eh? Magazine editor...
[tab]Haha... That’s completely different...
[sync][wait][clear][end]

msg_115:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Very well...
[tab]It shall cost you ¥3000.
[sync][wait][clear][end]

msg_116:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is that fine?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_117:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It seems thou dost not have enough money.
[tab]Money is the key that opens all doors.
[tab]Come back again.
[sync][wait][clear][end]

msg_118:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Wait. Thou still hast the spell of
[tab]the [end]

msg_119:
Light Dragon[end]

msg_120:
Black Dragon[end]

msg_121:
Yellow Dragon[end]

msg_122:
Blue Dragon[end]

msg_123:
Red Dragon[end]

msg_124:
Silver Dragon[end]

msg_125:
 cast upon thee.
[tab]Return when thou hast regained oneself.
[sync][wait][clear][end]

msg_126:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Let us begin...
[tab]Wang Long, Wang Long, Wang Looong!!
[end]

msg_127:
[tab]Looong, Looooooong!!!
[sync][wait][clear][end]

msg_128:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I sense bright light, the Light Dragon...
[tab]Thou shalt receive much experience, but
[tab]thy luck with money is down.
[sync][wait][clear][end]

msg_129:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I sense dark earth... the Black Dragon...
[tab]Thou shalt have no problem with money,
[tab]but thou shall gain little experience.
[sync][wait][clear][end]

msg_130:
[color(yellow)]Sumaru Genie[color(white)]
[tab]This lively dragon... the Yellow Dragon...
[tab]Thou shalt be engulfed in luck.
[tab]Now is the time to take chances.
[sync][wait][clear][end]

msg_131:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I sense quiet tides... the Blue Dragon...
[tab]Thou shalt see a hidden side of others.
[tab]There shall be a change of personalities.
[sync][wait][clear][end]

msg_132:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Full of passion... the Red Dragon...
[tab]Thou and thy friends shall be excited,
[tab]and shall shout victoriously after battle.
[sync][wait][clear][end]

msg_133:
[color(yellow)]Sumaru Genie[color(white)]
[tab]This light of truth... the Silver Dragon...
[tab]Thou shalt become at a loss for words,
[tab]and shall have no luck with negotiations...
[sync][wait][clear][end]

msg_134:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Now... Is there anything else...?
[tab]Speak as thou wish.
[choice(4)]Hear your fortune
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_135:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_136:
[color(yellow)]Sumaru Genie[color(white)]
[tab]For what have you sought me out today?
[choice(5)]Hear your fortune
Affinity Reading
Talk to the Sumaru Genie
Never mind
Leave
[end_choice][clear][end]

msg_137:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Make small talk
[if_any(MBIT_HI_GYPAISHO2, MBIT_HI_GYPAISHO1, MBIT_HI_GYPSTART)]Ask about fortune telling
Never mind
[end_choice][clear][end]

msg_138:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Very well...
[tab]It shall cost you ¥5000.
[sync][wait][clear][end]

msg_139:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Is that fine?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_140:
[color(yellow)]Sumaru Genie[color(white)]
[tab]It seems thou dost not have enough money.
[tab]Money is the key that opens all doors.
[tab]Come back again.
[sync][wait][clear][end]

msg_141:
Pick
[choice(5)][color(pink)]Wang Long[color(white)]
[color(blue)]Affinity Reading[color(white)]
[color(green)]Power up[color(white)]
[color(orange)]Money[color(white)]
[color(gray)]Done[color(white)]
[end_choice][clear][end]

msg_142:
[color(yellow)]Sumaru Genie[color(white)]
[tab]What do you propose we discuss?
[choice(3)]Ask about fortune telling
[if_all(MBIT_HI_GYPAISHO1)]Ask about affinity reading.
Never mind.
[end_choice][clear][end]

msg_143:
[color(yellow)]Sumaru Genie[color(white)]
[tab]Then I shall explain what I do here.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]Ask to "Hear your fortune" and I will take
[tab]a glimpse into your future.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]The reading may result in good fortune or
[tab]bad fortune for you.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]I cannot peer into your future again until
[tab]the effect of the previous reading wears off.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]The choice is yours. And I am not responsible
[tab]for the visions I see.
[wait][clear][end]

msg_144:
[color(yellow)]Sumaru Genie[color(white)]
[tab]I’ll explain affinity readings to you.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]Ask for an "Affinity reading" and I will
[tab]ask you some questions. Based on your answers
[tab]I will match you with a compatible person.
[wait][clear][color(yellow)]Sumaru Genie[color(white)]
[tab]That person may respond more positively 
[tab]to you when you meet them again.
[wait][clear][end]
