
msg_0:
There are more than 4 in the party.
[tab]It will hang at this rate.
[tab]Please inform Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Being honest with yourself is good...
[tab]Well, being a nuisance isn’t good, though.
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]The TV station and magazines believe the
[tab]New World Order’s stories and then pass it
[tab]to the people, so this makes it credible?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]It makes it seem like those D五j二 Vu Boy
[tab]days were such a long time ago...
[tab]It wasn’t really that long ago.
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]So the d五j二 vu was the memory from another
[tab]world. Then, any misunderstandings could’ve
[tab]been from the other world, too?
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Sumaru Castle has history too! We learned
[tab]local history in elementary school,
[tab]but I don’t remember it at all. AHAHAHA!
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]The receptionist is a contemporary to you
[tab]Ma-ya, right? She’s as carefree as you are.
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]I have been blind to myself...
[tab]I have nothing to say.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]Lately there have been so many cases, 
[tab]the people in the city must be unsure. 
[tab]Thus, a basis of belief in New World Order is done.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]Amano-kun...
[tab]Let’s hurry...
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]I don’t know the exact difference, but the
[tab][tatsuya] there is apparently different
[tab]from the [tatsuya] that I know...
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]...I still can’t believe it.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Sumaru Castle... Has this been here since
[tab]the Sumaru Kiyotada era? ...Is New World
[tab]Order using history?
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]Hah, that is quite a carefree attitude.
[tab]But that can’t be helped. No one really
[tab]knows about Nyarlathotep.
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab](Sigh)...[suou] is so blunt.
[tab]He’s so blunt, it’s embarrassing to watch...
[tab]Well, I guess that’s his good trait.
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]While we’re here just changing items,
[tab]they’re using rumors to turn something big
[tab]into reality... Damn, that pisses me off!
[wait][clear][end]

msg_16:
[color(yellow)]Baofu[color(white)]
[tab]Don’t be so hasty...
[tab]He’s finally ready to explain.
[tab]Let’s listen to the whole story... Alright?
[wait][clear][end]

msg_17:
[color(yellow)]Baofu[color(white)]
[tab]The "Other Side" isn’t so different after all. 
[tab]Well, I’m sure there’s a completely different 
[tab]world out there somewhere too.
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]I understand [suou]’s apprehension...
[tab]But just worrying about it
[tab]doesn’t do us any good.
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]There once was a Sumaru Castle,
[tab]and now there is a Sumaru Castle at the
[tab]same location... That’s all.
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]No one realizes the shadow in their heart...
[tab]Or maybe, they just ignore it.
[tab]Innocent, yet foolish...
[wait][clear][end]

msg_21:
[color(yellow)]Nanjo[color(white)]
[tab]Sergeant [suou]’s actions were expected.
[tab]As long as one is human, being ruled by
[tab]emotions cannot be helped sometimes...
[wait][clear][end]

msg_22:
[color(yellow)]Nanjo[color(white)]
[tab]We may have missed the fact that the world
[tab]is constantly changing. Perpetual change...
[tab]This outcome could have been predicted.
[wait][clear][end]

msg_23:
[color(yellow)]Nanjo[color(white)]
[tab]Relative judgement decides true value...
[tab]Whether [suou]’s secret is important or
[tab]not can’t be decided until we talk to him.
[wait][clear][end]

msg_24:
[color(yellow)]Elly[color(white)]
[tab]Mr. Katsuya’s actions this time had to
[tab]do with his father’s past...
[tab]It could not have been avoided.
[wait][clear][end]

msg_25:
[color(yellow)]Elly[color(white)]
[tab]Wang Long, Feng Shui, Ley Line... Energy flows
[tab]have always been spoken about around
[tab]the world. How could I have forgotten?
[wait][clear][end]

msg_26:
[color(yellow)]Elly[color(white)]
[tab]I see determination in [tatsuya]’s eyes.
[tab]What he is about to tell us must be
[tab]very important to him.
[wait][clear][end]

msg_27:
[color(yellow)][tatsuya][color(white)]
[tab]...Right now... there is nothing to say.
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]This hasn’t changed... There is no
[tab]difference from the "Other Side".
[wait][clear][end]

msg_29:
[color(yellow)][tatsuya][color(white)]
[tab]Just like Baofu-san said... The Sumaru
[tab]Castle wasn’t on the "Other Side"...
[tab]But it is on "This Side"... That’s all.
[wait][clear][end]

msg_30:
[color(yellow)][tatsuya][color(white)]
[tab]...This is my... I mean, "our" battle.
[tab]No one needs to know about it.
[wait][clear][end]

msg_31:
[color(yellow)]Receptionist[color(white)]
[tab]Hey Maya... What is going on lately? You’re
[tab]always covering news and never come into the
[tab]office. They don’t let you write anymore?
[wait][clear][end]

msg_32:
[color(yellow)]Receptionist[color(white)]
[tab]...Eh, am I thinking too much? ...I hope so.
[tab]But isn’t that... harassment from upstairs?
[wait][clear][end]

msg_33:
[color(yellow)]Receptionist[color(white)]
[tab]Ah, Maya! You would know this... Is Wang
[tab]Long really capable of world destruction?
[tab]You know, don’t you? Didn’t you cover it?
[wait][clear][end]

msg_34:
[color(yellow)]Receptionist[color(white)]
[tab]Hey!
[wait][clear][end]

msg_35:
[color(yellow)]Receptionist[color(white)]
[tab]Ah, Maya! You’re alright...!?
[tab]I was worried you’d be left on the ground.
[tab]But, you haven’t been purified yet, right?
[wait][clear][end]

msg_36:
[color(yellow)]Receptionist[color(white)]
[tab]That’s risky! They say you’ll be killed...!
[tab]I haven’t been either, though.
[wait][clear][end]

msg_37:
[color(yellow)]Receptionist[color(white)]
[tab]Oh, Maya, I’m so glad we’re safe... 
[tab]But, was all this caused by New World Order...?
[tab]This will be in the history books.
[wait][clear][end]

msg_38:
[color(yellow)]Receptionist[color(white)]
[tab]In that case, we are "living history"!
[tab]I’ll never forget about this incident... 
[tab]By the way, why is the sky colored like that?
[wait][clear][end]

msg_39:
[color(yellow)]Emergency Stairs[color(white)]
[tab][color(green)]You cannot enter here.[color(white)]
[sync][wait][clear][end]

msg_40:
MBIT HI NANJOTOUJO
Spread Nanjo rumor
Bit on
[wait][clear][end]

msg_41:
MBIT AIS 32
Affinity reading
Bit on
[wait][clear][end]

msg_42:
EBIT E006F
Cleared Lab
Bit on
[wait][clear][end]

msg_43:
EBIT E0077
Cleared Smile Hirasaka
Bit on
[wait][clear][end]

msg_44:
EBIT E007A
Cleared Concert Hall
Bit on
[wait][clear][end]

msg_45:
EBIT E007B
Tapped Tatsuzou
Bit on
[wait][clear][end]

msg_46:
EBIT E007F
Cleared Factory
Bit on
[wait][clear][end]

msg_47:
EBIT E008C
Cleared Ruins
Bit on
[wait][clear][end]

msg_48:
EBIT E009F
Cleared Mt. Iwato
Bit on
[wait][clear][end]

msg_49:
EBIT E00AF
Cleared Torifune
Bit on
[wait][clear][end]

msg_50:
Cleared Sumaru Castle
Bit on
[wait][clear][end]

msg_51:
[color(yellow)]Emergency Exit[color(green)]
[tab]You cannot enter here.[color(white)]
[sync][wait][clear][end]
