
msg_0:
[color(yellow)]Ulala[color(white)]
[tab](giggle)...
[tab]Matchmaker party, Matchmaker party♥
[tab]I can’t wait.
[wait][clear][end]

msg_1:
[color(yellow)]Disappointed Girl[color(white)]
[tab]I told you my birthday before, you forgot?
[tab]It’s in January...
[end]

msg_2:
[tab]That makes me sad.
[wait][clear][end]

msg_3:
[color(yellow)]Fortune Telling Girl[color(white)]
[tab]So you’re a Yellow Dragon, huh... 
[tab]Steady and conservative. I’m a Blue Dragon, so...
[end]

msg_4:
[tab]Ugh... It seems we aren’t very compatible.
[wait][clear][end]

msg_5:
[color(yellow)]Happy Guy[color(white)]
[tab]Wang Long fortune telling really works...
[tab]I got myself a wonderful girlfriend
[tab]just from doing as Wang Long said.
[wait][clear][end]

msg_6:
[color(yellow)]Happy Guy[color(white)]
[tab]I can’t live without Wang Long...
[tab]No, really.
[wait][clear][end]

msg_7:
[color(yellow)]Frightened Guy[color(white)]
[tab]Umm... The police are here, but...
[tab]Did something happen...?
[tab]It’s not a Joker case, is it!?
[wait][clear][end]

msg_8:
[color(yellow)]Frightened Guy[color(white)]
[tab]It is... It has to be!!
[end]

msg_9:
[tab]That man I saw at 3-B must be a cop!
[tab]Crap, what’s up with this school!?
[wait][clear][end]
