
msg_0:
More than four.
Hang time!
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]That strange man by the window,
[tab]he looks suspicious...
[tab]Should we report him to Detective [suou]?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]...He’s not here right now, though.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]What went down with Bao and that assassin?
[tab]He doesn’t bother to tell us, so I don’t
[tab]have a clue.
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]Bao dashed at full speed for his partner.
[tab]And it was a girl! ...For a GIRL, ya hear!?
[tab]Oh, geez...
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]I didn’t know that there was such a place
[tab]underwater. Maybe Atlantis does exist!
[tab][delay(15)]...!! [delay(30)]Did you find any treasure!?
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab][tatsuya]-kun’s so reserved...
[tab]If it’s only that much, he should’ve just
[tab]told us in the first place.
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]It’s not like "suspicious" means criminal
[tab]in every case. Suspicious people always
[tab]end up becoming the topics of rumors.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]A chance to capture Tatsuzou Sudou...
[tab]Is that what Baofu really thinks?
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]A Civil Defense Force with that weaponry...
[tab]Why would those weapons be needed
[tab]in the first place?
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]Amano-kun, let’s hurry...
[tab]I want to hear what [tatsuya] has to say!
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]Hahaha, [tatsuya]’s worries are
[tab]"only that much" to Serizawa-kun.
[wait][clear][end]

msg_12:
[color(yellow)]Baofu[color(white)]
[tab]Changing people by rumors...?
[tab]Conjuring people by rumors...?
[tab]That strange man is the latter.
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]What the hell is Serizawa talking about?
[tab]A partner is a partner, right?
[tab]Nothing more...[delay(30)]Nothing less.
[wait][clear][end]

msg_14:
[color(yellow)]Baofu[color(white)]
[tab]Heh heh heh, that’s Serizawa for ya...
[tab]But that kid seems to be looking beyond...
[tab]I bet he’d know what happened to Atlantis.
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab][tatsuya] has pride too, right...?
[tab]It’s easy to tell a secret, but maybe he
[tab]didn’t want to feel relieved by doing so?
[wait][clear][end]

msg_16:
[color(yellow)]Nanjo[color(white)]
[tab]One who holds many fortunes
[tab]will be doubted by many...
[tab]It cannot be helped.
[wait][clear][end]

msg_17:
[color(yellow)]Nanjo[color(white)]
[tab]Mr. Baofu and Tatsuzou Sudou...
[tab]I do not know what went on between them,
[tab]but that call was most likely...
[wait][clear][end]

msg_18:
[color(yellow)]Nanjo[color(white)]
[tab]That human-model tank was already finished.
[tab]Assuming that Matsuoka did not report it,
[tab]it must have been developed overseas...
[wait][clear][end]

msg_19:
[color(yellow)]Nanjo[color(white)]
[tab]He certainly is looking beyond...
[tab]What is he seeing that we cannot?
[wait][clear][end]

msg_20:
[color(yellow)]Elly[color(white)]
[tab]Individuality is looked upon with
[tab]reverence as well as with suspicion.
[tab]That is where rumors are born.
[wait][clear][end]

msg_21:
[color(yellow)]Elly[color(white)]
[tab]They say that everyone has two faces,
[tab]but Baofu’s are vastly different... 
[tab]Is he hiding sadness deep within his heart?
[wait][clear][end]

msg_22:
[color(yellow)]Elly[color(white)]
[tab]Defense units, Taiwanese Mafia, stars...
[tab]I’m surprised at the New World Order’s array
[tab]of minions. What is their true purpose...?
[wait][clear][end]

msg_23:
[color(yellow)]Elly[color(white)]
[tab]He definitely is looking beyond...
[tab]Is he seeing...
[tab]something we cannot?
[wait][clear][end]

msg_24:
[color(yellow)][tatsuya][color(white)]
[tab]It’s dangerous here...
[tab]We have no time for side trips.
[wait][clear][end]

msg_25:
[color(yellow)][tatsuya][color(white)]
[tab]I came to change destiny...
[tab]I’m only fighting for that.
[wait][clear][end]

msg_26:
[color(yellow)]Rumor Lover[color(white)]
[tab]It might be unrelated, but lately there’ve
[tab]been many cases of d五j二 vu. In fact, 
[tab]I’m one of them... What’s the Masked Circle?
[wait][clear][end]

msg_27:
[color(yellow)]Rumor Lover[color(white)]
[tab]You think that an oceanic ruin site really exists? 
[tab]Everyone’s debating this because of
[tab]the history boom... Pole shift? Who cares?
[wait][clear][end]

msg_28:
[color(yellow)]Rumor Lover[color(white)]
[tab]Hey you... It seems Narumi is dangerous...
[tab]The Ameno Torifune was found at the
[tab]subway construction site.
[wait][clear][end]

msg_29:
[color(yellow)]Rumor Lover[color(white)]
[tab]Earthquakes have been plaguing Narumi, 
[tab]and they say there’s a train passing right
[tab]through the ruins. You better be careful.
[wait][clear][end]

msg_30:
[color(yellow)]Rumor Lover[color(white)]
[tab]Word on the streets says that foreigner
[tab]is a millionaire map collector.
[wait][clear][end]

msg_31:
[color(yellow)]Rumor Lover[color(white)]
[tab]And he’s a powerful figure at a mysterious
[tab]company called "Demon"...
[tab]No, it’s not a rumor. It’s true!
[wait][clear][end]

msg_32:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Oh, such a pretty miss!
[tab]...What? Map collecting?
[tab]How do you know my hobby?
[wait][clear][end]

msg_33:
[color(yellow)]Salam Ladeen[color(white)]
[tab]I have no more interest in money.
[tab]I now live to collect maps...
[tab]So, what would you like?
[wait][clear][end]

msg_34:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Oh, such a pretty miss!
[tab]I’m so happy you came to see me.
[tab]So what do you want?
[wait][clear][end]

msg_35:
[color(yellow)]Salam Ladeen[color(white)]
[tab]So what do you want?
[choice(4)][if_all(!LBIT_0000)]Take a request
Talk
[if_all(!LBIT_0000)]Explanation
Nothing
[end_choice][clear][end]

msg_36:
[color(yellow)]Salam Ladeen[color(white)]
[tab]So what do you want?
[choice(4)][if_all(!LBIT_0000)]Give map
Talk
[if_all(!LBIT_0000)]Explanation
Nothing
[end_choice][clear][end]

msg_37:
[color(yellow)]Salam Ladeen[color(white)]
[tab]You want to hear about maps?
[tab]When you accept my request, I will
[tab]give you a blank map.
[wait][clear][color(yellow)]Salam Ladeen[color(white)]
[tab]When you visit the location you
[tab]should open your map to see your
[tab]progress.
[wait][clear][color(yellow)]Salam Ladeen[color(white)]
[tab]You can see the blocks you have yet to visit,
[tab]and areas you’ve already visited will be 
[tab]blacked out.
[wait][clear][color(yellow)]Salam Ladeen[color(white)]
[tab]Once you clear the dungeon you cannot
[tab]return to finish the map so be careful...
[wait][clear][color(yellow)]Salam Ladeen[color(white)]
[tab]I will trade a completed map for 
[tab]special cards.
[wait][clear][end]

msg_38:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Miss, where are you going now?
[tab]...[delay(10)]...[delay(10)]But I already have that map?
[tab]Tell me when you go to a new place.
[wait][clear][end]

msg_39:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Miss, where are you going now?
[tab]...[delay(10)]...[delay(10)]Eh? Aoba Park? I’ll pass.
[tab]There’s nothing special about a park, right?
[wait][clear][end]

msg_40:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Miss, where are you going now?
[tab]...[delay(10)]...[delay(10)]Oh, just there.
[tab]I don’t need a map of there.
[wait][clear][end]

msg_41:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Miss, where are you going now?
[tab]...[delay(10)]...[delay(10)]Eh, a shrine? I’m not interested.
[tab]I don’t need a map of there.
[wait][clear][end]

msg_42:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Miss, where are you going now?
[tab]...[delay(10)]...[delay(10)]Sumaru Castle? I’ll pass.
[tab]Anger the Lord, and it’s Hara-kiri, right?
[wait][clear][end]

msg_43:
[color(yellow)]Salam Ladeen[color(white)]
[tab]I have no more interest in money.
[tab]I now live to collect maps.
[tab]Miss, where are you going now?
[wait][clear][end]

msg_44:
[color(yellow)]Salam Ladeen[color(white)]
[tab]...[delay(10)]...[delay(10)]...[delay(1)]Hmm, I don’t know that place.
[tab]It’s a new place! Can you check it out?
[tab]Miss, please make a map of there!
[wait][clear][end]

msg_45:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Miss, where are you going now?
[tab]...[delay(10)]...[delay(10)]...[delay(1)]I don’t know that place either.
[tab]Miss, please make a map of there!
[wait][clear][end]

msg_46:
[tab]Will you make a map?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_47:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Ah! So you’ll make a map for me!?
[tab]Thank you.
[tab]Here’s a blank map.
[wait][clear][end]

msg_48:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Just keep walking, and complete the map.
[tab]If it is good, I’ll trade it for my
[tab]important card.
[wait][clear][end]

msg_49:
[color(green)]Maya got [item_with_type(item_fffe)].[color(white)]
[wait][clear][end]

msg_50:
[color(green)]Maya got [item_with_type(item_fffe)] and
[item_with_type(item_fffd)].[color(white)]
[wait][clear][end]

msg_51:
[color(yellow)]Salam Ladeen[color(white)]
[tab]...I see... You won’t make a map for me.
[tab]I would’ve traded it for a rare card.
[tab]That’s too bad.
[wait][clear][end]

msg_52:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Oh, you brought me a map of a new place!
[tab]I live to collect maps.
[tab]Let me see...
[wait][clear][end]

msg_53:
[color(yellow)]Salam Ladeen[color(white)]
[tab]This IS very unique... but... it’s incomplete!
[tab]I can’t trade it for my card.
[tab]...Please, complete this map!
[wait][clear][end]

msg_54:
[color(yellow)]Salam Ladeen[color(white)]
[tab]This IS very unique... but... it’s incomplete.
[tab]I can’t trade it for my card.
[tab]...But I’ll keep the map!
[wait][clear][end]

msg_55:
[color(yellow)]Salam Ladeen[color(white)]
[tab]This IS a very unique map!
[tab]Please, trade it for my card!!
[wait][clear][end]

msg_56:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Ah! So you’ll make a map for me!?
[tab]Here’s a blank...
[tab]What!? You already went?
[wait][clear][end]

msg_57:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Let me see...
[tab]This IS a very unique map!
[tab]Please, trade it for my card!!
[wait][clear][end]

msg_58:
[color(green)]As a reward for Map Making, Maya got
Salam Select Card Set FINAL.[color(white)]
[sync][wait][clear][end]

msg_59:
[color(green)]As a reward for Map Making, Maya got
Salam Select Card Set TAROT SPECIAL.[color(white)]
[sync][wait][clear][end]

msg_60:
[color(green)]As a reward for Map Making, Maya got
Salam Select Skill Card Set Part 2.[color(white)]
[sync][wait][clear][end]

msg_61:
[color(green)]As a reward for Map Making, Maya got
Salam Select Skill Card Set.[color(white)]
[sync][wait][clear][end]

msg_62:
[color(green)]As a reward for Map Making, Maya got
Salam Select Card Set Booster Pack.[color(white)]
[sync][wait][clear][end]

msg_63:
[color(green)]As a reward for Map Making, Maya got
Salam Select Card Set Part 2.[color(white)]
[sync][wait][clear][end]

msg_64:
[color(green)]As a reward for Map Making, Maya got
Salam Select Card Set.[color(white)]
[sync][wait][clear][end]

msg_65:
[color(green)]As a reward for Map Making, Maya got
Salam Select Card Set.[color(white)]
[sync][wait][clear][end]

msg_66:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Is there anything else?
[tab]Please ask me anything.
[wait][clear][end]

msg_67:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Please come again.
[tab]But please keep this a secret.
[tab]I have many enemies... Ahaha.
[wait][clear][end]

msg_68:
[color(yellow)]Salam Ladeen[color(white)]
[tab]Who was behind the TV station and Lab incidents? 
[tab]What was their objective? 
[tab]...I thought I could rest easy in this country.
[wait][clear][end]

msg_69:
[color(yellow)]Salam Ladeen[color(white)]
[tab]New World Order? I never heard of them.
[tab]N-E-W W-O-R-L... Nope, it’s not on my list.
[tab]They are nothing. They can’t do anything.
[wait][clear][end]

msg_70:
[color(yellow)]Salam Ladeen[color(white)]
[tab]What was that earthquake...!?
[tab]If it shakes violently, everyone will die.
[tab]Could that be that Wang Long? ...I’m scared.
[wait][clear][end]

msg_71:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Welcome.
[tab]Would you like to tell me your mood?
[tab]I will make something to match your heart.
[wait][clear][end]

msg_72:
[color(yellow)]Rumor-Lovin’ Bartender[color(green)]
[tab]The lady bartender at Ebony, the sky lounge
[tab]in Pleiades... Her job requires her to be
[tab]familiar with rumors.[color(white)]
[wait][clear][end]

msg_73:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]You are compatible with me?
[tab](giggle)... I am honored.
[tab]I will give you special service today.
[wait][clear][end]

msg_74:
[color(yellow)]Rumor-Lovin’ Bartender[color(green)]
[tab]The lady bartender at Ebony, the sky lounge
[tab]in Hotel Pleades... Her job requires her to be
[tab]familiar with rumors.[color(white)]
[wait][clear][end]

msg_75:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]What will you have today?
[wait][clear][end]

msg_76:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]What will you have today?
[choice(4)]Dine in
Talk
Never mind
Leave the store
[end_choice][clear][end]

msg_77:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]What do you want to talk about?
[choice(3)]Talk to bartender
Ask about bar
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_78:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Is there anything else I can get you?
[tab]Ah, you don’t have to force yourself.
[tab]I don’t mind if you’re just here to talk...
[choice(4)]Dine in
Talk
Never mind
Leave the store
[end_choice][clear][end]

msg_79:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]What do you want to talk about?
[choice(3)]Talk to bartender
Ask about bar
[if_all(EBIT_SINARIOFF)]Hidden items
[end_choice][clear][end]

msg_80:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]What would you like to hear?
[choice(3)]A rumor
A story
Never mind
[end_choice][clear][end]

msg_81:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Rumors? Hmmmmm... I’m sorry!
[tab]I’m out of them right now.
[tab]I’ll collect more interesting rumors.
[wait][clear][end]

msg_82:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Rumors? Alright...
[tab]Can you tell me one of yours, first?
[wait][clear][end]

msg_83:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab](giggle)...
[tab]I kept a good one just for today.
[tab]But let me hear yours first.
[wait][clear][end]

msg_84:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]The gossip on TV and in magazines is old.
[tab]I want to know fresh rumors...
[tab]Do you have any juicy news?
[wait][clear][end]

msg_85:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Hmmmm, is that so...?
[tab]Thank you for that interesting rumor.
[tab]Now I’ll tell you the rumor I have.
[wait][clear][end]

msg_86:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Oh, is that so...!?
[tab]I had no idea.
[tab]Hmmm, my rumor is...
[wait][clear][end]

msg_87:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Hmm...?
[tab]I’ve heard a similar rumor.
[tab]That’s too bad. Well, then...
[wait][clear][end]

msg_88:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Do you know the restaurant [color(orange)]Clair De Lune[color(white)]?
[tab]It seems they started [color(orange)]selling weapons[color(white)].
[tab]Seems they’re selling [color(orange)]mysterious weapons[color(white)].
[wait][clear][end]

msg_89:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]You know that jewelry shop, [color(orange)]Padparacha[color(white)]?
[tab]The designer there is rumored to
[tab][color(orange)]custom make weapons and armor[color(white)].
[wait][clear][end]

msg_90:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]About the man who lives in this hotel
[tab]suite... Ah, that guy over there!
[tab]Do you know the rumor about him?
[wait][clear][end]

msg_91:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]That man, [color(orange)]Salam[color(white)] is his name, is a
[tab]millionaire who [color(orange)]collects maps[color(white)].
[tab]He’d do business with demons for maps.
[wait][clear][end]

msg_92:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Kegare-purification is popular now...
[tab]I think it’s natural to have this "sin".
[tab]You can’t live life totally clean.
[wait][clear][end]

msg_93:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]It would be nice to be able to live clean,
[tab]but mixing things up a little brings out
[tab]the flavor... Like in a cocktail.
[wait][clear][end]

msg_94:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]I never thought the world would end at the
[tab]hands of Wang Long. I didn’t believe it at
[tab]first, but with the fortune popularity...
[wait][clear][end]

msg_95:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Where were you at the time of the quake?
[tab]It was frightening on the top floor, 
[tab]and I got worried about a possible tsunami!
[wait][clear][end]

msg_96:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Please come again...
[tab]It doesn’t matter if it is on a bad day.
[tab]I will brighten up dark feelings.
[wait][clear][end]

msg_97:
MBIT HI NANJOTOUJO
Spread Nanjo rumor
Bit on
[wait][clear][end]

msg_98:
Spread map dude rumor
Bit on
[wait][clear][end]

msg_99:
Accepted request of map dude
Bit on
[wait][clear][end]

msg_100:
Accepted request of map dude
Bit off
[wait][clear][end]

msg_101:
Map completed
Bit on
[wait][clear][end]

msg_102:
Map completed
Bit off
[wait][clear][end]

msg_103:
MBIT AIS 50
Affinity reading
Bit on
[wait][clear][end]

msg_104:
EBIT E006F
Cleared Lab / TV station
Bit on
[wait][clear][end]

msg_105:
EBIT E0077
Cleared Smile Hirasaka
Bit on
[wait][clear][end]

msg_106:
EBIT E007A
Cleared Concert Hall
Bit on
[wait][clear][end]

msg_107:
EBIT E007B
Tapped Tatsuzou
Bit on
[wait][clear][end]

msg_108:
EBIT E007F
Cleared Factory
Bit on
[wait][clear][end]

msg_109:
EBIT E008C
Cleared Ruins
Bit on
[wait][clear][end]

msg_110:
EBIT E009F
Cleared Mt. Iwato
Bit on
[wait][clear][end]

msg_111:
EBIT E00AF
Cleared Torifune
Bit on
[wait][clear][end]

msg_112:
EBIT[tab]E00B8
Cleared Sumaru Castle
Bit on
[wait][clear][end]

msg_113:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]What do you want to talk about?
[choice(2)]Ask about dining in
Never mind
[end_choice][clear][end]

msg_114:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Dining in?
[tab]You can select "Dine in" here,
[tab]and I will make you a cocktail!
[wait][clear][color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]Meals have the effect of increasing
[tab]a character’s ability temporarily.
[wait][clear][color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]The effect depends on the meal, and
[tab]once you eat, you cannot have another
[tab]meal until the effect has expired.
[wait][clear][end]

msg_115:
[color(yellow)]Rumor-Lovin’ Bartender[color(white)]
[tab]That will cost ¥[var(msg_var_0)]
[tab]Would you like to dine in?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_116:
[color(green)]Minors may not drink!
[wait][clear][end]
