
msg_0:
There are more than 4 in the party.
[tab]It will hang at this rate.
[tab]Please inform Kaneda and Kataoka.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab](giggle) That officer said "shady"!
[tab]Was that a joke, or was he serious?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]Sure, people in the industry are a little
[tab]"different" from the general public, but...
[tab]Baofu’s really "different", isn’t he?
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Are there going to be any prizes from Kismet? 
[tab]Lately, magazines give out a lot of prizes...
[tab]Why don’t you try something?
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]I see, the magazine printers are from
[tab]another company. Your old partner wasn’t
[tab]with the company. Layout is a design job.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]...Hmm?
[tab]Then, what is Ma-ya’s job?
[wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]I know I’ve seen this person somewhere.
[tab]Ma-ya, was it at your magazine?
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]Elly-chan’s pictures are in fashion magazines 
[tab]and stuff, huh? I never thought I’d be friends
[tab]with a real model.
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]Police work is an occupation where you
[tab]come across a lot of "shady" characters...
[tab]I’ve actually gotten used to it.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]...Baofu’s sense of fashion?
[tab]I don’t know about "cool", 
[tab]but it sure isn’t traditional...
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]...Wang Long Chizuru?
[tab]I do know about that famous fortune teller.
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]...What? You got your fortune told by her?
[tab]That’s pretty impressive.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Baofu’s idea isn’t bad. There are sins that
[tab]can’t be judged by the law. Then they must
[tab]be judged by the people, right?
[wait][clear][end]

msg_13:
[color(yellow)]Katsuya[color(white)]
[tab]The only prize I ever sent in for was in
[tab]a coffee sweepstakes...
[tab]I used to drink a lot of coffee.
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]It seems like publishing companies have
[tab]many unknown people coming and going...
[tab]Do they even notice an outsider?
[wait][clear][end]

msg_15:
[color(yellow)]Katsuya[color(white)]
[tab]Baofu, "aimed for brats" is too much...
[tab]Amano-kun, the one involved in it, is right here... 
[tab]Don’t worry about it, Amano-kun.
[wait][clear][end]

msg_16:
[color(yellow)]Katsuya[color(white)]
[tab]I never expected to become acquainted with
[tab]someone in the industry.
[wait][clear][end]

msg_17:
[color(yellow)]Katsuya[color(white)]
[tab]...What do you mean, "Who"...?
[tab]You’re basically a celebrity, right?
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]Hey, why is that receptionist
[tab]looking over here...?
[tab]What kind of face is that anyway?
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]Anybody walking into a publishing company
[tab]wears something like this, don’t they?
[tab]It shouldn’t be a big deal...
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]Don’t you see how "cool" this is...?
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]From those TV reports, the publisher can’t
[tab]be trusted either. Besides, do people
[tab]here have a sense of journalism anyway?
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]Good timing... Why don’t you put this guy’s
[tab]picture up as "Women’s Public Enemy #1: 
[tab]The true face of Makimura!!" or something...?
[wait][clear][end]

msg_23:
[color(yellow)]Baofu[color(white)]
[tab]Now they have pop-top openers on cans,
[tab]but back in my day, we collected pull-tops
[tab]and stuck them onto postcards...
[wait][clear][end]

msg_24:
[color(yellow)]Baofu[color(white)]
[tab]The reason for outsiders coming in and out
[tab]often is because the magazine printers are
[tab]outsiders. The publishers are "Editors".
[wait][clear][end]

msg_25:
[color(yellow)]Baofu[color(white)]
[tab]Isn’t Coolest a magazine geared at high
[tab]school kids? ...That means Serizawa is
[tab]reading a book aimed for brats...!?
[wait][clear][end]

msg_26:
[color(yellow)]Baofu[color(white)]
[tab]Serizawa seems to think of Kirishima as a friend, 
[tab]but what does she think...? 
[tab]There are people who quickly call others "friends".
[wait][clear][end]

msg_27:
[color(yellow)]Nanjo[color(white)]
[tab]This is Kismet Publishing... So what kind
[tab]of publication is Amano-san involved with?
[wait][clear][end]

msg_28:
[color(yellow)]Nanjo[color(white)]
[tab]Coolest...?
[tab]My apologies, I’ve never heard of it.
[wait][clear][end]

msg_29:
[color(yellow)]Elly[color(white)]
[tab]...Eh, Ms. Ulala, a friend of mine?
[wait][clear][end]

msg_30:
[color(yellow)]Elly[color(white)]
[tab]I am so honored to be able to be
[tab]acquainted with such a
[tab]wonderful career woman.
[wait][clear][end]

msg_31:
[color(yellow)]Makimura[color(white)]
[tab]My face on a magazine...!?
[tab]Give me a break.
[wait][clear][end]

msg_32:
[color(yellow)]Receptionist[color(white)]
[tab]Hey Maya...!
[tab]Didn’t you go to cover Seven Sisters High?
[tab]There was a murder there, wasn’t there?
[wait][clear][end]

msg_33:
[color(yellow)]Receptionist[color(white)]
[tab]...No way! You saw a dead body!?
[tab]Then you were questioned by the police and stuff? 
[tab]...Eh, that’s an officer right there?
[wait][clear][end]

msg_34:
[color(yellow)]Receptionist[color(white)]
[tab]...This has gotten pretty big, hasn’t it?
[wait][clear][end]

msg_35:
[color(yellow)]Receptionist[color(white)]
[tab]AH, YES! ...Oh, it’s just you, Maya...
[tab]Don’t scare me like that...!
[tab]No, I wasn’t sleeping!
[wait][clear][end]

msg_36:
[color(yellow)]Receptionist[color(white)]
[tab]Hey, Maya...
[tab]The guy with the long hair and glasses,
[tab]do you know him? ...What does he do...?
[wait][clear][end]

msg_37:
[color(yellow)]Receptionist[color(white)]
[tab]AH, YES! ...Oh, it’s just you, Maya...
[tab]Don’t scare me like that...!
[tab]No, I wasn’t sleeping!
[wait][clear][end]

msg_38:
[color(yellow)]Receptionist[color(white)]
[tab]Hey Maya... What is going on lately? You’re
[tab]always covering news and never come into the
[tab]office. They don’t let you write anymore?
[wait][clear][end]

msg_39:
[color(yellow)]Receptionist[color(white)]
[tab]...Eh, am I thinking too much? ...I hope so.
[tab]But isn’t that... harassment from upstairs?
[wait][clear][end]

msg_40:
[color(yellow)]Emergency Stairs[color(white)]
[tab][color(green)]You cannot enter here.[color(white)]
[sync][wait][clear][end]

msg_41:
MBIT AIS 32
Affinity reading
Bit on
[wait][clear][end]

msg_42:
EBIT E0015
Cleared Sevens
Bit on
[wait][clear][end]

msg_43:
EBIT E0018
Finished bar
Bit on
[wait][clear][end]

msg_44:
EBIT E0033
Baofu joined
Bit on
[wait][clear][end]

msg_45:
EBIT E0037
Police
Bit on
[wait][clear][end]

msg_46:
EBIT E0038
Con artist
Bit on
[wait][clear][end]

msg_47:
EBIT E003E
Cleared GOLD
Bit on
[wait][clear][end]

msg_48:
EBIT E0043
Cleared Zodiac
Bit on
[wait][clear][end]

msg_49:
EBIT E0044
Cleared Aoba Park
Bit on
[wait][clear][end]

msg_50:
EBIT E0046
Nanjo or Elly joined
Bit on
[wait][clear][end]

msg_51:
EBIT E006F
Cleared Lab
Bit on
[wait][clear][end]

msg_52:
[color(yellow)]Emergency Exit[color(green)]
[tab]You cannot enter here.[color(white)]
[sync][wait][clear][end]
