function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3043, 127);
    op_118();
    levelFootstepSet(sfx_15);
    envTriggerSet(EXIT, 131, 1, line, coll_23);
    envTriggerSet(ELE, 224, 1, line, coll_24);
    envTriggerSet(ELE, 224, 1, line, coll_25);
    cameraSet(southeast, 1200, 0, -1230);
    li(var_0, 0);
    li(var_1, 0);
    partyMemberCheck(var_0, ulala);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, katsuya);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, baofu);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, nanjo);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, elly);
    add(var_1, var_1, var_0);
    partyMemberCheck(var_0, tatsuya);
    add(var_1, var_1, var_0);
    boutrange(var_1, 0, 4, label_1a);
    li(var_0, 0);
    b(label_1f);
  label_1a:
    ref_1a = dialogAlloc();
    ref_1b = msgShow(msg_0);
/***************************************
There are more than 4 in the party.
[tab]It will hang at this rate.
[tab]Please inform Kaneda and Kataoka.
[wait][clear]
***************************************/
    wait(ref_1b);
    dialogFree(ref_1a);
    b(label_1f);
  label_1f:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_24);
    bitGet(var_0, EBIT_E008C);
    bez(var_0, label_2a);
    bnz(var_0, label_26);
  label_24:
    partyMemberCheck(var_0, tatsuya);
    bez(var_0, label_2a);
  label_26:
    ref_26 = spriteLoad(sprite_18);
    wait(ref_26);
    unitSpawn(tatsuya, sprite_18, 1050, 0, -800, west, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
  label_2a:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_3d);
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_35);
    partyMemberCheck(var_0, elly);
    bez(var_0, label_3d);
    ref_30 = spriteLoad(sprite_23);
    wait(ref_30);
    unitSpawn(elly, sprite_23, 1570, 0, -1170, north, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
    b(label_3d);
  label_35:
    bne(var_0, 1, label_3d);
    partyMemberCheck(var_0, nanjo);
    bez(var_0, label_3d);
    ref_38 = spriteLoad(sprite_1f);
    wait(ref_38);
    unitSpawn(nanjo, sprite_1f, 320, 0, -1070, east, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
    b(label_3d);
  label_3d:
    partyMemberCheck(var_0, ulala);
    bez(var_0, label_43);
    ref_3f = spriteLoad(sprite_6);
    wait(ref_3f);
    unitSpawn(ulala, sprite_6, 700, 0, -880, east, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
  label_43:
    partyMemberCheck(var_0, katsuya);
    bez(var_0, label_49);
    ref_45 = spriteLoad(sprite_d);
    wait(ref_45);
    unitSpawn(katsuya, sprite_d, 1700, 0, -990, east, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
  label_49:
    partyMemberCheck(var_0, baofu);
    bez(var_0, label_4f);
    ref_4b = spriteLoad(sprite_13);
    wait(ref_4b);
    unitSpawn(baofu, sprite_13, 1880, 0, -200, north, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
  label_4f:
    ref_4f = spriteLoad(sprite_d4);
    wait(ref_4f);
    unitSpawn(unit_58, sprite_d4, 1350, 0, -80, north, none);
    unitPalette(unit_58, 2);
    unitTriggerSet(unit_58, BLOCK_UKETUKE, 255, 1);
    envTriggerSet(BLOCK_UKETUKE, 255, 1, collision_2, coll_0);
    envTriggerSet(BLOCK_UKETUKE, 28, 1, line, coll_11);
    ref_56 = spriteLoad(sprite_61);
    wait(ref_56);
    unitSpawn(npc1, sprite_61, 520, 0, -360, west, none);
    unitTriggerSet(npc1, ASA, 255, 1);
    ref_5a = spriteLoad(sprite_63);
    wait(ref_5a);
    unitSpawn(npc2, sprite_63, 590, 0, -330, west, none);
    unitTriggerSet(npc2, MIE, 255, 1);
    ref_5e = spriteLoad(sprite_34);
    wait(ref_5e);
    unitSpawn(npc3, sprite_34, 640, 0, -610, south, none);
    unitTriggerSet(npc3, BRO, 255, 1);
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_6e);
    bitGet(var_0, MBIT_KASIMA_OUTTALK);
    bne(var_0, 0, label_6b);
    ref_66 = spriteLoad(sprite_cf);
    wait(ref_66);
    unitSpawn(npc4, sprite_cf, 148, 0, -300, west, none);
    unitTriggerSet(npc4, KEIBIIN, 255, 1);
    b(label_6d);
  label_6b:
    bne(var_0, 1, label_6d);
    b(label_6d);
  label_6d:
    b(label_83);
  label_6e:
    bne(var_0, 1, label_83);
    bitGet(var_0, EBIT_E00B8);
    bne(var_0, 0, label_77);
    ref_71 = spriteLoad(sprite_e0);
    wait(ref_71);
    unitSpawn(npc3, sprite_34, 1405, 0, -560, north, none);
    unitSpawn(npc5, sprite_e0, 1345, 0, -690, west, none);
    unitTriggerSet(npc5, SITAI, 255, 1);
    b(label_82);
  label_77:
    bne(var_0, 1, label_82);
    bitGet(var_0, MBIT_KASIMA_OUTTALK);
    bne(var_0, 0, label_7f);
    ref_7a = spriteLoad(sprite_cf);
    wait(ref_7a);
    unitSpawn(npc4, sprite_cf, 148, 0, -300, west, none);
    unitTriggerSet(npc4, KEIBIIN, 255, 1);
    b(label_81);
  label_7f:
    bne(var_0, 1, label_81);
    b(label_81);
  label_81:
    b(label_82);
  label_82:
    b(label_83);
  label_83:
    ref_83 = spriteLoad(sprite_0);
    wait(ref_83);
    ref_85 = spriteLoad(sprite_2);
    wait(ref_85);
    playerInit(south);
    controlDisable();
    unitIdleOnAll();
    bitGet(var_0, EBIT_E00AF);
    bne(var_0, 0, label_8d);
    b(label_96);
  label_8d:
    bne(var_0, 1, label_96);
    bitGet(var_0, EBIT_E00B8);
    bne(var_0, 0, label_93);
    unitFace(npc5, east);
    unitAnimationPlay(npc5, animation_16, 1);
    b(label_95);
  label_93:
    bne(var_0, 1, label_95);
    b(label_95);
  label_95:
    b(label_96);
  label_96:
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_103);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_f3);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_e3);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_d3);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_c3);
    unitFacePlayer(ulala);
    ref_a9 = bustupLoad(bustup_17);
    bustupWait(ref_a9);
    ref_ab = bustupAlloc(ref_a9, left, rgb(0,0,0));
    bustupFade(ref_ab, rgb(128,0,0), 30);
    ref_ad = dialogAlloc();
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_b4);
    ref_b0 = msgShow(msg_1);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Brown really is a funky guy. I thought
[tab]he just acted that way in TV shows.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_b0);
    b(label_bc);
  label_b4:
    bne(var_0, 1, label_bc);
    ref_b5 = msgShow(msg_2);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Is that Brown...!?
[tab]So, the Uesugi-kun who helped Elly-chan 
[tab]was the celebrity, Brown.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_b5);
    ref_b8 = msgShow(msg_3);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Hmmmm...
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_b8);
    b(label_bc);
  label_bc:
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_ad);
    ref_be = bustupFade(ref_ab, rgb(0,0,0), 10);
    bustupWait(ref_be);
    bustupFree(ref_ab);
    unitRestoreFacing(ulala);
    b(label_113);
  label_c3:
    unitFacePlayer(ulala);
    ref_c4 = bustupLoad(bustup_1d);
    bustupWait(ref_c4);
    ref_c6 = bustupAlloc(ref_c4, left, rgb(0,0,0));
    bustupFade(ref_c6, rgb(128,0,0), 30);
    ref_c8 = dialogAlloc();
    ref_c9 = msgShow(msg_4);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]The information that the Chief risked his
[tab]life over is all going in the New World
[tab]Order’s favor... That’s so sad.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_c9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_c8);
    ref_ce = bustupFade(ref_c6, rgb(0,0,0), 10);
    bustupWait(ref_ce);
    bustupFree(ref_c6);
    unitRestoreFacing(ulala);
    b(label_113);
  label_d3:
    unitFacePlayer(ulala);
    ref_d4 = bustupLoad(bustup_1e);
    bustupWait(ref_d4);
    ref_d6 = bustupAlloc(ref_d4, left, rgb(0,0,0));
    bustupFade(ref_d6, rgb(128,0,0), 30);
    ref_d8 = dialogAlloc();
    ref_d9 = msgShow(msg_5);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Ma-ya, [tatsuya]-kun is finally ready to speak...
[tab]Should we really be taking our time...?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_d9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_d8);
    ref_de = bustupFade(ref_d6, rgb(0,0,0), 10);
    bustupWait(ref_de);
    bustupFree(ref_d6);
    unitRestoreFacing(ulala);
    b(label_113);
  label_e3:
    unitFacePlayer(ulala);
    ref_e4 = bustupLoad(bustup_17);
    bustupWait(ref_e4);
    ref_e6 = bustupAlloc(ref_e4, left, rgb(0,0,0));
    bustupFade(ref_e6, rgb(128,0,0), 30);
    ref_e8 = dialogAlloc();
    ref_e9 = msgShow(msg_6);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Everyone is so positive and adaptive.
[tab]I’m just barely keeping up...
[tab]At times, I still feel like it’s a dream.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2d, 1);
    wait(ref_e9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_e8);
    ref_ee = bustupFade(ref_e6, rgb(0,0,0), 10);
    bustupWait(ref_ee);
    bustupFree(ref_e6);
    unitRestoreFacing(ulala);
    b(label_113);
  label_f3:
    unitFacePlayer(ulala);
    ref_f4 = bustupLoad(bustup_18);
    bustupWait(ref_f4);
    ref_f6 = bustupAlloc(ref_f4, left, rgb(0,0,0));
    bustupFade(ref_f6, rgb(128,0,0), 30);
    ref_f8 = dialogAlloc();
    ref_f9 = msgShow(msg_7);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Ma-ya, let’s do it...!
[tab]The world is on our shoulders!
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_30, 1);
    wait(ref_f9);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_f8);
    ref_fe = bustupFade(ref_f6, rgb(0,0,0), 10);
    bustupWait(ref_fe);
    bustupFree(ref_f6);
    unitRestoreFacing(ulala);
    b(label_113);
  label_103:
    unitFacePlayer(ulala);
    ref_104 = bustupLoad(bustup_19);
    bustupWait(ref_104);
    ref_106 = bustupAlloc(ref_104, left, rgb(0,0,0));
    bustupFade(ref_106, rgb(128,0,0), 30);
    ref_108 = dialogAlloc();
    ref_109 = msgShow(msg_8);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Nyar is always saying things to worry
[tab]people... He’s so mean.
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_2f, 1);
    wait(ref_109);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_108);
    ref_10e = bustupFade(ref_106, rgb(0,0,0), 10);
    bustupWait(ref_10e);
    bustupFree(ref_106);
    unitRestoreFacing(ulala);
    b(label_113);
  label_113:
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_173);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_163);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_153);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_143);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_133);
    unitFacePlayer(katsuya);
    ref_121 = bustupLoad(bustup_21);
    bustupWait(ref_121);
    ref_123 = bustupAlloc(ref_121, left, rgb(0,0,0));
    bustupFade(ref_123, rgb(128,0,0), 30);
    ref_125 = dialogAlloc();
    ref_126 = msgShow(msg_9);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]It’s not like Baofu to judge someone
[tab]solely on their words.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_126);
    ref_129 = msgShow(msg_10);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Could it be... 
[tab]that he thought only he was special?
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_129);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_125);
    ref_12e = bustupFade(ref_123, rgb(0,0,0), 10);
    bustupWait(ref_12e);
    bustupFree(ref_123);
    unitRestoreFacing(katsuya);
    b(label_183);
  label_133:
    unitFacePlayer(katsuya);
    ref_134 = bustupLoad(bustup_27);
    bustupWait(ref_134);
    ref_136 = bustupAlloc(ref_134, left, rgb(0,0,0));
    bustupFade(ref_136, rgb(128,0,0), 30);
    ref_138 = dialogAlloc();
    ref_139 = msgShow(msg_11);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]The top of this TV station is linked to
[tab]New World Order. Even the truth behind
[tab]the Chief’s death will be misinterpreted.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_139);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_138);
    ref_13e = bustupFade(ref_136, rgb(0,0,0), 10);
    bustupWait(ref_13e);
    bustupFree(ref_136);
    unitRestoreFacing(katsuya);
    b(label_183);
  label_143:
    unitFacePlayer(katsuya);
    ref_144 = bustupLoad(bustup_23);
    bustupWait(ref_144);
    ref_146 = bustupAlloc(ref_144, left, rgb(0,0,0));
    bustupFade(ref_146, rgb(128,0,0), 30);
    ref_148 = dialogAlloc();
    ref_149 = msgShow(msg_12);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]I don’t think this is the time to be
[tab]sitting around, either...
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_149);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_148);
    ref_14e = bustupFade(ref_146, rgb(0,0,0), 10);
    bustupWait(ref_14e);
    bustupFree(ref_146);
    unitRestoreFacing(katsuya);
    b(label_183);
  label_153:
    unitFacePlayer(katsuya);
    ref_154 = bustupLoad(bustup_21);
    bustupWait(ref_154);
    ref_156 = bustupAlloc(ref_154, left, rgb(0,0,0));
    bustupFade(ref_156, rgb(128,0,0), 30);
    ref_158 = dialogAlloc();
    ref_159 = msgShow(msg_13);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]It is still hard for me to believe. 
[tab]But [tatsuya] would never lie to me... 
[tab]Even if it’s [tatsuya] from the "Other Side"!
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_159);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_158);
    ref_15e = bustupFade(ref_156, rgb(0,0,0), 10);
    bustupWait(ref_15e);
    bustupFree(ref_156);
    unitRestoreFacing(katsuya);
    b(label_183);
  label_163:
    unitFacePlayer(katsuya);
    ref_164 = bustupLoad(bustup_21);
    bustupWait(ref_164);
    ref_166 = bustupAlloc(ref_164, left, rgb(0,0,0));
    bustupFade(ref_166, rgb(128,0,0), 30);
    ref_168 = dialogAlloc();
    ref_169 = msgShow(msg_14);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Giving up is the easy way...
[tab]From now on, we must believe there
[tab]is at least a glimmer of hope!
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_169);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_168);
    ref_16e = bustupFade(ref_166, rgb(0,0,0), 10);
    bustupWait(ref_16e);
    bustupFree(ref_166);
    unitRestoreFacing(katsuya);
    b(label_183);
  label_173:
    unitFacePlayer(katsuya);
    ref_174 = bustupLoad(bustup_21);
    bustupWait(ref_174);
    ref_176 = bustupAlloc(ref_174, left, rgb(0,0,0));
    bustupFade(ref_176, rgb(128,0,0), 30);
    ref_178 = dialogAlloc();
    ref_179 = msgShow(msg_15);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Anger, ignorance, and devotion... 
[tab]These are caused by emotion. From emotions, 
[tab]people spawn shadows, and that makes us human.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_179);
    unitAnimationPlay(katsuya, animation_a, 1);
    dialogFree(ref_178);
    ref_17e = bustupFade(ref_176, rgb(0,0,0), 10);
    bustupWait(ref_17e);
    bustupFree(ref_176);
    unitRestoreFacing(katsuya);
    b(label_183);
  label_183:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_1e0);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1d0);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_1c0);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_1b0);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_1a0);
    unitFacePlayer(baofu);
    ref_191 = bustupLoad(bustup_31);
    bustupWait(ref_191);
    ref_193 = bustupAlloc(ref_191, left, rgb(0,0,0));
    bustupFade(ref_193, rgb(128,0,0), 30);
    ref_195 = dialogAlloc();
    ref_196 = msgShow(msg_16);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Even someone like that can be a Persona user. 
[tab]I always thought it took a special talent 
[tab]or something.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1d, 1);
    wait(ref_196);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_195);
    ref_19b = bustupFade(ref_193, rgb(0,0,0), 10);
    bustupWait(ref_19b);
    bustupFree(ref_193);
    unitRestoreFacing(baofu);
    b(label_1f0);
  label_1a0:
    unitFacePlayer(baofu);
    ref_1a1 = bustupLoad(bustup_2d);
    bustupWait(ref_1a1);
    ref_1a3 = bustupAlloc(ref_1a1, left, rgb(0,0,0));
    bustupFade(ref_1a3, rgb(128,0,0), 30);
    ref_1a5 = dialogAlloc();
    ref_1a6 = msgShow(msg_17);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Not just here, but all media will report
[tab]the New World Order’s advantage...
[tab]Are there any TRUE journalists out there?
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1a6);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1a5);
    ref_1ab = bustupFade(ref_1a3, rgb(0,0,0), 10);
    bustupWait(ref_1ab);
    bustupFree(ref_1a3);
    unitRestoreFacing(baofu);
    b(label_1f0);
  label_1b0:
    unitFacePlayer(baofu);
    ref_1b1 = bustupLoad(bustup_2c);
    bustupWait(ref_1b1);
    ref_1b3 = bustupAlloc(ref_1b1, left, rgb(0,0,0));
    bustupFade(ref_1b3, rgb(128,0,0), 30);
    ref_1b5 = dialogAlloc();
    ref_1b6 = msgShow(msg_18);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]This time around, I agree with [suou]...
[tab]Look at the kid’s face...
[tab]We gotta get rid of all the pain...
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1b6);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1b5);
    ref_1bb = bustupFade(ref_1b3, rgb(0,0,0), 10);
    bustupWait(ref_1bb);
    bustupFree(ref_1b3);
    unitRestoreFacing(baofu);
    b(label_1f0);
  label_1c0:
    unitFacePlayer(baofu);
    ref_1c1 = bustupLoad(bustup_2d);
    bustupWait(ref_1c1);
    ref_1c3 = bustupAlloc(ref_1c1, left, rgb(0,0,0));
    bustupFade(ref_1c3, rgb(128,0,0), 30);
    ref_1c5 = dialogAlloc();
    ref_1c6 = msgShow(msg_19);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]To think there was such a secret in this world. 
[tab]I can understand why [tatsuya] is
[tab]called the Paradox...
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1c6);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1c5);
    ref_1cb = bustupFade(ref_1c3, rgb(0,0,0), 10);
    bustupWait(ref_1cb);
    bustupFree(ref_1c3);
    unitRestoreFacing(baofu);
    b(label_1f0);
  label_1d0:
    unitFacePlayer(baofu);
    ref_1d1 = bustupLoad(bustup_2d);
    bustupWait(ref_1d1);
    ref_1d3 = bustupAlloc(ref_1d1, left, rgb(0,0,0));
    bustupFade(ref_1d3, rgb(128,0,0), 30);
    ref_1d5 = dialogAlloc();
    ref_1d6 = msgShow(msg_20);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]If you’re still alright, it means it’s too
[tab]early to quit, right? Even if it’s futile,
[tab]let’s keep going forward as long as we can!
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_1d6);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1d5);
    ref_1db = bustupFade(ref_1d3, rgb(0,0,0), 10);
    bustupWait(ref_1db);
    bustupFree(ref_1d3);
    unitRestoreFacing(baofu);
    b(label_1f0);
  label_1e0:
    unitFacePlayer(baofu);
    ref_1e1 = bustupLoad(bustup_2d);
    bustupWait(ref_1e1);
    ref_1e3 = bustupAlloc(ref_1e1, left, rgb(0,0,0));
    bustupFade(ref_1e3, rgb(128,0,0), 30);
    ref_1e5 = dialogAlloc();
    ref_1e6 = msgShow(msg_21);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Worries create a shadow in one’s heart...
[tab]That is what he is after. It is especially
[tab]effective against someone like Serizawa.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_1e6);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_1e5);
    ref_1eb = bustupFade(ref_1e3, rgb(0,0,0), 10);
    bustupWait(ref_1eb);
    bustupFree(ref_1e3);
    unitRestoreFacing(baofu);
    b(label_1f0);
  label_1f0:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, MBIT_NANJO_YOMEURI);
    bne(var_0, 0, label_1f7);
    b(label_230);
    b(label_1f9);
  label_1f7:
    bne(var_0, 1, label_1f9);
    b(label_1f9);
  label_1f9:
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_220);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_20d);
    unitFacePlayer(nanjo);
    ref_1fe = bustupLoad(bustup_36);
    bustupWait(ref_1fe);
    ref_200 = bustupAlloc(ref_1fe, left, rgb(0,0,0));
    bustupFade(ref_200, rgb(128,0,0), 30);
    ref_202 = dialogAlloc();
    ref_203 = msgShow(msg_22);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]The nature of Persona... 
[tab]From those words, it may be hard to believe, 
[tab]but he was chosen by Philemon.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_203);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_202);
    ref_208 = bustupFade(ref_200, rgb(0,0,0), 10);
    bustupWait(ref_208);
    bustupFree(ref_200);
    unitRestoreFacing(nanjo);
    b(label_23f);
  label_20d:
    unitFacePlayer(nanjo);
    ref_20e = bustupLoad(bustup_36);
    bustupWait(ref_20e);
    ref_210 = bustupAlloc(ref_20e, left, rgb(0,0,0));
    bustupFade(ref_210, rgb(128,0,0), 30);
    ref_212 = dialogAlloc();
    ref_213 = msgShow(msg_23);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]The New World Order information operation
[tab]does not end in this country. 
[tab]They have already expanded it worldwide.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_213);
    ref_216 = msgShow(msg_24);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]So far we have discovered 11 countries...
[tab]In each country, the New World Order is
[tab]somehow involved in the government press.
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_216);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_212);
    ref_21b = bustupFade(ref_210, rgb(0,0,0), 10);
    bustupWait(ref_21b);
    bustupFree(ref_210);
    unitRestoreFacing(nanjo);
    b(label_23f);
  label_220:
    unitFacePlayer(nanjo);
    ref_221 = bustupLoad(bustup_3b);
    bustupWait(ref_221);
    ref_223 = bustupAlloc(ref_221, left, rgb(0,0,0));
    bustupFade(ref_223, rgb(128,0,0), 30);
    ref_225 = dialogAlloc();
    ref_226 = msgShow(msg_25);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]Amano-san, I think we’d better hurry...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_226);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_225);
    ref_22b = bustupFade(ref_223, rgb(0,0,0), 10);
    bustupWait(ref_22b);
    bustupFree(ref_223);
    unitRestoreFacing(nanjo);
    b(label_23f);
  label_230:
    ref_230 = bustupLoad(bustup_36);
    bustupWait(ref_230);
    ref_232 = bustupAlloc(ref_230, left, rgb(0,0,0));
    bustupFade(ref_232, rgb(128,0,0), 30);
    ref_234 = dialogAlloc();
    ref_235 = msgShow(msg_26);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]...Yes!! I knew the Yomiuri Giants are the No. 1 team! 
[tab]Players, coaches, and owner... 
[tab]everything is first-class...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_1a, 1);
    wait(ref_235);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_234);
    ref_23a = bustupFade(ref_232, rgb(0,0,0), 10);
    bustupWait(ref_23a);
    bustupFree(ref_232);
    bitSet(MBIT_NANJO_YOMEURI);
    b(label_23f);
  label_23f:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_269);
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_256);
    unitFacePlayer(elly);
    ref_247 = bustupLoad(bustup_3d);
    bustupWait(ref_247);
    ref_249 = bustupAlloc(ref_247, left, rgb(0,0,0));
    bustupFade(ref_249, rgb(128,0,0), 30);
    ref_24b = dialogAlloc();
    ref_24c = msgShow(msg_27);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]The nature of Persona... 
[tab]From those words, it may be hard to believe, 
[tab]but he was chosen by Philemon.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_24c);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_24b);
    ref_251 = bustupFade(ref_249, rgb(0,0,0), 10);
    bustupWait(ref_251);
    bustupFree(ref_249);
    unitRestoreFacing(elly);
    b(label_279);
  label_256:
    unitFacePlayer(elly);
    ref_257 = bustupLoad(bustup_3d);
    bustupWait(ref_257);
    ref_259 = bustupAlloc(ref_257, left, rgb(0,0,0));
    bustupFade(ref_259, rgb(128,0,0), 30);
    ref_25b = dialogAlloc();
    ref_25c = msgShow(msg_28);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]The New World Order information operation
[tab]does not end in this country. 
[tab]They have already expanded it worldwide.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_25c);
    ref_25f = msgShow(msg_29);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]So far we have discovered 11 countries...
[tab]In each country, the New World Order is
[tab]somehow involved in the government press.
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_25f);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_25b);
    ref_264 = bustupFade(ref_259, rgb(0,0,0), 10);
    bustupWait(ref_264);
    bustupFree(ref_259);
    unitRestoreFacing(elly);
    b(label_279);
  label_269:
    unitFacePlayer(elly);
    ref_26a = bustupLoad(bustup_42);
    bustupWait(ref_26a);
    ref_26c = bustupAlloc(ref_26a, left, rgb(0,0,0));
    bustupFade(ref_26c, rgb(128,0,0), 30);
    ref_26e = dialogAlloc();
    ref_26f = msgShow(msg_30);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Ms. Amano...
[tab]I don’t think this is the time to be
[tab]stopping anywhere...
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_26f);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_26e);
    ref_274 = bustupFade(ref_26c, rgb(0,0,0), 10);
    bustupWait(ref_274);
    bustupFree(ref_26c);
    unitRestoreFacing(elly);
    b(label_279);
  label_279:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_2b2);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_2a2);
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_292);
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_284);
  label_284:
    unitAnimationPlay(tatsuya, animation_6, 1);
    ref_285 = bustupLoad(bustup_12);
    bustupWait(ref_285);
    ref_287 = bustupAlloc(ref_285, right, rgb(0,0,0));
    bustupFade(ref_287, rgb(128,0,0), 30);
    bustupFlip(ref_287, true);
    ref_28a = dialogAlloc();
    ref_28b = msgShow(msg_31);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]. . . . . . . . .
[wait][clear]
***************************************/
    wait(ref_28b);
    dialogFree(ref_28a);
    ref_28e = bustupFade(ref_287, rgb(0,0,0), 10);
    bustupWait(ref_28e);
    bustupFree(ref_287);
    b(label_2c2);
  label_292:
    unitFacePlayer(tatsuya);
    ref_293 = bustupLoad(bustup_b);
    bustupWait(ref_293);
    ref_295 = bustupAlloc(ref_293, left, rgb(0,0,0));
    bustupFade(ref_295, rgb(128,0,0), 30);
    ref_297 = dialogAlloc();
    ref_298 = msgShow(msg_32);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]Just as they say, I am the Paradox.
[tab]That’s why... I don’t get involved much with
[tab]the people from "This Side"...
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_298);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_297);
    ref_29d = bustupFade(ref_295, rgb(0,0,0), 10);
    bustupWait(ref_29d);
    bustupFree(ref_295);
    unitRestoreFacing(tatsuya);
    b(label_2c2);
  label_2a2:
    unitFacePlayer(tatsuya);
    ref_2a3 = bustupLoad(bustup_10);
    bustupWait(ref_2a3);
    ref_2a5 = bustupAlloc(ref_2a3, left, rgb(0,0,0));
    bustupFade(ref_2a5, rgb(128,0,0), 30);
    ref_2a7 = dialogAlloc();
    ref_2a8 = msgShow(msg_33);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]We still have time... As long as we stop
[tab]Tatsuzou and Wang Long’s Dragon Ritual...
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2a8);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2a7);
    ref_2ad = bustupFade(ref_2a5, rgb(0,0,0), 10);
    bustupWait(ref_2ad);
    bustupFree(ref_2a5);
    unitRestoreFacing(tatsuya);
    b(label_2c2);
  label_2b2:
    unitFacePlayer(tatsuya);
    ref_2b3 = bustupLoad(bustup_b);
    bustupWait(ref_2b3);
    ref_2b5 = bustupAlloc(ref_2b3, left, rgb(0,0,0));
    bustupFade(ref_2b5, rgb(128,0,0), 30);
    ref_2b7 = dialogAlloc();
    ref_2b8 = msgShow(msg_34);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]Nyarlathotep is a shadow hiding within us...
[tab]But, it should not be feared... 
[tab]Don’t forget, that shadow is a part of you.
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_2d, 1);
    wait(ref_2b8);
    unitAnimationPlay(tatsuya, animation_a, 1);
    dialogFree(ref_2b7);
    ref_2bd = bustupFade(ref_2b5, rgb(0,0,0), 10);
    bustupWait(ref_2bd);
    bustupFree(ref_2b5);
    unitRestoreFacing(tatsuya);
    b(label_2c2);
  label_2c2:
    controlEnable();
}

function ASA()
{
    controlDisable();
    bitGet(var_0, EBIT_MAMIMES);
    bez(var_0, label_2cb);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_311);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_301);
  label_2cb:
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_2cf);
    b(label_2d2);
    b(label_2d2);
  label_2cf:
    bne(var_0, 1, label_2d2);
    b(label_2eb);
    b(label_2d2);
  label_2d2:
    unitFacePlayer(npc1);
    ref_2d3 = bustupLoad(bustup_cc);
    bustupWait(ref_2d3);
    ref_2d5 = bustupAlloc(ref_2d3, right, rgb(0,0,0));
    bustupFade(ref_2d5, rgb(128,0,0), 30);
    ref_2d7 = dialogAlloc();
    ref_2d8 = msgShow(msg_35);
/***************************************
[color(yellow)]Mami[color(white)]
[tab]Huh, Lisa...?
[tab]She seemed very down.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_0, 1);
    wait(ref_2d8);
    ref_2db = msgShow(msg_36);
/***************************************
[color(yellow)]Mami[color(white)]
[tab]Being attacked by the Joker seemed
[tab]to be a shock for her...
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2db);
    bitGet(var_0, EBIT_MAMIMES);
    bnz(var_0, label_2e4);
    ref_2e0 = msgShow(msg_37);
/***************************************
[color(yellow)]Mami Shibata[color(white)]
[tab][color(green)]A member of Muses, a high school girl
[tab]bad produced by Ginji Sasaki. She goes
[tab]to Sevens, and is known as Asacchi.[color(white)]
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_0, 1);
    bitSet(EBIT_MAMIMES);
    wait(ref_2e0);
  label_2e4:
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2d7);
    ref_2e6 = bustupFade(ref_2d5, rgb(0,0,0), 10);
    bustupWait(ref_2e6);
    bustupFree(ref_2d5);
    unitRestoreFacing(npc1);
    b(label_324);
  label_2eb:
    unitFacePlayer(npc1);
    ref_2ec = bustupLoad(bustup_cc);
    bustupWait(ref_2ec);
    ref_2ee = bustupAlloc(ref_2ec, right, rgb(0,0,0));
    bustupFade(ref_2ee, rgb(128,0,0), 30);
    ref_2f0 = dialogAlloc();
    ref_2f1 = msgShow(msg_38);
/***************************************
[color(yellow)]Mami[color(white)]
[tab]...Ah, you’re with Elly-san, right?
[tab]Thank you for yesterday... 
[tab]It’s because of all of you that we are safe.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_2f1);
    bitGet(var_0, EBIT_MAMIMES);
    bnz(var_0, label_2fa);
    ref_2f6 = msgShow(msg_39);
/***************************************
[color(yellow)]Mami Shibata[color(white)]
[tab][color(green)]A member of Muses, a high school girl
[tab]band produced by Ginji Sasaki. She goes
[tab]to Sevens, and is known as Asacchi.[color(white)]
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_0, 1);
    bitSet(EBIT_MAMIMES);
    wait(ref_2f6);
  label_2fa:
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_2f0);
    ref_2fc = bustupFade(ref_2ee, rgb(0,0,0), 10);
    bustupWait(ref_2fc);
    bustupFree(ref_2ee);
    unitRestoreFacing(npc1);
    b(label_324);
  label_301:
    unitFacePlayer(npc1);
    ref_302 = bustupLoad(bustup_cc);
    bustupWait(ref_302);
    ref_304 = bustupAlloc(ref_302, right, rgb(0,0,0));
    bustupFade(ref_304, rgb(128,0,0), 30);
    ref_306 = dialogAlloc();
    ref_307 = msgShow(msg_40);
/***************************************
[color(yellow)]Mami[color(white)]
[tab]After Lisa, Producer Sasaki has also disappeared. 
[tab]After all they have gone through... 
[tab]Could Muses be finished...?
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_307);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_306);
    ref_30c = bustupFade(ref_304, rgb(0,0,0), 10);
    bustupWait(ref_30c);
    bustupFree(ref_304);
    unitRestoreFacing(npc1);
    b(label_324);
  label_311:
    unitFacePlayer(npc1);
    ref_312 = bustupLoad(bustup_cc);
    bustupWait(ref_312);
    ref_314 = bustupAlloc(ref_312, right, rgb(0,0,0));
    bustupFade(ref_314, rgb(128,0,0), 30);
    ref_316 = dialogAlloc();
    ref_317 = msgShow(msg_41);
/***************************************
[color(yellow)]Mami[color(white)]
[tab]It seems Lisa hasn’t come home yet either. 
[tab]Where could she have gone at a time like this...?
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_317);
    ref_31a = msgShow(msg_42);
/***************************************
[color(yellow)]Mami[color(white)]
[tab]Even this place would have been in danger
[tab]if it weren’t for Brown-san...
[tab]Her father must be worried as well.
[wait][clear]
***************************************/
    unitAnimationPlay(npc1, animation_24, 1);
    wait(ref_31a);
    unitAnimationPlay(npc1, animation_0, 1);
    dialogFree(ref_316);
    ref_31f = bustupFade(ref_314, rgb(0,0,0), 10);
    bustupWait(ref_31f);
    bustupFree(ref_314);
    unitRestoreFacing(npc1);
    b(label_324);
  label_324:
    controlEnable();
}

function MIE()
{
    controlDisable();
    bitGet(var_0, EBIT_MIHOMES);
    bez(var_0, label_32d);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_376);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_363);
  label_32d:
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bne(var_0, 0, label_331);
    b(label_334);
    b(label_334);
  label_331:
    bne(var_0, 1, label_334);
    b(label_34a);
    b(label_334);
  label_334:
    unitFacePlayer(npc2);
    ref_335 = bustupLoad(bustup_ce);
    bustupWait(ref_335);
    ref_337 = bustupAlloc(ref_335, right, rgb(0,0,0));
    bustupFade(ref_337, rgb(128,0,0), 30);
    ref_339 = dialogAlloc();
    ref_33a = msgShow(msg_43);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]Lisa just disappeared somewhere. 
[tab]Meepo and others have been searching for her, 
[tab]but they still can’t find her.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_33a);
    bitGet(var_0, EBIT_MIHOMES);
    bnz(var_0, label_343);
    ref_33f = msgShow(msg_44);
/***************************************
[color(yellow)]Miho Ogishima[color(white)]
[tab][color(green)]A member of Muses, a high school girl
[tab]band produced by Ginji Sasaki. She goes
[tab]to Sevens, and is known as Meepo.[color(white)]
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_0, 1);
    bitSet(EBIT_MIHOMES);
    wait(ref_33f);
  label_343:
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_339);
    ref_345 = bustupFade(ref_337, rgb(0,0,0), 10);
    bustupWait(ref_345);
    bustupFree(ref_337);
    unitRestoreFacing(npc2);
    b(label_389);
  label_34a:
    unitFacePlayer(npc2);
    ref_34b = bustupLoad(bustup_ce);
    bustupWait(ref_34b);
    ref_34d = bustupAlloc(ref_34b, right, rgb(0,0,0));
    bustupFade(ref_34d, rgb(128,0,0), 30);
    ref_34f = dialogAlloc();
    ref_350 = msgShow(msg_45);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]...Eh, you know Elly-san...?
[tab]Meepo and the others were saved by
[tab]Brown-san and Elly-san.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_350);
    ref_353 = msgShow(msg_46);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]Please give them our thanks!
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_27, 1);
    wait(ref_353);
    bitGet(var_0, EBIT_MIHOMES);
    bnz(var_0, label_35c);
    ref_358 = msgShow(msg_47);
/***************************************
[color(yellow)]Miho Ogishima[color(white)]
[tab][color(green)]A member of Muses, a high school girl
[tab]band produced by Ginji Sasaki. She goes
[tab]to Sevens, and is known as Meepo.[color(white)]
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_0, 1);
    bitSet(EBIT_MIHOMES);
    wait(ref_358);
  label_35c:
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_34f);
    ref_35e = bustupFade(ref_34d, rgb(0,0,0), 10);
    bustupWait(ref_35e);
    bustupFree(ref_34d);
    unitRestoreFacing(npc2);
    b(label_389);
  label_363:
    unitFacePlayer(npc2);
    ref_364 = bustupLoad(bustup_ce);
    bustupWait(ref_364);
    ref_366 = bustupAlloc(ref_364, right, rgb(0,0,0));
    bustupFade(ref_366, rgb(128,0,0), 30);
    ref_368 = dialogAlloc();
    ref_369 = msgShow(msg_48);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]It seems like Lisa has a complex about her looks. 
[tab]She looks so hip, yet she calls herself strange...
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_369);
    ref_36c = msgShow(msg_49);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]She stands out, and is hip, isn’t she...?
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_36c);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_368);
    ref_371 = bustupFade(ref_366, rgb(0,0,0), 10);
    bustupWait(ref_371);
    bustupFree(ref_366);
    unitRestoreFacing(npc2);
    b(label_389);
  label_376:
    unitFacePlayer(npc2);
    ref_377 = bustupLoad(bustup_ce);
    bustupWait(ref_377);
    ref_379 = bustupAlloc(ref_377, right, rgb(0,0,0));
    bustupFade(ref_379, rgb(128,0,0), 30);
    ref_37b = dialogAlloc();
    ref_37c = msgShow(msg_50);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]Did you know? Brown-san is very powerful!
[tab]He may be a good match for Lisa’s father.
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_37c);
    ref_37f = msgShow(msg_51);
/***************************************
[color(yellow)]Miho[color(white)]
[tab]But based on impact, Lisa’s dad wins!
[tab]He’s REALLY scary when he’s mad. 
[tab]He does not say a word! He’s like a "silent dad".
[wait][clear]
***************************************/
    unitAnimationPlay(npc2, animation_24, 1);
    wait(ref_37f);
    unitAnimationPlay(npc2, animation_0, 1);
    dialogFree(ref_37b);
    ref_384 = bustupFade(ref_379, rgb(0,0,0), 10);
    bustupWait(ref_384);
    bustupFree(ref_379);
    unitRestoreFacing(npc2);
    b(label_389);
  label_389:
    controlEnable();
}

function BRO()
{
    controlDisable();
    bitGet(var_0, MBIT_BROWNTALK);
    bez(var_0, label_3a4);
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_3e1);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_3cb);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_3bb);
    unitFacePlayer(npc3);
    ref_395 = bustupLoad(bustup_c3);
    bustupWait(ref_395);
    ref_397 = bustupAlloc(ref_395, right, rgb(0,0,0));
    bustupFade(ref_397, rgb(128,0,0), 30);
    ref_399 = dialogAlloc();
    ref_39a = msgShow(msg_52);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]Oh, you’re here. As you can see, 
[tab]this place is way cool now too. 
[tab]Without me, it would be nothing... Da ha ha ha!
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_23, 1);
    wait(ref_39a);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_399);
    ref_39f = bustupFade(ref_397, rgb(0,0,0), 10);
    bustupWait(ref_39f);
    bustupFree(ref_397);
    unitRestoreFacing(npc3);
    b(label_3f1);
  label_3a4:
    unitFacePlayer(npc3);
    ref_3a5 = bustupLoad(bustup_c3);
    bustupWait(ref_3a5);
    ref_3a7 = bustupAlloc(ref_3a5, right, rgb(0,0,0));
    bustupFade(ref_3a7, rgb(128,0,0), 30);
    ref_3a9 = dialogAlloc();
    ref_3aa = msgShow(msg_53);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]Hey! Long time no see! ...Oh, this is the first time... 
[tab]Hey! First time, see! [delay(15)]Ha ha ha![delay(15)]
[tab]...Wait, I haven’t introduced myself...
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_23, 1);
    wait(ref_3aa);
    ref_3ad = msgShow(msg_54);
/***************************************
[color(yellow)]Brown[color(white)]
[tab][color(green)]A multi-talented entertainer. 
[tab]He’s an alumnus of St. Hermelin, 
[tab]like Yukino and Elly... He is also a Persona user.[color(white)]
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_0, 1);
    wait(ref_3ad);
    ref_3b0 = msgShow(msg_55);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]So, I am Hidehiko Uesugi... Call me Brown.
[tab]Nanjo and Elly are my old pals.
[tab]So, along with my new show...
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_2d, 1);
    bitSet(MBIT_BROWNTALK);
    wait(ref_3b0);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3a9);
    ref_3b6 = bustupFade(ref_3a7, rgb(0,0,0), 10);
    bustupWait(ref_3b6);
    bustupFree(ref_3a7);
    unitRestoreFacing(npc3);
    b(label_3f1);
  label_3bb:
    unitFacePlayer(npc3);
    ref_3bc = bustupLoad(bustup_c3);
    bustupWait(ref_3bc);
    ref_3be = bustupAlloc(ref_3bc, right, rgb(0,0,0));
    bustupFade(ref_3be, rgb(128,0,0), 30);
    ref_3c0 = dialogAlloc();
    ref_3c1 = msgShow(msg_56);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]Oh, you’re here. As you can see, 
[tab]this place is way cool now too. 
[tab]Without me, it would be nothing... Da ha ha ha!
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_23, 1);
    wait(ref_3c1);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3c0);
    ref_3c6 = bustupFade(ref_3be, rgb(0,0,0), 10);
    bustupWait(ref_3c6);
    bustupFree(ref_3be);
    unitRestoreFacing(npc3);
    b(label_3f1);
  label_3cb:
    unitFacePlayer(npc3);
    ref_3cc = bustupLoad(bustup_c3);
    bustupWait(ref_3cc);
    ref_3ce = bustupAlloc(ref_3cc, right, rgb(0,0,0));
    bustupFade(ref_3ce, rgb(128,0,0), 30);
    ref_3d0 = dialogAlloc();
    ref_3d1 = msgShow(msg_57);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]Da ha ha ha... What happened?
[tab]You look so surprised.[delay(15)]
[tab]Are you surprised by my activity?
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_23, 1);
    wait(ref_3d1);
    ref_3d4 = msgShow(msg_58);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]Da ha ha ha...!
[tab]Well, that’s the deal, so you guys go on
[tab]to the Sumaru Castle without any worry.
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_2d, 1);
    wait(ref_3d4);
    ref_3d7 = msgShow(msg_59);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]I’ll show the people of the city just
[tab]how way cool I am.
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_2d, 1);
    wait(ref_3d7);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3d0);
    ref_3dc = bustupFade(ref_3ce, rgb(0,0,0), 10);
    bustupWait(ref_3dc);
    bustupFree(ref_3ce);
    unitRestoreFacing(npc3);
    b(label_3f1);
  label_3e1:
    unitFacePlayer(npc3);
    ref_3e2 = bustupLoad(bustup_c3);
    bustupWait(ref_3e2);
    ref_3e4 = bustupAlloc(ref_3e2, right, rgb(0,0,0));
    bustupFade(ref_3e4, rgb(128,0,0), 30);
    ref_3e6 = dialogAlloc();
    ref_3e7 = msgShow(msg_60);
/***************************************
[color(yellow)]Brown[color(white)]
[tab]What, you’re still here...?
[tab]You all still have things to do, right?
[tab]Let’s try to at least stay alive.
[wait][clear]
***************************************/
    unitAnimationPlay(npc3, animation_2d, 1);
    wait(ref_3e7);
    unitAnimationPlay(npc3, animation_0, 1);
    dialogFree(ref_3e6);
    ref_3ec = bustupFade(ref_3e4, rgb(0,0,0), 10);
    bustupWait(ref_3ec);
    bustupFree(ref_3e4);
    unitRestoreFacing(npc3);
    b(label_3f1);
  label_3f1:
    controlEnable();
}

function BLOCK_UKETUKE()
{
    controlDisable();
    bitGet(var_0, MBIT_SH_S_12);
    bne(var_0, 0, label_3f7);
    b(label_404);
  label_3f7:
    bne(var_0, 1, label_404);
    bitGet(var_0, MBIT_SH_H_12);
    bne(var_0, 0, label_401);
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_3fe);
    b(label_405);
    b(label_400);
  label_3fe:
    bne(var_0, 1, label_400);
    b(label_400);
  label_400:
    b(label_403);
  label_401:
    bne(var_0, 1, label_403);
    b(label_403);
  label_403:
    b(label_404);
  label_404:
    b(label_45c);
  label_405:
    add(var_a, var_a, 1);
    boutrange(var_a, 0, 1, label_409);
    b(label_40d);
    b(label_40d);
  label_409:
    bne(var_a, 2, label_40d);
    sub(var_a, var_a, 2);
    b(label_419);
    b(label_40d);
  label_40d:
    unitFacePlayer(unit_58);
    ref_40e = dialogAlloc();
    ref_40f = msgShow(msg_61);
/***************************************
[color(yellow)]Receptionist[color(white)]
[tab](Sigh) ...I’m such a nice person. 
[tab]I’m tired from standing all day at work, 
[tab]yet I smile and give my seat away. I’m too nice.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_40f);
    ref_412 = msgShow(msg_62);
/***************************************
[color(yellow)]Receptionist[color(white)]
[tab]...Ah, yes! How can I help you...?
[tab]Did you hear me talking to myself...?
[tab]Ahhh... I’m such an idiot!
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_412);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_40e);
    unitRestoreFacing(unit_58);
    b(label_4c0);
  label_419:
    unitFacePlayer(unit_58);
    ref_41a = dialogAlloc();
    ref_41b = msgShow(msg_63);
/***************************************
[color(yellow)]Receptionist[color(white)]
[tab]Welcome to Sumaru TV.
[tab]How can I help you?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_41b);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_41a);
    delayClear();
    delayWait(30);
    choiceSetResult(2);
    op_105(2);
    ref_424 = bustupLoad(bustup_1);
    bustupWait(ref_424);
    ref_426 = bustupAlloc(ref_424, center, rgb(0,0,0));
    bustupFade(ref_426, rgb(128,0,0), 30);
    ref_428 = dialogChoiceAlloc();
    ref_429 = msgShow(msg_64);
/***************************************
[tab]What do you want?
[choice(3)]Guess name
Talk
No business
[end_choice][clear]
***************************************/
    ref_42a = textInputInit();
    wait(ref_429);
    dialogFree(ref_428);
    ref_42d = bustupFade(ref_426, rgb(0,0,0), 10);
    bustupWait(ref_42d);
    bustupFree(ref_426);
    wait(ref_42a);
    choiceGetResult(var_0);
    bne(var_0, 0, label_435);
    b(label_43d);
    b(label_43c);
  label_435:
    bne(var_0, 1, label_439);
    unitRestoreFacing(unit_58);
    b(label_45c);
    b(label_43c);
  label_439:
    bne(var_0, 2, label_43c);
    unitRestoreFacing(unit_58);
    b(label_43c);
  label_43c:
    b(label_4c0);
  label_43d:
    ref_43d = textInputPrompt();
    wait(ref_43d);
    textInputCompare(msg_65, var_0);
    bne(var_0, 0, label_44a);
    ref_441 = dialogAlloc();
    ref_442 = msgShow(msg_66);
/***************************************
[color(yellow)]Receptionist[color(white)]
[tab]Huh...?
[tab]There is no one by that name here...
[tab]Are you sure you’re not mistaken?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_442);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_441);
    unitRestoreFacing(unit_58);
    b(label_4c0);
    b(label_45c);
  label_44a:
    bne(var_0, 1, label_45c);
    ref_44b = dialogAlloc();
    ref_44c = msgShow(msg_67);
/***************************************
[color(yellow)]Saori Kudou[color(white)]
[tab]My, how did you know my name...?
[tab]There’s someone searching for me...!?
[tab]Oh, it must be that geezer.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_44c);
    ref_44f = msgShow(msg_68);
/***************************************
[color(yellow)]Saori Kudou[color(white)]
[tab]But, why me? ...Huhhhh!?
[tab]An arranged marriage with his grandson!?
[tab]What am I suppose to do... It’s so sudden...
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_44f);
    ref_452 = msgShow(msg_69);
/***************************************
[color(yellow)]Saori Kudou[color(white)]
[tab]Th-Thanks. I’ll make sure I get in touch.
[tab]What to do...? What to do...?
[tab]I want to marry a celebrity.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_452);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_44b);
    bitSet(MBIT_KUDOU_GET);
    bitSet(MBIT_SH_HH);
    unitRestoreFacing(unit_58);
    b(label_4c0);
    b(label_45c);
  label_45c:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_4a6);
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_496);
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_47c);
    unitFacePlayer(unit_58);
    ref_463 = dialogAlloc();
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_468);
    msgShow(msg_70);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_46b);
  label_468:
    bne(var_0, 1, label_46b);
    msgShow(msg_71);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_46b);
  label_46b:
    ref_46b = msgShow(msg_72);
/***************************************
[tab]Yes, how can I help you...?
[tab]I’ve been saying this for so long,
[tab]but I plan on quitting this company.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_46b);
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_472);
    msgShow(msg_73);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_475);
  label_472:
    bne(var_0, 1, label_475);
    msgShow(msg_74);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_475);
  label_475:
    ref_475 = msgShow(msg_75);
/***************************************
[tab]We’ll never know when something like
[tab]that will ever happen again, right...!?
[tab]Now, even I am a bureau candidate... right.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_475);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_463);
    unitRestoreFacing(unit_58);
    b(label_4c0);
  label_47c:
    unitFacePlayer(unit_58);
    ref_47d = dialogAlloc();
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_482);
    msgShow(msg_76);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_485);
  label_482:
    bne(var_0, 1, label_485);
    msgShow(msg_77);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_485);
  label_485:
    ref_485 = msgShow(msg_78);
/***************************************
[tab]We’re the first ones to report about New
[tab]World Order. We were even the first to
[tab]cover Wang Long... Did you know this?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_485);
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_48c);
    msgShow(msg_79);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_48f);
  label_48c:
    bne(var_0, 1, label_48f);
    msgShow(msg_80);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_48f);
  label_48f:
    ref_48f = msgShow(msg_81);
/***************************************
[tab]Now we’re known as "Scoop TV"...
[tab]As in "Scoop Sumaru TV"...
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_48f);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_47d);
    unitRestoreFacing(unit_58);
    b(label_4c0);
  label_496:
    unitFacePlayer(unit_58);
    ref_497 = dialogAlloc();
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_49c);
    msgShow(msg_82);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_49f);
  label_49c:
    bne(var_0, 1, label_49f);
    msgShow(msg_83);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_49f);
  label_49f:
    ref_49f = msgShow(msg_84);
/***************************************
[tab]...I’m glad our coverage was accurate, but... 
[tab]for something like this to happen...
[tab]I should have quit while I had a chance...
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_49f);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_497);
    unitRestoreFacing(unit_58);
    b(label_4c0);
  label_4a6:
    unitFacePlayer(unit_58);
    ref_4a7 = dialogAlloc();
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_4ac);
    msgShow(msg_85);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_4af);
  label_4ac:
    bne(var_0, 1, label_4af);
    msgShow(msg_86);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_4af);
  label_4af:
    ref_4af = msgShow(msg_87);
/***************************************
[tab]What is going to happen to us now? Ahh!
[tab]When we land, I’m going to quit work...!
[tab]But first, I’ll get a celebrity hunk.
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_4af);
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_4b6);
    msgShow(msg_88);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_4b9);
  label_4b6:
    bne(var_0, 1, label_4b9);
    msgShow(msg_89);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_4b9);
  label_4b9:
    ref_4b9 = msgShow(msg_90);
/***************************************
[tab]A celebrity and a receptionist... 
[tab]It seems like there’d be some kind of connection...
[tab]Why do announcers get all the attention!?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_26, 1);
    wait(ref_4b9);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_4a7);
    unitRestoreFacing(unit_58);
    b(label_4c0);
  label_4c0:
    controlEnable();
}

function MESTEST()
{
    bitGet(var_0, MBIT_HI_NANJOTOUJO);
    bnz(var_0, label_4c9);
    bitSet(MBIT_HI_NANJOTOUJO);
    ref_4c5 = dialogAlloc();
    ref_4c6 = msgShow(msg_91);
/***************************************
MBIT HI NANJOTOUJO
Spread Nanjo rumor
Bit on
[wait][clear]
***************************************/
    wait(ref_4c6);
    dialogFree(ref_4c5);
  label_4c9:
}

function MESTEST1()
{
    bitGet(var_0, MBIT_AIS_32);
    bnz(var_0, label_4d2);
    bitSet(MBIT_AIS_32);
    ref_4cd = dialogAlloc();
    ref_4ce = msgShow(msg_92);
/***************************************
MBIT AIS 32
Affinity reading
Bit on
[wait][clear]
***************************************/
    wait(ref_4ce);
    dialogFree(ref_4cd);
    b(label_519);
  label_4d2:
    bitGet(var_0, EBIT_E006F);
    bnz(var_0, label_4da);
    bitSet(EBIT_E006F);
    ref_4d5 = dialogAlloc();
    ref_4d6 = msgShow(msg_93);
/***************************************
EBIT E006F
Cleared Lab
Bit on
[wait][clear]
***************************************/
    wait(ref_4d6);
    dialogFree(ref_4d5);
    b(label_519);
  label_4da:
    bitGet(var_0, EBIT_E0077);
    bnz(var_0, label_4e2);
    bitSet(EBIT_E0077);
    ref_4dd = dialogAlloc();
    ref_4de = msgShow(msg_94);
/***************************************
EBIT E0077
Cleared Smile Hirasaka
Bit on
[wait][clear]
***************************************/
    wait(ref_4de);
    dialogFree(ref_4dd);
    b(label_519);
  label_4e2:
    bitGet(var_0, EBIT_E007A);
    bnz(var_0, label_4ea);
    bitSet(EBIT_E007A);
    ref_4e5 = dialogAlloc();
    ref_4e6 = msgShow(msg_95);
/***************************************
EBIT E007A
Cleared Concert Hall
Bit on
[wait][clear]
***************************************/
    wait(ref_4e6);
    dialogFree(ref_4e5);
    b(label_519);
  label_4ea:
    bitGet(var_0, EBIT_E007B);
    bnz(var_0, label_4f2);
    bitSet(EBIT_E007B);
    ref_4ed = dialogAlloc();
    ref_4ee = msgShow(msg_96);
/***************************************
EBIT E007B
Tapped Tatsuzou
Bit on
[wait][clear]
***************************************/
    wait(ref_4ee);
    dialogFree(ref_4ed);
    b(label_519);
  label_4f2:
    bitGet(var_0, EBIT_E007F);
    bnz(var_0, label_4fa);
    bitSet(EBIT_E007F);
    ref_4f5 = dialogAlloc();
    ref_4f6 = msgShow(msg_97);
/***************************************
EBIT E007F
Cleared Factory
Bit on
[wait][clear]
***************************************/
    wait(ref_4f6);
    dialogFree(ref_4f5);
    b(label_519);
  label_4fa:
    bitGet(var_0, EBIT_E008C);
    bnz(var_0, label_502);
    bitSet(EBIT_E008C);
    ref_4fd = dialogAlloc();
    ref_4fe = msgShow(msg_98);
/***************************************
EBIT E008C
Cleared Ruins
Bit on
[wait][clear]
***************************************/
    wait(ref_4fe);
    dialogFree(ref_4fd);
    b(label_519);
  label_502:
    bitGet(var_0, EBIT_E009F);
    bnz(var_0, label_50a);
    bitSet(EBIT_E009F);
    ref_505 = dialogAlloc();
    ref_506 = msgShow(msg_99);
/***************************************
EBIT E009F
Cleared Mt. Iwato
Bit on
[wait][clear]
***************************************/
    wait(ref_506);
    dialogFree(ref_505);
    b(label_519);
  label_50a:
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_512);
    bitSet(EBIT_E00AF);
    ref_50d = dialogAlloc();
    ref_50e = msgShow(msg_100);
/***************************************
EBIT E00AF
Cleared Torifune
Bit on
[wait][clear]
***************************************/
    wait(ref_50e);
    dialogFree(ref_50d);
    b(label_519);
  label_512:
    bitGet(var_0, EBIT_E00B8);
    bnz(var_0, label_519);
    bitSet(EBIT_E00B8);
    ref_515 = dialogAlloc();
    ref_516 = msgShow(msg_101);
/***************************************
EBIT E00B8
Cleared Sumaru Castle
Bit on
[wait][clear]
***************************************/
    wait(ref_516);
    dialogFree(ref_515);
  label_519:
}

function EXIT()
{
    controlDisable();
    sndMusicPlay(sound_3089, 127);
    objAnimTranslate(obj_8, 100, 0, 0, 30);
    objAnimTranslate(obj_9, -100, 0, 0, 30);
    objAnimWait(obj_8);
    objAnimWait(obj_9);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 6, false);
    screenFadeOuter(rgb(255,255,255), 6, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    bitClear(MBIT_EXITBIT);
    mapLoad(aoba, 9, 4);
}

function ELE()
{
    controlDisable();
    unitFacePlayer(unit_58);
    ref_52b = dialogAlloc();
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_530);
    msgShow(msg_102);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_533);
  label_530:
    bne(var_0, 1, label_533);
    msgShow(msg_103);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_533);
  label_533:
    ref_533 = msgShow(msg_104);
/***************************************
[tab]I’m very sorry.
[tab]Nobody is allowed up these stairs...
[tab]The reason?
[wait][clear]
***************************************/
    unitAnimationPlay(unit_58, animation_24, 1);
    wait(ref_533);
    bitGet(var_0, MBIT_KUDOU_GET);
    bne(var_0, 0, label_53a);
    msgShow(msg_105);
/***************************************
[color(yellow)]Receptionist[color(white)]

***************************************/
    b(label_53d);
  label_53a:
    bne(var_0, 1, label_53d);
    msgShow(msg_106);
/***************************************
[color(yellow)]Saori Kudou[color(white)]

***************************************/
    b(label_53d);
  label_53d:
    ref_53d = msgShow(msg_107);
/***************************************
[tab]...You know, right?
[wait][clear]
***************************************/
    wait(ref_53d);
    unitAnimationPlay(unit_58, animation_0, 1);
    dialogFree(ref_52b);
    unitRestoreFacing(unit_58);
    controlEnable();
}

function KEIBIIN()
{
    controlDisable();
    bitGet(var_0, MBIT_KI_DEVIL3);
    bne(var_0, 0, label_551);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_26, 1);
    ref_549 = dialogAlloc();
    ref_54a = msgShow(msg_108);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]I can’t guard this place anymore!!
[tab]If anything like that happens again,
[tab]I could lose my life!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_54a);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_549);
    unitRestoreFacing(npc4);
    b(label_599);
  label_551:
    bne(var_0, 1, label_599);
    bitGet(var_0, MBIT_KASIMA_OREIGET);
    bne(var_0, 0, label_58d);
    bitGet(var_0, IBIT_RUMOR_KASA);
    bne(var_0, 0, label_560);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_558 = dialogAlloc();
    ref_559 = msgShow(msg_109);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]There’s no doubt about it! It was Reiko
[tab]Kashima!! It wasn’t just a rumor.
[tab]Judging from that commotion...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_559);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_558);
    unitRestoreFacing(npc4);
    b(label_58c);
  label_560:
    bne(var_0, 1, label_58c);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_563 = dialogAlloc();
    ref_564 = msgShow(msg_110);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]Isn’t that umbrella Reiko Kashima’s!?
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_564);
    ref_567 = msgShow(msg_111);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]Defeating Reiko Kashima during all that
[tab]chaos, you are incredible! Much more
[tab]impressive than a security guard. Here...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_567);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_563);
    delayClear();
    delayWait(30);
    ref_56e = dialogAlloc();
    ref_56f = msgShow(msg_112);
/***************************************
[color(green)]Maya got the Incense Card Set.[color(white)]
[wait][clear]
***************************************/
    wait(ref_56f);
    dialogFree(ref_56e);
    delayClear();
    delayWait(30);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_575 = dialogAlloc();
    ref_576 = msgShow(msg_113);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]You can’t take it? Don’t worry about it.
[tab]It was actually our job. I’ve got to at
[tab]least do something in return, right?
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_576);
    unitFace(npc4, north);
    delayClear();
    delayWait(12);
    unitAnimationPlay(npc4, animation_19, 1);
    ref_57d = msgShow(msg_114);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]What the...!?
[tab]Where did he go...?
[tab]That’s abandoning the post!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_57d);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_575);
    unitRestoreFacing(npc4);
    partyItemAdd(st_card, 1);
    partyItemAdd(vi_card, 1);
    partyItemAdd(dx_card, 1);
    partyItemAdd(ag_card, 1);
    partyItemAdd(lu_card, 1);
    partyItemAdd(all_card, 1);
    bitClear(IBIT_RUMOR_KASA);
    bitSet(MBIT_KASIMA_OREIGET);
    b(label_58c);
  label_58c:
    b(label_598);
  label_58d:
    bne(var_0, 1, label_598);
    unitFacePlayer(npc4);
    unitAnimationPlay(npc4, animation_24, 1);
    ref_590 = dialogAlloc();
    ref_591 = msgShow(msg_115);
/***************************************
[color(yellow)]Frightened Security Guard[color(white)]
[tab]That WAS Reiko Kashima!! Just as I thought,
[tab]it wasn’t just a rumor. That whole mess
[tab]was caused by... Reiko Kashima.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_591);
    unitAnimationPlay(npc4, animation_0, 1);
    dialogFree(ref_590);
    unitRestoreFacing(npc4);
    b(label_598);
  label_598:
    b(label_599);
  label_599:
    bitSet(MBIT_KASIMA_OUTTALK);
    controlEnable();
}

function SITAI()
{
    controlDisable();
    ref_59d = dialogAlloc();
    ref_59e = msgShow(msg_116);
/***************************************
[color(yellow)]Corpse of a Tenchu Soldier[color(green)]
[tab]Looks like he was a member of the Civil
[tab]Defense Force. He’s already stopped
[tab]breathing.[color(white)]
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_59e);
    dialogFree(ref_59d);
    controlEnable();
    unitAnimationPlay(npc5, animation_16, 1);
}
