function START()
{
    screenEffectInit();
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), sub);
    sndMusicPlay(sound_3064, 127);
    levelFootstepSet(sfx_1a);
    envTriggerSet(EXITBOX, 131, 2, line, coll_2d);
    partyMemberCheck(var_0, ulala);
    bne(var_0, 0, label_8);
    b(label_e);
  label_8:
    bne(var_0, 1, label_e);
    ref_9 = spriteLoad(sprite_6);
    wait(ref_9);
    unitSpawn(ulala, sprite_6, 1033, 0, -1163, south, none);
    unitTriggerSet(ulala, B_URARATI, 255, 1);
    b(label_e);
  label_e:
    partyMemberCheck(var_0, katsuya);
    bne(var_0, 0, label_11);
    b(label_17);
  label_11:
    bne(var_0, 1, label_17);
    ref_12 = spriteLoad(sprite_d);
    wait(ref_12);
    unitSpawn(katsuya, sprite_d, 727, 0, -1250, south, none);
    unitTriggerSet(katsuya, B_KATUYYY, 255, 1);
    b(label_17);
  label_17:
    partyMemberCheck(var_0, baofu);
    bne(var_0, 0, label_1a);
    b(label_20);
  label_1a:
    bne(var_0, 1, label_20);
    ref_1b = spriteLoad(sprite_13);
    wait(ref_1b);
    unitSpawn(baofu, sprite_13, 1274, 0, -1227, east, none);
    unitTriggerSet(baofu, B_PAO, 255, 1);
    b(label_20);
  label_20:
    partyMemberCheck(var_0, nanjo);
    bne(var_0, 0, label_23);
    b(label_29);
  label_23:
    bne(var_0, 1, label_29);
    ref_24 = spriteLoad(sprite_1f);
    wait(ref_24);
    unitSpawn(nanjo, sprite_1f, 1057, 0, -1380, east, none);
    unitTriggerSet(nanjo, B_NANJ, 255, 1);
    b(label_29);
  label_29:
    partyMemberCheck(var_0, elly);
    bne(var_0, 0, label_2c);
    b(label_32);
  label_2c:
    bne(var_0, 1, label_32);
    ref_2d = spriteLoad(sprite_23);
    wait(ref_2d);
    unitSpawn(elly, sprite_23, 562, 0, -1161, west, none);
    unitTriggerSet(elly, B_ERI, 255, 1);
    b(label_32);
  label_32:
    partyMemberCheck(var_0, tatsuya);
    bne(var_0, 0, label_35);
    b(label_3b);
  label_35:
    bne(var_0, 1, label_3b);
    ref_36 = spriteLoad(sprite_18);
    wait(ref_36);
    unitSpawn(tatsuya, sprite_18, 700, 0, -1458, south, none);
    unitTriggerSet(tatsuya, B_TATU, 255, 1);
    b(label_3b);
  label_3b:
    ref_3b = spriteLoad(sprite_a8);
    wait(ref_3b);
    unitSpawn3d(shopkeeper, sprite_a8, 898, -80, -790, east, none);
    unitFace(shopkeeper, north);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    unknownVar1(var_0);
    bne(var_0, 6145, label_46);
    dngRoomSet(291);
    dngRoomDraw();
    cameraSetNorth(south);
    b(label_50);
  label_46:
    bne(var_0, 6162, label_4b);
    dngRoomSet(292);
    dngRoomDraw();
    cameraSetNorth(north);
    b(label_50);
  label_4b:
    ref_4b = dialogAlloc();
    ref_4c = msgShow(msg_0);
/***************************************
Cannot locate the hit ID.
[wait][clear]
***************************************/
    wait(ref_4c);
    dialogFree(ref_4b);
    b(label_50);
  label_50:
    cameraSet(southwest, 901, 0, -1486);
    ref_51 = spriteLoad(sprite_0);
    wait(ref_51);
    ref_53 = spriteLoad(sprite_2);
    wait(ref_53);
    playerInit(south);
    controlDisable();
    envTriggerSet(SHOPBOX, 56, 1, line, coll_6);
    envTriggerSet(SHOPBOX, 56, 1, line, coll_7);
    envTriggerSet(SHOPBOX, 56, 1, line, coll_8);
    objCollisionLink(collision_1, coll_4, obj_2);
    objVisible(obj_2, false);
    objVisible(obj_3, false);
    objVisible(obj_4, false);
    objVisible(obj_5, false);
    objVisible(obj_6, false);
    objVisible(obj_7, false);
    objVisible(obj_8, false);
    objVisible(obj_9, false);
    objVisible(obj_a, false);
    objVisible(obj_b, false);
    objVisible(obj_c, false);
    objVisible(obj_d, false);
    objVisible(obj_e, false);
    objVisible(obj_f, false);
    objVisible(obj_10, false);
    objVisible(obj_11, false);
    objVisible(obj_12, false);
    objVisible(obj_13, false);
    objVisible(obj_14, false);
    objVisible(obj_15, false);
    objVisible(obj_16, false);
    objVisible(obj_17, false);
    objVisible(obj_18, false);
    objVisible(obj_19, false);
    objVisible(obj_1a, false);
    objVisible(obj_1b, false);
    objVisible(obj_1c, false);
    objVisible(obj_1d, false);
    objVisible(obj_1e, false);
    objVisible(obj_1f, false);
    objVisible(obj_20, false);
    objVisible(obj_21, false);
    objVisible(obj_22, false);
    objVisible(obj_23, false);
    objVisible(obj_24, false);
    objVisible(obj_25, false);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    unitIdleOnAll();
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}

function B_URARATI()
{
    controlDisable();
    unitFacePlayer(ulala);
    ref_89 = bustupLoad(bustup_1b);
    bustupWait(ref_89);
    ref_8b = bustupAlloc(ref_89, left, rgb(0,0,0));
    bustupFade(ref_8b, rgb(128,0,0), 30);
    ref_8d = dialogAlloc();
    ref_8e = msgShow(msg_1);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Selling items in a place like this...
[tab]But where does she get that
[tab]stuff from?
[wait][clear]
***************************************/
    unitAnimationPlay(ulala, animation_1d, 1);
    wait(ref_8e);
    unitAnimationPlay(ulala, animation_a, 1);
    dialogFree(ref_8d);
    ref_93 = bustupFade(ref_8b, rgb(0,0,0), 10);
    bustupWait(ref_93);
    bustupFree(ref_8b);
    unitRestoreFacing(ulala);
    controlEnable();
}

function B_KATUYYY()
{
    controlDisable();
    b(label_ab);
    unitFacePlayer(katsuya);
    ref_9c = bustupLoad(bustup_25);
    bustupWait(ref_9c);
    ref_9e = bustupAlloc(ref_9c, left, rgb(0,0,0));
    bustupFade(ref_9e, rgb(128,0,0), 30);
    ref_a0 = dialogAlloc();
    ref_a1 = msgShow(msg_2);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]W... What is this room? It feels
[tab]the same as Philemon’s dimension...
[tab]Is this another world, too...?
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_28, 1);
    wait(ref_a1);
    dialogFree(ref_a0);
    unitAnimationPlay(katsuya, animation_a, 1);
    ref_a6 = bustupFade(ref_9e, rgb(0,0,0), 10);
    bustupWait(ref_a6);
    bustupFree(ref_9e);
    unitRestoreFacing(katsuya);
    b(label_d7);
  label_ab:
    bitGet(var_0, MBIT_TRI_KOWAI01);
    bnz(var_0, label_c8);
    unitFacePlayer(katsuya);
    ref_ae = bustupLoad(bustup_21);
    bustupWait(ref_ae);
    ref_b0 = bustupAlloc(ref_ae, left, rgb(0,0,0));
    bustupFade(ref_b0, rgb(128,0,0), 30);
    ref_b2 = dialogAlloc();
    ref_b3 = msgShow(msg_3);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Places where an incident occurs have
[tab]a peculiar atmosphere. That’s why
[tab]eerie stories are based on those areas.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_2d, 1);
    wait(ref_b3);
    ref_b6 = bustupFade(ref_b0, rgb(0,0,0), 10);
    bustupWait(ref_b6);
    bustupFree(ref_b0);
    ref_b9 = bustupLoad(bustup_24);
    bustupWait(ref_b9);
    ref_bb = bustupAlloc(ref_b9, left, rgb(0,0,0));
    bustupFade(ref_bb, rgb(128,0,0), 30);
    ref_bd = msgShow(msg_4);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]There are even stories going around
[tab]about that bizarre murder case. Geez, even
[tab]if it’s a joke, I wish they’d stop it.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_6, 1);
    wait(ref_bd);
    dialogFree(ref_b2);
    unitAnimationPlay(katsuya, animation_a, 1);
    ref_c2 = bustupFade(ref_bb, rgb(0,0,0), 10);
    bustupWait(ref_c2);
    bustupFree(ref_bb);
    unitRestoreFacing(katsuya);
    bitSet(MBIT_TRI_KOWAI01);
    b(label_d7);
  label_c8:
    unitFacePlayer(katsuya);
    ref_c9 = bustupLoad(bustup_21);
    bustupWait(ref_c9);
    ref_cb = bustupAlloc(ref_c9, left, rgb(0,0,0));
    bustupFade(ref_cb, rgb(128,0,0), 30);
    ref_cd = dialogAlloc();
    ref_ce = msgShow(msg_5);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]The items are much more expensive than the
[tab]ones in the city... It’s unlike what you
[tab]would think a fairy would do.
[wait][clear]
***************************************/
    unitAnimationPlay(katsuya, animation_1a, 1);
    wait(ref_ce);
    dialogFree(ref_cd);
    unitAnimationPlay(katsuya, animation_a, 1);
    ref_d3 = bustupFade(ref_cb, rgb(0,0,0), 10);
    bustupWait(ref_d3);
    bustupFree(ref_cb);
    unitRestoreFacing(katsuya);
  label_d7:
    controlEnable();
}

function B_PAO()
{
    controlDisable();
    bitGet(var_0, MBIT_TRI_ISATU);
    bnz(var_0, label_ec);
    unitFacePlayer(baofu);
    ref_dd = bustupLoad(bustup_2d);
    bustupWait(ref_dd);
    ref_df = bustupAlloc(ref_dd, left, rgb(0,0,0));
    bustupFade(ref_df, rgb(128,0,0), 30);
    ref_e1 = dialogAlloc();
    ref_e2 = msgShow(msg_6);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]I don’t know much about this room.
[tab]That flying bug is the owner, right?
[tab]Why don’t you ask her?
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_e2);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_e1);
    ref_e7 = bustupFade(ref_df, rgb(0,0,0), 10);
    bustupWait(ref_e7);
    bustupFree(ref_df);
    unitRestoreFacing(baofu);
    b(label_111);
  label_ec:
    bitGet(var_0, MBIT_TRI_KOWAI02);
    bnz(var_0, label_102);
    unitFacePlayer(baofu);
    ref_ef = bustupLoad(bustup_2d);
    bustupWait(ref_ef);
    ref_f1 = bustupAlloc(ref_ef, left, rgb(0,0,0));
    bustupFade(ref_f1, rgb(128,0,0), 30);
    ref_f3 = dialogAlloc();
    ref_f4 = msgShow(msg_7);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]A money-grubbing fairy and talkative
[tab]demons... After all of this and all those
[tab]ghost stories, they seem like lies, huh?
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_f4);
    ref_f7 = msgShow(msg_8);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]But there was one story that’s
[tab]really scary. Even I couldn’t sleep.
[tab]I’ll tell ya when I feel like it.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_2d, 1);
    wait(ref_f7);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_f3);
    ref_fc = bustupFade(ref_f1, rgb(0,0,0), 10);
    bustupWait(ref_fc);
    bustupFree(ref_f1);
    unitRestoreFacing(baofu);
    bitSet(MBIT_TRI_KOWAI02);
    b(label_111);
  label_102:
    unitFacePlayer(baofu);
    ref_103 = bustupLoad(bustup_2d);
    bustupWait(ref_103);
    ref_105 = bustupAlloc(ref_103, left, rgb(0,0,0));
    bustupFade(ref_105, rgb(128,0,0), 30);
    ref_107 = dialogAlloc();
    ref_108 = msgShow(msg_9);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Is that fairy in cahoots with Satomi
[tab]Tadashi? That background music may even
[tab]become a hit song soon.
[wait][clear]
***************************************/
    unitAnimationPlay(baofu, animation_1a, 1);
    wait(ref_108);
    unitAnimationPlay(baofu, animation_a, 1);
    dialogFree(ref_107);
    ref_10d = bustupFade(ref_105, rgb(0,0,0), 10);
    bustupWait(ref_10d);
    bustupFree(ref_105);
    unitRestoreFacing(baofu);
  label_111:
    controlEnable();
}

function B_NANJ()
{
    controlDisable();
    bitGet(var_0, MBIT_TRI_ISATU);
    bnz(var_0, label_124);
    ref_116 = bustupLoad(bustup_36);
    bustupWait(ref_116);
    ref_118 = bustupAlloc(ref_116, left, rgb(0,0,0));
    bustupFade(ref_118, rgb(128,0,0), 30);
    ref_11a = dialogAlloc();
    ref_11b = msgShow(msg_10);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]...Her again... How does she prepare
[tab]a fountain everywhere we go?
[tab]She has much more mobility than us...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_6, 1);
    wait(ref_11b);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_11a);
    ref_120 = bustupFade(ref_118, rgb(0,0,0), 10);
    bustupWait(ref_120);
    bustupFree(ref_118);
    b(label_133);
  label_124:
    unitFacePlayer(nanjo);
    ref_125 = bustupLoad(bustup_36);
    bustupWait(ref_125);
    ref_127 = bustupAlloc(ref_125, left, rgb(0,0,0));
    bustupFade(ref_127, rgb(128,0,0), 30);
    ref_129 = dialogAlloc();
    ref_12a = msgShow(msg_11);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]Absurd fees and expensive items...
[tab]They say that greediness knows no
[tab]limits, but hers is truly boundless...
[wait][clear]
***************************************/
    unitAnimationPlay(nanjo, animation_2d, 1);
    wait(ref_12a);
    unitAnimationPlay(nanjo, animation_a, 1);
    dialogFree(ref_129);
    ref_12f = bustupFade(ref_127, rgb(0,0,0), 10);
    bustupWait(ref_12f);
    bustupFree(ref_127);
    unitRestoreFacing(nanjo);
  label_133:
    controlEnable();
}

function B_ERI()
{
    controlDisable();
    bitGet(var_0, MBIT_TRI_ISATU);
    bnz(var_0, label_14b);
    unitFacePlayer(elly);
    ref_139 = bustupLoad(bustup_3d);
    bustupWait(ref_139);
    ref_13b = bustupAlloc(ref_139, left, rgb(0,0,0));
    bustupFade(ref_13b, rgb(128,0,0), 30);
    ref_13d = dialogAlloc();
    ref_13e = msgShow(msg_12);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Don’t be fooled by her cute looks.
[tab]She’s an unbelievable capitalist.

***************************************/
    unitAnimationPlay(elly, animation_2d, 1);
    wait(ref_13e);
    ref_141 = msgShow(msg_13);
/***************************************
[tab]I never thought I’d meet her again...
[wait][clear]
***************************************/
    unitLookAtUnit(elly, shopkeeper);
    wait(ref_141);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_13d);
    ref_146 = bustupFade(ref_13b, rgb(0,0,0), 10);
    bustupWait(ref_146);
    bustupFree(ref_13b);
    unitRestoreFacing(elly);
    b(label_15a);
  label_14b:
    unitFacePlayer(elly);
    ref_14c = bustupLoad(bustup_3f);
    bustupWait(ref_14c);
    ref_14e = bustupAlloc(ref_14c, left, rgb(0,0,0));
    bustupFade(ref_14e, rgb(128,0,0), 30);
    ref_150 = dialogAlloc();
    ref_151 = msgShow(msg_14);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]I’ve been wondering from before... 
[tab]What is the "recovery market" Trish keeps
[tab]speaking of? The fee never stops rising...
[wait][clear]
***************************************/
    unitAnimationPlay(elly, animation_2f, 1);
    wait(ref_151);
    unitAnimationPlay(elly, animation_a, 1);
    dialogFree(ref_150);
    ref_156 = bustupFade(ref_14e, rgb(0,0,0), 10);
    bustupWait(ref_156);
    bustupFree(ref_14e);
    unitRestoreFacing(elly);
  label_15a:
    controlEnable();
}

function B_TATU()
{
    controlDisable();
    unitFacePlayer(tatsuya);
    ref_15e = bustupLoad(bustup_10);
    bustupWait(ref_15e);
    ref_160 = bustupAlloc(ref_15e, left, rgb(0,0,0));
    bustupFade(ref_160, rgb(128,0,0), 30);
    ref_162 = dialogAlloc();
    ref_163 = msgShow(msg_15);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]Medicine at ¥500 means that she’s
[tab]selling items at 5 times the price
[tab]of Satomi Tadashi...
[wait][clear]
***************************************/
    unitAnimationPlay(tatsuya, animation_6, 1);
    wait(ref_163);
    dialogFree(ref_162);
    unitAnimationPlay(tatsuya, animation_a, 1);
    ref_168 = bustupFade(ref_160, rgb(0,0,0), 10);
    bustupWait(ref_168);
    bustupFree(ref_160);
    unitRestoreFacing(tatsuya);
    controlEnable();
}

function SHOPBOX()
{
    controlDisable();
    ref_16f = shopOverlayInit();
    unitFacePlayer(shopkeeper);
    bitGet(var_0, LBIT_0000);
    bnz(var_0, label_19d);
    ref_173 = bustupLoad(bustup_e4);
    bustupWait(ref_173);
    ref_175 = bustupAlloc(ref_173, right, rgb(0,0,0));
    bustupFade(ref_175, rgb(128,0,0), 30);
    ref_177 = dialogAlloc();
    ref_178 = msgShow(msg_16);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Hi...!
[tab]Welcome to Trish’s Item Shop♥...
[tab](giggle)...
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_6, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_7, 1);
    sync();
    wait(ref_178);
    ref_185 = msgShow(msg_17);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]I’ve started to sell items, too.
[tab]I can’t profit from just recovery.
[tab]I’m aiming for a nationwide monopoly!
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_6, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_7, 1);
    sync();
    wait(ref_185);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_177);
    ref_194 = bustupFade(ref_175, rgb(0,0,0), 10);
    bustupWait(ref_194);
    bustupFree(ref_175);
    bitSet(MBIT_TRI_ISATU);
    bitSet(LBIT_0000);
    wait(ref_16f);
    shopInventory(9, shopInventory_24);
    shopRate(500);
    b(label_1b7);
  label_19d:
    ref_19d = bustupLoad(bustup_e4);
    bustupWait(ref_19d);
    ref_19f = bustupAlloc(ref_19d, right, rgb(0,0,0));
    bustupFade(ref_19f, rgb(128,0,0), 30);
    ref_1a1 = dialogAlloc();
    ref_1a2 = msgShow(msg_18);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]This world is about give and take!
[tab]You can recover from anything, depending
[tab]on your wallet! ...What do you want?[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_7, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_6, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_1a2);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_1a1);
    ref_1b1 = bustupFade(ref_19f, rgb(0,0,0), 10);
    bustupWait(ref_1b1);
    bustupFree(ref_19f);
    wait(ref_16f);
    shopInventory(9, shopInventory_24);
    shopRate(500);
  label_1b7:
    choiceSetResult(5);
    op_105(3);
    ref_1b9 = bustupLoad(bustup_e4);
    bustupWait(ref_1b9);
    ref_1bb = bustupAlloc(ref_1b9, right, rgb(0,0,0));
    bustupFade(ref_1bb, rgb(128,0,0), 30);
    ref_1bd = dialogAlloc();
    ref_1be = msgShow(msg_19);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]What’ll it be?
[choice(7)]Heal
Buy items
Sell items
[if_all(EBIT_SINARIOFF)]Check items
Talk to Trish
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    wait(ref_1be);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_1c6);
    li(var_5, 0);
    b(label_1ee);
  label_1c6:
    bne(var_0, 1, label_1c9);
    li(var_5, 1);
    b(label_1ee);
  label_1c9:
    bne(var_0, 2, label_1d5);
    choiceSetResult(0);
    op_105(0);
    ref_1cc = msgShow(msg_20);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]What will you sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear]
***************************************/
    wait(ref_1cc);
    choiceGetResult(var_5);
    bne(var_5, 0, label_1d2);
    li(var_5, 1000);
    b(label_1d4);
  label_1d2:
    add(var_5, var_5, 20);
    b(label_1d4);
  label_1d4:
    b(label_1ee);
  label_1d5:
    bne(var_0, 3, label_1d8);
    li(var_5, 3);
    b(label_1ee);
  label_1d8:
    bne(var_0, 4, label_1e8);
    choiceSetResult(2);
    op_105(2);
    ref_1db = msgShow(msg_21);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Yeah, whaddaya want?
[choice(2)]Make small talk
Ask about healing spring
[end_choice][clear]
***************************************/
    wait(ref_1db);
    choiceGetResult(var_0);
    bne(var_0, 0, label_1e1);
    li(var_5, 4);
    b(label_1e7);
  label_1e1:
    bne(var_0, 1, label_1e4);
    li(var_5, 2000);
    b(label_1e7);
  label_1e4:
    bne(var_0, 2, label_1e7);
    li(var_5, 1000);
    b(label_1e7);
  label_1e7:
    b(label_1ee);
  label_1e8:
    bne(var_0, 5, label_1eb);
    li(var_5, 5);
    b(label_1ee);
  label_1eb:
    bne(var_0, 6, label_1ee);
    li(var_5, 6);
    b(label_1ee);
  label_1ee:
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_1bd);
    ref_1f0 = bustupFade(ref_1bb, rgb(0,0,0), 10);
    bustupWait(ref_1f0);
    bustupFree(ref_1bb);
    ref_1f3 = shopOpen(20);
    wait(ref_1f3);
}

function HA_SHOP_RESTART_0()
{
    choiceSetResult(5);
    op_105(3);
    ref_1f8 = bustupLoad(bustup_e4);
    bustupWait(ref_1f8);
    ref_1fa = bustupAlloc(ref_1f8, right, rgb(0,0,0));
    bustupFade(ref_1fa, rgb(128,0,0), 30);
    ref_1fc = dialogAlloc();
    ref_1fd = msgShow(msg_22);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Anything else?
[tab]Say anything♥...
[choice(7)]Heal
Buy items
Sell items
[if_all(EBIT_SINARIOFF)]Check items
Talk to Trish
Never mind
Leave
[end_choice][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_b, 1);
    wait(ref_1fd);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_205);
    li(var_5, 0);
    b(label_22d);
  label_205:
    bne(var_0, 1, label_208);
    li(var_5, 1);
    b(label_22d);
  label_208:
    bne(var_0, 2, label_214);
    choiceSetResult(0);
    op_105(0);
    ref_20b = msgShow(msg_23);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]What will you sell?
[choice(7)][dbl_tab][if_all(EBIT_SINARIOFF)]Hidden items
[dbl_tab]Sell items
[dbl_tab]Sell weapons
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell helmets
[dbl_tab]Sell armor
[dbl_tab][if_all(EBIT_SINARIOFF)]Sell leggings
[dbl_tab]Sell accessories
[end_choice][clear]
***************************************/
    wait(ref_20b);
    choiceGetResult(var_5);
    bne(var_5, 0, label_211);
    li(var_5, 1000);
    b(label_213);
  label_211:
    add(var_5, var_5, 20);
    b(label_213);
  label_213:
    b(label_22d);
  label_214:
    bne(var_0, 3, label_217);
    li(var_5, 3);
    b(label_22d);
  label_217:
    bne(var_0, 4, label_227);
    choiceSetResult(2);
    op_105(2);
    ref_21a = msgShow(msg_24);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Yeah, whaddaya want?
[choice(2)]Make small talk
Ask about healing spring
[end_choice][clear]
***************************************/
    wait(ref_21a);
    choiceGetResult(var_0);
    bne(var_0, 0, label_220);
    li(var_5, 4);
    b(label_226);
  label_220:
    bne(var_0, 1, label_223);
    li(var_5, 2000);
    b(label_226);
  label_223:
    bne(var_0, 2, label_226);
    li(var_5, 1000);
    b(label_226);
  label_226:
    b(label_22d);
  label_227:
    bne(var_0, 5, label_22a);
    li(var_5, 5);
    b(label_22d);
  label_22a:
    bne(var_0, 6, label_22d);
    li(var_5, 6);
    b(label_22d);
  label_22d:
    unitAnimationPlay(shopkeeper, animation_0, 1);
    dialogFree(ref_1fc);
    ref_22f = bustupFade(ref_1fa, rgb(0,0,0), 10);
    bustupWait(ref_22f);
    bustupFree(ref_1fa);
}

function HA_SHOP_TALK_0()
{
    ref_233 = bustupLoad(bustup_e4);
    bustupWait(ref_233);
    ref_235 = bustupAlloc(ref_233, right, rgb(0,0,0));
    bustupFade(ref_235, rgb(128,0,0), 30);
    ref_237 = dialogAlloc();
    ref_238 = msgShow(msg_25);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]It’s dangerous outside the door!
[tab]One mistake means a lifetime of pain...
[tab]Don’t be a tightwad, recover![sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_7, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_6, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_238);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_237);
    ref_247 = bustupFade(ref_235, rgb(0,0,0), 10);
    bustupWait(ref_247);
    bustupFree(ref_235);
}

function HA_SHOP_HEAL_0()
{
    ref_24b = call(KAIFUKUSURUBEKI);
    wait(ref_24b);
    bitGet(var_1, LBIT_0000);
    bne(var_1, 0, label_263);
    ref_24f = bustupLoad(bustup_e4);
    bustupWait(ref_24f);
    ref_251 = bustupAlloc(ref_24f, right, rgb(0,0,0));
    bustupFade(ref_251, rgb(128,0,0), 30);
    ref_253 = dialogAlloc();
    ref_254 = msgShow(msg_26);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Let me make it all♪...
[tab]Hey, everyone’s fine!
[tab]You can’t recover like this...!![sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_c, 1);
    unitWait(shopkeeper);
    unitAnimationHold(shopkeeper, animation_9, -1);
    sync();
    wait(ref_254);
    unitAnimationStop(shopkeeper);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_253);
    ref_25e = bustupFade(ref_251, rgb(0,0,0), 10);
    bustupWait(ref_25e);
    bustupFree(ref_251);
    b(label_304);
    b(label_2ae);
  label_263:
    bne(var_1, 1, label_2ae);
    ref_264 = call(GAKUDASI);
    wait(ref_264);
    msgVar_Number(msgvar_5, var_5);
    ref_267 = bustupLoad(bustup_e4);
    bustupWait(ref_267);
    ref_269 = bustupAlloc(ref_267, right, rgb(0,0,0));
    bustupFade(ref_269, rgb(128,0,0), 30);
    ref_26b = dialogAlloc();
    ref_26c = msgShow(msg_27);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]OKAY!! The state that the
[tab]recovery market is in right now...
[tab]The fee is ¥[var(msg_var_5)]!
[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_7, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_6, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    sync();
    wait(ref_26c);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_26b);
    ref_27b = bustupFade(ref_269, rgb(0,0,0), 10);
    bustupWait(ref_27b);
    bustupFree(ref_269);
    choiceSetResult(1);
    op_105(1);
    ref_280 = bustupLoad(bustup_1);
    bustupWait(ref_280);
    ref_282 = bustupAlloc(ref_280, center, rgb(0,0,0));
    bustupFade(ref_282, rgb(128,0,0), 30);
    ref_284 = dialogChoiceAlloc();
    shopCurrencyType(8, -110, 150);
    shopCurrencyDisplay(13, 150, false);
    ref_287 = msgShow(msg_28);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]You’ll heal, right?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_287);
    dialogFree(ref_284);
    ref_28a = bustupFade(ref_282, rgb(0,0,0), 10);
    bustupWait(ref_28a);
    bustupFree(ref_282);
    choiceGetResult(var_0);
    bne(var_0, 0, label_291);
    b(label_2ae);
    b(label_2ad);
  label_291:
    bne(var_0, 1, label_2ad);
    ref_292 = bustupLoad(bustup_e4);
    bustupWait(ref_292);
    ref_294 = bustupAlloc(ref_292, right, rgb(0,0,0));
    bustupFade(ref_294, rgb(128,0,0), 30);
    ref_296 = dialogAlloc();
    ref_297 = msgShow(msg_29);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Ch... Trying to grin and bear it...
[tab]It’s not my fault if you die...
[tab]Actually, DIE, you cheapskate![sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_7, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_1, 1);
    delayClear();
    delayWait(6);
    unitAnimationPlay(shopkeeper, animation_2, 1);
    sync();
    wait(ref_297);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    shopCurrencyDisplay(-110, 150, true);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_296);
    ref_2a8 = bustupFade(ref_294, rgb(0,0,0), 10);
    bustupWait(ref_2a8);
    bustupFree(ref_294);
    b(label_304);
    b(label_2ad);
  label_2ad:
    b(label_2ae);
  label_2ae:
    partyMoneyGet(var_6);
    sub(var_7, var_6, var_5);
    boutrange(var_7, -99999999, -1, label_2b3);
    b(label_2f3);
    b(label_2b9);
  label_2b3:
    li(var_6, 0);
    sub(var_7, var_6, var_5);
    partyMoneyAdd(var_7);
    ref_2b6 = call(KAIFUKUMESS);
    wait(ref_2b6);
    b(label_2b9);
  label_2b9:
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), add);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_3, 127);
    partyHealthRestore(maya);
    partySPRestore(maya);
    partyStatusClear(maya);
    partyMemberCheck(var_3, ulala);
    bez(var_3, label_2c8);
    partyHealthRestore(ulala);
    partySPRestore(ulala);
    partyStatusClear(ulala);
  label_2c8:
    partyMemberCheck(var_3, katsuya);
    bez(var_3, label_2cd);
    partyHealthRestore(katsuya);
    partySPRestore(katsuya);
    partyStatusClear(katsuya);
  label_2cd:
    partyMemberCheck(var_3, baofu);
    bez(var_3, label_2d2);
    partyHealthRestore(baofu);
    partySPRestore(baofu);
    partyStatusClear(baofu);
  label_2d2:
    partyMemberCheck(var_3, nanjo);
    bez(var_3, label_2d7);
    partyHealthRestore(nanjo);
    partySPRestore(nanjo);
    partyStatusClear(nanjo);
  label_2d7:
    partyMemberCheck(var_3, elly);
    bez(var_3, label_2dc);
    partyHealthRestore(elly);
    partySPRestore(elly);
    partyStatusClear(elly);
  label_2dc:
    partyMemberCheck(var_3, tatsuya);
    bez(var_3, label_2e1);
    partyHealthRestore(tatsuya);
    partySPRestore(tatsuya);
    partyStatusClear(tatsuya);
  label_2e1:
    screenFade(160, 120, rgb(255,255,255), rgb(255,255,255), add);
    screenFadeInner(rgb(0,0,0), 8, true);
    screenFadeOuter(rgb(0,0,0), 8, true);
    screenEffectUnknown();
    delayClear();
    delayWait(40);
    ref_2e7 = bustupLoad(bustup_1);
    bustupWait(ref_2e7);
    ref_2e9 = bustupAlloc(ref_2e7, center, rgb(0,0,0));
    bustupFade(ref_2e9, rgb(128,0,0), 30);
    ref_2eb = dialogAlloc();
    ref_2ec = msgShow(msg_30);
/***************************************
[color(green)]Maya’s party recovered.[color(white)][wait][clear]
***************************************/
    wait(ref_2ec);
    dialogFree(ref_2eb);
    ref_2ef = bustupFade(ref_2e9, rgb(0,0,0), 10);
    bustupWait(ref_2ef);
    bustupFree(ref_2e9);
    b(label_304);
  label_2f3:
    ref_2f3 = bustupLoad(bustup_e4);
    bustupWait(ref_2f3);
    ref_2f5 = bustupAlloc(ref_2f3, right, rgb(0,0,0));
    bustupFade(ref_2f5, rgb(128,0,0), 30);
    ref_2f7 = dialogAlloc();
    ref_2f8 = msgShow(msg_31);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Alright, I’ll make it all♪...
[tab]Hey, you don’t have enough money!
[tab]Come back when you get some!![sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_c, 1);
    unitWait(shopkeeper);
    unitAnimationPlay(shopkeeper, animation_6, 1);
    sync();
    wait(ref_2f8);
    shopCurrencyDisplay(-110, 150, true);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_2f7);
    ref_301 = bustupFade(ref_2f5, rgb(0,0,0), 10);
    bustupWait(ref_301);
    bustupFree(ref_2f5);
  label_304:
}

function GAKUDASI()
{
    li(var_5, 30000);
    bitGet(var_0, MBIT_TRI_HENKEN);
    bne(var_0, 0, label_309);
    b(label_312);
  label_309:
    bne(var_0, 1, label_312);
    bitGet(var_0, MBIT_TRI_NESAGARI);
    bne(var_0, 0, label_30e);
    add(var_5, var_5, var_5);
    b(label_311);
  label_30e:
    bne(var_0, 1, label_311);
    div(var_5, var_5, 2);
    b(label_311);
  label_311:
    b(label_312);
  label_312:
    shopInventory(3, shopInventory_3a2);
}

function KAIFUKUMESS()
{
    ref_314 = bustupLoad(bustup_e4);
    bustupWait(ref_314);
    ref_316 = bustupAlloc(ref_314, right, rgb(0,0,0));
    bustupFade(ref_316, rgb(128,0,0), 30);
    ref_318 = dialogAlloc();
    ref_319 = msgShow(msg_32);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]OKAY, here I goooo!
[tab]I’ll make it all better...!
[tab]Pirorororo♪...[sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_6, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(10);
    unitAnimationPlay(shopkeeper, animation_c, 1);
    unitWait(shopkeeper);
    sync();
    wait(ref_319);
    shopCurrencyDisplay(-110, 150, true);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    dialogFree(ref_318);
    ref_327 = bustupFade(ref_316, rgb(0,0,0), 10);
    bustupWait(ref_327);
    bustupFree(ref_316);
}

function KAIFUKUSURUBEKI()
{
    partyStatusHas(var_0, maya, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, maya, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, maya, maxHealth);
    partyInfoGet(var_5, maya, health);
    beq(var_4, var_5, label_333);
    b(label_38d);
  label_333:
    partyInfoGet(var_4, maya, maxSP);
    partyInfoGet(var_5, maya, sp);
    beq(var_4, var_5, label_337);
    b(label_38d);
  label_337:
    partyMemberCheck(var_4, ulala);
    bez(var_4, label_345);
    partyStatusHas(var_0, ulala, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, ulala, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, ulala, maxHealth);
    partyInfoGet(var_5, ulala, health);
    beq(var_4, var_5, label_341);
    b(label_38d);
  label_341:
    partyInfoGet(var_4, ulala, maxSP);
    partyInfoGet(var_5, ulala, sp);
    beq(var_4, var_5, label_345);
    b(label_38d);
  label_345:
    partyMemberCheck(var_4, katsuya);
    bez(var_4, label_353);
    partyStatusHas(var_0, katsuya, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, katsuya, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, katsuya, maxHealth);
    partyInfoGet(var_5, katsuya, health);
    beq(var_4, var_5, label_34f);
    b(label_38d);
  label_34f:
    partyInfoGet(var_4, katsuya, maxSP);
    partyInfoGet(var_5, katsuya, sp);
    beq(var_4, var_5, label_353);
    b(label_38d);
  label_353:
    partyMemberCheck(var_4, baofu);
    bez(var_4, label_361);
    partyStatusHas(var_0, baofu, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, baofu, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, baofu, maxHealth);
    partyInfoGet(var_5, baofu, health);
    beq(var_4, var_5, label_35d);
    b(label_38d);
  label_35d:
    partyInfoGet(var_4, baofu, maxSP);
    partyInfoGet(var_5, baofu, sp);
    beq(var_4, var_5, label_361);
    b(label_38d);
  label_361:
    partyMemberCheck(var_4, nanjo);
    bez(var_4, label_36f);
    partyStatusHas(var_0, nanjo, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, nanjo, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, nanjo, maxHealth);
    partyInfoGet(var_5, nanjo, health);
    beq(var_4, var_5, label_36b);
    b(label_38d);
  label_36b:
    partyInfoGet(var_4, nanjo, maxSP);
    partyInfoGet(var_5, nanjo, sp);
    beq(var_4, var_5, label_36f);
    b(label_38d);
  label_36f:
    partyMemberCheck(var_4, elly);
    bez(var_4, label_37d);
    partyStatusHas(var_0, elly, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, elly, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, elly, maxHealth);
    partyInfoGet(var_5, elly, health);
    beq(var_4, var_5, label_379);
    b(label_38d);
  label_379:
    partyInfoGet(var_4, elly, maxSP);
    partyInfoGet(var_5, elly, sp);
    beq(var_4, var_5, label_37d);
    b(label_38d);
  label_37d:
    partyMemberCheck(var_4, tatsuya);
    bez(var_4, label_38b);
    partyStatusHas(var_0, tatsuya, poison);
    bnz(var_0, label_38d);
    partyStatusHas(var_0, tatsuya, possesion);
    bnz(var_0, label_38d);
    partyInfoGet(var_4, tatsuya, maxHealth);
    partyInfoGet(var_5, tatsuya, health);
    beq(var_4, var_5, label_387);
    b(label_38d);
  label_387:
    partyInfoGet(var_4, tatsuya, maxSP);
    partyInfoGet(var_5, tatsuya, sp);
    beq(var_4, var_5, label_38b);
    b(label_38d);
  label_38b:
    bitClear(LBIT_0000);
    b(label_38f);
  label_38d:
    bitSet(LBIT_0000);
    b(label_38f);
  label_38f:
}

function HA_SHOP_END_0()
{
    ref_390 = bustupLoad(bustup_e4);
    bustupWait(ref_390);
    ref_392 = bustupAlloc(ref_390, right, rgb(0,0,0));
    bustupFade(ref_392, rgb(128,0,0), 30);
    ref_394 = dialogAlloc();
    ref_395 = msgShow(msg_33);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Come again!
[tab]I’ll be waiting...
[tab]Bye-bye![sync][wait][clear]
***************************************/
    unitAnimationPlay(shopkeeper, animation_7, 1);
    delayClear();
    delayWait(30);
    unitAnimationPlay(shopkeeper, animation_0, 1);
    delayClear();
    delayWait(20);
    unitAnimationPlay(shopkeeper, animation_7, 1);
    sync();
    wait(ref_395);
    unitAnimationPlay(shopkeeper, animation_b, 1);
    shopOverlayInit();
    dialogFree(ref_394);
    ref_3a2 = bustupFade(ref_392, rgb(0,0,0), 10);
    bustupWait(ref_3a2);
    bustupFree(ref_392);
    bitGet(var_0, MBIT_EXITBIT);
    bne(var_0, 0, label_3aa);
    unitRestoreFacing(shopkeeper);
    controlEnable();
    b(label_3ad);
  label_3aa:
    bne(var_0, 1, label_3ad);
    call(EXITBOX);
    b(label_3ad);
  label_3ad:
}

function HA_SHOP_EXPLAIN_0()
{
    choiceSetResult(3);
    op_105(7);
    ref_3b0 = dialogChoiceAlloc();
    ref_3b1 = msgShow(msg_34);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]What do you want to know?
[choice(4)]Ask about healing
Ask about buying
Ask about selling
Nothing
[end_choice][clear]
***************************************/
    wait(ref_3b1);
    dialogFree(ref_3b0);
    choiceGetResult(var_0);
    bne(var_0, 0, label_3bb);
    ref_3b6 = dialogAlloc();
    ref_3b7 = msgShow(msg_35);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Okay! Healing, right?
[tab]Choose "Heal" here and I’ll restore your HP and
[tab]SP, plus cure any status ailments like poison.
[wait][clear][color(yellow)]Trish[color(white)]
[tab]My fees depend on the current market value for
[tab]healing, but I do cure everyone, so you might
[tab]save a little in the long run.
[wait][clear]
***************************************/
    wait(ref_3b7);
    dialogFree(ref_3b6);
    b(label_3c9);
  label_3bb:
    bne(var_0, 1, label_3c1);
    ref_3bc = dialogAlloc();
    ref_3bd = msgShow(msg_36);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Okay! Buying, right? You can buy 
[tab]equipment and consumable items. There are 
[tab]items where you can only buy a certain amount.
[wait][clear]
***************************************/
    wait(ref_3bd);
    dialogFree(ref_3bc);
    b(label_3c9);
  label_3c1:
    bne(var_0, 2, label_3c7);
    ref_3c2 = dialogAlloc();
    ref_3c3 = msgShow(msg_37);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Okay! Selling, right?
[tab]You can sell items that you own.
[tab]They are worth half the original price.
[wait][clear][color(green)]Sell[color(white)]
[tab]However, you cannot sell an item you are
[tab]currently equipped with. There are also
[tab]items that you cannot sell back.
[wait][clear]
***************************************/
    wait(ref_3c3);
    dialogFree(ref_3c2);
    b(label_3c9);
  label_3c7:
    bne(var_0, 3, label_3c9);
    b(label_3c9);
  label_3c9:
}

function EXITBOX()
{
    controlDisable();
    bitClear(MBIT_EXITBIT);
    unknownVar1(var_0);
    bne(var_0, 6145, label_3d0);
    dngLoad2(ex_sevens1-1);
    b(label_3d8);
  label_3d0:
    bne(var_0, 6162, label_3d3);
    dngLoad2(ex_sevens1-18);
    b(label_3d8);
  label_3d3:
    ref_3d3 = dialogAlloc();
    ref_3d4 = msgShow(msg_38);
/***************************************
Cannot locate the Hit ID.
[wait][clear]
***************************************/
    wait(ref_3d4);
    dialogFree(ref_3d3);
    b(label_3d8);
  label_3d8:
}

function warp1()
{
    call(EXITBOX);
}

function DECIDE_EAT()
{
    choiceSetResult(1);
    op_105(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_3df = bustupLoad(bustup_e4);
    bustupWait(ref_3df);
    ref_3e1 = bustupAlloc(ref_3df, left, rgb(0,0,0));
    bustupFade(ref_3e1, rgb(128,0,0), 30);
    ref_3e3 = dialogAlloc();
    choiceSetResult(1);
    op_105(1);
    ref_3e6 = msgShow(msg_39);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]That ice cream costs ¥[var(msg_var_0)]
[tab]Will you dine in?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_3e6);
    choiceGetResult(var_7);
    bne(var_7, 0, label_3ec);
    li(var_7, 1);
    b(label_3ef);
  label_3ec:
    bne(var_7, 1, label_3ef);
    li(var_7, 0);
    b(label_3ef);
  label_3ef:
    wait(ref_3e6);
    dialogFree(ref_3e3);
    ref_3f1 = bustupFade(ref_3e1, rgb(0,0,0), 10);
    bustupWait(ref_3f1);
    bustupFree(ref_3e1);
    li(var_5, 20);
}

function NOITEM()
{
    unitFacePlayer(shopkeeper);
    ref_3f7 = bustupLoad(bustup_e4);
    bustupWait(ref_3f7);
    ref_3f9 = bustupAlloc(ref_3f7, right, rgb(0,0,0));
    bustupFade(ref_3f9, rgb(128,0,0), 30);
    ref_3fb = dialogAlloc();
    ref_3fc = msgShow(msg_40);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]What!?
[tab]You’re not buying anything!?[wait][clear]
***************************************/
    wait(ref_3fc);
    dialogFree(ref_3fb);
    ref_3ff = bustupFade(ref_3f9, rgb(0,0,0), 10);
    bustupWait(ref_3ff);
    bustupFree(ref_3f9);
    li(var_5, 20);
}

function DECIDE_BUY()
{
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_406 = bustupLoad(bustup_e4);
    bustupWait(ref_406);
    ref_408 = bustupAlloc(ref_406, left, rgb(0,0,0));
    bustupFade(ref_408, rgb(128,0,0), 30);
    ref_40a = dialogAlloc();
    choiceSetResult(1);
    op_105(1);
    ref_40d = msgShow(msg_41);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]Well... Considering the current market...
[tab]It costs ¥[var(msg_var_0)], will you buy it?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_40d);
    choiceGetResult(var_7);
    bne(var_7, 0, label_414);
    sndMusicPlay(sound_3037, 127);
    li(var_7, 1);
    b(label_417);
  label_414:
    bne(var_7, 1, label_417);
    li(var_7, 0);
    b(label_417);
  label_417:
    wait(ref_40d);
    dialogFree(ref_40a);
    ref_419 = bustupFade(ref_408, rgb(0,0,0), 10);
    bustupWait(ref_419);
    bustupFree(ref_408);
    li(var_5, 20);
}

function DECIDE_SELL()
{
    choiceSetResult(1);
    op_105(1);
    msgVar_Number(msgvar_0, var_6);
    unitFacePlayer(shopkeeper);
    ref_422 = bustupLoad(bustup_e4);
    bustupWait(ref_422);
    ref_424 = bustupAlloc(ref_422, left, rgb(0,0,0));
    bustupFade(ref_424, rgb(128,0,0), 30);
    ref_426 = dialogAlloc();
    choiceSetResult(1);
    op_105(1);
    ref_429 = msgShow(msg_42);
/***************************************
[color(yellow)]Trish[color(white)]
[tab]I can buy that for ¥[var(msg_var_0)]
[tab]Will you sell it?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_429);
    choiceGetResult(var_7);
    bne(var_7, 0, label_430);
    sndMusicPlay(sound_3037, 127);
    li(var_7, 1);
    b(label_433);
  label_430:
    bne(var_7, 1, label_433);
    li(var_7, 0);
    b(label_433);
  label_433:
    wait(ref_429);
    ref_434 = bustupFade(ref_424, rgb(0,0,0), 10);
    bustupWait(ref_434);
    bustupFree(ref_424);
    dialogFree(ref_426);
    li(var_5, 20);
}
