
msg_0:
[color(green)]"Restart" has been 
added to the main menu.[color(white)]
[wait][clear][color(green)]When you select "Restart"
you can play the game from the beginning
while keeping all your analyze data and tarot cards.[color(white)]
[half_tab][half_tab][half_tab][half_tab][wait][clear][end]

msg_1:
[color(green)]Tracks have been added
to the Gallery[color(white)]
[wait][clear][color(green)]Select "Music"
Some tracks from the previous title
Persona 2 Innocent Sin have been added.[color(white)]
[half_tab][half_tab][half_tab][half_tab][wait][clear][end]
