
msg_0:
[color(yellow)]近所のおばさん[color(white)]
[tab]あら？[tab]舞耶ちゃんじゃない。[delay(10)]
[tab]今日もお仕事なの？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あんまり変な取材してちゃダメよー
[tab]最近、危ない事件が多いんだから、
[tab]巻き込まれたりしたら大変だからね。[wait][clear][end]

msg_1:
[color(yellow)]近所のおばさん[color(white)]
[tab]空の科学館が凄い事になったわねー！
[tab]何か詳しい事知らない？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]いきなり燃えたと思ったら、
[tab]レストランの飛行船が空を飛んじゃうし…
[tab]おばさん腰抜かしそうだわ。[wait][clear][end]

msg_2:
[color(yellow)]近所のおばさん[color(white)]
[tab]今朝テレビを見ていたら、空の科学館が
[tab]子供の火遊びで全焼した、なんて言ってたのよ。
[tab]それはいいけど飛行船は何で飛んだのかしら？[wait][clear][end]

msg_3:
[color(yellow)]近所のおばさん[color(white)]
[tab]私見ちゃったのよ、南条財閥の御曹司！
[tab]週刊誌で何度も見てるから間違い無いわ。
[tab]この街の高級ホテルに宿泊しているらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]お金持ちで、しかも結構いい男なのよぉ。
[tab]おばさんが、あと２０才若かったらねぇ…[delay(15)]
[tab]舞耶ちゃんどう？[tab]狙ってみたら。[wait][clear][end]

msg_4:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＪＯＫＥＲになった人が誘拐されてるって話よ。
[tab]人を呪わば穴二つって言葉があるけど本当よねぇ。
[tab]でも、警察は何をしてるのかしら。[wait][clear][end]

msg_5:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、ちょっと聞いた？
[tab]何でも今回の事件の重要な情報を握る人物が、
[tab]いるんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]もうすぐバーに現れるらしいって、
[tab]もう、街中その話で持ちきりよ。
[tab]私も見に行ってみようかしら。[wait][clear][end]

msg_6:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、ちょっと聞いた？
[tab]何でも今回の事件の重要な情報を握る人物が、
[tab]いるんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]しかも女性だっていうのよ！
[tab]びっくりよねぇ。
[tab]女スパイなのかしら？[wait][clear][end]

msg_7:
[color(yellow)]近所のおばさん[color(white)]
[tab]さっき保険会社の調査員って人に
[tab]いろいろ聞かれたんだけど、大変みたいねぇ。
[tab]事件、事件で支払いばっかりみたいよ。[wait][clear][end]

msg_8:
[color(yellow)]近所のおばさん[color(white)]
[tab]桐島[tab]英理子って人気モデルがいるんだけど、
[tab]最近見ないと思ったらストーカー事件に
[tab]巻き込まれてるらしいんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]怖いわねぇ。私も気をつけないと。
[tab]舞耶ちゃんも気をつけなさいよ。[wait][clear][end]

msg_9:
[color(yellow)]近所のおばさん[color(white)]
[tab]あら、舞耶ちゃんじゃない。
[tab]あなた、講演会にいった？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]お隣の奥さんも行ったらしくて、世界が変わった
[tab]って言うんだけど、あんまり強く勧められると
[tab]何だか怖くてね。[delay(15)]どうしようかしら？[wait][clear][end]

msg_10:
[color(yellow)]近所のおばさん[color(white)]
[tab]事件、事件で疲れたのかしらねぇ。
[tab]前にも同じような事があったような気がして
[tab]仕方ないのよ。[wait][clear][end]

msg_11:
[color(yellow)]近所のおばさん[color(white)]
[tab]今回の事件は新世塾っていう悪の組織が
[tab]やった事なんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]普通なら信じられないけど、これだけ事件が
[tab]起こった後だと信じるしかないわよねぇ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]しかも、新世塾はもっと恐ろしい事を
[tab]考えてるらしいのよ。
[tab]おばさん、どうしたらいいのかしら？[wait][clear][end]

msg_12:
[color(yellow)]近所のおばさん[color(white)]
[tab]自衛隊のトラックが走り回ってるかと思ったら、
[tab]どかーん、バンバンって凄い音でしょ？
[tab]もう戦争が始まったかと思ったわ！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]いったい何があったのかしら？
[tab]ほんと、物騒な世の中になっちゃったわ。[wait][clear][end]

msg_13:
[color(yellow)]近所のおばさん[color(white)]
[tab]あ、舞耶ちゃん！
[tab]さっき、凄い地震があったでしょ。
[tab]お互い無事で良かったわねぇ。[wait][clear][end]

msg_14:
[color(yellow)]近所のおばさん[color(white)]
[tab]ちょっと、ちょっと聞いた？
[tab]鳴海区の地下鉄工事、新世塾が遺跡を
[tab]発掘する為にやってたウソの工事なんだって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私、市議会選挙で地下鉄工事推進派に
[tab]票を入れてたのよ。
[tab]きっとあの議員も新世塾の仲間だったんだわ！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]ああ、もう何てことでしょ！
[tab]これからは絶対アイツには票を入れたりしないわ！[wait][clear][end]

msg_15:
[color(yellow)]近所のおばさん[color(white)]
[tab]ま、街が飛んじゃってもう何がなんだか…[delay(15)]
[tab]逃げようにも逃げる場所もないし、
[tab]もう私たち、お終いなのかしら…[wait][clear][end]

msg_16:
[color(yellow)]近所のおばさん[color(white)]
[tab]お、落ち着きなさいよ。
[tab]大丈夫、大丈夫。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]きっとみんな助かるからね。[delay(20)]
[tab]助かるのよね？
[tab]とにかく落ち着かなきゃ…[wait][clear][end]

msg_17:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ゾディアックの店内はひろーい迷路に
[tab]なってるんですって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]最近の若い人達はそういうのが好きなのかしら。
[tab]変わってるわねぇ。[wait][clear][end]

msg_18:
[color(yellow)]近所のおばさん[color(white)]
[tab]蓮華台に珠閒瑠城が出現したでしょ？
[tab]昔の話なんだけど、あの城の城主が悪い人でね、
[tab]呪いとかで何人も人を殺してたらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]それで、ついに天野[tab]舞姫っていうお姫様に
[tab]殺されちゃったんですって。
[tab]だからきっとお化けか何かが出るわよ。[wait][clear][end]

msg_19:
[color(yellow)]近所のおばさん[color(white)]
[tab]昔、珠閒瑠城の悪い城主を倒した侍の、
[tab][suou][tab]辰之進だけど、天野[tab]舞姫ってお姫様と
[tab]二人でやっつけたらしいのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]なんか舞耶ちゃんと名前が似てない？
[tab]あなたもいい人見つけないとね。
[tab]あっはっは。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]って笑ってる場合じゃないわ。
[tab]ほんと、不安で胸がつぶれそうよ。
[tab]おばさん、繊細だから。[wait][clear][end]

msg_20:
[color(yellow)]近所のおばさん[color(white)]
[tab]蓮華台に珠閒瑠城が出現したでしょ？
[tab]昔の話なんだけど、あの城の城主が悪い人でね、
[tab]呪いとかで何人も人を殺してたらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]それで、ついに[suou][tab]辰之進っていう侍に
[tab]殺されちゃったんですって。
[tab]だからきっとお化けか何かが出るわよ。[wait][clear][end]

msg_21:
[color(yellow)]近所のおばさん[color(white)]
[tab]昔、珠閒瑠城の悪い城主を倒した
[tab]天野[tab]舞姫には、[suou][tab]辰之進って言う
[tab]いい人がいて、二人で城主を倒したの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]やっぱり最後に勝つのは愛よね。
[tab]その点うちは…[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]ってなんかすぐ落ち込んじゃうわ。
[tab]ずっと、不安で胸がつぶれそうなのよ。
[tab]おばさん、繊細だから。[wait][clear][end]

msg_22:
[color(yellow)]近所のおばさん[color(white)]
[tab]青葉公園の花が話すって聞いたんだけど、
[tab]あれかしら、ロボットでも作ったのかしら？
[tab]一度見に行ってみないといけないわね。[wait][clear][end]

msg_23:
[color(yellow)]近所のおばさん[color(white)]
[tab]伝説だかなんだか知らないけど、
[tab]武器を作って稼いでる職人なんて、
[tab]ろくなもんじゃないわ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]武器があるから、危ない事件が起こるのよ。
[tab]ね、あなたもそう思うでしょ？[wait][clear][end]

msg_24:
[color(yellow)]近所のおばさん[color(white)]
[tab]あーもう、嫌な話聞いちゃったわ。
[tab]なにが？[tab]って一度しか言わないわよ。[delay(15)]
[tab]くだんよ。く[delay(20)]だ[delay(20)]ん。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]なんでもカス校の防空壕に現れたらしくて、
[tab]予言の犠牲者が続出しているらしいわ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あんまり、くだん、くだんって言っていると、
[tab]向こうから現れるかもしれないから、
[tab]あんまりくだんの話はしないほうがいいわよ。[wait][clear][end]

msg_25:
[color(yellow)]近所のおばさん[color(white)]
[tab]ムー大陸に呪いのタクシーが現れたって
[tab]言うんだけど、きっとわたしも被害者だわ！！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]いや、こないだね、買い物の帰りにムー大陸の
[tab]前でタクシーを捕まえたんだけど、いつもは
[tab]２２４０円なのに、２３４０円だったのよ！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]道もまったく同じだったんだから！
[tab]まったくひどいと思わない？
[tab]いつか絶対とっちめてやるわ。[wait][clear][end]

msg_26:
[color(yellow)]近所のおばさん[color(white)]
[tab]ギガ・マッチョで今度はお爺さんが
[tab]走り回ってるらしいのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]まったく、誰か注意してあげないとだめね。
[tab]店内はバーゲン以外の理由で走っちゃダメだって。
[tab]え、ちがう？[wait][clear][end]

msg_27:
[color(yellow)]近所のおばさん[color(white)]
[tab]鳴海区に怪人青マントが出たんですって？
[tab]ああ…あの辺りには出かけないほうがいいわね。
[tab]ほんと、物騒な事ばかりで嫌になっちゃうわ。[wait][clear][end]

msg_28:
[color(yellow)]近所のおばさん[color(white)]
[tab]鳴海区に怪人赤マントが出たんですって？
[tab]ああ…あの辺りには出かけないほうがいいわね。
[tab]ほんと、物騒な事ばかりで嫌になっちゃうわ。[wait][clear][end]

msg_29:
[color(yellow)]近所のおばさん[color(white)]
[tab]ちょっと聞いた？
[tab]ケームセンターに恐竜が出たんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]もう、私ったらびっくりしちゃって。
[tab]最近はどこも危ないわね。
[tab]安心して子供を遊ばせられないわ。[wait][clear][end]

msg_30:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＣＤショップのギガ・マッチョに、
[tab]１００キロババアなんて名乗るお婆さんがいて、
[tab]店内を走り回っているそうよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]元気なのはいいけれど、いい年して非常識にも
[tab]程があるわよね。
[tab]お店の中で走っちゃ迷惑だわ。[wait][clear][end]

msg_31:
[color(yellow)]近所のおばさん[color(white)]
[tab]テレビ局にお化けが出たんですって。
[tab]心霊番組なんかやってたから、
[tab]霊が引き寄せられたのね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あなたも霊関係の仕事をする時は、
[tab]ちゃんとお祓いしないと危ないわよ。[wait][clear][end]

msg_32:
[color(yellow)]近所のおばさん[color(white)]
[tab]ツチノコが出たとかで大騒ぎしてるけど、
[tab]私はカズノコの方がいいわ。
[tab]ツチノコなんて役に立たないもの。[wait][clear][end]

msg_33:
[color(yellow)]近所のおばさん[color(white)]
[tab]カス校でテケテケってお化けが出て、
[tab]結構な騒ぎになってるみたいじゃない？
[tab]どうしてこう問題ばかり起こすのかしら。[wait][clear][end]

msg_34:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも不思議なカードが当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私もさっそく応募しないと。
[tab]はがきの周りを赤く塗っておくと
[tab]当たり易いのよね。[wait][clear][end]

msg_35:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも便利な道具が当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私もさっそく応募しないと。
[tab]はがきの周りを赤く塗っておくと
[tab]当たり易いのよね。[wait][clear][end]

msg_36:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]素敵なアクセサリーが当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私もさっそく応募しないと。
[tab]はがきの周りを赤く塗っておくと
[tab]当たり易いのよね。[wait][clear][end]

msg_37:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも防具が当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]護身グッズって意外とするでしょう？
[tab]こういう懸賞っていいわよねぇ。
[tab]私もさっそく応募しないと。[wait][clear][end]

msg_38:
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも本物の武器が当たるとかで評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]ただでさえ物騒な世の中なのに、
[tab]なんて事するんでしょ。
[tab]ＰＴＡに訴えてやめさせなきゃ。[wait][clear][end]

msg_39:
[color(yellow)]近所のおばさん[color(white)]
[tab]別冊ミラクルの懸賞に応募すると
[tab]不思議なカードが当たるって聞いたんだけど、
[tab]不思議なカードって何かしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]おばさんはやっぱり使っても貯金の減らない
[tab]キャッシュカードがいいわね。
[tab]あはは。[wait][clear][end]

msg_40:
[color(yellow)]近所のおばさん[color(white)]
[tab]別冊ミラクルの懸賞に応募すると
[tab]特殊なアイテムが当たるって聞いたんだけど
[tab]やっぱり手品セットのことかしら？[wait][clear][end]

msg_41:
[color(yellow)]近所のおばさん[color(white)]
[tab]よく知らないんだけど、月刊バトルマスター
[tab]って雑誌、懸賞でアクセサリーが当たるって
[tab]評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]でも、雑誌の名前からして、アクセサリーって
[tab]あれでしょ、勲章とかなんとか。
[tab]私そういうの見るのも嫌だわ。[wait][clear][end]

msg_42:
[color(yellow)]近所のおばさん[color(white)]
[tab]よく知らないんだけど、月刊バトルマスター
[tab]って雑誌、懸賞で本物の防具が当たるって
[tab]評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]雑誌には興味が無いけど、
[tab]物騒なご時世だから防具は欲しいわね。
[tab]一冊買ってみようかしら。[wait][clear][end]

msg_43:
[color(yellow)]近所のおばさん[color(white)]
[tab]よく知らないんだけど、月刊バトルマスター
[tab]って雑誌、懸賞で本物の武器が当たるって
[tab]評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]男の子ってそういうの好きじゃない。
[tab]子を持つ親としては心配で心配で。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]危ないから、本屋さんに行って
[tab]販売停止にしてもらうつもりなの。[wait][clear][end]

msg_44:
[color(yellow)]近所のおばさん[color(white)]
[tab]ホテル・プレアデスにちょっと変わった感じの人が
[tab]いるんだけど、見たことあるかしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あのひと、何でも地図を沢山集めてるらしくて、
[tab]いろんな物を持ってるって評判なのよ。
[tab]でも家の見取り図とかあると嫌よね。[wait][clear][end]

msg_45:
[color(yellow)]近所のおばさん[color(white)]
[tab]平坂のサトミタダシにちょっと変わった感じの人が
[tab]いるんだけど、見たことあるかしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あのひと、何でも地図を沢山集めてるらしくて、
[tab]いろんな物を持ってるって評判なのよ。
[tab]秘密のシェルターの地図とか持ってないかしら。[wait][clear][end]

msg_46:
[color(yellow)]近所のおばさん[color(white)]
[tab]パパラチャっていう宝石屋が、
[tab]いつのまにかシーサイドモールに入ってるのよ！
[tab]私びっくりしちゃったわ。[wait][clear][end]

msg_47:
[color(yellow)]近所のおばさん[color(white)]
[tab]まあ、武器や防具もいいけどさ、
[tab]何も宝石屋が作る事ないじゃない？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]なんだか、イメージ悪いわぁ。
[tab]そういうことは、よそでやってほしいわ。[wait][clear][end]

msg_48:
[color(yellow)]近所のおばさん[color(white)]
[tab]良かったわねぇー[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]何が良かったって？
[tab]副島さんが無事だったのよ！
[tab]クレール・ド・リュンヌの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]どうなったのか気になってたんだけど、
[tab]なんとか脱出して青葉区で
[tab]お店を再開したんですって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]主人には悪いんだけど、
[tab]副島さんって私の好みなのよぉ。
[tab]あと２０才若かったらねぇ…[wait][clear][end]

msg_49:
[color(yellow)]近所のおばさん[color(white)]
[tab]クレール・ド・リュンヌで防具を売ってるって
[tab]聞いたの。さっそく買いに行かなくちゃ。
[tab]子供と主人の分も必要ね。[wait][clear][end]

msg_50:
[color(yellow)]近所のおばさん[color(white)]
[tab]クレール・ド・リュンヌで武器を売ってる
[tab]らしいわね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]他のお店ならすぐにでもやめさせるけど、
[tab]副島さんがやる事だからいいわ。
[tab]でも、子供には行かせないようにしないと。[wait][clear][end]

msg_51:
[color(yellow)]近所のおばさん[color(white)]
[tab]珠閒瑠ジニーの占いがまた良くなったんだって。
[tab]なんでも相性占いが細かくなったらしいのよ。
[tab]これはぜひ行ってみないとね。[wait][clear][end]

msg_52:
[color(yellow)]近所のおばさん[color(white)]
[tab]珠閒瑠ジニーの相性占いが凄いんですって。
[tab]何が凄いって、どんな相手との相性でも
[tab]占えるらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]本当によく当たるみたいだから、
[tab]ペットを買う時とかに占って貰うといいわよねぇ。
[tab]まあ、アパートだから飼えないけど。[wait][clear][end]

msg_53:
[color(yellow)]近所のおばさん[color(white)]
[tab]珠閒瑠ジニーって占い屋さんがあるでしょ？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]これがさっぱり当たらないお店だったんだけど、
[tab]占い方法を変えてから、
[tab]すごく当たり始めたんですって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]以前、財布を無くした時に、
[tab]「探し物は見つかりません。」って言われて
[tab]怒っちゃったけど、また行ってみようかしら。[wait][clear][end]

msg_54:
[color(yellow)]近所のおばさん[color(white)]
[tab]エステショップのエテーリアがサービスを
[tab]変えたんですって。
[tab]どんなサービスかしら？[tab]チェックしないと。[wait][clear][end]

msg_55:
[color(yellow)]近所のおばさん[color(white)]
[tab]ロサカンディータのマヌカンさん、
[tab]波にのまれたって聞いたわよ。
[tab]海に行く時は気をつけないといけないわね。[wait][clear][end]

msg_56:
[color(yellow)]近所のおばさん[color(white)]
[tab]おばさん恥ずかしいわぁ。マヌカンさんが
[tab]「波にのまれた」って流行の事だったのね。
[tab]若い人の会話にはついていけないわ。[wait][clear][end]

msg_57:
[color(yellow)]近所のおばさん[color(white)]
[tab]ロサカンディータのマヌカンさん、
[tab]仕事でパリに行ったんですってね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]うらやましいわぁ。
[tab]おフランスでしょお。
[tab]私もマヌカンになろうかしら。[wait][clear][end]

msg_58:
[color(yellow)]近所のおばさん[color(white)]
[tab]おばさん恥ずかしいわぁ。マヌカンさんが
[tab]「波にのまれた」って流行の事だったのね。
[tab]若い人の会話にはついていけないわ。[wait][clear][end]

msg_59:
[color(yellow)]近所のおばさん[color(white)]
[tab]今度、ロサカンディータで防具を
[tab]取り扱い始めたんですってね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]防具ってかっこ悪いのが多いから、
[tab]おしゃれなのがあると嬉しいわね。[wait][clear][end]

msg_60:
[color(yellow)]近所のおばさん[color(white)]
[tab]パラベラムってバーの事、聞いたことある？
[tab]何でも用心棒を雇ったらしいわよ。
[tab]何か危ない商売でもしてるのかしら。[wait][clear][end]

msg_61:
[color(yellow)]近所のおばさん[color(white)]
[tab]ここだけの話、パラベラムっていうバーは
[tab]武器の密売をやってたらしいわよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]で、こんなご時世になったんで、
[tab]大っぴらに売買しているらしいわ。
[tab]気をつけたほうが良いわよ。[wait][clear][end]

msg_62:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＣＤショップのギガ・マッチョでマンボのＣＤを
[tab]売ってるらしいんだけど、どんな内容かしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]隠して売ってるから、
[tab]教育上良くない内容じゃないかって心配なのよ。[wait][clear][end]

msg_63:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＣＤショップのギガ・マッチョでロックのＣＤを
[tab]売ってるらしいんだけど、どんな内容かしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]隠して売ってるから、
[tab]教育上良くない内容じゃないかって心配なのよ。[wait][clear][end]

msg_64:
[color(yellow)]近所のおばさん[color(white)]
[tab]テレビゲームですら許せないのに、ムー大陸は
[tab]今度ギャンブルを始めたそうじゃないの！
[tab]許せないわ。すぐやめさせないと。[wait][clear][end]

msg_65:
[color(yellow)]近所のおばさん[color(white)]
[tab]トニーの露店のアクセサリーが
[tab]評判なんだけど、おばさんはちょっとね。
[tab]やっぱりデパートで買うのが一番だわ。[wait][clear][end]

msg_66:
[color(yellow)]近所のおばさん[color(white)]
[tab]トニーの露店でお守りみたいなのを
[tab]売ってるらしいんだけど、どうなのかしら？
[tab]ああいう店って苦手なのよ。[wait][clear][end]

msg_67:
[color(yellow)]近所のおばさん[color(white)]
[tab]東亜ディフェンスっていうお店が
[tab]防具の販売を強化したんですってね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]やっぱり危ないご時世だから、
[tab]自分の身は自分で守らないといけない
[tab]ってことなのかしら。[wait][clear][end]

msg_68:
[color(yellow)]近所のおばさん[color(white)]
[tab]東亜ディフェンスっていうお店で
[tab]武器の販売を始めたらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]こういうご時世だからって、
[tab]武器なんか売ってたら、もっと危なくなるわ。
[tab]おばさん、絶対反対よ。[wait][clear][end]

msg_69:
[color(yellow)]近所のおばさん[color(white)]
[tab]赤提灯しらいしの女将さんが、
[tab]長年の夢を実現したって聞いたけど、
[tab]うらやましい話よね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私も若い頃はいろいろあったけど、
[tab]今じゃ家事に追われる毎日ですもの。[wait][clear][end]

msg_70:
[color(yellow)]近所のおばさん[color(white)]
[tab]赤提灯しらいしの女将さん、
[tab]人さがしの仕事なんてしてたんだね。
[tab]知らなかったわ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]とは言っても、人を捜す事なんて滅多にないし、
[tab]関係ないといえば関係ないんだけどね。[wait][clear][end]

msg_71:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＫＡＯＲＩが閉まってたって聞いたんだけど、
[tab]あそこはたしか年中無休だったでしょ？
[tab]風邪でもひいたのかしら。[wait][clear][end]

msg_72:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＫＡＯＲＩが閉まってたのは、香ちゃんが
[tab]買いだしに行ってたからだって？
[tab]なあんだ。心配して損しちゃったわ。[wait][clear][end]

msg_73:
[color(yellow)]近所のおばさん[color(white)]
[tab]香ちゃん、やっぱり風邪でＫＡＯＲＩは
[tab]お休みだって？
[tab]あらあら、体には気をつけないとねぇ。[wait][clear][end]

msg_74:
[color(yellow)]近所のおばさん[color(white)]
[tab]ＫＡＯＲＩが新商品を売り始めたんだってね！
[tab]しかも、海外のすっごくいいやつなんでしょ？
[tab]早く買いに行かないと売り切れちゃうわ。[wait][clear][end]

msg_75:
[color(yellow)]近所のおばさん[color(white)]
[tab]香ちゃんが風邪でＫＡＯＲＩはお休みだって？
[tab]あらあら、体には気をつけないとねぇ。[wait][clear][end]

msg_76:
[color(yellow)]近所のおばさん[color(white)]
[tab]時間城で魔法のカードの複製も
[tab]してくれるんですって。
[tab]いったいどんな人がお客さんなんだろうね。[wait][clear][end]

msg_77:
[color(yellow)]近所のおばさん[color(white)]
[tab]時間城で魔法のカードを売ってるって
[tab]聞いたけど、いかにもって感じね。
[tab]すごく怪しい感じのお店ですもの。[wait][clear][end]

msg_78:
[color(yellow)]あぶない男[color(white)]
[tab]そこに空の科学館があるだろ？
[tab]あのビルに乗ってる飛行船は本物って話だ。
[tab]覚えておいて損はないと思うぜ。[wait][clear][end]

msg_79:
[color(yellow)]あぶない男[color(white)]
[tab]空の科学館が燃えちまったな。
[tab]飛行船は俺もいざという時はと思ってたんだが…
[tab]別の逃げ道を考えとかないとな。[wait][clear][end]

msg_80:
[color(yellow)]あぶない男[color(white)]
[tab]空の科学館の一件、実は相当ヤバいらしいな。
[tab]テレビでもみ消しの報道やってたぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]子供の火遊びで全焼したんだと。[delay(10)]
[tab]ボヤならともかく、全焼は不自然だろ。
[tab]これで皆を騙せるとでも思ってるのかね。[wait][clear][end]

msg_81:
[color(yellow)]あぶない男[color(white)]
[tab]事件に次ぐ事件で皆は警察を当てにしてるけど、
[tab]下手に信用しないほうがいいぜ。
[tab]裏じゃいろいろ悪どい事もやってんだ。[wait][clear][end]

msg_82:
[color(yellow)]克哉[color(white)]
[tab]……[wait][clear][end]

msg_83:
[color(yellow)]あぶない男[color(white)]
[tab]そういや俺さ、
[tab]ＪＯＫＥＲになった奴がさらわれるのを見たんだよ
[tab]連中、アジア系のマフィアみたいだったぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]警察に行かないのかって？[delay(15)]
[tab]冗談じゃないぜ。
[tab]俺がつかまったら馬鹿みたいじゃないか。[wait][clear][end]

msg_84:
[color(yellow)]あぶない男[color(white)]
[tab]街で噂なんだが事件の鍵を握る男がいるらしいな。
[tab]まいったぜ。俺の予想ではそいつは…[delay(15)]
[tab]おっと、これ以上はヤバいな。[wait][clear][end]

msg_85:
[color(yellow)]あぶない男[color(white)]
[tab]街で噂なんだが事件の鍵を握る女がいるらしいな。
[tab]末世に謎の美女とはおあつらえ向きだぜ。
[tab]これはまさに、俺のためのステージか？[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]え？[tab]なんで美女なのかって？[delay(15)]
[tab]解ってないなぁ。
[tab]秘密めいた女性が美女ってのは定番なんだよ。[wait][clear][end]

msg_86:
[color(yellow)]あぶない男[color(white)]
[tab]そういえば、今回の一連の事件の解決には、
[tab]日本でも屈指の財閥が動いてるって話だぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]どこで聞いたって？[delay(15)]
[tab]そりゃ、独自ルートってものがあるのさ。
[tab]深く聞いちゃいけねぇよ。[wait][clear][end]

msg_87:
[color(yellow)]あぶない男[color(white)]
[tab]そういえば、今回の一連の事件の解決には、
[tab]日本でも屈指の財閥が動いてるって話だぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]どこで聞いたって？[delay(15)]
[tab]そりゃ、独自ルートってものがあるのさ。
[tab]深く聞いちゃいけねぇよ。[wait][clear][end]

msg_88:
[color(yellow)]あぶない男[color(white)]
[tab]皆、穢れ、とやらがよっぽど恐ろしいのか、
[tab]穢れ祓いが大はやり。あちこちで懺悔の講演会さ。
[tab]バカだねぇ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]穢れも自分の一部なんだから、
[tab]他人にどうこうして貰うもんじゃねぇだろ。
[tab]案外、俺たち闇の人間の方が純粋なのかね。[wait][clear][end]

msg_89:
[color(yellow)]あぶない男[color(white)]
[tab]最近、妙な白昼夢を見る事があるんだ。
[tab]自分が普通のサラリーマンで、アイドルの
[tab]コンサートチケットを欲しがってるのさ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]ふん。柄でもないぜ。
[tab]俺が普通の生活に耐えられる筈がねぇのにな。
[tab]まあ、誰しも違う自分を持ってるってことかねぇ。[wait][clear][end]

msg_90:
[color(yellow)]あぶない男[color(white)]
[tab]ついに新世塾が表に出てきたか…[delay(15)]
[tab]これから凄い事になるな。
[tab]あんた達も程々にしときなよ。[delay(15)]ケガするぜ。[wait][clear][end]

msg_91:
[color(yellow)]あぶない男[color(white)]
[tab]海のほうで何かあったみたいだぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]周りは地震って騒いでるが揺れ方が違うし、
[tab]ま、地震よりやばい事なのは確かだな。[wait][clear][end]

msg_92:
[color(yellow)]あぶない男[color(white)]
[tab]アメノトリフネが鳴海区の地下鉄工事現場で
[tab]見つかった…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]気味が悪いじゃねえか。
[tab]あそこはただの工事現場だったんだぜ。
[tab]何度か入った事があるから間違いねぇ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]新世塾のやつらがよっぽど手際がいいのか、
[tab]それとも…[delay(15)]いや、考え過ぎか。[wait][clear][end]

msg_93:
[color(yellow)]あぶない男[color(white)]
[tab]過去の常識はあっという間に消えちまったな。
[tab]世界の滅亡を目の前にするなんて思わなかったが、
[tab]こんな形の終わりは認めたくないね。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]そりゃ、俺は力のない虫けらかもしれない。
[tab]が、意地ってものはある。[delay(15)]
[tab]納得の行かないエンドは許せないさ。[wait][clear][end]

msg_94:
[color(yellow)]あぶない男[color(white)]
[tab]肝の据わってない連中が多いようだが、
[tab]騒ぎ立てたところで何にもよくならねぇし、
[tab]いまは、落ち着いている事が大事だ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]あんたもそう思わねぇか？[wait][clear][end]

msg_95:
[color(yellow)]あぶない男[color(white)]
[tab]ゾディアックってクラブは、
[tab]中が結構広い迷路になってるっていうじゃないか。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]いざという時に逃げ込むのに、使えるな。
[tab]さっそく下調べにいくか。[wait][clear][end]

msg_96:
[color(yellow)]あぶない男[color(white)]
[tab]よみがえった珠閒瑠城だけどよ、
[tab]何でも曰く付きのお城らしいぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]城主の澄丸[tab]清忠は呪術の為に虐殺をやったりする
[tab]ひでえ奴だったんだが、最後は天野[tab]舞姫って
[tab]お姫様に殺されちまうんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]自業自得だけど無念だったんだろうね。
[tab]だから怨念が今でも渦巻いてるって訳さ。[wait][clear][end]

msg_97:
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠城の城主、澄丸[tab]清忠を倒したのは、
[tab][suou][tab]辰之進一人でじゃねえ。
[tab]天野[tab]舞姫ってお姫様と二人でだったらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]もしあんたが珠閒瑠城に行くんなら、
[tab]二人に縁があるところを調べたほうが良いぜ。
[tab]…ま、ただのヤマ感だけどな。[wait][clear][end]

msg_98:
[color(yellow)]あぶない男[color(white)]
[tab]よみがえった珠閒瑠城だけどよ、
[tab]何でも曰く付きのお城らしいぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]城主の澄丸[tab]清忠は呪術の為に虐殺をやったりする
[tab]ひでえ奴だったんだが最後は[suou][tab]辰之進って
[tab]侍に切り殺されちまうんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]自業自得だけど無念だったんだろうね。
[tab]だから怨念が今でも渦巻いてるって訳さ。[wait][clear][end]

msg_99:
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠城の城主、澄丸[tab]清忠を倒したのは、
[tab]天野[tab]舞姫一人でじゃねえ。
[tab][suou][tab]辰之進って侍と二人でだったらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]もしあんたが珠閒瑠城に行くんなら、
[tab]二人に縁があるところを調べたほうが良いぜ。
[tab]…ま、ただのヤマ感だけどな。[wait][clear][end]

msg_100:
[color(yellow)]あぶない男[color(white)]
[tab]青葉公園の花が話すって本当かね？
[tab]ちょっと信じられない話だが、困ったもんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]あんまり公園が評判になると、
[tab]あの場所で取り引きが出来なくなっちまうぜ。[wait][clear][end]

msg_101:
[color(yellow)]あぶない男[color(white)]
[tab]伝説の武器職人アサノタクミ…
[tab]俺としたことが名前も聞いた事無いなんてな。
[tab]ぜひ、評判の腕前を見せてもらいたいものだ。[wait][clear][end]

msg_102:
[color(yellow)]あぶない男[color(white)]
[tab]…くだんが出たらしいな。
[tab]ヤツだけはヤバイ。
[tab]気をつけたほうがいいぞ。[wait][clear][end]

msg_103:
[color(yellow)]あぶない男[color(white)]
[tab]呪いのタクシー騒ぎがムー大陸で起きてくれて
[tab]助かったぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]いや、ちょっといろいろあってな。
[tab]気にしないでくれ。[wait][clear][end]

msg_104:
[color(yellow)]あぶない男[color(white)]
[tab]ギガ・マッチョの妖怪、
[tab]まだ別のがいたらしいじゃないか。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]今度は２００キロジジイだとよ。
[tab]まあ、その快速は羨ましいね。[wait][clear][end]

msg_105:
[color(yellow)]あぶない男[color(white)]
[tab]怪人青マントが、停泊中の客船で
[tab]出没しているらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]カモフラージュにもってこいな事件だぜ。
[tab]マント１つで変装できるんだからな。[wait][clear][end]

msg_106:
[color(yellow)]あぶない男[color(white)]
[tab]怪人赤マントが、停泊中の客船で
[tab]出没しているらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]カモフラージュにもってこいな事件だぜ。
[tab]マント１つで変装できるんだからな。[wait][clear][end]

msg_107:
[color(yellow)]あぶない男[color(white)]
[tab]なんでもゲームセンターにムッシーとかいう恐竜が
[tab]出現して、騒ぎになっているらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]みんな近寄らなくなるかと思ったが、
[tab]野次馬も結構いるらしくてね。
[tab]人の入りは相変わらずさ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]ゲームセンターが閑散としてくれれば、
[tab]俺としてはいろいろ好都合だったんだが…
[tab]まあ、仕方ないな。[wait][clear][end]

msg_108:
[color(yellow)]あぶない男[color(white)]
[tab]ギガ・マッチョの妖怪の噂、どうでもいいが、
[tab]時速１００キロで走れるってのは羨ましいね。
[tab]俺が逃げるときはいつも命がけだからな。[wait][clear][end]

msg_109:
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠テレビのお化け騒ぎだが…[delay(15)]
[tab]いや、忘れてくれ。
[tab]俺の考え過ぎだろう。[wait][clear][end]

msg_110:
[color(yellow)]あぶない男[color(white)]
[tab]ツチノコだかなんだか知らないが、
[tab]よくまあ、騒ぎたてるもんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]まあ、珍しい動物は金になるから、
[tab]俺も興味が無い訳じゃないが、
[tab]モノが手に入りにくくちゃ商売できないからな。[wait][clear][end]

msg_111:
[color(yellow)]あぶない男[color(white)]
[tab]しかし、カス校ってのはいろいろと
[tab]騒ぎの起きる学校だぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]今度はテケテケとかいう妖怪が現れたんだと。
[tab]まあ、おかげで夜なら逃げ込むのには便利な
[tab]場所になってるし、俺は助かってるがね。[wait][clear][end]

msg_112:
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも不思議なカードが当たるとか。
[tab]まあ、俺には必要ない物だけどな。[wait][clear][end]

msg_113:
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも特殊なアイテムが当たるとか。
[tab]まあ、俺には必要ない物だけどな。[wait][clear][end]

msg_114:
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでもアクセサリーが当たるとか。
[tab]まあ、俺は興味ないけどな。[wait][clear][end]

msg_115:
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも防具が当たるとか。
[tab]まあ、俺は十分もってるから必要ないがな。[wait][clear][end]

msg_116:
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも武器が当たるとか。
[tab]ちょっとチェックしとかないとまずいかもな。[wait][clear][end]

msg_117:
[color(yellow)]あぶない男[color(white)]
[tab]別冊ミラクルってどんな雑誌だ？
[tab]懸賞で不思議なカードがもらえるって評判だが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]俺もちょっとそういうのには詳しくないんでね。
[tab]週刊誌になら何度かでた事があるんだけどな。
[tab]まあ、全部匿名だが。[wait][clear][end]

msg_118:
[color(yellow)]あぶない男[color(white)]
[tab]別冊ミラクルってどんな雑誌だ？
[tab]懸賞で変わったアイテムがもらえるって評判だが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]俺もちょっとそういうのには詳しくないんでね。
[tab]週刊誌になら何度かでた事があるんだけどな。
[tab]まあ、全部匿名だが。[wait][clear][end]

msg_119:
[color(yellow)]あぶない男[color(white)]
[tab]知ってるか？[delay(15)][tab]月刊バトルマスターの懸賞は
[tab]本物のアクセサリーが当たるんだぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]この本は愛読しているんだが、
[tab]懸賞がイマイチなところだけは不満なんだ。[wait][clear][end]

msg_120:
[color(yellow)]あぶない男[color(white)]
[tab]知ってるか？[delay(15)][tab]月刊バトルマスターの懸賞は
[tab]本物の防具が当たるんだぜ。
[tab]この本は愛読しているから詳しいんだ。[wait][clear][end]

msg_121:
[color(yellow)]あぶない男[color(white)]
[tab]知ってるか？[delay(15)][tab]月刊バトルマスターの懸賞は
[tab]本物の武器が当たるんだぜ。
[tab]この本は愛読しているから詳しいんだ。[wait][clear][end]

msg_122:
[color(yellow)]あぶない男[color(white)]
[tab]ホテル・プレアデスのエボニーに
[tab]地図を集めている男がいるらしいが…
[tab]見取り図とかは扱ってねえかな？[wait][clear][end]

msg_123:
[color(yellow)]あぶない男[color(white)]
[tab]平坂区のサトミタダシに
[tab]地図を集めている男がいるらしいが…
[tab]見取り図とかは扱ってねえかな？[wait][clear][end]

msg_124:
[color(yellow)]あぶない男[color(white)]
[tab]鳴海区の宝石屋が、ここで商売を再開してるぜ。
[tab]商売人の執念ってやつか？
[tab]まったく恐れ入るよ。[wait][clear][end]

msg_125:
[color(yellow)]あぶない男[color(white)]
[tab]パパラチャって宝石屋…
[tab]武器や防具も細工してくれるらしいな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]フフ…これで仕事もしやすくなったぜ。[wait][clear][end]

msg_126:
[color(yellow)]あぶない男[color(white)]
[tab]きょうびのレストランはしぶといね。
[tab]街がぶっ飛んでる時にちゃっかり逃げおおせて、
[tab]そこの青葉区で商売再開だとよ。[wait][clear][end]

msg_127:
[color(yellow)]あぶない男[color(white)]
[tab]レストランのクレール・ド・リュンヌで
[tab]防具を扱っているって聞いたんだが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]やはりな。[delay(15)]
[tab]どうりであのギャルソン、俺たちと同じ世界の
[tab]においがぷんぷんしてるはずだぜ。[wait][clear][end]

msg_128:
[color(yellow)]あぶない男[color(white)]
[tab]レストランのクレール・ド・リュンヌで
[tab]武器を扱っているって聞いたんだが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]やはりな。[delay(15)]
[tab]どうりであのギャルソン、俺たちと同じ世界の
[tab]においがぷんぷんしてるはずだぜ。[wait][clear][end]

msg_129:
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠ジニーだかなんだか知らないが、
[tab]相性占いがパワーアップとかで話題になるなんざ、
[tab]まだまだ頭が平和ボケしてる証拠さ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]まあ、そのほうが俺の仕事は
[tab]やりやすいんだけどな。[wait][clear][end]

msg_130:
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠ジニーの相性占いとやらが評判だが、
[tab]占いで相性を決められちゃたまらないね。
[tab]俺の相性はプラスかマイナス…損得で決まる。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]それでも、まあ好き嫌いでもめる事もあるしな。
[tab]意外とバカにできないものなのかもしれん。[wait][clear][end]

msg_131:
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠ジニーの占いが、
[tab]最近当たるようになったって評判だが、
[tab]くだらねえな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]占いより情報、それが一番さ。
[tab]腕のいい情報屋は予言者みたいなもんだぜ。[wait][clear][end]

msg_132:
[color(yellow)]あぶない男[color(white)]
[tab]エテーリアで同業他社との差別化のために、
[tab]サービスを変更したんだってな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]堅気の商売もご苦労なこった。
[tab]俺なら同業者は組むか潰すね。
[tab]こっちの方がすっきりするからな。[wait][clear][end]

msg_133:
[color(yellow)]あぶない男[color(white)]
[tab]ロカサンディータのマヌカンがパリで
[tab]波にのまれたって聞いたんだが弛んでるね。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]本職なら外の流行に飲み込まれるようじゃダメさ。
[tab]俺たちだって情報の波にさらされているが、
[tab]普段からきちんとしているから動じない。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]それが本当のプロだぜ。
[wait][clear][end]

msg_134:
[color(yellow)]あぶない男[color(white)]
[tab]俺としたことが勘違いしちまったようだな。
[tab]パリじゃなくバリで事故ってたんだって？
[tab]情報はしっかり確認しないとな。[wait][clear][end]

msg_135:
[color(yellow)]あぶない男[color(white)]
[tab]ロサカンディータのマヌカン、
[tab]バリで事故ってたんだって？[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]旅先だからってはめ外しすぎだろう。
[tab]一般人は普段の緊張感が足りないよな。[wait][clear][end]

msg_136:
[color(yellow)]あぶない男[color(white)]
[tab]ロサカンディータの話、聞いてるか？
[tab]ブティックで防具販売の時代が来るとはな。
[tab]いろいろやりにくくなりそうだ。[wait][clear][end]

msg_137:
[color(yellow)]あぶない男[color(white)]
[tab]バーのマスター、用心棒を雇ったんだって？
[tab]賢い選択だ。あのおやじ、大したもんだな。
[tab]見直したぜ。[wait][clear][end]

msg_138:
[color(yellow)]あぶない男[color(white)]
[tab]バーが実は武器屋だと聞いたが、知らなかったぜ。
[tab]マスターも言ってくれればいいのに。
[tab]しかし、こう評判だとかえって買いにくいな。[wait][clear][end]

msg_139:
[color(yellow)]あぶない男[color(white)]
[tab]最近は隠れた商売が流行らしいな。
[tab]ギガ・マッチョには、
[tab]隠し球の商品があるんだってよ。[wait][clear][end]

msg_140:
[color(yellow)]あぶない男[color(white)]
[tab]ギガ・マッチョで表では売らないＣＤが
[tab]あるんだってよ。
[tab]何だか俺みたいで好感が持てるね。[wait][clear][end]

msg_141:
[color(yellow)]あぶない男[color(white)]
[tab]ムー大陸がカジノを始めたんだってな。
[tab]たまらないねぇ。ギャンブルは最高の娯楽さ。
[tab]一つポーカーでもやってみるか。[wait][clear][end]

msg_142:
[color(yellow)]あぶない男[color(white)]
[tab]ムー大陸がカジノを始めたんだってな。
[tab]たまらないねぇ。ギャンブルは最高の娯楽さ。
[tab]一つブラックジャックでもやってみるか。[wait][clear][end]

msg_143:
[color(yellow)]あぶない男[color(white)]
[tab]ムー大陸がカジノを始めたんだってな。
[tab]たまらないねぇ。ギャンブルは最高の娯楽さ。
[tab]一つスロットでもやってみるか。[wait][clear][end]

msg_144:
[color(yellow)]あぶない男[color(white)]
[tab]フッ。トニーの奴、不思議なアクセサリーの
[tab]販売でなかなかの評判じゃねえか。
[tab]一度様子を見に行かないとな。[wait][clear][end]

msg_145:
[color(yellow)]あぶない男[color(white)]
[tab]フッ。トニーの奴、護身用グッズの
[tab]販売でなかなかの評判じゃねえか。
[tab]一度様子を見に行かないとな。[wait][clear][end]

msg_146:
[color(yellow)]あぶない男[color(white)]
[tab]東亜ディフェンスで扱ってる商品が
[tab]ずいぶんよくなったらしいな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]使える物が少ないんで最近行ってなかったが、
[tab]久々に店主の顔でも見てやるか。[wait][clear][end]

msg_147:
[color(yellow)]あぶない男[color(white)]
[tab]東亜ディフェンスが商売の幅を広げたらしいな。
[tab]しかし、武器まで売り始めるとは意外だぜ。
[tab]昔はあんなにいやがってたのによ。[wait][clear][end]

msg_148:
[color(yellow)]あぶない男[color(white)]
[tab]しらしいの女将が夢を実現させたってな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]夢、か…[delay(20)]
[tab]俺にはまぶしすぎる言葉だ。[wait][clear][end]

msg_149:
[color(yellow)]あぶない男[color(white)]
[tab]赤提灯しらいしの女将は、
[tab]人捜しの仕事もしてるんだって？[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]危ねえ危ねえ。
[tab]これからはあそこで飲むのはやめとかないと。
[tab]どこで足がつくか解らねえからな。[wait][clear][end]

msg_150:
[color(yellow)]あぶない男[color(white)]
[tab]ＫＡＯＲＩが閉まってたとかでみんな騒いでるが、
[tab]俺には関係ない事だ。[wait][clear][end]

msg_151:
[color(yellow)]あぶない男[color(white)]
[tab]時間城じゃご丁寧に魔法のカードの
[tab]複製までしてくれるそうだな。
[tab]サービス満点だ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]ま、俺が複製するのは別のものだから
[tab]関係ないね。[wait][clear][end]

msg_152:
[color(yellow)]あぶない男[color(white)]
[tab]時間城で魔法のカードを販売してるんだってな。
[tab]まあどうでもいいが、なんか胡散臭いぜ。
[tab]俺はあの店主がなんだか気に食わないんだ。[wait][clear][end]

msg_153:
[color(yellow)]うらら[color(white)]
[tab]マーヤ、なんか家に忘れ物？
[tab]ちょっと待ってみ、今鍵開けるから。[wait][clear][end]

msg_154:
[color(green)][tab]舞耶は、鍵を開けて自宅に入った。[wait][clear][end]

msg_155:
[color(yellow)]うらら[color(white)]
[tab]マーヤ、なんか家に忘れ物？
[tab]ちょっと待ってみ、今鍵開けるから。[wait][clear][end]

msg_156:
[color(yellow)]克哉[color(white)]
[tab]ここが天野君の家なのか？
[tab]なんだ、署の目と鼻の先じゃないか…[wait][clear][end]

msg_157:
[color(green)][tab]舞耶は、鍵を開けて自宅に入った。[wait][clear][end]

msg_158:
[color(green)][tab]無残に焼け落ち、廃墟になっている。[wait][clear][end]

msg_159:
[color(yellow)]パオフゥ[color(white)]
[tab]すっかり廃墟になってやがる。
[tab]よくまあ、あれで生き延びれたもんだな。
[tab]我ながら感心するぜ。[wait][clear][end]

msg_160:
[color(yellow)]克哉[color(white)]
[tab]こんな廃墟に用は無いな。
[tab]別のところにいこうか。[wait][clear][end]

msg_161:
[color(yellow)]うらら[color(white)]
[tab]焼け落ちた跡ってのは見てて気味が悪いね。
[tab]早く別の所にいこ。[wait][clear][end]

msg_162:
[color(yellow)]克哉[color(white)]
[tab]こんなところに用は無いと思うが…
[tab]さ、行くぞ。[wait][clear][end]

msg_163:
[color(green)][tab]ここには用は無い。[color(white)][wait][clear][end]

msg_164:
[color(yellow)]パオフゥ[color(white)]
[tab]ここは何かと物騒な場所だぜ。
[tab]用も無いのに近づくのは感心しねぇな。
[tab]さ、他へいくぜ。[wait][clear][end]

msg_165:
[color(yellow)]克哉[color(white)]
[tab]…もうここには用は無いな。
[tab]行こう。[wait][clear][end]

msg_166:
[color(yellow)]うらら[color(white)]
[tab]ちょっと、ちょっと。
[tab]こんなところで黄昏てる場合じゃないでしょ。
[tab]さ、いくよ。[wait][clear][end]

msg_167:
[color(green)][tab]ここには用は無い。[color(white)][wait][clear][end]

msg_168:
[color(yellow)]パオフゥ[color(white)]
[tab]海は良い…
[tab]が、今は感傷より行動だぜ。
[tab]じゃ、いくか。[wait][clear][end]

msg_169:
[color(yellow)]うらら[color(white)]
[tab]ここにいるとなんとなく暗くなっちゃうからさ、
[tab]早くべつんとこ、いこ。[wait][clear][end]

msg_170:
[color(yellow)]克哉[color(white)]
[tab]切り離された海はまさに異常な光景だな。
[tab]水平線の代わりにトリフネの壁がそびえている。
[tab]はやくなんとかしなければ。[wait][clear][end]
