
msg_0:
[color(yellow)]ハイカー[color(white)]
[tab]この間、山道を散策してたら
[tab]病院の裏手に出ちゃってさ、
[tab]暗くてすごく不気味だったの。[wait][clear][color(yellow)]ハイカー[color(white)]
[tab]あの病院って、なんだかよく解らないわよね。
[tab]患者の出入りも殆どないし、
[tab]どうして潰れないのか不思議だわ。[wait][clear][end]

msg_1:
[color(yellow)]うさん臭い警備員[color(white)]
[tab]ここから先、事故があって工事中よ。
[tab]ダメね。通れないよ。
[tab]引き返して。引き返して。[wait][clear][end]

msg_2:
[color(yellow)]克哉[color(white)]
[tab]事故？
[tab]所轄の署に、交通規制の連絡はしてるのか？[wait][clear][end]

msg_3:
[color(yellow)]うさん臭い警備員[color(white)]
[tab]いや、急の事故だよ。
[tab]ダメね。通れないよ。[wait][clear][end]

msg_4:
[color(yellow)]克哉[color(white)]
[tab]…仕方ないな。
[tab]わかった、ありがとう。[wait][clear][end]

msg_5:
[color(yellow)]警備員[color(white)]
[tab]ダミー。[wait][clear][end]

msg_6:
[color(yellow)]うさん臭い警備員[color(white)]
[tab]工事、時間かかるよ。
[tab]しばらくダメね。[wait][clear][end]

msg_7:
[color(yellow)]克哉[color(white)]
[tab]…どう思う？[wait][clear][end]

msg_8:
[color(yellow)]パオフゥ[color(white)]
[tab]あからさまに怪しいな。
[tab]少し戻ったところに裏道がある。
[tab]ちょいと遠回りだが、病院へ抜けられるはずだ。[wait][clear][end]

msg_9:
[color(yellow)]克哉[color(white)]
[tab]よし、じゃあその道をいく事にしよう。[wait][clear][end]

msg_10:
[color(yellow)]克哉[color(white)]
[tab]…どう思う？[wait][clear][end]

msg_11:
[color(yellow)]パオフゥ[color(white)]
[tab]あからさまに怪しいな。
[tab]少し戻ったところに裏道がある。
[tab]ちょいと遠回りだが、病院へ抜けられるはずだ。[wait][clear][end]

msg_12:
[color(yellow)]克哉[color(white)]
[tab]よし、じゃあその道をいく事にしよう。[wait][clear][end]

msg_13:
[color(yellow)]パオフゥ[color(white)]
[tab]ここから行くかい？
[tab]確かに病院には通じてるが、ちょいと遠回りだぜ。[wait][clear][end]

msg_14:
[color(yellow)]克哉[color(white)]
[tab]わざわざ遠回りする理由も無いし、
[tab]県道から行かないか。
[tab]あまり時間をかけたくない。[wait][clear][end]
