
msg_0:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(8)][tab]私はカス校生ではない。
[tab]昔はそうだったが今は違う。不撓不屈、真実一路、
[tab]未来の総理大臣を目指す、闘う大学生だっ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]ぬっ、どこの大学かだと？
[tab]細かい事を気にするな！[tab]人生寄り道が大切。
[tab]総理大臣が皆、一流大学だった訳では無いっ！[wait][clear][end]

msg_1:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]巷を騒がすＪＯＫＥＲ狩り、
[tab]未来の総理、闘う大学生が見逃すわけにはいかん！
[tab]この木刀むらまさで一網打尽にしてくれる。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]そのうちにな。[wait][clear][end]

msg_2:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]一連の事件の鍵を握る人物が、
[tab]近々バーへと姿を現すとは本当かっ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]混迷極めるこの事件のキーマン…
[tab]私にとって強力なライバルになりそうだな。[wait][clear][end]

msg_3:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]一連の事件の鍵を握る女性が、
[tab]近々バーへと姿を現すとは本当かっ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]それほどの重要人物なら、この私が守って
[tab]やらずして誰が守ろう！
[tab]で、どんな女性なのだ？[wait][clear][end]

msg_4:
[color(yellow)]闘う大学生[color(white)]
[tab]わがライバル、南条財閥の御曹司がこの街に
[tab]いるそうではないか。
[tab]きっと私の存在を確認しに来たに違いない。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]お互い日本の頂点を目指す男同士だからな。
[tab]むむ、闘志が燃え上がるぞ！
[tab]気合を入れねば。チェストォーッ！[wait][clear][end]

msg_5:
[color(yellow)]闘う大学生[color(white)]
[tab]おおっ！[delay(15)][tab]あなたはわが心の女神、人気モデルの
[tab]桐島[tab]英理子様！！
[tab]このようなところで出会おうとはっ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]この闘う大学生、運命を感じずにいられません！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]近ごろ、ストーカーに狙われていると聞きましたが
[tab]もし、私に任せていただければ、日がな一日、
[tab]２４時間、つかず離れずお守りします！！[wait][clear][end]

msg_6:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(8)]
[tab]みな講演会とやらで穢れ祓いをしているようだが
[tab]まだまだあまいッ！！！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私のように精進潔斎すれば、穢れなど祓わずとも
[tab]初めから存在しないのだ！！[delay(8)]
[tab]…が、後学のため一度講演会に行ってみるか。[wait][clear][end]

msg_7:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォー！！[delay(8)]
[tab]相次ぐ事件は私も不安だ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]しかしッ！！
[tab]白昼夢まで見るとは私もまだ未熟ッ！！
[tab]夢の内容？[delay(20)][tab]むむ、恐ろしくて言えんわ。[wait][clear][end]

msg_8:
[color(yellow)]闘う大学生[color(white)]
[tab]新世塾とはなんだ？
[tab]私の行っていた人生塾なら予備校だが…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]悪を企む不埒な組織なぞ、
[tab]私が一刀両断してくれる。
[tab]が、まずは総理大臣になってからだな。[wait][clear][end]

msg_9:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(8)][tab]皆、心配するな。
[tab]地震に雷、洪水、火災。
[tab]全て私がなんとかしてやろう！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]ただし、総理大臣になるまでまってくれ。[wait][clear][end]

msg_10:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォー！！[delay(8)]
[tab]おのれ新世塾！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]地下鉄工事と偽って、遺跡の発掘をしていたとは…
[tab]国民の血税を流用する不埒な族、成敗してくれる！[delay(15)]
[tab]…そのうちにな。[wait][clear][end]

msg_11:
[color(yellow)]闘う大学生[color(white)]
[tab]ち、チェストォー！！[delay(8)]
[tab]ま、街が飛んでいる！
[tab]デジャ・ヴュの通りだというのか！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]何ということだ。
[tab]この闘う大学生、世に出る前に朽ちるというのか？
[tab]せっかく二流大学で我慢したのに！[wait][clear][end]

msg_12:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォー！！[delay(8)]
[tab]私は負けん！
[tab]負けんぞぉ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]将来、南条グループの総帥になる男が
[tab]最後まであきらめるなと言っておった。
[tab]未来の総理である私がくじけてたまるか！[wait][clear][end]

msg_13:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]君は聞いたか？
[tab]クラブ[tab]ゾディアックの中はアイテム満載、
[tab]大迷宮だというではないか。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]これもまた試練。行きたいのは山々だが、
[tab]君子危うきに近寄らずともいう。
[tab]今回だけは見送ろう。[wait][clear][end]

msg_14:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]蓮華台に現れた奇っ怪な城！
[tab]かつて領民を虫けらのように扱った、
[tab]澄丸[tab]清忠の居城、珠閒瑠城ではないかっ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]かつては天野[tab]舞姫に誅され、
[tab]野望潰えたときいているが、蘇ったとは…
[tab]ぬぬっ、私が成敗してくれる！[delay(20)][tab]そのうちにな。[wait][clear][end]

msg_15:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]かつて澄丸[tab]清忠を成敗した[suou][tab]辰之進には
[tab]将来を誓い合った恋人がいたのだ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]名を天野[tab]舞姫という。
[tab]しかし、正義のため、二人の命は…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]くくっ…な、泣かせる！
[tab]私も国家のためさらに精進せねば！
[tab]チェストォーッ！[wait][clear][end]

msg_16:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]蓮華台に現れた奇っ怪な城！
[tab]かつて領民を虫けらのように扱った、
[tab]澄丸[tab]清忠の居城、珠閒瑠城ではないかっ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]澄丸[tab]清忠の怨念め、この終末に復活するとは…[delay(8)]
[tab]伝承にある英傑、[suou][tab]辰之進に成り代わり、
[tab]この私が成敗してくれる！[delay(20)][tab]そのうちにな。[wait][clear][end]

msg_17:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]澄丸[tab]清忠を誅殺した天野[tab]舞姫には、
[tab]将来を誓い合った恋人がいたのだ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]名を[suou][tab]辰之進。
[tab]しかし、正義のため、二人の命は…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]くくっ…な、泣かせる！
[tab]私も国家のためさらに精進せねば！
[tab]チェストォーッ！[wait][clear][end]

msg_18:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]大ニュースだぞ！
[tab]青葉公園に話をする花が咲いているらしい。
[tab]この花と語れば植物に秘められた謎が明らかに…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]これは私にノーベル賞を受賞させようという、[delay(10)]
[tab]神のお導きかもしれん。[delay(20)]
[tab]と思ったが、私は文系なのだ。[wait][clear][end]

msg_19:
[color(yellow)]闘う大学生[color(white)]
[tab]伝説の武器職人とやらは、まだ見つからんのか？
[tab]見つかったらぜひ、私の新しい愛刀を
[tab]作ってほしいのだが…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり、高いだろうな。
[tab]学割は利かんのだろうか？[wait][clear][end]

msg_20:
[color(yellow)]闘う大学生[color(white)]
[tab]わ、私にだって恐ろしいものはある。
[tab]しかし、それを乗り越えてこそ勇気！[delay(25)]
[tab]…なのだが、くだんは別扱いにしてくれ。[wait][clear][end]

msg_21:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]戦いが私を呼んでいる！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]ムー大陸に呪われたタクシーが出没し、
[tab]多くの人がその凶行にたおれたとか。
[tab]今こそ私の力を見せる時だ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]しかし学生が暴力事件を起こすのはまずいので、
[tab]卒業するまでまってもらおう。[wait][clear][end]

msg_22:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)][tab]世の中は広い！
[tab]時速１００キロで走るばあさんにも驚いたが、
[tab]なんと、さらにその上がいるそうだな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]なんでも、時速２００キロで走れるじいさんとか。
[tab]私もまだまだ修行が足りないようだ。
[tab]気合を入れねば！[tab][delay(15)]チェストォーッ！[wait][clear][end]

msg_23:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]ついに現れおったか怪人青マント！
[tab]私がこの木刀むらまさで成敗してくれるわ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]と思ったが、実は青マントの事はよく知らんのだ。
[tab]詳しい情報が集まるまでは、軽挙妄動は
[tab]控える事にしよう。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]言っておくが、怖い訳ではないぞ。[wait][clear][end]

msg_24:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]ついに現れおったか怪人赤マント！
[tab]私がこの木刀むらまさで成敗してくれるわ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]と思ったが、実は赤マントの事はよく知らんのだ。
[tab]詳しい情報が集まるまでは、軽挙妄動は
[tab]控える事にしよう。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]言っておくが、怖い訳ではないぞ。[wait][clear][end]

msg_25:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]なんと、ゲームセンターに恐竜が現れるとは、
[tab]店内はパニックに違いない！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]ここは私がこの木刀むらまさで…[delay(18)]
[tab]と思ったが貴重な恐竜を殺すわけには行かない。
[tab]ここは動物保護団体に任せよう。[wait][clear][end]

msg_26:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]驚いたことに、時速１００キロで走るばあさんを、
[tab]ギガ・マッチョで見た奴がいるらしいな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]１００ｍを４秒たらずで走りきるとは、
[tab]なんという健脚ッ！
[tab]オリンピックに出ればメダル総なめに違いない。[wait][clear][end]

msg_27:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]カシマレイコなどと、お化けのくせに
[tab]まぎらわしい名前をつけて迷惑だ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]始め聞いた時に一文字増やしたあの人と
[tab]間違えてしまったではないか！
[tab]まったく、いらぬ恥をかいたわ。[wait][clear][end]

msg_28:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]ついに神秘の生物ツチノコが世に出るのか！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私も小学生の時に見た事があるのだが、
[tab]ついに捕まえられなかったのだ。
[tab]今度はなんとか捕獲してほしいものだ。[wait][clear][end]

msg_29:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]わが、愛する母校、春日山高校に、
[tab]妖怪テケテケが出現したとは本当かッ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]後輩達もさぞ恐怖に脅えているだろう…
[tab]ここはこの私が妖怪を成敗して
[tab]学校の平和を取り戻さねば！！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]…と、言いたい所だが、妖怪退治は
[tab]残念ながら専門外なのだ。[wait][clear][end]

msg_30:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]雑誌、ファンタジーワールドの懸賞では、
[tab]不思議なカードが当たると評判だが論外だッ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]本は内容！
[tab]懸賞で売るものでは無いっ！
[tab]が、ためしに一冊買ってみるか。[wait][clear][end]

msg_31:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]雑誌、ファンタジーワールドの懸賞では、
[tab]いろんなアイテムが当たると評判だが論外だッ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]本は内容！
[tab]懸賞で売るものでは無いっ！
[tab]が、ためしに一冊買ってみるか。[wait][clear][end]

msg_32:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]雑誌、ファンタジーワールドの懸賞では、
[tab]アクセサリーが当たると評判だが論外だッ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]本は内容！
[tab]懸賞で売るものでは無いっ！
[tab]が、ためしに一冊買ってみるか。[wait][clear][end]

msg_33:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]雑誌、ファンタジーワールドの懸賞では、
[tab]防具が当たると評判だが論外だッ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]本は内容！
[tab]懸賞で売るものでは無いっ！
[tab]が、ためしに一冊買ってみるか。[wait][clear][end]

msg_34:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]雑誌、ファンタジーワールドの懸賞では、
[tab]本物の武器が当たると評判だが論外だッ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]本は内容、懸賞で売るものでは無いっ！
[tab]が、ためしに一冊買ってみるか。[wait][clear][end]

msg_35:
[color(yellow)]闘う大学生[color(white)]
[tab]別冊ミラクルとは、どんな雑誌だ？
[tab]いや世間を知るために一度読んで見ようと思ってな
[tab]けーっして不思議なカードが欲しい訳では無いぞ[wait][clear][end]

msg_36:
[color(yellow)]闘う大学生[color(white)]
[tab]別冊ミラクルとは、どんな雑誌だ？
[tab]いや世間を知るために一度読んで見ようと思ってな
[tab]けーっしてアイテム目当てという訳では無いぞ。[wait][clear][end]

msg_37:
[color(yellow)]闘う大学生[color(white)]
[tab]月刊バトルマスターは私も愛読しているが、
[tab]懸賞でアクセサリーが当たるとは知らなかった…[delay(8)]
[tab]まあ、大物は小さな事を気にしてはいかんしな。[wait][clear][end]

msg_38:
[color(yellow)]闘う大学生[color(white)]
[tab]月刊バトルマスターは私も愛読しているが、
[tab]懸賞でいろんな防具が当たるとは知らなかった…[delay(8)]
[tab]まあ、大物は小さな事を気にしてはいかんしな。[wait][clear][end]

msg_39:
[color(yellow)]闘う大学生[color(white)]
[tab]月刊バトルマスターは私も愛読しているが、
[tab]懸賞で本物の武器が当たるとは知らなかった…[delay(8)]
[tab]まあ、大物は小さな事を気にしてはいかんしな。[wait][clear][end]

msg_40:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(8)]
[tab]世の中には地図などをあつめる
[tab]変わった人物がおるのだな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私のような常識人には、なぜそんなものを
[tab]集めるのか理解できんが、興味があるなら
[tab]ホテル・プレアデスに行くといいぞ。[wait][clear][end]

msg_41:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(8)]
[tab]世の中には地図などをあつめる
[tab]変わった人物がおるのだな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私のような常識人には、なぜそんなものを
[tab]集めるのか理解できんが、興味があるなら
[tab]そこのサトミタダシに行くといいぞ。[wait][clear][end]

msg_42:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(8)]
[tab]ホテルにあった宝石屋のパパラチャが、
[tab]港南区で商売を再開したようだな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]見上げた根性！[tab]気に入った！！
[tab]私が総理になったあかつきには御用達としよう。
[tab]が、ちょっと無理かもしれないな…[wait][clear][end]

msg_43:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(15)]
[tab]パパラチャという宝石店は、
[tab]武具の開発もしているのか！？[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]ぬぬ、ぜひこの愛用の木刀むらまさを
[tab]パワーアップして貰わねば。[wait][clear][end]

msg_44:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(8)][tab]クレール・ド・リュンヌが
[tab]青葉通りで商売を再開したというが、素晴らしい！
[tab]この激動の中、見上げた根性だ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]もし、私が総理になったら、
[tab]指定レストランにしようと思うがどうかな。
[tab]その前に、この状況をどうかしないとダメだが。[wait][clear][end]

msg_45:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(15)]
[tab]信じがたいが、クレール・ド・リュンヌでは防具の
[tab]取り扱いを始めたらしい…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]しかし、食事と一緒に鎧が出てきたらいやだな。
[tab]何を考えているのか、
[tab]私のような常識人には理解できん。[wait][clear][end]

msg_46:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！[delay(15)]
[tab]信じがたいが、クレール・ド・リュンヌでは武器の
[tab]取り扱いを始めたらしい…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]しかし、食事と一緒に拳銃が出てきたらいやだな。
[tab]何を考えているのか、
[tab]私のような常識人には理解できん。[wait][clear][end]

msg_47:
[color(yellow)]闘う大学生[color(white)]
[tab]ふはははは！
[tab]珠閒瑠ジニーの相性占いが
[tab]パワーアップしたようだな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]前回の結果が最悪だったのは、
[tab]バージョンが悪かったからに違いない！
[tab]え、結果？[delay(15)][tab]そ、それは気にするな！！[wait][clear][end]

msg_48:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]何が相性占いだ！[tab]この動乱の時代に
[tab]たわけた事に浮かれおって！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私は絶対に信じんぞ。
[tab]私と相性がよいのがあのような……[delay(15)]
[tab]むむむ、信じてたまるか！！[wait][clear][end]

msg_49:
[color(yellow)]闘う大学生[color(white)]
[tab]珠閒瑠ジニーが望龍術を取り入れたそうだな。
[tab]望龍術はかつて天才軍師、諸葛孔明が使った技、
[tab]占い師ごときに究められるものでは無いわ！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]ま、君たちも興味がある時は私にきいてくれ。
[tab]３年後までに勉強しておくから。[wait][clear][end]

msg_50:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]時代はエステ業界にも戦いを求めているのか。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]エテーリアが他社との差別化のため、
[tab]サービス内容を変更したらしいぞ。[wait][clear][end]

msg_51:
[color(yellow)]闘う大学生[color(white)]
[tab]ロサカンディータのマヌカンが、
[tab]旅先で波にのまれたそうだが…[delay(15)]
[tab]あまいっ、あますぎるっ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私のように鍛えていれば、津波ですら平気だ！
[tab]今度、恵比須海岸で私の凄さを見せてあげよう。[delay(15)]
[tab]…今度な。[wait][clear][end]

msg_52:
[color(yellow)]闘う大学生[color(white)]
[tab]な、なに？[delay(15)][tab]波とは流行の事だと？
[tab]チェストォーッ！[delay(15)][tab]も、もちろん解っていたとも。
[tab]え、海岸とかなんとかいってたって？[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]そ、それはもちろん海岸で私のハイセンスな
[tab]スーツ姿を見せるつもりだったのだ。
[tab]本当だぞ。[wait][clear][end]

msg_53:
[color(yellow)]闘う大学生[color(white)]
[tab]例のマヌカン…結構、重体だそうだな。
[tab]私も少々きつく言い過ぎたようだ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]見舞いがてら、ブランドのジャケットでも
[tab]買いに行くか。[delay(15)]
[tab]金ができたらな。[wait][clear][end]

msg_54:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]ロサカンディータのマヌカンが、
[tab]パリで流行感覚を磨いてきたらしいな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり本場で修業するのが一番か…
[tab]私も一つ、ホワイトハウスで
[tab]修行したいところだ。[wait][clear][end]

msg_55:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)][tab]ロサカンディータで
[tab]防具を販売しているとは本当か？[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]むむ、女性が強い時代とはいえ、まさか、
[tab]武闘派まで出てくるとは…[delay(15)]まだまだ負けられん！
[tab]チェストォーッ！！[wait][clear][end]

msg_56:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]ついに用心棒を雇わねばならない時代なのかっ！
[tab]この私が至らぬばかりに……[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]しかし！[tab]パラべラムのマスターよ！
[tab]安心するがいい！[tab]私は必ず治安を回復する！[delay(15)]
[tab]そのためには、まず総理にならねば。[wait][clear][end]

msg_57:
[color(yellow)]闘う大学生[color(white)]
[tab]パラベラムというバーで武器が買えるとは本当か！
[tab]むむむ、これからは相手をよく見て話さなければ…
[tab]いや、決して武器をおそれているのでは無いぞ！[wait][clear][end]

msg_58:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)][tab]おのれ、ギガ・マッチョ！
[tab]マンボのＣＤを隠れて販売するとは、
[tab]なんたることっ！！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]この私をラテンの申し子と知っての策略か！
[tab]うぬぬ、断じて許せん。
[tab]即刻、買ってくれるわ！[wait][clear][end]

msg_59:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)][tab]おのれ、ギガ・マッチョ！
[tab]ロックのＣＤを隠れて売買するとは不届き千万！
[tab]顧客差別はこの私が天誅を加えてくれるわ！[wait][clear][end]

msg_60:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]最近、ムー大陸がカジノを始めたそうだな。
[tab]しかも、ポーカーが儲かるとか。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり、賭け事を楽しむくらいの
[tab]心の余裕は必要だな。
[tab]所持金に余裕がないし、行ってみるか。[wait][clear][end]

msg_61:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]最近、ムー大陸がカジノを始めたそうだな。
[tab]しかも、ブラックジャックが儲かるとか。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり、賭け事を楽しむくらいの
[tab]心の余裕は必要だな。
[tab]所持金に余裕がないし、行ってみるか。[wait][clear][end]

msg_62:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]最近、ムー大陸がカジノを始めたそうだな。
[tab]しかも、スロットが儲かるとか。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり、賭け事を楽しむくらいの
[tab]心の余裕は必要だな。
[tab]所持金に余裕がないし、行ってみるか。[wait][clear][end]

msg_63:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]トニーの店が大反響とは本当か！？
[tab]まさか奴ごときに後れを取ろうとは…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]なんでも、変わったアクセサリーが評判とか。
[tab]私も変わった受験グッズを販売してみようか。[delay(15)]
[tab]やはりダメかな？[wait][clear][end]

msg_64:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]トニーの店が大反響とは本当か！？
[tab]まさか奴ごときに後れを取ろうとは…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]なんでも、特殊なアイテムが評判とか。
[tab]私も特殊なカス校アイテムを販売してみようか。[delay(15)]
[tab]やはりダメかな？[wait][clear][end]

msg_65:
[color(yellow)]闘う大学生[color(white)]
[tab]ふっふっふ。東亜ディフェンスがさらに
[tab]素晴らしい防具を発売するのだよ。
[tab]知っていたかね？[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]つまり、私がまた一段と強くなるということだな。
[tab]どんな事件も私に任せたまえ！！
[tab]…が、その前にお金をためねば。[wait][clear][end]

msg_66:
[color(yellow)]闘う大学生[color(white)]
[tab]ふっふっふ。東亜ディフェンスがこのたび
[tab]強力な武器を発売することになったのだよ。
[tab]知っていたかね？[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]つまり、私がまた一段と強くなるということだな。
[tab]どんな事件も私に任せたまえ！！
[tab]…が、その前にお金をためねば。[wait][clear][end]

msg_67:
[color(yellow)]闘う大学生[color(white)]
[tab]そこのしらいしの女将が夢を実現させたそうだが、
[tab]まだまだあまーいっ！！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり私のように不可能を可能にしてこそ、
[tab]本当の夢だ！
[tab]君も私の世界制覇に期待してくれたまえ。[wait][clear][end]

msg_68:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]しらいしの女将がマンサーチャーの
[tab]仕事をしていたらしいな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私のように、何もしなくても周りが
[tab]寄ってくるようなＶＩＰには必要ないが…
[tab]好きなモデルの桐島[tab]英理子でも捜させるかな。[wait][clear][end]

msg_69:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]みな小さい事で動揺し過ぎだっ！！
[tab]ＫＡＯＲＩが閉まってたくらいなんだというのだ。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私は全然気にならないぞ！
[tab]おととい、必要なアロマエキスはすべて
[tab]まとめ買いしてあるからな。[wait][clear][end]

msg_70:
[color(yellow)]闘う大学生[color(white)]
[tab]なんと、香さんは新商品のために
[tab]買いだしに行ってたそうだな。
[tab]うぬぬぬぬ…[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]全商品を揃えたと思っていたのだが仕方ない、
[tab]私が新商品を見極めてやろうじゃないか！
[tab]チェストォーッ！！[wait][clear][end]

msg_71:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]ＫＡＯＲＩが閉まっていたのは、香さんが
[tab]風邪だったからというではないか！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]やはり弱きを助け、強きをくじいてこそ、真実の男。
[tab]さっそく看病に行かねばなるまい。[delay(15)]
[tab]と、思ったが、医療のことはよくわからんのだ。[wait][clear][end]

msg_72:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]ＫＡＯＲＩが商品を増やしたそうだな。[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]全商品を揃えたと思っていたのだが仕方ない、
[tab]私が新商品を見極めてやろうじゃないか！[wait][clear][end]

msg_73:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]時間城で魔法のカードの複製をしてくれるのだ！
[tab]知っていたか？[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]私はもちろん知っていたとも。
[tab]この怪奇現象乱立の時代に
[tab]魔法は必要不可欠だからな！[wait][clear][end]

msg_74:
[color(yellow)]闘う大学生[color(white)]
[tab]チェストォーッ！！[delay(15)]
[tab]時間城で魔法のカードを販売しているだと？
[tab]ばっかもん！！！！[wait][clear][color(yellow)]闘う大学生[color(white)]
[tab]この科学全盛期に魔法も何もあるものか！[delay(15)]
[tab]そんなモノはまやかしに決まっている。
[tab]で、一枚いくらなのだ？[wait][clear][end]

msg_75:
[color(yellow)]おばあちゃん[color(white)]
[tab]しらいしの娘さんは、ほんと困ったもんだねぇ。
[tab]昔は名うての、まん、さあちゃあだったなんて…
[tab]いくつになってもお調子もので困ったもんだよ。[wait][clear][end]

msg_76:
[color(yellow)]おばあちゃん[color(white)]
[tab]昔の警察官はそりゃあカッコよかった。
[tab]娘心にあこがれたもんだよ。
[tab]それが最近はだらしがないというか…[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]でも、はやく事件を解決してもらって、
[tab]安心してくらしたいもんだねぇ。[wait][clear][end]

msg_77:
[color(yellow)]おばあちゃん[color(white)]
[tab]こないだ黒ずくめの変な連中がこのあたりを
[tab]うろちょろしておったから、この杖を振り回して
[tab]追っ払ってやったよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]それにしても真っ昼間から何を一生懸命
[tab]探しとったんかのぅ。[wait][clear][end]

msg_78:
[color(yellow)]おばあちゃん[color(white)]
[tab]事件の重要人物が現れるとかで騒いどるが、
[tab]どんなものだか解らないよ。
[tab]あまり期待し過ぎるのはどうかと思うねぇ。[wait][clear][end]

msg_79:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近はなにかと物騒だけど、こういう時こそ
[tab]備えが肝心だね。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]わたしゃ、南条生命で貯蓄型保険に
[tab]入っているから安心さ。
[tab]あそこは頼りがいがあるからねぇ。[wait][clear][end]

msg_80:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近、頭の中がおかしいんじゃ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]春日山高校の文化祭が大盛況だったり、
[tab]仮面党とかいう集団が街を荒らしたり…
[tab]そういう、ありもしない記憶があるんじゃよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]やっぱり年なのかねぇ…
[tab]まだまだ若いつもりだったんじゃが。[wait][clear][end]

msg_81:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近、頭の中が混乱しとるから、
[tab]もう、そういう年かと思っとったら、
[tab]若い連中も混乱しとるみたいなんじゃ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]たしか…そう、でじゃぶーとか。
[tab]意味はよくわからんが、新しい病気なのかねぇ。[wait][clear][end]

msg_82:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近の人はあまり知らんみたいじゃが、
[tab]アメノトリフネと言えば、船の神様。
[tab]えらーい方なんじゃ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]変な空飛ぶ円盤の名前なんかにしてると、
[tab]いまにバチが当たるよ。[wait][clear][end]

msg_83:
[color(yellow)]おばあちゃん[color(white)]
[tab]えらい大きな地震でダメかと思ったけど、
[tab]窓ガラスが割れたぐらいで建物も全然平気。
[tab]たいしたもんだねえ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]でも、こんな騒ぎばかり続いていると、
[tab]今にもっと悪い事が起きるんじゃないか…
[tab]なんてねぇ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]相変わらず変な夢ばかり見るし、
[tab]わたしゃ不安だよ。[wait][clear][end]

msg_84:
[color(yellow)]おばあちゃん[color(white)]
[tab]地震が終わったら遺跡が見つかったとかで、
[tab]もう大騒ぎさ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]ついこの間までは街も静かだったのに、
[tab]いったいどうしてこうなっちまったんだろうねぇ。[wait][clear][end]

msg_85:
[color(yellow)]おばあちゃん[color(white)]
[tab]なんまんだぶ、なんまんだぶ。
[tab]ま、街が、そ、空を飛んどるんじゃ。
[tab]破滅じゃ、終いじゃ。[wait][clear][end]

msg_86:
[color(yellow)]おばあちゃん[color(white)]
[tab]わたしゃ、もうこんな歳だし、
[tab]世界が破滅するならそれでも良いと思うんだよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]だけど、若い子達が何とかしようと
[tab]頑張っているのを見ると、
[tab]あきらめるのが悪いような気がするね。[wait][clear][end]

msg_87:
[color(yellow)]おばあちゃん[color(white)]
[tab]ぞであっく、とかいうお店の中が迷路だって
[tab]聞いたんだけど、何の店なんだい？
[tab]踊り？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]じゃあ、踊りながら迷路を回るのが、
[tab]最近の流行りなのかい？
[tab]何だか変ってるねぇ。[wait][clear][end]

msg_88:
[color(yellow)]おばあちゃん[color(white)]
[tab]なんでも、珠閒瑠城が蘇ったんだって！？
[tab]ああ、天野[tab]舞姫様にお祈りしないと。
[tab]なんまんだぶ、なんまんだぶ…[wait][clear][end]

msg_89:
[color(yellow)]おばあちゃん[color(white)]
[tab]忘れとったが、天野[tab]舞姫様にも
[tab]お祈りしておかないとね。
[tab]なんまんだぶ、なんまんだぶ…[wait][clear][end]

msg_90:
[color(yellow)]おばあちゃん[color(white)]
[tab]なんでも、珠閒瑠城が蘇ったんだって！？
[tab]ああ、[suou][tab]辰之進様にお祈りしないと。
[tab]なんまんだぶ、なんまんだぶ…[wait][clear][end]

msg_91:
[color(yellow)]おばあちゃん[color(white)]
[tab]忘れとったが、[suou][tab]辰之進様にも
[tab]お祈りしておかないとね。
[tab]なんまんだぶ、なんまんだぶ…[wait][clear][end]

msg_92:
[color(yellow)]おばあちゃん[color(white)]
[tab]青葉公園の花は人間の言葉を話すんだってねぇ。
[tab]はあ～たいしたもんだ。
[tab]誰だか知らないが凄い花を作ったねぇ。[wait][clear][end]

msg_93:
[color(yellow)]おばあちゃん[color(white)]
[tab]伝説の武器職人ねぇ…
[tab]私が若い頃は、まだたくさん職人さんがいたけど、
[tab]武器の職人さんなんて初めて聞いたよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]私のおばあちゃんの頃なら結構いたんだろうけど、
[tab]今もその伝統を受け継いでる人がいるなんて
[tab]感心な事だね。[wait][clear][end]

msg_94:
[color(yellow)]おばあちゃん[color(white)]
[tab]よいか、くだんにだけは近づいてはならぬぞ。
[tab]くだんにだけは…[delay(20)]
[tab]なんまんだぶ、なんまんだぶ…[wait][clear][end]

msg_95:
[color(yellow)]おばあちゃん[color(white)]
[tab]怖い世の中だねぇ。
[tab]ムー大陸に人をはねる呪いのタクシーが
[tab]出たんだろう？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]これからはタクシーを呼ぶ時にも注意しないとね。
[tab]あんた達も、十分気をつけるんだよ。[wait][clear][end]

msg_96:
[color(yellow)]おばあちゃん[color(white)]
[tab]すんごい速さで走るばあさんに驚いてたら、
[tab]その倍の速さのじいさんがいるんだねぇ。
[tab]わたしゃ、ビックリたまげたよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]でも、２００キロジジイという名前はいけません！
[tab]２００キロおじいさん、と言わないとね。
[tab]まったく…汚い言葉は心も汚くしますよ。[wait][clear][end]

msg_97:
[color(yellow)]おばあちゃん[color(white)]
[tab]青マントがまた現れたんだねぇ。
[tab]私が女学生だった頃、よく話題になったもんさ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]昔話で人に何度か話したんだけど、マントの色が
[tab]思い出せなくて困ってね、赤だか青だか、
[tab]適当に言ってたんだけど、青だったんだね。[wait][clear][end]

msg_98:
[color(yellow)]おばあちゃん[color(white)]
[tab]赤マントがまた現れたんだねぇ。
[tab]私が女学生だった頃、よく話題になったもんさ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]昔話で人に何度か話したんだけど、マントの色が
[tab]思い出せなくて困ってね、赤だか青だか、
[tab]適当に言ってたんだけど、赤だったんだね。[wait][clear][end]

msg_99:
[color(yellow)]おばあちゃん[color(white)]
[tab]ムー大陸に恐竜がいると聞いたけど、
[tab]やっぱり新しいゲームなのかい？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]最近の遊びは良くわからないよ。
[tab]空気で膨らませて、中で子供を遊ばせるやつなら
[tab]知ってるんだけどねぇ。[wait][clear][end]

msg_100:
[color(yellow)]おばあちゃん[color(white)]
[tab]ギガ・マッチョってＣＤ屋さんに、凄い速さで走る
[tab]１００キロババアがいるって噂だけどね、
[tab]ちょっとひどい話だと思わないかい？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]これが若い子ならいい噂だろうに、年寄りだからと
[tab]妖怪だのババアだのと…年寄りが時速１００キロで
[tab]走っても、なんの不思議も無いよねぇ？[wait][clear][end]

msg_101:
[color(yellow)]おばあちゃん[color(white)]
[tab]テレビ局に謎かけだかなにかをしてくる、
[tab]お化けが出たんだって？
[tab]えーと、そう、カシマレイコとかいってたね。[wait][clear][end]

msg_102:
[color(yellow)]おばあちゃん[color(white)]
[tab]また、ツチノコ騒動かい…[delay(20)]これで何度目かねぇ。
[tab]今度も逃げられちまうんじゃないかと思うよ。
[tab]動物はそっとしておいてあげるのが一番さ。[wait][clear][end]

msg_103:
[color(yellow)]おばあちゃん[color(white)]
[tab]テケテケとかいうお化けの噂を耳にしたんだけど、
[tab]ただでさえ評判が悪いのに、こんどは
[tab]お化け騒ぎだなんて、春日山高校も難儀だねぇ。[wait][clear][end]

msg_104:
[color(yellow)]おばあちゃん[color(white)]
[tab]ふあんたじーわあるどという本の懸賞で
[tab]不思議なカードが当たるって話を聞いてね、
[tab]若い頃を思い出したのさ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]子供の頃に、雑誌の懸賞で手に持つと色が変る
[tab]不思議なカードをもらってね。
[tab]結構、嬉しかったもんだよ。[wait][clear][end]

msg_105:
[color(yellow)]おばあちゃん[color(white)]
[tab]ふあんたじーわあるどという本の懸賞で
[tab]変わった道具が当たるって話を聞いてね、
[tab]昔のことを思い出したんだよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]学生の頃に雑誌の懸賞で
[tab]携帯カイロをもらってね。
[tab]もったいなくて使えなかったもんさ。[wait][clear][end]

msg_106:
[color(yellow)]おばあちゃん[color(white)]
[tab]ふぁんたじーわあるどという雑誌の懸賞で、
[tab]アクセサリーが当たるそうじゃが、
[tab]最近は雑誌の懸賞も豪勢になったねぇ。[wait][clear][end]

msg_107:
[color(yellow)]おばあちゃん[color(white)]
[tab]ふぁんたじーわあるどという雑誌の懸賞で、
[tab]本物の防具が当たるって聞いたけれど、
[tab]そんなものもらって嬉しいのかねぇ？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]最近の流行りにはついていけませんよ。[wait][clear][end]

msg_108:
[color(yellow)]おばあちゃん[color(white)]
[tab]ふぁんたじーわあるどという雑誌の懸賞で、
[tab]本物の武器が当たるって聞いたけれど、
[tab]本当かい？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]そりゃ最近は物騒だけれど、
[tab]武器まで持ち出すのは感心しないねぇ。[wait][clear][end]

msg_109:
[color(yellow)]おばあちゃん[color(white)]
[tab]別冊ミラクルという雑誌の懸賞が、
[tab]話題になってるみたいだねぇ。
[tab]確か、不思議なカードがもらえるとか。[wait][clear][end]

msg_110:
[color(yellow)]おばあちゃん[color(white)]
[tab]別冊ミラクルという雑誌の懸賞が、
[tab]話題になってるみたいだねぇ。
[tab]確か、変わった道具がもらえるとか。[wait][clear][end]

msg_111:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近は、月刊バトルマスターという雑誌が
[tab]流行っているのかい？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]名前がなんだか物騒でよくないけど、
[tab]懸賞でアクセサリーが当たるそうだから、
[tab]案外危なくない本なのかねぇ。[wait][clear][end]

msg_112:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近は、月刊バトルマスターという雑誌が
[tab]流行っているのかい？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]懸賞で防具がもらえるって聞いたんだけど、
[tab]そういう雑誌を読むのは感心しないね。
[tab]戦争はもう懲り懲りだよ。[wait][clear][end]

msg_113:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近は、月刊バトルマスターという雑誌が
[tab]流行っているのかい？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]懸賞で武器がもらえるって聞いたんだけど、
[tab]そういう雑誌を読むのは感心しないね。
[tab]戦争はもう懲り懲りだよ。[wait][clear][end]

msg_114:
[color(yellow)]おばあちゃん[color(white)]
[tab]ホテルの喫茶店に地図をあつめている人が
[tab]いるんだって。
[tab]また、ずいぶん変わった物が好きなんだねぇ。[wait][clear][end]

msg_115:
[color(yellow)]おばあちゃん[color(white)]
[tab]そこの商店街のサトミタダシに、
[tab]地図をあつめている人がいるんだって。
[tab]また、ずいぶん変わった物が好きなんだねぇ。[wait][clear][end]

msg_116:
[color(yellow)]おばあちゃん[color(white)]
[tab]宝石屋さんがお店ごと越してきたんだってねぇ。
[tab]まずは、よかったよかった。[wait][clear][end]

msg_117:
[color(yellow)]おばあちゃん[color(white)]
[tab]宝石屋さんまで武器なんか作ろうとするなんて…
[tab]みんな戦争を忘れてしまったのかねぇ。[wait][clear][end]

msg_118:
[color(yellow)]おばあちゃん[color(white)]
[tab]ホテルの食堂が青葉区に店を移して
[tab]商売を再開したそうだよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]世の中たいへんな事になってるけど、
[tab]なんだか勇気づけられるねぇ。[wait][clear][end]

msg_119:
[color(yellow)]おばあちゃん[color(white)]
[tab]くれーるどれんねといったかね？
[tab]その食堂で防具を売ってるらしいんだ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]そういう店でも売ってるくらいだから、
[tab]もうみんな買ってるんだろうね。
[tab]やっぱり１つぐらい買った方がいいのかねぇ。[wait][clear][end]

msg_120:
[color(yellow)]おばあちゃん[color(white)]
[tab]食堂で武器が売られるなんて世も末だね。[delay(15)]
[tab]クレール・ド・リ…[delay(10)]やんぬ、とかという店で、
[tab]武器を売り始めたそうだよ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]ついこないだ戦争があったばかりのような
[tab]気がするのに、世間はそんなことは
[tab]忘れちまったのかねぇ。[wait][clear][end]

msg_121:
[color(yellow)]おばあちゃん[color(white)]
[tab]相性占いなんてする年じゃないと思ってたら、
[tab]珠閒瑠ジニーの相性占いは、
[tab]いろんな結果がでるそうじゃないか。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]最近、まくらを買い替えようかと思うんだけど、
[tab]合わないと寝られないから一つ占って貰おうかね。[wait][clear][end]

msg_122:
[color(yellow)]おばあちゃん[color(white)]
[tab]珠閒瑠ジニーで相性占いが評判に
[tab]なってるみたいだけど、相手もいないし、
[tab]寂しい年になってしまったねぇ。[wait][clear][end]

msg_123:
[color(yellow)]おばあちゃん[color(white)]
[tab]ワンロン占い、っていうのが
[tab]最近の流行りなんだねぇ。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]珠閒瑠ジニーっていうお店が
[tab]ワンロン占いを始めた、って凄い評判だよ。[wait][clear][end]

msg_124:
[color(yellow)]おばあちゃん[color(white)]
[tab]エステショップ、エテーリアが
[tab]新しいサービスを始めたんだって。
[tab]さっそく見に行ってみようかね。[wait][clear][end]

msg_125:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近の娘さんはそそっかしいね。
[tab]ロサカン…[delay(15)]なんとか、の店員さんが、
[tab]旅先で波にのまれたって。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]旅先で気がゆるむのはしかたないけど、
[tab]海は危ないんだから注意しなきゃ。[wait][clear][end]

msg_126:
[color(yellow)]おばあちゃん[color(white)]
[tab]え？[tab]のまれたのは、流行の波、だった？
[tab]何だい、波にのまれるのが流行りなのかい？
[tab]そりゃまたおかしな事が流行ってるもんだね。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]え？[tab]違うのかい？
[tab]ちょっと難しいことはよくわからないねぇ。
[tab]とにかく、無事なのは何よりだよ。[wait][clear][end]

msg_127:
[color(yellow)]おばあちゃん[color(white)]
[tab]ロサカン…[delay(15)]なんとか、の店員さんが、
[tab]旅先で流行の波に飲まれたんだってね。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]津波に流行があるなんて知らなかったけど、
[tab]危ないからほどほどにしないとね。
[tab]え？[tab]ちがう？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]わたしにゃ、よくわからないよ。[wait][clear][end]

msg_128:
[color(yellow)]おばあちゃん[color(white)]
[tab]服屋のロサカン…[delay(15)]なんとかで、
[tab]防具を売ってるんだって？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]じゃあこれからは防空頭巾とかが
[tab]流行るってのかい？
[tab]時代は変わったねぇ。[wait][clear][end]

msg_129:
[color(yellow)]おばあちゃん[color(white)]
[tab]飲み屋さんが用心棒を雇ったんだってねぇ。
[tab]それもいいけど今はほうむせきゅりていじゃよ。
[tab]チョーさんが言っとったから間違いない。[wait][clear][end]

msg_130:
[color(yellow)]おばあちゃん[color(white)]
[tab]飲み屋さんで武器を売るなんて、
[tab]世の中どうなっとるのかねぇ。
[tab]酔っぱらいに刃物なんて冗談じゃないよ。[wait][clear][end]

msg_131:
[color(yellow)]おばあちゃん[color(white)]
[tab]ギガ・マッチョには隠して売られている
[tab]マンボのＣＤがあったんだってね。
[tab]よっぽど売りたくないんだろうねぇ。[wait][clear][end]

msg_132:
[color(yellow)]おばあちゃん[color(white)]
[tab]聞いた話だけどね、
[tab]なんでもギガ・マッチョで隠して売られている
[tab]ロックのＣＤがあるんだってね。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]そういえば戦争の後も米とかを、
[tab]隠れて売ってたりとかしていたねぇ。
[tab]それと同じようなもんかねぇ？[wait][clear][end]

msg_133:
[color(yellow)]おばあちゃん[color(white)]
[tab]バクチはいけまっ[delay(8)]せん！
[tab]ろくなことにならないからね。[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]あんた達もムー大陸になんか遊びにいっちゃ
[tab]いけませんよ。[wait][clear][end]

msg_134:
[color(yellow)]おばあちゃん[color(white)]
[tab]トニーとかいう金髪のお兄ちゃんがやってる
[tab]露店があるじゃろ？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]あの店で売ってるアクセサリーは
[tab]ずいぶんと評判じゃないかい。
[tab]なかなか商売上手で感心させられるねぇ。[wait][clear][end]

msg_135:
[color(yellow)]おばあちゃん[color(white)]
[tab]トニーとかいう金髪のお兄ちゃんがやってる
[tab]露店があるじゃろ？[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]あの店はずいぶんと評判がいいようだね。
[tab]みんな、売ってる道具のはなしをしてたよ。
[tab]なかなか商売上手で感心させられるねぇ。[wait][clear][end]

msg_136:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近物騒だから、東亜でふぇんすという店が
[tab]儲かってるんだってね。
[tab]防具を売ってるとかいう…[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]やっぱり備えは大事なのかねえ。
[tab]まあ、この年だと慌てて身を守ろう
[tab]って気も起きないけどねぇ。[wait][clear][end]

msg_137:
[color(yellow)]おばあちゃん[color(white)]
[tab]最近物騒だから、東亜でふぇんすという店が
[tab]儲かってるんだってね。
[tab]武器を売ってるとかいう…[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]やっぱり備えは大事なのかねえ。
[tab]今さら危ない物を振り回してまで
[tab]身を守りたいとも思わないんだけどねぇ。[wait][clear][end]

msg_138:
[color(yellow)]おばあちゃん[color(white)]
[tab]しらいしの娘さん、夢を実現させたんだって。
[tab]ずいぶん喜んでるんだろうねぇ。[delay(15)]
[tab]それにしても、どんな夢なんだろうね。[wait][clear][end]

msg_139:
[color(yellow)]おばあちゃん[color(white)]
[tab]赤提灯しらいしで人捜しをしてくれるって。
[tab]また、探偵さんみたいな商売を始めたもんだね。
[tab]長続きするといいけど…[wait][clear][end]

msg_140:
[color(yellow)]おばあちゃん[color(white)]
[tab]ＫＡＯＲＩが閉まってたって話を聞いたけど、
[tab]みんな騒ぎ過ぎだよ。
[tab]誰だって休む日はあるさ。[delay(15)]ねえ。[wait][clear][end]

msg_141:
[color(yellow)]おばあちゃん[color(white)]
[tab]時間城じゃ魔法のカードの
[tab]複製もしてくれるそうだけど…[wait][clear][color(yellow)]おばあちゃん[color(white)]
[tab]わたしには家の鍵とか、入れ歯とかの
[tab]複製の方が有り難いね。
[tab]良く無くすんだよ。[wait][clear][end]

msg_142:
[color(yellow)]おばあちゃん[color(white)]
[tab]時間城で、魔法のカードを売ってるそうだよ。
[tab]ちかごろは物騒だから、みんなそんなものに
[tab]頼りたくなるんだねぇ。[wait][clear][end]

msg_143:
[color(yellow)]下町おやじ[color(white)]
[tab]ここ最近、事件続きでちょっと辛気臭えがよ、
[tab]平坂区は下町風情の漂ういい所だぜ。[wait][clear][color(yellow)]下町おやじ[color(white)]
[tab]個性的な店が並ぶカメヤ横丁に、駅ビルの
[tab]スマイル平坂もあって買い物も便利だし、
[tab]何より住む人があったけえからな。[wait][clear][end]

msg_144:
[color(yellow)]下町おやじ[color(white)]
[tab]ＪＯＫＥＲ事件ってのは、まだ解決しねえのかぃ？
[tab]警察は何をやってるのかねぇ。[wait][clear][color(yellow)]下町おやじ[color(white)]
[tab]おかげで街が辛気くさくてしょうがねえやな。
[tab]春日山高校の文化祭、春日祭もさっぱりだったし、
[tab]俺はもう、寂しくて泣けてくるよ。[wait][clear][end]

msg_145:
[color(yellow)]下町おやじ[color(white)]
[tab]おう、ＪＯＫＥＲ狩りが流行ってるらしいぜ。
[tab]至極、結構な話だと思わねぇか？
[tab]これで街が平和になるってもんだ。[wait][clear][end]

msg_146:
[color(yellow)]下町おやじ[color(white)]
[tab]おう！[tab]聞いたかい？
[tab]何でも事件解決の重要証人が、パラベラムって
[tab]バーに現れるらしいぜ。[wait][clear][end]

msg_147:
[color(yellow)]下町おやじ[color(white)]
[tab]事件解決の重要証人が現れるってんで
[tab]期待してたんだが、マスコミも警察も、
[tab]証人を逃がしちまったらしいんだ。[wait][clear][color(yellow)]下町おやじ[color(white)]
[tab]まったく、なってねぇよなぁ。[wait][clear][end]

msg_148:
[color(yellow)]下町おやじ[color(white)]
[tab]レッツ・ポジティブシンキングだぁ！
[tab]大丈夫！[tab]世界はきっとよくなるぜぃ。
[tab]全ては前向き、世直し様々とくらぁ！[wait][clear][end]

msg_149:
[color(yellow)]下町おやじ[color(white)]
[tab]レッツ・ポジティブシンキングだぁ！
[tab]大丈夫！[tab]街が飛んだら世界は再生でぃ。
[tab]穢れが消えて、楽園登場とくらぁ！
[wait][clear][end]

msg_150:
[color(yellow)]下町おやじ[color(white)]
[tab]レッツ・ポジティブシンキングだぁ！
[tab]大丈夫！[tab]地震はすべての始まりでぃ。
[tab]迷いを断ち切りゃ動じぬ心とくらぁ！[wait][clear][end]

msg_151:
[color(yellow)]下町おやじ[color(white)]
[tab]レッツ・ポジティブシンキングだぁ！
[tab]大丈夫！[tab]こいつぁ予定どおりだぜぃ。
[tab]古きを捨てて、さあ新世界とくらぁ！[wait][clear][end]

msg_152:
[color(yellow)]下町おやじ[color(white)]
[tab]こうなりゃやけくそシンキングだぁ！
[tab]とりあえず、安全な場所でも捜して、
[tab]飯もって隠れてりゃ助かるだろ！[wait][clear][color(yellow)]下町おやじ[color(white)]
[tab]ダメならまわりも道連れでい！[wait][clear][end]

msg_153:
[color(yellow)]下町おやじ[color(white)]
[tab]なんでもゾディアックってぇクラブは
[tab]中が迷路になってるらしいなぁ！[wait][clear][color(yellow)]下町おやじ[color(white)]
[tab]やるねぇ、奇抜だよ。
[tab]いっちょ、この俺が制覇してやるか！[wait][clear][end]

msg_154:
[color(yellow)]下町おやじ[color(white)]
[tab]春日山高校に妖怪がでたんだってよ！
[tab]テケテケとかいう名の変なやつなんだが、
[tab]生徒さんも難儀な事だねぇ。[wait][clear][end]

msg_155:
[color(yellow)]下町おやじ[color(white)]
[tab]宝石屋が腕に自信があるからとかで、
[tab]武器や防具の加工も引き受けるそうじゃないか。
[tab]職人の意地ってぇやつだね。[wait][clear][end]

msg_156:
[color(yellow)]下町おやじ[color(white)]
[tab]相性占いなんて、気にしてちゃ始まらねえだろ。
[tab]珠閒瑠ジニーだか何だか知らないが、
[tab]皆ちょっと騒ぎ過ぎじゃないかね。[wait][clear][end]

msg_157:
[color(yellow)]下町おやじ[color(white)]
[tab]珠閒瑠ジニーのインチキ占い師！
[tab]最近、ワンロン占い始めて変わったらしいな。
[tab]バカバカ当たるって評判だぜ。[wait][clear][end]

msg_158:
[color(yellow)]下町おやじ[color(white)]
[tab]パラベラムってバーじゃ武器を扱ってるって
[tab]噂になってるぜ。[wait][clear][color(yellow)]下町おやじ[color(white)]
[tab]バーにタバコとヤバい話はつきものってね。
[tab]ま、今の若者には古い話だがな。
[tab]ガハハ。[wait][clear][end]

msg_159:
[color(yellow)]下町おやじ[color(white)]
[tab]東亜ディフェンスが最近儲かってるらしいね。
[tab]防具の品揃えをよくしたってぇ話だよ。
[tab]ちょいと様子でも見に行くか。[wait][clear][end]

msg_160:
[color(yellow)]下町おやじ[color(white)]
[tab]東亜ディフェンスが最近儲かってるらしいね。
[tab]武器も売り始めたって話だよ。
[tab]ちょいと様子でも見に行くか。[wait][clear][end]

msg_161:
[color(yellow)]下町おやじ[color(white)]
[tab]しらいしの女将が人さがしの仕事をしてるってよ。
[tab]そんな商売がやってけるかどうかは知らねぇが、
[tab]どんな客が来るのかは興味があるよな。[wait][clear][end]

msg_162:
[color(yellow)]気の弱い男[color(white)]
[tab]春日祭で[color(orange)]妖怪テケテケを見た[color(white)]んだよ。
[tab]なのに誰も信用してくれないんだ。[wait][clear][color(yellow)]気の弱い男[color(white)]
[tab]誰か実在する証拠を取ってきてくれないかな…
[tab]そういえばあのテケテケ…
[tab]名札つけてたっけ？[wait][clear][end]

msg_163:
[color(yellow)]気の弱い男[color(white)]
[tab]誰か実在する証拠を取ってきてくれないかな…
[tab]テケテケの名札でもあれば、
[tab]みんな信じてくれると思うんだけど。[wait][clear][end]

msg_164:
[color(yellow)]気の弱い男[color(white)]
[tab]いやぁ、君たちのおかげで皆も信用してくれたよ。
[tab]本当にありがとう。[wait][clear][end]

msg_165:
[color(yellow)]気の弱い男[color(white)]
[tab]こ、これはまさしくテケテケの名札！
[tab]ありがとう。これでみんなを見返せるよ。
[tab]じゃ、これお礼の気持ちだから。[wait][clear][color(green)][tab]ソーマを手に入れた。[wait][clear][end]

msg_166:
[color(yellow)]仮だ！！[color(white)]
[tab]ダミーデータ[wait][clear][end]

msg_167:
[color(yellow)]うらら[color(white)]
[tab]駅ビルへいくのかい？[delay(20)]
[tab]今は急いでるからさ、買い物なら後にしようよ。[wait][clear][end]

msg_168:
[color(white)]ここには用は無い[wait][clear][end]

msg_169:
[color(yellow)]パオフゥ[color(white)]
[tab]おい、今はこんなところで油を売ってる
[tab]場合じゃねぇだろ。
[tab]いくぞ。[wait][clear][end]

msg_170:
[color(yellow)]うらら[color(white)]
[tab]全部のカタがついたら、一度ゆっくりと
[tab]ウィンドウショッピングにでも来たいよね。[delay(15)]
[tab]さ、行こ。[wait][clear][end]

msg_171:
[color(yellow)]克哉[color(white)]
[tab]坂上ビル…ただのオフィスみたいだ。
[tab]他人のビルに勝手に入ったら不法侵入になるぞ。
[tab]用もないし、別のところに行こう。[wait][clear][end]

msg_172:
[tab][color(green)]ここには用は無い。[color(white)][wait][clear][end]

msg_173:
[color(yellow)]パオフゥ[color(white)]
[tab]坂上ビル…こんな所になんのようだ？[delay(15)]
[tab]俺がいうのも何だが、
[tab]不法侵入はやめておいたほうがいいと思うぜ。[wait][clear][end]

msg_174:
[color(yellow)]うらら[color(white)]
[tab]特に怪しいところもない普通のビルだよ？
[tab]用もないし、さっさと次ぎいきましょ。[wait][clear][end]
