function M501()
{
    bitGet(var_0, TBIT_501);
    bez(var_0, label_82);
    bitGet(var_0, MBIT_MI_MAIHIME);
    bitGet(var_1, MBIT_MI_TATUNOSIN);
    bitGet(var_2, MBIT_MI_HANAKOTOBA);
    bitGet(var_3, MBIT_MI_DENNSETU);
    bitGet(var_4, MBIT_MI_DEVIL10);
    bitGet(var_5, MBIT_MI_DEVIL9);
    bitGet(var_6, MBIT_MI_DEVIL8);
    bitGet(var_7, MBIT_MI_DEVIL7);
    bitGet(var_8, MBIT_MI_DEVIL6);
    bitGet(var_9, MBIT_MI_DEVIL5);
    bitGet(var_a, MBIT_MI_DEVIL4);
    bitGet(var_b, MBIT_MI_DEVIL3);
    bitGet(var_c, MBIT_MI_DEVIL2);
    bitGet(var_d, MBIT_MI_DEVIL1);
    bnz(var_0, label_fe);
    bnz(var_1, label_10c);
    bnz(var_2, label_11a);
    bnz(var_3, label_120);
    bnz(var_4, label_126);
    bnz(var_5, label_12c);
    bnz(var_6, label_132);
    bnz(var_7, label_138);
    bnz(var_8, label_13e);
    bnz(var_9, label_144);
    bnz(var_a, label_14a);
    bnz(var_b, label_150);
    bnz(var_c, label_156);
    bnz(var_d, label_15c);
    bitGet(var_0, MBIT_MI_PELPELBUKI);
    bitGet(var_1, MBIT_DPELPELCADE);
    bitGet(var_2, MBIT_DPELPELITEM);
    bitGet(var_3, MBIT_DPELPELAKUSE);
    bitGet(var_4, MBIT_DPELPELBOUGU);
    bitGet(var_5, MBIT_DPELPELBUKI);
    bez(var_0, label_2a);
    bnz(var_1, label_162);
    bnz(var_2, label_168);
    bnz(var_3, label_16e);
    bnz(var_4, label_174);
    bnz(var_5, label_17a);
  label_2a:
    bitGet(var_3, MBIT_MI_MAGICKITEM);
    bitGet(var_4, MBIT_DMAGICKCADE);
    bitGet(var_5, MBIT_DMAGICKITEM);
    bitGet(var_6, MBIT_MI_BATOLUBUKI);
    bitGet(var_7, MBIT_HBATOLUAKUSE);
    bitGet(var_8, MBIT_HBATOLUBOUGU);
    bitGet(var_9, MBIT_HBATOLUBUKI);
    bitGet(var_a, MBIT_MI_SKYMAP);
    bitGet(var_b, MBIT_MI_JEWKOUNAN);
    bitGet(var_c, MBIT_MI_JEWDEVE);
    bitGet(var_d, MBIT_MI_CLEAOBA);
    bitGet(var_e, MBIT_MI_CLEARM);
    bitGet(var_f, MBIT_HI_CLEDEF);
    bez(var_3, label_3a);
    bnz(var_4, label_180);
    bnz(var_5, label_186);
  label_3a:
    bez(var_6, label_3e);
    bnz(var_7, label_18c);
    bnz(var_8, label_192);
    bnz(var_9, label_198);
  label_3e:
    bnz(var_a, label_19e);
    bnz(var_b, label_1ac);
    bnz(var_c, label_1b2);
    bnz(var_d, label_1b8);
    bez(var_e, label_46);
    bnz(var_f, label_1be);
    bitGet(var_0, MBIT_HI_CLEARM);
    bnz(var_0, label_1c4);
  label_46:
    bitGet(var_0, MBIT_MI_GYPAISHO2);
    bitGet(var_1, MBIT_MI_GYPAISHO1);
    bnz(var_0, label_1ca);
    bnz(var_1, label_1d0);
    bitGet(var_0, MBIT_MI_GYPSTART);
    bitGet(var_1, MBIT_MI_ETEHENNI);
    bitGet(var_2, MBIT_MI_ROSAHENNI);
    bitGet(var_3, TBIT_HE_RA);
    bitGet(var_4, TBIT_HE_RB);
    bitGet(var_5, MBIT_MI_ROSADEF);
    bitGet(var_6, MBIT_MI_BARHENNI);
    bitGet(var_7, MBIT_MI_BARARM);
    bitGet(var_8, MBIT_MI_GIGACD2);
    bitGet(var_9, MBIT_MI_GIGACD1);
    bitGet(var_a, MBIT_MI_MUSLOT);
    bitGet(var_b, MBIT_HI_MUPOKER);
    bitGet(var_c, MBIT_HI_MUBJ);
    bitGet(var_d, MBIT_HI_MUSLOT);
    bitGet(var_e, MBIT_MI_TONYITEM);
    bitGet(var_f, MBIT_HI_TONYACCE);
    bnz(var_0, label_1d6);
    bnz(var_1, label_1dc);
    bnz(var_2, label_1e2);
    bnz(var_3, label_1e9);
    bnz(var_4, label_1f1);
    bnz(var_5, label_1ff);
    bnz(var_6, label_205);
    bnz(var_7, label_20b);
    bnz(var_8, label_211);
    bnz(var_9, label_217);
    bez(var_a, label_68);
    bnz(var_b, label_21d);
    bnz(var_c, label_21d);
    bnz(var_d, label_21d);
  label_68:
    bez(var_e, label_6c);
    bnz(var_f, label_223);
    bitGet(var_0, MBIT_HI_TONYITEM);
    bnz(var_0, label_229);
  label_6c:
    bitGet(var_0, MBIT_MI_TOAARM);
    bitGet(var_1, MBIT_HI_TOADEF);
    bitGet(var_2, MBIT_HI_TOAARM);
    bitGet(var_3, MBIT_MI_SIRAHENNI);
    bitGet(var_4, MBIT_MI_SIRAMAN);
    bitGet(var_5, MBIT_MI_KAORIHENNI);
    bitGet(var_6, TBIT_HE_KA);
    bitGet(var_7, TBIT_HE_KB);
    bitGet(var_8, MBIT_MI_JIKANDUP);
    bitGet(var_9, MBIT_MI_JIKANSELL);
    bitGet(var_a, MBIT_MI_ZODI2F);
    bez(var_0, label_7a);
    bnz(var_1, label_22f);
    bnz(var_2, label_235);
  label_7a:
    bnz(var_3, label_23b);
    bnz(var_4, label_241);
    bnz(var_5, label_247);
    bnz(var_6, label_24e);
    bnz(var_7, label_256);
    bnz(var_8, label_26a);
    bnz(var_9, label_270);
    bnz(var_a, label_f8);
  label_82:
    bitGet(var_0, EBIT_E00B8);
    bitGet(var_1, EBIT_E00AF);
    bitGet(var_8, EBIT_E009F);
    bitGet(var_2, EBIT_E008C);
    bitGet(var_3, EBIT_E0085);
    bitGet(var_4, EBIT_E007B);
    bitGet(var_5, EBIT_E0077);
    bitGet(var_6, EBIT_E006F);
    bitGet(var_7, EBIT_E0046);
    bitGet(var_9, MBIT_HI_NANJOTOUJO);
    bitGet(var_a, MBIT_HI_ERITOUJO);
    bitGet(var_b, EBIT_E003E);
    bitGet(var_c, EBIT_E0038);
    bitGet(var_d, EBIT_E0033);
    bitGet(var_e, EBIT_E002B);
    bitGet(var_f, EBIT_E0018);
    bnz(var_0, label_f3);
    bnz(var_1, label_ee);
    bnz(var_8, label_e9);
    bnz(var_2, label_e4);
    bnz(var_3, label_df);
    bnz(var_4, label_da);
    bnz(var_5, label_d5);
    bnz(var_6, label_d0);
    bez(var_7, label_9d);
    bnz(var_9, label_c6);
    bnz(var_a, label_cb);
  label_9d:
    bnz(var_9, label_bc);
    bnz(var_a, label_c1);
    bnz(var_b, label_b7);
    bnz(var_c, label_b2);
    bnz(var_d, label_ad);
    bnz(var_e, label_a8);
    ref_a3 = dialogAlloc();
    ref_a4 = msgShow(msg_0);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]あら？[tab]舞耶ちゃんじゃない。[delay(10)]
[tab]今日もお仕事なの？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あんまり変な取材してちゃダメよー
[tab]最近、危ない事件が多いんだから、
[tab]巻き込まれたりしたら大変だからね。[wait][clear]
***************************************/
    wait(ref_a4);
    dialogFree(ref_a3);
    b(label_276);
  label_a8:
    ref_a8 = dialogAlloc();
    ref_a9 = msgShow(msg_1);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]空の科学館が凄い事になったわねー！
[tab]何か詳しい事知らない？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]いきなり燃えたと思ったら、
[tab]レストランの飛行船が空を飛んじゃうし…
[tab]おばさん腰抜かしそうだわ。[wait][clear]
***************************************/
    wait(ref_a9);
    dialogFree(ref_a8);
    b(label_276);
  label_ad:
    ref_ad = dialogAlloc();
    ref_ae = msgShow(msg_2);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]今朝テレビを見ていたら、空の科学館が
[tab]子供の火遊びで全焼した、なんて言ってたのよ。
[tab]それはいいけど飛行船は何で飛んだのかしら？[wait][clear]
***************************************/
    wait(ref_ae);
    dialogFree(ref_ad);
    b(label_276);
  label_b2:
    ref_b2 = dialogAlloc();
    ref_b3 = msgShow(msg_3);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]私見ちゃったのよ、南条財閥の御曹司！
[tab]週刊誌で何度も見てるから間違い無いわ。
[tab]この街の高級ホテルに宿泊しているらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]お金持ちで、しかも結構いい男なのよぉ。
[tab]おばさんが、あと２０才若かったらねぇ…[delay(15)]
[tab]舞耶ちゃんどう？[tab]狙ってみたら。[wait][clear]
***************************************/
    wait(ref_b3);
    dialogFree(ref_b2);
    b(label_276);
  label_b7:
    ref_b7 = dialogAlloc();
    ref_b8 = msgShow(msg_4);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＪＯＫＥＲになった人が誘拐されてるって話よ。
[tab]人を呪わば穴二つって言葉があるけど本当よねぇ。
[tab]でも、警察は何をしてるのかしら。[wait][clear]
***************************************/
    wait(ref_b8);
    dialogFree(ref_b7);
    b(label_276);
  label_bc:
    ref_bc = dialogAlloc();
    ref_bd = msgShow(msg_5);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、ちょっと聞いた？
[tab]何でも今回の事件の重要な情報を握る人物が、
[tab]いるんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]もうすぐバーに現れるらしいって、
[tab]もう、街中その話で持ちきりよ。
[tab]私も見に行ってみようかしら。[wait][clear]
***************************************/
    wait(ref_bd);
    dialogFree(ref_bc);
    b(label_276);
  label_c1:
    ref_c1 = dialogAlloc();
    ref_c2 = msgShow(msg_6);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、ちょっと聞いた？
[tab]何でも今回の事件の重要な情報を握る人物が、
[tab]いるんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]しかも女性だっていうのよ！
[tab]びっくりよねぇ。
[tab]女スパイなのかしら？[wait][clear]
***************************************/
    wait(ref_c2);
    dialogFree(ref_c1);
    b(label_276);
  label_c6:
    ref_c6 = dialogAlloc();
    ref_c7 = msgShow(msg_7);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]さっき保険会社の調査員って人に
[tab]いろいろ聞かれたんだけど、大変みたいねぇ。
[tab]事件、事件で支払いばっかりみたいよ。[wait][clear]
***************************************/
    wait(ref_c7);
    dialogFree(ref_c6);
    b(label_276);
  label_cb:
    ref_cb = dialogAlloc();
    ref_cc = msgShow(msg_8);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]桐島[tab]英理子って人気モデルがいるんだけど、
[tab]最近見ないと思ったらストーカー事件に
[tab]巻き込まれてるらしいんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]怖いわねぇ。私も気をつけないと。
[tab]舞耶ちゃんも気をつけなさいよ。[wait][clear]
***************************************/
    wait(ref_cc);
    dialogFree(ref_cb);
    b(label_276);
  label_d0:
    ref_d0 = dialogAlloc();
    ref_d1 = msgShow(msg_9);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]あら、舞耶ちゃんじゃない。
[tab]あなた、講演会にいった？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]お隣の奥さんも行ったらしくて、世界が変わった
[tab]って言うんだけど、あんまり強く勧められると
[tab]何だか怖くてね。[delay(15)]どうしようかしら？[wait][clear]
***************************************/
    wait(ref_d1);
    dialogFree(ref_d0);
    b(label_276);
  label_d5:
    ref_d5 = dialogAlloc();
    ref_d6 = msgShow(msg_10);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]事件、事件で疲れたのかしらねぇ。
[tab]前にも同じような事があったような気がして
[tab]仕方ないのよ。[wait][clear]
***************************************/
    wait(ref_d6);
    dialogFree(ref_d5);
    b(label_276);
  label_da:
    ref_da = dialogAlloc();
    ref_db = msgShow(msg_11);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]今回の事件は新世塾っていう悪の組織が
[tab]やった事なんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]普通なら信じられないけど、これだけ事件が
[tab]起こった後だと信じるしかないわよねぇ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]しかも、新世塾はもっと恐ろしい事を
[tab]考えてるらしいのよ。
[tab]おばさん、どうしたらいいのかしら？[wait][clear]
***************************************/
    wait(ref_db);
    dialogFree(ref_da);
    b(label_276);
  label_df:
    ref_df = dialogAlloc();
    ref_e0 = msgShow(msg_12);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]自衛隊のトラックが走り回ってるかと思ったら、
[tab]どかーん、バンバンって凄い音でしょ？
[tab]もう戦争が始まったかと思ったわ！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]いったい何があったのかしら？
[tab]ほんと、物騒な世の中になっちゃったわ。[wait][clear]
***************************************/
    wait(ref_e0);
    dialogFree(ref_df);
    b(label_276);
  label_e4:
    ref_e4 = dialogAlloc();
    ref_e5 = msgShow(msg_13);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]あ、舞耶ちゃん！
[tab]さっき、凄い地震があったでしょ。
[tab]お互い無事で良かったわねぇ。[wait][clear]
***************************************/
    wait(ref_e5);
    dialogFree(ref_e4);
    b(label_276);
  label_e9:
    ref_e9 = dialogAlloc();
    ref_ea = msgShow(msg_14);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ちょっと、ちょっと聞いた？
[tab]鳴海区の地下鉄工事、新世塾が遺跡を
[tab]発掘する為にやってたウソの工事なんだって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私、市議会選挙で地下鉄工事推進派に
[tab]票を入れてたのよ。
[tab]きっとあの議員も新世塾の仲間だったんだわ！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]ああ、もう何てことでしょ！
[tab]これからは絶対アイツには票を入れたりしないわ！[wait][clear]
***************************************/
    wait(ref_ea);
    dialogFree(ref_e9);
    b(label_276);
  label_ee:
    ref_ee = dialogAlloc();
    ref_ef = msgShow(msg_15);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ま、街が飛んじゃってもう何がなんだか…[delay(15)]
[tab]逃げようにも逃げる場所もないし、
[tab]もう私たち、お終いなのかしら…[wait][clear]
***************************************/
    wait(ref_ef);
    dialogFree(ref_ee);
    b(label_276);
  label_f3:
    ref_f3 = dialogAlloc();
    ref_f4 = msgShow(msg_16);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]お、落ち着きなさいよ。
[tab]大丈夫、大丈夫。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]きっとみんな助かるからね。[delay(20)]
[tab]助かるのよね？
[tab]とにかく落ち着かなきゃ…[wait][clear]
***************************************/
    wait(ref_f4);
    dialogFree(ref_f3);
    b(label_276);
  label_f8:
    ref_f8 = dialogAlloc();
    ref_f9 = msgShow(msg_17);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ゾディアックの店内はひろーい迷路に
[tab]なってるんですって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]最近の若い人達はそういうのが好きなのかしら。
[tab]変わってるわねぇ。[wait][clear]
***************************************/
    wait(ref_f9);
    dialogFree(ref_f8);
    bitClear(TBIT_501);
    b(label_276);
  label_fe:
    bitGet(var_0, MBIT_HI_TATUNOSIN);
    bnz(var_0, label_106);
    ref_100 = dialogAlloc();
    ref_101 = msgShow(msg_18);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]蓮華台に珠閒瑠城が出現したでしょ？
[tab]昔の話なんだけど、あの城の城主が悪い人でね、
[tab]呪いとかで何人も人を殺してたらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]それで、ついに天野[tab]舞姫っていうお姫様に
[tab]殺されちゃったんですって。
[tab]だからきっとお化けか何かが出るわよ。[wait][clear]
***************************************/
    wait(ref_101);
    dialogFree(ref_100);
    bitClear(TBIT_501);
    b(label_276);
  label_106:
    ref_106 = dialogAlloc();
    ref_107 = msgShow(msg_19);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]昔、珠閒瑠城の悪い城主を倒した侍の、
[tab][suou][tab]辰之進だけど、天野[tab]舞姫ってお姫様と
[tab]二人でやっつけたらしいのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]なんか舞耶ちゃんと名前が似てない？
[tab]あなたもいい人見つけないとね。
[tab]あっはっは。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]って笑ってる場合じゃないわ。
[tab]ほんと、不安で胸がつぶれそうよ。
[tab]おばさん、繊細だから。[wait][clear]
***************************************/
    wait(ref_107);
    dialogFree(ref_106);
    bitClear(TBIT_501);
    b(label_276);
  label_10c:
    bitGet(var_0, MBIT_HI_MAIHIME);
    bnz(var_0, label_114);
    ref_10e = dialogAlloc();
    ref_10f = msgShow(msg_20);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]蓮華台に珠閒瑠城が出現したでしょ？
[tab]昔の話なんだけど、あの城の城主が悪い人でね、
[tab]呪いとかで何人も人を殺してたらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]それで、ついに[suou][tab]辰之進っていう侍に
[tab]殺されちゃったんですって。
[tab]だからきっとお化けか何かが出るわよ。[wait][clear]
***************************************/
    wait(ref_10f);
    dialogFree(ref_10e);
    bitClear(TBIT_501);
    b(label_276);
  label_114:
    ref_114 = dialogAlloc();
    ref_115 = msgShow(msg_21);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]昔、珠閒瑠城の悪い城主を倒した
[tab]天野[tab]舞姫には、[suou][tab]辰之進って言う
[tab]いい人がいて、二人で城主を倒したの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]やっぱり最後に勝つのは愛よね。
[tab]その点うちは…[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]ってなんかすぐ落ち込んじゃうわ。
[tab]ずっと、不安で胸がつぶれそうなのよ。
[tab]おばさん、繊細だから。[wait][clear]
***************************************/
    wait(ref_115);
    dialogFree(ref_114);
    bitClear(TBIT_501);
    b(label_276);
  label_11a:
    ref_11a = dialogAlloc();
    ref_11b = msgShow(msg_22);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]青葉公園の花が話すって聞いたんだけど、
[tab]あれかしら、ロボットでも作ったのかしら？
[tab]一度見に行ってみないといけないわね。[wait][clear]
***************************************/
    wait(ref_11b);
    dialogFree(ref_11a);
    bitClear(TBIT_501);
    b(label_276);
  label_120:
    ref_120 = dialogAlloc();
    ref_121 = msgShow(msg_23);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]伝説だかなんだか知らないけど、
[tab]武器を作って稼いでる職人なんて、
[tab]ろくなもんじゃないわ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]武器があるから、危ない事件が起こるのよ。
[tab]ね、あなたもそう思うでしょ？[wait][clear]
***************************************/
    wait(ref_121);
    dialogFree(ref_120);
    bitClear(TBIT_501);
    b(label_276);
  label_126:
    ref_126 = dialogAlloc();
    ref_127 = msgShow(msg_24);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]あーもう、嫌な話聞いちゃったわ。
[tab]なにが？[tab]って一度しか言わないわよ。[delay(15)]
[tab]くだんよ。く[delay(20)]だ[delay(20)]ん。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]なんでもカス校の防空壕に現れたらしくて、
[tab]予言の犠牲者が続出しているらしいわ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あんまり、くだん、くだんって言っていると、
[tab]向こうから現れるかもしれないから、
[tab]あんまりくだんの話はしないほうがいいわよ。[wait][clear]
***************************************/
    wait(ref_127);
    dialogFree(ref_126);
    bitClear(TBIT_501);
    b(label_276);
  label_12c:
    ref_12c = dialogAlloc();
    ref_12d = msgShow(msg_25);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ムー大陸に呪いのタクシーが現れたって
[tab]言うんだけど、きっとわたしも被害者だわ！！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]いや、こないだね、買い物の帰りにムー大陸の
[tab]前でタクシーを捕まえたんだけど、いつもは
[tab]２２４０円なのに、２３４０円だったのよ！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]道もまったく同じだったんだから！
[tab]まったくひどいと思わない？
[tab]いつか絶対とっちめてやるわ。[wait][clear]
***************************************/
    wait(ref_12d);
    dialogFree(ref_12c);
    bitClear(TBIT_501);
    b(label_276);
  label_132:
    ref_132 = dialogAlloc();
    ref_133 = msgShow(msg_26);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ギガ・マッチョで今度はお爺さんが
[tab]走り回ってるらしいのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]まったく、誰か注意してあげないとだめね。
[tab]店内はバーゲン以外の理由で走っちゃダメだって。
[tab]え、ちがう？[wait][clear]
***************************************/
    wait(ref_133);
    dialogFree(ref_132);
    bitClear(TBIT_501);
    b(label_276);
  label_138:
    ref_138 = dialogAlloc();
    ref_139 = msgShow(msg_27);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]鳴海区に怪人青マントが出たんですって？
[tab]ああ…あの辺りには出かけないほうがいいわね。
[tab]ほんと、物騒な事ばかりで嫌になっちゃうわ。[wait][clear]
***************************************/
    wait(ref_139);
    dialogFree(ref_138);
    bitClear(TBIT_501);
    b(label_276);
  label_13e:
    ref_13e = dialogAlloc();
    ref_13f = msgShow(msg_28);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]鳴海区に怪人赤マントが出たんですって？
[tab]ああ…あの辺りには出かけないほうがいいわね。
[tab]ほんと、物騒な事ばかりで嫌になっちゃうわ。[wait][clear]
***************************************/
    wait(ref_13f);
    dialogFree(ref_13e);
    bitClear(TBIT_501);
    b(label_276);
  label_144:
    ref_144 = dialogAlloc();
    ref_145 = msgShow(msg_29);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ちょっと聞いた？
[tab]ケームセンターに恐竜が出たんですって！[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]もう、私ったらびっくりしちゃって。
[tab]最近はどこも危ないわね。
[tab]安心して子供を遊ばせられないわ。[wait][clear]
***************************************/
    wait(ref_145);
    dialogFree(ref_144);
    bitClear(TBIT_501);
    b(label_276);
  label_14a:
    ref_14a = dialogAlloc();
    ref_14b = msgShow(msg_30);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＣＤショップのギガ・マッチョに、
[tab]１００キロババアなんて名乗るお婆さんがいて、
[tab]店内を走り回っているそうよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]元気なのはいいけれど、いい年して非常識にも
[tab]程があるわよね。
[tab]お店の中で走っちゃ迷惑だわ。[wait][clear]
***************************************/
    wait(ref_14b);
    dialogFree(ref_14a);
    bitClear(TBIT_501);
    b(label_276);
  label_150:
    ref_150 = dialogAlloc();
    ref_151 = msgShow(msg_31);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]テレビ局にお化けが出たんですって。
[tab]心霊番組なんかやってたから、
[tab]霊が引き寄せられたのね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あなたも霊関係の仕事をする時は、
[tab]ちゃんとお祓いしないと危ないわよ。[wait][clear]
***************************************/
    wait(ref_151);
    dialogFree(ref_150);
    bitClear(TBIT_501);
    b(label_276);
  label_156:
    ref_156 = dialogAlloc();
    ref_157 = msgShow(msg_32);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ツチノコが出たとかで大騒ぎしてるけど、
[tab]私はカズノコの方がいいわ。
[tab]ツチノコなんて役に立たないもの。[wait][clear]
***************************************/
    wait(ref_157);
    dialogFree(ref_156);
    bitClear(TBIT_501);
    b(label_276);
  label_15c:
    ref_15c = dialogAlloc();
    ref_15d = msgShow(msg_33);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]カス校でテケテケってお化けが出て、
[tab]結構な騒ぎになってるみたいじゃない？
[tab]どうしてこう問題ばかり起こすのかしら。[wait][clear]
***************************************/
    wait(ref_15d);
    dialogFree(ref_15c);
    bitClear(TBIT_501);
    b(label_276);
  label_162:
    ref_162 = dialogAlloc();
    ref_163 = msgShow(msg_34);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも不思議なカードが当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私もさっそく応募しないと。
[tab]はがきの周りを赤く塗っておくと
[tab]当たり易いのよね。[wait][clear]
***************************************/
    wait(ref_163);
    dialogFree(ref_162);
    bitClear(TBIT_501);
    b(label_276);
  label_168:
    ref_168 = dialogAlloc();
    ref_169 = msgShow(msg_35);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも便利な道具が当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私もさっそく応募しないと。
[tab]はがきの周りを赤く塗っておくと
[tab]当たり易いのよね。[wait][clear]
***************************************/
    wait(ref_169);
    dialogFree(ref_168);
    bitClear(TBIT_501);
    b(label_276);
  label_16e:
    ref_16e = dialogAlloc();
    ref_16f = msgShow(msg_36);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]素敵なアクセサリーが当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私もさっそく応募しないと。
[tab]はがきの周りを赤く塗っておくと
[tab]当たり易いのよね。[wait][clear]
***************************************/
    wait(ref_16f);
    dialogFree(ref_16e);
    bitClear(TBIT_501);
    b(label_276);
  label_174:
    ref_174 = dialogAlloc();
    ref_175 = msgShow(msg_37);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも防具が当たるとかで評判よ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]護身グッズって意外とするでしょう？
[tab]こういう懸賞っていいわよねぇ。
[tab]私もさっそく応募しないと。[wait][clear]
***************************************/
    wait(ref_175);
    dialogFree(ref_174);
    bitClear(TBIT_501);
    b(label_276);
  label_17a:
    ref_17a = dialogAlloc();
    ref_17b = msgShow(msg_38);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ねえ、聞いた？
[tab]ファンタジーワールドっていう雑誌の懸賞の事！
[tab]何でも本物の武器が当たるとかで評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]ただでさえ物騒な世の中なのに、
[tab]なんて事するんでしょ。
[tab]ＰＴＡに訴えてやめさせなきゃ。[wait][clear]
***************************************/
    wait(ref_17b);
    dialogFree(ref_17a);
    bitClear(TBIT_501);
    b(label_276);
  label_180:
    ref_180 = dialogAlloc();
    ref_181 = msgShow(msg_39);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]別冊ミラクルの懸賞に応募すると
[tab]不思議なカードが当たるって聞いたんだけど、
[tab]不思議なカードって何かしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]おばさんはやっぱり使っても貯金の減らない
[tab]キャッシュカードがいいわね。
[tab]あはは。[wait][clear]
***************************************/
    wait(ref_181);
    dialogFree(ref_180);
    bitClear(TBIT_501);
    b(label_276);
  label_186:
    ref_186 = dialogAlloc();
    ref_187 = msgShow(msg_40);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]別冊ミラクルの懸賞に応募すると
[tab]特殊なアイテムが当たるって聞いたんだけど
[tab]やっぱり手品セットのことかしら？[wait][clear]
***************************************/
    wait(ref_187);
    dialogFree(ref_186);
    bitClear(TBIT_501);
    b(label_276);
  label_18c:
    ref_18c = dialogAlloc();
    ref_18d = msgShow(msg_41);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]よく知らないんだけど、月刊バトルマスター
[tab]って雑誌、懸賞でアクセサリーが当たるって
[tab]評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]でも、雑誌の名前からして、アクセサリーって
[tab]あれでしょ、勲章とかなんとか。
[tab]私そういうの見るのも嫌だわ。[wait][clear]
***************************************/
    wait(ref_18d);
    dialogFree(ref_18c);
    bitClear(TBIT_501);
    b(label_276);
  label_192:
    ref_192 = dialogAlloc();
    ref_193 = msgShow(msg_42);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]よく知らないんだけど、月刊バトルマスター
[tab]って雑誌、懸賞で本物の防具が当たるって
[tab]評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]雑誌には興味が無いけど、
[tab]物騒なご時世だから防具は欲しいわね。
[tab]一冊買ってみようかしら。[wait][clear]
***************************************/
    wait(ref_193);
    dialogFree(ref_192);
    bitClear(TBIT_501);
    b(label_276);
  label_198:
    ref_198 = dialogAlloc();
    ref_199 = msgShow(msg_43);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]よく知らないんだけど、月刊バトルマスター
[tab]って雑誌、懸賞で本物の武器が当たるって
[tab]評判なのよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]男の子ってそういうの好きじゃない。
[tab]子を持つ親としては心配で心配で。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]危ないから、本屋さんに行って
[tab]販売停止にしてもらうつもりなの。[wait][clear]
***************************************/
    wait(ref_199);
    dialogFree(ref_198);
    bitClear(TBIT_501);
    b(label_276);
  label_19e:
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_1a6);
    ref_1a0 = dialogAlloc();
    ref_1a1 = msgShow(msg_44);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ホテル・プレアデスにちょっと変わった感じの人が
[tab]いるんだけど、見たことあるかしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あのひと、何でも地図を沢山集めてるらしくて、
[tab]いろんな物を持ってるって評判なのよ。
[tab]でも家の見取り図とかあると嫌よね。[wait][clear]
***************************************/
    wait(ref_1a1);
    dialogFree(ref_1a0);
    bitClear(TBIT_501);
    b(label_276);
  label_1a6:
    ref_1a6 = dialogAlloc();
    ref_1a7 = msgShow(msg_45);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]平坂のサトミタダシにちょっと変わった感じの人が
[tab]いるんだけど、見たことあるかしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]あのひと、何でも地図を沢山集めてるらしくて、
[tab]いろんな物を持ってるって評判なのよ。
[tab]秘密のシェルターの地図とか持ってないかしら。[wait][clear]
***************************************/
    wait(ref_1a7);
    dialogFree(ref_1a6);
    bitClear(TBIT_501);
    b(label_276);
  label_1ac:
    ref_1ac = dialogAlloc();
    ref_1ad = msgShow(msg_46);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]パパラチャっていう宝石屋が、
[tab]いつのまにかシーサイドモールに入ってるのよ！
[tab]私びっくりしちゃったわ。[wait][clear]
***************************************/
    wait(ref_1ad);
    dialogFree(ref_1ac);
    bitClear(TBIT_501);
    b(label_276);
  label_1b2:
    ref_1b2 = dialogAlloc();
    ref_1b3 = msgShow(msg_47);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]まあ、武器や防具もいいけどさ、
[tab]何も宝石屋が作る事ないじゃない？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]なんだか、イメージ悪いわぁ。
[tab]そういうことは、よそでやってほしいわ。[wait][clear]
***************************************/
    wait(ref_1b3);
    dialogFree(ref_1b2);
    bitClear(TBIT_501);
    b(label_276);
  label_1b8:
    ref_1b8 = dialogAlloc();
    ref_1b9 = msgShow(msg_48);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]良かったわねぇー[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]何が良かったって？
[tab]副島さんが無事だったのよ！
[tab]クレール・ド・リュンヌの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]どうなったのか気になってたんだけど、
[tab]なんとか脱出して青葉区で
[tab]お店を再開したんですって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]主人には悪いんだけど、
[tab]副島さんって私の好みなのよぉ。
[tab]あと２０才若かったらねぇ…[wait][clear]
***************************************/
    wait(ref_1b9);
    dialogFree(ref_1b8);
    bitClear(TBIT_501);
    b(label_276);
  label_1be:
    ref_1be = dialogAlloc();
    ref_1bf = msgShow(msg_49);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]クレール・ド・リュンヌで防具を売ってるって
[tab]聞いたの。さっそく買いに行かなくちゃ。
[tab]子供と主人の分も必要ね。[wait][clear]
***************************************/
    wait(ref_1bf);
    dialogFree(ref_1be);
    bitClear(TBIT_501);
    b(label_276);
  label_1c4:
    ref_1c4 = dialogAlloc();
    ref_1c5 = msgShow(msg_50);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]クレール・ド・リュンヌで武器を売ってる
[tab]らしいわね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]他のお店ならすぐにでもやめさせるけど、
[tab]副島さんがやる事だからいいわ。
[tab]でも、子供には行かせないようにしないと。[wait][clear]
***************************************/
    wait(ref_1c5);
    dialogFree(ref_1c4);
    bitClear(TBIT_501);
    b(label_276);
  label_1ca:
    ref_1ca = dialogAlloc();
    ref_1cb = msgShow(msg_51);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]珠閒瑠ジニーの占いがまた良くなったんだって。
[tab]なんでも相性占いが細かくなったらしいのよ。
[tab]これはぜひ行ってみないとね。[wait][clear]
***************************************/
    wait(ref_1cb);
    dialogFree(ref_1ca);
    bitClear(TBIT_501);
    b(label_276);
  label_1d0:
    ref_1d0 = dialogAlloc();
    ref_1d1 = msgShow(msg_52);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]珠閒瑠ジニーの相性占いが凄いんですって。
[tab]何が凄いって、どんな相手との相性でも
[tab]占えるらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]本当によく当たるみたいだから、
[tab]ペットを買う時とかに占って貰うといいわよねぇ。
[tab]まあ、アパートだから飼えないけど。[wait][clear]
***************************************/
    wait(ref_1d1);
    dialogFree(ref_1d0);
    bitClear(TBIT_501);
    b(label_276);
  label_1d6:
    ref_1d6 = dialogAlloc();
    ref_1d7 = msgShow(msg_53);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]珠閒瑠ジニーって占い屋さんがあるでしょ？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]これがさっぱり当たらないお店だったんだけど、
[tab]占い方法を変えてから、
[tab]すごく当たり始めたんですって。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]以前、財布を無くした時に、
[tab]「探し物は見つかりません。」って言われて
[tab]怒っちゃったけど、また行ってみようかしら。[wait][clear]
***************************************/
    wait(ref_1d7);
    dialogFree(ref_1d6);
    bitClear(TBIT_501);
    b(label_276);
  label_1dc:
    ref_1dc = dialogAlloc();
    ref_1dd = msgShow(msg_54);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]エステショップのエテーリアがサービスを
[tab]変えたんですって。
[tab]どんなサービスかしら？[tab]チェックしないと。[wait][clear]
***************************************/
    wait(ref_1dd);
    dialogFree(ref_1dc);
    bitClear(TBIT_501);
    b(label_276);
  label_1e2:
    ref_1e2 = dialogAlloc();
    ref_1e3 = msgShow(msg_55);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ロサカンディータのマヌカンさん、
[tab]波にのまれたって聞いたわよ。
[tab]海に行く時は気をつけないといけないわね。[wait][clear]
***************************************/
    wait(ref_1e3);
    dialogFree(ref_1e2);
    bitClear(TBIT_501);
    bitSet(TBIT_501_M);
    b(label_276);
  label_1e9:
    bitGet(var_0, TBIT_501_M);
    bez(var_0, label_1f9);
    ref_1eb = dialogAlloc();
    ref_1ec = msgShow(msg_56);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]おばさん恥ずかしいわぁ。マヌカンさんが
[tab]「波にのまれた」って流行の事だったのね。
[tab]若い人の会話にはついていけないわ。[wait][clear]
***************************************/
    wait(ref_1ec);
    dialogFree(ref_1eb);
    bitClear(TBIT_501);
    b(label_276);
  label_1f1:
    bitGet(var_0, TBIT_501_M);
    bez(var_0, label_1e2);
    ref_1f3 = dialogAlloc();
    ref_1f4 = msgShow(msg_57);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ロサカンディータのマヌカンさん、
[tab]仕事でパリに行ったんですってね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]うらやましいわぁ。
[tab]おフランスでしょお。
[tab]私もマヌカンになろうかしら。[wait][clear]
***************************************/
    wait(ref_1f4);
    dialogFree(ref_1f3);
    bitClear(TBIT_501);
    b(label_276);
  label_1f9:
    ref_1f9 = dialogAlloc();
    ref_1fa = msgShow(msg_58);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]おばさん恥ずかしいわぁ。マヌカンさんが
[tab]「波にのまれた」って流行の事だったのね。
[tab]若い人の会話にはついていけないわ。[wait][clear]
***************************************/
    wait(ref_1fa);
    dialogFree(ref_1f9);
    bitClear(TBIT_501);
    b(label_276);
  label_1ff:
    ref_1ff = dialogAlloc();
    ref_200 = msgShow(msg_59);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]今度、ロサカンディータで防具を
[tab]取り扱い始めたんですってね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]防具ってかっこ悪いのが多いから、
[tab]おしゃれなのがあると嬉しいわね。[wait][clear]
***************************************/
    wait(ref_200);
    dialogFree(ref_1ff);
    bitClear(TBIT_501);
    b(label_276);
  label_205:
    ref_205 = dialogAlloc();
    ref_206 = msgShow(msg_60);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]パラベラムってバーの事、聞いたことある？
[tab]何でも用心棒を雇ったらしいわよ。
[tab]何か危ない商売でもしてるのかしら。[wait][clear]
***************************************/
    wait(ref_206);
    dialogFree(ref_205);
    bitClear(TBIT_501);
    b(label_276);
  label_20b:
    ref_20b = dialogAlloc();
    ref_20c = msgShow(msg_61);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ここだけの話、パラベラムっていうバーは
[tab]武器の密売をやってたらしいわよ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]で、こんなご時世になったんで、
[tab]大っぴらに売買しているらしいわ。
[tab]気をつけたほうが良いわよ。[wait][clear]
***************************************/
    wait(ref_20c);
    dialogFree(ref_20b);
    bitClear(TBIT_501);
    b(label_276);
  label_211:
    ref_211 = dialogAlloc();
    ref_212 = msgShow(msg_62);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＣＤショップのギガ・マッチョでマンボのＣＤを
[tab]売ってるらしいんだけど、どんな内容かしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]隠して売ってるから、
[tab]教育上良くない内容じゃないかって心配なのよ。[wait][clear]
***************************************/
    wait(ref_212);
    dialogFree(ref_211);
    bitClear(TBIT_501);
    b(label_276);
  label_217:
    ref_217 = dialogAlloc();
    ref_218 = msgShow(msg_63);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＣＤショップのギガ・マッチョでロックのＣＤを
[tab]売ってるらしいんだけど、どんな内容かしら？[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]隠して売ってるから、
[tab]教育上良くない内容じゃないかって心配なのよ。[wait][clear]
***************************************/
    wait(ref_218);
    dialogFree(ref_217);
    bitClear(TBIT_501);
    b(label_276);
  label_21d:
    ref_21d = dialogAlloc();
    ref_21e = msgShow(msg_64);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]テレビゲームですら許せないのに、ムー大陸は
[tab]今度ギャンブルを始めたそうじゃないの！
[tab]許せないわ。すぐやめさせないと。[wait][clear]
***************************************/
    wait(ref_21e);
    dialogFree(ref_21d);
    bitClear(TBIT_501);
    b(label_276);
  label_223:
    ref_223 = dialogAlloc();
    ref_224 = msgShow(msg_65);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]トニーの露店のアクセサリーが
[tab]評判なんだけど、おばさんはちょっとね。
[tab]やっぱりデパートで買うのが一番だわ。[wait][clear]
***************************************/
    wait(ref_224);
    dialogFree(ref_223);
    bitClear(TBIT_501);
    b(label_276);
  label_229:
    ref_229 = dialogAlloc();
    ref_22a = msgShow(msg_66);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]トニーの露店でお守りみたいなのを
[tab]売ってるらしいんだけど、どうなのかしら？
[tab]ああいう店って苦手なのよ。[wait][clear]
***************************************/
    wait(ref_22a);
    dialogFree(ref_229);
    bitClear(TBIT_501);
    b(label_276);
  label_22f:
    ref_22f = dialogAlloc();
    ref_230 = msgShow(msg_67);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]東亜ディフェンスっていうお店が
[tab]防具の販売を強化したんですってね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]やっぱり危ないご時世だから、
[tab]自分の身は自分で守らないといけない
[tab]ってことなのかしら。[wait][clear]
***************************************/
    wait(ref_230);
    dialogFree(ref_22f);
    bitClear(TBIT_501);
    b(label_276);
  label_235:
    ref_235 = dialogAlloc();
    ref_236 = msgShow(msg_68);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]東亜ディフェンスっていうお店で
[tab]武器の販売を始めたらしいの。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]こういうご時世だからって、
[tab]武器なんか売ってたら、もっと危なくなるわ。
[tab]おばさん、絶対反対よ。[wait][clear]
***************************************/
    wait(ref_236);
    dialogFree(ref_235);
    bitClear(TBIT_501);
    b(label_276);
  label_23b:
    ref_23b = dialogAlloc();
    ref_23c = msgShow(msg_69);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]赤提灯しらいしの女将さんが、
[tab]長年の夢を実現したって聞いたけど、
[tab]うらやましい話よね。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]私も若い頃はいろいろあったけど、
[tab]今じゃ家事に追われる毎日ですもの。[wait][clear]
***************************************/
    wait(ref_23c);
    dialogFree(ref_23b);
    bitClear(TBIT_501);
    b(label_276);
  label_241:
    ref_241 = dialogAlloc();
    ref_242 = msgShow(msg_70);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]赤提灯しらいしの女将さん、
[tab]人さがしの仕事なんてしてたんだね。
[tab]知らなかったわ。[wait][clear][color(yellow)]近所のおばさん[color(white)]
[tab]とは言っても、人を捜す事なんて滅多にないし、
[tab]関係ないといえば関係ないんだけどね。[wait][clear]
***************************************/
    wait(ref_242);
    dialogFree(ref_241);
    bitClear(TBIT_501);
    b(label_276);
  label_247:
    ref_247 = dialogAlloc();
    ref_248 = msgShow(msg_71);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＫＡＯＲＩが閉まってたって聞いたんだけど、
[tab]あそこはたしか年中無休だったでしょ？
[tab]風邪でもひいたのかしら。[wait][clear]
***************************************/
    wait(ref_248);
    dialogFree(ref_247);
    bitClear(TBIT_501);
    bitSet(TBIT_501_K);
    b(label_276);
  label_24e:
    bitGet(var_0, TBIT_501_K);
    bez(var_0, label_25e);
    ref_250 = dialogAlloc();
    ref_251 = msgShow(msg_72);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＫＡＯＲＩが閉まってたのは、香ちゃんが
[tab]買いだしに行ってたからだって？
[tab]なあんだ。心配して損しちゃったわ。[wait][clear]
***************************************/
    wait(ref_251);
    dialogFree(ref_250);
    bitClear(TBIT_501);
    b(label_276);
  label_256:
    bitGet(var_0, TBIT_501_K);
    bez(var_0, label_264);
    ref_258 = dialogAlloc();
    ref_259 = msgShow(msg_73);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]香ちゃん、やっぱり風邪でＫＡＯＲＩは
[tab]お休みだって？
[tab]あらあら、体には気をつけないとねぇ。[wait][clear]
***************************************/
    wait(ref_259);
    dialogFree(ref_258);
    bitClear(TBIT_501);
    b(label_276);
  label_25e:
    ref_25e = dialogAlloc();
    ref_25f = msgShow(msg_74);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]ＫＡＯＲＩが新商品を売り始めたんだってね！
[tab]しかも、海外のすっごくいいやつなんでしょ？
[tab]早く買いに行かないと売り切れちゃうわ。[wait][clear]
***************************************/
    wait(ref_25f);
    dialogFree(ref_25e);
    bitClear(TBIT_501);
    b(label_276);
  label_264:
    ref_264 = dialogAlloc();
    ref_265 = msgShow(msg_75);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]香ちゃんが風邪でＫＡＯＲＩはお休みだって？
[tab]あらあら、体には気をつけないとねぇ。[wait][clear]
***************************************/
    wait(ref_265);
    dialogFree(ref_264);
    bitClear(TBIT_501);
    b(label_276);
  label_26a:
    ref_26a = dialogAlloc();
    ref_26b = msgShow(msg_76);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]時間城で魔法のカードの複製も
[tab]してくれるんですって。
[tab]いったいどんな人がお客さんなんだろうね。[wait][clear]
***************************************/
    wait(ref_26b);
    dialogFree(ref_26a);
    bitClear(TBIT_501);
    b(label_276);
  label_270:
    ref_270 = dialogAlloc();
    ref_271 = msgShow(msg_77);
/***************************************
[color(yellow)]近所のおばさん[color(white)]
[tab]時間城で魔法のカードを売ってるって
[tab]聞いたけど、いかにもって感じね。
[tab]すごく怪しい感じのお店ですもの。[wait][clear]
***************************************/
    wait(ref_271);
    dialogFree(ref_270);
    bitClear(TBIT_501);
    b(label_276);
  label_276:
}

function M502()
{
    bitGet(var_0, TBIT_502);
    bez(var_0, label_2f9);
    bitGet(var_0, MBIT_MI_MAIHIME);
    bitGet(var_1, MBIT_MI_TATUNOSIN);
    bitGet(var_2, MBIT_MI_HANAKOTOBA);
    bitGet(var_3, MBIT_MI_DENNSETU);
    bitGet(var_4, MBIT_MI_DEVIL10);
    bitGet(var_5, MBIT_MI_DEVIL9);
    bitGet(var_6, MBIT_MI_DEVIL8);
    bitGet(var_7, MBIT_MI_DEVIL7);
    bitGet(var_8, MBIT_MI_DEVIL6);
    bitGet(var_9, MBIT_MI_DEVIL5);
    bitGet(var_a, MBIT_MI_DEVIL4);
    bitGet(var_b, MBIT_MI_DEVIL3);
    bitGet(var_c, MBIT_MI_DEVIL2);
    bitGet(var_d, MBIT_MI_DEVIL1);
    bnz(var_0, label_37b);
    bnz(var_1, label_389);
    bnz(var_2, label_397);
    bnz(var_3, label_39d);
    bnz(var_4, label_3a3);
    bnz(var_5, label_3a9);
    bnz(var_6, label_3af);
    bnz(var_7, label_3b5);
    bnz(var_8, label_3bb);
    bnz(var_9, label_3c1);
    bnz(var_a, label_3c7);
    bnz(var_b, label_3cd);
    bnz(var_c, label_3d3);
    bnz(var_d, label_3d9);
    bitGet(var_0, MBIT_MI_PELPELBUKI);
    bitGet(var_1, MBIT_DPELPELCADE);
    bitGet(var_2, MBIT_DPELPELITEM);
    bitGet(var_3, MBIT_DPELPELAKUSE);
    bitGet(var_4, MBIT_DPELPELBOUGU);
    bitGet(var_5, MBIT_DPELPELBUKI);
    bez(var_0, label_2a1);
    bnz(var_1, label_3df);
    bnz(var_2, label_3e5);
    bnz(var_3, label_3eb);
    bnz(var_4, label_3f1);
    bnz(var_5, label_3f7);
  label_2a1:
    bitGet(var_3, MBIT_MI_MAGICKITEM);
    bitGet(var_4, MBIT_DMAGICKCADE);
    bitGet(var_5, MBIT_DMAGICKITEM);
    bitGet(var_6, MBIT_MI_BATOLUBUKI);
    bitGet(var_7, MBIT_HBATOLUAKUSE);
    bitGet(var_8, MBIT_HBATOLUBOUGU);
    bitGet(var_9, MBIT_HBATOLUBUKI);
    bitGet(var_a, MBIT_MI_SKYMAP);
    bitGet(var_b, MBIT_MI_JEWKOUNAN);
    bitGet(var_c, MBIT_MI_JEWDEVE);
    bitGet(var_d, MBIT_MI_CLEAOBA);
    bitGet(var_e, MBIT_MI_CLEARM);
    bitGet(var_f, MBIT_HI_CLEDEF);
    bez(var_3, label_2b1);
    bnz(var_4, label_3fd);
    bnz(var_5, label_403);
  label_2b1:
    bez(var_6, label_2b5);
    bnz(var_7, label_409);
    bnz(var_8, label_40f);
    bnz(var_9, label_415);
  label_2b5:
    bnz(var_a, label_41b);
    bnz(var_b, label_429);
    bnz(var_c, label_42f);
    bnz(var_d, label_435);
    bez(var_e, label_2bd);
    bnz(var_f, label_43b);
    bitGet(var_0, MBIT_HI_CLEARM);
    bnz(var_0, label_441);
  label_2bd:
    bitGet(var_0, MBIT_MI_GYPAISHO2);
    bitGet(var_1, MBIT_MI_GYPAISHO1);
    bnz(var_0, label_447);
    bnz(var_1, label_44d);
    bitGet(var_0, MBIT_MI_GYPSTART);
    bitGet(var_1, MBIT_MI_ETEHENNI);
    bitGet(var_2, MBIT_MI_ROSAHENNI);
    bitGet(var_3, TBIT_HE_RA);
    bitGet(var_4, TBIT_HE_RB);
    bitGet(var_5, MBIT_MI_ROSADEF);
    bitGet(var_6, MBIT_MI_BARHENNI);
    bitGet(var_7, MBIT_MI_BARARM);
    bitGet(var_8, MBIT_MI_GIGACD2);
    bitGet(var_9, MBIT_MI_GIGACD1);
    bitGet(var_a, MBIT_MI_MUSLOT);
    bitGet(var_b, MBIT_HI_MUPOKER);
    bitGet(var_c, MBIT_HI_MUBJ);
    bitGet(var_d, MBIT_HI_MUSLOT);
    bitGet(var_e, MBIT_MI_TONYITEM);
    bitGet(var_f, MBIT_HI_TONYACCE);
    bnz(var_0, label_453);
    bnz(var_1, label_459);
    bnz(var_2, label_45f);
    bnz(var_3, label_45f);
    bnz(var_4, label_466);
    bnz(var_5, label_474);
    bnz(var_6, label_47a);
    bnz(var_7, label_480);
    bnz(var_8, label_486);
    bnz(var_9, label_48c);
    bez(var_a, label_2df);
    bnz(var_b, label_492);
    bnz(var_c, label_498);
    bnz(var_d, label_49e);
  label_2df:
    bez(var_e, label_2e3);
    bnz(var_f, label_4a4);
    bitGet(var_0, MBIT_HI_TONYITEM);
    bnz(var_0, label_4aa);
  label_2e3:
    bitGet(var_0, MBIT_MI_TOAARM);
    bitGet(var_1, MBIT_HI_TOADEF);
    bitGet(var_2, MBIT_HI_TOAARM);
    bitGet(var_3, MBIT_MI_SIRAHENNI);
    bitGet(var_4, MBIT_MI_SIRAMAN);
    bitGet(var_5, MBIT_MI_KAORIHENNI);
    bitGet(var_6, TBIT_HE_KA);
    bitGet(var_7, TBIT_HE_KB);
    bitGet(var_8, MBIT_MI_JIKANDUP);
    bitGet(var_9, MBIT_MI_JIKANSELL);
    bitGet(var_a, MBIT_MI_ZODI2F);
    bez(var_0, label_2f1);
    bnz(var_1, label_4b0);
    bnz(var_2, label_4b6);
  label_2f1:
    bnz(var_3, label_4bc);
    bnz(var_4, label_4c2);
    bnz(var_5, label_4c8);
    bnz(var_6, label_4c8);
    bnz(var_7, label_4c8);
    bnz(var_8, label_4ce);
    bnz(var_9, label_4d4);
    bnz(var_a, label_375);
  label_2f9:
    bitGet(var_0, EBIT_E00B8);
    bitGet(var_1, EBIT_E00AF);
    bitGet(var_8, EBIT_E009F);
    bitGet(var_2, EBIT_E008C);
    bitGet(var_3, EBIT_E0085);
    bitGet(var_4, EBIT_E007B);
    bitGet(var_5, EBIT_E0077);
    bitGet(var_6, EBIT_E006F);
    bitGet(var_7, EBIT_E0046);
    bitGet(var_9, MBIT_HI_NANJOTOUJO);
    bitGet(var_a, MBIT_HI_ERITOUJO);
    bitGet(var_b, EBIT_E003E);
    bitGet(var_c, EBIT_E0038);
    bitGet(var_d, EBIT_E0033);
    bitGet(var_e, EBIT_E002B);
    bitGet(var_f, EBIT_E0018);
    bnz(var_0, label_370);
    bnz(var_1, label_36b);
    bnz(var_8, label_366);
    bnz(var_2, label_361);
    bnz(var_3, label_35c);
    bnz(var_4, label_35c);
    bnz(var_5, label_357);
    bnz(var_6, label_352);
    bez(var_7, label_314);
    bnz(var_9, label_348);
    bnz(var_a, label_34d);
  label_314:
    bnz(var_9, label_33e);
    bnz(var_a, label_343);
    bnz(var_b, label_339);
    bnz(var_c, label_329);
    bnz(var_d, label_324);
    bnz(var_e, label_31f);
    ref_31a = dialogAlloc();
    ref_31b = msgShow(msg_78);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]そこに空の科学館があるだろ？
[tab]あのビルに乗ってる飛行船は本物って話だ。
[tab]覚えておいて損はないと思うぜ。[wait][clear]
***************************************/
    wait(ref_31b);
    dialogFree(ref_31a);
    b(label_4da);
  label_31f:
    ref_31f = dialogAlloc();
    ref_320 = msgShow(msg_79);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]空の科学館が燃えちまったな。
[tab]飛行船は俺もいざという時はと思ってたんだが…
[tab]別の逃げ道を考えとかないとな。[wait][clear]
***************************************/
    wait(ref_320);
    dialogFree(ref_31f);
    b(label_4da);
  label_324:
    ref_324 = dialogAlloc();
    ref_325 = msgShow(msg_80);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]空の科学館の一件、実は相当ヤバいらしいな。
[tab]テレビでもみ消しの報道やってたぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]子供の火遊びで全焼したんだと。[delay(10)]
[tab]ボヤならともかく、全焼は不自然だろ。
[tab]これで皆を騙せるとでも思ってるのかね。[wait][clear]
***************************************/
    wait(ref_325);
    dialogFree(ref_324);
    b(label_4da);
  label_329:
    ref_329 = dialogAlloc();
    ref_32a = msgShow(msg_81);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]事件に次ぐ事件で皆は警察を当てにしてるけど、
[tab]下手に信用しないほうがいいぜ。
[tab]裏じゃいろいろ悪どい事もやってんだ。[wait][clear]
***************************************/
    wait(ref_32a);
    dialogFree(ref_329);
    ref_32d = bustupLoad(bustup_23);
    bustupWait(ref_32d);
    ref_32f = bustupAlloc(ref_32d, left, rgb(0,0,0));
    bustupFade(ref_32f, rgb(128,0,0), 30);
    ref_331 = dialogAlloc();
    ref_332 = msgShow(msg_82);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]……[wait][clear]
***************************************/
    wait(ref_332);
    dialogFree(ref_331);
    ref_335 = bustupFade(ref_32f, rgb(0,0,0), 10);
    bustupWait(ref_335);
    bustupFree(ref_32f);
    b(label_4da);
  label_339:
    ref_339 = dialogAlloc();
    ref_33a = msgShow(msg_83);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]そういや俺さ、
[tab]ＪＯＫＥＲになった奴がさらわれるのを見たんだよ
[tab]連中、アジア系のマフィアみたいだったぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]警察に行かないのかって？[delay(15)]
[tab]冗談じゃないぜ。
[tab]俺がつかまったら馬鹿みたいじゃないか。[wait][clear]
***************************************/
    wait(ref_33a);
    dialogFree(ref_339);
    b(label_4da);
  label_33e:
    ref_33e = dialogAlloc();
    ref_33f = msgShow(msg_84);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]街で噂なんだが事件の鍵を握る男がいるらしいな。
[tab]まいったぜ。俺の予想ではそいつは…[delay(15)]
[tab]おっと、これ以上はヤバいな。[wait][clear]
***************************************/
    wait(ref_33f);
    dialogFree(ref_33e);
    b(label_4da);
  label_343:
    ref_343 = dialogAlloc();
    ref_344 = msgShow(msg_85);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]街で噂なんだが事件の鍵を握る女がいるらしいな。
[tab]末世に謎の美女とはおあつらえ向きだぜ。
[tab]これはまさに、俺のためのステージか？[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]え？[tab]なんで美女なのかって？[delay(15)]
[tab]解ってないなぁ。
[tab]秘密めいた女性が美女ってのは定番なんだよ。[wait][clear]
***************************************/
    wait(ref_344);
    dialogFree(ref_343);
    b(label_4da);
  label_348:
    ref_348 = dialogAlloc();
    ref_349 = msgShow(msg_86);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]そういえば、今回の一連の事件の解決には、
[tab]日本でも屈指の財閥が動いてるって話だぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]どこで聞いたって？[delay(15)]
[tab]そりゃ、独自ルートってものがあるのさ。
[tab]深く聞いちゃいけねぇよ。[wait][clear]
***************************************/
    wait(ref_349);
    dialogFree(ref_348);
    b(label_4da);
  label_34d:
    ref_34d = dialogAlloc();
    ref_34e = msgShow(msg_87);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]そういえば、今回の一連の事件の解決には、
[tab]日本でも屈指の財閥が動いてるって話だぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]どこで聞いたって？[delay(15)]
[tab]そりゃ、独自ルートってものがあるのさ。
[tab]深く聞いちゃいけねぇよ。[wait][clear]
***************************************/
    wait(ref_34e);
    dialogFree(ref_34d);
    b(label_4da);
  label_352:
    ref_352 = dialogAlloc();
    ref_353 = msgShow(msg_88);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]皆、穢れ、とやらがよっぽど恐ろしいのか、
[tab]穢れ祓いが大はやり。あちこちで懺悔の講演会さ。
[tab]バカだねぇ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]穢れも自分の一部なんだから、
[tab]他人にどうこうして貰うもんじゃねぇだろ。
[tab]案外、俺たち闇の人間の方が純粋なのかね。[wait][clear]
***************************************/
    wait(ref_353);
    dialogFree(ref_352);
    b(label_4da);
  label_357:
    ref_357 = dialogAlloc();
    ref_358 = msgShow(msg_89);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]最近、妙な白昼夢を見る事があるんだ。
[tab]自分が普通のサラリーマンで、アイドルの
[tab]コンサートチケットを欲しがってるのさ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]ふん。柄でもないぜ。
[tab]俺が普通の生活に耐えられる筈がねぇのにな。
[tab]まあ、誰しも違う自分を持ってるってことかねぇ。[wait][clear]
***************************************/
    wait(ref_358);
    dialogFree(ref_357);
    b(label_4da);
  label_35c:
    ref_35c = dialogAlloc();
    ref_35d = msgShow(msg_90);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ついに新世塾が表に出てきたか…[delay(15)]
[tab]これから凄い事になるな。
[tab]あんた達も程々にしときなよ。[delay(15)]ケガするぜ。[wait][clear]
***************************************/
    wait(ref_35d);
    dialogFree(ref_35c);
    b(label_4da);
  label_361:
    ref_361 = dialogAlloc();
    ref_362 = msgShow(msg_91);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]海のほうで何かあったみたいだぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]周りは地震って騒いでるが揺れ方が違うし、
[tab]ま、地震よりやばい事なのは確かだな。[wait][clear]
***************************************/
    wait(ref_362);
    dialogFree(ref_361);
    b(label_4da);
  label_366:
    ref_366 = dialogAlloc();
    ref_367 = msgShow(msg_92);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]アメノトリフネが鳴海区の地下鉄工事現場で
[tab]見つかった…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]気味が悪いじゃねえか。
[tab]あそこはただの工事現場だったんだぜ。
[tab]何度か入った事があるから間違いねぇ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]新世塾のやつらがよっぽど手際がいいのか、
[tab]それとも…[delay(15)]いや、考え過ぎか。[wait][clear]
***************************************/
    wait(ref_367);
    dialogFree(ref_366);
    b(label_4da);
  label_36b:
    ref_36b = dialogAlloc();
    ref_36c = msgShow(msg_93);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]過去の常識はあっという間に消えちまったな。
[tab]世界の滅亡を目の前にするなんて思わなかったが、
[tab]こんな形の終わりは認めたくないね。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]そりゃ、俺は力のない虫けらかもしれない。
[tab]が、意地ってものはある。[delay(15)]
[tab]納得の行かないエンドは許せないさ。[wait][clear]
***************************************/
    wait(ref_36c);
    dialogFree(ref_36b);
    b(label_4da);
  label_370:
    ref_370 = dialogAlloc();
    ref_371 = msgShow(msg_94);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]肝の据わってない連中が多いようだが、
[tab]騒ぎ立てたところで何にもよくならねぇし、
[tab]いまは、落ち着いている事が大事だ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]あんたもそう思わねぇか？[wait][clear]
***************************************/
    wait(ref_371);
    dialogFree(ref_370);
    b(label_4da);
  label_375:
    ref_375 = dialogAlloc();
    ref_376 = msgShow(msg_95);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ゾディアックってクラブは、
[tab]中が結構広い迷路になってるっていうじゃないか。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]いざという時に逃げ込むのに、使えるな。
[tab]さっそく下調べにいくか。[wait][clear]
***************************************/
    wait(ref_376);
    dialogFree(ref_375);
    bitClear(TBIT_502);
    b(label_4da);
  label_37b:
    bitGet(var_0, MBIT_HI_TATUNOSIN);
    bnz(var_0, label_383);
    ref_37d = dialogAlloc();
    ref_37e = msgShow(msg_96);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]よみがえった珠閒瑠城だけどよ、
[tab]何でも曰く付きのお城らしいぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]城主の澄丸[tab]清忠は呪術の為に虐殺をやったりする
[tab]ひでえ奴だったんだが、最後は天野[tab]舞姫って
[tab]お姫様に殺されちまうんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]自業自得だけど無念だったんだろうね。
[tab]だから怨念が今でも渦巻いてるって訳さ。[wait][clear]
***************************************/
    wait(ref_37e);
    dialogFree(ref_37d);
    bitClear(TBIT_502);
    b(label_4da);
  label_383:
    ref_383 = dialogAlloc();
    ref_384 = msgShow(msg_97);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠城の城主、澄丸[tab]清忠を倒したのは、
[tab][suou][tab]辰之進一人でじゃねえ。
[tab]天野[tab]舞姫ってお姫様と二人でだったらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]もしあんたが珠閒瑠城に行くんなら、
[tab]二人に縁があるところを調べたほうが良いぜ。
[tab]…ま、ただのヤマ感だけどな。[wait][clear]
***************************************/
    wait(ref_384);
    dialogFree(ref_383);
    bitClear(TBIT_502);
    b(label_4da);
  label_389:
    bitGet(var_0, MBIT_HI_MAIHIME);
    bnz(var_0, label_391);
    ref_38b = dialogAlloc();
    ref_38c = msgShow(msg_98);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]よみがえった珠閒瑠城だけどよ、
[tab]何でも曰く付きのお城らしいぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]城主の澄丸[tab]清忠は呪術の為に虐殺をやったりする
[tab]ひでえ奴だったんだが最後は[suou][tab]辰之進って
[tab]侍に切り殺されちまうんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]自業自得だけど無念だったんだろうね。
[tab]だから怨念が今でも渦巻いてるって訳さ。[wait][clear]
***************************************/
    wait(ref_38c);
    dialogFree(ref_38b);
    bitClear(TBIT_502);
    b(label_4da);
  label_391:
    ref_391 = dialogAlloc();
    ref_392 = msgShow(msg_99);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠城の城主、澄丸[tab]清忠を倒したのは、
[tab]天野[tab]舞姫一人でじゃねえ。
[tab][suou][tab]辰之進って侍と二人でだったらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]もしあんたが珠閒瑠城に行くんなら、
[tab]二人に縁があるところを調べたほうが良いぜ。
[tab]…ま、ただのヤマ感だけどな。[wait][clear]
***************************************/
    wait(ref_392);
    dialogFree(ref_391);
    bitClear(TBIT_502);
    b(label_4da);
  label_397:
    ref_397 = dialogAlloc();
    ref_398 = msgShow(msg_100);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]青葉公園の花が話すって本当かね？
[tab]ちょっと信じられない話だが、困ったもんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]あんまり公園が評判になると、
[tab]あの場所で取り引きが出来なくなっちまうぜ。[wait][clear]
***************************************/
    wait(ref_398);
    dialogFree(ref_397);
    bitClear(TBIT_502);
    b(label_4da);
  label_39d:
    ref_39d = dialogAlloc();
    ref_39e = msgShow(msg_101);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]伝説の武器職人アサノタクミ…
[tab]俺としたことが名前も聞いた事無いなんてな。
[tab]ぜひ、評判の腕前を見せてもらいたいものだ。[wait][clear]
***************************************/
    wait(ref_39e);
    dialogFree(ref_39d);
    bitClear(TBIT_502);
    b(label_4da);
  label_3a3:
    ref_3a3 = dialogAlloc();
    ref_3a4 = msgShow(msg_102);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]…くだんが出たらしいな。
[tab]ヤツだけはヤバイ。
[tab]気をつけたほうがいいぞ。[wait][clear]
***************************************/
    wait(ref_3a4);
    dialogFree(ref_3a3);
    bitClear(TBIT_502);
    b(label_4da);
  label_3a9:
    ref_3a9 = dialogAlloc();
    ref_3aa = msgShow(msg_103);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]呪いのタクシー騒ぎがムー大陸で起きてくれて
[tab]助かったぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]いや、ちょっといろいろあってな。
[tab]気にしないでくれ。[wait][clear]
***************************************/
    wait(ref_3aa);
    dialogFree(ref_3a9);
    bitClear(TBIT_502);
    b(label_4da);
  label_3af:
    ref_3af = dialogAlloc();
    ref_3b0 = msgShow(msg_104);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ギガ・マッチョの妖怪、
[tab]まだ別のがいたらしいじゃないか。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]今度は２００キロジジイだとよ。
[tab]まあ、その快速は羨ましいね。[wait][clear]
***************************************/
    wait(ref_3b0);
    dialogFree(ref_3af);
    bitClear(TBIT_502);
    b(label_4da);
  label_3b5:
    ref_3b5 = dialogAlloc();
    ref_3b6 = msgShow(msg_105);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]怪人青マントが、停泊中の客船で
[tab]出没しているらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]カモフラージュにもってこいな事件だぜ。
[tab]マント１つで変装できるんだからな。[wait][clear]
***************************************/
    wait(ref_3b6);
    dialogFree(ref_3b5);
    bitClear(TBIT_502);
    b(label_4da);
  label_3bb:
    ref_3bb = dialogAlloc();
    ref_3bc = msgShow(msg_106);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]怪人赤マントが、停泊中の客船で
[tab]出没しているらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]カモフラージュにもってこいな事件だぜ。
[tab]マント１つで変装できるんだからな。[wait][clear]
***************************************/
    wait(ref_3bc);
    dialogFree(ref_3bb);
    bitClear(TBIT_502);
    b(label_4da);
  label_3c1:
    ref_3c1 = dialogAlloc();
    ref_3c2 = msgShow(msg_107);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]なんでもゲームセンターにムッシーとかいう恐竜が
[tab]出現して、騒ぎになっているらしい。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]みんな近寄らなくなるかと思ったが、
[tab]野次馬も結構いるらしくてね。
[tab]人の入りは相変わらずさ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]ゲームセンターが閑散としてくれれば、
[tab]俺としてはいろいろ好都合だったんだが…
[tab]まあ、仕方ないな。[wait][clear]
***************************************/
    wait(ref_3c2);
    dialogFree(ref_3c1);
    bitClear(TBIT_502);
    b(label_4da);
  label_3c7:
    ref_3c7 = dialogAlloc();
    ref_3c8 = msgShow(msg_108);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ギガ・マッチョの妖怪の噂、どうでもいいが、
[tab]時速１００キロで走れるってのは羨ましいね。
[tab]俺が逃げるときはいつも命がけだからな。[wait][clear]
***************************************/
    wait(ref_3c8);
    dialogFree(ref_3c7);
    bitClear(TBIT_502);
    b(label_4da);
  label_3cd:
    ref_3cd = dialogAlloc();
    ref_3ce = msgShow(msg_109);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠テレビのお化け騒ぎだが…[delay(15)]
[tab]いや、忘れてくれ。
[tab]俺の考え過ぎだろう。[wait][clear]
***************************************/
    wait(ref_3ce);
    dialogFree(ref_3cd);
    bitClear(TBIT_502);
    b(label_4da);
  label_3d3:
    ref_3d3 = dialogAlloc();
    ref_3d4 = msgShow(msg_110);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ツチノコだかなんだか知らないが、
[tab]よくまあ、騒ぎたてるもんだ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]まあ、珍しい動物は金になるから、
[tab]俺も興味が無い訳じゃないが、
[tab]モノが手に入りにくくちゃ商売できないからな。[wait][clear]
***************************************/
    wait(ref_3d4);
    dialogFree(ref_3d3);
    bitClear(TBIT_502);
    b(label_4da);
  label_3d9:
    ref_3d9 = dialogAlloc();
    ref_3da = msgShow(msg_111);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]しかし、カス校ってのはいろいろと
[tab]騒ぎの起きる学校だぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]今度はテケテケとかいう妖怪が現れたんだと。
[tab]まあ、おかげで夜なら逃げ込むのには便利な
[tab]場所になってるし、俺は助かってるがね。[wait][clear]
***************************************/
    wait(ref_3da);
    dialogFree(ref_3d9);
    bitClear(TBIT_502);
    b(label_4da);
  label_3df:
    ref_3df = dialogAlloc();
    ref_3e0 = msgShow(msg_112);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも不思議なカードが当たるとか。
[tab]まあ、俺には必要ない物だけどな。[wait][clear]
***************************************/
    wait(ref_3e0);
    dialogFree(ref_3df);
    bitClear(TBIT_502);
    b(label_4da);
  label_3e5:
    ref_3e5 = dialogAlloc();
    ref_3e6 = msgShow(msg_113);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも特殊なアイテムが当たるとか。
[tab]まあ、俺には必要ない物だけどな。[wait][clear]
***************************************/
    wait(ref_3e6);
    dialogFree(ref_3e5);
    bitClear(TBIT_502);
    b(label_4da);
  label_3eb:
    ref_3eb = dialogAlloc();
    ref_3ec = msgShow(msg_114);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでもアクセサリーが当たるとか。
[tab]まあ、俺は興味ないけどな。[wait][clear]
***************************************/
    wait(ref_3ec);
    dialogFree(ref_3eb);
    bitClear(TBIT_502);
    b(label_4da);
  label_3f1:
    ref_3f1 = dialogAlloc();
    ref_3f2 = msgShow(msg_115);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも防具が当たるとか。
[tab]まあ、俺は十分もってるから必要ないがな。[wait][clear]
***************************************/
    wait(ref_3f2);
    dialogFree(ref_3f1);
    bitClear(TBIT_502);
    b(label_4da);
  label_3f7:
    ref_3f7 = dialogAlloc();
    ref_3f8 = msgShow(msg_116);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ファンタジーワールドの雑誌の懸賞が評判だな。
[tab]なんでも武器が当たるとか。
[tab]ちょっとチェックしとかないとまずいかもな。[wait][clear]
***************************************/
    wait(ref_3f8);
    dialogFree(ref_3f7);
    bitClear(TBIT_502);
    b(label_4da);
  label_3fd:
    ref_3fd = dialogAlloc();
    ref_3fe = msgShow(msg_117);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]別冊ミラクルってどんな雑誌だ？
[tab]懸賞で不思議なカードがもらえるって評判だが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]俺もちょっとそういうのには詳しくないんでね。
[tab]週刊誌になら何度かでた事があるんだけどな。
[tab]まあ、全部匿名だが。[wait][clear]
***************************************/
    wait(ref_3fe);
    dialogFree(ref_3fd);
    bitClear(TBIT_502);
    b(label_4da);
  label_403:
    ref_403 = dialogAlloc();
    ref_404 = msgShow(msg_118);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]別冊ミラクルってどんな雑誌だ？
[tab]懸賞で変わったアイテムがもらえるって評判だが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]俺もちょっとそういうのには詳しくないんでね。
[tab]週刊誌になら何度かでた事があるんだけどな。
[tab]まあ、全部匿名だが。[wait][clear]
***************************************/
    wait(ref_404);
    dialogFree(ref_403);
    bitClear(TBIT_502);
    b(label_4da);
  label_409:
    ref_409 = dialogAlloc();
    ref_40a = msgShow(msg_119);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]知ってるか？[delay(15)][tab]月刊バトルマスターの懸賞は
[tab]本物のアクセサリーが当たるんだぜ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]この本は愛読しているんだが、
[tab]懸賞がイマイチなところだけは不満なんだ。[wait][clear]
***************************************/
    wait(ref_40a);
    dialogFree(ref_409);
    bitClear(TBIT_502);
    b(label_4da);
  label_40f:
    ref_40f = dialogAlloc();
    ref_410 = msgShow(msg_120);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]知ってるか？[delay(15)][tab]月刊バトルマスターの懸賞は
[tab]本物の防具が当たるんだぜ。
[tab]この本は愛読しているから詳しいんだ。[wait][clear]
***************************************/
    wait(ref_410);
    dialogFree(ref_40f);
    bitClear(TBIT_502);
    b(label_4da);
  label_415:
    ref_415 = dialogAlloc();
    ref_416 = msgShow(msg_121);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]知ってるか？[delay(15)][tab]月刊バトルマスターの懸賞は
[tab]本物の武器が当たるんだぜ。
[tab]この本は愛読しているから詳しいんだ。[wait][clear]
***************************************/
    wait(ref_416);
    dialogFree(ref_415);
    bitClear(TBIT_502);
    b(label_4da);
  label_41b:
    bitGet(var_0, EBIT_E00AF);
    bnz(var_0, label_423);
    ref_41d = dialogAlloc();
    ref_41e = msgShow(msg_122);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ホテル・プレアデスのエボニーに
[tab]地図を集めている男がいるらしいが…
[tab]見取り図とかは扱ってねえかな？[wait][clear]
***************************************/
    wait(ref_41e);
    dialogFree(ref_41d);
    bitClear(TBIT_502);
    b(label_4da);
  label_423:
    ref_423 = dialogAlloc();
    ref_424 = msgShow(msg_123);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]平坂区のサトミタダシに
[tab]地図を集めている男がいるらしいが…
[tab]見取り図とかは扱ってねえかな？[wait][clear]
***************************************/
    wait(ref_424);
    dialogFree(ref_423);
    bitClear(TBIT_502);
    b(label_4da);
  label_429:
    ref_429 = dialogAlloc();
    ref_42a = msgShow(msg_124);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]鳴海区の宝石屋が、ここで商売を再開してるぜ。
[tab]商売人の執念ってやつか？
[tab]まったく恐れ入るよ。[wait][clear]
***************************************/
    wait(ref_42a);
    dialogFree(ref_429);
    bitClear(TBIT_502);
    b(label_4da);
  label_42f:
    ref_42f = dialogAlloc();
    ref_430 = msgShow(msg_125);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]パパラチャって宝石屋…
[tab]武器や防具も細工してくれるらしいな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]フフ…これで仕事もしやすくなったぜ。[wait][clear]
***************************************/
    wait(ref_430);
    dialogFree(ref_42f);
    bitClear(TBIT_502);
    b(label_4da);
  label_435:
    ref_435 = dialogAlloc();
    ref_436 = msgShow(msg_126);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]きょうびのレストランはしぶといね。
[tab]街がぶっ飛んでる時にちゃっかり逃げおおせて、
[tab]そこの青葉区で商売再開だとよ。[wait][clear]
***************************************/
    wait(ref_436);
    dialogFree(ref_435);
    bitClear(TBIT_502);
    b(label_4da);
  label_43b:
    ref_43b = dialogAlloc();
    ref_43c = msgShow(msg_127);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]レストランのクレール・ド・リュンヌで
[tab]防具を扱っているって聞いたんだが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]やはりな。[delay(15)]
[tab]どうりであのギャルソン、俺たちと同じ世界の
[tab]においがぷんぷんしてるはずだぜ。[wait][clear]
***************************************/
    wait(ref_43c);
    dialogFree(ref_43b);
    bitClear(TBIT_502);
    b(label_4da);
  label_441:
    ref_441 = dialogAlloc();
    ref_442 = msgShow(msg_128);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]レストランのクレール・ド・リュンヌで
[tab]武器を扱っているって聞いたんだが…[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]やはりな。[delay(15)]
[tab]どうりであのギャルソン、俺たちと同じ世界の
[tab]においがぷんぷんしてるはずだぜ。[wait][clear]
***************************************/
    wait(ref_442);
    dialogFree(ref_441);
    bitClear(TBIT_502);
    b(label_4da);
  label_447:
    ref_447 = dialogAlloc();
    ref_448 = msgShow(msg_129);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠ジニーだかなんだか知らないが、
[tab]相性占いがパワーアップとかで話題になるなんざ、
[tab]まだまだ頭が平和ボケしてる証拠さ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]まあ、そのほうが俺の仕事は
[tab]やりやすいんだけどな。[wait][clear]
***************************************/
    wait(ref_448);
    dialogFree(ref_447);
    bitClear(TBIT_502);
    b(label_4da);
  label_44d:
    ref_44d = dialogAlloc();
    ref_44e = msgShow(msg_130);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠ジニーの相性占いとやらが評判だが、
[tab]占いで相性を決められちゃたまらないね。
[tab]俺の相性はプラスかマイナス…損得で決まる。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]それでも、まあ好き嫌いでもめる事もあるしな。
[tab]意外とバカにできないものなのかもしれん。[wait][clear]
***************************************/
    wait(ref_44e);
    dialogFree(ref_44d);
    bitClear(TBIT_502);
    b(label_4da);
  label_453:
    ref_453 = dialogAlloc();
    ref_454 = msgShow(msg_131);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]珠閒瑠ジニーの占いが、
[tab]最近当たるようになったって評判だが、
[tab]くだらねえな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]占いより情報、それが一番さ。
[tab]腕のいい情報屋は予言者みたいなもんだぜ。[wait][clear]
***************************************/
    wait(ref_454);
    dialogFree(ref_453);
    bitClear(TBIT_502);
    b(label_4da);
  label_459:
    ref_459 = dialogAlloc();
    ref_45a = msgShow(msg_132);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]エテーリアで同業他社との差別化のために、
[tab]サービスを変更したんだってな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]堅気の商売もご苦労なこった。
[tab]俺なら同業者は組むか潰すね。
[tab]こっちの方がすっきりするからな。[wait][clear]
***************************************/
    wait(ref_45a);
    dialogFree(ref_459);
    bitClear(TBIT_502);
    b(label_4da);
  label_45f:
    ref_45f = dialogAlloc();
    ref_460 = msgShow(msg_133);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ロカサンディータのマヌカンがパリで
[tab]波にのまれたって聞いたんだが弛んでるね。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]本職なら外の流行に飲み込まれるようじゃダメさ。
[tab]俺たちだって情報の波にさらされているが、
[tab]普段からきちんとしているから動じない。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]それが本当のプロだぜ。
[wait][clear]
***************************************/
    wait(ref_460);
    dialogFree(ref_45f);
    bitClear(TBIT_502);
    bitSet(TBIT_502_M);
    b(label_4da);
  label_466:
    bitGet(var_0, TBIT_502_M);
    bez(var_0, label_46e);
    ref_468 = dialogAlloc();
    ref_469 = msgShow(msg_134);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]俺としたことが勘違いしちまったようだな。
[tab]パリじゃなくバリで事故ってたんだって？
[tab]情報はしっかり確認しないとな。[wait][clear]
***************************************/
    wait(ref_469);
    dialogFree(ref_468);
    bitClear(TBIT_502);
    b(label_4da);
  label_46e:
    ref_46e = dialogAlloc();
    ref_46f = msgShow(msg_135);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ロサカンディータのマヌカン、
[tab]バリで事故ってたんだって？[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]旅先だからってはめ外しすぎだろう。
[tab]一般人は普段の緊張感が足りないよな。[wait][clear]
***************************************/
    wait(ref_46f);
    dialogFree(ref_46e);
    bitClear(TBIT_502);
    b(label_4da);
  label_474:
    ref_474 = dialogAlloc();
    ref_475 = msgShow(msg_136);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ロサカンディータの話、聞いてるか？
[tab]ブティックで防具販売の時代が来るとはな。
[tab]いろいろやりにくくなりそうだ。[wait][clear]
***************************************/
    wait(ref_475);
    dialogFree(ref_474);
    bitClear(TBIT_502);
    b(label_4da);
  label_47a:
    ref_47a = dialogAlloc();
    ref_47b = msgShow(msg_137);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]バーのマスター、用心棒を雇ったんだって？
[tab]賢い選択だ。あのおやじ、大したもんだな。
[tab]見直したぜ。[wait][clear]
***************************************/
    wait(ref_47b);
    dialogFree(ref_47a);
    bitClear(TBIT_502);
    b(label_4da);
  label_480:
    ref_480 = dialogAlloc();
    ref_481 = msgShow(msg_138);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]バーが実は武器屋だと聞いたが、知らなかったぜ。
[tab]マスターも言ってくれればいいのに。
[tab]しかし、こう評判だとかえって買いにくいな。[wait][clear]
***************************************/
    wait(ref_481);
    dialogFree(ref_480);
    bitClear(TBIT_502);
    b(label_4da);
  label_486:
    ref_486 = dialogAlloc();
    ref_487 = msgShow(msg_139);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]最近は隠れた商売が流行らしいな。
[tab]ギガ・マッチョには、
[tab]隠し球の商品があるんだってよ。[wait][clear]
***************************************/
    wait(ref_487);
    dialogFree(ref_486);
    bitClear(TBIT_502);
    b(label_4da);
  label_48c:
    ref_48c = dialogAlloc();
    ref_48d = msgShow(msg_140);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ギガ・マッチョで表では売らないＣＤが
[tab]あるんだってよ。
[tab]何だか俺みたいで好感が持てるね。[wait][clear]
***************************************/
    wait(ref_48d);
    dialogFree(ref_48c);
    bitClear(TBIT_502);
    b(label_4da);
  label_492:
    ref_492 = dialogAlloc();
    ref_493 = msgShow(msg_141);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ムー大陸がカジノを始めたんだってな。
[tab]たまらないねぇ。ギャンブルは最高の娯楽さ。
[tab]一つポーカーでもやってみるか。[wait][clear]
***************************************/
    wait(ref_493);
    dialogFree(ref_492);
    bitClear(TBIT_502);
    b(label_4da);
  label_498:
    ref_498 = dialogAlloc();
    ref_499 = msgShow(msg_142);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ムー大陸がカジノを始めたんだってな。
[tab]たまらないねぇ。ギャンブルは最高の娯楽さ。
[tab]一つブラックジャックでもやってみるか。[wait][clear]
***************************************/
    wait(ref_499);
    dialogFree(ref_498);
    bitClear(TBIT_502);
    b(label_4da);
  label_49e:
    ref_49e = dialogAlloc();
    ref_49f = msgShow(msg_143);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ムー大陸がカジノを始めたんだってな。
[tab]たまらないねぇ。ギャンブルは最高の娯楽さ。
[tab]一つスロットでもやってみるか。[wait][clear]
***************************************/
    wait(ref_49f);
    dialogFree(ref_49e);
    bitClear(TBIT_502);
    b(label_4da);
  label_4a4:
    ref_4a4 = dialogAlloc();
    ref_4a5 = msgShow(msg_144);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]フッ。トニーの奴、不思議なアクセサリーの
[tab]販売でなかなかの評判じゃねえか。
[tab]一度様子を見に行かないとな。[wait][clear]
***************************************/
    wait(ref_4a5);
    dialogFree(ref_4a4);
    bitClear(TBIT_502);
    b(label_4da);
  label_4aa:
    ref_4aa = dialogAlloc();
    ref_4ab = msgShow(msg_145);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]フッ。トニーの奴、護身用グッズの
[tab]販売でなかなかの評判じゃねえか。
[tab]一度様子を見に行かないとな。[wait][clear]
***************************************/
    wait(ref_4ab);
    dialogFree(ref_4aa);
    bitClear(TBIT_502);
    b(label_4da);
  label_4b0:
    ref_4b0 = dialogAlloc();
    ref_4b1 = msgShow(msg_146);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]東亜ディフェンスで扱ってる商品が
[tab]ずいぶんよくなったらしいな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]使える物が少ないんで最近行ってなかったが、
[tab]久々に店主の顔でも見てやるか。[wait][clear]
***************************************/
    wait(ref_4b1);
    dialogFree(ref_4b0);
    bitClear(TBIT_502);
    b(label_4da);
  label_4b6:
    ref_4b6 = dialogAlloc();
    ref_4b7 = msgShow(msg_147);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]東亜ディフェンスが商売の幅を広げたらしいな。
[tab]しかし、武器まで売り始めるとは意外だぜ。
[tab]昔はあんなにいやがってたのによ。[wait][clear]
***************************************/
    wait(ref_4b7);
    dialogFree(ref_4b6);
    bitClear(TBIT_502);
    b(label_4da);
  label_4bc:
    ref_4bc = dialogAlloc();
    ref_4bd = msgShow(msg_148);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]しらしいの女将が夢を実現させたってな。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]夢、か…[delay(20)]
[tab]俺にはまぶしすぎる言葉だ。[wait][clear]
***************************************/
    wait(ref_4bd);
    dialogFree(ref_4bc);
    bitClear(TBIT_502);
    b(label_4da);
  label_4c2:
    ref_4c2 = dialogAlloc();
    ref_4c3 = msgShow(msg_149);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]赤提灯しらいしの女将は、
[tab]人捜しの仕事もしてるんだって？[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]危ねえ危ねえ。
[tab]これからはあそこで飲むのはやめとかないと。
[tab]どこで足がつくか解らねえからな。[wait][clear]
***************************************/
    wait(ref_4c3);
    dialogFree(ref_4c2);
    bitClear(TBIT_502);
    b(label_4da);
  label_4c8:
    ref_4c8 = dialogAlloc();
    ref_4c9 = msgShow(msg_150);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]ＫＡＯＲＩが閉まってたとかでみんな騒いでるが、
[tab]俺には関係ない事だ。[wait][clear]
***************************************/
    wait(ref_4c9);
    dialogFree(ref_4c8);
    bitClear(TBIT_502);
    b(label_4da);
  label_4ce:
    ref_4ce = dialogAlloc();
    ref_4cf = msgShow(msg_151);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]時間城じゃご丁寧に魔法のカードの
[tab]複製までしてくれるそうだな。
[tab]サービス満点だ。[wait][clear][color(yellow)]あぶない男[color(white)]
[tab]ま、俺が複製するのは別のものだから
[tab]関係ないね。[wait][clear]
***************************************/
    wait(ref_4cf);
    dialogFree(ref_4ce);
    bitClear(TBIT_502);
    b(label_4da);
  label_4d4:
    ref_4d4 = dialogAlloc();
    ref_4d5 = msgShow(msg_152);
/***************************************
[color(yellow)]あぶない男[color(white)]
[tab]時間城で魔法のカードを販売してるんだってな。
[tab]まあどうでもいいが、なんか胡散臭いぜ。
[tab]俺はあの店主がなんだか気に食わないんだ。[wait][clear]
***************************************/
    wait(ref_4d5);
    dialogFree(ref_4d4);
    bitClear(TBIT_502);
    b(label_4da);
  label_4da:
}

function M503()
{
}

function M504()
{
}

function M505()
{
}

function START()
{
}

function MD501()
{
    op_71();
}

function MD502()
{
    bitGet(var_0, TBIT_MAYA502);
    bitGet(var_1, EBIT_E003E);
    bitGet(var_2, EBIT_E0037_B);
    bitGet(var_3, EBIT_E0033);
    bitGet(var_4, EBIT_E002B);
    bnz(var_0, label_523);
    bnz(var_1, label_500);
    bnz(var_2, label_50e);
    bnz(var_3, label_51c);
    bnz(var_4, label_4f9);
    ref_4eb = bustupLoad(bustup_17);
    bustupWait(ref_4eb);
    ref_4ed = bustupAlloc(ref_4eb, left, rgb(0,0,0));
    bustupFade(ref_4ed, rgb(128,0,0), 30);
    ref_4ef = dialogAlloc();
    ref_4f0 = msgShow(msg_153);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]マーヤ、なんか家に忘れ物？
[tab]ちょっと待ってみ、今鍵開けるから。[wait][clear]
***************************************/
    wait(ref_4f0);
    dialogFree(ref_4ef);
    ref_4f3 = bustupFade(ref_4ed, rgb(0,0,0), 10);
    bustupWait(ref_4f3);
    bustupFree(ref_4ed);
    bitSet(TBIT_MAYA502);
    eventFileLoad(E, 127);
    b(label_524);
  label_4f9:
    ref_4f9 = dialogAlloc();
    ref_4fa = msgShow(msg_154);
/***************************************
[color(green)][tab]舞耶は、鍵を開けて自宅に入った。[wait][clear]
***************************************/
    wait(ref_4fa);
    dialogFree(ref_4f9);
    bitSet(TBIT_MAYA502);
    eventFileLoad(E, 127);
    b(label_524);
  label_500:
    ref_500 = bustupLoad(bustup_17);
    bustupWait(ref_500);
    ref_502 = bustupAlloc(ref_500, left, rgb(0,0,0));
    bustupFade(ref_502, rgb(128,0,0), 30);
    ref_504 = dialogAlloc();
    ref_505 = msgShow(msg_155);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]マーヤ、なんか家に忘れ物？
[tab]ちょっと待ってみ、今鍵開けるから。[wait][clear]
***************************************/
    wait(ref_505);
    dialogFree(ref_504);
    ref_508 = bustupFade(ref_502, rgb(0,0,0), 10);
    bustupWait(ref_508);
    bustupFree(ref_502);
    bitSet(TBIT_MAYA502);
    eventFileLoad(E, 127);
    b(label_524);
  label_50e:
    ref_50e = bustupLoad(bustup_21);
    bustupWait(ref_50e);
    ref_510 = bustupAlloc(ref_50e, left, rgb(0,0,0));
    bustupFade(ref_510, rgb(128,0,0), 30);
    ref_512 = dialogAlloc();
    ref_513 = msgShow(msg_156);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]ここが天野君の家なのか？
[tab]なんだ、署の目と鼻の先じゃないか…[wait][clear]
***************************************/
    wait(ref_513);
    dialogFree(ref_512);
    ref_516 = bustupFade(ref_510, rgb(0,0,0), 10);
    bustupWait(ref_516);
    bustupFree(ref_510);
    bitSet(TBIT_MAYA502);
    eventFileLoad(E, 127);
    b(label_524);
  label_51c:
    ref_51c = dialogAlloc();
    ref_51d = msgShow(msg_157);
/***************************************
[color(green)][tab]舞耶は、鍵を開けて自宅に入った。[wait][clear]
***************************************/
    wait(ref_51d);
    dialogFree(ref_51c);
    bitSet(TBIT_MAYA502);
    eventFileLoad(E, 127);
    b(label_524);
  label_523:
    eventFileLoad(E, 127);
  label_524:
}

function MD503()
{
    eventFileLoad(E, 128);
}

function MD504()
{
    bitGet(var_0, EBIT_E00AB);
    bitGet(var_1, EBIT_E00A8);
    bitGet(var_2, EBIT_E009F);
    bitGet(var_3, EBIT_E007F);
    bitGet(var_4, EBIT_E007B);
    bitGet(var_5, EBIT_E007A);
    bitGet(var_6, EBIT_E0077);
    bitGet(var_7, EBIT_E0046);
    bitGet(var_8, MBIT_HI_NANJOTOUJO);
    bitGet(var_9, MBIT_HI_ERITOUJO);
    bitGet(var_a, EBIT_E003E);
    bitGet(var_b, EBIT_E0037_B);
    bitGet(var_c, EBIT_E0033);
    bitGet(var_d, EBIT_E002B);
    bnz(var_0, label_560);
    bnz(var_1, label_560);
    bnz(var_2, label_554);
    bnz(var_3, label_560);
    bnz(var_4, label_560);
    bnz(var_5, label_554);
    bnz(var_6, label_560);
    bnz(var_7, label_554);
    bnz(var_a, label_554);
    bnz(var_b, label_548);
    bnz(var_c, label_548);
    bnz(var_d, label_543);
    eventFileLoad(E, 14);
    b(label_56c);
  label_543:
    ref_543 = dialogAlloc();
    ref_544 = msgShow(msg_158);
/***************************************
[color(green)][tab]無残に焼け落ち、廃墟になっている。[wait][clear]
***************************************/
    wait(ref_544);
    dialogFree(ref_543);
    b(label_56c);
  label_548:
    ref_548 = bustupLoad(bustup_2c);
    bustupWait(ref_548);
    ref_54a = bustupAlloc(ref_548, left, rgb(0,0,0));
    bustupFade(ref_54a, rgb(128,0,0), 30);
    ref_54c = dialogAlloc();
    ref_54d = msgShow(msg_159);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]すっかり廃墟になってやがる。
[tab]よくまあ、あれで生き延びれたもんだな。
[tab]我ながら感心するぜ。[wait][clear]
***************************************/
    wait(ref_54d);
    dialogFree(ref_54c);
    ref_550 = bustupFade(ref_54a, rgb(0,0,0), 10);
    bustupWait(ref_550);
    bustupFree(ref_54a);
    b(label_56c);
  label_554:
    ref_554 = bustupLoad(bustup_21);
    bustupWait(ref_554);
    ref_556 = bustupAlloc(ref_554, left, rgb(0,0,0));
    bustupFade(ref_556, rgb(128,0,0), 30);
    ref_558 = dialogAlloc();
    ref_559 = msgShow(msg_160);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]こんな廃墟に用は無いな。
[tab]別のところにいこうか。[wait][clear]
***************************************/
    wait(ref_559);
    dialogFree(ref_558);
    ref_55c = bustupFade(ref_556, rgb(0,0,0), 10);
    bustupWait(ref_55c);
    bustupFree(ref_556);
    b(label_56c);
  label_560:
    ref_560 = bustupLoad(bustup_17);
    bustupWait(ref_560);
    ref_562 = bustupAlloc(ref_560, left, rgb(0,0,0));
    bustupFade(ref_562, rgb(128,0,0), 30);
    ref_564 = dialogAlloc();
    ref_565 = msgShow(msg_161);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]焼け落ちた跡ってのは見てて気味が悪いね。
[tab]早く別の所にいこ。[wait][clear]
***************************************/
    wait(ref_565);
    dialogFree(ref_564);
    ref_568 = bustupFade(ref_562, rgb(0,0,0), 10);
    bustupWait(ref_568);
    bustupFree(ref_562);
    b(label_56c);
  label_56c:
}

function MD505()
{
    bitGet(var_0, EBIT_E00AB);
    bitGet(var_1, EBIT_E00A8);
    bitGet(var_2, EBIT_E009F);
    bitGet(var_3, EBIT_E007F);
    bitGet(var_4, EBIT_E007B);
    bitGet(var_5, EBIT_E007A);
    bitGet(var_6, EBIT_E0077);
    bitGet(var_7, EBIT_E0046);
    bitGet(var_8, MBIT_HI_NANJOTOUJO);
    bitGet(var_9, MBIT_HI_ERITOUJO);
    bitGet(var_a, EBIT_E003E);
    bitGet(var_b, EBIT_E0037_B);
    bitGet(var_c, EBIT_E0033);
    bitGet(var_d, EBIT_E002B);
    bitGet(var_e, EBIT_E0018);
    bnz(var_0, label_5ac);
    bnz(var_1, label_5ac);
    bnz(var_2, label_5ac);
    bnz(var_3, label_5ac);
    bnz(var_4, label_5a6);
    bnz(var_5, label_59a);
    bnz(var_6, label_59a);
    bnz(var_7, label_59a);
    bnz(var_a, label_59a);
    bnz(var_b, label_59a);
    bnz(var_c, label_59a);
    bnz(var_d, label_595);
    bnz(var_e, label_589);
  label_589:
    ref_589 = bustupLoad(bustup_21);
    bustupWait(ref_589);
    ref_58b = bustupAlloc(ref_589, left, rgb(0,0,0));
    bustupFade(ref_58b, rgb(128,0,0), 30);
    ref_58d = dialogAlloc();
    ref_58e = msgShow(msg_162);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]こんなところに用は無いと思うが…
[tab]さ、行くぞ。[wait][clear]
***************************************/
    wait(ref_58e);
    dialogFree(ref_58d);
    ref_591 = bustupFade(ref_58b, rgb(0,0,0), 10);
    bustupWait(ref_591);
    bustupFree(ref_58b);
    b(label_5b8);
  label_595:
    ref_595 = dialogAlloc();
    ref_596 = msgShow(msg_163);
/***************************************
[color(green)][tab]ここには用は無い。[color(white)][wait][clear]
***************************************/
    wait(ref_596);
    dialogFree(ref_595);
    b(label_5b8);
  label_59a:
    ref_59a = bustupLoad(bustup_2c);
    bustupWait(ref_59a);
    ref_59c = bustupAlloc(ref_59a, left, rgb(0,0,0));
    bustupFade(ref_59c, rgb(128,0,0), 30);
    ref_59e = dialogAlloc();
    ref_59f = msgShow(msg_164);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]ここは何かと物騒な場所だぜ。
[tab]用も無いのに近づくのは感心しねぇな。
[tab]さ、他へいくぜ。[wait][clear]
***************************************/
    wait(ref_59f);
    dialogFree(ref_59e);
    ref_5a2 = bustupFade(ref_59c, rgb(0,0,0), 10);
    bustupWait(ref_5a2);
    bustupFree(ref_59c);
    b(label_5b8);
  label_5a6:
    bitGet(var_0, EBIT_E007D);
    bnz(var_0, label_5aa);
    eventFileLoad(E, 66);
    b(label_5b8);
  label_5aa:
    dngLoad2(abandoned_factory-4);
    b(label_5b8);
  label_5ac:
    ref_5ac = bustupLoad(bustup_21);
    bustupWait(ref_5ac);
    ref_5ae = bustupAlloc(ref_5ac, left, rgb(0,0,0));
    bustupFade(ref_5ae, rgb(128,0,0), 30);
    ref_5b0 = dialogAlloc();
    ref_5b1 = msgShow(msg_165);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]…もうここには用は無いな。
[tab]行こう。[wait][clear]
***************************************/
    wait(ref_5b1);
    dialogFree(ref_5b0);
    ref_5b4 = bustupFade(ref_5ae, rgb(0,0,0), 10);
    bustupWait(ref_5b4);
    bustupFree(ref_5ae);
    b(label_5b8);
  label_5b8:
}

function MD506()
{
    bitGet(var_f, EBIT_E00AF);
    bitGet(var_0, EBIT_E00AB);
    bitGet(var_1, EBIT_E00A8);
    bitGet(var_2, EBIT_E009F);
    bitGet(var_3, EBIT_E007F);
    bitGet(var_4, EBIT_E007B);
    bitGet(var_5, EBIT_E007A);
    bitGet(var_6, EBIT_E0077);
    bitGet(var_7, EBIT_E0046);
    bitGet(var_8, MBIT_HI_NANJOTOUJO);
    bitGet(var_9, MBIT_HI_ERITOUJO);
    bitGet(var_a, EBIT_E003E);
    bitGet(var_b, EBIT_E0037_B);
    bitGet(var_c, EBIT_E0033);
    bitGet(var_d, EBIT_E002B);
    bitGet(var_e, EBIT_E0018);
    bnz(var_f, label_600);
    bnz(var_0, label_5f4);
    bnz(var_1, label_5f4);
    bnz(var_2, label_5f4);
    bnz(var_3, label_5f4);
    bnz(var_4, label_5f4);
    bnz(var_5, label_5f4);
    bnz(var_6, label_5f4);
    bnz(var_7, label_5f4);
    bnz(var_a, label_5f4);
    bnz(var_b, label_5e8);
    bnz(var_c, label_5e8);
    bnz(var_d, label_5e3);
    bnz(var_e, label_5d7);
  label_5d7:
    ref_5d7 = bustupLoad(bustup_17);
    bustupWait(ref_5d7);
    ref_5d9 = bustupAlloc(ref_5d7, left, rgb(0,0,0));
    bustupFade(ref_5d9, rgb(128,0,0), 30);
    ref_5db = dialogAlloc();
    ref_5dc = msgShow(msg_166);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ちょっと、ちょっと。
[tab]こんなところで黄昏てる場合じゃないでしょ。
[tab]さ、いくよ。[wait][clear]
***************************************/
    wait(ref_5dc);
    dialogFree(ref_5db);
    ref_5df = bustupFade(ref_5d9, rgb(0,0,0), 10);
    bustupWait(ref_5df);
    bustupFree(ref_5d9);
    b(label_60b);
  label_5e3:
    ref_5e3 = dialogAlloc();
    ref_5e4 = msgShow(msg_167);
/***************************************
[color(green)][tab]ここには用は無い。[color(white)][wait][clear]
***************************************/
    wait(ref_5e4);
    dialogFree(ref_5e3);
    b(label_60b);
  label_5e8:
    ref_5e8 = bustupLoad(bustup_2c);
    bustupWait(ref_5e8);
    ref_5ea = bustupAlloc(ref_5e8, left, rgb(0,0,0));
    bustupFade(ref_5ea, rgb(128,0,0), 30);
    ref_5ec = dialogAlloc();
    ref_5ed = msgShow(msg_168);
/***************************************
[color(yellow)]パオフゥ[color(white)]
[tab]海は良い…
[tab]が、今は感傷より行動だぜ。
[tab]じゃ、いくか。[wait][clear]
***************************************/
    wait(ref_5ed);
    dialogFree(ref_5ec);
    ref_5f0 = bustupFade(ref_5ea, rgb(0,0,0), 10);
    bustupWait(ref_5f0);
    bustupFree(ref_5ea);
    b(label_60b);
  label_5f4:
    ref_5f4 = bustupLoad(bustup_17);
    bustupWait(ref_5f4);
    ref_5f6 = bustupAlloc(ref_5f4, left, rgb(0,0,0));
    bustupFade(ref_5f6, rgb(128,0,0), 30);
    ref_5f8 = dialogAlloc();
    ref_5f9 = msgShow(msg_169);
/***************************************
[color(yellow)]うらら[color(white)]
[tab]ここにいるとなんとなく暗くなっちゃうからさ、
[tab]早くべつんとこ、いこ。[wait][clear]
***************************************/
    wait(ref_5f9);
    dialogFree(ref_5f8);
    ref_5fc = bustupFade(ref_5f6, rgb(0,0,0), 10);
    bustupWait(ref_5fc);
    bustupFree(ref_5f6);
    b(label_60b);
  label_600:
    ref_600 = bustupLoad(bustup_21);
    bustupWait(ref_600);
    ref_602 = bustupAlloc(ref_600, left, rgb(0,0,0));
    bustupFade(ref_602, rgb(128,0,0), 30);
    ref_604 = dialogAlloc();
    ref_605 = msgShow(msg_170);
/***************************************
[color(yellow)]克哉[color(white)]
[tab]切り離された海はまさに異常な光景だな。
[tab]水平線の代わりにトリフネの壁がそびえている。
[tab]はやくなんとかしなければ。[wait][clear]
***************************************/
    wait(ref_605);
    dialogFree(ref_604);
    ref_608 = bustupFade(ref_602, rgb(0,0,0), 10);
    bustupWait(ref_608);
    bustupFree(ref_602);
  label_60b:
}
