
﻿msg_0:
[color(yellow)]안내데스크 직원[color(white)]
[tab]아, 마야.
[tab]친구라면, 아직 안 왔어.
[wait][clear][end]

msg_1:
[color(yellow)]우라라[color(white)]
[tab]챠~오, 마야.
[tab]그럼, 기운 내서 가보자고~
[tab]무조~건, 멋진 남자 낚아야 해!
[sync][wait][clear][end]

msg_10:
[color(yellow)]안내데스크 직원[color(white)]
[tab]왜 그래, 마야? 헤에~
[tab]취재 때문에 맞선 파티에 못 가게 된 거야?
[tab]그 노처녀 상사, 진짜 심술궂다니까.
[wait][clear][end]

msg_11:
[color(yellow)]비상구[color(green)]
[tab]여기로는 들어갈 수 없다.[color(white)]
[sync][wait][clear][end]

msg_2:
[color(yellow)]세리자와 우라라[color(green)]
[tab]여성용 속옷 제조사에 근무하는 마야의 절친.
[tab]점술을 좋아하는 화장발 미인으로,
[tab]남자 운이 없는 것을 몹시 고민하고 있다.
[sync][wait][clear][end]

msg_3:
[color(yellow)]우라라[color(white)]
[tab]뭐어~!?
[tab]일 때문에 못 가게 됐다고~!?
[sync][wait][clear][end]

msg_4:
[color(yellow)]우라라[color(white)]
[tab]잠깐 너,
[tab]처음부터 갈 생각 없었던 거 아니야!?
[sync][wait][clear][end]

msg_5:
[color(yellow)]우라라[color(white)]
[tab]아, 알았다.
[tab]그 '데자뷔 소년'이 신경 쓰여서 그러는 거지?
[tab]하아~ 관두라니까!
[sync][wait][clear][end]

msg_6:
[color(yellow)]우라라[color(white)]
[tab]대체, 왜 역 앞에서 한 번 부딪혔을 뿐인
[tab]연하남한테 그렇게까지 열을 올리는 걸까~
[tab]아무리 예전에 만난 적이 있는 것 같다고는 해도 말이야…
[sync][wait][clear][end]

msg_7:
[color(yellow)]우라라[color(white)]
[tab]뭐야, 정말로 일 때문이야?
[tab]칠자매 학원에서 JOKER 소문 취재?
[sync][wait][clear][end]

msg_8:
[color(yellow)]우라라[color(white)]
[tab]아~ 정말, 어쩔 수 없네, 자!
[tab]후다닥 끝내면 아직 늦지 않아.
[tab]도와줄 테니까, 서두르는 거야!!
[sync][wait][clear][end]

msg_9:
[color(yellow)]우라라[color(white)]
[tab]이것 봐, 왕룡 점술에서도
[tab]「오늘은 운명의 만남이 있는 날」이라고 나왔단 말이야.
[tab]무조건 파티 가는 거다!
[sync][wait][clear][end]
