export const functions: Record<
  string,
  {
    args: string[];
    return?: boolean;
  }
> = {
  NOP: { args: [] },
  MES: { args: ["msg"] },
  RNDMES3: { args: ["msg", "msg", "msg"] },
  INTMES: { args: [] },
  JOYMES: { args: [] },
  ANGMES: { args: [] },
  FEARMES: { args: [] },
  CLS: { args: [] },
  JMP: { args: ["label"] },
  RNDJMP2: { args: ["label", "label"] },
  RNDJMP4: { args: ["label", "label", "label", "label"] },
  MENUJMP: { args: ["label", "label", "label", "label", "label", "label", "label", "label"] },
  REACTJMP: { args: [] },
  BITJMP: { args: ["bit", "label", "label"] },
  BITONJMP: { args: ["bit", "label"] },
  BITOFJMP: { args: ["bit", "label"] },
  SEXJMP: { args: ["label", "label"] },
  CHRJMP: { args: ["$", "label"] },
  MAPJMP: { args: ["$", "label", "label"] },
  LVJMP: { args: ["label", "label"] },
  INTJMP: { args: ["$", "label"] },
  JOYJMP: { args: ["$", "label"] },
  ANGJMP: { args: ["$", "label"] },
  FEARJMP: { args: ["$", "label"] },
  DVLJMP: { args: ["$", "label"] },
  CONTJMP: { args: ["$", "label"] },
  MXCNTJMP: { args: ["label"] },
  MXCRDJMP: { args: ["label"] },
  ITEMJMP: { args: ["label", "label"] },
  MONEYJMP: { args: ["label"] },
  CALL: { args: ["label"] },
  RETURN: { args: [], return: true },
  WAIT: { args: ["$"] },
  PLRSET: { args: ["$"] },
  CMNDJMP: { args: ["$", "label"] },
  EQUIPJMP: { args: ["$", "$", "label"] },
  STTSJMP: { args: ["$", "$", "label"] },
  BWAIT: { args: ["$"] },
  PRSJMP: { args: ["$", "$", "label"] },
  WINDSP: { args: [] },
  WINCLS: { args: [] },
  FACEDSP: { args: ["$", "$", "$", "$"] },
  FACEFADE: { args: ["$", "$", "$"] },
  FACECLS: { args: ["$"] },
  BLKOUT: { args: ["$"] },
  BLKIN: { args: ["$"] },
  PLRMOVE: { args: ["$", "$", "$", "$", "$", "$", "$", "$"] },
  PLRANM: { args: ["$", "$", "$", "$"] },
  DVLANM: { args: ["$"] },
  INTANM: { args: [] },
  PRSDSP: { args: ["$"] },
  PRSCLS: { args: ["$"] },
  RESETANM: { args: [] },
  VIEWMOVE: { args: ["$", "$", "$"] },
  OUT: { args: [] },
  CMDDSP: { args: [] },
  PLRDIR: { args: ["$", "$"] },
  DVLVOICE: { args: ["$"] },
  BGMVOL: { args: ["$", "$"] },
  BITON: { args: ["bit"] },
  BITOFF: { args: ["bit"] },
  INTPLUS: { args: [] },
  JOYPLUS: { args: [] },
  ANGPLUS: { args: [] },
  FEARPLUS: { args: [] },
  STTSCHG: { args: ["$", "$"] },
  REACTREC: { args: ["$"] },
  GETCARD: { args: [] },
  GETITEM: { args: [] },
  GETMNY: { args: [] },
  CONTRACT: { args: [] },
  CANCEL: { args: ["$"] },
  HEAL: { args: ["$", "$"] },
  DVLANG: { args: [] },
  GETFOOL: { args: [] },
  GETFREE: { args: [] },
  DLGNGON: { args: [] },
  DLGNGOFF: { args: [] },
  REACTEND: { args: [], return: true },
  TALKEND: { args: [], return: true },
  DVLESC: { args: [], return: true },
  PLRTURN: { args: [], return: true },
  EMYTURN: { args: [], return: true },
  BTLEND: { args: [], return: true },
  ESC: { args: [] },
  BYE: { args: [] },
  BGBRGHT: { args: ["$", "$", "$", "$"] },
  UNTBRGHT: { args: ["$", "$", "$"] },
  USPOTON: { args: ["$", "$", "$", "$", "$", "$"] },
  USPOTOFF: { args: ["$", "$"] },
  FSPOTON: { args: ["$", "$", "$", "$", "$", "$", "$", "$"] },
  FSPOTOFF: { args: ["$", "$"] },
  ESPOTON: { args: ["$", "$", "$", "$", "$", "$"] },
  ESPOTOFF: { args: ["$"] },
  CMPRJMP: { args: ["$", "$", "label", "label"] },
  BOSOSET: { args: [] },
  CALLWAIT: { args: [] },
  CALLWAITLAST: { args: [] },
  IDUNIT: { args: ["$"] },
  IDUNITCHARA: { args: ["$"] },
  IDUNITPLAYER: { args: ["$"] },
  IDUNITENEMY: { args: [] },
  IDUNITALL: { args: [] },
  IDUNITSELECTALL: { args: [] },
  IDUNITSELECTPLAYER: { args: [] },
  IDUNITSELECTENEMY: { args: [] },
  IDUNITUNSELECTALL: { args: [] },
  IDUNITUNSELECTPLAYER: { args: [] },
  IDUNITUNSELECTENEMY: { args: [] },
  UNITROT: { args: ["$"] },
  UNITROTPOS: { args: ["$", "$"] },
  UNITROTCHARA: { args: ["$"] },
  UNITROTPLAYER: { args: ["$"] },
  UNITROTENEMY: { args: [] },
  UNITMOVEPOS: { args: ["$", "$", "$", "$"] },
  UNITMOVEWAIT: { args: [] },
  UNITSHADE: { args: ["$", "$"] },
  IDBUSTUP: { args: ["$"] },
  BUSTUPSETCHARA: { args: ["$"] },
  BUSTUPSETPLAYER: { args: ["$"] },
  BUSTUPSETBANK: { args: ["$"] },
  BUSTUPDEL: { args: [] },
  BUSTUPFADE: { args: ["$", "$", "$", "$"] },
  BUSTUPFADEWAIT: { args: [] },
  VIEWRANGE: { args: ["$", "$"] },
  VIEWMOVEPOS: { args: ["$", "$", "$"] },
  VIEWMOVECHARA: { args: ["$", "$"] },
  VIEWMOVEPLAYER: { args: ["$", "$"] },
  VIEWMOVEENEMY: { args: ["$"] },
  VIEWWAIT: { args: [] },
  LIGHTSETUNIT: { args: ["$", "$", "$", "$"] },
  LIGHTDELUNIT: { args: ["$"] },
  LIGHTSETFIELD: { args: ["$", "$", "$", "$", "$", "$", "$", "$"] },
  LIGHTDELFIELD: { args: ["$"] },
  WINDOWCOLORNORMAL: { args: [] },
  WINDOWCOLORQUEST: { args: [] },
  IDSERVICE: { args: ["$"] },
  SERVICEJUMP: { args: ["label"] },
  SERVICECOURSEJUMP: { args: ["$", "label"] },
  GETCARDCODE: { args: ["$", "$"] },
  GETITEMCODE: { args: ["$", "$"] },
  COMMANDSET: { args: ["$"] },
  REG7SETITEMNAME: { args: ["$"] },
  REG7SETCARDNAME: { args: ["$"] },
  LEADERJUMP: { args: ["$", "label"] },
  UNITSUMMON: { args: [] },
  UNITSUMMONWAIT: { args: [] },
  UNITRETURN: { args: [] },
  UNITRETURNWAIT: { args: [] },
  VIEWMOVEUNITY: { args: ["$", "$"] },
  IDUNITPERSONA: { args: [] },
  UNITMOTION: { args: ["$"] },
  UNITMOTIONWAIT: { args: [] },
  RNDMES4: { args: ["msg", "msg", "msg", "msg"] },
  PADENABLE: { args: [] },
  PADDISABLE: { args: [] },
  CHARACTOR5JUMP: { args: ["$", "$", "$", "$", "$", "label"] },
  BWAIT2: { args: ["$"] },
};
