
msg_0:
[color(yellow)]Assistant Director[color(white)]
[tab]A-Are you guys just looking around!?
[tab]G-Get out of here, quick!! 
[tab]Junko Kurosu is going berserk in Studio One!!
[sync][wait][clear][end]

msg_1:
[color(yellow)]Assistant Director[color(white)]
[tab]Wang Long Chizuru’s fortune came true! 
[tab]She said that people will become Jokers... 
[tab]And all of a sudden, Kurosu-san became a Joker!!
[sync][wait][clear][end]
