function START()
{
    controlDisable();
    levelColorInvert();
    sndMusicPlay(sound_1132, 127);
    delayClear();
    delayWait(30);
    levelColorInvert();
    delayClear();
    delayWait(30);
    ref_8 = bustupLoad(bustup_25);
    bustupWait(ref_8);
    ref_a = bustupAlloc(ref_8, left, rgb(0,0,0));
    bustupFade(ref_a, rgb(128,0,0), 30);
    ref_c = dialogAlloc();
    ref_d = msgShow(msg_0);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]!?
[tab]I can feel [tatsuya]’s aura...
[tab]It’s coming from Studio One!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d);
    ref_10 = bustupFade(ref_a, rgb(0,0,0), 10);
    bustupWait(ref_10);
    bustupFree(ref_a);
    ref_13 = bustupLoad(bustup_23);
    bustupWait(ref_13);
    ref_15 = bustupAlloc(ref_13, left, rgb(0,0,0));
    bustupFade(ref_15, rgb(128,0,0), 30);
    ref_17 = msgShow(msg_1);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]He’s... alive!!
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_17);
    dialogFree(ref_c);
    ref_1b = bustupFade(ref_15, rgb(0,0,0), 10);
    bustupWait(ref_1b);
    bustupFree(ref_15);
    bitClear(EBIT_TV_KYOMEI);
    controlEnable();
}
