
msg_0:
[color(yellow)]Ulala[color(white)]
[tab]I bet the seminar started already.
[tab]The door’s locked.
[sync][wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]This building’s design is somewhat outdated.
[tab]If we can find an air duct, it’s possible
[tab]for us to check what’s happening inside, but...
[sync][wait][clear][end]

msg_2:
[color(yellow)]Katsuya[color(white)]
[tab]The question is where it’s located...
[sync][wait][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab]Huh? 
[tab]It’s in the women’s restroom on the 4th floor?
[tab]How did you know that, Amano-kun...?
[sync][wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]I see, it’s another of your d五j二 vu...
[tab]Hmm...
[sync][wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab]But the women’s restroom... 
[tab]Even if it’s an emergency, I wonder if 
[tab]it’s okay to barge into a women-only area...
[sync][wait][clear][end]

msg_6:
[color(yellow)]Ulala[color(white)]
[tab]Geez, you’re so uptight.
[tab]I’ll go check inside for you, okay?
[tab]Let’s go, Mr. Police Detective.
[sync][wait][clear][end]
