function START()
{
    controlDisable();
    unitFacePlayer(npc1);
    ref_2 = dialogAlloc();
    unitAnimationPlay(npc1, animation_24, 1);
    ref_4 = msgShow(msg_0);
/***************************************
[color(yellow)]Tenchu Army Soldier[color(white)]
[tab]You’re going after Tatsuzou Sudou, right?
[tab]He went that way... toward the heliport.
[tab]He’s gonna abandon the ship... and us.
[wait][clear]
***************************************/
    wait(ref_4);
    ref_6 = msgShow(msg_1);
/***************************************
[color(yellow)]Tenchu Army Soldier[color(white)]
[tab]...Undersea Ruins?
[tab]I think his secretary and that fortune teller
[tab]headed there.
[wait][clear]
***************************************/
    wait(ref_6);
    dialogFree(ref_2);
    controlEnable();
}
