function START()
{
    controlDisable();
    unitFacePlayer(enemy4);
    ref_2 = dialogAlloc();
    unitAnimationPlay(enemy4, animation_1a, 1);
    li(var_1, 0);
    bitGet(var_0, DBIT_NPC_JACK1);
    bne(var_0, 0, label_9);
    add(var_1, var_1, 1);
    b(label_b);
  label_9:
    bne(var_0, 1, label_b);
    b(label_b);
  label_b:
    bitGet(var_0, DBIT_NPC_JACK2);
    bne(var_0, 0, label_f);
    add(var_1, var_1, 1);
    b(label_11);
  label_f:
    bne(var_0, 1, label_11);
    b(label_11);
  label_11:
    bitGet(var_0, DBIT_NPC_JACK3);
    bne(var_0, 0, label_15);
    add(var_1, var_1, 1);
    b(label_17);
  label_15:
    bne(var_0, 1, label_17);
    b(label_17);
  label_17:
    bitGet(var_0, DBIT_NPC_JACK4);
    bne(var_0, 0, label_1b);
    add(var_1, var_1, 1);
    b(label_1d);
  label_1b:
    bne(var_0, 1, label_1d);
    b(label_1d);
  label_1d:
    bne(var_1, 0, label_21);
    ref_1e = msgShow(msg_0);
/***************************************
[color(yellow)]Peh[color(white)]
[tab]HeeHo... This fire’s stronger than I thought, HO! 
[tab]I can’t put it out by myself, HO! 
[tab]I need my friends’ help, HO!
[wait][clear]
***************************************/
    wait(ref_1e);
    b(label_28);
  label_21:
    boutrange(var_1, 1, 3, label_25);
    ref_22 = msgShow(msg_1);
/***************************************
[color(yellow)]Peh[color(white)]
[tab]Not enough, HO...
[tab]This isn’t enough yet, HO...
[tab]Bring more friends, HO!
[wait][clear]
***************************************/
    wait(ref_22);
    b(label_28);
  label_25:
    ref_25 = msgShow(msg_2);
/***************************************
[color(yellow)]Peh[color(white)]
[tab]I saw him go into the room by himself, HO!
[tab]He’s probably still hiding there, HO!
[wait][clear]
***************************************/
    wait(ref_25);
    b(label_28);
  label_28:
    unitAnimationPlay(enemy4, animation_0, 1);
    dialogFree(ref_2);
    controlEnable();
}
