
msg_0:
[color(green)]There’s no need to be here.[color(white)]
[wait][clear][end]

msg_1:
[color(green)]It’s locked, HO![color(white)]
[wait][clear][end]

msg_2:
[color(green)]You can’t enter here, HO![color(white)]
[wait][clear][end]

msg_3:
[color(green)]There’s no need to be here, HO![color(white)]
[wait][clear][end]

msg_4:
[color(yellow)]Voice Beyond Door[color(white)]
[tab]Uh...
[tab]Who are you, HO?
[tab]What do you want, HO?
[wait][clear][end]

msg_5:
[color(yellow)]Voice Beyond Door[color(white)]
[tab]I don’t like talking to people, HO!
[tab]That’s why I’m hiding, HO!
[tab]Please leave me alone, HO!
[wait][clear][end]

msg_6:
[color(yellow)]Voice Beyond Door[color(white)]
[tab]If you need help,
[tab]ask Pyro Jack, HO!
[wait][clear][end]

msg_7:
[color(yellow)]Voice Beyond Door[color(white)]
[tab]If you need help, ask other Jack Frosts, HO! 
[tab]Walk around the dungeon and you’ll meet
[tab]them somewhere, HO!
[wait][clear][end]

msg_8:
[color(yellow)]Voice Beyond Door[color(white)]
[tab]Huh!? My friend’s putting out a fire, HO?
[end]

msg_9:
[tab]B-But there’s only one, HO!
[tab]I’m shy, so I’ll stay here, HO!
[wait][clear][end]

msg_10:
[tab]There’s two friends, HO?
[tab]Uh... I still don’t wanna go, HO!
[wait][clear][end]

msg_11:
[tab]B-But that’s only 3, HO!
[tab]I’m still shy, so I’ll stay here, HO!
[wait][clear][end]

msg_12:
[tab]There’s already 4, HO?
[tab]Um, th-then, I’ll go too, HO!
[wait][clear][end]

msg_13:
[color(yellow)]Voice Beyond Door[color(white)]
[tab]Still trying to put out the fire, HO?
[end]

msg_14:
[tab]But if there’s only one of my friends,
[tab]I don’t want to go, HO!
[wait][clear][end]

msg_15:
[tab]But that’s only two, HO! If there
[tab]aren’t more, I don’t want to go, HO!
[wait][clear][end]

msg_16:
[tab]But that’s only three, HO!
[tab]I’m still kinda shy, so I can’t go, HO!
[wait][clear][end]

msg_17:
[tab]HeeHo! Is everyone there already, HO?
[tab]T-Then I’ll go too, HO!
[wait][clear][end]

msg_18:
[color(yellow)]Voice[color(white)]
[tab]Everyone!
[tab]I’m coming, HO!
[wait][clear][end]

msg_19:
[color(yellow)]Maya[color(white)]
[tab]. . . . . .
[wait][clear][end]

msg_20:
[color(green)]Maya felt a cool breeze.[color(white)]
[wait][clear][end]
