function START()
{
    controlDisable();
    ref_1 = dialogAlloc();
    ref_2 = msgShow(msg_0);
/***************************************
[color(yellow)]Voice of Jack Frost[color(white)]
[tab]The fire still won’t go out, HO!
[tab]Next is my turn, HO!
[tab]Everyone, sayonara, bye bye!
[wait][clear]
***************************************/
    wait(ref_2);
    dialogFree(ref_1);
    bitClear(MBIT_EXE_ZISATU2);
    controlEnable();
}
