function START()
{
    controlDisable();
    ref_1 = bustupLoad(bustup_21);
    bustupWait(ref_1);
    ref_3 = bustupAlloc(ref_1, left, rgb(0,0,0));
    bustupFade(ref_3, rgb(128,0,0), 30);
    ref_5 = dialogAlloc();
    ref_6 = msgShow(msg_0);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]My stomach’s growling...
[tab]No matter how much I pull myself
[tab]together, my body’s honest.
[wait][clear]
***************************************/
    wait(ref_6);
    dialogFree(ref_5);
    ref_9 = bustupFade(ref_3, rgb(0,0,0), 10);
    bustupWait(ref_9);
    bustupFree(ref_3);
    controlEnable();
}
