function START()
{
    controlDisable();
    levelColorInvert();
    sndMusicPlay(sound_1592, 127);
    delayClear();
    delayWait(30);
    levelColorInvert();
    delayClear();
    delayWait(30);
    ref_8 = bustupLoad(bustup_23);
    bustupWait(ref_8);
    ref_a = bustupAlloc(ref_8, left, rgb(0,0,0));
    bustupFade(ref_a, rgb(128,0,0), 30);
    ref_c = dialogAlloc();
    ref_d = msgShow(msg_0);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]’s still alive...
[tab]We must hurry...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_d);
    dialogFree(ref_c);
    ref_11 = bustupFade(ref_a, rgb(0,0,0), 10);
    bustupWait(ref_11);
    bustupFree(ref_a);
    bitClear(EBIT_TORIFUNE_KYOKEI);
    controlEnable();
}
