function START()
{
    controlDisable();
    ref_1 = bustupLoad(bustup_de);
    bustupWait(ref_1);
    ref_3 = bustupAlloc(ref_1, right, rgb(0,0,0));
    bustupFade(ref_3, rgb(128,0,0), 30);
    ref_5 = dialogAlloc();
    ref_6 = msgShow(msg_0);
/***************************************
[color(yellow)]Philemon[color(white)]
[tab]Phenomenal.
[tab]I shall open a new path for you.
[tab]Good luck.
[wait][clear]
***************************************/
    wait(ref_6);
    dialogFree(ref_5);
    ref_9 = bustupFade(ref_3, rgb(0,0,0), 10);
    bustupWait(ref_9);
    bustupFree(ref_3);
    sndMusicPlay(sound_1456, 127);
    bitSet(DBIT_EX_CLEAR4);
    bitClear(MBIT_EXE_2A);
    controlEnable();
}
