
msg_0:
[color(yellow)]Gate of Separation[color(white)]
[tab]’Tis sad, indeed... Thou seek to walk alone...
[tab]Then I shall say no more.
[tab]Thou mayst pass.
[wait][clear][end]

msg_1:
[color(yellow)]Gate of Separation[color(white)]
[tab]I am the Gate of Separation. The sorrow of
[tab]parting is the only thing that will open
[tab]the gate. Dost thou wish to pass?
[wait][clear][end]

msg_2:
[tab]Dost thou wish to pass?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_3:
[color(yellow)]Gate of Separation[color(white)]
[tab]Then I shall not open.
[tab]Begone!
[wait][clear][end]

msg_4:
[color(yellow)]Gate of Separation[color(white)]
[tab]Then,
[tab]present one to part momentarily.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]There’s only me...
[tab]Oh well. I’ll be waiting at
[tab]the Velvet Room.
[wait][clear][end]

msg_6:
[color(green)]Ulala left the party.[color(white)]
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]I don’t want you to be alone...
[tab]But there’s no choice.
[tab]I’ll be waiting at the Velvet Room.
[wait][clear][end]

msg_8:
[color(green)]Katsuya left the party.[color(white)]
[wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]You okay by yourself?
[tab]Well, don’t try too hard and kill yourself.
[tab]I’ll be at the Velvet.
[wait][clear][end]

msg_10:
[color(green)]Baofu left the party.[color(white)]
[wait][clear][end]

msg_11:
[color(yellow)]Nanjo[color(white)]
[tab]When in Rome, do as the Romans do...
[tab]I shall entrust you with everything.
[tab]I’ll head back to the Velvet Room.
[wait][clear][end]

msg_12:
[color(green)]Nanjo left the party.[color(white)]
[wait][clear][end]

msg_13:
[color(yellow)]Elly[color(white)]
[tab]I’m the only one here...
[tab]It can’t be helped.
[tab]I’ll go back to the Velvet Room.
[wait][clear][end]

msg_14:
[color(green)]Elly left the party.[color(white)]
[wait][clear][end]

msg_15:
[color(yellow)][tatsuya][color(white)]
[tab]Maya-nee... Will you be okay?
[tab]Please don’t push yourself.
[tab]I’ll be at the Velvet.
[wait][clear][end]

msg_16:
[color(green)][tatsuya] left the party.[color(white)]
[wait][clear][end]

msg_17:
Pick the one to separate from.
[choice(6)][if_all(LBIT_0000)]Ulala
[if_all(LBIT_0001)]Katsuya
[if_all(LBIT_0002)]Baofu
[if_all(LBIT_0003)]Nanjo
[if_all(LBIT_0004)]Elly
[if_all(LBIT_0005)][tatsuya]
[end_choice][clear][end]

msg_18:
[color(yellow)]Ulala[color(white)]
[tab]Huh? Me!? Hey, Ma-ya, isn’t that cold?
[tab]Well... I guess it can’t be helped...
[tab]Alright, I’ll be at the Velvet Room.
[wait][clear][end]

msg_19:
[color(green)]Ulala left the party.[color(white)]
[wait][clear][end]

msg_20:
[color(yellow)]Katsuya[color(white)]
[tab]Hmm... Under these circumstances,
[tab]I guess it’s necessary.
[tab]I’ll head back to the Velvet Room.
[wait][clear][end]

msg_21:
[color(green)]Katsuya left the party.[color(white)]
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]...Oh well. Don’t lose just because
[tab]I’m not here, you hear me?
[tab]I’ll be at the Velvet.
[wait][clear][end]

msg_23:
[color(green)]Baofu left the party.[color(white)]
[wait][clear][end]

msg_24:
[color(yellow)]Nanjo[color(white)]
[tab]U... Understood.
[tab]Then I shall await everyone
[tab]at the Velvet Room.
[wait][clear][end]

msg_25:
[color(green)]Nanjo left the party.[color(white)]
[wait][clear][end]

msg_26:
[color(yellow)]Elly[color(white)]
[tab]It cannot be helped.
[tab]Then, I’ll be at the Velvet Room.
[tab]Please be careful.
[wait][clear][end]

msg_27:
[color(green)]Elly left the party.[color(white)]
[wait][clear][end]

msg_28:
[color(yellow)][tatsuya][color(white)]
[tab]You can’t pass unless we do this.
[tab]It can’t be helped.
[tab]I’ll return to the Velvet.
[wait][clear][end]

msg_29:
[color(green)][tatsuya] left the party.[color(white)]
[wait][clear][end]

msg_30:
[color(yellow)]Gate of Separation[color(white)]
[tab]Your separation shall be rewarded
[tab]with the opening of this gate.
[tab]Now, pass through.
[wait][clear][end]
