function START()
{
    controlDisable();
    bitClear(LBIT_0000);
    bitClear(LBIT_0001);
    bitClear(LBIT_0002);
    bitClear(LBIT_0003);
    bitClear(LBIT_0004);
    bitClear(LBIT_0005);
    li(var_1, 0);
    partyMemberCheck(var_0, ulala);
    bne(var_0, 0, label_b);
    b(label_f);
  label_b:
    bne(var_0, 1, label_f);
    bitSet(LBIT_0000);
    add(var_1, var_1, 1);
    b(label_f);
  label_f:
    partyMemberCheck(var_0, katsuya);
    bne(var_0, 0, label_12);
    b(label_16);
  label_12:
    bne(var_0, 1, label_16);
    bitSet(LBIT_0001);
    add(var_1, var_1, 1);
    b(label_16);
  label_16:
    partyMemberCheck(var_0, baofu);
    bne(var_0, 0, label_19);
    b(label_1d);
  label_19:
    bne(var_0, 1, label_1d);
    bitSet(LBIT_0002);
    add(var_1, var_1, 1);
    b(label_1d);
  label_1d:
    partyMemberCheck(var_0, nanjo);
    bne(var_0, 0, label_20);
    b(label_24);
  label_20:
    bne(var_0, 1, label_24);
    bitSet(LBIT_0003);
    add(var_1, var_1, 1);
    b(label_24);
  label_24:
    partyMemberCheck(var_0, elly);
    bne(var_0, 0, label_27);
    b(label_2b);
  label_27:
    bne(var_0, 1, label_2b);
    bitSet(LBIT_0004);
    add(var_1, var_1, 1);
    b(label_2b);
  label_2b:
    partyMemberCheck(var_0, tatsuya);
    bne(var_0, 0, label_2e);
    b(label_32);
  label_2e:
    bne(var_0, 1, label_32);
    bitSet(LBIT_0005);
    add(var_1, var_1, 1);
    b(label_32);
  label_32:
    bne(var_1, 0, label_35);
    b(label_37);
    b(label_37);
  label_35:
    b(label_3c);
    b(label_37);
  label_37:
    ref_37 = dialogAlloc();
    ref_38 = msgShow(msg_0);
/***************************************
[color(yellow)]Gate of Separation[color(white)]
[tab]’Tis sad, indeed... Thou seek to walk alone...
[tab]Then I shall say no more.
[tab]Thou mayst pass.
[wait][clear]
***************************************/
    wait(ref_38);
    dialogFree(ref_37);
    b(label_177);
  label_3c:
    ref_3c = dialogAlloc();
    ref_3d = msgShow(msg_1);
/***************************************
[color(yellow)]Gate of Separation[color(white)]
[tab]I am the Gate of Separation. The sorrow of
[tab]parting is the only thing that will open
[tab]the gate. Dost thou wish to pass?
[wait][clear]
***************************************/
    wait(ref_3d);
    dialogFree(ref_3c);
    delayClear();
    delayWait(10);
    choiceSetResult(1);
    op_105(1);
    ref_44 = bustupLoad(bustup_1);
    bustupWait(ref_44);
    ref_46 = bustupAlloc(ref_44, center, rgb(0,0,0));
    bustupFade(ref_46, rgb(128,0,0), 30);
    ref_48 = dialogChoiceAlloc();
    ref_49 = msgShow(msg_2);
/***************************************
[tab]Dost thou wish to pass?
[choice(2)]Yes
No
[end_choice][clear]
***************************************/
    wait(ref_49);
    dialogFree(ref_48);
    ref_4c = bustupFade(ref_46, rgb(0,0,0), 10);
    bustupWait(ref_4c);
    bustupFree(ref_46);
    choiceGetResult(var_0);
    bne(var_0, 0, label_53);
    b(label_5a);
    b(label_5a);
  label_53:
    bne(var_0, 1, label_5a);
    ref_54 = dialogAlloc();
    ref_55 = msgShow(msg_3);
/***************************************
[color(yellow)]Gate of Separation[color(white)]
[tab]Then I shall not open.
[tab]Begone!
[wait][clear]
***************************************/
    wait(ref_55);
    dialogFree(ref_54);
    b(label_187);
    b(label_5a);
  label_5a:
    ref_5a = dialogAlloc();
    ref_5b = msgShow(msg_4);
/***************************************
[color(yellow)]Gate of Separation[color(white)]
[tab]Then,
[tab]present one to part momentarily.
[wait][clear]
***************************************/
    wait(ref_5b);
    dialogFree(ref_5a);
    bne(var_1, 1, label_eb);
    partyMemberCheck(var_0, ulala);
    bne(var_0, 0, label_62);
    b(label_76);
  label_62:
    bne(var_0, 1, label_76);
    ref_63 = bustupLoad(bustup_1a);
    bustupWait(ref_63);
    ref_65 = bustupAlloc(ref_63, left, rgb(0,0,0));
    bustupFade(ref_65, rgb(128,0,0), 30);
    ref_67 = dialogAlloc();
    ref_68 = msgShow(msg_5);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]There’s only me...
[tab]Oh well. I’ll be waiting at
[tab]the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_68);
    dialogFree(ref_67);
    ref_6b = bustupFade(ref_65, rgb(0,0,0), 10);
    bustupWait(ref_6b);
    bustupFree(ref_65);
    delayClear();
    delayWait(10);
    ref_70 = dialogAlloc();
    ref_71 = msgShow(msg_6);
/***************************************
[color(green)]Ulala left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(ulala);
    wait(ref_71);
    dialogFree(ref_70);
    b(label_76);
  label_76:
    partyMemberCheck(var_0, katsuya);
    bne(var_0, 0, label_79);
    b(label_8d);
  label_79:
    bne(var_0, 1, label_8d);
    ref_7a = bustupLoad(bustup_21);
    bustupWait(ref_7a);
    ref_7c = bustupAlloc(ref_7a, left, rgb(0,0,0));
    bustupFade(ref_7c, rgb(128,0,0), 30);
    ref_7e = dialogAlloc();
    ref_7f = msgShow(msg_7);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]I don’t want you to be alone...
[tab]But there’s no choice.
[tab]I’ll be waiting at the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_7f);
    dialogFree(ref_7e);
    ref_82 = bustupFade(ref_7c, rgb(0,0,0), 10);
    bustupWait(ref_82);
    bustupFree(ref_7c);
    delayClear();
    delayWait(10);
    ref_87 = dialogAlloc();
    ref_88 = msgShow(msg_8);
/***************************************
[color(green)]Katsuya left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(katsuya);
    wait(ref_88);
    dialogFree(ref_87);
    b(label_8d);
  label_8d:
    partyMemberCheck(var_0, baofu);
    bne(var_0, 0, label_90);
    b(label_a4);
  label_90:
    bne(var_0, 1, label_a4);
    ref_91 = bustupLoad(bustup_2d);
    bustupWait(ref_91);
    ref_93 = bustupAlloc(ref_91, left, rgb(0,0,0));
    bustupFade(ref_93, rgb(128,0,0), 30);
    ref_95 = dialogAlloc();
    ref_96 = msgShow(msg_9);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]You okay by yourself?
[tab]Well, don’t try too hard and kill yourself.
[tab]I’ll be at the Velvet.
[wait][clear]
***************************************/
    wait(ref_96);
    dialogFree(ref_95);
    ref_99 = bustupFade(ref_93, rgb(0,0,0), 10);
    bustupWait(ref_99);
    bustupFree(ref_93);
    delayClear();
    delayWait(10);
    ref_9e = dialogAlloc();
    ref_9f = msgShow(msg_10);
/***************************************
[color(green)]Baofu left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(baofu);
    wait(ref_9f);
    dialogFree(ref_9e);
    b(label_a4);
  label_a4:
    partyMemberCheck(var_0, nanjo);
    bne(var_0, 0, label_a7);
    b(label_bb);
  label_a7:
    bne(var_0, 1, label_bb);
    ref_a8 = bustupLoad(bustup_36);
    bustupWait(ref_a8);
    ref_aa = bustupAlloc(ref_a8, left, rgb(0,0,0));
    bustupFade(ref_aa, rgb(128,0,0), 30);
    ref_ac = dialogAlloc();
    ref_ad = msgShow(msg_11);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]When in Rome, do as the Romans do...
[tab]I shall entrust you with everything.
[tab]I’ll head back to the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_ad);
    dialogFree(ref_ac);
    ref_b0 = bustupFade(ref_aa, rgb(0,0,0), 10);
    bustupWait(ref_b0);
    bustupFree(ref_aa);
    delayClear();
    delayWait(10);
    ref_b5 = dialogAlloc();
    ref_b6 = msgShow(msg_12);
/***************************************
[color(green)]Nanjo left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(nanjo);
    wait(ref_b6);
    dialogFree(ref_b5);
    b(label_bb);
  label_bb:
    partyMemberCheck(var_0, elly);
    bne(var_0, 0, label_be);
    b(label_d2);
  label_be:
    bne(var_0, 1, label_d2);
    ref_bf = bustupLoad(bustup_3d);
    bustupWait(ref_bf);
    ref_c1 = bustupAlloc(ref_bf, left, rgb(0,0,0));
    bustupFade(ref_c1, rgb(128,0,0), 30);
    ref_c3 = dialogAlloc();
    ref_c4 = msgShow(msg_13);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]I’m the only one here...
[tab]It can’t be helped.
[tab]I’ll go back to the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_c4);
    dialogFree(ref_c3);
    ref_c7 = bustupFade(ref_c1, rgb(0,0,0), 10);
    bustupWait(ref_c7);
    bustupFree(ref_c1);
    delayClear();
    delayWait(10);
    ref_cc = dialogAlloc();
    ref_cd = msgShow(msg_14);
/***************************************
[color(green)]Elly left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(elly);
    wait(ref_cd);
    dialogFree(ref_cc);
    b(label_d2);
  label_d2:
    partyMemberCheck(var_0, tatsuya);
    bne(var_0, 0, label_d5);
    b(label_e9);
  label_d5:
    bne(var_0, 1, label_e9);
    ref_d6 = bustupLoad(bustup_b);
    bustupWait(ref_d6);
    ref_d8 = bustupAlloc(ref_d6, left, rgb(0,0,0));
    bustupFade(ref_d8, rgb(128,0,0), 30);
    ref_da = dialogAlloc();
    ref_db = msgShow(msg_15);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]Maya-nee... Will you be okay?
[tab]Please don’t push yourself.
[tab]I’ll be at the Velvet.
[wait][clear]
***************************************/
    wait(ref_db);
    dialogFree(ref_da);
    ref_de = bustupFade(ref_d8, rgb(0,0,0), 10);
    bustupWait(ref_de);
    bustupFree(ref_d8);
    delayClear();
    delayWait(10);
    ref_e3 = dialogAlloc();
    ref_e4 = msgShow(msg_16);
/***************************************
[color(green)][tatsuya] left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(tatsuya);
    wait(ref_e4);
    dialogFree(ref_e3);
    b(label_e9);
  label_e9:
    b(label_173);
    b(label_ed);
  label_eb:
    b(label_ed);
    b(label_ed);
  label_ed:
    delayClear();
    delayWait(10);
    ref_ef = bustupLoad(bustup_1);
    bustupWait(ref_ef);
    ref_f1 = bustupAlloc(ref_ef, center, rgb(0,0,0));
    bustupFade(ref_f1, rgb(128,0,0), 30);
    ref_f3 = dialogChoiceAlloc();
    ref_f4 = msgShow(msg_17);
/***************************************
Pick the one to separate from.
[choice(6)][if_all(LBIT_0000)]Ulala
[if_all(LBIT_0001)]Katsuya
[if_all(LBIT_0002)]Baofu
[if_all(LBIT_0003)]Nanjo
[if_all(LBIT_0004)]Elly
[if_all(LBIT_0005)][tatsuya]
[end_choice][clear]
***************************************/
    wait(ref_f4);
    dialogFree(ref_f3);
    ref_f7 = bustupFade(ref_f1, rgb(0,0,0), 10);
    bustupWait(ref_f7);
    bustupFree(ref_f1);
    choiceGetResult(var_0);
    bne(var_0, 0, label_10f);
    ref_fc = bustupLoad(bustup_1b);
    bustupWait(ref_fc);
    ref_fe = bustupAlloc(ref_fc, left, rgb(0,0,0));
    bustupFade(ref_fe, rgb(128,0,0), 30);
    ref_100 = dialogAlloc();
    ref_101 = msgShow(msg_18);
/***************************************
[color(yellow)]Ulala[color(white)]
[tab]Huh? Me!? Hey, Ma-ya, isn’t that cold?
[tab]Well... I guess it can’t be helped...
[tab]Alright, I’ll be at the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_101);
    dialogFree(ref_100);
    ref_104 = bustupFade(ref_fe, rgb(0,0,0), 10);
    bustupWait(ref_104);
    bustupFree(ref_fe);
    delayClear();
    delayWait(10);
    ref_109 = dialogAlloc();
    ref_10a = msgShow(msg_19);
/***************************************
[color(green)]Ulala left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(ulala);
    wait(ref_10a);
    dialogFree(ref_109);
    b(label_173);
  label_10f:
    bne(var_0, 1, label_123);
    ref_110 = bustupLoad(bustup_21);
    bustupWait(ref_110);
    ref_112 = bustupAlloc(ref_110, left, rgb(0,0,0));
    bustupFade(ref_112, rgb(128,0,0), 30);
    ref_114 = dialogAlloc();
    ref_115 = msgShow(msg_20);
/***************************************
[color(yellow)]Katsuya[color(white)]
[tab]Hmm... Under these circumstances,
[tab]I guess it’s necessary.
[tab]I’ll head back to the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_115);
    dialogFree(ref_114);
    ref_118 = bustupFade(ref_112, rgb(0,0,0), 10);
    bustupWait(ref_118);
    bustupFree(ref_112);
    delayClear();
    delayWait(10);
    ref_11d = dialogAlloc();
    ref_11e = msgShow(msg_21);
/***************************************
[color(green)]Katsuya left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(katsuya);
    wait(ref_11e);
    dialogFree(ref_11d);
    b(label_173);
  label_123:
    bne(var_0, 2, label_137);
    ref_124 = bustupLoad(bustup_2d);
    bustupWait(ref_124);
    ref_126 = bustupAlloc(ref_124, left, rgb(0,0,0));
    bustupFade(ref_126, rgb(128,0,0), 30);
    ref_128 = dialogAlloc();
    ref_129 = msgShow(msg_22);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]...Oh well. Don’t lose just because
[tab]I’m not here, you hear me?
[tab]I’ll be at the Velvet.
[wait][clear]
***************************************/
    wait(ref_129);
    dialogFree(ref_128);
    ref_12c = bustupFade(ref_126, rgb(0,0,0), 10);
    bustupWait(ref_12c);
    bustupFree(ref_126);
    delayClear();
    delayWait(10);
    ref_131 = dialogAlloc();
    ref_132 = msgShow(msg_23);
/***************************************
[color(green)]Baofu left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(baofu);
    wait(ref_132);
    dialogFree(ref_131);
    b(label_173);
  label_137:
    bne(var_0, 3, label_14b);
    ref_138 = bustupLoad(bustup_36);
    bustupWait(ref_138);
    ref_13a = bustupAlloc(ref_138, left, rgb(0,0,0));
    bustupFade(ref_13a, rgb(128,0,0), 30);
    ref_13c = dialogAlloc();
    ref_13d = msgShow(msg_24);
/***************************************
[color(yellow)]Nanjo[color(white)]
[tab]U... Understood.
[tab]Then I shall await everyone
[tab]at the Velvet Room.
[wait][clear]
***************************************/
    wait(ref_13d);
    dialogFree(ref_13c);
    ref_140 = bustupFade(ref_13a, rgb(0,0,0), 10);
    bustupWait(ref_140);
    bustupFree(ref_13a);
    delayClear();
    delayWait(10);
    ref_145 = dialogAlloc();
    ref_146 = msgShow(msg_25);
/***************************************
[color(green)]Nanjo left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(nanjo);
    wait(ref_146);
    dialogFree(ref_145);
    b(label_173);
  label_14b:
    bne(var_0, 4, label_15f);
    ref_14c = bustupLoad(bustup_3d);
    bustupWait(ref_14c);
    ref_14e = bustupAlloc(ref_14c, left, rgb(0,0,0));
    bustupFade(ref_14e, rgb(128,0,0), 30);
    ref_150 = dialogAlloc();
    ref_151 = msgShow(msg_26);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]It cannot be helped.
[tab]Then, I’ll be at the Velvet Room.
[tab]Please be careful.
[wait][clear]
***************************************/
    wait(ref_151);
    dialogFree(ref_150);
    ref_154 = bustupFade(ref_14e, rgb(0,0,0), 10);
    bustupWait(ref_154);
    bustupFree(ref_14e);
    delayClear();
    delayWait(10);
    ref_159 = dialogAlloc();
    ref_15a = msgShow(msg_27);
/***************************************
[color(green)]Elly left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(elly);
    wait(ref_15a);
    dialogFree(ref_159);
    b(label_173);
  label_15f:
    bne(var_0, 5, label_173);
    ref_160 = bustupLoad(bustup_b);
    bustupWait(ref_160);
    ref_162 = bustupAlloc(ref_160, left, rgb(0,0,0));
    bustupFade(ref_162, rgb(128,0,0), 30);
    ref_164 = dialogAlloc();
    ref_165 = msgShow(msg_28);
/***************************************
[color(yellow)][tatsuya][color(white)]
[tab]You can’t pass unless we do this.
[tab]It can’t be helped.
[tab]I’ll return to the Velvet.
[wait][clear]
***************************************/
    wait(ref_165);
    dialogFree(ref_164);
    ref_168 = bustupFade(ref_162, rgb(0,0,0), 10);
    bustupWait(ref_168);
    bustupFree(ref_162);
    delayClear();
    delayWait(10);
    ref_16d = dialogAlloc();
    ref_16e = msgShow(msg_29);
/***************************************
[color(green)][tatsuya] left the party.[color(white)]
[wait][clear]
***************************************/
    partyMemberRemove(tatsuya);
    wait(ref_16e);
    dialogFree(ref_16d);
    b(label_173);
  label_173:
    ref_173 = dialogAlloc();
    ref_174 = msgShow(msg_30);
/***************************************
[color(yellow)]Gate of Separation[color(white)]
[tab]Your separation shall be rewarded
[tab]with the opening of this gate.
[tab]Now, pass through.
[wait][clear]
***************************************/
    wait(ref_174);
    dialogFree(ref_173);
  label_177:
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    sndMusicPlay(sound_14d8, 127);
    bitSet(MBIT_EXE_WMON_01);
    bitClear(MBIT_EXE_WHIT_01);
    delayClear();
    delayWait(60);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
  label_187:
    controlEnable();
}
