
msg_0:
[color(yellow)]Meteor Masa[color(white)]
[tab]Question [var(msg_var_0)]!!!!! Remember the Editor-
[tab]in-Chief at Kismet who hates Maya?
[tab]What’s her last name? C’mon!
[wait][clear][end]

msg_1:
MIZUNO
[end]

msg_2:
[color(yellow)]Meteor Masa[color(white)]
[tab]Brrrrr! Aw, man, that’s not it.
[tab]You already forgot? So did I.
[tab]But let’s think harder.
[wait][clear][end]

msg_3:
[color(yellow)]Meteor Masa[color(white)]
[tab]Correct!! How’d you remember that!?
[tab]Yep, Mizuno. That mean old hag who
[tab]ruled with an iron fist.
[wait][clear][color(yellow)]Meteor Masa[color(white)]
[tab]Why does she hate Maya so much?
[tab]Is she jealous of Maya’s popularity? 
[tab]Well, I’m glad that she didn’t become a Joker.
[wait][clear][color(yellow)]Meteor Masa[color(white)]
[tab]I’ll unlock the door.
[tab]You may now proceed!
[wait][clear][end]
