
msg_0:
[color(yellow)]Meteor Masa[color(white)]
[tab]Question [var(msg_var_0)]!!!!! Did you beat the Rumor
[tab]Demons at Mu Continent? One of them was
[tab]the Cursed Taxi. What was the other one?
[wait][clear][end]

msg_1:
MUSSIE
[end]

msg_2:
[color(yellow)]Meteor Masa[color(white)]
[tab]Brrrr! Wrong-O!!
[tab]Think, Mu Continent, Mu Continent...
[tab]Maybe it’s already part of the answer...
[wait][clear][end]

msg_3:
[color(yellow)]Meteor Masa[color(white)]
[tab]Correct!! Mu Continent, so Mussie!!
[tab]You know, Loch Ness, so Nessie.
[tab]Simple, but helped, didn’t it?
[wait][clear][color(yellow)]Meteor Masa[color(white)]
[tab]Let me unlock the door.
[tab]You may now proceed!
[wait][clear][end]
