function START()
{
    controlDisable();
    ref_1 = dialogAlloc();
    ref_2 = msgShow(msg_0);
/***************************************
[color(yellow)]Lithograph of Memory[color(white)]
[tab]If you wish, I shall show you
[tab]that nostalgic moment once more.
[wait][clear]
***************************************/
    wait(ref_2);
    dialogFree(ref_1);
    screenEffectInit();
    screenFade(160, 120, rgb(0,0,0), rgb(0,0,0), sub);
    screenFadeInner(rgb(255,255,255), 8, false);
    screenFadeOuter(rgb(255,255,255), 8, false);
    screenFadeWait(inner);
    screenFadeWait(outer);
    ref_b = bustupLoad(bustup_5b);
    bustupWait(ref_b);
    ref_d = bustupAlloc(ref_b, right, rgb(0,0,0));
    bustupFade(ref_d, rgb(128,0,0), 30);
    ref_f = dialogAlloc();
    ref_10 = msgShow(msg_1);
/***************************************
[color(yellow)]Editor-in-Chief Mizuno[color(white)]
[tab][color(green)]Coolest’s Editor-in-Chief who hates Maya.
[tab]An experienced woman who goes by the book.
[tab]30-something and still not married.[color(white)]
[wait][clear]
***************************************/
    wait(ref_10);
    dialogFree(ref_f);
    ref_13 = bustupFade(ref_d, rgb(0,0,0), 10);
    bustupWait(ref_13);
    bustupFree(ref_d);
    screenEffectUnknown();
    screenFadeInner(rgb(0,0,0), 6, true);
    screenFadeOuter(rgb(0,0,0), 6, true);
    screenFadeWait(inner);
    screenFadeWait(outer);
    controlEnable();
}
