function START()
{
    controlDisable();
    unitFacePlayer(unit_13);
    unitAnimationPlay(unit_13, animation_19, 1);
    ref_3 = dialogAlloc();
    ref_4 = msgShow(msg_0);
/***************************************
[color(yellow)]Frightened Girl[color(white)]
[tab]W-When I was a kid, I heard he got
[tab]locked away in a sanitarium, but...
[tab]Either way it’s still scary...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_4);
    unitAnimationPlay(unit_13, animation_6, 1);
    ref_8 = msgShow(msg_1);
/***************************************
[color(yellow)]Frightened Girl[color(white)]
[tab]My friend did the curse for fun, and she
[tab]freaked out when someone answered...
[tab]Now she believes that there’s a Joker...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_8);
    dialogFree(ref_3);
    unitAnimationPlay(unit_13, animation_0, 1);
    controlEnable();
}
