
msg_0:
[color(yellow)]Frightened Girl[color(white)]
[tab]W-When I was a kid, I heard he got
[tab]locked away in a sanitarium, but...
[tab]Either way it’s still scary...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Frightened Girl[color(white)]
[tab]My friend did the curse for fun, and she
[tab]freaked out when someone answered...
[tab]Now she believes that there’s a Joker...
[sync][wait][clear][end]
