function START()
{
    controlDisable();
    bitGet(var_0, bit_c6e);
    bnz(var_0, label_c);
    ref_3 = dialogAlloc();
    ref_4 = msgShow(msg_0);
/***************************************
Sure enough, the VIP floor door is locked. 
I could hear faint music from within. 
[wait][clear]That lady detective, Shiori Miyashiro, 
is probably inside. 
I don’t know if she’s still alive or not, though.
[wait][clear]
***************************************/
    wait(ref_4);
    ref_6 = msgShow(msg_1);
/***************************************
I try knocking, but I don’t get a response. 
Looks like I’d best hurry up and get that key after all. 
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_6);
    dialogFree(ref_3);
    controlEnable();
    b(label_16);
  label_c:
    bitGet(var_0, bit_c70);
    bnz(var_0, label_15);
    ref_e = dialogAlloc();
    ref_f = msgShow(msg_2);
/***************************************
[color(green)][tatsuya] used the VIP floor key.[color(white)]
[wait][clear]
***************************************/
    wait(ref_f);
    dialogFree(ref_e);
    sndMusicPlay(sound_15b6, 127);
    bitSet(bit_c70);
    b(label_16);
  label_15:
    eventLoad(event_113);
  label_16:
    controlEnable();
}
