
msg_0:
Sure enough, the VIP floor door is locked. 
I could hear faint music from within. 
[wait][clear]That lady detective, Shiori Miyashiro, 
is probably inside. 
I don’t know if she’s still alive or not, though.
[wait][clear][end]

msg_1:
I try knocking, but I don’t get a response. 
Looks like I’d best hurry up and get that key after all. 
[sync][wait][clear][end]

msg_2:
[color(green)][tatsuya] used the VIP floor key.[color(white)]
[wait][clear][end]
