
msg_0:
[color(yellow)]Local Security[color(white)]
[tab]Currently, administrative mode is "B".
[wait][clear][end]

msg_1:
[tab]Change administrative mode to A?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_2:
[color(yellow)]Local Security[color(white)]
[tab]Changing administrative mode to "A"...
[tab]Executing command.
[wait][clear][end]

msg_3:
[color(yellow)]Local Security[color(white)]
[tab]Maintaining administrative mode.
[tab]Currently, administrative mode is "B".
[wait][clear][end]

msg_4:
[color(yellow)]Local Security[color(white)]
[tab]Currently, administrative mode is "A".
[wait][clear][end]

msg_5:
[tab]Change administrative mode to B?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_6:
[color(yellow)]Local Security[color(white)]
[tab]Changing administrative mode to "B"...
[tab]Executing command.
[wait][clear][end]

msg_7:
[color(yellow)]Local Security[color(white)]
[tab]Maintaining administrative mode.
[tab]Currently, administrative mode is "A".
[wait][clear][end]
