
msg_0:
[color(yellow)]Man’s Voice[color(white)]
[tab]You need password to enter here.
[tab]You know password?
[wait][clear][end]

msg_1:
Panther
PANTHER
panther
[end]

msg_2:
[color(yellow)]Man’s Voice[color(white)]
[tab]This place, no one enter besides
[tab]people concerned! If you no want
[tab]to die, then leave!
[wait][clear][end]

msg_3:
[color(yellow)]Man’s Voice[color(white)]
[tab]Come in.[wait][clear][end]
