function START()
{
    controlDisable();
    bitGet(var_0, EBIT_E0067);
    bnz(var_0, label_6f);
    bitGet(var_0, EBIT_E005E);
    bez(var_0, label_33);
    bitGet(var_0, EBIT_GATE2_MISS);
    bez(var_0, label_47);
    bitGet(var_0, EBIT_E005D);
    bez(var_0, label_1f);
    bitGet(var_0, EBIT_E0063);
    bnz(var_0, label_5b);
    ref_b = bustupLoad(bustup_40);
    bustupWait(ref_b);
    ref_d = bustupAlloc(ref_b, left, rgb(0,0,0));
    bustupFade(ref_d, rgb(128,0,0), 30);
    ref_f = dialogAlloc();
    ref_10 = bustupLoad(bustup_7a);
    bustupWait(ref_10);
    ref_12 = bustupAlloc(ref_10, right, rgb(0,0,0));
    bustupFade(ref_12, rgb(128,0,0), 30);
    ref_14 = msgShow(msg_0);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☳... It’s "4".
[tab]I think this is the fourth gate, but...
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_14);
    ref_17 = bustupFade(ref_d, rgb(0,0,0), 10);
    bustupWait(ref_17);
    bustupFree(ref_d);
    dialogFree(ref_f);
    ref_1b = bustupFade(ref_12, rgb(0,0,0), 10);
    bustupWait(ref_1b);
    bustupFree(ref_12);
    b(label_7c);
  label_1f:
    ref_1f = bustupLoad(bustup_40);
    bustupWait(ref_1f);
    ref_21 = bustupAlloc(ref_1f, left, rgb(0,0,0));
    bustupFade(ref_21, rgb(128,0,0), 30);
    ref_23 = dialogAlloc();
    ref_24 = bustupLoad(bustup_7a);
    bustupWait(ref_24);
    ref_26 = bustupAlloc(ref_24, right, rgb(0,0,0));
    bustupFade(ref_26, rgb(128,0,0), 30);
    ref_28 = msgShow(msg_1);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☳... It’s "4",
[tab]but... I lost my confidence...
[tab]Let’s look for Brown’s dressing room first.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_28);
    ref_2b = bustupFade(ref_21, rgb(0,0,0), 10);
    bustupWait(ref_2b);
    bustupFree(ref_21);
    dialogFree(ref_23);
    ref_2f = bustupFade(ref_26, rgb(0,0,0), 10);
    bustupWait(ref_2f);
    bustupFree(ref_26);
    b(label_7c);
  label_33:
    ref_33 = bustupLoad(bustup_3e);
    bustupWait(ref_33);
    ref_35 = bustupAlloc(ref_33, left, rgb(0,0,0));
    bustupFade(ref_35, rgb(128,0,0), 30);
    ref_37 = dialogAlloc();
    ref_38 = bustupLoad(bustup_7a);
    bustupWait(ref_38);
    ref_3a = bustupAlloc(ref_38, right, rgb(0,0,0));
    bustupFade(ref_3a, rgb(128,0,0), 30);
    ref_3c = msgShow(msg_2);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☳... It’s "4".
[tab]First, let’s find ☰... the first gate.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_3c);
    ref_3f = bustupFade(ref_35, rgb(0,0,0), 10);
    bustupWait(ref_3f);
    bustupFree(ref_35);
    dialogFree(ref_37);
    ref_43 = bustupFade(ref_3a, rgb(0,0,0), 10);
    bustupWait(ref_43);
    bustupFree(ref_3a);
    b(label_7c);
  label_47:
    ref_47 = bustupLoad(bustup_3e);
    bustupWait(ref_47);
    ref_49 = bustupAlloc(ref_47, left, rgb(0,0,0));
    bustupFade(ref_49, rgb(128,0,0), 30);
    ref_4b = dialogAlloc();
    ref_4c = bustupLoad(bustup_7a);
    bustupWait(ref_4c);
    ref_4e = bustupAlloc(ref_4c, right, rgb(0,0,0));
    bustupFade(ref_4e, rgb(128,0,0), 30);
    ref_50 = msgShow(msg_3);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☳... It’s "4".
[tab]Next is ☱... Let’s find the second gate.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_50);
    ref_53 = bustupFade(ref_49, rgb(0,0,0), 10);
    bustupWait(ref_53);
    bustupFree(ref_49);
    dialogFree(ref_4b);
    ref_57 = bustupFade(ref_4e, rgb(0,0,0), 10);
    bustupWait(ref_57);
    bustupFree(ref_4e);
    b(label_7c);
  label_5b:
    ref_5b = bustupLoad(bustup_40);
    bustupWait(ref_5b);
    ref_5d = bustupAlloc(ref_5b, left, rgb(0,0,0));
    bustupFade(ref_5d, rgb(128,0,0), 30);
    ref_5f = dialogAlloc();
    ref_60 = bustupLoad(bustup_7a);
    bustupWait(ref_60);
    ref_62 = bustupAlloc(ref_60, right, rgb(0,0,0));
    bustupFade(ref_62, rgb(128,0,0), 30);
    ref_64 = msgShow(msg_4);
/***************************************
[color(yellow)]Elly[color(white)]
[tab]Hmmmm... This Ba Gua Letter is ☳... "4",
[tab]right? Then why isn’t this the fourth gate...?
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_64);
    ref_67 = bustupFade(ref_5d, rgb(0,0,0), 10);
    bustupWait(ref_67);
    bustupFree(ref_5d);
    dialogFree(ref_5f);
    ref_6b = bustupFade(ref_62, rgb(0,0,0), 10);
    bustupWait(ref_6b);
    bustupFree(ref_62);
    b(label_7c);
  label_6f:
    ref_6f = bustupLoad(bustup_2d);
    bustupWait(ref_6f);
    ref_71 = bustupAlloc(ref_6f, left, rgb(0,0,0));
    bustupFade(ref_71, rgb(128,0,0), 30);
    ref_73 = dialogAlloc();
    ref_74 = msgShow(msg_5);
/***************************************
[color(yellow)]Baofu[color(white)]
[tab]Amano... We’ve already been here.
[tab]Next is the last one... look for ☷.
[sync][wait][clear]
***************************************/
    sync();
    wait(ref_74);
    dialogFree(ref_73);
    ref_78 = bustupFade(ref_71, rgb(0,0,0), 10);
    bustupWait(ref_78);
    bustupFree(ref_71);
    b(label_7c);
  label_7c:
    controlEnable();
}
