function START()
{
    controlDisable();
    ref_1 = dialogAlloc();
    ref_2 = msgShow(msg_0);
/***************************************
[color(yellow)]Sachiko’s Letter[color(white)]
[tab]August 18th.
[wait][clear][color(yellow)]Sachiko’s Letter[color(white)]
[tab]Only me and Mommy knows the lock’s number.
[tab]But Sachiko call tell it to Daddy, too.
[wait][clear]
***************************************/
    wait(ref_2);
    dialogFree(ref_1);
    controlEnable();
}
