function START()
{
    controlDisable();
    ref_1 = dialogAlloc();
    ref_2 = msgShow(msg_0);
/***************************************
[color(yellow)]Notice[color(white)]
[tab]Schedule for cleaning up the air raid shelter
[tab]is posted. Please check the paper posted
[tab]on the eastern wall, near the entrance.
[wait][clear]
***************************************/
    wait(ref_2);
    dialogFree(ref_1);
    controlEnable();
}
