function START()
{
    controlDisable();
    ref_1 = dialogAlloc();
    ref_2 = msgShow(msg_0);
/***************************************
[color(yellow)]Notice[color(white)]
[tab]The list of who will help lead the evacuation
[tab]has been made. It is posted on the western
[tab]wall, near the entrance. Please confirm it.
[wait][clear]
***************************************/
    wait(ref_2);
    dialogFree(ref_1);
    controlEnable();
}
