
msg_0:
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☷... It’s "8".
[tab]This should be the last gate...
[sync][wait][clear][end]

msg_1:
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☷... It’s "8",
[tab]but... I lost my confidence...
[tab]Let’s look for Brown’s dressing room first.
[sync][wait][clear][end]

msg_2:
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☷... It’s "8".
[tab]First, let’s find ☰... the first gate.
[sync][wait][clear][end]

msg_3:
[color(yellow)]Elly[color(white)]
[tab]This Ba Gua Letter is ☷... "8".
[tab]Next is ☱... Let’s find the second gate.
[sync][wait][clear][end]
