msg_0:
[end]

msg_1:
[end]

msg_2:
[end]

msg_3:
[end]

msg_4:
[end]

msg_5:
[end]

msg_6:
[end]

msg_7:
[end]

msg_8:
[end]

msg_9:
[end]

msg_10:
[end]

msg_11:
[end]

msg_12:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?
[tab]You some kinda famous reporter?
[tab]Maybe I should I get an autograph?
[tab][wait][clear][end]

msg_13:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'm amazed! There're actually humans that
[tab]don't run away at the sight of me...
[wait][clear][end]

msg_14:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Forget about that,
[tab]how's about going somewhere with me!?
[wait][clear][end]

msg_15:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahahaha!
[tab]Is that a new way of flirting!?
[wait][clear][end]

msg_16:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, give me a break...
[tab]Are you trying to hit on me?
[tab]Hahahahahahaha!
[wait][clear][end]

msg_17:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahahaha!!
[tab]Feels good to have a mike in front of me!
[tab]Ya want me to sing!?
[wait][clear][end]

msg_18:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]For being a human, don't you think you're
[tab]getting a bit too friendly with me!?
[wait][clear][end]

msg_19:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I've nothing to say to a human...!
[tab]Dumbass!
[wait][clear][end]

msg_20:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I don't know, but I'm pissed...
[wait][clear][end]

msg_21:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]H-Hey...
[tab]Y-You're up to something, huh?
[wait][clear][end]

msg_22:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Is, is it me, or do I feel
[tab]a nasty atmosphere?
[wait][clear][end]

msg_23:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I'm not talking...
[tab]Even I can keep a secret!
[wait][clear][end]

msg_24:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Your fortunes seem to come true!
[wait][clear][end]

msg_25:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Even though they're iffish,
[tab]I still worry about fortunes...
[wait][clear][end]

msg_26:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]Not bad for a human!
[wait][clear][end]

msg_27:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]A human, telling a demon's fortune?!
[tab]You've come to the wrong person!!
[tab]Hahahahahahahaha!!
[wait][clear][end]

msg_28:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, wait!
[tab]Trying to trick me with that crap!?
[tab]I'm not gonna let you get away with that!!
[wait][clear][end]

msg_29:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]For a human to talk to me like that...
[tab]you're about a thousand years too young!!
[wait][clear][end]

msg_30:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I don't have time to play house! ...Dumbass!!
[wait][clear][end]

msg_31:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]F-Fortunes, you say...?
[tab]She's just gonna try to preach religion...
[wait][clear][end]

msg_32:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're just saying that because you're
[tab]planning to stab me, aren't you ...?
[wait][clear][end]

msg_33:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're a real pig, I mean, a real "cop"?
[tab]Then you carry a gun, right!?
[wait][clear][end]

msg_34:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]Dude, you look kinda bitchin'!
[wait][clear][end]

msg_35:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!!
[tab]For a human trying to judge a demon,
[tab]you're about a thousand years too young!!
[wait][clear][end]

msg_36:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]You've been watching too many cop shows!!
[wait][clear][end]

msg_37:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're just a power hungry pig!
[tab]Stop trying to act like a hero!!
[wait][clear][end]

msg_38:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I said,
[tab]I don't know that skirt!
[tab]You're frickin' stubborn!!
[wait][clear][end]

msg_39:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Th-th-that chick!
[tab]I-I-I don't know her...
[tab]I-I t-told you I don't know her!
[wait][clear][end]

msg_40:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-You trying to threaten me?
[wait][clear][end]

msg_41:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm...
[tab]I sound like THAT!?
[tab]It doesn't fit my image...

[wait][clear][end]

msg_42:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]When you think about it,
[tab]that's not my voice...
[tab]But I've heard it somewhere else...
[wait][clear][end]

msg_43:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You got guts for a human!
[tab]You can be my brother!!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_44:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I have a good voice, huh?
[tab]Maybe I should be a singer?!
[tab]Hahahahaha!!
[wait][clear][end]

msg_45:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!!
[tab]Don't think I'd be scared by that...!
[tab]Dumbass!!
[wait][clear][end]

msg_46:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]Aren't you a little too suspicious?
[wait][clear][end]

msg_47:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]W-When did you make that tape...?
[tab]W-What do you know about me...?
[wait][clear][end]

msg_48:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You got it all wrong!!
[tab]This country doesn't have many babes,
[tab]so how about importing some?
[wait][clear][end]

msg_49:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Da---mn!
[tab]You're saying some complicated stuff,
[tab]but it's all good, as long as it's fun!
[wait][clear][end]

msg_50:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, smile!!
[tab]Smile and forget the complicated things!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_51:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!!
[tab]It's too complicated for me to understand!
[tab]Guess I'll have to just smile and nod!!
[wait][clear][end]

msg_52:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y'know, shut up...!
[tab]Dumbass!!
[wait][clear][end]

msg_53:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boring...!
[wait][clear][end]

msg_54:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y'know, listening to you speak makes me
[tab]concerned about my brain...
[wait][clear][end]

msg_55:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh--! Yeah--!!
[tab]I can smell someone's pheromome!
[wait][clear][end]

msg_56:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Just a little more and I can see it...
[wait][clear][end]

msg_57:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I like that backside!
[tab]Hahahahaha!!
[wait][clear][end]

msg_58:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't get so full of yourself...!
[tab]Bitch!!
[wait][clear][end]

msg_59:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]So what!?
[tab]This ain't fun!!
[wait][clear][end]

msg_60:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]A beautiful rose still has thorns, huh...
[wait][clear][end]

msg_61:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmm..
[tab]Looking closely, you look like someone...
[wait][clear][end]

msg_62:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I won't lose a staredown!!
[wait][clear][end]

msg_63:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]You're really ugly!!
[wait][clear][end]

msg_64:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Stop acting-up...!!
[tab]Dumbass!!
[wait][clear][end]

msg_65:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hu---Hh?
[tab]Whaddya want?
[wait][clear][end]

msg_66:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-You look just a bit strong...
[wait][clear][end]

msg_67:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You ain't no normal human...
[wait][clear][end]

msg_68:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Getting the guys to decide...
[tab]That's a way you girls hit on men, right?
[wait][clear][end]

msg_69:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm...
[tab]You're BOTH my type...
[tab]Can't I have both of you?
[wait][clear][end]

msg_70:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'm fine, as long as
[tab]your breasts are big!
[wait][clear][end]

msg_71:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]As long as you go out with me,
[tab]I don't care which one!!
[wait][clear][end]

msg_72:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I can tell my type by the person's style,
[tab]so let's see some skin...!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_73:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?
[tab]Whaddya talkin' about, bitch?!!
[tab]All human broads are the same!!
[wait][clear][end]

msg_74:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Well then, someone, anyone,
[tab]listen to what I have to say---!
[wait][clear][end]

msg_75:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Now that I think about it, I've never had
[tab]a friend to hear my problems...
[tab]You guys would really help me out!?
[wait][clear][end]

msg_76:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You know, killing innocent humans
[tab]weighs on my conscience...
[tab]Hahahahahaha!!
[wait][clear][end]

msg_77:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]There are people who are concerned for
[tab]little ol' me...
[tab]I'm SO happy!!
[wait][clear][end]

msg_78:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, wait!!
[tab]To get the sympathy of humans
[tab]is a demon's biggest shame!!
[wait][clear][end]

msg_79:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Geez, you're getting cocky.
[tab]There's no one as brave as
[tab]a big-headed human.
[wait][clear][end]

msg_80:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey, stop teasing me,
[tab]and start asking me some questions!
[wait][clear][end]

msg_81:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]OH MAMA!
[tab]Girl asking me questions, you're my type!
[wait][clear][end]

msg_82:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]Beating around the bush...
[tab]You're really interested in me, huh?!!
[wait][clear][end]

msg_83:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, it's fine that you're hard-working,
[tab]but I can see your underwear ...PSYCH!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_84:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]How dare you ignore me!!
[tab]You stupid pig!!
[wait][clear][end]

msg_85:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh yeah, gettin' down...!?
[tab]Wait... but, that dance seems
[tab]like some kind of a ritual...
[wait][clear][end]

msg_86:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Yeah--!
[tab]Then, I'll be the judge!!
[tab]That dance gets... an 8.5!!
[wait][clear][end]

msg_87:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Then, I'll be the judge!!
[tab]That dance gets... a 3!!
[tab]Hahahahaha!!
[wait][clear][end]

msg_88:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]It's a lot better to watch you guys
[tab]dance with straight faces!!
[wait][clear][end]

msg_89:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Shuuuuuuuut the FUUUUUCCCK
[tab]Uuuuuuuuuuuup!!!!!!
[wait][clear][end]

msg_90:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ugh-------!
[tab]Beyond pathetic!!
[tab]So pathetic, I'm pissed!
[wait][clear][end]

msg_91:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]W-What kind of ritual is it...?
[tab]I wouldn't happen to be the "sacrifice"!?
[wait][clear][end]

msg_92:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Can I trust you guys...?
[tab]But, y'know, you're not putting your
[tab]heart and soul into it...
[wait][clear][end]

msg_93:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You really need me?
[tab]Should I trust you...?
[wait][clear][end]

msg_94:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmmmmm...
[tab]I don't know what you're saying, but,
[tab]at any rate, you need my powers!
[wait][clear][end]

msg_95:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]A trade for my working with you...
[tab]Go kill all other humans in sight!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_96:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!
[tab]Focus, and look closely...!!
[tab]Do I look like a person easily persuaded?
[wait][clear][end]

msg_97:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]...Y'know.
[tab]I haven't sunken THAT low to
[tab]cooperate with humans!!
[wait][clear][end]

msg_98:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Th-There's a big "LIE"
[tab]written all over your face...
[wait][clear][end]

msg_99:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmm...
[tab]Humans think of complicated stuff, too...
[wait][clear][end]

msg_100:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Da---mn!
[tab]You're saying some complicated stuff,
[tab]but it's all good, as long as it's fun!
[wait][clear][end]

msg_101:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]This guy's really troubled!
[tab]It's fun to see people's troubled faces!
[wait][clear][end]

msg_102:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]So what are you trying to say!?
[tab]I have nothing to do with it!!
[tab]Dumbass!!
[wait][clear][end]

msg_103:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're pretty kind, huh?
[tab]Let me call you "Bro" too!!
[wait][clear][end]

msg_104:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Man, I can't bear to watch...
[tab]Let's forget about this indecisive fool,
[tab]and go play---!
[wait][clear][end]

msg_105:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey...
[tab]Such a touching brotherhood...
[tab]I'm moved!
[wait][clear][end]

msg_106:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]Even if you're not real brothers, 
[tab]I wouldn't be surprised if you were killed!
[wait][clear][end]

msg_107:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I get pissed just watching your dithering!
[wait][clear][end]

msg_108:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]They're ignoring me...
[tab]I-If they combine forces,
[tab]I might not be able to beat 'em...
[wait][clear][end]

msg_109:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm... I see....
[tab]Pretending to be a poet, 
[tab]and then making the move on the chicks...
[wait][clear][end]

msg_110:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm...
[tab]You're general knowledge is impressive...
[wait][clear][end]

msg_111:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Only your knowledge is first class!
[tab]Hahahahahaha!
[wait][clear][end]

msg_112:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]For puny humans, you're way too
[tab]young to talk about drinking.
[tab]Hahahahahaha!
[wait][clear][end]

msg_113:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Stop trying to act tough...!
[tab]Dumbass!!
[wait][clear][end]

msg_114:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]Enough with the general knowledge.
[tab]Just shut the hell up already!!
[wait][clear][end]

msg_115:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I guess it's really true that a
[tab]person knows no fear when he's drunk.
[wait][clear][end]

msg_116:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?
[tab]A fight?
[tab]Go! Go! Beat the snot outta 'em!
[wait][clear][end]

msg_117:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]You guys, did you know that the
[tab]"Striped Garps" are the favorites!?
[wait][clear][end]

msg_118:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh, a quarrel!!
[tab]I couldn't have asked for more!
[tab]Hahahahaha!!
[tab][wait][clear][end]

msg_119:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't bullshit me!!
[tab]The "Striped Garps" are the best..!
[tab]Dumbass!!
[wait][clear][end]

msg_120:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y'know, when I look at you two,
[tab]it looks religious...
[wait][clear][end]

msg_121:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmm...
[tab]You seem to be very experienced...
[wait][clear][end]

msg_122:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I don't really understand, but,
[tab]You're tasteful...
[wait][clear][end]

msg_123:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]Y'know, you're in front of ME!
[tab]Talk about something interesting!!
[wait][clear][end]

msg_124:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey!
[tab]If I speak my mind, will I get something?
[wait][clear][end]

msg_125:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'm thinking, I'm thinking!
[wait][clear][end]

msg_126:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]You wanna hear my opinions!?
[wait][clear][end]

msg_127:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I won't tell you...
[tab]Hahahahahaha!!
[wait][clear][end]

msg_128:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I don't understand, but kill them...
[tab]For now, kill them...
[tab]Hahahahahaha!!
[wait][clear][end]

msg_129:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]D-Don't ask me about
[tab]those difficult things...!
[tab]Dumbass!
[wait][clear][end]

msg_130:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]N-Not good...
[tab]I can't follow...
[wait][clear][end]

msg_131:
[color(yellow)][var(msg_var_0)][color(white)]
[tab] Uh, uh! Shoot!
[tab] W-W, What should I do...?
[wait][clear][end]

msg_132:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmm...
[tab]You guys are good with your mouths,
[tab]but seem suspect in your skills...?
[wait][clear][end]

msg_133:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I don't know how you say such things...
[tab]If trash-talking were a sport, 
[tab]you guys would be a championship team.
[wait][clear][end]

msg_134:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]The weaker they are, the louder they bark.
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_135:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey...
[tab]Cut it out, I'll kill you...
[wait][clear][end]

msg_136:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'm, seriously, gonna blow...
[wait][clear][end]

msg_137:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]D-Did I get caught up in this?
[wait][clear][end]

msg_138:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I see...
[tab]If it weren't a world where power rules,
[tab]you wouldn't be saying that...
[wait][clear][end]

msg_139:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]But, I think for some reason, 
[tab]the ones doing the crying are the men...
[wait][clear][end]

msg_140:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Anyways...
[tab]Shouldn't you get a boyfriend soon?
[tab]Hahahahahaha!
[wait][clear][end]

msg_141:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Are you a moron?
[tab]Women should just follow men!!
[wait][clear][end]

msg_142:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's scary to piss off a dame...
[wait][clear][end]

msg_143:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]For men and women, if the other gender was gone, 
[tab]there would be less troubles,
[tab]but there would be even less fun...
[wait][clear][end]

msg_144:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's the jealousy of an unpopular girl!
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_145:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You know,
[tab]it looks like I'm being scolded...
[wait][clear][end]

msg_146:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's cool, being able to say THAT...
[tab]I should hurry and get a girlfriend!!
[wait][clear][end]

msg_147:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Well, with a girl as hot as that, 
[tab]it's no wonder steam's coming off his head.
[wait][clear][end]

msg_148:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]What a corny phrase!!
[wait][clear][end]

msg_149:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Is that a script?
[tab]Hahahahaha!!
[wait][clear][end]

msg_150:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]I don't understand, but I'm the bad guy...?
[wait][clear][end]

msg_151:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-Y'know, your eyes are bloodshot...
[wait][clear][end]

msg_152:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmm...
[tab]I heard all brothers are on ill terms,
[tab]you guys don't seem to be...
[wait][clear][end]

msg_153:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Listening to your conversation
[tab]takes me back to the old days...
[wait][clear][end]

msg_154:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]Stop that crappy acting!
[wait][clear][end]

msg_155:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]The way I see it...
[tab]Back then, I had my say...
[wait][clear][end]

msg_156:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]A fight!?
[wait][clear][end]

msg_157:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What, are you at that "rebel" period?
[wait][clear][end]

msg_158:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Everything depends on your tone of voice.
[tab]Hahahahaha!!
[wait][clear][end]

msg_159:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You'll never understand each other
[tab]talking about such stupid things!!
[tab]Hahahahaha!
[wait][clear][end]

msg_160:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Wahhh!
[tab]My nose! ...It's bleeding!!
[wait][clear][end]

msg_161:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Tired of humans, and now after a demon...?
[tab]You girls are easy, huh?
[tab]Hahahahahaha!
[wait][clear][end]

msg_162:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahaha!!
[tab]They're showin' it all off!
[tab]Human girls must be pretty easy!!
[wait][clear][end]

msg_163:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-You idiots...!!
[tab]Do you really see me as
[tab]THAT desperate for a woman?!!
[wait][clear][end]

msg_164:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Teasing me, you lowlife human!!
[tab]So what if I'm the type
[tab]to be toyed with by girls!!
[wait][clear][end]

msg_165:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I-It's a slut...
[wait][clear][end]

msg_166:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What are you, stale goods?
[tab]Boy, get a couple of aging maids together,
[tab]and they go on and on...
[wait][clear][end]

msg_167:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmm... It's the way it is...
[tab]If you don't marry soon, you'll be an old maid!
[wait][clear][end]

msg_168:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, Hey! That biological clock is tickin'.
[tab]Before it stops, you better get a man!
[tab]Tick, tick, tick... Hahahahahaha!!
[wait][clear][end]

msg_169:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]You're not in a position to be picky!
[tab]Tick, tick, tick... Hahahahahaha!
[wait][clear][end]

msg_170:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What are you doing there in secret!?
[tab]That pisses me off!!
[wait][clear][end]

msg_171:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey...
[tab]Even if you do marry, it's not gonna last...
[wait][clear][end]

msg_172:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It, It's like they're making fun of guys...
[wait][clear][end]

msg_173:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]What's going on, with this chaos?
[wait][clear][end]

msg_174:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Mmmmmm..
[tab]That drink looks good...
[tab]I can't hold back!!!!
[wait][clear][end]

msg_175:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I kneel in reverence to your hypertension...
[wait][clear][end]

msg_176:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!!
[tab]The long-awaited occasion!
[tab]We're all gonna celebrate tonight!!!
[wait][clear][end]

msg_177:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Show me some skin!
[tab]Let's kick-up this party!!
[tab]Hahahahahahah!!
[wait][clear][end]

msg_178:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You smell like liquor...
[tab]Dumbass!!
[wait][clear][end]

msg_179:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ugh! ...Smells like barf!
[tab]Who the hell puked...!?
[tab]Dumbass!!
[wait][clear][end]

msg_180:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What's up with this?
[tab]This high anxiety....
[tab]I'm so uneasy...
[wait][clear][end]

msg_181:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You guys are the only ones
[tab]who say what you mean...
[tab]I'm lucky...
[wait][clear][end]

msg_182:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Is that how I'm portrayed by humans?
[wait][clear][end]

msg_183:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Yeah, that's right!
[tab]So what...?
[tab]Hahahahaha!!
[wait][clear][end]

msg_184:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]In the human world, they like to tell
[tab]stories like that at summer camp...
[wait][clear][end]

msg_185:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'm scared, but is there more...!?
[wait][clear][end]

msg_186:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Did you make that story up?
[tab]It was very good...
[wait][clear][end]

msg_187:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?
[tab]That wasn't supposed to be funny?
[tab]Hahahahahaha!!
[wait][clear][end]

msg_188:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]N--? There's a puddle by your feet...
[tab]Just joking...!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_189:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You frickin' swine!!
[tab]Next time you open your mouth, you're dead!
[wait][clear][end]

msg_190:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-You!
[tab]You were trying to scare me, huh!?
[tab]You're on! ...Dumbass!!
[wait][clear][end]

msg_191:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I, I don't want to listen anymore!!
[wait][clear][end]

msg_192:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I can't go to the bathroom by myself...
[wait][clear][end]

msg_193:
[end]

msg_194:
[end]

msg_195:
[end]

msg_196:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's brave...
[tab]Do it... if you can... huh...
[tab]Hahahahaha!!
[wait][clear][end]

msg_197:
[end]

msg_198:
[end]

msg_199:
[end]

msg_200:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Whoops, I killed 'em...
[tab]I feel sooo sorry...
[tab]Hahahahahaha!!
[wait][clear][end]

msg_201:
[end]

msg_202:
[end]

msg_203:
[end]

msg_204:
[end]

msg_205:
[end]

msg_206:
[end]

msg_207:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]More! More!
[tab]Give it to 'em!!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_208:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]You were friends, weren't you?
[tab]You're pretty cruel!!
[wait][clear][end]

msg_209:
[end]

msg_210:
[end]

msg_211:
[end]

msg_212:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey, are you serious...?
[tab]Hahahahahaha!!
[tab]How lame!!!
[wait][clear][end]

msg_213:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I can't really trust this...
[wait][clear][end]

msg_214:
[tab]Anyway, please autograph this paper!
[choice(4)]Maya Amano
M A Y A
Maya The Champ
Heeeeere's Maya!
[end_choice][clear][end]

msg_215:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]When I saw the name,
[tab]I felt a shudder down my back...
[wait][clear][end]

msg_216:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]Isn't this a bit cruel?
[wait][clear][end]

msg_217:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Wha...!?
[tab]YOU'RE a champion wrestler!? 
[tab]With that body!? Girls these days are strong...
[wait][clear][end]

msg_218:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey!
[tab]Don't play stupid games with me!!
[wait][clear][end]

msg_219:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Sh-She's cute...
[wait][clear][end]

msg_220:
[tab]Hey, hooters, howsabout it?..
[choice(3)]Sure, why not?
Not with a person who's after looks.
Shut up, pervert!!
[end_choice][clear][end]

msg_221:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]Other than your appearance,
[tab]I don't see any other points!
[wait][clear][end]

msg_222:
[tab]...So how else did you catch men?
[choice(3)]With a smile!
With a sexy pose - Just kidding!
With force!
[end_choice][clear][end]

msg_223:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh--!
[tab]Service with a smile, huh!?
[wait][clear][end]

msg_224:
[tab]Whatcha gonna do about this bloody nose!?
[choice(4)]Wipe it.
Lick it.
Pound it.
Nothing.
[end_choice][clear]
[end]

msg_225:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I think I'm falling in love!
[wait][clear][end]

msg_226:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Who said to wipe it!!
[wait][clear][end]

msg_227:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ouch!!
[tab]You're hitting me hard
[tab]to weaken me, aren't you!?
[wait][clear][end]

msg_228:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]W-What!?
[tab]Stop staring at me, it's embarrassing!
[wait][clear][end]

msg_229:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]Don't just stand there, DO something...!
[tab]Dumbass!!
[wait][clear][end]

msg_230:
[tab]Hey! Turn the mike this way!!
[choice(3)]Turn glances toward him.
Turn weapons on him.
Turn backs on him.
[end_choice][clear][end]

msg_231:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Eh!?
[tab]She's cute...
[wait][clear][end]

msg_232:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]OH MAMA!
[tab]Baby gots some nice booty!!
[wait][clear][end]

msg_233:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I've been ignored completely...
[tab]Now I'm really pissed...
[wait][clear][end]

msg_234:
[tab]...If you give me the gun, I'll talk!
[choice(4)]Give him the gun.
Give him candy.
Give him love.
Give him nothing.
[end_choice][clear]
[end]

msg_235:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]You're great!!
[wait][clear][end]

msg_236:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]This is exactly why people say
[tab]the Police are dirty...!!
[tab]Dumbass!!
[wait][clear][end]

msg_237:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh...?
[tab]How'd you know I got a sweet tooth...?
[tab]All right detective!!
[wait][clear][end]

msg_238:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I said give it to me, DAMN IT...!
[tab]You Dumbass!!
[wait][clear][end]

msg_239:
[tab]...What could be missing?
[choice(3)]We're missing love for you.
You want me to flatter you more?
Stop being selfish...
[end_choice][clear][end]

msg_240:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's it!
[tab]Love, we're missing love!!
[tab]We need love everywhere!!
[wait][clear][end]

msg_241:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're showing a lot of support...
[tab]Y-You strong?
[wait][clear][end]

msg_242:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!
[tab]You say clever things!
[wait][clear][end]

msg_243:
[tab]Where did you get that saying from?
[choice(3)]Our ancestors left it behind.
In conversations with other people.
In some magazine somewhere.
[end_choice][clear][end]

msg_244:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]What kind of people you hang out with?
[wait][clear][end]

msg_245:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]No half-hearted answers...!
[tab]Dumbass!!
[wait][clear][end]

msg_246:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]L-L-L-Let me borrow that magazine!!
[wait][clear][end]

msg_247:
[tab]Is it all right to call you big bro?
[choice(2)]Go ahead...
How's "Katsuya-nii"?
[end_choice][clear][end]

msg_248:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]B-Big bro-----!!
[wait][clear][end]

msg_249:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]When I think about it, why do I have
[tab]to call a human "big bro"...?
[tab]Don't get cocky! ...Dumbass!!
[wait][clear][end]

msg_250:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]Your name's "Katsuya"...?
[tab]It sounds weak to me!
[wait][clear][end]

msg_251:
[tab]Then tell me who's gonna be my girl!
[choice(4)]A pretty model!
A female wrestler
It's not a girl...
Don't bet on it!
[end_choice][clear][end]

msg_252:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Dammit, anyone will do!!
[wait][clear][end]

msg_253:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]R-Really?
[tab]Th-That's not good...
[wait][clear][end]

msg_254:
[tab]Wait, that IS a ritual, isn't it!?
[choice(3)]It grants one's love wishes!
It makes humans become gods...
It's a ritual to destroy you...
[end_choice][clear][end]

msg_255:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!!
[tab]Go ahead and try!!
[wait][clear][end]

msg_256:
[tab]WHY doesn't it fit my image?
[choice(3)]Because it's not your voice...
Your voice sucks!
It's coming from your stomach.
[end_choice][clear][end]

msg_257:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]So, you mean that there's some
[tab]ventriloquist somewhere...?!
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_258:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't say any more...
[tab]I already know that...
[wait][clear][end]

msg_259:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What!?
[tab]Say that again...
[tab]I'll rip your tongue off!
[wait][clear][end]

msg_260:
[tab]Teach me a wise saying!
[choice(3)]The power of human love is boundless.
Dreams are windows to the soul.
Excuses are like armpits, both stink.
[end_choice][clear]
[end]

msg_261:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey! Hold up!!
[tab]What do you mean "human love"!?
[tab]Demons can't love!!?
[wait][clear][end]

msg_262:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]There's something wrong with this guy...
[wait][clear][end]

msg_263:
[tab]I want to hear something good...
[choice(4)]About marriage
Talk business
Tell ghost stories
Tell some jokes
[end_choice][clear][end]

msg_264:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahaha!!
[tab]Tell me more!!
[wait][clear][end]

msg_265:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's getting cold...
[tab]You're not funny...!
[tab]You Dumbass!!
[wait][clear][end]

msg_266:
[tab]You don't plan to start a ritual, do you?
[choice(3)]It's ritual time!
It's party time!
It's funeral time!
[end_choice][clear][end]

msg_267:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-You ARE thinking
[tab]about sacrificing me...
[wait][clear][end]

msg_268:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Whew! ...Just a party...
[tab]Let's drink up, then!!
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_269:
[tab]C'mon and start beating on each other!!
[choice(3)]Hit 'em
Don't hit 'em
Hit [var(msg_var_0)]
[end_choice][clear][end]

msg_270:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey..
[tab]Tha, That was just a joke...
[wait][clear][end]

msg_271:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You afraid? ...You losers!!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_272:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Th-That hurt! Hey!!
[tab]You wanna die? ...Dumbass!!
[wait][clear][end]

msg_273:
[tab]Don't you think? You like blondes, too!?
[choice(3)]Blondes are the best!
Japanese chicks are #1!!
I'm not into girls.
[end_choice][clear][end]

msg_274:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]We will get along well!
[wait][clear][end]

msg_275:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahaha!!
[tab]Isn't it!?
[tab]It's all about internationalism!!
[wait][clear][end]

msg_276:
[tab]Do I get compensation!?
[choice(3)]I'll hook you up with a girl!
I'll adopt you!
I'll do nothing!
[end_choice][clear][end]

msg_277:
[tab]From now, you're my good buddies!
[choice(3)]OKAY...
If you become my slave.
Yeah, right...
[end_choice][clear][end]

msg_278:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]Can't you tell a joke...?
[tab]Like I would be friends with humans!
[wait][clear][end]

msg_279:
[tab]You want to do battle with me?
[choice(3)]I won't go easy on you!
If it's a battle of wits...
Screw you!
[end_choice][clear][end]

msg_280:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahaha!!
[tab]You really are weak!!
[wait][clear][end]

msg_281:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's not manly to run away!!
[tab]You lousy pig!!
[wait][clear][end]

msg_282:
[tab]...? But what's this "other" smell?
[choice(3)]It's my perfume.
It's your fart.
There's a fire around here.
[end_choice][clear][end]

msg_283:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I see, it smells good.
[tab]Is that "Channel No. 2+3"
[wait][clear][end]

msg_284:
[color(yellow)][var(msg_var_0)][color(white)]
[tab](cough) (cough)
[tab]That's too strong, you bitch!!
[wait][clear][end]

msg_285:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Damn, she figured it out...!
[tab]I'll have to smile my way out of this!!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_286:
[tab]You'll just have guys protect you, right?
[choice(2)]I just know it, HE will save me!
I can protect myself!
[end_choice][clear][end]

msg_287:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Well, when that happens,
[tab]I'll protect you!!
[wait][clear][end]

msg_288:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]I'd like that too!
[wait][clear][end]

msg_289:
[tab]So you got any summer stuff to do?
[choice(3)]Square dancing!
Watermelon crushing!
The beach!
[end_choice][clear][end]

msg_290:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]After square dancing,
[tab]you all sit in a circle, huh?
[wait][clear][end]

msg_291:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Damn...!
[tab]It's a senior citizens' party...
[wait][clear][end]

msg_292:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Crushing watermelons is fun,
[tab]but how about using your head instead...?
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_293:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Of course...
[wait][clear][end]

msg_294:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Yeah, the beach!
[tab]I love those gals in thongs!
[wait][clear][end]

msg_295:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Beach trip sounds good!
[tab]I'll rub oil all over you myself!
[tab]Hahahahahahaha!
[wait][clear][end]

msg_296:
[tab]Huh? Does that make me a poet?
[choice(3)]You're a poet.
You're a god!
You're an idiot!
[end_choice][clear][end]

msg_297:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]No need for flattery!
[wait][clear][end]

msg_298:
[tab]Who the hell do you look like...?
[choice(2)]My brother, Katsuya!
A handsome actor!
[end_choice][clear][end]

msg_299:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]So, your brother's ugly too then...
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_300:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]There is someone like that, huh...
[wait][clear][end]

msg_301:
[tab]Let's go to a frat party!!
[choice(3)]No, I have Maya.
Only if you don't tell Maya.
I'm not interested.
[end_choice][clear][end]

msg_302:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're pretty serious about her, huh...
[wait][clear][end]

msg_303:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Isn't that a little mean!?
[tab]Think about how she'll feel!!
[wait][clear][end]

msg_304:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Can't say yes in front of your girl, huh?
[tab]Hahahahahaha!!
[wait][clear][end]

msg_305:
[tab]But I wanted a cute little sister...
[choice(3)]Actually, so did I.
Actually, I'm your sister.
Actually, you have a sister.
[end_choice][clear][end]

msg_306:
[tab]W-Well... y'know, um...
[choice(2)]No, I don't know...
Yeah, I know what you're saying...
[end_choice][clear][end]

msg_307:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Yeah, you know!!
[tab]You understand what I want to say!!
[wait][clear][end]

msg_308:
[tab]What kind of guy is your type?
[choice(3)]Tall, dark, and handsome!
A successful one!
Well, not you...
[end_choice][clear][end]

msg_309:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!!
[tab]Even if he's good enough for you,
[tab]you're not good enough for him!
[wait][clear][end]

msg_310:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Are you stupid...!?
[tab]Keep dreaming!
[wait][clear][end]

msg_311:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm..
[tab]A successful one eh... I see... 
[tab]I guess I better become very successful...
[wait][clear][end]

msg_312:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I refuse too!!
[tab]Hahahahahaha!!
[wait][clear][end]

msg_313:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]They call humans who collect things
[tab]"collectors," right?
[tab]Well then...
[wait][clear][end]

msg_314:
[tab]What kind of collector are you?
[choice(3)]Card collector
Weapon collector
Demon collector
[end_choice][clear][end]

msg_315:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey, you!
[tab]You just want my cards!
[tab]You're annoying! ...Dumbass!!
[wait][clear][end]

msg_316:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Wea, Weapons?
[tab]You're a dangerous guy...
[wait][clear][end]

msg_317:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Whaddya mean "weapons!"
[tab]Just go play with your water pistol!!
[wait][clear][end]

msg_318:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-You're can't be...
[tab]A D-De-Devil Summoner!?
[wait][clear][end]

msg_319:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Then, you're a "summoner"?
[tab]You made my dad a "demon-friend"!!
[tab]I'm gonna kill you!!
[wait][clear][end]

msg_320:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]When humans fall in love,
[tab]they write "love letters," right...?
[tab]I don't really understand...
[wait][clear][end]

msg_321:
[tab]Why do they write love letters?
[choice(3)]Humans are shy but expressive.
It contains love magic.
It's the law.
[end_choice][clear][end]

msg_322:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]I never heard of a law like that!
[tab]You're an idiot!!
[wait][clear][end]

msg_323:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]They have a special ceremony when one
[tab]becomes an adult, right?
[tab]I want to ask you...
[wait][clear][end]

msg_324:
[tab]What kind of ceremony is it?
[choice(3)]A speech
A bungee jump
A drink fest
[end_choice][clear][end]

msg_325:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahaha!
[tab]How stupid!
[wait][clear][end]

msg_326:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh, I know that. That's where
[tab]you go jump off high places!!
[tab]You've got guts!
[wait][clear][end]

msg_327:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's where you jump off high spots...
[tab]You don't have that kind of bravery!
[tab]Don't show off. Go fetch me a drink!
[wait][clear][end]

msg_328:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]R-Really!?
[tab]Is it okay to do stuff like that!?
[wait][clear][end]

msg_329:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y'know
[tab]I found a camera,
[tab]but I don't know how to use it...
[wait][clear][end]

msg_330:
[tab]What should I take a picture of first?
[choice(4)]Humans
The truth
Nature
Nude women
[end_choice][clear][end]

msg_331:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh! I see!!
[tab]If you'd become the model, we'd be done!
[tab][wait][clear][end]

msg_332:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's just a waste of film
[tab]to take pictures of humans!!
[tab]Dumbass!!
[wait][clear][end]

msg_333:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]The truth... that's deep...
[tab]I feel a desire to do it now!!
[wait][clear][end]

msg_334:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]Y'know the only thing you're good at
[tab]is saying cheesy phrases!
[wait][clear][end]

msg_335:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're right!
[tab]I can get back to nature and relax!
[wait][clear][end]

msg_336:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]Can you be saying that?
[tab]You, the same humans who destroy nature!?
[wait][clear][end]

msg_337:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Is, Is that
[tab]what they call "art"?
[wait][clear][end]

msg_338:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey!
[tab]If you really think so, don't just stand
[tab]there, go fetch a model!! Dumbass!!
[wait][clear][end]

msg_339:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What the hell do you want!?
[tab]Calling me this way...!
[tab]And you're a frickin' human!!
[wait][clear][end]

msg_340:
[tab]You wanna be killed by me!?
[choice(4)]I wanna die.
I don't wanna die.
You will die.
CAN you kill me?
[end_choice][clear][end]

msg_341:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahaha!
[tab]Because you're so blunt,
[tab]I don't even feel like killing you!
[wait][clear][end]

msg_342:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Y-Your creepy...
[wait][clear][end]

msg_343:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hahahahahahaha!
[tab]You're really afraid!
[wait][clear][end]

msg_344:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]This is no good...
[wait][clear][end]

msg_345:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm...
[tab]So how are you going to kill me?
[tab]This ought to be interesting!
[wait][clear][end]

msg_346:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]But you know, why are you, a human,
[tab]talking to me, a demon, so casually?
[wait][clear][end]

msg_347:
[tab]Are you getting cocky!?
[choice(2)]You got a problem with that?
Noooo, I'd never do that!
[end_choice][clear][end]

msg_348:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]An unexpected answer!
[tab]You got some good points!
[wait][clear][end]

msg_349:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Then, what are you getting on?
[tab]A toilet?
[tab]Hahahahahahaha!!
[wait][clear][end]

msg_350:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]No, no, you ARE getting cocky!!
[tab]Now, I'm pissed!!
[wait][clear][end]

msg_351:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are not suited to talk about bikes...!
[tab]Dumbass!!
[wait][clear][end]

msg_352:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]...You're dead.
[wait][clear][end]

msg_353:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]But y'know...
[tab]When I see a something as weak as a human,
[tab]I just kinda want to bully them...
[wait][clear][end]

msg_354:
[tab]What do you guys think of demons?
[choice(3)]Trustworthy partners
Friends
. . . . . . . . .
[end_choice][clear][end]

msg_355:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't try to depend on me...!!
[tab]Dumbass!!
[wait][clear][end]

msg_356:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]R-Really...
[tab]You're down with a demon like me...
[wait][clear][end]

msg_357:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It would be fun to go with you guys,
[tab]but I'm pretty busy too, y'know...
[tab]So, I'll give you an important card.
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab][color(green)][var(msg_var_5)][color(white)] [color(green)][var(msg_var_4)][color(white)] card(s).
[wait][clear][end]

msg_358:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It was fun getting to know you guys!
[tab]I already thanked you, but take a card!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab][color(green)][var(msg_var_5)][color(white)] [color(green)][var(msg_var_4)][color(white)] card(s).
[wait][clear][end]

msg_359:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'll also give you [color(green)][var(msg_var_6)][color(white)] [color(green)]Free Tarot[color(white)] card(s).
[tab]It will be of good use to you!
[wait][clear][end]

msg_360:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?
[tab]Aren't you getting a little greedy?
[tab]You have enough!
[wait][clear][end]

msg_361:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Those cards are a sign of our friendship!
[tab]Take care of 'em!
[wait][clear][end]

msg_362:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I like you guys!!
[tab]If you want I'll sign a [color(green)]Pact[color(white)].
[wait][clear][end]

msg_363:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?
[tab]You're [color(green)]incredibly weak[color(white)]!
[tab]That was pretty reckless of you...
[wait][clear][end]

msg_364:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Well, when you've raised your skills,
[tab]call me again!
[tab]Later!!
[wait][clear][end]

msg_365:
[tab]Well? You want a [color(green)]pact[color(white)] with me?
[choice(2)]Yes
No
[end_choice][clear][end]

msg_366:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]We're companions now,
[tab]so it's nice to be workin' with ya....
[tab]Until we meet again, be safe!
[wait][clear][end]

msg_367:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh? Really?
[tab]That's kinda disappointing...
[tab]Well, later...
[wait][clear][end]

msg_368:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey! You have too many pacts!
[tab]You gotta [color(green)]break a Pact[color(white)] with someone.
[wait][clear][end]

msg_369:
[tab]Whose [color(green)]Pact[color(white)] you gonna [color(green)]break[color(white)]?
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_370:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Damn it!
[tab]I was shown up by a human!
[tab]Forget this, I'm outta here!!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Sorry, but I'm [color(green)]breaking[color(white)] this [color(green)]Pact[color(white)]!
[wait][clear][end]

msg_371:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Uh, y'know... I'm sorry, 
[tab]but could you [color(green)]break[color(white)] our [color(green)]Pact[color(white)]?
[tab]If you don't want to fine, but...
[wait][clear][end]

msg_372:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I feel sick to my stomach...
[tab]I'm leaving...
[wait][clear][end]

msg_373:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]My head hurts...
[tab]I'm going home...
[wait][clear][end]

msg_374:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh, shoot!!
[tab]Run away! Run away!!
[wait][clear][end]

msg_375:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You better knock it off!
[tab]I'm getting pissed!!
[wait][clear][end]

msg_376:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey!
[tab]Prepare a coffin - your size!!
[wait][clear][end]

msg_377:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I am very pissed off!!
[tab]I'm gonna kill you!!
[wait][clear][end]

msg_378:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're frickin' strong!
[tab]That's incredible!!
[wait][clear][end]

msg_379:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're incredibly strong!
[tab]Marvelous!!
[wait][clear][end]

msg_380:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I don't stand a chance...
[tab]You can boil me, roast me, or
[tab]do whatever you want!
[wait][clear][end]

msg_381:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Yeah--, that was really fun!!
[tab]I really want to thank you but...
[tab]I know...
[wait][clear][end]

msg_382:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Let's see...
[tab]I'll give you [color(green)][var(msg_var_1)][color(white)].
[tab]That's all I got on me, take care of it!
[wait][clear][end]

msg_383:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Let's see... Oh yeah,
[tab]I'll give you [color(green)]¥[var(msg_var_2)][color(white)].
[tab]Be thankful!
[wait][clear][end]

msg_384:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I know...
[tab]I'll [color(green)]recover[color(white)] your wounds!
[tab]This is my going-away present!
[wait][clear][end]

msg_385:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]See ya later!
[tab]Until we meet again, be safe!
[wait][clear][end]

msg_386:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, hey...
[tab]Just when I see a sad face, it's a human!
[tab]Well, this'll be a good time killer...
[wait][clear][end]

msg_387:
[color(green)]Selection ERROR[color(white)]
[end]

msg_388:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That smell... Back from a beauty spa!?
[tab]So you were getting ready for me...
[tab]I'm such a lucky guy\♥
[wait][clear][end]

msg_389:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh! You're especially beautiful today!
[tab]I'm so happy!!
[tab]You went to a beauty spa just for me...\♥
[wait][clear][end]

msg_390:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That enticing scent...
[tab]Back from the beauty spa\♥
[tab]Could this be "love"?
[wait][clear][end]

msg_391:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]A man, going to a beauty spa...?
[tab]I hate that!!
[wait][clear][end]

msg_392:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I thought something smelled, and it's you.
[tab]Stop wearing perfume, you're a guy!
[tab]You came out of a beauty spa, huh!?
[wait][clear][end]

msg_393:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]How nice, a man going to a beauty spa...!
[tab]Getting all dolled-up doesn't make you
[tab]any stronger! ...Dumbass!!
[wait][clear][end]

msg_394:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You know, somewhere in the back alleys
[tab]there seems to be a "Shrine of Warriors"!
[tab]"Warrior" sounds strong...
[wait][clear][end]

msg_395:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ever heard of Kiyohime nee-chan?
[tab]She is said to be very tidy!
[tab]I wonder if she would clean up that floor?
[wait][clear][end]

msg_396:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, in "Route B2,"
[tab]there's a rumor of big piles of treasure!
[tab]I want some, too...
[wait][clear][end]

msg_397:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, in "Route B3,"
[tab]there's a rumor of big piles of treasure!
[tab]I want some, too...
[wait][clear][end]

msg_398:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]An old man named "Rasputin" picked up a
[tab]"Fuse Box Key" and was making a fuss...
[tab]What's the big deal?
[wait][clear][end]

msg_399:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh yeah, when you look in a mirror,
[tab]left and right are reversed...
[tab]I bet you didn't know that!
[wait][clear][end]

msg_400:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]There's a "treasure room" at the bottom of
[tab]this building, but there's no door...
[tab]How the hell do you get in?!
[wait][clear][end]

msg_401:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You wanna get in the treasure room right?
[tab]Ask Leviathan.
[tab]He should be able to knock down the walls!
[wait][clear][end]

msg_402:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I saw a demon called "Seker"
[tab]jump over the "Unclosed Bridge" but,
[tab]that wasn't a half-hearted leap!!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]If we ask him to jump over,
[tab]he could push the switch over there and
[tab]open the "Unclosed Bridge"!
[wait][clear][end]

msg_403:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]On the road leading to Area 5,
[tab]there's a giant rock sitting in the way...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]The only one who can move that rock
[tab]around here is Shoggoth.
[tab]Well, that is of course, if he'd do it...
[wait][clear][end]

msg_404:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I just remembered...
[tab]When you were a kid, did you ever play
[tab]"Hide and Seek" with me?
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Back then, I hid behind the shrine,
[tab]and no one ever found me...
[tab]Ah, maybe it was someone else...
[wait][clear][end]

msg_405:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Now that I think of it, I just saw some
[tab]brat with a irritating face, holding a
[tab]flower! Feels like he once gave me orders.
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Who the hell was that guy?!
[wait][clear][end]

msg_406:
[end]

msg_407:
[end]

msg_408:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Katana[color(white)]
[tab]has [color(orange)]hidden powers[color(white)]!
[wait][clear][end]

msg_409:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Katana[color(white)]
[tab]is [color(orange)]the strongest[color(white)]!
[wait][clear][end]

msg_410:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Handgun[color(white)]
[tab]has [color(orange)]hidden powers[color(white)]!
[wait][clear][end]

msg_411:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Handgun[color(white)]
[tab]is [color(orange)]the strongest[color(white)]!
[wait][clear][end]

msg_412:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Coin[color(white)]
[tab]has [color(orange)]hidden powers[color(white)]!
[wait][clear][end]

msg_413:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Coin[color(white)]
[tab]is [color(orange)]the strongest[color(white)]!
[wait][clear][end]

msg_414:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Glove[color(white)]
[tab]has [color(orange)]hidden powers[color(white)]!
[wait][clear][end]

msg_415:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Glove[color(white)]
[tab]is [color(orange)]the strongest[color(white)]!
[wait][clear][end]

msg_416:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Rapier[color(white)]
[tab]has [color(orange)]hidden powers[color(white)]!
[wait][clear][end]

msg_417:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Keep this a secret from everyone!
[tab]They say the [color(orange)]Legendary Rapier[color(white)]
[tab]is [color(orange)]the strongest[color(white)]!
[wait][clear][end]

msg_418:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Plus, it's supposedly [color(orange)]really strong[color(white)]!
[wait][clear][end]

msg_419:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]But...
[tab]It's supposedly [color(orange)]really weak[color(white)]!
[tab]Hahahahahahaha!
[wait][clear][end]

msg_420:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's not that strong, but
[tab][color(orange)]it fuses with a secret spell[color(white)]!
[tab]Fusing is ALL THAT!!
[wait][clear][end]

msg_421:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Pyro Jack"?
[tab]He seems to be hiding the spell called
[tab][color(orange)]Dynamic Agilao[color(white)].
[wait][clear][end]

msg_422:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Jack Frost"?
[tab]He seems to be hiding the spell called
[tab][color(orange)]Atomic Bufula[color(white)].
[wait][clear][end]

msg_423:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Stymphalides"?
[tab]He seems to be hiding the spell called
[tab][color(orange)]Dangerous Garula[color(white)].
[wait][clear][end]

msg_424:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Barbatos"?
[tab]He seems to be hiding the spell called
[tab][color(orange)]Great Magnara[color(white)].
[wait][clear][end]

msg_425:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Ankou"?
[tab]He seems to be hiding the spell called
[tab][color(orange)]Hyper Zionga[color(white)].
[wait][clear][end]

msg_426:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Kanaloa"?
[tab]He seems to be hiding the spell called
[tab][color(orange)]Wondrous Aques[color(white)].
[wait][clear][end]

msg_427:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Demeter"?
[tab]She seems to be hiding the spell called
[tab][color(orange)]Ultra Freila[color(white)].
[wait][clear][end]

msg_428:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Succubus"?
[tab]She seems to be hiding the spell called
[tab][color(orange)]Super Megido[color(white)].
[wait][clear][end]

msg_429:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]If I talk with too many humans,
[tab]my image will tarnish...
[tab]But, instead...
[wait][clear][end]

msg_430:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh!
[tab]You're making a pact with me!
[tab]So, as promised, I'll be of service!
[wait][clear][end]

msg_431:
[tab]What should I do!?
[choice(4)]Give me an item.
Give me money.
Give me info.
[if(CBIT_HEAR_RUMOR)]Spread a rumor.
[end_choice][clear][end]

msg_432:
[tab]If there's a rumor, I'll spread it!
[choice(3)][if(CBIT_HEAR_WEPON)]Rumor about the Legendary Weapons.
[if(CBIT_HEAR_MAGIC)]Rumor about a spell.
Nothing in particular.
[end_choice][clear][end]

msg_433:
[tab]If there's a rumor, I'll spread it!
[choice(4)][if(CBIT_HEAR_WEPON)]Legendary Weapons
[if(CBIT_HEAR_MAGIC)]Rumor about a spell
[if(CBIT_HEAR_MAP1)]About this dungeon
Nothing special.
[end_choice][clear][end]

msg_434:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Everyone knows about that one!
[tab]Is there any other rumor?
[wait][clear][end]

msg_435:
[tab]What weapon?
[choice(6)][if(CBIT_HEAR_SWD)]Legendary Katana
[if(CBIT_HEAR_GUN)]Legendary Handgun
[if(CBIT_HEAR_GTR)]Legendary Coin
[if(CBIT_HEAR_FST)]Legendary Glove
[if(CBIT_HEAR_FLW)]Legendary Rapier
Never mind.
[end_choice][clear][end]

msg_436:
[tab]Whose spell?
[choice(6)][if(CBIT_HEAR_AGI)]Pyro Jack
[if(CBIT_HEAR_BUF)]Jack Frost
[if(CBIT_HEAR_GAR)]Stymphalides
[if(CBIT_HEAR_MAG)]Barbatos
[if(CBIT_RESERVE_Ff)]Some other demon.
Never mind.
[end_choice][clear][end]

msg_437:
[tab]Whose spell?
[choice(6)][if(CBIT_HEAR_JIO)]Ankou
[if(CBIT_HEAR_AQU)]Kanaloa
[if(CBIT_HEAR_FRA)]Demeter
[if(CBIT_HEAR_MEG)]Succubus
[if(CBIT_RESERVE_Fe)]Some other demon.
Never mind.
[end_choice][clear][end]

msg_438:
[tab]What kind of rumor?
[choice(3)][if(CBIT_HEAR_MAP1)]The fuse box in the Control Room...
[if(CBIT_HEAR_MAP2)]The locked door in the Control Room...
On second thought, Never mind.
[end_choice][clear][end]

msg_439:
[tab]What about the "katana"?
[choice(4)][if(CBIT_HEAR_SWD_G)][if_not(IBIT_SWD_LGND_G)]It's powerful?
[if(CBIT_HEAR_SWD_L)][if_not(IBIT_SWD_LGND_S)]It has dark power.
[if_not(IBIT_SWD_LGND_N)]It's ordinary.
[if_not(IBIT_SWD_LGND_B)]Never mind.
[end_choice][clear][end]

msg_440:
[tab]What about the "handgun"?
[choice(4)][if(CBIT_HEAR_GUN_G)][if_not(IBIT_GUN_LGND_G)]It's powerful?
[if(CBIT_HEAR_GUN_L)][if_not(IBIT_GUN_LGND_S)]It has dark power.
[if_not(IBIT_GUN_LGND_N)]It's ordinary.
[if_not(IBIT_GUN_LGND_B)]Never mind.
[end_choice][clear][end]

msg_441:
[tab]What about the "coin"?
[choice(4)][if(CBIT_HEAR_GTR_G)][if_not(IBIT_CON_LGND_G)]It's powerful?
[if(CBIT_HEAR_GTR_L)][if_not(IBIT_CON_LGND_S)]It has dark power.
[if_not(IBIT_CON_LGND_N)]It's ordinary.
[if_not(IBIT_CON_LGND_B)]Never mind.
[end_choice][clear][end]

msg_442:
[tab]What about the "glove"?
[choice(4)][if(CBIT_HEAR_FST_G)][if_not(IBIT_FST_LGND_G)]It's powerful?
[if(CBIT_HEAR_FST_L)][if_not(IBIT_FST_LGND_S)]It has dark power.
[if_not(IBIT_FST_LGND_N)]It's ordinary.
[if_not(IBIT_FST_LGND_B)]Never mind.
[end_choice][clear][end]

msg_443:
[tab]What about the "rapier"?
[choice(4)][if(CBIT_HEAR_FLW_G)][if_not(IBIT_NSW_LGND_G)]It's powerful?
[if(CBIT_HEAR_FLW_L)][if_not(IBIT_NSW_LGND_S)]It has dark power.
[if_not(IBIT_NSW_LGND_N)]It's ordinary.
[if_not(IBIT_NSW_LGND_B)]Never mind.
[end_choice][clear][end]

msg_444:
[tab]What about Pyro Jack?
[choice(6)][if(CBIT_HEAR_AGI_L)][if_not(BBIT_D_AGIRAO_L)]D. Agilao is strong
[if(CBIT_HEAR_AGI_M)][if_not(CBIT_HEAR_AGI_S)]Uses Dynamic Agilao
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_M)]D. Agilao is normal
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_S)]D. Agilao is weak
[if(CBIT_HEAR_AGI_C)][if_not(BBIT_D_AGIRAO_C)]D. Agilao fuses
Never mind.
[end_choice][clear][end]

msg_445:
[tab]What about Jack Frost?
[choice(6)][if(CBIT_HEAR_BUF_L)][if_not(BBIT_A_BUFURA_L)]A. Bufula is strong
[if(CBIT_HEAR_BUF_M)][if_not(CBIT_HEAR_BUF_S)]Uses Atomic Bufula
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_M)]A. Bufula is normal
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_S)]A. Bufula is weak
[if(CBIT_HEAR_BUF_C)][if_not(BBIT_A_BUFURA_C)]A. Bufula fuses
Never mind.
[end_choice][clear][end]

msg_446:
[tab]What about Stymphalides?
[choice(6)][if(CBIT_HEAR_GAR_L)][if_not(BBIT_D_GARURA_L)]D. Garula is strong
[if(CBIT_HEAR_GAR_M)][if_not(CBIT_HEAR_GAR_S)]Uses Dangerous Garula
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_M)]D. Garula is normal
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_S)]D. Garula is weak
[if(CBIT_HEAR_GAR_C)][if_not(BBIT_D_GARURA_C)]D. Garula fuses
Never mind.
[end_choice][clear][end]

msg_447:
[tab]What about Barbatos?
[choice(6)][if(CBIT_HEAR_MAG_L)][if_not(BBIT_G_MAGNAS_L)]G. Magnara is strong
[if(CBIT_HEAR_MAG_M)][if_not(CBIT_HEAR_MAG_S)]Uses Great Magnara
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_M)]G. Magnara is normal
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_S)]G. Magnara is weak
[if(CBIT_HEAR_MAG_C)][if_not(BBIT_G_MAGNAS_C)]G. Magnara fuses
Never mind.
[end_choice][clear][end]

msg_448:
[tab]What about Ankou?
[choice(6)][if(CBIT_HEAR_JIO_L)][if_not(BBIT_H_JIONGA_L)]H. Zionga is strong
[if(CBIT_HEAR_JIO_M)][if_not(CBIT_HEAR_JIO_S)]Uses Hyper Zionga
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_M)]H. Zionga is normal
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_S)]H. Zionga is weak
[if(CBIT_HEAR_JIO_C)][if_not(BBIT_H_JIONGA_C)]H. Zionga fuses
Never mind.
[end_choice][clear][end]

msg_449:
[tab]What about Kanaloa?
[choice(6)][if(CBIT_HEAR_AQU_L)][if_not(BBIT_W_AQUES_L)]W. Aques is strong
[if(CBIT_HEAR_AQU_M)][if_not(CBIT_HEAR_AQU_S)]Uses Wondrous Aques
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_M)]W. Aques is normal
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_S)]W. Aques is weak
[if(CBIT_HEAR_AQU_C)][if_not(BBIT_W_AQUES_C)]W. Aques fuses
Never mind.
[end_choice][clear][end]

msg_450:
[tab]What about Demeter?
[choice(6)][if(CBIT_HEAR_FRA_L)][if_not(BBIT_U_FRAIRA_L)]U. Freila is strong
[if(CBIT_HEAR_FRA_M)][if_not(CBIT_HEAR_FRA_S)]Uses Ultra Freila
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_M)]U. Freila is normal
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_S)]U. Freila is weak
[if(CBIT_HEAR_FRA_C)][if_not(BBIT_U_FRAIRA_C)]U. Freila fuses
Never mind.
[end_choice][clear][end]

msg_451:
[tab]What about Succubus?
[choice(6)][if(CBIT_HEAR_MEG_L)][if_not(BBIT_C_MEGIDO_L)]S. Megido is strong
[if(CBIT_HEAR_MEG_M)][if_not(CBIT_HEAR_MEG_S)]Uses Super Megido
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_M)]S. Megido is normal
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_S)]S. Megido is weak
[if(CBIT_HEAR_MEG_C)][if_not(BBIT_C_MEGIDO_C)]S. Megido fuses
Never mind.
[end_choice][clear][end]

msg_452:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Really!?
[tab]That's news to me...
[tab]Anyway, I'll go tell everyone!
[wait][clear][end]

msg_453:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?  No rumors!?
[tab]Next time, you better have
[tab]a juicy one ready!
[wait][clear][end]

msg_454:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I already know...
[tab]Your [color(orange)]katana[color(white)] is a [color(orange)]cheap souvenir[color(white)]...
[tab]I'm gonna tell everyone else!
[wait][clear][end]

msg_455:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I already know...
[tab]Your [color(orange)]handgun[color(white)] is a [color(orange)]toy gun[color(white)]...
[tab]I'm gonna tell everyone else!
[wait][clear][end]

msg_456:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I already know...
[tab]Your [color(orange)]coin[color(white)] is a [color(orange)]fake[color(white)]...
[tab]I'm gonna tell everyone else!
[wait][clear][end]

msg_457:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I already know...
[tab]Your [color(orange)]glove[color(white)] is [color(orange)]for doing work[color(white)]...
[tab]I'm gonna tell everyone else!
[wait][clear][end]

msg_458:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I already know...
[tab]Your [color(orange)]rapier[color(white)] is [color(orange)]all rusted[color(white)]...
[tab]I'm gonna tell everyone else!
[wait][clear][end]

msg_459:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm... You know, I kinda understand you,
[tab]but at other times, I don't...
[tab]Well, anyways...
[wait][clear][end]

msg_460:
[tab]What do you think of me?
[choice(4)]Cool
Strong
Smart
Fool
[end_choice][clear][end]

msg_461:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm... You got a lot of guts to
[tab]call me a "fool" to my face...
[tab]But y'know...
[wait][clear][end]

msg_462:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't you think humans are also fools?
[tab]So I'll give you the [color(green)][item_with_type(fool_card)][color(white)] card.
[tab]A perfect match for foolish humans!
[wait][clear][end]