msg_0:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_1:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_2:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_3:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_4:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_5:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_6:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_7:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_8:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_9:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_10:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_11:
[color(yellow)][var(msg_var_0)][color(white)]
[wait][clear][end]

msg_12:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Are you curious about me, HO?
[tab]HOHOHOHOHO...
[wait][clear][end]

msg_13:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You say that but...
[tab]You really want to play with me, HO!?
[tab]HOHOHOHOHO...
[wait][clear][end]

msg_14:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You want to know more about me, HO?
[tab]I want to know more about you too, HO...
[wait][clear][end]

msg_15:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That was Frosty's error, HO!
[wait][clear][end]

msg_16:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You, you!
[tab]You're thinking I'm a kid, HO!
[tab]I won't forgive you, HO!!
[wait][clear][end]

msg_17:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What's the problem, HO?!
[tab]I'm gonna get mad, HO!!
[wait][clear][end]

msg_18:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't point that thing at me, HO! 
[tab]What are you gonna do if someone gets hurt, HO?!
[wait][clear][end]

msg_19:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I'm scared, HO...
[wait][clear][end]

msg_20:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah... wah... wah...
[tab]G-Grandpaaa!!
[wait][clear][end]

msg_21:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Th... then you're going to hit my head...
[tab]with that, HO?
[tab]H... Hyaaaa.....
[wait][clear][end]

msg_22:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!!
[tab]Is that, HO...
[wait][clear][end]

msg_23:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Fortune telling looks interesting, HO!
[tab]I want to try it too, HO...
[wait][clear][end]

msg_24:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Is it really right, HO...?
[tab]HOHOHOHOHO...
[wait][clear][end]

msg_25:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]It's weirrrd, HO!
[wait][clear][end]

msg_26:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Fortune telling
[tab]is dumb, HO!
[wait][clear][end]

msg_27:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]It's funny, HO!
[wait][clear][end]

msg_28:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You, you!
[tab]Don't just say anything, HO!!
[tab]I'm gonna get mad, HO!!
[wait][clear][end]

msg_29:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Fortune telling isn't real, HO!
[tab]Humans really are stupid, HO!!
[wait][clear][end]

msg_30:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]I don't know any girl like that, HO...
[tab]But I'm a little curious, HO...
[wait][clear][end]

msg_31:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You say that... but really
[tab]you want to become my friend, HO!?
[tab]HOHOHOHOHO...
[wait][clear][end]

msg_32:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]Did I do something wrong again, HO...?
[tab]Papa is going to praise me again, HO!
[wait][clear][end]

msg_33:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You, you!
[tab]I don't know that woman, HO!!
[tab]I'm gonna get mad, HO!!
[wait][clear][end]

msg_34:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]W-Why...
[tab]I'm gonna c-cry, HO!!
[wait][clear][end]

msg_35:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]A girl like that...
[tab]I don't know any, HO...
[wait][clear][end]

msg_36:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Why is my voice in that, HO...?
[tab]A strange box, HO...
[wait][clear][end]

msg_37:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Why do you have my voice, HO?!
[tab]You are a "spy", HO!
[wait][clear][end]

msg_38:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I...
[tab]haven't done anything wrong...
[tab](sniff sniff)
[wait][clear][end]

msg_39:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]You know a lot of
[tab]strange words, HO...
[wait][clear][end]

msg_40:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are very smart, HO!
[tab]I admire you, HO!!
[wait][clear][end]

msg_41:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Humans are funny, HO!
[tab]I like them, HO!
[wait][clear][end]

msg_42:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What's that, HO?!
[tab]That's not funny at all, HO!!
[wait][clear][end]

msg_43:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You, you!
[tab]Your words are too difficult,
[tab]I can't understand at all, HO!!
[wait][clear][end]

msg_44:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]It's so pretty, HO...
[tab]I want to wear that too, HO...
[wait][clear][end]

msg_45:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]That's funny, HO...
[wait][clear][end]

msg_46:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I can't stop watchin', HO...
[tab]What happened to me, HO?
[wait][clear][end]

msg_47:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Wow so pretty, HO!
[tab]I like human women very much, HO!
[wait][clear][end]

msg_48:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]I'm kind of getting nervous, HO!!
[tab]Wh,Why is that, HO...?
[wait][clear][end]

msg_49:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Why are you asking me, HO?
[tab]I'm curious, HO.
[wait][clear][end]

msg_50:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmmm, I like...
[tab]a person that is a good cook, HO!!
[wait][clear][end]

msg_51:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You're both pretty, but...
[tab]not as pretty as my mama, HO!!
[wait][clear][end]

msg_52:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah...
[tab]You asked me, HO!?
[tab]I'm so happy, HO!!
[wait][clear][end]

msg_53:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You, You!
[tab]Why are you asking me this, HO?!!
[tab]How would I know, HO?!!
[wait][clear][end]

msg_54:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]Do humans have many "worries", HO?
[tab]Grandma told me, HO...
[wait][clear][end]

msg_55:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Humans are very kind, HO!
[tab]I like them a lot, HO!
[wait][clear][end]

msg_56:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]I'm so happy, HO!
[wait][clear][end]

msg_57:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]"Interview" looks fun, HO...
[tab]I want to try, HO...
[wait][clear][end]

msg_58:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey hey, you you!
[tab]This time do interview to me!!
[wait][clear][end]

msg_59:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It is a strange dance, HO...
[tab]It is making me feel warm, HO...
[wait][clear][end]

msg_60:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-you, are cool!!
[tab]I can't stop watching, HO!!
[wait][clear][end]

msg_61:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are concerned for me, HO?
[tab]But, I am a demon...
[wait][clear][end]

msg_62:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]"Heroes of Justice" have it hard, HO...
[tab]I feel for you, HO...
[wait][clear][end]

msg_63:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You... kind of look happy, HO!
[wait][clear][end]

msg_64:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Are you "Heroes of Justice"?!
[tab]Wow, cool, HO!!
[tab]I want to shake your hand, HO!!
[wait][clear][end]

msg_65:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I want a brother too, HO...
[tab]I want to get into fights n' stuff, HO...
[wait][clear][end]

msg_66:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What is it like to have brothers, HO...?
[wait][clear][end]

msg_67:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]You-You, are cool!
[tab]I admire you, HO!
[wait][clear][end]

msg_68:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]My grandpa likes to drink too, HO!
[wait][clear][end]

msg_69:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Humans drink too, HO!
[tab]That's funny, HO!!
[wait][clear][end]

msg_70:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Why do you care so much, HO?
[tab]Grown-ups are weird, HO...
[wait][clear][end]

msg_71:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]It's OK to use your mouth to argue,
[tab]But you can't use it to bite, HO!!
[wait][clear][end]

msg_72:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]The long-haired one says weird things, HO!
[tab]Are you tired, HO?
[wait][clear][end]

msg_73:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]When I grow up, do I become like you, HO?
[wait][clear][end]

msg_74:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Humans have it hard, HO!
[tab]I'm glad I'm a demon, HO!
[wait][clear][end]

msg_75:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You two aren't very clear, HO!
[tab]You know you're curious about me...
[wait][clear][end]

msg_76:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It looks like human men are more powerful
[tab]than human women, HO! Why is that, HO?!
[wait][clear][end]

msg_77:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Are men bad guys, HO?
[tab]I don't understand very well, HO...
[wait][clear][end]

msg_78:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You... look strong, HO!
[wait][clear][end]

msg_79:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You two seem like good friends, HO...
[wait][clear][end]

msg_80:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You, with the red hair, you look cool...
[tab]When I grow up,
[tab]I want to be like you, HO...
[wait][clear][end]

msg_81:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I kind of feel nervous, HO...
[tab]My chest feels warm, HO...
[wait][clear][end]

msg_82:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Women seem to like to talk about men, HO!
[tab]But I don't really understand...
[wait][clear][end]

msg_83:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]You seem to be having fun, HO!
[tab]Fun is a good thing, HO!!
[wait][clear][end]

msg_84:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah, I can't drink yet, HO.
[tab]By the way, the person in the suit...
[tab]What happened, HO?!
[wait][clear][end]

msg_85:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]Humans get scared by
[tab]that kind of story, HO...
[wait][clear][end]

msg_86:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Happy ending, Happy ending!
[tab]...Isn't it, HO?!!
[wait][clear][end]

msg_87:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]H-Hyaaaaaa....
[tab]I wet my pants, HO...
[wait][clear][end]

msg_88:
[end]

msg_89:
[end]

msg_90:
[end]

msg_91:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Humans are funny
[tab]even when they are mad, HO!!
[wait][clear][end]

msg_92:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]If you keep making me angry,
[tab]I will have to squash you, HO!!
[wait][clear][end]

msg_93:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]If you keep talking like that,
[tab]I'll really have to put you under, HO!!
[wait][clear][end]

msg_94:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]D-Don't get so mad...
[tab]I-I'm sorry, HO...(sniff).
[wait][clear][end]

msg_95:
[end]

msg_96:
[end]

msg_97:
[end]

msg_98:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]The humans are sad, HO!
[tab]That's kind of cute, HO!
[wait][clear][end]

msg_99:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah...
[tab]That sounds kind of fake, HO!
[tab]That makes me mad, HO!
[wait][clear][end]

msg_100:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What are you doing, HO?
[tab]It's too late now, HO!
[wait][clear][end]

msg_101:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Th... then...
[tab]It makes me seem evil, HO...
[tab]I'm going to cry, HO!!
[wait][clear][end]

msg_102:
[end]

msg_103:
[end]

msg_104:
[end]

msg_105:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]They're talking to dead people, HO!!
[tab]Humans are funny, HO!!
[wait][clear][end]

msg_106:
[end]

msg_107:
[end]

msg_108:
[end]

msg_109:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Humans are kind of mean, HO!
[tab]I admire that, HO!
[wait][clear][end]

msg_110:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Wh... when humans die,
[tab]they get insulted, HO...
[tab]Th... that is cold, HO.
[wait][clear][end]

msg_111:
[end]

msg_112:
[end]

msg_113:
[end]

msg_114:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Humans are goofy, HO!
[tab]I like them a lot, HO.
[wait][clear][end]

msg_115:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Kind of scary, HO...
[tab]There is something wrong with that, HO...
[wait][clear][end]

msg_116:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]You've been going to the Beauty Spa, HO!
[tab]How nice, HO!
[wait][clear][end]

msg_117:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]You went to the Beauty Spa, HO!
[tab]You're face is very nice, HO!
[wait][clear][end]

msg_118:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Very pretty, HO!!
[tab]You must've been to the Beauty Spa, HO?!
[wait][clear][end]

msg_119:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]You're a man, and you went to a Beauty Spa?
[tab]That is very, very sick, HO!!
[wait][clear][end]

msg_120:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]What's up with that complexion, HO?!
[tab]Men don't go to Beauty Spas, HO!!
[wait][clear][end]

msg_121:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]You're a man, and you went to a Beauty Spa?
[tab]Men don't do that, HO!!
[wait][clear][end]

msg_122:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]If that's the case, leave it to me, HO!
[wait][clear][end]

msg_123:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmmm... what should I do, HO? 
[tab]I want to help, but I'm not in the mood, HO...
[tab]Hmmm, in that case, in that case...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Pop Quiz!! Pop Quiz!!
[tab]If you answer all my questions correctly,
[tab]I'll help you, HO!
[wait][clear][end]

msg_124:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]So here we go, HO!!
[wait][clear][end]

msg_125:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Eyes, ears, nose, mouth...
[tab]Which one of these looks at Honey Bees, HO?
[wait][clear][end]

msg_126:
[tab]Which one of these looks at Honey Bees, HO?
[choice(4)]Eyes
Ears
Mouth
Nose
[end_choice][clear][end]

msg_127:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's correct, HO!
[tab]Was it too easy, HO?
[wait][clear][end]

msg_128:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]You look at honey bees with those, HO?
[wait][clear][end]

msg_129:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]You look at Honey Bees with your nose, HO?
[tab]I think looking is done with the eyes, HO!
[wait][clear][end]

msg_130:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Neck, wrist, ankle...
[tab]Which one can't you grab by yourself, HO?
[wait][clear][end]

msg_131:
[tab]Which one CAN'T you grab by yourself, HO?
[choice(4)]Neck
Wrist
Ankle
You can grab all
[end_choice][clear][end]

msg_132:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]That is easy to grab, HO!
[tab]You are kind of clumsy, HO!
[wait][clear][end]

msg_133:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]It's easy to grab with the opposite hand, HO!
[wait][clear][end]

msg_134:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huhhuhhuh...
[tab]The next one will be hard, HO!
[wait][clear][end]

msg_135:
[tab]What insect is in the middle of a lobby?
[choice(4)]Cicada
Bee
Fly
Ant
[end_choice][clear][end]

msg_136:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, HO!
[tab]That isn't right at all HO!
[wait][clear][end]

msg_137:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Right answer, HO!
[tab]A bee is in the middle of L-O-B-B-Y, HO!
[wait][clear][end]

msg_138:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, HO!
[tab]That is not a insect HO!
[wait][clear][end]

msg_139:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]The sun, moon, stars...
[tab]Which one is the largest, HO?
[wait][clear][end]

msg_140:
[tab]Which is the largest, HO?
[choice(3)]Sun
Moon
Star
[end_choice][clear][end]

msg_141:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]There are stars that are bigger
[tab]than the sun, HO!
[wait][clear][end]

msg_142:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]You shouldn't answer without
[tab]thinking first, HO!
[wait][clear][end]

msg_143:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Right answer, HO!
[tab]There is a "super" star which
[tab]is even larger than the sun, HO!
[wait][clear][end]

msg_144:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Snoring, turning over in bed, yawning, laughing... 
[tab]which one do you usually not do while sleeping, HO?
[wait][clear][end]

msg_145:
[tab]Which do you NOT do while sleeping, HO?
[choice(4)]Snore
Turn over
Yawn
Laugh
[end_choice][clear][end]

msg_146:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]That is done while sleeping, HO!
[wait][clear][end]

msg_147:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Right answer HO!
[tab]Yawning is usually done while awake, HO!
[wait][clear][end]

msg_148:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]Some people have funny dreams
[tab]and laugh out loud in their sleep, HO!
[wait][clear][end]

msg_149:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are pretty good, HO!
[tab]I am very impressed, HO!
[tab]I'll help put out the fire, HO!
[wait][clear][end]

msg_150:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I can't do that, HO!
[tab]I don't want to help because there are men, HO! 
[tab]I don't like men, HO!
[wait][clear][end]

msg_151:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You are all women, HO!
[tab]Then I must help, HO!
[wait][clear][end]

msg_152:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmm...
[tab]It would be better if there were more women, HO... 
[tab]Bring more, HO!
[wait][clear][end]

msg_153:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh?!
[tab]Why do I have to do something
[tab]like that, HO?!
[wait][clear][end]

msg_154:
[tab]What are you to me, HO?!
[choice(4)]Friends
Siblings
Master
Don't know
[end_choice][clear][end]

msg_155:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What are you talking about, HO?!
[tab]That is very rude, HO!
[tab]I don't feel like helping any more, HO!
[wait][clear][end]

msg_156:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You don't know, HO...!?
[tab]You are very lazy, HO...!
[tab]Just like me, HO!
[wait][clear][end]

msg_157:
[tab]By the way, do you like to build "snowmen"?
[choice(3)]I like to build snowmen.
I hate building snowmen.
I like snowball fights better.
[end_choice][clear][end]

msg_158:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You like annoying things like that, HO?
[tab]I can't believe it, HO!
[tab]I just can't believe it!!
[wait][clear][end]

msg_159:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Just as I thought, HO!
[tab]You and I are both lazy, 
[tab]so we both hate building snowmen, HO!
[wait][clear][end]

msg_160:
[tab]...So what do you want me to do for you?
[choice(3)]I want you to put out the fire.
I want to become friends.
I forgot.
[end_choice][clear][end]

msg_161:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahh, how annoying, HO...
[tab]I can't do annoying things like that, HO.
[tab]I'm going home to sleep, HO...
[wait][clear][end]

msg_162:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHYA!
[tab]You are SO lazy, HO!
[tab]We have so much in common, HO!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]I remember what it was, HO!!
[tab]You wanted me to put the fire out, HO.
[tab]It's a bother, but I'll give it a try, HO!
[wait][clear][end]

msg_163:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's right, HO!
[tab]This time, I do an interview on you, HO!
[wait][clear][end]

msg_164:
[tab]Do you know [var(msg_var_0)], HO?
[choice(2)]I know. That really cute demon!
I don't know. Must be a silly demon!
[end_choice][clear][end]

msg_165:
[tab]What do humans worry about, HO?
[choice(4)]About love.
About money.
About schoolwork.
Hmm... Stuff
[end_choice][clear][end]

msg_166:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]What "stuff", HO...?
[tab]I'm curious, HO...
[wait][clear][end]

msg_167:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]What "stuff", HO?!
[tab]Tell me what it means, HO!!
[wait][clear][end]

msg_168:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, between you with the long hair,
[tab]and you with the short hair...
[tab]Which one of you is the better cook, HO?
[wait][clear][end]

msg_169:
[tab]Which one is the better cook, HO!
[choice(3)]The one with the short hair!
You got it! The long haired one!
No match against your Mom!
[end_choice][clear][end]

msg_170:
[tab]What is this warm feeling... HO!
[choice(3)]Must be a sign of love!
It's heartburn. Don't drink so much!
You wanna fight? Just bring it!
[end_choice][clear][end]

msg_171:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's right, HO!!
[tab]Here is [var(msg_var_0)]'s interview!!
[wait][clear][end]

msg_172:
[tab]What did you come here for, HO?
[choice(3)]To kill-off demons
To go shopping
To find a rainbow colored flower...
[end_choice][clear][end]

msg_173:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh yeah!
[tab]The other day,
[tab]I did something very bad, HO!
[wait][clear][end]

msg_174:
[tab]What do you think I did, HO...?
[choice(3)]Did you run a red light?
You ate a demon instead of a human?
Peeked in your parents bedroom...?
[end_choice][clear][end]

msg_175:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Boo boo, wrong answer, HO!
[tab]But... is that a bad thing, HO?
[tab]I'm curious, HO...
[wait][clear][end]

msg_176:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ding Dong, HO!
[tab]HOHYAHAHAHA!
[tab]See, I'm a bad boy, HO!
[wait][clear][end]

msg_177:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ehh... I can't peak in, HO?
[tab]C-Could it be...
[tab]Papa is hurting mama, HO...?!
[wait][clear][end]

msg_178:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey you guys!
[tab]Why don't you quit being "Heroes" and
[tab]become demons like us, HO?!
[wait][clear][end]

msg_179:
[tab]Hey become a demon right now, HO!
[choice(3)]Sure, why not?
I will pass.
You're a demon?
[end_choice][clear][end]

msg_180:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHYAHAHAHA!
[tab]Just joking, HO!
[tab]Did I surprise you, HO?
[wait][clear][end]

msg_181:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I see...
[tab]It can't be helped.
[tab]That is too bad, HO...
[wait][clear][end]

msg_182:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey...
[tab]There really isn't any reason I should
[tab]be asking you this but...
[wait][clear][end]

msg_183:
[tab]Why was I born a demon, HO?
[choice(3)]God made you that way!
Your Mom and Dad are demons so...
I'm sorry I don't know...
[end_choice][clear][end]

msg_184:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]I see, that's right, HO!
[tab]You are smart, HO!
[wait][clear][end]

msg_185:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah... hearing you say that really makes
[tab]me want a big brother!
[tab]Hey hey, you you!!
[wait][clear][end]

msg_186:
[tab]If I ask mama, will she make me one, HO?
[choice(3)]She'll definitely make you one!
Perhaps a younger brother...
I'll be your older brother!
[end_choice][clear][end]

msg_187:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's it, HO!
[tab]Here we go, HO!! 100% accurate...
[tab][var(msg_var_0)]'s Fortune Telling!!
[wait][clear][end]

msg_188:
[tab]By the way..... How do you tell fortunes?
[choice(3)]By using crystal balls and stuff.
It's a corporate secret... NOT!
Weren't you just watching me before!?
[end_choice][clear][end]

msg_189:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah, you are pretty clever, HO!
[tab]HOHOHOHOHO...
[wait][clear][end]

msg_190:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey-Hey...
[tab]When I grow up, will I
[tab]understand what you are saying, HO?
[wait][clear][end]

msg_191:
[tab]Will I understand when I grow up, HO?
[choice(3)]Sure you will!
Nope, not if you're a guy!
Really, you're able to grow up?
[end_choice][clear][end]

msg_192:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey... why do I feel warm, HO?
[tab]Do you know, HO?
[wait][clear][end]

msg_193:
[tab]Hey... Why do I feel warm, HO?
[choice(3)]You're feeling the hot winds of Barcelona!
Because you were watching the dance?
Maybe you're running a fever?
[end_choice][clear][end]

msg_194:
[tab]Hey... What's it like inside that box, HO?
[choice(3)]It's full of machines!
[var(msg_var_0)] is inside!
Don't change the subject!
[end_choice][clear][end]

msg_195:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah, I got a good idea, HO!
[tab]I'll make liquor for grandpa and give it
[tab]to him as a present, HO!
[wait][clear][end]

msg_196:
[tab]...Hey, How do you make liquor, HO?
[choice(3)]You ferment grains and fruits.
It's faster to go out and buy it!
I'll teach you, so gimme a card!
[end_choice][clear][end]

msg_197:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey hey, You!
[tab]Are you tired, HO?
[wait][clear][end]

msg_198:
[tab]Hey hey, are you tired, HO...?!
[choice(3)]As you age, you get tired easily...
Heh heh, kids don't understand...
Well, my car has a flat...
[end_choice][clear][end]

msg_199:
[tab]Hey... you, why are you crying, HO?
[choice(3)](sob)... Because of stuff...
(weep)... It's just allergies... achooo!
(moan)... y-you wouldn't understand...
[end_choice][clear][end]

msg_200:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]So...
[tab]Why were you two fighting, HO?
[wait][clear][end]

msg_201:
[tab]...What were you fighting about, HO?
[choice(3)]We were just debating about baseball.
We were just discussing how to live.
You don't understand, your a kid...
[end_choice][clear][end]

msg_202:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey hey!
[tab]When I become your age, will I be
[tab]able to use those fancy words too, HO?
[wait][clear][end]

msg_203:
[tab]I want to hurry and use fancy words, HO!
[choice(3)]Crack a book once in a while...
Talk to your own kind.
You speak fancy already!
[end_choice][clear][end]

msg_204:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Huh...?
[tab]How do you... know my name, HO?
[wait][clear][end]

msg_205:
[tab]Where did you hear my name, HO...?
[choice(3)]Who DOESN'T know your name...?
Just stuff that I know. Don't ask.
I had a friend who was into demons...
[end_choice][clear][end]

msg_206:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Papa always tells me that I can't be
[tab]friends with humans, HO...
[tab]But it is okay to make one a pet, HO!
[wait][clear][end]

msg_207:
[tab]Will you be my "pet" then...?
[choice(3)]Don't be ridiculous!!
Sure! Do whatever you want to me.
No, I think YOU should be MY pet!!
[end_choice][clear][end]

msg_208:
[tab]You must be curious about me, HO!!
[choice(3)]Yes. I can't sleep because of you.
Yes. I think I'll make you my slave.
Enough of your arrogance!!
[end_choice][clear][end]

msg_209:
[tab]Hey, I want to wear those clothes too...
[choice(3)]Okay, it might suit you well...
Oh these clothes aren't for boys...
They'll get dirty if you wear them!!
[end_choice][clear][end]

msg_210:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey hey!
[tab]Why are human boys stronger than
[tab]human girls, HO?!
[wait][clear][end]

msg_211:
[tab]What makes boys stronger, HO?
[choice(3)]Socially, they are better off.
It's because they got bigger muscles.
They act tough, but they are not.
[end_choice][clear][end]

msg_212:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Humans are much bigger cowards
[tab]than I thought, HO...
[tab]HOHOHO!
[wait][clear][end]

msg_213:
[tab]Why are you such cowards, HO?
[choice(3)]Perhaps, since we haven't died yet...
The demons are too powerful!
We will show you how scared we are!
[end_choice][clear][end]

msg_214:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]You want to compare strength with me, HO?
[tab]For being a human, you have guts, HO...
[wait][clear][end]

msg_215:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HO!!
[tab]Does that mean human women are...!!
[wait][clear][end]

msg_216:
[tab]"Heroes of Justice", HO?!
[choice(2)]That's right. It's "Hero Time"!
Are you really THAT stupid?!
[end_choice][clear][end]

msg_217:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]My chest is feeling weird,...
[tab]and my heart is pounding fast, HO!!
[wait][clear][end]

msg_218:
[tab]Why is this happening, HO?
[choice(3)]Love at first sight, you're kidding...
Stop, I'm not like that... I think?
Do you have a time bomb in your chest?
[end_choice][clear][end]

msg_219:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Alright!!
[tab]I will challenge you, HO!!
[tab]...What sort of challenge should it be?
[wait][clear][end]

msg_220:
[tab]You pick the challenge, HO!
[choice(3)]If you're a real man, it's strength!
If you're a real man, it's looks!
Rock-Scissor-Paper...
[end_choice][clear][end]

msg_221:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey-Hey,
[tab]what did you use to call your
[tab]little brother, HO!?
[wait][clear][end]

msg_222:
[tab]What did you call him, HO...?!
[choice(3)]It's always been by his name.
Used to call him by his nickname...
Think I called him "little bro"...
[end_choice][clear][end]

msg_223:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]...mmm?
[tab]Are you a kid, HO...?
[tab]Are you an adult or a kid?
[wait][clear][end]

msg_224:
[tab]...Adult? Kid? Which are you, HO?!
[choice(3)]I'm more grown-up than you, kid.
I'm a kid... just like you.
Actually, I'm younger than you are.
[end_choice][clear][end]

msg_225:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!
[tab]Don't compare demons to humans, HO!
[tab]That's very rude, HO...!
[wait][clear][end]

msg_226:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Yesterday, a human kid was washing her hair
[tab]and I tapped her on the shoulder, HO...
[tab]She was surprised and started to cry, HO.
[wait][clear][end]

msg_227:
[tab]Hey, why did she cry, HO?
[choice(3)]It's because you're a demon.
It's because you suddenly tapped her.
Because she hates to wash her hair.
[end_choice][clear][end]

msg_228:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, I've been curious for some time now...
[tab]Humans sometimes put a banana-thing to
[tab]their ears and talk to themselves, HO.
[wait][clear][end]

msg_229:
[tab]What are they doing, HO?
[choice(3)]Talking to people far away.
They're mumbling to themselves.
They're summoning Master Joker.
[end_choice][clear][end]

msg_230:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh, yeah...
[tab]I had a question for you humans, HO!
[wait][clear][end]

msg_231:
[tab]Hey... is an "alien" a human, HO?
[choice(3)]According to rumor.
They're closer to demons actually.
There's no such thing as "aliens".
[end_choice][clear][end]

msg_232:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oh, yeah...
[tab]I found a skeleton in a human school, HO!
[tab]He was probably burned to death, HO!
[wait][clear][end]

msg_233:
[tab]...Did he do something bad, HO???
[choice(3)]He made a demon pact.
He didn't eat his vegetables.
It's a fake.
[end_choice][clear][end]

msg_234:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I am really mad now, HO!!
[tab]I really am, HO! I really am mad, HO!!!
[tab]There is something I want to ask you, HO.
[wait][clear][end]

msg_235:
[tab]What do you gain when you get mad, HO?
[choice(4)]You gain wrinkles
You gain weight
You gain attention
You gain nothing
[end_choice][clear][end]

msg_236:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]They say, that "God" created humans but
[tab]I think that's just a fairy tale, HO...
[tab]Cause humans are so stupid, HO!
[wait][clear][end]

msg_237:
[tab]...Did God really make them, HO?!
[choice(3)]God created man and demon.
Man created god and demon.
God made demons who made man.
[end_choice][clear][end]

msg_238:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That means we are distant relatives, HO!
[tab]I'm kind of happy, HO!
[wait][clear][end]

msg_239:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Papa said humans have real nerve,
[tab]and it is SO true, HO!!
[wait][clear][end]

msg_240:
[tab]So what are your nerves like, HO?
[choice(4)]Just like demons.
Like thick cords.
They're invisible.
Not your business!
[end_choice][clear][end]

msg_241:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah!
[tab]I have to go home now...
[tab]We can meet again okay, HO?
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]But, don't tell papa, HO!
[tab]If I'm nice to humans,
[tab]he will get mad at me, HO...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]So, this will be our little secret, HO!
[tab][color(green)][var(msg_var_5)][color(white)] [color(green)][var(msg_var_4)][color(white)] card(s)!
[tab]I'll give you these cause you're my friend!
[wait][clear][end]

msg_242:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]And also [color(green)][var(msg_var_6)][color(white)] [color(green)]Free Tarot[color(white)]!
[tab]I'm so generous HO!
[wait][clear][end]

msg_243:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]Looks like you can't hold any more, HO!
[tab]You've collected a lot of cards, HO...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]That's too bad, I gotta go bye-bye, HO!
[tab]Come over to play some time, HO!
[wait][clear][end]

msg_244:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO!
[tab]Looks like you can't hold any more, HO!
[tab]You've collected a lot of cards, HO...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]This is just a "preview"...
[tab]You like to talk a lot, HO.
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]I can't give you the cards, but
[tab]come over to play again soon, HO!
[wait][clear][end]

msg_245:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]See you again, HO! I promise, HO!
[wait][clear][end]

msg_246:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That was so much fun, HO!
[tab]I haven't laughed that hard in a while, HO!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey hey, You-You...
[tab]Sign a [color(green)]Pact[color(white)] with me, HO!?
[tab]Do it, do it, HO!!
[wait][clear][end]

msg_247:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]...But, your [color(green)]level is too low for
[tab]a Pact to be made[color(white)], HO!
[tab]Oh well, so instead...
[wait][clear][end]

msg_248:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Come see me when you get stronger, HO!
[tab]I'll be waiting for you, HO!
[wait][clear][end]

msg_249:
[tab]Who wants to make a [color(green)]Pact[color(white)], HO?
[choice(2)]I do! I do!
Not me.
[end_choice][clear][end]

msg_250:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Alriiiiight!!
[tab]From now on we're best friends, HO!
[tab]Just talk to me next time we meet, HO!
[wait][clear][end]

msg_251:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Oops!
[tab]That is too bad, HO...
[tab]But let's play next time, HO!
[wait][clear][end]

msg_252:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HOHO?
[tab]You already made three pacts, HO?
[tab]You'll have to [color(green)]break[color(white)] one, HO!
[wait][clear][end]

msg_253:
[tab]Whose do you want to [color(green)]break[color(white)], HO?
[choice(4)][pact_demon(0)]
[pact_demon(1)]
[pact_demon(2)]
Forget it...
[end_choice][clear][end]

msg_254:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahh!!
[tab]I never should've made a [color(green)]Pact[color(white)], HO!
[tab]I [color(green)]hate[color(white)] you, HO!!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]The hell with you, HO!
[tab]I hate humans, HO!!
[tab]I won't play with you any more, HO!!
[tab][wait][clear][end]

msg_255:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'm scared, HO...
[tab]I...[color(green)]cancel this pact[color(white)], HO...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]D-Don't get mad, HO...
[tab]If you get mad, I will cry, HO...
[tab]S... see you later HO...
[wait][clear][end]

msg_256:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I'm scared, HO!!
[wait][clear][end]

msg_257:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You!!
[tab]I won't forgive you, HO!!
[wait][clear][end]

msg_258:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HEH, HEHHEH, HEHHEHHEH!!
[tab]I-I think I'm starting to like humans a lot, HO!
[wait][clear][end]

msg_259:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ahh, that was fun, HO!!
[tab]I must repay you with something, HO!
[tab]So...
[wait][clear][end]

msg_260:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I give you [color(green)][var(msg_var_1)][color(white)], HO!
[tab]It's my treasure, HO!
[wait][clear][end]

msg_261:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's today's lunch money...
[tab]I'll give you [color(green)]¥[var(msg_var_2)][color(white)], HO!
[tab]Be my guest, take it, HO!
[wait][clear][end]

msg_262:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I'll [color(green)]recover[color(white)] you, HO!
[tab]There there, it's all better, HO!!
[wait][clear][end]

msg_263:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Well now, bye-bye, HO!
[wait][clear][end]

msg_264:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You know what? Somewhere in the back roads,
[tab]there's a mysterious "Shrine of Warriors"!
[tab]What's a "warrior", HO ?
[wait][clear][end]

msg_265:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know Kiyohime onee-chan, HO?
[tab]She's supposed to be a real neat freak!
[tab]You think she'll clean THOSE floors too, HO?
[wait][clear][end]

msg_266:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You know what, there's a rumor going around
[tab]that the "B2 Route" has lots of treasure!
[tab]I want some treasure too, HO...
[wait][clear][end]

msg_267:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You know what, there's a rumor going around
[tab]that the "B3 Route" has lots of treasure!
[tab]I want some treasure too, HO...
[wait][clear][end]

msg_268:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]The other day a man named "Rasputin"
[tab]picked up the "Fuse Box Key", HO!
[tab]I wonder what he's gonna use it for, HO?
[wait][clear][end]

msg_269:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, I noticed the other day
[tab]that left and right are backwards
[tab]in a mirror, HO! Did you know that, HO?
[wait][clear][end]

msg_270:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, there's a "Treasure Room" at the
[tab]bottom of this place, but there's no entrance... 
[tab]I wonder how you get in, HO?
[wait][clear][end]

msg_271:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You wanna get in the "Treasure Room" right?
[tab]Then you should ask Leviathon, HO.
[tab]That monster can break down walls, HO.
[wait][clear][end]

msg_272:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]The other day, a demon called "Seker"
[tab]was using a spell called "Mamagnara"!
[tab]It was really powerful, HO!
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]With that power, I think the "Unclosed
[tab]Bridge" might close, HO!
[wait][clear][end]

msg_273:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]You-You! My friend "Jack Frost" can put out
[tab]certain types of fires. HO!
[wait][clear][end]

msg_274:
[end]

msg_275:
[end]

msg_276:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Katana[color(white)]
[tab]has [color(orange)]hidden powers[color(white)], HO.
[wait][clear][end]

msg_277:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Katana[color(white)]
[tab]might be the [color(orange)]strongest[color(white)], HO.
[wait][clear][end]

msg_278:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor the [color(orange)]Legendary Handgun[color(white)]
[tab]has [color(orange)]hidden powers[color(white)], HO.
[wait][clear][end]

msg_279:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor the [color(orange)]Legendary Handgun[color(white)]
[tab]might be the [color(orange)]strongest[color(white)], HO.
[wait][clear][end]

msg_280:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Coin[color(white)]
[tab]has [color(orange)]hidden powers[color(white)], HO.
[wait][clear][end]

msg_281:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Coin[color(white)]
[tab]might be the [color(orange)]strongest[color(white)], HO.
[wait][clear][end]

msg_282:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Glove[color(white)]
[tab]has [color(orange)]hidden powers[color(white)], HO.
[wait][clear][end]

msg_283:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Glove[color(white)]
[tab]might be the [color(orange)]strongest[color(white)], HO.
[wait][clear][end]

msg_284:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Rapier[color(white)]
[tab]has [color(orange)]hidden powers[color(white)], HO.
[wait][clear][end]

msg_285:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Don't tell anyone, but, HO...
[tab]There's a rumor that the [color(orange)]Legendary Rapier[color(white)]
[tab]might be the [color(orange)]strongest[color(white)], HO.
[wait][clear][end]

msg_286:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's supposed to be [color(orange)]very powerful[color(white)], HO!
[wait][clear][end]

msg_287:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]But I heard that in reality...
[tab]it's very [color(orange)]weak[color(white)], HO!
[tab]Heeheehee!
[wait][clear][end]

msg_288:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]It's not really that strong, but,
[tab]It [color(orange)]fuses with another secret spell[color(white)]!
[tab]Fusing is very cool, HO!
[wait][clear][end]

msg_289:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Pyro Jack",
[tab]HO? He secretly has the spell called
[tab][color(orange)]Dynamic Agilao[color(white)], HO!
[wait][clear][end]

msg_290:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Jack Frost", HO?
[tab]He secretly has the spell called
[tab][color(orange)]Atomic Bufula[color(white)], HO!
[wait][clear][end]

msg_291:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Stymphalides", HO?
[tab]He secretly has the spell called
[tab][color(orange)]Dangerous Garula[color(white)], HO!
[wait][clear][end]

msg_292:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Barbatos", HO?
[tab]He secretly has the spell called
[tab][color(orange)]Great Magnara[color(white)], HO!
[wait][clear][end]

msg_293:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Ankou", HO?
[tab]He secretly has the spell called
[tab][color(orange)]Hyper Zionga[color(white)], HO!
[wait][clear][end]

msg_294:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Kanaloa", HO?
[tab]He secretly has the spell called
[tab][color(orange)]Wondrous Aques[color(white)], HO!
[wait][clear][end]

msg_295:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Demeter", HO?
[tab]She secretly has the spell called
[tab][color(orange)]Ultra Freila[color(white)], HO!
[wait][clear][end]

msg_296:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Do you know the demon "Succubus", HO?
[tab]She secretly has the spell called
[tab][color(orange)]Super Megido[color(white)], HO!
[wait][clear][end]

msg_297:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hmm... ah! If I talk too much,
[tab]I'll get in trouble, HO.
[tab]So, instead...
[wait][clear][end]

msg_298:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Hey, you have a "Pact" with me, HO!
[tab]I'll help you like I promised, HO!
[wait][clear][end]

msg_299:
[tab]What should I do, HO?
[choice(4)]Give me an item.
Give me money.
Give me info.
[if(CBIT_HEAR_RUMOR)]Spread a rumor.
[end_choice][clear][end]

msg_300:
[tab]What should I do, HO?
[choice(5)]Give me an item.
Give me money.
Give me info.
[if(CBIT_HEAR_RUMOR)]Spread a rumor.
[if(CBIT_HEAR_HIKESI)][if(DBIT_NPC_JACK4)]Put out the fire.
[end_choice][clear][end]

msg_301:
[tab]What kind of rumor should I spread, HO?
[choice(3)][if(CBIT_HEAR_WEPON)]Rumor about the Legendary Weapons.
[if(CBIT_HEAR_MAGIC)]Rumor about a spell.
Nothing in particular.
[end_choice][clear][end]

msg_302:
[tab]What kind of rumor should I spread, HO?
[choice(4)][if(CBIT_HEAR_WEPON)]Legendary Weapons
[if(CBIT_HEAR_MAGIC)]Rumor about a spell
[if(CBIT_HEAR_MAP1)]About this dungeon
Nothing special.
[end_choice][clear][end]

msg_303:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Everyone knows that rumor, HO!
[tab]I'd rather spread another one, HO...
[wait][clear][color(yellow)][var(msg_var_0)][color(white)]
[tab]Are there any other rumors, HO?
[wait][clear][end]

msg_304:
[tab]Which weapon, HO?
[choice(6)][if(CBIT_HEAR_SWD)]Legendary Katana
[if(CBIT_HEAR_GUN)]Legendary Handgun
[if(CBIT_HEAR_GTR)]Legendary Coin
[if(CBIT_HEAR_FST)]Legendary Glove
[if(CBIT_HEAR_FLW)]Legendary Rapier
Never mind.
[end_choice][clear][end]

msg_305:
[tab]About whose spell, HO?
[choice(6)][if(CBIT_HEAR_AGI)]Pyro Jack
[if(CBIT_HEAR_BUF)]Jack Frost
[if(CBIT_HEAR_GAR)]Stymphalides
[if(CBIT_HEAR_MAG)]Barbatos
[if(CBIT_RESERVE_Ff)]Some other demon.
Never mind.
[end_choice][clear][end]

msg_306:
[tab]About whose spell, HO?
[choice(6)][if(CBIT_HEAR_JIO)]Ankou
[if(CBIT_HEAR_AQU)]Kanaloa
[if(CBIT_HEAR_FRA)]Demeter
[if(CBIT_HEAR_MEG)]Succubus
[if(CBIT_RESERVE_Fe)]Some other demon.
Never mind.
[end_choice][clear][end]

msg_307:
[tab]What kind of rumor, HO?
[choice(3)][if(CBIT_HEAR_MAP1)]The fuse box in the Control Room...
[if(CBIT_HEAR_MAP2)]The locked door in the Control Room...
On second thought, never mind.
[end_choice][clear][end]

msg_308:
[tab]What about that "katana", HO?
[choice(4)][if(CBIT_HEAR_SWD_G)][if_not(IBIT_SWD_LGND_G)]It's powerful?
[if(CBIT_HEAR_SWD_L)][if_not(IBIT_SWD_LGND_S)]It has dark power.
[if_not(IBIT_SWD_LGND_N)]It's ordinary.
[if_not(IBIT_SWD_LGND_B)]Never mind.
[end_choice][clear][end]

msg_309:
[tab]What about that "handgun", HO?
[choice(4)][if(CBIT_HEAR_GUN_G)][if_not(IBIT_GUN_LGND_G)]It's powerful?
[if(CBIT_HEAR_GUN_L)][if_not(IBIT_GUN_LGND_S)]It has dark power.
[if_not(IBIT_GUN_LGND_N)]It's ordinary.
[if_not(IBIT_GUN_LGND_B)]Never mind.
[end_choice][clear][end]

msg_310:
[tab]What about that "coin", HO?
[choice(4)][if(CBIT_HEAR_GTR_G)][if_not(IBIT_CON_LGND_G)]It's powerful?
[if(CBIT_HEAR_GTR_L)][if_not(IBIT_CON_LGND_S)]It has dark power.
[if_not(IBIT_CON_LGND_N)]It's ordinary.
[if_not(IBIT_CON_LGND_B)]Never mind.
[end_choice][clear][end]

msg_311:
[tab]What about that "glove", HO?
[choice(4)][if(CBIT_HEAR_FST_G)][if_not(IBIT_FST_LGND_G)]It's powerful?
[if(CBIT_HEAR_FST_L)][if_not(IBIT_FST_LGND_S)]It has dark power.
[if_not(IBIT_FST_LGND_N)]It's ordinary.
[if_not(IBIT_FST_LGND_B)]Never mind.
[end_choice][clear][end]

msg_312:
[tab]What about that "rapier", HO?
[choice(4)][if(CBIT_HEAR_FLW_G)][if_not(IBIT_NSW_LGND_G)]It's powerful?
[if(CBIT_HEAR_FLW_L)][if_not(IBIT_NSW_LGND_S)]It has dark power.
[if_not(IBIT_NSW_LGND_N)]It's ordinary.
[if_not(IBIT_NSW_LGND_B)]Never mind.
[end_choice][clear][end]

msg_313:
[tab]What about Pyro Jack, HO?
[choice(6)][if(CBIT_HEAR_AGI_L)][if_not(BBIT_D_AGIRAO_L)]D. Agilao is strong
[if(CBIT_HEAR_AGI_M)][if_not(CBIT_HEAR_AGI_S)]Uses Dynamic Agilao
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_M)]D. Agilao is normal
[if(CBIT_HEAR_AGI_S)][if_not(BBIT_D_AGIRAO_S)]D. Agilao is weak
[if(CBIT_HEAR_AGI_C)][if_not(BBIT_D_AGIRAO_C)]D. Agilao fuses
Never mind.
[end_choice][clear][end]

msg_314:
[tab]What about Jack Frost, HO?
[choice(6)][if(CBIT_HEAR_BUF_L)][if_not(BBIT_A_BUFURA_L)]A. Bufula is strong
[if(CBIT_HEAR_BUF_M)][if_not(CBIT_HEAR_BUF_S)]Uses Atomic Bufula
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_M)]A. Bufula is normal
[if(CBIT_HEAR_BUF_S)][if_not(BBIT_A_BUFURA_S)]A. Bufula is weak
[if(CBIT_HEAR_BUF_C)][if_not(BBIT_A_BUFURA_C)]A. Bufula fuses
Never mind.
[end_choice][clear][end]

msg_315:
[tab]What about Stymphalides, HO?
[choice(6)][if(CBIT_HEAR_GAR_L)][if_not(BBIT_D_GARURA_L)]D. Garula is strong
[if(CBIT_HEAR_GAR_M)][if_not(CBIT_HEAR_GAR_S)]Uses Dangerous Garula
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_M)]D. Garula is normal
[if(CBIT_HEAR_GAR_S)][if_not(BBIT_D_GARURA_S)]D. Garula is weak
[if(CBIT_HEAR_GAR_C)][if_not(BBIT_D_GARURA_C)]D. Garula fuses
Never mind.
[end_choice][clear][end]

msg_316:
[tab]What about Barbatos, HO?
[choice(6)][if(CBIT_HEAR_MAG_L)][if_not(BBIT_G_MAGNAS_L)]G. Magnara is strong
[if(CBIT_HEAR_MAG_M)][if_not(CBIT_HEAR_MAG_S)]Uses Great Magnara
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_M)]G. Magnara is normal
[if(CBIT_HEAR_MAG_S)][if_not(BBIT_G_MAGNAS_S)]G. Magnara is weak
[if(CBIT_HEAR_MAG_C)][if_not(BBIT_G_MAGNAS_C)]G. Magnara fuses
Never mind.
[end_choice][clear][end]

msg_317:
[tab]What about Ankou, HO?
[choice(6)][if(CBIT_HEAR_JIO_L)][if_not(BBIT_H_JIONGA_L)]H. Zionga is strong
[if(CBIT_HEAR_JIO_M)][if_not(CBIT_HEAR_JIO_S)]Uses Hyper Zionga
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_M)]H. Zionga is normal
[if(CBIT_HEAR_JIO_S)][if_not(BBIT_H_JIONGA_S)]H. Zionga is weak
[if(CBIT_HEAR_JIO_C)][if_not(BBIT_H_JIONGA_C)]H. Zionga fuses
Never mind.
[end_choice][clear][end]

msg_318:
[tab]What about Kanaloa, HO?
[choice(6)][if(CBIT_HEAR_AQU_L)][if_not(BBIT_W_AQUES_L)]W. Aques is strong
[if(CBIT_HEAR_AQU_M)][if_not(CBIT_HEAR_AQU_S)]Uses Wondrous Aques
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_M)]W. Aques is normal
[if(CBIT_HEAR_AQU_S)][if_not(BBIT_W_AQUES_S)]W. Aques is weak
[if(CBIT_HEAR_AQU_C)][if_not(BBIT_W_AQUES_C)]W. Aques fuses
Never mind.
[end_choice][clear][end]

msg_319:
[tab]So what about Demeter, HO?
[choice(6)][if(CBIT_HEAR_FRA_L)][if_not(BBIT_U_FRAIRA_L)]U. Freila is strong
[if(CBIT_HEAR_FRA_M)][if_not(CBIT_HEAR_FRA_S)]Uses Ultra Freila
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_M)]U. Freila is normal
[if(CBIT_HEAR_FRA_S)][if_not(BBIT_U_FRAIRA_S)]U. Freila is weak
[if(CBIT_HEAR_FRA_C)][if_not(BBIT_U_FRAIRA_C)]U. Freila fuses
Never mind.
[end_choice][clear][end]

msg_320:
[tab]What about Succubus?
[choice(6)][if(CBIT_HEAR_MEG_L)][if_not(BBIT_C_MEGIDO_L)]S. Megido is strong
[if(CBIT_HEAR_MEG_M)][if_not(CBIT_HEAR_MEG_S)]Uses Super Megido
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_M)]S. Megido is normal
[if(CBIT_HEAR_MEG_S)][if_not(BBIT_C_MEGIDO_S)]S. Megido is weak
[if(CBIT_HEAR_MEG_C)][if_not(BBIT_C_MEGIDO_C)]S. Megido fuses
Never mind.
[end_choice][clear][end]

msg_321:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Wow, that's an interesting rumor, HO!
[tab]Now then, I'll go tell everybody, HO!
[wait][clear][end]

msg_322:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]That's about me, HO!!
[wait][clear][end]

msg_323:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]HUH! No rumors, HO?
[tab]Next time we meet, be sure to have some
[tab]fun rumors for me, HO!
[wait][clear][end]

msg_324:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I know the truth, HO...
[tab]Your [color(orange)]katana[color(white)] is a piece of [color(orange)]junk[color(white)]!
[tab]I'm going to tell everyone, HO!
[wait][clear][end]

msg_325:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I know the truth, HO...
[tab]Your [color(orange)]handgun[color(white)] is a piece of [color(orange)]junk[color(white)]!
[tab]I'm going to tell everyone, HO!
[wait][clear][end]

msg_326:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I know the truth, HO...
[tab]Your [color(orange)]coin[color(white)] is a piece of [color(orange)]junk[color(white)]!
[tab]I'm going to tell everyone, HO!
[wait][clear][end]

msg_327:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I know the truth, HO...
[tab]Your [color(orange)]glove[color(white)] is a piece of [color(orange)]junk[color(white)]!
[tab]I'm going to tell everyone, HO!
[wait][clear][end]

msg_328:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]I-I know the truth, HO...
[tab]Your [color(orange)]rapier[color(white)] is a piece of [color(orange)]junk[color(white)]!
[tab]I'm going to tell everyone, HO!
[wait][clear][end]

msg_329:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]By the way...
[tab]My papa always says that
[tab]humans are "stupid"...
[wait][clear][end]

msg_330:
[tab]You're not really that "dumb" right, HO?
[choice(4)]We're geniuses.
Same as demons.
We're morons.
. . . . . . . . .
[end_choice][clear][end]

msg_331:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]...Hmm?
[tab]Stupid, stupid, stupid, stupid...
[tab]Ah, now I remember, HO!
[wait][clear][end]

msg_332:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Here's a [color(green)][item_with_type(fool_card)][color(white)] card, HO!
[tab]This is my treasure, so take care of it!
[wait][clear][end]

msg_333:
[color(yellow)][var(msg_var_0)][color(white)]
[tab]Ah! I found a human, HO!!
[tab]Hey hey, talk with me, HO!!
[wait][clear][end]

msg_334:
[color(green)]Selection ERROR[color(white)]
[end]
