
msg_0:
[color(yellow)]Businessman[color(white)]
[tab]Hello.
[tab]Narumi is only 10 years old.
[tab]It looks so new, doesn’t it?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]It’s a hassle only having one place to go
[tab]shopping, and that’s the Hotel Pleiades.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]They’re big enough to support a growing
[tab]city, so that’s really good.
[wait][clear][end]

msg_1:
[color(yellow)]Businessman[color(white)]
[tab]There’ve been these bizarre seminars.
[tab]Everyone who goes comes back all weird...
[tab]...It makes it hard for me to work.
[wait][clear][end]

msg_2:
[color(yellow)]Businessman[color(white)]
[tab]I don’t know why, but I don’t want to be here.
[tab]Something feels wrong, but I can’t put my
[tab]finger on it.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]It feels like everything around me is
[tab]crumbling...[delay(15)]
[tab]...Nah, can’t be.
[wait][clear][end]

msg_3:
[color(yellow)]Businessman[color(white)]
[tab]I don’t think the world will end, but the
[tab]images in my head are telling me differently.
[tab]Can it really be true...?
[wait][clear][end]

msg_4:
[color(yellow)]Businessman[color(white)]
[tab]Forget work, all these earthquakes have
[tab]reminded me that ife is more important.
[tab]You should get out, too.
[wait][clear][end]

msg_5:
[color(yellow)]Businessman[color(white)]
[tab]They found some ruins in the subway.
[tab]You know, the one just north of here.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I want to check it out...
[tab]But, it’s just too scary.
[tab]You shouldn’t go there.
[wait][clear][end]

msg_6:
[color(yellow)]Businessman[color(white)]
[tab]I heard a strange thing.
[tab]The flowers in Aoba Park can talk.
[tab]Very strange, huh?
[wait][clear][end]

msg_7:
[color(yellow)]Businessman[color(white)]
[tab]I heard a rumor about the Legendary
[tab]Blacksmith, there must be some reason he’s
[tab]called Legendary.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I’m really interested in that rumor, 
[tab]but I haven’t heard anything else...
[tab]I guess no one’s interested.
[wait][clear][end]

msg_8:
[color(yellow)]Businessman[color(white)]
[tab]In the basement of Kasugayama High School...[delay(15)]
[tab]Kudan appeared.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]That school must be cursed...
[wait][clear][end]

msg_9:
[color(yellow)]Businessman[color(white)]
[tab]The Cursed Taxi is causing the taxi
[tab]business to lose a lot of customers. 
[tab]I use it since my company pays for it.
[wait][clear][end]

msg_10:
[color(yellow)]Businessman[color(white)]
[tab]Wow, now it’s 200 kilometers an hour.
[tab]There’s some old man running around
[tab]Giga Macho.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I wonder if he’s the husband of the
[tab]100km/h Hag...
[tab]I just have that feeling.
[wait][clear][end]

msg_11:
[color(yellow)]Businessman[color(white)]
[tab]These are Blue Cape’s stomping grounds.
[tab]Actually it’s that ship out in the harbor,
[tab]is it safe here?
[wait][clear][end]

msg_12:
[color(yellow)]Businessman[color(white)]
[tab]These are Red Cape’s stomping grounds.
[tab]Actually it’s that ship out in the harbor,
[tab]is it safe here?
[wait][clear][end]

msg_13:
[color(yellow)]Businessman[color(white)]
[tab]Someone saw a dinosaur...
[tab]it was in an arcade...
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]You’d kinda figure to see it out in the open, 
[tab]like in a park or something...
[tab]Must be a pretty small dinosaur.
[wait][clear][end]

msg_14:
[color(yellow)]Businessman[color(white)]
[tab]Do you know of Giga Macho?
[tab]It’s a music mega-store.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I heard some old lady they call the
[tab]100km/h Hag runs around the store at 100km
[tab]an hour. Talk about being out of breath!
[wait][clear][end]

msg_15:
[color(yellow)]Businessman[color(white)]
[tab]It seems that a ghost appeared at the
[tab]TV Station. Her name was Reiko Kashima.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Television stations are like mazes, 
[tab]so I’m sure they’re easy to hide out in 
[tab]and scare people...
[wait][clear][end]

msg_16:
[color(yellow)]Businessman[color(white)]
[tab]Is it true that someone saw a Tsuchinoko?
[tab]They say it’s in a manhole around here.
[tab]I was gonna look for it.
[wait][clear][end]

msg_17:
[color(yellow)]Businessman[color(white)]
[tab]Kasu High has a bad reputation, 
[tab]but talking bad about it because of 
[tab]a ghost is going too far.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Teke Teke didn’t go there because of their
[tab]reputation...
[tab]Anyway, I hope this trouble ends soon.
[wait][clear][end]

msg_18:
[color(yellow)]Businessman[color(white)]
[tab]Do you know of the magazine Fantasy World?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I’ve never read it myself, but they say
[tab]you can win special cards in their contest.
[wait][clear][end]

msg_19:
[color(yellow)]Businessman[color(white)]
[tab]Do you know of the magazine Fantasy World?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I’ve never read it myself, but they say
[tab]you can win items in their contest.
[wait][clear][end]

msg_20:
[color(yellow)]Businessman[color(white)]
[tab]Do you know of the magazine Fantasy World?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I’ve never read it myself, but they say
[tab]you can win accessories in their contest.
[wait][clear][end]

msg_21:
[color(yellow)]Businessman[color(white)]
[tab]Do you know of the magazine Fantasy World?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I’ve never read it myself, but they say
[tab]you can win armor in their contest.
[wait][clear][end]

msg_22:
[color(yellow)]Businessman[color(white)]
[tab]Do you know of the magazine Fantasy World?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I’ve never read it myself, but they say
[tab]you can win weapons in their contest.
[wait][clear][end]

msg_23:
[color(yellow)]Businessman[color(white)]
[tab]Miracle magazine is giving away mystical
[tab]cards in a contest.
[tab]Some people just buy it for the prizes.
[wait][clear][end]

msg_24:
[color(yellow)]Businessman[color(white)]
[tab]Miracle magazine is giving away various
[tab]items in a contest.
[tab]Some people just buy it for the prizes.
[wait][clear][end]

msg_25:
[color(yellow)]Businessman[color(white)]
[tab]I thought Battle Master was a dangerous
[tab]magazine, but they’re popular for contests.
[tab]They’re giving away accessories.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I was surprised, because the name is
[tab]so deceiving. I’m interested now.
[wait][clear][end]

msg_26:
[color(yellow)]Businessman[color(white)]
[tab]The city is dangerous nowadays, so Battle
[tab]Master is holding contest where you can win
[tab]armor.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Maybe I should enter...
[wait][clear][end]

msg_27:
[color(yellow)]Businessman[color(white)]
[tab]The city is dangerous nowadays, so Battle
[tab]Master is holding contest where you can win
[tab]weapons.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Maybe I should enter...
[wait][clear][end]

msg_28:
[color(yellow)]Businessman[color(white)]
[tab]In Ebony at the Hotel Pleiades, 
[tab]I heard there’s a map collector.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I saw a suspicious person by the window,
[tab]I’m thinking that’s him...
[tab]Does he have treasure maps?
[wait][clear][end]

msg_29:
[color(yellow)]Businessman[color(white)]
[tab]That jewelry shop owner at that hotel
[tab]is really skillful, but I never imagined
[tab]he could make weapons and armor.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Well, it’s better than making counterfeit jewelry. 
[tab]Besides, we seem to need that stuff nowadays.
[wait][clear][end]

msg_30:
[color(yellow)]Businessman[color(white)]
[tab]I just found out that the Clair De Lune
[tab]is selling armor.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I go there a lot on my lunch breaks,
[tab]but I never saw it as a place like that.
[tab]I’m surprised.
[wait][clear][end]

msg_31:
[color(yellow)]Businessman[color(white)]
[tab]I just found out that the Clair De Lune
[tab]is selling weapons.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I go there a lot on my lunch breaks,
[tab]but I never saw it as a place like that.
[tab]I’m surprised.
[wait][clear][end]

msg_32:
[color(yellow)]Businessman[color(white)]
[tab]The Sumaru Genie must have accurate
[tab]readings for people to say that she’s
[tab]improved.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I should give it a try.
[wait][clear][end]

msg_33:
[color(yellow)]Businessman[color(white)]
[tab]I heard that the Sumaru Genie started giving
[tab]Affinity Readings, then what did she used
[tab]to do?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]How did she attract customers before?
[tab]I don’t understand.
[wait][clear][end]

msg_34:
[color(yellow)]Businessman[color(white)]
[tab]The Sumaru Genie has been the talk of
[tab]the town lately, but Wang Long fortune
[tab]telling isn’t for me...
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I don’t like people I don’t know questioning me, 
[tab]so I shy away from that place.
[wait][clear][end]

msg_35:
[color(yellow)]Businessman[color(white)]
[tab]That foo-foo Etheria is changing their
[tab]services in order to be different than
[tab]their competitors.
[wait][clear][end]

msg_36:
[color(yellow)]Businessman[color(white)]
[tab]I heard that the Saleswoman at Rosa
[tab]Candida was swallowed by a wave on
[tab]vacation. Was it Paris... or Bali?
[wait][clear][end]

msg_37:
[color(yellow)]Businessman[color(white)]
[tab]That rumor about the Saleswoman at Rosa
[tab]Candida being swallowed by a wave was
[tab]just a rumor. I’m kinda relieved.
[wait][clear][end]

msg_38:
[color(yellow)]Businessman[color(white)]
[tab]The Saleswoman at Rosa Candida really was
[tab]swallowed by a wave in Bali.
[tab]On vacation, too. How sad.
[wait][clear][end]

msg_39:
[color(yellow)]Businessman[color(white)]
[tab]The Saleswoman at Rosa Candida
[tab]was overwhelmed by Paris’ fashion.
[tab]That’s the real thing.
[wait][clear][end]

msg_40:
[color(yellow)]Businessman[color(white)]
[tab]The Saleswoman at Rosa Candida really was
[tab]swallowed by a wave in Bali.
[tab]On vacation, too. How sad.
[wait][clear][end]

msg_41:
[color(yellow)]Businessman[color(white)]
[tab]The boutique Rosa Candida
[tab]is now selling armor.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]They’re really business savvy, they have
[tab]their finger on the pulse of the consumer.
[wait][clear][end]

msg_42:
[color(yellow)]Businessman[color(white)]
[tab]The barkeeper at Parabellum hired a
[tab]bouncer, I heard.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]That pretty extreme, at least in my opinion.
[wait][clear][end]

msg_43:
[color(yellow)]Businessman[color(white)]
[tab]Parabellum selling weapons...
[tab]It’s so sudden, I can’t believe it.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I go to that bar once in a while,
[tab]and I thought it wasn’t your average bar, 
[tab]but this is surprising.
[wait][clear][end]

msg_44:
[color(yellow)]Businessman[color(white)]
[tab]The music store Giga Macho supposedly
[tab]has a special Mambo CD that you can’t buy
[tab]normally.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Dealing on the black market is so dark,
[tab]especially for such lively music as that... 
[tab]They’re marketing it all wrong.
[wait][clear][end]

msg_45:
[color(yellow)]Businessman[color(white)]
[tab]The music store Giga Macho supposedly
[tab]has a special Rock CD that you can’t buy
[tab]normally.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Are they trying to create demand for it by
[tab]selling it in such a strange fashion? 
[tab]I think they should just sell it normally.
[wait][clear][end]

msg_46:
[color(yellow)]Businessman[color(white)]
[tab]The arcade, Mu Continent, 
[tab]seems to have opened a casino.
[tab]Gambling does well in recessions...
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I have to go there, at least once.
[tab]I heard that you can cash in on Poker.
[tab]I’m good at Poker, lucky me.
[wait][clear][end]

msg_47:
[color(yellow)]Businessman[color(white)]
[tab]The arcade, Mu Continent, 
[tab]seems to have opened a casino.
[tab]Gambling does well in recessions...
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I have to go there, at least once.
[tab]They say you should play Blackjack. 
[tab]I don’t remember how the rules go...
[wait][clear][end]

msg_48:
[color(yellow)]Businessman[color(white)]
[tab]The arcade, Mu Continent, 
[tab]seems to have opened a casino.
[tab]Gambling does well in recessions...
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I have to go there, at least once.
[tab]I heard that the Slots are loose.
[tab]Damn, I’m no good at this.
[wait][clear][end]

msg_49:
[color(yellow)]Businessman[color(white)]
[tab]I heard that the accessories sold at
[tab]Tony’s Shop have mysterious powers.
[tab]Why don’t you check it out?
[wait][clear][end]

msg_50:
[color(yellow)]Businessman[color(white)]
[tab]The self-defense items that Tony sells
[tab]are very popular.
[tab]I was going to go and buy some.
[tab][wait][clear][end]

msg_51:
[color(yellow)]Businessman[color(white)]
[tab]The selection at Toua Defense 
[tab]seems to have improved.
[tab]I’d hope so, at times like this...
[wait][clear][end]

msg_52:
[color(yellow)]Businessman[color(white)]
[tab]Toua Defense stopped peddling armor and
[tab]switched to weapons.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]They say that the best defense is
[tab]a good offense. But that’s still scary.
[wait][clear][end]

msg_53:
[color(yellow)]Businessman[color(white)]
[tab]When I heard that the owner of Izakaya
[tab]Shiraishi made her dream come true,
[tab]I couldn’t say anything.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]A lot has happened, and here I am,
[tab]with the word "dream" fading from
[tab]my mind...
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]It’s not like I’m discontent.
[tab]I’m just a bit sad.
[wait][clear][end]

msg_54:
[color(yellow)]Businessman[color(white)]
[tab]Can Izakaya Shiraishi afford to do
[tab]business searching for people?
[tab]I heard a rumor about that.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]Or is it that she’s making enough money,
[tab]so she’s doing this on the side?
[tab]She must be doing well for herself.
[wait][clear][end]

msg_55:
[color(yellow)]Businessman[color(white)]
[tab]Say, that store Kaori is really popular,
[tab]huh?
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]It was closed when I went there.
[tab]She probably got sick.
[wait][clear][end]

msg_56:
[color(yellow)]Businessman[color(white)]
[tab]The reason Kaori was closed was because
[tab]she went to buy more merchandise.
[tab]Well, I’m glad it wasn’t the flu.
[wait][clear][end]

msg_57:
[color(yellow)]Businessman[color(white)]
[tab]So, the owner of Kaori was sick.
[tab]She should be more careful with her health.
[wait][clear][end]

msg_58:
[color(yellow)]Businessman[color(white)]
[tab]Kaori is starting to sell new products.
[tab]Despite how popular they are, they put
[tab]a lot of effort into pleasing people.
[wait][clear][color(yellow)]Businessman[color(white)]
[tab]I can’t lose either.
[wait][clear][end]

msg_59:
[color(yellow)]Businessman[color(white)]
[tab]It seems that the owner of Kaori
[tab]caught a cold.
[tab]Well, she should rest...
[wait][clear][end]

msg_60:
[color(yellow)]Businessman[color(white)]
[tab]The Time Castle will duplicate Skill Cards.
[tab]They do some strange business.
[wait][clear][end]

msg_61:
[color(yellow)]Businessman[color(white)]
[tab]They’re selling Skill Cards at the Time Castle.
[tab]I wonder if they have magic shows, too?
[wait][clear][end]

msg_62:
[color(yellow)]Businessman[color(white)]
[tab]I heard from someone that 
[tab]there’s a giant maze in Zodiac.
[tab]I also heard that there’s a bunch of items.
[wait][clear][end]

msg_63:
[color(yellow)]Tourist[color(white)]
[tab]I talked to a fisherman, and he told me
[tab]about a red specter thing offshore.
[wait][clear][color(yellow)]Tourist[color(white)]
[tab]I didn’t know what he was talking about, 
[tab]but he was saying something about a cape.
[wait][clear][color(yellow)]Tourist[color(white)]
[tab]Could it be the [color(orange)]Red Cape
[tab]who appears offshore?[color(white)]
[tab]I want to see it.
[wait][clear][end]

msg_64:
[color(yellow)]Tourist[color(white)]
[tab]Red Cape, huh...
[tab]I want to get a picture of that.
[wait][clear][end]

msg_65:
[color(yellow)]Tourist[color(white)]
[tab]I talked to a fisherman, and he told me
[tab]about a blue specter thing offshore.
[wait][clear][color(yellow)]Tourist[color(white)]
[tab]I didn’t know what he was talking about, 
[tab]but he was saying something about a cape.
[wait][clear][color(yellow)]Tourist[color(white)]
[tab]Could it be the [color(orange)]Blue Cape
[tab]who appears offshore?[color(white)]
[tab]I want to see it.
[wait][clear][end]

msg_66:
[color(yellow)]Tourist[color(white)]
[tab]Blue Cape, huh...
[tab]I want to get a picture of that.
[wait][clear][end]

msg_67:
[color(yellow)]Tourist[color(white)]
[tab]Thanks for the cape story.
[tab]Now I have a story to tell my friends
[tab]at home.
[wait][clear][end]

msg_68:
[color(yellow)]Tourist[color(white)]
[tab]Oh!
[tab]Could that red cape be...
[wait][clear][color(yellow)]Tourist[color(white)]
[tab]It is! It’s the cape of the rumored apparition! 
[tab]Can you give it to me?
[tab]Really!?
[wait][clear][color(yellow)]Tourist[color(white)]
[tab]Thank you very much.
[tab]Please take this.
[wait][clear] [color(green)]Maya got [item_with_type(aishu_masamune)].
[wait][clear][end]

msg_69:
[color(yellow)]Tourist[color(white)]
[tab]Oh!
[tab]Could that blue cape be...[wait][clear][color(yellow)]Tourist[color(white)]
[tab]It is! It’s the cape of the rumored specter! 
[tab]Can you give it to me?
[tab]Really!?[wait][clear][color(yellow)]Tourist[color(white)]
[tab]Thank you very much.
[tab]Please take this.
[wait][clear] [color(green)]Maya got [item_with_type(woman_powered)].
[wait][clear][end]

msg_70:
[color(yellow)]Tourist[color(white)]
[tab]This place has been a hotbed of activity.
[tab]I just came at the wrong time. 
[tab]I’m worried about my family... I should go home.
[wait][clear][end]

msg_71:
[color(yellow)]Adventurer[color(white)]
[tab]Listen up!
[tab]I finally found a real [color(orange)]Tsuchinoko[color(white)]!!
[wait][clear][color(yellow)]Adventurer[color(white)]
[tab]...But it escaped down a manhole.
[tab]Can someone catch it for me?
[wait][clear][end]

msg_72:
[color(yellow)]Adventurer[color(white)]
[tab]Can someone catch it for me?
[tab]I finally find it, and it runs away...
[wait][clear][end]

msg_73:
[color(yellow)]Adventurer[color(white)]
[tab]It’s too bad how this turned out,
[tab]but thanks for trying anyway.
[tab]I’ll try looking somewhere else.
[wait][clear][end]

msg_74:
[color(yellow)]Adventurer[color(white)]
[tab]...This is the corpse of a Tsuchinoko?
[tab]I must’ve mistaken it for a snake.
[wait][clear][color(yellow)]Adventurer[color(white)]
[tab]Sorry to put you through so much trouble.
[tab]Let me give you this.
[wait][clear] [color(green)]Maya got [item_with_type(item_breeder)].
[wait][clear][end]

msg_75:
[color(yellow)]Adventurer[color(white)]
[tab]It sucks that the city is always busy.
[tab]I work in nature, so I get tired of places like this.
[wait][clear][color(yellow)]Adventurer[color(white)]
[tab]Plus, it seems that there’s a bunch of
[tab]dangerous things going on... 
[tab]I’d rather climb mountains and discover new animals.
[wait][clear][end]

msg_76:
[color(yellow)]Nanjo[color(white)]
[tab]The Laboratory has tight security, 
[tab]making it impossible to infiltrate from here...
[tab]But not from the Sewer.
[sync][wait][clear][end]

msg_77:
[color(yellow)]Nanjo[color(white)]
[tab]I never thought I’d say this, 
[tab]but let’s head towards the Sewer.
[sync][wait][clear][end]

msg_78:
[color(yellow)]Nanjo[color(white)]
[tab]It’s...[delay(15)]dangerous here.
[tab]We shouldn’t be here.
[wait][clear][end]

msg_79:
[color(yellow)]Elly[color(white)]
[tab]I didn’t think that the New World Order
[tab]could do something so extreme.
[wait][clear][color(yellow)]Elly[color(white)]
[tab]I can’t believe we were so careless.
[wait][clear][end]

msg_80:
[color(yellow)]Ulala[color(white)]
[tab]We shouldn’t be here, especially after what
[tab]happened. Let’s get the hell outta here!
[wait][clear][end]

msg_81:
[color(yellow)]Katsuya[color(white)]
[tab]We shouldn’t be trespassing on private property.
[tab]Let’s move on.
[wait][clear][end]

msg_82:
[color(yellow)]Baofu[color(white)]
[tab]. . . . . . . . .
[wait][clear][end]

msg_83:
[color(yellow)]Ulala[color(white)]
[tab]Hey, what do you want to go there for?
[tab]We have someplace to be, Ma-ya.
[wait][clear][end]

msg_84:
[color(yellow)]Baofu[color(white)]
[tab]I don’t think we need to go there anymore.
[tab]C’mon, hurry up!
[wait][clear][end]

msg_85:
[color(yellow)]Elly[color(white)]
[tab]Let’s leave Kei here, 
[tab]and go to the television station.
[wait][clear][end]

msg_86:
[color(yellow)]Nanjo[color(white)]
[tab]We have no more business here.
[tab]We should make our way to Smile Hirasaka.
[wait][clear][end]

msg_87:
[color(yellow)]Ulala[color(white)]
[tab]We don’t need to be here, right?
[tab]It’s certainly not enjoyable, 
[tab]so let’s get outta here.
[wait][clear][end]

msg_88:
[color(yellow)]Katsuya[color(white)]
[tab]You can’t possibly want to go into the sewer. 
[tab]There’s no reason to be here.
[tab]So, let’s go somewhere else.
[wait][clear][end]

msg_89:
[color(yellow)]Ulala[color(white)]
[tab]This station’s still under construction.
[tab]We might as well hoof it.
[wait][clear][end]

msg_90:
[color(yellow)]Katsuya[color(white)]
[tab]We shouldn’t be sneaking into a closed
[tab]construction site...
[tab]Let’s go.
[wait][clear][end]

msg_91:
[color(yellow)]Baofu[color(white)]
[tab]We’re done with this place.
[tab]Let’s make like a tree...
[wait][clear][end]

msg_92:
[color(yellow)]Katsuya[color(white)]
[tab]So, this is the Laboratory...[delay(15)]
[tab]We can’t get up to the building to see
[tab]inside with the gates closed.
[wait][clear][end]

msg_93:
[color(yellow)]Ulala[color(white)]
[tab]These walls are huge.
[tab]It’s like a prison.
[wait][clear][end]

msg_94:
[color(yellow)]Nanjo[color(white)]
[tab]This place is protected by cameras, sensors,
[tab]high-voltage fencing and a wall.
[tab]A frontal assault will be impossible.
[wait][clear][end]

msg_95:
[color(yellow)]Katsuya[color(white)]
[tab]You’re right.
[tab]We’ll have to find another way in, 
[tab]how about the Sewer?
[wait][clear][end]

msg_96:
[color(yellow)]Ulala[color(white)]
[tab]I really wish we wouldn’t, 
[tab]but we don’t have much of a choice.
[tab]Let’s go.
[wait][clear][end]

msg_97:
[color(yellow)]Katsuya[color(white)]
[tab]Getting in through the front is going to
[tab]be next to impossible.
[tab]Let’s try the Sewer.
[wait][clear][end]

msg_98:
[color(yellow)]Elly[color(white)]
[tab]Let’s leave Kei here, and go to Aoba.
[wait][clear][end]

msg_99:
[color(yellow)]Baofu[color(white)]
[tab]There’s nothing here for us.
[tab]Let’s jet.
[wait][clear][end]

msg_100:
[color(yellow)]Ulala[color(white)]
[tab]This place gives me the creeps.
[tab]Let’s get the hell outta here.
[wait][clear][end]
