
msg_0:
[color(yellow)]Young girl[color(white)]
[tab]Lately, there’s been a lot of bad news,
[tab]we have to blow off steam by going out.
[tab]Yumezaki is the place to hang out.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Mu Continent, the amusement center,
[tab]Giga Macho, the CD shop and recording studio.[delay(10)] 
[tab]The sports club GOLD is cool, too.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Now if I could just find a cool guy,
[tab]I’d be content...
[wait][clear][end]

msg_1:
[color(yellow)]Young girl[color(white)]
[tab]I don’t know who the perpetrator is, 
[tab]but Joker hunting isn’t a bad thing is it?
[tab]Since a Joker is dangerous and all.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I think it’s best to get rid of ’em.
[tab]They became a Joker by doing curses,
[tab]so it’s their own fault.
[wait][clear][end]

msg_2:
[color(yellow)]Young girl[color(white)]
[tab]All the TV shows talk about the Joker case.
[tab]When they DO show the pop group, Muses,
[tab]they’re interrupted by a Wang Long guest.
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Murders and abductions are bad, 
[tab]but making boring television is a real crime.
[tab]They should hurry up and solve it.
[wait][clear][end]

msg_3:
[color(yellow)]Young girl[color(white)]
[tab]People like going to seminars,
[tab]but I don’t feel like going.
[tab]I don’t like being told what to do.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Should I consider it, having a philosophy in life? 
[tab]I guess I’m different than most people.
[wait][clear][end]

msg_4:
[color(yellow)]Young girl[color(white)]
[tab]I’ve been having strange dreams. 
[tab]What I’m doing in them isn’t different, 
[tab]but my image of myself is so different.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]A normal girl who says irresponsible things.
[tab]It’s an unpleasant feeling...
[tab]It’s just a dream, but it’s me after all...
[wait][clear][end]

msg_5:
[color(yellow)]Young girl[color(white)]
[tab]NWO or WNO or whatever they are, 
[tab]what the hell are they thinking? 
[tab]Talking about kegare and resurrection and crap.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Everyone has different priorities,
[tab]I think the world is cool the way it is.
[tab]Business still sucks, though.
[wait][clear][end]

msg_6:
[color(yellow)]Young girl[color(white)]
[tab]Big earthquake, huh?
[tab]You think it was bad?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I withdrew all my savings for this... 
[tab]if the city falls apart, money’s no good.
[tab]I hope someone does something.
[wait][clear][end]

msg_7:
[color(yellow)]Young girl[color(white)]
[tab]Ruins were found in a subway construction
[tab]site in Narumi Ward.
[tab]You know, the stuff that was on TV.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Huh? You haven’t seen it?
[tab]The New World Order was digging it up.
[tab]They just do whatever they want.[wait][clear][end]

msg_8:
[color(yellow)]Young girl[color(white)]
[tab]The city is flying in the sky and it feels
[tab]normal. I seem to have this vision.
[tab]Is it D五j二 Vu?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]There’ll be something worse.
[tab]I bet all the stuff on TV will come true.
[wait][clear][end]

msg_9:
[color(yellow)]Young girl[color(white)]
[tab]It’s all over anyway, right?
[tab]Why don’t they just get it over with?
[tab]I’m so sick of this.
[wait][clear][end]

msg_10:
[color(yellow)]Young girl[color(white)]
[tab]I heard the inside of Club Zodiac is a big maze. 
[tab]But, you know, I hate walking.
[wait][clear][end]

msg_11:
[color(yellow)]Young girl[color(white)]
[tab]Sumaru Castle has reappeared.
[tab]I heard that the castle is home to a lot of
[tab]occult happenings...
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]...like Kiyotada Sumaru and Maihime Amano.
[tab]You should stay away from it.
[wait][clear][end]

msg_12:
[color(yellow)]Young girl[color(white)]
[tab]That haunted... I mean Sumaru Castle,
[tab]I heard it was once stage for romance.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]They say the ones who defeated Kiyotada
[tab]Sumaru, the owner of the castle, were the
[tab]couple Tatsunoshin [suou] and Maihime Amano.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]It would have been nice if it had a happy
[tab]ending...
[wait][clear][end]

msg_13:
[color(yellow)]Young girl[color(white)]
[tab]Sumaru Castle has reappeared.
[tab]I heard that the castle is home to a lot of
[tab]occult happenings...
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]...like Kiyotada Sumaru and Tatsunoshin
[tab][suou]. You should stay away from it.
[wait][clear][end]

msg_14:
[color(yellow)]Young girl[color(white)]
[tab]That haunted... I mean Sumaru Castle,
[tab]I heard it was once stage for romance.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]They say the ones who defeated Kiyotada
[tab]Sumaru, the owner of the castle, were the
[tab]couple Tatsunoshin [suou] and Maihime Amano.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]It would have been nice if it had a happy
[tab]ending...
[wait][clear][end]

msg_15:
[color(yellow)]Young girl[color(white)]
[tab]They say the flowers in Aoba Park talk.
[tab]Kinda like a parrot.
[tab]Maybe I should pick some sometime.
[wait][clear][end]

msg_16:
[color(yellow)]Young girl[color(white)]
[tab]I’ve heard that an experienced blacksmith
[tab]named Takumi Asano is very skilled.
[tab][wait][clear][color(yellow)]Young girl[color(white)]
[tab]He is also called the Legendary Blacksmith.
[tab]He makes katanas, right?
[tab]His wares fetch a hefty price...
[wait][clear][end]

msg_17:
[color(yellow)]Young girl[color(white)]
[tab]Ku, Kudan is that...
[tab]No! [delay(15)]I can’t say any more.
[wait][clear][end]

msg_18:
[color(yellow)]Young girl[color(white)]
[tab]Hey, hey, [delay(15)]is it true that the Cursed Taxi 
[tab]showed in front of Mu Continent?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]You know, I just grabbed a cab near there.
[tab]That was a close one.
[wait][clear][end]

msg_19:
[color(yellow)]Young girl[color(white)]
[tab]You remember the 100km/h Hag, right?
[tab]They say now there’s a 200km/h Fogey.
[tab]Ahhaha![wait][clear][color(yellow)]Young girl[color(white)]
[tab]It’s like an old age hot-rodder.
[tab]Even though he’s on foot.
[tab]That’s pretty funny.
[wait][clear][end]

msg_20:
[color(yellow)]Young girl[color(white)]
[tab]Blue Cape or whatever it is, has terrible
[tab]fashion sense. If it’s going to show up on
[tab]a passenger boat, it should be a Black Cape.
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]You know, like Zorro?
[tab]Something like that would be cool.
[wait][clear][end]

msg_21:
[color(yellow)]Young girl[color(white)]
[tab]Red Cape or whatever it is, has terrible
[tab]fashion sense. If it’s going to show up on
[tab]a passenger boat, it should be a Black Cape.
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]You know, like Zorro?
[tab]Something like that would be cool.
[wait][clear][end]

msg_22:
[color(yellow)]Young girl[color(white)]
[tab]It’s cool that there’s a dinosaur in Mu Continent. 
[tab]But, can’t they do something about its name,  
[tab]Mussie? It’s just not right.
[wait][clear][end]

msg_23:
[color(yellow)]Young girl[color(white)]
[tab]I heard there’s a 100km/h Hag
[tab]at Giga Macho.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]They say for being a old timer, 
[tab]she’s pretty fast.
[tab]Ahaha, that’s so stupid.
[wait][clear][end]

msg_24:
[color(yellow)]Young girl[color(white)]
[tab]I heard that Reiko Kashima showed up at the
[tab]TV station! TV stations ARE haunted.
[tab]Better not go alone.
[wait][clear][end]

msg_25:
[color(yellow)]Young girl[color(white)]
[tab]I heard a Tsuchinoko showed up...
[tab]Can I ask you something?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]What the hell’s a Tsuchinoko?
[tab]I’ve just been repeating what I hear, 
[tab]but I don’t know what it is. Ahaha...
[wait][clear][end]

msg_26:
[color(yellow)]Young girl[color(white)]
[tab]There was a ghost in Kasu High School...
[tab]called Teke Teke or something...
[tab]That school really IS screwed up.
[wait][clear][end]

msg_27:
[color(yellow)]Young girl[color(white)]
[tab]I heard Fantasy World is giving away some
[tab]strange cards. That’s stupid.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]You’d think money or something would
[tab]make a better prize.
[wait][clear][end]

msg_28:
[color(yellow)]Young girl[color(white)]
[tab]I heard Fantasy World is giving away some
[tab]really strange items. Who’d want crap
[tab]like that?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]You’d think money or something would
[tab]make a better prize.
[wait][clear][end]

msg_29:
[color(yellow)]Young girl[color(white)]
[tab]I heard Fantasy World was giving away
[tab]accessories. That’s sweet![wait][clear][color(yellow)]Young girl[color(white)]
[tab]I wonder if they have imported stuff.
[tab]Actually, I kinda collect them,
[tab]I plan on checking it out sometime.
[wait][clear][end]

msg_30:
[color(yellow)]Young girl[color(white)]
[tab]Hey, hey. I heard Fantasy World 
[tab]was giving away armor. 
[tab]Weren’t they originally halloween costumes?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]The city has gotten dangerous, 
[tab]so armor can be useful, but it’s so uncool. 
[tab]I might get some, if it looks good on me.
[wait][clear][end]

msg_31:
[color(yellow)]Young girl[color(white)]
[tab]I heard you can win real weapons from
[tab]Fantasy World, isn’t that dangerous?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Their name and what they do seems like
[tab]a total contradiction.
[tab]I wonder what kind of people read it.
[wait][clear][end]

msg_32:
[color(yellow)]Young girl[color(white)]
[tab]I heard you can win a Skill Card from a
[tab]magazine called Miracle. 
[tab]I wonder if there’s a card that’ll make you thin.
[wait][clear][end]

msg_33:
[color(yellow)]Young girl[color(white)]
[tab]I heard Miracle is giving away some
[tab]strange items. I just don’t get it.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]If anybody knows what kind of things they are, 
[tab]I’d like to know.
[wait][clear][end]

msg_34:
[color(yellow)]Young girl[color(white)]
[tab]I like accesories, but it would feel weird
[tab]winning an accessory from a magazine
[tab]called Monthly Battle Master.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]It’ll be something like a pendant with
[tab]pictures of bullets or tanks or stuff, right?
[tab]I think I’ll pass.
[wait][clear][end]

msg_35:
[color(yellow)]Young girl[color(white)]
[tab]It seems you can win real armor,
[tab]how convenient...
[tab]Did they plan it this way?
[wait][clear][end]

msg_36:
[color(yellow)]Young girl[color(white)]
[tab]I heard that if you want real weapons,
[tab]you should enter the Battle Master
[tab]contest.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I heard that you can win some pretty
[tab]impressive stuff.
[wait][clear][end]

msg_37:
[color(yellow)]Young girl[color(white)]
[tab]I heard someone at Ebony collects
[tab]maps from around the world.
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Maybe maps that cost thousands of yen...
[tab]Like Marco Polo’s map, perhaps.
[wait][clear][end]

msg_38:
[color(yellow)]Young girl[color(white)]
[tab]There’s a guy at Satomi Tadashi, 
[tab]in Hirasaka that’s collecting maps, 
[tab]what’s the big deal?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]He’s rich, he probably has a helicopter
[tab]or something so he can escape![delay(20)]
[tab]Not that it’ll matter where he goes.
[wait][clear][end]

msg_39:
[color(yellow)]Young girl[color(white)]
[tab]I heard the jewelry shop in the hotel in
[tab]Narumi moved their business to Kounan.
[tab]That’s dedication...
[wait][clear][end]

msg_40:
[color(yellow)]Young girl[color(white)]
[tab]The jeweler said he’s a master craftsman,
[tab]and will make weapons and armor, 
[tab]sounds like something from a fantasy novel.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]He’s probably some middle-aged guy with a
[tab]scruffy beard.
[tab]Hahaha...
[wait][clear][end]

msg_41:
[color(yellow)]Young girl[color(white)]
[tab]The restaurant Clair De Lune is incredible.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]You wouldn’t think they could move a
[tab]restaurant to Aoba Way if the city
[tab]takes off. But, it’s kinda cool.
[wait][clear][end]

msg_42:
[color(yellow)]Young girl[color(white)]
[tab]Do you know about Clair De Lune?
[tab]I heard they sell armor, but they’re
[tab]a restaurant, right?
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I think that’s wrong, but the people like it, 
[tab]it’s so strange...
[wait][clear][end]

msg_43:
[color(yellow)]Young girl[color(white)]
[tab]Do you know about Clair De Lune?
[tab]I heard they sell weapons, but they’re
[tab]a restaurant, right?
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I think that’s wrong, but the people like it, 
[tab]it’s so strange...
[wait][clear][end]

msg_44:
[color(yellow)]Young girl[color(white)]
[tab]I heard the Sumaru Genie can give you 
[tab]an affinity reading for non-humans. 
[tab]Are people going to use this to choose pets?
[wait][clear][end]

msg_45:
[color(yellow)]Young girl[color(white)]
[tab]Right now I have 8 boyfriends, 
[tab]but I can’t choose which one to keep.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Sumaru Genie’s affinity readings are popular, 
[tab]so I’m going to get my fortune read. 
[tab]Hehehe, I’m so smart.
[wait][clear][end]

msg_46:
[color(yellow)]Young girl[color(white)]
[tab]I heard the Sumaru Genie’s fortunes were
[tab]always wrong, but Wang Long’s are really accurate.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I heard it’s so accurate.
[tab]It’s pretty amazing.
[wait][clear][end]

msg_47:
[color(yellow)]Young girl[color(white)]
[tab]You know the salon, Etheria, changed their 
[tab]services. I guess to separate themselves
[tab]from their competition.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I better check up on it.
[tab]Looks are important after all.
[wait][clear][end]

msg_48:
[color(yellow)]Young girl[color(white)]
[tab]The clerk at Rosa Candida was swallowed by
[tab]a wave during vacation?[wait][clear][color(yellow)]Young girl[color(white)]
[tab]That’s so lame!
[tab]I won’t go to that store anymore.
[wait][clear][end]

msg_49:
[color(yellow)]Young girl[color(white)]
[tab]Rosa Candida started selling armor,
[tab]I guess it’s that kind of world now.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]It’s dangerous out there and all the self-
[tab]defense stuff is so lame. Armor design is
[tab]important, too.
[wait][clear][end]

msg_50:
[color(yellow)]Young girl[color(white)]
[tab]I thought they only had bouncers in movies.
[tab]But, Parabellum has hired one.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]That’s kinda cool.
[tab]Do bouncers get payed well?
[wait][clear][end]

msg_51:
[color(yellow)]Young girl[color(white)]
[tab]I heard they sell weapons at Parabellum,
[tab]they’ll sell just about anything. 
[tab]Maybe they’ll start selling humans.
[wait][clear][end]

msg_52:
[color(yellow)]Young girl[color(white)]
[tab]Did you hear about the new Mambo CD?
[tab]I like the Muses’ new album.
[tab]Mambo’s pretty lame.
[wait][clear][end]

msg_53:
[color(yellow)]Young girl[color(white)]
[tab]Did you know they sell black market CDs at
[tab]Giga Macho? I hope I’m not too late!
[tab]I gotta go buy some now!
[wait][clear][end]

msg_54:
[color(yellow)]Young girl[color(white)]
[tab]I heard the arcade, Mu Continent, 
[tab]became a casino.
[tab]They say that Poker is very profitable.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Gambling is fun, isn’t it?
[tab]Hehehe.
[wait][clear][end]

msg_55:
[color(yellow)]Young girl[color(white)]
[tab]I heard the arcade, Mu Continent, 
[tab]became a casino.
[tab]They say that Blackjack is very profitable.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Gambling is fun, isn’t it?
[tab]Hehehe.
[wait][clear][end]

msg_56:
[color(yellow)]Young girl[color(white)]
[tab]I heard the arcade, Mu Continent, 
[tab]became a casino. They say that 
[tab]the Slot machines are very profitable.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Gambling is fun, isn’t it?
[tab]Hehehe.
[wait][clear][end]

msg_57:
[color(yellow)]Young girl[color(white)]
[tab]I was told by someone that Tony’s Shop
[tab]sells some strange accessories.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Accessories from a place like that are no good, 
[tab]but they’re cheap, and sometimes you can 
[tab]find something good.
[wait][clear][end]

msg_58:
[color(yellow)]Young girl[color(white)]
[tab]They say Tony’s Shop sells some
[tab]strange things.
[tab]Like unique Magatamas or somethin’...
[wait][clear][end]

msg_59:
[color(yellow)]Young girl[color(white)]
[tab]Toua Defense is a scary store, isn’t it?
[tab]There’s a rumor that they have some
[tab]incredible armor.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I see people in uniform going in there all the time. 
[tab]I wouldn’t want to go near there.
[wait][clear][end]

msg_60:
[color(yellow)]Young girl[color(white)]
[tab]Toua Defense is a scary store, isn’t it?
[tab]There’s a rumor that they just got some
[tab]very powerful weapons.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I see people in uniform going in there all the time. 
[tab]I wouldn’t want to go near there.
[wait][clear][end]

msg_61:
[color(yellow)]Young girl[color(white)]
[tab]It seems that the owner of Shiraishi is
[tab]all excited over fulfilling her dream
[tab]or something. It’s so annoying.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]A middle-aged woman’s dream comes true,
[tab]but not mine.
[tab](Sigh) Where can I find a cool guy?
[wait][clear][end]

msg_62:
[color(yellow)]Young girl[color(white)]
[tab]I heard that Shiraishi will search for people.
[tab]I was hoping, but then they said my request
[tab]was impossible, and refused.
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I asked for a cool, handsome billionaire
[tab]that will love only me. They said that
[tab]there’s no such thing.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]Isn’t that rude!?
[wait][clear][end]

msg_63:
[color(yellow)]Young girl[color(white)]
[tab]I heard that Kaori is closed, 
[tab]so are they taking an extended vacation?
[tab]I’m envious...
[wait][clear][end]

msg_64:
[color(yellow)]Young girl[color(white)]
[tab]Huh? Kaori is closed because they are out
[tab]buying product?
[tab]What a hassle.[wait][clear][color(yellow)]Young girl[color(white)]
[tab]I hate that kind of work.
[tab]I want an easy job with lots of vacations.
[wait][clear][end]

msg_65:
[color(yellow)]Young girl[color(white)]
[tab]The lady at Kaori caught a cold?
[tab]She’s getting old.
[tab]Colds don’t bother me at all...
[wait][clear][end]

msg_66:
[color(yellow)]Young girl[color(white)]
[tab]So, Kaori is closed because they’re out
[tab]buying more product. That’s a job that
[tab]really keeps you busy.
[wait][clear][end]

msg_67:
[color(yellow)]Young girl[color(white)]
[tab]The lady at Kaori caught a cold?
[tab]She’s getting old.
[tab]Colds don’t bother me at all...
[wait][clear][end]

msg_68:
[color(yellow)]Young girl[color(white)]
[tab]I heard Time Castle will reproduce Skill Cards. 
[tab]Some people really used ’em.
[tab]I’m surprised.
[wait][clear][end]

msg_69:
[color(yellow)]Young girl[color(white)]
[tab]Rengedai’s Time Castle is that
[tab]store with lots of clocks, right?
[tab]It’s kinda scary.
[wait][clear][color(yellow)]Young girl[color(white)]
[tab]It seems you can buy Skill Cards there...
[tab]But, aren’t they really cursed cards?
[wait][clear][end]

msg_70:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey, you’ve got style.
[tab]How about going to that club with me?
[tab]What do you say?
[wait][clear][end]

msg_71:
[color(yellow)]Katsuya[color(white)]
[tab]Hmm...[delay(20)]
[tab]So, where are we going?
[wait][clear][end]

msg_72:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Uhhh, um,[delay(10)]
[tab]I’m very sorry.
[wait][clear][end]

msg_73:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Lately, there’s been some suspicious people
[tab]roaming around, so you should be careful.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Huh? Me?
[tab]Gimme a break.
[tab]I can take care of myself.
[wait][clear][end]

msg_74:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The people we’ve seen around here lately
[tab]have been seen abducting those that
[tab]have become Jokers.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Everyone’s talking about it.
[tab]You should be careful, too.[delay(15)]
[tab]If it comes down to it, I’ll protect you.
[wait][clear][end]

msg_75:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The buzz in the city is all about me, of couse...[delay(15)]
[tab]So? Aren’t you curious?
[wait][clear][end]

msg_76:
[color(yellow)]Ulala[color(white)]
[tab]Hmm...[delay(15)]
[tab]So, what do you know?
[wait][clear][end]

msg_77:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Uhhh, um, it was just a little joke,
[tab]don’t worry about it.
[tab]Hahaha...
[wait][clear][end]

msg_78:
[color(yellow)]Flirtatious Man[color(white)]
[tab]H-Hey...
[tab]I was just playin’ around.
[tab]I thought it might be funny.
[wait][clear][end]

msg_79:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey, do you know about the woman they keep
[tab]talking about? This woman seems to hold the
[tab]key that could unravel this whole thing.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’m not expecting to get a name, but can
[tab]we at least find out what she looks like?
[wait][clear][end]

msg_80:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Those businessmen sure have it rough.
[tab]It seems some workers at the Nanjo Group
[tab]are investigating the Joker incidents.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]It may be a first-rate business, but it
[tab]must suck to be treated like some lackey.
[tab]Don’t you think?
[wait][clear][end]

msg_81:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Wow, are you Eriko Kirishima, the model?
[tab]I am honored to make your acquaintance.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’ve worried about you since I heard on TV
[tab]that you were being stalked. If you would
[tab]allow me, I can protect you.
[wait][clear][end]

msg_82:
[color(yellow)]Ulala[color(white)]
[tab]You seem much more dangerous
[tab]than any stalker.
[wait][clear][end]

msg_83:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey now.
[tab]I’m well known for my sincerity.
[wait][clear][end]

msg_84:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Seminars have gotten popular, 
[tab]so I went to one. 
[tab]But, I was so disappointed.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Everyone was so focused on the seminar,
[tab]nobody would talk to me.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Huh? What was the seminar about?
[tab]Hahaha, I was talking to the girl next to
[tab]me and wasn’t paying attention.
[wait][clear][end]

msg_85:
[color(yellow)]Flirtatious Man[color(white)]
[tab]My mind has been playing tricks on me...
[tab]Is it a d五j二 vu or something?
[tab]That’s what worries me.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’m a sensitive person, after all. 
[tab]I would be so happy if a girl 
[tab]like you was at my side.
[wait][clear][end]

msg_86:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard on the news about the Torifune and
[tab]the New World Order, but that has nothing
[tab]to do with me. Let someone else worry...
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Anyway, why don’t we go out?
[tab]I feel something good will happen.
[wait][clear][end]

msg_87:
[color(yellow)]Flirtatious Man[color(white)]
[tab]That was a big earthquake we just had.
[tab]I heard about this kick-ass nightclub that
[tab]won’t even be affected by a nuclear war.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Why don’t we check it out together?
[tab]No, no, I’m not kidding.
[wait][clear][end]

msg_88:
[color(yellow)]Flirtatious Man[color(white)]
[tab]It seems like nothing’s on TV except stuff
[tab]about the New World Order. How boring!
[tab]That’s the time for me to shine![wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I promise I won’t bore you.
[tab]Let’s enjoy our last weekend together...
[tab][wait][clear][end]

msg_89:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Don’t worry if the city takes off, 
[tab]the TV said that this is the only city 
[tab]that will be saved. I’ve never been wrong.
[wait][clear][end]

msg_90:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Don’t worry! We’ll be saved.
[tab]I just know it.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So, when we’re through with all this,
[tab]wanna go out with me?
[wait][clear][end]

msg_91:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Did you know the inside of Club Zodiac
[tab]is like a maze?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Let’s go check it out together sometime.
[tab]I think it’ll be fun.
[wait][clear][end]

msg_92:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard that Sumaru Castle has reappeared.
[tab]The ghost of Kiyotada Sumaru has been seen
[tab]there. That’s pretty scary.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Legend says a princess named Maihime Amano
[tab]destroyed the ghost, along with her lover.
[tab]Hey, wanna be my Maihime?
[wait][clear][end]

msg_93:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I’m thinking about going to Sumaru Castle
[tab]to destroy the ghost like Tatsunoshin [suou] did, 
[tab]but I don’t have a partner.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Hey, would you like to become my Maihime?
[wait][clear][end]

msg_94:
[color(yellow)]Flirtatious Man[color(white)]
[tab]You know about Sumaru Castle, don’t you?
[tab]The ghost of Kiyotada Sumaru lives there.
[tab]If you go near it, you’ll be cursed.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Legend says a samurai named Tatsunoshin
[tab][suou] beat it to a pulp.
[tab]Can I become your knight and protect you?
[wait][clear][end]

msg_95:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Maihime Amano defeated the ghost, 
[tab]but she had a reliable partner, 
[tab]the samurai Tatsunoshin [suou].[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Don’t you worry your pretty little head.
[tab]I’ll be your partner anytime.
[wait][clear][end]

msg_96:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Did you know that the flowers in Aoba Park talk? 
[tab]That is so interesting...
[tab]Hey, why don’t we go see them together?
[wait][clear][end]

msg_97:
[color(yellow)]Flirtatious Man[color(white)]
[tab]There’s a rumor about a legendary blacksmith. 
[tab]I guess being self-employed scores big points
[tab]with the ladies?
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]...No, it’s all about looks.
[tab]Don’t you think so?
[wait][clear][end]

msg_98:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Everyone’s all scared of a Kudan. 
[tab]If you want, I’ll keep watch over you 
[tab]while you’re sleeping.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So, what is a Kudan anyway?
[tab]I’m actually not sure...
[tab]Hahahaha
[wait][clear][end]

msg_99:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey, you don’t take taxis, do you? 
[tab]Lately, a Cursed Taxi has been picking up 
[tab]fares in the area, so it’s not safe.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I can make sure you get home safe and sound...
[tab]Just let me know.
[wait][clear][end]

msg_100:
[color(yellow)]Flirtatious Man[color(white)]
[tab]D’ya know about the fast old man at Giga Macho? 
[tab]He’s known as the 200km/h Fogey!
[tab]That’s so cool.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Hell, I’m not that fast now...
[wait][clear][end]

msg_101:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Blue Cape used to just appear in the school, 
[tab]now he’s showing up on a boat in Narumi’s harbor.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Of course, I know Blue Cape’s weakness. 
[tab]If you’d join me for dinner, I’ll tell you.
[wait][clear][end]

msg_102:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Red Cape used to just appear in the school, 
[tab]now he’s showing up on a boat in Narumi’s harbor.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Of course, I know Red Cape’s weakness. 
[tab]If you’d join me for dinner, I’ll tell you.
[tab]What do you say?
[wait][clear][end]

msg_103:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Did you hear the story about 
[tab]the dinosaur at Mu Continent? 
[tab]Of course you haven’t seen it yet, right?
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]If you’d like, we could go see it...
[tab]If you get scared, just hold on to me.
[tab]What do you say?
[wait][clear][end]

msg_104:
[color(yellow)]Flirtatious Man[color(white)]
[tab]That crabby old hag used to be famous,
[tab]but now it’s the 100km/h Hag.
[tab]Apparently, she blasts by Giga Macho.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I think it’s pretty cool,
[tab]but she’s too old for me.
[tab]Too bad, fast women are my game.
[wait][clear][end]

msg_105:
[color(yellow)]Flirtatious Man[color(white)]
[tab]It’s about that ghost, Reiko Kashima,
[tab]that appears at Sumaru TV. 
[tab]I wish they’d do something about her.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]As long as she’s a pretty ghost, it’s cool with me... 
[tab]but the conversation would suck.
[tab]I wish she would reform.
[wait][clear][end]

msg_106:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey hey, are you interested in the Tsuchinoko?
[tab]Do you wanna see it?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I could go find one for you... 
[tab]what would it be worth to you, a date maybe?
[wait][clear][end]

msg_107:
[color(yellow)]Flirtatious Man[color(white)]
[tab]...[delay(20)]Teke Teke, right?
[tab]No, I don’t like talking about high school.
[wait][clear][end]

msg_108:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard you could win a strange card from
[tab]a magazine called Fantasy World.
[tab]Are you interested?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I could get you an entry blank, 
[tab]but what’s it worth to you?
[tab][wait][clear][end]

msg_109:
[color(yellow)]Flirtatious Man[color(white)]
[tab]A magazine called Fantasy World is giving
[tab]away prizes, are you interested?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I could get you an entry blank, 
[tab]but what’s it worth to you?
[wait][clear][end]

msg_110:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The magazine Fantasy World is having a
[tab]contest, the prizes are some cool
[tab]accessories.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I could get you an entry blank, 
[tab]but what’s it worth to you?
[wait][clear][end]

msg_111:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The magazine Fantasy World is having a
[tab]contest, the prizes are some cool armor.
[tab]Are you interested?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I could get you an entry blank, 
[tab]but what’s it worth to you?
[wait][clear][end]

msg_112:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The Magazine Fantasy World is having a
[tab]contest, the prizes are actual weapons.
[tab]Are you interested?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I could get you an entry blank, 
[tab]but what’s it worth to you?
[wait][clear][end]

msg_113:
[color(yellow)]Flirtatious Man[color(white)]
[tab]They say some of the prizes that Miracle
[tab]is giving away are strange cards.
[tab]Oh, you seem interested.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’ve already won one.
[tab]If you’d go out on a date with me,
[tab]I might give it to you as a present.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So?
[tab]What do you think?
[wait][clear][end]

msg_114:
[color(yellow)]Flirtatious Man[color(white)]
[tab]They say one of the prizes Miracle’s giving
[tab]away is really cool.
[tab]Oh, you seem interested.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’ve already won one.
[tab]If you’d go out on a date with me,
[tab]I might give it to you as a present.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So?
[tab]Do you feel lucky?
[wait][clear][end]

msg_115:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard that you can win some cool accessories 
[tab]from Battle Master, but that’s so stupid.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]What girl would even read it?
[tab]I can’t even use it as a decent pick-up line.
[wait][clear][end]

msg_116:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard that you can win some cool armor
[tab]from Battle Master, but that’s so stupid.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]What girl would even read it?
[tab]I can’t even use it as a decent pick-up line.
[wait][clear][end]

msg_117:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard that you can win some real weapons
[tab]from Battle Master, but that’s so stupid.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]What girl would even read it?
[tab]I can’t even use it as a decent pick-up line.
[wait][clear][end]

msg_118:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Do you know about that bar Ebony in the hotel? 
[tab]A rich map collector is there.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]If you’re going there on business, 
[tab]we can get a room and mix business 
[tab]with pleasure.
[wait][clear][end]

msg_119:
[color(yellow)]Flirtatious Man[color(white)]
[tab]There’s a rich map collector at Satomi
[tab]Tadashi in Hirasaka.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]If you plan on going there to sell, may I escort you? 
[tab]On the way back, maybe we can stop for a drink...
[wait][clear][end]

msg_120:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The jewelry store in Hotel Pleiades has
[tab]moved to the Kounan Ward.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]That’s a lot for a business to go through
[tab]to stay in business, that’s tenacity.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So, why don’t we go look at some jewelry?
[tab]Like some engagement rings...
[tab]Heeheehee.
[wait][clear][end]

msg_121:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The jewelry store in Hotel Pleiades...
[tab]Padparacha was it? It seems they’ve begun
[tab]making weapons and armor, too.
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Let’s say I took a girl there, 
[tab]and they pulled out something like that, 
[tab]that would completely ruin the mood.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]It’s going to make it hard to go there.
[wait][clear][end]

msg_122:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The jewelry store that moved to Kounan...
[tab]Padparacha was it? I heard they started
[tab]making weapons and armor.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]They start a new business, at a time like this? 
[tab]Seems pretty foolish...
[wait][clear][end]

msg_123:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Something like that happens and Clair De
[tab]Lune has to reopen in Aoba.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]That’s amazing... wanna go check it out?
[wait][clear][end]

msg_124:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey, can you believe this?
[tab]The restaurant Clair De Lune started
[tab]selling armor.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’d like to check it out, 
[tab]but I don’t want to go alone. 
[tab]I would be so honored if you would join me.
[wait][clear][end]

msg_125:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Hey, can you believe this?
[tab]The restaurant called Clair De Lune
[tab]started selling weapons.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’d like to check it out, 
[tab]but I don’t feel like going alone. 
[tab]I would be so honored if you would come with me.
[wait][clear][end]

msg_126:
[color(yellow)]Flirtatious Man[color(white)]
[tab]You know the Sumaru Genie, right? 
[tab]They say that they introduced a 
[tab]new kind of fortune telling. Wanna check it out?
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]They might tell you just how great a match
[tab]we really are...
[wait][clear][end]

msg_127:
[color(yellow)]Flirtatious Man[color(white)]
[tab]You know the Sumaru Genie, right? 
[tab]They say that they introduced a
[tab]new kind of fortune telling. Wanna check it out?
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Then they’ll tell us that we were fated to
[tab]be together...
[wait][clear][end]

msg_128:
[color(yellow)]Flirtatious Man[color(white)]
[tab]You know that fortune teller, Sumaru Genie?
[tab]They used to be known for always being wrong, 
[tab]but it seems to have improved.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I heard their fortunes have gotten very accurate, 
[tab]using Wang Long. Maybe we should see what 
[tab]our future holds...
[wait][clear][end]

msg_129:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The salon, Etheria, is offering a different
[tab]service, since there’s so much competition.
[tab]Maybe if I change, I’ll get more women.
[wait][clear][end]

msg_130:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Is it true that the clerk from Rosa Candida
[tab]was swallowed by a wave!? 
[tab]I’ll have to go nurse her back to health.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So, I’d like to ask you something. 
[tab]I can’t tell if the girl in that store is pretty or not. 
[tab]Does anybody know?
[wait][clear][end]

msg_131:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Huh? The wave that swallowed the Saleswoman
[tab]from Rosa Candida was a wave of fashion?
[tab]Oh, why didn’t she just tell me that?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]People always tell me that my style is
[tab]ahead of its time.
[tab][wait][clear][end]

msg_132:
[color(yellow)]Flirtatious Man[color(white)]
[tab]The sales clerk from Rosa Candida is
[tab]feeling under the weather?
[tab]I’m so worried...[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I tend to be pretty macho, but I’m still
[tab]sensitive to a woman in need...
[wait][clear][end]

msg_133:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Is it true that Rosa Candida started
[tab]selling armor?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I never expected armor would be fashionable.
[tab]Maybe I should bust out with a samurai look...
[wait][clear][end]

msg_134:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Do you know a bar called Parabellum?
[tab]It seems the owner there hired a bouncer.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]That’s how dangerous it is out there.
[tab]So... care to have your own personal bouncer?
[wait][clear][end]

msg_135:
[color(yellow)]Flirtatious Man[color(white)]
[tab]You know a bar called Parabellum?
[tab]Guess what! They’re selling weapons like crazy.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]So, when we walk in the city, we have to be careful. 
[tab]Of course, as long as I’m with you,
[tab]you’ll always be safe.
[wait][clear][end]

msg_136:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Do you know about the special CDs that
[tab]Giga Macho has?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]That new Mambo song really makes you feel
[tab]the Latin heat! This is top secret information,
[tab]I’m only telling you.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Huh?[delay(15)] You already heard?
[tab]So much for my top secret information...
[wait][clear][end]

msg_137:
[color(yellow)]Flirtatious Man[color(white)]
[tab]There’s a rumor that Giga Macho sells
[tab]black market CDs. If you’re going, 
[tab]can I come with you?
[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]They only sell them to people they know.
[tab]If you go with me, there won’t be any problems. 
[tab]What... do you say?
[wait][clear][end]

msg_138:
[color(yellow)]Flirtatious Man[color(white)]
[tab]It seems that Mu Continent is the hot place
[tab]to go nowadays. They’ve opened a casino.
[tab]Why don’t we go check it out?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’ll win a fortune at Poker and shower you with gifts. 
[tab]You’ll have no choice but to fall in love with me.
[wait][clear][end]

msg_139:
[color(yellow)]Flirtatious Man[color(white)]
[tab]It seems that Mu Continent is the hot place
[tab]to go nowadays. They’ve opened a casino.
[tab]Why don’t we go check it out?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’ll win a fortune at Blackjack and shower 
[tab]you with gifts. You’ll have no choice but
[tab]to fall in love with me.
[wait][clear][end]

msg_140:
[color(yellow)]Flirtatious Man[color(white)]
[tab]It seems that Mu Continent is the hot place
[tab]to go nowadays. They’ve opened a casino.
[tab]Why don’t we go check it out?[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’ll win a fortune at the Slot machines
[tab]and shower you with gifts. You’ll have no
[tab]choice but to fall in love with me.
[wait][clear][end]

msg_141:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Sidewalk sales have gotten popular, 
[tab]people like buying items there.
[tab]That Tony guy is kinda creepy...
[wait][clear][end]

msg_142:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Sidewalk sales have gotten popular, 
[tab]people like buying items there.
[tab]That Tony guy is kinda creepy...
[wait][clear][end]

msg_143:
[color(yellow)]Flirtatious Man[color(white)]
[tab]There’s this store called Toua Defense.
[tab]It’s a surplus store, they started selling armor.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]It’s so dangerous out there.
[tab]You need a big, strong man to keep an eye
[tab]on you, little lady...[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’m nice, and I’m 100% reliable.
[wait][clear][end]

msg_144:
[color(yellow)]Flirtatious Man[color(white)]
[tab]There’s this store called Toua Defense.
[tab]It’s a surplus store, they started selling weapons.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]It’s so dangerous out there.
[tab]You need a big, strong man to keep an eye
[tab]on you, little lady...[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I’m nice, and I’m 100% reliable.
[wait][clear][end]

msg_145:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Did you hear the owner of Shiraishi had all
[tab]of her dreams come true?
[tab]It’s all because of me.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]Go out with me, and all your dreams will come true. 
[tab]Everyone else knows of my powers, 
[tab]how about you?
[wait][clear][end]

msg_146:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard they search for people at Shiraishi.
[tab]Hell, people are always searching for
[tab]what I have to offer...[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]If I had a steady girlfriend, 
[tab]I wouldn’t have to worry though... 
[tab]So?[delay(15)] Do you feel lucky? I promise it’ll be great.
[wait][clear][end]

msg_147:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard Kaori was closed,
[tab]I wonder if it still is.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]See, I’m sensitive, so I need to heal my heart. 
[tab]Ms. Kaori may be a little old but
[tab]she’s still pretty hot. Heeheehee.
[wait][clear][end]

msg_148:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Kaori is already open? Out buying new
[tab]products, eh? I wonder if they found
[tab]anything that gets you women.
[wait][clear][end]

msg_149:
[color(yellow)]Flirtatious Man[color(white)]
[tab]Ms. Kaori has a cold, huh? 
[tab]I’ll have to love her back to health... 
[tab]hope I don’t catch her cold, though...
[wait][clear][end]

msg_150:
[color(yellow)]Flirtatious Man[color(white)]
[tab]I heard Time Castle will copy cards, 
[tab]so I asked them to copy a prepaid card, 
[tab]but they refused.[wait][clear][color(yellow)]Flirtatious Man[color(white)]
[tab]I thought I could make some money off it...
[tab]What a pisser...
[wait][clear][end]

msg_151:
[color(yellow)]Flirtatious Man[color(white)]
[tab]They’re selling Skill Cards at Time Castle.
[tab]I actually went and got one, so now I can
[tab]handle any kind of villain.
[wait][clear][end]

msg_152:
[color(yellow)]Biker[color(white)]
[tab]This area has gotten pretty scary, 
[tab]all the suspicious cars cruising around...
[tab]Something’s going to go down here, I know.
[wait][clear][end]

msg_153:
[color(yellow)]Biker[color(white)]
[tab]Recently I saw someone in a big black car
[tab]grabbing people off the street, must be
[tab]the people that turned into Jokers.[wait][clear][color(yellow)]Biker[color(white)]
[tab]I let the fuzz know about it, but they blew me off. 
[tab]They don’t give a damn... 
[wait][clear][end]

msg_154:
[color(yellow)]Biker[color(white)]
[tab]I guess a lot of people know about the
[tab]dude who has information on the incident.
[tab]But, it ain’t on TV, is it?[wait][clear][color(yellow)]Biker[color(white)]
[tab]Who finds out about that stuff?
[tab]I bet THAT person has even more
[tab]information.
[wait][clear][end]

msg_155:
[color(yellow)]Biker[color(white)]
[tab]I guess a lot of people know about the
[tab]broad who has information on the incident.
[tab]But, it ain’t on TV, is it?[wait][clear][color(yellow)]Biker[color(white)]
[tab]Who finds out about that stuff?
[tab]I bet THAT person has even more
[tab]information.
[wait][clear][end]

msg_156:
[color(yellow)]Biker[color(white)]
[tab]This curse thing had everyone all bent out 
[tab]of shape. But now, nothing surprises us... 
[wait][clear][end]

msg_157:
[color(yellow)]Biker[color(white)]
[tab]These seminars have attracted a bunch of freaks, 
[tab]all going around saying, "Let’s think positive!"
[wait][clear][end]

msg_158:
[color(yellow)]Biker[color(white)]
[tab]It’s been impossible to relax and think clearly... 
[tab]do you think they’re sending out 
[tab]brainwashing waves?
[wait][clear][end]

msg_159:
[color(yellow)]Biker[color(white)]
[tab]I heard there were ruins under the city.
[tab]Didn’t anyone catch on when they were
[tab]building the damned city?[wait][clear][color(yellow)]Biker[color(white)]
[tab]Or if they did, the New World Order covered it up...
[tab]Either way, this sucks...
[wait][clear][end]

msg_160:
[color(yellow)]Biker[color(white)]
[tab]These earthquakes foretell the coming of the end... 
[tab]No matter what they say, we can’t trust the police. 
[tab]Is this really the end?
[wait][clear][end]

msg_161:
[color(yellow)]Biker[color(white)]
[tab]Sumaru is floating, we have to prepare
[tab]ourselves for what’s to come...
[tab]I can’t believe we’re the only ones...
[wait][clear][end]

msg_162:
[color(yellow)]Biker[color(white)]
[tab]Some girl named Anna keeps telling me to
[tab]not give up, and to live up to my potential.[wait][clear][color(yellow)]Biker[color(white)]
[tab]At first I thought they were just pissing
[tab]their lives away, but they appreciate life
[tab]when they see it disappearing...
[wait][clear][end]

msg_163:
[color(yellow)]Biker[color(white)]
[tab]The inside of Club Zodiac is a maze.
[tab]But, that’s just what I heard.
[tab]That’s pretty crazy...
[wait][clear][end]

msg_164:
[color(yellow)]Biker[color(white)]
[tab]I’m usually not afraid of ghosts or monsters,
[tab]but from what everyone says about Kudan, I am. 
[tab]I’ll get on my bike and bail.
[wait][clear][end]

msg_165:
[color(yellow)]Biker[color(white)]
[tab]The Sumaru Genie’s fortune telling seems popular, 
[tab]but I don’t believe in that crap. 
[tab]So it doesn’t concern me.
[wait][clear][end]

msg_166:
[color(yellow)]Biker[color(white)]
[tab]I heard Rosa Candida deals in real armor,
[tab]so I went to check them out.[wait][clear][color(yellow)]Biker[color(white)]
[tab]They had lotsa different crap, 
[tab]but they didn’t have anything I could wear.
[tab]Hahaha.
[wait][clear][end]

msg_167:
[color(yellow)]Biker[color(white)]
[tab]Giga Macho is selling copies of that new Mambo CD.
[tab]They shoulda told me, since I’m a regular.
[wait][clear][end]

msg_168:
[color(yellow)]Biker[color(white)]
[tab]When I heard Giga Macho was selling
[tab]black market CDs, I was pissed off.[wait][clear][color(yellow)]Biker[color(white)]
[tab]Since I’m a regular, they shoulda treated
[tab]me like one.
[wait][clear][end]

msg_169:
[color(yellow)]Biker[color(white)]
[tab]Mu Continent became a casino. 
[tab]Here’s something you might want to know. 
[tab]If you’re going to play, pick the 7th Poker machine.
[wait][clear][end]

msg_170:
[color(yellow)]Biker[color(white)]
[tab]Mu Continent became a casino. 
[tab]Here’s something you might want to know. 
[tab]If you’re going to play, play Blackjack.
[wait][clear][end]

msg_171:
[color(yellow)]Biker[color(white)]
[tab]Mu Continent became a casino. 
[tab]Here’s something you might want to know. 
[tab]If you’re going to play, pick the 7th Slot Machine.
[wait][clear][end]

msg_172:
[color(yellow)]Biker[color(white)]
[tab]You know Tony, the crazy foreigner?
[tab]I heard he’s selling some cool shit.[wait][clear][color(yellow)]Biker[color(white)]
[tab]His stuff’s pretty popular, go check it out.
[tab]I’m always giving him a hard time.
[wait][clear][end]

msg_173:
[color(yellow)]Biker[color(white)]
[tab]You know Tony, the crazy foreigner?
[tab]I heard he’s selling some cool shit.[wait][clear][color(yellow)]Biker[color(white)]
[tab]His stuff’s pretty popular, go check it out.
[tab]I’m always giving him a hard time.
[wait][clear][end]

msg_174:
[color(yellow)]Biker[color(white)]
[tab]I heard that the selection at Toua Defense
[tab]has improved, so I’m thinking about
[tab]checking it out.[wait][clear][color(yellow)]Biker[color(white)]
[tab]It’s the military look...
[tab]It ain’t my style, but it’s kinda interesting.
[wait][clear][end]

msg_175:
[color(yellow)]Biker[color(white)]
[tab]They say that Toua Defense started handling
[tab]weapons, but they need to get some more armor.[wait][clear][color(yellow)]Biker[color(white)]
[tab]I kind of like the military look, 
[tab]so I wish they’d focus more on armor.
[tab]I’m not even going to use those weapons.
[wait][clear][end]

msg_176:
[color(yellow)]Biker[color(white)]
[tab]The other day, I saw a old lady on a 750
[tab]hauling some serious ass. 
[tab]It surprised the hell out of me.[wait][clear][color(yellow)]Biker[color(white)]
[tab]Blazing around at 100km/h in the middle of the day, 
[tab]it was pretty insane. She left me in her dust...
[wait][clear][end]

msg_177:
[color(yellow)]Biker[color(white)]
[tab]Man, I can’t believe it.[wait][clear][color(yellow)]Biker[color(white)]
[tab]I was cruising at night and got smoked
[tab]by an old man on a Harley.
[tab]He was so damned fast.[wait][clear][color(yellow)]Biker[color(white)]
[tab]That thing was going at least 200km/h.
[tab]That thing scared the shit out of me.
[wait][clear][end]

msg_178:
[color(yellow)]Katsuya[color(white)]
[tab]We shouldn’t just stand here.  
[tab]We should focus on finding the swindler. 
[tab]Let’s look somewhere else.
[wait][clear][end]

msg_179:
[color(yellow)]Ulala[color(white)]
[tab]Anna-chan is waiting at Club Zodiac right?
[tab]We should hurry.
[wait][clear][end]

msg_180:
[color(yellow)]Ulala[color(white)]
[tab]After we solve this, wanna box?
[tab]It’s pretty good exercise.
[tab]Well, later though.
[wait][clear][end]

msg_181:
[color(yellow)]Baofu[color(white)]
[tab]I’m worried about Serizawa.
[tab]Let’s hurry.
[wait][clear][end]

msg_182:
[color(yellow)]Ulala[color(white)]
[tab]There’s nothing here.
[tab]Let’s get going.
[wait][clear][end]

msg_183:
[color(yellow)]Katsuya[color(white)]
[tab]Pachinko Silver?[delay(15)]
[tab]Going at your own pace isn’t a bad thing,
[tab]but don’t you think this isn’t the time?
[wait][clear][end]

msg_184:
[color(yellow)]Ulala[color(white)]
[tab]Oh!
[tab]It’s Pachinko Silver!
[tab]Wanna play?[wait][clear][color(yellow)]Ulala[color(white)]
[tab]...Of course not.
[tab]Well, let’s come back after
[tab]we’re through with this.
[wait][clear][end]
