
msg_0:
[color(yellow)]Walking Woman[color(white)]
[tab]The more recent incidents with the Joker
[tab]have become more violent than before.
[tab]The killer must be a psychopath.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]There’s no good or bad in murder, 
[tab]but it’s been getting worse ever since 
[tab]the media got involved.
[wait][clear][end]

msg_1:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard the emblem of Seven Sisters High can
[tab]protect you from the Joker...[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Well, I pulled out my old uniform just in case... 
[tab]If it really works, then at least I’ll be safe. 
[tab]But I’m still worried...
[wait][clear][end]

msg_2:
[color(yellow)]Walking Woman[color(white)]
[tab]It’s strange that the Aerospace Museum would 
[tab]burn down. It was fairly new and it had the
[tab]latest fire equipment. [wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It wasn’t just any old fire, that’s for sure...
[tab] I have this really bad feeling...
[tab]I hope nothing like this happens again..
[wait][clear][end]

msg_3:
[color(yellow)]Walking Woman[color(white)]
[tab]The recent murders have really shaken some
[tab]people in this town. Some are even afraid
[tab]to leave their houses. [wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]What’s happening to this town? 
[tab]It used to be such a peaceful place. 
[tab]The Joker sure put a stop to that...
[wait][clear][end]

msg_4:
[color(yellow)]Walking Woman[color(white)]
[tab]I wonder if the authorities have any more
[tab]leads on the Joker... [wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Like it matters, anyway... Now that Wang Long 
[tab]fortune telling has proven to be more reliable.
[wait][clear][end]

msg_5:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard this from someone, but it seems that
[tab]people who’ve become a Joker are being
[tab]kidnapped. I wonder who’s doing it and why.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I haven’t become a Joker, 
[tab]but I bought myself a gun just in case. 
[tab]You should watch out too...
[wait][clear][end]

msg_6:
[color(yellow)]Walking Woman[color(white)]
[tab]Is it true that there is someone who holds
[tab]information to the incident? 
[tab]If it is true, I wonder if it will help solving it.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Either way it’s just a rumor, 
[tab]so it’ll take a while for it to clear up.
[wait][clear][end]

msg_7:
[color(yellow)]Walking Woman[color(white)]
[tab]Someone out there knew the secret behind
[tab]the Joker incident but apparently they
[tab]disappeared before they could say anything.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I was hoping for all of this to end soon.
[tab]We musn’t give up hope...
[wait][clear][end]

msg_8:
[color(yellow)]Walking Woman[color(white)]
[tab]Lately, something isn’t right when I wake
[tab]up in the morning. I have two sets of
[tab]memories from the day before.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I must be losing my mind...
[wait][clear][end]

msg_9:
[color(yellow)]Walking Woman[color(white)]
[tab]At least I’m not the only one who feels
[tab]confused...[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]My friends and family are suffering from
[tab]the same d五j二 vu. Could it be caused by stress?
[wait][clear][end]

msg_10:
[color(yellow)]Walking Woman[color(white)]
[tab]I can’t believe that everything that has
[tab]happened up to now was all part of the
[tab]New World Order’s plan.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It looks like the military is part of the
[tab]plan as well. Maybe we should ask for help
[tab]from the Americans.
[wait][clear][end]

msg_11:
[color(yellow)]Walking Woman[color(white)]
[tab]That wasn’t just any earthquake, was it?
[tab]It was too well timed. This place is going
[tab]to hell in a handbasket...
[wait][clear][end]

msg_12:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems they have finally found the ruins
[tab]called Torifune.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Is it really going to fly?
[tab]Maybe I should buy a parachute.
[wait][clear][end]

msg_13:
[color(yellow)]Walking Woman[color(white)]
[tab]We’re screwed, aren’t we? If we’re flying
[tab]in the air, no one can possibly come save us.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Either the world will end like this,
[tab]or we’ll get shot down by a missile.
[tab]Isn’t there anything we can do!?
[wait][clear][end]

msg_14:
[color(yellow)]Walking Woman[color(white)]
[tab]All of the TV stations stopped broadcasting. 
[tab]The last thing I saw happen
[tab]was a worldwide earthquake...[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]But we’re still alive, so it’s too soon to
[tab]give up hope!
[wait][clear][end]

msg_15:
[color(yellow)]Walking Woman[color(white)]
[tab]I’ve never been to the store called Zodiac,
[tab]but building it like a dungeon is something 
[tab]new to me.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I don’t feel like actually going, 
[tab]but it sounds like an interesting place to visit.
[wait][clear][end]

msg_16:
[color(yellow)]Walking Woman[color(white)]
[tab]People say that the revived owner of the
[tab]castle was a sorcerer.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]The legends say that he was killed by the
[tab]princess, Maihime Amano, which ended his
[tab]evil reign, but that couldn’t happen now.
[wait][clear][end]

msg_17:
[color(yellow)]Walking Woman[color(white)]
[tab]Tatsunoshin [suou] with the help of his lover
[tab]defeated the lord of Sumaru Castle. 
[tab]At that moment their fates were sealed.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]A sad end would soon await them after...
[tab]I always thought it was just a fairy tale,
[tab]but now it seems true.
[wait][clear][end]

msg_18:
[color(yellow)]Walking Woman[color(white)]
[tab]Some say that the revived owner of the
[tab]castle was a sorcerer.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Legend says he was killed by a samurai
[tab]named Tatsunoshin [suou], and everything
[tab]was alright, but that couldn’t happen now.
[wait][clear][end]

msg_19:
[color(yellow)]Walking Woman[color(white)]
[tab]Maihime Amano had a lover named
[tab]Tatsunoshin [suou], and together they
[tab]defeated the lord of the castle.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]But fate would not be so kind to them in the end. 
[tab]It seemed like just one of those
[tab]stories you hear, but now...
[wait][clear][end]

msg_20:
[color(yellow)]Walking Woman[color(white)]
[tab]Have you heard that Aoba Park’s flowers talk? 
[tab]I was this close to them, and I never realized. 
[tab]Maybe I should check them out.
[wait][clear][end]

msg_21:
[color(yellow)]Walking Woman[color(white)]
[tab]There’s a rumor about a legendary blacksmith, 
[tab]but for it to become true people have to 
[tab]believe in it.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I wish Sumaru city would go back to being a
[tab]peaceful city at least you wouldn’t have
[tab]to carry a weapon everywhere.
[wait][clear][end]

msg_22:
[color(yellow)]Walking Woman[color(white)]
[tab]I think we shouldn’t talk about Kudan very much. 
[tab]They say rumors just might come true,
[tab]and it could be too late.
[wait][clear][end]

msg_23:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems a Cursed Taxi appeared at Mu
[tab]Continent and caused a huge accident.
[tab]I think an exorcism is in order...
[wait][clear][end]

msg_24:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard there’s a 200km/h Fogey running
[tab]around at super speed at Giga Macho.
[tab]I wonder how he does it...[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I wish he would share some of that energy
[tab]with my grandfather.
[wait][clear][end]

msg_25:
[color(yellow)]Walking Woman[color(white)]
[tab]Why does that Blue Cape in Narumi always
[tab]show up on top of a boat?[delay(15)]
[tab]I thought it hung out at the school.
[wait][clear][end]

msg_26:
[color(yellow)]Walking Woman[color(white)]
[tab]Why does that Red Cape in Narumi always
[tab]show up on top of a boat?[delay(15)]
[tab]I thought it hung out at the school.
[wait][clear][end]

msg_27:
[color(yellow)]Walking Woman[color(white)]
[tab]Isn’t that dinosaur over at Mu Continent a robot? 
[tab]The robots these days are so life-like 
[tab]that you can’t tell nowadays.
[wait][clear][end]

msg_28:
[color(yellow)]Walking Woman[color(white)]
[tab]Did you know that there’s an old lady running 
[tab]around Yumezaki’s Giga Macho at 100km/h.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]She has to be on steroids or something.
[tab]That lady is going as fast as a car! 
[tab]The average person can walk about 5km/h.
[wait][clear][end]

msg_29:
[color(yellow)]Walking Woman[color(white)]
[tab]Since I heard Reiko Kashima appeared at 
[tab]Sumaru TV, I went out and researched it.
[tab]It would be dangerous to run into her.
[wait][clear][end]

msg_30:
[color(yellow)]Walking Woman[color(white)]
[tab]So a Tsuchinoko really does exist.
[tab]Some kid asked me if they did and I told
[tab]him it was a lie. I should apologize.
[wait][clear][end]

msg_31:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems Kasugayama High is in a panic
[tab]since Teke Teke appeared. It’s not surprising
[tab]as they’ve always had problems like this.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]There must be something wrong with their
[tab]educational system.
[wait][clear][end]

msg_32:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems you can win cards with strange
[tab]powers from Fantasy World.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I thought it was just a good luck charm,
[tab]but it seems to have real power. 
[tab]I wonder what it is.
[wait][clear][end]

msg_33:
[color(yellow)]Walking Woman[color(white)]
[tab]It’s well known that you can win some
[tab]pretty cool items from Fantasy World.
[tab]Why don’t you try sending in for one?
[wait][clear][end]

msg_34:
[color(yellow)]Walking Woman[color(white)]
[tab]The accessories that can be won from
[tab]Fantasy World are pretty popular.
[tab]I wonder what kind they are.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]If it has a design of a dolphin or a fairy, 
[tab]I might want it.
[wait][clear][end]

msg_35:
[color(yellow)]Walking Woman[color(white)]
[tab]Armor is a pretty popular prize from
[tab]Fantasy World. But are they real? 
[tab]Who would just give away stuff like that?[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]They have to be real, right? 
[tab]Nobody would be interested if they were fake 
[tab]or just accessories.
[wait][clear][end]

msg_36:
[color(yellow)]Walking Woman[color(white)]
[tab]Weapons are a pretty popular prize that
[tab]Fantasy World gives away. 
[tab]Are they really allowed to do that?[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It wouldn’t be funny if the police catches
[tab]you as soon as you win it. 
[tab]I don’t think I would send in for it.
[wait][clear][end]

msg_37:
[color(yellow)]Walking Woman[color(white)]
[tab]They say you can win Skill Cards
[tab]from the Miracle.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Are they used for playing tricks on people? 
[tab]That’s what it seems like.
[wait][clear][end]

msg_38:
[color(yellow)]Walking Woman[color(white)]
[tab]They say you can win strange items
[tab]from the magazine called Miracle.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I’m not sure what they are but they’re
[tab]probably for playing tricks.
[wait][clear][end]

msg_39:
[color(yellow)]Walking Woman[color(white)]
[tab]What kind of magazine is Battle Master?
[tab]It is giving away some accessories but
[tab]the name and the image don’t match.
[wait][clear][end]

msg_40:
[color(yellow)]Walking Woman[color(white)]
[tab]I hear you can win armor from a magazine
[tab]called Battle Master. It’s expensive to buy,
[tab]so I might try entering the contest.
[wait][clear][end]

msg_41:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems that Battle Master is giving away
[tab]weapons as prizes. I think they’re just
[tab]taking advantage of the situation.
[wait][clear][end]

msg_42:
[color(yellow)]Walking Woman[color(white)]
[tab]That rich person who’s always at the Ebony
[tab]in Hotel Pleiades, seems to be a map collector.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I think he collects some weird things,
[tab]but if it’s making him money, 
[tab]I might start collecting my own maps.
[wait][clear][end]

msg_43:
[color(yellow)]Walking Woman[color(white)]
[tab]That rich person at the Satomi Tadashi
[tab]seems to be a map collector.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]People say that he’s pretty odd, 
[tab]but I admire that he doesn’t let 
[tab]this situation affect him.
[wait][clear][end]

msg_44:
[color(yellow)]Walking Woman[color(white)]
[tab]The city is floating, but didn’t Narumi
[tab]stay on the ground?[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It seems the jewel shop in the hotel
[tab]just moved straight to Kounan and reopened
[tab]for business.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]You’ve got some guts, but am I the only
[tab]one who thinks this shouldn’t be the time
[tab]to be doing something like that?
[wait][clear][end]

msg_45:
[color(yellow)]Walking Woman[color(white)]
[tab]The owner of the jewelry shop at the hotel
[tab]claims that there’s nothing he can’t make.
[tab][wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I never expected him to start making
[tab]weapons and armor. I wonder if he had
[tab]too much to drink.
[wait][clear][end]

msg_46:
[color(yellow)]Walking Woman[color(white)]
[tab]The owner of the jewelry shop at the hotel
[tab]claims that there’s nothing he can’t make.
[tab][wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I never expected for him to start making
[tab]weapons and armor. Maybe he just snapped
[tab]when the city started floating.
[wait][clear][end]

msg_47:
[color(yellow)]Walking Woman[color(white)]
[tab]The Clair De Lune restarted business
[tab]down there at Aoba Way!
[tab]I’m so surprised.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It must have taken a lot of manpower to
[tab]move the entire store from where it was.
[wait][clear][end]

msg_48:
[color(yellow)]Walking Woman[color(white)]
[tab]The Clair De Lune is starting to sell
[tab]armor now.
[tab][wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]That’s nice of them, but it also reminds
[tab]us of how dangerous the world has become now.
[wait][clear][end]

msg_49:
[color(yellow)]Walking Woman[color(white)]
[tab]The Clair De Lune is starting to sell
[tab]weapons now.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]That’s nice of them, but it also reminds
[tab]us of how dangerous the world has become now.
[wait][clear][end]

msg_50:
[color(yellow)]Walking Woman[color(white)]
[tab]The Sumaru Genie’s readings are more accurate. 
[tab]The range of her affinity reading has expanded.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It’s very accurate, so I recommend it.
[tab]Why don’t you go in for a reading?
[wait][clear][end]

msg_51:
[color(yellow)]Walking Woman[color(white)]
[tab]The Sumaru Genie has started to do Affinity 
[tab]Readings. Affinity Readings are the basics of
[tab]fortune telling!
[wait][clear][end]

msg_52:
[color(yellow)]Walking Woman[color(white)]
[tab]Do you know about the Sumaru Genie?
[tab]I’ve gone there before, 
[tab]but that place is horrible.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]They say all these bad things and they’re
[tab]never accurate. But when they switched to
[tab]Wang Long, they got very accurate.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]That’s why I plan on going there sometime.
[tab]I actually worry about stuff like that.
[wait][clear][end]

msg_53:
[color(yellow)]Walking Woman[color(white)]
[tab]The Etheria has it rough... 
[tab]They say they changed their services 
[tab]to distinguish it from other companies.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I’m kind of interested in going there, 
[tab]but I can’t afford it... 
[tab]I think housewives deserve to get paid.
[wait][clear][end]

msg_54:
[color(yellow)]Walking Woman[color(white)]
[tab]The sales lady of Rosa Candida drowned in
[tab]a wave of fashion right? I’m so envious.[delay(15)]
[tab]I wish I could go to Paris.
[wait][clear][end]

msg_55:
[color(yellow)]Walking Woman[color(white)]
[tab]A-ha! [delay(15)]It wasn’t a wave of fashion but
[tab]a real wave after all. I was confused
[tab]between Paris and Bali. I’m so embarrassed!
[tab][wait][clear][end]

msg_56:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard the sales lady of Rosa Candida was
[tab]swallowed by a wave in Paris!!
[tab]The ocean IS scary!
[wait][clear][end]

msg_57:
[color(yellow)]Walking Woman[color(white)]
[tab]Even Rosa Candida started selling armor
[tab]because it’s getting so dangerous...
[tab]What’s going to happen now?
[wait][clear][end]

msg_58:
[color(yellow)]Walking Woman[color(white)]
[tab]The bar called Parabellum seems to have
[tab]hired a bodyguard. I guess it’s getting
[tab]too dangerous even for them.
[wait][clear][end]

msg_59:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard that the bar, Parabellum, is actually
[tab]a weapon shop! They sell some pretty
[tab]dangerous stuff, but people buy it anyway.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]It’s probably for self-defense, 
[tab]but I’m scared to use things like that. 
[tab]It just doesn’t feel right.
[wait][clear][end]

msg_60:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems Giga Macho’s hidden CD is a Mambo one. 
[tab]I’m not too interested in Mambo though.
[wait][clear][end]

msg_61:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems Giga Macho has a Rock CD that
[tab]that they don’t sell normally.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]They don’t put them on the racks and only
[tab]people who special order it can buy it.
[tab]Something to do with copyrights, huh?
[wait][clear][end]

msg_62:
[color(yellow)]Walking Woman[color(white)]
[tab]Is it true that Mu Continent has a Casino?[delay(15)]
[tab]I never thought an arcade would become a casino.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I heard Poker is a good game if you want
[tab]to win money. But, those games are
[tab]rigged so that the odds are against you.
[wait][clear][end]

msg_63:
[color(yellow)]Walking Woman[color(white)]
[tab]Is it true that Mu Continent has a Casino?[delay(15)]
[tab]I never thought an arcade would become a casino.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I heard Blackjack is a good game if you
[tab]want to win money. But, those games are
[tab]rigged so that the odds are against you.
[wait][clear][end]

msg_64:
[color(yellow)]Walking Woman[color(white)]
[tab]Is it true that Mu Continent has a Casino?[delay(15)]
[tab]I never thought an arcade would become a casino.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I heard the Slots are pretty good if you
[tab]want to win money. But, those games are
[tab]rigged so that the odds are against you.
[wait][clear][end]

msg_65:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems that Tony’s Shop has started
[tab]selling accessories with strange powers.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]They sometimes sell some cute ones
[tab]there so, I kind of like it there.
[tab]I think I’ll go shop there soon.
[wait][clear][end]

msg_66:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard that Tony’s Shop started selling
[tab]self-defense items. I think he’s selling
[tab]unique Magatamas...
[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]I don’t know if it really has an effect or not, 
[tab]but it’s sure strange that he would
[tab]be selling such Magatamas.
[wait][clear][end]

msg_67:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems that they’ve upgraded the items
[tab]sold at Toua Defense big time.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Items like that don’t become popular just because... 
[tab]The world is becoming a dangerous place...
[wait][clear][end]

msg_68:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems Toua Defense has expanded their
[tab]stock from just armor, to weapons as well.[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Items like that don’t become popular just because... 
[tab]The world is becoming a dangerous place...
[wait][clear][end]

msg_69:
[color(yellow)]Walking Woman[color(white)]
[tab]The landlady of Shiraishi has realized her dreams. 
[tab]This is great since it’s been
[tab]nothing but bad news lately.
[wait][clear][end]

msg_70:
[color(yellow)]Walking Woman[color(white)]
[tab]It seems Shiraishi has been doing man searching. 
[tab]But it doesn’t sound very profitable...[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Maybe that’s why the last store went out
[tab]of business.
[wait][clear][end]

msg_71:
[color(yellow)]Walking Woman[color(white)]
[tab]Is Kaori still closed? That’s no good...
[tab]I was just thinking about going out to buy
[tab]something.
[wait][clear][end]

msg_72:
[color(yellow)]Walking Woman[color(white)]
[tab]So the reason that Kaori closed, 
[tab]was to purchase new items. 
[tab]I should hurry up and get myself over there.
[wait][clear][end]

msg_73:
[color(yellow)]Walking Woman[color(white)]
[tab]Oh my... Miss Kaori has a cold?
[tab]That’s too bad, I’ll have to wait a while
[tab]for my aromatherapy.
[wait][clear][end]

msg_74:
[color(yellow)]Walking Woman[color(white)]
[tab]They say they’ll fix cards at the Time Castle, 
[tab]but how does it work? I just don’t get it.
[wait][clear][end]

msg_75:
[color(yellow)]Walking Woman[color(white)]
[tab]I heard they sell Skill Cards at the Time Castle... 
[tab]Isn’t that strange?[wait][clear][color(yellow)]Walking Woman[color(white)]
[tab]Do spells really exist? It’s kind of odd
[tab]to think so in this day and age.
[wait][clear][end]

msg_76:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Another Joker incident...
[tab]It sure is an unpleasant world.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Compared to what happened earlier, 
[tab]the incidents have become more complex and cruel. 
[tab]It’s as if the killer is changing.
[wait][clear][end]

msg_77:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I didn’t know that Sevens’ emblem had
[tab]an anti-Joker effect.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]This sounds a little strange, 
[tab]but you can’t take these rumors lightly. 
[tab]I might as well go ahead and get one myself.
[wait][clear][end]

msg_78:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Do you know about the serial murders 
[tab]that took place some 10 years ago? 
[tab]They never did catch the killer...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]This time I hope they catch him and put
[tab]him away for a long time.
[wait][clear][end]

msg_79:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard the Aerospace Museum burned down.
[tab]The children loved that place...
[tab]That’s too bad.
[wait][clear][end]

msg_80:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Did you see that show on Wang Long Chizuru? 
[tab]I never thought a world full of
[tab]horror would come true.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s hard to believe that when something
[tab]this strange happens so frequently, 
[tab]you can’t say it’s not true.
[wait][clear][end]

msg_81:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Lately, there have been plenty of
[tab]unbelievable things going on. 
[tab]We just can’t rely on the police alone.
[wait][clear][end]

msg_82:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I, too, have finally seen a Joker. 
[tab]But, then it was abducted by some men in black.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I can’t just stand around anymore.[delay(15)]
[tab]More stores that sell weapons have opened
[tab]up for business. I should go buy some...
[wait][clear][end]

msg_83:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]This sounds sudden, but it looks like the
[tab]Joker incident may have been solved. 
[tab]It seems someone had important information.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The whole city is talking about it.
[tab]I hope it will turn out for the better.
[wait][clear][end]

msg_84:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Y-you are from the Nanjo Conglomerate...
[tab]We appreciate your business.
[wait][clear][end]

msg_85:
[color(yellow)]Nanjo[color(white)]
[tab]Excuse me, but...[delay(15)]
[tab]Have we met?
[wait][clear][end]

msg_86:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I’m just a manager of a small section...
[tab]But about 80% of our products are handled
[tab]by the Nanjo Conglomerate.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I’ve always wanted to meet you...
[tab]Here is my business card...
[wait][clear][end]

msg_87:
[color(yellow)]Nanjo[color(white)]
[tab]East Japan Spinning... oh, you’re from the fiber plant.[delay(10)] 
[tab]My subordinates say that it’s a fine company. 
[tab]It’s a pleasure...
[wait][clear][end]

msg_88:
[color(yellow)]Ulala[color(white)]
[tab]Damn... I feel like we’re on a
[tab]totally different wavelength on
[tab]this conversation.
[wait][clear][end]

msg_89:
[color(yellow)]Nanjo[color(white)]
[tab]This is the duty of a Nanjo family member. 
[tab]Shall we get going?
[wait][clear][end]

msg_90:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Ah, Nanjo-san.[delay(15)]
[tab]It has really been a pleasure.
[wait][clear][end]

msg_91:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The rumored person finally appeared,
[tab]but disappeared just as quickly...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I was hoping it would solve this mystery,
[tab]but I guess I was hoping for too much.
[wait][clear][end]

msg_92:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Lately the seminar seems to be very popular.
[tab]Everyone seems to have been influenced
[tab]even though I have no interest.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Every human has a darker side to them.
[tab]I think it would be best to balance these sides. 
[tab]Heck, what do I know?
[wait][clear][end]

msg_93:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Ah, Nanjo-san.
[tab]We seem to meet quite often.
[tab]Eh? Did anything strange happen?
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The topic about the seminar seems to be popular. 
[tab]Sasaki the music producer said he will open 
[tab]a seminar in Smile Hirasaka.
[wait][clear][end]

msg_94:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Lately my memory is getting worse. 
[tab]I must be working too hard...
[wait][clear][end]

msg_95:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Since they show it on the news, 
[tab]I assume it’s real, but it is still
[tab]hard to believe.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems that the New World Order is
[tab]responsible for everything. 
[tab]Are they planning to destroy the world?
[wait][clear][end]

msg_96:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Ah, Nanjo-san.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard the news that the New World
[tab]Order plans to destroy the world.
[tab]Could this be true?
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Do you know anything about it?
[wait][clear][end]

msg_97:
[color(yellow)]Nanjo[color(white)]
[tab]No... nothing...
[wait][clear][end]

msg_98:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]N-no, it’s not that I thought
[tab]you were involved or anything.
[tab]I’m just worried.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I just thought someone in your position
[tab]may be aware of some of these things...
[tab]My apologies.
[wait][clear][end]

msg_99:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]This is a catastrophe. If it’s come to this, 
[tab]there is no doubt that the world is headed 
[tab]for destruction.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Is there anything that we can do...?
[wait][clear][end]

msg_100:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Did you hear about the ruins found
[tab]on the subway construction site?
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]This is basically what’s on the news nowadays. 
[tab]Not that talking about it will solve anything...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]At this rate, the world is completely 
[tab]under the New World Order’s control. 
[tab]Is there anything that can be done about it?
[wait][clear][end]

msg_101:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s strange that something like this had
[tab]to become a reality... Does this mean that
[tab]everything was all for nothing?
[wait][clear][end]

msg_102:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]This came up totally unexpected. 
[tab]I can’t do anything about it...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I’ve come to a conclusion of not giving up. 
[tab]There’s not much I can do, 
[tab]but there is no point in being pessimistic.
[wait][clear][end]

msg_103:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems Club Zodiac is altering their
[tab]store into a maze.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s an original idea, 
[tab]but won’t the customers get lost?
[wait][clear][end]

msg_104:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]That is quite a creepy castle. 
[tab]I’ve heard that long ago, the owner, 
[tab]Kiyotada Sumaru, sacrificed many civilians.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Finally he was defeated by Maihime Amano,
[tab]but it seems that his vengeful spirit
[tab]will lead the world to an end.
[wait][clear][end]

msg_105:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Long ago, Tatsunoshin [suou] was able
[tab]to defeat Kiyotada Sumaru with the help
[tab]of his lover, Maihime Amano.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It wasn’t easy defeating him before,
[tab]and I’m sure it won’t be easy this
[tab]time around.
[wait][clear][end]

msg_106:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]That is quite a creepy castle. 
[tab]I’ve heard that long ago, the owner, 
[tab]Kiyotada Sumaru, sacrificed many civilians.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]He was finally defeated by Tatsunoshin [suou],
[tab]but it seems that his vengeful spirit
[tab]will lead the world to an end.
[wait][clear][end]

msg_107:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Long ago, Maihime Amano was able to
[tab]defeat Kiyotada Sumaru with the help of her
[tab]lover, Tatsunoshin [suou].
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It wasn’t easy defeating him before,
[tab]and I’m sure it won’t be easy this
[tab]time around.
[wait][clear][end]

msg_108:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Just recently, I heard the flowers of the
[tab]Aoba Park can speak. I doubt that this was
[tab]true, but apparently I was wrong.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Even the famous botanist Siebold would
[tab]have a ball speaking to plants.
[wait][clear][end]

msg_109:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard there is a legendary blacksmith.
[tab]Is it true that this person made swords?
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I don’t plan to use them, but I do enjoy
[tab]looking at Katanas and swords.
[wait][clear][end]

msg_110:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]N-No, I don’t know anything
[tab]about the Kudan...
[wait][clear][end]

msg_111:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Do you know the rumor about 200km/h Fogey?
[tab]They say this Fogey’s even faster than the
[tab]100km/h Hag?
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The Fogey appears around Giga Macho.
[tab]However, that 200km/h part seems unreal.
[wait][clear][end]

msg_112:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Do you know about the rumor of the Cursed Taxi? 
[tab]It seems taxi drivers are having a hard time 
[tab]getting customers because of it.
[wait][clear][end]

msg_113:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard a rumor about a caped specter
[tab]appearing but I’ve never heard about a
[tab]Blue Cape. A Red Cape, yes...
[wait][clear][end]

msg_114:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard the Red Cape has appeared...
[tab]If that is the Red Cape I know, 
[tab]it will abduct pretty girls one by one.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It often appears at dance parties so
[tab]you may want to be careful.
[tab]Although, this was 13 years ago...
[wait][clear][end]

msg_115:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard of Mussie appearing in the Mu
[tab]Continent![delay(15)] But now it’s a dinosaur?
[tab]It’s probably just another attraction...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Of course, it is a time that many
[tab]unbelievable things are happening,
[tab]so it could be real...
[wait][clear][end]

msg_116:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard a monster called 100km/h Hag
[tab]appeared at Giga Macho running around
[tab]at super speed.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I shop at Giga Macho often, 
[tab]so I’m kind of scared. 
[tab]I wish somebody would do something about it.
[wait][clear][end]

msg_117:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard Reiko Kashima haunted the Sumaru
[tab]TV station. I wish it would go away, 
[tab]but it’d be a problem if it came to a house...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I’m kind of worried.
[wait][clear][end]

msg_118:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Did you hear about the Tsuchinoko being spotted? 
[tab]I heard stories when I was a kid,
[tab]but nobody’s managed to catch it...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Since they already know that
[tab]it hides under a manhole, 
[tab]I wish they would catch it soon.
[wait][clear][end]

msg_119:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]There’s an air raid shelter at Kasu High.
[tab]And people are in chaos because of Teke Teke.
[tab]I think it actually comes out of there.
[wait][clear][end]

msg_120:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It looks like a magazine called Fantasy
[tab]World is going to get popular.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s pretty famous right now since the
[tab]readers can win mysterious cards.
[wait][clear][end]

msg_121:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It looks like a magazine called Fantasy
[tab]World is going to get popular.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s pretty famous right now since the
[tab]readers can win special items.
[wait][clear][end]

msg_122:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It looks like a magazine called Fantasy
[tab]World is going to get popular.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s pretty famous right now since the
[tab]readers can win nice accessories.
[wait][clear][end]

msg_123:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It looks like a magazine called Fantasy
[tab]World is going to get popular.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s pretty famous right now since the
[tab]readers can win real armor.
[wait][clear][end]

msg_124:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It looks like a magazine called Fantasy
[tab]World is going to get popular.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s pretty famous right now since the
[tab]readers can win real weapons.
[wait][clear][end]

msg_125:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Is all this prize-giveaway madness from
[tab]magazines like Miracle becoming a trend?
[tab]Because of my job, I’m interested.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Oh, I’m in the fashion industry. 
[tab]If they’re just after the mysterious cards, 
[tab]then it wouldn’t concern me.
[wait][clear][end]

msg_126:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Is all this prize-giveaway madness from
[tab]magazines like Miracle becoming a trend?
[tab]Because of my job, I’m interested.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Oh, I’m in the fashion industry. 
[tab]If they’re just after the strange items, 
[tab]then it wouldn’t concern me.
[wait][clear][end]

msg_127:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Until now, Monthly Battle Master was just
[tab]a small magazine. Its subscriptions have
[tab]increased because of the recent outbreaks.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems the accessories they are giving away 
[tab]as prizes are very popular.
[wait][clear][end]

msg_128:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Until now, Monthly Battle Master was just
[tab]a small magazine. Its subscriptions have
[tab]increased because of the recent outbreaks.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems the armor they are giving away
[tab]as prizes are very popular.
[wait][clear][end]

msg_129:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Until now, Monthly Battle Master was just
[tab]a small magazine. Its subscriptions have
[tab]increased because of the recent outbreaks.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems the weapons they are giving away
[tab]as prizes are very popular.
[wait][clear][end]

msg_130:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]There’s a millionaire at the Ebony in
[tab]Hotel Pleiades who collects maps.
[tab]The hobby of a rich person, I suppose.
[wait][clear][end]

msg_131:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems there’s a millonaire at Satomi
[tab]Tadashi whose hobby is collecting maps.
[tab]He’s rather obsessed about it.
[wait][clear][end]

msg_132:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The jeweler of Padparacha sure works hard! 
[tab]During this chaos, he moved the store to Kounan...
[wait][clear][end]

msg_133:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Business owners have expanded their line of retail. 
[tab]Now, the Padparacha jewelry store are now 
[tab]making weapons and armor.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I think I should have gotten into the
[tab]retail business as well...
[wait][clear][end]

msg_134:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]That waiter is no ordinary person! 
[tab]During the turmoil here in the city, 
[tab]he moved the entire store to Aoba.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]To be able to eat food from Clair De Lune
[tab]at a time like this is indeed a blessing.
[tab]We need to keep our energy up.
[wait][clear][end]

msg_135:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard that they sell armor at Clair De Lune. 
[tab]I was surpised to hear that since I
[tab]frequent that place very often.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]That’s the first time I’ve heard of that.
[tab]I guess there are many surprises around
[tab]this area that I still don’t know about.
[wait][clear][end]

msg_136:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard that they sell weapons at Clair De Lune. 
[tab]I was surpised to hear that since I
[tab]frequent that place very often.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]That’s the first time I’ve heard of that.
[tab]I guess there are many surprises around
[tab]this area that I still don’t know about.
[wait][clear][end]

msg_137:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Sumaru Genie’s Affinity Readings seem to
[tab]have broadened its range. 
[tab]Maybe I’ll go if it can tell me about my work.
[wait][clear][end]

msg_138:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Sumaru Genie’s fortune telling seems
[tab]to be very accurate. It’s very popular.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It has Affinity Reading, right? I wonder
[tab]if it can tell me if certain businesses
[tab]are compatible with each other...
[wait][clear][end]

msg_139:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Wang Long fortune telling
[tab]really is amazing.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Sumaru Genie is known for being inaccurate, 
[tab]but they say that all changed
[tab]when they switched to Wang Long.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Maybe I might find out what sort of
[tab]clothing might become popular in the
[tab]future.
[wait][clear][end]

msg_140:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The Etheria salon changed their service
[tab]to distinguish themselves from the competition. 
[tab]I wonder how they did it...
[wait][clear][end]

msg_141:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard the Rosa Candida’s Saleswoman was
[tab]swallowed by a wave in Paris. 
[tab]If it was in Paris, I’m sure they meant fashion...
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It’s somewhat believable! 
[tab]It might’ve been a stunt to show off 
[tab]the new products she bought from Paris!
[wait][clear][end]

msg_142:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]So that’s what it was... How shocking...
[tab]A pro must know everything about
[tab]international fashion.
[wait][clear][end]

msg_143:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Eh... was swallowed by a wave in Bali?[delay(15)]
[tab]I work with clothing so I assumed it was
[tab]about fashion...
[wait][clear][end]

msg_144:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard that Rosa Candida’s Saleswoman was
[tab]swallowed by a wave in Bali.
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]They say a vacation will relieve us of stress, 
[tab]but if we aren’t more careful,
[tab]we’ll end up in an accident.
[wait][clear][end]

msg_145:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]At a boutique called Rosa Candida, 
[tab]they started dealing with armor. 
[tab]Would you be interested?
[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I mean, if armor is going to become popular, 
[tab]it might affect my work.
[wait][clear][end]

msg_146:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The barkeep at the Parabellum just hired a bouncer. 
[tab]He’s kind of intimidating so I don’t go over there 
[tab]very often.
[wait][clear][end]

msg_147:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]The bar called Parabellum seems to have
[tab]started dealing weapons. 
[tab]Well, with a name like that, what do you expect?
[wait][clear][end]

msg_148:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Giga Macho is secretly selling a Mambo CD. 
[tab]I don’t think it’s good business in the long run.
[wait][clear][end]

msg_149:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Giga Macho is secretly selling a rock CD claiming 
[tab]that it’s a special CD. 
[tab]I wonder why they can’t make it widely available.
[wait][clear][end]

msg_150:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Mu Continent just opened up a casino! 
[tab]Now, that’s what I’m talking about! 
[tab]I should go pay them a visit![wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I hear Poker is an especially good
[tab]game to win money at. How about it?
[tab]Care to check it out?
[wait][clear][end]

msg_151:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Mu Continent just opened up a casino! 
[tab]Now, that’s what I’m talking about! 
[tab]I should go pay them a visit![wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I hear Blackjack is an especially good
[tab]game to win money at. How about it?
[tab]Care to check it out?
[wait][clear][end]

msg_152:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Mu Continent just opened up a casino! 
[tab]Now, that’s what I’m talking about! 
[tab]I should go pay them a visit![wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]You don’t need to know any rules to play the Slots. 
[tab]They’re pretty much idiot proof. 
[tab]Care to check it out?
[wait][clear][end]

msg_153:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Do you know about Tony’s Shop? 
[tab]It’s famous for selling mysterious accessories,
[tab]but I don’t know where to find it.
[wait][clear][end]

msg_154:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Do you know about Tony’s Shop? 
[tab]It’s famous for selling self-defense items, 
[tab]but I don’t know where to find it.
[wait][clear][end]

msg_155:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Toua Defense has started dealing with more armor. 
[tab]Are they trying to get people into the military look?
[wait][clear][end]

msg_156:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Even though Toua Defense has started selling
[tab]weapons, they mainly specialize in armor.
[wait][clear][end]

msg_157:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard the owner of Shiraishi realized her dream. 
[tab]I envy her... 
[tab]Not very many people see their dreams come true.
[wait][clear][end]

msg_158:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems Shiraishi has a man search 
[tab]service available, but I’m not too excited about it.
[wait][clear][end]

msg_159:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I was surprised to hear that Kaori was closed. 
[tab]I just went there not too long ago.
[tab]I wonder what happened.
[wait][clear][end]

msg_160:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Oh I see.
[tab]I’m glad the store was closed only
[tab]temporarily for business purposes.
[wait][clear][end]

msg_161:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Oh, so she had a cold... 
[tab]I shouldn’t have said that to her the other day... 
[tab]Now, I feel bad...
[wait][clear][end]

msg_162:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I heard that Kaori has imported new products
[tab]from overseas and it seems to be doing
[tab]very well for her.
[wait][clear][end]

msg_163:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Ms. Kaori seems to have caught a cold.
[tab]She was trying to be herself the other day
[tab]but I could tell she was pushing herself.[wait][clear][color(yellow)]Middle-Aged Businessman[color(white)]
[tab]Anyway, I hope she feels better soon.
[wait][clear][end]

msg_164:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]I hear they’ll copy Skill Cards for you at
[tab]the Time Castle. That’s good news for
[tab]people who are into that sort of thing.
[wait][clear][end]

msg_165:
[color(yellow)]Middle-Aged Businessman[color(white)]
[tab]It seems that Time Castle is selling Skill Cards. 
[tab]Those things look like something
[tab]the kiddies would enjoy.
[wait][clear][end]

msg_166:
[color(yellow)]Young Man[color(white)]
[tab]I just moved here, but Aoba sure is a
[tab]great place.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]It’s very peaceful and relaxing. 
[tab]Also, I’ll be well informed by having Kismet
[tab]Publications and Sumaru TV around.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]There’s even an outdoor music bowl,
[tab] so I’ll see some celebrities when I go shopping.
[tab]Now, only if the rent was cheaper...
[wait][clear][end]

msg_167:
[color(yellow)]Young Man[color(white)]
[tab]I don’t know why, but it seems that the
[tab]Joker is repelled by Seven Sisters High’s emblem.
[tab]A lot of people are talking about it.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]The media is falling behind as the number
[tab]of incidents increase. Pay attention to rumors! 
[tab]They can be more informative!
[wait][clear][end]

msg_168:
[color(yellow)]Young Man[color(white)]
[tab]Did you see the news? They say that the
[tab]Aerospace Museum was burned to the ground. 
[tab]I wonder who would do such a thing.
[wait][clear][end]

msg_169:
[color(yellow)]Young Man[color(white)]
[tab]When things get this bad, 
[tab]we can’t rely on the cops anymore...[wait][clear][color(yellow)]Young Man[color(white)]
[tab]They should bust out the military to take
[tab]care of this Joker thing.
[wait][clear][end]

msg_170:
[color(yellow)]Young Man[color(white)]
[tab]I heard the cops aren’t doing anything to
[tab]solve this case. I wonder if it’s true.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]There are conspiracies going on everywhere... 
[tab]It’s so bad that you can’t even trust  
[tab]the cops anymore...
[wait][clear][end]

msg_171:
[color(yellow)]Young Man[color(white)]
[tab]A suspicious looking black car drove by a 
[tab]few times. I wonder if those guys are the
[tab]ones hunting for Jokers?[wait][clear][color(yellow)]Young Man[color(white)]
[tab]If they are, I’m sure they’re up to no good. 
[tab]People who go cruise around in
[tab]black cars are bad news...
[wait][clear][end]

msg_172:
[color(yellow)]Young Man[color(white)]
[tab]Everyone’s been talking about the person
[tab]withholding the info about the incident.
[tab]All we know now, is that it’s a man.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]There must be some kind of reward to bring
[tab]this guy in. I wonder what he looks like...
[wait][clear][end]

msg_173:
[color(yellow)]Young Man[color(white)]
[tab]Everyone’s been talking about the person
[tab]withholding the info about the incident.
[tab]All we know now, is that it’s a woman.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]There must be some kind of reward to bring
[tab]this girl in. I wonder what she looks like...
[wait][clear][end]

msg_174:
[color(yellow)]Young Man[color(white)]
[tab]It seems that a very important person
[tab]ended up escaping. I should’ve gotten a look.
[wait][clear][end]

msg_175:
[color(yellow)]Young Man[color(white)]
[tab]Come on, let’s think positive! 
[tab]Everybody should attend the seminar! 
[tab]Your life will surely change because of it!
[wait][clear][end]

msg_176:
[color(yellow)]Young Man[color(white)]
[tab]The New World Order will purify us all!
[tab]You may not accept them at first, 
[tab]but what they do, is done in the name of love!
[wait][clear][end]

msg_177:
[color(yellow)]Young Man[color(white)]
[tab]The Earthquake was a sign from the almighty! 
[tab]The world must be purified!
[wait][clear][end]

msg_178:
[color(yellow)]Young Man[color(white)]
[tab]Can’t you see!? This is the birth of a new world! 
[tab]Embrace it with all of your heart!
[wait][clear][end]

msg_179:
[color(yellow)]Young Man[color(white)]
[tab]The almighty has turned his back on us!
[tab]We must sacrifice more people to appease him![wait][clear][color(yellow)]Young Man[color(white)]
[tab]If we offer the unworthy people of this
[tab]city as a sacrifice, the pure will be saved!
[wait][clear][end]

msg_180:
[color(yellow)]Young Man[color(white)]
[tab]They remodeled the inside of Club Zodiac
[tab]to be a maze, but I didn’t even know about
[tab]it until now!
[wait][clear][end]

msg_181:
[color(yellow)]Young Man[color(white)]
[tab]Those flowers in Aoba Park can talk!
[tab]No joke! Why don’t you go talk to them yourself?
[wait][clear][end]

msg_182:
[color(yellow)]Young Man[color(white)]
[tab]The magazine, Fantasy World is pretty
[tab]popular right now, but I prefer Sumaru Walker. 
[tab]It’s not all fashion, ya know.
[wait][clear][end]

msg_183:
[color(yellow)]Young Man[color(white)]
[tab]Miracle eh... I’m more interested in the
[tab]content than prizes.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]I’ll stick with reading Men’s Life...
[wait][clear][end]

msg_184:
[color(yellow)]Young Man[color(white)]
[tab]They say Battle Master Monthly is starting
[tab]to give out real accessories. Reading that
[tab]mag really brings back some memories.
[wait][clear][end]

msg_185:
[color(yellow)]Young Man[color(white)]
[tab]They say Battle Master Monthly is starting
[tab]to give out real armor. Reading that
[tab]mag really brings back some memories.
[wait][clear][end]

msg_186:
[color(yellow)]Young Man[color(white)]
[tab]They say Battle Master Monthly is starting
[tab]to give out real weapons. Reading that
[tab]mag really brings back some memories.
[wait][clear][end]

msg_187:
[color(yellow)]Young Man[color(white)]
[tab]I hear you can get an Affinity
[tab]Reading at the Sumaru Genie. [wait][clear][color(yellow)]Young Man[color(white)]
[tab]It’s not like I care... I don’t have a
[tab]partner to go with. (Sigh) Maybe, I’ll go
[tab]to Yumezaki to try and pick up some girls.
[wait][clear][end]

msg_188:
[color(yellow)]Young Man[color(white)]
[tab]The Sumaru Genie’s readings used to be bad, 
[tab]but when they started Wang Long,
[tab]that all changed.[wait][clear][color(yellow)]Young Man[color(white)]
[tab]Chizuru’s Wang Long readings are amazing.
[wait][clear][end]

msg_189:
[color(yellow)]Young Man[color(white)]
[tab]A bar called Parabellum is selling weapons now. 
[tab]That place was pretty scary before, 
[tab]now it’s even scarier...
[wait][clear][end]

msg_190:
[color(yellow)]Young Man[color(white)]
[tab]I’m spending way too much time at
[tab]Mu Continent since they opened up the casino.
[wait][clear][end]

msg_191:
[color(yellow)]Mellow old man[color(white)]
[tab]Did you know the [color(orange)]flowers at Aoba Park can speak?[color(white)] 
[tab]I see the manager speaking to them, 
[tab]but I can’t hear what he’s saying.
[wait][clear][end]

msg_192:
[color(yellow)]Mellow old man[color(white)]
[tab]It’s hard when you start losing your hearing. 
[tab]I’d like to talk to the flowers about the old times...
[wait][clear][end]

msg_193:
[color(yellow)]Baofu[color(white)]
[tab]Sudou’s son should be at the sanitarium
[tab]at Mt. Katatsumuri.
[wait][clear][end]

msg_194:
[color(yellow)]Katsuya[color(white)]
[tab]I see...
[tab]Amano-kun, let’s check it out.
[wait][clear][end]

msg_195:
[color(yellow)]Baofu[color(white)]
[tab]Hold on! There’s a place called the
[tab]Velvet Room around here. 
[tab]It has something to do with demons...
[wait][clear][end]

msg_196:
[color(yellow)]Baofu[color(white)]
[tab]Considering the situation you’re in right now,
[tab]you’ll need all the help you can get.
[tab]Let’s go in and have a look...
[wait][clear][end]

msg_197:
[color(yellow)]Katsuya[color(white)]
[tab]What is that? What does that have to do
[tab]with anything?
[wait][clear][end]

msg_198:
[color(yellow)]Baofu[color(white)]
[tab]I don’t even feel like explaining...
[tab]Just follow me...
[wait][clear][end]

msg_199:
[color(yellow)]Ulala[color(white)]
[tab]It’s alright to relax in a park,
[tab]but I don’t think now is the time.
[wait][clear][end]

msg_200:
[color(green)]There’s no need to be here.[color(white)][wait][clear][end]

msg_201:
[color(yellow)]Baofu[color(white)]
[tab]Now’s not the time to be napping!
[tab]Let’s get going!
[wait][clear][end]

msg_202:
[color(yellow)]Katsuya[color(white)]
[tab]We might have to come here again,
[tab]but now isn’t the time.
[tab]Let’s get going.
[wait][clear][end]

msg_203:
[color(yellow)]Ulala[color(white)]
[tab]I know it’s been rough, but let’s finish
[tab]our mission before we relax.
[tab]Let’s go.
[wait][clear][end]

msg_204:
[color(yellow)]Katsuya[color(white)]
[tab]We can’t just go snooping around the
[tab]TV station? They won’t let us any further
[tab]than the reception area.
[wait][clear][end]

msg_205:
[color(yellow)]Baofu[color(white)]
[tab]What are we doing here? They won’t let us
[tab]in anyway. Besides, they won’t have
[tab]any more info than what they actually show.
[wait][clear][end]

msg_206:
[color(yellow)]Katsuya[color(white)]
[tab]I doubt that the kind of people we’re
[tab]looking for would hang out here...
[tab]Let’s look somewhere else.
[wait][clear][end]

msg_207:
[color(yellow)]Baofu[color(white)]
[tab]Hey! We don’t have any time to waste!
[tab]Let’s head over to GOLD.
[wait][clear][end]

msg_208:
[color(yellow)]Ulala[color(white)]
[tab]A TV station, huh? I am a little curious,
[tab]but now isn’t the time.
[wait][clear][color(yellow)]Ulala[color(white)]
[tab]Let’s check it out some other time.
[wait][clear][end]

msg_209:
[color(green)]There is no need to be here.[color(white)][wait][clear][end]

msg_210:
[color(yellow)]Baofu[color(white)]
[tab]Hey, we’re not finished yet...
[tab]Let’s head on over to the Velvet...
[sync][wait][clear][end]
