msg_0:
[color(yellow)]Katsuya[color(white)]
[tab]Sometimes I don't know...
[tab]what Justice really is...
[tab]Nanjo-kun, can I get your insight?
[wait][clear][end]

msg_1:
[color(yellow)]Nanjo[color(white)]
[tab]An old wise man once said, "All human
[tab]judgement is relative, with no such thing
[tab]as 'absolute' Justice..."
[wait][clear][end]

msg_2:
[color(yellow)]Katsuya[color(white)]
[tab]There is much cruelty done in the name of Justice... 
[tab]Can I be proud...?
[tab]Can I truly say I am doing what is just?
[wait][clear][end]

msg_3:
[color(yellow)]Nanjo[color(white)]
[tab]As long as Justice prevails the majority of the time... 
[tab]It takes a saint, or God, to provide completely 
[tab]flawless Justice...
[wait][clear][end]

msg_4:
[load_sound(sndeff_15)][sync][color(yellow)]Katsuya[color(white)]
[tab]Do people have the right to judge others?
[tab][play_sound(sndeff_15)][sync]Is there really such a
[tab]thing as pure justice? [sync]
[wait][clear][end]

msg_5:
[color(yellow)]Nanjo[color(white)]
[tab]Punishment exists to deter man's sins.
[tab]It is necessary for the sake of mankind.
[tab]Justice should speak through your actions...
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab][var(msg_var_0)]...
[tab]First I would like to know where you were
[tab]at the time of the incident..
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]Hmm... interesting... You just said something
[tab]that only the criminal could possibly know.
[tab]Did you realize that?
[wait][clear][end]

msg_8:
[load_sound(sndeff_10)][sync][color(yellow)]Katsuya[color(white)]
[tab]Isn't it true that you just said you didn't
[tab]know any "woman"? Odd... [play_sound(sndeff_10)][sync]I didn't say
[tab]one word about the victim being a woman...[sync]
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]No matter how many times.... 
[tab]Seeing a person's death just breaks my heart...
[wait][clear][end]

msg_10:
[color(yellow)]Katsuya[color(white)]
[tab]You'll always have a place in my heart...
[tab]Rest in peace...
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]I didn't think your death would affect me so deeply... 
[tab]I've lost an important person in my life.
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab]Nanjo-kun...
[tab]I can't allow a civilian to put himself at risk... 
[tab]Let me handle this.
[wait][clear][end]

msg_13:
[color(yellow)]Nanjo[color(white)]
[tab]Let's put our hands in Sergeant [suou]'s
[tab]ability to handle the situation...
[wait][clear][end]