msg_0:
[color(yellow)][tatsuya][color(white)]
[tab]There was a woman that once told me...
[tab]"Everybody has a right to have a dream"...
[tab]Is it the same for you too...?
[wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]Isn't it the same as a drink you've never
[tab]tried before? It could taste sweet or bitter,
[tab]but it's your choice to drink it or not.
[wait][clear][end]

msg_2:
[color(yellow)][tatsuya][color(white)]
[tab]Don't you miss your old job...?
[tab]Weren't you a special prosecutor...?
[wait][clear][end]

msg_3:
[color(yellow)]Baofu[color(white)]
[tab]I've already forgotten about my past...
[tab]What I need now is just
[tab]amber-colored water...
[wait][clear][end]

msg_4:
[color(yellow)][tatsuya][color(white)]
[tab]Don't you ever get tired of life...?
[wait][clear][end]

msg_5:
[load_sound(sndeff_1f)][sync][color(yellow)]Baofu[color(white)]
[tab]Kid, [play_sound(sndeff_1f)][sync]you talk like you know what's up...[sync]
[tab]Come back after you've lived a reckless
[tab]life... Dying's the easy way out...
[wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]You... How dare you hurt [tatsuya]...!
[tab]I won't let anyone else have the pleasure
[tab]of killing you... You're MINE...!
[wait][clear][end]

msg_7:
[color(yellow)]Baofu[color(white)]
[tab]What do you think you are doing to young
[tab][tatsuya]...? I won't forgive anyone who
[tab]hurts this kid!
[wait][clear][end]

msg_8:
[color(yellow)]Baofu[color(white)]
[tab]I'm pretty ruthless... Now you're going to
[tab]feel the pain [tatsuya] felt, but many times
[tab]stronger... Prepare to writhe in agony...
[wait][clear][end]