msg_0:
[color(yellow)]Nanjo[color(white)]
[tab]Hmph... Such a foolish-looking face.
[tab]The degree of knowledge conjectured by just
[tab]pausing and thinking..
[wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]Heh heh... How true.
[tab]I was just thinking the same thing.
[wait][clear][end]

msg_2:
[color(yellow)]Baofu[color(white)]
[tab]Hey hey, this is the human's world...
[tab]Did you make a wrong turn?
[wait][clear][end]

msg_3:
[color(yellow)]Nanjo[color(white)]
[tab]Or they wish to go home, but cannot.
[tab]Let us send them back then...
[tab]To the next world, of course.
[wait][clear][end]

msg_4:
[load_sound(sndeff_24)][sync][color(yellow)]Nanjo[color(white)]
[tab]To be able to come into the presence
[tab]of a high class demon such as you,
[tab][play_sound(sndeff_24)][sync]I am most honored...[sync]
[wait][clear][end]

msg_5:
[color(yellow)]Baofu[color(white)]
[tab]For boys like you there's a perfect tonic.
[tab]It's a brandy-mix drink known as the "Me".
[tab]In alcohol terms, it means "cynic"...
[wait][clear][end]

msg_6:
[color(yellow)]Nanjo[color(white)]
[tab]The economy's basis depends on individuals
[tab]striving for improvement. Recession occurs
[tab]when individuals don't! This must change!
[wait][clear][end]

msg_7:
[color(yellow)]Nanjo[color(white)]
[tab]To have equality with those countries who
[tab]lack military power, there must be liberal
[tab]Foreign Policy in place!
[wait][clear][end]

msg_8:
[load_sound(sndeff_21)][sync][color(yellow)]Nanjo[color(white)]
[tab]The education system is waning. Conservative
[tab]ways just cannot keep up with the times.
[tab][play_sound(sndeff_21)][sync]There needs to be a drastic reformation![sync]
[wait][clear][end]

msg_9:
[color(yellow)]Nanjo[color(white)]
[tab]You lived your life to its fullest...
[tab]It was truly admirable.
[wait][clear][end]

msg_10:
[color(yellow)]Nanjo[color(white)]
[tab]Here lies a most honorable person...
[tab]Let these words be on your tombstone...
[tab]Rest in peace...
[wait][clear][end]

msg_11:
[color(yellow)]Nanjo[color(white)]
[tab]Your name has been etched in Kei Nanjo's
[tab]heart forever. Surely, your name shall be
[tab]known to the next generation.
[wait][clear][end]

msg_12:
[color(yellow)]Nanjo[color(white)]
[tab]Mr. Baofu...
[tab]May I take care of this situation alone?
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]That's more than I wanted...
[tab]I hate to deal with such troublesome crap.
[tab]Go ahead and do whatever.
[wait][clear][end]