msg_0:
[tab][color(green)]Maya attempted to persuade the demon.[color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]That's right.
[tab]Your mother back home is worried...
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]That's right.
[tab]It's bad luck to keep worrying her.
[wait][clear][end]

msg_3:
[tab][color(green)]Maya passionately persuaded the demon.[color(white)]
[wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]Reform from your criminal ways...
[tab]You still have time.
[tab]You still have a chance to start over!
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]Don't act so stubbornly.
[tab]Be more "reasonable".
[wait][clear][end]

msg_6:
[tab][color(green)]Maya kindly persuaded the demon.[color(white)]
[wait][clear][end]

msg_7:
[load_sound(sndeff_11)][sync][color(yellow)]Katsuya[color(white)]
[tab]I understand that you are really a
[tab]kind-hearted demon...
[tab][play_sound(sndeff_11)][sync]Can't we end this senseless battle?[sync]
[wait][clear][end]

msg_8:
[color(yellow)]Ulala[color(white)]
[tab]That's right. There's no point in fighting
[tab]like this.
[wait][clear][end]

msg_9:
[color(yellow)]Katsuya[color(white)]
[tab]What's wrong Serizawa-kun?
[wait][clear][end]

msg_10:
[color(yellow)]Ulala[color(white)]
[tab]Sorry...
[tab]I'm not in the mood...
[wait][clear][end]

msg_11:
[color(yellow)]Katsuya[color(white)]
[tab]I have no choice...
[tab]Amano-kun and I will take care of it...
[wait][clear][end]