msg_0:
[color(yellow)]Ulala[color(white)]
[tab]THAT'S the swindler, Detective!
[tab]If you check, he will have a birthmark
[tab]shaped like a butterfly!
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]Is there any evidence to substantiate
[tab]these accusations...?
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]You greedy con artist!!
[tab]Quit playing innocent!
[wait][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab]How about it...
[tab]Do you recognize this woman?
[wait][clear][end]

msg_4:
[color(yellow)]Ulala[color(white)]
[tab]I don't care what's said. YOU'RE the one who
[tab]would've married me, taken my money,
[tab]and split! If you don't kill him, I WILL!
[wait][clear][end]

msg_5:
[load_sound(sndeff_14)][sync][color(yellow)]Katsuya[color(white)]
[tab]There are such things as extenuating
[tab]circumstances. Now's the time to confess...
[tab][play_sound(sndeff_14)][sync]Before she kills you...[sync]
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]...
[tab]Are you eating right?
[tab]Mother was worried about you.
[wait][clear][end]

msg_7:
[color(yellow)][tatsuya][color(white)]
[tab]Yeah...
[tab]I'm not a kid you know...
[tab]Leave me alone...
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]...
[tab]You should keep up your studies at school.
[tab]Your future is at stake...
[wait][clear][end]

msg_9:
[color(yellow)][tatsuya][color(white)]
[tab]It's my life...
[tab]Don't bother me...
[wait][clear][end]

msg_10:
[load_sound(sndeff_13)][sync][color(yellow)]Katsuya[color(white)]
[tab][tatsuya]...
[tab][play_sound(sndeff_13)][sync]Humans cannot live alone...[sync]
[tab]Don't you understand?
[wait][clear][end]

msg_11:
[color(yellow)][tatsuya][color(white)]
[tab]. . . . . . . . . . . . . . . . . . . . .
[wait][clear][end]

msg_12:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya]...
[tab]Stay back...
[wait][clear][end]

msg_13:
[color(yellow)][tatsuya][color(white)]
[tab]. . . . . . . . . . . . . . . . . .
[wait][clear][end]

msg_14:
[color(yellow)]Katsuya[color(white)]
[tab]Serizawa-kun...
[tab]Could you stand back?
[wait][clear][end]

msg_15:
[color(yellow)]Ulala[color(white)]
[tab]I'm good with that! Go for it!
[tab]Show 'em what you've got.
[wait][clear][end]