msg_0:
[color(yellow)]Baofu[color(white)]
[tab]How about a shot? There must be things
[tab]you would like to get off your chest...
[tab]The only ones here are demons.
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]I'm a cop... Yeah, I'm a cop...
[tab]But I really wanted to be something else!!
[wait][clear][end]

msg_2:
[color(yellow)]Ulala[color(white)]
[tab]I want to find a real stud and get married
[tab]soon! ...Hey demon, join us for a drink!
[tab]C'mon and just drink!!
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]Alcohol (hic) makes the world go 'round!!
[tab]Now drink already, drink! Have another!!
[wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]You mean money...
[tab]You lousy drunk...
[tab]Hey [suou], you're drinking too much...
[wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab](sniff) You there, demon, you look sad...
[tab]I see... It must be hard for you... You've
[tab]got my sympathy... Drink and forget...
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab](sniff)...(sniff)
[tab]Yes... I understand... I understand...
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]Drinking's fun.
[tab]We never get to see detectives like this...
[wait][clear][end]

msg_8:
[load_sound(sndeff_1a)][sync][color(yellow)]Baofu[color(white)]
[tab]The truth can be in a drink.
[tab]Go ahead and [play_sound(sndeff_1a)][sync]you have some, too.[sync]
[wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab]Hey Serizawa...
[tab]What kind of drink do you like?
[tab]Go ahead, I'm listening.
[wait][clear][end]

msg_10:
[color(yellow)]Ulala[color(white)]
[tab]Maybe a "Nighty Night".
[wait][clear][end]

msg_11:
[color(yellow)]Baofu[color(white)]
[tab]Heh, heh... That figures... Go ahead and
[tab]fall asleep. A dream is better than the
[tab]real world we're living in...
[wait][clear][end]

msg_12:
[color(yellow)]Ulala[color(white)]
[tab]What kind of liquor do YOU like?
[wait][clear][end]

msg_13:
[color(yellow)]Baofu[color(white)]
[tab]ME...?
[tab]I like Bourbon...
[wait][clear][end]

msg_14:
[color(yellow)]Ulala[color(white)]
[tab]A frontier spirit...?
[tab]How long you think humans can keep thinking
[tab]like that?
[wait][clear][end]

msg_15:
[color(yellow)]Baofu[color(white)]
[tab]I'll teach you a cocktail that fits you.
[tab]The world's sweetest "dream" cocktail...
[wait][clear][end]

msg_16:
[color(yellow)]Ulala[color(white)]
[tab]That sounds strange coming from you...
[tab]Hmm... So, what is it then?
[wait][clear][end]

msg_17:
[load_sound(sndeff_1b)][sync][color(yellow)]Baofu[color(white)]
[tab]One part "Hope", one part "Friendship", and
[tab]one part "Health", with a splash of "Sense".
[tab]It's called "Desire"... [play_sound(sndeff_1b)][sync]Rare indeed...[sync]
[wait][clear][end]

msg_18:
[color(yellow)]Baofu[color(white)]
[tab]Just listen. If you don't cooperate,
[tab]I'll start scattering these...
[wait][clear][end]

msg_19:
[color(yellow)]Baofu[color(white)]
[tab]What do you think of this tape...?
[tab]Good audio quality, huh?
[tab]Puts you in a compromising position, huh?
[wait][clear][end]

msg_20:
[color(yellow)]Baofu[color(white)]
[tab]Hold on a second...
[tab]Listen to this really carefully...
[wait][clear][end]

msg_21:
[color(yellow)]Baofu[color(white)]
[tab]You're a pretty cunning guy...
[tab]Hey, don't get the wrong idea!
[tab]This is business...
[wait][clear][end]

msg_22:
[color(yellow)]Baofu[color(white)]
[tab]Hold it, don't jump to conclusions...
[tab]Listen to this first...
[wait][clear][end]

msg_23:
[load_sound(sndeff_18)][sync][color(yellow)]Baofu[color(white)]
[tab]Y'know, [play_sound(sndeff_18)][sync]it's a waste
[tab]to keep this under wraps...[sync]
[tab]Is it okay if I start scattering these?
[wait][clear][end]

msg_24:
[color(yellow)]Baofu[color(white)]
[tab]The older, the wiser.
[tab]Watch, I'll show you the difference between
[tab]an experienced fighter and a beginner.
[wait][clear][end]

msg_25:
[color(yellow)]Katsuya[color(white)]
[tab]Talk is cheap! Why don't you back up those
[tab]words with some results.
[wait][clear][end]

msg_26:
[color(yellow)]Katsuya[color(white)]
[tab]I don't want to do this with Baofu.
[wait][clear][end]

msg_27:
[color(yellow)]Baofu[color(white)]
[tab]Hmmph, fine then!
[tab]Hey Serizawa, come on!
[wait][clear][end]

msg_28:
[load_sound(sndeff_33)][sync][sync]
[end]

msg_29:
[play_sound(sndeff_33)][sync][sync]
[end]