msg_0:
[color(yellow)]Baofu[color(white)]
[tab]Hey Serizawa...
[tab]What kind of drink do you like?
[tab]Go ahead, I'm listening.
[wait][clear][end]

msg_1:
[color(yellow)]Ulala[color(white)]
[tab]Maybe a "Nighty Night".
[wait][clear][end]

msg_2:
[color(yellow)]Baofu[color(white)]
[tab]Heh, heh... That figures... Go ahead and
[tab]fall asleep. A dream is better than the
[tab]real world we're living in...
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]What kind of liquor do YOU like?
[wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]Me..?
[tab]I like Bourbon.
[wait][clear][end]

msg_5:
[color(yellow)]Ulala[color(white)]
[tab]A frontier spirit...?
[tab]How long you think humans can keep thinking
[tab]like that?
[wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]I'll teach you a cocktail that fits you.
[tab]The world's sweetest "dream" cocktail...
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]That sounds strange coming from you...
[tab]Hmm... So, what is it then?
[wait][clear][end]

msg_8:
[load_sound(sndeff_1b)][sync][color(yellow)]Baofu[color(white)]
[tab]One part "Hope", one part "Friendship", and
[tab]one part "Health", with a splash of "Sense".
[tab]It's called "Desire"...[play_sound(sndeff_1b)][sync]Rare indeed...[sync]
[wait][clear][end]

msg_9:
[color(yellow)]Baofu[color(white)]
[tab][tatsuya], stand back for a second...
[tab]I need to have an adult conversation with
[tab]Serizawa.
[wait][clear][end]

msg_10:
[color(yellow)][tatsuya][color(white)]
[tab]I understand...
[wait][clear][end]