msg_0:
[color(yellow)]Baofu[color(white)]
[tab]Just listen. If you don't cooperate,
[tab]I'll start scattering these...
[wait][clear][end]

msg_1:
[color(yellow)]Baofu[color(white)]
[tab]What do you think of this tape...?
[tab]Good audio quality, huh?
[tab]Puts you in a compromising position, huh?
[wait][clear][end]

msg_2:
[color(yellow)]Baofu[color(white)]
[tab]Hold on a second...
[tab]Listen to this really carefully...
[wait][clear][end]

msg_3:
[color(yellow)]Baofu[color(white)]
[tab]You're a pretty cunning guy...
[tab]Hey, don't get the wrong idea!
[tab]This is business...
[wait][clear][end]

msg_4:
[color(yellow)]Baofu[color(white)]
[tab]Hold it, don't jump to conclusions...
[tab]Listen to this first...
[wait][clear][end]

msg_5:
[load_sound(sndeff_18)][sync][color(yellow)]Baofu[color(white)]
[tab]Y'know, [play_sound(sndeff_18)][sync]it's a waste
[tab]to keep this under wraps...[sync]
[tab]Is it okay if I start scattering these?
[wait][clear][end]

msg_6:
[color(yellow)]Baofu[color(white)]
[tab]Heh heh...
[tab]Isn't this too much for kids?
[tab]Leave this up to me.
[wait][clear][end]

msg_7:
[color(yellow)]Elly[color(white)]
[tab]Okay!
[tab]I'll leave it up to you, Baofu.
[wait][clear][end]

msg_8:
[load_sound(sndeff_33)][sync][sync]
[end]

msg_9:
[play_sound(sndeff_33)][sync][sync]
[end]