msg_0:
[color(yellow)]Ulala[color(white)]
[tab]You don't have any friends because you're
[tab]always causing people problems!
[tab]Do you understand?
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]Aggressive people like you tend to get
[tab]caught up in the wrong crowd!
[wait][clear][end]

msg_2:
[color(yellow)]Nanjo[color(white)]
[tab]Like attract like. If you
[tab]want better friends, better yourself.
[wait][clear][end]

msg_3:
[color(yellow)]Ulala[color(white)]
[tab]What's with your attitude?
[tab]You're bringing down all the people
[tab]around you.
[wait][clear][end]

msg_4:
[color(yellow)]Katsuya[color(white)]
[tab]People like you turn out to be criminals!
[tab]You must clean up your act!
[wait][clear][end]

msg_5:
[color(yellow)]Nanjo[color(white)]
[tab]A warped person such as you will
[tab]never be #1!
[tab]Come back when you mature!
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]Mind your manners! That's no way to act
[tab]when someone is talking to you!
[wait][clear][end]

msg_7:
[color(yellow)]Ulala[color(white)]
[tab]Are you even listening...?
[tab]We're not nagging you because we hate you.
[tab]Do you understand...?
[wait][clear][end]

msg_8:
[load_sound(sndeff_23)][sync][color(yellow)]Nanjo[color(white)]
[tab][play_sound(sndeff_23)][sync]The path of a friend seeks virtue...[sync]
[tab]We are saying this out of care!
[wait][clear][end]