msg_0:
[color(yellow)]Nanjo[color(white)]
[tab]Anti-phone tapping laws have been passed.
[tab]Sergeant [suou], is phone tapping "legal"
[tab]for police work?
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]It's hard to answer... Phone taps are only
[tab]used in special, important cases. We do not
[tab]make it a habit to invade people's privacy.
[wait][clear][end]

msg_2:
[color(yellow)]Baofu[color(white)]
[tab]Have you even read the law? I've never
[tab]seen so many loopholes in a law. Do they
[tab]really plan to protect people's privacy?
[wait][clear][end]

msg_3:
[color(yellow)]Nanjo[color(white)]
[tab]Mr. Baofu seems to be in disagreement.
[tab]Next, from the perspective of a demon,
[tab][var(msg_var_0)], I would like your opinion.
[wait][clear][end]

msg_4:
[color(yellow)]Nanjo[color(white)]
[tab]Anti-phone tapping laws have been passed.
[tab]I'd like to ask the Tap Buster,
[tab]Baofu, what exactly is privacy?
[wait][clear][end]

msg_5:
[color(yellow)]Baofu[color(white)]
[tab]It's a person's uncovered truth... Though
[tab]it is hidden, there are times where it must
[tab]be revealed. That's where I come in...
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]Are you implying the police do the same?
[tab]We only invade a person's privacy when an
[tab]investigation absolutely calls for it!
[wait][clear][end]

msg_7:
[color(yellow)]Nanjo[color(white)]
[tab]Sergeant [suou] seems to be disagreeing.
[tab]Next, from the perspective of a demon,
[tab][var(msg_var_0)], I would like your opinion.
[wait][clear][end]

msg_8:
[load_sound(sndeff_22)][sync][color(yellow)]Nanjo[color(white)]
[tab]We got Mr. [suou]'s and Mr. Baofu's thoughts.
[tab]Finally, from the perspective of a demon,
[tab][var(msg_var_0)], [play_sound(sndeff_22)][sync]I would like your opinion.[sync]
[wait][clear][end]

msg_9:
[load_sound(sndeff_37)][sync][sync]
[end]

msg_10:
[play_sound(sndeff_37)][sync]
[end]