msg_0:
[color(yellow)][tatsuya][color(white)]
[tab]I won't let you lay a finger on this
[tab]woman...
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]Stay back [tatsuya]...
[tab]If something happens to you, I wouldn't be
[tab]able to show my face to Father and Mother.
[wait][clear][end]

msg_2:
[color(yellow)][tatsuya][color(white)]
[tab]I came here to protect you...
[wait][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya], stand back!!
[tab]I'm the cop, let me handle this.
[wait][clear][end]

msg_4:
[load_sound(sndeff_2b)][sync][color(yellow)][tatsuya][color(white)]
[tab]You won't back down...?
[tab][play_sound(sndeff_2b)][sync]Then... prepare to die.[sync]
[wait][clear][end]

msg_5:
[color(yellow)]Katsuya[color(white)]
[tab][tatsuya], give the macho routine a rest...
[tab]I'm not just going to stand by and watch!
[wait][clear][end]