msg_0:
[color(yellow)][tatsuya][color(white)]
[tab]Don't look away...
[wait][clear][end]

msg_1:
[color(yellow)][tatsuya][color(white)]
[tab]. . . . . . . . . . . .
[wait][clear][end]

msg_2:
[load_sound(sndeff_2a)][sync][color(yellow)][tatsuya][color(white)]
[tab][play_sound(sndeff_2a)][sync]There's no need for words...[sync]
[wait][clear][end]

msg_3:
[color(yellow)][tatsuya][color(white)]
[tab]Both of you, stand back...
[wait][clear][end]

msg_4:
[color(yellow)]Nanjo[color(white)]
[tab]I understand, [tatsuya].
[tab]But don't worry Ms. Amano too much.
[wait][clear][end]