msg_0:
[tab][color(green)]Maya attempted to persuade the demon. [color(white)]
[wait][clear][end]

msg_1:
[color(yellow)]Katsuya[color(white)]
[tab]That's right.
[tab]Your mother back home is worried...
[wait][clear][end]

msg_2:
[tab][color(green)]Maya passionately persuaded the demon. [color(white)]
[wait][clear][end]

msg_3:
[color(yellow)]Katsuya[color(white)]
[tab]Reform from your criminal ways...
[tab]You still have time.
[tab]You still have a chance to start over!
[wait][clear][end]

msg_4:
[tab][color(green)]Maya kindly persuaded the demon. [color(white)]
[wait][clear][end]

msg_5:
[load_sound(sndeff_11)][sync][color(yellow)]Katsuya[color(white)]
[tab]I understand that you are really a
[tab]kind-hearted demon...
[tab][play_sound(sndeff_11)][sync]Can't we end this senseless battle?[sync]
[wait][clear][end]

msg_6:
[color(yellow)]Katsuya[color(white)]
[tab]No matter how many times.... 
[tab]Seeing a person's death just breaks my heart...
[wait][clear][end]

msg_7:
[color(yellow)]Katsuya[color(white)]
[tab]You'll always have a place in my heart...
[tab]Rest in peace...
[wait][clear][end]

msg_8:
[color(yellow)]Katsuya[color(white)]
[tab]I didn't think your death would affect me so deeply... 
[tab]I've lost an important person in my life.
[wait][clear][end]